### ISSUE TITLE
feature request: Pass HTML tag attributes as single object

### ISSUE THREAD

**Issue by arunkumar413** [facebook/react#28143] opened 2024-01-28 16:17 UTC
## The current behavior
Currently we're passing multiple attributes separately to ensure jsx compatibility with HTML like below 

```
<input type='text' name='firstName'/>

```

## The expected behavior

Could you please allow react to  pass the attributes of  an HTML tag in a single object like below. This shouldn't break the current behavior but as an additional feature. 
```
<input attributes={type:'text', name:'firstName'} />
```

**Comment by ritikbanger** [comment] 2024-01-28 17:55
Could you please list the benefits out for doing so? The input tag is a native HTML tag. If you want, you can still create a parent component that may take a single object prop and then you pass them to the underlying input tag.

**Comment by prashanth-cn** [comment] 2024-01-28 21:20
we can spread the props

**Comment by Hudsxn** [comment] 2024-01-29 04:23
Yeah, this is simple enough to do with a spread operator. You can prepare your props dynamically before and use the ... operator:

```javascript
const inputAttributes = {
    type: 'text',
    name: 'firstName'
};
return <input {...inputAttributes}/>;
```

**Comment by pwbriggs** [comment] 2024-01-29 05:50
Elaborating on @prashanth-cn's comment and the [React docs], this is already possible using JavaScript's [spread syntax]. Instead of the normal `<Element key={value} />` syntax, you can spread an object inside a pair of curly braces.

So this code:

```jsx
function App() {
  return <Greeter salutation="hello" name="world" />
}
```

is equivalent to

```jsx
function App() {
  const config = {salutation: "hello", name: "world"}
  return <Greeter {...config} />
}
```

[React docs]: https://react.dev/learn/passing-props-to-a-component#forwarding-props-with-the-jsx-spread-syntax
[Spread syntax]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by pwbriggs** [comment] 2024-01-29 05:51
Sorry, I didn't see @Hudsxn's reply.

**Comment by arunkumar413** [comment] 2024-01-29 16:27
Thanks all for the answers. The spread operator will suffice my requirement.

**Comment by Hudsxn** [comment] 2024-01-29 23:43
No problem :) 

A good understanding of JavaScript takes time. For extra information, you can use the spread operator on both object and arrays, as such:
```javascript
const mainObject = {
    hello: true
};
const secondObject = {
    ...mainObject,
    world: false
};
console.log(secondObject) // outputs { hello: true, world: false }
```

And with arrays
```javascript
const arrayOne = [1,2,3];
const arrayTwo = [...arrayOne, 4,5,6];

console.log(arrayTwo); // outputs [1,2,3,4,5,6]
```

**Comment by ritikbanger** [comment] 2024-01-30 05:16
Please close the issue, if the problem is solved. @arunkumar413

**Closed** 2024-01-30 05:26 UTC
Labels: Status: Unconfirmed
