### ISSUE TITLE
Bug: React App showing blank screen on IE 11

### ISSUE THREAD

**Issue by uttarwarsandesh33** [facebook/react#18114] opened 2020-02-24 04:31 UTC
## Steps To Reproduce

1. do npm start
showing error in console -

**[HMR] Waiting for update signal from WDS...
SCRIPT5022: SyntaxError
0.chunk.js (327239,38)
SCRIPT5022: The error you provided does not contain a stack trace.
0.chunk.js (355760,64)**

Link to code example:
 **added line in index.js**
      import "react-app-polyfill/ie11";
      import "react-app-polyfill/stable";
  **in package.json**
     "development": [
      "ie 11",
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "last 1 ie version"
    ]

## The current behavior
showing blank screen and error in console is 
    **[HMR] Waiting for update signal from WDS...
     SCRIPT5022: SyntaxError
      0.chunk.js (327239,38)
      SCRIPT5022: The error you provided does not contain a stack trace.
      0.chunk.js (355760,64)**

## The expected behavior
should show landing screen

**Comment by bvaughn** [comment] 2020-02-24 16:55
> 1. do npm start

This isn't really a repro case without a pointer to a project. :smile:

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-02-26 19:45
Closing due to lack of repro inf.

**Closed by bvaughn** 2020-02-26 19:45 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
