### ISSUE TITLE
input Unable to enter a decimal

### ISSUE THREAD

**Issue by qq541167695** [facebook/react#7545] opened 2016-08-23 02:42 UTC
`
        <input
            type="number"
            step=".01"
            min={1}
            max={9999}
            defaultValue={ 1.00 } />
`

> the input Unable to enter a decimal

**Comment by bhargav175** [comment] 2016-08-23 09:57
Can you please elaborate the issue ? I am able to enter decimals in the input. 

https://codepen.io/bhargav175/pen/oLRdJp

**Comment by thysultan** [comment] 2016-08-23 14:06
@bhargav175 on the codepen, when you type 1.0 it adds the '1' then the cursor shifts to the beginning of the input such that i end up typing '0.1'.

**Comment by keyanzhang** [comment] 2016-08-23 17:37
Thanks for reporting! It should be a duplicate of #7253.

**Comment by zpao** [comment] 2016-08-23 17:39
Yup, looks like the same core issue and there's a bunch of discussion over there. Let's close this.

**Closed by zpao** 2016-08-23 17:39 UTC
