### ISSUE TITLE
Error: "Commit tree does not contain fiber 641. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by mhkasif** [facebook/react#18505] opened 2020-04-06 14:31 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by bvaughn** [comment] 2020-04-09 22:25
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-04-17 00:02
Closing due to lack of info.

**Closed by bvaughn** 2020-04-17 00:02 UTC
Labels: Resolution: Needs More Information
