### ISSUE TITLE
document is not defined on server

### ISSUE THREAD

**Issue by bishtawi** [facebook/react#3620] opened 2015-04-08 09:57 UTC
I saw there was a bug for this a year ago (facebook/react#1866) and it was fixed. I am encountering it now on 0.13.1. 

I am running react on the server to generate html. On one of my parent components I have a variable whose value cannot be determined until it reaches some child component. So I need to implement some way for a child component to pass back data to its parent. I read https://facebook.github.io/react/tips/communicate-between-components.html and I implemented it:

Parent component passes callback function as a prop to child component.
Child component calls callback in componentWillMount function (also tested calling callback in getInitialState).
Callback calls setState to update state variable in parent.

This does not work serverside as an exception is thrown about document not being defined.

**Comment by tmbtech** [comment] 2015-04-08 16:57
There's no DOM when SSR, you will have to add some kind of abstraction to test if the DOM is present. 

https://gist.github.com/tmbtech/92522d315d50ea5281d1

**Comment by bishtawi** [comment] 2015-04-08 17:09
So I cannot pass data up to a parent component serverside? That state variable in the parent component needs to be set in order for the page to be generated properly. Hence the reason why I need it to happen serverside and not just on the client.

**Comment by jsfb** [comment] 2015-04-08 17:19
Parents and children can still communicate in the normal way (callbacks, but you need to do it in the right places, because some lifecycle methods (including `componentDidMount`) won't be called on the server side), but the fact that you're relying on a child for information seems to imply you need to know something about the child's layout/size/etc.  The blocking issue for you is going to be that... if you're relying on the browser to figure out the component's layout/size, that information won't be available to you on the server side (because you don't have the browser).

**Comment by bishtawi** [comment] 2015-04-08 18:00
Well, my use case is creating breadcrumbs. I am using react-router and in my layout component I am rendering the breadcrumbs. But I dont know what breadcrumbs are until the page components (child component of the layout component) is created.

**Comment by bishtawi** [comment] 2015-04-08 18:11
I already deleted most of the code and tried to implement a workaround, but my code originally looked something like this:

react-router:
````
<Route name="app" path="/" handler={ require('./components/layout') }>
  <DefaultRoute handler={require('./components/home')}/>
  <Route name='About Us' path="/about-us" handler={require('./components/about')}/>
  /* more routes */
</Route>
````

layout:
````
getInitialState: function() {
  return {breadcrumbs: []};
},
breadCrumbCallback: function(bc) {
  this.setState({breadcrumbs: bc});
},
render: function() {
    if (this.state.breadcrumbs.length) {
        var breadcrumbs = /* create breadcrumbs html from breadcrumbs state variable*/
    }
    return (
      <div>
        {breadcrumbs}
        <RouteHandler breadCrumbCallback={this.breadCrumbCallback}/>
      </div>
    )
}
````

Then in each of my page components (home, about, etc), I call breadCrumbCallback:
````
componentWillMount: function() {
  this.props.breadCrumbCallback(/*Page specific breadcrumbs array*/)
}
````


Is there something I am doing wrong?

**Comment by tmbtech** [comment] 2015-04-08 18:16
I think you can use `this.context.router` to figure out the breadcrumbs in the parent container. 

https://github.com/rackt/react-router/blob/master/docs/api/RouterContext.md
https://github.com/rackt/react-router/issues/404 -- react-router breadcrumbs

**Comment by bishtawi** [comment] 2015-04-08 18:21
Yeah, thats actually the workaround I am using right now. But, correct me if I am wrong, this is still a bug in react, no?

**Comment by zpao** [comment] 2015-04-09 21:40
You only have a single render pass on the server so abstractly this pattern doesn't really make sense on the server. You're parent has already rendered so effectively you're trying to kick off a 2nd render when you call a function that sets state in the parent. It does seem like we shouldn't throw in such a bad way here though. I bet we can blame @sebmarkbage for the changes he made to the state queue...

**Comment by jsfb** [comment] 2015-04-09 21:46
@bishtawi I'm not entirely convinced it's a bug in React.  For SSR, I can think of a bunch of reasons to want to enforce single-pass rendering (if nothing else, it keeps open the possibility of streaming the output to the client).  I can't think of any (good) reason to have a child pass that kind of information back up to the parent (your use case sounds like an antipattern to me).  So maybe the bug is that the error message isn't the best, but the behavior is probably correct.

**Comment by sebmarkbage** [comment] 2015-04-09 21:50
We've determined that callbacks up to parents from all life cycle methods is typically an anti-pattern. It actually opens up a lot of strange timing issues. (For example ref resolution order changed in 0.13 so refs of a parent is not resolved when a child's componentDidMount is called.)

@jsfb, we can't proclaim that it's an anti-pattern without providing an alternative solution. We should also fix the error message if we don't want to support this.

**Comment by jsfb** [comment] 2015-04-09 21:50
@sebmarkbage I thought @tmbtech did provide an alternate solution, no?

**Comment by zpao** [comment] 2015-04-09 21:52
The alternative solution presented makes use of something specific to react-router.

**Comment by jsfb** [comment] 2015-04-09 21:55
Well, the general solution is to have the parent do whatever calculation the child is doing (possibly by calling into a shared library).  Outside of layout, the parent should have all the information that the child has (since the child presumably got it from the parent).

**Comment by sebmarkbage** [comment] 2015-04-09 22:03
One neat way to do this is to have a static method on the child so you can call. `ChildComponent.getBreadcrumb(this.props)` before rendering it. The `ChildComponent` can forward the call deeper if it needs to.

Neither of these solutions solve the case when the parent and child are vastly detached from each other and passing info through the intermediate abstractions is prohibitive. It is the exact same problem as layout. That's what prerender was suppose to solve. https://github.com/reactjs/react-future/blob/master/04%20-%20Layout/02%20-%20Layout%20Components.js#L15

**Comment by wied03** [comment] 2015-06-09 17:15
I'm having the same issue with 0.13.3 and I'm not passing callbacks around. I'm just trying to setState using an externally fetched value from within componentWillMount and I'm encountering the issue

**Comment by jimfb** [comment] 2015-06-09 17:26
@wied03 Is there a reason you are using `componentWillMount` instead of the `constructor` or `getInitialState`?  Also, can you provide a jsfiddle that demonstrates the issue?

**Comment by sebmarkbage** [comment] 2015-06-09 17:28
I noticed similar issues in workers. We should fix these for 0.14.

**Comment by wied03** [comment] 2015-06-09 17:53
@jimfb I thought it was failing in a different place than it was. As it turns out, I'm trying to do the same thing the original poster is. Sorry for the noise. As to why not initial_state or a constructor, it's a simpler programming model this way. I have cascading dropdowns and can have the same code, which makes piecemeal calls to setState, deal with an initial preselections and also react to valueLink requestChange events. Using initial state requires that I combine it all into piece of code and pass the "candidate" state around.

**Comment by helkgate** [comment] 2015-06-09 18:55
Brother im an idiot with this stuff. I'm not even sure what you sent me in
the first place

**Comment by spicyj** [comment] 2015-06-09 23:58
@sebmarkbage Can you be more specific?

**Comment by sebmarkbage** [comment] 2015-06-10 02:05
@spicyj I found it! https://github.com/facebook/react/blob/52752446760dee0bc7232b4146f5a309ac57f065/src/shared/vendor/core/dom/getActiveElement.js#L23

**Comment by sebmarkbage** [comment] 2015-06-10 02:08
The stack is:

getActiveElement
ReactInputSelection.getSelectionInformation
Mixin.initializeAll
Mixin.perform
batchedMountComponentIntoNode

This should not happen on the server though

**Comment by ericclemmons** [comment] 2015-06-11 20:24
Someone pointed me to this thread, so I'd like to chime in on a use-case...

I've been doing a rewrite of [react-resolver][1] to avoid several context issues in v0.13, and **it is heavily dependent on `setState` on the server**:

1. Desired root element is rendered normally via `React.renderWhatever` to kick off the lifecycle.
2. Containers wrap lazy-loaded components & fetch their data via Promises on `componentWillMount`.
3. Data is returned, and `setState` is called within the Container after Promises resolve.
4. The wrapped Component renders, kicking off steps 2-4 all over again.
5. Once the tree completes, the `Resolver` aggregates all lazy-loaded data.
6. A final `React.renderWhatever` is called, but this time the data is already available & the full tree renders synchronously.

The alternative would be to constantly re-render the full tree from the root until no more promises appear, but that seems poor architecturally, as then we have 2 different algorithms for both server & client rather than a "universal" (can't say "isomorphic" without @mjackson knowing about it! :D) one, since `setState` is neutered on the server.

- Eric @ 30,000 ft :)

[1]: https://github.com/ericclemmons/react-resolver

**Comment by andreimc** [comment] 2015-07-20 06:56
Any news on this issue how can I work around it ?

**Comment by ericclemmons** [comment] 2015-07-20 14:40
@andreimc In both using React v0.13 & React v0.14 (beta) on the server, I've found it's wise to **move any `setState` logic within `componentWillMount` to `constructor`**.

Otherwise I've seen both:

- _document is not defined_
- _Cannot read property '_currentElement' of null_

**Comment by andreimc** [comment] 2015-07-26 07:02
thanks @ericclemmons

**Comment by mik01aj** [comment] 2015-08-21 13:53
From what I understand, [the commit that fixed this](https://github.com/wehriam/react-select/commit/4fe950a9e93b73f87a02cd3a4614d46665e1d43e) was merged to master, and will be released in `v0.14`, and I can already use it by installing version `0.14.0-beta3` from npm. I guess this ticket could be closed then.

**Comment by ericclemmons** [comment] 2015-08-21 18:21
I am confuse.  The commit you linked isn't for React proper.  It's kinda bad for user libs to have to hack around `setState` in `componentWillMount`.  IMO, either there should be deprecation warnings for users to move their logic from `componentWillMount` to `constructor`, or adjust `setState` to work as expected.

**Comment by spicyj** [comment] 2015-08-21 18:26
@ericclemmons Yes, this is still a React issue.

**Comment by mik01aj** [comment] 2015-08-21 18:28
Ah, you're right, I didn't notice that. Now I'm confused too. I upgraded React to `0.14.0-beta3` because I saw [this comment](https://github.com/reactjs/react-rails/issues/146#issuecomment-111736033) and this seemed to fix the problem for me.

**Comment by spicyj** [comment] 2015-08-21 18:35
Hm, it's possible 40b7c19a890b04e5d7bd1273e4f90bb78769ae5b fixed it.

**Comment by ericclemmons** [comment] 2015-08-21 18:54
Good find!  Looks like that'll make it into the next release...

**Comment by thinkkevin** [comment] 2015-09-29 06:15
I installed the 0.14-rc1, but still got this issue.

~~~~
::ffff:127.0.0.1 - - [29/Sep/2015:05:58:09 +0000] "GET /v1/article/236 HTTP/1.1" 200 - "-" "-"
/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/getActiveElement.js:23
    return document.body;
           ^

ReferenceError: document is not defined
    at getActiveElement (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/getActiveElement.js:23:12)
    at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactInputSelection.js:40:23)
    at ReactReconcileTransaction.Mixin.initializeAll (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/Transaction.js:168:30)
    at ReactReconcileTransaction.Mixin.perform (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/Transaction.js:133:12)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactUpdates.js:175:19)
    at Object.wrapper [as flushBatchedUpdates] (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.enqueueUpdate (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactUpdates.js:215:22)
    at enqueueUpdate (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactUpdateQueue.js:30:18)
    at Object.ReactUpdateQueue.enqueueSetState (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactUpdateQueue.js:208:5)
    at Article.ReactComponent.setState (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/react/lib/ReactComponent.js:69:20)
    at Article.<anonymous> (/Users/qinguo/allcodes/gitebay/NewX/go/lib/shared/mixin/request.js:35:14)
    at Request.self.callback (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/request/request.js:1073:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/qinguo/allcodes/gitebay/NewX/go/node_modules/request/request.js:1019:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
~~~~

**Comment by Rleahy22** [comment] 2015-10-13 15:49
Using 0.14 still seeing this issue. I'm using document.querySelectorAll because I need to pass dom nodes as part of props, but I get: 

```ReferenceError: Error with partial rendering: Error with partial rendering: document is not defined```

**Comment by bORm** [comment] 2015-12-16 09:06
How fix it?

**Comment by ericclemmons** [comment] 2015-12-16 17:01
Personally, I haven't seen this error in _ages_.  So if anyone on this thread is still having an issue, please provide an example repo so we can actually _test_ it.  Otherwise, we're guessing as to what 99% of what your app is doing.

**Comment by CreativeKoen** [comment] 2016-03-16 20:56
@ericclemmons I'm still very new to react but I'm getting this error. This is the repo https://github.com/CreativeKoen/creativekoen.nl run `npm install && gulp build && node server.js`
the last cmd will crash and throw the error.

**Comment by dreambo8563** [comment] 2016-09-01 07:26
@ericclemmons , I got one..
 I am using react start kit. I import react echart as an component and ensure.require the component. then .... got this error on server side.
my repo https://github.com/dreambo8563/RSK/blob/master/src/routes/content/index.js

will see the error:
```
ReferenceError: document is not defined
    at detect (D:\Projects\RSK-master\node_modules\.3.1.3@zrender\lib\core\env.js:104:31)
    at Object.<anonymous> (D:\Projects\RSK-master\node_modules\.3.1.3@zrender\lib\core\env.js:21:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Projects\RSK-master\node_modules\.3.2.3@echarts\lib\echarts.js:30:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)

```

**Comment by aweary** [comment] 2017-09-20 00:08
It's been over a year and there have been no reports of this issue occurring anymore. There is also no clear example that we could use to reproduce this issue in the latest versions of React. I'm going to close this out under the assumption that https://github.com/facebook/react/commit/40b7c19a890b04e5d7bd1273e4f90bb78769ae5b or some other commit from that period resolved this issue.

If you're still seeing this issue, please provide a small repro that we can verify. Thanks!

**Closed by aweary** 2017-09-20 00:08 UTC

**Comment by kushalmahajan** [comment] 2018-02-09 06:29
I am facing this issue in React 16. Seemingly cannot find  any solution when rendered from server. Without server render it used to work fine. 

Sharing my two snippets - server/index.js and src/index.js (client )

`import express from 'express';
import serverRenderer from './middleware/renderer';

const PORT = 3001;
const path = require('path');
const app = express();
const router = express.Router();
import Loadable from 'react-loadable';

// root (/) should always serve our server rendered page
router.use('^/$', serverRenderer);
app.use('/static', express.static(path.join(__dirname, 'assets')));
router.use(express.static(
    path.resolve(__dirname, '..', 'build'),
    { maxAge: '30d' },
));
router.use('*', serverRenderer);
app.use(router);
Loadable.preloadAll().then(() => {
    app.listen(PORT, (error) => {
        if (error) {
            return console.log('something bad happened', error);
        }

        console.log("listening on " + PORT + "...");
    });
});
`

This above works fine if I use containers/app.js (with no document inside) instead of src/index.js.

src/index.js

`import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
// import { ConnectedRouter } from 'react-router-redux';
// import { StaticRouter } from 'react-router'

import './index.css';
import store, { history } from './store';
import App from './containers/app';

const target = document.querySelector('#root');

ReactDOM.hydrate(
      <App />,
      target
);
`

Using the above file won't work from server and throws the same error

**Comment by gaearon** [comment] 2018-02-09 11:58
You’re writing in a very old issue that has been fixed. Whatever problem you’re having with React 16 is unrelated. Please file a new issue with a minimal reproducing example for your problem. Thanks!
