### ISSUE TITLE
Deprecate `isMounted`

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5465] opened 2015-11-13 23:18 UTC
`isMounted` is already unavailable on ES6 classes, and we already have a warning saying we "might" remove them, but we don't actually have a github issue to deprecate them.  As per our discussions today, we are basically agreed that we're going to start moving away from `isMounted` and deprecate it.  We still need to figure out some good stories around promises (and related use cases).

This issue is to track progress toward that goal.

For background, please read:
- https://github.com/facebook/react/issues/2787#issuecomment-68738793
- https://github.com/facebook/react/issues/3417
- https://github.com/facebook/react/pull/5420#issuecomment-155577641

**Comment by yaycmyk** [comment] 2015-11-16 16:14
I don't agree with this. ES6 promises in particular cannot be reliably cancelled on `componentWillUnmount`, so removing the only way to check if the component is mounted before setState or another action is opening the way for a lot of hard to trace async bugs.

**Comment by jimfb** [comment] 2015-11-16 18:27
@yaycmyk Thus the line:
 > We still need to figure out some good stories around promises (and related use cases).

Please read the background issues I listed, in particular: https://github.com/facebook/react/issues/2787#issuecomment-68738793

**Comment by yaycmyk** [comment] 2015-11-16 19:12
I did read the comments. I just find the issues intractable.

**Comment by nvartolomei** [comment] 2015-11-16 19:15
Why promises cant be reliable cancelled? Any sources/proofs/examples?

On Monday, November 16, 2015, Evan Jacobs <notifications@github.com> wrote:

> I don't agree with this. ES6 promises in particular cannot be reliably
> cancelled on componentWillUnmount, so removing the only way to check if
> the component is mounted before setState or another action is opening the
> way for a lot of hard to trace async bugs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react/issues/5465#issuecomment-157084353>.
>


-- 
Nicolae Vartolomei, http://nvartolomei.com/

**Comment by yaycmyk** [comment] 2015-11-16 19:20
@nvartolomei Look at the ES6 promise spec.

**Comment by zpao** [comment] 2015-11-16 19:27
This is a longer term goal, not something that is happening immediately. But we want to track the planning and discussions in a single place and not across comments in every issue when this comes up. We are aware of the problem of Promises currently being uncancellable which is a major reason we haven't already done this.

**Comment by jimfb** [comment] 2015-11-16 19:28
@yaycmyk To over-simplify a very complex issue... the comments are saying... using `isMounted` to avoid `setState` for unmounted components doesn't actually solve the problem that the `setState` warning was trying to indicate - in fact, it just hides the problem.  Also, calling `setState` as the result of a promise is a bit of an anti-pattern anyway, since it can cause race conditions which won't necessarily show up in testing.  Thus we want to get rid of it, and figure out a "best practice" recommendation for using promises with React.

**Comment by yaycmyk** [comment] 2015-11-16 19:32
> calling setState as the result of a promise is a bit of an anti-pattern anyway, since it can cause race conditions which won't necessarily show up in testing

We can agree to disagree on that one. There are times when content is being fetched asynchronously and you don't want to have to go through a full-scale rerender to pop that content in once it is resolved. I use it specifically in an infinite table view implementation where a full virtual rerender would be unnecessary.

**Comment by jimbolla** [comment] 2015-11-16 19:42
You might not be able to cancel a promise, but you can make it dereference the component on unmount, like so:

```javascript
const SomeComponent = React.createClass({
    componentDidMount() {
        this.protect = protectFromUnmount();

        ajax(/* */).then(
            this.protect( // <-- barrier between the promise and the component
                response => {this.setState({thing: response.thing});}
            )
        );
    },
    componentWillUnmount() {
        this.protect.unmount();
    },
});
```

The important distinction is when `this.protect.unmount()` is called in `componentWillUnmount`, all callbacks get dereferenced, meaning the component gets dereferenced, and then when the promise completes, it just calls a no-op. This should prevent any memory leaks related to promises references unmounted components. [source for protectFromUnmount](https://gist.github.com/jimbolla/f548d20da071b7c67807)

**Comment by istarkov** [comment] 2015-11-18 22:41
This simple method can be used to add cancel to any promise

``` javascript
const makeCancelable = (promise) => {
  let hasCanceled_ = false;

  return {
    promise: new Promise(
      (resolve, reject) => promise
        .then(r => hasCanceled_
          ? reject({isCanceled: true})
          : resolve(r)
        )
    ),
    cancel() {
      hasCanceled_ = true;
    },
  };
};
```

HOW TO USE

```javascript
const somePromise = new Promise(r => setTimeout(r, 1000));

const cancelable = makeCancelable(somePromise);

cancelable
  .promise
  .then(() => console.log('resolved'))
  .catch(({isCanceled, ...error}) => console.log('isCanceled', isCanceled));

// Cancel promise
cancelable.cancel();
```

**Comment by yaycmyk** [comment] 2015-11-18 22:42
Listing ways to sup-up ES6 promises to make them cancellable is besides the point. The intent should be to provide a solution that works WITH the spec rather than trying to work AROUND the spec.

**Comment by ir-fuel** [comment] 2015-11-20 10:39
I agree. Instead of simply checking if the component is still mounted when we receive the promise result we have to resort to all kinds of magic so we can "unbind" our promise from the component it's supposed to set its result in, clearly fighting against the way promises are designed.
To me it feels like overengineering a solution where a simple test is the easiest way to take care of this.

**Comment by laskos** [comment] 2015-11-20 11:19
We can keep simple checking just by:

```javascript
React.createClass(function() {
  componentDidMount: function () {
    this._isMounted = true;

    
    ajax(/* */).then((response) => {
      this._isMounted && this.handleResponse(response);
    });
  }

  handleResponse: function(response) {
    /* */
  }

  componentWillUnmount: function () {
    this._isMounted = false;
  }
});
```

**Comment by ir-fuel** [comment] 2015-11-20 11:29
This is of course my opinion, but it seems to me that async data loading with a promise inside a react component is such a common scenario that it should be covered by react, instead of having to write our own boilerplate code.

**Comment by laskos** [comment] 2015-11-20 12:04
The problem is, that to fallow the true mount state we must add listener when react will finish DOM mount in each component (the same, which attach componentDidMount, if defined), but it will affect on perf, because we don't need to fallow it everywhere. Component dont listen DOM mount ready by default since componentDidMount is undefined.

**Comment by BurntCaramel** [comment] 2015-12-07 11:01
What if `setState` could be passed a chained promise which resolves to the desired state changes? If the component unmounts, then if there are any pending promises their eventual result is ignored.

**Comment by koistya** [comment] 2015-12-17 10:05
@istarkov nice pattern, like it! Here is slightly altered API for it:

```js
// create a new promise
const { response, cancel } = await cancelable(fetch('/api/data'));

// cancel it
cancel();
```

**Comment by dtertman** [comment] 2016-01-19 21:31
Since I'm new to React and reading docs, just to throw this out there : the [Load Initial Data via Ajax](https://facebook.github.io/react/tips/initial-ajax.html) tip uses ```.isMounted()```, so the website disagrees with the website.  It would be great to see a complete Tip about how to cancel the initial load in ```componentWillUnmount```, maybe using @istarkov's pattern above.

**Comment by jimfb** [comment] 2016-01-19 21:40
@dtertman Fixed in https://github.com/facebook/react/pull/5870, will be online when the docs get cherry-picked over.

**Comment by dtertman** [comment] 2016-01-19 22:19
@jimfb thanks, not sure how I missed that in search.

**Comment by vpontis** [comment] 2016-03-01 00:24
@istarkov not sure if this was intentional but your `makeCancelable` does not handle if the original promise fails. If the original promise fails no handler is ever called.

This does not seem ideal because you may still want to handle an error on the original promise. 

Here is my proposal for a `makeCancelable` that handles a rejection in the original promise: 

```jsx
const makeCancelable = (promise) => {
  let hasCanceled_ = false;

  const wrappedPromise = new Promise((resolve, reject) => {
    promise.then((val) =>
      hasCanceled_ ? reject({isCanceled: true}) : resolve(val)
    );
    promise.catch((error) =>
      hasCanceled_ ? reject({isCanceled: true}) : reject(error)
    );
  });

  return {
    promise: wrappedPromise,
    cancel() {
      hasCanceled_ = true;
    },
  };
};

```

**Comment by istarkov** [comment] 2016-03-01 00:57
@vpontis :+1:

**Comment by vpontis** [comment] 2016-03-01 01:06
@istarkov your original post is referenced here: https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

Want to update your post or should I message the author of the post?

**Comment by jimfb** [comment] 2016-03-01 01:49
@vpontis Thanks, I'll fix!

**Comment by leviathan88** [comment] 2016-08-04 14:17
Hello people, I have a problem with _'setState(...): Can only update a mounted or mounting component...'_

I already asked on SO but nobody answered it,
anyway , before I run my app, I run a service to check for existing token,
then it redirects to '/login', after I enter my credentials I render the Dashboard component,
and everything is working but when I logout, and go to form to log in again, I get the above mentioned warning...I read everything there is about this problem, but can't seem to understand what I need to do in my case, here is my LoginComponent, from what do I actually need to "unsubscribe" from ?

```
class LoginComponent extends Component {

  constructor() {
    super();
    this.state = this._buildState();
    this.login = this.onClickLogin.bind(this);    
    this.changeName = this.changeName.bind(this)
  }

  componentDidMount() {
    this._isMounted = true;
  }
  componentWillUnmount() {
    this._isMounted = false;
  } 

  _buildState() {
    return {
      username: '',
      password: ''
    }
  }

  changeName(evt) {
    if (!this._isMounted) return;
    this.setState({
      username: evt.target.value
    })
  }

  changePass(evt) {
    if (!this._isMounted) return;
    this.setState({
      password: evt.target.value
    })
  }

  onClickLogin() {
    if (!this._isMounted) return;
    const { username, password } = this.state;
    this.props.login(username, password);
  }

  render() {
    
    return (
      <div style={styleDivLogin} >
        <some form..../>
        <ButtonComponent name="login" onClick={this.login}/><br/>
      </div>
    )
  }
}
```

**Comment by alangpierce** [comment] 2016-10-11 01:04
Hey @jimfb, fun running into you on the internet!

Another bug fix in the `makeCancelable` function: it can cause an `UnhandledPromiseRejectionWarning` in recent node versions (particularly when running tests with a new version of node). One of the changes in [node 6.6.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.6.0) is that all unhandled promise rejections result in a warning. The existing code from @vpontis had separate `then` and `catch` calls on the same base promise. Effectively, this creates *two* promises, one which only handles success, and one which only handles errors. That means that if there is an error, the first promise will be viewed by node as an unhandled promise rejection.

The fix is pretty easy: just chain the two calls so that it makes one promise with both a success and error handler. Here's the fixed code:

```js
const makeCancelable = (promise) => {
  let hasCanceled_ = false;

  const wrappedPromise = new Promise((resolve, reject) => {
    promise
      .then((val) =>
        hasCanceled_ ? reject({isCanceled: true}) : resolve(val)
      )
      .catch((error) =>
        hasCanceled_ ? reject({isCanceled: true}) : reject(error)
      );
  });

  return {
    promise: wrappedPromise,
    cancel() {
      hasCanceled_ = true;
    },
  };
};
```

**Comment by STRML** [comment] 2016-12-30 18:30
@alangpierce That is very close to correct, but not quite; if `resolve()` or `reject()` synchronously throws for any reason on a resolved promise, both handlers will be called.

The solution is to use the `.then(onFulfilled, onRejected)` pattern:

```js
const makeCancelable = (promise) => {
  let hasCanceled_ = false;

  const wrappedPromise = new Promise((resolve, reject) => {
    promise.then(
      (val) => hasCanceled_ ? reject({isCanceled: true}) : resolve(val),
      (error) => hasCanceled_ ? reject({isCanceled: true}) : reject(error)
    );
  });

  return {
    promise: wrappedPromise,
    cancel() {
      hasCanceled_ = true;
    },
  };
};

```

**Comment by br4nnigan** [comment] 2017-03-08 13:57
this seems to work too, does anything speak against it? (I don't want to reject after cancel but that's just my use case)

    export default class PromiseCancelable extends Promise {

        hasCanceled = false;

        constructor(callback: Function<Function, Function>) {

            super((resolve, reject) => {

                callback.call(this, (...args) => {

                    if ( !this.hasCanceled ) resolve.apply(this, args);
                }, (...args) => {
                    if ( !this.hasCanceled ) reject.apply(this, args);
                });
            });
        }

        cancel() {

            this.hasCanceled = true;
        }
    }

**Comment by benmmurphy** [comment] 2017-03-16 16:30
isn't this makeCancelable solution effectively the same is the isMounted() call when looking at point 3 as to why isMounted() is deprecated:

> Calling setState when a component is completely unmounted.
This is a strong indication that an asynchronous callback isn't being properly cleaned up. Unfortunately, mainstream JS APIs makes it very easy to avoid cleaning up hanging asynchronous callbacks.

> One callback isn't a big deal. However, that callback hangs on to objects and intermediate callbacks, promises and subscriptions. If alot of your components do this, you will quickly run into memory issues

makeCancellable just creates another promise which ends up holding a reference to functions which hold a reference to the component. the makeCancellable solution is just moving the boolean property isMounted into the promise.

in order to solve the GC issue you need to be nulling something out when cancel() is being called. otherwise you still have a reference chain from the async process to the component.

    class CancellableDeferred {
      constructor(request) {
        this.deferred = $.Deferred();

        request.then((data) => {
          if (this.deferred != null) {
            this.deferred.resolve(data);
          }
        });

        request.fail((data) => {
          if (this.deferred != null) {
            this.deferred.reject(data);
          }
        });
      }

      cancel() {
        this.deferred = null;
      } 

      promise() {
        return this.deferred.promise();
      }
    }

-> is how i would do it with jQuery deferred objects. i haven't really familiar with the Promise API so I don't know how it would look. Also, this doesn't reject the deferred when cancel() has been called and the deferred has not been resolved. Probably, people have a different opinion on how this should work.

so chain looks something like this:

> AJAX Request -> Closure -> CancellableDeferredInstance -> JQuery Deferred -> Component

then after cancel it looks like this:

> AJAX Request -> Closure -> CancellableDeferredInstance  /object reference now null/ JQuery Deferred -> Component

so the AJAX Request is no longer preventing the Component from being GCd

**Comment by vpontis** [comment] 2017-03-16 16:54
Hi @benmmurphy, I am not super familiar with JS garbage compiling and it may work differently with React, but I have a different understanding.

`makeCancellable` allows a React component to be garbage collected when it is unmounted. I'll explain.

> makeCancellable just creates another promise which ends up holding a reference to functions which hold a reference to the component. the makeCancellable solution is just moving the boolean property isMounted into the promise.

Without `makeCancellable`:

```
handleError() {
  if (this.isMounted()) {
    console.log('ERROR')
  }
}
```

With `makeCancellable` :
```
promise.then(...).fail((reason) => {
  if (reason.isCancelled) return;
  console.log('ERROR');
})
```

Without `makeCancellable` you still have a reference to `this` so the component can not be garbage collected when it is unmounted. But in the other case, the cancellable promise's fail handler is called as soon as the component is unmounted, so you don't have any references hanging around anymore.

**Comment by benmmurphy** [comment] 2017-03-16 17:46
@vpontis 

i have some nodejs code that illustrates the problem. The Foo component will only be GC'd once the asynchronous callback `resolve` has been set to null. For example lets say you fire off an ajax request that takes 30s to resolve then the component is unmounted. Then the component will not be GCd for 30s. This is one of the problems they are trying to solve with deprecating isMount().

    npm install promise
    npm install weak

    node --expose-gc gc.js
    first gc Foo {}
    after first gc Foo {}
    after resolve = null Foo {}
    foo gc'd
    after second gc {}

https://gist.github.com/benmmurphy/aaf35a44a6e8a1fbae1764ebed9917b6

**Comment by benmmurphy** [comment] 2017-03-16 19:12
in terms of the promise API this works for me in nodejs in terms of GC. though, i would prefer not to have the `_resolve`, `_reject` params near the closures because i'm not sure if this is guaranteed to work according to the JS spec or if it just happens to work because node is doing some optimizations. Can an implementation capture all variables visible or just the variables that are referenced in the closure? I dunno maybe someone who actually understands JS can chime in and explain :)

    var makeCancelable = (promise) => {
      let resolve;
      let reject;

      const wrappedPromise = new Promise((_resolve, _reject) => {
        resolve = _resolve;
        reject = _reject;

        promise.then((val) => {
           if (resolve != null) resolve(val)
        });
        promise.catch((error) => {
           if (reject != null) reject(error)
        });
      });

      return {
        promise: wrappedPromise,
        cancel() {
          resolve = null;
          reject = null;
        },
      };
    };

**Comment by artyomtrityak** [comment] 2017-05-24 21:49
Will isMounted function be removed in 16.0 ?

**Comment by BnayaZil** [comment] 2017-06-08 05:42
Suggestion for small improvement with @istarkov code:
```
const makeCancelable = (promise) => {
	let hasCanceled_ = false
	promise.then((val) =>
		hasCanceled_ ? reject({isCanceled: true}) : resolve(val)
	)
	.catch((error) =>
		hasCanceled_ ? reject({isCanceled: true}) : reject(error)
	)

	return {
		promise,
		cancel() {
			hasCanceled_ = true
		}
	}
}
```
It's just that the new promise is redundant.

**Comment by ZebraFlesh** [comment] 2017-07-21 21:40
> It's just that the new promise is redundant.

@BnayaZil You're calling `resolve` and `reject` functions, but it's unclear where those are from. Did you mean `Promise.resolve` and `Promise.reject`? In that case, you'd still be returning a new Promise.

**Comment by mo** [comment] 2017-07-24 09:51
A few days ago a new API was added to the DOM specification that allows you to abort fetch() requests. This API is not implemented in any browser yet but I have created a polyfill for it available on NPM was "abortcontroller-polyfill". The polyfill does essentially the same thing as the code posted by @istarkov but allows you to transition with no code changes to the real browser API once it's implemented.

Details here:
https://mo.github.io/2017/07/24/abort-fetch-abortcontroller-polyfill.html

**Comment by aweary** [comment] 2017-09-20 01:40
Since `React.createClass` no longer exists in React 16 and the new `create-react-class` package includes a clear deprecation message for `isMounted`, I'm going to close this out.

**Closed by aweary** 2017-09-20 01:40 UTC

**Comment by hjylewis** [comment] 2017-10-26 04:00
I agree with @benmmurphy that @istarkov's solution is effectively the same as using `isMounted()` since it doesn't solve the garbage collection problem. 

@benmmurphy's solution is closer but nulls out the wrong variables so the promise handlers are not dereferenced.  

The key is passing a function up through the closure that deferences the handlers:

```
const makeCancelable = promise => {
  let cancel = () => {};

  const wrappedPromise = new Promise((resolve, reject) => {
    cancel = () => {
      resolve = null;
      reject = null;
    };

    promise.then(
      val => {
        if (resolve) resolve(val);
      },
      error => {
        if (reject) reject(error);
      }
    );
  });

  wrappedPromise.cancel = cancel;
  return wrappedPromise;
};
``` 

Further explanation about why this solution allows for garbage collection and not the previous solutions can be found [here](https://github.com/hjylewis/trashable/blob/master/PROOF.md).

I went ahead and turned this into an npm package, [trashable](https://github.com/hjylewis/trashable). And since the use case is react, I made a HOC component that tracks promises and cancels them when the component gets unmounted, [trashable-react](https://github.com/hjylewis/trashable-react).

**Comment by pygy** [comment] 2017-11-10 09:20
None of these solutions cancel Promises, which can be cancelled without any extension by absorbing a forever-pending promise.

```JS
function makeCancelable(promise) {
  let active = true;
  return {
    cancel() {active = false},
    promise: promise.then(
      value => active ? value : new Promise(()=>{}),
      reason => active ? reason : new Promise(()=>{})
    )
  }
}

// used as above:

const {promise, cancel} = makeCancelable(
  new Promise(
    (fulfill) => setTimeout(() => {
      console.log("fulfilling")
      fulfill("Hey!")
    })
  )
)

promise.then((v) => console.log(v)) // never logs
cancel()

```

[live here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4wAVzTViEegAIsGANYwAwhikwoGAEawAFAAcATrSwQ4MAJRzgAHTRy5sYnIzSIANxhyAvHOJjcRgAbgcnYxhicWNHe0cnOWoNai19G2B3GW8-OTAMKEt2cMSTMwsYRDky80t8YkImfRLEuU8C4L8APjcPHIB+No6fKrQYAHc5AAVTWph9dN8u4FYrChbEyIw4eSXe7J9BrZ3HUYnp2YqFqyWVqw37hNYHZ7QHIThXYBqKiiSUrSsXKKFTqTTaPTzEpjSYzcqWZoJJz6CRQSBQKA2PaWYgAFQgOFo4mI126tg2Tg+tFg+CgtAA5s1wOI0dAoBA0PS7CBHq0nKj0VAmQAJGAATwAhNzeYlViVHo8HD86g0mvpPFielSaXTGRrHslwekHGwOCBMDg8PhqHABDR6IxmDw2ABdVhAA)

There may be subtleties to iron out regarding GC and coffee has yet to kick in, but that pattern ensures that the promise returned is really cancelled and it can be made not to leak (I've implemented it in the past).

**Comment by hjylewis** [comment] 2017-11-10 12:59
@pygy Thanks for the reply!

Unfortunately, your solution still doesn't allow for Garbage Collection. You've essentially just rewritten @istarkov's solution which uses a conditional.

You can test this easily by dropping this implementation into [trashable](https://github.com/hjylewis/trashable) and running the tests (the garbage collection test fails).

Your implementation also fails to properly handle errors.

**Comment by adeelibr** [comment] 2018-07-05 18:28
It's 2018 is there an even better approach then the one's mentioned above?

**Comment by npblubb** [comment] 2018-07-05 19:00
yes you can use some navigation frameworks that have a documentation twice the size of react native but is very professionel

**Comment by dantman** [comment] 2019-02-05 22:40
These snippets for "canceling" a promise aren't that great IMHO. The cancelled promises will still not resolve until the original promise resolves. So memory cleanup won't happen till it would if you just used an isMounted trick.

A proper cancelable promise wrapper would have to make use of a second promise and Promise.race. i.e. `Promise.race([originalPromise, cancelationPromise])`

**Comment by benmmurphy** [comment] 2019-02-06 13:25
> @benmmurphy's solution is closer but nulls out the wrong variables so the promise handlers are not dereferenced.

I think my solution works but I don't know enough about what promises the javascript runtime gives to know for sure. If you run the solution under node in your test harness it correctly GCs the value. My solution assigned the the resolve/reject functions to a higher scope and then nulled these values out when cancel was called. However, the functions were still available in the lower scope but not referenced. I think modern javascript engines don't capture variables in a closure unless they are referenced. I think this used to be a big problem where people would accidentally create DOM leaks because they did stuff like: var element = findDOM(); element.addEventListener('click', function() {}); and element would be referenced in the closure even though it wasn't used in the closure.

**Comment by drprasad-capillary** [comment] 2019-02-25 07:54
@hjylewis @benmmurphy why do we need to dereference handlers ?? after handlers excuted, garbage collection any way happens, right ??

**Comment by benmmurphy** [comment] 2019-02-25 14:50
> These snippets for "canceling" a promise aren't that great IMHO. The cancelled promises will still not resolve until the original promise resolves. So memory cleanup won't happen till it would if you just used an isMounted trick.
> 
> A proper cancelable promise wrapper would have to make use of a second promise and Promise.race. i.e. `Promise.race([originalPromise, cancelationPromise])`

@hjylewis and mine do you actually work you can verify it with node weak. but looking at them again i agree neither of them are idiosyncratic written promise code. as a promise user you would probable expect a 'cancelled' promise to resolve in the rejected state and neither of them do this. though, possibly in the case of a component this is a solution that would be easier to use because you don't have to write extra code to ignore the reject handler.

i think an idiosyncratic rejectable promise would use Promise.race([]) to build a cancellable promise. it works because when a promise becomes resolved the pending callbacks are deleted so at the point there would be no reference chain from the browser network to your component because there would be no longer a reference between the race promise and the component.

**Comment by ketysek** [comment] 2019-03-01 10:19
I'm curious if it's somehow possible to use `Promise.all()` with those cancelable promises and avoid uncaught errors in browsers console ... because I'm able to catch only first cancellation error, others remains uncaught.

**Comment by adeelibr** [comment] 2019-05-17 10:14
> It's 2018 is there an even better approach then the one's mentioned above?

Any better approach to cancel a promise execution i.e, setTimeout, API Calls etc.. It's 2019 😭 😞

**Comment by adeelibr** [comment] 2019-05-17 12:24
There is Promise cancellation thread going on TC39, (I think) it's of relevance here (maybe .. not sure)
https://github.com/tc39/proposal-cancellation/issues/24

**Comment by paul4156** [comment] 2019-09-18 23:27
> Any better approach to cancel a promise execution i.e, setTimeout, API Calls etc.. It's 2019 😭 😞

Are we looking for something like

```javascript
const promise = new Promise(r => setTimeout(r, 1000))
  .then(() => console.log('resolved'))
  .catch(()=> console.log('error'))
  .canceled(() => console.log('canceled'));

// Cancel promise
promise.cancel();
```

**Comment by impulsgraw** [comment] 2021-02-17 13:54
Ladies, as of 2021 I guess everyone better take a look at rxjs instead of reinventing the wheel again and again...

**Comment by baldwinjj** [comment] 2022-07-29 19:14
I know this is an old thread but I figure I'd chime in just in case anyone else comes across it looking for a generic solution to cancel promises as I did. @dantman is right, @istarkov's solution doesn't behave as I was expecting because the canceled promise doesn't reject until after the wrapped promise has resolved. Here is a solution that better matches my (and perhaps others') expectations. It immediately rejects whenever cancel is called.
```
const makeCancelable = (promise) => {
  let onCancel;
  const cancelPromise = new Promise((resolve, reject) => {
    onCancel = () => reject({ isCanceled: true });
  });
  return {
    promise: Promise.race([promise, cancelPromise]),
    cancel: onCancel,
  };
};
```
Here is an example of both solutions in action: https://stackblitz.com/edit/js-2kfvyt?file=index.js
