### ISSUE TITLE
[react 17] Bug: Click event being picked up by component rendered by the click

### ISSUE THREAD

**Issue by tholman** [facebook/react#21804] opened 2021-07-06 15:59 UTC
React version: 17.2

## Steps To Reproduce

1. Using a class component, if a click event changes some state, which renders a new component, and the new component adds an event listener on its `componentDidMount` checking for clicks, the new component will trigger that event

Link to code example: https://codepen.io/tholman/pen/87c661f0c893a2f8727db927c48d6d12

(this does not happen if the created component uses hooks to add its event listener)

## The current behavior
A state change via a click that causes a new component to be rendered, that new component can pick up the original click event that created it, which seems like its reaching back in time, to so speak.

## The expected behavior
Perhaps this is now intended behavior with the react 17 event changes (although it doesn't happen if I add the event listener with a hook on a functional component, but I would expect that if a click event causes a render, and the listener is added on the `componentDidMount` function, I would assume the "click" is complete, and wouldn't be detected.

**Comment by nelson360** [comment] 2021-12-07 09:53
somehow this worked out for me 
// Imports are like this
const { useState, useEffect } = React;

function App() {
  const [renderOther, setRenderOther] = useState(true);

  return (
    <div>
      <button onClick={(e) => setRenderOther(!renderOther)} >Click me</button>
      
      {renderOther && <ComponentCheckingForClick />}
    </div>
  );
}

class ComponentCheckingForClick extends React.Component {
  
  componentDidMount() {
    window.addEventListener('click ', this.onEventClick)
  }
  
  componentWillUnmount() {
    window.removeEventListener('click not', this.onEventClick)
  }
    onClickPreventDefault(e) {
    alert('onClickPreventDefault called, form will not submit');
    e.preventDefault();
  }
 
  onEventClick(e) {
    alert("click!", e.target)
  }
  
  render() {
    return <div>Other Component</div>
  }
}


ReactDOM.render(<App />, document.querySelector("#app"));

**Comment by nelson360** [comment] 2021-12-07 10:21
This `somehow this worked out for me
// Imports are like this
const { useState, useEffect } = React;

function App() {
const [renderOther, setRenderOther] = useState(true);

return (

<button onClick={(e) => setRenderOther(!renderOther)} >Click me
  {renderOther && <ComponentCheckingForClick />}
</div>
);
}

class ComponentCheckingForClick extends React.Component {

componentDidMount() {
window.addEventListener('click ', this.onEventClick)
}

componentWillUnmount() {
window.removeEventListener('click not', this.onEventClick)
}
onClickPreventDefault(e) {
alert('onClickPreventDefault called, form will not submit');
e.preventDefault();
}

onEventClick(e) {
alert("click!", e.target)
}

render() {
return

Other Component

}
}
ReactDOM.render(, document.querySelector("#app"));`

**Comment by BennyCarlsson** [comment] 2022-05-20 09:15
This happened to me using React18 and hooks.

Example: https://codesandbox.io/s/festive-mopsa-lgke69?file=/src/App.js

Got a solution using e.stopPropagation() from creating a stackoverflow question. but it's still weird it's happening. https://stackoverflow.com/questions/72315874/react-18-addeventlistentclick-triggers-on-a-click-that-happens-before-compon

**Comment by sargalias** [comment] 2022-10-23 01:36
Related or duplicate of https://github.com/facebook/react/issues/24657?

**Comment by eps1lon** [comment] 2022-10-29 09:03
Duplicate of https://github.com/facebook/react/issues/24657. Check out https://github.com/facebook/react/issues/24657#issuecomment-1150119055 for an extensive explanation

**Closed by eps1lon** 2022-10-29 09:03 UTC
Labels: Status: Unconfirmed
