### ISSUE TITLE
Support for indeterminate checkbox state

### ISSUE THREAD

**Issue by azich** [facebook/react#2973] opened 2015-01-28 22:33 UTC
Chrome, Firefox, Safari, IE and other modern browsers support the notion of a checkbox in an indeterminate state which can be set or cleared using the `indeterminate` property of a checkbox input node. (It cannot be set using attributes.)

This state is most commonly used at the top of a list or tree of checkboxes to indicate that some but not all of the checkboxes underneath are checked.

This behavior seems reasonably well-defined in modern Chrome, Firefox, Safari, and IE. If the checkbox's indeterminate property is set, the checkbox renders its indeterminate state regardless of what its checked state is (or if its checked state is programmatically toggled) and clicking on a checkbox clears its indeterminate state.

Unfortunately there is a little bit of inconsistency. In Chrome, Firefox, and Safari clicking an indeterminate checkbox clears the indeterminate state and also toggles the checked state (triggering both a change and click event) while in IE it just clears the indeterminate state and leaves the checked state alone (triggering only a click event).

- Should React support an `indeterminate` prop for checkbox inputs?
- Should it be supported for uncontrolled checkboxes (via an `defaultIndeterminate` or similar prop)?
- Should clicking an indeterminate checkbox follow the browser's checked-toggling behavior?

[Claims above come from playing with [this jsFiddle](http://jsfiddle.net/3bn73ey5) in Chrome 40, Firefox 35, Safari 7, and IE 11]

**Comment by syranide** [comment] 2015-01-28 22:36
Duplicate of #1798

**Comment by zpao** [comment] 2015-07-22 19:12
Yup, let's chat in there.

**Closed by zpao** 2015-07-22 19:12 UTC
