### ISSUE TITLE
Unexpected unmount/mount has occurred when delete node.

### ISSUE THREAD

**Issue by Sheile** [facebook/react#8731] opened 2017-01-10 06:34 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If `props.children` has single node, all behavior is right.
But `props.children` has multiple nodes, unexpected unmount/mount has occurred on unchanged node when delete other node.

**minimal demo of the problem**
#### Without any problem(`props.children` has single node)
https://jsfiddle.net/sheile/pyuqmytj/1/
When click "toggle" button, toggle `<span>loading</span>` and don't affect on `<Dummy/>` node.

#### Problem reproduce(`props.children` has multiple nodes)
https://jsfiddle.net/sheile/pyuqmytj/2/
i.e. Add `<h1>` node to previous fiddle.

When click "toggle" button, toggle `<span>loading</span>` and unmount `<Dummy/>` and mount new `<Dummy/>` node.
note: `key` attribute is helpless about this problem.

**What is the expected behavior?**
Keep `<Dummy/>` node regardless number of children.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Reproduced by react 0.14.8, 15.4.2 and 16.0.0-alpha.

**Comment by aweary** [comment] 2017-01-10 18:07
@Sheile thanks for the report. I was able to verify this behavior. At a quick glance I think its a bug with our child reconciler. The IDs we generate for the children are not consistent when we update them:

<img width="716" alt="screen shot 2017-01-10 at 11 56 45 am" src="https://cloud.githubusercontent.com/assets/6886061/21818172/6e732378-d72c-11e6-980e-3058aea9f71f.png">

Since the IDs don't match [`ReactChildReconciler`](https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/ReactChildReconciler.js#L148-L158) ends up mounting the child again and the old one gets queued up to be unmounted. I'm not very familiar with child reconciliation but this seems like unexpected behavior (cc @gaearon what do you think?) This might just be a consequence of returning a different root element (even if it's the same type).

@Sheile you can get around this by inlining your conditional render

```jsx
  <div>
    {this.props.children}
    {this.props.loading && <span>Loading</span>}
  </div>
```

**Comment by gaearon** [comment] 2017-01-10 20:30
Could this be the same as the first issue I ever reported? 😄 
https://github.com/facebook/react/issues/1493

I don't think this is necessarily a bug, but I’m not sure.

Here’s why I think it happens. Looking at the second fiddle, in the `if` branch, `div`'s children end up being an array with two elements (`Dummy` and `span`). However, in the `else` branch, `div`'s children is actually a single child: `Dummy`. So when we toggle the button, we switch between an array with one element to just that element. React currently treats it as a change in type, although I’m not sure it’s right.

In any case, this is very easy to work around:

```js
class Loader extends React.Component {
  render() {
    return (
      <div>
        {this.props.children}
        {this.props.loading &&
          <span>Loading</span>
        }
      </div>
    )
  }
}
```

Just don’t rely on matching up "holes" between different branches.
https://jsfiddle.net/8rnmsqtv/

**Comment by syranide** [comment] 2017-01-10 21:01
This is an unfortunate side-effect of Reacts special logic that exists to counter the effects where JSX does not wrap an only child in an array. I.e. React treats `child === [child]`, but `[child] !== [[child]]`. So since you are inserting `this.props.children` next to another element it becomes nested and the special logic stops working as you're now effectively encountering `[child] !== [[child]]`. IMHO I think putting anything adjacent to `this.props.children` isn't very nice and should be avoided (thus avoiding this problem too).

On another note, it would be interesting if there was a neat way for JSX to actually mark an only child so that React can apply the special logic only when that has happened. Thus entirely eliminating this unintuitive and magic behavior from React.

**Comment by Sheile** [comment] 2017-01-12 02:08
Thank you for pointing related issues and taking time to explain it.
I have understood this problem and workaround.

Yesterday, I tried to flatten children in `ReactElement.createElement` when `children` is Array.
This problem has been resolved, but need additional `key` attribute to identify node that in different nest level like this.
https://github.com/Sheile/react/commits/test/unexpected-unmount

hmm.. this problem is more than I can handle.
Please close this issue if no longer need discussion.

**Comment by gaearon** [comment] 2017-04-21 14:38
Going to close as wontfix for now. Can come back later.

**Closed by gaearon** 2017-04-21 14:38 UTC
