### ISSUE TITLE
In react 15.6 and greater (safari only), onChange does not fire for input boxes when using sendkeys in the test automation framework selenium

### ISSUE THREAD

**Issue by stephenweaver** [facebook/react#10687] opened 2017-09-12 20:09 UTC
**Do you want to request a *feature* or report a *bug*?**

I believe this is a bug that was introduced in version 15.6. It also exists in the latest tagged version.
(v16.0.0-rc.2)

**What is the current behavior?**

When running functional tests using selenium and the safari web driver (https://github.com/SeleniumHQ/selenium/wiki/SafariDriver), using the "sendKeys" method doesn't trigger an onChange event of an input field. This appears to be safari only, however, I've only tested in Chrome and Safari. The result is the the app doesn't see the text in the form input fields. (In our case, we can't log in when running our automation tests, because the username field thinks it's empty, even though the text appears to be in the field)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

It's a rather complicated setup process if you don't already have selenium working, but assuming you have a selenium test set up, it's very simple to reproduce.

Create a clean react 15.6 app. 
Edit the App.js file to include `<input id='test-text' onChange={this.onTextChanged}/>`
Add this method above the render function `onTextChanged() {
    console.log('onTextChanged');
  }` 
Run the selenium test that types into the new input field.
You'll notice that the console logs have not mention of "onTextChanged"

If you edit the packages.json file to use react 15.5, remove the node_modules folder, and re-run yarn install and yarn start; you'll notice the you do in

**What is the expected behavior?**

You should notice a console log instance of "onTextChanged" for each character typed into the input field.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

As mentioned above, chrome is not effected by this issue, and the issue appears to be introduced in version 15.6.0. 

Reverting our app back to 15.5.4 allows our automation tests to run, if this could be fixed in v16, that would be great as we won't be upgrading until this is resolved. Please let me know if I can provide any more useful information.

**Comment by gaearon** [comment] 2017-09-12 20:47
@jquense

**Comment by aweary** [comment] 2017-09-12 21:29
@stephenweaver can you provide some more information on your test setup, such as what version you're using for Selenium, Chrome, and Safari? According to https://github.com/SeleniumHQ/selenium/wiki/SafariDriver-Internals the `SafariDriver` browser extension is deprecated, is that what you're using?

**Comment by khramovv** [comment] 2017-09-13 06:50
@aweary yes you are wright we are using last supported SafariDriver.safariextz v2.48 that is actually deprecated. But we cannot use the new one Safari driver from apple as it is launching browser in automation mode (like private mode) and our application does not suport such kind of browser mode. But as @stephenweaver mentioned with react v15.5.4 we did not have such issue and the react v15.6.0 bring it to us.

**Comment by jquense** [comment] 2017-09-13 12:41
Hmm my experience of the older safari driver is that it is fairly flaky. I'm not sure how the input changes in 15.6 could break anything tho, we are running a few tests on older safari with the older driver and not seeing this issue as well. Does anyone have an idea on how to narrow this down a bit?

**Comment by aweary** [comment] 2017-09-15 15:35
It would be helpful if we could get a repro, though I know that's difficult due to Selenium's setup process. Without that, it's too difficult to say what might be happening with any certainty. The changes made to inputs in 15.6 were pretty significant, but they resolved a number of important issues. If this issue is isolated to a deprecated driver, the worst case scenario is that this is an acceptable tradeoff for better long-term stability.

**Comment by stephenweaver** [comment] 2017-09-19 22:08
I appreciate the responses. We're currently really swamped, so for now now we just rolled back a version. I'll try to find some time in the next few weeks to send over a complete demo. But, if you're pretty sure that you aren't planning on ever addressing the issue, please let me know so we'll can allocate the extra time needed on finding a way around the issue when we do upgrade.

**Comment by aweary** [comment] 2017-09-19 22:43
> But, if you're pretty sure that you aren't planning on ever addressing the issue, please let me know so we'll can allocate the extra time needed on finding a way around the issue when we do upgrade.

We can't definitively say we will or won't accept a fix for this since we don't know what that would entail yet. If we can identify a fix that is non-intrusive and doesn't compromise the other fixes we've already made, then I think we would consider it. Though it's unlikely that we would include a fix that introduced any special-cased logic for this driver issue.

Sorry we can't provide a more concrete answer right now, but please ping us if you do find the time to send over a complete demo!

**Comment by denislutz** [comment] 2018-05-25 09:37
Hi, we seem to have the same issue. Are there any updates on it?
related libs:

```
"react": "16.2.0",
"react-dom": "16.2.0",
"redux": "^3.7.2",
```

**Comment by gaearon** [comment] 2018-05-25 13:46
If there were updates they would be on this issue. If you read the discussion above, you’ll see we’d need a reproducing case.

**Comment by gaearon** [comment] 2018-08-16 16:10
I'm going to close because there aren't sufficient details here to proceed.

>If this issue is isolated to a deprecated driver, the worst case scenario is that this is an acceptable tradeoff for better long-term stability.

**Closed by gaearon** 2018-08-16 16:10 UTC
Labels: Component: DOM, Type: Regression

**Comment by NallaSandeep** [comment] 2020-01-09 06:00
@gaearon 
Please try out below code on ios devices vs android devices, so that you can get to know the difference.

```
driver.get("https://www.ftd.com");
WebElement element = driver.findElement(By.name("zipcode"));
element.sendKeys("60515");
Thread.sleep(5000);
JavascriptExecutor js = (JavascriptExecutor) driver;
js.executeScript("arguments[0].scrollIntoView(true);", element);
Thread.sleep(5000);
```

Expected result:
On entering zip code, the gift finder section should be expanded. 

Note: Working as expected in android device, but not on ios device.

_Video recording:_
**On Android device:** [](https://automate.browserstack.com/builds/6ba5eb243ede57f67b414d322883dc6daff88cf6/sessions/2229a608c679da67cf362316eebc80e5068d3179?auth_token=0b1be4580244d42f90e8de911ac98cb84bdd2a614b2cf4e0e9dcab05f1b97803)
**On IOS device:** [](https://automate.browserstack.com/builds/6ba5eb243ede57f67b414d322883dc6daff88cf6/sessions/98ab850bd3211a08cc465142f1491fedeed30450?auth_token=473e56711ac595408c80b0415e58453f372d71742bfc41cb7bccba4e96e5c218)

Please provide the working solution for this.
