### ISSUE TITLE
TypeError when parent Component is updated after uncaught exception in child Component's componentWillMount

### ISSUE THREAD

**Issue by AZielinski** [facebook/react#3313] opened 2015-03-04 22:29 UTC
Expected result: rendered text `There was an error`
Actual result: `Uncaught TypeError: Cannot read property 'unmountComponent' of undefined`
JSFiddle: http://jsfiddle.net/kb3gN/10167/

The code:
```js
var Parent = React.createClass({
    getInitialState: function() {
        return {error: false};
    },
    componentWillMount: function() {
        var self = this;
        // window.onerror is only used for brevity
        window.onerror = function() {
            if(self.isMounted()) {
                self.setState({error: true});
            }
        };
    },
    render: function() {
        if(this.state.error) {
            return <div>There was an error</div>;
        } else {
            return <Child />;
        }
    }
});

var Child = React.createClass({
    componentWillMount: function() {
        throw new Error("test error");
    },
    render: function() {
        return <div>Child</div>;
    }
});

React.render(<Parent />, document.body);
```

**Comment by jsfb** [comment] 2015-03-05 09:54
Good catch.  An explosion within a component should not cause the React core to die.  cc @sebmarkbage

**Comment by sebmarkbage** [comment] 2015-03-05 09:57
This is effectively a duplicate of #2461

Throwing during the render phase leaves React in a broken state and we're unable to recover. We need to do some major refactoring and introduce better regressions tests to support this. Will close this out and leave it to #2461

**Closed by sebmarkbage** 2015-03-05 09:57 UTC
Labels: Type: Bug
