### ISSUE TITLE
Bug: React.js new bug, I think

### ISSUE THREAD

**Issue by MortezaHeydari97** [facebook/react#19176] opened 2020-06-22 17:24 UTC
Hi, today I created a new react.js project in **typescript** template using this command : 
`npx create-react-app my-project-name --template typescript`.
Then project's react version is: 16.13.1 .

After completing this process, I ran it using this command: `npm start`. It ran successfully and I saw the result.
Then when I tried to get install a new package like `react-router-dom`, I saw some of packages are removing from my project's `node_modules`.

Now when I'm trying to run the project, it will getting an error as below:
`./src/assets/styles/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/styles/index.scss)
Error: Package exports for 'C:\projects\sokna-pwa\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target`.

But when I removed css files from index.tsx and App.tsx, it compiled successfully. Then the problem is in the css files.

After too many long searchs, I tries this command from this **[#issue](https://github.com/symfony/webpack-encore/issues/717)** :
`yarn add sass-loader@^7.0.1 node-sass --dev`

This command will fixes my project for temp but when I getting try to add a new package to my project, the last error will appears.

How can I fix this ???
Thank for your help

**Comment by bvaughn** [comment] 2020-06-23 19:37
Duplicate of #19166 and #19172.

This should be filed in the create-react-app repo:
https://github.com/facebook/create-react-app

Please check before filing as it has likely already been filed.

**Closed by bvaughn** 2020-06-23 19:37 UTC
Labels: Status: Unconfirmed

**Comment by MortezaHeydari97** [comment] 2020-07-01 16:10
@bvaughn So thanks !
