### ISSUE TITLE
Add alias methods for the React lifecycle components

### ISSUE THREAD

**Issue by ianks** [facebook/react#5671] opened 2015-12-15 23:31 UTC
Here is a classic example of creating a React class in es6:
```js
export class Counter extends React.Component {
  componentWillReceiveProps(nextProps, nextContext) {
     ...
  }

  shouldComponentUpdate(nextProps, nextState, nextContext) { 
     ...
  }
  render() {
    ...
  }
}
```

There are a few things I find bothersome with the lifecycle method names:

# Problem

## Including 'component' in the method name is redundant

Since we are extending a class, Liskov substitution tells us that we the subclass we are implementing should implement the behaviors of `Component`. Since we know our class is a Component, saying `componentWillReceiveProps` is redundant, we could just as well say `willReceiveProps`.

This redundancy may seem trivial, but it is more typing, more boilerplate, and thus, more error-prone.

## The name is non-orthogonal

1. `componentWillMount`
2. `componentDidMount`
3. `componentWillReceiveProps`
4. `shouldComponentUpdate` <- :confused:
5. `componentWillUpdate`
6. `componentDidUpdate`
7. `componentWillUnmount`

I end up typing `componentShouldUpdate` more often than I would like to admit. At best, this is a distraction, at worst, it is a subtle source of bugs. 

# Proposed Solution

Add alias methods fore the lifecycle methods

1. `componentWillMount`             ----> `willMount`
2. `componentDidMount`             ----> `didMount`
3. `componentWillReceiveProps` ----> `willReceiveProps`
4. `shouldComponentUpdate`      ----> `shouldUpdate`
5. `componentWillUpdate`             ----> `willUpdate`
6. `componentDidUpdate`            ----> `didUpdate`
7. `componentWillUnmount`          ----> `willUnmount`

Now, this will obviously require a deprecation cycle as we need to warn users that are using these method names for other reasons. It seems to be somewhat common (a quick search on Github shows many people doing this).

## Conclusion

Although this may seem like bike-shedding, I think this is important and will save time/agony for the long future of React users (old and new).

:heart:

**Comment by gaearon** [comment] 2015-12-15 23:56
Please see https://github.com/reactjs/react-future/issues/40#issuecomment-142442124 and https://github.com/reactjs/react-future/issues/40#issuecomment-153440651.

**Comment by jimfb** [comment] 2016-01-04 19:40
@gaearon is correct, duplicate of https://github.com/reactjs/react-future/issues/40.

**Closed by jimfb** 2016-01-04 19:40 UTC
