### ISSUE TITLE
Add support in the future for custom elements

### ISSUE THREAD

**Issue by pspeter3** [facebook/react#1214] opened 2014-03-04 17:40 UTC
It would be really cool to allow view to be custom elements. http://coding.smashingmagazine.com/2014/03/04/introduction-to-custom-elements

**Comment by gargantuan** [comment] 2015-10-06 14:41
Custom elements currently work, but are broken in the release candidate. There's a discussion in issue  [#4933](https://github.com/facebook/react/issues/4933) and it seems the position of the React team is that it will remain broken.

I do not see how web components address any of the issues of modern web development. However, it looks like we will lose all the semnatic goodness of custom elements in support of a spec that's failed before it even begins.

**Comment by jimfb** [comment] 2015-10-06 17:58
To be clear: custom elements do work correctly (as intended) in the release candidate.  The custom element specification allows for arbitrary attributes to be specified on a custom element, which is why the design decision to use the `class` attribute instead of `className` was chosen (the custom elements spec requires us to preserve the full case-sensitive namespace).  We will continue the discussion of that topic in the issue you linked.

We have another issue tracking upcoming DOM technology, so I'm going to close this issue out in favor of https://github.com/facebook/react/issues/2836

**Closed by jimfb** 2015-10-06 17:58 UTC
Labels: Type: Feature Request
