### ISSUE TITLE
Bug: dispatch useReducer not working with useEffect

### ISSUE THREAD

**Issue by hazratgs** [facebook/react#20179] opened 2020-11-06 12:30 UTC
Hello everyone, I ran into an interesting feature, I use useEffect as an executor of certain actions and specify flags from useReducer state as dependencies, for example:

```
. . .
const [state, dispatch] = useReducer(reducer, initialState);
const { isScrollToBottom } = state;
console.log('render', isScrollToBottom);

useEffect(() => {
    console.log('dispatch useEffect deps []');
    dispatch({ type: 'setScrollToBottom', payload: true });
  }, []);

  useEffect(() => {
    const { scrollTop, offsetHeight, scrollHeight } = scroll;
    if (scrollTop + offsetHeight === scrollHeight) {
      console.log('dispatch useEffect deps [messages]');
      dispatch({ type: 'setScrollToBottom', payload: true });
    }
  }, [messages]);

  useEffect(() => {
    console.log('run useEffect deps [isScrollToBottom, bottomTarget]');
    if (isScrollToBottom && bottomTarget && bottomTarget.current) {
      bottomTarget.current.scrollIntoView();
      console.log('dispatch useEffect deps [messages]');
      dispatch({ type: 'setScrollToBottom', payload: false });
    }
  }, [isScrollToBottom, bottomTarget]);
. . .
```

As a result, dispatch from useEffect with payload false does not work, it simply does not execute, this is what the console outputs:
```
render false
run useEffect deps [isScrollToBottom, bottomTarget]
dispatch useEffect deps [messages]
dispatch useEffect deps []
render true
run useEffect deps [isScrollToBottom, bottomTarget]
dispatch useEffect deps [messages]
dispatch useEffect deps [messages]
render true
render true

```

I want to return it to false after executing the flag action, but for some reason it doesn't work ((

React version: 16.13.1

Update:
The problem was solved by changing the property in the reducer itself:
```
export const reducer = (state: StateType, action: Action): StateType => {
  switch (action.type) {
    case 'setScrollToBottom':
      return {
        ...state,
        isScrollToBottom: !state.isScrollToBottom,
      };
    default:
      return state;
  }
};

```

**Comment by bvaughn** [comment] 2020-11-06 19:15
Bug reports like this really need full repros (not partial code snippets).

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-11-16 13:30
Closing this due to lack of a repro or repsonse.

**Closed by bvaughn** 2020-11-16 13:30 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
