### ISSUE TITLE
Remove selectionStart polyfill?

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11806] opened 2017-12-08 01:23 UTC
Looking at this code:

https://github.com/facebook/react/blob/bee4baf1fd8d018a020cd72de1635839d7dc2bb1/packages/react-dom/src/client/ReactInputSelection.js#L91-L100

When would `selectionStart` not exist? According to http://help.dottoro.com/ljtfkhio.php, only in IE8. (It might be wrong though.)

It would be nice to check, and remove the relevant code if it's supported everywhere else.

**Comment by gaearon** [comment] 2017-12-08 01:23
Tagging as good first issue—the outcome is a report on which browsers support the feature.

**Comment by jquense** [comment] 2017-12-08 02:00
I am fairly sure it's ie8 only for inputs/text areas. We just removed the equivalent code in a bunch of libraries with no (observable) issues so far. I'd imagine tho the story is different contenteditable? Maybe the draftjs folks have some insight?

**Comment by gaearon** [comment] 2017-12-08 02:10
Tagging @flarnie

**Comment by gaearon** [comment] 2017-12-08 02:11
(I haven’t thought about CE but you might be right!)

**Comment by Miklet** [comment] 2017-12-08 19:04
I also checked at [caniuse](https://caniuse.com/#search=selectionStart). Seems support starts from IE9.

**Comment by xxblakefailxx** [comment] 2017-12-08 20:47
[MDN ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) also reports IE9 and up support.

**Comment by flarnie** [comment] 2017-12-09 00:19
The comment `// Content editable or old IE textarea. ` is a concern because we rely on `contenteditable` in Draft.js. Let me look into it a bit.

**Comment by flarnie** [comment] 2017-12-09 00:57
This example shows that unlike other inputs or a textarea, 'selectionStart' is not available on a contenteditable div. So let's keep this polyfill, and also add a test for this somewhere. I would love to have a Draft.js fixture, but maybe just a contenteditable fixture or test.
https://codepen.io/anon/pen/ZagBrx?editors=1111
I was just playing with that in latest Firefox.
![screen shot 2017-12-08 at 4 54 42 pm](https://user-images.githubusercontent.com/1114467/33790842-cf498ebe-dc38-11e7-8145-c2958a9f5b7d.png)

**Comment by flarnie** [comment] 2017-12-09 01:02
For anyone interested in more info:
Only `input` and `textarea` are defined as having the text field selection API.
https://www.w3.org/TR/2008/WD-html5-20080610/editing.html#textFieldSelection

In Draft we rely on the similar but different Selection interface -
https://www.w3.org/TR/2008/WD-html5-20080610/editing.html#selection1
which we wrap in an immutable record - 
https://github.com/facebook/draft-js/blob/master/src/model/immutable/SelectionState.js

**Comment by xxblakefailxx** [comment] 2017-12-09 09:29
@flarnie  Would this test suffice? Mainly checking selection start is working where we expect and showing that it doesn't work in the ce case? That way when it's supported we are aware and can remove the backwards support? Or did you have something else in mind?

**Comment by flarnie** [comment] 2017-12-09 13:45
@xxblakefailxx Glad to see a test for this - I should have been more clear that I recommend keeping this polyfill in place, and so the test would verify that it *does* work for contenteditable. If we reverse the expectation of the last test in the suite you wrote then it looks good to me.

To remove this polyfill would be a breaking change, because that would remove our support for selection in `contenteditable`, and some text editing libraries may be relying on it.

It looks like Draft relies entirely on the Selection api, which is different, but I imagine that adding this support was based in part on potential use cases with Draft.js. @sophiebits can confirm whether removing this polyfill would also break Draft.js.

**Comment by sophiebits** [comment] 2017-12-11 04:12
I know contenteditable inputs don't work properly without this. Maybe there is something we can do in user space (such as in draft itself) but it can't just be removed.

**Comment by xxblakefailxx** [comment] 2017-12-11 04:32
@sophiebits Do you know of a way we can manual test that shows the contenteditables not working without the polyfill?

**Comment by sophiebits** [comment] 2017-12-12 18:59
Not sure but I think if you comment out this code and try to use any Draft editor then you will probably see the problem. If it's not obvious when typing directly then try cutting/pasting and more complex cursor movements.

**Comment by vikramcse** [comment] 2017-12-27 06:26
Is someone working on this issue? If not then I would love to work on this issue :)

**Comment by flarnie** [comment] 2018-01-02 19:11
Discussing in the comments we determined that `contenteditable` containers need this polyfill, and it should not be removed after all at this time. I'm closing this issue, but if there are further action items we can open a new issue.

**Closed by flarnie** 2018-01-02 19:11 UTC
Labels: Browser: IE, Component: DOM, Difficulty: medium, good first issue, Type: Needs Investigation

**Comment by sophiebits** [comment] 2018-01-02 19:56
The issue may be specific to Draft. If someone wants to investigate and determine exactly what the problem is, maybe we can remove this code from React.

**Comment by flarnie** [comment] 2018-01-02 20:44
It's an issue with any `contenteditable` div, so anyone using that type of input would need this polyfill, not just Draft.js. My example above is just a div with `contenteditable`. https://codepen.io/anon/pen/ZagBrx?editors=1111

If we really want to remove it, to avoid a 'gotcha' for users we would want a dev-only warning when they use `contenteditable`, and we would want to provide examples of how to use the polyfill outside of React.

**Comment by sophiebits** [comment] 2018-01-02 20:48
Yes, selectionStart does not exist, but we only need it in order to restore selection, which we may not need for Draft. If we moved that logic into Draft then we could skip the selection restoration logic for contenteditable.

We already have a warning against contenteditable saying it's unsupported.
