### ISSUE TITLE
[DevTools Bug]: React.memo causing DevTools to fail to render the entire DOM tree.

### ISSUE THREAD

**Issue by theschubinator** [facebook/react#21538] opened 2021-05-20 16:41 UTC
### Website or app

Companies Website

### Repro steps

1. The DevTools failed to render the entire tree; therefore, I could not find any elements to debug within the DevTools.
2. We targeted it down to the use of React.memo to wrapped one of our components.
3. When removing the React.memo logic everything worked as expected.

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment] 2021-05-20 18:49
> Companies Website

This isn't a repro case that we can access. Please share code (or a public website) that we can run to reproduce this problem.

**Comment by bvaughn** [comment] 2021-05-20 19:35
For example, this Code Sandbox uses `React.memo` and the app renders fine in DevTools:
https://codesandbox.io/s/serene-goodall-7u5k3?file=/src/App.js

```js
function Component() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}

const MemoizedComponent = memo(Component);

export default function App() {
  return <MemoizedComponent />;
}
```

**Comment by bvaughn** [comment] 2021-05-20 20:42
Going to close this issue for now since there's no repro and it seems to work as expected from my own testing. Will happily re-open it and investigate if a repro is provided.

**Closed by bvaughn** 2021-05-20 20:42 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed, Type: Bug
