### ISSUE TITLE
Stateless functional components and shouldComponentUpdate

### ISSUE THREAD

**Issue by slorber** [facebook/react#5677] opened 2015-12-16 14:05 UTC
This is probably a question / documentation issue.

```
var Aquarium = ({species}) => (
  <Tank>
    {getFish(species)}
  </Tank>
);
```

In some places of the doc we can read:

https://facebook.github.io/react/docs/reusable-components.html

> In an ideal world, most of your components would be stateless functions because these stateless components can follow a faster code path within the React core. This is the recommended pattern, when possible.

https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

> This pattern is designed to encourage the creation of these simple components that should comprise large portions of your apps. In the future, we’ll also be able to make performance optimizations specific to these components by avoiding unnecessary checks and memory allocations.

What I find unclear is these explainations is how React optimize the rendering when using stateless functional components. The good sense would be that React uses something similar to `shallowEqual` to know if it has to call the function or not, but as React does not enforce strict immutability yet (I mean the PureRenderMixin is actually an option, not the default), I wonder how these functional components behave.

I think this should be better documented if any memoization technique is used when rendering these functional components, because it's not so obvious to me if my app will perform almost the same (or better) if I choose to replace all my components using PureRenderMixin and no state/lifecycle methods by functional components as I don't have much insights of the internal working of the optimizations done.

**Comment by jimfb** [comment] 2015-12-16 14:28
For complex components, defining `shouldComponentUpdate` (eg. pure render) will generally exceed the performance benefits of stateless components.  The sentences in the docs are hinting at some future optimizations that we have planned, whereby we won't allocate an internal instance for stateless functional components (we will just call the function).  We also might not keep holding the props, etc.  Tiny optimizations.  We don't talk about the details in the docs because the optimizations aren't actually implemented yet (stateless components open the doors to these optimizations).

**Comment by slorber** [comment] 2015-12-17 11:35
Thanks

So what I understand is that currently functional components do not memoize their execution based on shallowCompare of props right? Couldn't it be implemented easily?

**Comment by jimfb** [comment] 2015-12-17 12:57
Correct.  Such memoization would break any application that was not using immutable data, because the "optimization" would be making an assumption that the root prop reference changes when the data changes.  Imagine that the prop is an array, pushing to the array would not show up in a shallowCompare, which is why that optimization is not valid by default.

**Comment by slorber** [comment] 2015-12-17 13:12
So how can I use that memoization with a functional component? Will I be able to do so in the future?

I guess I could wrap it in an HOC but this then probably defeats the purpose of using functional components for the coming little optimizations that can be done

**Comment by jimfb** [comment] 2015-12-17 13:19
There are discussions about having a `pureRender` flag that you could set on the function, or allowing it to participate in the shouldUpdate lifecycle, but that's currently not implemented.  At the moment, stateless functions can not be pure-render.

It is worth keeping in mind that sometimes people abuse/overuse pure-render; it can sometimes be as or more expensive than running the render again, because you're iterating over the array of props and potentially doing things like string compares, which is just extra work for components that ultimately return true and then proceed to rerender anyway.  PureRender / `shouldComponentUpdate` really is considered an escape hatch for performance and is not necessarily something that should be blindly applied to every component.

**Comment by slorber** [comment] 2015-12-17 13:34
I would be happy to have that flag.


yes I understand that however in most cases where we start to compare primitive values there's generally a parent that may already have memoized the rendering. It's often the data is coming from an API or is stored in objects so your primitives are probably in an immutable object at first before being dispatched to deeper components.

I think in  ELM or Om this is applied by default to all the tree and works pretty well.

Is it that bad to compare strings vs comparing object identities? I guess strings hashes are compared first no?

**Comment by jimfb** [comment] 2015-12-17 13:50
Elm and Om are both far more functional/immutable than general javascript, which is probably why it makes more sense there.  We are supporting standard javascript as a target language, and javascript is a language where mutability is common.

My perf benchmarks have found string compares to sometimes be quite slow (just doing string-compares of the prop-names with pre-defined values that we need to handle specially, and that isn't even arbitrarily long data compares).  Hash comparison can only detect miss-matches, but can not guarantee that two strings are equal (due to collisions), but your assumption is that the two strings are equal in the common case, otherwise why would you be using pure-render.  String pooling does a better job than hashing, but it starts to get complicated.

Anyway, we digress.  The simple answer is: no, we don't do pure render by default, but we may provide a way for you to opt-in in the future.

**Comment by slorber** [comment] 2015-12-17 14:03
so this is fine :)

I don't know so much about the javascript's inner working but coming from Java world we have string pooling built-in so I may assume wrong things about js :)

**Comment by jimfb** [comment] 2015-12-17 14:10
I also come from a Java background.  Java's pooling works pretty well, but you still can't depend on `str1 == str2` in Java, for exactly the reason that pooling is not guaranteed by the JVM because "it starts to get complicated".

**Comment by tjconcept** [comment] 2016-01-08 15:05
Interesting read. I assumed functional components would be "pure render" by default when seeing the syntax and reading the blog post about 0.14.

**Comment by jimfb** [comment] 2016-01-08 17:59
I'm going to close this out, since it was mostly a discussion thread and there is nothing actionable here.

**Closed by jimfb** 2016-01-08 17:59 UTC

**Comment by giltig** [comment] 2016-01-18 08:57
Hi, the action that I think should be here is memoization by default of stateless functions of React.
Here is an example of doing it manually - notice the diffs in the console.log...:
https://jsfiddle.net/giltig/a6ehwonv/28/

**Comment by idrm** [comment] 2016-06-21 12:27
@giltig, Your memoization function will not work as intended when there are multiple instances of the same component with different properties.

**Comment by jooj123** [comment] 2016-08-20 06:47
Is there any sort of rule of thumb for react being quicker for a component to render with many stateless functions or many classes with shouldComponentUpdate shallow equals. 
Or is it something that needs to be profiled for every use case?

In my case there is many small components that are very small and are constantly mounted and unmounted. 

I assume there will massive perf savings in mounting / unmounting for stateless because there is no lifecycle ?

**Comment by gaearon** [comment] 2016-08-20 09:51
There are currently no special optimizations done for functions, although we might add such optimizations in the future. But for now, they perform exactly as classes.

**Comment by jooj123** [comment] 2016-08-20 13:37
fair enough - after running through parts of the react source, i can see that stateless functions still mount like regular classes

**Comment by giltig** [comment] 2016-08-21 14:22
@idrm Hi, but that's all the point. Memoization works when you give the component the same props which is exactly what we want, so it will only trigger render for components who receives different props thus getting pure rendering for stateless components as well (without shouldComponentUpdate)

**Comment by shishirarora3** [comment] 2016-08-21 14:42
So should we memoize or is it already done in react code?

**Comment by giltig** [comment] 2016-08-21 15:50
There is a library 
https://www.npmjs.com/package/memoization
You can use and just memoize all your stateless components (in export for example)

**Comment by idrm** [comment] 2016-08-27 17:10
@giltig, what I'm saying is that your memoization function (purify) is, essentially, a component instance cache with a bucket size of 1 per "purified" component. I don't see how a memoize approach can become a substitute for shouldComponentUpdate the way React currently works.

**Comment by Recmo** [comment] 2017-02-16 10:36
Here's a simple work-around:

```
function pure(func) {
  class PureComponentWrap extends React.PureComponent {
    render() {
      return func(this.props, this.context)
    }
  }
  return PureComponentWrap
}
```

```
const MyComponent = pure(({msg}, {style}) =>
  <span style={style}>{msg}</span>
)

MyComponent.contextTypes = {
  style: React.PropTypes.string
}
```

Unlike `pure` and `purify` from recompose and memoization, this turns the stateless functional component in a `PureComponent`:

**Comment by jwcone** [comment] 2017-02-19 06:02
@Recmo 

I'm new to React, so I welcome any correction/explanation, but I think you'd want to include a defaultProps assignment in your pure() function:

`PureComponentWrap.defaultProps = func.defaultProps`

Also, as a tangent, is this basically the HOC wrap approach that slorber mentioned, earlier?

**Comment by clayne11** [comment] 2017-03-15 18:22
You shouldn't use `defaultProps` for functional components. You should use the language and use default parameters in the function.

**Comment by Klaasvaak** [comment] 2017-03-23 07:29
Should this do the trick?
```
var Aquarium = ({species}) => (
  <Tank>
    {getFish(species)}
  </Tank>
);
Aquarium.prototype.isPureReactComponent = true;
```

**Comment by mir3z** [comment] 2017-03-24 14:53
To sum up the discussion... The current state is that functional components are always re-rendered even if props are unchanged, right?

How is that different from non-functional components? Correct me if I'm wrong but my understanding is that React does not compare props or state itself unless you provide `shouldComponentUpdate`. On the other hand it compares virtual dom representation to find out what actually have changed.

**Comment by jooj123** [comment] 2017-03-26 23:06
> To sum up the discussion... The current state is that functional components are always re-rendered even if props are unchanged, right?

Correct.

> How is that different from non-functional components?

You can provide a `shouldComponentUpdate` check with these and prevent the diffing algorithm from being run - potentially adding some performance gains.
Both functional and non-functional use the same dom diffing process from my understanding

**Comment by davidworkman9** [comment] 2017-03-29 15:09
>  Should this do the trick?
> 
> ```
> var Aquarium = ({species}) => (
>   <Tank>
>     {getFish(species)}
>   </Tank>
> );
> Aquarium.prototype.isPureReactComponent = true;
> ```

Looks like it doesn't. https://jsfiddle.net/a6ehwonv/91/

**Comment by Klaasvaak** [comment] 2017-03-30 09:29
@davidworkman9 was looking at this code here: https://github.com/facebook/react/blob/v15.4.2/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L70 and thought that it might work. But I guess it doesn't

**Comment by msuperina** [comment] 2017-04-10 08:56
I started working at this small library taht may be helpful in such situation 
https://github.com/msuperina/react-cache
It is definitely just a start as there may be many more optimizations to do.

**Comment by Huxpro** [comment] 2017-06-21 05:48
It's surprising that functional component not `PureComponent` by default...

**Comment by a8568730** [comment] 2017-07-21 08:53
I wrap my functional components with [Recompose.pure](https://github.com/acdlite/recompose/blob/master/docs/API.md#pure).
```
const ExpensiveChild = ({children}) => {
  return(
  <p>Hi {children}</p>
)};

const PureChild = Recompose.pure(ExpensiveChild)
```
[Codepen](https://codepen.io/a8568730/pen/vZoMjd?editors=1011)

**Comment by felquis** [comment] 2017-07-31 12:49
I improved @davidworkman9's example https://github.com/facebook/react/issues/5677#issuecomment-290120634 ... here -> https://jsfiddle.net/tynt7te9/ and updated to 15.6.1

I realized the best thing to do is to use:
```js
class PureComponent extends React.PureComponent {
  render () {
    console.count('PureComponent')
    return <div>React.PureComponent: {this.props.render}</div>
  }
 
  shouldComponentUpdate: false
}
```

https://jsfiddle.net/tynt7te9/1/ pretty cool

**Comment by danny-andrews** [comment] 2017-09-27 21:11
> It's surprising that functional component not PureComponent by default...

Although it's somewhat counter-intuitive, I think it actually makes sense that functional components are not `PureComponent` by default. The only guarantee (correct me if I'm wrong) React has with functional components that it doesn't have with class-based is that they don't have any internal state. People could still be mutating their props in the wild and relying on their components to re-render, making this a breaking change. (I agree, however, that there should be some way to opt-in to this behavior in the interim.)

**Comment by pravdomil** [comment] 2017-10-17 18:49
what about first step to get some optimization on StatelessComponents? with empty props check?
```js
shouldComponentUpdate(nextProps, nextState) {
    for(let key in nextProps) {
        if(nextProps.hasOwnProperty(key)) {
            return true;
        }
    }
    
    for(let key in this.props) {
        if(this.props.hasOwnProperty(key)) {
            return true;
        }
    }
    
    return false;
}
```

**Comment by mrchief** [comment] 2018-04-13 01:32
`Recompose.pure` is simply a wrapper around React's `Component` and `shallowEqual`. Wondering what's the benefit of using that vs just extending  `Component` (and avoid packing extra pounds).

**Comment by danny-andrews** [comment] 2018-07-13 23:03
> My perf benchmarks have found string compares to sometimes be quite slow (just doing string-compares of the prop-names with pre-defined values that we need to handle specially, and that isn't even arbitrarily long data compares).

@jimfb Can you share this benchmark? Maybe things have changed since 2015, but it appears string comparison is quite fast, and the most JS implementations use string interning. https://stackoverflow.com/questions/5276915/do-common-javascript-implementations-use-string-interning

**Comment by skipjack** [comment] 2019-01-11 07:43
For anyone who's still stumbling on this, `React.memo` was released recently which is an easy built-in way to create a pure, stateless component:

https://reactjs.org/docs/react-api.html#reactmemo

**Comment by mrchief** [comment] 2019-01-11 20:19
Better than memo, what you're looking for is React [hooks](https://reactjs.org/docs/hooks-intro.html)

**Comment by mqklin** [comment] 2019-02-07 11:15
@mrchief you can't use Hooks to solve this problem

**Comment by mrchief** [comment] 2019-02-07 20:37
@mqklin Why do you say that? I'm going on based on the OP, maybe I missed something down the thread?

**Comment by mqklin** [comment] 2019-02-08 03:38
Sorry, I had to explain.
Hooks can't cancel update like `memo` can. You can't use Hooks to control render. Can you provide an example?
For `memo` it's simple:
```
export default memo(YourFunctionalComponent);
```

**Comment by mrchief** [comment] 2019-02-08 21:08
> Hooks can't cancel update like `memo` can. You can't use Hooks to control render. Can you provide an example?

Sure you can. In fact, hooks can go beyond `React.Memo` in some use-cases. `React.Memo` avoids (or cancels as you call it) updates by doing a "shallow" compare of the props. In that sense, it'll fail to prevent the update if you use deep objects or objects that have function refs. Hooks can help you in those cases as well. 

First of all, if you have shallow components, the simple `useState` hook can help you avoid re-renders.

Secondly, if you have nested parent/child structure and you want to avoid child re-renders on parent update, there is [`useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo) which lets you memoize the renders:

```
const yourComponent = useMemo(() => <YourFunctionalComponent a={a} b={b}), [a, b]);
```

This is equivalent to `shouldComponentUpdate` where your component will only render if `a` or `b` has changed (or whatever props you pass in the 2nd argument array).

Then there's [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback) hook that lets you keep the same function ref so SCU works.

Finally there's [`useReducer`](https://reactjs.org/docs/hooks-reference.html#usereducer) hook that let's you deal with deep objects.

You can find all of this info in the [FAQs](https://reactjs.org/docs/hooks-faq.html); specifically in [How do I implement shouldComponentUpdate?](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-shouldcomponentupdate) and [Are Hooks slow because of creating functions in render?](https://reactjs.org/docs/hooks-faq.html#are-hooks-slow-because-of-creating-functions-in-render).

I'm not saying no one should use `React.memo` (as `useMemo` and hooks in general have some constraints where `React.memo` might be a better choice) rather trying to highlight the fact that we now have more options and choices in our toolbelt.
