### ISSUE TITLE
onLoad not working on <svg /> tags

### ISSUE THREAD

**Issue by zabojad** [facebook/react#9607] opened 2017-05-04 21:00 UTC
It seems that the `onLoad` attribute doesn't work on `<svg>` tags as it does on `<img />` tags...

Could you add support for `onLoad` on `<svg />` ?

**Comment by Flaque** [comment] 2017-05-05 02:11
@zabojad How are you calling onLoad?

When I try:

```
class App extends Component {
  render() {
    return (
      <div className="App">
        <img onLoad={console.log("img loaded")} src="http://i.imgur.com/pU14Lav.jpg"/>

        <svg width="100px" height="100px" onLoad={console.log("svg loaded")}/>
      </div>
    );
  }
}
```

I get "svg loaded" and "img loaded" in my console.

**Comment by davezuko** [comment] 2017-05-05 17:44
@Flaque you aren't passing functions to `onLoad`, though, you are passing the result of an expression (in this case `undefined`) that just immediately calls `console.log`. Unless I'm unaware of some crazy React magic.

That says nothing about whether or not the original issue is reproducible, but I'm confused by your counterexample. =

**Comment by Flaque** [comment] 2017-05-05 18:20
@davezuko GOOD point. I was wrong.


This:
```
class App extends Component {

  sayHello() {
    console.log("Hello")
  }

  render() {
    return (
      <div className="App">
        <svg width="100px" height="100px" onLoad={this.sayHello}/>
      </div>
    );
  }
}
```

Definitely does not print "Hello". Good catch @davezuko.

**Comment by Flaque** [comment] 2017-05-05 18:21
I think this might be a duplicate btw: https://github.com/facebook/react/issues/5626

**Comment by zabojad** [comment] 2017-05-08 07:47
Hi there !

I indeed confirm that I'm passing a function to the `onLoad` attr of `<svg>`. And it indeed looks like a duplicate of #5626...

Thank you for having looked into this!

**Comment by aweary** [comment] 2017-10-04 16:27
Closing as a duplicate of https://github.com/facebook/react/issues/5626, which is already closed 😄

**Closed by aweary** 2017-10-04 16:27 UTC

**Comment by kelvin-homann** [comment] 2019-10-28 13:47
Seems like this Bug still exists, and I don't know why this has been closed when #5626 clearly just had a working PR for <image> tags inside <svg> tags but not the <svg> tag itself.

**Comment by BrunoWinck** [comment] 2019-11-09 14:10
Reached the same conclusion as @kelvin-homann after reading all 3 issues. 
This shouldn't have been closed, it was similar but not a duplicate. ping @aweary

**Comment by emilwikstrom** [comment] 2020-01-02 23:47
I also get this issue. A workaround (that was ok in my case) is to use the "ref" property.

**Comment by Siddhchakra** [comment] 2020-01-23 05:49
> I also get this issue. A workaround (that was ok in my case) is to use the "ref" property.

Hi emilwikstrom,
Could you please share the workaround?

It would be very helpful.

**Comment by emilwikstrom** [comment] 2020-02-11 07:35
> > I also get this issue. A workaround (that was ok in my case) is to use the "ref" property.
> 
> Hi emilwikstrom,
> Could you please share the workaround?
> 
> It would be very helpful.

By using the callback react ref property [https://reactjs.org/docs/refs-and-the-dom.html#callback-refs] you get a dom element handle when the element is loaded.
