### ISSUE TITLE
Error: "Could not find node with id "1804" in commit tree"

### ISSUE THREAD

**Issue by gricard** [facebook/react#17788] opened 2020-01-06 13:33 UTC
Describe what you were doing when the bug occurred:
1. Opened profiler
2. Recorded session
3. Clicked "Ranked" button

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.3.0-3e0967783

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159833
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159779)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:160302)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:322998)
    at ii (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59363)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:107431)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99973)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99898)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:96672)

Component stack: in Sl
    in div
    in div
    in div
    in vo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Qi
    in Ve
    in nn
    in Da
    in Yc

**Comment by bvaughn** [comment] 2020-01-06 17:23
Duplicate of #16446, hopefully fixed via #17771 - but has not yet gone through the Chrome review process, so the fix isn't live yet.

**Closed by bvaughn** 2020-01-06 17:23 UTC
Labels: Component: Developer Tools, Resolution: Duplicate, Type: Bug
