### ISSUE TITLE
*bug* style undefined in setValueForStyles

### ISSUE THREAD

**Issue by mackersD** [facebook/react#9970] opened 2017-06-14 23:34 UTC
It appears that it is possible to have the style property on node undefined in the setValueForStyles method in CSSPropertyOperations.js (using v15.5.4)

https://github.com/facebook/react/blob/v15.5.4/src/renderers/dom/shared/CSSPropertyOperations.js#L220

It is unknown how it was able to get into this state, but here is the stack trace:

TypeError: style is undefined
  at style(~/react-dom/lib/CSSPropertyOperations.js:190:0)
  at CSSPropertyOperations(~/react-dom/lib/ReactDOMComponent.js:880:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:514:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:697:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:516:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:697:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:516:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:697:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:516:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:697:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:516:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:697:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:516:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:697:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:516:0)
  at internalInstance(~/react-dom/lib/ReactReconciler.js:46:0)
  at ReactReconciler(~/react-dom/lib/ReactCompositeComponent.js:371:0)

**Comment by mackersD** [comment] 2017-06-14 23:36
This occured on Firefox Version: 52.0 and Windows 7

**Comment by gaearon** [comment] 2017-06-14 23:43
Can you provide a reproducing case?

**Comment by mackersD** [comment] 2017-06-15 23:03
I unfortunately will have difficulty providing a reproducing case, as I don't have an indication of which of our react components were involved in this update. The stack trace is pretty much what I have from our production error reporting system.

Could it potentially be related to certain types of DOM nodes not having style attributes?

**Comment by gaearon** [comment] 2017-06-16 00:47
It's a bit hard for me to imagine that. If you can reproduce it locally you can set a breakpoint and try to capture some data as you work your way up the call stack.

**Comment by aweary** [comment] 2017-07-05 21:33
I'm going to close this issue out as there hasn't been any recent updates and there's not enough information for us to reproduce the issue and provide assistance.

@mackersD if you end up finding a way to reproduce this, let us know.

**Closed by aweary** 2017-07-05 21:33 UTC
Labels: Need More Information

**Comment by aaronschubert0** [comment] 2017-11-01 16:24
@gaearon @aweary This is happening for me when running tests. I can reproduce it, so hopefully you will be able to also.

Repro steps:
- React & ReactDOM 16.0.0
- Use Jest for testing with the react-native preset `--preset='react-native'`
- Use Enzyme's mount function

Calling mount with the jest react-native preset present will make the style property undefined, without it, it will *not* be undefined. The node is different depending on the preset. Under the react-native preset the node is `Element` whereas without the preset it is `HTMLUnknownElement`

Hopefully that is enough information to start to debug

**Comment by gaearon** [comment] 2017-11-02 00:39
Please file a new issue with a runnable project reproducing this. That said I don't understand why you're using RN preset for ReactDOM and whether that's intended to be supported by Enzyme or not.

**Comment by aaronschubert0** [comment] 2017-11-02 09:28
@gaearon Sure will do. The reason is that we want to use one test command to test both our ReactDOM and RN components using jest in the same project.
