### ISSUE TITLE
Error info removes app

### ISSUE THREAD

**Issue by richburdon** [facebook/react#9995] opened 2017-06-17 16:21 UTC
Feature: it's really hard to track down runtime errors. E.g.

`warning.js?b25d:36 Warning: Stateless function components cannot be given refs (See ref "wrappedInstance" in StatelessComponent created by Apollo(Component)). Attempts to access this ref will fail.`

None of my code is in the stacktrace (swallowed by React)

**Comment by aweary** [comment] 2017-06-19 14:08
Hey, @richburdon! Thanks for your input, we agree that the warning itself wasn't as descriptive as it could be. Note that it is just a warning, so there is no actual stack trace available (it's just a `console.error` call), but thankfully React 16 does implement better error reporting! It will even include the render stack.

[Here's an example](https://jsfiddle.net/oL9q399e/) that logs this warning. Check out the console to see that it is now including the render stack, making it easier to trace the error.

Since this issue is already resolved in master I'm going to close this, but we're always open to hearing feedback about how we can make error messages better.

**Closed by aweary** 2017-06-19 14:08 UTC

**Comment by gaearon** [comment] 2017-06-19 14:41
(Note we don't recommend using React 16 at the time.)

**Comment by gaearon** [comment] 2017-06-19 14:44
Also, React 15 also provides this information:

>in StatelessComponent created by Apollo(Component)

**The fact that `StatelessComponent` and `Component` appear in the trace instead of real component names means that your build is probably misconfigured.**

If you could share a minimal project reproducing this I could take a look at why this is happening.

**Comment by gaearon** [comment] 2017-06-19 14:46
Here is an example using React 15 (current version) that includes component names in the warning:
https://jsfiddle.net/d1eLnzsm/

>Warning: Stateless function components cannot be given refs (See ref "foo" **in Greeting created by App**). Attempts to access this ref will fail.
