### ISSUE TITLE
Error: "Could not find commit data for root "1" and commit 6" - ReactDevTools

### ISSUE THREAD

**Issue by aravindballa** [facebook/react#16818] opened 2019-09-18 11:22 UTC
React Dev Tools - Profiler
Describe what you were doing when the bug occurred:
Was debugging in Storybook
1. Changed the value in dropdown from WrapStory to Root

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.6-a39d9c3

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:16722)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:293893)
    at Al (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:294128)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55891)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62940)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99536)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84256)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81286)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25364
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)

Component stack: in Al
    in div
    in div
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by threepointone** [comment] 2019-09-18 11:56
Closing as a duplicate of https://github.com/facebook/react/issues/16506 cc @bvaughn

**Closed by threepointone** 2019-09-18 11:56 UTC
Labels: Component: Developer Tools

**Comment by bvaughn** [comment] 2019-09-18 15:59
@aravindballa: A few questions:

* Do you see any warnings in your console prior to this? e.g. duplicate key warning
* How reliably can you repro this crash?
* Any chance I could see the code or app to repro it myself?

**Comment by aravindballa** [comment] 2019-09-19 07:20
I don't remember any errors prior to this. There was one warning though - `Warning: componentWillReceiveProps has been renamed, and is not recommended for use.`

The crash occurs when I am on the `Ranked` tab, selecting the first flame, and changing from `WrapStory` to `Root`.

It is on a private repo so can't really show you any code.

I wish I could be of more help here.
Love your work ✌️

**Comment by bvaughn** [comment] 2019-09-19 15:44
@aravindballa Thanks for the added info. Can you repro the crash consistently though? If so, any chance I could see the _app_ (if not the source code) so I could do a little debugging?
