### ISSUE TITLE
After the introduction of external pages by dangerouslySetInnerHTML, JS fails

### ISSUE THREAD

**Issue by vvlong2008** [facebook/react#11562] opened 2017-11-15 09:26 UTC
After the introduction of external pages by dangerouslySetInnerHTML, JS fails

**Comment by M-ZubairAhmed** [comment] 2017-11-15 09:54
Hi could you please provide with more detail and ability to reproduce this error

**Comment by gaearon** [comment] 2017-11-18 19:32
Closing as it's not clear what the problem is, and there are no details.

**Closed by gaearon** 2017-11-18 19:32 UTC
