### ISSUE TITLE
Uncaught TypeError: Cannot read property 'expirationTime' of undefined

### ISSUE THREAD

**Issue by JDansercoer** [facebook/react#14767] opened 2019-02-06 14:43 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

App crashes

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

This is currently my only component, copied from the docs

```
import React, { useState, useEffect } from 'react';

function Example() {
  const [count, setCount] = useState(0);

  // Similar to componentDidMount and componentDidUpdate:
  useEffect(() => {
    // Update the document title using the browser API
    document.title = `You clicked ${count} times`;
  });

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}

export default Example;
```

However, my page crashes, and I get the following error

```
Uncaught TypeError: Cannot read property 'expirationTime' of undefined
    at processUpdateQueue (react-dom.development.js:15860)
    at mountClassInstance (react-dom.development.js:11353)
    at mountIndeterminateComponent (react-dom.development.js:14701)
    at beginWork (react-dom.development.js:15194)
    at performUnitOfWork (react-dom.development.js:18780)
    at workLoop (react-dom.development.js:18820)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at replayUnitOfWork (react-dom.development.js:18052)
```

Unfortunately, I cannot reproduce it in codesandbox, so not sure what exactly I might be doing wrong?

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.0 (React & ReactDOM)

**Comment by bvaughn** [comment] 2019-02-06 15:13
I am also not able to reproduce this in Code Sandbox nor in a create-react-app, so I suspect your package versions maybe aren't what you think they are? Can you delete `node_modules` and re-install?

**Comment by bvaughn** [comment] 2019-02-06 17:00
I am going to close this issue for now since I'm unable to reproduce it. I'll re-open if further discussion provides a repro 👍

**Closed by bvaughn** 2019-02-06 17:00 UTC

**Comment by JDansercoer** [comment] 2019-02-06 17:47
Yes, was about to close this as well, since I found the issue.

For further reference or people stumbling upon this, update your `react-hot-loader`.

Version `4.3.6` wasn't to fond of hooks apparently!

**Comment by ha404** [comment] 2019-03-26 21:16
Apparently `react-hot-loader`'s broken up to `4.5.2` as well, `4.8` worked 👍

**Comment by Ai01** [comment] 2019-06-19 07:58
![image](https://user-images.githubusercontent.com/18245929/59747033-a8775800-92aa-11e9-8394-692e3c342127.png)
in fact.this error because the `update` is `undefined` in react-dom.development.js. Someone find
the solution for this question?

**Comment by himynameisdave** [comment] 2019-06-19 21:20
I am seeing this issue and can reliably reproduce. My code is extremely similar to @JDansercoer's original post above ☝️  in that it's a function component which uses `useState` and `useEffect`. Updated all my dependencies (including the suggested  `react-hot-loader` update suggested above) but nothing has resolved it.

**Versions**
- `react@16.8.6`
- `react-dom@16.8.6`
- `react-hot-loader@4.11.1`
- `webpack@4.34.0`
- `webpack-dev-server@3.7.2`

Seeing the issue when running in `Chrome 75.0.3770.100` on MacOS `10.14.5`.


---

Still exploring the issue and will report back here if I find anymore details that would be helpful.

**Comment by bvaughn** [comment] 2019-06-19 21:27
Share an actual (runnable) repro?

**Comment by himynameisdave** [comment] 2019-06-19 22:59
@bvaughn so I've resolved the issue by using [this patched version of `react-dom`](https://github.com/hot-loader/react-dom). I guess Hooks aren't really well supported by `react-hot-loader` (?) so this gets us around the issue.

In any case this isn't an problem with `react` so this issue needn't be reopened here. 👍

**Comment by gsaandy** [comment] 2019-06-28 06:59
I'm getting the same issue with https://docz.site and create react app 2
