### ISSUE TITLE
Devtools : highlight box is shown too small.

### ISSUE THREAD

**Issue by soulcactus** [facebook/react#17432] opened 2019-11-22 10:43 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
When Chrome devtools is highlighting highlight box is shown too small.

![image](https://user-images.githubusercontent.com/44562005/69419027-185ca380-0d5f-11ea-8284-8004147dc713.png)

**What is the expected behavior?**
Highlight box is shown actual template size.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome 78.0.3904.97
React Developer Tools 4.2.0

**Comment by bvaughn** [comment] 2019-11-26 19:09
Looks kind of like the highlight boxes are just smaller, but with the right relative sizes. Are you zoomed in or something? What's the repro steps on this issue? It doesn't repro for me on any site I've seen.

**Comment by soulcactus** [comment] 2019-11-28 04:33
No I didn't zoom in. Please consider visit my website. https://everycode.store/

**Comment by bvaughn** [comment] 2020-05-19 21:27
Interesting to note that the overlay measurements used to highlight the selected element in the page seems to work fine, but the trace updates measurements are broken.

**Comment by bvaughn** [comment] 2020-05-19 23:58
I think this is being caused by the `HTMLCanvasElement` we're drawing the trace highlights into. The dimensions we're using are the same, but the canvas is rendering them weirdly. Maybe it's a DPI issue.

**Comment by soulcactus** [comment] 2020-05-21 03:42
Oh, I see :) Thank  you for your answer!

**Comment by bvaughn** [comment] 2020-05-21 15:31
Not really an answer yet 😅 Still something I'm looking into, but got distracted by some other higher pri issues. I'm planning on poking at it some more today.

**Comment by bvaughn** [comment] 2020-05-21 15:48
I don't understand what's different about your website that this happens, when the highlights seem to work okay on other sites. Do you have any ideas?

**Comment by bvaughn** [comment] 2020-05-21 16:19
Fixed with #18973

**Closed** 2020-05-21 17:04 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
