### ISSUE TITLE
Error: "Could not find commit data for root "44" and commit 4"

### ISSUE THREAD

**Issue by phamwon** [facebook/react#16414] opened 2019-08-16 08:57 UTC
---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.2-2bcc6c6

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:16552)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:292537)
    at ml (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:292772)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)

Component stack: in ml
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ua
    in le
    in ve
    in ko
    in Fl

**Comment by threepointone** [comment] 2019-08-16 09:33
Cc @bvaughn

**Comment by bvaughn** [comment] 2019-08-16 15:08
Some info on how to repro this would be helpful. A callstack by itself is hard to work with.

**Comment by bvaughn** [comment] 2019-08-18 15:43
Possible duplicate of #16441, which was fixed via https://github.com/bvaughn/react-devtools-experimental/commit/4697f5b37967b85b2c844044aeebb5b1a740875d

If you're still able to reproduce this bug after the 4.0.4 update is installed, please re-open with additional repro info! 😄

**Closed by bvaughn** 2019-08-18 15:43 UTC
Labels: Component: Developer Tools, Type: Bug
