### ISSUE TITLE
Bug: react-hooks/exhaustive-deps - Using a function passed through props in useCallback causes false positive

### ISSUE THREAD

**Issue by Cnoor0171** [facebook/react#25002] opened 2022-07-29 04:41 UTC
When a function passed through props is used inside `useCallback`, the `react-hooks/exhaustive-deps` eslint rule give a false positive.

Using a value on the props object or reference the function doesn't generate a warning. Only when the function is called. See example below.

React version: 17.0.1
eslint-plugin-react-hooks: 4.6.0

## Steps To Reproduce

1. The following code causes a linting error:
```tsx
import React, { useCallback } from 'react';

interface TestComponent {
    value: number;
    testFunc: () => void;
}

export const TestComponent: React.FC<TestComponent> = (props) => {
    const onClick1 = useCallback(() => {
        props.testFunc();
    }, [props.testFunc]);  // Error here

    const onClick2 = useCallback(() => {
        console.log(props.value);
    }, [props.value]);  // No error here

    const onClick3 = useCallback(() => {
        console.log(props.testFunc);
    }, [props.testFunc]);  // No error here
    
    return <div>
        <div onClick={onClick1}></div>
        <div onClick={onClick2}></div>
        <div onClick={onClick3}></div>
    </div>
};
```

Link to code example:

## The current behavior
eslint produces an error
```
React Hook useCallback has a missing dependency: 'props'. Either include it or remove the dependency array. However, 'props' will change when *any* prop changes, so the preferred fix is to destructure the 'props' object outside of the useCallback call and refer to those specific props inside useCallback.
```

## The expected behavior
No error on all 3 cases.

**Comment by eps1lon** [comment] 2022-07-29 06:46
Duplicate of https://github.com/facebook/react/issues/16265

**Closed by eps1lon** 2022-07-29 06:46 UTC
Labels: Status: Unconfirmed
