### ISSUE TITLE
Bug: 通过脚手架创建的项目 编译不报错 运行时依赖报错

### ISSUE THREAD

**Issue by DoFelix** [facebook/react#20116] opened 2020-10-28 10:58 UTC
React version:

## Steps To Reproduce

1.
2.

Link to code example:

## The expected behavior
![image](https://user-images.githubusercontent.com/48934944/97427495-981bc680-194f-11eb-9120-c039fcd39725.png)

**Comment by bvaughn** [comment] 2020-10-28 13:35
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-11-07 14:38
Closing this issue due to lack of repro info or issue updates. We can re-open if updates come in.

**Closed by bvaughn** 2020-11-07 14:38 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed, Type: Bug
