### ISSUE TITLE
Version 4 removed files location

### ISSUE THREAD

**Issue by HugoSnow** [facebook/react#16557] opened 2019-08-23 15:35 UTC
**This technically is a _feature_, a missing one from version 3**.

On version 3 you could visualize files locations which was key in finding bugs, me and my team are currently struggling due to this removed feature on version 4.

You should fix this ASAP as it costs a lot of time now.

**Comment by bvaughn** [comment] 2019-08-23 17:47
Duplicate of #16497

**Closed by bvaughn** 2019-08-23 17:47 UTC
