### ISSUE TITLE
nbsp renders differently in production

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/react#8336] opened 2016-11-17 18:56 UTC
I am using `{'\u00a0'}` in my render method like so:

```
var Hello = React.createClass({
  render: function() {
    return <div><input/>{'\u00a0'}{name}</div>;
  }
});
```

It renders as expected in dev mode. But in production it renders with a strange A. See attacked images.

This is Dev Mode:
![070](https://cloud.githubusercontent.com/assets/123349/20403075/35063226-acb4-11e6-96f6-8f484ffaad1c.png)

This is Prod Mode (notice the strange A):
![071](https://cloud.githubusercontent.com/assets/123349/20403076/3506fde6-acb4-11e6-8301-2b569afb22ea.png)

I am using React 15.3.2.

**Comment by StokeMasterJack** [comment] 2016-11-17 19:47
I have narrowed the problem down a bit. When I build with this option set:

`devtool: 'eval-source-map',                          //dev-mode`

it renders fine. But when I render instead with this:

`devtool: 'cheap-module-source-map',         //prod-mode`

it adds the extra funky A character.

Does this mean this is a web pack bug? I have to say it's sometimes hard to determine where React ends and web pack starts.

**Comment by Aweary** [comment] 2016-11-17 19:51
> Does this mean this is a web pack bug? 

Can you reproduce the issue without React? If changing `devtool` is what causes the issue then it's likely a Webpack issue, but you can always verify by creating a small bundle with plain JavaScript files and see if occurs there as well.

**Comment by StokeMasterJack** [comment] 2016-11-17 23:30
Looks like someone reported the same issue for webpack:
https://github.com/webpack/compression-webpack-plugin/issues/20

**Comment by zpao** [comment] 2016-11-18 16:52
Looks like this isn't a React issue, so closing out. Feel free to reopen if I'm wrong.

**Closed by zpao** 2016-11-18 16:52 UTC

**Comment by StokeMasterJack** [comment] 2016-11-18 17:05
Yes. I agree. Though I never quite solved it (on the webpack side). The bottom line is that webpack was spitting out something different in dev mode then it was in prod mode. I ended up fixing the issue by adding charset=”utf-8" to my script tag:

```
<script 
  type=”text/javascript” 
  src=”/build/bundle.js” 
  charset=”utf-8">
</script>
```

Also, wrote a [blog post](https://medium.com/@daveford/webpack-character-encoding-5c654e5cb037#.47we7xm45) about it.

**Comment by vijayst** [comment] 2016-12-12 08:40
@StokeMasterJack I did not get lucky with the charset="utf-8" fix. Webpack still spits the A. Thanks anyway.
