### ISSUE TITLE
The `allowScriptAccess` attribute is not supported

### ISSUE THREAD

**Issue by Lanfei** [facebook/react#6491] opened 2016-04-12 03:05 UTC
There is a scene, I wanted to put a flash in my page:

```jsx
<embed src={this.state.src} wmode="opaque" allowScriptAccess="always" allowFullScreen/>
```

But the `allowScriptAccess` attribute is missing.

I have tried another way:

```jsx
<object data={this.state.src} type="application/x-shockwave-flash">
	<param name="movie" value={this.state.src}/>
	<param name="wmode" value="opaque"/>
	<param name="allowfullscreen" value="true"/>
	<param name="allowscriptaccess" value="always"/>
</object>
```

But when i changed the `src` state, though element's attributes are changed, the flash didn't really change with it.

**Comment by syranide** [comment] 2016-04-12 08:22
@Lanfei You can't update parameters for an already instantiated flash, you need to recreate it. I.e. give it a key equal to src, and perhaps other arguments.

**Comment by Lanfei** [comment] 2016-04-14 08:01
@syranide 
Thank you for your reply, I was aware of that, but how to recreate a HTML element in react?

**Comment by satya164** [comment] 2016-04-14 09:40
@Lanfei Give it a different key to recreate it. For example, if you want to re-create when you change the src attribute, give the src as the key.

**Comment by jimfb** [comment] 2016-04-14 16:13
Thanks @syranide and @satya164!

I'm going to close this out to take it off our radar, since it appears we've identified the root cause and it's not React's fault.  Flash does not support updating parameters on an already instantiated flash.  Feel free to continue the discussion on this thread.

**Closed by jimfb** 2016-04-14 16:13 UTC

**Comment by Lanfei** [comment] 2016-04-16 07:15
I resolved this problem by giving a different `key`.
Thank you all, @syranide @satya164 @jimfb .
