### ISSUE TITLE
Bug: Cannot read property 'isCollapsed' of undefined/Some Components Missing in DevTools/Blank tab

### ISSUE THREAD

**Issue by abrown945** [facebook/react#19332] opened 2020-07-13 14:40 UTC
I cannot view all of my components in the Components tab. Sometimes none. It has been occurring all morning and I do not know how to rectify this.

I cannot search for the components by name either. It is not there.

When I was attempting to highlight a component to see its props value, I got the below message after clicking on it to see if that would help as nothing was showing.

![image](https://user-images.githubusercontent.com/23192489/87317255-c25a8d00-c4f4-11ea-96cb-b7dbab9def85.png)

React version:

## Steps To Reproduce

1. Start React App.
2. Open Dev Tools.
3. Go on Components tab.
4. Click on Component that is not displayed in dev tools Component tab.
5. Error message from above.

Same steps for a blank Component tab. Unfortunately, restarting the app does not seem to rectify the issue either. Seems to be an error with the extension itself but I thought I'd try here first.

**Comment by bvaughn** [comment] 2020-07-13 15:08
Can you share a repro (e.g. the project you're trying to use that causes React DevTools to error)? I haven't seen this behavior before, or heard reports of it.

**Comment by abrown945** [comment] 2020-07-13 15:10
I can't share the repo as its my work repo. There was an error like this in the past but it was archived because the poster did not provide steps to reproduce

**Comment by abrown945** [comment] 2020-07-13 15:11
I'll see if this happens with another react project in case its a versioning thing with my dev tools

**Comment by bvaughn** [comment] 2020-07-13 15:13
Hm. Yeah it's hard for us to do much without a repro. Could you try creating a reduced case by removing things from your local app until you've gotten it as small as you can (while still seeing the error) and then sharing *that* small repro with us via Code Sandbox or something? The cause is often just a small thing.

May also be nice to find out the version of DevTools you've got installed and which browser/version you're using.

**Comment by abrown945** [comment] 2020-07-13 15:13
Unfortunately, it does seem unique to my work repo so I am not sure what has happened. I'll check to see if I have installed any new dependencies. That screenshot is the extent of my error message

**Comment by abrown945** [comment] 2020-07-13 15:14
Will do @bvaughn I am being pulled away for a moment but I will do my best to give you something more to work with within the next couple of hours

**Comment by bvaughn** [comment] 2020-07-13 15:15
Thanks so much!

**Comment by abrown945** [comment] 2020-07-13 15:56
I am still investigating but I am providing the following information in the meantime, I hope this helps

Browser: Chrome

Browser version: Version 83.0.4103.116 (Official Build) (64-bit)

React Dev Tools Version
4.8.1 (7/10/2020)

**Comment by bvaughn** [comment] 2020-07-13 16:08
Gotcha. Nothing too helpful there unfortunately. Same versions as me.

**Comment by gaearon** [comment] 2020-07-13 16:19
@abrown945 For what it's worth, if your work repo is a publicly available product, and the issue reproduces in production, just seeing that page would be helpful too. Not necessarily the source code.

**Comment by abrown945** [comment] 2020-07-13 17:01
@gaearon I'll check to see if it happens in production. Its not public unfortunately but that will help narrow down the issue

I'll also check to see if this happens in other branches

**Comment by abrown945** [comment] 2020-07-13 21:02
@bvaughn and @gaearon I cannot reproduce the issue now and it seems to have resolved itself. I couldn't earlier due to server maintenance of the site.

Thank you for helping me even with the limited perspective I could give. I appreciate your responsiveness and swiftness to aid me regardless of the difficulty on you two! Have a great day!

**Comment by unzico** [comment] 2020-07-14 21:39
Are you using [Suspense](https://reactjs.org/docs/concurrent-mode-suspense.html)? I'm encountering a problem, where all components below Suspense don't show up in the Flamegraph. However, I'm not sure if this is related to Suspense.

**Comment by bvaughn** [comment] 2020-07-14 22:33
@unzico FWIW there is a known issue or two with Suspense in the latest release that I'm working to fix. We'll publish an update shortly. Sorry!

**Comment by bvaughn** [comment] 2020-07-15 14:12
I suspect that #19368 may fix the issues reported here as well.

**Comment by abrown945** [comment] 2020-07-15 15:54
@bvaughn and @unzico we are using Suspense! So I guess that is the root of the issue

**Comment by abrown945** [comment] 2020-07-15 15:56
@bvaughn forgive me if I am misunderstanding but it looks like you linked to a pull request that will resolve the issue. Am I to read this as, when this PR is approved the devtools error will be resolved with an update to my React app?

**Comment by bvaughn** [comment] 2020-07-15 16:23
I think the next DevTools release (sometime today) should resolve your issue without any updates or changes to your app.

**Comment by bvaughn** [comment] 2020-07-15 16:26
Should be fixed by #19373 

New release will go out shortly

**Closed by bvaughn** 2020-07-15 16:26 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information

**Comment by abrown945** [comment] 2020-07-15 17:13
Thank you for the update and I appreciate the help!
