### ISSUE TITLE
DevTools profiler: Error: "Cannot read property 'concat' of undefined"

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#18934] opened 2020-05-16 06:33 UTC
Describe what you were doing when the bug occurred:
1. Loaded page.
2. Fast Refreshed.
3. Started profiler.
4. Stopped profiler. Crash.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162638)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161628)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:164582)
    at ec (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:339280)
    at ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59620)
    at nl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:69923)
    at Ll (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:110996)
    at qc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102381)
    at Hc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102306)
    at Vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102171)

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by souki1990** [comment] 2020-05-17 22:45
I have tried to reproduce several times but no profiler crashing so far on my side

**Comment by bvaughn** [comment] 2020-05-18 20:41
4.6.0-6cceaeb67 was built back in March. I've added a few Profiler bug fixes recently that might potentially address this. If you can repro the issue (#18934) would you be willing to try it with an updated build (from master)?

https://github.com/facebook/react/tree/master/packages/react-devtools-extensions#build-steps

**Comment by bvaughn** [comment] 2020-05-19 18:14
By the way, I released an update yesterday (4.7.0) to the Chrome/Firefox/Edge stores.

**Comment by bvaughn** [comment] 2020-05-19 18:19
I assume this error is in [`CommitTreeBuilder`](https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/devtools/views/Profiler/CommitTreeBuilder.js) because it's the only place in Profiler code that calls `.concat()` that I see:
https://github.com/facebook/react/blob/5aa967b69b255ede89c03dda8cd617b61c492cdb/packages/react-devtools-shared/src/devtools/views/Profiler/CommitTreeBuilder.js#L240-L241

In particular, the problem would happen if `getClonedNode` failed to find a matching node for the parent:
https://github.com/facebook/react/blob/5aa967b69b255ede89c03dda8cd617b61c492cdb/packages/react-devtools-shared/src/devtools/views/Profiler/CommitTreeBuilder.js#L154-L162

This isn't an expected case, so I'm not sure what went wrong here. Being able to repro this woudl be very helpful.

**Comment by bvaughn** [comment] 2020-05-19 21:17
Looks like this is a duplicate of #18256 so I'm going to close this one.

**Closed by bvaughn** 2020-05-19 21:17 UTC
Labels: Component: Developer Tools
