### ISSUE TITLE
Bug: Cannot useState in a reusable component library.

### ISSUE THREAD

**Issue by anmdsystems** [facebook/react#24941] opened 2022-07-17 04:47 UTC
In a sample typescript react project, 

1. Add test-component-library dependency int package.json =>  
"dependencies": {
    "test-component-library": "git+https://github.com/anmdsystems/test-component-library.git"

2. Add App.tsx =>  return &lt;Button label="Test"&gt; &lt;/Button&gt;

import React from 'react';
import './App.css';
import { Button } from 'test-component-library';

function App() { 
 return <Button label="Test" ></Button>

}

export default App;

3. Run the sample app, console shows the error message

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
printWarning @ react.development.js:209
error @ react.development.js:183
resolveDispatcher @ react.development.js:1592
useState @ react.development.js:1621
Button @ Button.tsx:9
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:209 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
printWarning @ react.development.js:209
error @ react.development.js:183
resolveDispatcher @ react.development.js:1592
useState @ react.development.js:1621
Button @ Button.tsx:9
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1622 Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at Object.useState (react.development.js:1622:1)
    at Button (Button.tsx:9:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)

**Comment by eps1lon** [comment] 2022-07-17 07:46
Your app and component library probably have each a version of React installed. Libraries should declare React in `peerDependencies` and apps should make sure you only have a single version installed (hence the "You might have more than one copy of React in the same app" error).

Duplicate of https://github.com/facebook/react/issues/13991

**Closed** 2022-07-17 07:46 UTC
Labels: Status: Unconfirmed

**Comment by bugfix2020** [comment] 2022-08-10 13:50
I have the same problem how should I deal with it？

> 你的应用程序和组件库可能都安装了一个版本的 React。库应该在其中声明 React `peerDependencies`，应用程序应该确保您只安装了一个版本（因此“您可能在同一个应用程序中拥有多个 React 副本”错误）。
> 
> #13991的副本[](https://github.com/facebook/react/issues/13991)

I have the same problem how should I deal with it?

**Comment by bugfix2020** [comment] 2022-08-10 13:59
> 你的应用程序和组件库可能都安装了一个你的 React。库应该在其中声明 React `peerDependencies`，应用程序确保安装一个版本（因此“可能在同一个应用程序中拥有多个 React 副本”错误）。
> 
> #13991的副本[](https://github.com/facebook/react/issues/13991)

it's working now ! thx~
