### ISSUE TITLE
Key property on SVG elements causes warning

### ISSUE THREAD

**Issue by skuridin** [facebook/react#9011] opened 2017-02-15 19:38 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I use `key` property on SVG elements (line, text, circle), I see `Warning: line: 'key' is not a prop`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Can't reproduce it in JSFiddle ([tried](https://jsfiddle.net/reactjs/69z2wepo/)), but can in a fresh project created with `create-react-app`

**What is the expected behavior?**

No warnings

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- Project created with `create-react-app`
- React version is `15.4.2`
- MacOS 10.12.3
- Chrome 56.0.2924.87

**Comment by nseptier** [comment] 2017-02-15 19:56
I have the same kind of issue. A piece of code as simple as the following produces the same kind of warning, whether it's with `ref` or `key` :
```
render() {
  return (
    <input ref={node => this.input = node} />
  )
}
```

**Comment by gaearon** [comment] 2017-02-15 20:18
@nseptier Can you provide the full runnable example code rather than a single method?

**Comment by gaearon** [comment] 2017-02-15 20:18
@skuridin I’d appreciate if you could do this too. I understand it's probably simple, but please provide a complete code snippet that reproduces the issue.

**Comment by skuridin** [comment] 2017-02-15 20:42
Can't reproduce it after reinstalling node_modules.

**Comment by abdulhannanali** [comment] 2017-02-15 20:54
I was unable to reproduce it in the jsBin too.

**Comment by gaearon** [comment] 2017-02-15 20:57
Oops, this actually comes from React DevTools update I pushed.
https://github.com/facebook/react-devtools/pull/376

**Comment by gaearon** [comment] 2017-02-15 21:03
Fixed in https://github.com/facebook/react-devtools/pull/517.
I'll upload an update to Chrome extension soon, and it will take an hour or two to get published.
Thanks for reporting!

**Closed by gaearon** 2017-02-15 21:03 UTC
