### ISSUE TITLE
Error: "Could not find commit data for root "1081" and commit 18"

### ISSUE THREAD

**Issue by jackton1** [facebook/react#17543] opened 2019-12-06 21:26 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.1-3816ae7c3

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:163226)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:332702)
    at uc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:332919)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59907)
    at el (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:68139)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:108547)
    at Lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92715)
    at Pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92640)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89544)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:46341

Component stack: in uc
    in div
    in div
    in wo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Li
    in $e
    in dn
    in Ca
    in Pc

**Comment by aweary** [comment] 2019-12-07 16:29
Duplicate of #16446

**Closed by aweary** 2019-12-07 16:29 UTC
