### ISSUE TITLE
How to import react npm compoent in jsx file?

### ISSUE THREAD

**Issue by ihaolin** [facebook/react#4549] opened 2015-08-03 10:37 UTC
Hello, I am freshman of react，I use **gulp** to build web assets，I compile all jsx files with **gulp-react** to js like this:
```javascript
 gulp.src(paths.appJsx)
        .pipe(concat('app.jsx'))
        .pipe(react());
```
But now, I want to use some react component registered in npm，such as **react-iscroll**，I don't know how to introduce it in my jsx file，if I directly add bellow to jsx file't top，it won't work well:
```javascript
// my component jsx file
var React = require('react'),
    ReactIScroll = require('react-iscroll'),
    iScroll = require('iscroll');
``` 
How I import them rightly?

Thanks & Regards.

**Comment by LeezQ** [comment] 2015-08-03 11:04
webpack and bable-loader is is the better choice

**Comment by jimfb** [comment] 2015-08-03 15:59
Questions like this are better addressed on StackOverflow.  We're trying to keep github issues for tracking bugs in React.  This is not a bug in React, so I'm going to close it out.  Feel free to continue the discussion on this thread, or move the conversation to StackOverflow.

**Closed by jimfb** 2015-08-03 15:59 UTC
