### ISSUE TITLE
Bug: StrictMode is causing issue when value is calculated using ref value

### ISSUE THREAD

**Issue by tonai** [facebook/react#28206] opened 2024-02-02 15:48 UTC
When using StrictMode, render and useEffect are wrong when calculating a value based on some ref.
For example with this code:
```ts
function useDiff(items: number[]): boolean {
  const ref = useRef<number[]>(items); // reference to the previous value of items

  let hasDiff = false;
  const prev = ref.current;
  const all = new Set(prev.concat(items));
  all.forEach((name) => {
    if (!prev.includes(name) || items.includes(name)) {
      hasDiff = true;
    }
  });
  ref.current = items;

  useEffect(() => {
    if (hasDiff) {
      console.log("There are some differences !"); // This never gets logged when using StrictMode
    }
  });

  return hasDiff; // this is always false when using StrictMode
}
```

React version: 18.2

## Steps To Reproduce

1. See code sandbox example
2. Click on "Add" button
3. It should display `hasDiff = true` and log `There are some differences !` in the console

Link to code example: https://codesandbox.io/p/sandbox/happy-antonelli-ysr36h?file=%2Fpackage.json%3A13%2C29

## The current behavior

When clicking the "Add" button wrong value is being rendered (`hasDiff = false`), and `console.log` inside `useEffect` is not triggered.

## The expected behavior

Removing `StrictMode` will change the behavior like so:
When clicking the "Add" button `hasDiff = true` is being rendered, and `console.log` inside `useEffect` is triggered.
I expect the code to work the same when using `StrictMode`.

**Comment by bobmakesmagics** [comment] 2024-02-02 16:46
Hi,
This is new user on this repository.
I'd like to contribute this project.
Can I try to fix this issue now?

**Comment by bobmakesmagics** [comment] 2024-02-02 17:23
It seems like the issue might be related to the fact that StrictMode intentionally invokes certain functions twice, including render methods and effects, to help detect side-effects.

In your useDiff custom hook, you are logging 'render' and 'useEffect' directly, and those logs are being affected by StrictMode's double-invocation.

**Comment by tonai** [comment] 2024-02-02 18:17
Yes that's exactly the problem.
For the render I can understand that it is not safe to render something that depends on refs.
Render should only depends on state to be predictible.
But `useEffect` is the only way to switch from declarative code to imperative code and if you look at the logs it is quite strange:
* at startup you have 2 times the "render" log and 2 times the "useEffect" log
* then if you click the "Add" button you have again 2 times the "render", but then only 1 time the "useEffect" log (the one associated with the second render, because we dont have the "There are some differences !" log)

![react-useeffect](https://github.com/facebook/react/assets/5246045/16c733d0-9421-4869-842c-1b891001873d)

Why this behavior ? This is really strange. Should we not have the `useEffect` also run twice ?

**Comment by pwbriggs** [comment] 2024-02-06 06:47
> Can I try to fix this issue now?

@bobmakesmagics Go ahead, no need to ask. 😄 Submit a PR when you have a working patch.

Thanks! ❤️

**Comment by rickhanlonii** [comment] 2024-02-11 19:26
Yeah, StrictMode is finding a legit bug here. If is not safe to read or write refs in render, and StrictMode catches that this is unsafe for you. The reason this is unsafe, is because a component may render more than once before it commits, render and commit are not 1-1. 

As an example of where this hook breaks, consider a component that uses this hook, with a child that suspends in an update. When the hook is rendered, the hook mutates the ref and `hasDiff` is true. Then something below it suspends and this component is never committed, and the effect hasn't fired. When done suspending, we then render again from the suspense boundary re-rendering this hook. The ref is mutated in render again, and `hasDiff` is false. Rendering finishes and commits, and the effect is fired with `hasDiif` is false.

The fix is to refactor this to not read or write to the ref in render.

**Closed by rickhanlonii** 2024-02-11 19:26 UTC
Labels: Status: Unconfirmed

**Comment by tonai** [comment] 2024-02-12 14:37
Thanks @rickhanlonii for the explanations.
I totally agree for the render part, this is not safe to use ref.
But I think this is problematic for the `useEffect` part where you want to write imperative code and have more control over the flow.
Or is there another way to trigger some piece of code after the rendering has been done based on states and refs ?

**Comment by rickhanlonii** [comment] 2024-02-12 15:18
There's no way in react to trigger reactivity based on refs. Refs are, by design, not reactive. In this use case, if you want to show something has changed since the last update in render, you can follow the pattern to [Store Information from Previous Renders](https://react.dev/reference/react/useState#storing-information-from-previous-renders). To fire an effect when it changes, you can use a ref like this:

```js
function useDiff(items) {
  const ref = useRef(items);
  useEffect(() => {
    const prev = ref.current;
    ref.current = items;

    if (hasDiff(prev, items)) {
      console.log("There are some differences !");
    }
  }, [items]);
}
```
