### ISSUE TITLE
CSSTransitionGroup no transition if add and remove to fast

### ISSUE THREAD

**Issue by bitplanets** [facebook/react#2729] opened 2014-12-17 12:20 UTC
# How to reproduce

 - Add item A (opacity 0)
 - While item A is transitioning (ex.: opacity 0.5): remove item A
 - The next tick (or very fast) the item A has opacity = 0;
 
Now the item A disappears completely, no transition.

# What was supposed to:

 - Add item A (opacity 0)
 - While item A is transitioning (ex.: opacity 0.5): remove item A
 - The item should be fading smoothly from 0.5 to 0 opacity

**Comment by Merri** [comment] 2015-01-27 07:44
We recently noticed severe issues with CSSTransitionGroup in Android Chrome. I attempted to make a reduced test case, and to my surprise I found another issue that exists on all browsers, while the original Android Chrome issue didn't trigger (being transitions not triggering almost ever even with a single item).

Now I have issue reproduceable with all browsers. Here is the test case on Codepen: http://codepen.io/Merri/pen/ogwrpg

Everything is fine if you do stuff in a relatively slow pace, but once you start hitting more stuff then browsers begin to either not trigger transitionend event for React, or React fails to notice the event correctly. The end result is that elements remain in DOM when they should no longer exist there.

It depends a lot on browser how easily the issue triggers. IE11 seems to do very well, but you can make it fail if you just keep enter down long enough. Firefox doesn't do as well, but Chrome is worst of all: it is very easy to make it fail even with regular clicking.

If you notice a clear design flaw in what I've made above, please tell me. I can't see any big issue with it. To me it just seems like it is better not to use CSSTransitionGroup at all due to this bugginess that it has with lots of elements as it doesn't have a good fallback if it fails to receive transitionend event.

**Comment by gaearon** [comment] 2015-01-27 09:59
I mentioned it elsewhere but it's worth repeating that [`TimeoutTransitionGroup`](https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx) is much more stable because it doesn't rely on buggy `transitionend` event. (Never mind jQuery dependency, just tweak it to use `react/lib/CSSCore` for `addClass`/`removeClass`). Yes it's a bit of extra hassle to maintain matching durations in CSS and components, but it's worth it for stability.

Hopefully when [this](https://github.com/chenglou/react-state-stream) matures, we'll have a much better transition group.

**Comment by spicyj** [comment] 2015-04-01 21:39
This sounds like a dupe of #1326; merging.

**Closed by spicyj** 2015-04-01 21:39 UTC
Labels: Component: Addons / TransitionGroup
