### ISSUE TITLE
SyntaxError with React and ReactDOMServer imported into express project

### ISSUE THREAD

**Issue by narzantaria** [facebook/react#16669] opened 2019-09-05 17:15 UTC
I installed and imported **react** and **react-dom** into the **express** project. I want to learn how to use React server-side rendering, based on a simple boilerplate.
I have a minimal Express project, where I imported React.
Npm throws: 
> "SyntaxError: Unexpected identifier".

I looked at the docs and a lot of examples on the basis of which I build my own, but for some reason it does not start, even in the simplest configuration. Can someone tell me how to run it properly?
Thanks!

Here is index.js listing (express server starter):
```
const express = require('express');
import React from "react";
import ReactDOMServer from 'react-dom/server';
import App from './components/App';

const app = express();

app.get("/", (req, res) => {
  res.send(`
      <!DOCTYPE html>
      <head>
        <title>Server-side React</title>
      </head>
      <body>
        <div id="root">${ReactDOMServer.renderToString(<App />)}</div>
      </body>
    </html>
  `);
});

app.listen(3000);
```
App.js of React:
```
import React from 'react';

const App = () => {
  return (
    <div>
      <h3>Hello!!!</h3>
    </div>
  );
};

export default App;
```
index.js of React:
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.hydrate(<App />, document.getElementById('root'));
```
Installed dependencies:
react,react-dom,express,body-parser.

**Comment by threepointone** [comment] 2019-09-05 17:46
Could you please make a git repo that reproduces the problem? My guess is that you haven't setup babel to convert jsx, but I can't say without looking at a real project.

**Comment by threepointone** [comment] 2019-09-06 12:37
Closing because there’s no reproducing example here. Happy to reopen if you can provide a runnable example that demonstrates the problem (I still believe the issue is that you need to setup Babel, if that helps)

**Closed by threepointone** 2019-09-06 12:37 UTC
Labels: Resolution: Needs More Information
