### ISSUE TITLE
CSSTransitionGroup does not work appropriately if the className is modified

### ISSUE THREAD

**Issue by jsgoupil** [facebook/react#4804] opened 2015-09-07 03:42 UTC
If the entering element has its `className` modified during a transition, then the "-enter" and "-enter-active" `className` gets deleted. Which will most likely kill the transition then cause problems with the element because of `currentlyTransitioningKeys` will be out of sync. It should keep the added `className`s appropriately.

Example. Click "Add Item" multiple items before the transition ends.

    var ReactCSSTransitionGroup = React.addons.CSSTransitionGroup;
    var c = 1;
    var TodoList = React.createClass({
      getInitialState: function() {
        return {items: ['hello', 'world', 'click', 'me']};
      },
      handleAdd: function() {
          var newItems =
            this.state.items.concat(["ABC" + (c++)]);
        this.setState({items: newItems});
      },
      handleRemove: function(i) {
        var newItems = this.state.items;
        newItems.splice(i, 1);
        this.setState({items: newItems});
      },
      render: function () {
          var r = Math.random();
        var items = this.state.items.map(function(item, i) {
          return (
            <div key={item} onClick={this.handleRemove.bind(this, i)} className={'A'+r}>
              {item}
            </div>
          );
        }.bind(this));

        return (
          <div>
            <button onClick={this.handleAdd}>Add Item</button>
            <ReactCSSTransitionGroup transitionName="section">
              {items}
            </ReactCSSTransitionGroup>
          </div>
        );
      }
    });

**Comment by spicyj** [comment] 2015-09-08 22:07
Dupe of #761. Your best bet is probably to add a wrapping element whose classes don't change.

**Closed by spicyj** 2015-09-08 22:07 UTC
Labels: Component: Addons / TransitionGroup

**Comment by jsgoupil** [comment] 2015-09-08 22:17
That's unfortunate. I was trying to mix this with bootstrap col-md-push-X. Where X is computed.
I wouldn't be able to do this wrapping as I need that specific class name on that element. So, no animation for me :(

**Comment by jsgoupil** [comment] 2015-09-09 16:47
I guess the work around would do to do the wrapping and use -appear class instead of entering.
Just in case would want to use the same thing.
