### ISSUE TITLE
Issue: 'render' is not defined   

### ISSUE THREAD

**Issue by johnson-byjus** [facebook/react#20862] opened 2021-02-23 08:41 UTC
Getting `render not defined error` in the below code. When I changed this to a functional component got 
`componentDidMount not found error.` All react and react-dom are installed version is "^16.8.5"

```
import React, { Component } from 'react';

import { Page, PageBody, PageHeader } from "components/page";
import { Box, BoxHeader, BoxBody } from "components/box";
import Tab from 'modules/core/components/Tab';
import Update from './support/Update'
import Delete from './support/Delete'

class Support extends Component {
    render = () => {
        const tabs = [{
            component: <Update />
        }, {
            component: <Delete />
        }];

        return (
            <div>
                <Box type="default">
                    <BoxBody>
                        <Tab
                            tabs={tabs}
                        />
                    </BoxBody></Box>
            </div>
        );
    }
}

export default Support

```

The weird part is only some people face this issue. (mostly ubuntu users)

**Comment by zeus0123** [comment] 2021-02-23 09:28
Getting arrow function undefined error on using react classes.
 onFeedbackSubmit and handleFeedbackChange both show undefined.
I am using react 16.13.1 and react-dom 16.13.1

```
import { submitTopic } from '../../services/configure';
import { LoaderWrapper } from '../';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faWindowMinimize } from '@fortawesome/free-solid-svg-icons';
import {
  FeedbackTrigger,
  FeedbackBox,
  FeedbackHeader,
  FeedbackHeaderMinimizeIcon,
  FeedbackBody,
  Feedbacktext,
  Submit,
} from './FeedBack.styles';

class Feedback extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      shown: false,
      isSending: false,
      feedbackText: '',
      feedbackSuccessMessage: '',
    };

  }

  onFeedbackSubmit = () => {
    const { feedbackText } = this.state;
    if (feedbackText) {
      this.setState({
        isSending: true,
      });
      submitTopic({
        subject: 'MIO Feedback from Advisor',
        emailBody: feedbackText,
      })
        .then(() => {
          this.setState({
            isSending: false,
            feedbackSuccessMessage: 'Feedback Has Been Submitted Successfully',
          });
          window.setTimeout(() => {
            this.setState({
              shown: false,
            });
          }, 2000);
        })
        .catch(() => {
          this.setState({
            isSending: false,
          });
        });
    }
  };

  handleFeedbackChange = (e) => {
    this.setState({
      feedbackText: e.target.value,
    });
  };

  render() {
    const { isSending, feedbackSuccessMessage } = this.state;
    return (
      <div>
        <FeedbackTrigger
          className="icon dripicons-message"
          onClick={() => this.setState({ shown: !this.state.shown })}
        >
          &nbsp; <span style={{position: 'relative', bottom: '4px'}}>Feedback</span>
        </FeedbackTrigger>

        <FeedbackBox style={{ display: this.state.shown ? 'block' : '' }}>
          <FeedbackHeader
            className="icon dripicons-message"
            onClick={() => this.setState({ shown: !this.state.shown })}
            style={{
              position: 'relative',
              left: '-7%'
            }}
          >
            &nbsp; <div style={{
              position: 'absolute',
              top: '19%',
              left: '51%'
            }}>Feedback</div>
            <FeedbackHeaderMinimizeIcon style={{
              position: 'relative',
              right: '-5%',
              bottom: '5px'
            }}>
              <span>
                <FontAwesomeIcon icon={faWindowMinimize} />
              </span>
            </FeedbackHeaderMinimizeIcon>
          </FeedbackHeader>
          <FeedbackBody>
            <Feedbacktext
              placeholder="Please share your thoughts"
              onChange={this.handleFeedbackChange}
              onFocus={(e) => (e.target.placeholder = '')}
              onBlur={(e) =>
                (e.target.placeholder = 'Please share your thoughts')
              }
            ></Feedbacktext>
            {!isSending && feedbackSuccessMessage}
            <LoaderWrapper isLoading={isSending}>
              <Submit type="button" onClick={() => this.onFeedbackSubmit()}>
                Submit
              </Submit>
            </LoaderWrapper>
          </FeedbackBody>
        </FeedbackBox>
      </div>
    );
  }
}

export default Feedback;
```

**Comment by bvaughn** [comment] 2021-02-23 14:46
Seems like the problem here is likely that either some of your users are using browsers that don't support this syntax _or_ that one of your build/compilation steps are converting it into an invalid syntax. Pretty confident this doesn't have anything to do with React itself.

Either way, this bug report does not have enough info for one of us to reproduce it. (For example you mention an error about `componentDidMount` but that's not even referenced in the small code sample mentioned.)

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by haneenmahd** [comment] 2021-02-26 09:36
You need to bind the functions inside the constructor.
```
this.handleChange = this.handleChange.bind(this);
```

Can you share the browser you use and their versions please?

**Comment by haneenmahd** [comment] 2021-02-26 09:38
> Getting arrow function undefined error on using react classes.
> onFeedbackSubmit and handleFeedbackChange both show undefined.
> I am using react 16.13.1 and react-dom 16.13.1
> 
> ```
> import { submitTopic } from '../../services/configure';
> import { LoaderWrapper } from '../';
> import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
> import { faWindowMinimize } from '@fortawesome/free-solid-svg-icons';
> import {
>   FeedbackTrigger,
>   FeedbackBox,
>   FeedbackHeader,
>   FeedbackHeaderMinimizeIcon,
>   FeedbackBody,
>   Feedbacktext,
>   Submit,
> } from './FeedBack.styles';
> 
> class Feedback extends React.Component {
> 
>   constructor(props) {
>     super(props);
>     this.state = {
>       shown: false,
>       isSending: false,
>       feedbackText: '',
>       feedbackSuccessMessage: '',
>     };
> 
>   }
> 
>   onFeedbackSubmit = () => {
>     const { feedbackText } = this.state;
>     if (feedbackText) {
>       this.setState({
>         isSending: true,
>       });
>       submitTopic({
>         subject: 'MIO Feedback from Advisor',
>         emailBody: feedbackText,
>       })
>         .then(() => {
>           this.setState({
>             isSending: false,
>             feedbackSuccessMessage: 'Feedback Has Been Submitted Successfully',
>           });
>           window.setTimeout(() => {
>             this.setState({
>               shown: false,
>             });
>           }, 2000);
>         })
>         .catch(() => {
>           this.setState({
>             isSending: false,
>           });
>         });
>     }
>   };
> 
>   handleFeedbackChange = (e) => {
>     this.setState({
>       feedbackText: e.target.value,
>     });
>   };
> 
>   render() {
>     const { isSending, feedbackSuccessMessage } = this.state;
>     return (
>       <div>
>         <FeedbackTrigger
>           className="icon dripicons-message"
>           onClick={() => this.setState({ shown: !this.state.shown })}
>         >
>           &nbsp; <span style={{position: 'relative', bottom: '4px'}}>Feedback</span>
>         </FeedbackTrigger>
> 
>         <FeedbackBox style={{ display: this.state.shown ? 'block' : '' }}>
>           <FeedbackHeader
>             className="icon dripicons-message"
>             onClick={() => this.setState({ shown: !this.state.shown })}
>             style={{
>               position: 'relative',
>               left: '-7%'
>             }}
>           >
>             &nbsp; <div style={{
>               position: 'absolute',
>               top: '19%',
>               left: '51%'
>             }}>Feedback</div>
>             <FeedbackHeaderMinimizeIcon style={{
>               position: 'relative',
>               right: '-5%',
>               bottom: '5px'
>             }}>
>               <span>
>                 <FontAwesomeIcon icon={faWindowMinimize} />
>               </span>
>             </FeedbackHeaderMinimizeIcon>
>           </FeedbackHeader>
>           <FeedbackBody>
>             <Feedbacktext
>               placeholder="Please share your thoughts"
>               onChange={this.handleFeedbackChange}
>               onFocus={(e) => (e.target.placeholder = '')}
>               onBlur={(e) =>
>                 (e.target.placeholder = 'Please share your thoughts')
>               }
>             ></Feedbacktext>
>             {!isSending && feedbackSuccessMessage}
>             <LoaderWrapper isLoading={isSending}>
>               <Submit type="button" onClick={() => this.onFeedbackSubmit()}>
>                 Submit
>               </Submit>
>             </LoaderWrapper>
>           </FeedbackBody>
>         </FeedbackBox>
>       </div>
>     );
>   }
> }
> 
> export default Feedback;
> ```

You need to bind the functions inside the constructor.
```
this.handleChange = this.handleChange.bind(this);
```

Can you share the browser you use and their versions please?

**Comment by bvaughn** [comment] 2021-02-26 16:49
I'm going to close this issue due to lack of a repro case.  Does not seem likely to be caused by React.

**Closed by bvaughn** 2021-02-26 16:49 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed

**Comment by haneenmahd** [comment] 2021-02-27 08:51
> I'm going to close this issue due to lack of a repro case. Does not seem likely to be caused by React.

It's not a problem with React.
But, it is a syntax error.
