### ISSUE TITLE
HTML5 number input uncontrolled mode issues when changing defaultValue

### ISSUE THREAD

**Issue by yaycmyk** [facebook/react#7507] opened 2016-08-15 19:53 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Providing a `defaultValue` to an HTML5 number input causes the element to enter into some sort of _semi-controlled_ mode. Changing the `defaultValue` should be a noop after the element has been mounted, but it seems to set a property in the element and break the behavior of the uncontrolled component.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See this fiddle and try to enter `1e8`: http://codepen.io/3lux/pen/yJkWoj

**What is the expected behavior?**

`1e8` should show up in the input box; since some DOM property is being changed when the provided `defaultValue` is changed, I think the DOM is trying to programmatically set the input to an interim value that's not a real number, like `1e` and then wipes it out and resets to an empty string, which is caught in the `onChange` handler and persisted back to the `defaultValue`, effectively losing the input.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Latest React, latest Chrome

**Comment by nhunzaker** [comment] 2016-08-16 02:06
I believe this is the same issue as https://github.com/facebook/react/issues/7253, it happens because defaultValue always gets reassigned on change:

https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/ReactDOMInput.js#L217

Invoked in the handleChange callback for inputs here:

https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/ReactDOMInput.js#L284

![uncontrolled](https://cloud.githubusercontent.com/assets/590904/17685675/41970052-6334-11e6-8e90-f74c569b9889.gif)

**Comment by Aweary** [comment] 2016-08-16 03:31
Yupp, same root cause as #7253. This isn't specific to `defaultValue`, you'd have the same issue if you used `value`. https://jsfiddle.net/Lqgh8v7a/. I'm going to close this, but feel free to subscribe to #7253 for updates on this 👍

**Closed by Aweary** 2016-08-16 03:31 UTC

**Comment by yaycmyk** [comment] 2016-08-16 03:45
Why are you closing it? You just admitted it's a legitimate bug.

**Comment by Aweary** [comment] 2016-08-16 04:00
I'm not closing it because it's not a bug, I'm closing it because it's an issue we're already tracking in #7253. Having multiple issues open for variations of a root issue only serves to fragment discussion (see https://github.com/facebook/react/issues/7297 for another example #7253)

It's not that we're ignoring it, just trying to keep our issues organized 😄 you can subscribe to #7253 to get updates on any progress made.

**Comment by yaycmyk** [comment] 2016-08-16 04:07
Okay, thanks.
