### ISSUE TITLE
Warning: It looks like you're using a minified copy of the development build of React.

### ISSUE THREAD

**Issue by zhoou** [facebook/react#6611] opened 2016-04-25 15:27 UTC
It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

**Comment by gaearon** [comment] 2016-04-25 16:00
Hi!

It’s not entirely clear what you mean by creating this issue. The warning explains the problem, along with the link you quoted. Hopefully this is helpful, but if it isn’t, please describe the problems you had following these instructions in more detail.

If you think the warning is being fired incorrectly and you have a good reason to minify React without envifying it, please let us know in https://github.com/facebook/react/issues/6479.

I’m closing because the issue is vague and not actionable in its current form. Cheers!

**Closed by gaearon** 2016-04-25 16:00 UTC
