### ISSUE TITLE
Change warning for <select value={null} /> to suggest an empty array rather than empty string

### ISSUE THREAD

**Issue by ryb73** [facebook/react#9038] opened 2017-02-21 21:49 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Setting the value to `""` on a `<select>` with `size` > 3 does not deselect the currently selected option.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
JSFiddle: https://jsfiddle.net/rpbiwer/55jzq7dq/2/

**What is the expected behavior?**
After rendering a `<select>` with the value set to an empty string, I expect there to be no selection in the rendered select box. Mainly this expectation comes from this React warning when I use `null` instead of `""`:
```
Warning: `value` prop on `select` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
```

In the fiddle, if I change this line:
```javascript
let newSelection = nowHidden ? "" : this.state.selected;
```
to
```javascript
let newSelection = nowHidden ? undefined : this.state.selected;
```
I get the behavior I expect.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I've gotten this with React 15.3.0 and whichever version is used in the fiddle. I don't know if it worked in previous versions.
This was tested using Chrome 56 on OS X.

**Comment by syranide** [comment] 2017-02-22 08:13
"In my opinion" this is/was intended behavior. Empty string is a valid option value. Also, at least earlier, not all browsers support having no option selected which means that for these browsers the controlled input would be broken as it would have an option selected visually for the user but the value would still be `null`. But if that has changed and all browsers now do support it, then having a way to set "no value" would be a good idea yes.

**Comment by ryb73** [comment] 2017-02-22 20:12
@syranide thanks for pointing that out. I wasn't aware of how the browsers handle this sort of thing. If what you say is still true, I'd change the request in this issue from "make `""` work how I want it to" to "revise the misleading 'Consider using the empty string' error message".

**Comment by gaearon** [comment] 2017-10-04 16:46
I think the correct fix here is to emit a different warning for `select` with `props.multiple` set to `true`. In this case we want to suggest an empty array rather than an empty string.

**Comment by Hendeca** [comment] 2017-10-06 23:17
Submitted a proposed fix: pull request #11141

**Comment by maecapozzi** [comment] 2017-10-26 17:37
@Hendeca, it looks like your PR has been approved.

**Comment by gaearon** [comment] 2017-10-31 11:48
Fixed in https://github.com/facebook/react/pull/11141.

**Closed by gaearon** 2017-10-31 11:48 UTC
Labels: Component: DOM, Difficulty: beginner, Type: Bug
