### ISSUE TITLE
Not able to render n number of deep expandable table rows which render another rows

### ISSUE THREAD

**Issue by Foxhoundn** [facebook/react#8775] opened 2017-01-13 12:12 UTC
**Do you want to request a *feature* or report a *bug*?**
Probably neither, but I am stuck with this.

**What is the current behavior?**
Rendering multiple rows in table that are expanded by the "parent" row is not possible due to <tbody /> not being permitted in <tbody /> and the absence of fragmentation

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Here's to get an idea https://jsfiddle.net/69z2wepo/67419/

**What is the expected behavior?**
This is the expected behaviour, I guess, until Fiber lands. I am just looking for an explanation on how to achieve this.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am on 15.3.2 but probably all pre-fiber versions have this.

Thanks for any help!

**Comment by gaearon** [comment] 2017-01-13 13:18
As you noted, it’s a known limitation until Fiber is out. I’m not really sure how we could help you—the only way I see to fix this specific case is to not use components, and just use functions for rows (e.g. `renderRow`). Then you could flatten their rendering result. Or you could stop using `<table>`s 😄 .

Closing as a duplicate of #2127.

**Closed by gaearon** 2017-01-13 13:18 UTC

**Comment by Foxhoundn** [comment] 2017-01-13 13:33
@gaearon could you elaborate more on the flattening of the stateless render result please? In my case I will always need to return the actual HTML (<tr>) and then render other rows, if there are any.

**Comment by gaearon** [comment] 2017-01-13 13:51
Not sure what you mean, but I just propose to use functions that return arrays of rows. And flattening them in the component that renders `<table>`.

**Comment by Foxhoundn** [comment] 2017-01-13 13:56
Each row has a state that expands/collapses other ^^children^^ rows. How
would I achieve that with a stateless component?

Thanks

**Comment by gaearon** [comment] 2017-01-13 13:59
You could keep track of that state in the parent component. Like an object `{ rowId -> isCollapsed }`
