### ISSUE TITLE
Add 'DEV' flag

### ISSUE THREAD

**Issue by flarnie** [facebook/react#9569] opened 2017-05-01 17:42 UTC
We want to have a check for whether React is in 'DEV' mode, which would work for all previous versions of React.

**Comment by gaearon** [comment] 2017-05-02 16:30
>which would work for all previous versions of React.

I think this is a non-goal (as it's something we'd implement on DevTools side with duck type checks etc). Just providing a boolean as an argument to the [`inject` call](https://github.com/facebook/react/blob/109d1c95e3e3c777a2990ee8ca23f56bbe886440/src/renderers/dom/fiber/ReactDOMFiber.js#L556) should be enough.

**Comment by gaearon** [comment] 2017-05-02 16:37
One thing we need to ensure is it highlights in DEV mode even if React *thinks* it's in prod mode. For example if you set `process.env.NODE_ENV` to `"production"` but don't uglify (and thus get deoptimizations caused by code in DEV blocks).

**Comment by gaearon** [comment] 2017-05-02 16:46
Also the opposite: it should show as DEV if you uglify but don't set `process.env.NODE_ENV` to `"production"`. Tricky 🤔

**Comment by gaearon** [comment] 2017-05-03 16:43
I think this was fixed in https://github.com/facebook/react/pull/9586, and we won’t be bringing it to 15.x.

**Closed by gaearon** 2017-05-03 16:43 UTC
