### ISSUE TITLE
Bug: IE 11 not working with latest React version

### ISSUE THREAD

**Issue by Markus-ipse** [facebook/react#20598] opened 2021-01-15 14:07 UTC
React version: 
react@17.0.1 
react-dom@17.0.1

## Steps To Reproduce

1. Create a new project with CRA: `npx create-react-app ie11-test --template typescript --use-npm`
2. Install polyfills for IE11: `npm i react-app-polyfill`
3. Add polyfills to src/index.tsx
4. Add IE 11 under both 'production' and 'development' in 'browserslist' in package.json
5. start dev server and open in IE 11

It does however start working in IE 11 if i downgrade react to 16.13.1 with `npm i react@16.13.1 react-dom@16.13.1` *but* I have to remove node_modules and do `npm i` again for it to start working in IE11. 

Version 16.14.0 is also broken in IE 11 though.

Link to code example: https://github.com/Markus-ipse/react-ie11-issue/

## The current behavior
When opening in IE11 it crashes with the following error message:
![image](https://user-images.githubusercontent.com/830794/104734888-31819a00-5741-11eb-86c7-502b89eef672.png)
> SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
## The expected behavior
For it to not crash in IE11 after adding polyfills and adding IE11 to browserlists

**Comment by gaearon** [comment] 2021-01-15 15:47
Seems suspicious that it's only discovered many months after the 16.14 release. I'd bet that something is wrong with the polyfilling, but I don't know how exactly.

The symptom appears to mean that when `react` is initialized, `Symbol` polyfill is not yet there, but when `react-dom` is initialized, the `Symbol` polyfill has already run. This would cause them to not recognize each other. Can you check if this is correct, and why this might be happening?

**Comment by gaearon** [comment] 2021-01-15 15:48
Check the compiled code. I wonder if TS is inserting an import to `react/jsx-runtime` _before_ other imports, which would cause the polyfill to run too late.

**Comment by Markus-ipse** [comment] 2021-01-15 16:15
You're right, there is a jsx-runtime before the polyfill import (if I read the minified file correctly), however it does not appear to be TS related as I have the same problem when creating another project using CRA but skipping the typescript template this time.

![image](https://user-images.githubusercontent.com/830794/104750749-c8a41d00-5754-11eb-91ba-c29525aca952.png)
This is from the non-TS version ☝️ 

I do agree with you that it's really strange that it's taken this long for the problem to surface though - I've spent a good part of the day googling without finding anyone else having the same problem (in recent months) 🤷

**Comment by gaearon** [comment] 2021-01-15 17:15
So the easy workaround for now is to separate the file where you load the polyfill and the file where you use JSX.

```js
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import './renderApp'; // Call ReactDOM.render here
```

The upstream solution is to move the order of the imports, I think. I.e. make the transform put the JSX import last. Can you file an issue in Babel to discuss this?

**Comment by gaearon** [comment] 2021-01-15 17:16
Going to close it here since the issue is not something we can fix in the _React library_ but it can be fixed in Babel and TS.

**Closed by gaearon** 2021-01-15 17:16 UTC
Labels: Status: Unconfirmed

**Comment by eps1lon** [comment] 2021-01-15 17:28
We had a previous report in https://github.com/facebook/react/issues/20481 which we moved to https://github.com/babel/babel/issues/12522.

The fix was merged but is not released yet. So the next release of `@babel/plugin-transform-react-jsx` should fix this.
