### ISSUE TITLE
Resetting an animation in useEffect React is not setting all state variables to initial state

### ISSUE THREAD

**Issue by Amit-Tomar** [facebook/react#17112] opened 2019-10-16 08:58 UTC
**Bug**

**What is the current behavior?**

I have a simple animation -

1. Lines get highlighted one after the other on click of a button.

2. Clicking on button again, while the animation is running, should de-highlight the lines to original state. 

I use [GSAP](https://greensock.com/gsap/) for doing animations.

On setting the timeline progress of animation to 0, all the values get reset, however, the last one modified continues to remain in same state. 

To reproduce, click the button, and after a couple lines have highlighted, click the button again. 

Code Sandbox : https://codesandbox.io/s/inspiring-gates-poozb

**What is the expected behavior?**

All the variables would have been set to false on toggling the animation state. However, the last modified variable in the current animation remains in the same state.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Working with following dependencies: 
![Screenshot 2019-10-16 at 2 13 50 PM](https://user-images.githubusercontent.com/5795958/66903064-61faf580-f01f-11e9-9863-48200839afea.png)

Doesn't work as expected with following dependencies: 
![Screenshot 2019-10-16 at 2 13 23 PM](https://user-images.githubusercontent.com/5795958/66903143-8c4cb300-f01f-11e9-9fd6-71ad763cb626.png)

Platform tested on : Mac OS Mojave with latest Chrome.

I would like to understand what is causing this issue and steps I can take to make it work in the above mentioned version where it doesn't work.

**Comment by Sharakai** [comment] 2019-10-17 17:11
Although I can't work out what the issue is myself, I've added some additional logging to highlight what is going on with the state changes: https://codesandbox.io/s/tender-leftpad-pjtsd
Open DevTools and check the console to see what is going on. I can see all the `setHightlightX` functions are being called correctly, but the final state seems to flick the last highlight from `true`->`false`->`true`, as though the state updates have been actioned out-of-order.

I have found a "fix" for it, though: Change the `setHighlight` usage to functions, e.g. `setHightlightA(() => Boolean(animationData.highlightA))`: https://codesandbox.io/s/nostalgic-feather-pvs1k

**Comment by Amit-Tomar** [comment] 2019-10-18 11:14
> Although I can't work out what the issue is myself, I've added some additional logging to highlight what is going on with the state changes: https://codesandbox.io/s/tender-leftpad-pjtsd
> Open DevTools and check the console to see what is going on. I can see all the `setHightlightX` functions are being called correctly, but the final state seems to flick the last highlight from `true`->`false`->`true`, as though the state updates have been actioned out-of-order.
> 
> I have found a "fix" for it, though: Change the `setHighlight` usage to functions, e.g. `setHightlightA(() => Boolean(animationData.highlightA))`: https://codesandbox.io/s/nostalgic-feather-pvs1k

Thanks. Wonder what difference setting it like this makes which make it work though?

**Comment by Amit-Tomar** [comment] 2019-10-18 11:15
I have also realised that changing useEffect to useLayoutEffect also gives the intended behavior. Not sure why though.

**Comment by miturostislav** [comment] 2019-10-20 19:36
The issue seems to be fixed in 16.9.0 version.

**Closed** 2019-10-31 14:24 UTC
