### ISSUE TITLE
HTML input tag maxLength BUG

### ISSUE THREAD

**Issue by unsignedlinux** [facebook/react#10250] opened 2017-07-22 05:52 UTC
I met a problem as follow
I want to render the input tag value when react component mounted,
and I have set maxLength attribute for this Input, but confusing me is that the value length over maxLength but display it without split,
you can see demo https://jsfiddle.net/rfezx7jL/
anyone can help me?

**Comment by jquense** [comment] 2017-07-22 11:53
Hi there, this how the maxLength works on browser inputs for better or worse. React doesn't do anything it just passes the attribute through to the input, which prevents a user from typing paste a specific length, but not setting the value programmatically as you are doing.

**Comment by nbkhope** [comment] 2017-07-23 06:00
Remove the `value` and `onChange` properties from the input and it will work just fine. The moment you set those properties yourself, you are making a React controlled component. As such, you are in charge to making the validations. That is not a bug.

**Comment by aweary** [comment] 2017-08-04 18:24
Closing this out since you can use uncontrolled inputs if you want the input to respect the `maxLength` attribute, and just manually manage the max length of the value with controlled inputs.

**Closed by aweary** 2017-08-04 18:24 UTC
