### ISSUE TITLE
bug componentWillUnmount is called before componentDidMount 

### ISSUE THREAD

**Issue by istarkov** [facebook/react#5719] opened 2015-12-22 23:42 UTC
`React 0.14.3`
`componentWillUnmount` is called before `componentDidMount`, but this must be impossible.

As additional check: calling `findDomNode` inside `componentDidMount` causes `Invariant Violation: findDOMNode was called on an unmounted component`.

code example and output [jsbin example](https://jsbin.com/xuluviyufo/3/edit?js,console)

```javascript
import React, { Component } from 'react';
import { render, findDOMNode } from 'react-dom';

let buggyUid_ = 0;

class BuggyBehavior extends Component {
  constructor() {
    super();
    this.buggy = buggyUid_++;
  }

  componentDidMount() {
    console.log('didMount', this.buggy);
    findDOMNode(this);
  }

  componentWillUnmount() {
    console.log('willUnmount', this.buggy);
  }

  render() {
    return <div />;
  }
}

class WillReceiveUpdater extends Component {
  componentWillReceiveProps(nextProps) {
    if (nextProps.interval[nextProps.prop] !== 3) {
      nextProps.setInterval({...nextProps.interval, ...{[nextProps.prop]: 3}});
    }
  }

  render() {
    return <div />;
  }
}

class Main extends Component {
  constructor() {
    super();
    this.uid_ = 0;
    this.state = {
      data: [],
      interval: {a: 0, b: 0},
      uid: 0,
    };
  }

  componentDidMount() {
    setTimeout(() => this.setState({data: [1, 2, 3], uid: this.uid_++}), 1);
  }

  setInterval = (value) => {
    this.setState({interval: value, uid: this.uid_++});
  }

  render() {
    return (
      <div>
        <BuggyBehavior key={this.state.uid} />
        <WillReceiveUpdater
          prop={'a'}
          interval={this.state.interval}
          setInterval={this.setInterval}
        />
        <WillReceiveUpdater
          prop={'b'}
          interval={this.state.interval}
          setInterval={this.setInterval}
        />
      </div>
    );
  }
}

const App = () => <Main />;

render(
  <App />,
  document.getElementById('root')
);
```

code output of example above

```javascript
// didMount 0
// willUnmount 0
// willUnmount 1 !!! WAT didMount is not called yet
// didMount 1
// invariant.js:39 Uncaught Error: Invariant Violation: findDOMNode was called on an unmounted component.
```

**Comment by chicoxyzzy** [comment] 2015-12-23 00:43
Just tried this example and I can confirm this behaviour exists. Is it expected behaviour to prevent memory leaks and clean something from constructor even if component is not mounted yet?

**Comment by jimfb** [comment] 2015-12-23 02:11
@sebmarkbage destructors.

**Comment by spicyj** [comment] 2015-12-23 02:50
This might be #2410.

**Comment by sompylasar** [comment] 2016-06-09 00:44
@istarkov @chicoxyzzy @spicyj The related issue #2410 [has been closed](https://github.com/facebook/react/issues/2410#event-646217597), should this issue be closed, too (if stopped reproducing)?

**Comment by spicyj** [comment] 2016-06-09 00:50
The jsbin is broken in 15.0.2 and fixed in 15.1.0 so almost certainly that, thanks.

**Closed by spicyj** 2016-06-09 00:50 UTC

**Comment by romulof** [comment] 2017-05-26 14:47
I'm experiencing this issue with React 15.5.4 while using React-Modal.

**Comment by gaearon** [comment] 2017-05-26 14:49
If you're experiencing an issue please create an example reproducing it. Then we can diagnose it. Thanks!

**Comment by romulof** [comment] 2017-05-26 15:42
Sorry, I forgot to attach the example link.

But forget it, the bug was caused by `async-reactor` incorrect error handling putting React in a erroneous state.
