### ISSUE TITLE
Bug:[Jest Timer Mocks] act is diff with react-dom/utils make act warning on async act

### ISSUE THREAD

**Issue by memsenpai** [facebook/react#18884] opened 2020-05-11 04:21 UTC
When i use 
`import { act } from 'react-test-rerender';`
![image](https://user-images.githubusercontent.com/10399540/81523754-04424800-9379-11ea-99a0-419def556061.png)

When i replace it with 
`import { act } from 'react-dom/test-utils';`

this warning is gone :v: 

React version: 
react-test-renderer: 16.13.1
react-dom: 16.13.1
jest: 26.0.0
Code example:

```
await act(async () => {
  jest.runAllTimers();
});
```

**Comment by bvaughn** [comment] 2020-05-12 22:39
`react-dom` and `react-test-renderer` are different renderers. That's why the error message mentions that they have different `act()`s.

Which renderer are you using in your tests?

**Comment by memsenpai** [comment] 2020-05-13 07:22
@bvaughn i try with `create` from react-test-rerender and `render` from @testing-library/react
same issue.
must use `act` from react-dom/test-utils for resolve

**Comment by bvaughn** [comment] 2020-05-13 15:47
`react-testing-library` uses `react-dom` so it makes sense that you would need to use the `act` from `react-dom`.

**Comment by bvaughn** [comment] 2020-07-30 17:49
Since the issue is not currently actionable, I'm going to close this issue until more information is provided.

**Closed by bvaughn** 2020-07-30 17:49 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
