### ISSUE TITLE
React DevTools force re-render button

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#16968] opened 2019-10-01 04:14 UTC
I'd like to have a button that forces a re-render of the selected component when clicked. For example, adding a button like this on the right of the component controls:

![image](https://user-images.githubusercontent.com/1500684/65933573-35b06980-e3cf-11e9-8245-e5bedac5c552.png)

This can be accomplished today by adding a new prop and changing the prop, but it's more work than I want to do.

This would be useful for use while profiling how a component performs with unnecessary re-renders. Right now I just have a button that's tied to a "forceRender" function:

```jsx
function useForceRerender() {
  const [, set] = React.useState()
  return React.useCallback(() => set({}), [])
}

function FilterComponent() {
  const forceRerender = useForceRerender()
 
  return (
    <>
      <button onClick={forceRerender}>force rerender</button>
      {/* more JSX */}
    </>
  )
}
```

Would be cool to have this built-in :)

**Comment by hristo-kanchev** [comment] 2019-10-01 12:55
Something like this maybe?

![forceupdate](https://user-images.githubusercontent.com/23095052/65963573-5aeab980-e45b-11e9-9a05-282bf6d6b832.gif)

Do you think the UI is getting cluttered over there, @bvaughn ?

If you are cool with this I can submit the PR.

**Comment by kentcdodds** [comment] 2019-10-01 13:17
That would be perfect for me 👍

**Comment by bvaughn** [comment] 2019-10-01 15:37
> Do you think the UI is getting cluttered over there, @bvaughn ?

Yup, that was my first thought when I saw the buttons take up slightly more space than the component name in your screenshot. Not sure what can be done about it that wouldn't add more clicks though (or make the hit area too small to be user friendly).

Let's not worry about the button space for now. I can revisit that UI.

> If you are cool with this I can submit the PR.

Sure, let's see a PR.

I wonder if "_Re-render component_" might be more intuitive to new users than "_Force update_"?

**Comment by hristo-kanchev** [comment] 2019-10-02 07:00
Yeah, "Re-render component" is better. I'll change the tooltip text 👍

**Comment by hristo-kanchev** [comment] 2019-10-07 07:23
Hey @bvaughn! Hope you are doing well.

I'm struggling to find a good way to re-render the component that will capture all use cases. 

I used `instance.forceUpdate` but this doesn't capture all use cases - for example functional components. 

I can push my code if you want to check it out and advise if possible?

**Comment by bvaughn** [comment] 2019-10-09 16:23
You should push it if you'd like someone to look it over. I don't know if I'll have any time in the near future though. Going to be pretty busy preparing for React conf.

**Comment by bvaughn** [comment] 2019-10-09 16:24
I will say that I don't think `instance.forceUpdate` is the right way to go though.

You might try using the `scheduleUpdate` function injected into the renderer, although this would only work for v16.9+ (but I think that's okay).

**Comment by bvaughn** [comment] 2019-10-14 15:50
Looked at @hristo-kanchev's PR this morning and the code looks good, but I realized something was bugging me about the feature request. I don't understand the use case here.

If your component is pure, forcing a re-render should be a no-op. (The output should be the same since the inputs didn't change.) So what is the purpose of doing this? Could you walk me through what you're trying to do/test/measure, @kentcdodds?

**Comment by kentcdodds** [comment] 2019-10-15 15:52
The situation is mostly to determine whether opting out of re-renders would be beneficial. In my specific case, I'm contriving examples to demonstrate the benefits of `React.memo`, but in more real-world scenarios it could be used anywhere that people think there may be a benefit to opting a tree out of unnecessary updates. It's basically a way to help them measure.

I suppose it could be argued that it'd be better for people to profile actual interactions instead though. This feature may just increase people's general unfounded fear of re-renders.

**Comment by nik72619c** [comment] 2019-10-24 11:25
Shal I give it a try .. I'd love to make my first PR :)

**Comment by hristo-kanchev** [comment] 2019-10-28 08:55
Hey @nik72619c there is already a PR open for this. 

We are currently in a discussion if we actually need this feature. 

I agree with @kentcdodds that it might "increase people's general unfounded fear of re-renders". 

We are also adding an additional button, and the UI is looking cluttered (especially if you have a long component name).

Should we close this issue/PR for now, @bvaughn ? 
I'm not sure what should we do 🤷‍♂

**Comment by kentcdodds** [comment] 2019-10-28 13:10
I suggest we close it.

**Comment by bvaughn** [comment] 2019-10-28 16:43
Sorry for taking a while to circle back to this. I was distracted by the conference.

The explained reasons for this feature make sense, (thanks for adding the motivation) but I'm not sure the benefits outweigh the potential costs in this case, so I agree with the outcome of just closing it for now. We can always reopen!

Thanks for the discussion and the PR contribution!

**Closed by bvaughn** 2019-10-28 16:43 UTC
Labels: Component: Developer Tools, Type: Feature Request, good first issue (taken)

**Comment by slikts** [comment] 2020-02-27 09:58
An another use case for a feature like this is checking if effects are correctly memoized and cleaned up, so it's not just about rerenders.

**Comment by dchebakov** [comment] 2020-04-07 16:13
It would be nice to have this button. In my case I need force rerender button to reset state to initial values.

**Comment by giotiskl** [comment] 2020-09-18 09:25
shame this was closed, can be a useful feature

**Comment by gcvs** [comment] 2021-09-08 12:08
It's a shame, I wanted to step through the render method in the javascript debugger to reason about why certain things are / are not happening in my component.  It's very inconvenient to refresh the page, and go through the many steps necessary to recreate the conditions, just to have one shot at stepping through with a debugger.  One render is also wasted just to add the breakpoint, I can't even add the breakpoint ahead of time because the source code isn't immediately loaded.

**Comment by bvaughn** [comment] 2021-09-08 13:48
@gcvs You might already be aware, but if not– check out [conditional breakpoints](https://developers.google.com/web/updates/2015/07/set-a-breakpoint-based-on-a-certain-condition). They're a great help with what you're describing.

**Comment by morganga** [comment] 2022-08-09 10:19
@bvaughn conditional breakpoints do not help at all here with what I described.  I was not waiting for a special condition to step through a component being rendered multiple times.  Quite the opposite, I was waiting for the one and only render of a component that's lazily loaded then immediately rendered.  The component has to be loaded before I can even find it in the source tab from which to add the breakpoint.

Now, eleven months later I'm googling for a solution to the same problem, and find my own comment :)

I'm debugging an order confirmation page. To get there, I have to navigate through checkout, which involves adding products to the basket, filling in registration details, adding payment, consents etc.  It takes a while to reach the order confirmation page.  If I use breakpoints, conditional or not, then every time I want to step through the render, I have to create a new customer and go through the checkout process again.
Essentially, it takes a long time to reproduce the exact conditions I want to test, so it's much more convenient to ask the component to re-render, than it is to create a new order from scratch.

**Comment by davispuh** [comment] 2022-12-21 12:54
I'm also looking for option to this. Is there any other workaround that making full page refresh? Refreshing whole page doesn't allow to debug if we are doing too much work at every render because it's expected first render will do way more. I'm interested in debugging next renders.

**Comment by DannyMeister** [comment] 2023-10-26 18:19
It is disappointing to not have a way to induce a re-render in the dev tools.

I have an awful hack for a very limited scenario.  If you want to re-render simply to hit a breakpoint in a renderer without reloading the page (and requiring a lengthy set of steps to get the app back to the current state) then I can put a `debugger` statement in my code so that hot reload will serve the change to the browser which will break on the statement.  A normal breakpoint will not work during hot reloads.

![image](https://github.com/facebook/react/assets/7937829/b838d44e-3c17-4975-8459-463474e48428)

**Comment by sumner0620** [comment] 2025-04-01 11:16
I'm also pretty bummed out that this didn't make it to prod. I feel as though it'd be a useful feature when trying to debug simple timing issues on re-renders.
