### ISSUE TITLE
Bug - react onClick() doesn't work well on WKWebview - iOS 13

### ISSUE THREAD

**Issue by Aarbel** [facebook/react#17258] opened 2019-11-04 10:50 UTC
# Context
Apple just realeased new version of WKWebview with iOS 13.
On my mobile app i don't use react native but pure React / HTML inside a Native Webview.

# Problem 
Touch events don't work well on onClick() since the update. 
The user has to touch very fast to trigger the onClick(). If the use touches more than 200 / 300 ms it doesn't trigger the onClick()

Do you know a way to fix it ?

Thanks a lot for your help !

**Comment by jamesmosier** [comment] 2019-11-05 19:37
You may find some of the [answers here](https://stackoverflow.com/a/27525707/1554860) useful. Otherwise it may be more of a browser issue than a React issue. There is another workaround [here](https://github.com/facebook/react/issues/2753).

**Comment by Aarbel** [comment] 2019-11-06 12:35
Yes its more a browser issue, seems react fastclick doesn't work well on new Webkit version.
If you have other infos i would be glad to read them !

**Comment by Aarbel** [comment] 2019-11-06 17:29
In fact i don't use fastclick

**Comment by andreyqin** [comment] 2019-11-07 09:51
We've run into the exact same issue the other day. I could reproduce it on iPhone 11 Max Pro simulator in XCode but only when the app was getting zoomed in. Once I switched to the different simulator and then went back to the iPhone, I wasn't longer able to reproduce it. I did some digging into the issue and it looked like WKWebview couldn't have registered `onClick` callbacks for some reason whereas, for example, `touchstart` worked fine.

@Aarbel did you manage to figure out how to get it worked?

**Comment by Aarbel** [comment] 2019-11-11 15:02
@andreyqin not yet, the onclick works well if you touch fast the screen. 

So looks like it's a question of touchstart delay that trigger click events. 

Very hard to find the origin and find a way to fix it.

**Comment by Aarbel** [comment] 2019-11-12 18:20
The problem only occurs on WkWebview.

Works fine on iOS Safari.

Very weird.

**Comment by EddyVinck** [comment] 2019-11-19 10:36
I'm also experiencing issues with click events on iOS 13. 

I have `onClick` listeners on `<div />` elements inside a portal. The events aren't fired on the first touch. The first touch only fires `onTouchStart`, and on  the second touch `onClick` is fired, resulting in my multi-select component being unusable since you need to double tap every item.

**Comment by EddyVinck** [comment] 2019-11-20 09:02
@graouts perhaps this issue is related to some issues/WebKit changes you discussed in [this issue](https://github.com/Leaflet/Leaflet/issues/6817#issuecomment-536557192)?

[WebKit bug #202143](https://bugs.webkit.org/show_bug.cgi?id=202143)

**Comment by Aarbel** [comment] 2019-11-20 13:08
Thank you @EddyVinck for the screenshots, glad to see people don't use React Native for responsive mobile web apps.
Have you tried with [react-tappable](https://github.com/JedWatson/react-tappable) to fix it ?

**Comment by EddyVinck** [comment] 2019-11-20 13:14
@Aarbel Yeah this application is just a PWA server side rendered by [DEITY Falcon](https://github.com/deity-io/falcon) and 'regular' React.

I haven't tried `react-tappable` yet. Did it fix the issues you were having?

**Comment by Aarbel** [comment] 2019-11-20 13:18
Very interesting. You distribute it on Stores or only PWA ?

**Comment by EddyVinck** [comment] 2019-11-20 13:21
@Aarbel Only PWA, but this is for a demo project showcasing DEITY Falcon. Did you try `react-tappable`? Did it fix your issues with iOS13?

**Comment by Aarbel** [comment] 2019-11-20 14:01
@EddyVinck not yet, just tested on wkwebview and seems to be stable. 

About PWA : you can wrap them in a native webview (with cordova for example) and ship them on the store. Few settings to set but works really great

**Comment by Aarbel** [comment] 2019-11-30 10:40
@EddyVinck i can confirm you that `react-tappable` is a great solution 🎉
Indeed the tap works much better than previously (we the react `onClick` was working on iOS 12) because it is triggered even if the user holds the tappable element for a long time.

Could be great that React fully handle touch behavior with the `onClick` method or maybe a new `onTap` method.

**Comment by zhangyu0218** [comment] 2020-01-10 05:38
I found a similar problem in ios 13 WKWebview. I wrote a function that listens for the number of onclicks (increment the value of each click, starting at 0), and when I first click the value becomes 2 instead of 1.

**Comment by fusioneery** [comment] 2020-04-15 16:27
bump

**Comment by gaearon** [comment] 2020-04-15 16:30
Did anyone into _why_ this is happening?

**Comment by sbannigan** [comment] 2020-04-28 01:36
I've run into this issue before with angular as well. It's also reproducible with plain javascript. As far as I know, it was a webkit bug that was introduced in iOS 13, then resolved in 13.2. As of iOS 13.4 it seems to be an issue again, I'm not sure why. This [codepen](https://codepen.io/juliogcampos/pen/BzdjwY) is an easy way to see the issue.

![2019-09-03 14 44 55](https://user-images.githubusercontent.com/15218748/80436912-4033d280-88ce-11ea-9ff0-f5a991b91878.gif)

**Comment by graouts** [comment] 2020-04-28 12:09
@sbannigan If you encounter a bug in WebKit, especially with a simple test, please file a bug at bugs.webkit.org. Thanks.

**Comment by Aarbel** [comment] 2020-04-29 07:26
@graouts the bug can also come from the way javascript handles the touch events. That's why HammerJs exist. Does React has to handle that ? For basic Clicks i think yes, as more and more projects are cross platforms.
Far harder to make the apple team fix it with their 20st century bug tracker (webkit bugzilla).

**Comment by graouts** [comment] 2020-04-29 08:29
@Aarbel A member of the Apple team here! Hardest to fix bugs that aren't filed :)

**Comment by Aarbel** [comment] 2020-04-29 09:27
@graouts sorry to be pushy, you should really internally convince Apple to leave webkit. I'm serious. And also allow Chromium webview in native iOS apps. I really don't understand why webkit is still maintained. Looks like a big waste of money with 0 strategic impact for Apple (it was strategic at the beginning, but now the "tech browser game" doesn't bring more retention for the business). So if i was working for Apple i would particularly investigate this subject and maybe save them loads of money. Microsoft made the move to Chromium. Most front-end developers are waiting for the move from Apple.

I'm working on crossplatform since 5 years. On every iOS release you introduce html / css / javascript bugs, and many are not yet solved (like the legendary input focus problems for example). We need to fix them every time, using javascript patches like hammerJS, big waste of time. Also a big pain for our users. You can contact me if you want the details of all the problems we faced.

About Bugzilla, i've posted this other issue 1 year and a half ago: https://bugs.webkit.org/show_bug.cgi?id=183870#c9, no news since 1 year. This tool is really horrible to track issues. Looks like it's really easy for you to miss them.

**Comment by graouts** [comment] 2020-04-29 12:38
I won't debate the merits of Bugzilla, your point is taken though. However, it's harder still to track issues if they are not filed in the WebKit bug reporter in the first place.

**Comment by graouts** [comment] 2020-04-29 13:09
Based on the information shared by @sbannigan, I filed webkit.org/b/211179.

**Comment by Dom355** [comment] 2020-10-27 01:38
I have the same issue. On Chrome and Safari mobile. On desktop, the button works fine.....

**Comment by sfonua10** [comment] 2021-01-03 04:34
Yep, I'm experiencing the same issue with Chrome and Safari mobile. Chrome desktop onClick seems to work

**Comment by gaearon** [comment] 2021-03-24 18:42
Seems like this has no relation to React so I'm closing.

**Closed by gaearon** 2021-03-24 18:42 UTC
Labels: Browser: Safari, Component: DOM, Type: Needs Investigation

**Comment by webb24h** [comment] 2021-07-21 02:32
> Seems like this has no relation to React so I'm closing.

I confirm this is not a react only issue as im using plain javascript and only href works. button and onclick events do not fire at all.

**Comment by Aarbel** [comment] 2021-07-21 12:49
I highly recommend using Capacitor for your PWAs or mobile apps, the lib provides polyfills / fixes to build well your react apps, and don't have mobile / desktop environment surprises
