### ISSUE TITLE
SyntheticEvent.key property is "unidentified" in Safari on Mac OS X

### ISSUE THREAD

**Issue by ProtectedVoid** [facebook/react#7897] opened 2016-10-06 12:37 UTC
# BUG

### Current Behavior
Using a standard `<input type="number" onKeyDown={ this.myKeyDownEvent } />` with an onKeyDown event, the SyntheticEvent.key property is "unidentified" in Safari, for any key pressed.

**FIDDLE: ** https://jsfiddle.net/protectedvoid/u9mtvoyr/

### Expected Behavior
SyntheticEvent.key should provide the proper values for all standard keyboard inputs (letters, numbers, numberpad, arrows, backspace, etc), as it does in Chrome (since both are webkit-based browsers).

### Version Info
- Mac OSX El Capitan
- React 15.3.2
- Safari 9.1.3

**Comment by syranide** [comment] 2016-10-06 13:56
Not a bug. Safari does not support `key` and does not expose values that could be used to accurately and reliably polyfill it fully either (unless this has changed recently, which I doubt).

However, it should report correct values for most control keys like space, enter, arrows, escape, etc.

**Comment by ProtectedVoid** [comment] 2016-10-07 13:40
The control, space, arrow, etc keys do report correctly, as you say.  So, I'm guessing the solution to this would be to (essentially) roll our own keyMap for KeyDown and KeyUp events that is specific to Safari, since this isn't normalized by default?  

On a side note - there should probably be a note on the SytheticEvent documentation for KeyDown, KeyPress, and KeyUp events that React's SyntheticEvent is not truly normalized for Safari browsers.

**Comment by syranide** [comment] 2016-10-07 14:07
> So, I'm guessing the solution to this would be to (essentially) roll our own keyMap for KeyDown and KeyUp events that is specific to Safari, since this isn't normalized by default?

I doubt they can be reliably polyfilled in Safari, that's why we don't do it. Note that `keyCode` refers to the virtual key code of the users keyboard layout, so you cannot use it to reliably turn it into characters if that's what you're hoping (hence why we don't do it). But in certain circumstances that may be acceptable (say hotkeys).

> On a side note - there should probably be a note on the SytheticEvent documentation for KeyDown, KeyPress, and KeyUp events that React's SyntheticEvent is not truly normalized for Safari browsers.

@ProtectedVoid Yeah perhaps, but that applies to many browsers and many different types of events. You'll also find that some browsers don't support `key` and similar features fully either, so "truly normalized" is a grey area regardless.

**Comment by mikkelwf** [comment] 2016-10-19 15:06
I definitely think there should be added some note to the documentation about this. 

I'm struggling with this issue right now, and i implicitly thought the SyntheticEvent actually handled this issue (because SyntheticEvent normalize other browser event quirks).

And that this issue is not only restricted to Safari, but also other browsers, makes it even more important to put in a note. (I guess somebody would now argue that it is common knowledge that keyboard events are not consistent cross browser, but I, for one, very seldomly use keyboard events, so i would definitely have found is useful, if the react docu stated this).

**Comment by ProtectedVoid** [comment] 2016-10-19 22:24
@syranide The main thing I was looking for in using key / which / keyCode was in implementing a method that restricted input to numeric values only, while allowing for tabs, backspace, delete, shift, home, end, arrow, & meta keys.  

> @ProtectedVoid Yeah perhaps, but that applies to many browsers and many different types of events. You'll also find that some browsers don't support key and similar features fully either, so "truly normalized" is a grey area regardless.

In reading the documentation for SyntheticEvent, I was under the mistaken impression that things like key events were already normalized across the modern browsers.  That was an assumption I made, so that's on me.  I'm not suggesting an overly detailed explanation or anything, but at least something indicating that not all properties of the SyntheticEvent are available in all browsers (even modern ones).

**Comment by Aweary** [comment] 2016-10-20 02:53
> I doubt they can be reliably polyfilled in Safari, that's why we don't do it. Note that keyCode refers to the virtual key code of the users keyboard layout, so you cannot use it to reliably turn it into characters if that's what you're hoping (hence why we don't do it). 

@syranide can you give an example of where using `keyCode` would be incorrect? Do you know if `keyIdentifier` (which `KeyboardEvent.key` replaced) also refers to the virtual key code?

**Comment by syranide** [comment] 2016-10-20 07:30
@Aweary KeyboardEvent supports both `keyCode` and `charCode` (mostly for keypress). The reason for the distinction is that there is a difference between the code which represents the button on your keyboard (`keyCode`) and the character code it represents after being translated by your keyboard layout settings in the OS (`charCode`). An important thing to note is that pressing `e` on your keyboard will always generate the same `keyCode`, whereas the resulting `charCode` may be `e`, `E`, `é`, `€`, etc or something else entirely if you have say a Russian/Korean keyboard layout.

So the resulting `charCode` also depends on shift/ctrl/deadkey/etc-state, so `keyCode` is a bad idea for filtering characters, pressing `1` does not generate a number if you hold shift/ctrl/etc. It's also generally not a good idea to actively filter inputs because it destroy the undo history (and even corrupts the undo history in Chrome, still not fixed...). Stuff may also be pasted/dragged/etc, so keydown is insufficient regardless.

I looked into using `keyIdentifier` for the normalization back then too, I concluded that it couldn't be used reliably. I don't remember exactly why, either because it only represents the keyboard button identifier (i.e. the universal code for the keyboard button, does not reflect shift/ctrl/deadkey/composition-state) and/or it reported wrong keys in some cases.

It's also interesting to note that some browsers that natively support `key` actually report wrong/inconsistent characters (possibly due to omissions in the specification). So even if our normalization was perfect, you still couldn't rely on `key` behaving perfectly.

**Comment by Aweary** [comment] 2016-10-20 18:28
@syranide thanks for breaking that down for me. I agree that there doesn't seem to be safe way to polyfill this then. It looks like [work is being done](https://bugs.webkit.org/show_bug.cgi?id=36267) on getting `key` into Safari.

cc @lacker we *might* want to make mention of this in the docs, since this isn't the first time it's tripped people up. 

Going to close this since we can't resolve this as it stands.

**Closed by Aweary** 2016-10-20 18:28 UTC

**Comment by syranide** [comment] 2016-10-20 18:46
> cc @lacker we might want to make mention of this in the docs, since this isn't the first time it's tripped people up.

Documenting all the normalizations we do and the pros/cons sounds like an undeniably beneficial thing, even just knowing which things are normalized is a big win :+1:, if someone is willing to invest the time.
