### ISSUE TITLE
[DevTools Bug]: Profiler freezes when navigating through commits

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#22123] opened 2021-08-18 09:33 UTC
### Website or app

https://github.com/eps1lon/material-ui/tree/757f6cf571557f8b03a372db5c7cc1cf3837c944

### Repro steps

1. Enable chrome://flags/#enable-throttle-display-none-and-visibility-hidden-cross-origin-iframes
1. goto https://611f52616dca6500083055f2--material-ui.netlify.app/components/slider/#ContinuousSlider
1. record at least 2 commits via Profiler

The larger the component tree the more reliable the crash. When I reduce the component tree in the UI the crash stops at some point.

https://user-images.githubusercontent.com/12292047/129874688-1f38e1ea-6f80-4fbc-a331-b76fdde32b99.mp4

### How often does this bug happen?

Every time

### DevTools package (automated)

1d2528097

### DevTools version (automated)

4.16

### GitHub query string (automated)

```text
profiler freeze
```

**Comment by iunfixit** [comment] 2021-08-19 20:06
I cannot reproduce this(the crash) but I experience some freeze periods when changing commits, I tried `localhost:3000/components/slider` on Linux with Brave and on Windows with Chromium, both have a little freeze when changing commits, the machines are different and it is worse on the Linux one. The bigger the viewport, and when scrolling down, showing more components, the slower it gets.

**Comment by lunaruan** [comment] 2021-08-19 23:00
Hey! Thanks for reporting! 

I followed along with your repro steps but I also can't reproduce this issue. Do you have different repro instructions? Alternatively, you could try to submit a fix if you're up for it! 😊

**Comment by eps1lon** [comment] 2021-08-20 07:23
> I cannot reproduce this(the crash) but I experience some freeze periods when changing commits, 

To clarify what I mean with crash: It freezes until Chrome tells me that the (devtools) page is unresponsive. Upon closing, Chrome notifies me that the extension crashed.

May I ask the people who cannot reproduce to include their CPU information? I'm using a Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz which should be sufficient. Maybe throttling locally helps to reproduce the bug.

To reproduce please use https://611f52616dca6500083055f2--material-ui.netlify.app/components/slider/#ContinuousSlider (supports profiling).

**Comment by eps1lon** [comment] 2021-08-20 07:24
Ok I just disabled chrome://flags/#enable-throttle-display-none-and-visibility-hidden-cross-origin-iframes and can no longer reproduce the issue.

**Comment by NoobMaster1999** [comment] 2021-08-20 07:41
I reproduce this issue. Can I solve this issue??

**Comment by lunaruan** [comment] 2021-08-20 16:28
I'm testing on a Mac Big Sur 2.9 GHz 6-Core Intel Core i9 processor on chrome version 92.0.4515.159. I tried throttling and force enabling  `chrome://flags/#enable-throttle-display-none-and-visibility-hidden-cross-origin-iframes` and I still can't reproduce this issue.

What browser version are you on?

**Comment by eps1lon** [comment] 2021-08-20 16:44
> I tried throttling and force enabling chrome://flags/#enable-throttle-display-none-and-visibility-hidden-cross-origin-iframes and I still can't reproduce this issue.

That's odd. 

> What browser version are you on?

Same as yours.

I can't reproduce it on Windows 10 but on Ubuntu 20.04 (same machine). 

I'll keep the throttling flag disabled for now. Hopefully this just goes away over time with some Chrome/OS patch.

**Comment by lunaruan** [comment] 2021-08-20 18:08
Sounds good. We'll keep on the lookout for similar issues 😊

Closing this for now. If you keep seeing the issue and have some time to investigate, we'd really appreciate it!

**Closed by lunaruan** 2021-08-20 18:08 UTC
Labels: Type: Bug, Status: Unconfirmed, Resolution: Needs More Information, Component: Developer Tools
