### ISSUE TITLE
Chain dependency causes warnings with create-react-class

### ISSUE THREAD

**Issue by lightbringer1991** [facebook/react#11382] opened 2017-10-27 03:41 UTC
**Do you want to request a *feature* or report a *bug*?**
Potential bug

**What is the current behavior?**
Render react app produces warning in development mode:
```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
- create a new project `Project A` that uses `create-react-class` to create a Component `ComponentX`
- build the project into a library (minify all js assets)
- create another project `Project B` and include `Project A` as a dependency
- Create another React Component `const ComponentY extends React.Component`, and use `ComponentX` from `Project A`
- bundle `Project B` with production build
- create a third project `Project C`, and include `Project B` as a dependency
- build a react app that uses `ComponentY` from `Project B`
- warnings!!!!

**What is the expected behavior?**
there should not have any warnings regarding `create-react-class` from a third party dependency

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version 15.6.2

One quick example is installing `adslot-ui` as a dependency (https://www.npmjs.com/package/adslot-ui/tutorial), then create a react app that uses `Carousel` component (this component implements `nuka-carousel`, which uses `create-react-class`)

**Comment by gaearon** [comment] 2017-10-27 10:04
This is a duplicate of https://github.com/facebook/react/issues/9999. We'd be happy to take a fix for it.

**Closed by gaearon** 2017-10-27 10:04 UTC
