### ISSUE TITLE
Quick removal and addition of animated CSS class results in no animation

### ISSUE THREAD

**Issue by olalonde** [facebook/react#7142] opened 2016-06-29 00:22 UTC
I am trying to call `setState({ flash: false })` followed by `setState({ flash: 'up' })` which should remove the flash class from the DOM element and add it again, therefore triggering the css animation defined on that class (it only works the first time). 

This is not working as expected, unless I introduce some timeouts. The first time the class is added, the animation is triggered. But subsequent calls to `componentWillReceiveProps` fail to trigger the animation. I'm not sure if this is an issue with the way React updates the DOM or an inherent limitation of CSS animations. I know React has some specialised utilities for animations but I'd rather keep the code below if there's any way to fix it.

Stat.js
```javascript
import React, { Component } from 'react'
import { Link } from 'react-router'
import styles from './Stat.scss'

export default class Stat extends Component {
  constructor(props) {
    super(props)
    this.state = {
      flash: false,
    }
  }
  componentWillReceiveProps(nextProps) {
    if (nextProps.count !== this.props.count) {
      const flash = nextProps.count > this.props.count
        ? 'Up'
        : 'Down'
      this.setState({ flash: false }, () => {
        this.setState({ flash })
      })
    }
  }
  render() {
    const { count, name, href } = this.props
    const { flash } = this.state
    const flashClass = flash ? styles[`flash${flash}`] : ''
    return (
      <Link to={href} className="stat-link">
        <div className={`stat-number ${flashClass}`}>
          {count}
        </div>
        <div className="stat-label">{name}</div>
      </Link>
    )
  }
}

```

Stat.scss
```scss
$highlight-up-color: green;
$highlight-down-color: red;

@keyframes highlight-up {
  0% {
    color: $highlight-up-color;
  }
  100% {
    color: default;
  }
}

@keyframes highlight-down {
  0% {
    color: $highlight-down-color;
  }
  100% {
    color: default;
  }
}

.flashUp {
  animation: highlight-up 2s;
}
.flashDown {
  animation: highlight-down 2s;
}

```

**Comment by olalonde** [comment] 2016-06-29 00:31
I'm using this as a temporary fix:

```javascript
  componentWillReceiveProps(nextProps) {
    if (nextProps.count !== this.props.count) {
      const flash = nextProps.count > this.props.count
        ? 'Up'
        : 'Down'
      this.setState({ flash })
      if (__CLIENT__) {
        window.clearTimeout(this.timeout)
        this.timeout = window.setTimeout(() => {
          this.setState({ flash: false })
        }, 2000)
      }
    }
  }

  componentWillUnmount() {
    if (__CLIENT__) {
      clearTimeout(this.timeout)
    }
  }
```

**Comment by grassator** [comment] 2016-06-29 08:49
@olalonde I would say it's an expected behavior since React batches updates to DOM with RAF.

You can probably use `forceUpdate` for this. A better way probably would be to use `componentDidUpdate` to remove the class there.

**Comment by gaearon** [comment] 2016-06-29 19:36
>I would say it's an expected behavior since React batches updates to DOM with RAF.

This is not correct. React does not use RAF to delay applying updates.
React only batches `setState` calls that happen while handling the DOM event.

@olalonde Can you create a JSFiddle demonstrating the problem?

**Comment by olalonde** [comment] 2016-06-29 20:16
@gaearon here: https://jsfiddle.net/v1qxfqkn/

**Comment by Aweary** [comment] 2016-06-29 20:33
Looks like React is processing the className change so quickly that it doesn't actually register in the DOM. If you add a delay to the second `setState` call it does work like you're describing (though with a minor delay).
```js
     this.setState({ flash: false }, () => {
        setTimeout(() => this.setState({ flash }), 50)
      })
```

**Comment by gaearon** [comment] 2016-06-29 21:08
I don’t think there is anything actionable for React here. When you call `setState`, React will update the DOM. It might do this asynchronously—if you call `setState` from an event handler or a lifecycle hook—but still during the same tick.

Two DOM changes in the same tick probably don’t trigger the animation. So something like

```js
        this.setState({ flash: false }, () => {
          this.setState({ flash })
        })
```

doesn’t work for this reason—both DOM changes end up in the same tick.

For some reason it still doesn’t always animate for me even if I put a `setTimeout` there. I’m not sure why but it doesn’t look related to React.

I will close this and encourage you to create a plain JS sample that demonstrates this behavior. If you can show that the issue only happens with React, I’ll be happy to reopen. For now, it seems like more CSS/DOM issue. (e.g. maybe it is better to listen to `onAnimationEnd` rather than timeouts—I don’t really know.)

**Closed by gaearon** 2016-06-29 21:08 UTC

**Comment by olalonde** [comment] 2016-06-29 21:25
Just found this: https://css-tricks.com/restart-css-animation/

Apparently, this is not related to React (but it'd still be nice if someone could point out the React way to achieve what I'm trying to do).

**Comment by olalonde** [comment] 2016-06-29 21:31
I found the following workaround:

```javascript

  componentWillReceiveProps(nextProps) {
    if (nextProps.count !== this.props.count) {
      const flash = nextProps.count > this.props.count
        ? 'Up'
        : 'Down'
      this.setState({ flash })
    }
  }
  render() {
    const { count } = this.props
    const { flash } = this.state
    const flashClass = flash ? `flash${flash}` : ''
    return (
      <div key={Math.random()} className={flashClass}>
        {count}
      </div>
    )
  }
```

I guess it forces React's diff algorithm to believe it needs to create a new DOM element each time because the key changes.

Update jsfiddle: https://jsfiddle.net/wd5bm20j/

**Comment by gaearon** [comment] 2016-06-30 00:07
>I guess it forces React's diff algorithm to believe it needs to create a new DOM element each time because the key changes. I'm not sure how reliable that is though!

Yes, but in this case you might as well not use React at all 😉 . This is very inefficient and bad for performance.

**Comment by alexwolfe** [comment] 2018-01-04 21:16
@gaearon Do you have a suggestion for better performance? I have the same problem. Imagine an email application that needs to temporarily highlight the number of unread emails as they come in. You could also see something like this in an application with notifications as they increment (some small animation to draw attention). 

Other than using a plugin/library to achieve this, how do you recommend writing this from scratch? Thanks!

**Comment by jquense** [comment] 2018-01-04 21:27
The issue here is specific to any css transition and there are plenty of work around. I'd suggest checking out how libraries handle it (zepto is good reference lib). Basically tho you don't need changes to happen on separate ticks but you need to reflow the browser between changes

**Comment by alexwolfe** [comment] 2018-01-04 21:37
@jquense Thanks Jason, I'm looking for the specific/suggested react way to do this which I think would be helpful for those on the thread (or new visitors). I've searched for this quite a bit and haven't seen many good solutions, they all just key off of other libraries. React is opinionated about this behavior since it impacts performance, I would love to see examples of how developers should approach this properly in their react applications. 

This is a tricky use case since the component is mounted once but the same css animation needs to be re-run on every increment/decrement. Since the class is the same, react does not register the change.  A solid example here would be awesome.

**Comment by fsahlen** [comment] 2018-01-04 22:56
This might not be an optimal solution but I solved it by having duplicate elements (divs) where I assign the css class (flash) alternately. E.g.

```javascript
somethingHappened() {
    this.setState({ toggle: !this.state.toggle });
}

render() {
    return (
      <div className={this.state.toggle === true ? myAnimationClass : null}>
      <div className={this.state.toggle === false? myAnimationClass : null}>
        .....
      </div>
      </div>
    )
}
```

**Comment by jquense** [comment] 2018-01-05 00:06
the only thing that affects performance here is intentionally destroying and remounting elements via a `key` change.

My point above is that the correct solution is the same regardless of whether its React, Angular or Backbone, you need to deal with the idiosyncrasies of css animation from js.

here is the original example above working: https://codesandbox.io/s/2496rpxlkj

**Comment by meghaaila** [comment] 2018-01-24 16:17
For my case I have a dropdown and when the element in the dropdown changes, the animation has to pop up in a dom element.
I have a boolean state variable that basically decides which class to set. If the variable is true I set the class, otherwise it's empty. 

this.state = {
     animationClass: true
}

In the onClick event of the dropdown:
setTimeout(() => {
	this.setState({selectValue :val , animationClass: true});
},100);

and in the render method:
var flash = this.state.animationClass ? "bounce": "";
return (
<div className = {flash}>
.
.
</div>
);

**Comment by saitonakamura** [comment] 2018-02-01 18:07
I've found a solution using two dirty things, one is calling `void element.offsetWidth` to trigger a reflow [from css tricks](https://css-tricks.com/restart-css-animation/#article-header-id-0) and other one is using `findDOMNode`
https://codepen.io/saitonakamura/pen/bLVLoN?editors=0110

**Comment by jasonmerecki** [comment] 2018-02-04 20:50
I had a similar problem, my use case was a stock quote, and I needed to animate a cell to flash the background red or green depending on the direction of the change in the quote price. My solution is all css animation, resulting in only one change to the DOM (or to the component state) to reflect the updated price and apply the right classname for the background animation.

https://codepen.io/jmerecki/pen/VQaXoZ

I did not code this as a React component in the example because there isn't anything React specific. But hopefully this helps other people with a similar need to temporarily change the look of something on the screen and allow it animate back to its original state.

**Comment by saitonakamura** [comment] 2018-02-06 08:12
@jasonmerecki there is a problem with your code. Because if we want to show the animation again, for example in case of two consecutive raises, it won't work

**Comment by jasonmerecki** [comment] 2018-02-06 21:40
aha! Thanks @saitonakamura. I actually need to fix that for my own needs too. 

I'm not happy with my solution but at least it's working. Basically I duplicate all of the css and then flip out like "flashRed1" and "flashRed2". Since they are different classes, then the browser will apply the new class and the new animation. 

https://gist.github.com/jasonmerecki/984b5d132077e7a370567c130c1922d9
https://codepen.io/jmerecki/pen/rJMpGK/

**Comment by wmira** [comment] 2018-05-06 02:32
Here is a rough fiddle https://codesandbox.io/s/yj0o0yw3k1

**Comment by indikaanu83** [comment] 2018-09-21 08:47
I added the function below to index.html

 ```
$.fn.extend({
      animateCss: function (animationName, callback) {
        var animationEnd = (function (el) {
          var animations = {
            animation: 'animationend',
            OAnimation: 'oAnimationEnd',
            MozAnimation: 'mozAnimationEnd',
            WebkitAnimation: 'webkitAnimationEnd',
          };

          for (var t in animations) {
            if (el.style[t] !== undefined) {
              return animations[t];
            }
          }
        })(document.createElement('div'));

        this.addClass('animated ' + animationName).one(animationEnd, function () {
          $(this).removeClass('animated ' + animationName);

          if (typeof callback === 'function') callback();
        });

        return this;
      },
    });
```

```
 function AnimateError() {
      $('#LoginBox').animateCss('shake');
    }

```

Here is the react component

```
 <div id="LoginBox" className="login-box-body" onLoad={this.props.isLogginError === true ? window.AnimateError() : () => { }}>
/* All the other html elements */
</div>
```

I'm pretty sure this is not the correct way to do this. :)

**Comment by learis** [comment] 2020-05-07 20:49
With react hooks I encountered this problem. I attempt to restart an animation after each update. In useEffect I add the CSS animation. In the return portion of useEffect, I remove it so that it can be re-added the next update. But this doesn't retrigger the animation.

So then I tried alternating between two different CSS classes that do the same thing like what @jasonmerecki suggested. But it still didn't work! Finally I alternated between the typical animation class and a reverse of that animation played in reverse. This made it work! 

Below is the codesandbox demonstrating this.

https://codesandbox.io/s/animating-on-update-example-ijok5

**Comment by prokorpio** [comment] 2021-09-20 08:35
Hi, I have also encountered this problem with react hooks. Thanks to @JordanHoffman's idea to alternate using a typical-animation and the reverse-reverse of it, I was able to make it work. :) This saved me from days of being stuck on this problem. Thank you!

However my use case is a bit different to that of Jordan, so I'm sharing my implementation here just in case anyone has the same use case as mine. 

Use case: I need to highlight/animate a SidebarItem when it has received a modification from the back-end or when it was first added to the Sidebar. Otherwise, it should remain un-animated even through renders.
``` javascript
const output = useRef(null) // hold output div
const reversed  = useRef(false); // to alternate between two "identical" animations
useEffect(() => {
  // add animation, but alternate between
  // the heartbeat animation and its reversed-reversed copy
  if(status === 'NEW' || status === 'UPDATE'){
    if(reversed.current){
      output.current.classList.add(styles.heartBeat)
      reversed.current = false 
    }else{
      output.current.classList.add(styles.heartBeatReverse)
      reversed.current = true 
    }
  }

  // cleanup, remove the previously added class before updating
  const outputComponent = output.current 
  return(()=>{
    reversed.current
    ? outputComponent.classList.remove(styles.heartBeatReverse)
    : outputComponent.classList.remove(styles.heartBeat)
  })

  // this effect runs when the status prop or the last_modification prop changes
}, [status, last_modification]);


```

**Comment by janusqa** [comment] 2022-09-09 08:20
@JordanHoffman @prokorpio 
After a whole week of research, somehow I ended here.   This solved the problem for me.
THANK YOU!!!!
To me it's the cleanest solution so far.

**Comment by Laravel-elixir** [comment] 2025-02-01 02:24
I finalized the solution https://jquerys.space/questions/how-can-you-create-an-animation-that-plays-forward-on-the-first-click-and-then-reverses-on-the-second
