### ISSUE TITLE
Key warning

### ISSUE THREAD

**Issue by SergeyShablenko** [facebook/react#13506] opened 2018-08-29 11:23 UTC
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

React throws warning

`Each child in an array or iterator should have a unique "key" prop.`

But I don\`t render arrays or fragments

I have a component like this

```jsx
import { Component } from 'react';

class FormContent extends Component {
  render() {
    return this.props.children;
  }
}

export default FormContent;
```

and use it like this

```jsx
import PropTypes from 'prop-types';
import { Children, Component } from 'react';

import Content from './FormContent';
import Actions from './FormActions';

class Form extends Component {
  static propTypes = {
    title: PropTypes.string,
    className: PropTypes.string,
    inline: PropTypes.bool,
    withoutWell: PropTypes.bool,
    disabled: PropTypes.bool,
    onSubmit: PropTypes.func
  };

  static defaultProps = {
    title: '',
    className: '',
    inline: false,
    withoutWell: false,
    disabled: false,
    onSubmit: () => {
    }
  };

  render() {
    const CHILDREN = Children.toArray(this.props.children);

    if (this.props.withoutWell) {
      return <form className={`form${this.props.inline ? '-inline' : '-horizontal'} ${this.props.className}`}
                   onSubmit={::this._handleSubmit}
                   autoComplete="off">
        <fieldset className="container-fluid" disabled={this.props.disabled}>
          {this.props.title.length ? <legend>{this.props.title}</legend> : null}
          {CHILDREN.find(child => child.type === Content)}
          {CHILDREN.find(child => child.type === Actions)}
          <button className="hidden" />
        </fieldset>
      </form>;
    }
    return <div className="well with-shadow well-xs-transparent">
      <form className={`form${this.props.inline ? '-inline' : '-horizontal'} ${this.props.className}`}
            onSubmit={::this._handleSubmit}
            autoComplete="off">
        <fieldset disabled={this.props.disabled}>
          {this.props.title.length ? <legend>{this.props.title}</legend> : null}
          {CHILDREN.find(child => child.type === Content)}
          {CHILDREN.find(child => child.type === Actions)}
          <button type="submit" className="hidden" />
        </fieldset>
      </form>
    </div>;
  }

  _handleSubmit(e): void {
    e.preventDefault();
    e.stopPropagation();
    this.props.onSubmit(e);
  }
}

export default Form
```

The warning tells me that there should be unique key inside of `FormContent`, but I simply wrapped children with my class to split them in future (Form component). How to fix it? 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

Should not show warning

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Chrome: Version 68.0.3440.106 (Official Build) (64-bit)
Ubuntu 18 LTS

**Comment by gaearon** [comment] 2018-08-29 11:57
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

It's probably not a bug in React but it's hard to say because you provided a non-runnable snippet of code. Instead, to get help on reports like this the best thing you can do is to **reduce** your example to the smallest possible code that still reproduces the issue, and then **post** it on a site where it can run, e.g. JSFiddle or CodeSandbox. I’m closing because you didn’t attempt to do this, so we can’t treat it as a bug.

**Closed by gaearon** 2018-08-29 11:57 UTC

**Comment by Froydis** [comment] 2018-08-29 15:49
Den ons. 29. aug. 2018, 13:59 skrev Dan Abramov <notifications@github.com>:
