### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by samkhatri** [facebook/react#22570] opened 2021-10-15 19:16 UTC
### Website or app

https://wayray.com/#how-we-work

### Repro steps

not able to see

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.19.2-20ca9b565

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25708:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:23923:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24083:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:52511:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by MrJoy** [comment] 2021-10-20 00:26
I have 4.20.0 installed, and just ran into the same problem.  It was working fine, and then... boom.  Not sure _precisely_ when it happened -- I was editing code to resolve some errors, then when I went back to try things out in my app...  It was in this state.

**Comment by jstejada** [comment] 2021-10-20 16:23
Looks like this might be a duplicate of #21636 (see [this comment](https://github.com/facebook/react/issues/21636#issuecomment-908971792)), and it has been [reported several times in the past as well](https://github.com/facebook/react/issues?q=is%3Aissue+%22because+a+node+with+that+id+is+already+in+the+Store%22+is%3Aclosed). 

Which makes me think this is not a new issue introduced by v4.20, and is likely a long standing issue. Since it's hard to reproduce and likely due to a race condition it makes it hard to track down.

We'll continue to look into this if we can get a reliable repro case (and if you can provide one that would be super helpful).

In the meantime I'll merge this into  #21636 and mark this as a duplicate.

**Closed as completed by jstejada** 2021-10-20 16:23 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools

**Comment by MrJoy** [comment] 2021-10-21 20:04
Only other note of potential relevance:  When it showed up, my un-ejected CRA app had compile errors and so my code wasn't actually running -- it was just rendering the development-mode error dump.
