### ISSUE TITLE
Perf.printWasted() is showing more instances than actual renders

### ISSUE THREAD

**Issue by KeKs0r** [facebook/react#4462] opened 2015-07-22 14:37 UTC
Hi,

I am trying to analyse the performance of my app. I use Perf.printWasted heavily and face some weird behaviour.

I am usually activating Perf only for a single transition. When doing this for going from one view to another, I get a very long view of Performance waste. I was digging into it and tried to get rid of one single instance:
![image](https://cloud.githubusercontent.com/assets/2970814/8827880/76fa6a6e-308f-11e5-984d-8cddb5753f54.png)

In the following example I am focusing on Index 1 ("betround_games >game") Which supposedly rerenders 27 times without changing the dom.

Since I am using PureRender, I was curious how often the render of betround_games and my game component is triggered. So i added a counter to both components render with the result:
betround_games render : 1
games render:  9 (for 9 different games)

So every instance is exactly rendered once. I also saw that sometimes adding new nodes is still counting as wasted time as shown in #1931

That would explain 9 wasted instances, but does not explain why Perf is counting 27 instances of wasted time.

Either I am understanding the measurement wrong or I make some wrong assumptions.

**Comment by jimfb** [comment] 2015-07-22 17:15
@KeKs0r If you could create a simple example that demonstrates the issue, that would be helpful in helping us investigate.

**Comment by gaearon** [comment] 2016-05-23 16:41
I don’t know if this specific case is still accurate, but ReactPerf has been rewritten from scratch in 15.1.0, so this particular bug report is very likely no longer accurate. Since there is no described way to reproduce, I’m closing, but feel free to follow up if this still happens after 15.1.0!

**Closed by gaearon** 2016-05-23 16:41 UTC
Labels: Component: Addons / Perf, Component: Addons / TransitionGroup
