### ISSUE TITLE
Developer Tools issues

### ISSUE THREAD

**Issue by Zahraamirii** [facebook/react#22845] opened 2021-11-29 11:53 UTC
Hi. I installed React Developer Tools but yet I have not access to component in developer tools. Even thought I allowed access to file URLs but I still have not accessibility to React Developer Tools. Please help me.

**Comment by akgupta0777** [comment] 2021-11-29 16:08
Please list these details for further investigation
- **Devtools version** 
- **Browser extension or Standalone app ?**
- **Website or app for reproducing**
- **Browser name**
- **By any reason you have multiple devtools extensions installed ?**

**Comment by bvaughn** [comment] 2021-12-04 18:49
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-12-04 18:49 UTC
