### ISSUE TITLE
refs is undefined

### ISSUE THREAD

**Issue by SylarRuby** [facebook/react#7124] opened 2016-06-26 08:38 UTC
**React 15.1.0**

```
var React = require("react")

var Foo = React.creactClass({
  render: function(){
   
    console.log(this.refs.bar");
    return(
      <div><input ref="bar" /></div>
    )
  }
});
module.exports = Foo;
```

Im getting `undefined` in console.

What could be the possibilities? I'm also using [react-rails](https://github.com/reactjs/react-rails).

**Comment by keyanzhang** [comment] 2016-06-26 08:56
Hey,

Your `console.log` call happens before the return statement. In other words, `render()` hasn't returned anything yet while you are accessing `this.refs.bar`, so `refs` hasn't been available. You can take a look at the examples here: https://facebook.github.io/react/docs/more-about-refs.html#a-complete-example.

Since this is not a bug I'm going to close it out. If there's still anything unclear, StackOverflow would be a better place to ask about this. Thanks!

**Closed by keyanzhang** 2016-06-26 08:56 UTC
