### ISSUE TITLE
catching nulls and undefineds in createClass?

### ISSUE THREAD

**Issue by Pomax** [facebook/react#3486] opened 2015-03-23 17:23 UTC
Right now something like this is going by pretty much uncaught until it causes terrible breakage:
```
var Link = Collection.link; // oh no, I meant ".Link", not ".link"! Link is now "undefined"
var Thing = React.createClass({
...
render: function() { return <Link/>; }
...
});
```
Similarly, the following will "work" until an undef'd mixin is actually used:
```
var Mixin = 
var Thing = React.createClass({
...
mixins: [
  Collection.minkeyMixim; // Crap, another typo! Mixin is now "undefined"
],
...
});
```
The mixins issue I suspect is something that createClass can trivially test before accepting the component definition (check for an `obj.mixins`, if extant, check that every element in it resolves to an object (rather than `false`, `undefined`, `null`, "a string", etc), the bad element situation might also be doable inside createClass, checking that all the elements that are used inside of an element in fact exist before letting the createClass call succeed. I suspect it can, but less sure than the mixin check.

**Comment by spicyj** [comment] 2015-03-23 19:49
Your first request is a dupe of #1302 which is embarrassingly still open with an umnerged PR. Your second suggestion isn't really possible without advanced static analysis but is something that http://flowtype.org/ could warn about if it doesn't already.

**Closed by spicyj** 2015-03-23 19:49 UTC

**Comment by Pomax** [comment] 2015-03-23 20:33
I'm not sure that's true, in plain React JS the library will see `React.createElement("Link")`, but won't see an entry for that thing in its table of elements, so it could certainly report "trying to render an element that was never registered" or the like? It'd still be an error in the console rather than during JSX/bundling/whatever, but that'd still go a long way to narrowing down where things are wrong

**Comment by spicyj** [comment] 2015-03-23 20:41
When referencing an existing component, it'll actually just be `React.createElement(Link)` and you can't tell statically what that Link refers to. createElement can warn when called, of course, which is what I think we do already.
