### ISSUE TITLE
Problem with updating component state in the "Components" tab of React Developer Tools -  Chrome extension

### ISSUE THREAD

**Issue by marcinszymaszek** [facebook/react#16890] opened 2019-09-25 12:13 UTC
Hello everyone,

I have a problem with Chrome extension -  React Developer Tools, if I change component's state it's not changing in the dev tools window (as in the screenshot below) I am only able to see arrows with title "Reset value". 
Does somebody know how it could be fixed?

Thanks a lot for help!

![Zrzut ekranu z 2019-09-25 14-06-22](https://user-images.githubusercontent.com/40744326/65599624-8e7e9d00-df9e-11e9-9f5e-4be249278c6d.png)

**Comment by bvaughn** [comment] 2019-09-25 20:43
Duplicate of #16843

Fix will be going out sometime this afternoon, probably. Sorry for the inconvenience.

**Closed by bvaughn** 2019-09-25 20:43 UTC
Labels: Component: Developer Tools, Resolution: Duplicate
