### ISSUE TITLE
Fail to update DOM style attribute

### ISSUE THREAD

**Issue by testerez** [facebook/react#8362] opened 2016-11-20 17:18 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
style attribute is not updated correctly when we set `padding` and `paddingTop` at the same time and then re-render with only `padding`. Same issue with `border`. I suppose that it would be the same with `margin` (not tested)

Example: http://codepen.io/testerez/pen/pNRQjW?editors=0010

**What is the expected behavior?**
The DOM element style should be the last rendered one and should not be affected by the previous style value.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on chrome 54 with React 15.4 and 15.3.2

**Comment by linmic** [comment] 2016-11-21 02:29
This issue has been reported several times, and currently there's no perfect solution for it. The [latest discussion](https://github.com/facebook/react/issues/6348).

**Comment by testerez** [comment] 2016-11-21 02:33
Ok, thanks for the reply.

**Comment by Aweary** [comment] 2016-11-21 04:27
Thanks @linmic! Closing as a duplicate of https://github.com/facebook/react/issues/6348, try and direct any future discussion there 👍

**Closed** 2016-11-21 04:28 UTC
