### ISSUE TITLE
Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 4"

### ISSUE THREAD

**Issue by eunsookim** [facebook/react#16534] opened 2019-08-22 00:11 UTC
PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.5-5441b09

Call stack: at d (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:5744)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:8526)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51:275512)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51:4368)

Component stack: in bi
    in div
    in div
    in div
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by bvaughn** [comment] 2019-08-23 14:48
Looks like this is a duplicate of #16412 that doesn't add any new info (no steps to reproduce, etc) so I'm going to close it.

**Closed by bvaughn** 2019-08-23 14:48 UTC
