### ISSUE TITLE
Bug: `useInsertionEffect()` cleanup function does not fire if a component is wrapped in React.lazy

### ISSUE THREAD

**Issue by JonnyBurger** [facebook/react#26670] opened 2023-04-19 09:57 UTC
React version: 18.2.0

## Reproduction

```ts
import { lazy, useState, useInsertionEffect, Suspense } from "react";

export default function App() {
  const [show, setShow] = useState(false);

  return (
    <div>
      <Suspense>{show ? <LazyComp2 /> : <LazyComp1 />}</Suspense>
      <button onClick={() => setShow((s) => !s)}>Toggle</button>
    </div>
  );
}

const MyComp = () => {
  useInsertionEffect(() => {
    console.log("start1");
    return () => {
      console.log("stop1");
    };
  }, []);
};

const MyComp2 = () => {
  useInsertionEffect(() => {
    console.log("start2");
    return () => {
      console.log("stop2");
    };
  }, []);
};

const LazyComp1 = lazy(() => Promise.resolve({ default: MyComp }));
const LazyComp2 = lazy(() => Promise.resolve({ default: MyComp2 }));
```

Click the button twice.

Link to code example:

https://codesandbox.io/s/focused-burnell-ewgso1?file=/src/App.js:0-773

## The current behavior

Logs:

```
start1
start2
stop2
start1
```

## The expected behavior

```
start1
stop1
start2
stop2
start1
```

This is also the behavior of `useLayoutEffect` if not in strict mode.

**Comment by Andarist** [comment] 2023-05-23 08:53
I was just about to report the same issue (my repro case can be found [here](https://stackblitz.com/edit/react-ts-tjuru8?file=App.tsx,Page2.tsx,Page1.tsx), it's prepared based on @jmca's repro for [the issue](https://github.com/emotion-js/emotion/issues/3038) caused by this - but it's essentially the same repro as yours).

I think that `useInsertionEffect` is essentially the same as `useLayoutEffect`, it's just that they have a "higher priority" and they are executed first, in a batch, before `useLayoutEffect`s. So I'm heavily leaning towards your conclusion - this is a bug in React. All other semantics of layout effects should be shared between `useInsertionEffect` and `useLayoutEffect` (such as [mounting/unmounting them appropriately in Offscreen components](https://github.com/facebook/react/pull/21386), their [reappearing](https://github.com/facebook/react/pull/21898) and more)

**Comment by Andarist** [comment] 2023-05-23 15:31
@gaearon yes! I actually started to work on a PR locally - it's very draft-ish and I only fixed one of the discrepancies so far. Gonna open a draft PR later today.

**Comment by Andarist** [comment] 2023-05-23 17:35
To rephrase what the observed issue here is:
1. insertion effects are not disconnected when the suspended subtree gets hidden
2. they are also not disconnected when a different subtree gets finally rendered (when Suspense resumes~)
3. to get them to disconnect we need to "revisit" the old component and switch away from it **without** suspending.
4. this doesn't match how any other type of effects work. I'd expect those effects to get disconnected in the similar vein as layout effects are but if that's not desirable for some reason then they likely should be disconnected just like passive effects (or using some different semantics of their own but the bottom line is that they should be disconnected *at some point*)

**Comment by sebmarkbage** [comment] 2023-08-19 22:12
This is intentional to avoid layout thrash when things are hidden and restored. It's also to allow for hidden trees to be able to do early preemptive layout calculations for hidden trees so that they can be instantly restored.

**Comment by Andarist** [comment] 2023-08-19 22:21
Hmm, but that cleanup has to be called at some point in time - when that is?

**Comment by sebmarkbage** [comment] 2023-08-20 12:43
When the Suspense boundary itself is committed and deleted or if an update changes it to no longer be visible. I could imagine the second case being a bug since it’s a thing we typically don’t model at all.

**Comment by lubieowoce** [comment] 2023-08-20 13:30
> When the Suspense boundary itself is committed and deleted

unless i'm misunderstanding, this doesn't seem to be the case
https://stackblitz.com/edit/react-ts-3vk942?file=App.tsx,Page2.tsx,Page1.tsx

Repro: press "Go to Page 1", "Go to Page 2", "Just unmount the whole thing". the suspense boundary and the suspending children below all get destroyed, but the background stays pink (i.e. Page1's `useInsertionEffect` is not actually cleaned up)

**Comment by lpolito** [comment] 2023-12-13 20:20
Was there any movement on this? I ran into the same issue linked by @Andarist , specifically with Emotion's Global component not calling the clean up on unmount.

In my case all components are wrapped inside of React.lazy() because that's how we have our page route components set up (all pages being lazily loaded).

**Comment by guillaumebrunerie** [comment] 2023-12-13 21:04
For what it's worth, styled-component worked around this bug by simply using `useLayoutEffect` instead of `useInsertionEffect`. Maybe Emotion could do the same in the mean time?

**Comment by fsjsd** [comment] 2024-03-08 10:04
Any movement on this one?

**Comment by owenashurst** [comment] 2024-04-06 20:26
I had to downgrade to React 17.0.2 to resolve this for now.

**Closed** 2024-09-17 18:01 UTC
Labels: Type: Bug

**Comment by Andarist** [comment] 2024-09-18 07:27
@rickhanlonii I somewhat doubt that a PR to Relay fixed this issue 😅
