### ISSUE TITLE
Error: "Minified React error 

### ISSUE THREAD

**Issue by jpelaa** [facebook/react#16921] opened 2019-09-27 09:32 UTC
An error was thrown: "Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "

The error was thrown at hi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:61172)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:256084
    at Vo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:256125)
    at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58828)
    at Jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103390)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89163)
    at Ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89088)
    at ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86037)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45275
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:3691)

**Comment by threepointone** [comment] 2019-09-27 12:04
The error at the link is clear about the error. 

This issue has no other information, so I’m going to close it. Happy to discuss if you can share more details.

**Closed by threepointone** 2019-09-27 12:04 UTC

**Comment by bvaughn** [comment] 2019-09-27 18:07
@jpelaa - Seems like this issue might be the same as is being reported in #16925 and #16926.

It's been closed since it doesn't provide much info. It would be helpful though if you were able to fill in some of the missing details:

* What operating system and browser/version are you using?
* What were you doing when this error happened? (Is it happening for a specific website? or after you've clicked a specific button?)

I am not able to reproduce the error locally and would greatly appreciate help in figuring out how to.

**Comment by bvaughn** [comment] 2019-09-28 00:13
4.1.2 has just been published to NPM and uploaded to the Chrome+Firefox stores with a fix for this issue (still assuming it is the same as was reported in #16926 and #16925). Sorry for the inconvenience.

**Comment by jpelaa** [comment] 2019-09-28 09:28
Thanks,Man. I can check this.
Happy coding!

Jayaprakash E

{
    name     : "Jayaprakash E",
    title    : "Front-end Developer",
    company  : "Doodleblue",
    location : "Chennai,IN"
}
