### ISSUE TITLE
Children forEach filters functions

### ISSUE THREAD

**Issue by neytema** [facebook/react#9821] opened 2017-05-31 07:36 UTC
**React v15.5.4**

Unexpected behaviour of `React.Children.forEach` – silently filters functions.

**Current behavior:**

```jsx
const element = (
  <div>
    {() => {}}
    {() => {}}
  </div>
);
console.log(React.Children.toArray(element.props.children))
// Output: []
```

**Expected behavior:**

Children.forEach should throw *Invariant* error then *function* type child is met.

or

Children.forEach shouldn't filter *function* type children.

**Comment by ahlusar1989** [comment] 2017-05-31 13:03
🤔 @neytema I am not able to reproduce this. What browser are you using?

**Comment by frankalbenesius** [comment] 2017-05-31 21:16
Hey @neytema, I did [some experimenting](https://codepen.io/alberknocker/pen/Emqdgj) and it appears that all React.Chilrden utilities filter down to just components children.

It's not totally clear from the [React.Children docs](https://facebook.github.io/react/docs/react-api.html#react.children) if that's the intended behavior, but I think it might be. But I'm no React expert so I'm not sure.

It looks like you could just use the "children" prop as an array normally if you'd like to iterate through the functions, though.

**Comment by neytema** [comment] 2017-05-31 23:45
@ahlusar1989 nodejs v6.10.3

@frankalbenesius I am concerned about inconsistency..

If you'd pass an *object* type child `React.Children.forEach` will throw 'Objects are not valid as a React child' error. Functions are not valid React child also. As far as I know.

**Object example:**

```jsx
const element = <div>{{}}</div>;
React.Children.toArray(element.props.children);
// throws 'Objects are not valid as a React child (found: object with keys {}).'
```

And you can't simply use children as array because it is not always an array or not a flat one.

**Comment by ahlusar1989** [comment] 2017-06-03 11:16
@neytema I understand. Referencing the above example, you would need to pass a string type or React component(created by `React.createElement`) or array type of React elements; type checking is the only means for preventing the above error, if I am not mistaken.

**Comment by danburzo** [comment] 2019-03-26 06:01
Landed here because I couldn't get functions as children to work with `React.Children` methods. As per https://github.com/facebook/react/issues/11888, this is intentional and I guess this issue can be closed with the same resolution?

**Closed** 2022-02-22 08:58 UTC
Labels: Type: Feature Request, Type: Discussion
