### ISSUE TITLE
Suggestion: [eslint-plugin-react-hooks] - exhaustive-deps allow configure `isStableKnownHookValue` for own hooks

### ISSUE THREAD

**Issue by gdbd** [facebook/react#24112] opened 2022-03-17 11:55 UTC
Hi, i have example of own defined hook which returns always memorized callback `setValue`:

**Problem**
```
   const [value, setValue] = useAppState( ... );

```
Then `setValue` used in hook which required deps, for example useEffect:

```
    useEffect(() => {
        if (value != 'a') {
            setValue('a');
        }
    }, [value]);
```

But unlike 'useState' this generates an error:

![image](https://user-images.githubusercontent.com/5655858/158798838-82fb7ffe-9907-4db2-8276-3230a68610a8.png)

I am found source which contain function to check this here:

https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js

**Suggestion**
Add configuration options to set own hooks to be handled as out of the box

**Comment by vkurchatkin** [comment] 2022-03-17 19:06
` additionalHooks`  defines hooks that have deps and are subject to exhaustive-deps rules. It works because a lot of hooks have the same signature : `useHook(fn, deps)`. 

> my suggestion to parameterize these names

That would only work for hooks that work exactly like `useState` and `useReducer`, i. e. they return an array where only the second element is stable. What if the first element is stable? What if the whole value returned from the hook is stable?

**Comment by gdbd** [comment] 2022-03-18 07:34
> `additionalHooks` defines hooks that have deps and are subject to exhaustive-deps rules. It works because a lot of hooks have the same signature : `useHook(fn, deps)`.

there is not my question, it is good and i am know it



> That would only work for hooks that work exactly like `useState` and `useReducer`, i. e. they return an array where only the second element is stable. What if the first element is stable? What if the whole value returned from the hook is stable?

this is not my responsibility to think about, contributors can decide based on them knowledge. Just for example:

```
      'react-hooks/exhaustive-deps': [
                    2,
                    {
                        knownHooks: '(useAppState($stable,$stable))',
                    },
                ],
```

@vkurchatkin, what is your real question or reason to ask?

**Comment by hqnhqh** [comment] 2022-03-19 13:00
fuckiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiing usa

**Comment by sweetliquid** [comment] 2022-03-22 16:18
I like this

**Comment by scottrippey** [comment] 2022-03-23 20:08
I absolutely would love this feature.
As the creator of many custom hook libraries, it would be wonderful to mark certain return values as "stable", the way `useRef/useState/useReducer` work.

I also totally understand that this configuration could be tricky, since it's not just a string-matching algorithm.  However, 99% of the time, I'm either mimicking `useState` style (where `result[1]` is stable), or `useRef` style (where the entire return value is stable).  So I would certainly be happy with a configuration that simply allows me to opt-in to one of these 2 styles.
For example:
```
{
  "rules": {
    // ...
    "react-hooks/exhaustive-deps": ["warn", {
      // all these return fully-stable objects, like useRef:
      "stableHooks": "useValueRef|useCallbackRef|useNavigate",

      // all these return a stable 2nd argument, like useState/useReducer:
      "stableHookTuples": "useAppState|useLocation" 
    }]
  }
}
```

These options should be used carefully, obviously.  And the documentation should highlight the importance of this.  
But it would certainly help to reduce the amount of unnecessary dependencies, especially in codebases that have a lot of custom hooks that work hard to ensure stable references.

**Comment by scottrippey** [comment] 2022-03-24 17:49
Also, to further the point ... the current `additionalHooks` configuration also makes the assumption that the custom hook follows the `hook(fn, deps)` signature.  
It's really helpful that `additionalHooks` lets us extend the rules, even though it only works for a specific (common) scenario.
So it would make perfect sense to have `stableHooks` and `stableStateHooks` for extending the rules for those specific (common) scenarios.

**Comment by scottrippey** [comment] 2022-03-24 17:56
This appears to be a duplicate of https://github.com/facebook/react/issues/22539; I suggest we consolidate

**Comment by gdbd** [comment] 2022-03-25 11:33
@scottrippey it looks like eslint-plugin-react-hooks team is not interested in any suggestions, because yet no official response from them. So its looks like we need use selfmade fork from @[grncdr](https://github.com/grncdr)

**Comment by eps1lon** [comment] 2022-05-17 18:12
Duplicate of https://github.com/facebook/react/issues/16873

**Closed by eps1lon** 2022-05-17 18:12 UTC
Labels: Status: Unconfirmed
