### ISSUE TITLE
Error: "Cannot read property 'duration' of undefined"

### ISSUE THREAD

**Issue by shiftyp** [facebook/react#18798] opened 2020-05-01 12:41 UTC
Describe what you were doing when the bug occurred:
1. Add interaction tracing with unstable_trace
2. Record a profile, navigate to Profiler > Profiled Interactions
3. Error appears when scrolling view or immediately

![Kapture 2020-05-01 at 8 37 44](https://user-images.githubusercontent.com/131928/80805899-3688c400-8b87-11ea-88ca-3a7ae7de3589.gif)
---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:344360
    at Array.map (<anonymous>)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:344166
    at ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59620)
    at Ll (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:109960)
    at qc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102381)
    at Hc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102306)
    at Vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102171)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:98781)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:46014

Component stack: in Unknown
    in Unknown
    in div
    in div
    in n
    in div
    in bc
    in div
    in n
    in div
    in vc
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by chiragswadia** [comment] 2020-05-01 15:55
Looks like duplicate of https://github.com/facebook/react/issues/18786 🤔

**Comment by shiftyp** [comment] 2020-05-01 16:32
Here is a deployed repro case: https://react-example1.s3.amazonaws.com/index.html

Steps:

1. Load above URL
2. Open React Profiler
3. Start recording
1. Hit the "Fetch" button a few times
4. Stop Recording
5. navigate to the Profiled Interactions tab
6. Scroll down to the bottom of the list. The error should occur as you approach the bottom of the view

You can find the code for the case here: https://github.com/shiftyp/object-hooks/blob/experimental-tracing/packages/object-hooks/src/useInstances.ts#L37

**Comment by bvaughn** [comment] 2020-05-01 22:10
Thanks for the repro case, @shiftyp!

**Comment by bvaughn** [comment] 2020-05-06 21:40
@shiftyp Did you forget to commit something?

Checking out the `experimental-tracing` branch and running `yarn install && yarn start` throws:
> Cannot resolve dependency 'object-hooks'

**Comment by bvaughn** [comment] 2020-05-08 00:05
Disregard. The remote repro was sufficient.

Thanks for sharing it!

**Closed** 2020-05-08 00:07 UTC
Labels: Component: Developer Tools, Type: Bug
