### ISSUE TITLE
*bug* style undefined in setValueForStyles in Edge

### ISSUE THREAD

**Issue by desbrowne** [facebook/react#13256] opened 2018-07-24 03:19 UTC
**What is the current behavior?**

The minimal repro can be viewed at https://jsfiddle.net/vr0mb5gw/
Issue reproduced with React 16.4.1 using Edge (Windows 10 1803 - 17134.165) (not tested on previous framework and browser versions).

The React component is rendering 
```
<svg>
	<div style={{ width: '50%' }}>
		<h1>Hello, {this.props.name}</h1>
	</div>
</svg>
```

Which generates the following errors: 
```
 SCRIPT5007: Unable to set property 'width' of undefined or null reference

The above error occurred in one of your React components:
    in h1 (created by App)
    in div (created by App)
    in svg (created by App)
    in App
```

The <div inside the <svg element isn't really legal but seems to work in browsers other than Edge. We ran into this issue because a third party React component was rendering a <div instead of <g if we didn't specify the correct prop.

In Edge the <div is created using the <svg namespace (as that is the parent's namespace). Because of this the <div doesn't have a style property. So when the function setValueForStyles in CSSPropertyOperations.js tries to set any styles the style var is undefined.

**What is the expected behavior?**
Maybe nothing needs to change, HTML elements aren't valid so user error right? This issue could be enough to document it for others?

The bug was certainly not obvious as the error message is unrelated to the fact that the elements are using different namespaces. The fact that the invalid <div was produced by a third party React component meant that it was even less obvious why this failed. The React component error (above) shows the element order but if you are not familiar with html elements not being allowed in svg then the issue isn't obvious.

Currently if you place a <form element inside another <form element you will get a warning from the React development build so there is an argument that other misuses of element order generate a warning so maybe this should?

**Comment by aweary** [comment] 2018-07-24 05:11
Thanks for the report @desbrowne!

This does appear to be expected behavior. There's no "div" element in the SVG namespace, so this is essentially undefined behavior dependent on how different browsers handle that.

We do want to add a warning for invalid nesting inside SVG tags. That's being tracked in https://github.com/facebook/react/issues/11013. We'd love a PR for it 🙂

Since this is expected and we already have an issue tracking our preferred solution I'm going to close this. Let me know if you have any questions!

**Closed by aweary** 2018-07-24 05:11 UTC
