### ISSUE TITLE
<input> Ctrl+Z broken on a-synchronous setState()

### ISSUE THREAD

**Issue by rogierschouten** [facebook/react#5807] opened 2016-01-08 11:07 UTC
The example below is a simple page with just one <input> element. Typing in the <input> goes just fine. However, Ctrl+Z (undo) is broken in Chrome and IE:  in Chrome, it doesn't remove the first typed letter. In IE, it actually only adds stuff.

``` javascript
var React = require("react");

var MyInput = React.createClass({
    render: function() {
        var _this = this;
        return (React.createElement("input", {
            "onChange": function (event) {
                var value = event.target.value;
                setTimeout(function () {
                    _this.setState({ value: value });
                }, 0);
            }, 
            "type": "text",
            "value": this.state.value
        }));
    }
});

ReactDOM.render(
  React.createElement(MyInput, null),
  document.getElementById('all-content')
);
```

The culprit here is my a-synchronous setState() call - remove the setTimeout() and it works properly. However it is React that breaks this: the browsers can handle a-sync updates just fine without React:

``` html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <script>
        function onInput(event) {
            var value = event.target.value;
            var input = document.getElementById("myinput");
            setTimeout(function() {
                input.value = value;
            }, 0);
        }
    </script>
</head>
<body>
    <input type="text" id="myinput" onInput="onInput(event)">
</body>
</html>
```

This example works just fine, even with the setTimeout() present.

The above are simplified examples, not my actual use case (a flux-like store framework that sends updates a-synchronously in an animation frame / React.addons.batchedUpdates to be able to condense change events and improve performance).

**Comment by jimfb** [comment] 2016-01-08 18:07
I'm a little surprised it works fine without React but fails with React.

@rogierschouten @syranide @spicyj Any thoughts on why?

**Comment by syranide** [comment] 2016-01-08 20:43
@jimfb Me too... I played around with a little bit earlier. Intuitively it probably has to do with the specific events used by React, Chrome is probably broken when setting the value during some of the other events.

Anyway, @rogierschouten you definitely do not want to defer setting the value, it will break your selection and introduces other subtle issues. Controlled inputs work on the idea that setting it to the value it would have normally become does **not** actually update the value, so the native behavior is kept (and selection is intact). If you deviate from that React has to update the value and then there is no knowledge about what to do with the selection. When you defer you effectively break this because you explicitly tell it to restore it to the previous value and later set it to the new (but there is no information about the selection now).

**Comment by rogierschouten** [comment] 2016-01-08 23:48
@syranide  I totally agree with you it should be synchronous. I'm between a rock and a hard place architecturally speaking. The typical Flux architecture with its synchronous change events suffers from maintainability issues in larger systems with store interdependencies.
Queueing events solves a lot, and I would ideally like to flush my event queue at the end of every DOM event - in effect making value updates synchronous. I was hoping to hook into React to accomplish that, but so far that hasn't worked. My second bet was the animation frame approach.  For now I will actually flush events in every DOM event handler.

**Comment by gaearon** [comment] 2017-10-03 23:17
Closing as this works as designed.

If you use controlled inputs, you need to ensure you flush the value changes before React exits the event handler.

**Closed by gaearon** 2017-10-03 23:17 UTC
