### ISSUE TITLE
Error: "Could not find commit data for root "26047" and commit 5"

### ISSUE THREAD

**Issue by nassif7** [facebook/react#16510] opened 2019-08-20 12:12 UTC
PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.5-5441b09

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:16721)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51:293849)
    at Al (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51:294084)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51:4368)

Component stack: in Al
    in div
    in div
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by bvaughn** [comment] 2019-08-20 15:54
Closing as a duplicate of #16446, but as the issue template says...

> PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

...instructions would be helpful! 😄 🙇

**Closed** 2019-08-20 15:56 UTC
