### ISSUE TITLE
Cannot Found Out The Error

### ISSUE THREAD

**Issue by Rajan-max** [facebook/react#21206] opened 2021-04-08 12:11 UTC
I have already tried all the solutions mentioned still none of them works.Neither the reasons are matching with my error..Please Help
![Screenshot (6)](https://user-images.githubusercontent.com/51814768/114024440-c8b74300-9893-11eb-8633-2cd949e4cd3c.png)

**Comment by eps1lon** [comment] 2021-04-08 12:41
It doesn't look like this bug report has enough info for one of us to reproduce it. Though you might want to take a look at https://github.com/facebook/react/issues/13991 which looks similar.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by abhi12123** [comment] 2021-04-09 17:13
Did you try using hooks inside Class component. In that case it might have run into this error. Can you share the code by any means as @eps1lon have mentioned ?

**Comment by saharshg** [comment] 2021-04-10 19:44
This could also happen for multiple reasons which are already stated in the error itself, but if you need any specific resolution then please provide the code example.

**Comment by Rajan-max** [comment] 2021-04-12 18:41
import React, { useState } from 'react'
import Base from '../core/Base'
import { isAuthenticated } from '../auth/helper'
import { Link } from 'react-router-dom'
import { createCategory } from './helper/adminapicall'

const AddCategory = () => {
	const [name, setName] = useState('')
	const [error, setError] = useState(false)
	const [success, setSuccess] = useState(false)

	const { user, token } = isAuthenticated()

	const goBack = () => {
		return (
			<div className='mt-5'>
				<Link className='btn btn-sm btn-success mb-3' to='/admin/dashboard'>
					Admin Home
				</Link>
			</div>
		)
	}

	const handleChange = (event) => {
		setError('')
		setName(event.target.value)
	}

	const onSubmit = (event) => {
		event.preventDefault()
		setError('')
		setSuccess(false)

		//backend request fired
		createCategory(user._id, token, { name }).then((data) => {
			if (data.error) {
				setError(true)
			} else {
				setError('')
				setSuccess(true)
				setName('')
			}
		})
	}

	const successMessage = () => {
		if (success) {
			return <h4 className='text-success'>Category created successfully</h4>
		}
	}

	const warningMessage = () => {
		if (error) {
			return <h4 className='text-success'>Failed to create category</h4>
		}
	}

	const myCategoryForm = () => {
		return (
			<form>
				<div className='form-group'>
					<p className='lead'>Enter the category</p>
					<input
						type='text'
						className='form-control my-3'
						onChange={handleChange}
						value={name}
						autoFocus
						required
						placeholder='For Ex. Summer'
					/>
					<button onClick={onSubmit} className='btn btn-outline-info'>
						Create Category
					</button>
				</div>
			</form>
		)
	}

	return (
		<Base
			title='Create a category here'
			description='Add a new category for new tshirts'
			className='container bg-info p-4'
		>
			<div className='row bg-white rounded'>
				<div className='col-md-8 offset-md-2'>
					{successMessage()}
					{warningMessage()}
					{myCategoryForm()}
					{goBack()}
				</div>
			</div>
		</Base>
	)
}

export default AddCategory

Actually one component is rendering very well and during this component those errors are being popped out.

**Comment by bvaughn** [comment] 2021-04-13 15:43
@Rajan-max This is not a complete repro. This shows the component that's related to the error, but not how it's being used, so it's not possible for us to troubleshoot the porblem.

Please provide something we can actually run (like a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub).

**Comment by bvaughn** [comment] 2021-05-04 13:38
Closing due to lack of repro info.

**Closed by bvaughn** 2021-05-04 13:38 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
