### ISSUE TITLE
Cant't mount text node components

### ISSUE THREAD

**Issue by vhiroki** [facebook/react#9667] opened 2017-05-11 19:46 UTC
Cant't mount text node components in a child window in **IE11** and **Edge**.

http://jsfiddle.net/69z2wepo/78456/

```jsx
const SomeComponent = () => (
  <div>
    <span>This will be displayed</span>
    <br/>
    This will not be displayed (This is the text node that will break the mounting)
    <br/>
    <span>This will not be displayed because the mounting has stopped</span>
  </div>
);

class PopoutWindow extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      openedWindow: null
    };
  }

  componentDidMount() {
    var win,
        container,
        openedWindow = {};

    var onLoadHandler = () => {
      container = win.document.createElement('div');
      container.id = 'test';
      win.document.body.appendChild(container);
      ReactDOM.render(this.props.children, container);
      openedWindow.update = newComponent => {
        ReactDOM.render(newComponent, container);
      };
      this.setState({openedWindow: openedWindow});
    };

    win = window.open('about:blank', 'Test', 'width: 600px; height: 600px'); 

    win.onload = onLoadHandler;

    // call onload handler in case it's not been called
    setTimeout(onLoadHandler, 0);
  }

  componentDidUpdate() {
    this.state.openedWindow.update(this.props.children);
  }

  render() {
    return <div />;
  }
}

ReactDOM.render((
  <PopoutWindow title="Test">
    <SomeComponent />
  </PopoutWindow>
), container);
```

It throws the following error: `SCRIPT87: Invalid argument.`

Debugging the stack trace I've noticed that the fragment creation (`ownerDocument.createDocumentFragment()`, line 7923, `react-dom.js`) is resulting in a malformed fragment. Later, when trying to append this "malformed" fragment to the DOM (`parentNode.insertBefore(tree.node, referenceNode)`, line 1623, `react-dom.js`), it fails and throws that error.

I tried to replace the fragment by a span element for this specific case (IE11 and child window) and it worked. Could this be a solution?

**Comment by gaearon** [comment] 2017-07-11 13:18
Tagging this as a bug although not sure if it's on our side or not. Still needs someone to investigate.

**Comment by kenotron** [comment] 2017-09-14 19:54
@gaearon after digging into this a bit more, I found that it is due to Edge / IE does not work with documentFragment append when working with children window. As for the reason for this, I don't know... but if React can provide a workaround for these browsers, it would be nice :)

**Comment by kenotron** [comment] 2017-09-15 19:44
I'm working a fix for this...

**Comment by kenotron** [comment] 2017-09-16 17:47
Quick update here on this bug: I've found the root cause for React 15 AND 16. I created a PR for master against the unused 15 APIs, so I closed that one. I created a new PR for the 16 fiber reconciler code instead.

**Closed** 2017-09-22 23:08 UTC
Labels: Type: Bug
