### ISSUE TITLE
Can the componentDidCatch method be called via react-test-renderer

### ISSUE THREAD

**Issue by davewthompson** [facebook/react#12803] opened 2018-05-14 22:19 UTC
**Do you want to request a *feature* or report a *bug*?**
May I request a feature?

**What is the current behavior?**
componentDidCatch is not handled by the _react-test-renderer_

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
We'd like to test our componentDidCatch handler inside Jest and Enzyme. Is there any way we could make the behaviour of the componentDidCatch handler configurable?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest version of both React and the Enzyme framework.

**Comment by gaearon** [comment] 2018-08-02 19:16
Test renderer should support `componentDidCatch`.

**Comment by gaearon** [comment] 2018-08-02 19:16
If it doesn't please provide a reproducing example.

**Comment by gaearon** [comment] 2018-08-06 19:30
Closing since there's no reproducing case.

**Closed by gaearon** 2018-08-06 19:30 UTC
Labels: Component: Test Renderer, Resolution: Needs More Information
