### ISSUE TITLE
No cursor in input element when onfocus uses stopPropagation in Firefox 54

### ISSUE THREAD

**Issue by jan0e** [facebook/react#10232] opened 2017-07-20 09:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the onFocus event handler of an <input> element calls stopPropagation, the cursor of the <input> element as well as the selection is not shown in Firefox 54.0.1 64 Bit. 

**Steps to reproduce**
Create an <input> element and call stopPropation() in the onFocus event handler. 
``` 
handleOnFocus(e) {
  e.stopPropagation();
}
render() {
  return <input onFocus={this.handleOnFocus} type="text" />;
}
``` 
[JSFiddle](https://jsfiddle.net/y36vcoLb/1/)

**What is the expected behavior?**
Expected is that the cursor and the selection of text is visible in the <input> element, as seen in Chrome 58 64-Bit and Edge 38.
 
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I have seen this issue in React 15.5.4 and 15.6.1 in Firefox 54.0.1 64-Bit on Windows 10

**Comment by gaearon** [comment] 2017-07-20 09:35
Have you verified that the issue does not occur without React?

**Comment by jan0e** [comment] 2017-07-20 09:57
Yes, see [JSFiddle](https://jsfiddle.net/y6trqg1m/)

**Comment by aweary** [comment] 2017-09-15 21:44
Hey, @jan0e! That example without React isn't actually representative of what React does with event listeners. React has a single listener registered on the `document`, which listeners for these events during the capture phase and then simulates the bubbling/capture phases you'd expect.

This is an issue with Firefox related to `stopPropogation` during the capture phase. See this issue in Bugzilla: 

[Calling event.stopPropagation() in the capture phase of focus events prevents the cursor appearing in input elements.
](https://bugzilla.mozilla.org/show_bug.cgi?id=509684)

[Here is a JSFiddle](https://jsfiddle.net/9w1q2v8z/) that registers a capture listener and reproduces the issue without React. Since this is a reported Firefox bug, and working around this would require a major change to React's event system, I'm going to close this out.

Thanks for bringing this to our attention!

**Closed by aweary** 2017-09-15 21:44 UTC

**Comment by stefnotch** [comment] 2023-05-17 06:53
Update from the future: This Firefox bug seems to have been fixed.
