### ISSUE TITLE
Bug: Inconsistent render behavior triggered by setState in blur/focus callbacks

### ISSUE THREAD

**Issue by TisnKu** [facebook/react#19698] opened 2020-08-26 06:30 UTC
React version: 16

## Steps To Reproduce
Open the [codepen](https://codepen.io/c392625/pen/RwapKja) demo.
1. Focus the outside div by clicking the black area
2. Focus inner yellow div by either pressing arrow keys or clicking or tab

## The current behavior
When using arrow keys to change focus, `render` is called once **only**.
When using click or tab to change focus, `render` is called **twice**.

## The expected behavior
`render` should be called the same times under 2 scenarios.

**Comment by eps1lon** [comment] 2020-08-26 07:52
In short: Duplicate of https://github.com/facebook/react/issues/19400

> When using click or tab to change focus, render is called twice.

On the arrow press you manually call `focus()` in the keydown handler which triggers onBlur and onFocus. Since this all happens synchronously in an event handler React can batch these updates and you end up with a single render.

However, on TAB the browsers default behavior blurs the active element and focuses the next element. This sequence isn't batched by React. So you end up with an `onBlur` and `onFocus` call that React can't batch and you end up with two renders.

**Closed by eps1lon** 2020-08-26 07:52 UTC
Labels: Status: Unconfirmed

**Comment by gaearon** [comment] 2021-02-10 23:19
>In short: Duplicate of #19400

I don't think this was correct. I believe #19400 is specific to Concurrent Mode (and the fix there is unrelated to normal 16).
