### ISSUE TITLE
[Bug] "Missing React element for debugID" triggered by ReactDOMServer.renderToStaticMarkup

### ISSUE THREAD

**Issue by pvande** [facebook/react#7190] opened 2016-07-05 19:12 UTC
As of React v15.2.0, the provided fiddle is throwing the "Missing React element for debugID" warning, which has been described as an internal (i.e. not user-facing) React warning.

https://jsfiddle.net/s4c36s0n/

This warning was not present in React v15.1.0.

(I make no claim that this is a sane usage pattern, only that it exists in [real-world components](https://github.com/zenoamaro/react-quill/blob/master/src/toolbar.js#L157) and that it's an unexpected failure case.)

**Comment by gaearon** [comment] 2016-07-05 19:15
Thanks! Yes, this is a duplicate of #7187.

**Closed by gaearon** 2016-07-05 19:15 UTC

**Comment by pvande** [comment] 2016-07-05 19:58
@gaearon Wasn't sure if you wanted separate issues for different causes or if you just wanted a single issue tracking the symptom.  Cheers!

**Comment by gaearon** [comment] 2016-07-05 19:59
Yea, thanks for filing! (The issue is the same but it’s good to have several test cases.)

**Comment by gaearon** [comment] 2016-07-05 23:23
Fixed by #7193.
