### ISSUE TITLE
15.4.1 version of react and react-dom don't work together

### ISSUE THREAD

**Issue by varghesep** [facebook/react#8551] opened 2016-12-11 23:43 UTC
I've used the 15.4.1 version of the react and react-dom together. I get the following errors:

![image](https://cloud.githubusercontent.com/assets/12233474/21084429/0ee3ab0a-bfc9-11e6-9aa9-2edd7b8bf4ff.png)

![image](https://cloud.githubusercontent.com/assets/12233474/21084427/048eda9e-bfc9-11e6-9fae-873d93762d1a.png)

This is my set-up:

![image](https://cloud.githubusercontent.com/assets/12233474/21084418/e695190e-bfc8-11e6-8cd0-ff3b3fdb5fb5.png)

![image](https://cloud.githubusercontent.com/assets/12233474/21084422/f2ca4046-bfc8-11e6-9597-e4ffa0078d86.png)

I don't have the problem if I use the same code, but the 15.1.0 version instead of 15.4.1.

**Comment by gaearon** [comment] 2016-12-11 23:47
Yes, this is a known regression. Please subscribe to https://github.com/facebook/react/issues/8392 for updates.
Unfortunately it’s not clear to me how to fix this so help would be appreciated.
I’m closing as a duplicate of https://github.com/facebook/react/issues/8392.

**Closed by gaearon** 2016-12-11 23:47 UTC

**Comment by gaearon** [comment] 2017-01-06 20:51
This should be fixed by updating all packages to 15.4.2.
Please verify.
