### ISSUE TITLE
Bug: To support Ukraine, how to change ReactJs to UkraineNeedHelpJs

### ISSUE THREAD

**Issue by cnmade** [facebook/react#23403] opened 2022-03-03 06:24 UTC
To real support Ukraine, we shall do more, How about change the project name to UkraineNeedHelpJs, Until Ukraine no more war.
The new name is good to see and understand:
Ukraine Need Help 
I hope you guys stand with us to support Ukraine.

If you not agree, You are less kind person which may want to support Russian.

**Comment by cnmade** [comment] 2022-03-03 06:27
翻译：
```
为了真正支持乌克兰，我们将做更多的事情，把项目名称改为UkraineNeedHelpJs，直到乌克兰不再有战争。

这个新名字很好理解：

乌克兰需要帮助

我希望你们和我们站在一起支持乌克兰。

如果你不同意，你就不是那么善良的人，你可能想支持俄罗斯人。
```

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:28
Afghanistan: ?

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:28
Iraq：？

**Comment by cnmade** [comment] 2022-03-03 06:31
By side of USA: Afghanistan, Iraq were both terrorism country, so we shall only stand together support poor Ukraine.

**Comment by fengtomy** [comment] 2022-03-03 06:32
Technology knows no borders

**Comment by cnmade** [comment] 2022-03-03 06:34
If USA like： there is no borders. If USA not happy: now it has borders as you can see and feel it.

**Comment by cnmade** [comment] 2022-03-03 06:35
And shall we ask USA to rename it's country name to : UkraineNeedHelp, from USA  => UNH  , I hope they accept my suggest. or they do not really want to help Ukraine.

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:35
I started learning VUE

**Comment by cnmade** [comment] 2022-03-03 06:49
@jeasonstudio i see you down vote. you are not good person we know.

You are kind heart less.

Why you not stand with us, please support Ukraine, seriously.

**Comment by Lee94** [comment] 2022-03-03 07:07
UkraineNeedHelpAndBlackLivesMatter.Js

**Comment by cnmade** [comment] 2022-03-03 07:07
> UkraineNeedHelpAndBlackLivesMatter.Js

I like you new name

**Comment by eps1lon** [comment] 2022-03-03 07:08
Duplicate of https://github.com/facebook/react/issues/23402#issuecomment-1057735150

**Comment by cnmade** [comment] 2022-03-03 07:08
Ladies and gentleman, let's move and provide our stronger support, show your kind heart to the world.

**Comment by cnmade** [comment] 2022-03-03 07:09
@eps1lon no, this issue is not duplicated. we shall stronger support Ukraine.

**Closed by eps1lon** 2022-03-03 07:08 UTC
Labels: Status: Unconfirmed

**Comment by SaltFish001** [comment] 2022-03-03 07:09
同志们, Node.js也是一丘之貉. 我头一次因为我用这两技术而羞耻.
Shame on me!
Shame on React!
Shame on Node.js!
![image](https://user-images.githubusercontent.com/42058801/156514377-11752733-80c2-4356-bd72-c4cb3cab61be.png)

**Comment by cnmade** [comment] 2022-03-03 07:12
@SaltFish001 技术是纯净的，人可能是肮脏的。我们要鼓励真正善举。请加入我们一起，让我们提供更强力的支持乌克兰。 
加一个支持链接，没什么大不了的，真正彰显决心的，是把项目名改为支持乌克兰。
让全世界看看。
树立一个高品德，高素质的榜样。

**Comment by eps1lon** [comment] 2022-03-03 07:15
I'm pretty sure OP is being sarcastic. If you want to suggest additional ways of showing support please file them against https://github.com/reactjs/reactjs.org/

**Comment by cnmade** [comment] 2022-03-03 07:16
No time to sarcastic, we shall move.

**Comment by Niefee** [comment] 2022-03-03 07:51
你这么干，对阿富汗、伊拉克又选择性忽视。
Shame on you

**Comment by Aeolos1994** [comment] 2022-03-03 08:05
> 

你确定这人不是友军么..
不过 厚葬了吧

**Comment by cnmade** [comment] 2022-03-03 08:10
哈哈，我感觉他们支持乌克兰力度不够大，应该更进步一点。

**Comment by dushaobindoudou** [comment] 2022-03-03 08:46
开始废弃React，去他妈的nazi

**Comment by chenzezhang** [comment] 2022-03-03 08:52
做人不好吗，奈何做狗

**Comment by liaotuo** [comment] 2022-03-03 08:53
狗日的美帝国主义

**Comment by cnoder-wgh** [comment] 2022-03-03 11:00
别打啦别打啦，我分不清
