### ISSUE TITLE
dangerouslySetInnerHTML and &reg; mark

### ISSUE THREAD

**Issue by guatedude2** [facebook/react#8567] opened 2016-12-13 19:13 UTC
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** when setting `dangerouslySetInnerHTML` with a url that contains the text "http://console.appnexus.com/creative?sometoken=abc&regstop=1" the result is "http://console.appnexus.com/creative?sometoken=abc®stop=1".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Problem: https://jsfiddle.net/oq8zoufg/

**What is the expected behavior?**
The text &reg should not be replaced with ®
Workaround: https://jsfiddle.net/grqc28qq/

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** Only tested in Chrome

**Comment by Andarist** [comment] 2016-12-14 14:52
Its not a react issue, please look at this - https://jsfiddle.net/oq8zoufg/2/

**Comment by guatedude2** [comment] 2016-12-14 14:59
Ah ok. I'll test this out on Safari, and Firefox to verify if its a chrome bug or what. Thanks for looking into it. 

Alejandro Gonzalez

**Comment by Andarist** [comment] 2016-12-14 15:07
its not a bug, you just need to use proper HTML entities while setting this https://developer.mozilla.org/en-US/docs/Glossary/Entity

**Comment by Aweary** [comment] 2016-12-14 15:30
Thanks @Andarist, that's exactly it. Closing this out since it's not a React issue 👍

**Closed by Aweary** 2016-12-14 15:30 UTC

**Comment by guatedude2** [comment] 2016-12-14 17:07
Makes sense, I'll just use the proper html entity escaping
