### ISSUE TITLE
request: option to issue warning if a prop is passed but is unlisted in proptypes

### ISSUE THREAD

**Issue by PhilVargas** [facebook/react#4113] opened 2015-06-12 20:27 UTC
PropTypes are an incredibly useful feature in react, especially the `#isRequired` option. Nearly every component i create is started with the proptypes option, but as refactors occur, features added, or just progress with tdd occurs, i've found that sometime i add a prop to the component, but forget to add it to PropTypes. What I'd like to see happen is an option to make proptypes issue a warning if a prop is passed to the component, but not listed in the PropTypes object. 
So sort of the opposite of the isRequired option. isRequired issues a warning if the specified prop is not passed to the component, a strictPropTypes option will issue a warning when you pass the component any prop that is not listed in PropTypes 
for example
```javascript
var Foo = React.createClass({
  strictPropTypes: true,
  
  propTypes: {
    bar: React.PropTypes.string.isRequired
    baz: React.PropTypes.string
  },
  
  render: function(){
    return <div className={ this.props.qux }>{ this.props.bar }</div>
  }
    
})

React.render(Foo, {qux: 'quux'})
```

The would issue two warnings, one for not passing it a required
prop (`bar`), and another for passing it a prop thats not listed in propTypes
when strictPropTypes is true (`qux`)

**Comment by spicyj** [comment] 2015-06-12 20:31
Dupe of #1587.

**Closed by spicyj** 2015-06-12 20:31 UTC
