### ISSUE TITLE
hostContainerInfo always null in IE11 Edge

### ISSUE THREAD

**Issue by KalpanaAr** [facebook/react#9546] opened 2017-04-27 18:53 UTC
We have a react application that is working perfectly fine on all browsers except IE11 (11.0.9). React Application won't even load on IE11 because in react-dom/lib/ReactDOMComponent.js @ line 405 hostContainerInfo is always null. While Chrome and firefox always gets proper value for hostContainerInfo.

```
 mountComponent: function (transaction, hostParent, hostContainerInfo, context) {
    this._rootNodeID = globalIdCounter++;
    this._domID = hostContainerInfo._idCounter++;
```
The error I am getting is this:

```
Unable to get property '_idCounter' of undefined or null reference
```

 Versions used:
react/react-dom: 15.4.1

Tried downgrading react to 15.3.2 and upgrading it 15.4.1, but the problem still exists. 

Any guidance on how to approach this problem would be very helpful. Thanks.

**Comment by gaearon** [comment] 2017-07-11 13:22
We will need a reproducing example because IE11 works in our experience.

**Comment by aweary** [comment] 2017-09-20 16:08
Since there was no reproducing example provided, I'm going to assume this is no longer an issue and close this out.

**Closed by aweary** 2017-09-20 16:08 UTC
Labels: Status: Unconfirmed

**Comment by keithhalterman** [comment] 2017-11-09 21:14
Seeing this same error from users with IE 11
@KalpanaAr did you find anything to help solve this?

```TypeError: Unable to get property '_idCounter' of undefined or null reference
  at p.Mixin.mountComponent(../jspm_packages/npm/react-dom@15.6.2/lib/ReactDOMComponent.js:407:4)```
