### ISSUE TITLE
unmountComponentAtNode doesn't unbind in-flight listeners, throws opaque error.

### ISSUE THREAD

**Issue by lutherism** [facebook/react#4892] opened 2015-09-16 22:16 UTC
Our React app was triggering the following error during navigation events:

`Uncaught TypeError: Cannot read property 'firstChild' of undefined`

The error was occurring in the function `findComponentRoot`, when it failed to find a component for an event callback.

In our app, this was happening when we would navigate during a blur event, and call `unmountComponentAtNode` on the rendering, in order to refresh the page. The docs for `unmountComponentAtNode` say

> Remove a mounted React component from the DOM and clean up its event handlers and state

However, this does not seem to be the case. After we refresh the page with `unmountComponentAtNode`, there were other React-bound callbacks still in React's queue for that event. Leading to the error.

The docs and intuition seem to imply `unmountComponentAtNode` should clear these callbacks, since it knows the components will no longer exist to handle them.

**Comment by lencioni** [comment] 2015-11-12 18:02
Is this perhaps a duplicate of #3298 and #2605?

**Comment by lutherism** [comment] 2015-11-13 03:50
P

**Comment by aweary** [comment] 2017-09-20 01:10
Since there's no repro provided and there's been no activity for almost 2 years, I'm going to close this out. If this is still an issue with the latest version of React, please provide an example reproduction the issue so we can verify.

Thanks!

**Closed by aweary** 2017-09-20 01:10 UTC
