### ISSUE TITLE
React dev tools not working when running the application/website on incognito mode

### ISSUE THREAD

**Issue by vikram87in** [facebook/react#26766] opened 2023-05-03 13:43 UTC
React dev tools not working when running the application/website on incognito mode. This page doesn’t appear to be using React. I am trying it on this url: https://www.facebook.com/virat.kohli/
Note: it works with non-incognito mode. Issue replicating on chrome and edge both

**Comment by RichDom2185** [comment] 2023-05-03 15:33
This seems to be a duplicate of #26756.

**Comment by rajnish307** [comment] 2023-05-04 05:45
Yes, I can confirm it is working as expected now after the fix.

**Comment by vikram87in** [comment] 2023-05-04 09:58
@rajnish307 I think the new version is yet to be published. Will have to wait for some time, I guess

**Comment by hoxyq** [comment] 2023-05-15 20:51
Expected to be fixed in v4.27.7.

**Closed by hoxyq** 2023-05-15 20:51 UTC
