### ISSUE TITLE
Ensures ARIA attributes are allowed for an element's role (aria-allowed-attr - https://accessibilityinsights.io/info-examples/web/aria-allowed-attr)Bug: 

### ISSUE THREAD

**Issue by msftedad** [facebook/react#30012] opened 2024-06-21 09:26 UTC
React version: 16.14.0

## Steps To Reproduce

1. Launch the application using URL: [Bryntum Scheduler - Vertical mode demo (React)](https://www.bryntum.com/products/scheduler/examples/frameworks/react/javascript/vertical/build/).
2. “Vertical mode demo (React)” screen should open.
3. TAB to “Filter Event” button.
4. Run AI4W fast pass and observe the issue.

Link to code example:

## The current behavior
Ensures ARIA attributes are allowed for an element's role (aria-allowed-attr - https://accessibilityinsights.io/info-examples/web/aria-allowed-attr)

Element path: .b-filter-bar-enabled

 

Snippet: <div class="b-grid-header b-level-0 b-depth-0 b-last-leaf b-filter-bar-enabled" role="presentation" aria-sort="none" aria-label="SPACE for context menu" data-column-id="b-scheduler-1-col-1" data-column="_verticalTimeAxis2" style="min-width: 0px; flex: 1 1 0%;" aria-colindex="1">

![224570_AI4W](https://github.com/facebook/react/assets/93735775/e17de8f2-2611-41b9-bdf3-a889d0862326)

## The expected behavior
ARIA attributes are not allowed: aria-sort="none", aria-colindex="1"

**Comment by eps1lon** [comment] 2024-06-25 11:17
Duplicate of https://github.com/facebook/react/issues/30018

**Closed by eps1lon** 2024-06-25 11:17 UTC
Labels: Status: Unconfirmed
