### ISSUE TITLE
React throws warning concerning unique "key" prop, when collection has only one element

### ISSUE THREAD

**Issue by dmaklygin** [facebook/react#7774] opened 2016-09-20 09:03 UTC
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
1. Create list of elements, which contains just *one* element. Element key is undefined.
2. Render list properly.
3. React throws warning: `VM60 react-with-addons.js:22809 Warning: Each child in an array or iterator should have a unique "key" prop. `

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

This is an example: https://jsfiddle.net/ah0r5ffs/

**What is the expected behavior?**
Expected behavior: list contains just one element, therefore, key is unique. Warning shouldn't be displayed. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Appeared in the following versions: ("react": "15.3.1", "react-dom": "15.3.1")
This worked in previous version. ("react": "15.0.2", "react-dom": "15.3.1")

**Comment by syranide** [comment] 2016-09-20 09:30
Not a bug, it should still have a key. It's not about uniqueness, it's about maintaining correct behavior when re-rendering. If the list grows to more elements then it won't be able to reuse the existing instances if the elements are not properly keyed.

**Comment by karczk** [comment] 2016-09-20 12:23
Message is misleading. Keys are unique, but the key cannot be null or undefined.
3x div, only one key is not defined: https://jsfiddle.net/1phtzqkj/1/ (run, look at console)
```
function validateExplicitKey(element, parentType) {
  if (!element._store || element._store.validated || element.key != null) {
    return;
  }

```

**Comment by dmaklygin** [comment] 2016-09-20 21:01
so, that means, we're gonna close this issue?

**Comment by karczk** [comment] 2016-09-20 21:09
I propose to add one more warning (about null key). Message about unique keys for this situation is misleading.

**Comment by Aweary** [comment] 2016-09-20 21:11
Yeah I'm going to close this, since using `undefined` as a key name is not recommended. As for not requiring a key on arrays with single items: I don't really see a use case for rendering an array containing one item. The only case where I see that being valid is if additional items might be present in the array later, in which case you'll need to use unique keys anyways.

**Closed by Aweary** 2016-09-20 21:11 UTC
