### ISSUE TITLE
React dev tools not showing (blank)

### ISSUE THREAD

**Issue by aaronchua13** [facebook/react#16840] opened 2019-09-20 07:00 UTC
i was working with it a while ago but now it will only show nothing in the Components tab. I tried everything, reinstalled or even try on a different browser. I even restarted my PC. 
![Screenshot from 2019-09-20 14-53-15]

![Screenshot from 2019-09-20 14-53-15](https://user-images.githubusercontent.com/41131879/65306178-5dc1f080-dbb7-11e9-85e1-f3c7319ddd59.png)

**Comment by mark-quinn** [comment] 2019-09-20 10:30
Having the same issues. On updating the state, an icon appears which says reset value. If you copy the object and paste it into the console you can see that the object is updating but it's just the extension that is not displaying it as normal.

**Comment by bvaughn** [comment] 2019-09-20 16:26
Works for me on a fresh install. (Just tested to verify.)

Can you provide some more info? There isn't a lot to go on on this issue. For example, please specify:
* What OS you're using
* What browser and version
* Which DevTools extension version (you can find this in about:extensions on Chrome or about:addons on Firefox)
* Which website(s) this bug is happening on

**Comment by bvaughn** [comment] 2019-09-20 16:27
> Having the same issues. On updating the state, an icon appears which says reset value.

I don't understand this comment. If you're having the same issue (an empty/blank DevTools) how are you updating state?

**Comment by davidsavoie1** [comment] 2019-09-20 17:57
I'm experiencing this issue too. The devtool's Components tab is empty and no element can be selected.

OS: Linux Mint (Virtual machine)
Browser: Chrome 
Extension version: 4.1.0 (9/19/2019)
Website: Localhost (development)

I also tried restarting the console, restarting the browser, reinstalling the extension, restarting the virtual machine without success... It worked just before lunch, now it doesn't. Very weird...

**Comment by bvaughn** [comment] 2019-09-20 18:04
Any errors in the extension's background page or console?

It could potentially be related to this change?
https://github.com/facebook/react/pull/16752

cc @onionymous

**Comment by aaronchua13** [comment] 2019-09-20 18:17
@bvaughn 
OS: Linux mint
Browser: chrome, mozilla
Website: development
Version: 4.1.0

**Comment by aaronchua13** [comment] 2019-09-20 18:18
> > Having the same issues. On updating the state, an icon appears which says reset value.
> 
> I don't understand this comment. If you're having the same issue (an empty/blank DevTools) how are you updating state?

I did the same.

**Comment by davidsavoie1** [comment] 2019-09-20 18:22
> Any errors in the extension's background page or console?
> 
> It could potentially be related to this change?
> #16752
> 
> cc @onionymous

Nothing in the console. 'Profiler' tab says:
```
Profiling not supported.
Profiling support requires either a development or production-profiling build of React v16.5+.
```

**Comment by bvaughn** [comment] 2019-09-20 20:20
For those of you affected by this bug, would you be interested in installing a one-off release (with the trusted types change backed out) to confirm if it fixes things for you? If so, I'll build and share one.

**Comment by davidsavoie1** [comment] 2019-09-21 01:02
@bvaughn I don't mind trying it out if you provide some guidance on how to do so. Better trying something out than having no devtool at all! We get used to those goodies! ;)

**Comment by bvaughn** [comment] 2019-09-21 17:35
By the way, we are having a little trouble reproducing this issue on our end using a Linux VM. Does this bug affect all React websites? Or one in particular?

I'll update this issue with a link to a build shortly, David.

**Comment by Rex1911** [comment] 2019-09-22 05:57
> By the way, we are having a little trouble reproducing this issue on our end using a Linux VM. Does this bug affect all React websites? Or one in particular?
> 
> I'll update this issue with a link to a build shortly, David.

I'm having the same issue, and for me, I've been experiencing this bug on all react websites. The Components tab is empty. 

OS: Ubuntu 18.04
Browser: Chrome v69.0.3497.100
Website: Every react based website
Version: 4.1.0

**Comment by Abibibi** [comment] 2019-09-22 15:41
> For those of you affected by this bug, would you be interested in installing a one-off release (with the trusted types change backed out) to confirm if it fixes things for you? If so, I'll build and share one.

Yes, sure.

**Comment by Abibibi** [comment] 2019-09-22 15:42
> For those of you affected by this bug, would you be interested in installing a one-off release (with the trusted types change backed out) to confirm if it fixes things for you? If so, I'll build and share one.

Sure.

**Comment by aaronchua13** [comment] 2019-09-23 00:41
> By the way, we are having a little trouble reproducing this issue on our end using a Linux VM. Does this bug affect all React websites? Or one in particular?
> 
> I'll update this issue with a link to a build shortly, David.

yes it does.

**Comment by junchaohu** [comment] 2019-09-23 07:11
Does everyone have solutions??

**Comment by sshmyg** [comment] 2019-09-23 10:46
Same issue for standalone version + react native 

![image](https://user-images.githubusercontent.com/1410608/65419946-81c84080-de08-11e9-941e-ee5f88b75085.png)

**Comment by mark-quinn** [comment] 2019-09-23 10:48
Reinstalled the extension and I am still having problems.

OS: MacOS Mojave 10.14.5
Browser: Chrome 76.0.3809.132

**Comment by mark-quinn** [comment] 2019-09-23 10:50
> Any errors in the extension's background page or console?
> 
> It could potentially be related to this change?
> #16752
> 
> cc @onionymous

No changes in the console. Only visual change is the reset value icon displayed next to the objects in state which I have never noticed before. 

![image](https://user-images.githubusercontent.com/33720042/65420154-563d5a00-ddf8-11e9-8e93-7d58b32f0bf8.png)

**Comment by EddyHamzich** [comment] 2019-09-23 14:50
^ same issue. The state actually does update because I can see it changing in my web-app it just doesnt update in DevTools.

**Comment by bvaughn** [comment] 2019-09-23 15:29
This thread seems to be splitting into two separate things, which isn't helpful. So far as I can tell, @mark-quinn and @EddyHamzich seem to be describing #16843 - **not** what this issue is reporting. (If DevTools was "blank" for you, as the screenshots above, you wouldn't be able to select a component or see its properties.)

**Comment by aaronchua13** [comment] 2019-09-23 15:46
I still have the issue and I am wondering why I got this in the first place, some devs in the office has the same pc as mine and working properly except mine.

**Comment by bvaughn** [comment] 2019-09-23 15:52
@aaronchua13 Do you perhaps have other extensions installed that might be interfering? Or have you set any advanced configuration options in Chrome preferences panel?

**Comment by davidsavoie1** [comment] 2019-09-23 16:06
The only other extensions I have are Redux DevTools (working) and Google Docs offline. I don't see where there could be interference. And I do experience the issue on various React websites, including official React site. Thanks for the help.

**Comment by aaronchua13** [comment] 2019-09-23 16:11
No, I don't think that's the case. I only have few extensions and I also tried it in firefox which has no extenion at all but still have the issue. I'll upload some photos later maybe it'll help.

**Comment by bvaughn** [comment] 2019-09-23 16:13
Sorry, give me another minute. I forgot to back out one of the commits.

**Comment by bvaughn** [comment] 2019-09-23 16:37
Here is a build of the Chrome extension that backs out the changes from #16752:

[ReactDevTools.zip](https://github.com/facebook/react/files/3643169/ReactDevTools.zip)

Can you give this a try and let me know if it fixes the blank panel issue you're seeing? It would be helpful in narrowing down the cause of the regression, since I'm not able to reproduce it yet.

cc @aaronchua13, @Abibibi

**Comment by mattcee233** [comment] 2019-09-23 16:46
@bvaughn
FYI your reversion resolved this issue for me, running chrome 60.0.3112.78, was affecting all websites visited

**Comment by bvaughn** [comment] 2019-09-23 16:54
Thanks for the data point, @mattcee233. Going to wait to hear from a couple others but if it also fixes it for them, I'll probably post a new release with the change reverted and we'll have to revisit the trusted types support.

**Comment by Rex1911** [comment] 2019-09-23 17:06
> Here is a build of the Chrome extension [that backs out the changes](https://github.com/facebook/react/compare/master...bvaughn:revert-pr-16752?expand=1) from #16752:
> 
> [ReactDevTools.zip](https://github.com/facebook/react/files/3643169/ReactDevTools.zip)
> 
> Can you give this a try and let me know if it fixes the blank panel issue you're seeing? It would be helpful in narrowing down the cause of the regression, since I'm not able to reproduce it yet.
> 
> cc @aaronchua13, @Abibibi

I've tested this out on my machine and everything seems to work fine. I can confirm I see the Components again in the Components tab

**Comment by linshunghuang** [comment] 2019-09-23 17:58
Hi, can someone help me get a reliable repro? Thanks!

Here are the versions (all stock installations) I used for testing in a fresh Linux VM:

Unbuntu 18.04.3 LTS
Chrome Version 77.0.3865.90
React Dev Tool 4.1.0 (9/192019)
Website: https://reactjs.org/

I'm not getting a blank Components tab. What am I missing?

**Comment by bvaughn** [comment] 2019-09-23 18:08
@linshunghuang works with my at Facebook. Once we revert this change, he will be working to re-add Trusted Type support- so it's important that he/we understand how to reproduce the original issue (so we avoid reintroducing it with a future change).

I appreciate all of the info folks have been providing so far! 🙇 It would be super helpful if any of you are also able to help him find a way to repro the issue.

**Comment by davidsavoie1** [comment] 2019-09-23 19:39
> It would be super helpful if any of you are also able to help him find a way to repro the issue.
@bvaughn I honestly don't know how to do that, but I'd be glad to help out if I can.

**Comment by bvaughn** [comment] 2019-09-23 19:58
This fix will be released with 4.1.1 (sometime soon)

Let's keep talking and sharing info if possible to try to narrow down how to repro the issue though.

**Closed** 2019-09-23 19:58 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information

**Comment by linshunghuang** [comment] 2019-09-24 00:17
Ok, I got a repro using Chromium 69.0.3497.0.

**Comment by davidsavoie1** [comment] 2019-09-24 14:06
@bvaughn A newbie question here... How can I actually *use* the zip folder you provided?

**Comment by bvaughn** [comment] 2019-09-24 15:47
@davidsavoie1

1. download it and extract it
1. go to about:extensions
1. enable "developer mode" in the top right
1. click "load unpacked" button
1. browse to select the extracted folder

**Comment by Abibibi** [comment] 2019-09-24 16:48
> Here is a build of the Chrome extension [that backs out the changes](https://github.com/facebook/react/compare/master...bvaughn:revert-pr-16752?expand=1) from #16752:
> 
> [ReactDevTools.zip](https://github.com/facebook/react/files/3643169/ReactDevTools.zip)
> 
> Can you give this a try and let me know if it fixes the blank panel issue you're seeing? It would be helpful in narrowing down the cause of the regression, since I'm not able to reproduce it yet.
> 
> cc @aaronchua13, @Abibibi

It works fine now. All components are displayed in the tab. Thanks a lot

**Comment by RossVertizan** [comment] 2019-09-25 13:01
@bvaughn - Just another quick confirmation that this fixes the problem for me.  I'm using React with Electron on Windows 10.

**Comment by bvaughn** [comment] 2019-09-25 16:25
Thanks~ I plan to release this update today.

**Comment by bvaughn** [comment] 2019-09-26 14:23
Hey folks, sorry I didn't get the release made yesterday. I will get it out today.

Would like to run one more build by you all first though (from PR #16900) to verify that we didn't reintroduce the problem being reported on this thread.

[ReactDevTools.zip](https://github.com/facebook/react/files/3658211/ReactDevTools.zip)

Sorry to ask another favor on this same thread. Trying to avoid the larger inconvenience of another regression though!

**Comment by Abibibi** [comment] 2019-09-26 14:56
> Hey folks, sorry I didn't get the release made yesterday. I will get it out today.
> 
> Would like to run one more build by you all first though (from PR #16900) to verify that we didn't reintroduce the problem being reported on this thread.
> 
> [ReactDevTools.zip](https://github.com/facebook/react/files/3658211/ReactDevTools.zip)
> 
> Sorry to ask another favor on this same thread. Trying to avoid the larger inconvenience of another regression though!

This works too.

**Comment by bvaughn** [comment] 2019-09-26 15:23
Thanks @Abibibi!

@sshmyg I don't think this change should have any impact on the standalone version. That uses a web socket. The browser extension uses the `postMessage` API to inject which this change touches.

**Comment by sshmyg** [comment] 2019-09-26 15:32
@bvaughn Latest standalone version also has this bug with empty screen.

**Comment by bvaughn** [comment] 2019-09-26 15:40
Hm... that sounds unexpected. The code change that caused this regression was inside of `react-devtools-extensions` which is only the browser extensions. The standalone version is a different package. If you're seeing a bug with it, please report a separate issue with repro steps.

**Comment by RossVertizan** [comment] 2019-09-26 16:02
@bvaughn  - Yes this still works for me.
Thanks.

**Comment by bvaughn** [comment] 2019-09-26 17:51
This fix has just been published to NPM and posted to Chrome/Firefox as v4.1.1

**Comment by kroudir** [comment] 2019-12-10 18:26
I am experiencing the same problem with React Dev Tools 4.2.1
macOS Catalina
Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Chrome extension version 4.2.1
An app that I am working on.

**Comment by ahmedreda97** [comment] 2019-12-11 06:47
> I am experiencing the same problem with React Dev Tools 4.2.1
> macOS Catalina
> Chrome Version 78.0.3904.108 (Official Build) (64-bit)
> Chrome extension version 4.2.1
> An app that I am working on.

+1

**Comment by Borumer** [comment] 2019-12-21 01:44
> @bvaughn
> FYI your reversion resolved this issue for me, running chrome 60.0.3112.78, was affecting all websites visited

How do you put this into chrome?

**Comment by savybrandt** [comment] 2020-10-29 21:59
My dev tools are also blank. Steps to reproduce-
1. Do your job like normal, but don't have your computer plugged in
2. Your computer dies
3. Plug in your computer and get some charge
4. Open chrome to continue doing your job as you were before
5. Open devtools Components tab
=> it's blank
<img width="770" alt="Screen Shot 2020-10-29 at 2 55 06 PM" src="https://user-images.githubusercontent.com/61570254/97636740-cb656080-19f6-11eb-9841-801fe7178470.png">

**Comment by gaearon** [comment] 2020-10-29 22:20
Hi folks, the original bug has been closed. You're commenting in a closed issue, which is very unlikely to be read and acted upon. When you have a problem, please *create a new issue with fresh information*. E.g. these repro steps by @savybrandt are great, but they need to be a new issue. I'm going to lock this one.
