### ISSUE TITLE
Using React 15, under Edge, dangerouslySetInnerHTML doesn't work on any SVG tag

### ISSUE THREAD

**Issue by lgra** [facebook/react#7563] opened 2016-08-25 18:12 UTC
Hi everyone.

This issue is following #6950
The fix works on IE11. Unfortunately, it doesn't under Edge.

It seems that Edge is implementing innerHTML property on SVG tag, but in an inefficient way. Using it appends SVG text in the DOM tree, as it can be seen using the inspector, but Edge doesn't render anything... Unless you modify the svg string in the inspector...

See the [codepen](http://codepen.io/lgra/pen/OXPgoQ) (updated to use React 15.3) under Edge to see that issue.

Of course, if we enforce Edge to use the hack, it works. I don't know how to enforce it except browser sniffing (grr...).

**Comment by Aweary** [comment] 2016-08-29 20:57
Hey @lgra, thanks for the report. What version of Edge are you using?

**Comment by lgra** [comment] 2016-08-30 09:30
Hi Brandon,
I've tried using Edge 38.14393.0.0 / EdgeHTML 14.14393 - from a modern.ie VM.

**Comment by Aweary** [comment] 2016-08-30 14:32
Thanks @lgra! I think this is a duplicate of https://github.com/facebook/react/issues/7506. I'm going to close this out in favor of https://github.com/facebook/react/issues/7506, so feel free to subscribe to that issue for updates 👍

**Closed by Aweary** 2016-08-30 14:32 UTC

**Comment by lgra** [comment] 2016-08-30 14:49
You're perfectly true, that's a perfect duplicate. #7506 uses my codepen. Don't know how I've didn't seen it. I'll switch to this one.

**Comment by Aweary** [comment] 2016-08-30 15:05
@lgra if I understand correctly, this version of edge is a prerelease version, correct? That's what I get from looking at [modern.ie](http://www.modern.ie) briefly. 

If so, it seems like a regression in Edge and something that should be reported to them so the Edge team can fix it.
