### ISSUE TITLE
Remove functionality that appends 'px' to unitless numbers in STYLE prop

### ISSUE THREAD

**Issue by jameshopkins** [facebook/react#1873] opened 2014-07-18 23:13 UTC
It is dangerous to assume a number that has a distance unit omitted from it, should be pixel-based. 

Working within the [SVG user space](http://www.w3.org/TR/SVG/coords.html#SVGInitialUserCoordinateSystem), it is sometimes required that [number values are left unitless](http://www.w3.org/TR/SVG/coords.html#LengthsInSVG), so that they're proportionate to the user-defined matrix.

The is also the additional overhead in maintaining a property (that accepts a unitless number value) [whitelist](https://github.com/facebook/react/blob/a8fc3b940dbe20c0c7decd19b028215b236c50a6/src/browser/ui/dom/CSSProperty.js#L24), instead of just allowing a pass-through.

**Comment by viniciusdacal** [comment] 2017-04-12 02:26
it seems to be duplicated with #1357, it is not?

**Comment by gaearon** [comment] 2017-10-01 23:38
Yes, this is a duplicate of https://github.com/facebook/react/issues/1357.

**Closed by gaearon** 2017-10-01 23:38 UTC
Labels: Component: DOM
