### ISSUE TITLE
Should React.Children.only() handle mapped children?

### ISSUE THREAD

**Issue by epsitec** [facebook/react#6156] opened 2016-03-01 09:11 UTC
Let's say we have a component `Foo` which expects to get a single child:

```javascript
 class Foo extends React.Component {
    render () {
      const {children} = this.props;
      return React.Children.only (children);
    }
}
```

This works as expected if I render `<Foo><div/></Foo>` since `children` then maps to a single child, and `React.Children.only()` will happily return the only child.

However, when using `Foo` like this, it throws:

```javascript
class Bar extends React.Component {
  render () {
    const keys = ['a'];
    return <Foo>{keys.map (k => <div key={k}/>)}</Foo>;
  }
}
```

Now, `Foo` gets an array with one `<div>` element.

I was expecting `React.Children.only()` to also handle this case and return the only child in the array. But obviously, it does not.

Now, I have to write this instead:

```javascript
 class Foo extends React.Component {
    render () {
      const {children} = this.props;
      return (Array.isArray (children)) ? children[0] : React.Children.only (children);
    }
}
```

 Is this by design? Did I miss something here?

**Comment by jimfb** [comment] 2016-03-01 09:57
cc @sebmarkbage 

Duplicate of https://github.com/facebook/react/issues/4424

**Closed by jimfb** 2016-03-01 09:57 UTC
