### ISSUE TITLE
Bug: useLayoutEffect callback called twice when a dom node is in a dependency array

### ISSUE THREAD

**Issue by everdimension** [facebook/react#18848] opened 2020-05-06 19:43 UTC
React version: v16.3.1

## Steps To Reproduce

1. add `useLayoutEffect`
2. add dom node to the deps array
3. invoke setState inside useLayoutEffect callback

Link to code example:
https://codepen.io/everdimension/pen/rNOpZGK

## The current behavior
`useLayoutEffect` callback gets called a second time, although the values in the deps array have not changed

## The expected behavior
`useLayoutEffect` callback should not get called unless values in the dependency array change

**Comment by vkurchatkin** [comment] 2020-05-06 20:18
You are not supposed to use `ref.current` as a dependency, since changing it doesn't result in a rerender. 

There is no bug in React. `ref.current` is `undefined` initially, then your effect is triggered, `setState` is called, which results in a rerender. `ref.current` is not `undefined` anymore, so the effect is triggered gain.

**Comment by jeppe-smith** [comment] 2020-05-06 20:22
Looks like `useLayoutEffect` callback gets called twice is because `ref.current` is not attached to the `DOM` on the first callback and then it is on the second resulting in the reference to not have equality.

**Comment by everdimension** [comment] 2020-05-06 20:22
@vkurchatkin 
> ref.current is undefined initially

Actually, it is defined, AFAU that's the point of useLayoutEffect: by the time it's run, the dom had already been commited. I added an `if` with an early return to my example to demonstrate that.

> You are not supposed to use ref.current as a dependency

I thought that was what official react hooks linter recommended?
If that's the wrong way, then what's the proper way to update effect if the dom node changes or gets destroyed?

**Comment by vkurchatkin** [comment] 2020-05-06 20:31
> Actually, it is defined

It is defined when `useLayoutEffect` is executed, but during first render `undefined` is what you pass inside of dependencies array.

> If that's the wrong way, then what's the proper way to update effect if the dom node changes or gets destroyed?

The proper way is to store dom node inside of state:


```js
const [node, setNode] = React.useState(null);

return <div ref={setNode}>My node</div>
```

**Comment by everdimension** [comment] 2020-05-06 20:34
> It is defined when useLayoutEffect is executed, but during first render undefined is what you pass inside of dependencies array.

whoa...

Ok, I'll need some time for this to sink in... :)

**Comment by bvaughn** [comment] 2020-05-06 20:48
> There is no bug in React. `ref.current` is `undefined` initially, then your effect is triggered, `setState` is called, which results in a rerender. `ref.current` is not `undefined` anymore, so the effect is triggered gain.

@vkurchatkin's explanation is correct.


> The proper way is to store dom node inside of state:

I'm not sure I agree with this bit though! Refs can be callbacks functions too. So you could also rewrite your code like so:
```js
function useSomeHook() {
  const [width, setWidth] = React.useState(0);

  const refSetterFunction = React.useCallback(domElement => {
    if (domElement) {
      setWidth(500);
    }
  }, []);

  return { width, ref: refSetterFunction };
}

export default function App() {
  const { ref, width } = useSomeHook();
  return <div ref={ref}>width: {width}</div>;
}
```

Going to close this issue since it's not a bug :smile:

**Closed by bvaughn** 2020-05-06 20:48 UTC
Labels: Status: Unconfirmed

**Comment by vkurchatkin** [comment] 2020-05-06 21:53
@bvaughn 

If you have to clean up when your DOM node changes, you have two options. First is to use effects, which means that you HAVE to put the node in state:

```js
React.useLayoutEffect(() => {
  if (!domNode) {
     return;
  } 
  const resizeObserver = new ResizeObserver(...);
  ...
  return () => {
     resizeObserver.disconnect();
  }
}, [domNode])
```

The second is to do it manually:

```js
  const cleanupRef = React.useRef();
  const ref = React.useCallback(domNode => {
    if (cleanupRef.current) {
      cleanupRef.current();
    }

    cleanupRef.current = undefined;

   if (!domNode) {
     return;
   }
     const resizeObserver = new ResizeObserver(...);

     cleanupRef.current =  () => {
        resizeObserver.disconnect();
     };
  }, []);

React.useEffect(() => {
  return () => {
     if (cleanupRef.current) {
      cleanupRef.current();
    }
  };
}, [])
```

While you can certainly use the second option, and even wrap it in some sort of hook, I would rather just go with the first one.

**Comment by bvaughn** [comment] 2020-05-06 23:21
The example shown didn't involve any cleanup, just a read-on-mount. Using state seemed like overkill. :smile:

**Comment by everdimension** [comment] 2020-05-07 11:50
@bvaughn Thanks, I understand now why there is a second rerender which I didn't expect.

But I don't think I see a solution yet.

The idea is to create a reusable hook which _doesn't_ create a ref object, but accepts a ref.

I read that it's a better practice to create refs outside of reusable hooks. In that case, you can reuse hooks with different logic involving one dom element. Something like this:

```jsx
function SomeComponent() {
  const ref = useRef();
  const { width } = useResizeObserver({ ref });
  const { focused } = useFocusWithin({ ref });
  const { hovered } = useHoverDisclosure({ ref });

  return (
    <div ref={ref}>{...}</div>
  );
}
```

You could argue that if you use ref callbacks then this can be solved with function composition, but this would create a much more cumbersome API for the consumer of these hooks.

What do you think? cc @vkurchatkin

**Comment by vkurchatkin** [comment] 2020-05-07 11:59
> The idea is to create a reusable hook which doesn't create a ref object, but accepts a ref

There is no feasible way to detect when such a ref changes. But IMO this is fine. When a hook accepts a DOM ref it is a clear signal to the user, that this ref should not change until the component is unmounted and they should structure their code accordingly.
