### ISSUE TITLE
On "onChange" event and input[type="number"]

### ISSUE THREAD

**Issue by phaistonian** [facebook/react#6087] opened 2016-02-22 14:29 UTC
As seen [here](http://jsfiddle.net/girlie_mac/5Assc/), when altering the value of an input[type="number"] element an `onChange` is triggered.

Thing is, that's not the case in React.

Here's a [pen](http://codepen.io/phaistonian/pen/adgaXE?editors=1111) to illustrate the case (view console).

**Comment by jimfb** [comment] 2016-02-22 14:36
Your pen appears to demonstrate that React IS triggering `onChange` at the correct time.  At least, in my browser (Chrome).  What browser/version are you using?

**Comment by phaistonian** [comment] 2016-02-22 14:40
Chrome, stable.

What I am suggesting is that when increasing/decreasing the value using the arrows should cast a 'change' event not an 'input' one.

**Comment by jimfb** [comment] 2016-02-22 15:29
Ah, ok, so the event is firing.  It's just that the native event is of a different type.  There is a reason for this...

We listen to the native `input` event because we want it to fire for each character typed:

 > Unlike the input event, the change event is not necessarily fired for each change to an element's value.  (details: https://developer.mozilla.org/en-US/docs/Web/Events/change)

So we will sometimes call your change handler when there is no underlying/native change event to pass to you.  Thus the reason we always pass an input event instead.

AFAIK, there is no reason to need the change event as oppose to the input event, right?

**Comment by phaistonian** [comment] 2016-02-22 15:33
Actually, what if you want to handle `onChange` the way it's done natively, i.e when changing the value by clicking the arrows OR when _blur_ing?

That's `change` but not `input`.

Doing so, is not possible as things are - not without adding a "native" listener.

**Comment by jimfb** [comment] 2016-02-22 15:48
> What if you want to handle onChange the way it's done natively, i.e when changing the value by clicking the arrows OR when bluring?

That is very very rarely the intended/desired behavior.  People generally want onChange to fire any time there was a change, which is why we have the current behavior.  You can always add a native listener if you want to bail out and get the other behavior (that's why we have escape hatches).

I'm going to close this out because this is intended behavior, not a bug, and therefore there isn't anything actionable here.  Feel free to continue the discussion on this thread, and we can re-open if our thinking on this matter changes dramatically.

**Closed by jimfb** 2016-02-22 15:48 UTC

**Comment by phaistonian** [comment] 2016-02-22 15:51
Thank you for your responses @jimfb.

I will resolve this, as you suggest it, passing a native listener.
