### ISSUE TITLE
Range input value not set on initial render in 15.2.0

### ISSUE THREAD

**Issue by mikecao** [facebook/react#7170] opened 2016-07-02 09:22 UTC
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

When rendering a range input element, the value of the input isn't set on the initial render. You have to call render again for the value to get picked up.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

I've created a demo here, https://jsfiddle.net/caozilla/qchxo3qb/4/.

The demo includes a component called Test which simply renders an range input component by passing some props. There is an update button which calls setState and should trigger the render. There are also console.log statements which show the values being used during the render.

When you run the demo you'll notice that you have to click the update button twice before the input value updates. The strange thing is that it seems to have something to do with the min and max attributes of the input. There is a commented out line where it does `var max = 100` and that seems to work fine on initial render. But when it references the state value, it doesn't work.

**What is the expected behavior?**

The input value should be set properly on initial render.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This affects React 15.2.0. It works fine in 15.1.0. I've only tested on the latest Chrome.

**Comment by syranide** [comment] 2016-07-02 14:11
It works just fine: https://jsfiddle.net/4feqLmmy/

You even log the value yourself in the console and it shows `0 0 0`, then when you press the button value is updated to 50 and thus prints `50 0 100` and it updates the range correctly. I don't see anything wrong here besides your jsfiddle.

**Comment by syranide** [comment] 2016-07-02 14:19
Duplicate of #7099

Basically, range input truncates the value according to min/max but React doesn't consider this and can apply the properties in the wrong order causing it to be truncated first and then the limits updated.

**Comment by syranide** [comment] 2016-07-02 14:21
It's really kind of hacky and a bad idea in some cases, but if you put min+max as a key on the range input it will always show correctly.

**Comment by mikecao** [comment] 2016-07-13 20:52
@syranide I just saw that #7099 was fixed but the fix only applied to the step parameter. Would this fix also work for min/max values?

**Comment by syranide** [comment] 2016-07-14 08:18
@mikecao Yeah that should work.

**Comment by troydemonbreun** [comment] 2016-08-01 15:54
Okay, will fix this one like I fixed for #7251

**Comment by zpao** [comment] 2016-08-23 17:37
This was fixed.

**Closed by zpao** 2016-08-23 17:37 UTC

**Comment by NeilSchneider** [comment] 2016-09-01 19:16
The app fails to start with the following message:
webpack-dev-server --inline --hot --port 9090 ./index.js
I'm using node 4.5.0 and npm 2.15.9
Any suggestions?
Thanks
