### ISSUE TITLE
Cannot read property 'return' of null

### ISSUE THREAD

**Issue by jquense** [facebook/react#12449] opened 2018-03-24 19:24 UTC
Running into a strange issue that i cannot reproduce, it happens when running tests in Karma using `16.3.0-alpha.3`

![image](https://user-images.githubusercontent.com/339286/37868035-ee7c67a2-2f76-11e8-9568-2149d81907d5.png)

The issue is here:

https://github.com/facebook/react/blob/208b490ed907346ae3e37159535299899f74312d/packages/react-reconciler/src/ReactFiberScheduler.js#L864-L877

My test is throwing an error because of a missing `onChange` handler when rendering a checkbox with `checked` but no handler. What appears to be happening is that `nextUnitOfWork` is not `null` and misses the first branch, `replayUnitOfWork` is run, after which `nextUnitOfWork` _is_ null and `sourceFiber` doesn't exist and so access of `return` fails.

I've tried for a while to reproduce it, the following codesandbox is a simplified version of the code that is throwing, but the error isn't present there :/ https://codesandbox.io/s/0332y243zp

**Comment by acdlite** [comment] 2018-03-24 19:55
Hmm, I was concerned this might happen. We assume that `replayUnitOfWork` will be idempotent but looks like you've found a case where it's not. I'll take a look at this.

**Comment by acdlite** [comment] 2018-03-24 20:00
Changing line 877 to

```js
const sourceFiber: Fiber = failedUnitOfWork;
```

isn't a sufficient fix because if it's not equal to `nextUnitOfWork`, that means the stack is misaligned.

One option is to add an invariant that throws if `nextUnitOfWork !== failedUnitOfWork`. Usually we avoid DEV-only invariants, but since this should only be possible in an error case, anyway, maybe we can get away with it.

**Comment by gaearon** [comment] 2018-04-01 00:35
Repro case from https://github.com/facebook/react/issues/12497: https://jsfiddle.net/thysultan/Luktwrdm/264/

**Comment by gaearon** [comment] 2018-04-01 00:36
Btw, there's another potentially related bug that happens if you remove [this feature flag override](https://github.com/facebook/react/blob/0c80977061ba576cee9ae0891245be233929d2ed/packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js#L24) that manifests as an `Unexpected pop` warning. Maybe we should change this test suite to use the feature flag that people use in real bundles? This doesn't leave me very confident.

**Comment by gaearon** [comment] 2018-04-01 00:50
Added failing tests in https://github.com/facebook/react/pull/12508.

**Comment by gaearon** [comment] 2018-04-03 23:36
Fixed in https://github.com/facebook/react/pull/12508

**Closed by gaearon** 2018-04-03 23:36 UTC
Labels: Type: Bug

**Comment by onpaws** [comment] 2018-04-05 23:38
Cheers, this PR just saved us from what would have been a confusing day!

**Comment by JeffUberman** [comment] 2018-04-19 20:39
I've upgraded to React v16.3.2 and am seeing a similar error: 

<img width="1199" alt="screen shot 2018-04-19 at 3 02 50 pm" src="https://user-images.githubusercontent.com/7062515/39015394-e4bdce6a-43e2-11e8-909a-1120d36d8a30.png">

It's referencing a similar area of the React codebase, without a null check:

<img width="673" alt="screen shot 2018-04-19 at 3 06 20 pm" src="https://user-images.githubusercontent.com/7062515/39015541-4dad88de-43e3-11e8-88f4-6ee803f578f4.png">

**Comment by gaearon** [comment] 2018-04-19 21:51
Please file a new issue with a reproducing case. Thanks.

**Comment by gaearon** [comment] 2018-05-04 20:35
To everyone who "+1"s the previous comment: sorry, but this doesn't help us solve the issue at all.

If you're seeing this after upgrading both `react` and `react-dom` to 16.3.2 or higher, **please file a new issue with a minimal reproducing case extracted from your project**. This will be very helpful to everyone, and we'll be able to quickly diagnose and fix this.
