### ISSUE TITLE
warn:It looks like Index is reassigning its own `this.props` while rendering,This is not supported and can lead to confusing bugs.

### ISSUE THREAD

**Issue by Dengzygx** [facebook/react#14494] opened 2018-12-26 03:12 UTC
when I try to update react from 15.4.1 to 16.7.0，what's wrong with this?

**Comment by Razzwan** [comment] 2019-01-08 22:30
The same, when updated from 16.3.1 to 16.7.0 version

**Comment by gaearon** [comment] 2019-01-18 03:05
It should tell you which component is doing that. That component has a bug which needs to be fixed.

Please provide a reproducing example if you can't fix the bug on your own. Thanks!

**Comment by Yingkaixiang** [comment] 2019-02-25 06:25
I ran into the same problem when I use [react-css-modules](https://github.com/gajus/react-css-modules) to wrap my component.

```js
import CSSModule from "react-css-modules";
import styles from "./index.less";

class Demo extends React.Component {
  ...
}

export default CSSModule(styles)(Demo);
```

Warning: It looks like Demo is reassigning its own `this.props` while rendering. This is not supported and can lead to confusing bugs.

**Comment by gaearon** [comment] 2019-02-25 11:50
I would recommend against the approach used by that library (overriding props). It’s fragile and unsupported.

However, they did fix the warning in https://github.com/gajus/react-css-modules/commit/5e787d41192c96d5650a3036443cff2bb977cd39. If the fix is not released yet please file an issue in that library.

**Closed by gaearon** 2019-02-25 11:50 UTC
Labels: Resolution: Needs More Information, Type: Question

**Comment by Yingkaixiang** [comment] 2019-02-26 05:59
Thanks very much and I am considering removing the dependency on this package
