### ISSUE TITLE
How to work with web component?

### ISSUE THREAD

**Issue by minipai** [facebook/react#2701] opened 2014-12-13 15:55 UTC
I want to use https://github.com/github/time-elements

But in JSX Gotchas http://facebook.github.io/react/docs/jsx-gotchas.html
says React won't render is="" attribute.

Fill this fixed? Or there is workaround?

**Comment by jsfb** [comment] 2015-01-09 21:28
I think this is effectively a duplicate of https://github.com/facebook/react/issues/2746, so I'm going to close as duplicate.  Please reopen if this is the incorrect action.

**Closed by jsfb** 2015-01-09 21:28 UTC
Labels: Resolution: Duplicate
