### ISSUE TITLE
React Performance with bound functions

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#5197] opened 2015-10-16 18:32 UTC
When I'm abstracting a components, I sometimes find it necessary to bind a function to a parameter before passing it to a child component. 

For example, if I have a list of counters, we want to bind the increment prop to increment the appropriate counter.

```js
counts.map((count,i) => {
 return <Counter count={count}  inc={this.incCount.bind(this, i)/>
})
```

This always returns a new function even though incCount, this, and i are all referentially equal. But every time you bind them, you get a new function. 

It also wouldnt make sense to entirely rewrite counter to accept incAtIndex and index.

And it seems crazy to create some kind of helper component.

```js
<BoundFunc f={this.incCount} args={[i]} props={{count}} render={(f, props} => {
  return <Counter {...props} inc={c}/>
}}/>
```

Anyways, has there been any thought put into this? It would be amazing (and help with performance) if there was some way (perhaps non-native way) that we can accomplish the following, specifially in react

```js
a = f.bind(x,y)
b = f.bind(x,y)
a === b
// => true!
```

**Comment by jimfb** [comment] 2015-10-16 18:36
Bind generates a new function, so it's not going to be triple equals equal.  I'm not sure how we can get around this.

The good news is: from a performance perspective, we do not actually update the DOM node when a callback function changes.

Have you been running into performance problems due to bound functions?

**Comment by syranide** [comment] 2015-10-16 18:36
Personally I use a special PureRenderMixin:ish base class that ignores functions when comparing prev/next, far from perfect, but works well enough.

@jimfb The problem is that if every component you create receives a bound function, then *all* components will re-render every time.

**Comment by jimfb** [comment] 2015-10-16 18:38
@syranide Yeah, I agree, but...
 > Bind generates a new function, so it's not going to be triple equals equal. I'm not sure how we can get around this.

Do you have any ideas?

**Comment by syranide** [comment] 2015-10-16 18:43
@jimfb WeakMap seems like the best near-term solution, but it's a bit cumbersome to use for this for something that should be trivial (or JS getting its shit together and offering better utilities for comparison).

**Comment by STRML** [comment] 2015-10-16 18:54
@ccorcos I've used a pattern like this to get around the issue:

```js
class Counter extends React.Component {
  static propTypes = {
    inc: React.PropTypes.func.isRequired,
    count: React.PropTypes.number.isRequired,
    counterIdx: React.PropTypes.number.isRequired
  }
  onClick(e) {
    this.props.inc(this.props.counterIdx);
  }
  render() {
    return <div onClick={this.onClick}>{this.props.count}</div>
  }
}
```

**Comment by gaearon** [comment] 2015-10-16 19:19
Yes, passing index as a prop is what I do in perf tight scenarios too.

**Comment by ccorcos** [comment] 2015-10-16 19:34
@STRML yeah, the problem with this is code reuse. You have to change the counter component!

@syranide That's what I'm thinking -- use a pure render mixin that doesnt care about functions. But what happens when the function keeps getting passed down. Maybe a component 2 layers below has the old bound function when the counter was at a different index...

@jimfb One hack would be an LRU cache or something to hold references to bound functions. 

I think the best solution would be to have something baked into React.

```js
React.addons.bind = function(f, ctx, ...args) {
  bound = function(...moreArgs) { return f.apply(ctx, args.concat(moreArgs)) }
  bound.f = f
  bound.args = args
  bound.REACT_BOUND_FUNCTION = true
  return bound
}
```

React can look for that special key to do a shallow comparison on the arguments and the function during reconcilliation. There would need to be some more code to handle binding more than once.

**Comment by syranide** [comment] 2015-10-16 19:37
@ccorcos You'll have to make sure to always bind the same function and arguments, if something needs to be dynamic you'll have to bind a local method which holds the logic instead.

**Comment by ccorcos** [comment] 2015-10-16 20:59
Yes. Well in every case I've run into, it always boils down to a single function reference. e.g. `this.incCount` here:

```js
counts.map((count,i) => {
 return <Counter count={count}  inc={this.incCount.bind(this, i)/>
})
```

An more simple solution would be if React checked for a `.equals` method during reconciliation. That would be more generalized. With that, here's how we could solve the binding issue:

```js
shallowListEq = function(a,b) {
  if (a.length === b.length) {
    // no Array.zip in ES6?!
    for (var i = 0; i < a.length; i++) {
      if (a[i] !== b[i]) {
        return false
      }
    }
    return true
  }
  return false
}

React.addons.bind = function(f, ctx, ...args) {
  // f could already be a REACT_BOUND_FUNCTION so we want to maintain
  // the argument and function references.
  let prevArgs = (f.args || [])
  bound = function(...moreArgs) { 
    return f.apply(ctx, prevArgs.concat(args.concat(moreArgs))) 
  }
  // keep the previous f if it exists
  bound.f = (f.f || f)
  bound.args = prevArgs.concat(args)
  bound.REACT_BOUND_FUNCTION = true
  bound.equals = function(g) {
    return g.REACT_BOUND_FUNCTION && f.f === g.f && shallowListEq(f.args, g.args)
  }
  return bound
}
```

**Comment by ccorcos** [comment] 2015-10-17 19:15
Oh yeah. You're right. I totally missed the context part of it. We can keep an array of contexts and do a shallow compare of those as well. Then iterate though binding them with arguments.  I'll redo this example later...

**Comment by ccorcos** [comment] 2015-10-21 04:13
ok. How about this guy:

```jsx
React.addons.bind = function(f, ctx, ...args) {
  bound = f.apply(ctx, args)
  // book keeping
  bound.f = (f.f || f)
  bound.ctx = (f.ctx || []).concat(ctx)
  bound.args = (f.args || []).concat(args)
  bound.REACT_BOUND_FUNCTION = true
  bound.equals = function(g) {
    return (
      g.REACT_BOUND_FUNCTION && 
      bound.f === g.f && 
      shallowListEq(bound.args, g.args) && 
      shallowListEq(bound.ctx, g.ctx)
    )
  }
  return bound
}
```

**Comment by tomwidmer** [comment] 2016-01-13 12:25
It's also annoying that this will always re-render Counter when the parent re-renders:
```javascript
counts.map((count,i) => {
 return <Counter count={count}  inc={() => this.context.dispatch(incAction, i)}/>
})
```
I guess this is a hard problem to solve in JS, though at least the binding one has solutions as proposed above.

For the bind one, don't you just have to implement a suitable shouldComponentUpdate (in a base class or mixin) that handles equality comparisons on REACT_BOUND_FUNCTION things (and otherwise is like the pure render mixin)? No need for core React changes, unless I'm missing something... Without shouldComponentUpdate, react always has to re-render (regardless of reconciliation), since it doesn't know that you haven't mutated the props. As @jimfb mentions, updating the callbacks when a render has happened is fast enough already, since it doesn't manipulate the DOM, so the place to optimize is in preventing the render happening at all (particularly for a large sub-tree).

**Comment by jimfb** [comment] 2016-01-13 13:41
This is a great discussion, but I'm not seeing anything actionable in this thread (unless I missed something, let me know and we can re-open).  For this reason, I'm going to close the issue, since it's not an actionable bug in the React core.  However, I encourage you guys to continue the discussion in this thread, or move it to StackOverflow / discuss.reactjs.org / reactiflux.com / whatever.

**Closed** 2016-01-13 13:41 UTC

**Comment by ccorcos** [comment] 2016-01-14 00:11
@jimfb certainly not a bug, just a feature.

@tomwidmer finally someone is feeling my pain, haha. You could definitely implement your own shouldComponentUpdate. But you'll end up having to create some sort of bind function that works.

One solution I've just recently discovered is this:

In the Elm/Redux pattern, you're effectively doing this:

```js
const view = (dispatch, state) => {
  const inc = () => dispatch({type:'inc'})
  return <Counter count={state.count}  inc={inc}/>
}
```

You can gain some performance if you deal directly with the streams rather than pushing them out to the edges.

```js
const view = (dispatch$, state$) => {
  const inc = () => dispatch$({type:'inc'})
  return state$.map((state) => {
    return <Counter count={state.count}  inc={inc}/>
  })
}
```

Dealing with lists of counters proves a little more annoying, but you could totally do it with this pattern.

**Comment by jimfb** [comment] 2016-01-14 00:18
@ccorcos Is there an actionable feature here?  As far as I can tell, there is nothing actionable within the core.  Anything that could be done can be an external addon (we're not adding more addons to the repository; eventually we'd like to get them all into separate repositories).  Anyway, let me know if there is something that we can/should do in the core to make this better.  Otherwise, let's solve this outside the core.

**Comment by STRML** [comment] 2016-02-01 14:22
Here's a solution that I've added to my component superclasses (but you could just as easily import it and assign the fn to the class). It doesn't require any changes to SCU and garbage collects properly when the component dies.

```js
    class SuperComponent extends React.Component {
      // Preserve reference equality at all costs!
      // We do this by creating a bound function, then storing a reference to it based
      // on the identity of the source function. Consider this like .bind(), except it always
      // returns the same fn for the same callback & data.
      _bindCallback(callback, data) {
        this.callbacks = this.callbacks || new Map();
        let dataMap = this.callbacks.get(callback);
        // Check if we've already got it.
        if (dataMap && dataMap.get(data)) return dataMap.get(data);
        else if (!dataMap) dataMap = new Map();

        let fn = callback.bind(this, data);
        dataMap.set(data, fn);
        this.callbacks.set(callback, dataMap);
        return fn;
      };
      
    }
```

**Comment by ccorcos** [comment] 2016-02-01 20:32
nice. my goal was to hopefully make it more functional -- for example, this wouldnt work for stateless components.

**Comment by STRML** [comment] 2016-02-01 21:21
True, but it seems you generally wouldn't have the same problems in stateless components; a stateless component generally should be a leaf node. It doesn't make much sense to me to use a stateless component to instantiate an array of children (which is usually why you'd want to bind data to a callback).

**Comment by oztune** [comment] 2016-02-01 21:49
Agreed with @STRML. In my experience stateless components are very difficult to optimize anyway.

**Comment by ccorcos** [comment] 2016-02-01 22:30
Yeah, I'm not going to argue with that. I've just been playing around with Elm and those kinds of architectures where the entire state is held in an atom and passed down through stateless components. So the entire UI is stateless.
