### ISSUE TITLE
Bug: Elements with opacity values set with percentage are set to 1% in production. This makes them "invisible."

### ISSUE THREAD

**Issue by THEmmanuel** [facebook/react#24628] opened 2022-05-27 15:29 UTC
React version:
17.0.2, previous versions too

## Steps To Reproduce

1. Set an elements opacity to a value like 50%
2. Deploy to production and it's changed to 1%

## The current behaviour
The opacity of an element gets set to 1% in production if the value in its CSS rulesets is in percentage, Like 70%

## The expected behaviour
The opacity value should be 70% (for example)

Way to bypass this is to use decimals while setting opacity in CSS.

Like opacity: 0.7;
Instead of opacity: 70%;

**Comment by gaearon** [comment] 2022-05-27 18:00
Can you provide a reproducing case please?

**Comment by THEmmanuel** [comment] 2022-05-27 22:20
Sure!
I've created a code sandbox here:
https://codesandbox.io/s/musing-liskov-p4w1hr

Hosted here on Netlify as the production environment:
https://csb-p4w1hr.netlify.app/

The first element has its opacity set to 70% and is completely invisible.

**Comment by eps1lon** [comment] 2022-05-28 10:22
Duplicate of https://github.com/facebook/react/issues/20569. See the last comment in https://github.com/facebook/react/issues/20569 for the current state of this issue.

**Closed** 2022-05-28 10:24 UTC
Labels: Status: Unconfirmed
