### ISSUE TITLE
Provide a better message when component type is undefined with SSR

### ISSUE THREAD

**Issue by lukasborawski** [facebook/react#11902] opened 2017-12-21 14:55 UTC
This might be a reference to this one: https://github.com/facebook/react/issues/10212#issuecomment-346302374

The problem still exist.

So, trying to render with server side and got this error. I don't have this notation in my code but this might be a problem with dependencies.

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at ReactDOMServerRenderer.renderDOM (/Users/lukasborawski/Dev/web-client/node_modules/react-dom/cjs/react-dom-server.node.development.js:2304:27)
...
```

```
"react": "^16.1.1",
"react-dom": "^16.2.0",
```

Thx for help.

**Comment by aweary** [comment] 2017-12-21 17:11
@lukasborawski you should be running the same versions of `react` and `react-dom`. Using two different versions (especially minor or major versions) can lead to unexpected behavior. Can you try updating `react` to `16.2.0` and see if your issue persists?

Otherwise, we'll need an example that reproduces the issue so we can investigate it.

Thanks!

**Comment by trebushuk** [comment] 2017-12-22 13:29
Have a same issue.
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at a.renderDOM (/home/{username}/Workspace/{progect}/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:420)
```
In the first argument of `renderDOM` is passed this kind object:
```js
{ '$$typeof': Symbol(react.element),
  type: undefined,
  key: null,
  ref: null,
  props: {},
  _owner: null }
```
Versions of `react` and `react-dom` was same. I have updated both of it and nothing changed.
```diff
-    "react": "^16.0.0",
+    "react": "^16.2.0",

-    "react-dom": "^16.0.0",
+    "react-dom": "^16.2.0",
```

**Comment by gaearon** [comment] 2017-12-22 14:03
Please provide a reproducing project. We can’t help otherwise.

**Comment by gaearon** [comment] 2017-12-22 14:04
(My best guess is you imported a component incorrectly and thus ended up with `undefined` as a type. We should change to throw a better error when this happens.)

**Comment by trebushuk** [comment] 2017-12-25 17:15
@gaearon This project that should reproduce the issue
https://github.com/trebushuk/test-react-project
I tryed on the versions of node `v6.12.2` & `v9.3.0`

**Comment by lukasborawski** [comment] 2017-12-27 11:52
@aweary @gaearon @trebushuk I've updated the react version to 16.2 and still have this issue. Looked up for components imports and all looks fine, typical and normal. Can't share the project bc this one is customers private. Any other ideas?

**Comment by yerlanyr** [comment] 2017-12-28 16:49
That project should reproduce the issue. https://github.com/yerlanyr/reactrouterserver
````
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `AppRoot`.
    at invariant (C:\Data\FrontendProjects\reactrouterserver\node_modules\fbjs\lib\invariant.js:42:15)
    at instantiateReactComponent (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\instantiateReactComponent.js:72:56)
    at instantiateChild (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\ReactChildReconciler.js:42:28)
    at C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\ReactChildReconciler.js:69:16
    at traverseAllChildrenImpl (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\traverseAllChildren.js:75:5)
    at traverseAllChildren (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\traverseAllChildren.js:170:10)
    at Object.instantiateChildren (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\ReactChildReconciler.js:68:7)
    at ReactDOMComponent._reconcilerInstantiateChildren (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\ReactMultiChild.js:183:41)
    at ReactDOMComponent.mountChildren (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\ReactMultiChild.js:222:27)
    at ReactDOMComponent._createContentMarkup (C:\Data\FrontendProjects\reactrouterserver\node_modules\react-dom\lib\ReactDOMComponent.js:657:32)
````

**Comment by lukasborawski** [comment] 2017-12-29 20:22
For me this was a problem with `ServerRouter`, changed to the `StaticRouter` and everything is fine now.

**Comment by gaearon** [comment] 2018-01-02 16:00
We should probably provide a better error message if component type is undefined.

**Comment by HeroProtagonist** [comment] 2018-01-02 17:08
If no one is working on this I can do it today or tomorrow also happy new year!

**Comment by gaearon** [comment] 2018-01-02 17:09
Sure!

**Comment by timneutkens** [comment] 2018-02-02 11:05
@gaearon looks like it's fixed in master, tried building and got this:

```
Invariant Violation: Element type is invalid: expected a string (for built-incomponents) or a class/function (for composite components) but got: undefined.
```

To reproduce the issue on the currently released version:

```
const ReactDOMServer = require('react-dom/server')
const React = require('react')
const X = undefined
ReactDOMServer.renderToString(React.createElement(X, {}))
```

So I guess both this one and PR #11966 can be closed 👌

**Comment by HeroProtagonist** [comment] 2018-02-02 17:16
@gaearon and @timneutkens I just was looking at this last night (after a hiatus) and saw that it was essentially fixed. I updated my PR to match the error in `ReactFiber.js` and put a test for it. In case that is desired.

**Closed** 2018-02-05 17:09 UTC
Labels: Component: Server Rendering, Difficulty: starter, good first issue (taken)
