### ISSUE TITLE
Bug: React.Node should not have `true`, or PropTypes.node warns it

### ISSUE THREAD

**Issue by ypresto** [facebook/react#17871] opened 2020-01-19 19:30 UTC
React version: 16.8.6

## Steps To Reproduce

```js
import PropTypes from 'prop-types';

type Props = {
  component: React.Node
};

function Container(props: Props) {
  return ...;
}

Container.propTypes = {
  component: PropTypes.node
}

<Container component={true} />
```

## The current behavior

Flow does not emit error (as React.Node accepts `true`), but PropTypes.node emits below runtime error in browser's console.

```
Invalid prop `component` supplied to `Container`, expected a ReactNode.
```

## The expected behavior

Flow emits type error.

----

[According to a maintainer of prop-types](https://github.com/facebook/prop-types/issues/310#issuecomment-574986751), formerly React itself did not accept `true` for JSX node (in flow `React.Node`) (so not changing prop-types for now), is it right?

**Comment by ljharb** [comment] 2020-01-19 20:16
Note; I’m not claiming that, I’m suggesting it as a possible history. Clarification would be appreciated.

**Comment by bvaughn** [comment] 2020-01-19 21:49
> ## The expected behavior
> Flow emits type error.

Why is this the expected behavior?

[The React docs say](https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored):
```js

```

**Comment by ljharb** [comment] 2020-01-19 22:07
I’m wondering if perhaps true was invalid prior to react 15?

**Comment by bvaughn** [comment] 2020-01-20 17:55
Not sure! I wasn't on the team before v15. 🙂

I don't think that would change my stance on this issue though. I don't think this is a bug or requires any change from React.

**Comment by ljharb** [comment] 2020-01-20 18:36
It requires a change in prop-types, however, (which i maintain) so it’d be useful to determine exactly when it changed. That said, there’s probably nothing actionable for react to do at this point and the issue can be closed.

**Comment by bvaughn** [comment] 2020-01-21 00:11
Right, my comment was only meant for React. Looks like there's a separate issue filed against `prop-types` (https://github.com/facebook/prop-types/issues/310). I'm going to go ahead and close this issue down.

**Closed by bvaughn** 2020-01-21 00:11 UTC
Labels: Status: Unconfirmed, Type: Discussion

**Comment by ljharb** [comment] 2020-01-21 01:01
Did some testing; looks like React 15 disallowed `true`; React 16 allows it. I'll update the `prop-types` package.
