### ISSUE TITLE
[DevTools Bug]: 'Unable to find React on the page' in incognito on Firefox

### ISSUE THREAD

**Issue by MaxLeiter** [facebook/react#26462] opened 2023-03-22 18:12 UTC
### Website or app

https://react.dev

### Repro steps

1. Open an incognito tab
2. visit a react 18 website
3. try and use dev tools (I'm on `4.27.1`)

<img width="1728" alt="CleanShot 2023-03-22 at 11 10 16@2x" src="https://user-images.githubusercontent.com/8675906/226998803-79f8e57b-ab7f-46e1-9cad-8744fe92296a.png">

### How often does this bug happen?

Every time

**Comment by aynp** [comment] 2023-03-28 19:50
Duplicate of #16547

**Closed** 2023-03-28 20:47 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools
