### ISSUE TITLE
Badly timed update makes it impossible to determine the new value in checkbox's `onChange` handler

### ISSUE THREAD

**Issue by hon2a** [facebook/react#9151] opened 2017-03-10 15:48 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature, I guess, despite the subject formulation.

**What is the current behavior?**

If an update is performed exactly at the wrong moment (on native `click` capture on document root), it happens just between the moment React decides that the `onChange` handler for a checkbox should be called and the moment it is called. As a result, it's impossible to tell what the new value is inside the `onChange` handler. (In other words, in that particular case, `event.target.checked` is back to the old unchanged value when the `onChange` handler is called.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

[Here](https://jsfiddle.net/hon2a/dwofvdye/)'s a demo. Note how clicking on the checkbox never checks it.

**What is the expected behavior?**

That's up for discussion. I'd probably expect the `onChange` not to be triggered at all, and a warning to be issued, so that it's easier to figure this out and remove the cause (it took me quite some time :)). Even nicer would be some special property of the `SyntheticEvent` holding the correct changed value, but that might be too big of a change for such a edge-case scenario.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Chrome / Win / React 15.4.1 (but it likely applies to all browsers/OS)

**Comment by gaearon** [comment] 2017-03-10 16:14
cc @aweary @nhunzaker @jquense

**Comment by aweary** [comment] 2017-03-10 17:43
I would say it's probably an unsupported pattern that should be avoided (we provide capture listeners if you need them, .e.g, `onClickCaputre`).

The issue is that the `setState` call in the capture phase forces [`ReactDOMInput.updateWrapper` to set the `checked` property](https://github.com/facebook/react/blob/e452e3374135c116ef687a8bb3a5d277e3cde8fb/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js#L166-L172) to whatever it is in `props`, so the newly updated `checked` value is reset by the time the top-level event listener is invoked.

Since the `setState` call issued in the capture phase occurs before the top-level listener is invoked, it would be difficult to know if a DOM update would disrupt a pending event dispatch.

**Comment by jquense** [comment] 2017-03-10 17:47
hehe @aweary beat me too it. I'd agree tho, I think this falls outside a reasonably supported use case. @hon2a could you talk a bit about _why_ you need to do this? In general your gonna be in for some hurt preempting the React event system.

**Comment by hon2a** [comment] 2017-03-10 20:26
Sure, here's my use-case: I'm managing a library of basic UI components. In some of them, e.g. `Dropdown`, I need to listen to events _outside_ the component, which falls outside of the component's basic scope. (I want the `Dropdown` to close when you interact with something outside it.) I have a simple function `listenOutsideElement` that does this by subscribing to the event at document root in capture phase (so as to avoid being prevented by `stopPropagation`). It's not ideal but it worked just fine up to this point (apart from problems with unit-testing).

I've created the issue mostly hoping to save someone else the time with that warning, as it took me quite a while to figure out. (Suddenly there was this place where checkboxes were returning the wrong value in `onChange`.) I've created a work-around for now. To resolve it properly, I'd probably have to provide a service handling these document-level tasks through context, so that they can make use of React event system and make the components using them testable as well.

So yeah, I did get to the issue by playing dirty :)

**Comment by jquense** [comment] 2017-03-10 20:39
you might want to check out how we managed the same sort of functionality in [react-overlays](https://github.com/react-bootstrap/react-overlays/blob/master/src/RootCloseWrapper.js) I think we avoid this issue, by tagging an event on `capture` but not doing anything until the bubble phase

**Comment by aweary** [comment] 2017-03-17 22:31
great advice! I'm going to close this out since it's an unsupported pattern but @hon2a thanks so much for bringing this to our attention 👍

**Closed by aweary** 2017-03-17 22:31 UTC

**Comment by hon2a** [comment] 2017-03-18 08:28
@jquense Thanks for the tip, I'll be sure to check it out.
