### ISSUE TITLE
Use Semvar

### ISSUE THREAD

**Issue by AdamHess** [facebook/react#5077] opened 2015-10-07 22:06 UTC
The versioning scheme is actually quite childish and doesnt comply with any industry standard. 
-
major.minor.patch

major - this will break previous libraries that use this

minor - this adds new functionality/features

patch - something is broken

0 indicates that its still in development and anything can change at any time. Yet people are already using your product in production and relying heavily on it.  You send a message to your end users that you do not care about them or their compatibility issues by not using semantic versioning. 

NodeJs finally moved to real semantic versioning with IOJS merged in they are now up to 4.1.2 and clearly explains the backward compatability issues with the different versioning.

**Comment by jimfb** [comment] 2015-10-07 22:27
Every stable (a release that we would expect people to use) includes breaking changes.  We use React in production at Facebook, so we'll do our best to remain as stable as we can, but we are still figuring out the optimal API.  At some point, we will transition past 0.*, and then we'll follow semver.

Duplicate of https://github.com/facebook/react/issues/4998

**Closed by jimfb** 2015-10-07 22:27 UTC

**Comment by camspiers** [comment] 2015-10-08 00:27
React is actually using semver. As it is still at MAJOR 0, public API breakages are fine in both MINOR and PATCH versions (though React doesn't actually make breaking changes in PATCH). React provides warnings about deprecations and documents the upgrade process in release notes, it also has provided codemodding tools to help the transition: https://www.npmjs.com/package/react-codemod

http://semver.org/

>Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

>Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

React has every intention of moving past MAJOR 0, and React has communicated this:

https://facebook.github.io/react/blog/2014/03/28/the-road-to-1.0.html
https://github.com/facebook/react/wiki/Projects

With all this said, there is this part of semver in the FAQ:

> How do I know when to release 1.0.0?

>If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

But React has given pretty clear a good reasons for their decisions:

https://facebook.github.io/react/blog/2014/03/28/the-road-to-1.0.html

**Comment by AdamHess** [comment] 2015-10-08 19:57
Then stop encouraging people to use it. If it's not a finished product it's not ready for the 1000s of people who are already using it in production environment. You're encouraging bad development practices to stay up to date.

**Comment by zpao** [comment] 2015-10-08 20:01
We've explained things in the past and this isn't a fruitful discussion. If you put that much stock into a version number then you don't need to use React.
