### ISSUE TITLE
Feature request: Warnings hook

### ISSUE THREAD

**Issue by dtinth** [facebook/react#10072] opened 2017-06-29 09:26 UTC
**Do you want to request a *feature* or report a *bug*?**
I want to request a *feature*.

**What is the current behavior?**
- Warning code is hardcoded to call `fbjs/lib/warning`. This makes it hard to integrate warnings with tools.

- As a workaround we could use webpack’s `resolve.alias` to alias `fbjs/lib/warning` into our fork which displays it on-screen.

   - This use case is similar to https://github.com/facebook/react/pull/7360.

- Another use case is to integrate React warnings with our testing infrastructure. This helps us to better see which warning belongs to which test.

    ![image](https://user-images.githubusercontent.com/193136/27680560-587f934a-5ce6-11e7-985b-a1a2042d831a.png)

**What is the expected behavior?**
- React allows library user to override the default warnings behavior.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- The workaround works in React 15 and should still work in React 16, as the flat bundles does `var warning = require('fbjs/lib/warning')` which means we can still hook into it for now.

- This probably breaks when the flat bundles stopped doing `var warning = require('fbjs/lib/warning')`.

**Comment by gaearon** [comment] 2017-07-11 10:23
For now, the easiest workaround is to override `console.error` and `console.warn`. But yes, ideally we’d have an API for this. It’s not super clear what it would look like. We might look at this during 16.x release cycle.

**Comment by dtinth** [comment] 2017-07-11 11:29
@gaearon We’ve considered that approach, but it breaks devtools traceback.

For example, given a file `log.js`:

```js
// log.js
console.error('Warning 1')
console.error('Warning 2')
```

When run, devtools will show the source location where `console.error` was called.

![image](https://user-images.githubusercontent.com/193136/28066283-8e912ece-6666-11e7-9c32-5e66fedbe0ef.png)

By overriding `console.error` like this:

```js
// override.js
console.error = (original => function () {
  return original.apply(this, arguments)
})(console.error)
```

Now all `console.error` calls will be seen as being made from `override.js` always, even if all we do is passing through all errors.

![image](https://user-images.githubusercontent.com/193136/28066250-6bed841c-6666-11e7-8228-264ed104afba.png)

**Comment by gaearon** [comment] 2017-07-11 11:43
Good observation.

**Comment by gaearon** [comment] 2017-10-04 20:05
Going to close as a duplicate of https://github.com/facebook/react/issues/4302.

**Closed by gaearon** 2017-10-04 20:05 UTC
Labels: Type: Feature Request
