### ISSUE TITLE
Input element that type is'number' does not meet expectations

### ISSUE THREAD

**Issue by MrErHu** [facebook/react#10489] opened 2017-08-18 07:27 UTC
For Example:

```javascript
<input type="number" onChange={this._onChange} />
```
In Chrome, you cannot  type a non-number character, in Safari And Firefox, You can type non-number character ,but in this moment value of Change is empty string ""。How can solve this problem?

**Comment by Necmttn** [comment] 2017-08-18 08:35
it's actually not react issue. if you try to open [MDN specs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) in safari or firefox . `<input type="number" />` will have similar behavior.
first of all check this 
https://facebook.github.io/react/docs/forms.html

if you wanna have number validation 
Check this example.
https://codepen.io/Necmttn/pen/PKQNxw?editors=0010

**Comment by aweary** [comment] 2017-08-18 16:24
Hey @MrErHu! This is a known issue and a duplicate of https://github.com/facebook/react/issues/6556. As mentioned, this is mostly browser-dependent and there's no easy way for React to prevent this since the browser isn't triggering the event with the data we need to detect and prevent this. Please refer to https://github.com/facebook/react/issues/6556 for more information. Thanks!

**Comment by aweary** [comment] 2017-08-18 16:24
Duplicate of #6556

**Closed by aweary** 2017-08-18 16:24 UTC

**Comment by MrErHu** [comment] 2017-08-22 03:56
@aweary Thank you so much!!

**Comment by MrErHu** [comment] 2017-08-22 03:58
@Necmttn the demo you provided is not suitable for me, because I need "type" to call virtual keyboards in mobile phone.

**Comment by Necmttn** [comment] 2017-08-22 04:09
make it `number` won't change effect tough. but you need to play with css a bit to hide s spin toolbox 

check 
https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box
