### ISSUE TITLE
Error: Invalid operand to 'in': Object expected ==> IE10

### ISSUE THREAD

**Issue by Veerbhadra277** [facebook/react#16886] opened 2019-09-25 08:40 UTC
Getting "_Invalid operand to 'in': Object expected_"  error, in react application, I haven't used 'in' operator throughout my application, it seems while bundling react application operator inserted and caused this issue/error.

any help on above issue will be appreciated 

Similar issue for IE 11 but fixed now,
 link -> http://github.com/material-components/material-components-web/issues/2626

**Comment by threepointone** [comment] 2019-09-25 10:57
I don't think React uses any code like this either, but it's hard to comment without an example application, or a reproducing usecase on codesandbox or as a plain git repo. Please share.

**Comment by Veerbhadra277** [comment] 2019-09-25 18:45
Hey sunil thanks for reply !!!
please note following git proj of simple application getting failed in ie10

https://github.com/Veerbhadra277/TestReactjss

**Comment by bvaughn** [comment] 2019-09-25 23:02
I'm a little skeptical of the repro shared, since it doesn't seem to have added the [`Map` and `Set` polyfills required for IE9 and IE10](https://reactjs.org/docs/react-dom.html#browser-support). This means that an error like `'Set' is undefined` would be expected. (Just confirmed on a fresh VM.)

**Comment by bvaughn** [comment] 2019-09-25 23:04
After adding those polyfills, the repo you linked to works fine in IE10, so I'm going to close this issue for now.

**Closed by bvaughn** 2019-09-25 23:04 UTC
Labels: Resolution: Needs More Information
