### ISSUE TITLE
Bug: The initial page load fails in IE11 with React 16.14 and above

### ISSUE THREAD

**Issue by baharev** [facebook/react#20481] opened 2020-12-17 15:24 UTC
I created the simplest *Hello, World!* React application that I can think of. I used CRA. The source code is here:

https://github.com/baharev/ie11bug.git

The deployed application is here:

https://www.baharev.info/sandbox/ie11bug/index.html

The deployed application is what you see in the git repo with React 16.14.0, and that fails in IE11.

You see **Hello, World!** if the page is successfully loaded. It works fine in Firefox, Chrome, Edge, etc. but fails to load in IE11.

React fails to load, and in the dom explorer I see `<div id="root"></div>`. In the Console I get:

```
SCRIPT5022: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
2.72241442.chunk.js (2,239441)
```
which is:

> The full text of the error you just encountered is:
> Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead.

**Note that the very same code works just fine in IE11 with React 16.13.1 and only breaks with 16.14.0 and above.** It also fails with 17.0.1.

Any help is greatly appreciated.

**Comment by eps1lon** [comment] 2020-12-17 19:39
Thanks for the report.

Considering this happens in 16.14 but not 16.13.1 and with the latest react-scripts, I suspect that this is caused by the new JSX transform.

I ran 

```jsx
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import ReactDOM from 'react-dom';

ReactDOM.render(
    <p>Hello, World!</p>,
    document.getElementById('root')
);
```
through https://new-jsx-transform.netlify.app/ which produces
```js
import { jsx as _jsx } from "react/jsx-runtime";
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import React from 'react';
import ReactDOM from 'react-dom';
ReactDOM.render( /*#__PURE__*/_jsx("p", {
  children: "Hello, World!"
}), document.getElementById('root'));
```

What is likely happening that `react/jsx-runtime` is evaluated without polyfills applied and `react-dom` is evaluated with polyfills. This is will likely cause a mismatch in react symbols between `react` and `react-dom` caused by https://github.com/facebook/react/blob/56e9feead0f91075ba0a4f725c9e4e343bca1c67/packages%2Fshared%2FReactSymbols.js#L35-L55.

I think that the babel plugin should not inject `react/jsx-*` at the start so that it's not applied before polyfills. Though I'm not familiar what the recommended approaches for polyfills are and it might be possible that these should be loaded differently. 

@gaearon Should we change the babel plugin or has React a documented recommendation for how to apply polyfills?

**Comment by baharev** [comment] 2020-12-17 20:27
@eps1lon Thanks for the prompt reply.

> has React a documented recommendation for how to apply polyfills?

See here https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill#react-app-polyfill

I think I followed the documentation as best as possible.

**Comment by eps1lon** [comment] 2020-12-17 20:58
> See here https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill#react-app-polyfill

> I think I followed the documentation as best as possible.

Would definitely agree there.

Could you try adding `<script src="https://polyfill.io/v3/polyfill.min.js?features=Symbol%2CSymbol.for%2CSymbol.asyncIterator%2CSymbol.unscopables%2CSymbol.toStringTag%2CSymbol.toPrimitive%2CSymbol.split%2CSymbol.search%2CSymbol.species%2CSymbol.replace%2CSymbol.prototype.description%2CSymbol.match%2CSymbol.keyFor%2CSymbol.hasInstance%2CSymbol.isConcatSpreadable%2CSymbol.iterator"></script>` inside the `<head />` in https://github.com/baharev/ie11bug/blob/6d7a251f85cf792170701a4d6f875899bc907162/public/index.html#L3-L6 and tell me if the issue persists?

**Comment by baharev** [comment] 2020-12-17 21:16
Yes, it does!

It is now deployed at https://www.baharev.info/sandbox/ie11bug/index.html and renders in IE11.

**Comment by baharev** [comment] 2020-12-17 21:19
Yes, it does solve the problem!

It is now deployed at https://www.baharev.info/sandbox/ie11bug/index.html and renders in IE11.

**Comment by baharev** [comment] 2020-12-17 21:27
OK, so you have figured out why it is happening, and we now know that importing `react/jsx-runtime` after the polyfills indeed solves the problem. That's good.

Unfortunately, I would need a solution where the polyfill is in my bundle, and I don't have to connect to a third-party website, polyfill.io in this case. (For the time being, I am fine with React 16.13.1 as a workaround.)

**Comment by eps1lon** [comment] 2020-12-17 22:32
I've opened https://github.com/babel/babel/issues/12522 since I believe it's the responsibility of the plugin. If they confirm the issue I'm going to close this one. 

Naively, React should either require a symbol polyfill or use numbers. That would at least give us a clearer error message what went wrong. Though I don't understand what problems global Symbols solve for React here.

**Comment by eps1lon** [comment] 2020-12-17 22:43
Closing in favor of https://github.com/babel/babel/issues/12522. If you want to be notified when this is fixed, subscribe to updates of https://github.com/babel/babel/issues/12522.

**Closed by eps1lon** 2020-12-17 22:43 UTC
Labels: Type: Needs Investigation

**Comment by baharev** [comment] 2020-12-17 22:57
@eps1lon I would argue that React also has a code issue, regardless of babel. The problem is that right hand does not know what the left hand is doing. To be more specific, this check:

```
if (typeof Symbol === 'function' && Symbol.for) {
```

is repeated twice, and if I load the polyfill in between, you get a different answer in IE11 the second time. 

One way to fix this would be to **store the result of the check** the first time in `react/jsx-runtime`, and the second time ask how `react/jsx-runtime` was loaded (with or without Symbols), but don't repeat the check, just load the result of the check from `react/jsx-runtime`. In that case, you would get a consistent behaviour, even if I load the polyfill in between. I would argue that this inconsistency is sort of a code issue in React.

I looked at many of the issues that have been raised due to this inconsistency (I am not the first one who got bitten by this issue), and my above suggestion would solve it, I think.

>  I don't understand what problems global Symbols solve for React here.

My guess would be debugging. Symbols are nicer to look at than numbers. But I am just guessing.
