### ISSUE TITLE
ReactTestRenderer outputs undefined html tag

### ISSUE THREAD

**Issue by Joey92** [facebook/react#7392] opened 2016-08-01 15:45 UTC
We're currently starting test coverage with Jest and are using the ReactTestRenderer to compare against Snapshots. We're running into this issue here:

I have a simple component just rendering a prop. Leaving PropTypes out for now.
```jsx
const PocComponent = (props) => (
    <div>
        {props.someAttribute}
    </div>
);

export default PocComponent;
```

We use this in a Test
```jsx
...
import POC from '../PocComponent';

describe('POC', () => {
    it('should work', () => {
        const component = ReactTestRenderer.create(
            <POC
                someAttribute={1}
            />
        );
        const tree = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
```

ReactTestRenderer gives us this output in the snapshot:
```jsx
exports[`POC should work 1`] = `
<div>
  <undefined />
</div>
`;
```

if we pass someAttribute as a string, instead of a number, the snapshot is generated as expected with the number 1 instead of the tag `undefined`.

Am using React & ReactTestRenderer v. 15.3.0

**Comment by spicyj** [comment] 2016-08-01 22:33
I can't reproduce this. This test passes for me:

```
  it('renders a simple component', function() {
    function Link() {
      return <a role="link">{1}</a>;
    }
    var renderer = ReactTestRenderer.create(<Link />);
    expect(renderer.toJSON()).toEqual({
      type: 'a',
      props: { role: 'link' },
      children: [1],
    });
  });
```

**Comment by Joey92** [comment] 2016-08-02 08:58
Hey spicyj,

that test passes for me, too. The issue here is rather the generated output of the function `toMatchSnapshot`

```jsx
it('renders a simple component', function() {
        function Link() {
            return <a role="link">{1}</a>;
        }
        var renderer = ReactTestRenderer.create(<Link />);
        expect(renderer.toJSON()).toMatchSnapshot();
    });
```
With this modification it will generate a snapshot file with this contents:
```jsx
exports[`POC renders a simple component 1`] = `
<a
  role="link">
  <undefined />
</a>
`;
```

**Comment by Joey92** [comment] 2016-08-02 09:31
Maybe this is an issue with jest, rather than react?

**Comment by zpao** [comment] 2016-08-02 17:01
Yea, that would be an issue with Jest. I see you filed https://github.com/facebook/jest/issues/1352 so let's close this one.

**Closed by zpao** 2016-08-02 17:01 UTC
