### ISSUE TITLE
React component passed as children to some component down nullifies effect of PureComponent

### ISSUE THREAD

**Issue by anuprai11** [facebook/react#11203] opened 2017-10-12 07:46 UTC
I don't know if this would come under feature request or a bug or if this is just expected and things should be handled differently in shouldComponentUpdate.

Current behaviour : If A is a component which renders B and passes C as children to B. Now if A re-renders for some state change of which no part is passed to B or C so basically nothing changes in the subtree of B. B still always re-renders.

https://jsfiddle.net/7utuxyfp/1/

this is the fiddle to reproduce this issue. Click on C to make state change in A and B re-renders.

Here the effect is not much but in some cases children is passed some level deep and can cause un-necessary re-renders.

this is in React-16 and previous versions.

https://stackoverflow.com/questions/46660619/react-children-rendering-procedure

this is a question where some of the observations are posted feel free to answer there only if this is expected or should be handled in a different way. :)

**Comment by gaearon** [comment] 2017-10-12 11:05
Closing as a duplicate of https://github.com/facebook/react/issues/7412.
(Yes, this is expected.)

**Closed by gaearon** 2017-10-12 11:05 UTC
