### ISSUE TITLE
Able to create new events

### ISSUE THREAD

**Issue by argentum47** [facebook/react#8665] opened 2016-12-31 07:07 UTC
I want a feature.

To be able to extend the SyntheticUIEvents, so that I can add my own Event when required.
Thank you.

**Comment by aweary** [comment] 2017-01-04 16:34
Closing as a duplicate of https://github.com/facebook/react/issues/4645

**Closed by aweary** 2017-01-04 16:34 UTC
Labels: Resolution: Duplicate

**Comment by argentum47** [comment] 2017-02-12 16:53
cool
