### ISSUE TITLE
[DevTools Bug]: Blank tools localhost only

### ISSUE THREAD

**Issue by FanatiG** [facebook/react#22577] opened 2021-10-18 10:24 UTC
### Website or app

google.com

### Repro steps

This started after last update 4.20.0
![image](https://user-images.githubusercontent.com/11052469/137713404-e6702959-7870-46a6-8566-4cfe61d25309.png)
![image](https://user-images.githubusercontent.com/11052469/137713464-c5e478d2-4e9e-4ee4-abdf-83d23c04704b.png)

### How often does this bug happen?

Every time

**Comment by FanatiG** [comment] 2021-10-18 11:00
Sorry for the
"Website or app
google.com"
But it just didnt work with 
"Website or app
localhost"

**Comment by FanatiG** [comment] 2021-10-18 11:29
I've tried with netflix but it doesn't seem to work, sadly =( thanks for your advise anyways! may be it will help someone else

**Comment by Sayvai** [comment] 2021-10-18 11:39
> I've tried with netflix but it doesn't seem to work, sadly =( thanks for your advise anyways! may be it will help someone else

I've updated my original comment, with the addition of [CNN](https://edition.cnn.com/) React site, which is proven to reliably work as a workaround, so try that too.

But also found it does not work with the **PayPal** React site as a workaround.

**Comment by FanatiG** [comment] 2021-10-18 11:41
Sadly didn't work as well

**Comment by Sayvai** [comment] 2021-10-18 12:00
Does React Dev Tools load up elements when you navigate to Netflix or CNN? If not then, here is a refined step-by-step set of instructions for a workaround:

- Open a new tab
- Ensure Chrome Dev Tools is not open at all
- navigate to [CNN](https://edition.cnn.com/) (loads faster than Netlfix)
- Open Chrome Dev Tools > React Dev Tools
- The React elements should load up and display for [CNN](https://edition.cnn.com/) site (probably most important here)
- Click on any React element within React Dev Tools
- Now navigate to your localhost site

**Comment by Sayvai** [comment] 2021-10-18 13:21
This bug also affected my colleague as of today, where the workaround i posted resolved the issue for now, and his version of React Dev Tools is also `4.20.0`.

Besides, as requested, here's my list of **enabled** Chrome extensions:
- Awesome Screenshot and Screen Recorder
- daily.dev | The Homepage Developers Deserve
- Ghostery – Privacy Ad Blocker
- Google Docs Offline
- Honey
- Octotree - GitHub code tree
- Picture-in-Picture Extension (by Google)
- React Developer Tools
- Redux DevTools
- Treeverse

**Comment by bvaughn** [comment] 2021-10-18 15:22
@FanatiG We generally ask people to try to reduce bugs to a minimal repro case. Often this is enough for them to remove any sensitive stuff from the app. (Often folks will even realize the specific cause of a bug while doing this.)

Can you try stripping things out of your app until it works to see if you can create a repro like this for us?

**Comment by Sayvai** [comment] 2021-10-18 18:50
@jstejada @bvaughn  - i was on a lookout for other React websites (after some extensive searching) which emits the same behaviour, and i finally found one a React site that is continuously reproducible while using the React Dev Tools on stable version of `4.20.0`. 

The site is a well known public site targeted at Dev / Agile; [Atlassian](https://www.atlassian.com/).

Also worthwhile noting that, i managed to apply my [hacky workaround](https://github.com/facebook/react/issues/22577#issuecomment-945692490) to resolve the issue.

Hopefully, you'll easily be able to debug the issue off the [Atlassian](https://www.atlassian.com/) React website 🤞

**Comment by Sayvai** [comment] 2021-10-18 18:59
Also, i realised i can only reproduce, when opening a new tab, and then open React Dev Tools. But then i close Chrome Dev Tools while staying on Atlassian, and then re-open React Dev Tools, and then this time the Component Tree loads up this time.

Not sure how reliable this method is, but worth pointing out the observation, where opening a new Chrome tab each tab may be a more reliable approach to debug.

**Comment by jstejada** [comment] 2021-10-18 19:33
@Sayvai, unfortunately I can't seem to reproduce the issue on atlassian.com. I am:

- Opening a new tab
- Visit atlassian.com
- Open Chrome Dev Tools
- Open Components Tab

After doing that the Components tree is always showing up, although sometimes it takes about a second for it to show. Are you always able to consistently reproduce on that site?

![image](https://user-images.githubusercontent.com/1271509/137794993-0d372a12-0423-4e4e-b147-a73a51e2bc0c.png)
![image](https://user-images.githubusercontent.com/1271509/137795017-0871861a-0d95-44f2-b297-3d7f4b9a4190.png)

**Comment by FanatiG** [comment] 2021-10-18 19:33
> btw @Sayvai , @FanatiG , what version of React are you using?

16.14.0

**Comment by Sayvai** [comment] 2021-10-18 21:22
Yeah, Atlassian could be a separate issue. Haven't retried local application since a few hours or so ago.

I'll think about the app mimick-like re-creation, time-permitting of course, also provided that i am even able to provide a reproducible issue from that.

**Comment by FanatiG** [comment] 2021-10-19 06:51
> @Sayvai, @FanatiG, another thing to check is:
> 
> when the components tree fails to load, do you see any error messages in the console?

No

**Comment by jstejada** [comment] 2021-10-19 16:58
@Sayvai, @FanatiG:

Quick favor, could you verify if this build also completely fixes the issue in your local app?:
[ReactDevTools-warning-reverted.zip](https://github.com/facebook/react/files/7375344/ReactDevTools-warning-reverted.zip)


-------------------


@sergeyphi:

If you can could you verify if either of these 2 builds completely fixes the issue for you?:

- [ReactDevTools-warning-reverted.zip](https://github.com/facebook/react/files/7375344/ReactDevTools-warning-reverted.zip)
- [ReactDevTools.zip](https://github.com/facebook/react/files/7367423/ReactDevTools.zip)


--------

**NOTE: Make sure you've disabled your current version of DevTools before installing this one**. In order to install it, you should be able to drag and drop the zip file into `chrome://extensions`.**

**Comment by sergeyphi** [comment] 2021-10-19 17:43
I can't say definitively (not to mislead you), but seems like ReactDevTools.zip works for me -- the issue is not appearing. While with ReactDevTools-warning-reverted.zip I'm still experiencing the issue.

**Comment by Sayvai** [comment] 2021-10-19 20:54
> @Sayvai, @FanatiG:
> 
> Quick favor, could you verify if this build _also_ completely fixes the issue in your local app?:
> 
> * [ReactDevTools-warning-reverted.zip](https://github.com/facebook/react/files/7375344/ReactDevTools-warning-reverted.zip)
> 
> @sergeyphi:
> 
> If you can could you verify if either of these 2 builds completely fixes the issue for you?:
> 
> * [ReactDevTools-warning-reverted.zip](https://github.com/facebook/react/files/7375344/ReactDevTools-warning-reverted.zip)
> * [ReactDevTools.zip](https://github.com/facebook/react/files/7367423/ReactDevTools.zip)
> 
> **NOTE: Make sure you've disabled your current version of DevTools before installing these other builds. In order to install it, you should be able to drag and drop the zip file into `chrome://extensions`.**

@jstejada - when i installed this particular custom build ([ReactDevTools-warning-reverted.zip](https://github.com/facebook/react/files/7375344/ReactDevTools-warning-reverted.zip)),and disabled the stable build version, i then performed multiple test runs of the local app on a remotely hosted internal site, and i can confirm that the Component Tree loads first time, for the 12 repeated test runs. 100% of the time. 💯 

In-between the 12 test runs, i quit and restarted Chrome 3 times, and navigated to four different internally remote hosted app environment URLs. Again, each time, the component tree loaded first time without issues.

Screenshot of first test run below
![Screenshot 2021-10-19 at 21 42 22](https://user-images.githubusercontent.com/7581546/137988802-06964af8-074c-42fe-a175-7302f1c8ce0a.png)
:

**Comment by Sayvai** [comment] 2021-10-19 21:12
> @Sayvai, @FanatiG, @sergeyphi
> 
> If you can, would you mind trying out this last build and verifying that it reliably fixes the issue on your local apps? I think we narrowed down the cause even a bit further. thanks so much for all your help so far!
> 
> * [ReactDevTools-backend-fix.zip](https://github.com/facebook/react/files/7376561/ReactDevTools-backend-fix.zip)
> 
> Also let me know if you see anything logged to the console
> 
> **Again: Make sure you've disabled your current version of DevTools before installing these other builds. In order to install it, you should be able to drag and drop the zip file into `chrome://extensions`.**
 
@jstejada - Upon installing [ReactDevTools-backend-fix.zip](https://github.com/facebook/react/files/7376561/ReactDevTools-backend-fix.zip), and removing / disabling the other versions, i found that after 6 repeated test runs (4 internal remote site, and restarted Chrome once), the component tree loads up first time each time. 💯 
 
Here's a screenshot with all the extra (mostly duplicate) console debugging info output. Note i invoked my own comment so you can tell the logging apart prior and after i opened React Dev Tools (Component tab):
 
![Screenshot 2021-10-19 at 22 02 23](https://user-images.githubusercontent.com/7581546/137991038-621b74ac-5006-433b-96d3-ab24aec81f49.png)

The logging repeated itself every couple of seconds or so since i opened React Dev Tools. The messages looked liked duplicates to me.

Hopefully this will give you more useful info to work with 🤞

**Comment by jstejada** [comment] 2021-10-19 22:18
@Sayvai I'm seeing some unexpected data in those logs, so i have a couple of questions:

- You said you are using version 4.20.0 of [React Developer Tools from the Chrome Web Store](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)?

- Could you open `chrome://extension`, search for "React", and send me a screenshot of what you see? I'm looking for something like this:
![image](https://user-images.githubusercontent.com/1271509/137998398-3a2de8e3-3eef-4615-b434-0857691eaaac.png)

**Comment by jstejada** [comment] 2021-10-20 13:57
will close it once the fix from #22597 is shipped and verified

**Comment by jstejada** [comment] 2021-11-01 16:11
We're shipping another version v4.21.0 to the web store which we think should address this. It should be available in chrome in a few days.

**Comment by Sayvai** [comment] 2021-11-03 08:29
> We're shipping another version v4.21.0 to the web store which we think should address this (or reduce the amount of times it triggers #21636). It should be available in chrome in a few days.

@jstejada - version `4.21.0` appears to have resolved the issue 😃 

Managed to reliably load up the component tree on first load 100% of the time, after repeatedly closing and re-opening dev tools for like 20 times across **localhost**, and **remotely hosted** sites of local app, with 2 Chrome restarts in-between to mix things up.

Many thanks for your huge efforts in resolving this issue 🙌  🎖️

**Comment by buondevid** [comment] 2021-11-03 11:04
I confirm that the problem has been resolved with the last version, many thanks for the great work 😄

**Comment by jstejada** [comment] 2021-11-03 14:35
FYI v4.21.0 is now on Chrome Web Store which should resolve or at least reduce the occurrence of this issue. If you keep seeing problems let us know and we'll re-open the issue.

**Closed by jstejada** 2021-11-03 14:35 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools

**Comment by aalices** [comment] 2021-11-05 08:34
@jstejada I'm still experiencing the issue 😞  I updated DevTools to 4.21.0 and my Chrome is 95.0.4638.69 - the browser is managed by my company.

On localhost the `Components` section is either blank or loads but does not update when something changes on the page. Everything works on websites like reactjs.org Also, from time to time when I hit `opt/alt + R` it logs an error like the ones mentioned by other users.

**Comment by bvaughn** [comment] 2021-11-05 13:27
@aalices Just to confirm–
1. Does this happen consistently for you on your website (running on localhost)?
2. Does it happen for any other websites? (What about your website deployed externally)?

Any repro info you can share with us?

**Comment by aalices** [comment] 2021-11-05 13:32
1. Yes, it stopped working about 2 weeks ago (at least that's when I noticed) and I haven't seen it working since then
2. Everything works fine on any other website, also on deployed version on the website I am working on.

Unfortunately I cannot share it as it's only for users who bought the product. However, I can try creating a basic CRA app and see what happens.

**Comment by jstejada** [comment] 2021-11-08 14:19
@aalices let's continue the conversation in https://github.com/facebook/react/issues/22636 which is a more general version of this issue
