### ISSUE TITLE
Any Material UI responsive theme available compatible with next js

### ISSUE THREAD

**Issue by ankitpatelinitio** [facebook/react#16815] opened 2019-09-18 05:15 UTC
I have to implement my project functionality into a responsive theme. So please suggest me a material UI responsive theme compatible with next js.

Thanks.

**Comment by eps1lon** [comment] 2019-09-18 06:07
Duplicate of https://github.com/mui-org/material-ui/issues/17474

**Closed** 2019-09-18 08:30 UTC
