### ISSUE TITLE
[DevTools Bug]: Installing react-devtools is giving a certificate error

### ISSUE THREAD

**Issue by sambaran69** [facebook/react#22456] opened 2021-09-28 22:17 UTC
### Website or app

react-devtools installation

### Repro steps

`yarn global add react-devtools`

or

`npm install -g react-devtools`

gives the following error:

RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/Users/sambaran/.config/yarn/global/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:485:26)
    at ClientRequest.emit (node:events:390:22)
    at ClientRequest.origin.emit (/Users/sambaran/.config/yarn/global/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:462:9)
    at TLSSocket.emit (node:events:378:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

### How often does this bug happen?

Every time

**Comment by akgupta0777** [comment] 2021-09-29 06:26
Installing fine on my machine. Maybe you have to look through your NPM configuration files. OR make sure you have enabled firewall options in windows OS.

**Comment by bvaughn** [comment] 2021-09-29 13:44
I don't think this has anything to do with React DevTools. Seems like maybe an NPM proxy issue?

https://github.com/npm/npm/issues/7519#issuecomment-97522305

**Comment by bvaughn** [comment] 2021-09-29 17:03
I'm going to close this issue since I don't think this error is being caused by react-devtools.

**Closed by bvaughn** 2021-09-29 17:03 UTC
Labels: Status: Unconfirmed
