### ISSUE TITLE
Question about automatic batching behavior in React 18

### ISSUE THREAD

**Issue by RahulPhpDev** [facebook/react#24211] opened 2022-03-30 11:48 UTC
In one scenario Automatic batching is not working  

having proper setup for react 18, everything else is working as it should be,

 but it does multiple rending , when it should do automatic batching and re-render only single time
 
 here is example
```
const [num, setNum ] = useState();
  useEffect( () => {
         setTimeout(() => {
          setNum(Math.random())
          setNum(Math.random())
          setNum(Math.random())
          setNum(Math.random())
         })
      }, [])

```
Please let us know if Automatic batching  is limited

**Comment by eps1lon** [comment] 2022-03-30 12:02
It doesn't look like this bug report has enough info for one of us to reproduce it. A similar example only commits once with the updated number: https://codesandbox.io/s/batching-in-settimeout-kzjs0g?file=/src/index.js

Are you sure you're using React 18 not 17?

Please provide a CodeSandbox (https://react.new/) that reproduces the problem.

**Comment by gaearon** [comment] 2022-03-30 18:21
Since there is a sandbox showing the original sandbox works, I think we can close this.

**Closed by gaearon** 2022-03-30 18:21 UTC
Labels: Resolution: Needs More Information, Type: Discussion, React 18
