### ISSUE TITLE
How will react solve nested contexts?

### ISSUE THREAD

**Issue by rabbitooops** [facebook/react#14620] opened 2019-01-18 03:09 UTC
I have lots of contexts and I have got to write in this way, so ugly! It hinders my work now. Such design makes it almost unusable.
```js
<context1.Provider value={value1}>
  <context2.Provider value={value2}>
    <context3.Provider value={value3}>
      <context4.Provider value={value4}>
        <context5.Provider value={value5}>

        </context5.Provider>
      </context4.Provider>
    </context3.Provider>
  </context2.Provider>
</context1.Provider>
```
```js
<context1.Consumer>
  {value1 => <context2.Consumer>
    {value2 => <context3.Consumer>
      {value3 => <context4.Consumer>
        {value4 => <context5.Consumer>
          {value5 => (
            null
          )}
        </context5.Consumer>}
      </context4.Consumer>}
    </context3.Consumer>}
  </context2.Consumer>}
</context1.Consumer>
```

**Comment by Penspinner** [comment] 2019-01-18 04:14
The upcoming Hooks API provide a different way to consume contexts.

https://reactjs.org/docs/hooks-reference.html#usecontext

**Comment by rabbitooops** [comment] 2019-01-18 04:17
Thank you. But what about provider?

**Comment by milesj** [comment] 2019-01-18 05:02
I'll be honest. If you're encountering this kind of implementation, then your architecture design seems poor and you probably shouldn't be using React context.

**Comment by rabbitooops** [comment] 2019-01-18 05:10
Nope, I'm designing a new store container.  It needs to work with context in react. 
https://github.com/rabbitooops/rako

**Comment by milesj** [comment] 2019-01-18 05:17
What does that library have to do with 5 layers deep of providers/consumers?

**Comment by rabbitooops** [comment] 2019-01-18 05:19
Because it supports inject multiple store to react instead of single store solution like Redux.

**Comment by rabbitooops** [comment] 2019-01-18 06:11
So context API is only friendly to single store solution like redux.

**Comment by rabbitooops** [comment] 2019-01-18 09:50
Imagine there are three stores theme, user and counter.
```js
function theme(getState) {
  return {
    color: 'white',
    setColor(color) {
      this.setState({color})
    }
  }
}

function user(getState) {
  return {
    name: '',
    setName(name) {
      this.setState({name})
    }
  }
}

function counter(getState) {
  return {
    value: 0,
    increment() {
      const {value} = getState()
      this.setState({value: value + 1})
    }
  }
}

const [themeStore, userStore, counterStore] = createStores(theme, user, counter)
const [themeContext, userContext, counterContext] = createContexts(themeStore, userStore, counterStore)


class App extends React.Component {
  render() {
    return (
      <themeContext.StoreProvider>
        <userContext.StoreProvider>
          <counterContext.StoreProvider>

            <Child />

          </counterContext.StoreProvider>
        </userContext.StoreProvider>
      </themeContext.StoreProvider>
    )
  }
}

class Child extends React.Component {
  static contextType = [themeContext, userContext]
  render() {
    const [theme, user] = this.context

    /* ... */
  }
}
```

**Comment by gaearon** [comment] 2019-01-18 10:08
What would your ideal syntax be?

**Comment by rabbitooops** [comment] 2019-01-18 10:11
Use context.write, support consuming multiple contexts without nesting.

**Comment by gaearon** [comment] 2019-01-18 10:40
Consuming multiple contexts without nesting is already supported.

Context.write has an RFC open for it. We don't know if it'll get through because it raises some very complicated questions. But while the RFC is open I'm not sure what's actionable in this issue. Do you have something to add beyond what's already in the RFC motivation?

**Comment by rabbitooops** [comment] 2019-01-18 12:15
I wanna ask a question. Why doesn't react support consuming multiple contexts in class? Seems hooks API has lots of issues to be solved and is very unstable right now.😨🧐😥🤕

**Comment by rabbitooops** [comment] 2019-01-18 15:08
I am going to implement a `StoreProviders` which can nest multiple contexts automatically.
```js
const StoreProviders = constructStoreProviders(...storeContexts)

<StoreProviders>
  <Child />
</StoreProviders>
```
Thanks for your answer Dan! :)

**Comment by TrySound** [comment] 2019-01-18 15:34
@rabbitooops https://github.com/reactjs/rfcs/issues/101

**Comment by zhujinxuan** [comment] 2019-01-18 15:37
@rabbitooops How about using a single store and Symbol as keys to mimic multi-layers of store?

```
data Store = Leaf Object | C Store Store
```

Or in a imperfect way in javascript:

```
const LEFT = Symbol('LEFT')
const RIGHT = Symbol('RIGHT')
function createLeafStore = return new Store({});
function createStore(leftChild :: Store, rightChild :: Store) {
  return new Store({[LEFT]: leftChild, [Right]: rightChild})
}
```

**Comment by rabbitooops** [comment] 2019-01-18 15:51
@TrySound Different: `App.useProvider`

**Comment by rabbitooops** [comment] 2019-01-18 15:56
@zhujinxuan I am sorry, I can't get you.

**Comment by YosbelSardinas-minted** [comment] 2019-01-18 16:47
@zhujinxuan You can use [Unstated](https://github.com/jamiebuilds/unstated), example:
```jsx
<Subscribe to={[AppContainer, CounterContainer, ...]}>
  {(app, counter, ...) => (
    <Child />
  )}
</Subscribe>
```

**Comment by gaearon** [comment] 2019-01-18 19:01
>Seems hooks API has lots of issues to be solved and is very unstable right now

We're preparing it for a release within a week or two — not sure why you inferred that. They'll be ready soon although if you want to be safe, please wait until a stable release.

>And what about this?

Calling Hooks in a loop (as you do in `forEach`) is generally not allowed. It's easy to cause issues this way.

> useStoreProviders

Both `useProvider` and `useShouldComponentUpdate` are problematic as Hooks (which is why React doesn't have them). See my response in https://github.com/facebook/react/issues/14534#issuecomment-455411307.

----

Overall, I'm struggling to understand the intent of this issue.

Consuming multiple contexts is solved by `useContext` Hook. We *don't* recommend to somehow "automate" it with arrays because this makes it too easy to write components that subscribe to too much context and re-render too often. You should have a clear sense of which contexts a component listens to, which is what `useContext` API gives you. If you must, you can write `useMyContexts()` Hook that explicitly uses specific contexts. I just don't recommend making it dynamic like you did because if the array length changes, it can break.

Putting multiple providers can be seen as "boilerplate" and we might eventually have a solution for this. But I also don't understand why you see it as a big problem. Examples in this thread aren't realistic enough to explain the issue to me. I don't see anything bad with nesting several layers of JSX somewhere at the top of the application. Pretty sure you have much deeper `div` nesting in most components and that doesn't hurt too much.

I'll close this as I think I already replied to these points, and the discussion goes in circles. If there's something missing let me know.

**Closed by gaearon** 2019-01-18 19:01 UTC
Labels: Type: Question

**Comment by YosbelSardinas-minted** [comment] 2019-01-18 19:54
@gaearon OT: There is any plan to add something like `useRender` or something to have more control of rendering? eg:

```js
useRender(() => <div />, [...props])
```
The second arg has the same role of `useEffect` hook.

**Comment by gaearon** [comment] 2019-01-18 20:22
`useMemo` is your friend.

See second snippet in https://reactjs.org/docs/hooks-faq.html#how-to-memoize-calculations.

**Comment by rabbitooops** [comment] 2019-01-19 15:48
@gaearon  May I ask a question, is it necessary to be so strict for hook?

There is a difference between `useProvider` and `App.useProvider`.
`App.useProvider` and `App.useShouldComponentUpdate` can only be used when users write them on the top level or pass `App` to specific hooks on purpose, it's easy to know if it has potential effect because such hooks always need to get `App` parameter.

Normal custom hooks can't use them because they can't access `App`. It's safe and convenient for most users.

**Comment by 0xorial** [comment] 2019-05-10 13:22
I ended up with a code like that:
```TypeScript
function provider<T>(theProvider: React.Provider<T>, value: T) {
   return {
      provider: theProvider,
      value
   };
}

function MultiProvider(props: {providers: Array<{provider: any; value: any}>; children: React.ReactElement}) {
   let previous = props.children;
   for (let i = props.providers.length - 1; i >= 0; i--) {
      previous = React.createElement(props.providers[i].provider, {value: props.providers[i].value}, previous);
   }
   return previous;
}
```

Then in my top-level providing component:
```TypeScript 
public render() {
      return (
         <MultiProvider
            providers={[
               provider(Context1.Provider, this.context1),
               provider(Context2.Provider, this.context2),
               provider(Context3.Provider, this.context3),
               provider(Context4.Provider, this.context4),
               provider(Context5.Provider, this.context5),
            ]}
         ><AppComponents />
      </MultiProvider>
}
```

@gaearon 
>  I don't see anything bad with nesting several layers of JSX somewhere at the top of the application.

I have ~15 dependencies that I want to be injectable in that manner, and having 15 levels of indentation doesn't look pretty to me :)

**Comment by alesmenzelsocialbakers** [comment] 2019-05-10 17:22
@0xorial you dont really need to have a component for that, after all <></> is just a function call React.createElement. So you could simplify it to a compose function like:

```js
const compose = (contexts, children) =>
  contexts.reduce((acc, [Context, value]) => {
    return <Context.Provider value={value}>{acc}</Context.Provider>;
  }, children);
```

and use it as:

```js
import Context1 from './context1';
import Context2 from './context2';
import Context3 from './context3';
...
import Context15 from './context15';

const MyComponent = (props) => {
  // const value1..15 = ... get the values from somewhere ;

  return compose(
    [
      [Context1, value1],
      [Context2, value2],
      [Context3, value3],
      ...
      [Context15, value15],
    ],
    <SomeSubComponent/>
  );
}
```

**Comment by disjukr** [comment] 2019-07-15 09:22
I wrote a library in the past that handles this case: https://github.com/disjukr/join-react-context

**Comment by Ilham132** [comment] 2019-09-17 13:04
![IMG_20190109_125516](https://user-images.githubusercontent.com/55145819/65044010-4b14a500-d986-11e9-9034-58e4e9c8f20a.jpg)

**Comment by Ilham132** [comment] 2019-09-17 13:05
![react11](https://user-images.githubusercontent.com/55145819/65044068-6d0e2780-d986-11e9-9eb0-96c222ce4a09.png)

**Comment by jsdevel** [comment] 2020-01-21 23:56
this is definitely something that happens in applications all the time.  `useContext` is great for _consuming_ the contextual data in a component, but it isn't so great when you need to _provide_ context in an app with multiple providers.

**Comment by kornfleks** [comment] 2020-01-29 09:50
Here is a closure alternative of @alesmenzelsocialbakers solution:
```jsx
const composeProviders = (...Providers) => (Child) => (props) => (
  Providers.reduce((acc, Provider) => (
    <Provider>
      {acc}
    </Provider>
  ), <Child {...props} />)
)

const WrappedApp = composeProviders(
  ProgressProvider,
  IntentsProvider,
  EntitiesProvider,
  MessagesProvider
)(App)

ReactDOM.render(<WrappedApp />, document.getElementById('root'));
```

Downside is that you have to write each specific Provider component.
*Example:*
```jsx
export const ProgressProvider = ({ children }) => {
  const [progress, setProgress] = useState(0)

  return (
    <ProgressContext.Provider value={{ progress, setProgress }}>
      {children}
    </ProgressContext.Provider>
  )
}
```

**Comment by csr632** [comment] 2020-03-16 17:45
I have created a [state management library](https://github.com/csr632/react-hook-svs) that is better at service composition. [Here is a demo of avoiding provider hell](https://codesandbox.io/s/github/csr632/react-hook-svs/tree/master/src?fontsize=14&hidenavigation=1&module=%2Fdemos%2Fcomposition.tsx&moduleview=1&theme=dark). Feel free to try it or read its source(100 lines of code)!

It introduce a "scope" object to collect the context provider, so that:
- Services can consume former services, even they are in same component.
- All the providers collected by a scope can be injected at onece, avoiding provider hell.

**Comment by kolodny** [comment] 2020-04-29 18:35
I took a crack at this as well. This seems to work fine:

```tsx
const composeWrappers = (
  wrappers: React.FunctionComponent[]
): React.FunctionComponent => {
  return wrappers.reduce((Acc, Current): React.FunctionComponent => {
    return props => <Current><Acc {...props} /></Current>
  });
}
```

Usage is:

```tsx
const SuperProvider = composeWrappers([
    props => <IntlProvider locale={locale} messages={messages} children={props.children} />,
    props => <ApolloProvider client={client}>{props.children}</ApolloProvider>,
    props => <FooContext.Provider value={foo}>{props.children}</FooContext.Provider>,
    props => <BarContext.Provider value={bar}>{props.children}</BarContext.Provider>,
    props => <BazContext.Provider value={baz}>{props.children}</BazContext.Provider>,
  ]);
  return (
    <SuperProvider>
      <MainComponent />
    </SuperProvider>
  );
```

I also published this helper as an npm library [`react-compose-wrappers`](https://github.com/kolodny/react-compose-wrappers)

**Comment by fanoop** [comment] 2020-06-18 02:55
The following shows how I am passing around the authenticated user to components that need it.

I decided to create one state for my application.  In my State.js file I set up my initial state, context, reducer, provider, and hook.

```javascript
import React, { createContext, useContext, useReducer } from 'react';

const INITIAL_STATE = {}

const Context = createContext();

const reducer = (state, action) => 
  action 
    ? ({ ...state, [action.type]: action[action.type] }) 
    : state;

export const Provider = ({ children }) => (
  <Context.Provider value={ useReducer(reducer, INITIAL_STATE) }>
    { children }
  </Context.Provider>
);

const State = () => useContext(Context);

export default State;
```

Then in my index.js file I wrapped my app in the provider.

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from './State';
import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <StateProvider>
      <App />
    </StateProvider>
  </React.StrictMode>,
  document.getElementById('root'),
);
```

To consume the state in a component I can use the hook.  I can also use dispatch to update the state.  For example if I want to get or set a user.

```javascript
import React, {useEffect} from 'react';
import State from './State'

const ExampleComponent = () => {
  const [{ user }, dispatch] = State(); 

  useEffect(() => {
    const getUser = async () => {
      const data = await fetch('http://example.com/user.json');  // However you get your data
      dispatch({ type: 'user', user: data });
    }
    getUser();
  });

  // Don't render anything until user is retrieved
  // The user is undefined since I passed an empty object as my initial state
  if(user === undefined) return null; 

  return(
    <p>{user.name}</p>
  );
}

export default ExampleComponent;
```

I think this way gives me the freedom to build the state how I need it without adding a ton of extra contexts and helps me to avoid a deep nest of providers.

**Comment by Emyboy** [comment] 2020-06-23 08:51
> The upcoming Hooks API provide a different way to consume contexts.
> 
> https://reactjs.org/docs/hooks-reference.html#usecontext

How to do I use this in a class component ?

**Comment by Zhigamovsky** [comment] 2020-06-23 11:28
> > The upcoming Hooks API provide a different way to consume contexts.
> > https://reactjs.org/docs/hooks-reference.html#usecontext
> 
> How to do I use this in a class component ?

Aren't hooks used to take advantage of various React features without writing classes? 
Well, that is, everything that various hooks do is already exist in the classes. If you're talking about convenient syntax and usage api, then the react moves away from classes to functional components, so welcome to functions and hooks)

**Comment by TotooriaHyperion** [comment] 2020-10-16 08:00
I created a package to solve the problem by provide similar API to vue3

https://github.com/TotooriaHyperion/react-multi-provide

- solve the problem that react context takes extra view tree.
- also preserve reactivity of what was injected
- fractal between providers
- use WeakMap to store the dependencies
- use Object wrapped symbol to achieve better typescript support, dependency injection & debug experience

Outer.tsx
```
import React, { useMemo } from "react";
import { Providers, useCreateContexts, useProvide } from "../..";
import { createService, ServiceA } from "./service";

export const Outer: React.FC = ({ children }) => {
  const contexts = useCreateContexts();
  const service = useMemo(createService, []);
  useProvide(contexts, ServiceA.id, service);
  return <Providers contexts={contexts}>{children}</Providers>;
};
```

Inner2.tsx
```
import React from "react";
import { useContexts, useReplaySubject } from "../../lib";
import { ServiceA } from "./service";

export const Inner2: React.FC = () => {
  const [
    {
      state$,
      actions: { inc, dec },
    },
  ] = useContexts([ServiceA.id]);
  const count = useReplaySubject(state$);
  return (
    <>
      <p>{count}</p>
      <div>
        <button onClick={inc}>Increment</button>
        <button onClick={dec}>Decrement</button>
      </div>
    </>
  );
};
```

**Comment by buhichan** [comment] 2020-10-28 06:21
here is how I do it:
```tsx
interface Composable {
    (node: React.ReactNode): React.ReactElement
}

const composable1: Composable = (node)=>{
      return <someContext.Provider>{node}</someContext.Provider>
}

function Comp({children}:{children?:React.ReactNode}){
       return pipe(
             composabl1, composabl2, composable3
       )(children)
}

```
You can find the `pipe` function in many popular libraries such as rxjs, there's also several language-level proposals for this pipeline-like operation. There's no need to 'solve' it by using another lib.

**Comment by waleedshkt** [comment] 2020-12-04 08:34
From all the above proposed solutions to wrapping components with multiple providers, [this one](https://github.com/facebook/react/issues/14620#issuecomment-491366098) by @alesmenzelsocialbakers is the most performant and neat one

**Comment by jdarshan5** [comment] 2021-06-02 14:20
well I have a problem with context, this is my code
`
<AContext.Provider value={this.alpha}>
<BContext.Provider value={this.beta}>
{...children}
</BContext.Provider>
</AContext.Provider>
`
Problem is that if I try to access the context value of the AContext then it gives me the values of the BContext and I have access them in my class component.
consumption of AContext in child component is as below,
`class P2 extends React.Component {

  static contextType = AContext;

  componentDidMount = () => {
    console.log(this.context);
  }

  render() {
    return(
      <View>
        <Text>
          2
        </Text>
      </View>
    )
  }
}`
Here the problem is that on component did mount the console is showing the data of this.beta which is passed to the BContext.
Plz help me

**Comment by nanxiaobei** [comment] 2021-06-07 08:45
`**react-easy-contexts**` is made to solve this. https://github.com/nanxiaobei/react-easy-contexts

Introduction article: https://nanxiaobei.medium.com/react-easy-contexts-add-multiple-react-contexts-in-the-simplest-way-915d15cca5ca

**Comment by pandanoir** [comment] 2021-12-25 13:54
I published package that provides type-safe way to merge providers flat.

https://www.npmjs.com/package/react-merge-providers

**Comment by doronhorwitz** [comment] 2022-10-13 13:58
This is a fun solution too: https://dev.to/alfredosalzillo/the-react-context-hell-7p4

**Comment by pandanoir** [comment] 2024-01-05 17:24
I have completely resolved the issue.

```tsx
const valid: FC = () => (
  <MergeProvider
    contexts={[
      [createContext(0), 0],
      [createContext("string"), "string"],
    ]}
  />
);
const invalid: FC = () => (
  <MergeProvider // type error!
    contexts={[
      [createContext(0), "0"], // mismatch
      [createContext("string"), "string"],
    ]}
  />
);
```

The implementation of `MergeProvider` is available [here](https://www.typescriptlang.org/play?jsx=4&ssl=1&ssc=1&pln=2&pc=1#code/JYWwDg9gTgLgBAbzgMQMIBo6ogOxgUwA8ZMBjKfAQwOzyJLgAUoIwBnAdWBgAtUfgAGwAmFHHAC+cAGYsQcAEQVKpGAoDcAKFK428QgC44AbWO0CxADw4AriABG+KAD5Mth04C6mM7gsxLPShgHABzVzggkNDPTzgAXhNNOBNyKho-egAKAAYASkwc72TU5Qy6YiyFKLCFAsUa0IVizy0dHD04AE8jU3N6aztHF0xG2ISTYzTqfH7K-MwFHghQ-GbWzU0YLrB8OABVHGBcABUIAEk6KDZ8VWOcS33nBJKs-bh6fBxhNjhKHC6cAA-HAspQoKEjPs8glnv9AUYcPgAG5OGGfb6-MEQowhaROODnGHxZ7IiDAYTAwklREopxaba7QlsZgQZEUpyWE7PRKHe5nS4Ea63GD3SwlE4fYhfH6gvEEgBKeWMcSBJRSCqlBExJjmAXlUDghAiBu6qvVKSNWplv0BastDqYLHYXF4-CEoi+FpSRjJFItvvJwhpcD9wecbV08AAsk5Vqz2cICYkudadVllMJcIJASq4AAfOCZ7OA+Eq5WeZxZBAldr+NjoWsCERiRsSIysl3cPjNz0PJB1+hsIySiTPABkzITHKgXOcxOctcyxDYADoKMIbKR8FkLWDSKQfHrMMjKIIbPhPAvQd64JY9avp0nDafz-h4ghXxexwgVKQJJYAD0D5Pk4i4OgUFqkL2rYlHkWjaFGoZnhSRhoBMWTXpYsYQvgoGGoOK4foQUiARGiEdPAISvqhKCoBhWE4fGLCJgShEwGwH5dKR5HtJ0NHCAATGh9GJJhsI3ik2FxnhLEzlBy4cR+xi3lMZSzIpuT1EUjaOqU6QaRUMBVI0dSLKZxQOp4EglGRmjwRRnTUShQkiQxEm7lJTGyWy8kOuxnEICpelqQZepaYsOTNLpjqhTM4XVDAwS1PUiXJU0lmWtZtmLg5QA)
