### ISSUE TITLE
Bug: HTML <video> doesn't work with muted Attribute

### ISSUE THREAD

**Issue by infinite0007** [facebook/react#22045] opened 2021-08-08 08:44 UTC
When trying to embed a Video you can use the <source> HTML tag. For some reason if you put the muted attribute on it, it won't stick to the DOM, which doesn't allow videos to autoplay what makes it difficult with privacy settings of a couple of browsers like Safari on IOS. So here is a proof. I noticed it after a couple of tests on IOS. For me the muted tag wasn't important for playing videos on Chrome. On IOS the video just autoplays when the muted-tag is set. 

![IMG_20210808_103818](https://user-images.githubusercontent.com/50872737/128626265-f11a09b5-514c-4928-a152-c6abd1db7fb5.jpg)

-->
My research has shown that the bug has existed since 2016.

Fix just for now but not practically:
let’s use dangerouslySetInnerHtml to ensure the muted attribute is written to the DOM:

![1_hewat2uh6MghJvBcQoyLmA (1)](https://user-images.githubusercontent.com/50872737/128626324-630b6a88-ffbf-4c1a-aa3a-99b3561c485e.png)

**Comment by eps1lon** [comment] 2021-08-09 09:09
Duplicate of https://github.com/facebook/react/issues/10389

**Closed by eps1lon** 2021-08-09 09:09 UTC
Labels: Status: Unconfirmed
