### ISSUE TITLE
Throw warning when undefined passed in as event callback

### ISSUE THREAD

**Issue by dmitrig01** [facebook/react#2210] opened 2014-09-19 00:50 UTC
Maybe there's a valid use case for this, but I had something like:

```javascript
module.exports = React.createClass({
	_onsave: function() {
	},
	render: function() {
		return (
			<button className="btn btn-green btn-regular" onClick={ this._onSave }>Save</button>
		);
	}
});
```

if it'd yelled at me, it would have been easier to debug :-)

**Comment by spicyj** [comment] 2015-04-11 18:21
Dupe of #1225, more or less.

**Closed by spicyj** 2015-04-11 18:21 UTC
