### ISSUE TITLE
useReducer become bad if I open the chrome react-dev-tool and click the react dom node

### ISSUE THREAD

**Issue by fantasticsoul** [facebook/react#16435] opened 2019-08-17 08:48 UTC
**Do you want to request a *feature* or report a *bug*?**
### bug
___
**What is the current behavior?**
i have [issue](https://github.com/facebook/react/issues/16347) been closed, so I `CHANGE` my writing way, I am very confused these days about the bug, just see the code below:
```jsx
import React, { useReducer } from 'react';

let cursor = 1;
function getCursor() {
  return cursor;
}
function incCursor() {
  cursor++;
}
const cursor_ref_ = {};//map cursor to ref

// always return new state
function reducer(initState, partialState) {
  Object.assign(initState.state, partialState);
  return Object.assign({}, initState);
}

// make setState handler with dispatch
const makeSetState = (cursor, ccDispatch) => {
  // broadcast is true by default, that means any ref call setState will trigger other ref update ui
  return (state, broadcast = true) => {
    console.log(`%c cursor ${cursor} update state`, 'color:purple; border:3px solid purple;');
    if(broadcast){
      console.log(`%c cursor ${cursor} broadcast state`, 'color:purple; border:3px solid purple;');
      Object.keys(cursor_ref_).filter(v => v != cursor).forEach(c => {
        const ref = cursor_ref_[c];
        console.log(`%c start trigger cursor ${c} setState`, 'color:blue; border:3px solid blue;');
        // flag broadcast false, let it only change ref state self
        ref.ctx.setState(state, false);
      });
    }
    ccDispatch(state)
  }
}

// initState is the target state that service for user 
function useMySpecialHook(initState) {
  const tmpCursor = getCursor();
  const [ccState, ccDispatch] = useReducer(reducer, { state: initState, cursor: tmpCursor });
  const targetCursor = ccState.cursor;
  let isFirstRendered = targetCursor === tmpCursor;

  let ref;
  if (isFirstRendered) {
    incCursor();
    console.log(`%c make setState for cursor ${targetCursor}`, 'color:green; border:3px solid green;');
    ref = {
      ctx: {
        cursor: targetCursor,
        state: ccState.state,
        setState: makeSetState(targetCursor, ccDispatch),
      }
    };
    cursor_ref_[targetCursor] = ref;
  } else {
    // get the ref by cursor
    ref = cursor_ref_[targetCursor];
    // replace state
    ref.ctx.state = ccState.state;
    console.log(`%c replace cursor ${targetCursor} setState `+targetCursor, 'color:red; border:3px solid red;');

    // in re-render period, alway assign a latest setState handler to ref.ctx
    ref.ctx.setState = makeSetState(targetCursor, ccDispatch);
  }

  return ref.ctx;
}

export default function DemoCounter() {
  const { state, setState } = useMySpecialHook({ count: 100 });
  const dispatch = ({ type }) => {
    if (type === 'increment') setState({ count: state.count + 1 });
    else setState({ count: state.count - 1 });
  }
  const changeCount = () => {
    setState({ count: Date.now() });
  }
  return (
    <div style={{ border: '1px solid blue', margin: '8px' }}>
      <h2>DemoCounter</h2>
      Count: {state.count}
      <button onClick={() => dispatch({ type: 'increment' })}>+</button>
      <button onClick={() => dispatch({ type: 'decrement' })}>-</button>
      <button onClick={changeCount}>setState</button>
    </div>
  );
}
```
then I  import Counter component and init 2 instance(at least 2) in `index.js`, and I click any one of them's inc button or dec button, the other one will been trigger rendered also, it works perfectly, but if I open the chrome react dev-tool, and click one react dom node in the tool, things become bad, it does't work agian/(ㄒoㄒ)/~~，if you don't understand what I said, just see the [video](https://concentjs.github.io/concent-site/bug-video.html)

<p>
<video id="video" controls="" preload="none">
<source id="mp4" 
src="https://concentjs.github.io/concent-site/bug-video.html" type="video/mp4">
</video>
</p>

**What is the expected behavior?**
no matter if I click the react dom node in the dev-tool or not, the two instance will always been trigger rendered. please run the copy the code and run it in your computer, it is really strange, if I change component from hook to class(I mean take over class ins's setState, some examples like: https://stackblitz.com/edit/cc-complex-counter), it is always fine!!!! react-dev-tool does no matter to these code, but for hook, I don't know why it become bad if I click the react dom node in the dev-tool...

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: 1.16.9
react dev tool: lastest

**Comment by gaearon** [comment] 2019-08-17 15:23
Assigning to `cursor_ref_` properties is a mutation. You shouldn’t mutate anything in idiomatic React during rendering. 

The idiomatic way to implement what you’re trying to do is a React feature called “context”. You might want to check it out.

I’ll close this because this is expected behavior. If you want to learn more about how to avoid mutation please refer to the Support section on our website: https://reactjs.org/community/support.html.

**Closed by gaearon** 2019-08-17 15:23 UTC

**Comment by fantasticsoul** [comment] 2019-08-19 07:13
I know mutation will break react render mechanism， but this bug is not as simple as you imagine, look at the code blow (it is very very very simple).
```jsx
import React, { useState } from 'react';

export default function DemoCounter() {
  const [fnWrapper] = useState('fn');
  const [count, setCount] = useState(0);
  fnWrapper.__proto__.setCount = s => {
    setCount(s);
  }

 // assign fnWrapper.__proto__.setCount to callSetCount
  const callSetCount = fnWrapper.__proto__.setCount;

  return (
    <div style={{ border: '1px solid blue', margin: '8px' }}>
      count: {count}
      {/* this does not work if I open react-dev-tool and click the dom node */}
      <input value={count} onChange={e => fnWrapper.setCount(e.currentTarget.value)} />

       {/* this always works not matter I open react-dev-tool and click the dom node or not */}
      <input value={count} onChange={e => callSetCount(e.currentTarget.value)} />
    </div>
  );
}

```
### why callSetCount always works but `fnWrapper.__proto__.setCount` not if and only if I open the react-dev-tool click the dom node ~~~~(>_<)~~~~，

### please tell me the truth.
