### ISSUE TITLE
Error: "Could not find commit data for root "34103" and commit 1"

### ISSUE THREAD

**Issue by villesau** [facebook/react#17047] opened 2019-10-08 21:26 UTC
Describe what you were doing when the bug occurred:
1. React dev tools profiler crashed when changing from "anonymous" to "overlay" and asked to report the issue

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.1.1-a9cd9a765

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162685)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:331467)
    at sc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:331684)
    at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58733)
    at Ri (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:66060)
    at Jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104557)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89163)
    at Ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89088)
    at ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86037)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45275

Component stack: in sc
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by bvaughn** [comment] 2019-10-09 16:26
Looks like a duplicate of #16506 so I'm going to close this.

**Closed by bvaughn** 2019-10-09 16:26 UTC
Labels: Component: Developer Tools, Resolution: Duplicate, Type: Bug
