### ISSUE TITLE
require in stateless functional component fails

### ISSUE THREAD

**Issue by abloomston** [facebook/react#6298] opened 2016-03-19 16:07 UTC
The behavior of webpack `require` differs between regular React components and React stateless functional components.

This will work:

```
var Component = React.createClass({
	render: function() {
		return (
      <div>
        <h1>Component</h1>
        <img src={require('./test.png')}/>
      </div>
		);
	}
});
```

This will not:

```
var StatelessFunctionalComponent = props => (
  <div>
    <h1>Stateless Functional Component</h1>
    <img src={require('./test.png')}/>
  </div>
);
```

See https://github.com/abloomston/webpack-react-require-problem for a simple project that reproduces this issue.

Apologies in advance if I am making an obvious mistake in my configuration.

**Comment by cody** [comment] 2016-03-19 18:19
The fat arrow function makes the difference. Just use babel with the ES2015 preset and it works: https://babeljs.io/docs/plugins/preset-es2015

**Comment by gaearon** [comment] 2016-03-19 20:46
@cody is correct.

The problem is that Webpack fails to parse the arrow function in the compiled code and doesn’t replace `require()` with its module resolution mechanism.

You can see this by inspecting the compiled code:

```js
	var Component = React.createClass({
	  displayName: 'Component',

	  render: function () {
	    return React.createElement(
	      'div',
	      null,
	      React.createElement(
	        'h1',
	        null,
	        'Component'
	      ),
	      React.createElement('img', { src: __webpack_require__(160) }) // <--- note: Webpack recognized this
	    );
	  }
	});

	var StatelessFunctionalComponent = props => React.createElement(
	  'div',
	  null,
	  React.createElement(
	    'h1',
	    null,
	    'Stateless Functional Component'
	  ),
	  React.createElement('img', { src: require('./test.png') }) // <---- note: just require
	);
```

It’s possible that Webpack 2 beta doesn’t have this problem but I haven’t checked. In either case it’s likely that **if you want your code to run in most browsers, you *do* want to compile arrow functions with Babel**. Adding `es2015` preset to your Babel configuration should solve this problem.

I am closing because it is not related to React.

**Comment by abloomston** [comment] 2016-03-19 20:46
Thanks for your help on this!

**Closed by gaearon** 2016-03-19 20:46 UTC
