### ISSUE TITLE
Runtime error in production mode, makes browser hang

### ISSUE THREAD

**Issue by vsvanshi** [facebook/react#17181] opened 2019-10-25 08:16 UTC
**Do you want to request a *feature* or report a *bug*?** : BUG

**What is the current behavior?** : Whenever there is a runtime error occuring on a page, the error stack is being logged again and again, and the browser hangs up

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?** - the browser should not hang, even if the nothing in rendered on the browser

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** React : 16.8.6, Chrome : 77.0.3865.120, MAC OS

Attaching a screenshot for reference
![Screenshot 2019-10-25 at 1 48 20 PM](https://user-images.githubusercontent.com/8156467/67555128-59e13b00-f72e-11e9-8155-4c1550fecc27.png)

as you can see, 1697 errors logged in just around 10s, which is causing the browser to hang indefinitely.

**Comment by ganapativs** [comment] 2019-10-25 11:37
It looks like these errors are not from React. Mostly from one of the libraries/business logic.

Can you share more info/minimal repro?

**Comment by bhaveshkumar-1mg** [comment] 2019-10-26 08:03
It seems to be a error loop owing to faulty business logic. @vsvanshi Can you check for that

**Comment by vsvanshi** [comment] 2019-10-28 16:13
@bhaveshkumar-1mg  - its simple as printing a dynamic value inside the render function.

`<div>
    {this.props.myObj.someProp}
</div>
`
in my case the `this.props.myObj` is undefined so a runtime error is called.
I don't know why an infinite error loop is being thrown.
Before posting here, I have gone through numerous links, but honestly saying, I am not even sure, what to type in google to identify the problem.

I am also using next.js <7.0.2> if that helps in figuring out.

And yes, i know the best practices for the code that i should keep a check for null or undefined values.
But I just want to know even if an error is being thrown, why its going into infinite loop.

**Comment by vaporwavie** [comment] 2019-10-28 16:24
There is proabably a faulty routine inside your component that is causing it to re-render indefinitely, potentially causing a memory leak and alas hanging your tab.

It's difficult to evaluate your scenario because we don't have access to your code.

**Comment by threepointone** [comment] 2019-10-29 18:24
Closing this issue, happy to re open if you can provide a reproducing usecase

**Closed by threepointone** 2019-10-29 18:24 UTC
