### ISSUE TITLE
Bug: Controlled `radio` element doesn't update the `checked` property when the selected radio changes

### ISSUE THREAD

**Issue by mickaelzhang** [facebook/react#25685] opened 2022-11-15 15:48 UTC
React version: 16.14.0, 18.2.0

## Steps To Reproduce

1. Create group of `radio` input element in a controlled way using the `checked` prop
2. Click on an unselected element
3. The clicked/selected element is now selected for the user
4. The `checked` prop is still on the original `radio` input element

Link to code example:
https://codesandbox.io/s/funny-rui-tphkuc?file=/src/App.js:188-191

## The current behavior

For a group of `type="radio"`, the `checked` prop stays on the initially selected radio button
If the selected radio button changes, the state update correctly visually but the `checked` isn't add as a property in the DOM of the now selected radio button (and the previous selected radio button still have the `checked` property)

## The expected behavior

For a group of `type="radio"`, when changing the selected radio button, the `checked` property should be removed from the previously selected radio button and be added to the new one

**Comment by eps1lon** [comment] 2022-11-15 21:23
The `checked` **property** is updated correctly. What you're referring to is the `checked` **attribute** which is not supposed to change. For CSS selectors use the `:checked` pseudo-selector instead.

Duplicate of https://github.com/facebook/react/issues/24439

**Closed by eps1lon** 2022-11-15 21:23 UTC
Labels: Status: Unconfirmed

**Comment by mickaelzhang** [comment] 2022-11-16 10:26
@eps1lon Thanks for the clarification!
Using `defaultChecked` instead seems to change the attribute, I suppose it is a bug then
