### ISSUE TITLE
can't change visibility as expected

### ISSUE THREAD

**Issue by MurakamiKennzo** [facebook/react#17349] opened 2019-11-12 10:28 UTC
**Do you want to request a *feature* or report a *bug*?**
a bug.

**What is the current behavior?**

not change the style visibility as expected, but className can be well.

[react-visibility-bug](https://github.com/MurakamiKennzo/react-visibility-bug)

please follow the step in this repository and get what I said.

**What is the expected behavior?**

change the style visibility as className did.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react ^16.11.0
Google Chorme 78.0.3904.97
Mac OSX Mojave 10.14.6

**Comment by ivansivaklepsi** [comment] 2019-11-12 13:25
This is not a bug, you don't have the right code to do this.
First of all, you're trying to set a `className` on the 2nd button to `true` or `false`, but there is no such class in your CSS, so it has no effect on the visibility of the button.
Then there's another issue on line 12, where you're setting the visibility to `show` (which is not a valid value for this attribute), instead of `visible`.
Just replace `show` for `visible`, use style instead of className on the 2nd button and the bug will be fixed.

**Comment by MurakamiKennzo** [comment] 2019-11-13 01:39
I got it, I'm so stupid here. But since it's not a valid value, it's not a warning here and do thing hack I think is good. Maybe pass the invalid value on or give me a warning is a good idea.

Thanks a lot.

**Closed** 2019-11-13 01:44 UTC
