### ISSUE TITLE
Textarea does not update when replaceState({}) invoked

### ISSUE THREAD

**Issue by vladmiller** [facebook/react#2573] opened 2014-11-20 02:45 UTC
Hello, discovered little annoying bug
When you invoke replaceState() with an empty object textarea innerHTML does not update, however the value do

Please see example here
http://jsfiddle.net/kb3gN/7887/

**Comment by spicyj** [comment] 2015-02-26 01:19
This sounds like a dupe of #2533.

**Closed by spicyj** 2015-02-26 01:19 UTC
Labels: Component: Controlled Components
