### ISSUE TITLE
TransitionGroup leave animation doesn't get non-active style

### ISSUE THREAD

**Issue by matthewwithanm** [facebook/react#847] opened 2014-01-08 19:55 UTC
I think I've come across a bug with TransitionGroup which basically causes properties of the "leave" styles to be ignored. [Here][1]'s a fiddle demonstrating the problem.

As you can see, the "leave" animation doesn't use the correct origin or transition (in the latest Chrome or FF). If those properties are moved to an always-matching selector (".bluebox"), it works fine.

My only guess as to why this would happen is that the active leave class is being added in the same tick as the leave.

[1]: http://jsfiddle.net/matthewwithanm/GqhtQ/

**Comment by spicyj** [comment] 2015-04-01 21:55
This isn't super actionable so I'm going to close it out. Thanks for your thoughts though! CSS transitions seem to be surprisingly tricky.

**Closed by spicyj** 2015-04-01 21:55 UTC
Labels: Component: Addons / TransitionGroup

**Comment by tannerlinsley** [comment] 2016-09-18 21:11
I know this is close, but I thought I would also let people know that this problem snuck up on me to the point that I also dug through the source code only to find that I needed to move the `transition` property to the `-active` classes, instead of having it defined by default on the `idle` or default class of the element.  This is not a bug.  It will feel like one though if you have moved from angular to react.  Ng-Animate goes into great detail to avoid strange edge cases like this one, and since this library is still young (and in my opinion, getting a bit neglected), so don't expect all the edge cases to be covered ;) Great addon nonetheless.  Thanks React team!
