### ISSUE TITLE
Error: "Cannot read property 'isCollapsed' of undefined"

### ISSUE THREAD

**Issue by mykhaliuk** [facebook/react#20630] opened 2021-01-20 17:02 UTC
Describe what you were doing when the bug occurred:
1. Can't describe. Just found devtools Components tab w/ this error 🤷🏻‍♂️
---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-f160547f47

Call stack: at store_Store.getElementAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21226:35)
    at store_Store.getElementIDAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21242:26)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28678:63
    at List.render (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:22934:18)
    at vi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13515:76)
    at ui (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13506:10)
    at mk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16077:86)
    at lk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15459:11)
    at kk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15451:23)
    at ck (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15435:5)

Component stack: at List (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:22629:30)
    at div
    at AutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:3003:5)
    at div
    at div
    at Tree_Tree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28429:47)
    at div
    at div
    at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28921:3)
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27558:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28206:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33383:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29219:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29336:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32934:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24322:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24811:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29404:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36207:3)

**Comment by eps1lon** [comment] 2021-01-20 17:43
Thanks for the report.

This sounds like a duplicate of #19927. It would help a lot if you could provide a reproduction (preferably with a codesandbox (https://react.new) to #19927 🙏.

**Closed by eps1lon** 2021-01-20 17:43 UTC
