### ISSUE TITLE
[Bug]: createRoot type error - TS2345

### ISSUE THREAD

**Issue by Coding-Maniac** [facebook/react#24196] opened 2022-03-29 17:25 UTC
React version: 18.0.0

## Steps To Reproduce

1. When following the [React V18 Upgrade guid](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html).
2. use `createRoot` to create the root element.

Link to code example: Was unable recreate in sandbox, Since it doesn't have the types for `createRoot`

## The current behavior
1. Throws a type error `TS2345: Argument of type 'HTMLElement | null' is not assignable to parameter of type 'Element | DocumentFragment'`

## The expected behavior
1. Shouldn't throw the type error

**Comment by bvaughn** [comment] 2022-03-29 17:30
> Link to code example

Can you provide a link to what you're talking about?

This sounds like a TypeScript error perhaps?

**Comment by bvaughn** [comment] 2022-03-29 17:42
I think there's some confusion. The PR you submitted is for the _React source code_. It  should not impact any Flow or TypeScript errors you see when creating a React project yourself. Can you provide a little more context on what you're doing (where's the repro of _your code_)?

**Comment by Coding-Maniac** [comment] 2022-03-29 17:53
[Error Replicated Report](https://github.com/Coding-Maniac/create_root_error_react)
I have replicated the error in the above repo. Since i wasn't able to do it sandbox.
If you could kindly clone the repo.
You can see in [index.tsx](https://github.com/Coding-Maniac/create_root_error_react/blob/main/src/index.tsx). createRoot throws a typeError

**Comment by bvaughn** [comment] 2022-03-29 17:55
Gotcha.

TypeScript React types aren't managed by our team. They are stored in this repo: https://github.com/DefinitelyTyped/DefinitelyTyped

You probably want to follow up with this over there. (There are some existing things, e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43848)

Going to close this issue since we can't help directly.

**Closed by bvaughn** 2022-03-29 17:55 UTC
Labels: Status: Unconfirmed

**Comment by lu-zen** [comment] 2022-03-29 18:02
I managed to [reproduce it](https://codesandbox.io/s/goofy-forest-307ij9). Looks like @types/react-dom was not updated with react-dom@18 type definitions yet.

Probably the issue should be open at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo, as bvaughn stated.
