### ISSUE TITLE
textarea + onFocus + stopPropagation = incorrect cursor rendering on Firefox

### ISSUE THREAD

**Issue by felipeochoa** [facebook/react#8642] opened 2016-12-25 22:25 UTC
**What is the current behavior?**
Using `.stopPropagation` in an `onFocus` event on a textarea or its parent causes the cursor to disappear or render at an incorrect location in Firefox.

You can see the vanishing cursor [at this fiddle](https://jsfiddle.net/aq59me3d/3/). There are no issues on Chrome and Edge, but FireFox 50.1.0 has this problem. In my full app, the cursor doesn't vanish but rather moves elsewhere (italics are placeholder text):

<img width="118" alt="2016-12-25" src="https://cloud.githubusercontent.com/assets/2739312/21473053/83e67f52-cac5-11e6-8b6c-1e1f98289bb6.png">
<img width="88" alt="2016-12-25 1" src="https://cloud.githubusercontent.com/assets/2739312/21473058/a0e1f168-cac5-11e6-872e-70d8e6d83c93.png">
<img width="66" alt="2016-12-25 2" src="https://cloud.githubusercontent.com/assets/2739312/21473055/8836dc5a-cac5-11e6-8adc-4edb65763104.png">

I have not reproduced this behavior in the fiddle.

**What is the expected behavior?**
It's hard to say what the expected behavior is, since the real `focus` event does not bubble. [Here](https://jsfiddle.net/axacmxfv/)'s a fiddle to show that the cursor position is not affected when the event is stopped in a vanilla-JS environment.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
The fiddle shows the issue with `15.4.1` on FF (on Windows 10).  I saw the same issue on `15.3`. 

**Why stopPropagation**
Before I get eaten alive for using this, I'll just say that having a non-bubbling focus event simplifies one of the interactions I'm setting up. Specifically, my app has a bunch of widgets that can be marked active. When a user clicks into a field in the widget, that widget should be marked active. However, widgets can be nested in other widgets, in which only the inner-most widget should be marked active.

**Comment by aweary** [comment] 2017-12-21 05:15
Thanks for the report @felipeochoa.

This is a duplicate of https://github.com/facebook/react/issues/10232. See [my comment in that thread](https://github.com/facebook/react/issues/10232#issuecomment-329911313), this is a known issue in Firefox with capture listeners.

> Here's a fiddle to show that the cursor position is not affected when the event is stopped in a vanilla-JS environment.

The reason this works is because not using a capture listener, while React's synthetic event system does.

Since this is a known issue in Firefox with no easy workaround I'm going to close this out.

**Closed by aweary** 2017-12-21 05:15 UTC
Labels: Component: DOM, Type: Bug
