### ISSUE TITLE
TypeError: Cannot read property 'firstChild' of null at precacheChildNodes (react-dom.js:6619)

### ISSUE THREAD

**Issue by jochenberger** [facebook/react#9351] opened 2017-04-06 08:38 UTC
With 15.5.0-rc.1, I get
```
Uncaught TypeError: Cannot read property 'firstChild' of null
    at precacheChildNodes (react-dom.js:6619)
    at getNodeFromInstance (react-dom.js:6714)
    at ReactDOMComponent.trapBubbledEventsLocal (react-dom.js:5772)
    at CallbackQueue.notifyAll (react-dom.js:948)
    at ReactTestReconcileTransaction.close (react-dom.js:12207)
    at ReactTestReconcileTransaction.closeAll (react-dom.js:14993)
    at ReactTestReconcileTransaction.perform (react-dom.js:14940)
    at ReactUpdatesFlushTransaction.perform (react-dom.js:14927)
    at ReactUpdatesFlushTransaction.perform (react-dom.js:13047)
    at Object.flushBatchedUpdates (react-dom.js:13130)
```

**Comment by jochenberger** [comment] 2017-04-06 08:40
And also on another code path:
```
react-dom.js:6619 Uncaught TypeError: Cannot read property 'firstChild' of null
    at precacheChildNodes (react-dom.js:6619)
    at Object.getNodeFromInstance (react-dom.js:6714)
    at Object.didPutListener (react-dom.js:13926)
    at Object.putListener (react-dom.js:2556)
    at Object.putListener (react-dom.js:5692)
    at CallbackQueue.notifyAll (react-dom.js:948)
    at ReactTestReconcileTransaction.close (react-dom.js:12207)
    at ReactTestReconcileTransaction.closeAll (react-dom.js:14993)
    at ReactTestReconcileTransaction.perform (react-dom.js:14940)
    at ReactUpdatesFlushTransaction.perform (react-dom.js:14927)
```

**Comment by gaearon** [comment] 2017-04-06 10:33
Please create a minimal reproducing example. Otherwise we can't really help because there's no way to diagnose what happened.

**Comment by jochenberger** [comment] 2017-04-06 10:52
Yes, I'm trying to figure out what does wrong. I suspect it has something to do with detached DOM trees. At least `inst._hostNode` is `null` in https://github.com/facebook/react/blob/1f487eb933756ec5f2d33a316dc92df9475b0044/src/renderers/dom/client/ReactDOMComponentTree.js#L190.

**Comment by jochenberger** [comment] 2017-04-06 11:40
See http://codepen.io/jochenberger/pen/wJbJpo?editors=0010#0
Actually, I can't get it to work at all. If you select "2", it still says "Selected 1". It works fine with 15.4.2 though.

**Comment by syranide** [comment] 2017-04-06 13:45
Yeah React seems totally broken. It breaks if you update state in any way, even without the select-element.

**Comment by gaearon** [comment] 2017-04-06 15:21
Looks like a bug in RC.

**Comment by aweary** [comment] 2017-04-06 15:54
I created [a JSFiddle](https://jsfiddle.net/6y71rhvc/) using `15.5.0-rc.1` that contains a controlled text input, controlled `select` and a counter. I'm not seeing the error reported in the Codepen. Basic state updates appear to be working fine.

**Comment by bvaughn** [comment] 2017-04-06 15:56
The Codepen ([here](http://codepen.io/jochenberger/pen/wJbJpo?editors=0010#0)) is comparing a string value ("2") to a numeric value (2) which makes it appear to fail.

**Comment by aweary** [comment] 2017-04-06 15:58
It appears to be related to reconciliation when the render output is different, specifically

```jsx
{ this.state.selected == '1' && <div>Selected 1</div>}
```

If you remove those two lines that conditionally render `div`s it works fine. If I had that line to the JSFiddle it will break once the node is removed and then re-added.

**Comment by nhunzaker** [comment] 2017-04-06 16:06
@aweary Suspicious. I made a significant change to controlled inputs. Do you think it is related to https://github.com/facebook/react/pull/7359?

**Comment by aweary** [comment] 2017-04-06 16:07
@nhunzaker no I don't think so. It looks like the lazy tree updates expect that an update be an actual node, but it's being passed as a string:
<img width="754" alt="screen shot 2017-04-06 at 11 02 21 am" src="https://cloud.githubusercontent.com/assets/6886061/24764174/18f904a0-1ab9-11e7-95e5-9192dc779d19.png">

**Comment by syranide** [comment] 2017-04-06 16:10
@nhducit It is not caused by the `<select>`, it breaks without it too.

**Comment by bvaughn** [comment] 2017-04-06 16:11
@nhunzaker @aweary FWIW there were 6 cherrypicked commits in this branch. The rest of the changes were deprecations and small relocations. The cherrypicked commits were:

fe4a5b4 Fix Chrome number input backspace and invalid input issue (#7359)
ef38390 Add component stack to invalid element type warning (#8495)
17434d7 Fix test renderer unmount (#8512)
ac53db3 Delete @nosideeffect annotation (#8882)
9d21b52 Change the order between function declaration and object assignment (#8895)
e33eab4 Bump fbjs to 0.8.9 (#8910)

**Comment by aweary** [comment] 2017-04-06 16:14
AFAICT the issue stems from the fact that [an `INSERT_MARKUP` update](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/shared/stack/reconciler/ReactMultiChild.js#L33-L43) sets `content` to a string, but [when the update is handled](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/dom/stack/client/DOMChildrenOperations.js#L183-L188) it's being handled by a [`DOMLazyTree` method that expects a node tree](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/dom/stack/client/DOMLazyTree.js#L57-L58)

I'm not sure how it relates to those commits yet 🤔

**Comment by aweary** [comment] 2017-04-06 16:16
It might be because `useCreateElement` is not being properly set
<img width="446" alt="screen shot 2017-04-06 at 11 16 27 am" src="https://cloud.githubusercontent.com/assets/6886061/24764621/8b254ac4-1aba-11e7-8658-974fbd400d1f.png">

**Comment by aweary** [comment] 2017-04-06 16:44
Adding to that, it looks like it's due to the wrong transaction type getting injected into `ReactUpdates`

<img width="753" alt="screen shot 2017-04-06 at 11 42 19 am" src="https://cloud.githubusercontent.com/assets/6886061/24765665/43fb36dc-1abe-11e7-914c-b70d8839c384.png">

`ReactTestReconcileTransaction` doesn't track `useCreateElement` and shouldn't be used in production.

**Comment by aweary** [comment] 2017-04-06 16:49
And _that_ is because code from the shallow renderer is being included and parsed in `react-dom`
<img width="607" alt="screen shot 2017-04-06 at 11 46 16 am" src="https://cloud.githubusercontent.com/assets/6886061/24765783/c367aa40-1abe-11e7-89ab-445a1c2eb16b.png">


cc @gaearon @trueadm it looks like it's probably related to the new build process then?

**Comment by gaearon** [comment] 2017-04-06 17:08
New build process isn’t in React 15.5, only in master. Good investigation though!

**Comment by bvaughn** [comment] 2017-04-06 17:28
Nice find, @aweary.

Dan's right, the 15.5 build process is a bit of a one-off.

**Comment by bvaughn** [comment] 2017-04-06 18:18
> And that is because code from the shallow renderer is being included and parsed in `react-dom`

This is because of my changes in 3a7eef2. I'm on it!

**Comment by bvaughn** [comment] 2017-04-06 18:30
Fixed with 714e5ea. Fix will go out with our next rc 2 release in a few moments.

**Comment by bvaughn** [comment] 2017-04-06 18:31
Sorry for the inconvenience! Thanks for reporting this @jochenberger and for help identifying the cause @aweary! You rock!

**Comment by bvaughn** [comment] 2017-04-06 23:31
Took us a bit longer than anticipated, but RC 2 was just released and fixes this issue.
http://codepen.io/bvaughn/pen/YZbdjK?editors=0010#0

Thanks again for reporting it!

**Closed by bvaughn** 2017-04-06 23:31 UTC
Labels: Type: Bug
