### ISSUE TITLE
[ReactDOM bug] Missing upgrade in test-utils

### ISSUE THREAD

**Issue by spamshaker** [facebook/react#25469] opened 2022-10-12 06:24 UTC
According to documentation https://reactjs.org/docs/test-utils.html#renderintodocument, should be:
```javascript
const domContainer = document.createElement('div');
ReactDOM.createRoot(domContainer).render(element);
```
but is ReactDOM.render
https://github.com/facebook/react/blob/2cf4352e1c81a5b8c3528519a128c20e8e65531d/packages/react-dom/src/test-utils/ReactTestUtils.js#L137

**Comment by zabihhaqqani** [comment] 2022-10-12 12:57
Hi, I would like to work on this issue!

**Comment by eps1lon** [comment] 2022-10-16 10:30
Duplicate of https://github.com/facebook/react/issues/25446

**Closed by eps1lon** 2022-10-16 10:30 UTC
