### ISSUE TITLE
Error: "Could not find node with id "5203" in commit tree"

### ISSUE THREAD

**Issue by jonasthiesen** [facebook/react#17500] opened 2019-12-02 15:32 UTC
Describe what you were doing when the bug occurred:
1. Recording with the Profiler
2. Clicking on the "Ranked Chart"

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.1-3816ae7c3

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157108
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157054)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157577)
    at vl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:314907)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59907)
    at el (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:68139)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:108547)
    at Lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92715)
    at Pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92640)

Component stack: in vl
    in div
    in div
    in div
    in wo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Li
    in $e
    in dn
    in Ca
    in Pc

**Comment by aweary** [comment] 2019-12-02 18:58
cc @bvaughn

**Comment by jonasthiesen** [comment] 2019-12-02 19:24
If you need any additional information, I'll gladly supply it. Not really sure if it's anything specific to my setup (seeing it mentioned multiple times in the other issues, I would assume not?)

After playing around with it, it seems to work when I click on "Ranked Chart", but then it sometime breaks if I click on additional items. Strange.

**Comment by bvaughn** [comment] 2019-12-03 15:41
I'm going to close this issue because it's a duplicate of #16446 but any extra info you could provide on how to repro would be helpful!

**Closed by bvaughn** 2019-12-03 15:41 UTC
Labels: Component: Developer Tools, Type: Needs Investigation
