### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by MeisterTea** [facebook/react#18726] opened 2020-04-24 13:27 UTC
There seems to be a memory leak when running jest tests

![](https://i.imgur.com/NAgFU1n.png)

React version: 16.13.1

## Steps To Reproduce

* Pull repo: https://github.com/MeisterTea/react-memory-leak
* `yarn` or `npm install`
* `yarn test:w1`

I am getting a heap size larger than one gigabyte on a production code repository

**Comment by eps1lon** [comment] 2020-04-24 13:42
Could try it without `@testing-library/react` but a custom beforeEach/afterEach cleanup? If it still leaks try without `jest`? 

Since we only render a static component I doubt that this is react leaking but rather `@testing-library/react` or `jest`. Maybe that's expected that jest retains some "things" from passed tests.

Component under test:
```jsx
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}```

**Comment by eps1lon** [comment] 2020-04-24 14:36
Did some digging and this is definitely a leak caused by `@testing-library/react`. Could you open an issue in that repo please: https://github.com/testing-library/react-testing-library/issues/new/choose

**Comment by bvaughn** [comment] 2020-04-24 15:58
Thanks for the added context, @eps1lon!

Going to close this issue for now.

**Closed by bvaughn** 2020-04-24 15:58 UTC
Labels: Status: Unconfirmed
