### ISSUE TITLE
Tutorial Link Expired

### ISSUE THREAD

**Issue by SCKelemen** [facebook/react#8711] opened 2017-01-08 06:04 UTC
Line 19 |  react/docs/tutorial/tutorial.md

Links to: http://codepen.io/ericnakagawa/debug/ALxakj/auth

**Comment by bvaughn** [comment] 2017-01-08 08:50
Thanks for letting us know. :smile:

This is a duplicate of #8699 though. Closing this one.

**Closed by bvaughn** 2017-01-08 08:50 UTC
