### ISSUE TITLE
Batching can update one component twice, causing unpredictable lifecycle

### ISSUE THREAD

**Issue by m4tthumphrey** [facebook/react#2410] opened 2014-10-26 11:31 UTC
This one is hard to explain or reproduce but I'll try...

I'm using the following mixin which has changed slightly from the original I found in a gist a while back:

```js

var React = require('react');

var LayeredComponentMixin = {

  componentDidMount: function() {
    this._layer = document.createElement('div');
    document.body.appendChild(this._layer);
    this._renderLayer();
  },

  componentDidUpdate: function() {
    this._renderLayer();
  },

  componentWillUnmount: function() {
    this._unrenderLayer();
    document.body.removeChild(this._layer);
  },

  _renderLayer: function() {
    var layer = this.renderLayer();

    if (null === layer) {
      layer = <noscript />;
    }

    React.render(layer, this._layer);

    if (this.layerDidMount) {
      this.layerDidMount(this._layer);
    }
  },

  _unrenderLayer: function() {
    if (this.layerWillUnmount) {
      this.layerWillUnmount(this._layer);
    }

    React.unmountComponentAtNode(this._layer);
  }

};

module.exports = LayeredComponentMixin;
```

This allows me to create layered components, in my case a modal dialog. I use the following component to build my modals:

```js

var React = require('react');

var ToolboxUserActionCreators = require('../../actions/ToolboxUserActionCreators');

var ModalStore = require('../../stores/ModalStore');

function getStateFromStore() {
  return {
    modalCount: ModalStore.getModalCount()
  };
}

var Modal = React.createClass({

  componentWillMount: function() {
    this.setState({
      modalLevel: ModalStore.getModalCount()
    });
  },

  componentDidMount: function() {
    ModalStore.addChangeListener(this.onChange);
    document.addEventListener('keydown', this.handleKeyDown);
  },

  componentWillUnmount: function() {
    ModalStore.removeChangeListener(this.onChange);
    document.removeEventListener('keydown', this.handleKeyDown);
  },

  getInitialState: function() {
    return getStateFromStore();
  },

  getDefaultProps: function() {
    return {
      className: 'feature'
    }
  },

  render: function() {
    var className               = 'toolbox2-modal-content toolbox2-modal-' + this.props.className;
    var modalBackdropClassName  = 'toolbox2-modal-backdrop';
    var handleBackdropClick     = this.handleBackdropClick;
    var killClick               = this.killClick;
    var modalLevel              = this.state.modalLevel;
    var totalModals             = this.state.modalCount;

    if (modalLevel < totalModals) {
      modalBackdropClassName += ' toolbox2-modal-backdrop-secondary';
    }

    return (
      <div className={modalBackdropClassName} onClick={handleBackdropClick}>
        <div className={className} onClick={killClick}>
          {this.props.children}
        </div>
      </div>
    );
  },

  killClick: function(e) {    
    e.stopPropagation();
  },

  handleBackdropClick: function() {
    this.props.onRequestClose();
  },

  handleKeyDown: function(e) {
    if (e.keyCode === 27) {
      this.handleBackdropClick();
    }
  },

  onChange: function() {
    this.setState(getStateFromStore());
  }

});

module.exports = Modal;
```

This combination works perfectly. That is until I close the highest modal. If an `<input />` component is used inside of the `<Modal>` render method, ie `this.props.children`, the following error is thrown. All other element types (that I've tried including `textarea` and `select` work fine, but `input` throws the following: 

`Uncaught Error: Invariant Violation: getDOMNode(): A component must be mounted to have a DOM node`

The trace is as follows:

```
Uncaught Error: Invariant Violation: getDOMNode(): A component must be mounted to have a DOM node. bundle.js:60783
invariant bundle.js:60783
ReactBrowserComponentMixin.getDOMNode bundle.js:62069
ReactCompositeComponent.createClass.componentDidUpdate bundle.js:64334
assign.notifyAll bundle.js:68718
ON_DOM_READY_QUEUEING.close bundle.js:72258
Mixin.closeAll bundle.js:68960
Mixin.perform bundle.js:68901
Mixin.perform bundle.js:68887
assign.perform bundle.js:56107
(anonymous function) bundle.js:56186
wrapper bundle.js:53734
Mixin.closeAll bundle.js:68960
Mixin.perform bundle.js:68901
ReactDefaultBatchingStrategy.batchedUpdates bundle.js:64050
batchedUpdates bundle.js:56122
ReactEventListener.dispatchEvent bundle.js:64980
```

`ReactCompositeComponent.createClass.componentDidUpdate bundle.js:64334` is [here](https://github.com/facebook/react/blob/b7cd3e7d1de31108594a6698215bfa7bf8619b34/src/browser/ui/dom/components/ReactDOMInput.js#L98).

This only happens when there are several modals on top of each other; one dialog with an `<input />` runs fine with no error.

The weird thing is that the app still runs fine, the error thrown has no impact (apart from being thrown) on how my app performs....

This is on 0.12RC1 using webpack to build.

**Comment by m4tthumphrey** [comment] 2015-03-18 15:20
This has raised it's ugly head again since 0.13... The error message is now:

> Uncaught Error: Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains `render` method but is not mounted in the DOM

@spicyj @zpao @syranide

**Comment by danschumann** [comment] 2015-03-18 15:59
I'm getting this error on a callback for `onBlur` that was generated from a mixin.

Specifically, it looks like this:

```
App.mixins.nativeOnChange = (method) ->

  return nativeOnChange: (attribute, originalVal, m) ->

    unless _.isFunction method
      method = @[method]

    # Override CB
    if _.isString m
      m = @[m]
    else unless _.isFunction m
      m = method

    console.log 'native!', arguments...

    return {
      onKeyDown: (e) ->
        console.log 'kEY!', e.keyCode
        if e.keyCode is 13 then m.call this, e, attribute, $(e.target).val()

      onBlur: (e) ->
        console.log 'bluuur!', e
        m.call this, e, attribute, $(e.target).val()
    }
```
for the mixin, and implementation is:

```
              props = @nativeOnChange()
              <div className='clearfix decimal-container'>
                <input
                  className='form-control decimal-tiny pull-right'
                  type='number' min=0 max=5 defaultValue={decimal ? opts.decimal}
                  {...props}
                />
                Decimals:
              </div>
```

So, basically, it generates an object `{onBlur: fn..., onKeyDown: fn...}`, and within the `onBlur`, I am calling `@getDOMNode()`, which throws the error

**Comment by spicyj** [comment] 2015-03-20 01:17
@m4tthumphrey Do you have a repro case for this? Are you sure you're calling getDOMNode at a time that the node is still in the DOM?

**Comment by m4tthumphrey** [comment] 2015-03-20 09:27
Well yes I guess so. It works fine in 0.12.2.

**Comment by mfunkie** [comment] 2015-03-23 13:36
This is getting me too after upgrading to 0.13.  The problem seems to exist with an input that I have nested in a few components within a React Bootstrap Modal and I close the modal.  I can't get much more of a trace on this than that though...

**Comment by m4tthumphrey** [comment] 2015-03-23 14:03
@mfunkie Yes that case sounds exactly the same except I'm not using bootstrap.

**Comment by mfunkie** [comment] 2015-03-23 18:03
More on this, with my modal, I'm using the React Bootstrap [Overlay Mixin](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayMixin.js) which creates a new React tree.  If I just render the Modal as a child component, opening and closing it does not trigger the error anymore.  Could this be related to React elements being on a different Tree, `React.unmountComponentAtNode` being called, and for some reason that Input node is still being checked against for updates?

**Comment by mfunkie** [comment] 2015-03-23 18:54
It turns out in my issue, I had two components listening to the same Flux Store.  The Container component that would run the Overlay, and the inner body of the Modal.  By adding the following function to the inner Modal Body, I was able to avoid the error

```
shouldComponentUpdate(nextProps, nextState) {
  if (!nextState.modalOpen && this.state.modalOpen) {
    return false;
  }
  return true;
}
```

My best guess is that the change listener was still queued up to run and an inner state was rendered after the Modal had already been considered closed.

**Comment by wilkerlucio** [comment] 2015-04-03 16:53
@mfunkie I'm having the same issue as you, I was using react-modal before and just changed to the one in react-bootstrap.

**Comment by chetstone** [comment] 2015-04-04 22:52
I'm also using react-bootstrap and ran into this issue. I'm using react@0.12.2, react-bootstrap@0.17.0 

@mfunkie workaround fixed it for me. Thanks!

**Comment by gaearon** [comment] 2015-06-26 12:22
This tripped me, I'd have expected `findDOMNode(this)` to return `null` for unmounted components.

**Comment by gaearon** [comment] 2015-06-26 12:23
I guess throwing makes sense, but the error message is too cryptic:

>Uncaught Error: Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains render method but is not mounted in the DOM

I honestly thought I had duplicate React or something, so I didn't even bother to check whether the component was mounted. (It wasn't.)

**Comment by jimfb** [comment] 2015-06-26 17:27
@gaearon Tracking as https://github.com/facebook/react/issues/4233.

**Comment by jimfb** [comment] 2015-06-26 17:39
With regards to the original issue/topic: It sounds like the issue might be related to react-bootstrap calling update on an unmounted ReactDOMInput component, right?

So next steps on this issue are:
1.  Confirm/repro the bug with the latest React and react-bootstrap, and if the issue is still present, file a bug on react-bootstrap for updating an unmounted component.  @mfunkie @wilkerlucio @chetstone, can you help with this one, since you guys are the ones who see the bug?
2.  On our end, updating an unmounted component should be a noop, meaning that componentDidUpdate probably shouldn't be called (or at the very least, shouldn't throw in ReactDOMInput).  See: https://github.com/facebook/react/blob/b7cd3e7d1de31108594a6698215bfa7bf8619b34/src/browser/ui/dom/components/ReactDOMInput.js#L98  Error boundaries should help.

**Comment by chetstone** [comment] 2015-07-30 21:04
I looked into this. The problem is still there using react 0.13.3 and react-bootstrap 0.23.7. I cannot test with the latest react-bootstrap because changes in in 0.24.0 broke my abandonded project in ways that would require major rewrites. It could be that these changes affect this issue.

**Comment by aaronjensen** [comment] 2015-08-08 01:45
This repros outside of react-bootstrap for me. Just having an `<input />` in a form that gets swapped out during a submit triggers it.

**Comment by spicyj** [comment] 2015-08-08 01:48
@aaronjensen Any chance you can post a simple repro case for us?

**Comment by aaronjensen** [comment] 2015-08-08 01:52
@spicyj i'll work on it.

**Comment by m4tthumphrey** [comment] 2015-08-08 06:28
FYI, this was initially reported as part of the React core, nothing todo with react-bootstrap. I believe the issue is still there.

**Comment by spicyj** [comment] 2015-08-08 06:36
@m4tthumphrey Yes, but it's terribly difficult for me us to debug without a repro case, which your original issue also didn't provide.

**Comment by aaronjensen** [comment] 2015-08-08 07:07
@spicyj Here is a repro: https://github.com/aaronjensen/react-2410-repro

Currently, it depends on redux and react-router. I ripped out everything else from our app and this is the minimum I could get to w/o starting to reimplement redux or react-router. Hope this is helpful.

**Comment by aaronjensen** [comment] 2015-08-08 07:08
The error does not happen if this line is removed: https://github.com/aaronjensen/react-2410-repro/blob/master/app/create_router.jsx#L10

**Comment by m4tthumphrey** [comment] 2015-08-08 08:23
@spicyj I know, I wasn't criticising or anything, just updating the issue. To be honest I haven't looked into this issue for months as still use the temp solution mentioned above. I'll revisit this week.

**Comment by spicyj** [comment] 2015-08-08 08:45
@aaronjensen Thanks for the repro case. I'll try to look into this.

@m4tthumphrey No worries.

**Comment by spicyj** [comment] 2015-08-08 09:13
Okay, I tracked down the root cause.

If updates to a parent and child component are both enqueued during a batch and while the parent is updating another update to the child is enqueued, we end up reconciling the child twice which breaks other assumptions and interleaves lifecycle methods incorrectly. In both 0.13.2 and master (if you fix the batchedUpdates reference), this code

```
var Parent = React.createClass({
  getChild: function() {
    return this.refs.child;
  },
  render: function() {
    return <Child ref="child" />;
  }
});

var once = false;
var Child = React.createClass({
  getInitialState: function() {
    return {updated: false};
  },
  componentWillUpdate: function() {
    if (!once) {
      once = true;
      this.setState({updated: true});
    }
  },
  componentDidUpdate: function() {
    console.log('child update');
  },
  render: function() {
    console.log('child render');
    return <div />;
  }
});

var parent = React.render(<Parent />, document.getElementById('container'));
var child = parent.getChild();
console.log('--- start of batch');
React.addons.batchedUpdates(function() {
  parent.forceUpdate();
  child.forceUpdate();
});
console.log('-- end of batch');
```

produces the output

```
child render
--- start of batch
child render
child render
child update
child update
-- end of batch
```

where the render and update lines should be interleaved.

**Comment by spicyj** [comment] 2015-08-08 09:14
I thought we had a warning for setState in componentWillUpdate but I guess not.

**Comment by m4tthumphrey** [comment] 2015-08-27 15:29
Just an quick update. I thought I'd give 0.13.3 a go and straight away ran into

`Uncaught Error: Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains `render` method but is not mounted in the DOM`

**Comment by spicyj** [comment] 2015-08-27 21:05
@m4tthumphrey That message means the same as "Invariant Violation: getDOMNode(): A component must be mounted to have a DOM node." In #4727 I improved the message to make it a bit clearer.

I wouldn't expect this issue to be fixed until we make a specific attempt to fix it at which time you'll see stuff happening on this issue.

**Comment by m4tthumphrey** [comment] 2015-10-07 20:09
I've just upgraded my app to 0.14 and so far I haven't been able to reproduce this bug. @spicyj could anything you know of fixed this prior to the 0.14 release?

**Comment by spicyj** [comment] 2015-10-07 20:13
No, it isn't fixed. The test case I posted still has the problem.

**Comment by spicyj** [comment] 2015-12-28 22:27
#3762 has a nice repro too; should verify that it gets fixed too.

**Closed** 2016-04-29 21:02 UTC
Labels: Component: Batching
