### ISSUE TITLE
Feature Suggestion: Add `ignoreMemberCallExpression` option for `exhaustive-deps` lint rule

### ISSUE THREAD

**Issue by chayeoi** [facebook/react#20755] opened 2021-02-07 12:09 UTC
## As-is

When only referring to object's member properties, `exhaustive-deps` lint rule does not show a warning.

However, **when calling object's member property, this rule shows a warning.**

```tsx
function Password() {
  const verifyPassword = useMutation(apis.verifyPassword);

  useEffect(() => {
    verifyPassword.mutate;
  }, [verifyPassword.mutate]); // PASS

  useEffect(() => {
    verifyPassword.mutate();
  } ,[verifyPassword.mutate]); // React Hook useEffect has a missing dependency: 'verifyPassword'. Either include it or remove the dependency array.
} 
```

I saw [Dan's comment](https://github.com/facebook/react/issues/14920#issuecomment-467494468) on this behavior.

> This is because technically props.foo() passes props itself as this to foo call. So foo might implicitly depend on props. We'll need a better message for this case though. The best practice is always destructuring.

It is fully understood.

However, **when the entire object is included as a dependency, the following problem can occur.**
Take a look at the following code.

```tsx
const verifyPassword = useMutation(apis.verifyPassword); // `verifyPassword` equals to `{ isLoading: boolean; mutate: Function }`

// `verifyPassword(password)` sets `isLoading` to `true` and causes `useEffect` hook that depends on `verifyPassword` objects to be re-excuted. This eventually leads to an infinite loop.
useEffect(() => {
  if (password === PASSWORD_LENGTH) {
    verifyPassword.mutate(password);
  } 
  
}, [password, verifyPassword]);
```

**There are two ways to avoid this problem.**

```tsx
// 1. Use destructuring
const { mutate } = useMutation(apis.verifyPassword);

useEffect(() => {
  if (password === PASSWORD_LENGTH) {
    mutate(password);
  }
}, [password, mutate]);

// 2. Assign member property to other variable
useEffect(() => {
  const mutate = verifyPassword.mutate;

  mutate();
}, [verifyPassword.mutate]);
```

## To-be

In many cases, it is not common to refer to other members through `this`.

And as in the example above, it is a good idea to use namespace to avoid name conflicts. (https://github.com/facebook/react/issues/16265#issuecomment-587977285)

So, I would like to suggest an **option to set not to warn about _member call expresion_ when using the `exhaustive-deps` rule.**

```tsx
// 'react-hooks/exhaustive-deps': ['warn', { ignoreMemberCallExpression: true }]
useEffect(() => {
  verifyPassword.mutate();
}, [verifyPassword.mutate]); // PASS
```

**Comment by seiyab** [comment] 2021-02-10 04:50
I already created PR.
https://github.com/facebook/react/pull/20521

**Comment by chayeoi** [comment] 2021-02-11 00:16
@seiyab Great! However, there seems to be no discussion about this PR..

**Comment by seiyab** [comment] 2021-02-17 13:13
You're right.
There should have been discussion about the API like this issue before creating PR...

I think adding a new option like your suggestion seems to be a good approach since similar suggestion https://github.com/facebook/react/issues/16265#issuecomment-685723348 gained 10+ 👍 s.
However, no discussion about the option follows in #16265 yet.
Discussing about the option in this issue separately from the problem issue #16265 makes sense.

**Comment by seiyab** [comment] 2021-09-14 11:56
related issue: https://github.com/facebook/react/issues/22305

**Comment by seiyab** [comment] 2022-01-10 11:48
bump

**Comment by eps1lon** [comment] 2022-04-29 15:53
Closing in favor of https://github.com/facebook/react/issues/16265. https://github.com/facebook/react/issues/16265 talks about the general issue. It's not settled that the lint rule should have an option.

**Closed by eps1lon** 2022-04-29 15:53 UTC
Labels: Type: Enhancement, Component: ESLint Rules
