### ISSUE TITLE
Bug: Focusing the input element does not bring up the keyboard on initial page load on mobile

### ISSUE THREAD

**Issue by kiprasmel** [facebook/react#19063] opened 2020-06-02 01:54 UTC
React version: 16.12.0

## Steps To Reproduce

1. 

```tsx
<input autoFocus />
```

## The current behavior

The keyboard of a mobile device is not brought up - only the input is focused. However, navigating to another page with, i.e. react-router-dom's `<Link />` and then coming back, the input is focused AND the keyboard is brought up.

## The expected behavior

The keyboard is brought up in both cases.

---

Tested on an android with google chrome.

Same thing happens if I try using `useEffect` / `useLayoutEffect` + `ref`s

**Comment by lucasemanuelherrera** [comment] 2020-06-04 23:08
Hi!

You should do it in componentDidMount and refs callback instead. Something like this

componentDidMount(){
   this.nameInput.focus(); 
}

class App extends React.Component{
  componentDidMount(){
    this.nameInput.focus();
  }
  render() {
    return(
      <div>
        <input 
          defaultValue="Won't focus" 
        />
        <input 
          ref={(input) => { this.nameInput = input; }} 
          defaultValue="will focus"
        />
      </div>
    );
  }
}
    
ReactDOM.render(<App />, document.getElementById('app'));
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react-dom.js"></script>
<div id="app"></div>

**Comment by algorithmhash** [comment] 2020-06-06 12:13
Edited for readability 

```
componentDidMount(){
this.nameInput.focus();
}

class App extends React.Component{
componentDidMount(){
this.nameInput.focus();
}
render() {
return(

<input
ref={(input) => { this.nameInput = input; }}
defaultValue="will focus"
/>

);
}
}

ReactDOM.render(, document.getElementById('app'));
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react-dom.js"></script>
```

**Comment by eps1lon** [comment] 2020-08-20 12:43
> The keyboard is brought up in both cases.

How does this behave using only HTML and the DOM API? Maybe this is intended behavior by the user agent and React shouldn't do anything about it.

**Comment by bvaughn** [comment] 2020-10-28 13:37
Closing this due to lack of a repro/response

**Closed by bvaughn** 2020-10-28 13:37 UTC
Labels: Resolution: Needs More Information
