### ISSUE TITLE
React 0.14 migration error

### ISSUE THREAD

**Issue by Volodymyr128** [facebook/react#5139] opened 2015-10-12 15:24 UTC
Got the next error while migrated to 0.14 version:

```Invariant Violation: Objects are not valid as a React child (found: object with keys {status, data, operationId, correlationId}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `exports`.```

Is it related to the next string in doc: ```Plain objects are no longer supported as React children; arrays should be used instead. You can use the createFragment helper to migrate, which now returns an array.```? What I should change in the code below:

```javascript
render() {
    const warningDialog = (<RegisterPopup />);
    return (
        <div className="app">
            <div className="view register-step">
                <Header
                    title={this.props.title}
                    progress={this.props.progress}
                    back={this.props.back}/>
                <div className="page">
                    <div className="page-inner">
                        <Content>
                            <form>
                                {this._getContent()}
                            </form>
                        </Content>
                        <Footer
                            buttonClassName={nextBtnClassName}
                            buttonText={this.props.buttonText}
                            clickHandler={this._next.bind(this, this.props.next)}/>
                    </div>
                </div>
                {warningDialog} //< ===== Here
            </div>
        </div>
    );
}
```

**Comment by yaycmyk** [comment] 2015-10-12 15:41
@Volodymyr128 This was documented in the changelog - React doesn't accept objects as children anymore and you can use the createFragment API to convert your object into an array.

**Comment by jimfb** [comment] 2015-10-12 17:36
@yaycmyk Sounds right to me, thanks for answering!

@Volodymyr128 This is a usage question rather than a bug in the React core. We use github issues for tracking bugs in the React core. Usage questions are better answered on StackOverflow. Since this is not a bug in the React core, I'm going to close this issue. Feel free to continue the discussion on this thread.

**Closed by jimfb** 2015-10-12 17:36 UTC

**Comment by spicyj** [comment] 2015-10-12 18:28
warningDialog is probably not the problem. We give you the keys (status, data, operationId, correlationId) so that the real callsite is easier to find.

**Comment by togakangaroo** [comment] 2015-12-12 01:55
Not to resurrect this issue, but I can't find anywhere where this change is discussed. If you don't mind, what is the change behind it? Passing objects and arrays as children seemed completely natural to me and now everything is breaking...

**Comment by yaycmyk** [comment] 2015-12-12 02:00
Arrays are still fine, but not POJOs. https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html <- see the breaking changes section

**Comment by togakangaroo** [comment] 2015-12-12 02:09
Right, what was the reasoning for this change? I'm not trying to be combative, just it screws up some patterns I've been using and I'd like to know the rationale.

**Comment by zpao** [comment] 2015-12-12 07:56
We want to be able to treat an object as if it were a react element, which would allow a JSX transform to transform to objects directly instead of React.createElement function calls. We can't do that well if objects also have other meaning.
