### ISSUE TITLE
`react-dom/server.renderStaticMarkup()` returns empty string server-side

### ISSUE THREAD

**Issue by adamzerella** [facebook/react#14858] opened 2019-02-15 01:07 UTC
**Do you want to request a *feature* or report a *bug*?**

**bug**

**What is the current behavior?**

I'm trying to extract the initial HTML from react code on the server side. To do this, I'm using the official react-dom/server library function `renderToStaticMarkup()` referenced here: https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup

I'm reading a react source file, transpiling the JSX and ES6 syntax to CommonJS using Babel and then parsing the evaluated CommonJS to `renderToStaticMarkup()`.

## React code:
```jsx
import React from 'react';

class Test extends React.Component {
    render() {
        return <p>Hello World!</p>;
    }
}

export default Test;
```

## Server-side code:
```javascript
const { renderToStaticMarkup } = require( 'react-dom/server');
const Babel = require( '@babel/core' );
const Fsp = require( 'fs' ).promises;

(async () => {
    let fileContent = await Fsp.readFile( 'test.js', 'utf-8' );

    let code = Babel.transform( 
        fileContent, 
        { 
            presets: [ '@babel/preset-env', '@babel/preset-react' ],
            comments: false,
            minified: true
        }).code;

    let result = renderToStaticMarkup( code );

    console.log( result );
})();
```

## package.json:
```json
{
  "dependencies": {
    "@babel/core": "^7.3.3",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "react": "^16.8.2",
    "react-dom": "^16.8.2"
  }
}
```

**What is the output?**
`&quot;use strict&quot;;Object.defineProperty(exports,&quot;__esModule&quot;,{value:true});exports.default=void 0;var _re act=_interopRequireDefault(require("react"));function...`

**What is the expected output?**
`<p>Hello World!</p>`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```json
"react": "^16.8.2",
"react-dom": "^16.8.2"
```

**Comment by steve-taylor** [comment] 2019-02-15 06:43
Why ```return `<p>Hello World!</p>`;``` instead of `return <p>Hello World!</p>;`?

**Comment by threepointone** [comment] 2019-02-15 12:23
I'm not sure what you're trying to be honest. what do you expect this code to do? 
```jsx
eval(` 
import React from 'react';

class Test extends React.Component {
    render() {
        return `<p>Hello World!</p>`;
    }
}

export default Test;
`)
```
It doesn't evaluate as an expression, so I'm not sure you'll get expected results from it.

I also don't think you would need to read the source code from the file. (I'm going to assume the file's name is `test.js`, it's confusing to name it `react.js`)
```jsx
import { renderToStaticMarkup } from  'react-dom/server';
import React from 'react'
import Test from './test.js'
let result = renderToStaticMarkup(<Test/>);
console.log( result );
```

As @steve-taylor mentioned, you also don't have to return a string, use jsx and write `return <p>Hello World!</p>;` instead.

Please make a reproducible code sample if you get a bug, or feel free to close this issue.

**Comment by adamzerella** [comment] 2019-02-16 09:04
> Why `` return `<p>Hello World!</p>`; `` instead of `return <p>Hello World!</p>;`?

@steve-taylor Sorry Steve this was a typo, your right it should be `return <p>Hello World!</p>;`

**Comment by adamzerella** [comment] 2019-02-16 09:07
> I'm not sure what you're trying. what do you expect this code to do?
> 
> ```js-jsx
> eval(` 
> import React from 'react';
> 
> class Test extends React.Component {
>     render() {
>         return `<p>Hello World!</p>`;
>     }
> }
> 
> export default Test;
> `)
> ```
> 
> It doesn't evaluate as an expression, so I'm not sure you'll get expected results from it.
> 
> I also don't think you would need to read the source code from the file. (I'm going to assume the file's name is `test.js`, it's confusing to name it `react.js`)
> 
> ```js-jsx
> import { renderToStaticMarkup } from  'react-dom/server';
> import React from 'react'
> import Test from './test.js'
> let result = renderToStaticMarkup(<Test/>);
> console.log( result );
> ```
> 
> As @steve-taylor mentioned, you also don't have to return a string, use jsx and write `return <p>Hello World!</p>;` instead.
> 
> Please make a reproducible code sample if you get a bug, or feel free to close this issue.

@threepointone Sorry for the confusion, I'm running eval on the transpiled react source code, I'm not sure if this is required but I believe this was needed in the past to get the correct output. I've updated my question to be more reproducible. You were correct in thinking `react.js` was `test.js`, @steve-taylor point was also correct, I've updated the return function.

**Comment by threepointone** [comment] 2019-02-16 10:17
Please make a reproducible sample on codesandbox and share the link here.

**Comment by adamzerella** [comment] 2019-02-16 10:37
> Please make a reproducible sample on codesandbox and share the link here.

Here's a example link: https://codesandbox.io/s/zkx1o96804

**Comment by gaearon** [comment] 2019-02-16 14:30
I’ll close because this is unrelated to React and is definitely not a bug. This is a question about how to execute code from a string and use its export value. There’s a few ways but StackOverflow is a more appropriate place to ask.

**Closed by gaearon** 2019-02-16 14:30 UTC
Labels: Type: Question
