### ISSUE TITLE
Bug: onFocus and onBlur has inconsistent batching

### ISSUE THREAD

**Issue by samcooke98** [facebook/react#19400] opened 2020-07-18 01:00 UTC
React version: `0.0.0-experimental-4c8c98ab9` with concurrent mode. 

## Steps To Reproduce

1. In the provided code sandbox, click on a `Todo` component
2. Tab back and forth between the two 
3. At inconsistent times, there will be a frame where the focus hasn't left, but the outline isn't rendered. The outline is only drawn when focus is in. Because there is a brief frame without the border, the todo visibly flickers. 

Link to code example: 

https://codesandbox.io/s/samc-focus-demo-9jyso?file=/package.json:201-229

Video; https://drive.google.com/file/d/18PW8M_VvE3Nau7NkdQq4X8En_Vcen_xQ/view?usp=sharing
Focus shifts multiple times at the beginning, without a flicker. 
Around the 6 seconds mark, there is a flicker.

Photo of the frame; 
![image](https://user-images.githubusercontent.com/787007/87840493-3e811600-c8e3-11ea-8323-076faaabc8c7.png)

## The current behavior

At times there is an 'impossible' frame, where the focus has been set to false, despite the focus just having shifted from one element to another within the same div. 

## The expected behavior
I'm not sure if this pattern is something that is concurrent mode incompatible or something... 

But regardless, I'd expect the behaviour to be consistent - eg for `focus` and `blur` events to be combined into a single frame.

This codepen shows the expected outcome with vanila JS https://codepen.io/samcooke98/pen/OJMaXvx

## Related?
https://github.com/facebook/react/issues/19385

**Comment by gaearon** [comment] 2020-08-06 14:25
Just wanted to follow up that we have some related changes planned in this area in the next months to simplify the model, so we'll be looking at this bug after those changes.

**Comment by jaredpalmer** [comment] 2020-09-20 14:34
Any updates on this? Seeing weird behavior with setState in onFocus and onBlur

**Comment by gaearon** [comment] 2020-09-20 17:00
We haven’t gotten to this yet but it’s planned. This is CM-only, right?

**Comment by jaredpalmer** [comment] 2020-09-23 19:46
@gaearon correct seeing it on experimental with CM. Confirmed it wasn't recoil either.

**Comment by gaearon** [comment] 2020-09-23 22:10
As a temporary fix, like always with this kind of issue, you can wrap `setState` into `ReactDOM.flushSync`:
https://codesandbox.io/s/samc-focus-demo-forked-g08oj

**Comment by jaredpalmer** [comment] 2020-09-23 22:21
Can you explain the difference between that and wrapping with unstable_batchedUpdate? I’m sure they are completely different, but humor me.

**Comment by gaearon** [comment] 2020-09-23 22:51
Ah, yeah.

- `batchedUpdates` means "don't let the setStates inside commit independently". So it *prevents* flush inside but it doesn't force the flush on exit.
- `flushSync` means "commit the setStates inside as you exit me". So it doesn't prevent flushes inside (afaik) but it forces a flush on exit.

So `batchedUpdates` is useful when you have multiple `setState`s (e.g. due to Flux subscription) but you want to only have one render pass. It's less useful in CM because we already batch things by default more aggressively in it.

Whereas `flushSync` is useful to *force* a thing to happen now. Like if iOS prevents audio from playing if you don't do it in the same tick, so you say "apply this now". It has a caveat that it's not always possible (e.g. you can't call it from inside a lifecycle to avoid recursive commits).

**Comment by gaearon** [comment] 2020-09-23 22:57
For example,

```js
function handleClick() {
  batchedUpdates(() => {
    setStateA()
    setStateB()
  })
  console.log('hello')
}
```

This is actually useless because React event handers are *already* batched. You can think of it as there being an outermost `batchedUpdates` call. The render pass begins when you exit the outermost `batchedUpdates` call. And then the actual flush happens depending on the mode (e.g. in CM it may be time-sliced, although we plan to make changes for discrete events like focus/click).

On the other hand, something like this:

```js
function handleClick() {
  flushSync(() => {
    setStateA()
    setStateB()
  })
  console.log('hello')
}
```

actually forces both the render pass and the commit to happen before your log. Because it's useful to enforce the DOM has already been changed. Like if you need to do something with it. Usually comes up in cases where you're interfacing with some browser API that needs to be called right away.

**Comment by gaearon** [comment] 2020-09-23 23:32
Correction about `batchedUpdates`:

>It's less useful in CM because we already batch things by default more aggressively in it.

It's actually completely useless in CM because its semantics don't affect anything. This is because in CM there is nothing that would force `setState` to flush "right now" by default. So there is no need for a method that prevents that from happening.

**Comment by jaredpalmer** [comment] 2020-09-23 23:34
Thank you! Very useful. So flushSync is definitely  what I need as I’m doing programmatic scroll into view + focus based on some effects and keyboard events.

**Comment by gaearon** [comment] 2021-02-10 23:18
This does not appear reproducible in a sandbox using the build from https://github.com/facebook/react/pull/20792. That PR enables some flags that aren't enabled yet, but will be closer to the release. Essentially, they make discrete events (including focus/blur) flush in a microtask.

https://codesandbox.io/s/samc-focus-demo-forked-zlfbm?file=/package.json

I think we can close this since it's not directly actionable, but it will take some time before this behavior gets to an `experimental` build because we need to do more testing. Thanks for raising this!

**Closed by gaearon** 2021-02-10 23:18 UTC
Labels: Component: Concurrent Mode, Type: Bug

**Comment by gaearon** [comment] 2021-03-31 14:18
Can't reproduce this in latest `experimental` so I think the fix is out.
