### ISSUE TITLE
Error: "Commit tree does not contain fiber 673. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by tianyu** [facebook/react#20469] opened 2020-12-15 17:26 UTC
Describe what you were doing when the bug occurred:
1. Profiled react application
2. Saw an element that re-rendered multiple times.
3. Clicked on it in the flame graph.
4. Under "Why did this render?" saw "Hooks changed"
5. Under "Rendered at", clicked the second option.
6. Error shows up.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-f160547f47

Component stack: CommitFlamegraphAutoSizer@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:34144:50
div
div
div
SettingsModalContextController@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:28205:1
Profiler_Profiler@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:35772:50
ErrorBoundary_ErrorBoundary@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:29219:5
PortaledContent@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:29336:27
div
div
ProfilerContextController@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:32933:1
TreeContextController@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:24321:1
SettingsContextController@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:24810:1
ModalDialogContextController@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:29403:1
DevTools_DevTools@moz-extension://6380acc0-3e17-43af-8b20-53f30c399d2a/build/main.js:36206:1

**Comment by bvaughn** [comment] 2020-12-15 18:39
Can you reliably reproduce this? If so, can you please share a repro case with us? (The bug is unlikely to be fixed without out.)

Going to close this as a duplicate of #20431 but *please* share info if you're able to repro this.

**Closed by bvaughn** 2020-12-15 18:39 UTC
