### ISSUE TITLE
React performs n-1 insertBefore operations when I move only one item in list

### ISSUE THREAD

**Issue by bgnx** [facebook/react#10565] opened 2017-08-29 12:04 UTC
https://codesandbox.io/s/vqk87kvj1y. List contains 10000 items, I move one item from bottom to top and react performs 9999 insertBefore operations. It sucks. Take a look at infernojs example  https://jsbin.com/qeqatiruko/1/edit?html,js,output - it will perform only one insertBefore operation for one move in all cases.

**Comment by 3axap4eHko** [comment] 2017-08-29 14:59
Also I figured out that `arr.unshift(arr.pop());` performs 9999 insertBefore, but `arr.push(arr.shift());` performs 1 insertBefore

**Comment by aweary** [comment] 2017-08-29 15:10
Thanks for the report @bgnx! This is essentially a duplicate of https://github.com/facebook/react/issues/10565, please direct any feedback on this issue there. Thanks!

**Closed by aweary** 2017-08-29 15:10 UTC
