### ISSUE TITLE
Use of ReactOS logo and project name

### ISSUE THREAD

**Issue by yereverluvinunclebert** [facebook/react#10849] opened 2017-09-26 21:39 UTC
This project seems to have subsumed almost the same name and logo of the ReactOS project. 

That seems rather disengenuous.

The ReactOS logo is very close the spinning atom logo with a globe in the middle and so is yours. The project name is ReactOS and your is ReactJS. This seems at best confusing and at worst it looks as if your project is treading on the coat-tails of ReactOS.

EDIT: name correction

**Comment by herodrigues** [comment] 2017-09-26 22:33
React logo has nothing to do with ReactOS logo. I can list several projects that have similar logos with a globe and rings around it.
I think you're exaggerating things a little bit in here. 

By the way, this is not even an issue. Feel free to post this question in websites like https://stackexchange.com/, maybe you'll find some people that agree with your point of view.

A quick search on Google and you would find this article: http://blog.mostlydoing.com/2014/02/react-atom-trends-in-logo-design.html

**Comment by gaearon** [comment] 2017-09-27 00:03
Hey, sorry about that.

This is the first time since open sourcing React (in 2013) that someone has brought this up. In practice, we haven't seen any confusion between the two, as people generally know whether they're looking for an operating system or a JavaScript library, and there's no overlap between the two.

I agree the logo similarity is unfortunate but it's a pretty obvious leap from "react" to "reactor" and that is often visualized with something atom-like. I'm sure you can find a bunch of other projects called similarly that also use a similar logo.

I don't think it would be fair to say React is "treading on the coat-tails of ReactOS". React was [installed about a million times this week](https://npm-stat.com/charts.html?package=react), and I'm fairly confident the people who installed it didn't mean to install ReactOS, but were intentional users of React.

I appreciate you sharing the concern but I hope this answers it.
Cheers!

**Comment by jeditobe** [comment] 2017-09-27 09:35
ReactJS and ReactOS have a difference of only one letter.

**Comment by yereverluvinunclebert** [comment] 2017-09-27 09:59
It is an answer to the concern but it does not resolve it. The name and logo is confusing now and will lead to further confusion in the future. It definitely IS an issue. This is not an over-'react'ion.

The point is to have chosen React as a name and then the atom logo is obviously inspired (consciously or sub-consciously) by previous exposure to the ReactOS logo otherwise it is too much of a coincidence. The confusion started at the point the atom logo was paired with the React name. Having just one element might be acceptable but both? That starts to become more than just mere coincidence. 

Regardless of the cause, the fact is, it now exists. The result is that the combination is confusing at the very least. The fact that the React product is sponsored by Facebook could lead to some serious issues for the ReactOS team now and definitely in the future. Rather than seeing this as a non-issue, I suggest you start thinking about a solution. 

This does not need to become an argument as I expect in any discussion or argument it would become quite clear that the ReactOS name and logo pairing existed long before that of React. So, to prevent such an argument it might be wise to think about a possible solution now...

I never said "React is treading on the coat-tails of ReactOS", I said "**it looks as if** your project is treading on the coat-tails of ReactOS" and it certainly does look that that way due to the pairing of the logo and name. How unlucky would you have to be to choose a logo and name that similar? It is certainly a mistake if an unconscious one.

I suggest that this could be quite a serious issue in the future given that ReactOS aims to be the de facto open source replacement for Windows and therefore you need to give some thought to resolving this. For both projects sake, I think it needs to be resolved. 

If you can keep it civil and non-adversarial then that would be my suggestion. The ReactOS team and community is a very friendly group of people and open to ideas. Please be aware that the ReactOS team has NOT formally raised this as an issue. People coming from the ReactOS forums and commenting here may simply have the best interests of the ReactOS project in mind. I remind you that this is a community project just like your own.

Trying to be as friendly as possible here in order to deflect any naturally defensive responses. I think you need to look into this to prevent it being a problem before it becomes one.

**Comment by binarymaster** [comment] 2017-09-28 11:15
> ReactOS IRC channel every day has new visitors asking for help with ReactJS

This. And Telegram group too.

**Comment by gaearon** [comment] 2017-09-28 14:33
Reopening to continue the discussion since it seems like my answer was not satisfactory.

**Comment by gaearon** [comment] 2017-09-28 14:50
>Regardless of the cause, the fact is, it now exists. The result is that the combination is confusing at the very least. 

What I’m trying to say is that we never experienced this confusion. If you search for “ReactOS” on the issue tracker, the only match are these two threads.

I’m not saying this to dismiss your concerns, and I very much appreciate your friendly attitude. But if this problem is one-sided, **you have more context into where exactly the people get confused**. Could you share some examples of how that happens?

I understand it can be tough in an IRC chat where, unlike a website, there is less information you can convey. I don’t think anybody would mistake the projects from looking at their websites, but a single letter is easier to miss in the channel list.

We don’t even use IRC actively anymore, and perhaps we can remove its mention from our website. Would that be helpful? Perhaps there could also be some way to highlight more clearly that the ReactOS channel is about an operating system.

I’d like to mention that Pierre Schweitzer (who *does* represent ReactOS) has reached out to us a few years ago. He agreed that renaming either of the projects is not a realistic solution.

I would love to hear specific suggestions on how we can improve this and arrive at a mutual understanding.

Thanks!

**Comment by jeditobe** [comment] 2017-09-28 15:53
> renaming either of the projects is not a realistic solution.

But you are able to change the logo of React JS

**Comment by bjrmatos** [comment] 2017-09-28 16:07
> But you are able to change the logo of React JS 

that would not be fair for our community, both logos share the shape but the design of the logos are very easy to recognize.

since you are only describing issues on your IRC channel, why changing the logo would change something for that specific problem?

**Comment by yereverluvinunclebert** [comment] 2017-09-28 17:12
Thankyou for re-opening the issue, that is appreciated. Discussion is continuing re: your project's use of the name and logo in combination and how it affects the ReactOS project now and in the future. Examples of adverse affects don't really come into it at this point. ReactOS has a trademark for ReactOS and is a user of the React word and the atom logo. We just want to assert our rights to out the name/logo combination to prevent confusion and to ensure those rights are not subverted by another project that could claim ownership of that combination. 

Discussion continues and I'm sure some may comment here too. Let's leave this open for the moment and we'll see how the discussion matures from the ReactOS community/project team side.

**Comment by herodrigues** [comment] 2017-09-28 19:42
Pointless discussion.
It would make more sense if someone from the Atom project team would have made those claims.

Considering that ReactOS is not even stable, it would be easier to change the ReactOS name and logo.

**Comment by MailYouLater** [comment] 2017-09-30 06:59
To be honest, the first time I saw a mention of ReactJS I thought it was a typo of ReactOS, so I wouldn't be at all surprised (considering how widespread ReactJS usage is becoming) that people just getting into website design would think the opposite: "ReactOS? huh, must be a typo of ReactJS." which (IMO) makes it a bigger issue for ReactJS than it is for ReactOS because people who are looking for ReactJS help are finding ReactOS instead.

Then there's the separate issue that both ReactJS and ReactOS are in the IT field, so the similarities between logo and name mean that if they want to, ReactOS (having used their name and logo much longer than ReactJS has) could sue ReactJS.

ReactJS being a Facebook project, I think Facebook's legal team made quite a blunder letting ReactJS be published in a world where ReactOS already existed, and I personally feel that ReactJS should change it's name. (Note: This last paragraph is just my personal opinion. Please continue with the civil conversation that's going on.)

**Comment by bjrmatos** [comment] 2017-09-30 08:43
> which (IMO) makes it a bigger issue for ReactJS than it is for ReactOS (at least for now) because people who are looking for ReactJS help are finding ReactOS instead.

i've never saw this confusion in our community, in fact, for me this is the first time i heard about ReactOS (and i'm sure that most React.js developers don't know about the existence of ReactOS, because i never saw a mention for it until now). at least for the react side i don't think that anyone would confuse ReactOS with React.js.



> Then there's the separate issue that both ReactJS and ReactOS are in the IT field, so the similarities between logo and name mean that if they want to, ReactOS (having used their name and logo much longer than ReactJS has) could sue ReactJS.

well, i don't think there is no problem with this, as said in previous comments, some representants of ReactOS has said that renaming projects is not a realistic solution, and i would say that it is the same case for the logo. the logos are very different still to be considered the same, the only coincidence is the base shape of the atom, which in react the shape is more highlighted and with more color, very different.



> I think Facebook's legal team made quite a blunder letting ReactJS be published in a world where ReactOS already existed.

maybe the did not know about the existence of ReactOS project in the first place, which seems very logical to me because the project does not have a lot of popularity (at least in the most common developer network: Github). 



> and I personally feel that ReactJS should change it's name.

changing a name of such huge popular project like React.js would be very chaotic for this community, i would say that it will even make the situation worse because there will be thousands of articles, blog posts, stackoverflow questions that will not belong to any project, and probably these kind of content that will be left on the fly would cause even more confusion for the ReactOS project.

**Comment by MailYouLater** [comment] 2017-09-30 20:29
> for the react side i don't think that anyone would confuse ReactOS with React.js.

This is obviously not the case if people are going to the ReactOS IRC channel and/or Telegram group looking for ReactJS help. Which (as has already been stated in this thread) they *are* doing, and frequently.

Regarding the potential for suing, the ReactOS foundation may not be intending to do so, but it would be intelligent for the ReactJS project to take the fact that they're putting themselves in a potentially dangerous legal situation seriously.

> > I think Facebook's legal team made quite a blunder letting ReactJS be published in a world where ReactOS already existed.
> 
> maybe the did not know about the existence of ReactOS project in the first place, which seems very logical to me because the project does not have a lot of popularity (at least in the most common developer network: Github).

If Facebook's legal team was wholly unaware of ReactOS when they allowed Facebook to make the ReactJS project public, they're failing in their responsibilities. Researching what projects exists with similar names in and outside of your field of business (but especially in it) in order to prevent the company from placing itself in a potentially bad legal situation is one of the primary reasons for having such departments. Also, a GitHub presence is unlikely to be what a (decent) legal team looks for when researching such potential issues. Wikipedia on the other hand (while admittedly not a good location for legal advice) would be a much better 'quick indicator' regarding whether a project with a similar name exists and ReactOS has been one of the linked projects on [Wikipedia's react disambiguation page](http://wikipedia.org/wiki/React) (a place most people would check if they were considering naming a software project "React") for over a decade.

> > and I personally feel that ReactJS should change it's name.
> 
> changing a name of such huge popular project like React.js is not something cheap and it would be very chaotic for this community, i would say that it will even make the situation worse because there will be thousands of articles, blog posts, stackoverflow questions that will not belong to any project, and probably these kind of content that will be left on the fly would cause even more confusion for the ReactOS project.

As stated, 'ReactJS should change its name' is my personal opinion. However I will state that changing the name of ReactJS would be much less of a financial burden to Facebook than changing the name of ReactOS would be to the ReactOS Foundation. Also, Facebook and ReactJS have enough of a popular presence at the moment that a name change would be very visible, and not likely to leave many people confused. Even considering the potential for stragglers looking for ReactJS when it has been renamed, such a change would notably cut down on the number of people looking for ReactJS help in ReactOS help channels.

Again, I'm not saying that "ReactJS must change its name", just that this **is** a problem, and changing the name of the (much younger) ReactJS project is what I personally would vote for.

**Comment by herodrigues** [comment] 2017-09-30 21:17
Honda and Hyundai have similar name and logo. Hyundai belongs to the Hyundai Group which is older than Honda, though Hyundai cars (owned now by Hyundai Motor Company) were manufactured many years after the first Honda car.

Honda is very famous worldwide because of its awesome cars. Hyundai is becoming famous too though its cars don't directly compete with Honda cars in the market.

Now imagine the following situation: an owner (Joe) of a Honda car suddenly "realizes" that Honda and Hyundai have similar name and logo.

"Oh, look! *H*yu**nda**i and **H**o**nda***. That's very similar! But hey, look again! Honda's logo is a H and Hyundai's logo is an italic H"

At this moment, Joe totally forgets that any brand can have a letter H as logo if their business name starts with such letter.
Also, Joe also forgets that these logos have different font style and design.

Then, Joe starts emailing Hyundai about such "discovery" asking for its owners to change their brand name. Joe also calls his friends to support his views, even though he knows Honda businessmen have admitted that those similarities are not intentional.

Did you find Joe's story ridiculous?

**Comment by Mathspy** [comment] 2017-10-01 00:53
The amount of npm packages named react-* for doing things in a React way
The amount of tutorials for using React
The amount of Stackoverflow questions asking about React-related things
The amount of articles written about React whether they are tutorial-like or news-like (Blog post about new features) or otherwise
...
And much more.
All of this will have to be changed?

Okay let's actually say everyone involved agreed, let's change React's name. What do you think will happen?
As returning developers watch old un-renamed tutorials or read articles and search React, you're the first thing they hit (due to Google removing ReactJS from first results for searching React). Confused, they will look for a way to communicate with owners of ReactOS, "Did React stop being a JS library and became an OS??"
If anything such a change will lead more people your way than someone misspelling ReactJS for ReactOS, so if this is the only thing bothering you, then this is far from the best way to address your concerns.
So logically I think we can start this conversation probably by saying renaming ReactJS is not only damaging to the whole ReactJS ecosystem, but also to the causes you came here to address. Do you have any other alternative to propose?

**Comment by bjrmatos** [comment] 2017-10-01 05:52
> This is obviously not the case if people are going to the ReactOS IRC channel and/or Telegram group looking for ReactJS help. Which (as has already been stated in this thread) they are doing, and frequently.

yes, but this is something that can be solvable without solutions like changing logos or names. it is a community support problem. 



> Also, Facebook and ReactJS have enough of a popular presence at the moment that a name change would be very visible, and not likely to leave many people confused.

IMO you are very wrong about this, the impact of such change is really huge.

you right about this, 

> changing the name of the (much younger) ReactJS project is what I personally would vote for.

you are right about that React JS is much younger, but React JS has much much impact and content presence in internet than ReactOS so changing something at this point would be very bad. i would say that probably there are good solutions that does not involve changing the image of the projects. so far at this point the issues described are about community support channels, i think this is something fixeable but i don't know enough about the community support channels of ReactOS in order to give some proposals.

**Comment by gaearon** [comment] 2017-10-02 12:33
After the discussion with Pierre Schweitzer who represents the ReactOS project, we are adding a disambiguation note to the IRC page: https://github.com/facebook/react/pull/11025. I hope this helps reduce the confusion.

**Comment by jeditobe** [comment] 2017-10-02 13:33
Lol, I see a mistake here! 

ReactOS channel is #ReactOS, and not #React as you wrote in patch

**Comment by gaearon** [comment] 2017-10-02 13:36
Hmm, that’s what Pierre told me.

<img width="633" alt="screen shot 2017-10-02 at 2 35 42 pm" src="https://user-images.githubusercontent.com/810438/31079882-02e36e00-a77f-11e7-8468-6da4db0e00c5.png">

I'll ask him to comment here to clarify. :-)

**Comment by jeditobe** [comment] 2017-10-02 14:21
![capture](https://user-images.githubusercontent.com/1814425/31081839-cbe91f5a-a795-11e7-8f03-c4840eb42490.PNG)

Probably, you guys have taken over this channel too.  I do not see to belong to ReactOS team.

**Comment by gaearon** [comment] 2017-10-02 14:27
OK, this is indeed confusing. But I can assure you nobody from the React team is on `#react` channel either. I don't know who set it up. I'll change the docs to point to `#reactos` instead, but I want to make it clear we neither manage `#react` nor claim any ownership over it.

**Comment by gaearon** [comment] 2017-10-02 14:30
I further clarified in https://github.com/facebook/react/commit/12d5231c2aa60277ab22e441bc9b09b57ff3d4cc.

**Comment by blackcrack** [comment] 2017-10-02 18:28
change you name and all iss good..
as example, UIjs, Guijs,Gui.js, JavaScript.Gui,
NODE.NativeGUI, Interactive.js or JS-Interactive which sounds even better..
or Render.js.Native or Easydeb.js or "Easdebint Javascript" "Interactive js UI lib"
easy take a exist name from a long year exist Community (and you has kniw it !!)
it lame and swiped.. prove and demonstrate, that you are have insufficient ingenuity 
to even to find a proper name who be independence.
This is my opinion.. and i guess we have a free opinion.. so..
Also the thing with the notoriety of the name for become a very good  start of the own Project..
the Reactos was known and the React it's not meant a Ordering system.. but any know which direction 
this name is, you can't deny it ... i give you the names as gift : 

UIjs, Guijs,Gui.js, JavaScript.Gui, NODE.NativeGUI, Interactive.js or JS-Interactive which sounds even better.. 
or Render.js.Native or Easydeb.js or "Easdebint Javascript" "Interactive js UI lib"

take one of them and you have like reactos peace and frendship .
and what speaks against if you programming a gui for Reactos too..
by side of the Reactos .. and therewith can you stand as partner too..
a change name would be really better. 
Because, i guess, this fit certainly others also not .. 
where want saves a free WinNT unter GPL Community name and a system where it is later free to download.. and therewith take i am the Hat ;)

best regards
Blackcrack

**Comment by HBelusca** [comment] 2017-10-02 18:40
Changing the names, on both sides, would be now extremely difficult due to: 1. public recognition problems; 2. Possibly internal or documented APIs whose names include "React(J/O)S" in them, etc... which would need to be renamed, thus breaking backward-compatibility.

**Comment by blackcrack** [comment] 2017-10-02 18:42
it is easy to give only a emoji but it is really better to give a  statement 👍

**Comment by binarymaster** [comment] 2017-10-02 18:47
This is going to be offtop...  :face_with_thermometer:

**Comment by gigaherz** [comment] 2017-10-02 18:47
A note about the confusion regarding the `#react` IRC channel: it would appear that someone took advantage of a netsplit and changed the topic and channel modes -- the channel is still effectively owned by ReactOS as it always was, the forwarding to `#reactos` is still in place, and the only way to join it is by previously having joined `#reactos` -- or during a netsplit.

@jeditobe please ask around next time before jumping to conclusions, please.

**Comment by HBelusca** [comment] 2017-10-02 19:02
@blackcrack
> how old is the Reactos Project now ?
Check: http://web.archive.org/web/19990823212715/http://www.reactos.com:80/public/contact.html (archived 23rd August 1999);
and history of the logo:
- First known ReactOS logo ever (1999): https://web.archive.org/web/19991008000009/http://www.reactos.com/
- Updated "radioactive" ReactOS logo (2002): https://web.archive.org/web/20020326061016/http://reactos.com/
- New "atomic" ReactOS logo (2003): https://web.archive.org/web/20031016123206/http://reactos.com/

**Comment by blackcrack** [comment] 2017-10-02 19:16
👍

**Comment by jeditobe** [comment] 2017-10-18 10:39
Just a fresh example of confusion

https://twitter.com/jnsdrtlf/status/920369019412209664

**Comment by HeisSpiter** [comment] 2017-10-31 20:17
Dear all,

I do not believe that keeping that issue open for ages will bring anything new to the discussion. I think @HBelusca summed up everything previously. Both projects have their personality and identity through their name and their logo. It would make no sense to rename nor to change the logo of the two projects.

@gaearon already made a huge step in the direction of disambiguation and I am glad he did. We should play fool and be already happy with that as it reduces the amount of lost people on the IRC channels.

All that could be done now, to address last remark from @jeditobe would be to put an extra explanation our own website stating we are not based on ReactJS. The same way we often state we are not based on Linux in any way. This is the really same issue with a different project.

I propose we close this issue, given all the above statements. This issue lasted long enough and none of our projects will gain anything from fighting against the other.

As a side note for observers who may wonder, since this specific issue has been opened, I have been mailing with @gaearon to find constructive answers to this issue. Telling the others what to do is not being constructive.

If some ReactOS folks are still not happy with this, I invite you to discuss this at the next monthly meeting.

Thanks again, @gaearon, for your help on this topic.

Cheers,
Pierre

**Comment by gaearon** [comment] 2017-10-31 20:22
Thanks, Pierre!

I will close this issue but if you feel like there's something else we could do to help reduce the confusion, let us know.  

❤️

**Closed by gaearon** 2017-10-31 20:22 UTC
Labels: Type: Discussion

**Comment by ghassanmas** [comment] 2018-01-29 23:38
I found this issue when I was trying to figure out why ReactJS has the atom logo, then I got it, since chemical substance reacts with each other "chemical reaction" as a result the arrangement of electrons is changed around the atoms. so the name and the logo of React really fits the concept behind the library of ReactJS.

**Comment by gaearon** [comment] 2018-01-30 00:02
I'll lock this since we have resolved the matter. Thanks to everybody who participated.
