### ISSUE TITLE
State not getting updated properly while using useReducer with Context API

### ISSUE THREAD

**Issue by BrinsterAman** [facebook/react#21151] opened 2021-03-31 16:09 UTC
Due to proprietary code issue, can't share the code but will explain the issue elaborately. I have two functions, **function 1** and **function 2** . Inside **function 1**, I am updating my state twice by calling dispatch with two different action.type each time. After updating my state, I want to call **function 2** (from **function 1**), and read state's value. But my state is not getting updated properly. 

Can you please help me with this issue.

I am using useReducer with context api, for state management.

**Comment by bvaughn** [comment] 2021-03-31 17:28
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

Note that you **do not have to share proprietary code** to share a repro. In fact, it's easier for us if you don't, and instead just share a small sample of code that isolates the actual problem you're reporting.

**Comment by BrinsterAman** [comment] 2021-04-01 08:35
Can you please check this sandbox link for your reference, [Sandbox](https://codesandbox.io/s/crazy-lamport-0ghrk?file=/src/Home.js). But this is just a sample to demonstrate what we are trying in our original code flow. Just look for the **console.log** value. As far as my understanding goes, **console.log** value should have been **State show -> true** but it is printing **NOT true**.

**Comment by tomasyaya** [comment] 2021-04-01 08:49
Why don't you execute checkComputation() on a separate useEffect with the corresponding value in the dependency array?

**Comment by BrinsterAman** [comment] 2021-04-01 10:11
As mentioned, this is just a sample representation of how we are calling functions and dispatch. According to our requirement, we need to dispatch before calling the other function, for here the checkShowValue() function. Please can you tell me why the state is not getting properly updated??

**Comment by tomasyaya** [comment] 2021-04-01 12:27
I think React tries to batch updates together if possible for performance.

Your code runs synchronously so checkShowValue will be executed before the update is reflected.

For instance, this shows the console log you wish.

```
const doComputation = async () => {
    dispatch({ type: "SET_SHOW", payload: true });
    await new Promise(res => res(checkShowValue()));
    dispatch({ type: "SET_NUMBER", payload: 14 });
  };
```

That's why maybe you could change the approach like

`React.useEffect(() => { checkComputation() }, [show])`

or something like that

**Comment by BrinsterAman** [comment] 2021-04-01 12:50
I updated my codesandbox code, with your proposed solution of using async and await but it still, prints **NOT true**. Can you please once verify on the same link. Also, as per our requirement, we just want **doComputation()** function to be called once in a lifecycle, so by providing anything in the dependency array will trigger it again and again, as state value is changing many places in our original code.

**Comment by tomasyaya** [comment] 2021-04-01 13:29
```
import React, { useContext, useEffect } from "react";
import { Context } from "./Store";

const Home = () => {
  const [state, dispatch] = useContext(Context);
  const {show} = state;

  const checkShowValue = React.useCallback( () => {
    if (show) {
      console.log("State show ->", show);
    } else {
      console.log("NOT true");
    }
  }, [show])

  const doComputation =  () => {
    dispatch({ type: "SET_SHOW", payload: true });
    dispatch({ type: "SET_NUMBER", payload: 14 });
  };
  
  useEffect(() => {
    doComputation();
  }, []);

  useEffect(() => { show && checkShowValue() }, [checkShowValue, show])

  return <>{show && <h1>{state.number}</h1>}</>;
};

export default Home;
```

**Comment by tomasyaya** [comment] 2021-04-01 13:36
Also, you can try using this approach which seems to be less prone to unwanted behavior.
```

const StateContext = React.createContext({});
const DispatchContext = React.createContext({});

export function Provider({ children }) {
  const [state, dispatch] = React.useReducer(reducer, initialState);

  return (
    <StateContext.Provider value={state}>
      <DispatchContext.Provider value={dispatch}>{children}</DispatchContext.Provider>
    </StateContext.Provider>
  );
}

export function useState(){
    return React.useContext(StateContext)
}

export function useDispatch(){
    return React.useContext(DispatchContext)
}
```

**Comment by bvaughn** [comment] 2021-04-01 13:54
> I think React tries to batch updates together if possible for performance.

React does batch updates from an effect together, yes.

I think there's another misunderstanding here thought related to [how closures work in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures).

I copied this code from the sandbox above and added some inline comments:
```js
const [state, dispatch] = useContext(Context);

// This function (checkShowValue) is defined each time your component renders.
// It closes over the value of `state` (whatever that object happens to be during render).
const checkShowValue = () => {
  // ...
};

const doComputation = async () => {
  dispatch({ type: "SET_SHOW", payload: true });

  // Adding an async pause here doesn't give you the value you're looking for,
  // because this function (doComputation) closes over checkShowValue,
  // which itself closes over an old value of `state`.
  // No matter how long you wait, the old value will always be printed.
  await new Promise((res) => res(checkShowValue()));

  dispatch({ type: "SET_NUMBER", payload: 14 });
};
```

I'm going to close this issue because it's not a React bug. We can keep chatting on it though!

**Closed by bvaughn** 2021-04-01 13:54 UTC
Labels: Resolution: Needs More Information
