### ISSUE TITLE
Error: "Could not find node with id "490" in commit tree"

### ISSUE THREAD

**Issue by rgehan** [facebook/react#17503] opened 2019-12-02 18:36 UTC
I wasn't doing anything too fancy:
- Ran a really quick profile
- Clicked on the ranked tab

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: `4.2.1-3816ae7c3`

```
Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157108
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157054)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157577)
    at vl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:314907)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59907)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:107381)
    at Lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92715)
    at Pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92640)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89544)

Component stack: in vl
    in div
    in div
    in div
    in wo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Li
    in $e
    in dn
    in Ca
    in Pc
```

**Comment by aweary** [comment] 2019-12-02 18:57
Thanks for reporting, marking as a duplicate of #17500

**Closed by aweary** 2019-12-02 18:57 UTC
