### ISSUE TITLE
Image onError event is getting triggered even if image is loading

### ISSUE THREAD

**Issue by allanchua101** [facebook/react#13649] opened 2018-09-14 09:01 UTC
***Current Behavior***

Image _onError_ event is getting triggered every time it loads data from a piped image from Amazon S3:

*Sample Code*
```jsx
   <img src={this.props.src}
        onError={this.props.onFailedImageLoad} 
        onLoad={this.props.onImageLoad}
        alt="Cannot load image" />
```
*Piping Image Code*
```js
    s3ObjectTags
      .execute(s3Config)
      .promise()
      .then(data => {
        res.writeHead(200, { "content-type": "image/png" });
        s3Streamer.execute(s3Config).createReadStream().pipe(res);
      })
      .catch(err => {
        let filePath = path.join(__dirname, "..", "..", "..", "images", "missing-file.png");
        let src = fs.createReadStream(filePath);

        res.writeHead(404, { "content-type": "image/png" })
        src.pipe(res);
      });
```
***Expected Behavior***

Image should not trigger onError event if image will loads

**Comment by gaearon** [comment] 2018-09-14 12:33
Can you check whether it's React-specific or you get the same behavior with browser built-in `error` event?

**Comment by allanchua101** [comment] 2018-09-14 12:45
Thanks for response man! I appreciate it, 

I'll try to do it once I get back in the office and let you know what I find.

Have a nice weekend!!!

**Comment by threepointone** [comment] 2019-09-09 09:30
Closing this issue because there's no reproducing example. Happy to reopen if there's more information.

**Closed by threepointone** 2019-09-09 09:30 UTC
Labels: Resolution: Needs More Information, Type: Needs Investigation
