### ISSUE TITLE
Bug: using MessageChannel prevents node.js process from exiting

### ISSUE THREAD

**Issue by just-boris** [facebook/react#20756] opened 2021-02-07 14:13 UTC
----

# Edited: Here's how to fix this: https://github.com/facebook/react/issues/20756#issuecomment-780927519.

----

React version: 17.0.1 (latest)

## Steps To Reproduce

This code finishes properly in node.js 14, but holds the process open in node.js 15

```js
global.window = global; // simulate JSDOM
require('scheduler');
```

Since node.js 15, there is a global `MessageChannel` object now, which prevents node event loop from exiting. To let the process shut down properly, it should either call `port.close()` or `port.unref()`

This becomes an issue when testing React code within JSDOM environment, as the test process cannot exit properly.

## The current behavior

The process with JSDOM tests never finishes

## The expected behavior

The process finishes properly

**Comment by rickhanlonii** [comment] 2021-02-10 03:47
Nice find! Do you want to submit a PR to fix?

**Comment by patil2097** [comment] 2021-02-10 08:15
I would love to help you on fixing this problem.Can you guide me in submitting a fix? I am really new to open source.  @rickhanlonii

**Comment by amensum** [comment] 2021-02-10 09:06
Can I take this issue for try to fix it and send PR?

**Comment by amensum** [comment] 2021-02-10 11:06
@just-boris 
Can you show an example for reproduce this issue?

**Comment by amensum** [comment] 2021-02-10 15:37
Issue example:

```js
const { JSDOM } = require('jsdom')

var { window } = new JSDOM()

global.window = window
global.document = window.document

require('scheduler')
```

**Comment by rickhanlonii** [comment] 2021-02-10 17:30
Hey all, anyone can take this issue, I'll review the first PR.

The problem is that [this feature detection](https://github.com/facebook/react/blob/454c2211c09bfa2fd5475c25665f3bbeb6882841/packages/scheduler/npm/index.js#L3) is too naive. In node environments, we should use `unstable_no_dom` and in browser environments we should use the browser scheduler.

**Comment by gaearon** [comment] 2021-02-17 21:01
We're going with https://github.com/facebook/react/pull/20834 as a likely fix in 17.1.0, but it will need more testing.

**Comment by gaearon** [comment] 2021-02-17 23:43
## How to fix this

### If you can upgrade to React 17.1.0

When React 17.1.0 comes out, it will contain a fix for this. So upgrading would solve this problem.

(At the time this comment is written, it's not out yet, but I expect it to be out soon.)

### If you can't upgrade to React 17.1.0

```
npm i react-16-node-hanging-test-fix 
```

and add this **to your test setup file as THE VERY FIRST IMPORT**:

```js
import 'react-16-node-hanging-test-fix';

// All other imports go after it:
import React from 'react'
// ...
```

This should fix the hanging on Node 15+ with jsdom on older versions of React. We don't plan to be updating them because there's too much risk of breaking something else, as this detection is subtle and there are many possible edge cases.

The package with the fix will print a warning asking you to remove it after you upgrade to React 17.1.0. This is because the fix itself is to disable Node's `MessageChannel` implementation, which is not ideal in long term.

--- 

Let me know if you run into more problems! I'll keep the issue for now until we release 17.1.0.

**Comment by just-boris** [comment] 2021-02-18 00:29
Brilliant fix :)

```
delete global.MessageChannel;
```

Would it make sense to let Node.js devs know that this is happening? Perhaps, they could consider undoing the change in Node 16.

**Comment by gaearon** [comment] 2021-02-18 00:44
I've briefly chatted with Node folks but it seems pretty difficult to change (and would be a breaking change). In our case, `setImmediate` is closer to the semantics we need anyway, so it makes sense as a fix. Just a bit risky to port to all the past versions in case people run bad polyfills etc.

**Closed** 2021-03-01 18:34 UTC
Labels: Component: Scheduler, good first issue

**Comment by jarredt** [comment] 2022-08-25 00:01
@gaearon -- I think the `react-16-node-hanging-test-fix` file may have a critical typo:
```
if (semverGt(version, '17.0.1')) {
  console.error(
    'The `react-16-node-hanging-test-fix` package is no longer needed ' +
    'with React ' + version + ' and may cause issues. Remove this import.'
  )
}
```
Shouldn't the `if` be evaluating for "greater than or equal to **17.1.0**"? Per [your comment](https://github.com/facebook/react/issues/20756#issuecomment-780927519) and the comment at the top of the package file, the issue is fixed starting with `17.1.0`.

Right now it's evaluating "greater than **17.01**" -- so I'm getting the warning for `17.0.2` even though the issue isn't fixed there.

**Comment by jarredt** [comment] 2022-08-25 00:19
Also... it looks like maybe the fix actually didn't land until React 18, so maybe needs to be changed to `18.0.0`?

Ref: Mention of the fixing PR (#20834) in https://github.com/facebook/react/pull/24195.

**Comment by rickhanlonii** [comment] 2022-08-25 18:27
@jarredt what version of `scheduler` are you using? I think the issue is that the code checks for 17.0.1, but the fix is actually in the `scheduler` package. It was fixed in version 0.20.1 of the scheduler.

**Comment by jarredt** [comment] 2022-08-29 20:06
@rickhanlonii -- ah, so we're using `20.0.2` for `react-dom`, but one of our `storybook`-related dependencies is bringing in `0.19.1` as a transitive of `react-dom@16.14.0`. I assume that may be the issue I'll see if I can get that bumped or excluded from executing in our tests.

**Comment by andrecrimb** [comment] 2022-09-09 14:11
@jarredt did you manage to get around this issue? We are facing the same problem.

**Comment by jarredt** [comment] 2022-09-09 16:17
For now I've just kept using the temp fix package but patched it to adjust
the version on which it applies the warning. I'm hoping we can update
storybook soon and so won't need to make any adjustments after that.
