### ISSUE TITLE
Bug: useSyncExternalStore update not batched within unstable_batchedUpdates

### ISSUE THREAD

**Issue by Andarist** [facebook/react#24831] opened 2022-06-30 17:20 UTC
## Steps To Reproduce

1. schedule two updates using "default priority" scope (eg. from within setTimeout)
2. let one of the updates be handled through `useSyncExternalStore` and let the other one be handled through regular `setState`

Link to code example:
https://codesandbox.io/s/interesting-chatterjee-9ed8hj?file=/src/App.js (without `unstable_batchedUpdates`)
https://codesandbox.io/s/prod-glitter-51vwm1?file=/src/App.js (with `unstable_batchedUpdates`)

## The current behavior

The `useSyncExternalStore` update gets flushed and committed before the other one has a chance to be committed to the screen. This doesn't allow me to read the updated state of the committed DOM of the children components from within the Parent's effect

## The expected behavior

I would expect to be able to "join" this sync update of the `useSyncExternalStore` somehow. Ideally, I wouldn't have to wrap both with `unstable_batchedUpdates`. It would be cool if I could just schedule a single update with the same priority. If I understand correctly multiple updates coming from different `useSyncExternalStore` updates can be batched together (it doesn't work like `flushSync`, so it doesn't literally immediately flush the scheduled update) - and I would just like to hop on that train with my second update.

I could live with the solution based on `unstable_batchedUpdates` but that doesn't seem to work either.

**Comment by markerikson** [comment] 2022-08-14 17:51
Andarist pointed out this is likely the cause of https://github.com/reduxjs/react-redux/issues/1912

**Comment by sebmarkbage** [comment] 2022-09-05 21:01
`unstable_batchedUpdates` is a way to deprioritize an update by delaying it. The default priority is even more delayed and more batched than `unstable_batchedUpdates`. So `unstable_batchedUpdates` is a noop in React 18.

If you need the consistency you need to compromise by making your updates less batched and flush earlier than they otherwise would with `flushSync`.

That's the compromise of using `useSyncExternalStore`. To preserve consistency with external mutable store you have to make it less batchable - less delayed, than other forms of updates.

**Comment by TkDodo** [comment] 2022-10-31 11:21
> So `unstable_batchedUpdates` is a noop in React 18.

Cool, that's the first time I'm seeing this. Is the same true for `unstable_batchedUpdates` from `react-native` @sebmarkbage ?

**Comment by TkDodo** [comment] 2024-04-10 07:03
bump

**Comment by markerikson** [comment] 2024-07-09 23:08
BUMP!

**Comment by rickhanlonii** [comment] 2024-07-13 03:52
This is fixed in the RC and has been fixed in canary for awhile. We now flush default with all other sync updates.

<img width="1382" alt="Screenshot 2024-07-12 at 11 49 36 PM" src="https://github.com/user-attachments/assets/eb13e881-c2de-4081-9a33-417cdc7aab78">


https://codesandbox.io/s/stupefied-julien-6fysc9?file=/package.json

If I'm missing something let me know and I'll re-open.

**Closed by rickhanlonii** 2024-07-13 03:52 UTC
Labels: Status: Unconfirmed
