### ISSUE TITLE
No warning or Error on component mounting itself

### ISSUE THREAD

**Issue by brasscapon** [facebook/react#15856] opened 2019-06-11 01:42 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When mounting a component within itself, there is no warning or error, and leads to an infinite loop until the browser tab crashes. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
```
const Card = (
  <Card>test</Card>
);

<Card />
```

**What is the expected behavior?**
warning in dev tools or throws an error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "^16.8.1",

**Comment by threepointone** [comment] 2019-09-04 11:13
Recursive/nested components are a valid usecase (much like recursive/nested functions). Could you provide a reproducing example where this was an actual issue? 

(aside: Your example is strange because it wouldn't even run; Card wouldn't be defined where it's used and would immediately error. I assume you meant to wrap it with a function)

Closing this issue, happy to discuss if there's a codesandbox reproducing example.

**Closed by threepointone** 2019-09-04 11:13 UTC
