### ISSUE TITLE
Bug: React 18 upgrade getting uncaught runtime errors

### ISSUE THREAD

**Issue by mohamed-isak** [facebook/react#26819] opened 2023-05-16 10:10 UTC
React version: 18
## The current behavior 
Hi am updated my index.js file createRoot for react.renderDOM warning issue fix, after updating my code getting below error

**My code changes:** 
**My old and new code update**

![image](https://github.com/facebook/react/assets/61628358/73371dc5-f636-4f04-98fd-845408030720)

**Below is the error**
![image](https://github.com/facebook/react/assets/61628358/3a3bad42-626d-4611-b759-4210596b11ac)

## The expected behavior
I want to stops the run time errors from react libraries

**Comment by thejzain** [comment] 2023-05-16 10:36
I was also having same kind of problem and sticked to the old method

**Comment by gaearon** [comment] 2023-05-16 16:21
The "old method" will be removed in a future release so that's not a solution.

The error you're seeing is due to repeated `setState` calls from inside a lifecycle method, as the error message says. We can't guess where it's happening without a reduced code example. If you think there is a bug in React, please provide one. I will have to close this issue because it contains no runnable code example reproducing the problem.

I'd note that generally you want to look at the stack trace to see what's causing these updates. In your example, there's something called `TemplateBase` which calls something called `PluginHost.broadcast` which eventually leads to `setState` calls. So something gets into an infinite loop there. Using GitHub search, I found [this file](https://github.com/DevExpress/devextreme-reactive/blob/b2fdd43eec5e20a269fadc7aa8641940094b8e43/packages/dx-react-core/src/plugin-based/template.tsx) which is probably where the issue originates. I suggest to file an issue in https://github.com/DevExpress/devextreme-reactive if you can isolate the problem to that package.

**Closed by gaearon** 2023-05-16 16:21 UTC
Labels: Status: Unconfirmed
