### ISSUE TITLE
bug - getDerivedStateFromProps is invoked after change state in the same component

### ISSUE THREAD

**Issue by KarloZKvasin** [facebook/react#12916] opened 2018-05-28 08:12 UTC
**bug - getDerivedStateFromProps is invoked after change state in the same component**

CodeSandbox ( https://codesandbox.io/s/8k1v8xjq68 )
In my example you can see, that the ElementOne clear state after change state in this component, because  the static function getDerivedStateFromProps is invoked (In the guide is: The static getDerivedStateFromProps lifecycle is invoked after a component is instantiated as well as when it **receives new props**. -> ElementOne received new state.). ElementTwo is same with component willReceiveProps, but this behavior is ok.

react 16.4
react-dom 16.4

**Comment by tomaspolz** [comment] 2018-05-28 08:16
+1

**Comment by rozekfr** [comment] 2018-05-28 08:17
+1

**Comment by TryingToImprove** [comment] 2018-05-28 10:19
It seems to have been changed in 16.4 - https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops

**Comment by philipp-spiess** [comment] 2018-05-28 11:15
This is a duplicate of https://github.com/facebook/react/issues/12898. Please refer to that thread instead.

**Closed** 2018-05-28 14:17 UTC

**Comment by gaearon** [comment] 2018-05-28 14:19
Closing as a duplicate. 

As I explain in https://github.com/facebook/react/issues/12898#issuecomment-392117539, if this change broke your code, it means there was already a bug in your code that you didn’t notice. I’m sorry for disruptions but we generally try to make dormant bugs visible (so people can fix them), and this case is no exception.

If your `getDerivedStateFromProps` implementation doesn’t have bugs then this change will not affect it.

**Comment by minbelapps** [comment] 2019-08-20 13:20
@gaearon:  The https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html says: _getDerivedStateFromProps exists for only one purpose. It enables a component to update its internal state as the result of changes in props._

So why it's updated after the state change?

The description says: A change could trigger B change.  Implementation: A chang or B change could trigger B change. 

And you are repeating in all the posts that it's not the bug. 

It's the same as to try to make a red car, make a description, that it's the red car, but in reality to make a green car and repeat that's not a bug, it's the expected behavior.

**Comment by suiyuan2009** [comment] 2020-01-06 09:13
You can save pre prop and compare with the new prop.
