### ISSUE TITLE
Bug: Suspense/fallback adds a style display: none !important and this doesn't get removed on IE 11

### ISSUE THREAD

**Issue by wickedrahul** [facebook/react#20054] opened 2020-10-19 14:30 UTC
Suspense/fallback wraps the components with `display:none !important` initially and somehow this style doesn't get removed automatically even after the components loads into the DOM on IE 11. Works fine on chrome through. If I manually remove this from the dev tool, you can see it shows up.

Seems like this is re-introduced:
https://github.com/facebook/react/issues/14114

React version: 16.12.0

	
`<Suspense fallback={<CircularProgress />}>
			<Provider store={store}>
				<PersistGate loading={<div>Loading...</div>} persistor={persistor}>
					<Main />
				</PersistGate>
			</Provider>
		</Suspense>
`

![image](https://user-images.githubusercontent.com/17119296/96467074-2dc89f00-1248-11eb-8054-567d079a0665.png)

**Comment by bvaughn** [comment] 2020-10-19 14:33
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by wickedrahul** [comment] 2020-10-19 14:50
> It doesn't look like this bug report has enough info for one of us to reproduce it.
> 
> Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.
> 
> Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

Updated the comment. Please le me know if that's good enough.

**Comment by bvaughn** [comment] 2020-10-19 14:55
Please create a Code Sandbox that shows the problem.

**Comment by wickedrahul** [comment] 2020-10-19 15:07
Is there any option out there on Sandbox that selects other browser because the site doesn;t even load directly.

**Comment by eps1lon** [comment] 2020-10-19 15:21
> Is there any option out there on Sandbox that selects other browser to see because the site doesn't even load directly on IE 11.

Should work by deploying: 

Add
```json
"browserslist": {
  "production": [
    "IE 11"
  ],
  "development": [
    "IE 11"
  ]
}
```

to the package.json in your codesandbox, deploy (select Vercel or Netlify) from the "Deployment" panel and share the url to the deployed page.

**Comment by bvaughn** [comment] 2020-10-19 15:21
You can create the sandbox with Chrome/Firefox/Edge and then link to it. It doesn't need to be created in IE.

Alternately you could share a create-react-app project with us?

**Comment by amir-beheshty** [comment] 2020-10-19 20:26
I believe this is similar issues as [18906](https://github.com/facebook/react/issues/18906) and [14114](https://github.com/facebook/react/issues/14114). 
The `display: none important!` persists in IE-11.

**Comment by bvaughn** [comment] 2020-10-28 13:39
Closing this due to lack of a repro.

**Closed by bvaughn** 2020-10-28 13:39 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
