### ISSUE TITLE
Set state to <select>'s defaultValue can't work

### ISSUE THREAD

**Issue by oceanpad** [facebook/react#7525] opened 2016-08-19 01:40 UTC
```
constructor(props) {
    super(props);
    this.state = {
       select_value=""
    };       
setTest(){
  this.setState{select_value = 1}
}
<select defaultValue={this.state.select_value}>
    <option value="1">normal</option>
    <option value="2" >model</option>
</select>
```

**Comment by Aweary** [comment] 2016-08-19 01:44
Hey @oceanpad, can you share small case test case reproducing your issue? You can use [this JSFiddle](https://jsfiddle.net/reactjs/69z2wepo/) as a starting point.

I'm afraid the code you provided isn't enough to help you, nor is it valid JavaScript, so more details would be great.

**Comment by muxahuk** [comment] 2016-08-20 09:55
well, first of all u have typing error.. `this.state = { select_value="" };` it should be `select_value:""` with `:` not `=`...

**Comment by oceanpad** [comment] 2016-08-22 11:51
@Aweary Thankyou so much, this is my code, I want to show model option as default option, but when it init , it show none.
What's the reason?

**Comment by oceanpad** [comment] 2016-08-22 11:52
@muxahuk Thank you so much, I found that this is a very basic problem, I had resolve it .

**Comment by muxahuk** [comment] 2016-08-22 11:59
I don't get it.. u have `select_value` equal to '' ( empty string ) and when u render u pass empty string to defaultValue.. what do u expect to be set ? Have u tried setting `select_value` to `1` ? does it works ?
Here's a link on how u would bind `<select>` with value from `state`
https://facebook.github.io/react/docs/forms.html#why-select-value

**Comment by Aweary** [comment] 2016-08-22 14:45
Since @oceanpad says his problem is resolved I'm going to close this. It seems like a usage question anyways, which should be directed somewhere else like StackOverflow 👍

**Closed by Aweary** 2016-08-22 14:45 UTC
