### ISSUE TITLE
No error is shown when use a undefined variable

### ISSUE THREAD

**Issue by aight8** [facebook/react#7617] opened 2016-08-30 19:10 UTC
I use react with webpack. When I use a variable in my component like ```{props.children}``` instead of ```this.props.children``` the component fail silently. No errors is shown.

**Comment by gaearon** [comment] 2016-08-30 19:55
React does not swallow your exceptions so it must be something else.
Is there any chance you are using a Promise polyfill that doesn’t log unhandled rejections?

**Comment by gaearon** [comment] 2016-08-30 19:56
By the way we won’t be able to help unless you provide an example reproducing this.

**Comment by nhunzaker** [comment] 2016-08-30 20:09
I've bumped into this in the past when the call-stack from a Promise results in a reflow of React, catching any errors in the render process (to the best of my ability to debug, anyway). Is it possible that this is what is going on?

**Comment by nickhudkins** [comment] 2016-09-16 21:02
@gaearon ran into this today!

``` javascript 
class Baz extends React.Component {
  render() {
    return <div>Baz</div>
  }
}

class Bar extends React.Component {
  render() {
    const { foo } = this.state; // Reference Error!
    return <div>Bar</div>
  }
}

class Foo extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loaded: false
    }
  }
  
  componentDidMount() {
    Promise.resolve()
      .then(() => {
        this.setState({ loaded: true })
      })
      .catch(()=> { 
        console.log('Swallowed!') 
      });
  }
  render() {
    const { loaded } = this.state;
    return loaded ? <Bar /> : <Baz />;
  }
}

ReactDOM.render(<Foo />, document.getElementById('root'));
```

^^ the example here will result in swallowed errors. wrapping the `this.setState({loaded : true })` in a setTimeout results in the error not being swallowed:
``` javascript 
class Baz extends React.Component {
  render() {
    return <div>Baz</div>
  }
}

class Bar extends React.Component {
  render() {
    const { foo } = this.state; // Reference Error!
    return <div>Bar</div>
  }
}

class Foo extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loaded: false
    }
  }
  
  componentDidMount() {
    Promise.resolve()
      .then(() => {
        setTimeout(() => this.setState({ loaded: true }));
      })
      .catch(()=> { 
        console.log('Not Swallowed!') ;
      });
  }
  render() {
    const { loaded } = this.state;
    return loaded ? <Bar /> : <Baz />;
  }
}

ReactDOM.render(<Foo />, document.getElementById('root'));
```

Is this my own ignorance with promises?

**Comment by gaearon** [comment] 2016-09-16 21:10
>^^ the example here will result in swallowed errors

Yes, but you are swallowing them:

```js
      .then(() => {
        this.setState({ loaded: true })
      })
      .catch(()=> { 
        console.log('Swallowed!') 
      });
```

Your `catch()` handler is going to catch **any error thrown in the `then()` chain before it, including the one caused by a `render()` due to a `setState()` call**.

If you don’t want to catch errors resulting from `setState()`, and want to only catch network failures (let’s imagine your `Promise.resolve()` is actually a `fetch()`), you want to use the second `then()` argument instead:

```js
  componentDidMount() {
    Promise.resolve()
      .then(() => {
        this.setState({ loaded: true })
      }, (err) => {
        console.log('An error occurred (but not in setState!)', err);
      });
```

In this case, unless you `catch()` later in the chain, the error in `render()` will be uncaught and, with a good Promise polyfill (or with native Promises in Chrome and maybe other browsers), displayed.

**Comment by gaearon** [comment] 2016-09-16 21:11
I’m closing since there is no reproducible case.
If you can reproduce Reac swallowing an error, please file an issue with a case reproducing it.

**Closed by gaearon** 2016-09-16 21:11 UTC
Labels: Status: Unconfirmed

**Comment by nickhudkins** [comment] 2016-09-16 21:25
Awesome. Thank you! I hadn't considered the fact that the setState resulted
in the throwing and therefore the catch handling it. I think you even
tweeted about this recently :(.

**Comment by gaearon** [comment] 2016-09-16 21:58
It’s hard to remember until you spend a few hours debugging it. Don’t worry 😉

**Comment by capaj** [comment] 2016-11-16 15:10
@gaearon 

> Your catch() handler is going to catch any error thrown in the then() chain before it, including the one caused by a render() due to a setState() call.

I though setState was asycnhronous? How could it work like that?

**Comment by gaearon** [comment] 2016-11-16 15:30
It will likely be almost-always async in the future but there are cases when it can't be (e.g. inside an input event handler).

**Comment by gaearon** [comment] 2017-07-27 10:36
A small update on this. We just released [React 16 beta](https://github.com/facebook/react/issues/10294) which shouldn’t emit cryptic errors like this one. Even if the application code swallows an error, React 16 will still print it to the console. It might be too early for you to try React 16 (since ecosystem is still preparing for it), but this error should never occur in the future after you switch to it.

**Comment by Kayron013** [comment] 2019-10-22 15:10
> A small update on this. We just released [React 16 beta](https://github.com/facebook/react/issues/10294) which shouldn’t emit cryptic errors like this one. Even if the application code swallows an error, React 16 will still print it to the console. It might be too early for you to try React 16 (since ecosystem is still preparing for it), but this error should never occur in the future after you switch to it.

I am using React v16.9.0, yet I still came across this error. I was, however, able to find the problem, which was not caused by me catching any errors.
