### ISSUE TITLE
Error event fired twice when in development mode

### ISSUE THREAD

**Issue by marcellomontemagno** [facebook/react#12093] opened 2018-01-25 17:01 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Error event fired twice when in development mode.

In the example you can see that '>>>>>>error' is logged twice while I only expect to see it once.

Note: this issue doesn't happen with the production version of react

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

- codepen demo:
https://codepen.io/anon/pen/ppXZXP?editors=0011

static html reproducing the problem:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World</title>
    <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/babel">

      function handleErr(event){
        console.log('>>>>>>error')
      }

      window.addEventListener('error', handleErr);

      function onClick (e) {
        e.stopPropagation()
        e.preventDefault()
        throw new Error('-------------');
      }

      ReactDOM.render(
        <button onClick={onClick}>button</button>,
        document.getElementById('root')
      );

    </script>
  </body>
</html>
```

**What is the expected behavior?**

I expect to see '>>>>>>error' logged once

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

reproduced on:

react v16.2.0
Chrome 63.0.3239.132
OSX 10.10.5

**Comment by aulisius** [comment] 2018-01-26 09:42
I think it has something to do with [invokeGuardedCallback](https://github.com/facebook/react/blob/master/packages/shared/invokeGuardedCallback.js#L34). in _DEV_ mode. They dispatch a fake event to preserver dev-tool behaviour. This comment block would give a better idea

```js
// To preserve the expected "Pause on exceptions" behavior, we don't use a
// try-catch in DEV. Instead, we synchronously dispatch a fake event to a fake
// DOM node, and call the user-provided callback from inside an event handler
// for that fake event. If the callback throws, the error is "captured" using
// a global event handler. But because the error happens in a different
// event loop context, it does not interrupt the normal program flow.
// Effectively, this gives us try-catch behavior without actually using
// try-catch. Neat!
```

This is more like the intended behavior and not a bug.

**Comment by marcellomontemagno** [comment] 2018-01-26 11:21
Hey @aulisius thanks for your reply :)

I understand the intention of preserving the expected "Pause on exceptions" behaviour of the dev tools, I doubt the react developers expect an user defined error event listener to be invoked twice with the same instance of the error though.

I'm not even sure `invokeGuardedCallback` is the culprit here (the user callbacks are executed in a next message of the event loop but I don't see where the extra throw is happening), I'll try to dig better in the react code asap.

As an extra info I've also noticed that 'error' events are fired twice while 'unhandledrejection' events behave correctly

**Comment by gaearon** [comment] 2018-01-28 13:30
I think this is a duplicate of https://github.com/facebook/react/issues/10474.

**Closed by gaearon** 2018-01-28 13:30 UTC
