### ISSUE TITLE
onMouseEnter triggered on children in React 16

### ISSUE THREAD

**Issue by dbismut** [facebook/react#11152] opened 2017-10-09 09:57 UTC
Hi, I'm having an issue with `onMouseEnter` being triggered on children of a component. *It only occurs with React 16*.

I've created a [CodePen that shows the issue](https://codepen.io/testprofile75/pen/VMXXdb).

Simplified structure is as below:
```
           <Card/> :
–––––––––––––––––––––––––––––
|                            |
|          <Cover/>          |
|                            |
------------------------------
|                            |
|    <div class="text" />    |
|                            |
–––––––––––––––––––––––––––––
```

`<Card />` is a component that needs to capture `onMouseMove` events (and trigger a `render`) and `<Cover/>` is a simple component that waits for an image (passed as a `prop`) to be loaded before displaying it (using `onload` on an `Image` created in the `constructor`).

If you open the console, you'll see that `onMouseEnter` is triggered when hovering `<Card />` (normal behavior), but also when hovering the `.text` div (which is not supposed to happen).

If you remove the whole `onload` logic from the `<Cover/>` element, then `onMouseEnter` works as intended.

It's possible that I'm coding this in a way that isn't appropriate, but it does look like a bug anyway :)

**Comment by gaearon** [comment] 2017-10-09 13:45
This sounds like a duplicate of https://github.com/facebook/react/issues/10906.

**Comment by dbismut** [comment] 2017-10-09 13:53
Thanks Dan. I had seen the issue but the jsFiddle example seemed like a different cause.

**Comment by gaearon** [comment] 2017-10-09 16:02
Let’s keep it open then. I have a suspicion they might be related, but I could be wrong.

**Comment by gaearon** [comment] 2017-10-09 19:30
Fixed by https://github.com/facebook/react/pull/11164.

**Closed by gaearon** 2017-10-09 19:30 UTC
Labels: Component: DOM, Type: Bug

**Comment by gaearon** [comment] 2017-11-03 00:50
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.

**Comment by gaearon** [comment] 2017-11-03 00:50
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.

**Comment by dbismut** [comment] 2017-11-03 08:18
Hey @gaearon this works now :) Thanks!
