### ISSUE TITLE
Bug: using google translate on a page then removing the translated component generates an error

### ISSUE THREAD

**Issue by WesleyKlop** [facebook/react#26048] opened 2023-01-25 16:51 UTC
React version: 18.2.0

## Steps To Reproduce

1. Create a component that renders `children` directly or wrapped by a fragment
2. Programatically or using google in-page translate clear the component
    <img width="612" alt="image" src="https://user-images.githubusercontent.com/12008100/214622717-f3d871cd-7cb4-483b-9b6d-e4b7e9e6fdf8.png">
3. Trigger a re-render that removes the component
4. Observe error 
    <img width="1049" alt="image" src="https://user-images.githubusercontent.com/12008100/214622966-f547fe7e-e132-4eaa-8b9d-edb08f3063dd.png">
    `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

There is a better title for this bug report I just can't think of it yet 😅 

Link to code example: https://codesandbox.io/s/determined-antonelli-7swu6w?file=/src/App.js

## The current behavior

The page turns blank because the element to remove could not be found

## The expected behavior

Either ignore the element and try to continue, or re-render the first parent node that _does_ exist

**Comment by RiverTwilight** [comment] 2023-01-26 09:27
In this case, we can solve the problem by simply remove Comp component and directly place text, or add at least one wrapper for children.

Why do you need a component which returns original text node? If you need process text data you should use a function instead of a component. React helps to solve UI problem. I think it's a misusing of ref and component here.

**Comment by eps1lon** [comment] 2023-01-30 07:39
Duplicate of https://github.com/facebook/react/issues/11538. See https://github.com/facebook/react/issues/11538#issuecomment-417504600 for the latest update.

**Closed by eps1lon** 2023-01-30 07:39 UTC
Labels: Status: Unconfirmed
