### ISSUE TITLE
ReactDOM.render returns null for pure functions

### ISSUE THREAD

**Issue by thejameskyle** [facebook/react#5455] opened 2015-11-12 06:15 UTC
I was thrown off by this behavior, figured it warranted an issue.

```js
function Component() {
  return <div/>;
}

var result = ReactDOM.render(<Component/>, el);

result === null;
```

I was attempting to `ReactDOM.findDOMNode` the result of `ReactDOM.render`.

**Comment by jimfb** [comment] 2015-11-12 06:22
Documented in [several places](https://facebook.github.io/react/docs/top-level-api.html#reactdom.render):
 > Render a ReactElement into the DOM in the supplied container and return a reference to the component (or returns null for stateless components).

As well as mentioned in big [red boxes](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions):
> NOTE:
Because stateless functions don't have a backing instance, you can't attach a ref to a stateless function component. Normally this isn't an issue, since stateless functions do not provide an imperative API. Without an imperative API, there isn't much you could do with an instance anyway. However, if a user wants to find the DOM node of a stateless function component, they must wrap the component in a stateful component (eg. ES6 class component) and attach the ref to the stateful wrapper component.

Duplicate of https://github.com/facebook/react/issues/4936

**Closed by jimfb** 2015-11-12 06:22 UTC
