### ISSUE TITLE
random svg text tspan not shows properly 

### ISSUE THREAD

**Issue by ankitpatial** [facebook/react#4376] opened 2015-07-14 15:37 UTC
I have a app that require sag text with wrapping and length editing functionality, i am done with computing the text wrap and text editing functionality, but the thing i am stuck on is "when i edit element width i.e  decrease element width to make textin 2 lines, 1st lines show ok but 2nd is not, but if i refresh page it looks ok. when i stretch element it show every thing ok i.e. text from 2 to 1 line.

It looks like increase in no of rows (tspans) is not working while decrease in tspans reflects ok.I am having key assigned to each element. there is no warning by react in browser console.

Any idea what can be the issue ?

For me it seems like react is not rendering new tspan properly, i can see tspan properly in dom.

**Comment by ankitpatial** [comment] 2015-07-15 13:37
seems like its a similar case as mentioned in #807

**Comment by ankitpatial** [comment] 2015-07-15 13:45
anyone, any idea it will be fixed ?
will react 0.14 will fix it ?

**Comment by zpao** [comment] 2015-09-23 07:05
dupe of #3972 which is fixed in 0.14

**Closed by zpao** 2015-09-23 07:05 UTC
