### ISSUE TITLE
findDOMNode throws inside Suspense with componentDidUpdate

### ISSUE THREAD

**Issue by zombieJ** [facebook/react#15857] opened 2019-06-11 03:45 UTC
### It is a...

🐞 BUG

### What is the current behavior?
<img width="953" alt="屏幕快照 2019-06-11 上午11 32 42" src="https://user-images.githubusercontent.com/5378891/59242037-a410c680-8c3c-11e9-8b59-1faf8079fb00.png">

### Reproduce

https://codesandbox.io/s/antd-reproduction-template-7jmkr

1. Quick click `Page 1` button.
2. Then, quick click `Page 2` button.

### What is the expected behavior?

`findDOMNode` should work in Suspense

### Others

related issue: #14188

**Comment by zombieJ** [comment] 2019-06-12 15:22
ping @jquense @gaearon @acdlite

**Comment by eps1lon** [comment] 2019-06-19 10:47
This is likely a duplicate of #14188 which is fixed on master but not released yet.

**Comment by xiaoshuangLi** [comment] 2019-08-26 08:29
I upgrade to react@16.9.0 and react-dom@16.9.0, but still get this error.Does upgrading version work on you?? @zombieJ 

![image](https://user-images.githubusercontent.com/12060054/63676726-2e210200-c81e-11e9-9d94-bff11f8cf631.png)

**Comment by gaearon** [comment] 2019-08-26 09:41
The original example posted by @zombieJ doesn't reproduce in 16.9 anymore.
If you have a similar problem please file a new issue with reproducing code.

**Closed by gaearon** 2019-08-26 09:41 UTC

**Comment by xiaoshuangLi** [comment] 2019-08-27 03:38
> @zombieJ. Hi, I upgrade to react@16.9.0 and react-dom@16.9.0, but still get this error.Does upgrading version work on you??
> 
> rc-tooltip@3.7.3
> rc-trigger@2.6.5
> rc-align@2.4.5
> 
> ![image](https://user-images.githubusercontent.com/12060054/63676726-2e210200-c81e-11e9-9d94-bff11f8cf631.png)

It's my fault, forget to change @hot-loader/react-dom@16.8.6, Sorry..
