### ISSUE TITLE
Bug in controlled input of type number

### ISSUE THREAD

**Issue by jfremy** [facebook/react#6900] opened 2016-05-27 02:01 UTC
There seems to be a bug in the way React interfaces with controlled inputs of type number

If the input contains an invalid number (let's say --2 or 2++), then trying to clear the input value by setting it to an empty string does nothing.

You can check an example to reproduce there: https://jsfiddle.net/96bnn12r/2/ 
The onChange handler will set the controlled value to the value returned by ev.target.value.
In the case of an invalid value, the input returns an empty string (as per html spec https://html.spec.whatwg.org/multipage/forms.html#states-of-the-type-attribute 4.10.5.1.12) so this should actually clear the input but the invalid input stays.

When setting the input value to an empty string after entering an invalid value, it should clear the input content not keep the invalid value.

Seen in React 0.14.8, 15.0.1, 15.1.0 on OSX Chrome v50, Firefox 46.0.1

**Comment by jimfb** [comment] 2016-05-27 02:12
Duplicate of https://github.com/facebook/react/issues/6556, related to https://github.com/facebook/react/issues/6368

**Closed by jimfb** 2016-05-27 02:12 UTC
