### ISSUE TITLE
Error: "can't access property "isCollapsed", child is undefined"

### ISSUE THREAD

**Issue by Jurrevandenberg** [facebook/react#21321] opened 2021-04-20 15:00 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.12.3-8f202a7c8d

Component stack: List@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:23907:30
div
AutoSizer@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:3140:19
div
div
Tree_Tree@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:29857:47
div
div
OwnersListContextController@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:29005:37
SettingsModalContextController@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:29446:40
Components_Components@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:37593:52
ErrorBoundary_ErrorBoundary@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:33093:5
PortaledContent@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:33172:34
div
div
ProfilerContextController@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:37211:35
TreeContextController@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:25674:31
SettingsContextController@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:26288:35
ModalDialogContextController@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:33315:38
DevTools_DevTools@moz-extension://d7e5d713-e002-4ecc-9f7e-2f81502878f8/build/main.js:40586:27

**Comment by charlie632** [comment] 2021-04-20 18:46
?

**Comment by bvaughn** [comment] 2021-04-20 19:20
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-05-03 13:52
Closing because there isn't enough info.

**Closed by bvaughn** 2021-05-03 13:52 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
