### ISSUE TITLE
Bug: componentDidMount fires before lazy-loaded components are mounted

### ISSUE THREAD

**Issue by logan2z** [facebook/react#18139] opened 2020-02-26 18:50 UTC
In a component with child components that are lazy loaded using React.lazy, the component's componendDidMount() callback is fired before the lazy-loaded children are loaded/mounted.  This makes it very difficult to perform logic on child components (eg. calling a component method via a ref, using ReactDOM.findDOMNode on the children, etc.) in componentDidMount.  This all obviously works fine with components that are synchronously loaded but makes it very difficult to migrate an existing React application using synchronously loaded components to one that leverages React.lazy.  

This behavior is observed with React version 16.12.

The issue can be illustrated with code like this:

```
import React, {Suspense} from 'react';
import ReactDOM from 'react-dom';

const SomeComponent = React.lazy(() => import("./SomeComponent"));

class Comp extends React.Component {
     constructor() {
           super();
           this.compRef = React.createRef();
     }

     componentDidMount() {
           this.compRef.current.blur();
     }

     render() {
         return 
             <Suspense fallback={<div>Loading...</div>} >
                  <SomeComponent ref={this.compRef} />
             </Suspense>
       }   
}

ReactDOM.render(<Comp/>, document.createElement("div"))
```

## The current behavior
The current behavior is that the componentDidMount callback is fired before the lazy loaded component is rendered/mounted so using compRef fails.

## The expected behavior
The componentDidMount method should only fire once all of the child components have loaded/mounted.  Or, there should be some other way to consolidate code that performs operations on asynchronously loaded/rendered components.

**Comment by kunukn** [comment] 2020-02-27 08:28
Maybe do this instead?
The callback is executed when the lazy SomeComponent is mounted.

```jsx
const SomeComponent = React.lazy(() => import("./SomeComponent"));

class Comp extends React.Component {
  someComponentMounted(el) {
    el.blur();
  }

  render() {
    return (
      <Suspense fallback={<div>Loading...</div>}>
        <SomeComponent
          ref={el => {
            this.someComponentMounted(el);
          }}
        />
      </Suspense>
    );
  }
}

```

**Comment by LXSMNSYC** [comment] 2020-02-27 09:17
Not really a bug but it is always implied that the suspended component will always fail first due to asynchronicity and so it will always render the fallback, hence the render method is successful then the `componentDidMount` will always call. This is certainly the intended behavior.

**Comment by logan2z** [comment] 2020-02-27 18:12
I understand that callback refs can be used to execute code when the referenced component is mounted.  But if a project has a lot of existing code in componentDidMount that operates on several components in the tree, it can be awkward to have to split it into a series of independent callbacks - especially if some consolidated logic is required.  I think it would make it much easier for existing projects to introduce lazy loading of components if there was a way to execute some code after all of the lazy loaded components are loaded/mounted.

**Comment by logan2z** [comment] 2020-02-27 18:47
> Maybe do this instead?
> The callback is executed when the lazy SomeComponent is mounted.
> 
> ```js-jsx
> const SomeComponent = React.lazy(() => import("./SomeComponent"));
> 
> class Comp extends React.Component {
>   someComponentMounted(el) {
>     el.blur();
>   }
> 
>   render() {
>     return (
>       <Suspense fallback={<div>Loading...</div>}>
>         <SomeComponent
>           ref={el => {
>             this.someComponentMounted(el);
>           }}
>         />
>       </Suspense>
>     );
>   }
> }
> ```

Thanks.  I understand that I could use a callback ref to get a reference to the component once it mounts.  But there are cases where there is a significant amount of logic in componentDidMount that spans child components and it would be very awkward to try and split it up into separate callbacks.  

I think that providing some way to determine when all of the child components are finally mounted would make it much easier for existing code to introduce the use of lazy loaded components.

**Comment by logan2z** [comment] 2020-02-27 18:53
> Not really a bug but it is always implied that the suspended component will always fail first due to asynchronicity and so `Suspense` will always render the fallback, hence the render method is successful (since the pending/failing component is handled gracefully) then the `componentDidMount` is called. This is certainly the intended behavior.

Logically I understand the design and that - technically speaking - one could consider the Suspense component mounted once the fallback is rendered, so there is some justification for calling componentDidMount.  But previously, componentDidMount wasn't called until all of the child components were mounted, not just the root component.  So it seems the semantics of componentDidMount changed in the face of lazy loaded components.  And if that's a design choice made by the React team then that's fine.  But I still think there should be some way for a component to know when it's render() method has successfully rendered _all_ child components so that it can perform any necessary logic on those child components in one place.  

Clearly I don't know as much about the design of React as its implementors, but it seems as though it would have been simple to just leave the semantics of componentDidMount alone so that it is only called once all components are mounted - whether or not they are lazy.   If any component-specific logic was to be executed, it could still be encapsulated using a callback ref. 

I only see upside in leaving componentDidMount semantics as they were before the introduction of React.lazy/Suspense.  It would certainly make adoption in existing code much easier.

**Comment by tomasyaya** [comment] 2020-02-27 18:55
@logan2z  and componentDidUpdate?

**Comment by LXSMNSYC** [comment] 2020-02-27 20:59
Well the thing is, React couldn't really poll for these components to be ready, and so they only commit if all of the components are have committed their updates. If they were and if `componentDidMount` awaits the suspending component, then the whole app would be suspended as well (given that at least one single component is being awaited to be resolved.), you can't really have a "synchronized" way of accessing the host instance (the DOM instance) on commit phase if the component is still loading.

I would really suggest the `ref` callback for capturing host instances.

**Comment by bvaughn** [comment] 2020-03-03 23:49
The described behavior is indeed working as designed. `componentDidMount` is called when a **component mounts**, regardless of what/when its descendants mount

> I only see upside in **leaving componentDidMount semantics as they were before** the introduction of React.lazy/Suspense. It would certainly make adoption of React.lazy in existing code much easier.

This is what we did. The previous solution for lazy-loading anything (data, component, whatever) was to **first mount** (i.e. `componentDidMount`), then fetch, then update state (to re-render) when the fetch completed.

The specific solution on how to check when your lazy-loaded data/dependency finishes loading probably depends on your application code. A ref callback function seems like one reasonable way of doing this.

**Comment by gaearon** [comment] 2020-03-16 20:57
Yeah there's not much we can do here. If we did like you described (e.g. wait for all child components) then this would cut out a huge amount of use cases — e.g. focusing a text field like

```js
<>
  <input />
  <SomethingThatContainsLazyCodeDeepInside />
</>
```

and it would always be dangerous to add `lazy` deeply because that would break assumptions.

**In general**, `findDOMNode` is not a recommended pattern anyway — whether in `componentDidMount` or anywhere else. This is precisely because you won't get notified about what arbitrary children do. You can use callback refs for this instead.

**Closed by gaearon** 2020-03-16 20:57 UTC
Labels: Status: Unconfirmed
