### ISSUE TITLE
The automatic bailout doesn't take context into account

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#4219] opened 2015-06-25 03:31 UTC
See https://twitter.com/ryanflorence/status/613905590176186368

And the following thread.

Quick fix?

**Comment by jimfb** [comment] 2015-06-25 03:36
Is this different from https://github.com/facebook/react/issues/2517 ?

Workaround is to call forceUpdate() after updating a context variable, right?

**Comment by ryanflorence** [comment] 2015-06-25 03:49
see #4218

**Comment by spicyj** [comment] 2015-06-25 03:50
Dupe of #4218. ;)

**Closed by spicyj** 2015-06-25 03:50 UTC
