### ISSUE TITLE
[DevTools Bug]: StrictMode not shown in component tree

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/react#21974] opened 2021-07-27 21:02 UTC
### Website or app

https://codesandbox.io/s/objective-lehmann-u2jn4?file=/src/App.js

### Repro steps

- Open React devtools in codesandbox
- See that there's no StrictMode in the tree any more

<img width="1463" alt="Screen Shot 2021-07-27 at 4 56 17 PM" src="https://user-images.githubusercontent.com/2440089/127226919-bad27090-db61-45eb-8133-ed701e411d3b.png">

### How often does this bug happen?

Every time

**Comment by rickhanlonii** [comment] 2021-07-27 21:04
Verified that the StrictMode component is being rendered to rule out any weirdness:

<img width="1465" alt="Screen Shot 2021-07-27 at 5 04 17 PM" src="https://user-images.githubusercontent.com/2440089/127227263-14ac2b72-be09-4ad6-99b2-8ba8e49e5d49.png">

**Comment by bvaughn** [comment] 2021-08-30 19:39
IMO this is not a bug. It's an intentional decision, since `<StrictMode>` wrapper components are only one way to opt an app into strict behavior.

We have another task to track making it clear which subtrees are strict or not (82) as well as one for allowing devs to temporarily override strict behavior for an app/tree (#21367).

I'm going to close this task because I think it suggests work like #22201 which is only a partial solution. I'd rather approach something that addresses all of the above concerns.

Thanks! 🙇🏼

**Closed by bvaughn** 2021-08-30 19:39 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools

**Comment by bvaughn** [comment] 2021-12-08 21:23
Related UI investigation: https://github.com/facebook/react/pull/22886
