### ISSUE TITLE
Error: "Could not find commit data for root "957" and commit 2"

### ISSUE THREAD

**Issue by rohanvachheta** [facebook/react#18804] opened 2020-05-02 17:13 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:173658)
    at p (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:359968)
    at Zc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:360183)
    at ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59620)
    at nl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:69923)
    at Ll (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:110996)
    at qc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102381)
    at Hc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102306)
    at Vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102171)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:98781)

Component stack: in Zc
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by 49-22** [comment] 2020-05-04 02:22
It would be better if you provide more details on the question.

**Comment by bvaughn** [comment] 2020-05-07 23:41
This looks like a duplicate of #18010 so I'm going to close it.

It's possible that PR #18862 fixes this issue, but that remains to be seen. If you can reproduce this issue, we would greatly appreciate if you left a comment with repro instructions so we could test that PR and see!

**Closed by bvaughn** 2020-05-07 23:41 UTC
