### ISSUE TITLE
onTouchStart event has null touches

### ISSUE THREAD

**Issue by maxlapshin** [facebook/react#5092] opened 2015-10-08 14:28 UTC
event that comes to onTouchStart handler has null field touches, but its  event.nativeEvent.touches has this field.

Is it a bug or a design feature?

**Comment by jimfb** [comment] 2015-10-08 15:42
Sounds like a valid issue; I don't think that was intended.

**Comment by maxlapshin** [comment] 2015-10-08 15:59
Should I try to make pull request?

**Comment by jimfb** [comment] 2015-10-08 16:03
Yes, a pull request would be very much appreciated :).

**Comment by Jyrno42** [comment] 2015-10-09 10:49
Tried to repro but could not. Any more context on this?

see: http://codepen.io/anon/pen/RWgMgX

(Chrome on android / Ios Chrome / Ios Safari / Chrome mobile emulation)

**Comment by jimfb** [comment] 2015-10-09 10:54
@maxlapshin What browser/device are you using?  Also, can you provide a simple test case / jsfiddle?

**Comment by maxlapshin** [comment] 2015-10-09 10:56
iPad safari.

Will reproduce it and give you better info about it.

**Comment by spicyj** [comment] 2015-10-09 15:58
Closing until then – if you repro feel free to comment here and we can reopen.

**Closed by spicyj** 2015-10-09 15:58 UTC
Labels: Component: Events, good first bug
