### ISSUE TITLE
React devtools 15.1.0 ctor timer error

### ISSUE THREAD

**Issue by jaylaw81** [facebook/react#6842] opened 2016-05-23 13:26 UTC
bug

Warning displayed in console about internal error of React performance measurement code.

```js
import React from 'react';
import { render } from 'react-dom';
import Perf from 'react-addons-perf';
import { browserHistory, Router } from 'react-router';

import routes from './routes';
import persist from 'altFlux/persist';

persist('docs');

const target = document.getElementById('app');

Perf.start();

render(
  <Router
    routes={routes}
    history={browserHistory}
  />,
  target,
  () => {
    Perf.stop();
    Perf.printWasted();
  }
);
```
![screen shot 2016-05-23 at 9 21 08 am](https://cloud.githubusercontent.com/assets/91464/15472297/5e440d48-20c8-11e6-99d7-363f6d1bdcce.png)

15.1.0
Google Chrome

**Comment by gaearon** [comment] 2016-05-23 16:37
Can you please provide a complete runnable example that reproduces this?

**Comment by jaylaw81** [comment] 2016-05-23 17:41
@gaearon https://github.com/jaylaw81/sdp-bugfix

private repo

**Comment by gaearon** [comment] 2016-05-23 18:21
Thanks, this makes sense. For the context, I forgot about the portal use case where people `ReactDOM.render` again right inside a lifecycle method, thus making timers stack. We should probably keep the warning but push any timers running when a flush starts onto the stack, and pop them when the flush ends.

**Comment by sassanh** [comment] 2016-07-18 18:29
Is it considered fixed? I'm using 15.2.1.

https://www.dropbox.com/s/dqcwnukwokwubsf/Screenshot%202016-07-18%2022.57.18.png?dl=0

This warning repeated 484 times on console and then:

https://www.dropbox.com/s/3ip8vqros8biz8b/Screenshot%202016-07-18%2022.58.08.png?dl=0

this error repeated 484 times on console and page failed to render.

**Comment by sassanh** [comment] 2016-07-18 18:38
The problem was that I was using an undefined variable but the error/warning messages were completely misleading. After defining the variable it works without any warnings nor errors.

**Comment by gaearon** [comment] 2016-07-18 18:40
Can you please provide a sample reproducing this?

**Comment by sassanh** [comment] 2016-07-18 18:46
Thanks for quick reply. I need to create one as the code is not open source, I'll do it asap.

**Comment by gaearon** [comment] 2016-07-18 19:00
Thanks.

I’ll reopen so this is on my our radar. To be clear, this is likely not a bug in React (the actual error probably was in the component, and it got React into an inconsistent state). But we should recover from such errors, or at least not to spam you with warnings.

**Comment by sassanh** [comment] 2016-07-18 19:04
Yeah I understand it's not a "bug" in react that produced the problem but as you said I think it could have handled better so that the developer could find the issue easier. Spamming warnings/errors and making the tab unresponsive (I couldn't even refresh or close the chrome tab and I had to kill it.) isn't nice.

**Comment by gaearon** [comment] 2016-07-18 19:11
Yea, totally. At the very least we should make the warning warn at most once. This is enough for us to catch issues in tests but solves the spamming problem. The relevant code is in `ReactDebugTool`. Would you like to send a PR to fix it? You could keep a bool `hasWarned` and use that flag to decide whether to log warning or ignore it silently.

**Comment by sassanh** [comment] 2016-07-18 19:12
Sure, I try to manage to do it at the weekend.

**Comment by sassanh** [comment] 2016-07-19 11:24
Even though https://github.com/facebook/react/pull/7299 manages to reduce warnings, we still have problem with 484 errors and chrome tab getting unresponsive for around a minute (user can only kill it).

**Comment by gaearon** [comment] 2016-07-19 11:34
What errors are you referring to?

**Comment by sassanh** [comment] 2016-07-19 12:27
https://www.dropbox.com/s/3ip8vqros8biz8b/Screenshot%202016-07-18%2022.58.08.png?dl=0

**Comment by gaearon** [comment] 2016-07-19 13:13
Those errors appear unrelated to the issue in this thread. In general, we don’t currently support gracefully recovering from errors thrown in components. This may come later (#2461) but it’s not there right now. So yes, you’ll see many errors thrown. We recommend scrolling up to the first one and fixing it (it usually causes all the others).

**Comment by sassanh** [comment] 2016-07-19 13:48
I see, thanks for info. So I guess we can close this.

**Closed** 2016-07-19 18:43 UTC
Labels: Component: Addons / Perf, Type: Bug
