### ISSUE TITLE
Error: "Cannot read property 'concat' of undefined"

### ISSUE THREAD

**Issue by RealDrewKlayman** [facebook/react#20296] opened 2020-11-19 03:32 UTC
Describe what you were doing when the bug occurred:
1.  Ran Profiler
2. (Was On Flamegraph)

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.0-11a2ae3a0d

Call stack: at updateTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19691:53)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19563:26)
    at ProfilingCache_ProfilingCache.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20104:11)
    at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34150:33)
    at Fh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:12806:7)
    at ni (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13448:7)
    at jk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16065:86)
    at ik (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15450:11)
    at hk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15442:23)
    at Zj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15426:5)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34133:50)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28195:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35761:50)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29208:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29325:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32923:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24311:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24800:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29393:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36196:3)

**Comment by eps1lon** [comment] 2020-11-19 09:58
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-11-19 19:28
Likely related to issue #20173 (which also lacks a repro case)

**Comment by bvaughn** [comment] 2020-11-20 17:34
I think the underlying cause of this is the same as #16493 which I now have a repro for.

**Comment by RealDrewKlayman** [comment] 2020-11-20 20:21
With that in mind do I still need to repo this? 

I'm having troubles figuring out which part of our code is causing this issue..

**Comment by bvaughn** [comment] 2020-11-20 20:59
The more repros the better, since there could be more than one root bug that has a similar error message. :smile: But if you can't, I'll go with what I have

**Comment by sibelius** [comment] 2020-11-23 14:17
is this related to react 17?

**Comment by RealDrewKlayman** [comment] 2020-11-24 18:18
I am on React 17, but it works up until a certain point when clicking through the graph. I'm doing some more testing to figure out exactly where it occurs.

**Comment by bvaughn** [comment] 2020-12-01 18:45
Quick question for folks who are seeing this bug in your app: Are you using the `React.Lazy` component?

**Comment by RealDrewKlayman** [comment] 2020-12-01 23:57
> Quick question for folks who are seeing this bug in your app: Are you using the `React.Lazy` component?

Yes, I am.

**Comment by TkDodo** [comment] 2020-12-02 20:29
Yes, I also got the bug right now, React 17 and `React.Lazy` is also involved in case that helps :)

**Comment by bvaughn** [comment] 2020-12-03 14:52
@RealDrewKlayman @TkDodo Can either of you share your repro with me? The one I have is sporadic- but I think I'm zeroing in on maybe fixing this. More data would be heopful

**Comment by bvaughn** [comment] 2020-12-04 18:01
If you can repro this yourself, would any of you be willing to try this build of DevTools and let me know if it fixes the issue?

https://github.com/facebook/react/files/5644517/ReactDevTools.zip

I have reason to suspect that *maybe* I've fixed at least one case of this already (recently, unreleased) and I'm wondering if that's why I'm having trouble reproing.

**Comment by bvaughn** [comment] 2020-12-04 22:06
I believe this issue was fixed via PR #20362. It has now been published as v4.10.1 and should be available shortly.

Please let me know if you still see the issue after installing that version and I can re-open and investigate further.

**Closed by bvaughn** 2020-12-04 22:06 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information

**Comment by RealDrewKlayman** [comment] 2020-12-05 01:42
Still waiting on the new version to show up and then I'll test it @bvaughn .

**Comment by bvaughn** [comment] 2020-12-05 15:08
Thanks!

Takes Chrome a couple of days sometimes :( Firefox and Edge are pretty fast
