### ISSUE TITLE
Error: "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by CheMingjun** [facebook/react#18442] opened 2020-03-31 14:24 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.5.0-355970aa4

Call stack: at n.get (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:173031)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159357)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159939)

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by gaearon** [comment] 2020-03-31 14:29
>Describe what you were doing when the bug occurred:

I don't see a description.

**Comment by CheMingjun** [comment] 2020-04-01 02:57
1.  many functional components in the page;
2. open "Components" tab in chrome dev tools,then click the component in a random way;
4. crash occured.

**Comment by bvaughn** [comment] 2020-04-01 16:26
@CheMingjun I don't think this is going to be sufficient for us to reproduce the bug.

Can you share a repro with us by chance? (Which website were you clicking around on?)

**Comment by bvaughn** [comment] 2020-04-09 22:25
Closing due to lack of repro info

**Closed by bvaughn** 2020-04-09 22:25 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
