### ISSUE TITLE
ReactCSSTransitionGroup warns when removed while transition in progress

### ISSUE THREAD

**Issue by kassens** [facebook/react#3623] opened 2015-04-08 19:05 UTC
The [`noEventTimeout` timer](https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/addons/transitions/ReactCSSTransitionGroupChild.js#L80) is not cleared when a child is unmounted while a transition is in progress. This causes a false positive warning.

**Comment by sejoker** [comment] 2015-04-27 21:56
@kassens  Could you help me reproduce a bug? I prepared [example](https://jsfiddle.net/sejoker/j9p8xuq6/3/). On click of any item from the list I start the animation for 6 seconds, additionally I output debug info into console. It clearly shows that also warning takes place (5 seconds timeout violated) `componentWillUnmount`  is triggered after `endListener` function executes. It seems to me that a child cannot be unmounted while a transition is in progress (only after) by design. Please correct me if I am wrong.

**Comment by cpb** [comment] 2016-06-01 08:58
I've been giving this a look, mostly in the commit and pull request history. Seems that last spring and summer @sejoker gave this an earnest shot. However, #3745 was never merged and ultimately closed for lacking tests and/or reproducibility.

However, a couple other efforts contributed to resolving this even just a couple days after @sejoker gave up. In contributing to #1326, @djrodgerspryor changed `ReactCSSTransitionGroup` to require timeouts. This had the 'side effect' of [removing the  code path](https://github.com/facebook/react/pull/4561/files#diff-a0fc1c23053b3bb4b32e9df5735574e1L93) that needed the aforementioned `noEventTimout` timer.

One of @zpao's concerns in #3745 was a lack of tests. While contributing fixes to #4876 @zjjw added [additional timeout cleaning code in `ReactCSSTransitionGroupChild`](https://github.com/facebook/react/pull/5391/files#diff-a0fc1c23053b3bb4b32e9df5735574e1R137) with [test coverage](https://github.com/facebook/react/pull/5391/files#diff-53f26523bfa9afbac5b9c0ae2b8bfe9fR273).

So, in the interests of issue gardening I humbly recommend that this issue be closed. :-)

#reactEurope-hackathon

**Comment by cpb** [comment] 2016-06-01 09:59
@vjeux care to close this one?

**Comment by steveluscher** [comment] 2016-06-01 18:20
This looks lovely to me. Nicely swept timeouts, thanks to #4876.

![cleaning-company-broom](https://cloud.githubusercontent.com/assets/13243/15720799/c77638a8-27ea-11e6-8f1a-f9520ee0a1c3.gif)

**Closed by steveluscher** 2016-06-01 18:20 UTC
Labels: Component: Addons / TransitionGroup, good first bug
