### ISSUE TITLE
Devtools: broken indentation in the components tree

### ISSUE THREAD

**Issue by keann** [facebook/react#17405] opened 2019-11-20 11:04 UTC
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
Items in the components' tree are rendered as a plain list

![Screenshot 2019-11-20 at 13 58 42](https://user-images.githubusercontent.com/12268898/69233511-1697b200-0b9e-11ea-93d4-e1484195b295.png)
![Screenshot 2019-11-20 at 14 05 35](https://user-images.githubusercontent.com/12268898/69233941-fa484500-0b9e-11ea-976d-35b65a0f9761.png)

**What is the expected behavior?**
Each item has an indentation according to its depth in the tree

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React Developer Tools @ 4.2.0 (Chrome Extension)
Google Chrome @ 78.0.3904.108

**Comment by keann** [comment] 2019-11-20 15:18
It appears that the items are somehow strangely aligned on the right side. Thus a very long string (in my case — a component with a dozen mobx stores injected) «pushes» all the tree to the left when being in a viewport.

![Screen-Recording](https://user-images.githubusercontent.com/12268898/69250099-1b6d5d80-0bc0-11ea-83de-8ccc368abfe5.gif)

**Comment by bvaughn** [comment] 2019-11-26 19:38
DevTools compresses indentation for deep trees to avoid the requirement for horizontal scrolling:
https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#no-more-horizontal-scrolling

This is an intentional feature :smile: In most cases, it improves the dev experience.

In your case above, you have some _really long component names_ (e.g. `inject-app-with-auth-creation-docs-filters-permission-settings-sources-users`) This will definitely make things compress more than would otherwise be necessary. I suggest shortening some of those really long names.

**Comment by bvaughn** [comment] 2019-11-26 19:38
To be clear: we can keep chatting about this feature! It's not a bug though, so I'm going to close this issue for now since it's not actionable.

**Closed by bvaughn** 2019-11-26 19:38 UTC

**Comment by keann** [comment] 2019-11-27 10:50
Ah, I see now :) Thanks!
