### ISSUE TITLE
Bug:  eslint-plugin-react-hooks doesn't support eslint.config.js 

### ISSUE THREAD

**Issue by yy-do-it** [facebook/react#29047] opened 2024-05-13 07:35 UTC
React version: Any

## Steps To Reproduce

1. Configure eslint-plugin-react-hooks with eslint.config.js es module config
2. It doesn't resolve react-hooks plugin

## The current behavior

Passing `...reactHooks.configs.recommended.rules`  does not resolve the plugin
![зображення](https://github.com/facebook/react/assets/167980386/af3699c3-7dcd-403b-a457-409e77dfcf97)

## The expected behavior

For the plugin to work with the modern eslint config.

**Comment by eps1lon** [comment] 2024-05-13 08:13
Duplicate of https://github.com/facebook/react/issues/28313

**Closed by eps1lon** 2024-05-13 08:13 UTC
Labels: Status: Unconfirmed
