### ISSUE TITLE
Props UI is not showing on right panel

### ISSUE THREAD

**Issue by Shyam268** [facebook/react#24039] opened 2022-03-08 06:54 UTC
I see the props UI is helpful to know the change in property on each commit in a **profile** tab. but i don't see the props UI on right panel. i am using react version 17+.is there any reason why this is not shown.?

**Comment by eps1lon** [comment] 2022-03-08 07:36
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Shyam268** [comment] 2022-03-08 09:37
please check the image attached:  
![image](https://user-images.githubusercontent.com/30112490/157200407-26b41091-26e9-4928-9e9f-fe751d5afba4.png).

i have created simple react app loading json data.
[my-app.zip](https://github.com/facebook/react/files/8204668/my-app.zip)

still i dont see the props ui on right panel :
![image](https://user-images.githubusercontent.com/30112490/157209240-7c95a322-44f7-4a10-8df5-0e50e484c042.png)

config details: 
chrome version: 99.0.4844.51 (Official Build) (64-bit)
react:  17.0.2,

**Comment by eps1lon** [comment] 2022-03-08 09:54
What you're seeing in https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html#profiling-an-application is the "components" tab not the "profiler" tab. 

The profiler doesn't track the props over time. It only tracks if props change.

**Comment by Shyam268** [comment] 2022-03-08 10:37
Here i want to know what change causing re-render on each commit like this .
![image](https://user-images.githubusercontent.com/30112490/157219805-20e78d50-dd98-460c-b46b-c7ebdafd581a.png).

and this props panel i am not able to see

**Comment by bvaughn** [comment] 2022-03-09 18:29
@Shyam268 I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**. 

More screenshots of the profiler UI aren't really going to help at this point. We really need a way to see what you're seeing.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

---

As for the screenshot above, that looks like a very old version of React DevTools and not the latest. The profiler UI no longer looks like the screenshots you've shared, but rather like this:

![Screen Shot 2022-03-09 at 1 28 51 PM](https://user-images.githubusercontent.com/29597/157507358-90bb061f-7e61-4f83-b0ac-a2695d2055f9.png)

**Comment by Shyam268** [comment] 2022-03-10 06:09
this is happening for basic react sample project as well.  will you share me react latest profiling document. 
i have enabled the react devtools extenstion.
![image](https://user-images.githubusercontent.com/30112490/157599907-b0026977-7d54-4eed-99d7-1d16549b07c1.png)

so asper latest Profile UI, i don't see "why did this render?". is there any extensions or configuration that i am missing.

**Comment by bvaughn** [comment] 2022-03-10 14:06
@Shyam268  Please open the Profiler settings and make sure you've enabled that option?
![Screen Shot 2022-03-10 at 9 04 58 AM](https://user-images.githubusercontent.com/29597/157678173-7d192f8a-833d-4bf4-9364-bbf5e675a95b.png)

**Comment by Shyam268** [comment] 2022-03-10 17:37
thank you now i am able to see this feature. 
![image](https://user-images.githubusercontent.com/30112490/157721822-67241caf-e8da-452b-b9ef-7e94501d1e84.png)

Here the 1ms of 1.6 ms what does it mean, and the right side panel ender at 5.6s of 4.7ms .

**Comment by bvaughn** [comment] 2022-03-11 01:35
I'm going to close this issue since the problem being reported (nothing on the right hand side) seems to have been a misunderstanding / disabled setting.

Check out this page on the docs to learn more about what the various parts of the profiler UI mean:
https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html

**Closed by bvaughn** 2022-03-11 01:35 UTC
Labels: Status: Unconfirmed, Resolution: Needs More Information, Component: Developer Tools
