### ISSUE TITLE
How can I visit the official site that writing by other language (default English)?

### ISSUE THREAD

**Issue by leftjs** [facebook/react#5991] opened 2016-02-06 05:48 UTC
visit the link [`getting-started`](https://facebook.github.io/react/docs/getting-started.html), it's English page, how to read this page that writing by other language.

**Comment by jimfb** [comment] 2016-02-06 05:59
https://facebook.github.io/react/docs/getting-started-zh-CN.html

Duplicate of https://github.com/facebook/react/issues/4614

**Closed** 2016-02-06 05:59 UTC
Labels: Type: Question

**Comment by leftjs** [comment] 2016-02-06 06:02
thanks, Jim
