### ISSUE TITLE
Don't trigger warnings when a prop is {null}

### ISSUE THREAD

**Issue by Akronix** [facebook/react#7820] opened 2016-09-28 09:45 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you have an unexpected prop in a component but that prop is not meant to be generated on the HTML DOM so that is set to {null}, React triggers this warning:
```
Warning: Unknown prop `activeClassName` on <h1> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in h1 (created by HelloWorldComponent)
    in HelloWorldComponent
```

The actual use case is to have a reusable component called `<Anchor>` and it'd be either `<Link activeClassName="'is-active" />` or `<a activeClassName={null} />`. [Here's our actual code.](https://github.com/worona/worona-dashboard/blob/dev/client/packages/bulma-dashboard-theme-worona/src/components/Header/MenuItem.jsx#L25)
In the HTML output, there's no any activeClassName attribute for the second case, so there shouldn't be any react warning.

**Example reproducing it**
I've reproduced the issue in a simple example here:
https://jsbin.com/bozuwuq/edit?html,js,console,output

**What is the expected behavior?**
Don't warn when a prop is defined to {null} and, therefore, never generated in the DOM.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version: 15.3.0
OS: Ubuntu and Mac OS X. Chromium and Google Chrome.

**Comment by jimfb** [comment] 2016-09-28 10:06
Duplicate of https://github.com/facebook/react/issues/7266, see discussion there.

**Closed by jimfb** 2016-09-28 10:06 UTC

**Comment by Akronix** [comment] 2016-09-28 10:24
really? isn't there any actual difference for react between setting a prop wittingly to `{null}` (suppose to mean  _not use the prop_ ) and accidentally have the prop set to undefined?

**Comment by jimfb** [comment] 2016-09-28 10:40
@Akronix If anything, setting the prop to null implies that "the attribute does exist, and has no value"... which is even worse than setting the prop to undefined.  If undefined is prohibited (which it is, as per the discussion I linked), then null should certainly be prohibited.

So yes, there is a difference, and both values should be prohibited.  The key should not exist on the props object for an `<h1>` tag.  See https://github.com/facebook/react/issues/7266 for best practice solutions that you can apply to fix your code.
