### ISSUE TITLE
support code property in synthetic events:

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/react#13011] opened 2018-06-11 08:29 UTC
on the MDN site https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

Mozilla is saying Event.code is the new way to distinguish which button a user is pressing, having to pull this off of the native event is a pain, and since this is the new standard, it'd be nice to have it on React's synthetic events.

**Comment by aweary** [comment] 2018-06-18 21:05
Duplicate of https://github.com/facebook/react/issues/12902

**Closed by aweary** 2018-06-18 21:05 UTC
