### ISSUE TITLE
Change event does not fire in IE and Edge under certain circumstances

### ISSUE THREAD

**Issue by iclanzan** [facebook/react#4672] opened 2015-08-20 21:40 UTC
I have put together this [simple example](http://jsbin.com/cimirozeje/edit?js,console,output) to demonstrate the issue.

The problem is happening on `select` elements. If there are any mouse event listeners attached that would trigger a render, the `onChange` handler never gets called.

It looks like unlike other browsers, **IE** and **Edge** trigger mouse events on the `select` element when clicking on the options, but that should not prevent the `change` event from triggering.

**Comment by jimfb** [comment] 2016-05-03 01:42
Repro: http://jsfiddle.net/trtz1y99/

**Comment by jdalton** [comment] 2016-11-09 00:52
Chrome and Edge 15 (insider preview) seem to both log `MouseUp` and `Change`.

**Comment by nhunzaker** [comment] 2017-07-11 22:40
Looks like this is still a problem, so I thought I'd reproduce it on CodePen so that it could be opened in IE11:

https://codepen.io/nhunzaker/pen/OgrRgm

**Comment by jasonwilliams** [comment] 2018-07-12 14:36
`change` and `MouseUp` both fire for me in Microsoft Edge 42.17134.1.0 @nhunzaker

**Comment by nhunzaker** [comment] 2018-07-15 01:59
@jasonwilliams We should confirm IE11, but I wonder if we can close this out and focus on the rendering/expansion issue separately.

**Comment by jasonwilliams** [comment] 2018-07-15 12:12
@nhunzaker `change` and mouseup` fire on Internet Explorer 11 too, but the rendering issue is the same as Edge. I think we should close this and open up a new issue for that

**Comment by nhunzaker** [comment] 2018-07-15 21:41
Sounds good. I made a quick write up (https://github.com/facebook/react/issues/13212). Travel and bandwidth issues make it hard for me to look much into this, but we can at least start to talk about it there.

Thanks everyone for weighing in!

**Closed by nhunzaker** 2018-07-15 21:41 UTC
Labels: Component: DOM, Type: Bug, mentorship
