### ISSUE TITLE
Bug: react-hooks/exhaustive-deps reports a casted TypeScript type as a dependency

### ISSUE THREAD

**Issue by alecmolloy** [facebook/react#19802] opened 2020-09-10 00:16 UTC
This bug is likely a very close sibling of https://github.com/facebook/react/issues/19327, only this time it is for casting `as T`. I can't understand the line that fixed it ([this specifically](https://github.com/facebook/react/pull/19316/files#diff-26e3db67655052fb708395a89179543bR546-R549)), but am happy to help write the rest of the PR's tests if someone can help with the fix for this one.

React version: 16.13.1 (latest)
eslint-plugin-react-hooks version: 4.1.0 (latest)

## Steps To Reproduce
1. Cast a variable to a type in a hook callback.

Link to code example:
https://codesandbox.io/s/admiring-tharp-cbq0d?file=/src/App.tsx

```tsx
type Foo = "Bar";

export default function App() {
  const callback = React.useCallback(() => {
    // this is the offending line:
    const foo = "Foo" as Foo;
    return foo;
  }, []);
  return <div onClick={callback} />;
}
```

## The current behavior
```
React Hook React.useCallback has a missing dependency: 'Foo'. Either include it or remove the dependency array.eslintreact-hooks/exhaustive-deps
```

## The expected behavior
No error, a type cannot be a dependency.

**Comment by jp7837** [comment] 2020-09-10 04:52
Slightly different repro FWIW:

```ts
const callback = React.useCallback((handler: T) => {
	return () => {};
}, []);
```

`React Hook React.useCallback has a missing dependency: 'T'. Either include it or remove the dependency array.`

**Comment by eps1lon** [comment] 2020-09-10 08:55
Duplicate of #19742

**Closed by eps1lon** 2020-09-10 08:55 UTC
Labels: Status: Unconfirmed
