### ISSUE TITLE
Confusing stack traces for exceptions in render

### ISSUE THREAD

**Issue by wonnage** [facebook/react#4910] opened 2015-09-18 18:56 UTC
I put a `throw` inside of a render function, and got this stacktrace:

```
Error caught: TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentMixin._updateRenderedComponent (https://localhost/vendor.js:19381:53)
    at ReactCompositeComponentMixin._performComponentUpdate (https://localhost/vendor.js:19363:11)
    at ReactCompositeComponentMixin.updateComponent (https://localhost/vendor.js:19279:13)
    at ReactPerf.measure.wrapper [as updateComponent] (https://localhost/vendor.js:11015:22)
    at ReactCompositeComponentMixin.receiveComponent (https://localhost/vendor.js:19143:11)
    at Object.ReactReconciler.receiveComponent (https://localhost/vendor.js:11151:23)
   ...
```

None of this is code I wrote, and none of this points to the component that failed. I'm using ES6 classes instead of React.createClass, which may or may not be relevant.

**Comment by syranide** [comment] 2015-09-21 15:29
`MyClass.render` not showing up in the stracktrace is very weird, but ultimately not something React does or even can manipulate. AFAIK the error is not re-thrown either (which sometimes messes up stack traces). Everything below that will only ever be internals really and uninteresting from a debugging perspective.

Which browser is this? Also, when all else fails, enable "pause on exception" in your browser and it usually points you to the problem even if the stack trace doesn't.

**Comment by wonnage** [comment] 2015-09-21 22:32
Yeah, I had to turn on pause on handled exceptions as well (which, if you use jquery, makes you step through a bunch of feature tests every time). I agree that this is just a React issue.

The unintuitive part for me is having to know that callback() in fact renders the page synchronously, necessitating the second catch(). Perhaps giving it a better name in the docs (e.g `continueRender`) would make this clearer.

**Comment by spicyj** [comment] 2015-09-22 01:33
This is not the error you threw, but it is a second error that gets thrown later because React (currently) doesn't gracefully handle thrown errors (#2461).

As for why you're not seeing the first error, something else is catching the error – probably promises are getting you. See http://blog.taylormcgann.com/2014/08/21/catch-errors-javascript-promise-chains/. (dupe of #2912 and several others)

**Closed by spicyj** 2015-09-22 01:33 UTC
