### ISSUE TITLE
Bug: url misspelled as uri when adding background image

### ISSUE THREAD

**Issue by aryan040501** [facebook/react#20559] opened 2021-01-07 20:31 UTC
React version:
17.0.1
## Steps To Reproduce

1. Add an empty url in the background-image tag in css
2. The url will not be fetched and it will say "Unable to find *uri*"

Link to code example:

.chatBody{
    background-image: url("");
}
## The current behavior
Error: Unable to find URI

## The expected behavior
Error: Unable to find URL

PS: I would love to rectify the issue as I found it :)

**Comment by aryan040501** [comment] 2021-01-07 20:31
I would love to work on this issue.

**Comment by eps1lon** [comment] 2021-01-08 05:15
Thanks for the report.

I was unable to reproduce this issue with codesandbox (https://codesandbox.io/s/hardcore-rubin-xrrpm?file=/src/styles.css). It seems to me that this is not caused by React but your build tool (e.g. create-react-app or next.js or a custom webpack config).

I recommend that you file an issue in the repositories responsible for those tools. Be sure to include a minimal reproducible example.

**Comment by rickhanlonii** [comment] 2021-01-08 18:36
Also can't repro and React doesn't really touch CSS files directly @eps1lon says.

Closing until there's more information that shows this is a React issue.

**Closed by rickhanlonii** 2021-01-08 18:36 UTC
Labels: Status: Unconfirmed
