### ISSUE TITLE
Bug: Clean up useEffect given [] empty dependency array causes a tedious linter error

### ISSUE THREAD

**Issue by myCatsName** [facebook/react#27333] opened 2023-09-04 17:45 UTC
Below is an example component (full component [LINK](https://github.com/myCatsName/bitburner-src/blob/Update-Gang-descriptions/src/Gang/ui/AscensionModal.tsx#L28)) which is causing a linter error if not disabled. This issue propbably relates to https://github.com/facebook/react/issues/16265 ;-)

A clean up useEffect given an empty dependency array, using a props method causes an error React Hook useEffect has a missing dependency: 'props'.

This might be a familiar issue to some, and perhaps I need a different approach and there is some reason to change.

But I raise the issue because it is from what I see a pain point for users of this functionality. Someone described it as not "ergonomic". And the same issue will continue to arise in the project this originates from. 

IMO in 2023 the React linter causes a conflict against what is commonly taught and what for my practical purposes has both worked and caused no issues. The clean up useEffect has a different behavior when given no dependency array, an empty `[]` array, or a filled one. There may be methods in at least some cases to de-structure and what not, satisfy the linter, but it is a pain point and I have struggled to find another working solution avoiding error. 

And keep in mind the code works in my use case, and similar useEffect syntax is noted [by Dan Abramov](https://overreacted.io/a-complete-guide-to-useeffect/#dont-lie-to-react-about-dependencies) - "to be clear, this code does work."

It feels like useEffect has developed over time and linter in this case has not. Or I'm wrong?

React version:
`"react": "^17.0.2",`

```
type AscensionModalProps = {
  open: boolean;
  onClose: () => void;
  member: GangMember;
  onAscend: () => void;
};
export function AscensionModal(props: AscensionModalProps): React.ReactElement {
  const gang = useGang();
  useRerender(1000);

  //Cleanup if modal is closed for other reasons, ie. ns.gang.ascendMember()
  useEffect(() => {
    return () => {
      props.onClose();
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps
  // dependency array must be given and empty or modal will not open
  // React error wants 'props' in dependency or don't use 'props'.
  // See: https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook

```

[Here is the open source project and a specific useEffect clean up as an example]
(https://github.com/myCatsName/bitburner-src/blob/Update-Gang-descriptions/src/Gang/ui/AscensionModal.tsx#L28)

## The current behavior
React cause me trouble

## The expected behavior
React cause react

**Comment by myCatsName** [comment] 2023-09-04 18:00
I suspect this goes back to https://github.com/facebook/react/issues/14920 , which is actually frustrating to read. The one who pushed those changes at first ignored this very common issue. And I would say brushed it off very carelessly by claiming

>If your component doesn't handle updates to a prop, it is usually buggy. The design of useEffect forces you to confront it. You can of course work around it, but the default is to nudge you to handle these cases.

Feels needless and unhelpful when such a simple function needs me to "confront" the very resource that provided it.

Please stop fighting and fix. Offer a different solution.

**Comment by myCatsName** [comment] 2023-09-05 00:14
Thank you @AuthorProxy , that might work - but it shows that React forces us to work around useEffect instead of having a simple tool.

**Comment by mbkv** [comment] 2023-09-05 13:53
This is (potentially) a bug react is trying to warn you about

If onClose is defined every render (ie: without useCallback), it'll potentially cause an outdated onClose function to be called instead of whatever the latest version is

```typescript
const [counter, setCounter] = useState(0);

if (counter > 10) {
  return null;
}

return (
  <IncrementModal
    onIncrement={() => setState(old => old + 1)}
    onClose={() => {
      // with your implemention using an empty dependency array
      // this would only ever output 0, even though this modal only unmounts
      // after counter reaches 11
      console.log(counter)
    }}
  />
)
```

**Comment by myCatsName** [comment] 2023-09-05 14:54
Thanks @mbkv . Surprisingly so many of the solutions in discussion about this issue are exactly to disable the linter, which to me is a big sign that a change should be made on React's side of this. Unfortunately in many practical and professional cases, it has made more sense for users to disable linters, which React is partly responsible for. For example a comment from the issue #16265

> My co-workers are all ignoring this warning because there's no convenient way to make it happy


For myself and I guess many others, our use case is so simple. `onClose: () => void;` closes the component modal, and [] is such an easy way to get the right behavior - run the clean up return only 1 time at component unmount. Because I have control of the component from start to finish, I know that onClose() prop is static and available.

Destructuring doesn't always work, or hasn't for me, and other solutions are bloating the code and require us to understand and implement something completely different. useCallback, memoization, duplicate destructured code - or work around the linter, with a disable line, or a custom hook "withoutDependency".

**Comment by NMinhNguyen** [comment] 2023-09-05 23:04
For what it’s worth, the docs call out this pattern as a code smell, and you should spot issues if you wrap this component in `StrictMode`: https://react.dev/reference/react/useEffect#my-cleanup-logic-runs-even-though-my-component-didnt-unmount

**Comment by myCatsName** [comment] 2023-09-05 23:59
>react team doesn't need to support each of this case, because it is projects specific cases

I agree with you on that @AuthorProxy . When the project maintainer got involved in the code, in fact we do have custom hooks in place, and they were able to smooth everything in our code. Thanks for your support.

But I will leave the issue because I think the process could be better for an average user. Too many projects are disabling linter lines because of this I think. And now that I understand the possible bug better, I would hope for something different in the way React handles the error, or maybe updating some documentation at least, because there are a lot of possible solutions offered and many of them simply break and change the context and will frustrate future users.

**Comment by daukantas** [comment] 2023-09-06 05:28
JYour github input has been violating my email !

Attention:  Please  make adjusted  changes to prevent your input entering this email site.


Warning! Please review “Scams and Identity Theft Attempts Targeting International Affiliates”, which can be found at https://www.hupd.harvard.edu/scams-targeting-international-affiliates
Scams and Identity Theft Attempts Targeting International Affiliates<https://www.hupd.harvard.edu/scams-targeting-international-affiliates>
Introduction
www.hupd.harvard.edu<http://www.hupd.harvard.edu/>
.


________________________________

**Comment by frfancha** [comment] 2023-09-18 05:57
There is no bug at all in that warning.
Nothing guarantees that the onClose function is still the original one when the component unmounts.
And if the user of the component provides a refined onClose function that's because it wants that refined function to be called, not the original one that your implementation is calling. This what the warning tries to tell you.
What's to do?
-if you are _sure_ that users of your component _always_ passes the final onClose function at first render, you can ignore the warning (I wouldn't recommend it)
-if your goal is just to call the latest version of the onClose function, but of course to not add it to the dependencies as you don't want to "close" any time the onClose changes, then it is easy: just point to it from a ref.
Before the useEffect :
const onCloseRef = useRef(props.onClose);
onCloseRef.current = props.onClose;
And in your useEffect call onCloseRef.current
Which makes your useEffect code intention very clear : you don't want to trigger it when onClose changes, just call whatever the current version is when the component unmounts.

**Comment by sophiebits** [comment] 2023-10-19 07:08
This is not a bug so I'll close it but to add a bit more color – in most cases it *is* a bug to ignore the linter, which is why it exists and is still recommended. The effects documentation on react.dev is quite good and discusses this in detail, starting with this page: https://react.dev/learn/synchronizing-with-effects.

There are some use cases where there is not yet an ergonomic API in React. As this page mentions, there is a planned API useEffectEvent to solve this case (name and exact semantics may change), but it will remain the case that other dependencies are required to be written.

https://react.dev/learn/separating-events-from-effects

**Closed by sophiebits** 2023-10-19 07:08 UTC
Labels: Status: Unconfirmed
