### ISSUE TITLE
Hooks can only be called inside the body of a function component.

### ISSUE THREAD

**Issue by ChiefORZ** [facebook/react#15837] opened 2019-06-07 12:09 UTC
Hello there!

We, in our team, love the new Hooks API!
But it comes with one negative thing we are experiencing since the 16.8 update...

```
Hooks can only be called inside the body of a function component.
```

We internally use multiple repositories.
One for every customer project and multiple shared libraries.

Since hooks require us to only have one copy of react in the scope (https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) we are forced to link our project to allow development of the shared libraries while running the dev server from the customer projects.
So we have to link our projects depending on which project we are currently working on.
```sh
#!/bin/bash
cd /shared-component-library
pushd ./node_modules/react && yarn link && popd
pushd ./node_modules/react-dom && yarn link && popd
yarn link

cd /shared-hooks-library
yarn link "react"
yarn link "react-dom"
yarn link

cd /customer-project-1
yarn link "react"
yarn link "react-dom"
yarn link "shared-component-library"
yarn link "shared-hooks-library"
```
This process has to be done for every frontend developer and does not work every time you try.
Before you add new dependencies you have to unlink every linked dependency.
and therefore it is very time consuming and is in our way.

---

Then we stumbled upon yarn plug'n play... which is not working for the most part. most npm packages cannot be installed, therefore its not a viable option for us.

And then we tried the package manager `pnpm` which installs all dependencies on a central location in the filesystem and we thought that this might fix all of our issues. unfortunately there are two react instances too...

---

We would highly appreciate if someone would put some effort into this topic.
Maybe by finding a way to make sure only one react instance is present - making it a Singleton somehow?!
We don't have to re-invent the package management for this issue i think - it's just a matter of detecting of a react instance is already present - i think ^^

**Comment by robertknight** [comment] 2019-06-07 22:25
You might wish to try [yalc](https://github.com/whitecolor/yalc) as an alternative way to use a package that is being developed locally rather than coming from npm. The workflow and behavior is very much like publishing and consuming a package to npm, without the hazards that symlinks cause, except that the package "registry" is just a folder on your local machine.

**Comment by robertknight** [comment] 2019-06-07 22:38
> Maybe by finding a way to make sure only one react instance is present - making it a Singleton somehow?!

Assuming you are using a bundler such as Webpack, it is the bundler that is putting multiple copies of React into the JS files that the browser loads. The bundler in turn is just trying to be faithful to how node module lookup is supposed to work. That's why I like yalc as a solution since it fixes the problem at the bottom layer of the stack.

The FAQ page you linked to has a link to an existing GitHub issue with other solutions for the problem: https://github.com/facebook/react/issues/13991

**Comment by threepointone** [comment] 2019-09-04 11:14
Closing this as a dupe of #13991

**Closed by threepointone** 2019-09-04 11:14 UTC
