### ISSUE TITLE
Cannot analyse component State

### ISSUE THREAD

**Issue by rakhi2104** [facebook/react#17767] opened 2020-01-03 14:13 UTC
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
- On trying to analyse a component State using React Developer Tools, the analyse pane stays in the `Loading ...` state and throws this error
```js
Uncaught TypeError: Cannot read property 'name' of undefined
    at O (backend.js:1)
    at s (backend.js:1)
    at s (backend.js:1)
    at s (backend.js:1)
    at l (backend.js:1)
    at Object.inspectElement (backend.js:6)
    at t.<anonymous> (backend.js:6)
    at t.r.emit (backend.js:6)
    at backend.js:32
    at t (backend.js:8)
```
**What is the expected behavior?**
- Able to analyse component State as in the previous React Dev Tools versions. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- React Developer Tools version: 4.3.0 (12/20/2019)
- React Version: ^16.4.0
- Browsers:
  - Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
  - Brave: Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)

**Comment by bvaughn** [comment] 2020-01-03 16:41
This looks like a duplicate of #17754 which was fixed by #17757 yesterday (but has not yet been released). If you'd like to provide a repro case for the bug, I can verify that it is indeed the same bug- but I'm pretty confident based on your description here.

The release should go out in the next couple of days.

**Closed by bvaughn** 2020-01-03 16:41 UTC
