### ISSUE TITLE
almost same problem.

### ISSUE THREAD

**Issue by swathisaathvi** [facebook/react#17049] opened 2019-10-09 08:51 UTC
almost same problem.

I am updating the global state using context api, but when I am calling global state in `useEffect()` it still retreive the initial value, not updated value. here I used [], as second parameter for useEffect function. when I remove it, it execute all code withing useEffect function as unlimited.

_Originally posted by @muhammadwfa in https://github.com/facebook/react/issues/14066#issuecomment-533625045_

**Comment by kunukn** [comment] 2019-10-09 11:10
Can you create a minimal, reproducible example? It could be in codesandbox or github repo.

Can you please update the title to something more meaningful than "almost same problem"?

**Comment by bvaughn** [comment] 2019-10-09 16:46
Hi @swathisaathvi! This issue needs more information before we'll be able to provide any help. I'm going to close it for now since it seems like it was just copy-pasted from another user's (@muhammadwfa) comment.

If you provide some more context (some example code that shows what you're doing and what's happening that's unexpected) I'll re-open it!

**Closed by bvaughn** 2019-10-09 16:46 UTC
