### ISSUE TITLE
Paste Event Handler not invoked when focus is applied to element programmatically

### ISSUE THREAD

**Issue by bkilrain** [facebook/react#9769] opened 2017-05-24 20:09 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Clicking on an element to set focus allows the onPaste handler to be invoked as expected. When you apply focus to an element using the [HTMLElement.focus](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) method, the onPaste handler is not invoked.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
[jsFiddle here](https://jsfiddle.net/bkilrain/69z2wepo/79420/)

1. Open the console on the jsFiddle
2. Click on yellow div to focus
3. Use keyboard (ctrl/cmd-V) or edit menu to fire paste event
4. Notice paste event logged in console as expected
5. Click on input element to focus
6. Press an arrow key to set focus on yellow div programmatically
7. Use keyboard (ctrl/cmd-V) or edit menu to fire paste event
8. Notice no paste event logged in console

You can double check the paste event is firing using dev tools.

**What is the expected behavior?**
I expect the event handler to be invoked regardless of how focus is applied to the element

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.5.4
React 15.4 

Tested on macOS 10.12.5 w/ Chrome v 58.0.3029.110 (64-bit)

**Comment by aweary** [comment] 2017-05-28 15:16
Hey @bkilrain! Thanks for the report. This appears to be how Chrome behaves, though I'm not sure if it's a Chrome bug or not. Here's a [JSFiddle reproducing the issue without React](https://jsfiddle.net/9jkr9o3v/), which shows that it's not an issue with React itself.

I was able to reproduce this behavior in Chrome 58.0.3029.110 and Safari 10.0.2, but it works fine (with or without React) in Firefox 53.0.3.

**Comment by aweary** [comment] 2017-05-28 15:19
Since it's not clear whether this is _expected_ based on any spec, and the behavior is inconsistent between major browsers, I don't think this is something that can or will be addressed in React itself.

I recommend maybe [referring to the Chrome bug tracker](http://dev.chromium.org/for-testers/bug-reporting-guidelines), where there may already be an issue for this (couldn't find one though) or you can file a new one.

Hope that helps!

**Closed by aweary** 2017-05-28 15:19 UTC
