### ISSUE TITLE
Cannot preventDefault input[type=number] onWheel event in Chrome

### ISSUE THREAD

**Issue by jjenzz** [facebook/react#15199] opened 2019-03-23 14:04 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In Chrome, using `event.preventDefault()` and/or `event.nativeEvent.preventDefault()` within `onWheel` handler of an `input[type=number]` does not prevent number scrolling.

[![image](https://user-images.githubusercontent.com/175330/54867920-3613dc00-4d7e-11e9-889c-7d89f444a662.png)](https://www.chromestatus.com/features/6662647093133312)
https://www.chromestatus.com/features/6662647093133312

React example: https://codesandbox.io/s/00kx423nyl
HTML & JS example for comparison: https://jsbin.com/warerunitu/edit?html,js,output

**What is the expected behavior?**

I would expect the same behaviour as shown in the HTML & JS example above.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested in `react@16.8.5`, `react-dom@16.8.5` and Chrome v73. I'm unsure if previous versions are affected.

**Comment by charlzzdev** [comment] 2019-03-23 17:33
Hey! You could do it the same way as in the HTML & JS example using the `useEffect` hook like this:
```
function App() {
  useEffect(() => {
    document.getElementById('theid').addEventListener('wheel', event => {
      event.preventDefault()

      console.log(
        event,
        event.defaultPrevented
      )
    })
  }, [])

  return (
    <div className="App">
      <input
        type="number"
        id="theid"
      />
    </div>
  );
}
```

**Comment by jjenzz** [comment] 2019-03-24 08:39
Sure, I’m just reporting the issue with onWheel here. It would be good to be able to use React if I’m using React 😊

**Comment by def0x099** [comment] 2019-03-25 20:47
There should be a flag for passive mode tbh if there isn't already

**Comment by gaearon** [comment] 2019-03-26 19:50
This is a duplicate of https://github.com/facebook/react/issues/14856.

**Closed by gaearon** 2019-03-26 19:50 UTC
