### ISSUE TITLE
ReactDefaultPerf.printWasted() doesn't work

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#5548] opened 2015-11-25 21:59 UTC
Calling `ReactDefaultPerf.printWasted()` results in:

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
writes.(anonymous function).forEach @ ReactDefaultPerfAnalysis.js:195
Object.keys.forEach @ ReactDefaultPerfAnalysis.js:192
getUnchangedComponents @ ReactDefaultPerfAnalysis.js:191
getInclusiveSummary @ ReactDefaultPerfAnalysis.js:139
ReactDefaultPerf.getMeasurementsSummaryMap @ ReactDefaultPerf.js:118
ReactDefaultPerf.printWasted @ ReactDefaultPerf.js:133
```

(this is on a page internally at Facebook so I assume it's a fairly recent React version)

**Comment by jimfb** [comment] 2016-01-12 06:30
@Daniel15 Are you still experiencing this issue internally?  If so, can you create an internal task with details and repro steps?  Assign to the oncall, cc the React team.

Our internal configuration is a bit different, and we don't want to discuss internal code/details/configurations on github.  I'm going to close this out, and we can help you debug using internal tools if you're still running into problems.

**Comment by lostfictions** [comment] 2016-03-25 16:40
Small note for anyone experiencing a similar error message who arrived here by Googling: I got bit by this because I updated react and react-dom without updating react-addons-perf at the same time.

**Comment by sverrejoh** [comment] 2016-04-10 07:26
I'm getting this issue after upgrading to react 15.0.1. All my React packages (including perf) is 15.0.1. printExclusive() etc. works, but printWasted gives the exception shown above.

**Comment by gaearon** [comment] 2016-04-10 11:46
@sverrejoh Are you running `ReactPerf.start()` before using it?

**Comment by sverrejoh** [comment] 2016-04-10 12:22
Yes. `ReactPerf.start()`, `ReactPerf.stop()` and then the rest of the Perf API works, for example `ReactPerf.printExclusive()`.

I changed over to my 0.14.7 branch, and there everything works like it should, and I double checked that both ReactPerf and React was on 15.0.1.

![image](https://cloud.githubusercontent.com/assets/1209/14410147/a621a9b2-ff27-11e5-8243-ce314f9431a5.png)

**Comment by gaearon** [comment] 2016-04-10 13:59
Let’s reopen until we hear more.

**Comment by Danita** [comment] 2016-04-14 16:40
I had it working for a few minutes and then it started failing without me doing anything strange.

**Comment by gaearon** [comment] 2016-04-14 16:47
@Danita 

Thanks for the info, do you also have the same stack trace and error message as the first post?

**Comment by Danita** [comment] 2016-04-14 16:51
Yes. I was exposing the `Perf` object as `window.Perf`. I tried again exposing it as `window.P` and `P.printWasted()` it's working again. Puzzling.

I'm using the full 15.0.1 ecosystem, on Babel 6, Webpack and Webpack dev server, testing on Chrome.

**Comment by gaearon** [comment] 2016-04-14 17:31
Any chance you have a public project where you can more or less consistently reproduce this?

**Comment by gaearon** [comment] 2016-04-14 17:44
Technically this means there was [a write](https://github.com/facebook/react/blob/0b1fd186855a48dff78987f13466cec1e579b78c/src/test/ReactDefaultPerf.js#L197) for which there was no [hierarchy record](https://github.com/facebook/react/blob/0b1fd186855a48dff78987f13466cec1e579b78c/src/test/ReactDefaultPerf.js#L351). This code is super fragile so it’s hard to pin it down without having a specific component hierarchy that happens to cause this.

**Comment by gaearon** [comment] 2016-04-14 17:51
If someone wants to spend some effort tracking it down, I would recommend:

1. Add 

  ```js
  if (!measurement.hierarchy[id]) {
    console.log('missing hierarchy for', id)
  }
  ````
  just before [this line](https://github.com/facebook/react/blob/0b1fd186855a48dff78987f13466cec1e579b78c/src/test/ReactDefaultPerfAnalysis.js#L183).

2. Add

  ```js
  console.log('write for id', id, 'with args', fnName, args)
  ```
  just before [this line](https://github.com/facebook/react/blob/0b1fd186855a48dff78987f13466cec1e579b78c/src/test/ReactDefaultPerf.js#L199).

Then please share the relevant `write for id` logs that correspond to the ID you see in the `missing hierarchy for` message.

**Comment by Danita** [comment] 2016-04-14 18:26
@gaearon Thanks Dan, I'll try setting up that to see if I can help. Unfortunately I cannot share my project right now because of client terms.

**Comment by gaearon** [comment] 2016-04-14 18:44
@Danita Yeah, I thought this might be the case. Thanks for taking the time to investigate.

**Comment by Danita** [comment] 2016-04-14 18:49
@gaearon OK I added the lines and I managed to also reproduce the error. [Here you can find the console log](https://dl.dropboxusercontent.com/u/7686719/log.txt).

FYI, my app is a SPA, I captured this on a route where I have a long list of items that can be filtered by certain criteria and doing `Perf.start()` before filtering and `Perf.stop()` `Perf.printWasted()` after some of those items were removed because of the filtering.

**Comment by gaearon** [comment] 2016-04-14 18:56
Thank you, this is very helpful! I’ll dig into it and see if I can repro this given the new info.

**Closed** 2016-04-14 23:03 UTC
Labels: Component: Addons / Perf
