### ISSUE TITLE
Optimizing the reconciliation of unchanged DOM nodes

### ISSUE THREAD

**Issue by milankinen** [facebook/react#5248] opened 2015-10-22 21:56 UTC
Hi! I'm not sure if this is a bug or feature but I'll make this issue anyway.

It seems that React tries to optimize the reconciliation by [early stopping the reconciliation of react element if its reference has not changed](https://github.com/facebook/react/blob/v0.14.0/src/renderers/shared/reconciler/ReactReconciler.js#L70-L84). However, because only `ReactCompositeComponentMixin` has the `_context` property, the check fails with normal DOM nodes (`div`, `ul`, ...). In practice this means that the sub-tree will be diffed although the element hasn't changed at all, resulting poor performance with huge sub-trees.

I tried to change the check a little bit:

``` javascript
if (nextElement === prevElement && (!internalInstance.hasOwnProperty("_context") || context === internalInstance._context)) {
  return;
}
```

I tried to run it with the following test application and I got a massive performance improvement

``` javascript
import React from "react"
import {render} from "react-dom"

const range = n => Array.apply(null, {length: n}).map(Number.call, Number)

const staticList = (
  <ul>
    {range(100000).map((_, idx) => <li key={idx}>Item #{idx}</li>)}
  </ul>
)


class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = { counter: 0 }
  }

  increment() {
    this.setState({counter: this.state.counter + 1})
  }

  decrement() {
    this.setState({counter: this.state.counter - 1})
  }

  render() {
    const {counter} = this.state
    return (
      <div>
        Counter value is {counter}
        <div>
          <button onClick={this.increment.bind(this)}>+</button>
          <button onClick={this.decrement.bind(this)}>-</button>
        </div>
        {staticList}
      </div>
    )
  }
}

render(<App />, document.getElementById("app"))
```

What do you think? Does this optimization make any sense or does it have any unwanted effects I'm unaware of? If I've understood right, react elements are [immutable](https://github.com/facebook/react/blob/v0.14.0/src/isomorphic/classic/element/ReactElement.js#L112-L113) so the strict equality check should be enough but how about `ReactDOMNode` (internalInstance)?

And yes. I know that this could be solved by using custom component class and `componentShouldUpdate` but that's not I'm searching for.

**Comment by spicyj** [comment] 2015-10-24 04:47
This sounds like a bug.

**Comment by yiminghe** [comment] 2015-10-26 15:39
when consider context, optimization is hard:

https://jsfiddle.net/yiminghe/nc70bv0t/1/

**Comment by jimfb** [comment] 2015-10-26 16:32
Yes, as @yiminghe said, optimizing context is hard.  You can't bail out with a `!internalInstance.hasOwnProperty("_context")` check because the DOM component may have children which are composite components; such a check would lead to erroneous behavior.  To avoid reconciling the DOM nodes, we would need to save the previous context on the internal instance (ie. `_context`), which we can't do if most DOM nodes are going to become stateless components.  There might be some fancy magic we could do if we knew that none of the deep children were composites and/or if we utilized some glimmer-like diffing, but I think that's out of scope of this issue.

Anyway, the decision to not skip DOM components was an intentional one.  Not a bug.

We can leave this issue open for a few days to see if anyone has ideas/solutions, or if @sebmarkbage wants to jump in.

**Comment by iclanzan** [comment] 2015-12-26 19:16
I was trying to pass a DOM component element tree to `React.render`, and upon re-rendering I noticed it was skipping this optimization. Wrapping some key sub-trees in Composite components results in orders of magnitude faster re-renders (because it passes the check to bail out early), but it feels like a hack.

**Comment by gaearon** [comment] 2015-12-26 20:42
I bumped into this when hand-optimizing `connect()` from [React Redux](https://github.com/rackt/react-redux/blob/master/src/components/connect.js). In the end I used a combination of constant element and `shouldComponentUpdate` to do the optimization I wanted.

**Comment by gaearon** [comment] 2017-10-03 22:38
Seems like this particular bug was fixed in React 16.

**Closed by gaearon** 2017-10-03 22:38 UTC
