### ISSUE TITLE
Bug: "Unspecified error" some of the time in IE11 in iframe

### ISSUE THREAD

**Issue by mparizeau-pdftron** [facebook/react#19530] opened 2020-08-04 23:33 UTC
React version: 16.12

## Steps To Reproduce

1. Open http://cygnetuat.sterlingdatarooms.com/PDFTronClientTest/ in IE11
2. Wait for the application to load in the iframe

## The current behavior
Sometimes an "Unspecified error" will appear in the console and the viewer in the iframe won't load

![image](https://user-images.githubusercontent.com/15879431/89355081-60162780-d66f-11ea-829a-fbbf2e8e1f32.png)

Unfortunately it is not 100% reproducible. Sometimes the error won't occur. I'm also having trouble creating a minimal sample to reproduce this.

## The expected behavior
There is no error.

## Investigation

The relevant line in the callstack where the error is occurring is here https://github.com/facebook/react/blob/03de849af03996b7477420c97de7741ce1214149/packages/react-dom/src/client/ReactDOMInput.js#L415

I suspect it might be the same issue discussed here https://github.com/Availity/react-block-ui/issues/18
>This was a real pain to track down, but apparently IE 11 will just throw Unspecified error. when accessing document.activeElement from an <iframe>, sometimes.

The solution they used to fix the error was to use this function instead of accessing document.activeElement directly https://gist.github.com/Alex1990/046a6553dc83e22dd6f4

Ideally this function could be used inside React as well. I am also happy to use a workaround if there is one.

**Comment by dhavalsingh** [comment] 2020-08-05 16:24
is anyone working on this? or can i give it a shot?

**Comment by pfongkye** [comment] 2020-08-14 20:29
@dhavalsingh are you working on this issue?

**Comment by hemakshis** [comment] 2020-08-18 17:25
Hi, is this issue available? If yes, I wanna take it up as my first issue to the React project. Thanks!

**Comment by pfongkye** [comment] 2020-08-18 17:38
Hi @hemakshis, I was waiting for @dhavalsingh to reply. I think you can go for it. I can help if needed.

**Comment by eps1lon** [comment] 2020-08-18 17:52
@hemakshis All yours. If you get stuck at any point in time feel free to share your progress.

**Comment by hemakshis** [comment] 2020-08-19 05:03
Thanks a lot @pfongkye and @eps1lon. Will definitely reach out if I face any issues.

**Comment by hemakshis** [comment] 2020-08-19 14:30
Hi, I am unable to reproduce this error, can someone help me with it? And how can I contact you - Discord, IRC, or some other means?
Thanks.

**Comment by eps1lon** [comment] 2020-08-19 14:40
> Hi, I am unable to reproduce this error, can someone help me with it?

Looking at the initial issue description this might be tough to accomplish:

> Unfortunately it is not 100% reproducible. Sometimes the error won't occur. I'm also having trouble creating a minimal sample to reproduce this.

I guess @bvaughn envisioned that this could just be solved by replacing the current read with https://gist.github.com/Alex1990/046a6553dc83e22dd6f4. 

But reproducing a IE11-iframe bug that only "sometimes" sometimes occurs seems like a pretty hard task to me.

**Comment by hemakshis** [comment] 2020-08-20 16:24
Hi,
Thanks for your inputs. I was going through the code and thought that there might be other places as well where we are trying to get `document.activeElement` and found that there is already a very similar implementation done in this file:

[getActiveElement.js](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/getActiveElement.js)
https://github.com/facebook/react/blob/c641b611c4d270660b0bb850759f5a324787a7b3/packages/react-dom/src/client/getActiveElement.js#L10-L20

I think we can reuse this function in mentioned line of description. Please let me know if this sounds correct or not.
Also, I found a lot of places in the code where we can replace `document.activeElement` with this function. If they also need to be done I can compile the list of files/lines where we may have to make this change.

**Comment by hemakshis** [comment] 2020-08-20 19:33
Hi,
Created #19664 
Request you to please review it.
Thanks

**Comment by hemakshis** [comment] 2020-08-21 04:55
Hi @pfongkye, @eps1lon, I want to continue contributing so do you think I can take up some other issue, if yes, please let me know? Maybe not as trivial as this one.

**Comment by eps1lon** [comment] 2020-08-21 06:57
Closed in #19664


> Hi @pfongkye, @eps1lon, I want to continue contributing so do you think I can take up some other issue, if yes, please let me know? Maybe not as trivial as this one.

You can look through the [issues marked as "bug"](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Type%3A+Bug%22) and see if something catches your eye. The conversations might have some hints how a fix might look or whether this this isn't worth fixing because an upcoming refactor might fix it incidentally.

Also triaging issues or simply checking if they're still valid or need an updated reproduction is a form of contributing as well.

**Closed by eps1lon** 2020-08-21 06:57 UTC
Labels: Component: DOM, Type: Bug, good first issue (taken)
