### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by SK-DNS-NET** [facebook/react#23317] opened 2022-02-17 11:33 UTC
### Website or app

local running intranet web app

### Repro steps

1 . start intranet web app
2. call in DevTools from React DevTools "Components"

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.23.0-e28a0db22

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26229:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24415:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24581:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54033:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by SK-DNS-NET** [comment] 2022-02-17 11:34
Thanks

**Comment by MalinnaLeach** [comment] 2022-02-25 16:16
This is a duplicate of:  https://github.com/facebook/react/issues/23226

**Comment by bvaughn** [comment] 2022-03-14 13:35
Closing as a duplicate of #23226.

**Closed by bvaughn** 2022-03-14 13:35 UTC
Labels: Type: Bug, Resolution: Duplicate, Status: Unconfirmed, Component: Developer Tools
