### ISSUE TITLE
A property from parent component does not update realtime on a child functional component

### ISSUE THREAD

**Issue by redeguzman-gbf** [facebook/react#16819] opened 2019-09-18 11:39 UTC
**Beginner question: not sure if this is an issue with react or with my code. I'm basically asking for help.**

**Current behavior**

I have a property that I pass down to a child component that does not update in real time.

Example:

```ES6
class Parent extends Component {
  state = {
    sampleProp = true
  }
  render() {
    <Fragment>
      <Child sampleProp={this.state.sampleProp} />
      <TouchableOpacity onPress={() => this.setState({sampleProp: sampleProp ? false : true})}>
        {/* button content */}
      </TouchableOpacity>
    </Fragment>
  }
}

const Child = ({sampleProp}) => {
  // some useState hooks
  console.log(sampleProp) // if at this point sample prop is true...

  const onClick = React.useCallback(
    () => {
      console.log(sampleProp) // this is false on first click then true on subsequent clicks
      // update some state
    },
    [stateVariable]
  )

  return (
    <TouchableOpacity onPress={() => onClick()}>
      {/* update some state */}
    </TouchableOpacity>
  )
}
```

Basing from the code above, the value of `sampleProp` in the child component is equal to the one in parent but when I update its value from the parent, then I click on `onClick` from the child, I get the previous value of `sampleProp`. I don't know what I'm doing wrong because I am a beginner with React JS

**Comment by threepointone** [comment] 2019-09-18 11:55
I can't comment with a reproducing example on codesandbox or as a git repo. But if I had to guess, it's because you haven't added `sampleProp` to the dependencies array of `useCallback`. 

(Honestly, I don't think you need a `useCallback` there at all, simply pass the function as the handler.) 

I'm closing this since it isn't a bug or feature request per se, but happy to discuss if you have a reproducing example.

**Closed by threepointone** 2019-09-18 11:55 UTC

**Comment by redeguzman-gbf** [comment] 2019-09-18 16:12
Sorry I forgot to mention that I am developing with React Native 0.60.4.

Thanks for your answer. I think you have a point there but nothing changes when I put `sampleProp` in the dependencies, (in my react native app).

I created a sample React app [here](https://codesandbox.io/s/upbeat-wilson-vl1l9) that mimics my RN except that the list is a `Flatlist` with `extraData` prop set to a state variable (which is also set as the dependency of the `useCallback` hook) and the `sampleProp` from `Parent` component is coming from a Redux store and mapped to local props. Any feedback is much appreciated.
