### ISSUE TITLE
40 errors associated with this file

### ISSUE THREAD

**Issue by Corsairs** [facebook/react#18097] opened 2020-02-21 19:16 UTC
![https://i.imgur.com/o4MKh9p.jpg](https://i.imgur.com/o4MKh9p.jpg)

https://github.com/reactjs/reactjs.org

I decided to try react and reactjs.org and saw a lot of errors.

i use windows

Strange, but even with these errors the site seems to work.

```
GET http://0.0.0.0:8000/__webpack_hmr net::ERR_ADDRESS_INVALID

C:/react/reactjs.org/node_modules/react-error-overlay/lib/index.js:2172 Warning: The <HeaderLink /> component appears to be a function component that returns a class instance. Change HeaderLink to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `HeaderLink.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.

C:/react/reactjs.org/node_modules/react-error-overlay/lib/index.js:2172 Warning: The <Header /> component appears to be a function component that returns a class instance. Change Header to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `Header.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.



__stack_frame_overlay_proxy_console__ | @ | C:/react/reactjs.org…y/lib/index.js:2172
-- | -- | --
  | warningWithoutStack | @ | C:/react/reactjs.org….development.js:530
  | mountIndeterminateComponent | @ | C:/react/reactjs.org…evelopment.js:18805
  | beginWork$1 | @ | C:/react/reactjs.org…evelopment.js:20162
  | beginWork$$1 | @ | C:/react/reactjs.org…evelopment.js:25756
  | performUnitOfWork | @ | C:/react/reactjs.org…evelopment.js:24695
  | workLoopSync | @ | C:/react/reactjs.org…evelopment.js:24671
  | performSyncWorkOnRoot | @ | C:/react/reactjs.org…evelopment.js:24270
  | scheduleUpdateOnFiber | @ | C:/react/reactjs.org…evelopment.js:23698
  | updateContainer | @ | C:/react/reactjs.org…evelopment.js:27103
  | eval | @ | C:/react/reactjs.org…evelopment.js:27528
  | unbatchedUpdates | @ | C:/react/reactjs.org…evelopment.js:24433
  | legacyRenderSubtreeIntoContainer | @ | C:/react/reactjs.org…evelopment.js:27527
  | render | @ | C:/react/reactjs.org…evelopment.js:27608
  | eval | @ | C:/react/reactjs.org/.cache/app.js:94
  | setTimeout (async) |   |  
  | eval | @ | C:/react/reactjs.org…omready/ready.js:26
  | eval | @ | C:/react/reactjs.org/.cache/app.js:93
  | Promise.then (async) |   |  
  | eval | @ | C:/react/reactjs.org/.cache/app.js:91
  | Promise.then (async) |   |  
  | eval | @ | C:/react/reactjs.org/.cache/app.js:48
  | eval | @ | C:/react/reactjs.org/.cache/app.js:130
  | ./.cache/app.js | @ | commons.js:827
  | __webpack_require__ | @ | commons.js:725
  | fn | @ | commons.js:102
  | eval | @ | C:/react/reactjs.org…js.org/.cache/app:3
  | 0 | @ | commons.js:5470
  | __webpack_require__ | @ | commons.js:725
  | (anonymous) | @ | commons.js:792
  | (anonymous) | @ | commons.js:795


```

**Comment by sophiebits** [comment] 2020-02-22 03:29
I think this may be caused by gatsby using the react-hot-loader, an unsupported project – but in any event, this isn't a bug in React so I'm going to close this issue. Thanks for filing.

(If you have an idea of how to fix the error, feel free to send a PR to the reactjs.org repo.)

**Closed by sophiebits** 2020-02-22 03:29 UTC
Labels: Status: Unconfirmed

**Comment by Corsairs** [comment] 2020-02-22 08:04
> I think this may be caused by gatsby using the react-hot-loader, an unsupported project – but in any event, this isn't a bug in React so I'm going to close this issue. Thanks for filing.
> 
> (If you have an idea of how to fix the error, feel free to send a PR to the reactjs.org repo.)

I'm trying to find a solution to the problem but so far to no avail
