### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read properties of null (reading 'match')

### ISSUE THREAD

**Issue by jiawen4760256** [facebook/react#24658] opened 2022-06-02 11:40 UTC
![image](https://user-images.githubusercontent.com/100251578/171621585-2ee26d9d-2ad1-4a9f-9db6-a7268fa12e40.png)

**Comment by eps1lon** [comment] 2022-06-02 16:19
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by drush** [comment] 2022-06-04 00:07
We are seeing similar issue with any hook usage.  Commenting out the hooks avoids the error.  Examples:

```
Cannot read properties of null (reading 'useContext')
Cannot read properties of null (reading 'useState')
```

**Comment by hamlim** [comment] 2022-06-04 17:33
@drush those errors seem unrelated from the original post, most likely in your case you might be using a version of React before `16.8` that introduced hooks. I'd confirm what version of react is being resolved and try upgrading!

**Comment by drush** [comment] 2022-06-04 18:25
@hamlin this may be on the right track, but the main project is on r17 and we have a branch with r18. The yarn.lock seems to only have references to target react version BUT we do see warnings during build that some sub-deps have unmet react version dependency. 

It seems like these warnings may actually be breaking errors. Maybe we are missing a tool that provides more explicit code tracing to know if these issues are critical.

**Comment by Binurim** [comment] 2022-06-24 06:36
> ![image](https://user-images.githubusercontent.com/100251578/171621585-2ee26d9d-2ad1-4a9f-9db6-a7268fa12e40.png)

I had this exact same issue in an Angular Application. But it was caused by a chrome extension. After the extension was removed this error didn't come.

**Comment by eps1lon** [comment] 2022-06-28 09:39
Closing since no repro has been provided in 3 weeks and people seem to be mistaken this issue with other (most likely unrelated) "cannot read properties of null" issues.

**Closed by eps1lon** 2022-06-28 09:39 UTC
Labels: Status: Unconfirmed, Resolution: Needs More Information

**Comment by ali037kazemi** [comment] 2022-07-27 11:12
> > ![image](https://user-images.githubusercontent.com/100251578/171621585-2ee26d9d-2ad1-4a9f-9db6-a7268fa12e40.png)
> 
> I had this exact same issue in an Angular Application. But it was caused by a chrome extension. After the extension was removed this error didn't come.

which extension? I have this issue too. is there another way to solve this?

**Comment by singhswapnil110** [comment] 2023-01-01 17:00
Facing a similar issue with useReducer hook
"react": "^18.2.0",
"react-dom": "^18.2.0"

<img width="833" alt="React_useReducer_Error" src="https://user-images.githubusercontent.com/34860120/210178884-aba37755-a0fb-4a77-8d4c-42f21a1302b7.png">

**Comment by singhswapnil110** [comment] 2023-01-01 19:50
> We are seeing similar issue with any hook usage. Commenting out the hooks avoids the error. Examples:
> 
> ```
> Cannot read properties of null (reading 'useContext')
> Cannot read properties of null (reading 'useState')
> ```

Was facing a similar issue with useReducer, turns out was accidentally calling the useReducer hook outside of a functional component.

**Comment by entitinhat** [comment] 2023-01-08 02:20
> > We are seeing similar issue with any hook usage. Commenting out the hooks avoids the error. Examples:
> > ```
> > Cannot read properties of null (reading 'useContext')
> > Cannot read properties of null (reading 'useState')
> > ```
> 
> Was facing a similar issue with useReducer, turns out was accidentally calling the useReducer hook outside of a functional component.

Iam having the same issue, can I ask how you fix that error?

**Comment by GabrielModog** [comment] 2023-01-25 07:55
I'm having same issue
![image](https://user-images.githubusercontent.com/1420545/214509103-2242116a-1dfe-478b-9b5e-bf3cfea0303a.png)
