### ISSUE TITLE
[DevTools Bug] Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by preyneyv** [facebook/react#22770] opened 2021-11-15 21:35 UTC
### Website or app

https://codesandbox.io/s/react-devtools-weird-bug-o3sib?file=/src/App.js

### Repro steps

I stumbled across the weirdest bug with React DevTools and hooks that causes it to error out when inspecting a component. A minimal test case is documented in the Code Sandbox link, along with more details on the behavior and seemingly-arbitrary fixes. This does not affect the actual functionality of the app itself in any way, it behaves exactly as expected.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.21.0-2f8f60ca8

### Error message (automated)

Cannot read properties of undefined (reading 'push')

### Error call stack (automated)

```text
at J (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:13006:7)
    at L (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:13040:10)
    at exports.inspectHooksOfFiber (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:13101:12)
    at inspectElementRaw (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:7732:65)
    at Object.inspectElement (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:8004:38)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:9837:56
    at Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:4257:18)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:10500:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:11737:9)
```

### Error component stack (automated)

```text
at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:38726:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37092:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37572:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40146:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35254:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35695:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42085:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37092:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37222:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37256:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37222:3)
    at SchedulingProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43423:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:41711:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30116:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30727:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37635:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53004:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot read properties of undefined (reading 'push') in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment] 2021-11-22 15:24
Thanks for the repro! Confirmed I can repro the problem on my end too.

Looks like the bug is coming from the `react-debug-tools` package, in the `buildTree` method.
```
TypeError: Cannot read properties of undefined (reading 'push')
    at buildTree (webpack-internal:///../../build/oss-experimental/react-debug-tools/cjs/react-debug-tools.development.js:571)
    at inspectHooks (webpack-internal:///../../build/oss-experimental/react-debug-tools/cjs/react-debug-tools.development.js:637)
    at inspectHooksOfFiber (webpack-internal:///../../build/oss-experimental/react-debug-tools/cjs/react-debug-tools.development.js:737)
    at inspectElementRaw (webpack-internal:///../react-devtools-shared/src/backend/renderer.js:2945)
    at Object.inspectElement (webpack-internal:///../react-devtools-shared/src/backend/renderer.js:3217)
    at eval (webpack-internal:///../react-devtools-shared/src/backend/agent.js:173)
    at Bridge.emit (events.js?9d21:37)
    at eval (bridge.js?1790:274)
    at listener (webpack-internal:///./src/backend.js:40)
```

Probably here:
https://github.com/facebook/react/blob/149b420f63903bcfb99455337a376c75384f86af/packages/react-debug-tools/src/ReactDebugHooks.js#L562-L564

**Comment by bvaughn** [comment] 2021-11-22 16:03
Given the naming of the hook in your repro:
```js
export default function App() {
  // (1a) This breaks React DevTools.
  function _useState() {
```

I believe this is a duplicate of #20613.

**Comment by bvaughn** [comment] 2021-11-22 16:07
Confirmed that renaming `_useState` to _anything else_ fixes the issue. Looks like a duplicate of #20613.

Going to close this one then since we have enough info on that one to document the problem.

**Closed by bvaughn** 2021-11-22 16:07 UTC
Labels: Type: Bug, Component: Developer Tools
