### ISSUE TITLE
Error: "Could not find commit data for root "226" and commit 6"

### ISSUE THREAD

**Issue by SMores** [facebook/react#17123] opened 2019-10-16 21:55 UTC
Describe what you were doing when the bug occurred:
1. Record a 5 second profile in the React Profiler Tab
2. Switch the React root in the dropdown

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.0-a8b8ffb89

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162685)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:332158)
    at sc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:332375)
    at fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59263)
    at Hi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:66573)
    at lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104884)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89467)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89392)
    at pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86341)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45721

Component stack: in sc
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by bvaughn** [comment] 2019-10-21 21:53
Duplicate of #16506

**Closed by bvaughn** 2019-10-21 21:53 UTC
