### ISSUE TITLE
blank space and line feed in Jsx

### ISSUE THREAD

**Issue by YeZhiqiuSev** [facebook/react#6637] opened 2016-04-28 03:13 UTC
as we all know,the render function return a html.The problem is, when i type space after 'return' and then connect HTML fragment,there is no problem.But there will be an error ` Uncaught TypeError: Cannot read property 'getNativeNode' of null` when i type enter to generate a new line and connect HTML fragment.I also checkout this 

> Currently, in a component's render, you can only return one node; if you have, say, a list of divs to return, you must wrap your components within a div, span or any other component.

> Don'tforget that JSX compiles into regular JS; returning two functions doesn't really make syntactic sense. Likewise, don't put more than one child in a ternary.

So,how to understand this problem?

**Comment by Aweary** [comment] 2016-04-28 03:19
> But there will be an error Uncaught TypeError: Cannot read property 'getNativeNode' of null when i type enter to generate a new line and connect HTML fragment

Can you share a code snippet demonstrating what you mean?

**Comment by keyanzhang** [comment] 2016-04-28 03:22
The "more than one node" part seems like a duplicate of #2127

**Comment by YeZhiqiuSev** [comment] 2016-04-28 03:24
1.type space afer 'return',no problem.
![image](https://cloud.githubusercontent.com/assets/18155748/14874492/762f7134-0d33-11e6-9d0c-8f0a45ef50fa.png)
2.make a new line,got an error.
![image](https://cloud.githubusercontent.com/assets/18155748/14874504/95d62366-0d33-11e6-8931-d81440d11438.png)
and I got an error that a mentioned before.

**Comment by Aweary** [comment] 2016-04-28 03:26
@YeZhiqiuSev you get that error because you're breaking to a new line after a `return` statement. In Javascript the return value is required to be on (or start on) the same line as the return value.

Try this instead:

```js

render: function() {
  return (
  <div className='main-content idc-instance-page'></div>
  )
}
```

**Comment by YeZhiqiuSev** [comment] 2016-04-28 03:32
@Aweary Thank you.It's a javascript rule .Got It.

**Closed** 2016-04-28 03:33 UTC
