### ISSUE TITLE
TypeError: inst.render is not a function when testing stateless functional components

### ISSUE THREAD

**Issue by udivankin** [facebook/react#5637] opened 2015-12-10 12:08 UTC
Functional component which looks like this
```
function DateTime({ dateTime }) {
  return <span>{(dateTime || new Date()).toLocaleDateString(currentLocale)}</span>;
}
```
being included to any conventional component causes this component's test failing with 
```
TypeError: inst.render is not a function
        at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:587:34)
        at ReactCompositeComponentMixin._renderValidatedComponent (node_modules/react/lib/ReactCompositeComponent.js:607:32)
        at ...
```

React 0.14.3, JEST 0.8.0, npm 3.5.2, node 5.2

Any suggestions on how to get rid of this?

**Comment by jimfb** [comment] 2015-12-10 18:21
Are you sure the react version is 0.14.3?  Can you provide a 0.14 fiddle that demonstrates the problem?

My fiddle: https://jsfiddle.net/4trs9u2r/

**Comment by udivankin** [comment] 2015-12-11 09:13
Your fiddle describes absolutely correct case and does not cause any problems in runtime, but if you try to test it with jest and smth like that
```
jest.autoMockOn();

import Hello from 'Hello';

describe('Hello', () => {
  let component;

  it('should render Hello', () => {
    const renderedComponents = TestUtils.scryRenderedComponentsWithType(component, Hello);
    expect(renderedComponents.length).toBe(1);
  });
});
```

this test will fail with an error specified above

**Comment by jimfb** [comment] 2015-12-11 17:35
Yeah, that's a bug in testutils.  This is only an issue in unit tests when you're using one of the ComponentWithType methods.  Tracking as duplicate of https://github.com/facebook/react/issues/4972.

**Closed by jimfb** 2015-12-11 17:35 UTC
Labels: Status: Unconfirmed
