### ISSUE TITLE
Bug: strict equality operator for comparison of oldProps and newProps and/or old & new context will not work since THOSE ARE OBJECTS

### ISSUE THREAD

**Issue by pPanda-beta** [facebook/react#17856] opened 2020-01-16 17:27 UTC
In React Fiber implementation everywhere prop objects are checked using "===" operator, which in case of object doesn’t verify using deep equality check, and works like a reference equality.
See below for the code mentions. 

React version:
16.12.0
React-Dom version:
16.11.0

## Steps To Reproduce

1. Write the following code to test it.
2. Check in the console.

```js

const logDifferences = (nameOfComponent) => (oldProps, newProps) => {
  const serializedOldProps = JSON.stringify(oldProps);
  const serializedNewProps = JSON.stringify(newProps);
  console.warn(`[${nameOfComponent}] Differences --> `, "old props :", serializedOldProps, "new props :", serializedNewProps, "verdict : ", serializedOldProps !== serializedNewProps);
};

class Child extends React.Component {
  componentWillReceiveProps (nextProps, nextContext) {
    logDifferences("Child")(this.props, nextProps);
  }

  render () {
    return (<>Child got rendered at : {new Date().toISOString()}</>);
  }
}

class SweetChild extends React.PureComponent {
  componentWillReceiveProps (nextProps, nextContext) {
    logDifferences("SweetChild")(this.props, nextProps);
  }

  render () {
    return (<>Sweet Child got rendered at : {new Date().toISOString()}</>);
  }
}

class Parent extends React.Component {
  state = {currentDate: new Date()};

  componentDidMount() {
    setInterval(()=> this.setState({currentDate: new Date()}), 500);
  }
  
  render() {    
    return (
      <div>
        Parent state updated at : {this.state.currentDate.toISOString()}
        <br />
        <Child a="1" b={4}/>
        <br />
        <SweetChild a="1" b={4}/>
      </div>
    );
  }
} 

ReactDOM.render(<Parent />, document.body);

```

Link to code example:

https://codepen.io/ppanda-beta/pen/gObdvwO?editors=0011

## The current behavior
For Component instances, `componentWillReceiveProps` is  called and component is re rendered
For PureComponent instances, `componentWillReceiveProps` is  called but component is not re rendered when props are `shallowEqual`

## The expected behavior
For both Component and PureComponent, componentWillReceiveProps should not be called, and not rerendered. 

## Possible reasons 
https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/react-reconciler/src/ReactFiberClassComponent.js#L1034
https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/react-reconciler/src/ReactFiberClassComponent.js#L1051-L1056
https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/react-reconciler/src/ReactFiberClassComponent.js#L1052-L1053
https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/react-reconciler/src/ReactFiberClassComponent.js#L1069-L1070
https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/react-reconciler/src/ReactFiberClassComponent.js#L1060-L1063
https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/react-reconciler/src/ReactFiberClassComponent.js#L286-L288

## Temporary Solution
Override `  shouldComponentUpdate(nextProps, nextState, nextContext)` to stop extra re-rendering.

**Comment by threepointone** [comment] 2020-01-21 15:03
This is expected behaviour, React does not do shallow comparison by default (otherwise, every component would be memoized). This is also why `shouldComponentUpdate`/`.memo` are provided. 

Closing since this is expected behaviour.

**Closed by threepointone** 2020-01-21 15:03 UTC
Labels: Status: Unconfirmed
