### ISSUE TITLE
Error: "f.hasOwnProperty is not a function"

### ISSUE THREAD

**Issue by MichaelOstrovsky** [facebook/react#17819] opened 2020-01-10 11:31 UTC
Describe what you were doing when the bug occurred:
1. Opened components tree
2. Clicked Context.Provider
3. Clicked "SomeProvider" component right above that Context.Provider

This issue does not happen if I click "SomeProvider" first. only after clicking Context.Provider within this "SomeProvider" wrapper component.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.3.0-3e0967783

Call stack: at ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:268899)
    at ii (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59363)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:107431)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99973)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99898)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:96672)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:46436
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:3676)
    at $o (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:46146)
    at na (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:46382)

Component stack: in ha
    in div
    in ya
    in Ea
    in div
    in div
    in ya
    in Ea
    in div
    in Unknown
    in div
    in bi
    in div
    in Ai
    in Suspense
    in ei
    in div
    in div
    in la
    in Ur
    in vo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Qi
    in Ve
    in nn
    in Da
    in Yc

**Comment by lunaruan** [comment] 2020-01-10 18:25
Hello! Thanks for reporting this issue. This bug was most likely fixed in  #17768 for v4.4.0. Fortunately that version went live in the Chrome store a couple of days ago, so it should be deployed to your browser soon!

I'm going to close this issue since it's been fixed on our end. If you're still able to reproduce it with version 4.4.0 please let us know and we'll reopen the issue.
cc: @bvaughn

**Closed by lunaruan** 2020-01-10 18:25 UTC

**Comment by bvaughn** [comment] 2020-01-10 18:39
Thanks for the tag, Luna!

Try restarting your browser to see if it picks up the new version of the extension, @MichaelOstrovsky. Worst case, you could always uninstall and reinstall.
