### ISSUE TITLE
bug* element.scrollIntoView()

### ISSUE THREAD

**Issue by ado-astpos** [facebook/react#15915] opened 2019-06-18 20:57 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am attempting to do 
`formHandlerRef =  React.createRef()`
then attach it to an MDB Col as a ref

pass this down as props to another component
`scrollToFormHandler = () => {
   const formHandler = this.formHandlerRef.current;
   formHandler.scrollIntoView({ behavior: 'smooth', block: 'start', inline: 'start' });
  };`

and call the function from a child component.

**What is the expected behavior?**

The intended behavior is when the props function is fired off in the child component (after the formHandler component has been rendered and is on another part of the screen) to scroll into view which I have achieved with the following code.

`scrollToFormHandler = () => {
    // eslint-disable-next-line react/no-find-dom-node
    const formHandler = ReactDOM.findDOMNode(this.formHandlerRef.current);
    formHandler.scrollIntoView({ behavior: 'smooth', block: 'start', inline: 'start' });
  };`

I have looked online and tried finding any other situations where this was a problem or something I may be missing but have found nothing yet so I am coming here. This may be a problem on my end but just wanted to bring it up in case.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am using `create-react-app`
`    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^3.0.1"
 `
Thank you!

**Comment by ee92** [comment] 2019-06-19 01:44
The child component renders before the parent, at which point the ref doesn't exist yet. This might be causing your problem. 

Are you getting any error? Like "cannot call scrollIntoView on undefined" or something like that?

**Comment by ado-astpos** [comment] 2019-06-19 16:57
Yes, that is exactly the error I'm getting:
`Uncaught (in promise) TypeError: formHandler.scrollIntoView is not a function
    at MenuBuilder._this.scrollToFormHandler (MenuBuilder.js:211)`

I also get this when I console log formHandler.current:
`Col {props: {…}, context: {…}, refs: {…}, updater: {…}, _reactInternalFiber: FiberNode, …}
context: {}
props: {lg: "7", className: "my-lg-5 offset-lg-5 formhandler-phone-margin", children: {…}, tag: "div", xs: null, …}
refs: {}
state: null

The scrollToFormHandler is a method on the menuBuilder component and the `formHandlerRef = React.createRef();` is also on the menuBuilder component, which is also the only one that renders the formHandler component.

Thank you for the help.

**Comment by ee92** [comment] 2019-06-19 18:30
I assume you are trying to call that function in componentDidMount of the FormHandler component.

Since children always mount before parents, the MenuBuilder component is not yet mounted or rendered, so the ref still has no DOM element to point to. 

You might try calling the function in componentDidUpdate instead, checking that `formHandlerRef.current` actually exists.

But ideally you would want to have your formHandlerRef inside your FormHandler component, not in the parent. So maybe re-think why you are doing that in the first place?

**Comment by ado-astpos** [comment] 2019-06-19 18:52
I am calling it as a method on the MenuBuilder component that I then pass down as a prop to a different component rendered by MenuBuilder (NavHandler) to be called after all components have been rendered (on a button click).

My thinking behind this was to have a central place for this function so I can change the scroll behavior easily in the future and simplify child components of MenuBuilder.

But I did not know that children render before parents that is good to know, thank you.

Should I be calling this ref and the .scrollIntoView() method separately on the FormHandler component each time I want to use it instead? And if so what's wrong with my method?

**Comment by ee92** [comment] 2019-06-19 19:32
It's not very clear what you are trying to do, but if you are getting that error, it means your ref is not pointing to a DOM element (so it doesn't have the `scrollIntoView` method).

I noticed you are using `findDOMNode` which is at best redundant because `formHandlerRef.current` should already be a pointer to a DOM node.

My guess is that you are [attaching the ref to a functional component](https://reactjs.org/docs/refs-and-the-dom.html#refs-and-function-components) which does not work.

**Comment by ado-astpos** [comment] 2019-06-19 20:41
I may not be describing the situation correctly, but both components rendered by MenuBuilder (FormHandler and NavHandler) are class components.

I am using `findDOMNode` because it is the only thing that worked after trying multiple different options.

I know the ref works because I am using it to find the DOM Node (the DOMNode I am finding is `this.formHandlerRef.current`):
 
This is my whole method on the MenuBuilder component that I pass down in props to NavHandler:
`scrollToFormHandler = () => {
    // eslint-disable-next-line react/no-find-dom-node
    const formHandler = ReactDOM.findDOMNode(this.formHandlerRef.current);
    formHandler.scrollIntoView({ behavior: 'smooth', block: 'start', inline: 'start' });
  };`

what should have worked is this:
`scrollToFormHandler = () => {
this.formHandlerRef.currentscrollIntoView({ behavior: 'smooth', block: 'start', inline: 'start' });
  };`
but for some reason it throws me the error described before.

**Comment by ee92** [comment] 2019-06-19 21:32
Still unsure what you are trying to achieve but I tried to recreate a [minimal example](https://codesandbox.io/s/friendly-dirac-p40qg?fontsize=14).

Not sure if this is what you're going for but it all seems to work as expected. Feel free to edit the code to make it reproduce your error.

**Comment by threepointone** [comment] 2019-09-05 12:28
This appears to be a usage question, rather than a bug/feature request. I'm going to close the issue, but feel free to carry on the discussion.

**Closed by threepointone** 2019-09-05 12:28 UTC

**Comment by fangyuan** [comment] 2019-11-16 15:47
@ado-astpos is `ref` bind to  html tag`<HTMLElement>`? I met with the same error, when I use antd `Input` component and bind `ref` to `Input`, however `Input` component is not a `HTMLElment`. You could try bind ref with html tag. Hope it helps.
