### ISSUE TITLE
Breaking error in IE 8

### ISSUE THREAD

**Issue by Dharmoslap** [facebook/react#6291] opened 2016-03-18 10:53 UTC
![virtualbox_ie8 - win7_18_03_2016_10_50_19](https://cloud.githubusercontent.com/assets/3543614/13875677/8e46df68-ecff-11e5-92f8-2d1b0e492a0a.png)

How to replicate this issue

1. run Windows 7 with IE 8 on VirtualBox [https://dev.windows.com/en-us/microsoft-edge/tools/vms/](https://dev.windows.com/en-us/microsoft-edge/tools/vms/)
2. clone this repo https://github.com/Dharmoslap/react-select
3. run "npm start" and open http://10.0.2.2 in IE 8
4. try to select different options in select component and the error will appear

Although it's not fancy at all, I still need to support IE 8 for a few more months.

Thanks

**Comment by gaearon** [comment] 2016-03-18 11:26
What is the exact line of code throwing the error? Can you show the call stack please?

**Comment by gaearon** [comment] 2016-03-20 21:01
Debugging experience in IE8 is truly abysmal. :smile: 

I was able to get it to break at the actual error site after removing a few `try-catch`es from React. The line in question is here:

<img width="661" alt="screen shot 2016-03-20 at 20 55 35" src="https://cloud.githubusercontent.com/assets/810438/13907091/3a7d7488-eede-11e5-8a6e-f7b3a6a6b218.png">

As you can see it is not related to React. Apparently [`isEqualNode()` is only supported since IE9](https://msdn.microsoft.com/en-us/library/ff975128(v=vs.85).aspx). See also information on [quirksmode](http://quirksmode.org/dom/core/) about this.

The usage is [located in react-select code](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L313) so you may ask them to fix it. I’m not sure why it is using `isEqualNode` rather than just `===` comparison there.

In any case, this is not a bug in React, so I will close this.

**Closed by gaearon** 2016-03-20 21:01 UTC
