### ISSUE TITLE
Hooks at a Glance

### ISSUE THREAD

**Issue by tomasdelaveau** [facebook/react#21725] opened 2021-06-23 00:58 UTC
In the _Effect Hook_ section, it reads **By default, React runs the effects after every render — including the first render.**
I just copied and pasted the example in a Next JS page, and upon page load (ie. first render) I see the title remains unchanged (even if I remove the `<title>` tag from the head in `_app.js`). It only changes to "You clicked 1 times" after the first click (ie. second render).

**Comment by bvaughn** [comment] 2021-06-23 19:12
Hi!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-07-14 22:55
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-07-14 22:55 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
