### ISSUE TITLE
The components panel is blank unless I minify my React code

### ISSUE THREAD

**Issue by dfenske** [facebook/react#20109] opened 2020-10-27 17:53 UTC
Hello,

I am using NextJS to build an application. We have had this application running for a couple years now, but recently the dev tools have broken on our local build. 

When I run my node application locally, the Components panel is blank. If I minify my code and run the compiled code, I see components in the panel. Can you help me solve this bug? I see no related console errors and I can't find any other way to debug or understand what is causing this problem.
![image](https://user-images.githubusercontent.com/4571750/97341421-46d1e100-1842-11eb-8912-99fec17b6aa2.png)
![image](https://user-images.githubusercontent.com/4571750/97341654-94e6e480-1842-11eb-9968-d3ad3bc5a39d.png)

**Comment by bvaughn** [comment] 2020-10-27 20:41
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-11-07 14:39
Closing this issue due to lack of repro info or issue updates. We can re-open if updates come in.

**Closed by bvaughn** 2020-11-07 14:39 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed
