### ISSUE TITLE
Issue #5929 still happening on IE 10.  React.cloneElement handles `undefined` props differently to React.createElement

### ISSUE THREAD

**Issue by squon66** [facebook/react#8343] opened 2016-11-18 15:30 UTC
I know this issue has been addressed previously but it still seems to be happening on IE 10 browsers.  When I use cloneElement, all the defaultProps values come up as 'undefined' if not explicitly sent in as a prop

**Comment by gaearon** [comment] 2017-10-04 14:35
I would be surprised if that was the case since most apps would break.
Therefore, it's probably something localized to your app.

Since there's no reproducible test case in this issue, there's no way to verify what happened.
So I'm closing this.

**Closed by gaearon** 2017-10-04 14:35 UTC
