### ISSUE TITLE
npm start error on Mac

### ISSUE THREAD

**Issue by DavidRNogueira** [facebook/react#16719] opened 2019-09-10 01:19 UTC
I keep getting this error when plugging in npm start to the system. Any ideas?

`Davids-MacBook-Air:davidsapp davidnogueira$ npm start

> davidsapp@0.1.0 start /Users/davidnogueira/Documents/React:Redux/davidsapp
> react-scripts start

sh: react-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! davidsapp@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the davidsapp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidnogueira/.npm/_logs/2019-09-10T01_15_07_461Z-debug.log
Davids-MacBook-Air:davidsapp davidnogueira$ `

**Comment by threepointone** [comment] 2019-09-10 07:58
Have you run `yarn` or `non install` in this directory before? I’d guess you haven’t installed dependencies yet. 

Closing because there’s no reproducing example, happy to re-examine if you can share a git repo that demonstrates the problem.

**Closed by threepointone** 2019-09-10 07:58 UTC

**Comment by DavidRNogueira** [comment] 2019-09-10 20:51
I'm not sure what file you need to see in a github repo. No, I haven't run yarn or non install. All I have done is `npx create-react-app davidsapp` and `cd davidsapp` and `npm install` (which gives me tons of warnings). Please let me know what to provide. Thanks

**Comment by threepointone** [comment] 2019-09-10 21:14
What are the warnings that you get? Could you paste it into gist.github.com and share the link?

**Comment by DavidRNogueira** [comment] 2019-09-11 22:56
https://gist.github.com/DavidRNogueira/da37a599c37ad8661c55bf599b7e0751
