### ISSUE TITLE
React and react-router. If I create a component it calls render(). If not a component it is good without render(). It's crazy

### ISSUE THREAD

**Issue by johnunclesam** [facebook/react#11574] opened 2017-11-16 18:47 UTC
Here is the link to [Sandbox][1]

I have simple code like this:

**Sidebar.js**:

    import React, { Component } from "react";
    import { BrowserRouter as Router, Route, NavLink } from "react-router-dom";
    
    import Menu from "./Menu";
    
    class SidebarExample extends Component {
      render() {
        console.log("Sidebar - render()", new Date());
        return (
          <Router>
            <div>
              <div>
                If I uncomment the below component Menu the render() method of the component is called everytime I change the link. Why? In the Menu component the is the same html code below. What is going on?
                {/*<Menu />*/}
                <ul>
                  <li>
                    <NavLink exact to="/">
                      Home
                    </NavLink>
                  </li>
                  <li>
                    <NavLink to="/bubblegum">Bubblegum</NavLink>
                  </li>
                  <li>
                    <NavLink to="/shoelaces">Shoelaces</NavLink>
                  </li>
                </ul>
              </div>
            </div>
          </Router>
        );
      }
    }
    
    export default SidebarExample;

**Menu.js**:

    import React, { Component } from "react";
    import { NavLink } from "react-router-dom";
    
    class Menu extends Component {
      render() {
        console.log("Menu - render()", new Date());
        return (
          <ul>
            <li>
              <NavLink exact to="/">
                Home
              </NavLink>
            </li>
            <li>
              <NavLink to="/bubblegum">Bubblegum</NavLink>
            </li>
            <li>
              <NavLink to="/shoelaces">Shoelaces</NavLink>
            </li>
          </ul>
        );
      }
    }
    
    export default Menu;

If I uncomment the component the render() method of the component is called everytime I change the link. Why? In the Menu component there is the same html code below.

**What is going on?**

I'm loosing my mind!

  [1]: http://codesandbox.io/s/34r1l9wl4m

**Comment by phc5** [comment] 2017-11-16 19:04
Hi @johnunclesam, if I'm not mistaken that is the expected behavior. Uncommenting `<Menu />` inside the render method of `Sidebar.js` will render whatever is returned in the render method of `<Menu />`. See [Composing Components](https://reactjs.org/docs/components-and-props.html/#composing-components) in the React docs.

**Comment by johnunclesam** [comment] 2017-11-16 19:15
Thanks @phc5. I don't find anything related to this "issue" there. but I know it's my fault. Wher I fall? What I miss? Why React have to re-render any time if the same code is in a simply component?

**Comment by phc5** [comment] 2017-11-16 19:35
You could perhaps do something like this since it looks like the JSX in `Sidebar.js` is duplicate of `Menu.js`:
**Sidebar.js**
```
import React, { Component } from "react";
import { BrowserRouter as Router, Route, NavLink } from "react-router-dom";

import Menu from "./Menu";

class SidebarExample extends Component {
  render() {
    return (
      <Router>
            <Menu />
      </Router>
    );
  }
}

export default SidebarExample;
```

**Comment by gaearon** [comment] 2017-11-17 01:55
We use issue tracker for React bugs and feature requests. This looks like a question. Please use a more appropriate venue for support requests: https://reactjs.org/community/support.html. Thanks!

**Closed by gaearon** 2017-11-17 01:55 UTC
