### ISSUE TITLE
[Bug] Clicked button error

### ISSUE THREAD

**Issue by koansang** [facebook/react#12659] opened 2018-04-20 06:22 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
button click

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
if clicked button, occur error then remove components.
![image](https://user-images.githubusercontent.com/12390185/39033733-74517588-44ae-11e8-89f2-b3bf2965a2cf.png)

onClick event is: 
```js
  closeTutorial = (e) => {
    e.stopPropagation();
    e.preventDefault();

    this.setState({
      showTutorial: false,
    });
  }
```

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react - 16.3.1
react - 16.3.1
browser - chrome
OS - window10

**Comment by raunofreiberg** [comment] 2018-04-20 12:41
Can you provide more information by creating a reduced test case on https://codesandbox.io/s/new? I can't reproduce this on my own.

**Comment by eduardobudant** [comment] 2018-04-25 18:24
Can I take this one?

**Comment by aweary** [comment] 2018-04-25 21:29
@eduardobudant there's nothing here to take, @koansang hasn't provided enough information about his issue 🙂Since there's been no follow up, I'm going to close this out.

**Closed by aweary** 2018-04-25 21:29 UTC
