### ISSUE TITLE
Calling onBlur and mutating state can cause onClick to not fire. 

### ISSUE THREAD

**Issue by BJK** [facebook/react#4210] opened 2015-06-24 14:52 UTC
We encountered this while trying to have different parts of form validation happen on both the onBlur and the onClick. It seems that if you update State on an onBlur, and that state element is injected into the DOM via JSX, positionally ABOVE a button with an onClick--the onClick will not fire. 

I believe this is related to this issue: https://github.com/facebook/react/issues/2291

See this http://jsfiddle.net/kb3gN/11477/ which is a variation on the example provided above. If you enter some text, you'll have to click the button twice, to see click: true.

Not 100% confident that order matters in the DOM, but you can see it consistently reproducable in the JSFiddle above. 

 @andela-domonori first noticed the weird behavior.

**Comment by syranide** [comment] 2015-06-24 15:02
This is browser behavior and it seems entirely correct to me. The button receives the mouse down event but since the element moves immediately after then mouse up happens outside and no click is registered. Do the same thing but move your cursor back over the button first and then release, now you get the click as expected.

**Comment by jimfb** [comment] 2015-06-24 15:40
Confirmed, it looks like the issue is that you're not getting a click as a result of the button moving.  If you put the error output under the button (such that it won't affect the positioning of the button), everything behaves as expected (so it's not an issue related to mutating state, it's an issue related to you moving things in the dom).  Also, all the things @syranide pointed out.  I'm going to close this as "not a react issue".

**Closed by jimfb** 2015-06-24 15:40 UTC

**Comment by chhikaradi1993** [comment] 2019-07-15 17:11
@OndeVai OndeVai - This is a valid issue. I am also encountering this

**Comment by chhikaradi1993** [comment] 2019-07-15 17:20
For me there is no error in any state. My form is filled and valid. But I am doing field validation on blur event then my component is rerendering and onClick event is not firing.

**Comment by ashkart** [comment] 2019-08-05 15:05
I switch my "isEditState" flag on my "EditableField" component in onBlur for the input which fired when I click "Ok" button to save input text (And on clicking somewhere else I drop text changes in that onBlur callback). So the onClick event doesnt fire when 'Ok' clicked. I do not do any movements in a DOM tree.

**Comment by nguyenhoavuong** [comment] 2019-09-20 03:27
It seem like blur  event causes a rerender component. I have a simple solution: 
**using onMouseLeave event instead of using onBlur**
But it's not perfect solution because my input will lost typing when mouse leave the input

**Comment by dashName** [comment] 2019-12-19 20:26
> It seem like blur event causes a rerender component. I have a simple solution to improve:
> **using onMouseLeave event instead of using onBlur**
> But it's not perfect solution because my input will lost typing when mouse leave the input
onMouseLeave={hideMe}
...
...
 hideMe = (e) => {
        const currentTarget = e.currentTarget;
        setTimeout(()=>{
            if (!currentTarget.contains(document.activeElement)) {
                this.setState({ showSuggestions: false })
            }
        }, 0);
    };
this works!

**Comment by anton-thushara** [comment] 2020-05-14 05:48
i experienced the same issue and found a workaround.

onBlur={() => setTimeout(onBlur, 500)}

override the onBlur and delay it a bit. basically delay what ever should happen after onBlur by about 500ms.

**Comment by vipcxj** [comment] 2020-07-04 16:36
Why closed? Five years passing, so many people have to suffer from this issue.

**Comment by johnneuland** [comment] 2020-09-02 11:14
@anton-thushara  @dashName @jimfb Could you look into problem please? A codesandbox is also given. https://stackoverflow.com/questions/63686646/stop-handleblur-from-doing-anything

**Comment by benbakle** [comment] 2020-10-22 02:12
The work around using `setTimeout` works because events are fired in order of priority.  The event listener `click` comes after `blur` in priority. This causes a `blur` to fire but not the `click`.  You can use `mousedown` instead of `click` due to it's priority over `blur`. By using `setTimeout` on the `blur` it delays the `blur` and allows for the `click` to take priority.

**Comment by gaearon** [comment] 2020-10-22 11:52
If there is a React bug here please file a new issue. We don’t track discussions on closed issues.

**Comment by charleswritescode** [comment] 2021-01-14 16:52
If it helps anybody, this is how I solved it in my event handler

`event.relatedTarget?.click()`

**Comment by brianpursley** [comment] 2021-04-30 18:22
> If it helps anybody, this is how I solved it in my event handler
> 
> `event.relatedTarget?.click()`

Almost.

This works for the scenario where you click on a button, but if you just tab to the next control, which happens to be a button, it clicks it, which is not the tab behavior you want.

**Comment by JounQin** [comment] 2021-09-16 10:06
Using `onMouseDown` to replace `onClick` seems working to me.

**Comment by lortiz-daitan** [comment] 2021-10-04 18:52
In my case, I had to make some components appear/disapear based on a state controlled by the `onBlur`. So, the `onClick` of the other was not working because the scroll was being changed after the `onBlur`, when the new elements were added at the DOM.

The `onMouseDown` worked partially for me. The click worked, but the `onBlur` stopped being called.

My solution was to keep the `onClick` and add a `setTimeout` of 100ms inside the `onBlur`. So, the click can be executed before the `onBlur` mutates the state and cause all the consequences (rerendering + add the new elements at the DOM + change scroll)

**Comment by purushothaman-source** [comment] 2021-10-05 10:09
> The `onMouseDown` worked partially for me. The click worked, but the `onBlur` stopped being called.
> 
@lortiz-daitan same issue I faced recently in my case also there is appear/ disappear element s the onMouseDown will solve this issue ...this is event order `onMouseDown -> onMouseUp -> onBlur -> onClick` ...if you put event.preventDefault() inside onMouseDown function then onBlur won't fire ...

https://codepen.io/mudassir0909/pen/eIHqB

And also you have to be careful ,when using onMouseDown ,because it will trigger for left/right/mouse wheel click ..
you can check which key is pressed  using event.button if it returns 0 it means left click is happened if it is 1 it means wheel is clicked if it is 2 it means right click is happened ..

**Comment by LuisJoseLopezD** [comment] 2022-02-19 01:36
> Using `onMouseDown` to replace `onClick` seems working to me.

this shit works

**Comment by contigen** [comment] 2023-04-07 11:46
Calling the .click() method in a focus event's handler works for my use case; anyhow, is this a react thing, I'll know how to write my code comment better

**Comment by dung28-td** [comment] 2023-09-27 04:12
Try to group all elements before element has onClick in a `div` or something else.

This won't work
```tsx
<input onBlur={/* validate ... */} />
{error && <span>{error}</span>}
<button onClick={/* handleClick */}>Submit</button>
```

But this will work
```tsx
<div>
  <input onBlur={/* validate ... */} />
  {error && <span>{error}</span>}
</div>
<button onClick={/* handleClick */}>Submit</button>
```

**Comment by quangv** [comment] 2024-02-21 20:44
FYI, `onMouseDown` doesn't allow for pointer cancellation, thus making it inaccessible and breaks [WCAG](https://www.w3.org/TR/WCAG22/#pointer-cancellation), I believe.

**Comment by sjin66** [comment] 2024-08-20 06:44
In React 18, you can wrap operations that trigger a re-render in the new "startTransition" method. "startTransition" allows you to update state without blocking the UI.
