### ISSUE TITLE
[DevTools Bug]: _jsxDEV is not a function

### ISSUE THREAD

**Issue by avishihora** [facebook/react#27834] opened 2023-12-13 18:28 UTC
### Website or app

https://lp-y3y1.onrender.com/

### Repro steps

I have deployed my website on render. Render ( Hosting Platform ) shows me successful deploy but I am not able see anything. Can anyone guide me !?

### How often does this bug happen?

Every time

**Comment by Hackoverflow3** [comment] 2023-12-13 22:57
is it a static website or dymanic website ?

**Comment by Janelaxagh** [comment] 2023-12-15 15:12
Apologies for the typo. Here's the revised content:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- React Refresh scripts for development -->
  <script type="module">
    import { injectIntoGlobalHook } from "/@react-refresh";
    injectIntoGlobalHook(window);
    window.$RefreshReg$ = () => {};
    window.$RefreshSig$ = () => (type) => type;
  </script>

  <!-- Vite development client script -->
  <script type="module" src="/@vite/client"></script>

  <meta charset="UTF-8" />
  <link rel="icon" type="image/*" href="/src/assets/images/android-chrome-512x512.png" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <!-- Your generated output.css -->
  <link href="/dist/output.css" rel="stylesheet" />
  
  <title>Avi Shihora</title>
</head>
<body>
  <div id="root"></div>
  
  <!-- Main React app script -->
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
```

This HTML file contains the foundational structure for your application, including linked React scripts, stylesheets, and the entry point for your application within the `<div id="root">` tag. Additionally, it includes a stylesheet named `output.css`, which is located at `/dist/output.css`.
And the file name is output.css for some reason

**Comment by mxmalykhin** [comment] 2023-12-22 03:20
Hi, I looked at your link and I think I found the reason for [this issue](https://github.com/vitejs/vite/issues/5885) in Vite. They offer several solutions. You can try updating the [React plugin](https://github.com/vitejs/vite/issues/5885#issuecomment-1152978143) for Vite or try [changing the env](https://github.com/vitejs/vite/issues/5885#issuecomment-1020082111).

**Comment by hoxyq** [comment] 2024-01-02 13:47
This doesn't look like a DevTools problem, so I am going to close this. Please reopen if you can provide more context on this, including the reproducer.

**Closed by hoxyq** 2024-01-02 13:47 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools
