### ISSUE TITLE
Object tags fatally crash React apps in Chrome 56 and above (node cache issue)

### ISSUE THREAD

**Issue by 43081j** [facebook/react#8718] opened 2017-01-09 11:24 UTC
Since the recent update to Chrome in the Canary and Beta branches, React apps which contain an object tag fail fatally (rendering is halted due to internal exception).

This is because it seems the chromium devs have altered the following:

```
let foo = document.createElement('object');
foo.test = 5;
// foo.test is undefined here in Chome 56 (beta)
```

The reason this kills react is [this line](https://github.com/facebook/react/blob/aca2e0403691a2842d4a9d8964c9b1016e248b6a/src/renderers/dom/shared/ReactDOMComponentTree.js#L60).

We try stick some arbitrary object onto the end of the element (a cached HTMLElement -> component relationship i suppose). So if an object tag hits this caching code, it'll throw an exception eventually when something tries to access the instance.

This means if the change reaches Chrome stable, too, quite a few react apps could "randomly" stop working (as users update their browsers).

**Comment by gaearon** [comment] 2017-01-09 13:24
>This means if the change reaches Chrome stable, too, quite a few react apps could "randomly" stop working (as users update their browsers).

Have you filed a bug with Chromium? Any browser crashes are bugs in their code—unfortunately React team is not in a position to fix them.

**Comment by gaearon** [comment] 2017-01-09 13:29
Also can you provide an exact way to reproduce?
https://jsfiddle.net/7eyrfyjg/ doesn't crash Canary for me.

**Comment by 43081j** [comment] 2017-01-09 13:55
This is because the exception comes from React, when it tries to access what it now thinks is defined (but isn't).

I'm not able to get an example up at the minute (mobile) but a simple react component which produces an object tag should do the job.

I have not filed a bug with Chromium because i assumed it is to-spec, what they have changed. However, if it reaches stable, it will break plenty of React apps, I'm sure (anyone who uses an object tag, possibly even Facebook, for fallback video rendering maybe).

It seems React shouldn't really be throwing arbitrary properties onto well-defined elements (classes essentially, HTMLElement, etc). But also Chromium shouldn't be introducing breaking changes like that I guess.

**Comment by 43081j** [comment] 2017-01-09 13:57
Also, from what I remember, the exception I saw came from a non-production related block trying to access the node caches.

So its also possible this won't affect production builds but only dev ones, hopefully.

**Comment by gaearon** [comment] 2017-01-09 14:07
>It seems React shouldn't really be throwing arbitrary properties onto well-defined elements (classes essentially, HTMLElement, etc).

AFAIK this is how the vast majority of libraries that operate on DOM work.

**Comment by 43081j** [comment] 2017-01-09 14:13
Quite a few do, that's true, however it doesn't make it any better to do.

But that's beyond the scope of this issue. I suppose the React devs would rather Chromium revert the change, but still it is worth investigating from this end too.

**Comment by gaearon** [comment] 2017-01-09 14:18
What would really help is a small repro that consistently shows the problem without React itself.

**Comment by gaearon** [comment] 2017-01-09 14:19
OK, I got one: https://jsfiddle.net/s74spneo/.
Will file a bug.

**Comment by gaearon** [comment] 2017-01-09 14:26
Filed as https://bugs.chromium.org/p/chromium/issues/detail?id=679345.
Since it’s not actionable on our side, closing this issue.
Thanks for reporting.

**Closed by gaearon** 2017-01-09 14:26 UTC

**Comment by thom-nic** [comment] 2017-01-16 21:03
I just stumbled upon this after Chrome Beta prompted me to update.  This issue might find more traffic as it's now affecting the Beta channel.  Are there any possible workarounds aside from "don't use Chrome Canary/ Beta" in development or "avoid using `<object>` tags?

**Comment by gaearon** [comment] 2017-01-16 21:07
FWIW the fix was already merged to Chrome.

**Comment by thom-nic** [comment] 2017-01-16 21:09
I noticed that - I was about to try Chrome Canary and see if the issue is fixed there.  Will update with findings.
