### ISSUE TITLE
Number Input with defaultValue does not accept decimal input

### ISSUE THREAD

**Issue by dphaener** [facebook/react#8211] opened 2016-11-05 04:43 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When using a number input that has a defaultValue, you cannot enter a decimal value. When attempting to type a decimal, the cursor is moved to the beginning of the input. This behavior is *not* observed when there is no defaultValue given.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://jsfiddle.net/zc0x3egz/

**What is the expected behavior?**
The input should allow you to type a decimal.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is happening with React 15.3.2. It does *not* happen in 0.14.x

**Comment by LadyYoung957** [comment] 2016-11-05 04:48
Lmao y'all never get in boyy

**Comment by nhunzaker** [comment] 2016-11-05 13:17
Hey! I fixed this with https://github.com/facebook/react/pull/7750. However it looks like it hasn't made its way to a release yet.

**Comment by Aweary** [comment] 2016-11-05 15:18
#7750 is not included in the 15.4.0 release as far as I can tell. At this point it might be too late to include it since the RCs have been out for a while, and #7750 is a change that we'd likely want tested in RCs before releasing.

**Comment by nhunzaker** [comment] 2016-11-05 15:20
Totally understandable. Please let me know if I can help in any way.

**Comment by Aweary** [comment] 2016-11-05 15:23
I think @gaearon is managing releases now? Not sure with all the recent roster changes 😄 

Going to close this out as well, since it's essentially a duplicate of https://github.com/facebook/react/issues/7253 and a fix is already merged into master.

**Closed by Aweary** 2016-11-05 15:23 UTC
