### ISSUE TITLE
Bug: Parent rerenders unnecessarily on Child-to-Parent setter call, while child rerenders only when changes occur.

### ISSUE THREAD

**Issue by taku-271** [facebook/react#28287] opened 2024-02-09 04:16 UTC
React version: 18

## Steps To Reproduce

1. Define state in the parent component.
```typescript
const [state, setState] = useState();
```
2. Render the child component and pass the function to modify the parent component's state to the child component.
```html
<ChildComponent setState={setState} />
```
3. Calls the setter but does not change the value of state.
```typescript
setState((state) => state + 0);
```

Link to code example: https://codesandbox.io/p/sandbox/rendering-test-vts4v2?file=%2Fsrc%2FApp.js%3A3%2C20

## The current behavior
The parent component rerenders even if the state remains unchanged.
When the parent component rerenders only due to unchanged state, the child component does not rerender.
![image](https://github.com/facebook/react/assets/87481129/be7d453b-595c-4509-a2af-c7a81b608058)

If the value of state has been changed, the child components are rerendered.
![image](https://github.com/facebook/react/assets/87481129/28268d31-d080-4db2-a69e-8346819701be)

## The expected behavior
The parent component should not rerender if the state remains unchanged.
If the parent component rerenders, the child component should also rerender.

**Comment by markerikson** [comment] 2024-02-09 05:33
This is expected behavior.

React queues state updates, and applies them in the render phase.  If the new state value returned is identical to the previous value, React will bail out of the render for that component.  If nothing else forced the component to render (its parent, other state updates, etc), then React will bail out of the render completely under the assumption that the output will be identical and there won't be any updates to apply.

See my post [A (Mostly) Complete Guide to React Rendering Behavior](https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/) for details.

**Comment by dai-shi** [comment] 2024-02-09 05:45
> The parent component rerenders even if the state remains unchanged.

But, it happens only when it rendered previously. This is a bit interesting. There might be some cases, useState's early bail-out doesn't work. (or, it can be said, it works, but some others trigger rendering?)

FWIW, if you used `useReducer` the behavior would be more consistent. (because there's no early bail-out.) 😄 
(I've got quite a few questions about this kind of behavior in Jotai.)

**Comment by markerikson** [comment] 2024-02-09 05:50
@dai-shi yeah, I'm distinguishing between "bail out _while rendering_", vs the "early bailout _while queuing the state update_" behavior.  (I know the early bailout exists, but I've tried to trace the code path a couple times and it's pretty confusing.)

**Comment by abdelhakimrafik** [comment] 2024-02-09 13:09
When the parent component's state changes, it causes a re-render of the entire tree. If this change is followed by another unchanged state, the parent re-renders. However, subsequent unchanged state triggers do not cause a re-render.
![image](https://github.com/facebook/react/assets/62836886/d42bc0ff-0dac-4c19-8b2e-461b552b9633)

**Comment by markerikson** [comment] 2024-02-10 04:37
@abdelhakimrafik yep, that's not documented, but that matches the behavior I've seen in the past.

**Comment by rickhanlonii** [comment] 2024-02-10 19:00
This is actually documented in the `useState` docs under [Caveats](https://react.dev/reference/react/useState#setstate-caveats).

> If the new value you provide is identical to the current state, as determined by an [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) comparison, React will skip re-rendering the component and its children. This is an optimization. **Although in some cases React may still need to call your component before skipping the children, it shouldn’t affect your code.** [emphasis mine]


The reason this is happening in this cases is because, in order to bail out, we need to eagerly compute the last value the reducer returned with the new value the reducer returns, because reducers can close over props. In this case, when you first click "unchanged state" the last reducer rendered was `setState(state => state +1)`, so when we compare it to the result of `setState(state => state + 0)`, they're different . When you click again, the last reducer was `setState(state => state + 0)`, so they match and we can bail out. Note that setState callbacks essentially create an in-line reducer, and running the last reducer is necessary because it may have closed over props.

 This behavior might seem weird, but it was necessary to [fix a bug](https://github.com/facebook/react/pull/15124) where we would eagerly bail out in cases that would shouldn't, actually breaking the app. 

`useReducer` is consistent because it never bails out. We [tried to bail out for useReducer](https://github.com/facebook/react/pull/14569), but there were many bugs with it, so we [removed the optimization](https://github.com/facebook/react/pull/22445).

There may be ways we could improve this in the future, which is why it's important to not depend on the behavior and ensure rendering a component is Pure. React needs to be able to control when, and how many times, a component is rendered for performance and UX improvements. For the latest information on which cases are supported and how React currently works, tests in the React repo are the best source.

Closing as this behavior is expected and documented.

**Closed by rickhanlonii** 2024-02-10 19:00 UTC
Labels: Status: Unconfirmed
