### ISSUE TITLE
Error: "Could not find node with id "339" in commit tree"

### ISSUE THREAD

**Issue by Wenhan129** [facebook/react#16551] opened 2019-08-23 10:18 UTC
PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.5-5441b09

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11441
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11387)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11920)
    at xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51:277765)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:98280)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363

Component stack: in xi
    in div
    in div
    in div
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by threepointone** [comment] 2019-08-23 10:58
Do you have any reproduction steps, and/ or any sample code that triggered this? Try to describe the steps you were taking right before this error occurred, thank you!

**Comment by bvaughn** [comment] 2019-08-23 14:42
Looks like a duplicate of #16446. Since there's no repro info, going to close it as a dup.

**Closed by bvaughn** 2019-08-23 14:42 UTC
Labels: Component: Developer Tools, Type: Bug
