### ISSUE TITLE
Bug: unexpected rerender when using `useMutableSource`

### ISSUE THREAD

**Issue by csr632** [facebook/react#19200] opened 2020-06-26 17:44 UTC
React version: experimental

## Steps To Reproduce

https://codesandbox.io/s/react-redux-usemutablesource-j1vgy

(modified from [Brian Vaughn's fake react-redux demo](https://github.com/reactjs/rfcs/pull/147#issuecomment-597939617))

1. Increment Buttons1(update `state.s1`) for several times, only Label1 is rerendered, which is expected. 
2. Increment Buttons2(update `state.s2`), **both Label1 and Label2 is rerendered, which is unexpected**.
    > Also notice that the unexpected render of Label1 is not commited, even when the render return value is different(since it render `Math.random()`).

Since Label1 return the same `state.s1` from `getSnapshot`, Label1 should not rerendered.

This bug may lead to worse performance, because Components are rerendered for state fields that they don't need.

----
@bvaughn  may be interested in this.
@dai-shi may also be interested in this because [his use-context-selector need the correct behaviour to be efficient](https://github.com/dai-shi/use-context-selector/blob/f187fb46f34614a62b9e09a13361af4b00cce02a/src/index.ts#L138)

**Comment by bvaughn** [comment] 2020-07-07 17:07
Note that this isn't actually an issue with the second state, specifically, so much as it is an issue with the second mutation against the shared source. (So if you reverse steps 1 and 2 in the repro, the unexpected behavior will happen for step 1.)

**Comment by bvaughn** [comment] 2020-07-07 17:37
I think the reason for the *unexpected* render of the label component is due to the `useState` bailout mechanism. It looks like React doesn't commit any mutations, or do any further rendering for sub-components (if the label component rendered children), so the overhead of this isn't large even though it's not ideal.

Here's a reduced test case:
```js
const {
  createContext,
  createMutableSource,
  useCallback,
  useContext,
  useEffect,
  useMemo,
} = React;

function getStoreVersion(store) {
  return store.getState();
}

function subscribe(store, callback) {
  return store.subscribe(callback);
}

const MutableSourceContext = createContext(null);

function Provider({ children, store }) {
  const mutableSource = useMemo(() => {
    return createMutableSource(store, getStoreVersion);
  }, [store]);

  return (
    <MutableSourceContext.Provider value={mutableSource}>
      {children}
    </MutableSourceContext.Provider>
  );
}

function useSelector(selector) {
  const mutableSource = useContext(MutableSourceContext);
  const getSnapshot = useCallback((store) => selector(store.getState()), [
    selector,
  ]);

  return useMutableSource(mutableSource, getSnapshot, subscribe);
}

function reducer(state, action) {
  switch (action.type) {
    case "INCREMENT_ONE":
      return {
        ...state,
        one: state.one + 1,
      };
    case "INCREMENT_TWO":
      return {
        ...state,
        two: state.two + 1,
      };
    default:
      return state;
  }
}

// Faux Redux store
const store = {
  _listeners: [],
  _value: {
    one: 100,
    two: 200,
  },
  getState: () => store._value,
  dispatch: (action) => {
    store._value = reducer(store._value, action);
    store.version++;
    store._listeners.forEach((listener) => listener());
  },
  subscribe: (listener) => {
    store._listeners.push(listener);
    return () => {
      const index = store._listeners.indexOf(listener);
      if (index >= 0) {
        store._listeners.splice(index, 1);
      }
    };
  },
};

const selector1 = (state) => state.one;
const selector2 = (state) => state.two;

function Grandchild({ value }) {
  Scheduler.unstable_yieldValue(`Grandchild render "${value}"`);
  useEffect(() => {
    Scheduler.unstable_yieldValue(`Grandchild useEffect "${value}"`);
  });
  return value;
}

function Child1({ store }) {
  const one = useSelector(selector1);
  Scheduler.unstable_yieldValue(`Child1 render "${one}"`);
  useEffect(() => {
    Scheduler.unstable_yieldValue(`Child1 useEffect "${one}"`);
  });
  return <Grandchild value={one} />;
}

function Child2({ store }) {
  const two = useSelector(selector2);
  Scheduler.unstable_yieldValue(`Child2 render "${two}"`);
  useEffect(() => {
    Scheduler.unstable_yieldValue(`Child2 useEffect "${two}"`);
  });
  return <Grandchild value={two} />;
}

function App() {
  Scheduler.unstable_yieldValue("App render");
  return (
    <Provider store={store}>
      <Child1 store={store} />
      {"|"}
      <Child2 store={store} />
    </Provider>
  );
}

const root = ReactNoop.createRoot();
act(() => {
  root.render(<App />);
  expect(Scheduler).toFlushAndYield([
    "App render",
    'Child1 render "100"',
    'Grandchild render "100"',
    'Child2 render "200"',
    'Grandchild render "200"',
    'Grandchild useEffect "100"',
    'Child1 useEffect "100"',
    'Grandchild useEffect "200"',
    'Child2 useEffect "200"',
  ]);
});
expect(root.getChildrenAsJSX()).toEqual("100|200");

act(() => {
  store.dispatch({ type: "INCREMENT_TWO" });

  expect(Scheduler).toFlushAndYield([
    'Child2 render "201"',
    'Grandchild render "201"',
    'Grandchild useEffect "201"',
    'Child2 useEffect "201"',
  ]);
});
expect(root.getChildrenAsJSX()).toEqual("100|201");

act(() => {
  store.dispatch({ type: "INCREMENT_ONE" });

  expect(Scheduler).toFlushAndYield([
    'Child1 render "101"',
    'Grandchild render "101"',
    'Child2 render "201"', // Unexpected render
    'Grandchild useEffect "101"',
    'Child1 useEffect "101"',
    'Child1 render "101"', // Unexpected render after commit?
  ]);
});
expect(root.getChildrenAsJSX()).toEqual("101|201");
```

**Comment by bvaughn** [comment] 2020-07-07 17:56
> I think the reason for the *unexpected* render of the label component is due to the `useState` bailout mechanism. Even though the state value doesn't change, one of the label components re-renders (shallowly).

Confirmed, in that I can reproduce the same "unexpected" behavior with just the `useState` hook.
```js
const setStateCallbacks = {};

function Grandchild({ value }) {
  Scheduler.unstable_yieldValue(`Grandchild render "${value}"`);
  React.useEffect(() => {
    Scheduler.unstable_yieldValue(`Grandchild useEffect "${value}"`);
  });
  return value;
}

function Child({ label }) {
  const [value, setValue] = React.useState(0);
  setStateCallbacks[label] = setValue;
  Scheduler.unstable_yieldValue(`Child "${label}" render "${value}"`);
  React.useEffect(() => {
    Scheduler.unstable_yieldValue(`Child "${label}" useEffect "${value}"`);
  });
  return <Grandchild value={value} />;
}

function App() {
  Scheduler.unstable_yieldValue("App render");
  return (
    <>
      <Child label="one" />
      {"|"}
      <Child label="two" />
    </>
  );
}

const root = ReactNoop.createRoot();
act(() => {
  root.render(<App />);
  expect(Scheduler).toFlushAndYield([
    "App render",
    'Child "one" render "0"',
    'Grandchild render "0"',
    'Child "two" render "0"',
    'Grandchild render "0"',
    'Grandchild useEffect "0"',
    'Child "one" useEffect "0"',
    'Grandchild useEffect "0"',
    'Child "two" useEffect "0"',
  ]);
});
expect(root.getChildrenAsJSX()).toEqual("0|0");

act(() => {
  setStateCallbacks.one(0);
  setStateCallbacks.two(1);

  expect(Scheduler).toFlushAndYield([
    'Child "two" render "1"',
    'Grandchild render "1"',
    'Grandchild useEffect "1"',
    'Child "two" useEffect "1"',
  ]);
});
expect(root.getChildrenAsJSX()).toEqual("0|1");

act(() => {
  setStateCallbacks.one(1);
  setStateCallbacks.two(1);

  expect(Scheduler).toFlushAndYield([
    'Child "one" render "1"',
    'Grandchild render "1"',
    'Child "two" render "1"', // Unexpected render
    'Grandchild useEffect "1"',
    'Child "one" useEffect "1"',
    'Child "one" render "1"', // Unexpected render after commit
  ]);
});
expect(root.getChildrenAsJSX()).toEqual("1|1");
```

**Comment by bvaughn** [comment] 2020-07-07 18:31
Okay, looking more closely at the implementation- let's walk through what's happening.

When `useMutableSource` schedules a possible update (or `useState` or `useReducer`) it uses this `dispatchAction` function:
https://github.com/facebook/react/blob/dccf541ec534035a1ee768e3e493893e01e05e4d/packages/react-reconciler/src/ReactFiberHooks.old.js#L1660-L1663

When we dispatch our first update, the render queue is empty, so we are able to eagerly compute state:
https://github.com/facebook/react/blob/dccf541ec534035a1ee768e3e493893e01e05e4d/packages/react-reconciler/src/ReactFiberHooks.old.js#L1714-L1717

If the state is the same, we can bailout without doing any additional work:
https://github.com/facebook/react/blob/dccf541ec534035a1ee768e3e493893e01e05e4d/packages/react-reconciler/src/ReactFiberHooks.old.js#L1733-L1739

The second time we update- the queue isn't empty, so we aren't able to do that eager computation. Why is that?

This bailout optimization was added back in #14569. Looking at the original implementation notes from that PR I see (emphasis added):

> In some cases, we can bail out without entering the render phase by eagerly computing the next state and comparing it to the current one. **This only works if we are absolutely certain that the queue is empty at the time of the update.** In concurrent mode, this is difficult to determine, **because there could be multiple copies of the queue and we don't know which one is current without doing lots of extra work, which would defeat the purpose of the optimization**. However, in our implementation, there are at most only two copies of the queue, and if both are empty then we know that the current queue must be.

So this is why the bailout mechanism itself doesn't do anything after the second update, but I'm not yet sure why the queue isn't empty in this case.

**Comment by bvaughn** [comment] 2020-07-07 19:53
After speaking with the team, this sounds like a known limitation of the bailout mechanism because of our current Fiber architecture. One positive clarification of my previous comment: this will *only happen once per sub tree* so the performance impact should be further minimized.

I'm going to close this issue for now since it seems the mechanism is working as designed (with a known limitation that I was not aware of until digging in).

Thank you so much for the helpful report with repro case ❤️

**Closed by bvaughn** 2020-07-07 19:53 UTC
Labels: Status: Unconfirmed
