### ISSUE TITLE
Scoping of render() under TypeScript (and maybe ES6)

### ISSUE THREAD

**Issue by japhar81** [facebook/react#8850] opened 2017-01-23 18:55 UTC
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
This code throws `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.`

```
export class Test extends React.Component<any, any> {
    static propTypes = {};
    state = {test: ''};

    onChange = (event: any): void => {
        this.setState({test: this.state.test});
    };

    render() {
        return (
                <input
                    type='text'
                    value={this.state.test}
                    placeholder='test'
                    onChange={this.onChange}
                />
        );
    }
}
```

This variation does not;

```
export class Test extends React.Component<any, any> {
    static propTypes = {};
    state = {test: ''};
    
    render() {
        let onChange = (event: any): void => {
            this.setState({test: this.state.test});
        };

        return (
                <input
                    type='text'
                    value={this.state.test}
                    placeholder='test'
                    onChange={onChange}
                />
        );
    }
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

I'm using this repo to test this in the Login.tsx component: https://github.com/japhar81/redux_todo/commit/035041f4d5efadb56d164895f8938e231ffd9980

**What is the expected behavior?**

I've managed to chase this down to scope being lost because render is a function. I suspect if it was possible to do `render = () => { ... }` this would not be an issue, but that syntax is blocked by the TSD for react. I'm not sure if this is a react bug or a TSD one.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm running 15.4.2, Chrome on MacOS but i can reproduce in FF and Edge on Win 10 as well. I haven't used older versions but i suspect it was there.

**Comment by donataswix** [comment] 2017-01-30 14:00
I think you are supposed to bind `onChange` to current instance (`this`), like:
```javascript
constructor(props) {
  super(props);
  this.onChange = this.onChange.bind(this);
}
```
Or use autobind library.

**Comment by aweary** [comment] 2017-01-30 16:31
I'm not familiar with TypeScript, but if it supports class properties and property initializers (like what you get with `babel-plugin-transform-class-properties`) then using an arrow function should mean it's implicitly bound to the instance.

> I'm using this repo to test this in the Login.tsx component: japhar81/redux_todo@035041f

I tried cloning the repo and running it, but didn't see the error. If you can provide a simpler example reproducing your issue with clear steps on how to reproduce that would be great.

**Comment by japhar81** [comment] 2017-01-30 16:47
I'll work on a simpler repro this week. I did get around it by doing this;
```
onChange={(e) => this.usernameChange(e)}
```

Still ugly, but workable and scopes properly.

**Comment by dthomas00** [comment] 2017-05-14 06:24
Test

**Comment by dthomas00** [comment] 2017-05-15 00:07
New Test

**Comment by dthomas00** [comment] 2017-05-15 00:21
New Test

**Comment by dthomas00** [comment] 2017-05-15 00:25
New Test

**Comment by dthomas00** [comment] 2017-05-15 04:50
New Test

**Comment by dthomas00** [comment] 2017-05-15 04:57
New Test

**Comment by dthomas00** [comment] 2017-05-15 04:58
New Test

**Comment by aweary** [comment] 2017-05-15 10:28
@dthomas00 please stop, comments notify the people participating in the discussion and the project maintainers.

**Comment by gaearon** [comment] 2017-10-04 16:28
It seems like the issue was due to user's mistake of calling the function instead of passing it.
Closing.

**Closed by gaearon** 2017-10-04 16:28 UTC
Labels: Status: Unconfirmed
