### ISSUE TITLE
DefaultProps for React Stateless function 

### ISSUE THREAD

**Issue by sudharsanmit** [facebook/react#7123] opened 2016-06-26 03:30 UTC
Pls help resolve the error in stateless function. This works if I provide `hello = Hello({name:"World"})`

```
function Hello(props){
    return <div>Hello {props.name}</div>;
}

Hello.defaultProps = {name:"World"};

var hello=Hello();

ReactDOM.render(hello, mountNode);

```
Returns error -

`TypeError: Cannot read property 'name' of undefined
`

I tried this based on the following in the documentation.

> This simplified component API is intended for components that are pure functions of their props. These components must not retain internal state, do not have backing instances, and do not have the component lifecycle methods. They are pure functional transforms of their input, with zero boilerplate. However, you may still specify .propTypes and .defaultProps by setting them as properties on the function, just as you would set them on an ES6 class.

-- https://facebook.github.io/react/docs/reusable-components.html

**Comment by Aweary** [comment] 2016-06-26 03:42
@sudharsanmit you wouldn't call `Hello` as a function, React will do that for you and pass in `props` and all that. You can just use your component directly. 

```js
function Hello(props){
    return <div>Hello {props.name}</div>;
}

Hello.defaultProps = {name:"World"};

ReactDOM.render(
  <Hello />,
 mountNode
);

```
https://jsfiddle.net/0f8a9rjr/

**Comment by sudharsanmit** [comment] 2016-06-26 03:57
Thanks @Aweary for your reply. Stateless functions are still broken. It doesn't work well with all APIs. Check out the below example. I tried it out with renderToStaticMarkup. Same behaviour with renderToString as well. Are stateless functions generally incompatible? I didn't find any specific mentions.

Try this -

```
"use strict";
var React = require('react');
var ReactDOMServer = require('react-dom/server');

function Hello(props) {
    return React.createElement(
        "div",
        null,
        "Hello ",
        props.name
    );
}

Hello.defaultProps = {name:"World"};

var hello = Hello({ name: "world"});
console.log(ReactDOMServer.renderToStaticMarkup(hello));
console.log(ReactDOMServer.renderToStaticMarkup('<Hello />'));

```

```
$ node hello.js
<div>Hello world</div>
C:\react-server\node_modules\fbjs\lib\invariant.js:45
    throw error;
    ^

Invariant Violation: renderToStaticMarkup(): You must pass a valid ReactElement.
    at invariant (C:\react-server\node_modules\fbjs\lib\invariant.js:38:15)
    at Object.renderToStaticMarkup (C:\react-server\node_modules\react\lib\ReactServerRendering.js:77:83)
    at Object.<anonymous> (C:\react-server\hello.js:18:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)

```

**Comment by keyanzhang** [comment] 2016-06-26 04:16
As @Aweary mentioned, you shouldn't _call_ `Hello` as a function (`var hello = Hello(...)`). The "pure function" part is about the way we _define_ it, but not the way we _call/invoke_ it. You can take a look at https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components.

Since this is not a bug I'm going to close it out. If there's still anything unclear, StackOverflow would be a better place to ask about this. Thanks!

**Closed by keyanzhang** 2016-06-26 04:16 UTC

**Comment by chicoxyzzy** [comment] 2016-06-26 04:21
@sudharsanmit in your second example `Hello` is not a Stateless Component Function but a function which should return React Element via `React.createElement`. Also you pass wrong [parameters](https://facebook.github.io/react/docs/top-level-api.html#react.createelement) to it.

**Comment by sudharsanmit** [comment] 2016-06-26 04:30
@aweary Pls see the first line of the output. It renders perfectly if the parameter {name:"world"} is passed. @chicoxyzzy It was to ilustrate that I cannot pass markups directly as suggested by @Aweary .

var hello = Hello();
will return error as shown in my first example. It ignores the default prop.

**Comment by sudharsanmit** [comment] 2016-06-26 04:33
@keyanzhang Actually what you said is not an issue at all. It is rendered perfect if I call Hello as a function. The only issue is it ignores defaultProps. Even in the example you provided it states defaultProps can be used. 
```

"use strict";
var React = require('react');
var ReactDOMServer = require('react-dom/server');

function Hello(props) {
    return React.createElement(
        "div",
        null,
        "Hello ",
        props.name
    );
}

Hello.defaultProps = {name:"World"};

var hello = Hello({ name: "world"});
console.log(ReactDOMServer.renderToStaticMarkup(hello));

$ node hello.js
<div>Hello world</div>
```

**Comment by keyanzhang** [comment] 2016-06-26 04:34
In your code, 
> `console.log(ReactDOMServer.renderToStaticMarkup('<Hello />'));`

`'<Hello />'` is a string. Is it a typo?

**Comment by sudharsanmit** [comment] 2016-06-26 04:34
@keyanzhang It was just to illustrate I can't just pass even a markup as suggested in the first response.

**Comment by chicoxyzzy** [comment] 2016-06-26 04:38
This is not a markup. It's DSL which desugars to `React.createElement`.
Please read the docs https://facebook.github.io/react/docs/jsx-in-depth.html

All your examples work as expected.

**Comment by sudharsanmit** [comment] 2016-06-26 04:44
@chicoxyzzy It still doesn't answer why defautProps are ignored while it works when provided with input. All examples say you can include default props.

var hello = Hello({ name: "world"}); -- works
var hello = Hello(); -- Error!!!!

**Comment by chicoxyzzy** [comment] 2016-06-26 04:53
When you call your `Hello` function without arguments it's parameter `props` becomes `undefined`. So JS emits `TypeError` because `undefined` can't have any properties (`name` in your case). This is how JavaScript works. It's not React related issue.

**Comment by sudharsanmit** [comment] 2016-06-26 05:10
@chicoxyzzy Thanks. Makes a lot of sense.

**Comment by sudharsanmit** [comment] 2016-06-26 06:39
@chicoxyzzy This one renders.. props is empty. But function has defaultProps. Hit react. But returns blank! :) May be an edge case. But ignored!

```
$ node hello.js
<div>Hello </div>

```

```
"use strict";
var React = require('react');
var ReactDOMServer = require('react-dom/server');

function Hello(props) {
    return React.createElement(
        "div",
        null,
        "Hello ",
        props.name
    );
}
Hello.defaultProps = {name:"World"};

var hello = Hello({});
console.log(ReactDOMServer.renderToStaticMarkup(hello));

```

**Comment by keyanzhang** [comment] 2016-06-26 06:58
Hi @sudharsanmit,

I don't understand why you use `var hello = Hello({})` here. Stateless functional component, or React itself is **not** designed to be used this way. If you take a look at the [jsfiddle link](https://jsfiddle.net/0f8a9rjr/) that @Aweary provided, you'll see that `defaultProps` definitely works with functional component.  

If for some reason you can't use JSX, then the following code
```javascript
function Hello(props){
    return <div>Hello {props.name}</div>;
}

Hello.defaultProps = {name:"World"};

ReactDOM.render(
  <Hello />,
 mountNode
);
```

actually gets transpiled down to
```javascript
function Hello(props) {
    return React.createElement(
        "div",
        null,
        "Hello ",
        props.name
    );
}

Hello.defaultProps = { name: "World" };

ReactDOM.render(React.createElement(Hello, null), mountNode);
```
Instead of `var hello = Hello({})`, it actually should be `React.createElement(Hello, null)` where the second argument of `React.createElement` is `props`.

**Comment by sudharsanmit** [comment] 2016-06-26 08:35
@keyanzhang Your example will work. They are dependent on ReactDOM.render. Try your own example for ReactDOMServer.renderToStaticMarkup. If you are able to render to node, ideally it should render as a string too. Is there a way around?

Btw, var hello = Hello({}) passes type as div and props as null as per API. React.createElement(Hello, null) will not work as Hello is not a ReactClass.

**Comment by chicoxyzzy** [comment] 2016-06-26 11:32
@sudharsanmit when you do `var hello = Hello({});` you call `Hello` with empty object argument. Object *can* have properties so when you trying to get object's `name` you get `undefined` not `TypeError`. `undefined` renders to empty string by React. `defaultProps` don't work because your function returns `ReactElement` instance not `React` component.

**Comment by sudharsanmit** [comment] 2016-06-26 19:24
@chicoxyzzy React component is created internally when ReactDOM.render method is invoked where it has access to defaultProps. ReactDOMServer.renderToStaticMarkup doesn't go through the render lifecycle to create a component. Hence the defaultprops get ignored.

**Comment by chicoxyzzy** [comment] 2016-06-26 19:40
`defaultProps` is a property of `Hello` but not `hello`.

> React component is created internally when ReactDOM.render method is invoked

No it isn't. React components' render method returns `ReactElement` instance. But you already pass `ReactElement` to `renderToStaticMarkup `.

**Comment by sudharsanmit** [comment] 2016-06-26 20:04
@chicoxyzzy The defaultProps are resolved based on the type. See snippet 2. The defaultProps are defined on Hello. Not on 'div'. That is the reason this fails.

This is how the Hello looks : 
```
{ '$$typeof': Symbol(react.element),
  type: 'div',
  key: null,
  ref: null,
  props: { children: [ 'Hello ', undefined ] },
  _owner: null,
  _store: {} }

```

ReactDOMElement.js

```
  // Resolve default props
  if (type && type.defaultProps) {
    var defaultProps = type.defaultProps;
    for (propName in defaultProps) {
      if (props[propName] === undefined) {
        props[propName] = defaultProps[propName];
      }
    }
  }

```

**Comment by keyanzhang** [comment] 2016-06-26 20:09
> React component is created internally when ReactDOM.render method is invoked where it has access to defaultProps. ReactDOMServer.renderToStaticMarkup doesn't go through the render lifecycle to create a component. Hence the defaultprops get ignored.

This is not correct. `defaultProps` is not ignored when using `ReactDOMServer.renderToStaticMarkup`. The issue is that you used an incorrect and not supported way to use your functional component. As a framework, it's impossible for us to support invalid usages or change the behavior of JavaScript itself, so `var hello = Hello({})` won't work.

<img width="777" alt="screen shot 2016-06-26 at 12 55 21 pm" src="https://cloud.githubusercontent.com/assets/2268452/16364519/e1774bf4-3b9d-11e6-92ea-c14bcf938731.png">

I'm sorry but I think I'm going to lock this conversation since this is not a bug but invalid usage. StackOverflow would be a better place to ask about this. Thanks!
