### ISSUE TITLE
React 18 

### ISSUE THREAD

**Issue by ravian0519** [facebook/react#23062] opened 2022-01-03 16:20 UTC
When is the new release coming?

**Comment by anton-g** [comment] 2022-01-03 19:16
https://github.com/facebook/react/issues/23059#issuecomment-1004155070

**Comment by eps1lon** [comment] 2022-01-07 18:49
Duplicate of https://github.com/facebook/react/issues/23059#issuecomment-1004155070

**Closed by eps1lon** 2022-01-07 18:49 UTC
Labels: Type: Discussion, React 18
