### ISSUE TITLE
Cannot read property 'getNativeNode' of null (ReactReconciler)

### ISSUE THREAD

**Issue by artemT82** [facebook/react#7113] opened 2016-06-24 11:21 UTC
Hello everyone. I have a problem after updating React from v0.14.8 to the current latest v15.1.0. 

Actually, I cannot even tell what exactly cause this problem. On some pages of my SPA everything works just fine, but during one specific action in my app, this error happens. 

This problem appeared after React (and some dependent libraries) update

![screenshot from 2016-06-24 13 40 15](https://cloud.githubusercontent.com/assets/17126360/16336516/dee3aff0-3a16-11e6-9f74-9383bd8282b9.png)

**Comment by gaearon** [comment] 2016-06-24 17:56
Thank you for reporting!
We also saw this error in production on a React Native app but couldn’t find a way to reproduce it.

Can you try slimming it down to a small case that reliably reproduces it, and share that case?

**Comment by gaearon** [comment] 2016-06-28 02:17
(Note: we probably won’t be able to fix it without a case reproducing it.)

**Comment by artemT82** [comment] 2016-06-29 10:00
Looks like I fixed it for my case. Obviously, I shouldn't been creating the issue in this repo, as in my case the problem was not in React itself, but in my absent-mindedness. But I'll share this case anyway. The problem appeared on a page with RadioButton Component from Material-UI lib. As I mentioned before, during a React update, I also updated some dependent libraries, including Material UI. In the new version of MUI a file structure has changed, so I had to change the way I import MUI components into my files. That's where the problem had it roots. I mistakenly imported RadioButton Component instead of RadioButtonGroup component (if you're familiar with MUI lib, then you know that the structure should be 'RadioButtonGroup > RadioButton', and in my case it was 'RadioButton > RadioButton', which is inappropriate). This led to the error on a screenshot, which, obviously, led to the error "Cannot read property 'getNativeNode' of null".
![screenshot from 2016-06-29 12 16 24](https://cloud.githubusercontent.com/assets/17126360/16448234/150100f2-3df9-11e6-8a80-705dc7524cce.png)

**Comment by gaearon** [comment] 2016-06-30 01:53
That’s super useful, thanks!

**Comment by spicyj** [comment] 2016-06-30 01:56
I think this still counts as "exception thrown during render": https://github.com/facebook/react/blob/6cc037bd0d49f1f55cbdd36fbfd395118c64d393/src/renderers/dom/shared/ReactDOMComponent.js#L156. :\

**Comment by gaearon** [comment] 2016-06-30 02:04
Well, we now know that `ReactDOMComponent.mountComponent` throwing can lead to a `null` child in multichild. I wasn’t sure how to repro this before.

**Comment by gaearon** [comment] 2016-10-27 15:09
Closing because it seems like React got into an inconsistent state due to the user error above.
Still not very good but at least it's possible to fix in apps.

**Closed by gaearon** 2016-10-27 15:09 UTC
Labels: Type: Bug
