### ISSUE TITLE
Performance regression for removing rows from large table

### ISSUE THREAD

**Issue by krausest** [facebook/react#7227] opened 2016-07-08 19:57 UTC
In my javascript frameworks benchmark I ran into a performance regression for react.
To reproduce open [the react.js 15.2 version](http://stefankrause.net/js-frameworks-benchmark2/react-v15.2.0/index.html) and open the console.
Repeat three times the following: Click "Create 10,000" then click "Clear"
You'll get a result like that:
runLots took 1905.0000000000005
clear took **1997.0249999999996**
runLots took 1813.8500000000004
clear took **4208.895**
runLots took 1806.864999999998
clear took **401.119999999999**

Now repeat the same for [react.js 0.14.8](http://stefankrause.net/js-frameworks-benchmark2/react-v0.14.8/index.html) and you'll get something like that:
unLots took 2938.8900000000003
clear took **399.2250000000013**
runLots took 2726.365
clear took **383.45500000000175**
runLots took 2872.625
clear took **381.7250000000058**

(Measurement on Chrome 51 on MacOS 10.11.5 on a MBP 15)

Notice that clear is a lot slower for the first two runs for React v 15, but the third clear run performs about the same for both react versions.

The source code can be found in the [repository](https://github.com/krausest/js-framework-benchmark) of my benchmark.

**Comment by gaearon** [comment] 2016-07-08 20:17
In general we don’t advise you to render 10K items. Use something like https://bvaughn.github.io/react-virtualized/ instead.

However, this indeed seems like a perf regression. It appears that we’re spending a little time in `willDeleteListener` per each item, and it adds up with 10K items. 

<img width="703" alt="screen shot 2016-07-08 at 21 10 52" src="https://cloud.githubusercontent.com/assets/810438/16700227/c0d027b0-4550-11e6-8926-1ac06f78635b.png">

It seems like we’re doing some work for nodes with `onClick` handlers [just for the sake of Mobile Safari](https://github.com/facebook/react/blob/b6e1eb27185dd90e74ad8a67f98f6c5b35043c1a/src/renderers/dom/client/eventPlugins/SimpleEventPlugin.js#L618-L640). I’m not confident but this *might* be the cause of this regression. If it is, we should just guard this by a feature test.

**Comment by gaearon** [comment] 2016-07-08 21:09
This is a very simple scenario: we are unmounting 10,000 components.
The bottleneck is somewhere in reconciliation.

React 0.14 is reconciling fast right away:

<img width="762" alt="screen shot 2016-07-08 at 22 06 01" src="https://cloud.githubusercontent.com/assets/810438/16701528/340a4d6c-4558-11e6-97c4-8e98a6a58891.png">

React 15 is reconciling slow at first (notice how long `reconcilerUpdateChildren` is compared to applying DOM updates):

<img width="1097" alt="screen shot 2016-07-08 at 22 03 56" src="https://cloud.githubusercontent.com/assets/810438/16701545/4cf18ade-4558-11e6-8e9b-35d5d53de69e.png">

But it warms up exactly after two mount-unmount cycles (notice how its size is less relative to DOM updates):

<img width="928" alt="screen shot 2016-07-08 at 22 04 07" src="https://cloud.githubusercontent.com/assets/810438/16701567/7ca72acc-4558-11e6-86c6-2cd6eaf38163.png">

**Comment by gaearon** [comment] 2016-07-08 22:22
It looks like there is some sort of V8 optimization that doesn’t kick in until you unmount a *lot* of components. I was able to drastically reduce time (from 2 seconds to 300 milliseconds) on React 15 by replacing `delete` statements with `null` assignment in these two places:

* [`SimpleEventPlugin`](https://github.com/facebook/react/blob/b6e1eb27185dd90e74ad8a67f98f6c5b35043c1a/src/renderers/dom/client/eventPlugins/SimpleEventPlugin.js#L639)
* [`EventPluginHub`](https://github.com/facebook/react/blob/b6e1eb27185dd90e74ad8a67f98f6c5b35043c1a/src/renderers/shared/stack/event/EventPluginHub.js#L174)

This is probably not a real solution (I think just leaving them as `null` means memory keeps growing, even if just for property keys).

Still, I wonder why 0.14.x is not similarly penalized.

**Comment by gaearon** [comment] 2016-07-08 22:34
Replacing objects with ES6 Maps gives similar performance improvements there.

**Comment by gaearon** [comment] 2016-07-09 10:50
This was fixed in #7232. Thank you very much for caring and providing specific instructions.

**Closed by gaearon** 2016-07-09 10:50 UTC

**Comment by julienw** [comment] 2016-07-09 15:36
As a quick experiment, I ran the benchmarks under Firefox: both versions ran in the same speed as the 15.2 in Chrome (I mean: slow). I surely hope the fix would fix it in Firefox too !

**Comment by gaearon** [comment] 2016-07-09 15:49
Maybe putting these fields on the internal instances instead of global maps will help it in Firefox. Would you like to investigate why it's slow?

**Comment by gaearon** [comment] 2016-07-09 16:12
I have it a look, and Firefox slowness is due to DOM `removeChild` being slow. I don’t think we can fix it.

**Comment by bzbarsky** [comment] 2016-07-11 05:21
> I gave it a look, and Firefox slowness is due to DOM removeChild being slow.

I'd really appreciate a Firefox bug report with testcase here!

**Comment by julienw** [comment] 2016-07-11 08:42
@bzbarsky I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1285874 with the information of this bug. I don't have the time to do a reduced testcase now though.

**Comment by smaug----** [comment] 2016-07-11 21:03
FWIW, removeChild is slow in Gecko because of layout. No idea whether setting display: none before removal or some such might speed up the process. It might help if done on the element on which removeChild is being called.

**Comment by bzbarsky** [comment] 2016-07-11 21:07
@julienw Thank you for filing!
