### ISSUE TITLE
Devtools blocking React page loading

### ISSUE THREAD

**Issue by krisavi** [facebook/react#16507] opened 2019-08-20 11:49 UTC
**Do you want to request a *feature* or report a *bug*?**
It is a bug in dev tools I believe.

**What is the current behavior?**
Whenever I go to specific page that uses react it shows me blank page. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Unfortunately I cannot provide steps to reproduce.

When I set the React dev tools to load only when I click, then page loads. But when reloading the devtools, it shows blank again. Seems like renderer is being overridden and it is unable to show anything when devtools are loaded.

In the console I get error on row, but might be irrelevant:
```
window.__REACT_DEVTOOLS_GLOBAL_HOOK__ && Object.keys(window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers).length && (window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers = {});
Uncaught TypeError: Cannot convert undefined or null to object
```

**What is the expected behavior?**
The page to load as it did with previous version.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
It did work before Chrome restart, now Chrome 76.0.3809.100. Tried reinstalling React DevTools, so they should be the newest. Most likely before restart of Chrome extension was older version.

There might be code issue on webpage side, but dev tools should not cause blank page still. Maybe to show warning, but not break the page. Since I am not maintainer of the web site side code, then it is something I cannot change. Observation was that the Dev Tools is for some reason breaking the loading of page.

**Comment by bvaughn** [comment] 2019-08-20 16:06
I am also running Chome 76.0.3809.100 (Official Build) (64-bit) and not experiencing what you're describing.

> Since I am not maintainer of the web site side code, then it is something I cannot change. Observation was that the Dev Tools is for some reason breaking the loading of page.

What page are you referring to? Maybe it's something specific to the page? Or maybe another extension you have installed is interfering with React DevTools somehow?

**Comment by gaearon** [comment] 2019-08-20 16:11
The line you’re quoting is not from DevTools. It must be some code from the website that tries to disable DevTools. The code is touching internal fields so it’s not a surprise it is fragile.

I’m going to close this because it’s not actionable. If you specifically write code to interfere with how DevTools work, it will be fragile and it’s due diligence you need to take to put try/catch around it.

There is no way we could fix this on our side because there will always be a way to write some code that depends on DevTools internals and breaks in future versions. That’s a risk you’re taking by patching its private fields.

**Closed by gaearon** 2019-08-20 16:11 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information

**Comment by bvaughn** [comment] 2019-08-20 16:19
My guess would be this package:
https://www.npmjs.com/package/disable-react-devtools

```js
// Overrides the following:
// https://github.com/facebook/react-devtools/blob/master/shells/chrome/src/checkForReact.js
if (
  process.env.NODE_ENV === 'production' &&
  window.__REACT_DEVTOOLS_GLOBAL_HOOK__ &&
  Object.keys(window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers).length
) {
  window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers = {};
}
```

**Comment by clamstew** [comment] 2019-08-20 17:38
@krisavi - the error your seeing for logic that would block v3 and below can be fixed with object checking.

```
window.__REACT_DEVTOOLS_GLOBAL_HOOK__ && 
window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers && 
Object.keys(window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers).length && (window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers = {});
```

`Uncaught TypeError: Cannot convert undefined or null to object` is being caused by `Object.keys(window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers).length` failing since `__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers` is no longer defined, seemingly, in v4. 

This doesn't help v4 blocking at all, but should fix v3 and below from blowing up.

**Comment by bvaughn** [comment] 2020-01-14 21:17
v4 declares the property as `renderers` (no underscore). Things shouldn't really be monkeying with this hook thoguh
