### ISSUE TITLE
Bug: Crash after update

### ISSUE THREAD

**Issue by krishnaTORQUE** [facebook/react#19539] opened 2020-08-05 18:01 UTC
React version:16.13.1

It was working until I update react to latest version

No issue in development server

Once I build the project getting this issue

SyntaxError: missing } after property list
note: { opened at line 1, column 1998

ChunkLoadError: Loading chunk 1 failed
/static/js/1.75c86cba.chunk.js

**Comment by bvaughn** [comment] 2020-08-05 19:29
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-08-05 19:30
I will add that, from the error message you've posted, the error is almost certainly in your build toolchain (either a corrupted cache, or a build configuration issue, etc.)

**Comment by bvaughn** [comment] 2020-10-28 13:37
Closing this due to lack of a repro.

**Closed by bvaughn** 2020-10-28 13:37 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
