### ISSUE TITLE
getDerivedStateFromProps broken in 16.4?

### ISSUE THREAD

**Issue by javascrewpt** [facebook/react#12922] opened 2018-05-28 20:46 UTC
**Do you want to request a *feature* or report a *bug*?**
I believe there is a bug in React 16.4 regarding the `getDerivedStateFromProps`. 

**What is the current behavior?**
Trying to set the state based on the props kind of overrides the state forever, which makes it impossible to edit it later on.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Example is as follows: http://jsbin.com/yawasoz/1/edit?html,js,output
Add some item, click on it, try to edit it.

**What is the expected behavior?**
To work like this (React 16.3): http://jsbin.com/luzimujiwi/1/edit?html,js,output

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I think this happens only in React 16.4, 16.3 seems to work fine (same code, different React version): http://jsbin.com/luzimujiwi/1/edit?html,js,output

**Comment by muhammadtarek** [comment] 2018-05-28 21:16
I guess this is a duplicate of #12898. You can see the [blog post](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops) for more details

**Comment by javascrewpt** [comment] 2018-05-28 21:39
yes, exactly, thank you. I posted too fast. can you please close this?

**Closed** 2018-05-28 21:39 UTC
