### ISSUE TITLE
Bug: [eslint-plugin-react-hooks] RuleOfHooks does not find conditional hook if HOC (e.g. mobx "observer") applied directly

### ISSUE THREAD

**Issue by ahoisl** [facebook/react#20499] opened 2020-12-22 11:20 UTC
React version: 16.13.1

## Steps To Reproduce

1. Create a component using a conditional hook
2. Wrap the component with a HOC, e.g. mobx [observer](https://mobx.js.org/react-integration.html)

## Example

```
function HOC<T>(c: T): T { return c; }

const ConditionalHookComp = HOC(
    ({ flag }): JSX.Element => {
        if (flag) {
            useEffect(() => console.log("something"));
        }
        return <></>;
    });
```

## The current behavior
The linter does not issue a warning/error for the conditional use of hooks, unless you remove the HOC.

## The expected behavior
The linter issues a warning/error for the conditional use of hooks regardless whether the component is wrapped by an HOC or not.

**Comment by ahoisl** [comment] 2020-12-22 11:20
This might be related to #20448

**Comment by eps1lon** [comment] 2020-12-23 10:35
Duplicate of https://github.com/facebook/react/issues/20448.

Note that the eslint plugin requires you to name your function components.

**Closed by eps1lon** 2020-12-23 10:35 UTC
Labels: Status: Unconfirmed

**Comment by ahoisl** [comment] 2020-12-23 10:47
Understood, the component itself is probably not named, just the HOC-enhanced version, right. Unfortunately, directly wrapping the component with the HOC is the default way in [mobx](https://mobx.js.org/react-integration.html)

**Comment by eps1lon** [comment] 2020-12-23 10:52
Does the following diff help?
```diff
const ConditionalHookComp = HOC(
-    ({ flag }): JSX.Element => {
+    function MyNameIsInigoMontoya({ flag }): JSX.Element => {
        if (flag) {
            useEffect(() => console.log("something"));
        }
        return <></>;
    });
```

**Comment by ahoisl** [comment] 2020-12-23 11:43
Yes (if you remove the `=>`), this causes the linter to issue the warning again, so it's definitely a duplicate of #20448 

It's still kind of weird cause without the HOC wrapper it's still an unnamed function, just assigned to a variable. So not really consistent in my opinion.

**Comment by eps1lon** [comment] 2020-12-23 11:49
> It's still kind of weird cause without the HOC wrapper it's still an unnamed function, just assigned to a variable. So not really consistent in my opinion.

```jsx
const ConditionalHookComp = () => {}
```
is not an unnamed function (`console.log(ConditionalHookComp.name); // "ConditionalHookComp"`).

**Comment by ahoisl** [comment] 2020-12-23 11:58
You are right, my mistake, name is inferred. We will probably need to follow some pattern for the observer HOC in our project if we want the linter support
