### ISSUE TITLE
Setting custom data attributes starting with numbers are removed

### ISSUE THREAD

**Issue by mimosa123321** [facebook/react#4772] opened 2015-09-02 18:16 UTC
Setting a custom data attribute such as data-test="" works, whereas data-0="" would fail.
Is this expected behaviour?

**Comment by zpao** [comment] 2015-09-02 19:16
It is currently expected behavior with our code (our regexp: `/^(data|aria)-[a-z_][a-z\d_.\-]*$/`) but…

I was going to say that it doesn't actually work and `data-0` isn't valid according to the spec but I think I would be wrong. It looks like it would be (`data-name` as a whole must be XML-compatible, not just the `name` part, so `NameStartChar` only applies to `d` in `data`). Hopefully there was a good reason (like lack of support in IE8) but I don't remember off the top of my head. I knew we discussed a lot around capital letters in there but decided not to support that intentionally.

@syranide - do you remember if we ever talked about numbers?

**Comment by syranide** [comment] 2015-09-02 19:20
@zpao Yes you "guys" rejected having it, no significant reason I think other than just keeping it as it was, AFAIK it's completely safe to have (IE8 too). cc @chenglou

**Comment by imgarylai** [comment] 2016-02-18 06:45
Hi, I got same problem when I used this [dense.js](https://github.com/gocom/dense) and tried to set a custom data attribute such as data-2x = "xxx". 

Will this behavior be accepted in the future?

**Comment by jimfb** [comment] 2016-02-18 06:54
I'm not sure what dense.js has to do with this issue, but I think this is a duplicate of https://github.com/facebook/react/issues/2329 which was fixed in https://github.com/facebook/react/pull/5216 and appears to work on latest http://jsfiddle.net/8pLf9dbw/

**Closed by jimfb** 2016-02-18 06:54 UTC

**Comment by imgarylai** [comment] 2016-02-18 09:01
@jimfb thanks for your answer. (I mentioned dense only because I got this problem when i was using it.)

I check your jsfiddle. That's my problem and it looks working great. However, does it work in es5?  

Here is my jsfiddle: https://jsfiddle.net/garylai/Lbe2auh3/1/

![screen shot 2016-02-18 at 4 57 53 pm](https://cloud.githubusercontent.com/assets/1407908/13138228/d03e15e0-d660-11e5-81ed-a02c98d16dbf.png)

The data-0 attribute didn't show correctly.

**Comment by cody** [comment] 2016-02-18 09:20
@imgarylai 
The bugfix is in git, that's the version @jimfb's fiddle is using. It will be released in React v15.

**Comment by jimfb** [comment] 2016-02-18 12:34
@cody is correct.

@imgarylai Yes, it works on es5: http://jsfiddle.net/1LgLy7mL/

**Comment by imgarylai** [comment] 2016-02-19 02:37
@cody @jimfb thank you :+1::+1::+1:
