### ISSUE TITLE
Unable to fix "PropTypes has been moved to a separate package."

### ISSUE THREAD

**Issue by agerson** [facebook/react#10277] opened 2017-07-26 02:10 UTC
One of the modules I use, [react-native-spinkit](https://github.com/maxs15/react-native-spinkit), started throwing this error after I updated to RN v.46. I went into the file causing the error (node_modules/react-native-spinkit/index.js) and made the changes described in [Migrating from React.PropTypes](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes). I even tried automatically applying the changes with [jscodeshift](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types). Then I ran:

`watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache
`

However, I am still getting this warning. I want to help a project I use. What am I doing wrong?

[Code before](https://github.com/maxs15/react-native-spinkit/blob/6a53f5be6e0ff630d194c7174a8fba680b058186/index.js)

[Code after](https://gist.github.com/agerson/1f100838fe7aa478a310cf177036f154)

**Comment by bvaughn** [comment] 2017-07-26 05:05
If you modified `node_modules/react-native-spinkit/index.js` and then ran `rm -rf node_modules/ && yarn cache clean && yarn install` you would end up with a new copy of react-native-spinkit (without your modifications).

The correct way to fix this warning would be to file an issue or pull request against [maxs15/react-native-spinkit](https://github.com/maxs15/react-native-spinkit/) asking them to release an update to NPM with the change described [here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes). In this case, it looks like someone has already done this (see [issue #74](https://github.com/maxs15/react-native-spinkit/issues/74) and [pull request #75](https://github.com/maxs15/react-native-spinkit/pull/75)).

I'm going to close this issue as it doesn't require any action from the React team.

**Closed by bvaughn** 2017-07-26 05:05 UTC

**Comment by agerson** [comment] 2017-07-26 19:34
Sorry, you are right! However, I tried running it before that command and it still produced the error, even though the changes were most certainly in place in the file.

**Comment by bvaughn** [comment] 2017-07-26 22:07
It's possible this message was being caused by another lib. Not sure.

**Comment by agersoncgps** [comment] 2017-07-29 03:01
According to the logs its react-native-spinkit
