### ISSUE TITLE
Replace "scry" with a less fancy word.

### ISSUE THREAD

**Issue by kamagatos** [facebook/react#5571] opened 2015-11-30 22:02 UTC
I think **scryRenderedDOMComponentsWithClass** (and all other methods starting with scry) should be deprecated in favor of more obvious names like **findRenderedDOMComponentsWithClass**.

**Comment by jimfb** [comment] 2015-11-30 22:12
Duplicate of https://github.com/facebook/react/issues/3951

**Closed by jimfb** 2015-11-30 22:12 UTC
