### ISSUE TITLE
Coverage Support for JSX-Control-Statements

### ISSUE THREAD

**Issue by OverseePublic** [facebook/react#12705] opened 2018-04-27 14:41 UTC
Conditional Rendering Components JSX-Control-Statement produces incorrect coverage in if / else branches. We are using it in our project and we want official Facebook's opinion about these as whether it will be updated with babel's AST for future support. If not please warn the developers that they will get incorrect branch coverage. See the reported issue below.
https://github.com/istanbuljs/nyc/issues/812

1. Will facebook support any approach similar to JSX-Control-Statements in the future?
1. If facebook does not support any approach like above, facebook should warn it's developers about using such library due to incorrect coverages.
1. Issue consistent in jest and nyc since they both use babel's AST.

https://github.com/AlexGilleran/jsx-control-statements

**Do you want to request a *feature* or report a *bug*?**
Feature(?)
**What is the current behavior?**
Incorrect Coverage

**What is the expected behavior?**
Correct Coverage Report on custom conditional rendered components.

**Comment by gaearon** [comment] 2018-04-27 20:00
>Will facebook support any approach similar to JSX-Control-Statements in the future?

Not likely. We don't recommend this approach. We might add support for do-expressions to JSX in the future which should give you something similar in spirit though.

>If facebook does not support any approach like above, facebook should warn it's developers about using such library due to incorrect coverages.

There are thousands of React libraries that do strange things; we can't warn about every single one of them. Whenever this has been asked, we have always recommended against trying to recreate control flow as React components.

>Issue consistent in jest and nyc since they both use babel's AST.

It's not clear to me what the issue is about exactly, but it's not something related to the React repository so I'll close this.

**Closed by gaearon** 2018-04-27 20:00 UTC

**Comment by texttechne** [comment] 2018-11-21 22:19
Wow, everything is so wrong about this issue, that I cannot resist to comment:

1. JSX-Control-Statements is NOT a React component, but a babel plugin which transpiles to JS
1. The coverage report is correct, jsx-control-statements works as expected, only the test code is flawed (see: https://github.com/AlexGilleran/jsx-control-statements/issues/75)
1. to top things off this issue has been duplicated: #12698

**Comment by OverseePublic** [comment] 2018-11-21 22:59
I think you need to read again. I do not plan to waste more time. This will be my last comment for you.


‘’’
If facebook does not support any approach like above, facebook should warn it's developers about using such library due to incorrect coverages.
There are thousands of React libraries that do strange things; we can't warn about every single one of them. Whenever this has been asked, we have always recommended against trying to recreate control flow as React components.
‘’’
