### ISSUE TITLE
Strange behaviour for SVG defs

### ISSUE THREAD

**Issue by taddei** [facebook/react#2380] opened 2014-10-19 14:37 UTC
I have found a case where two very similar functions that output exactly the same DOM element, work in 2 different ways. Am I missing something? The only difference is I moved the DEFS block from the render function to the renderDefs function.

    var mainView = React.createClass({
    
      getInitialState: function () {
        return {
          showDef: false
        }
      },
    
      changeDefs: function () {
    
        this.setState({
          showDef: true
        })
      },
    
      renderDefs: function () {
        if (!this.state.showDef) return null;
        return (
        <defs>
          <linearGradient id="Gradient1">
            <stop offset="5%" stopColor="white"/>
            <stop offset="95%" stopColor="blue"/>
          </linearGradient>
        </defs>
          );
      },
    
      render: function () {
        var fillStyle = this.state.showDef ? {fill: "url(#Gradient1)"} : {fill: "red"};
        return (
          <svg viewBox="0 0 1024 700" onClick={this.changeDefs}>
              {this.renderDefs()}
            <rect x="0" y="0" height="50" width="50" style={fillStyle}/>
          </svg>
          );
      }
    
    //  FIXME, THIS VERION DOESN'T WORK
    //  NO CLUES WHY
    //  renderDefs: function () {
    //    if (!this.state.showDef) return null;
    //    return (
    //      <linearGradient id="Gradient1">
    //        <stop offset="5%" stopColor="white"/>
    //        <stop offset="95%" stopColor="blue"/>
    //      </linearGradient>
    //      );
    //  },
    //
    //  render: function () {
    //    var fillStyle = this.state.showDef ? {fill: "url(#Gradient1)"} : {fill: "red"};
    //    return (
    //      <svg viewBox="0 0 1024 700" onClick={this.changeDefs}>
    //        <defs>
    //          {this.renderDefs()}
    //        </defs>
    //        <rect x="0" y="0" height="50" width="50" style={fillStyle}/>
    //      </svg>
    //      );
    //  }
    });

**Comment by mmoriar1** [comment] 2016-03-15 18:43
FYI for any other internet denizens coming upon weird `<defs>` issues when adding elements dynamically to an `<svg>`, the key (pun intended) for me was to add a dynamic `key` property to `<defs>` so that react properly catches and schedules the update for the parent element itself.

**Comment by gaearon** [comment] 2016-03-18 21:42
Can you please prepare a fiddle that demonstrates the issue and add steps to reproduce it? Unfortunately I can’t figure out what to do with the fiddle in https://github.com/facebook/react/issues/2380#issuecomment-59807316. Thanks!

**Comment by gaearon** [comment] 2016-03-18 21:45
Whoops, never mind, I reproduced it in 0.14.
This appears fixed in v15 RC2: http://jsbin.com/getiwetolo/1/edit

I’m closing but please let me know if I missed something.

**Closed by gaearon** 2016-03-18 21:45 UTC
Labels: SVG, Type: Bug
