### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by TheRitual** [facebook/react#22963] opened 2021-12-15 06:16 UTC
### Website or app

https://github.com/TheRitual/ByHeart

### Repro steps

Accualy this bug appears only on React Native debugger. The web version of debugger doesn't show any errors. The project is new and i just installed packages
```
$ expo install react-navigation
$ expo install react-navigation-stack
$ expo install expo-app-loading
$ expo install react-native-screens
$ expo install react-native-safe-area-context
```

so my dependencies are:

```json
"dependencies": {
    "expo": "~43.0.2",
    "expo-status-bar": "~1.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "react-navigation": "^4.4.4",
    "react-navigation-stack": "^2.10.4",
    "expo-app-loading": "~1.2.1",
    "react-native-screens": "~3.8.0",
    "react-native-safe-area-context": "3.3.2"
  },
```

I checked and now this bug appears in every new expo init even if it is just blank project. Old projects work fine.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.14.0-d0ec283819

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:140545
    at c.emit (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:89515)
    at C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:90986
    at C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:347787
    at Array.forEach (<anonymous>)
    at S.Gc.e.onmessage (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:347771)
    at S.n (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:40:3009)
    at S.emit (events.js:315:20)
    at e.exports.P (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:9318)
    at e.exports.emit (events.js:315:20)
    at e.exports.dataMessage (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:15409)
    at e.exports.getData (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:14651)
    at e.exports.startLoop (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:12066)
    at e.exports._write (C:\Users\Ritual\AppData\Local\react_native_debugger\app-0.12.1\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:11421)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by jstejada** [comment] 2021-12-15 14:17
thanks for the report! merging as a duplicate of #21636

**Closed by jstejada** 2021-12-15 14:17 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools
