### ISSUE TITLE
Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 38"

### ISSUE THREAD

**Issue by antonramha** [facebook/react#16620] opened 2019-08-30 13:41 UTC
Describe what you were doing when the bug occurred:
1. Start profiling app, record and reload page
2. going through profilers commits
3. crush

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.6-a39d9c3

Call stack: at d (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:5745)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:8527)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:275553)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55891)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62940)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99536)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84256)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81286)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25364
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)

Component stack: in bi
    in div
    in div
    in div
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by bvaughn** [comment] 2019-08-30 14:36
@antonramha As the bug template asks for, could you describe what you were doing when the bug occurred? :smile:

Otherwise this is a duplicate of #16412 and since this one provides no new info, I'm going to close it.

**Closed by bvaughn** 2019-08-30 14:36 UTC
