### ISSUE TITLE
React DevTools failing to load state/props sidebar

### ISSUE THREAD

**Issue by gsouquet** [facebook/react#21187] opened 2021-04-06 17:18 UTC
I am working on a React application and when debugging it I have noticed that some components fail to load the right sidebar that usually contains the props and the state.

**Operating system:** macOs
**Browser:** Chrome and Firefox
**Devtools version:** Created from revision `f160547f47` on 12/4/2020
**React version:** 16.14.0

Upon debugging the application I could dig the following stack trace when focusing on the failing component in the tree

```
value is undefined main.js:1901
    hydrate moz-extension://1e1c0ba1-2bf5-d94f-82f9-a719f696d0a4/build/main.js:1901
    forEach self-hosted:206
    hydrate moz-extension://1e1c0ba1-2bf5-d94f-82f9-a719f696d0a4/build/main.js:1890
    hydrateHelper moz-extension://1e1c0ba1-2bf5-d94f-82f9-a719f696d0a4/build/main.js:29182
    onInspectedElement moz-extension://1e1c0ba1-2bf5-d94f-82f9-a719f696d0a4/build/main.js:29068
    emit moz-extension://1e1c0ba1-2bf5-d94f-82f9-a719f696d0a4/build/main.js:18990
    _wallUnlisten moz-extension://1e1c0ba1-2bf5-d94f-82f9-a719f696d0a4/build/main.js:19123
    listener moz-extension://1e1c0ba1-2bf5-d94f-82f9-a719f696d0a4/build/main.js:36391
    apply self-hosted:2705
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:616
    asyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:2432
```

Let me know if I could provide you with any more information that could be useful for you to look into this issue

**Comment by bvaughn** [comment] 2021-04-06 18:35
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-04-08 18:06
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-04-08 18:06 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
