### ISSUE TITLE
Number input goes into infinite loop when Chrome debugger on

### ISSUE THREAD

**Issue by eipark** [facebook/react#6506] opened 2016-04-13 13:59 UTC
Possibly related to: https://github.com/facebook/react/issues/1549

On Mac, Chrome 49. 

I have a pretty standard number input like so:

`<input type='number' step='0.01' min='0' onChange={someCallback} value={value}/`>

When I click the arrow in the input field to change the number, it works properly. However when I open the Chrome inspector and throw a breakpoint somewhere in my rendering flow, I get into an infinite loop where the value of the input field keeps incrementing. It's possible this may be a chrome bug as well. 

Stack trace showing how it's looping: 
![image](https://cloud.githubusercontent.com/assets/723778/14495595/2025a7bc-015e-11e6-9f22-13443151723c.png)

**Comment by gaearon** [comment] 2016-04-13 15:37
Would you mind reproducing this in JSFiddle? Thanks.

**Comment by jimfb** [comment] 2016-04-15 18:33
Ping @eipark

**Comment by eipark** [comment] 2016-04-15 18:42
Not sure if this is reproduceable with a jsfiddle since you need to set a breakpoint in the chrome debugger.

**Comment by jimfb** [comment] 2016-04-15 18:45
Can you modify and post the code from one of the examples in the React starter pack, with instructions on how to reproduce?

**Comment by eipark** [comment] 2016-04-15 19:01
Sure. Here is the `basic-jsx-external` example with a modified `example.js`:

```
var ExampleApplication = React.createClass({
  getInitialState() {
    return {value: 3.0};
  },
  render: function() {
    var elapsed = Math.round(this.props.elapsed  / 100);
    var seconds = elapsed / 10 + (elapsed % 10 ? '' : '.0' );
    var message =
      'React has been successfully running for ' + seconds + ' seconds.';

    // Set a breakpoint here in Chrome and click the arrow on the input field
    return (
      <div>
        <p>{message}</p>
        <input type='number' step='0.01' min='0.0' value={this.state.value} onChange={(e) => {this.setState({value: e.target.value})}}/>
      </div>
    );
  }
});

var start = new Date().getTime();

setInterval(function() {
  ReactDOM.render(
    <ExampleApplication elapsed={new Date().getTime() - start} />,
    document.getElementById('container')
  );
}, 50);
```

I was able to repro the bug with this setup.

**Comment by jimfb** [comment] 2016-04-18 22:08
Ok, nice repro!  I was able to reproduce.  @spicyj immediately said "Chrome bug!" as soon as he saw it, maybe he is right.  Interestingly, the Firefox debugger behaves even worse than Chrome does.

I spent a good chunk of the day trying to root cause this (probably more time than it is worth).  On a whim, I decided to comment out the fake-dom-node-event-logic, and that fixed the issue.

@spicyj says he'd still call that a chrome bug, and that we could probably file a bug.

Action items:
- [ ] Fix React.
- [ ] File chrome bug.

**Comment by jimfb** [comment] 2016-04-18 22:49
Actually, I take that back, perhaps it is not related to the fake-dom-node-logic.  I was overly excited, commenting it out doesn't appear to have done anything :(.

**Comment by nhunzaker** [comment] 2016-08-06 14:23
This appears to be a bug in Chrome:

![loop](https://cloud.githubusercontent.com/assets/590904/17457204/7bf3e7a0-5bbf-11e6-9967-828bd6c97637.gif)

Using:

```javascript
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <input type="number" step="0.01" min="0" value="3" />
    <script>
      document.querySelector('input').addEventListener('input', function(e) {
        // Break here!
        console.log(e.target.value);
      })
    </script>
  </body>
</html>
```

Chrome continues to dispatching a new `input` event until another event is fired. If the move my mouses, or a key is pressed, the loop halts.

**Comment by nhunzaker** [comment] 2016-08-06 14:39
Went ahead and filed an issue: https://bugs.chromium.org/p/chromium/issues/detail?id=635244&can=2&start=100&num=100&q=breakpoint&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by spicyj** [comment] 2016-08-15 19:27
Thanks @nhunzaker!

**Comment by nhunzaker** [comment] 2017-09-18 16:13
Fixed in Chrome!
https://bugs.chromium.org/p/chromium/issues/detail?id=635244&can=2&start=100&num=100&q=breakpoint&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Closed by nhunzaker** 2017-09-18 16:13 UTC
