### ISSUE TITLE
isMounted() returning undefined

### ISSUE THREAD

**Issue by chandu0101** [facebook/react#4163] opened 2015-06-18 03:46 UTC
isMounted() returning undefined instead of false/true

```js

   * Checks whether or not this composite component is mounted.
       * @return {boolean} True if mounted, false otherwise.
       * @protected
       * @final
       */
      isMounted: function() {
        if ("production" !== process.env.NODE_ENV) {
          var owner = ReactCurrentOwner.current;
          if (owner !== null) {
            ("production" !== process.env.NODE_ENV ? warning(
              owner._warnedAboutRefsInRender,
              '%s is accessing isMounted inside its render() function. ' +
              'render() should be a pure function of props and state. It should ' +
              'never access something that requires stale data from the previous ' +
              'render, such as refs. Move this logic to componentDidMount and ' +
              'componentDidUpdate instead.',
              owner.getName() || 'A component'
            ) : null);
            owner._warnedAboutRefsInRender = true;
          }
        }
        var internalInstance = ReactInstanceMap.get(this); // undefined in our case
        return (
          internalInstance &&
          internalInstance !== ReactLifeCycle.currentlyMountingInstance
        );
      },

```
please check this for long story : https://github.com/japgolly/scalajs-react/pull/146

**Comment by spicyj** [comment] 2015-06-18 04:00
Dupe of #3814 (fixed in master already).

**Closed by spicyj** 2015-06-18 04:00 UTC
