### ISSUE TITLE
Error: "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by mikethejet** [facebook/react#21218] opened 2021-04-09 06:52 UTC
Describe what you were doing when the bug occurred:
1.  run expo app in a web browser
2. it uses WebView component
3. WebView not loaded so i look to console..

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-f160547f47

Call stack: at formatSourceForDisplay (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32085:27)
    at Source (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32123:6)
    at Hh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:12807:7)
    at mk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16012:11)
    at lk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15459:11)
    at kk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15451:23)
    at ck (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15435:5)
    at Wj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15047:105)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:17261:17)
    at MessagePort.Q.port1.onmessage (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:17300:7)

Component stack: at Source (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32105:3)
    at div
    at InspectedElementView_InspectedElementView (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31992:3)
    at div
    at InspectedElementWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32192:50)
    at Suspense
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31435:3)
    at div
    at div
    at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28921:3)
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27558:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28206:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33383:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29219:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29336:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32934:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24322:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24811:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29404:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36207:3)

**Comment by bvaughn** [comment] 2021-04-09 14:01
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-04-13 15:44
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-04-13 15:44 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed
