### ISSUE TITLE
Bug: Debugger triggered twice in StrictMode

### ISSUE THREAD

**Issue by hxse** [facebook/react#22720] opened 2021-11-08 05:13 UTC
React version:
  "react": "^17.0.0"
  "vite": "^2.6.4"
  "@vitejs/plugin-react": "^1.0.0"
## Steps To Reproduce

1. yarn create vite test --template react
2. **code in src/App.jsx** 
```
import React from "react";
import { useState } from "react";
import logo from "./logo.svg";
import "./App.css";
function App() {
  const [clicks, setClicks] = useState(0);
  console.log("I render 😁");
  function countAdd() {
    setClicks((clicks) => {
      console.log("click...");
      debugger;
      return clicks + 1;
    });
  }
  return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <button onClick={countAdd}>Clicks: {clicks}</button>
        </header>
      </div>
  );
}

export default App;
```
3. **code in main.jsx**
```
import React from 'react'
import ReactDOM from 'react-dom'
import './index.css'
import App from './App'

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
```
3. yarn install && yarn run dev
4. open chrome 127.0.0.1:3000 and open chrome DevTools

## The current behavior
When I first clicked the button everything went as expected
When I click the button the second time , the breakpoint will be triggered twice, the log only prints once, the log is expected, but the breakpoint is not.
The third click is the same as the second click
Removing the `<React.StrictMode>` of the parent component(main.jsx) behaves as expected
## The expected behavior
Trigger breakpoints only once.

**Comment by guojin-long** [comment] 2021-11-09 02:19
进入两次是正确的。  可以参考  https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by hxse** [comment] 2021-11-09 05:48
> 触发两次是正确的。 可以参考 https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

I know there will be two calls, but there shouldn't be twice debugger triggered  because the log only triggered once.
Since log only triggered once, so debug should only triggered once, otherwise this logic is inconsistent.

**Comment by guojin-long** [comment] 2021-11-09 13:21
根据严格模式的初衷，是为了暴露意料之外的副作用。    我觉得react在渲染的时候临时禁用了console.log也许不是件好事，因为console.log也是副作用之一。  从某种程度上来说， 加重了开发者的心智负担，毕竟还有不少的人习惯用console.log来调试应用程序。相关的issue在之前有人提出过，相信以后还会有人继续提出。

**Comment by bvaughn** [comment] 2021-11-09 13:34
> I know there will be two calls, but there shouldn't be twice `debugger` triggered  because the `console.log` only triggered once.
Since `console.log` only triggered once, so `debugger` should only triggered once, otherwise this logic is inconsistent.
Also, `debugger` triggered twice is very affects debugging efficiency.

I understand why this is confusing, but this is the intentional, expected behavior.

In newer versions of React, DevTools can be used to control whether or not the console logs are suppressed for the second/double render. In older versions of React, they are suppressed by default.

Regardless, neither React nor DevTools can disable `debugger` statements. So this is why the two mismatch.

My apologies for the confusion. I'm going to close this issue since it's working as designed (and as best we can support).

**Closed by bvaughn** 2021-11-09 13:34 UTC
Labels: Status: Unconfirmed
