### ISSUE TITLE
Error: "Commit tree does not contain fiber 12613. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by bloycey** [facebook/react#19340] opened 2020-07-14 00:02 UTC
Describe what you were doing when the bug occurred:
1. Recorded activity using profiler tool.
2. Navigated to ranked tab.
3. Error message displayed.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.1-d4eadea6c

Component stack: Wl@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:347075
div
div
div
Eo@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:267242
$c<@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:371653
n@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:280167
ra/<@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:282951
div
div
Ji@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:330056
Ge@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:209982
sn@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:219298
Wa@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:298042
ps@moz-extension://11647b02-2c4c-4d9c-945f-5dde85fa8015/build/main.js:40:376893

**Comment by bvaughn** [comment] 2020-07-14 02:12
Duplicate of #18831

**Closed by bvaughn** 2020-07-14 02:12 UTC
