### ISSUE TITLE
Bug: Render after suspense is thrown away leaving DOM unmatched with state

### ISSUE THREAD

**Issue by joeljeske** [facebook/react#18844] opened 2020-05-06 16:31 UTC
React version: 16.12.0

## Steps To Reproduce

 A component that suspends as a result of a context update is never rendered to DOM after suspension is finished.

Link to code example:

https://codesandbox.io/s/react-suspense-context-bug-rklls?file=/package.json:163-170

## The current behavior

If a component suspends as a result of a context update, the component's render is called after suspension is finished but the result of the render is not reflected in the DOM (and effects aren't called). 

## The expected behavior

If a component suspends as a result of a context update, the component's render should be called and flushed to the DOM and effects called. 

## Related Issues: 

https://github.com/facebook/react/issues/17356 - seems related to memoization but this does not use any memoization

**Comment by chriserickson-cb** [comment] 2020-05-28 14:58
We ran into this same problem, the codesandbox seems like a pretty good reproduction case.

We're on React 16.9 / React Native 0.61.5.

**Comment by gaearon** [comment] 2020-06-29 19:53
I think this is a duplicate of https://github.com/facebook/react/issues/17356.

>seems related to memoization but this does not use any memoization

It does use memoization in the sense that `children` is always going to be the same element since it's passed from above.

**Closed** 2020-06-30 21:06 UTC
Labels: Component: Reconciler, Component: Suspense, Type: Bug
