### ISSUE TITLE
React 15-rc.1 regression: onTouchTap not working

### ISSUE THREAD

**Issue by appsforartists** [facebook/react#6221] opened 2016-03-08 22:30 UTC
[onTouchTap](https://github.com/zilverline/react-tap-event-plugin) stops working in React 15.  I've prepared [this reduction](http://codepen.io/appsforartists/full/grrMVZ).

The only difference between pane A and pane B is which version of React is used.  If you open it on a touchscreen device (or in DevTools with emulation on), you'll see that onTouchTap worked in React 14, but ceases to work in React 15.

**Comment by appsforartists** [comment] 2016-03-08 22:41
Someone proposed that onTouchTap might now be integrated.  [It's not](http://codepen.io/appsforartists/full/wGGzzw)

**Comment by saumya** [comment] 2016-03-09 06:13
Finally! Thanks for the heads up.
After banging on for 2 days and trying to fix on my side, thinking everything is wrong on my setup, [commented here](https://github.com/callemall/material-ui/issues/1192#issuecomment-193892684) yesterday.

I thought its MaterialUI. Will give it a try on React 14.

**Comment by saumya** [comment] 2016-03-09 06:27
I have now tested it with `"react": "^0.14.7"` and `"react-dom": "^0.14.7"`. It works fine, without even the touch emulator.

**Comment by gaearon** [comment] 2016-04-01 01:22
This is not a regression.

If you look at the [history of TapEventPlugin in the React codebase](https://github.com/facebook/react/commits/master/src/renderers/dom/client/eventPlugins/TapEventPlugin.js) you will see that it was affected by one of the recent refactorings (it’s internal code and we make no guarantees about the API stability). Specifically, 4a465fbd9a99815e9a0eb8b14af0c0423d9e8552 and f470cb88f88b4667419f170fcc7971dad4298494 changed some of the arguments that were being passed.

I sent a PR to `react-tap-event-plugin` that mirrors these changes. In my testing this makes it compatible with React 15 RC2, and I would expect it to also be compatible with the final 15 because that code hasn’t changed since. You can find that PR as https://github.com/zilverline/react-tap-event-plugin/pull/65.

I’m closing this but please let us know if you have any other issues. Cheers!

**Closed by gaearon** 2016-04-01 01:22 UTC

**Comment by appsforartists** [comment] 2016-04-01 06:39
I didn't realize that TapEventPlugin was still maintained internally.

What's the plan for unifying the two?  React should support touch events out-of-the-box.  If for some reason that's out-of-scope, can Facebook use/maintain the npm package, so we don't have two parallel copies of the same code?

**Comment by gaearon** [comment] 2016-04-01 12:08
I don't think it's maintained per se. It's just that there was an internal refactoring that changed the argument order, and @soprano went through all matching call sites, changing them there, and it happened to include TapEventPlugin. We make no guarantees about it not being broken. I think we should remove it from the core source code. But yeah, this means that its maintainers will need to track changes to internal APIs. We don't have a better solution right now. Eventually we might expose event system officially as well as DOM configs but if addons taught us anything, it's that anything we expose creates a huge maintenance burden down the road which creates significant delays in development of React itself. So please excuse us that we don't have a good story around this right now. We are happy to discuss handling taps in a separate issue though so feel free to file it! Thanks.

**Comment by jimfb** [comment] 2016-04-01 17:29
@gaearon is correct.  To add to his comment, the plan is to rip it out of the core repository and have this handled in user land, as per: https://github.com/facebook/react/issues/436#issuecomment-178268985

**Comment by appsforartists** [comment] 2016-04-01 17:46
Thanks guys.

For some reason, I remembered touch events not being detected without TapEventPlugin being installed.  I [just tested it](http://codepen.io/appsforartists/pen/PNJjOa), and that is no longer the case.  Since [Chrome](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away?hl=en) and [Safari](https://trac.webkit.org/changeset/191072) have both removed their tap delays for mobile pages, it's probably time to stop using TapEventPlugin and just us the onClick event.

As for gestures, I'm considering building higher-order-components to detect them, and I certainly won't be quite about it if it happens.  :wink:

**Comment by gaearon** [comment] 2016-04-01 18:00
>Since Chrome and Safari have both removed their tap delays for mobile pages, it's probably time to stop using TapEventPlugin and just us the onClick event.

:+1:

**Comment by ffxsam** [comment] 2016-04-08 06:25
@appsforartists 
>Since Chrome and Safari have both removed their tap delays for mobile pages

But how long will it take for these changes to hit iOS Safari? The latest iOS 9.3.1 doesn't have fast tap response.

**Comment by pudgereyem** [comment] 2016-09-23 10:45
> Since Chrome and Safari have both removed their tap delays for mobile pages, it's probably time to stop using TapEventPlugin and just use the onClick event.

Totally agree @appsforartists.

However, while `onClick` is working fine (meaning; without 350ms delay) in modern iOS Safari, it does not work with Cordova. Anyone that has encountered the same issue, and know why that is the case?
