### ISSUE TITLE
Bug: <div> stops scrolling using keyboard arrows when tabIndex is specified for the onKeyDown event to work

### ISSUE THREAD

**Issue by holem** [facebook/react#25462] opened 2022-10-11 12:17 UTC
Hi everyone. 

There is one `div` that is always wider than the page have available space for it. It is placed in a container with `overflow-x: visible`, which in turn is placed in a flex container. So, with this layout, if you click on this `div` and then press the left-right arrows on the keyboard, the container will scroll. This is the expected behavior (at least in Chrome and Edge, but for some reason not in Firefox).

Now I need to add an `onKeyDown` event handler to change the contents of the `div` when certain buttons on the keyboard are pressed (including left-right arrows). In order for the `onKeyDown` event to work, you need to add `tabIndex=0` for this block. But when I have the `tabIndex` added, the container stopped scrolling when the right-left arrows are pressed. And this is not the expected behavior. I expect that scrolling the container with the left-right arrows from the keyboard will continue to work even if we started listening for keystroke events.

Probably, `event.preventDefault()` should be called to cancel this scrolling effect, but in this particular case I'm not calling this function.

React version: 18.2

## Steps To Reproduce

Here is the code on CodeSandbox that demonstrates the problem: 
https://codesandbox.io/s/onkeydown-arrow-scroll-problem-97e00l

## The current behavior

When `tabIndex` is specified, scrolling the `div` element using the left-right arrows from the keyboard stops.

## The expected behavior

Adding a `tabIndex` property and/or `onKeyDown` event handler should not affect the `div` scroll control capabilities. So the `div` should scroll with left-right arrows.

**Comment by unaisshemim** [comment] 2022-10-11 14:22
If you set the tabindex attribute on a [<div>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div), then its child content cannot be scrolled with the arrow keys unless you set tabindex on the content, too. [Check out this fiddle to understand the scrolling effects of tabindex](https://jsfiddle.net/jainakshay/0b2q4Lgv/).


ref-https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by cskaust** [comment] 2022-10-12 07:45
Can i please know how to raise issues as a github beginner

**Comment by eps1lon** [comment] 2022-10-16 09:54
Closing since this is expected behavior in the DOM as explained in https://github.com/facebook/react/issues/25462#issuecomment-1274775248

**Closed by eps1lon** 2022-10-16 09:54 UTC
Labels: Status: Unconfirmed
