### ISSUE TITLE
Custom property names containing "[" or "]" get removed from custom components

### ISSUE THREAD

**Issue by dfrankland** [facebook/react#12455] opened 2018-03-26 06:35 UTC
This could be considered a bug or a feature request. I say this because I know that React is checking for [W3C valid attribute property names](https://www.w3.org/TR/xml/#NT-NameStartChar), but the check is run inconsistently between normal components and custom components which makes its behavior confusing. That means this could be feature to be more explicit about its behavior.

For my particular use case, this only needs to be improved upon in `react-dom/server`. I am trying to render custom properties like those belonging to [`amphtml`](https://github.com/ampproject/amphtml), particularly the [`amp-bind`](https://www.ampproject.org/docs/reference/components/amp-bind) API which requires `[` and `]` in property names. I think that the [check for valid attribute property names](https://github.com/facebook/react/blob/dadafd6bd802082b990e447032cb82574bcdc118/packages/react-dom/src/server/DOMMarkupOperations.js#L79-L81) should only throw warnings, or it should have an option to prevent the removal of custom properties.

Example:

*   JS
    ```js
    const customProps = {
      "[custom-property]": "Hello, world!"
    };
    ```

*   JSX
    ```js
    <div>
      <div {...customProps}>Test</div>
      <custom-component {...customProps}>Test</custom-component>
    </div>
    ```

*   Resulting HTML
    ```html
    <div data-reactroot="">
      <div [custom-property]="Hello, world!">Test</div>
      <custom-component>Test</custom-component>
    </div>
    ```

This throws a warning only for the `<custom-component />`.

Try it out in CodeSandbox: <https://codesandbox.io/s/vjj64jv2z0>

**Comment by aweary** [comment] 2018-03-26 16:54
Hey @dfrankland, this is a duplicate of #10064.

**Closed by aweary** 2018-03-26 16:54 UTC
