### ISSUE TITLE
CDN production version is broken

### ISSUE THREAD

**Issue by j055** [facebook/react#14765] opened 2019-02-06 11:51 UTC
Hi

This morning all of our sites which use React have stopped working. We use the CDN:

https://unpkg.com/react@16/umd/react.production.min.js

https://unpkg.com/react-dom@16/umd/react-dom.production.min.js

To reproduce download zip and run example from here:

https://reactjs.org/docs/add-react-to-a-website.html

The sites work with the development version but switching to the production version causes script error:

    react-dom.production.min.js:134 Uncaught TypeError: Cannot read property 'current' of undefined
        at Vg (react-dom.production.min.js:134)
        at Xc (react-dom.production.min.js:147)
        at ra (react-dom.production.min.js:146)
        at Qc (react-dom.production.min.js:144)
        at Ba (react-dom.production.min.js:142)
        at fh (react-dom.production.min.js:159)
        at Ce (react-dom.production.min.js:159)
        at rb.render (react-dom.production.min.js:214)
        at react-dom.production.min.js:163
        at dh (react-dom.production.min.js:158)
    Vg @ react-dom.production.min.js:134
    Xc @ react-dom.production.min.js:147
    ra @ react-dom.production.min.js:146
    Qc @ react-dom.production.min.js:144
    Ba @ react-dom.production.min.js:142
    fh @ react-dom.production.min.js:159
    Ce @ react-dom.production.min.js:159
    rb.render @ react-dom.production.min.js:214
    (anonymous) @ react-dom.production.min.js:163
    dh @ react-dom.production.min.js:158
    ad @ react-dom.production.min.js:163
    render @ react-dom.production.min.js:216
    (anonymous) @ like_button.js:25

**Workaround**

Specify previous version:

https://unpkg.com/react@16.7.0/umd/react.production.min.js

https://unpkg.com/react-dom@16.7.0/umd/react-dom.production.min.js

Please advise

Thanks

Andrew

**Comment by bvaughn** [comment] 2019-02-06 12:56
At a quick glance, I think that line is referring to `ReactCurrentOwner`

**Comment by bvaughn** [comment] 2019-02-06 12:59
Changing  `react.production.js` and `react-dom.production.js`  to `react.production.min.js` and `react-dom.production.min.js` works for me. Maybe it was a transient unpkg issue?

**Comment by gaearon** [comment] 2019-02-06 13:01
Do these two links work for you?

https://unpkg.com/react@16.8.0/umd/react.production.min.js
https://unpkg.com/react-dom@16.8.0/umd/react-dom.production.min.js

**Comment by bvaughn** [comment] 2019-02-06 13:03
This does highlight the fact that splitting the current owner/dispatcher refs (#14548) probably broke peer dependencies.

**Comment by j055** [comment] 2019-02-06 13:15
Yes. My test is working again without changing anything.

**Comment by bvaughn** [comment] 2019-02-06 13:25
To be clear, an older version of `react` package will not work with a newer version of a renderer.

An older renderer _will_ work with a newer version of the `react` package.

**Comment by bvaughn** [comment] 2019-02-06 15:34
This specific issue was caused by a transient unpkg problem, so I'm going to close it. The backwards incompatibility this is covered by #14763 so let's track it there.

**Closed by bvaughn** 2019-02-06 15:34 UTC
Labels: Status: Unconfirmed
