### ISSUE TITLE
Difference between controlled and uncontrolled components should not be value={null|non null}

### ISSUE THREAD

**Issue by joshudson** [facebook/react#21619] opened 2021-06-04 00:54 UTC
On working with React we keep on having strange almost non-debuggable and non-bisectable issues that eventually turn out to be a null got where it shouldn't have been despite programming in typescript. We have no idea why JSX/TSX components work this way, but it's completely non-intuitive and troublesome.

We're tired of debugging this repeatedly, and really would insist that it must be dependent on whether value was set at all as opposed to whether it was set to non-null.

Anyway, we're not alone. On searching the complete issue list to see if somebody had filed this before, I found @rymohr <A HREF="https://github.com/facebook/react/issues/2533#issuecomment-72974806">wrote in issue #2533</A>:

<BLOCKQUOTE>
I still think react should be checking for the presence of a value key, not the value itself. If you want the component to be uncontrolled, don't pass a value prop.

// controlled
<textarea value={this.props.text} />

// uncontrolled
<textarea />

Removes any possible confusion since you no longer need to know all possible values of this.props.text to know if the textarea is controlled or not.
</BLOCKQUOTE>

An alternative solution would be to add another property `forceControlled: boolean|null|unknown` that if set to true or false overrides the value behavior and sets the controlled-ness to the given value of that property. I'm not quite sure, but I think setting `value` and `forceControlled` to false should act like setting `defaultValue`. But also consider checkboxes ...

I have no idea how one would go about fixing it (backwards compatible or not), but we are actually willing to drop React over this if it isn't fixed. Web searches reveal this is actually a quite common stumbling block for beginners even up to rather high level because the behavior is so non-intuitive that it resists bisection.

**Comment by markerikson** [comment] 2021-06-04 02:44
I'm not on the React team, but tbh I'm having trouble trying to understand what situation or behavior you're even describing here. Can you provide some kind of a CodeSandbox or code example that demonstrates the concerns you're trying to discuss?

**Comment by joshudson** [comment] 2021-06-04 03:35
@markerikson: `<textarea value={''} />` and `<textarea value={null} />` have radically different behaviors and we are fed up with the bugs due to it.

**Comment by markerikson** [comment] 2021-06-04 04:25
For the benefit of myself and anyone else reading: could you recap _what_ the different behaviors are?  What "bugs" are you referring to here - are you saying that React itself is broken somehow, or that your own app has issues when you accidentally let a null through?

**Comment by joshudson** [comment] 2021-06-04 04:39
@markerikson When a null gets through the control's type is initialized as uncontrolled. If you expect a controlled component and get an uncontrolled component, the internal state desyncs. And if the component would become controlled later because the variable inside `{}` changes to have a non-null value, strange behavior persists as the component never really becomes controlled.

I'm not really at the point where I can say bugs in my own code or bugs in the react library; but in any case it doesn't matter as the user-facing behavior of such controls is inconsistent and doesn't follow any apparent model to the user. The react manual pretty much straight up says don't try to change a control between controlled and uncontrolled, which is not something we're intending to do.

From a design standpoint it's too much of a hazard to the developer having an API like this, and from a quality control analysis this nonsense needs to be stopped once and for all one way or another. It visually passes inspection writing `<textarea value={variable} onchange={...}>` (or `<input value={variable}>  onchange={...}`) for that matter but the code is fragile and too often a null comes by and hoses something.

**Comment by bvaughn** [comment] 2021-06-04 14:45
@joshudson I'm sorry you and your team have had a frustrating experience.

Unfortunately, it doesn't look like this issue has enough info for one of us to understand what you're reporting, or to reproduce it.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by gaearon** [comment] 2021-06-04 14:47
To be clear I don't think there's a known difference between `value={null}` and `value={''}`, both should be treated as empty and controlled. The only uncontrolled one is `value={undefined}`.

**Comment by joshudson** [comment] 2021-06-04 14:49
And I think the only uncontrolled one should be "didn't set `value=` at all".

**Comment by gaearon** [comment] 2021-06-04 14:52
That could be one way to do it, though many people don't realize the difference between not having a property and having that property being set to `undefined`. I don't think we currently have any APIs that distinguish presence of a property from it being non-`undefined` so it would create a new precedent. At the same time, plenty of people want to work it in the opposite way, and have `null` be treated as uncontrolled: https://github.com/facebook/react/issues/11417. If we do change it, one way or another, it would be a pretty significant change for a lot of codebases. I don't know that the solution you're proposing solves more issues than it creates.

**Comment by joshudson** [comment] 2021-06-04 14:54
What about the other idea; an explicit boolean property that when provided sets controlled or uncontrolled? We could easily have a quality control rule of always set this property.

**Comment by nmain** [comment] 2021-06-04 14:59
You might consider rolling your own input components that encapsulate the logic that you feel is important to your projects.  You can easily have any logic you want for what is and isn't controlled in it, and pass the appropriate `undefined` to the native DOM input in one small piece of easily auditable code.

**Comment by gaearon** [comment] 2021-06-04 15:02
Yeah I'd say using your own components is best practice either way.

**Comment by joshudson** [comment] 2021-06-04 15:02
Hmmm that is a real possibility.

**Comment by joshudson** [comment] 2021-06-04 15:07
Incidentally, this page https://reactjs.org/docs/forms.html contains the unfortunate text "If you’ve specified a value but the input is still editable, you may have accidentally set value to undefined or null"

**Comment by bvaughn** [comment] 2021-06-04 15:39
Thanks for the feedback, Josh. I'm going to close this issue now because it doesn't seem like this is a _bug_ so much as a discussion about why the API works the way it does. Like Sophie said [back in 2019](https://github.com/facebook/react/issues/11417#issuecomment-473368945), it's unlikely that we'll make changes to this API since the changes would likely just have different positive and negative tradeoffs. An [RFC](https://github.com/reactjs/rfcs#react-rfcs) would be the best route to go to propose a change to an API like this though, if there's a compelling case to be made.

**Closed by bvaughn** 2021-06-04 15:39 UTC
Labels: Resolution: Needs More Information
