### ISSUE TITLE
HTML5 input browser warnings

### ISSUE THREAD

**Issue by radekmie** [facebook/react#6992] opened 2016-06-08 08:49 UTC
In my render method, I have something like

```js
<input type="email" value={this.state.input} onChange={() => {}} />
```

If I first render this input - no matter what - browser remains silent. When I call `this.setState({input: 'invalid2'})` (or press any with this input focused), it moves cursor at the end and yields a warning:

![screenshot from 2016-06-08 10-45-11](https://cloud.githubusercontent.com/assets/1379064/15888235/644a6d18-2d66-11e6-8640-34408f46dd80.png)

[jsfiddle](https://jsfiddle.net/n0rdtv1f/)

This might be related: #6441.

It's happening in 15.1.0, I haven't tested any other version.

Is this expected behavior?

**Comment by lionng429** [comment] 2016-06-08 09:00
@radekmie you should read more about [Controlled Component](https://facebook.github.io/react/docs/forms.html#controlled-components). it does not related to #6441

**Comment by radekmie** [comment] 2016-06-08 09:09
@lionng429 I've read it. Okay, it's not related to #6441, but how to fix it? Even if `onChange` is a normal handler (I've used empty handler because it was quicker), this warning occurs and cursor is moved to the end.

**Comment by lionng429** [comment] 2016-06-08 09:42
@radekmie 
I cannot reproduce the error with a proper handler [here](https://jsfiddle.net/d0jx5rq9/1/). any info about browser version?

**Comment by radekmie** [comment] 2016-06-08 10:59
@lionng429
Now there's no warning on `onChange`, but it's still present after `setState` in `setTimeout`. I've got this warning in Chrome 53.

**Comment by jimfb** [comment] 2016-06-08 17:49
Chrome is trying to be smart.  They are warning if you set the invalid value outside of the event handler (the idea being, you are getting your 'value' from your app instead of from the user input, so it should be a valid value).

Personally, I think chrome is being overly aggressive with this warning, but that's a design decision.  You could file a bug on Chrome if you'd like.  Explain your use case, etc.

Regardless, this is not a bug in React, and I don't know of anything we could do to mitigate this issue, so I'm going to close it out.

**Closed by jimfb** 2016-06-08 17:49 UTC

**Comment by radekmie** [comment] 2016-06-08 19:05
Thanks @jimfb.

**Comment by bradwestfall** [comment] 2016-08-05 16:24
Wanted to open this again because there seems to be a difference between React 15.1 and 15.3. In 15.1 a controlled `<input type="email"/>` field doesn't experience repeated warnings, but in 15.3 it does. Look at these pens that have the exact same code and open devtools - then type random chars into each pen's `input`

React 15.1: http://codepen.io/bradwestfall/pen/ZOqJKm
React 15.3: http://codepen.io/bradwestfall/pen/RRZJWk

![react](https://cloud.githubusercontent.com/assets/2272118/17443208/34bcbadc-5aee-11e6-9e7e-edcbd958e9cb.gif)

**Comment by pgiankoulidis** [comment] 2016-08-05 16:27
Στις 5 Αυγ 2016 19:26, ο χρήστης "Brad Westfall" <notifications@github.com>
έγραψε:

**Comment by radekmie** [comment] 2016-08-05 17:35
@bradwestfall
I've tested almost all versions of React - [here are my results](https://github.com/vazco/uniforms/issues/80#issuecomment-234642159).

**Comment by bradwestfall** [comment] 2016-08-05 20:02
Thanks @radekmie. But I still don't fully understand. Does this mean a fix is coming or the new behavior is the new status quo?

**Comment by radekmie** [comment] 2016-08-05 20:12
Unfortunately I don't know.
