### ISSUE TITLE
ios 8.4 safari react dom : Attempting to configurable attribute of unconfigurable property.

### ISSUE THREAD

**Issue by TomD3Wiz** [facebook/react#13676] opened 2018-09-18 05:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Page crashes

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

![image](https://user-images.githubusercontent.com/5779182/45666143-c9621f80-bb57-11e8-9845-bffae5a06b7f.png)

Can't load any of the fiddle pages in ios 8.4 but a basic react app should demonstrate the issue. 

**What is the expected behavior?**
App should load 
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.4.2

**Comment by philipp-spiess** [comment] 2018-09-20 21:14
Hey!

I'm having a hard time reproducing this issue. When I use a new CodeSandbox project (https://new.codesandbox.io) it does indeed not work on iOS 8.4 but this is due to the code that CodeSandbox is inserting:

![](http://cl.ly/777548d8cee0/Screen%20Shot%202018-09-20%20at%2023.06.05.png)

React itself is working as expected on iOS 8.4, no matter if I use the production or development build of React. I've deployed our internal testing application so you can try it out: https://philipp-react-dom-fixtures.netlify.com

![](http://cl.ly/b34259803c33/Screen%20Shot%202018-09-20%20at%2023.10.40.png)

I suggest you try and find out if other code is interfering by removing everything that is not React specific to your application.

I'm closing this ticket for now as iOS 8.4 is clearly working in the latest React version but feel free to follow up with a reproduction case that is isolated enough.

**Closed by philipp-spiess** 2018-09-20 21:14 UTC
