### ISSUE TITLE
React.renderComponentToStaticMarkup doesn't generate selected attributes from value/defaultValue

### ISSUE THREAD

**Issue by insin** [facebook/react#1398] opened 2014-04-11 11:16 UTC
I'm using static markup for unit testing [newforms](https://github/insin/newforms) output and I'd also like to support using it to render forms as static HTML.

Adding a `value` or `defaultValue` to a `<select>` doesn't generate static HTML with the appropriate `selected` attributes. However, they do get generated if you manually add them to `<option>` components, but then you get warning messages in the console when using the development build of React.

Is it possible to support both use cases without manually setting `selected` attributes, or will I just have to live with the warnings? :)

JSFiddle showing `<select>` static HTML output: http://jsfiddle.net/insin/2tvb7/3/

**Comment by martintietz** [comment] 2015-02-16 17:40
+1

**Comment by RickWong** [comment] 2015-02-18 12:24
What's the status on this? It's hard to choose between: losing the benefits of server-side rendered React, or not remembering the customer's selected options.

Right now the only workaround that solves both is to put an extra duplicate of the selected value, at the top of the option list. :cry: 
@spicyj ?

**Comment by scottnonnenberg** [comment] 2015-03-12 18:39
+1 the warning is ugly, and so is the duplicate option at the top of the list.

Right now I'm going with the duplicate option because on the server side the warning goes to stderr, which my systems interpret as a real problem.

**Comment by jwalton** [comment] 2015-04-05 21:16
+1: Came here today to raise this exact issue.  :)

**Closed** 2015-04-07 23:49 UTC
Labels: Type: Bug
