### ISSUE TITLE
shallow compare & test renderer have strict dependencies

### ISSUE THREAD

**Issue by peacechen** [facebook/react#8468] opened 2016-11-30 20:40 UTC
I'm using multiple libraries which call for various versions of React and React Native.  NPM tries to find a common compatible version for everything, but these warnings persist:

> npm WARN react-addons-shallow-compare@15.3.2 requires a peer of react@^15.3.2 but none was installed.
> npm WARN react-test-renderer@15.4.1 requires a peer of react@^15.4.1 but none was installed.

Is it necessary to tightly couple the versions?  It would be beneficial to loosen the dependencies and let the consumer of the library choose which version to use.

**Comment by Aweary** [comment] 2016-11-30 20:46
You should install a version of `react-test-renderer` and `react-addons-shallow-compare` corresponding to the version of `react` and `react-dom` that you know you depend on.

These packages often depend on React internals (especially `react-test-renderer`) which means they should always be paired with the same version of React and ReactDOM. Mixing versions will likely result in undefined behavior.

**Comment by gaearon** [comment] 2016-11-30 20:46
To be fair they don't depend on internals *as much* since 15.4.0 but we'll likely stick with current strategy at least until 16.

**Comment by Aweary** [comment] 2016-11-30 23:03
Very true, it's better than it was. But even a small dependency on some internal state or module is enough to avoid mismatching versions, so I think we can close this for now as expected behavior and revisit when the situation changes.

**Closed by Aweary** 2016-11-30 23:03 UTC

**Comment by peacechen** [comment] 2016-12-02 16:50
react-test-renderer and shallow-compare are not explicit dependencies of my project.  It's a sub-dependency of another library, so I don't have control over what they're relying on.

**Comment by gaearon** [comment] 2016-12-02 16:54
Then that library should also depend on React of that version. But then it’s harder for you to use since you might have a different version of React. So seems like a good solution would be to ask that library to move **them all** to peer dependencies.
