### ISSUE TITLE
Problem with react useState and useEffect

### ISSUE THREAD

**Issue by rdwnsjjd** [facebook/react#23002] opened 2021-12-20 15:47 UTC
I have this code : 
```jsx
function Parent(props) {

    const [items, setItems] = useState([]);
    const [itemArr, setItemArr] = useState([]);
    const [reRender, setReRender] = useState(false);

    useEffect(() => {
        let _items = items.slice(0).reverse().map((item, idx) => {
            return {
                type: {
                    subject: item.type,
                    type: "text"
                },
                child: {
                    subject: <Child
                                data = {item}
                             ></Child>,
                    type: "inline"
                },
            }
        });

        setItemArr(_items);
    }, [reRender])

    function newItem(info) {

        let [date, time] = getDate();

        let tmp = items;
        tmp.push({
            id: items.length,
            type: info.type,
            date: date,
            time: time
        });
        
        setItems(tmp);
        setReRender(!reRender);
    }

    return (
            <MyTable
                 items = {itemArr}
            ></MyTable>
    )
}
```

and my `Child` component: 

```jsx

export default function ScanTimer(props) {

    console.log(props.data);

    useEffect(() => {
        console.log(props.data);
    }, []);

    return(
        <div></div>
    )
}

```

when I run my app, and add two item to the table, first `console.log` in child component (the one that is out of `useEffect`) shows right data. but last one (in `useEffect`) shows wrong data (the data that is for first item inserted into table).

it happens also when I init a state In this way:
```jsx
const [data, setData] = useState(props.data);
```
in the Child element.

I don't know why it happens. can somebody help me??

**Comment by rifatdinc** [comment] 2021-12-20 23:25
I had such a problem too. Promise.resolve()
Can you try using this method?
`
  useEffect(() => {
        Promise.resolve(props.data).then((data) => {
            console.log(data);
        });
    }, []);
`

**Comment by andyFang94** [comment] 2021-12-21 09:41
> 
try:
useEffect(() => { Promise.resolve(props.data).then((data) => { console.log(data); }); }, [props.data]);

**Comment by andyFang94** [comment] 2021-12-21 09:42
> I had such a problem too. Promise.resolve() Can you try using this method? `useEffect(() => { Promise.resolve(props.data).then((data) => { console.log(data); }); }, []);`

try:
useEffect(() => { Promise.resolve(props.data).then((data) => { console.log(data); }); }, [props.data]);

**Comment by bvaughn** [comment] 2021-12-21 16:36
It looks like this bug report only includes a partial code example. This means that **it's going to be very hard for us to fix**. Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem.

**Comment by bvaughn** [comment] 2021-12-21 16:37
I did notice that the effects dependency array is missing `items` so it will only re-run when `reRender` changes:
```js

    useEffect(() => {
        // You reference items here
        let _items = items.slice(0).reverse().map((item, idx) => {
            return {
                type: {
                    subject: item.type,
                    type: "text"
                },
                child: {
                    subject: <Child
                                data = {item}
                             ></Child>,
                    type: "inline"
                },
            }
        });

        setItemArr(_items);
    }, [reRender]) // But you don't include it in the dependencies here
```

**Comment by fueher** [comment] 2021-12-21 22:55
I'm assuming newItem function is getting called somewhere in the Table or child component? As stated above, there isn't enough info to know what the issue is but on my first glance, it looks like you are directly modifying the items. Instead, you should do something like this:
```javascript
// In newItem function, change
let tmp = items;
tmp.push({
   id: items.length,
   type: info.type,
   date: date,
   time: time
});
// to this
let tmp = [...items, {
   id: items.length,
   type: info.type,
   date: date,
   time: time
}]);

setItems(tmp);
```
This will allow components to rerender when the reference changed. You should also include items in the useEffect deps to not use the stale version.

**Comment by frfancha** [comment] 2022-02-01 21:43
@rdwnsjjd 
So question: do you you want to trigger your effect only when explicitly requested by "reRender", or just every time 'items' changes?
If that is only when 'reRender' triggers it, then you must use a ref to items in the useEffect, not items itself. Using items itself works, but your effect appears to be dependent of items which is not _if_ you really want to run on 'reRender' only.
Now if (as it is much more probable) you need to run your useEffect any time "items" is changed, then why not just using that as dependency of the useEffect and get rid of the "reRender" variable?
I would even say, do you really need a state for itemArr?
Can't it just be a const computed in the regular render procedure based on items, keeping only items as a state?

Now let's come to the "let tmp = items;"
Oh my... First you never change tmp (pushing to an array is not changing the array ref), so that should be a "const", not a "let".
And, when you write that you realize: what's the point of that 'const tmp =items;'?
Nothing! tmp _is_ just items, you could as well push to items itself.
But items is a state, so pushing in it will change it but without changing its ref, so react will not know it, sure sign for a future bug.
Recommended:
setItems(_items => [..._items, theNewItem])

**Comment by eps1lon** [comment] 2022-04-29 14:56
Closing since we haven't gotten any requested information since the issue was opened.

**Closed by eps1lon** 2022-04-29 14:56 UTC
Labels: Resolution: Needs More Information
