### ISSUE TITLE
[DevTools Bug]: Where's the error stack trace?

### ISSUE THREAD

**Issue by joego2124** [facebook/react#21711] opened 2021-06-21 01:28 UTC
### Website or app

There's no error stack trace when there's an error

### Repro steps

There's no error stack trace when there's an error

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment] 2021-06-22 22:29
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-06-22 22:29 UTC
Labels: Component: Developer Tools, Status: Unconfirmed, Type: Bug
