### ISSUE TITLE
Dropdown not working on official react docs website!

### ISSUE THREAD

**Issue by manish-rajpurohitt** [facebook/react#20404] opened 2020-12-08 06:19 UTC
Browser - Brave Browser (Version 1.19.46 Chromium: 87.0.4280.67 (Official Build) beta (64-bit))
OS - Ubuntu 20.01.1 LTS.
No Extensions installed in browser.
All dropdown's on right side like Advanced Concepts, Main Concepts in this website https://reactjs.org/docs/getting-started.html are not showing on click. Sample Screenshot. I have disabled all sheilds of browser. 
![image](https://user-images.githubusercontent.com/25878398/101447390-29b52580-394b-11eb-93fe-b0a4e7ed27d1.png)

**Comment by RafiqAli** [comment] 2020-12-08 07:16
+ 1
Browser : Safari Version 14.0 (15610.1.28.1.9, 15610)
OS : macOS Catalina 10.15.7

**Comment by tpettrov** [comment] 2020-12-08 08:22
Same

OS: Windows 10
Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by eps1lon** [comment] 2020-12-08 10:47
Can confirm the issue. It is caused by a JS asset that is redirected many times before it fails. Closing in favor of https://github.com/reactjs/reactjs.org/issues/3437 which isn't resolved yet.

**Closed by eps1lon** 2020-12-08 10:47 UTC
