### ISSUE TITLE
Error: "Could not find commit data for root "1" and commit null"

### ISSUE THREAD

**Issue by xu33** [facebook/react#16417] opened 2019-08-16 09:48 UTC
---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.2-2bcc6c6

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:16552)
    at pl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:293513)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)
    at kt (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25092)

Component stack: in pl
    in div
    in ml
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ua
    in le
    in ve
    in ko
    in Fl

**Comment by bvaughn** [comment] 2019-08-16 15:07
Some info on how to repro this would be helpful. A callstack by itself is hard to work with :)

**Comment by bvaughn** [comment] 2019-08-16 15:08
Duplicate of #16414

**Closed by bvaughn** 2019-08-16 15:08 UTC
