### ISSUE TITLE
Guide or document highlighting what needs to be implemented to create a react renderer?

### ISSUE THREAD

**Issue by cesarandreu** [facebook/react#4286] opened 2015-07-04 22:12 UTC
With the announcement of 0.14, it seems like one goal is to make it easier to create renderers for different environments.

I realize it's still beta, but I'd love if there were some guide or document that talks about what interfaces you need to implement. 

I've been reading through react-native and the client dom renderer to try and get an idea, but I'm having a hard time wrapping my head around everything. Navigating through react and react-native's source has proven to be challenging.

**Comment by jimfb** [comment] 2015-07-06 22:53
My intuition is that this is a bit out of scope.  Also, to be honest, we're still figuring out where everything should live, so all of this is subject to change.  It's all internal API, so don't rely on any of it.

I think the answer is that you need to implement whichever functions you want to provide.  The most obvious are `MyReactRenderer.render()` and `MyReactRenderer.unmount()`, but depending on your target environment and use cases, you may want more (or even fewer) things.  For instance, the server side renderer doesn't need to provide unmount (because you will never mount/unmount on the server), and the web renderer provides `findDOMNode` because that is sometimes helpful when working with the web but which is impossible/meaningless to implement with server-side rendering.

The React core provides `React.createElement`, `React.createClass` and `React.Component`, `React.PropTypes`, `React.Children`, and the other helpers related to elements and component classes.  Everything else is the domain of the Renderer.  We've put some shared renderer stuff in `src/renderers/shared/` because we think it's useful when implementing your renderer, but not all renderers can/should re-use that code.

Ultimately, I think you're supposed to think of the core as a shared library that is shared with your Renderer implementation.  Your Renderer is permitted to call into and re-use as much code as is practical, which largely depends on how similar your environment is to what already exists.  It would be much easier to target a xml-like output language than one built on top of opengl for instance (because the React renderers are currently optimized for (x)html markup), but it's just a matter of how much code you can re-use instead of re-implement.  A good way to get started would be to fork an existing renderer (ideally, fork whichever is closest to whatever you're trying to implement).

My intuition is that we close this issue, since it's not a bug in React, and is probably not something we want to add to the formal documentation, but it might make for a reasonably interesting blog post so it's worth keeping in mind.

**Comment by zpao** [comment] 2015-07-09 06:08
While we might not end up with a formal spec, we should probably figure out our messaging here before launch. I think @jimfb is mostly right but too much ambiguity here is probably not advantageous to us. cc @sebmarkbage

**Comment by gaearon** [comment] 2016-10-27 14:46
Closing as this is not yet officially supported. When it is, we'll document the API.

**Closed by gaearon** 2016-10-27 14:46 UTC
