### ISSUE TITLE
when install React 16.8.6 , Firefox and IE not show project but Chrome show it

### ISSUE THREAD

**Issue by riazi** [facebook/react#15655] opened 2019-05-15 04:52 UTC
i install react 16.8.6 and run project , chrom show it but firefox and IE not showing!!! , in react 16.8.5 i dont have this problem

firefox error in consol:SyntaxError: missing = in const declaration

IE error SCRIPT1002: Syntax error

**Comment by kunukn** [comment] 2019-05-16 10:45
Can you share a reproducibility code example? 
E.g a Codesandbox or Github -project?

Did you remember to also update react-dom to version 16.8.6?

**Comment by riazi** [comment] 2019-05-18 03:42
> Can you share a reproducibility code example?
> E.g a Codesandbox or Github -project?
> 
> Did you remember to also update react-dom to version 16.8.6?

i dont wirte new code , i use example code in react js , 
after install i start project and i have this issue

**Comment by aniltomar10** [comment] 2019-05-21 16:46
I am facing the same issue. Following below steps.
1. created new project using command npx create-react-app my-app
2. run project using command npm start

It opens application in IE 11 by default but page is blank. Copy same url (http://localhost:3000) in google chrome and it works.

**Comment by kunukn** [comment] 2019-05-21 19:45
I can confirm I get a syntax error in IE11 on Windows 10

Try to update to latest react-scripts in package.json

These works for me with IE11

upgrade (recommended)
`"react-scripts": "3.0.1"`

or downgrade 
`"react-scripts": "2.1.8"`

**Comment by aniltomar10** [comment] 2019-05-21 21:00
@kunukn  I have this version "3.0.1" in my package.json file. but it's not working. Below are the dependencies from my package.json file
"dependencies": {
    "bootstrap": "^4.3.1",
    "react": "^16.8.6",
    "react-bootstrap": "^1.0.0-beta.8",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  }

**Comment by kunukn** [comment] 2019-05-21 21:31
This probably should have been issued at create-react-app github

I also removed `development` section from `browserslist` in package.json

I changed the "react-scripts": "2.1.8"
applied `yarn install` and it worked.

I changed the "react-scripts": "3.0.1"
applied `yarn install` and it worked.

I was fiddling around and made it worked.

**Comment by riazi** [comment] 2019-05-22 05:22
my package.json file :
 "dependencies": {
    "@babel/polyfill": "^7.4.4",
    "bootstrap": "^4.3.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  },

**Comment by kunukn** [comment] 2019-05-22 07:14
I actually also did this to make it work in IE 11
https://facebook.github.io/create-react-app/docs/supported-browsers-features

**Comment by riazi** [comment] 2019-06-19 05:13
i try again and install again  not  show IE 11 and firfox 48 but in firfox 67 show it ,
react 16.8.5 show in IE and firefox48

**Comment by threepointone** [comment] 2019-09-03 13:32
Closing this issue, happy to discuss if you can provide a reproducing usecase either on codesandbox, or as a git repo I could try locally.

**Closed by threepointone** 2019-09-03 13:32 UTC
Labels: Resolution: Needs More Information
