### ISSUE TITLE
Some one is changing the state variable from the react devlopment tool in production build?

### ISSUE THREAD

**Issue by surajit25** [facebook/react#22758] opened 2021-11-15 04:37 UTC

**Comment by akgupta0777** [comment] 2021-11-15 06:59
Please give us more description of the issue and also provide a reproducible repo.
consider using [**codesandbox**](https://www.codesandbox.io) for code.

**Comment by bvaughn** [comment] 2021-11-15 15:50
Hi @surajit25 

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2022-03-09 18:30
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2022-03-09 18:30 UTC
Labels: Status: Unconfirmed, Resolution: Needs More Information, Component: Developer Tools
