### ISSUE TITLE
Invalid style doesn't update react tree

### ISSUE THREAD

**Issue by vkrbt** [facebook/react#15453] opened 2019-04-19 09:52 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Inline style value not updates if it's not valid. `none` is not valid value for `min-height`, but I think it should be updated on render.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/mmqnwwkx9p
Look at styles on component updates;
`min-height` not updates on render;
`min-height` and `max-height` should have opposite values;

**What is the expected behavior?**
Values should be updated on render;

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I tested in 16.8.4 and 16.8.6

**Comment by Sharl212** [comment] 2019-04-21 13:47
I think the intended behavior is not updating if the css value is invalid. but for some reason `maxHeight` bypasses that. i tried other css properties and none of them updated their values to `none` or any other invalid values. not sure if thats the case , we might wait until an expert help us here. but certainly an interesting bug.

**Comment by Sharl212** [comment] 2019-04-21 13:56
Aren't that an intended behavior ? as `max-height` can take `none` as a valid value but not `min-height`.
i think its validated for each style? not sure. hope an expert can clear that out.

**Comment by kunukn** [comment] 2019-04-23 19:16
Without looking at the I code, I suspect it is because Inline styles are set using JS DOM API. To set min-height to a non-valid value such as `none` has the effect of not being applied. 

E.g. 
`document.body.style.minHeight = 'none'` // --> the value is not set
`console.log(document.body.style.minHeight)` // --> ""

But if the invalid CSS rules are ignored by the browser, does it makes sense to include them?

**Comment by threepointone** [comment] 2019-09-04 11:31
Closing since it seems to be as expected. I would recommend using a type system/linters to catch such errors.

**Closed by threepointone** 2019-09-04 11:31 UTC
