### ISSUE TITLE
tspan created with wrong namespace

### ISSUE THREAD

**Issue by flying-sheep** [facebook/react#3420] opened 2015-03-16 12:34 UTC
[demo](http://jsbin.com/tisuma/11/edit?html,js,console,output)

howering the right point should create exactly the same as the left one, but the namespace of the second tspan of the second group ends up being xhtml, not svg.

(the console output on mouse enter should be `[true, true, true, true]` and on exit `[true, true, true]`, but the real output on enter is `[true, true, true, false]`, which means that the second tspan’s namespace URI isn’t `http://www.w3.org/2000/svg` as it should)

**Comment by zpao** [comment] 2015-09-23 07:06
dupe of #3972 which is fixed in 0.14

**Closed by zpao** 2015-09-23 07:06 UTC
Labels: SVG
