### ISSUE TITLE
Children.type.displayName is impossible on node.js

### ISSUE THREAD

**Issue by bORm** [facebook/react#6167] opened 2016-03-02 10:16 UTC
```
import React, { Component } from 'react';
import { render } from 'react-dom';

class Parent extends Component {
	render() {
		const {children} = this.props.children;
		console.log(typeof children.type); // 'function'
		console.log(typeof children.type.displayName); // undefined
		return(
			<div className={children.type.displayName}>
				{ children }
			</div>
		);
	}
}

class Child extends Component {
	render() {
		return(
			<div>
				I`am children
			</div>
		);
	}
}

render(<Parent><Child/></Parent>, ....);
```

**Comment by mxstbr** [comment] 2016-03-02 10:27
Reproducable in this ESNextBin after fixing `const children = this.props.children`: http://esnextb.in/?gist=419bc812ce787cebbbca

**Comment by bORm** [comment] 2016-03-02 10:35
and??? Where class 'children' in parent div?
Show console
```
function 4dafa3e7-83cb-4a07-ae77-f48dc54cc7d2:40660 
undefined 4dafa3e7-83cb-4a07-ae77-f48dc54cc7d2:40660
```

**Comment by bORm** [comment] 2016-03-02 10:40
@mxstbr how get displayName children component?

**Comment by mxstbr** [comment] 2016-03-02 10:43
I don't know, sorry. I just provided your code as a running bin so somebody with more knowledge than I have can give you an answer!

**Comment by bORm** [comment] 2016-03-02 10:56
Oh sorry, wait developer

**Comment by jimfb** [comment] 2016-03-02 13:45
You should not rely on the name of a component, we use it for debugging information/messages only.  It is unreliable at best, and may behave differently in production.

@bORm it sounds like you are using it to determine styling information.  We recommend inline styles, or explicitly passing the css class name.

If you have other use cases, I would be curious to hear about them.  I'm going to close this issue because I don't think we want to support people accessing the component names for purposes like this, but feel free to continue the discussion on this thread.

**Closed by jimfb** 2016-03-02 13:45 UTC

**Comment by bORm** [comment] 2016-03-02 14:34
Ok, thanks,
in my case i have a few components 
```
import React, { Component } from 'react';
import { render } from 'react-dom';

class Parent extends Component {
    render() {
        const {children} = this.props.children;
        console.log(typeof children.type); // 'function'
        console.log(typeof children.type.displayName); // undefined
        return(
            <div className={children.type.displayName}>
                { children }
            </div>
        );
    }
}

class Child1 extends Component {
    render() {
        return(<div>Child1</div>);
    }
}
class Child2 extends Component ....
class Child3 extends Component ....
.... and more
```

i use it
```
<Parent><Child1/></Parent>
<Parent><Child2/></Parent>
<Parent><Child3/></Parent>
```

and i want add dynamic className to Parent component

Do you have any solution?

**Comment by jimfb** [comment] 2016-03-02 14:40
@bORm You'll want to take a look at https://github.com/facebook/react-devtools/issues/308

**Comment by bORm** [comment] 2016-03-02 14:52
@jimfb 
i see only one solution
add displayName to defaultProps
```
// Children
	static defaultProps = {
		name: 'chevron'
	};
```
and use it in Parent
```
class Parent extends Component {
    render() {
        ...
children.props.name
...
```

**Comment by jimfb** [comment] 2016-03-02 15:30
@bORm This is turning into a usage question (since there is already an open issue for solving what you're asking, as per above); we use github to track bugs in the React core and redirect usage questions to other sites like StackOverflow.

The thread I linked mentions that you can set a static property on the child components, using a transform that supports static class properties, or by setting the property after creating the class:

```
class Child extends Parent { ... }
Child.dispalyName = 'MyChildName';
Child.myName = 'MyChildName';
```

Then you can read that property off the class.

Or, that thread also links a discussion about fixing this in general for React https://github.com/facebook/react/issues/5618#issuecomment-162643284 if you wanted to submit a PR to make React better.

Or you could "fix" the babel plugin to recursively chase down parents in order to determine if a specific component is a React Component and should therefore get a displayName assigned at transform time.

We prefer composition over inheritance, so supporting the inheritance pattern is not a priority for us, but we'd be happy to take PRs to fix or you can utilize the workarounds mentioned in the other thread or you can wait for someone to fix it.  At the moment, I think those are your options.

**Comment by bORm** [comment] 2016-03-02 15:36
thanks for the detailed answer
