### ISSUE TITLE
Fix gap between footer logo and links

### ISSUE THREAD

**Issue by amanr-dev** [facebook/react#28542] opened 2024-03-12 07:23 UTC
At the `react.dev/learn` & `react.dev/community` or any route add a gap between footer's `logo` and `links` 

# screenshot
![Screenshot 2024-03-12 124202](https://github.com/facebook/react/assets/124811276/ce6e8fff-5a51-44da-8b7f-25b96549290c)

**Comment by rhen99** [comment] 2024-03-12 09:46
Is that site on GitHub?

**Comment by sahiladit** [comment] 2024-03-12 15:56
issue : #28542
Can you assign this to me?

**Comment by Luguito** [comment] 2024-03-13 00:53
Hey @amanr-dev, I was checking and i saw everything alright. I checked on a few resolutions and all seems to be fine. Could you provide more information to replicate that UI error ?

**Comment by kodaliakhil** [comment] 2024-03-13 04:33
Hey @amanr-dev,  I checked both `react.dev/learn` & `react.dev/community`  on all resolutions and everything seems to be fine.

**Comment by Harshit1723** [comment] 2024-03-19 14:42
I'm proficient with this,Can you assign it to me

**Comment by pwbriggs** [comment] 2024-03-20 01:21
@Harshit1723 the resolution was that this issue isn't reproducible on other devices. Can you reproduce this issue on your device? If so, please open a new issue with instructions for how to repro.

Thanks!

**Comment by RitaDee** [comment] 2024-03-20 09:05
Could you assign this issue to me? I can reproduce it on my device:

<img width="1425" alt="Screenshot 2024-03-20 at 09 49 17" src="https://github.com/facebook/react/assets/106407013/8ce1b164-5ac7-4717-ae38-4bc891b471fd">

I am using a Macbook.

Steps to reproduce:

- Open the website [link](https://react.dev/learn)
- Scroll to the footer and you will see there is no space between the loge and the (link)[https://opensource.fb.com/]

**Suggestion:**

The space between the logo and the link should look like this:

<img width="434" alt="image" src="https://github.com/facebook/react/assets/106407013/52117d49-b7ad-487e-a657-d30bf11dcb56">

Instead of this:

<img width="211" alt="image" src="https://github.com/facebook/react/assets/106407013/889efa33-ebf3-4c4f-aec1-07c7361d5456">

**Comment by RitaDee** [comment] 2024-03-20 11:53
Thank you, @amanr-dev for assigning this issue to me.

**Comment by pwbriggs** [comment] 2024-03-20 13:26
@RitaDee I think you misunderstood the issue. The Meta Open Source logo is supposed to look like that (as seen on https://opensource.fb.com). I think the issue @amanr-dev was referring to was this one:

![s](https://github.com/facebook/react/assets/146312751/d2a862d4-ee1b-4036-aff5-9d2e158c1e0d)

Thanks anyway though! ❤️

**Comment by sahiladit** [comment] 2024-03-20 15:40
It seems fine ,which system are you using?i'm not getting this issue?

**Comment by amanr-dev** [comment] 2024-03-20 15:42
> one

Yes , you are right

**Comment by amanr-dev** [comment] 2024-03-20 15:44
> It seems fine ,which system are you using?i'm not getting this issue?

My device's screen size is `1519 × 742`

**Comment by sahiladit** [comment] 2024-03-20 15:44
I think you should close this issue.

**Comment by amanr-dev** [comment] 2024-03-21 15:42
> Thank you, @amanr-dev for assigning this issue to me.

Hi @RitaDee, I think I should close this issue a second time. The reason is that the code for the website is not available in the Repository.

**Closed** 2024-03-21 15:43 UTC
