### ISSUE TITLE
Error: "can't access property "concat", parentNode.children is undefined"

### ISSUE THREAD

**Issue by wegry** [facebook/react#21399] opened 2021-04-30 18:06 UTC
Describe what you were doing when the bug occurred:
1. Profiling a react@17.0.2 app in development mode

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.13.0-2a7bb41548

Component stack: CommitFlamegraphAutoSizer@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:35634:34
div
div
div
SettingsModalContextController@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:29015:40
Profiler_Profiler@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:37064:34
ErrorBoundary_ErrorBoundary@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:30336:5
PortaledContent@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:30415:34
div
div
ProfilerContextController@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:34461:35
TreeContextController@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:25251:31
SettingsContextController@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:25854:35
ModalDialogContextController@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:30557:38
DevTools_DevTools@moz-extension://122e8673-c113-6c45-8af1-d4483976b1ea/build/main.js:37571:27

**Comment by bvaughn** [comment] 2021-04-30 19:19
@wegry Really sorry you ran into this bug!

It doesn't look like this bug report has enough info for one of us to reproduce it though.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-05-03 13:53
Closing because there isn't enough info.

**Closed by bvaughn** 2021-05-03 13:53 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
