### ISSUE TITLE
Number input not firing onChange

### ISSUE THREAD

**Issue by SergeyShablenko** [facebook/react#10370] opened 2017-08-03 17:03 UTC
I don\`t know if it is bug or feature, but since you put into input with type number two minuses it will stop calling `onChange` callback, but value inside input will change

**React 15.4.2**
**Browser Version 60.0.3112.90 (Official Build) (64-bit)**

**Comment by jquense** [comment] 2017-08-03 17:14
Can you provide a reproduction in a jsfiddle or other similar tool?

cc @nhunzaker

**Comment by SergeyShablenko** [comment] 2017-08-03 17:31
Tried on jsfiddle, but it works there, strange

**Comment by SergeyShablenko** [comment] 2017-08-03 17:37
```jsx
<input type="number" 
       className="form-control"
       value={typeof this.state.value !== 'undefined' && this.state.value !== null ? this.state.value : ''}
       onChange={e => this.onChange(e.target.value)} />
```

```js
onChange(value) {
    const VALUE = parseFloat(value);

    this.setState({ value: VALUE >= 0 && !isNaN(VALUE) ? value : '' });
}
```

**Comment by Fasani** [comment] 2017-08-04 12:42
It is odd that it would work with JSFiddle but not for you locally.

type=number may only work with the HTML 5 doctype. Did you specify HTML 5? (This is the only thing I can think without seeing more code.)

**Comment by shablenko** [comment] 2017-08-04 13:04
Yes, i specified HTML 5

**Comment by Antwan86** [comment] 2017-08-08 17:22
It does the same with `<input type=radio>` elements.

On [this codepen](https://codepen.io/anon/pen/ayJMvL), if you click on "**one**", then "**two**", then "**one**", then "**two**", only the first two `onChange` events are fired. Expected behaviour is to have the value changing everytime.

I tested with several HTML elements, but some of them are working (checkboxes for example).

Reproducible since 15.6.0, working with previous versions.
This is kind of a big deal as it's breaking our app, and surely many others.

**Comment by jquense** [comment] 2017-08-08 17:48
@Antwan86 yup we are already aware of that issue, it's unrelated to this one though

**Comment by Antwan86** [comment] 2017-08-08 18:29
My bad just saw the appropriate ticket. Keep up the good work!

**Comment by aweary** [comment] 2017-08-08 18:37
This is mostly a duplicate of https://github.com/facebook/react/issues/6556. [Here's an example that can reproduce the issue](https://jsfiddle.net/0dmqta7z/). If you type `--` and then start typing numbers the value _appears_ to change but React isn't firing change events because the value is invalid. This same thing happens with other accepted non-numerical characters like `e`

**Comment by mpelham** [comment] 2017-08-09 02:42
@Antwan86 your codepen was a great example of the issue. I made a minor fork of it and pinned it to 15.5.4 to highlight the issue in the hopes that others looking for the root case of the issue find this thread.

15.5.4:
https://codepen.io/anon/pen/RZVwYz

15.6.1
https://codepen.io/anon/pen/ayJMvL

**Comment by oliviertassinari** [comment] 2017-09-12 10:55
The issue can be reproduced with
- @latest: https://jsfiddle.net/m9oduftm/
- @next: https://jsfiddle.net/ugr5sp1q/

**Comment by aweary** [comment] 2017-09-15 21:59
Since the root cause is the same, I'm going to close this as a duplicate of https://github.com/facebook/react/issues/10370.

**Closed by aweary** 2017-09-15 21:59 UTC

**Comment by leMaik** [comment] 2017-11-08 11:44
@aweary So this issue is a duplicate of… itself? :sweat_smile:

**Comment by oliviertassinari** [comment] 2017-11-08 11:57
@aweary The issue can be reproduced in the v0.16.0 version: https://jsfiddle.net/d4a52zdk/. The issue can't be a duplicate of itself. You might want to reopen it.
