### ISSUE TITLE
Cannot read property 'target' of undefined - getEventTarget

### ISSUE THREAD

**Issue by tonoslav** [facebook/react#21788] opened 2021-07-02 08:09 UTC
Hello guys, 

I got this problem in my errors log 
**Cannot read property 'target' of undefined** which means that **nativeEvent** is **undefined**
by this function: 
https://github.com/facebook/react/blob/ed6c091fe961a3b95e956ebcefe8f152177b1fb7/packages/react-dom/src/events/getEventTarget.js#L14-L22

Cannot backtrace is enough to detect how is it even possible , but somehow it is.
Might be problem with unmounted component maybe.
Shouldn't it be check if **nativeEvent** is **defined**?

Cannot replicate the problem, happend once in about milion use, so it must be some edge case.

**OS** Windows 10
**Chrome** 91.0.4472
**React** 17.0.2

**Comment by mridul037** [comment] 2021-07-02 09:47
console.log(nativeEvent)

**Comment by bvaughn** [comment] 2021-07-03 23:45
> Cannot replicate the problem, happend once in about milion use, so it must be some edge case.

Without a repro (or even any application source code) there is nothing the core team can do to help investigate this.

**Comment by bvaughn** [comment] 2021-07-06 17:05
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-07-06 17:05 UTC
Labels: Resolution: Needs More Information
