### ISSUE TITLE
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

### ISSUE THREAD

**Issue by benwiley4000** [facebook/react#5538] opened 2015-11-24 01:42 UTC
`Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's 'render' method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

This has been talked about; the answer: 'don't run two copies of React!'. I got it. Here's the thing: I'm not running two copies of React. I'm building a React component npm module that is installed in a larger project. Within my module, I'm including React as a peer dependency and it's marked as an external in my webpack.config.js. This has actually been working fine all the time, with one exception: when my components have refs.

I've gone so far as to use a document.querySelector() (yikes!) to get rid of that error message. There has to be a better way. I'm opening an issue now, though, because I want to use the react-widgets package and it uses refs. This is breaking my project.

Can't React be smart enough to associate these refs with the running copy of React? Am I missing something?

Thanks

-Ben

**Comment by benwiley4000** [comment] 2015-11-24 22:29
Update: This issue has gone away for me. I'm not 100% sure what solved the problem, but I think it may be thanks to upgrading npm to v3.x and node to v4.x -- and/or not using npm link.

**Comment by jimfb** [comment] 2015-11-24 22:59
Ok, let's close this out.

@benwiley4000: If you do ever find out what went wrong, and can provide steps to reproduce, we can re-investigate.

**Closed by jimfb** 2015-11-24 22:59 UTC

**Comment by benwiley4000** [comment] 2015-11-24 23:15
I'm fairly certain it's a problem only with `npm link`, though I'm having trouble producing it on one of the two modules that were experiencing this error before, so there may have been compounding factors related to outdated node/npm versions. For now, consider that my module (`react-component-x`) relies on a peerDependency, `react-widgets`. My project, `react-project-x` requires `react-component-x`. When `react-component-x` is installed via `npm link`, the error above is displayed (I just tested this a moment ago). When I run `npm unlink react-component-x` inside of `react-project-x` and the install `react-component-x` from its remote git repository, the error goes away.

**Comment by benwiley4000** [comment] 2015-11-25 05:49
Can confirm: Definitely an `npm link` issue (git installation worked fine with the same older versions of npm/node).

**Comment by frekw** [comment] 2016-02-29 21:18
I'm also seeing this in exactly the same situation.

We have an internal ui library (written in React) that uses refs. Since I want to develop it as the same time as the main application, I've `npm link`'ed it.

Whenever I try to test a component via `mocha` (running the Webpack build is fine, probably due to some de-duping going on) I get the following error:

`ui-library/foo.js`
```javascript
import React from 'react'

export const Foo = React.createClass({
  render() {
    return <div ref="div">Foo</div>
  }
})
```
`main-project/test/test-that-uses-foo.js`
```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import TestUtils from 'react-addons-test-utils'
import {Foo} from 'ui-library/foo'

it('shouldn\'t blow up', () => {
    const foo = TestUtils.renderIntoDocument(<Foo />)
    ReactDOM.findDOMNode(foo).textContent.should.equal('Foo')
  })
```

`mocha` now crashes with the following output:

```console
Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
      at invariant (node_modules/fbjs/lib/invariant.js:39:15)
      at Object.ReactOwner.addComponentAsRefTo (node_modules/react/lib/ReactOwner.js:67:79)
      at attachRef (node_modules/react/lib/ReactRef.js:23:16)
      at Object.ReactRef.attachRefs (node_modules/react/lib/ReactRef.js:42:5)
      at ReactDOMComponent.attachRefs (node_modules/react/lib/ReactReconciler.js:21:12)
      at CallbackQueue.assign.notifyAll (node_modules/react/lib/CallbackQueue.js:65:22)
      at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (node_modules/react/lib/ReactReconcileTransaction.js:81:26)
      at ReactReconcileTransaction.Mixin.closeAll (node_modules/react/lib/Transaction.js:202:25)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:149:16)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:282:15)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
      at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:476:18)
      at Object.wrapper [as _renderNewRootComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:550:32)
      at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:570:23)
      at Object.wrapper [as render] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:76:21)
      at Context.<anonymous> (test-that-uses-foo.js:NN:NN)
```

**Comment by frekw** [comment] 2016-02-29 21:24
Also, this still happens on the latest node and npm versions.

```terminal
$ node -v
v5.7.0
$ npm -v
3.7.5
```

**Comment by frekw** [comment] 2016-02-29 22:55
If anyone gets stuck here again, this workaround works fine: https://www.sharpoblunto.com/News/2016/01/25/testing-react-component-libraries-using-npm-link

**Comment by ChenLi0830** [comment] 2016-04-23 23:58
Updating Node and NPM solved the problem for me. Thanks @benwiley4000!

**Comment by Jaikant** [comment] 2016-07-08 08:52
adding  "import React from 'react'" solved it for me. Weird.

**Comment by AlastairTaft** [comment] 2016-08-23 02:50
If you're using symlinked modules for development, this is solved in node v6.

**Comment by thespacecadette** [comment] 2016-09-12 13:01
For Jest users, if you declare React inside the 'describe' function, it should work.

**Comment by wan54** [comment] 2018-02-19 23:32
Using npm 5.6.0, node 9.5.0, webpack 3 the issue happens to us

Fixed it by creating an alias for `react` in webpack dev config:

`react: path.resolve(__dirname, 'node_modules/react')`
