### ISSUE TITLE
Bug: Keydown event is taking 500ms and the same function via onClick take 50ms

### ISSUE THREAD

**Issue by sobingt** [facebook/react#19989] opened 2020-10-09 10:46 UTC
I am trying to create a keyboard shortcut for my react-redux application. The keydown function takes 500 ms and if I do the same via the onClick function it takes 50ms. I have tried the same by creating a production version but no good results.

A hack I tested was to call an onClick event inside the keydown function which take lesser time than the original function. I also tried using Chrome Memory Profiler to see that's wrong. But no luck.

Can anyone suggest any solution to debug this problem?

React version: 16.13

**Comment by aweary** [comment] 2020-10-09 16:45
@sobingt please provide a code sample (preferably with [CodeSandbox](http://codesandbox.io/) that reproduces the issue. Otherwise it's impossible for us to help.

> I am trying to create a keyboard shortcut for my react-redux application. 

Can you reproduce the same issue with using `react-redux` or other third-party libraries as well?

**Comment by Ashish-Kushwaha** [comment] 2020-10-14 07:47
> I am trying to create a keyboard shortcut for my react-redux application. The keydown function takes 500 ms and if I do the same via the onClick function it takes 50ms. I have tried the same by creating a production version but no good results.
> 
> A hack I tested was to call an onClick event inside the keydown function which take lesser time than the original function. I also tried using Chrome Memory Profiler to see that's wrong. But no luck.
> 
> Can anyone suggest any solution to debug this problem?
> 
> React version: 16.13

 can you  provide code, please.........

**Comment by Ashish-Kushwaha** [comment] 2020-10-14 07:48
**can you  provide your code please**

**Comment by sobingt** [comment] 2020-10-14 09:07
@aweary @Ashish-Kushwaha I am trying to reproduce the issue on CodeSandbox with minimal bells and whistles. It's a huge project. Give me some time.

**Comment by bvaughn** [comment] 2020-10-28 13:36
Any update on the repro?

**Comment by bvaughn** [comment] 2020-11-07 14:38
Closing this issue due to lack of repro info or issue updates. We can re-open if updates come in.

**Closed by bvaughn** 2020-11-07 14:38 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
