### ISSUE TITLE
Stateless Component: React.forwardRef make defaultProps invalid

### ISSUE THREAD

**Issue by gitHber** [facebook/react#16653] opened 2019-09-04 07:39 UTC
When I add React.forwardRef to a stateless component that is already have defaultProps,  It make all defaultProps to undefined? 
React.forwardRef can't use with defaultProps ?

react-version: 16.8.6

**Comment by threepointone** [comment] 2019-09-04 10:49
Could you please use codesandbox.io to make a reproducing example? Or a git repo I can try locally (but preferred codesandbox). Thanks!

**Comment by bvaughn** [comment] 2019-10-03 17:54
Closing because this issue has insufficient info.

**Closed** 2019-10-03 17:54 UTC
Labels: Resolution: Needs More Information

**Comment by PaulRBerg** [comment] 2019-11-21 14:40
This should be reopened. Here's a [CodeSandbox](https://codesandbox.io/s/friendly-field-95pqc) that reproduces the problem.

It seems that eslint-plugin-react throws this error:

> Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?

But it's confusing, since removing the `propTypes` (in my IDE not on CodeSandbox), gets me the "is missing in props validation" warning.

**Comment by bvaughn** [comment] 2019-11-22 16:38
Ah, I see why there's confusion here. The function passed to `forwardRef` is _not_ a React component. (React components don't accept a second `ref` param for example.) It's just a function that "renders" (returns) React elements. So it does not support `defaultProps`. We have [tests](https://github.com/facebook/react/blob/0bd0c5269f2fe90ff7897ed5ce9146db99126eaf/packages/react/src/__tests__/forwardRef-test.js#L150-L171) that confirm this as expected behavior.

React also logs the following error in the console (as can be seen in your Code Sandbox repro):
> Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?

**Comment by ronen** [comment] 2019-12-11 07:59
I just hit on this too.   In case anyone else comes across this thread and needs some extra hand-holding (I was still a bit befuddled and took me a bit to understand):   

> The function passed to `forwardRef` is not a React component.

...but the function *returned* by `forwardRef` *is* effectively a React component.   So that's where the `propTypes` and `defaultProps` would go.  It also needs a `displayName`.  I.e.:

```
const MyComponent = React.forwardRef((props, ref) => { 
   ...
})

MyComponent.displayName = 'MyComponent'

MyComponent.propTypes = {
   name: PropTypes.string,
}

MyComponent.defaultProps = {
  name: 'default Name'
```
