### ISSUE TITLE
Edge: File input inside a label keeps reopening the file explorer window

### ISSUE THREAD

**Issue by bsonntag** [facebook/react#7683] opened 2016-09-08 17:44 UTC
**Do you want to request a *feature* or report a *bug*?**

I want to report a bug.

**What is the current behavior?**

When using a `<input type="file">` inside a `<label>` on MS Edge, the file explorer window keeps reopening.
When this happens, the only way to close Edge is by killing the process.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Place a `<input type="file">` inside a `<label>`, like this:
https://jsfiddle.net/pjccb2rq/

**What is the expected behavior?**

When the file explorer window is closed, either by selecting a file or by cancelling, the file explorer window should be closed and remain closed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React version: 15.3.1
Browser: MS Edge
OS: Windows 10

I didn't test previous React versions.

**Comment by Aweary** [comment] 2016-09-08 20:06
Thanks @bsonntag, I was able to reproduce this on master as well.

**Comment by zpao** [comment] 2016-09-08 23:52
That's… strange. We shouldn't be doing anything when you close the dialog there o_O. Can try to repro outside of React? (ideally the same basic set of operations you'd see in React, document.createElement, etc)

**Comment by Aweary** [comment] 2016-09-08 23:59
@zpao I did try reproducing this without React and I wasn't able to at all. When I tried setting some breakpoints in Edge to look into this it kept crashing. Maybe it's just my VM, but it's definitely strange.

**Comment by Aweary** [comment] 2016-09-09 03:42
@zpao I realized my test case was incorrect, I am able to reproduce this outside of React.

```js
var root = document.getElementById('root')
var label = document.createElement('label')
var input = document.createElement('input')
input.type = 'file'
label.appendChild(input)
root.appendChild(lable)
```

So this does seem to be an issue with Edge, not React.

**Comment by bsonntag** [comment] 2016-09-09 08:13
I did try [this example](http://codepen.io/bsonntag/pen/YGyzZE?editors=1010#), that just uses HTML, on the same machine and this one works.
From your example it does seem to be an issue with Edge's `document.createElement`.

**Comment by bsonntag** [comment] 2016-09-09 08:39
I found this on Edge's issues: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8282613/

**Comment by Aweary** [comment] 2016-09-09 14:49
Thanks for finding that @bsonntag. Since this is not a React issue and it's already been reported I'm going to go ahead and close this out 👍

**Closed by Aweary** 2016-09-09 14:49 UTC

**Comment by zpao** [comment] 2016-09-09 16:57
Thanks for hunting down & confirming that it's an Edge bug!

**Comment by Darcy-FzR** [comment] 2017-01-23 06:42
@zpao @bsonntag  Although bsonntag find that on Edge's issues, just like his previous comment, if you only  uses HTML (label tag with input tag), it works fine. So what should we explain this?

**Comment by Darcy-FzR** [comment] 2017-01-23 06:46
I met this scene when i use react , it won't appear when you just use pure html.

**Comment by bsonntag** [comment] 2017-01-23 10:36
@Darcy-FzR this is a bug in Edge's `document.createElement`, as you can see in aweary's example.

A workaround for this is to make the `label` and the `input` siblings and use the `label`'s [`for` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for), like this:

```jsx
function LabeledInput() {
  return <div>
    <label for='input-id'>Label</label>
    <input id='input-id' type='file' />
  </div>
}
```

**Comment by kaibakker** [comment] 2017-02-07 15:42
for should be htmlFor

https://facebook.github.io/react/docs/dom-elements.html

**Comment by bsonntag** [comment] 2017-02-07 17:42
@kaibakker you're absolutely right. I fixed my snippet to help with copy-pasting.
