### ISSUE TITLE
Bug: why v17.0.2 react version is 17.0.0

### ISSUE THREAD

**Issue by 2239559319** [facebook/react#24415] opened 2022-04-21 09:07 UTC
[version](https://github.com/facebook/react/blob/v17.0.2/packages/react/package.json#L7)
React version:

why react version in tag v17.0.2 is 17.0.0, Which commit is the source code of version 17.0.2 react

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by eps1lon** [comment] 2022-04-24 09:42
Duplicate of  https://github.com/facebook/react/issues/24079

**Closed by eps1lon** 2022-04-24 09:42 UTC
Labels: Status: Unconfirmed
