### ISSUE TITLE
Error: "Cannot read property 'isCollapsed' of undefined"

### ISSUE THREAD

**Issue by AndriiTsapenkoCasafari** [facebook/react#16422] opened 2019-08-16 15:03 UTC
---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.2-2bcc6c6

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:29005)
    at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:29131)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:218806
    at n.t.render (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:153564)
    at Ei (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:66077)
    at Ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:65872)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99617)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363

Component stack: in n
    in div
    in n
    in div
    in div
    in Vr
    in div
    in div
    in io
    in ar
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ua
    in le
    in ve
    in ko
    in Fl

**Comment by bvaughn** [comment] 2019-08-16 15:06
Some description of how to repro this would be helpful 😄

**Comment by gaearon** [comment] 2019-08-16 15:16
@bvaughn Maybe we should add it to the DevTools bug template? I think we'll keep getting these reports without descriptions if the template doesn't ask to fill it in.

**Comment by bvaughn** [comment] 2019-08-16 15:43
The template does start off with a bit that says "_please provide repro information here_" :)

**Comment by gaearon** [comment] 2019-08-16 20:39
Maybe caps lock

**Comment by threepointone** [comment] 2019-09-06 09:06
Going to close this issue because it doesn’t contain any reproducing steps or description, happy to reopen if there’s more information.

**Closed by threepointone** 2019-09-06 09:06 UTC
Labels: Component: Developer Tools, Type: Bug
