### ISSUE TITLE
Error: "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by loverdeveloper** [facebook/react#16950] opened 2019-09-29 08:46 UTC
Describe what you were doing when the bug occurred:
1. Profiling my react web page
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.1.2-5184346da

Call stack: at Map.has (<anonymous>)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150140)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)

Component stack: in dl
    in div
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by bvaughn** [comment] 2019-09-29 16:30
Seems likely a duplicate of #16491 and #16501. Going to close this one since #16501 has more info.

**Closed by bvaughn** 2019-09-29 16:30 UTC
