### ISSUE TITLE
Bug: React Developer Tools conflicts with Firefox sass sourcemaps on webpack

### ISSUE THREAD

**Issue by alvaro-escalante** [facebook/react#18188] opened 2020-02-29 03:19 UTC
The React Developer Tools add-on conflicts with Firefox source maps displaying just `inline` for all sass partials, works on Google Chrome. When the add-on is disabled it all works fine again.

React version: 16.13.0
Firefox version: 74

## Steps To Reproduce

1.  Use `style-loader`, `css-loader` and `sass-loader` with the add-on enabled on Firefox
2. Open Firefox Inspector, the source maps file name displays `inline`
```
module: {
    rules: [
      {
        test: /\.scss$/,
        include,
        use: ['style-loader', 'css-loader?sourceMap', 'sass-loader?sourceMap']
      }
    ]
  }
```

## The current behavior
It displays `inline:` for file name on Firefox inspector

## The expected behavior
To display proper partials e.g.` _page.sass:`

**Comment by jquense** [comment] 2020-02-29 05:02
This seems like a sass loader or webpack. Issue not a React one?

**Comment by threepointone** [comment] 2020-02-29 11:20
It’s not clear from this issue what this has to do with React. By “add-on” do you mean React dev tools? How would the devtools affect your situation? Please describe an exact set of steps, with screenshots, to reproduce this locally.

**Comment by alvaro-escalante** [comment] 2020-02-29 15:54
I meant the React Developer Tools add-on for Firefox its home page direct you here.

**Comment by bvaughn** [comment] 2020-02-29 20:04
I still have no idea how React DevTools could be interfering with your browser's source maps. It's just an extension that injects some JavaScript into the active tab for React to interact with. Has nothing to do with actual loading or parsing of resources.

If anything, this seems like a browser bug.

**Comment by alvaro-escalante** [comment] 2020-02-29 22:47
I know it sounds strange, but it does happen, as bizarre as it may be. Toggle the React Developer Tools off and all is good.

**Comment by bvaughn** [comment] 2020-03-01 00:27
Sounds like a browser bug. The two should have **nothing** to do with each other.

**Comment by alvaro-escalante** [comment] 2020-03-01 01:28
> Sounds like a browser bug. The two should have **nothing** to do with each other.
You are right they should not, but they do

**Comment by threepointone** [comment] 2020-03-01 08:58
We haven’t heard of this issue from anyone else. There isn’t much we can do from our side, I’d recommend filing an issue at https://bugzilla.mozilla.org/home against Firefox. I’ll leave this open for a while to see if anyone else has any idea.

**Comment by bvaughn** [comment] 2020-03-02 17:21
I think we should just close this bug, Sunil. I think @alvaro-escalante (or anyone) should report this to Mozilla. For the time being, I am not aware of anything we are doing (or could do) that should affect how the browser loads or parses source maps.

**Comment by alvaro-escalante** [comment] 2020-03-03 00:03
@bvaughn Have you tried to reproduce the problem? 

I just don't understand why it should be Firefox's problem when disabling the add-on fixes the issue.

I know it's a very niche problem that involves Firefox, webpack, sass source-maps and React Developer tools, and so I am quite sure that not many people have figure out that disabling the add-on fixes the problem. But it is a bug nonetheless.

Most people, most likely, have turned to Google Chrome cause there's no problem there, If this is the stance... you might as well not do a version for Firefox.

**Comment by hristo-kanchev** [comment] 2020-03-03 13:32
Hello there @alvaro-escalante.

I had some time today to check your issue.

I can't reproduce the problem with Firefox 73.

Screen bellow:
<img width="1679" alt="Screenshot 2020-03-03 at 14 21 59" src="https://user-images.githubusercontent.com/23095052/75779858-b72f6d80-5d5a-11ea-9367-b19306ea1cf8.png">

For me the latest version of Firefox is 73. 

I can see that FF 74 is currently in beta judging by [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/74): 👇 

<img width="577" alt="Screenshot 2020-03-03 at 14 26 43" src="https://user-images.githubusercontent.com/23095052/75780142-2311d600-5d5b-11ea-84b9-28585f25a52d.png">

As @bvaughn and @threepointone were saying we haven't heard of a similar issue. 

I suggest we close this issue as it seems that it's on Mozilla's side. It might be still be worth while to file an issue on https://bugzilla.mozilla.org/home

**Comment by threepointone** [comment] 2020-03-03 13:34
Closing. Happy to reopen if 1. There’s a reproducing case 2. There’s a logged issue with Firefox’ tracker and any suggested action that could isolate this as a react issue.

**Closed by threepointone** 2020-03-03 13:34 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed

**Comment by alvaro-escalante** [comment] 2020-03-03 16:57
> Hello there @alvaro-escalante.
> 
> I had some time today to check your issue.
> 
> I can't reproduce the problem with Firefox 73.
> 
> Screen bellow:
> <img alt="Screenshot 2020-03-03 at 14 21 59" width="1679" src="https://user-images.githubusercontent.com/23095052/75779858-b72f6d80-5d5a-11ea-9367-b19306ea1cf8.png">
> 
> For me the latest stable version of Firefox is 73.
> I can see that Firefox 74 is currently in **beta** judging by [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/74): 👇
> 
> <img alt="Screenshot 2020-03-03 at 14 26 43" width="577" src="https://user-images.githubusercontent.com/23095052/75780142-2311d600-5d5b-11ea-84b9-28585f25a52d.png">
> 
> As @bvaughn and @threepointone were saying - we haven't heard of a similar issue before.
> 
> I suggest we close this issue as it seems that it's on Mozilla's side.
> It might be still be worth while to file an issue on https://bugzilla.mozilla.org/home

The reason why it did not replicate is because you used my latest boilerplate repo which has a workaround on `webpack.modules.js` that uses `MiniCssExtractPlugin` if you comment out that and use the commented loader above which is the one that uses the faster `style-loader` the problem will indeed occur.

**Comment by bvaughn** [comment] 2020-03-03 17:20
> I just don't understand why it should be Firefox's problem, when disabling the add-on it fixes the issue.

> Most people that care about source-maps and use Firefox, most likely, have turned to Google Chrome cause there's no problem there, If this is the stance... you might as well not do a version for Firefox.

Browsers can have bugs that websites (or extensions) trigger. The websites/extensions can work around the bugs in some cases. (If you know of a workaround for this one, other than disabling the extension, let's talk!) But the bugs themselves **should be fixed on the browser side**. Right?

An extension like React DevTools **should not be able to break sourcemap parsing for the browser**. It should not be possible, **even if the extension wanted to**. The fact that that's happening, to me, indicates that there's something on the Firefox side that should be fixed.

**Comment by hristo-kanchev** [comment] 2020-03-03 17:29
Hi @alvaro-escalante

Even when I enabled the config that was commented out (the one you mentioned), I still wasn't able to replicate this.
![Mar-03-2020 18-27-49](https://user-images.githubusercontent.com/23095052/75802278-c4f5ea80-5d7c-11ea-81a3-f82cea1c1213.gif)

**Comment by alvaro-escalante** [comment] 2020-03-03 17:33
@hristo-kanchev and you commented out the previous one, the `exports.Styles` above? It so I just give up, I tried this with all versions of Firefox and no add-ons but the RDT.

**Comment by bvaughn** [comment] 2020-03-03 18:06
> I tried this with all versions of Firefox and no add-ons but the RDT.

Out of curiosity, I wonder if you would be willing to try with a different add-on (e.g. Redux DevTools, Vue or Preact DevTools) just to provide an additional data point.

**Comment by alvaro-escalante** [comment] 2020-03-03 18:18
Redux DevTools:  ✅
Preact Developers Tools: ✅
Vue.js devtools: ✅
React Dev tools: ❌
