### ISSUE TITLE
Bug: How to deal with HTML popover in react

### ISSUE THREAD

**Issue by codeAbinash** [facebook/react#27486] opened 2023-10-09 06:23 UTC
# How to deal with HTML popover in react
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

React version: 18.2.0

## Steps To Reproduce

1. Trying to use HTML popover
 
![Screenshot 2023-10-09 115001](https://github.com/facebook/react/assets/83173549/05bd50bb-8ed2-4a38-9e71-30822229507b)

## The current behavior
`Type '{ children: string; popovertarget: string; }' is not assignable to type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.
  Property 'popovertarget' does not exist on type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.`

`Type '{ children: string; popover: true; id: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'popover' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.`

## Please add support for HTML popover in react.

**Comment by kaungmyatlwin** [comment] 2023-10-09 07:10
Popover API support is being handled in this PR #27480.

**Comment by acusti** [comment] 2023-12-08 06:26
@codeAbinash if you specify `popover="auto"` (the default value), react will render the HTML correctly and the popover will work. the errors you pasted into your issue is actually not an issue with the react library but with typescript’s react libdef, which is being discussed here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66550

lastly, i’d consider this a duplicate of #27479 and close this one in favor of the other.

**Comment by codeAbinash** [comment] 2023-12-08 06:35
Thanks @acusti

**Comment by eps1lon** [comment] 2024-01-17 16:54
Closing in favor of https://github.com/facebook/react/issues/27479

**Closed by eps1lon** 2024-01-17 16:54 UTC
Labels: Status: Unconfirmed
