### ISSUE TITLE
Provide stack traces with warnings

### ISSUE THREAD

**Issue by rogierschouten** [facebook/react#2827] opened 2015-01-08 13:41 UTC
I find that I'm often having a hard time tracking the source of various React warnings. Would it be an idea to have a setting to throw the warnings so we can at least have a stack trace?

**Comment by gaearon** [comment] 2015-01-08 13:58
I think this should be covered by #2769

**Comment by rogierschouten** [comment] 2015-01-08 14:39
Yeah that's nice already but I'd like specifically to NOT catch the error. That way, the stack shows in the console and I don't have to do anything to get the information.

**Comment by gaearon** [comment] 2015-01-08 14:46
Well, not catching it would blow up the rendering so it's not best way.
However I think `console.trace` might be useful there for browsers that support it?

**Comment by malandrew** [comment] 2015-01-20 18:21
Another option is to use `Error()` or subclass `Error` as `DeprecationError()` and instantiate the error as soon as something is detected as being used incorrectly and console.error it. ```console.error(new Error('Some warning'));` . Right now, debugging the source of some errors is a huge time vampire.

@gaearon As long as a stack trace is long enough to contain the function calls in your code, there is nothing inherently wrong with having lots of react stuff in the stack traces. Libraries should be a black box except when things fail. It's when things fail that you want to be able to see what happened. If you can't see what happened in that black box, you can only effectively debug errors causes by incorrect usage of a library/framework. Debugging problems in react code becomes harder and people who encounter them can't give as much information to contributors of react to figure out if something in react needs to be fixed.

**Comment by spicyj** [comment] 2015-02-27 00:24
We can probably switch our warning module to use console.error instead, which gives a stack trace in most browsers I think.

**Comment by jimfb** [comment] 2015-07-31 06:23
Duplicate of https://github.com/facebook/react/issues/4216.  Fixed in 0.14.

**Closed by jimfb** 2015-07-31 06:23 UTC
