### ISSUE TITLE
Bug [React-DOM]: Missing "bun" export field in package.json

### ISSUE THREAD

**Issue by Guibi1** [facebook/react#28941] opened 2024-04-28 02:44 UTC
In the exports field of the `react-dom`'s package.json, there is no "bun" field. Bun defaults to the "default" field for compatibility. However, the `./server.node.js` file doesn't export `renderToReadableStream()`, while Bun supports Web Streams out of the box.

See: [The Bun doc on Module resolution](https://bun.sh/docs/runtime/modules#importing-packages)
This issue is similar to #26906, but Bun always supported Web Streams so there is no backwards compatibility issues.

React version: 18.3.1

## Steps To Reproduce

1. Install `react-dom`.
2. Import `renderToReadableStream()`
3. Run the file using Bun
4. Notice that the error is something like this: `SyntaxError: Export named 'renderToReadableStream' not found in module '~/??/node_modules/react-dom/server.node.js'.`, which clearly shows that Bun uses the default export.

Link to code example:
I am not sure how to use Bun on the browser.

## The current behavior

Bun uses the default export. (aka server.node.js)

## The expected behavior

Bun uses a custom "bun" export. (aka server.browser.js)

I have tested the following change locally and it completely fixes this issue:

![fixed package.json](https://github.com/facebook/react/assets/36936511/08a9d496-edaf-48eb-9d41-e07c1b00a084)

**Comment by AldoMX** [comment] 2024-05-01 13:42
The issue is fixed in react-dom v19, and taking a closer look they created new configuration files for bun:
https://github.com/facebook/react/blob/main/packages/react-dom/package.json#L63

I'm not sure how willing would be the team to merge my PR with your suggested fix, but let's wish for the best 🤞:
https://github.com/facebook/react/pull/28962

**Comment by Guibi1** [comment] 2024-05-01 16:10
Oh nice I'll upgrade to `react-dom@next` then. I _would_ be useful to merge your PR, just for compatibility.

**Comment by gnoff** [comment] 2024-05-01 20:50
@Guibi1 for React 18 you can always just import the right version yourself if you know you are using bun. `import ... from "react-dom/server.browser"`

I don't think we'll do another 18 release with this but React 19 should support it. If bun also supported running with custom conditions you could potentially customize the resolution that way but I don't think it supports that right now

**Closed by gnoff** 2024-05-01 20:50 UTC
Labels: Status: Unconfirmed
