### ISSUE TITLE
React dev tools doesn't appear in chrome (Ubuntu 18.04.3)

### ISSUE THREAD

**Issue by goldylucks** [facebook/react#16888] opened 2019-09-25 10:40 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
React dev tools don't appear in chrome dev tools

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Download latest chrome extension and go to https://reactjs.org, open dev tools

**What is the expected behavior?**
React dev tools tab should appear in chrome

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: N/A  

```bash
▶ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

▶ google-chrome --version
Google Chrome 77.0.3865.75
```

This worked in previous versions of chrome/chrome extension, but I'm not sure when exactly the bug surfaced, since I haven't used it in a while.

Thanks in advance for any help, React is awesome :)

**Comment by bvaughn** [comment] 2019-09-25 20:44
Seems most likely to be a duplicate of #16840, the fix for which will be releasing sometime this afternoon probably. Sorry for the inconvenience!

**Closed by bvaughn** 2019-09-25 20:44 UTC
Labels: Component: Developer Tools, Resolution: Duplicate

**Comment by bvaughn** [comment] 2019-09-25 21:08
@goldylucks To help verify if this is indeed the same issue, would you be willing to install this prerelease build of DevTools and let me know if it fixes the missing tab issue?

[ReactDevTools.zip](https://github.com/facebook/react/files/3643169/ReactDevTools.zip)

To install:
1. go to about:extensions
1. disable the React DevTools extension currently installed
1. download [the new extension](https://github.com/facebook/react/files/3643169/ReactDevTools.zip) and extract the ZIP file
1. in about:extensions, enable "developer mode" in the top right
1. click "load unpacked" button
1. browse to select the extracted folder

**Comment by goldylucks** [comment] 2019-10-03 13:09
Sorry, had a crazy week.
Working fine with the new release, thank you!
