### ISSUE TITLE
Bug: 手机端的touch事件没反应

### ISSUE THREAD

**Issue by chenleyiduo** [facebook/react#21318] opened 2021-04-20 01:24 UTC
React version:

## Steps To Reproduce

1.react16.2

手机华为p30、荣耀
在div中绑定onTouchStart、onTouchEnd、onTouchMove事件，在手机上的百度浏览器、自带浏览器等不能拖动，在手机的微信浏览器、qq浏览器可以拖动滑块。

请问需要在手机端拖动滑块应该怎么做2.

Link to code example:

**Comment by bvaughn** [comment] 2021-04-20 01:32
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-05-03 13:52
Closing because there isn't enough info.

**Closed by bvaughn** 2021-05-03 13:52 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
