### ISSUE TITLE
emoji in useState string makes useState stop working

### ISSUE THREAD

**Issue by TheRav3n** [facebook/react#17814] opened 2020-01-09 17:50 UTC
I am running on latest React. When I try to use unicode emojis in a useState string, the useState function stops updating the string.

Example:
```javascript
const [text, setText] = useState('😀');

console.log(text);
```

Emoji will be visibile in console log. However, when I run:

```javascript
setText('different text');
```

`text` now is an empty string.

What is happening? Why? How can I solve it?

**Comment by TheRav3n** [comment] 2020-01-09 17:56
I described the "general problem", which is that `useState` has issues with emojis. What I am actually trying to do is using `emoji-picker-react` to add emojis to an input field. `emoji-picker-react` returns an emoji. Then I run:

```javascript
setText(text + emoji);
```

`text` becomes an empty string and will not be "writable" anymore, until refresh of the page.

**Comment by lunaruan** [comment] 2020-01-09 18:40
Hello! I created a Codesandbox and I could not reproduce this issue. 
https://codesandbox.io/s/competent-meadow-zetlm

I'm going to close this issue for now because it seems like it's working as expected. If you are able to share a repro with us, we'll take a look and reopen the issue.

**Closed by lunaruan** 2020-01-09 18:40 UTC
