### ISSUE TITLE
[DevTools] Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by Bartel-C8** [facebook/react#24522] opened 2022-05-09 12:37 UTC
### Website or app

https://developer.chrome.com/blog/mv2-transition/

### Repro steps

Use latest React DevTools with Electron (Chromium) (18.2.0 / Chromium 100)

```
  (node:80082) ExtensionLoadWarning: Warnings loading extension at ./node_modules/electron-devtools-vendor/extensions/react-developer-tools:
    Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

### How often does this bug happen?

Every time

**Comment by lunaruan** [comment] 2022-05-09 15:32
Hey! Thanks so much for the heads up! We've added it to our plans for this year. 😊

**Comment by lunaruan** [comment] 2022-05-09 20:05
Hey, sure you can take a stab at it!

**Comment by mondaychen** [comment] 2022-05-10 21:26
@DhairyaBahl that would be nice! When do you plan to start working on it?

**Comment by bvaughn** [comment] 2022-05-11 01:26
To my knowledge, the last time we investigated manifest v3 – there were blockers for our adopting it.

**Comment by DhairyaBahl** [comment] 2022-05-11 12:31
@mondaychen I will start exploring this issue soon. Since I am a new contributor to React, successful PR may take some time. If this issue needs to be resolved on urgent basis then do let me know.

**Comment by mondaychen** [comment] 2022-05-11 14:36
@bvaughn haven't tested but at least it's still in the V3 docs https://developer.chrome.com/docs/extensions/mv3/content_scripts/#run_time

**Comment by MustkimKhatik** [comment] 2022-05-17 04:13
Hey @lunaruan, is their any assignee who is working on this issue? or is there any kind of stuff I can do?

**Comment by JadaMonroe** [comment] 2022-05-22 14:16
https://github.com/reduxjs/redux-devtools/issues/1037

**Comment by Hanaffi** [comment] 2022-06-01 11:27
@lunaruan @gaearon Can you assign this to me please?

**Comment by lunaruan** [comment] 2022-06-01 14:54
@Hanaffi sure :)

**Comment by lunaruan** [comment] 2022-06-01 21:12
@DhairyaBahl Oh no sorry! We thought you weren't because we hadn't heard from you in awhile (sorry people drop out a lot in OSS!). I'll assign this to you instead 😊

Do you know when you'd get around to it, just so we know when to reassign this if needed?

**Comment by DhairyaBahl** [comment] 2022-06-03 13:31
> Do you know when you'd get around to it, just so we know when to reassign this if needed?

Actually @lunaruan I was going through this issue and 've been reading the contributor docs and lots of other docs just to have bit more clarity on this issue coz I am contributing to React for the first time. So, it may take a while before I can make a PR but 'll try to make a PR within a week or two. Hope you understand. 

Thanks 🙂

**Comment by lunaruan** [comment] 2022-06-03 17:44
@DhairyaBahl That works for us! Thanks so much for volunteering to help out!

**Comment by mondaychen** [comment] 2022-06-09 13:38
@DhairyaBahl are you working on Windows because you no longer have access to your Linux machine? Just wanna make sure because you only need to build it on one OS.
Which yarn command was this?

**Comment by DhairyaBahl** [comment] 2022-06-09 13:59
@mondaychen I was working on linux server and i don't think that electron will work properly on linux VM. So, I decided to build and test everything on my host OS i.e. windows. I executed yarn command in the root folder of this project and got the error. just to mention, I am still having access to my linux server.

**Comment by mondaychen** [comment] 2022-06-09 14:21
@DhairyaBahl I'll try set up a Windows VM in a minute. 
Just curious why do you need to run the electron app? This task is about building the extension, I don't think you would touch anything that would break the electron app

**Comment by DhairyaBahl** [comment] 2022-06-09 14:48
@mondaychen I thought that I will have to test my changes on electron to check if the warning is still there or not. So, that's why I preferred windows gui coz over there, I will be able to check these changes easily.

**Comment by mondaychen** [comment] 2022-06-09 15:07
@DhairyaBahl OK that makes sense. But I'd say that's the last step. I believe you can test everything in Chrome.

**Comment by Tran-Quyen** [comment] 2022-06-16 16:35
How can I contribute with github ?

**Comment by mondaychen** [comment] 2022-06-16 19:16
Hi @Tran-Quyen this issue has been assigned to @DhairyaBahl. 
@DhairyaBahl do you have any updates?

**Comment by Tran-Quyen** [comment] 2022-06-17 03:13
> Hi @Tran-Quyen this issue has been assigned to @DhairyaBahl. @DhairyaBahl do you have any updates?

Thank for your reply. How can i contribute with your repository.

**Comment by MahendraBishnoi29** [comment] 2022-06-19 12:48
@lunaruan  Please assign this issue to me.

**Comment by darkknight20032001** [comment] 2022-06-19 22:50
@lunaruan  Is this issue open??? Please assign this issue to me???

**Comment by bvaughn** [comment] 2022-06-19 23:55
Folks, this issue is already assigned to someone else. I’d you’d like to submit a PR, no one is stopping you, but you only have to scroll up a few messages to see that the issue is already claimed.

**Comment by Hanaffi** [comment] 2022-06-23 19:18
@lunaruan Hey , It has been +2 weeks with no progress.
Can you assign it back to me?

**Comment by SijaAnan** [comment] 2022-06-30 15:05
Did anyone manage to reproduce this issue?
If so, how can I reproduce it?

**Comment by mondaychen** [comment] 2022-06-30 15:10
@Hanaffi I've assigned it to you. Please keep us updated with anything you have. Thanks.

**Comment by tejassinghsital** [comment] 2022-07-10 11:24
@mondaychen Hello, I am new to open source contributions and don't actually know how to grab my first issue to resolve. So can you please help me out with the same?
Here's my mail: tejassinghsital19@gmail.com please reply here or on my mail as I don't know whether GitHub has a chat feature.  Thank you in advance and I look forward to getting a reply from you.

**Comment by mondaychen** [comment] 2022-07-13 19:53
@Hanaffi any updates?

**Comment by Hanaffi** [comment] 2022-07-14 11:24
@mondaychen Ops , Sorry wasnt notified that I was assigned to it.
Will handle it.

**Comment by AnmolBansalDEV** [comment] 2022-08-06 12:31
sorry, hanaffi was not active, I submitted the PR. Hope no one is angry as It's my first contribution. @mondaychen

**Comment by mondaychen** [comment] 2022-08-09 19:21
Hi all,
We originally mark this as a "good first issue" as it does not require deep understanding of react or react devtools. So far, we have not seen a mature PR on this issue. As the deadline is fast approaching, we decided we need to get to done soon. If you have something that's almost done, please let me know. Otherwise, please consider this project is taken by a react team member.

**Comment by SijaanX** [comment] 2022-08-09 19:26
@mondaychen  Hi Mondy,
I agree its a good first issue as I understood everything that needs to be done.

But there is an issue here that im trying to solve which isnt directly related to the manifest upgrade.

Firstly in order to test the changes you need to build the extension locally. Although there is a readme in the package extension, there are still several issues when building the extension locally which I already opened issues for, and 1 got accepted and they changed the readme for, but there arw still more.

If you want I can give you an exact timeline tomorrow as I would like to work on it, but the extension repo is giving me a lot of problems currently.

**Comment by mondaychen** [comment] 2022-08-09 20:29
@SijaanX 
I agree there's room for improvements in our documentation, and thank you for contributing by creating issues about it.
If you (or anyone else) have more questions regarding how to set up the development environment, build & test the extension, you can ask here or in another issue, and I'd like to offer help.
As for this project, I hope you understand it's actually much more work for team members to guide external contributors to get things done than to get it done ourselves. It's also very unpredictable -- you can see this project was assigned to several different people, and now we are still nowhere near any real progress. For a project with a hard deadline, it's safer for us to assign a teammate to it.

**Comment by SijaanX** [comment] 2022-08-09 21:02
I understand you completely and its not a good sign when people just get busy and don't give a notice, and when stuck don't try to get help (which will definitely help a lot of others).
Anyway, I'm building it now locally again, and I will make sure to list all of the issues I face for future contributors. 
Again I will completely understand if you give it to a team member, as migration deadline is the start of 2023 which is around the corner. 

I will do my best now to try and do the upgrade locally. It would be nice if I succeed anyway :D

**Comment by SijaanX** [comment] 2022-08-09 21:25
@mondaychen Issues:

#1: When building the extension locally, you have to run: `yarn build-for-devtools` from the root repository.

This result in the following: ```
'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```
I guess the solution to this is to change `cp ` to `copy `as I'm using windows?

**Comment by mondaychen** [comment] 2022-08-09 22:36
@SijaanX if you are having issues with basic bash commands like cp you will encounter the same issue with other commands too. I don’t have a lot of experience developing on Windows, but to my knowledge you probably need to set up a Linux-like command line environment such as WSL https://docs.microsoft.com/en-us/windows/wsl/setup/environment

**Comment by SijaanX** [comment] 2022-08-09 22:37
@mondaychen Managed to solve it as I used xcopy with the recursive flags.

**Comment by SijaanX** [comment] 2022-08-10 09:12
is this error:

```
injectGlobalHook.js:2132 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-jmNafx23y91B5KUD5ahB8ex4/ewYkOS39Bl4Yk3Mweg='), or a nonce ('nonce-...') is required to enable inline execution.

injectCode @ injectGlobalHook.js:2132
page-data.json:1          Failed to load resource: the server responded with a status of 404 ()
```

related to the fact that I have to change the XMLHttpRequest to fetch() or is it something else?

This is the relevant part from the manifest.json:

  "content_security_policy": {
    "extension_pages": "script-src 'self'; object-src 'self'"
  },

**Comment by mondaychen** [comment] 2022-08-10 14:04
Yes, looks like we'll need to either use a different policy or change how we implement `injectCode`

**Comment by AnmolBansalDEV** [comment] 2022-08-12 20:47
I'm almost done with the updates but I'm not able to test the extension, even though I followed the readme file. any suggestions are highly appreciated. thank you

**Comment by mondaychen** [comment] 2022-08-15 15:43
@AnmolBansalDEV Can you describe the issue you are having? Which step did you get stuck with?

**Comment by SijaanX** [comment] 2022-08-18 22:40
@mondaychen I managed to change how we inject the code.
Now I'm getting stuck on something else where I have to idea where to debug it from:

![image](https://user-images.githubusercontent.com/42915732/185507497-6e01c536-12ce-4c85-b833-b11e631aa9b4.png)

Any idea?

**Comment by mondaychen** [comment] 2022-08-21 02:59
@SijaanX can you push your code somewhere? I'll take a look

**Comment by awells111** [comment] 2022-08-23 17:00
@SijaanX I have a Windows machine and I have git installed so I use the git bash terminal and I don't have to change any of the commands to build.

**Closed** 2022-10-22 02:52 UTC
Labels: Type: Feature Request, Component: Developer Tools

**Comment by pomack** [comment] 2022-11-03 14:53
@mondaychen It's been a couple weeks since the Manifest V3 update was added. What is the timeframe for getting the updated extension into the Chrome webstore?

**Comment by mondaychen** [comment] 2022-11-03 15:20
@pomack we've released it to some users within Meta. If nothing goes wrong in the following a few weeks, we will release it to Chrome Web Store

**Comment by Bartel-C8** [comment] 2022-12-06 08:40
There are still warnings when using React Devtools with the latest Electron (v22):

```
┏ Electron -------------------

  (node:50201) ExtensionLoadWarning: Warnings loading extension at /Users/bartel/git/klstr-ctrl/node_modules/electron-devtools-vendor/extensions/react-developer-tools:
    Permission '<all_urls>' is unknown or URL pattern is malformed.
  
  (Use `Electron --trace-warnings ...` to show where the warning was created)

┗ ----------------------------
```

And:
```
┏ Electron -------------------

  [50201:1206/093424.883640:ERROR:extensions_browser_client.cc(62)] Extension Error:
    OTR:     false
    Level:   2
    Source:  chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
    Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
    ID:      dmcmnlnmbgdfljfjniabngbfglcgggdk
    Type:    RuntimeError
    Context: chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
    Stack Trace: 
      {
        Line:     107
        Column:   1
        URL:      chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
        Function: (anonymous function)
      }

┗ ----------------------------
┏ Electron -------------------

  [50201:1206/093424.884128:ERROR:extensions_browser_client.cc(62)] Extension Error:
    OTR:     false
    Level:   1
    Source:  manifest.json
    Message: Service worker registration failed. Status code: 15
    ID:      dmcmnlnmbgdfljfjniabngbfglcgggdk
    Type:    ManifestError

┗ ----------------------------
```

Somehow the ID is messed up, I don't know what electron (or my electron install provider) does with this, but it's definitely the React Devtools:

`node_modules//electron-devtools-vendor/extensions/react-developer-tools/build/background.js:107:  chrome.scripting.registerContentScripts([{`

**Comment by Bartel-C8** [comment] 2022-12-06 13:54
Apparently, this is a Electron issue (only): https://github.com/electron/electron/issues/36545

But, isn't the `"scripting"` permission needed for accessing `chrome.scripting`?
As explained here: https://developer.chrome.com/docs/extensions/reference/scripting/#manifest ?

**Comment by iErik** [comment] 2023-01-15 04:31
That's still happening for me :c is there any solution or workaround for this issue?
