### ISSUE TITLE
Bug:  Getting Invalid Hook Call Error

### ISSUE THREAD

**Issue by singhdilip1007** [facebook/react#24492] opened 2022-05-04 06:06 UTC
This is the code I've written to call square web payments SDK with **.Net wit reactJs application**:
```JavaScript
import React from "react";
import {
    SquarePaymentsForm,
    CreditCardInput
} from "react-square-web-payments-sdk";

const PaymentFormSdk = () => {
    return (
        <SquarePaymentsForm applicationId="sandbox-sq0idb-****************" locationId="LP**************">
            <CreditCardInput/>
        </SquarePaymentsForm>
    );
};
export default PaymentFormSdk;
```

This is the way I'm calling this component on button click from another react component:
```HTML
{
this.state.Isshowpayment == true ?
<div><h2> Payment Information</h2><PaymentFormSdk/></div> 
: null
 }
```
Here's some dependency detail:
```Json
{
 "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.2.2",
    "react-scripts": "^3.0.1",
    "reactstrap": "^6.3.0",
    "rimraf": "^2.6.2",
    "react-square-web-payments-sdk": "2.2.3"
}
```

Please help me on it while its most prioritized task for me, thanks in advance

**Comment by ahmadaafaq** [comment] 2022-05-06 05:23
I think you are missing some rule to call hooks, please go through https://reactjs.org/docs/hooks-rules.html

**Comment by singhdilip1007** [comment] 2022-05-06 05:36
I've followed the details with link shared by you, all things are fine as per above. Thanks @ahmadaafaq

**Comment by bvaughn** [comment] 2022-05-06 17:35
@singhdilip1007 Were you able to resolve the issue then or is it still occurring? If you're still having troubles, you'll need to share more of your code (preferably a Code Sandbox that we can run and reproduce the error).

**Comment by singhdilip1007** [comment] 2022-05-07 15:04
@bvaughn Please see this link, I've added here my requirement:
https://codesandbox.io/s/laughing-hooks-itsehd?file=/src/App.js

I've a class component like **app.js** and in this component, there is a button. Once click on that button I'm trying to call **Paymentform.js** component which is showing above hook call error message

@ahmadaafaq FYI

**Comment by bvaughn** [comment] 2022-05-07 15:49
I don't see any errors or warnings in the console on the Code Sandbox you linked, @singhdilip1007.

**Comment by singhdilip1007** [comment] 2022-05-07 16:15
@bvaughn Yes, here's its not showing any error but in our application its showing error as `Invalid Hook Call Error` like above I"ve mentioned in description

**Comment by bvaughn** [comment] 2022-05-07 16:43
It sounds like a problem with your application configuration. I suggest checking out this page for common causes and fixes:
https://reactjs.org/warnings/invalid-hook-call-warning.html

I'm going to close this issue because I'm fairly confident the link above contains the cause, and also because there isn't much that we can do without a repro case.

**Closed by bvaughn** 2022-05-07 16:43 UTC
Labels: Status: Unconfirmed, Resolution: Needs More Information

**Comment by ahmadaafaq** [comment] 2022-05-09 05:55
> @bvaughn Please see this link, I've added here my requirement: https://codesandbox.io/s/laughing-hooks-itsehd?file=/src/App.js
> 
> I've a class component like **app.js** and in this component, there is a button. Once click on that button I'm trying to call **Paymentform.js** component which is showing above hook call error message
> 
> @ahmadaafaq FYI

Like I mentioned the set of rules, there's a rule that you can not call a hook inside a **Class** only call hooks from react **functions**, may be that is what you are missing calling a hook inside class component.
https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions
