### ISSUE TITLE
calling setState on componentWillMount in Shallow Render results in TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by drabinowitz** [facebook/react#4461] opened 2015-07-22 13:53 UTC
Calling `setState` on `componentWillMount` in a component being Shallow Rendered will result in the error `TypeError: Cannot read property '_currentElement' of null` being thrown. I set up a test case:

```javascript
var expect = require('chai').expect;                                             
                                                                                 
describe('testing state', function() {                                           
                                                                                 
  beforeEach(function() {                                                        
    var Window = require('domino/lib/Window');                                   
    var domino = require('domino');                                              
                                                                                 
    global.document || (global.document = domino.createDocument());              
    global.window = new Window(global.document);                                 
    global.navigator = global.window.navigator;                                  
  });                                                                            
                                                                                 
  it('should handle having initial state', function() {                          
    // this passes                                                               
    var React = require('react');                                                
    var ReactTestUtils = require('react/lib/ReactTestUtils');                    
                                                                                 
    var Sample = React.createClass({displayName: "Sample",                       
      getInitialState: function() {                                              
        return {                                                                 
          groovy: 'doovy'                                                        
        };                                                                       
      },                                                                         
                                                                                 
      render: function() {                                                       
        return React.createElement("div", null, this.state.groovy);              
      }                                                                          
    });                                                                          
                                                                                 
    var renderer = ReactTestUtils.createRenderer();                              
    renderer.render(React.createElement(Sample, null), this);                    
    var result = renderer.getRenderOutput();                                     
    expect(result.props.children).to.equal('doovy');                             
  });                                                                            
                                                                                 
  it('should handling set state on componentWillMount', function() {             
    // this fails                                                                
    var React = require('react');                                                
    var ReactTestUtils = require('react/lib/ReactTestUtils');                    
                                                                                 
    var Sample = React.createClass({displayName: "Sample",                       
      componentWillMount: function() {                                           
        return this.setState({                                                   
          groovy: 'doovy'                                                        
        });                                                                      
      },                                                                         
                                                                                 
      render: function() {                                                       
        return React.createElement("div", null, this.state.groovy);              
      }                                                                          
    });                                                                          
                                                                                 
    var renderer = ReactTestUtils.createRenderer();                              
    renderer.render(React.createElement(Sample, null), this);                    
    var result = renderer.getRenderOutput();                                     
    expect(result.props.children).to.equal('doovy');                             
  });                                                                            
});    
```

**Comment by jimfb** [comment] 2015-07-22 17:18
Who would be best to answer this one?  @spicyj @graue

**Comment by graue** [comment] 2015-07-23 01:01
Seems like a valid bug report — thanks @drabinowitz, and the test case is rad. I may not be able to look at this for a while, unfortunately.

**Comment by drabinowitz** [comment] 2015-07-23 01:19
no worries let me know if you need any more info from me. This was on React 14 beta btw (not sure if that matters)

**Comment by fabiomcosta** [comment] 2015-08-26 21:23
A simple example that throws the error:
```js
describe('A', () => {
  var React;
  var ReactTestUtils;

  beforeEach(() => {
    jest.resetModuleRegistry();
    React = require('React');
    ReactTestUtils = require('ReactTestUtils');
  });

  it('test', () => {
    class A extends React.Component {
      componentWillMount() {
        this.setState({a:true});
      }
    }
    ReactTestUtils.createRenderer().render(<A/>);
  });
});
```

**Comment by tnrich** [comment] 2015-08-27 06:50
Any way of getting around this issue? I am currently running into it.

**Comment by graue** [comment] 2015-08-29 04:37
Sorry about the slow response from us (FB) here. I'm the principal author of the shallow render feature, but React core isn't my main gig and I've been swamped with product work. I don't have an offhand answer for you, @tnrich, but I've just put time on my calendar to look into this next week.

Jim, Ben, Paul — if by chance one of you happened to take care of this before then, I wouldn't be mad :)

**Comment by tnrich** [comment] 2015-08-29 15:06
An update on my end. I think that my problem actually went away when I
deduped my npm dependencies to remove an extra react version that was
causing issues. If this error pops up again I'll let you know. Thanks for
the response!

**Comment by drabinowitz** [comment] 2015-08-30 14:42
Hmm I am still able to reproduce this issue in my test case after running npm dedupe

**Comment by tnrich** [comment] 2015-08-31 05:53
Just to clarify, my previous comment wasn't supposed to mean that the issue has gone away. I think I was seeing a separate issue caused by multiple react versions that I misidentified as this issue (I hope that makes sense).

**Comment by sebinsua** [comment] 2015-10-01 14:57
I am getting this error, too. I'm using react v0.14.0-rc1.

```
TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentMixin._updateRenderedComponent (http://localhost:3000/testbundle.js:16293:52)
    at ReactCompositeComponentMixin._performComponentUpdate (http://localhost:3000/testbundle.js:16278:10)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:3000/testbundle.js:16207:12)
    at ReactPerf.measure.wrapper [as updateComponent] (http://localhost:3000/testbundle.js:22790:21)
    at ReactCompositeComponentMixin.performUpdateIfNecessary (http://localhost:3000/testbundle.js:16155:12)
    at Object.ReactReconciler.performUpdateIfNecessary (http://localhost:3000/testbundle.js:23592:22)
    at runBatchedUpdates (http://localhost:3000/testbundle.js:25280:21)
    at ReactReconcileTransaction.Mixin.perform (http://localhost:3000/testbundle.js:27239:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (http://localhost:3000/testbundle.js:27239:20)
    at ReactUpdatesFlushTransaction.assign.perform (http://localhost:3000/testbundle.js:25237:38
```

Looking at the code it seems to fail on the second line of `_updateRenderedComponent`:

```
  /**
   * Call the component's `render` method and update the DOM accordingly.
   *
   * @param {ReactReconcileTransaction} transaction
   * @internal
   */
  _updateRenderedComponent: function (transaction, context) {
    var prevComponentInstance = this._renderedComponent;
    var prevRenderedElement = prevComponentInstance._currentElement; // "TypeError: Cannot read property '_currentElement' of null" is thrown here.
```

**Comment by graue** [comment] 2015-10-01 23:25
Note that shallow rendered components override `_instantiateReactComponent` to return a `new NoopInternalComponent()` instead of whatever it normally returns. That still shouldn't be undefined and should have a `_currentElement` attribute, though. https://github.com/facebook/react/blob/0fb49fc4dc31b99f40e73041718e162bc3595fdb/src/test/ReactTestUtils.js#L384

**Comment by Emibob** [comment] 2015-10-06 20:21
I'm experiencing this issue too - @sebinsua your suggestion gets me past the initial error & on to `Cannot read property 'ref' of undefined` in `ReactRef.js:63:20`

**Comment by troutowicz** [comment] 2015-10-09 15:15
@graue Whether or not this breaks other things I don't know. But moving [lines 278-285](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L278-L285) directly above [line 269](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L269) fixed this for me.

**Comment by neelance** [comment] 2015-10-15 13:54
We are also affected by this issue. I think shallow rendering is a really cool feature for testing, but unfortunately I can't use it for some of our components due to this bug.

**Comment by neelance** [comment] 2015-10-22 12:28
I created pull request #5247 with a fix that works for me. Can someone else verify?

**Comment by alexeyraspopov** [comment] 2015-10-30 21:23
Any workaround for this issue?

**Comment by albertogasparin** [comment] 2015-11-04 11:49
:+1: Having same issue

**Comment by lparry** [comment] 2015-11-19 01:52
Just ran into this too :/

**Comment by mihaialexe** [comment] 2015-11-20 09:35
Any update on this? I see that 0.14.3 was released, but these kind of tests are still failing.

**Comment by neelance** [comment] 2015-11-20 16:16
@mihaialexe I think I have to add a test to my pull request before it can be merged, but I did not get around to do it yet.

**Comment by spicyj** [comment] 2015-12-02 02:56
Closing in favor of #5561 which should merge soon.

**Closed by spicyj** 2015-12-02 02:56 UTC
Labels: Component: Addons / TestUtils / Shallow Render
