### ISSUE TITLE
[DevTools Bug]: react-devtools standalone launching and quitting after 2 seconds with no errors on Ubuntu 22.04

### ISSUE THREAD

**Issue by tomatic** [facebook/react#25234] opened 2022-09-11 10:20 UTC
### Website or app

https://www.facebook.com

### Repro steps

Run `react-devtools` in the terminal.

An empty window appears for maybe 2 seconds and then disappears. The terminal doesn't show any messages whatsoever.

There is another issue here regarding react-devtools failing silently on Debian, where the submitter alleged that it was related to insufficient permissions to run electron. Not sure if that's related to this issue, but I can run electron just fine, it's just react-devtools that are failing.

OS is Ubuntu 22.04 (Kubuntu), Node is v16.16.0, react-devtools 4.25.0

(Updated to add URL)

### How often does this bug happen?

Every time

**Comment by lunaruan** [comment] 2022-09-13 18:24
Hey! Thanks for reporting! I'm unable to reproduce your issue with your current repro steps, but it seems likely a permission issue. I'm going to close this for now, but feel free to reopen if you have more repro steps!

**Closed by lunaruan** 2022-09-13 18:24 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools

**Comment by IronGeek** [comment] 2022-10-20 22:39
Hi, I'm sorry for commenting on closed issue.

I recently had the same problem outlined here (also on Ubuntu 22.04), and manage to resolve it by running the standalone DevTools app using `--no-sandbox` paramater.

```
react-devtools --no-sandbox
```
---
How I came to the above workaround:

1. Change the `{ stdio: 'ignore' }` to `{ stdio: 'inherit' }` in: https://github.com/facebook/react/blob/65e32e58b6057db1fdfed95a942fad4fc96da191/packages/react-devtools/bin.js#L32-L34
2. Run **react-devtools**
3. **react-devtools** will run and immediately exit with the following error message:

   ```
   [1818947:1018/105356.570413:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
   ```
4. A bit of Googling for the error message lead me here:
   https://github.com/Automattic/simplenote-electron/issues/3044
6. _Profit_

I hope this will help someone having the same problem...
