### ISSUE TITLE
[reactDOM.createPortal] issue with portal used in new window - IE errors when calling window.getComputedStyle()

### ISSUE THREAD

**Issue by jbgarr** [facebook/react#13096] opened 2018-06-22 16:42 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When `ReactDOM.createPortal` is used with a container in a new window (by calling `window.open()`), and `window.getComputedStyle()` is called on a DOM node found in the container an `Unspecified error.` is thrown in IE. This seems to work fine in Chrome, and Firefox, but in IE (running version 11.0.09600.19003) it throws an error.

The issue can be seen in the following CodeSandbox: https://codesandbox.io/s/zk7895x5n3

**What is the expected behavior?**
Calling `window.getComputedStyle()` on an element in a portal located in a new window should work in IE like it does in the other browsers.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I see this issue in React/React-dom v16.3.2, IE v11.0.09600.19003 (running in VirtualBox on a Mac).

**Comment by aweary** [comment] 2018-06-22 21:40
@jbgarr can you try to reproduce this without React and see if you get the same error? I'm guessing this just might be how `window.getComputedStyle` works in IE11 when called with a node from a different window.

Does `externalWindow.getComputedStyle` work?

**Comment by jbgarr** [comment] 2018-06-23 00:02
@aweary Thanks for the reply. It looks like the issue is indeed due to how IE handles `window.getComputedStyle`... sadly.

I've created a jsfiddle that shows the issue in vanilla js: https://jsfiddle.net/jbgarr/a68qok5v/5/

As you suggested, yes, `externalWindow.getComputedStyle` does work, but it's a little trickier than that since the call to `getComputedStyle` is actually being made by a third-party component (react-select) that I'm using. I've hacked together a monkey patch solution that might work, but it's definitely not the clean solution I was hoping for.

If anyone else out there has ideas, I'm all ears!

**Comment by aweary** [comment] 2018-06-24 00:53
Thanks for verifying! Since this isn't a bug with React I'm going to close this out. The best place for usage questions our [community support resources](https://facebook.github.io/react/community/support.html). You may want to try and work with the author(s) of react-select to see if they can provide a better solution for you.

**Closed by aweary** 2018-06-24 00:53 UTC

**Comment by anandrikka** [comment] 2018-10-03 15:34
@aweary I'm also facing similar kind of problem. Could you share your solution ?
