### ISSUE TITLE
Error: "Could not find commit data for root "729" and commit 2"

### ISSUE THREAD

**Issue by elliott-greaves-babylon-health** [facebook/react#17292] opened 2019-11-06 19:11 UTC
Describe what you were doing when the bug occurred:
1. Viewing a component within Storybook
2. Opened Profiler
3. Changed the target from Root to Story

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.0-a8b8ffb89

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162685)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:332158)
    at sc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:332375)
    at fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59263)
    at Hi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:66573)
    at lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104884)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89467)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89392)
    at pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86341)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45721

Component stack: in sc
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by aweary** [comment] 2019-11-06 19:21
@elliott-greaves-babylon-health can you please share a code example that reproduces the issue? It's difficult for us to help without that.

**Comment by bvaughn** [comment] 2019-11-26 19:15
Duplicate of #16506

**Closed by bvaughn** 2019-11-26 19:15 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
