### ISSUE TITLE
ReactDefaultPref-test.js randomly fails

### ISSUE THREAD

**Issue by jalejos** [facebook/react#5149] opened 2015-10-12 22:55 UTC
Hello everybody, I'm relatively new to the project and I think I ran into an issue. I was running grunt test on a recently cloned copy of the master branch and I have been getting a failed test every once in a while while doing so without touching any part of the code. 

The error is found on *it(should count no-op update as waste)* and happens on *expect(summary[1]['Instances']).toBe(2);* The error message is that it is expecting the instances to be 2, but it randomly returns 0's and 1's.

**Comment by jimfb** [comment] 2015-10-12 22:57
Haven't seen that before - Have you done a git pull to latest?  What version of node are you running?  What operating system?

**Comment by jalejos** [comment] 2015-10-12 23:04
I'm running on Ubuntu and node version is v0.10.25. The pull was done earlier today and re-reading the error I think it is directed towards somewhere else, so I'll leave it here

src/test/__tests__/ReactDefaultPerf-test.js (0.571s)
● ReactDefaultPerf › it should count no-op update as waste
  - Expected: 1 toBe: 2
        at Spec.<anonymous> (src/test/__tests__/ReactDefaultPerf-test.js:70:28)
  - TypeError: Cannot read property 'Owner > component' of undefined
        at Spec.<anonymous> (src/test/__tests__/ReactDefaultPerf-test.js:78:22)

**Comment by jimfb** [comment] 2015-10-13 00:44
Interesting.  We don't support building on node 0.10.25.  I'm actually a little surprised you were able to do an npm install of the React repository.

I just ran the tests ten times on my Linux machine (`Linux ubuntu 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:23:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`, node v4.2.0 and was unable to repro the issue).

@jalejos Can you upgrade your version of node to v4.2.0 and let me know if you're still able to reproduce the issue?

**Comment by jalejos** [comment] 2015-10-13 17:07
Hi again, sorry for the late reply, I've updated my node version to 4.2.0 and ran npm install again after deleting node_modules, npm version is 2.14.7 and I am still having the same issue. After that happening I decided to clone the project to a separate folder and run the steps over again and the issue was still present.

**Comment by jimfb** [comment] 2015-10-13 18:10
@spicyj any ideas?  This is a mystery to me.

Is anyone else able to reproduce the issue?

**Comment by spicyj** [comment] 2015-10-13 18:18
No idea.

**Comment by jimfb** [comment] 2015-10-13 23:33
@jalejos At this point, I'm not sure what we can do to fix.  This is the first I've heard of the issue, and I'm unable to reproduce.  If you get a chance to investigate, I'd be super curious to hear what you discover.

**Comment by iredelmeier** [comment] 2015-10-27 08:13
@jimfb I'm also seeing random failures with 4.1.2 and 4.2.1 and Ubuntu.

It looks like the cause has to do with these lines in [ReactDefaultPerfAnalysis.getInclusiveSummary](https://github.com/facebook/react/blob/master/src/test/ReactDefaultPerfAnalysis.js#L158). Candidates that are faster than `DONT_CARE_THRESHOLD` don't make it into the summary.

If you crank up `DONT_CARE_THRESHOLD`, the test should start failing. The other tests still pass, at least for me.

Could be something to do with `performanceNow`? It doesn't seem to be using the mocked version.

**Comment by gaearon** [comment] 2016-10-27 14:56
Closing as very old.

**Closed by gaearon** 2016-10-27 14:56 UTC
