### ISSUE TITLE
Question: How to remove dynamic children from Parent State?

### ISSUE THREAD

**Issue by IanChok** [facebook/react#18049] opened 2020-02-17 02:21 UTC
I'm using react hook `useContext`. I have two identical components (siblings), each that use the same context that is a list.

**Scenario**
1. The first sibling is created, calls `useContext`, and then pushes something into the list. 
2. The second sibling is then created, using the same `useContext`, and then pushes something into the list. 

**Issue**
The second sibling has the current state of list, which has two items, _but the first sibling state is not updated with the second item that was pushed in by the second sibling_

**Expected**
That each component that is using the same `useContext` will be updated amongst all components that use the same context.

Is this a bug or am I misusing this? Any help or guidance is appreciated 🙇

**Comment by nizamcse** [comment] 2020-02-17 06:13
You might be missing something. Context working as expected - You can see the example here.

[Code Sandbox](https://codesandbox.io/s/focused-water-ib0qd?fontsize=14&hidenavigation=1&theme=dark) @IanChok

**Comment by IanChok** [comment] 2020-02-17 08:29
Actually the sibling components are in a parent component, and the parent component is a direct child of the provider. Is it best practice to only use context as a direct child of a provider?

**Comment by threepointone** [comment] 2020-02-17 12:05
Please share a reproducing usecase with codesandbox? Hard to tell without some code. 

> Is it best practice to only use context as a direct child of a provider?
No, context is specifically for passing deep into trees. That shouldn't be a problem.

**Comment by IanChok** [comment] 2020-02-18 19:08
[Code Sandbox](https://codesandbox.io/s/runtime-fast-bcpjx?fontsize=14&hidenavigation=1&theme=dark)

So this is a bit different, but basically what I'm trying to do is create dynamic children components and have the parent keep the state of the children. And when the child is clicked on, I want to remove that child from the state of the parent. 

**Scenario**
Child 1, 2 and 3 are created. When I click child 2 to remove it, both child 2 and 3 are removed.

**Expected**
Only child 2 is removed

How do i achieve this?

I've tried to pass a _remove_ method from the parent down to each children created. The remove method calls the parent state and removes the child from the state (demonstrated from the sandbox above). But, when an earlier child clicks on the callback remove function, it appears that the callback function (when accessing the state) only refers to the state at the time the child was created, and doesn't have the updated state with new children (hence both child 2, and 3 are removed).

**Comment by sophiebits** [comment] 2020-02-22 04:10
The issue is that your addChild function is referring to a copy of the removeChild function that is using an older copy of `state`. So when you click and removeChild runs, the `state` in that function is actually the state at the time the child was created.

A couple ways to fix this:

1. In most cases you would want to construct the React elements (`<DynamicChild />`) at render time rather than storing them in state. For example, you can store just `{id}` in state, then render `{state.map(child => <DynamicChild id={child.id} key={child.id} removeChild={removeChild} />)}` instead of `{state.map(child => child.child)}` below.

2. You can rewrite removeChild to use the _functional_ setState form, which always receives the latest state. That would look something like:
  ```
  const removeChild = id => {
    setState(oldState => {
      return oldState.filter(child => child.id !== id);
    });
  };
  ```

I verified that both of these would fix your issue.

This is a subtle issue. If you don't have a full understanding based on what I just wrote, these blog posts may help – they cover some similar questions:

https://overreacted.io/how-are-function-components-different-from-classes/
https://overreacted.io/making-setinterval-declarative-with-react-hooks/

I'm going to close this, as it isn't a bug in React. Next time, if you need help with your code, please see our community resources at: https://reactjs.org/community/support.html

**Closed by sophiebits** 2020-02-22 04:10 UTC
Labels: Resolution: Invalid, Resolution: Needs More Information, Type: Question

**Comment by IanChok** [comment] 2020-02-23 02:50
Thanks @sophiebits! 🙇
