### ISSUE TITLE
CSSTransitionGroup throws when a child returns null from render

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react#2619] opened 2014-11-27 20:42 UTC
I came across this, when using `react-router`. When loading a route initially where the route handler is actually inside a `ReactCSSTransitionGroup` and then removing it from the transition group leads to an `Uncaught TypeError: Cannot read property 'addEventListener' of null `. The weird thing is that it only happens on initial load of a nested route, not when the same view is being pulled up via the menu. I'm not sure if this is an issue related `react-router` or if it belongs to `react`. But the thing is that the `RouteHandler` component either returns a react element, or it returns `null`. It seems like an edge case maybe, because it only happens in this specific initial render setup.

It could be fixed, by adding a guard to the `transition()` method of  `ReactCSSTransitionGroupChild`:
```
if (!node) {
  finishCallback && finishCallback();
  return;
}
```

**Comment by gaearon** [comment] 2015-03-01 12:53
I don't think this is solved.

It's easy to reproduce with React 0.12.2: just have the child return `null` from `render`. It's rather frustrating because some other developer may change the animated component to return `null` when data is not ready, and not realize that this breaks the case when that component is inside the transition group.

**Comment by joshthecoder** [comment] 2015-03-06 08:14
Yup ran into this as well. If you pass a component to ReactCSSTransitionGroup that renders null you get this exception. Using React 0.12.1

**Comment by gaearon** [comment] 2015-03-06 12:14
@spicyj Can you please reopen?

**Comment by jarvanxing** [comment] 2015-06-10 09:32
i've get the same exception, too.  Hope this will be fixed soon.

**Comment by johanneslumpe** [comment] 2015-06-10 09:54
@spicyj is there anything stopping you people from implementing the suggested fix? :)

**Comment by dubert** [comment] 2015-06-18 14:58
I'm encountering a similar issue.

**Comment by gaearon** [comment] 2015-06-18 15:19
>is there anything stopping you people from implementing the suggested fix? :)

I guess a PR would be welcome?

**Comment by johanneslumpe** [comment] 2015-06-18 15:27
@gaearon yeah, there is is!

**Closed** 2015-06-20 23:42 UTC
Labels: Component: Addons / TransitionGroup

**Comment by digitalmaster** [comment] 2015-07-20 23:03
I'm still seeing this issue. 

React with addons v0.13.3

**Comment by spicyj** [comment] 2015-07-20 23:04
Yes, the fix is in 0.14.

**Comment by digitalmaster** [comment] 2015-07-20 23:06
Ahh.. well that would explain things.

How can I get my hands on 0.14?

**Comment by spicyj** [comment] 2015-07-20 23:09
Sorry – not released yet, but hopefully in the next few weeks. 0.14-beta is on npm (see the React blog).
