### ISSUE TITLE
Firefox browser console opens randomly blank after installing react dev tools

### ISSUE THREAD

**Issue by dehghani-mehdi** [facebook/react#16564] opened 2019-08-24 04:50 UTC
Hi,

Firefox v68.0.2
React dev tools: latest version

After disabling React dev tools same tab works as expected.

p.s: this happens mostly on non-react tabs.

I just started using react dev tools and I don't know about prev version of Firefox or React dev tools btw.

**Comment by bvaughn** [comment] 2019-08-24 16:59
I don't think I understand what's being reported here. Could you provide a video or at least a screenshot? What does it mean that it "opens randomly"? Which part of it is blank?

From my own testing, I don't see anything unusual with React DevTools in Firefox on non-React sites.

**Comment by dehghani-mehdi** [comment] 2019-08-25 04:14
Here on react repository you love add `Resolution: Needs More Information` label and them leave the issue be open forever, I hope this time you remove this label as soon as you was happy with provided info, which I think with this screenshot you should be happy.

Luckily I hit F12 on this page (this github page) and it happens again, at first try.

![Screenshot](https://user-images.githubusercontent.com/9152330/63645492-94b9f900-c714-11e9-8fef-1b773facc29c.png)

**Comment by bvaughn** [comment] 2019-08-25 21:14
> Here on react repository you love add Resolution: Needs More Information label and then leave the issue open forever

The label was added to this issue because the original issue description was very sparse. This is a very active open source project, and only a few of us are working to maintain it, so having clear instructions on how to reproduce an issue **is very important**.

The comment you added provides a little more context, but I'm still not sure I know how to reproduce the issue. (It does not happen for me.) Possibly another extension you have installed is somehow triggering this? Do you see any errors in the console after this happens.

in case you are not familiar with how to debug and extension in Firefox, this thing provides a lot of helpful information:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging

it would be very helpful to me if you are able to provide anything more in the way of error logs.

**Comment by dehghani-mehdi** [comment] 2019-08-26 04:22
Thank you for your time.

> The label was added to this issue because the original issue description was very sparse. This is a very active open source project, and only a few of us are working to maintain it, so having clear instructions on how to reproduce an issue is very important.

It's totally okay, I'm developer too and I know any details can be helpful and even key to the solution, if the reporter provide enough info you should remove the label, that's what I was talking about.

> Possibly another extension you have installed is somehow triggering this?

I tried with new [profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) and got same result. (obviously I just installed React dev tools)

> Do you see any errors in the console after this happens?

As I mentioned and screenshot says too, the console is totally empty (it just has title)

About debugging extension, I'll try if I find enough free time, but there is no promise.

**Comment by dehghani-mehdi** [comment] 2019-09-04 11:26
@bvaughn I think this issue doesn't related to React dev tools in it's Firefox's bug. I'm not sure yet, so please don't close the issue, I'll back to you asap!

**Comment by bvaughn** [comment] 2019-09-14 03:29
Potentially related issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1581230

I don't think this issue has anything to do with React DevTools at this point, so I'm going to close it. We can continue to talk here though.

**Closed by bvaughn** 2019-09-14 03:29 UTC
Labels: Component: Developer Tools, Type: Bug
