### ISSUE TITLE
CSSTransitionGroup buggy due to transition events not firing reliably

### ISSUE THREAD

**Issue by mariusk** [facebook/react#1326] opened 2014-03-29 18:17 UTC
While trying to convince React to replace DOM nodes in-place (which seems is not supported), I've discovered something that looks like bugs. I've put up a demo on http://jsbin.com/hokahaze/6/edit .

First of all, if a node gets replaced while animation is progressing, it is not removed. In the demo it means additional lines are created. As soon as the animation completes, the node usually goes away.

The second "feature" here is that if you leave that demo running, change to another tab, wait 10 seconds and change back to the tab with the demo running, it will now have accumulated lots of "green items" which are basically stuck (meaning their animation completed, but they were not removed from the dom).

**Comment by jiyinyiyong** [comment] 2015-01-26 07:58
Is this issue going to be fixed now?

**Comment by bradens** [comment] 2015-01-26 17:46
@ninjabiscuit the suggested workaround is the one in https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx which just relies on a timeout, rather than assuming the browser will fire the event.  Until the browsers fire the event properly, this will probably be the only thing we can do.

**Comment by Flaise** [comment] 2015-01-26 19:54
What @bradens suggested is what I'm doing. It works alright but it's less maintainable than a solution that doesn't require extra parameters.

**Comment by artursapek** [comment] 2015-02-16 14:25
I think there should be a warning about this in the [docs](http://facebook.github.io/react/docs/animation.html). It's a pretty big flaw and caught me off guard.

I would do it myself and submit a pull request but I'm not sure what the convention is for warning about bugs in the React docs. Does it belong as a "Note" (markdown block quote) or is there a convention for more severe warnings? I can't find any examples.

**Comment by spicyj** [comment] 2015-04-01 21:47
Yeah, this is unfortunate and something we don't have a great solution for. Khan Academy's TimeoutTransitionGroup has worked for several people in the linked issue #1707:

http://khan.github.io/react-components/#timeout-transition-group

**Comment by johtso** [comment] 2015-04-17 18:47
Yes, a mention in the docs would be great!

**Comment by Bacto** [comment] 2015-06-10 08:52
I have the same problem.
If it can help, I've reproduce it here:
https://jsfiddle.net/7wyp8e1r/3/

Wait a few seconds to see the DIV not destroyed because of the transitionend event not fired.

**Comment by jedwards1211** [comment] 2015-06-30 05:31
I just ran into this problem.  New thoughts: couldn't `TransitionGroup` detect if a child gets reintroduced or reordered before its `componentWillLeave()` has called the `callback`?  The solution when a child is reintroduced could be to call `componentWillEnter()`, and in the case of a reorder just assume the `transitionend` won't be fired and remove the component immediately.  Of course it would have to be smart enough to ignore the `callback` if it does still get called later.

**Comment by jedwards1211** [comment] 2015-06-30 05:38
`TimeoutTransitionGroup` doesn't seem to be working for me as a drop-in replacement for `TransitionGroup` (rather than `CSSTransitionGroup`).  Has anyone had luck in that case?

**Comment by jedwards1211** [comment] 2015-06-30 05:52
My `componentWillEnter()` and `componentWillLeave()` rely on `setState(...)` to trigger the CSS animations (I'm doing a dynamic grid layout where I have to set the translation programatically).  What's worked best for me so far is to `setTimeout()` for 100 ms longer than the animation, and when it fires, if the component is still mounted, perform the same `setState(...)` that my `componentWillEnter()` does.  All of the children jerk around instead of animating though, because the child order change is canceling the animation.

**Comment by spicyj** [comment] 2015-06-30 13:44
TimeoutTransitionGroup, like CSSTransitionGroup, uses TransitionGroup to do CSS animations. If you're triggering them by hand there's no reason to use TimeoutTransitionGroup.

**Comment by jedwards1211** [comment] 2015-07-01 21:45
For the non-CSS case, I created a modified version of `ReactTransitionGroup` [here](https://github.com/jedwards1211/robust-transition-group/tree/master) that solves this problem by altering the semantics: if a component is added back before it finishes leaving, for example, its `componentWillEnter()` will be called again.  Likewise, `componentWillLeave()` can be called before `componentWillEnter()` is finished if the component was added and removed that quickly.  It ignores the callbacks if the component isn't in the appropriate state, and only calls `componentDidLeave()` etc. if the appropriate callback fired while the component was in the leaving etc. state.

This is completely analogous to how CSS transitions can reverse in mid-flight, and I think a must for any component that can be added and removed before it can finish transitioning.

It doesn't handle the problem of no `transitionend` event if the children are re-ordered since that's a CSS-specific issue; but it does provide more reliable and consistent base behavior for abstract transitions.

**Comment by ccorcos** [comment] 2015-07-22 23:41
I agree, CSSTransitionGroup is not working terribly reliably. I keep getting this warning all the time:

```
Warning: transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition.
```

Is would be great if this worked better. At the very least, I'd love to know *which* animation isnt firing a transitionend!

**Comment by jimfb** [comment] 2015-07-22 23:45
Tracking @ccorcos request as https://github.com/facebook/react/issues/4465 (obviously he already knows that; I'm just linking the threads for future reference)

**Comment by spicyj** [comment] 2015-08-12 00:43
Going to go with #4561 I think.

**Comment by oozaa** [comment] 2015-08-27 22:56
I have similar problem with TransitionGroup(not CSS, using callbacks) and wondering is that the same one and I can hope for fix in 0.14. 

At start my TransitionGroup is empty, then component re-renders and adds 5 components to it, triggers componentWillEnter,componentDidEnter - all good. 
After some action my component re-renders and puts 0 components to TransitionGroup, triggers 5 times componentWillLeave(on detach I do not perform any transition, calling to callback straight away) and detaches ONLY ONE component! If I rerender again with 0 components it detaches again ONLY ONE.
If in  componentWillLeave i use setTimeout((),100) all works how it should be.

**Comment by spicyj** [comment] 2015-08-27 22:58
@oozaa That was a separate issue which should also be fixed.

**Comment by jedwards1211** [comment] 2015-08-28 03:54
@spicyj do you have a link to the issue/fix?  Does it work properly even when components are removed before done entering or added back before done leaving?

**Comment by jedwards1211** [comment] 2015-08-28 03:54
@oozaa if nothing else works for you feel free to try out my [robust-transition-group](https://github.com/jedwards1211/robust-transition-group)

**Comment by dragoscd** [comment] 2015-08-31 12:16
I used focus and blur on window to disable the animation while the window is not focused.

  onWindowBlur: function() {
    clearInterval(this.sliderInterval);
  },

  onWindowFocus: function() {
    this.activateAutoSlide();
  }

**Comment by flipace** [comment] 2015-09-10 21:03
You might also want to checkout VelocityTransitionGroup: https://github.com/tkafka/react-VelocityTransitionGroup - it uses Velocity.js instead of CSS transitions though.

(I made a minor addition to this component in my fork which allows you to specify if the transitiontype should stay the same after it has been set once and another transitionName is set later: https://github.com/flipace/react-VelocityTransitionGroup)

**Comment by spicyj** [comment] 2015-09-10 21:10
In 0.14 RC you're asked to specify durations, so this is fixed.

**Closed by spicyj** 2015-09-10 21:10 UTC
Labels: Component: Addons / TransitionGroup

**Comment by AvraamMavridis** [comment] 2015-10-02 08:13
Is this issue solved? I have it in 0.13.3

**Comment by flipace** [comment] 2015-10-02 08:41
As @spicyj wrote - it'll be fixed in 0.14 by asking you for durations. In 0.13.3 it's still an issue.

**Comment by chriswalkr** [comment] 2016-03-10 12:21
Is this issue solved for ReactTransitionGroup? It doesn't require passing in timeouts. I'm getting an animation bug which is resolved using ReactCSSTransitionGroup but exists when using ReactCSSTransitionGroup.

**Comment by spicyj** [comment] 2016-03-10 22:48
ReactTransitionGroup itself shouldn't have any issues since it doesn't have anything to do with transition events.
