### ISSUE TITLE
Hard to catch errors in `React.render`

### ISSUE THREAD

**Issue by SegFaultx64** [facebook/react#5549] opened 2015-11-26 01:25 UTC
This is related to #2461. Essentially if we wrap a render call in a try catch this works the first time. It seems like when `React.render` is called a second time (the update case) it does not work. It seems that  `React.render` is async when updating an existing component tree. 

I may be missing something but it seems like this leaves no way for developers to catch errors when rendering children components.

I have a JSBin demoing this issue here: http://jsbin.com/mifedepada/edit?js,console,output

**Comment by staxmanade** [comment] 2015-12-06 03:56
@SegFaultx64 I've been playing [with a wrapper](https://github.com/staxmanade/react-component-errors) that - check out [this plnkr](http://plnkr.co/edit/iMfSu5?p=preview). It' using [this project](https://github.com/staxmanade/react-component-errors) I just threw together to help diagnose/detect errors. But it may also help in this scenario.

Thoughts?

**Comment by jimfb** [comment] 2015-12-06 04:48
I'm going to close this out as a duplicate of #2461; let's keep the discussion in that thread.

**Closed by jimfb** 2015-12-06 04:48 UTC
