### ISSUE TITLE
Need a test for setState in shallow render

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#4019] opened 2015-06-03 16:35 UTC
Related to #2393 

Rendering a component like this:

``` jsx
<div onClick={() => this.setState({something: 1}) />
```

rendering via shallow render, then calling handler

``` js
var result = shallowRenderer.getRenderOutput();
result.props.onClick()
```

Produces the following:

```
    ReferenceError: document is not defined
      at getActiveElement (myapp/node_modules/react/lib/getActiveElement.js:23:12)
      at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (myapp/node_modules/react/lib/ReactInputSelection.js:40:23)
      at ReactReconcileTransaction.Mixin.initializeAll (myapp/node_modules/react/lib/Transaction.js:168:30)
      at ReactReconcileTransaction.Mixin.perform (myapp/node_modules/react/lib/Transaction.js:133:12)
      at ReactUpdatesFlushTransaction.Mixin.perform (myapp/node_modules/react/lib/Transaction.js:134:20)
      at ReactUpdatesFlushTransaction.assign.perform (myapp/node_modules/react/lib/ReactUpdates.js:95:38)
      at Object.flushBatchedUpdates (myapp/node_modules/react/lib/ReactUpdates.js:175:19)
      at Object.wrapper [as flushBatchedUpdates] (myapp/node_modules/react/lib/ReactPerf.js:70:21)
      at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (myapp/node_modules/react/lib/Transaction.js:207:25)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (myapp/node_modules/react/lib/Transaction.js:148:16)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (myapp/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
      at Object.enqueueUpdate (myapp/node_modules/react/lib/ReactUpdates.js:215:22)
      at enqueueUpdate (myapp/node_modules/react/lib/ReactUpdateQueue.js:30:18)
      at Object.ReactUpdateQueue.enqueueSetState (myapp/node_modules/react/lib/ReactUpdateQueue.js:208:5)
      at [object Object].ReactComponent.setState (myapp/node_modules/react/lib/ReactComponent.js:69:20)
      at Object.React.createElement.React.createElement.React.createElement.onChange (myapp/client/components/LoginForm.js:30:35)
```

Ideally, this module should realise it's running on the server, and skip this behaviour check

**Comment by jimfb** [comment] 2015-06-05 00:41
cc @graue

**Comment by gaearon** [comment] 2015-08-26 20:55
I think I don't have this problem in 0.14, can somebody else verify?

**Comment by spicyj** [comment] 2015-08-26 20:58
https://github.com/facebook/react/commit/40b7c19a890b04e5d7bd1273e4f90bb78769ae5b may have fixed this. Not sure it actually rerenders though?

**Comment by glenjamin** [comment] 2015-08-27 07:57
Just tried this on `0.14.0-beta3` - reproduces in the same way as 0.13.

```sh
> node -e 'console.log(process.versions)'
{ http_parser: '2.3',
  node: '0.12.7',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1p' }
```

```js
var React = require('react');
var TestUtils;
if (React.version.substring(4) == '0.13') {
  TestUtils = require('react/addons').addons.TestUtils;
} else {
  TestUtils = require('react-addons-test-utils');
}

if (process.env.document) {
  global.document = {};
}

var renderer = TestUtils.createRenderer();

var Node = React.createClass({
  getInitialState: function() {
    return { foo: 'bar' };
  },
  clicked: function() {
    this.setState({foo: 'baz'});
  },
  render: function() {
    return (
      React.createElement('div', {
        onClick: this.clicked
      }, this.state.foo)
    );
  }
});

renderer.render(
  React.createElement(Node)
);

renderer.getRenderOutput().props.onClick();

console.log(renderer.getRenderOutput().props.children);
```

0.13
```
> node sample.js
/myapp/node_modules/react/lib/getActiveElement.js:23
    return document.body;
           ^
ReferenceError: document is not defined
    at getActiveElement (/myapp/node_modules/react/lib/getActiveElement.js:23:12)
    at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/myapp/node_modules/react/lib/ReactInputSelection.js:40:23)
    at ReactReconcileTransaction.Mixin.initializeAll (/myapp/node_modules/react/lib/Transaction.js:168:30)
    at ReactReconcileTransaction.Mixin.perform (/myapp/node_modules/react/lib/Transaction.js:133:12)
    at ReactUpdatesFlushTransaction.Mixin.perform (/myapp/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (/myapp/node_modules/react/lib/ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (/myapp/node_modules/react/lib/ReactUpdates.js:175:19)
    at Object.wrapper [as flushBatchedUpdates] (/myapp/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/myapp/node_modules/react/lib/Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/myapp/node_modules/react/lib/Transaction.js:148:16)
```

0.13 with document hack
```
> document=1 node sample.js
baz
```

0.14.0-beta4
```
> node sample.js
/myapp/node_modules/react/node_modules/fbjs/lib/getActiveElement.js:25
    return document.body;
           ^
ReferenceError: document is not defined
    at getActiveElement (/myapp/node_modules/react/node_modules/fbjs/lib/getActiveElement.js:25:12)
    at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/myapp/node_modules/react/lib/ReactInputSelection.js:38:23)
    at ReactReconcileTransaction.Mixin.initializeAll (/myapp/node_modules/react/lib/Transaction.js:168:75)
    at ReactReconcileTransaction.Mixin.perform (/myapp/node_modules/react/lib/Transaction.js:135:12)
    at ReactUpdatesFlushTransaction.Mixin.perform (/myapp/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/myapp/node_modules/react/lib/ReactUpdates.js:86:38)
    at Object.flushBatchedUpdates (/myapp/node_modules/react/lib/ReactUpdates.js:147:19)
    at Object.wrapper [as flushBatchedUpdates] (/myapp/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/myapp/node_modules/react/lib/Transaction.js:202:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/myapp/node_modules/react/lib/Transaction.js:149:16)
```

0.14.0-beta3 with document hack
```
> document=1 node sample.js
baz
```

There's no git tags for the 0.14 series, but from a grep around it looks like that commit is present in beta3.

**Comment by sebmarkbage** [comment] 2015-09-14 17:52
@spicyj Should we have a custom transaction for shallow rendering?

**Comment by spicyj** [comment] 2015-10-07 19:37
Yeah maybe.

**Comment by glenjamin** [comment] 2015-10-27 09:29
For reference for future readers of this bug, the simplest current workaround I'm aware of is to do something like https://github.com/chantastic/react-media-object/commit/336112628be14b6fc6c50a10f7630110327dd108

Basically, create a global document object to silence the warning before any tests are run.

```js
global.document = {}
```

**Comment by robertknight** [comment] 2016-01-17 18:39
`getActiveElement` was changed a couple of weeks ago to allow a null document - https://github.com/facebook/fbjs/commit/2364a846f1c429eedf48edcdb34fd7fd11dd2978 . If there is nothing else in `setState` that assumes the presence of a DOM, this might be fixed.

**Comment by graue** [comment] 2016-01-18 09:10
Good call, @robertknight. Looks like this was fixed in 0.14.0 (not RCs), broken in 0.14.4 (the fix was accidentally reverted upstream in fbjs), and fixed again in 0.14.6. I just tried @glenjamin's example with 0.14.6 and it's working (prints baz).

**Comment by robertknight** [comment] 2016-01-18 11:08
@graue - I don't think we should close this until there is a regression test for it. I might be able to have a look at that.

**Comment by spicyj** [comment] 2016-01-19 00:27
Yeah, let's at least have a test.

**Comment by Rybadour** [comment] 2017-03-10 18:59
FYI: I found this issue while investigating why I was getting warnings about setState even though shallow rendering was working perfectly fine. Could you look into removing the warnings about using setState during shallow rendering.

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.`

Thanks!

**Comment by stefman1** [comment] 2017-03-21 17:16
this decided to happen for me today. not fun :( .... even though worked fine till now
    ` ReferenceError: document is not defined
      at getActiveElement (node_modules/fbjs/lib/getActiveElement.js:27:16)`

**Comment by sebmarkbage** [comment] 2017-03-21 21:36
@stefman1 That was a bug in a fbjs release. You can update to the new version. https://twitter.com/intelligibabble/status/844238291335458816

**Comment by gaearon** [comment] 2018-01-02 13:26
We have a bunch of tests using `setState` with shallow renderer now. Also the new shallow renderer doesn't use `getActiveElement()` anyway.

**Closed by gaearon** 2018-01-02 13:26 UTC
Labels: Component: Shallow Renderer
