### ISSUE TITLE
Error: "Children cannot be added or removed during a reorder operation."

### ISSUE THREAD

**Issue by AnthonyJRay** [facebook/react#21468] opened 2021-05-08 06:43 UTC
### Which website or app were you using when the bug happened?
Working in a React application in VSCode on Local Host.

### What were you doing on the website or app when the bug happened?
Adding functionality to an icon on a card to display or hide it through a click event in React changing a state property with setState.

```js
class Contact extends Component {
  state = {
    showContactInfo: true,
  };

  render() {
    const { name, email, phone } = this.props.contact;
    const { showContactInfo } = this.state;

    return (
      <div className="card card-body mb-3">
        <h4>
          {name}
          <FontAwesomeIcon
            icon={faSortDown}
            onClick={() =>
              this.setState({ showContactInfo: !this.state.showContactInfo })
            }
          />
        </h4>
        {showContactInfo ? (
          <ul className="list-group">
            <li className="list-group-item">{email}</li>
            <li className="list-group-item">{phone}</li>
          </ul>
        ) : null}
      </div>
    );
  }
}
```

### Generated information

DevTools version: 4.13.1-93782cfed2

Call stack:
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21622:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19607:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19767:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37788:39)

Component stack:
(none)

GitHub URL search query:
https://api.github.com/search/issues?q=Children%20cannot%20be%20added%20or%20removed%20during%20a%20reorder%20operation.%20in%3Atitle%20is%3Aissue%20is%3Aopen%20is%3Apublic%20label%3A%22Component%3A%20Developer%20Tools%22%20repo%3Afacebook%2Freact

**Edited** by @bvaughn to fix formatting

**Comment by bvaughn** [comment] 2021-05-08 14:27
Hey @AnthonyJRay, any chance you can reproduce this bug? (Or did it only happen once?) If you _can_ reproduce it, can you share a little more info on how? I don't think the code you've shared above is enough for us to see the bug happening (so that we can fix it)

**Comment by sulenchy** [comment] 2021-05-11 16:16
@AnthonyJRay  I had this same error earlier this morning and I was able to resolve it by adding a unique key to the element wrapping the items.

So it looks like you have many of the cards displaying that react was unable to distinguish.  Hope this helps.

**Comment by bvaughn** [comment] 2021-05-11 16:25
@sulenchy Can you share a repro of your project _before_ you made that change? Still looking for a way to reproduce this bug.

**Comment by bvaughn** [comment] 2021-05-20 02:18
Closing this issue since there's still no repro.

**Closed by bvaughn** 2021-05-20 02:18 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug

**Comment by ayronman99** [comment] 2022-06-13 14:49
> @AnthonyJRay I had this same error earlier this morning and I was able to resolve it by adding a unique key to the element wrapping the items.
> 
> So it looks like you have many of the cards displaying that react was unable to distinguish. Hope this helps?

In my case I added the index to the key worked like a charm
