### ISSUE TITLE
Bug: Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by enkuush-ca** [facebook/react#18192] opened 2020-03-01 18:34 UTC
This error happens in devtools (when running devtools shell), I didn't investigate it in detail, but seemingly the reason is that inside InteractionListItem.js we are trying to access commitData[commitIndex].duration however in some cases commitData is an array one index smaller than commitIndex.

**Comment by mayankagarwal44442** [comment] 2020-03-01 19:13
I'd like to work on this issue.

**Comment by mayankagarwal44442** [comment] 2020-03-01 19:20
PS: I am a new contributor here, so I'll do more research and get to specifics of a possible solution in a day or two if that's alright

**Comment by mayankagarwal44442** [comment] 2020-03-03 06:57
Due to some problems, I will not be able to follow up on the issue. But the fix is as described by description, not difficult. For more information, you can contact me at mayankagarwal44442@gmail.com

**Comment by bvaughn** [comment] 2020-03-03 17:23
Can you provide some more information on how you're reproducing this?

**Comment by kaykdm** [comment] 2020-03-11 06:54
I think duplicate of #18044

**Comment by bvaughn** [comment] 2020-03-11 16:03
Closing due to lack of response from OP and because it also seems to be a duplicate.

**Closed by bvaughn** 2020-03-11 16:03 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
