### ISSUE TITLE
Default bolean prop named "show or visible"

### ISSUE THREAD

**Issue by ShafiqueMalik** [facebook/react#24518] opened 2022-05-08 12:12 UTC
Hi reactjs Team, I suggest that, team should add a new prop for every component that purly used to show or hide component conditionally.
i.e
Instead of writing code like this in JSX.
{show && <Component/>}
we simply use like this <Component show={true}/> and that's it.

**Comment by eps1lon** [comment] 2022-05-17 17:48
Duplicate of https://github.com/facebook/react/issues/4373. See https://github.com/facebook/react/issues/4373#issuecomment-133485039 for why this is closed.

**Closed by eps1lon** 2022-05-17 17:48 UTC
Labels: Type: Enhancement, Status: Unconfirmed
