### ISSUE TITLE
How to call function from a function

### ISSUE THREAD

**Issue by gopalkhasria** [facebook/react#16349] opened 2019-08-10 14:52 UTC
I am trying to build an website for upload and download music with firebase. The propblem is i am getting the error Typerror: Cannot read "uploadMusic", where upload music is my function that i am calling after image_upload. I also use bind() in cinstructor but still getting sam issue
This is my code
```jsx
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      //.....
    };
    this.upload_image = this.upload_image.bind(this);
    this.uploadMusic = this.uploadMusic.bind(this);
    this.savingAll = this.savingAll.bind(this);
  }
  componentDidMount() {
    var firebaseConfig = {
    };
    if (!firebase.apps.length) {
      firebase.initializeApp(firebaseConfig);
    }
  }
  //code for handle changes
  upload = () => {
    if (
      this.state.music !== "" &&
      this.state.singer.length &&
      this.state.album.length &&
      this.state.name.length &&
      this.state.lyrics.length &&
      this.state.category.length
    ) {
      if (this.state.img !== "") {
        this.upload_image();
      } else {
        var url = "somethig";
        this.uploadMusic(url);
      }
    } else {
      alert("fill all the fields");
    }
  };
  upload_image = () => {
    console.log("Uploading image");
    var img = this.state.img;
    var img_url;
    var ref = firebase
      .storage()
      .ref()
      .child("img/" + this.state.name);
    ref.put(img).then(function(snapshot) {
      ref.getDownloadURL().then(function(url) {
        img_url = url;
        this.uploadMusic(img_url);//cannot start this function
      });
    });
  };
  uploadMusic = img_url => {
    console.log("Uploading Music");
    var music_url;
    var ref = firebase
      .storage()
      .ref()
      .child("music/" + this.state.name);
    ref.put(this.state.music).then(function(snapshot) {
      ref.getDownloadURL().then(function(url) {
        music_url = url;
        this.savingAll(img_url, music_url);
      });
    });
  };
  savingAll = (img_url, music_url) => {
    console.log("Saving all");
    var name = this.state.name;
    var singer = this.state.singer;
    var category = this.state.category;
    var album = this.state.album;
    var lyrics = this.state.lyrics;
    var db = firebase.firestore();
    let data = {
      name,
      singer,
      category,
      album,
      lyrics,
      icon: img_url,
      music_url: music_url
    };
    db.collection("tracks")
      .doc(name)
      .set(data);
    if (this.state.new_singer) {
      console.log("Adding singer");
      db.collection("singers")
        .doc("singer")
        .set({ name: singer });
    }
    console.log("All finish");
  };
```
What can i do i have the same issue when i try to read state sometimes

**Comment by MarkMurphy** [comment] 2019-08-10 16:17
Hi @gopalkhasria,

This is the sort of question that's more appropriate for something like StackOverflow because it's just a generic question regarding javascript. 

The problem is with the function you passed to `then`:

```js
ref.getDownloadURL().then(function(url) {
  img_url = url;
  this.uploadMusic(img_url);
});
``` 

It's not an arrow function or bound to the current scope using bind so it's changing the value of `this`.

You should read this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this 

Because you're using arrow functions already for your class methods, you don't need to bind them in the constructor, you can remove those lines.

So one option is to do this:

```js
ref.getDownloadURL().then((url) => {
  img_url = url;
  this.uploadMusic(img_url);
});
``` 

I'm not sure you're actually doing anything with `img_url` after assigning it there so you could potentially simplify it even further:

```js
ref.getDownloadURL().then(this.uploadMusic);
``` 

or if you use async/await:

```js
const downloadUrl = await ref.getDownloadURL()
this.uploadMusic(downloadUrl);
```

**Closed** 2019-08-10 16:17 UTC
