### ISSUE TITLE
Component rendering null always triggers a DOM update

### ISSUE THREAD

**Issue by leoasis** [facebook/react#3713] opened 2015-04-21 21:13 UTC
You can see the behavior in this fiddle: https://jsfiddle.net/leoasis/0psmxd3t/2/

Basically the thing is that the `<noscript>` tag is always being updated in the DOM (check the Elements view with the Chrome inspector to see the elements updated). This doesn't happen if the component explicitly returns a `<noscript>` instead of `null`.

**Comment by jsfb** [comment] 2015-04-21 21:31
I think the only thing this affects is performance.

**Comment by zpao** [comment] 2015-04-24 06:15
Nice find! @chenglou added support for `null`, perhaps he wants to look into it ;)

**Comment by leoasis** [comment] 2015-04-27 13:26
I've been looking into it a little bit, perhaps I don't know what I'm talking about but the issue seems to be in the `ReactCompositeComponent`, in the `_updateRenderedComponent`, where in this case it gets a prevElement that is the empty element, and a nextElement that is null, and that is sent to `shouldUpdateReactComponent` which returns false if any of the elements is null, thus making the element to unmount and mount again. I'm not sure yet where the normalization to the emptyElement should happen though.

Anyway if I'm just saying really basic stuff, it's anyway fun to dig into React internals, learning how that works :D

**Comment by spicyj** [comment] 2015-04-30 07:09
Dupe of #2770, I think.

**Closed by spicyj** 2015-04-30 07:09 UTC
Labels: Component: Core, Type: Bug
