### ISSUE TITLE
React shouldn't bind wheel or touch events to the document. 

### ISSUE THREAD

**Issue by joshduck** [facebook/react#1254] opened 2014-03-12 22:41 UTC
React binds touchmove, touchstart, touchend, touchcancel and wheel handlers to the document. When the user tries to scroll the browser needs to execute these event handlers to ensure event.preventDefault() was not called. This means scrolling will stall while JavaScript is executing.

Chrome has a fast-path that checks whether the coordinate where the touch event happens has touch listeners (https://plus.google.com/+RickByers/posts/cmzrtyBYPQc). If there are no listeners Chrome can allow the scroll to happen even if the main thread is blocked on JavaScript. 

We should bind our listeners for these events directly to the node which requires it. That event handler can then dispatch the event to the standard React top level event system. Then it will bubble/capture just like everything else and be visible to all event plugins.

**Comment by u9520107** [comment] 2015-08-05 02:11
Is this still being investigated?
In my project, I have a component that uses scrollable div's with roughly 300 direct child, which nests maybe 6 to 7 children. While putting translateZ(0) to force composition layer seems to be able to boost scroll performance to 60 fps. As soon as the document wheel event is attached, the performance is crippled. Even after the component that relies on wheel events is dismounted, the wheel listener on document would live on, reducing the scroll performance to around 30-40 fps.

**Comment by nolanlawson** [comment] 2016-09-01 16:37
This problem was [also noticed](https://twitter.com/JustRogDigiTec/status/768874533579137025) by former Edge/IE engineer Justin Rogers, who now works with y'all at Facebook. :smiley: React's technique of adding a global `wheel` listener on the `document` defeats optimizations that certain browsers (notably Safari and Edge) have implemented to avoid jank that only needs to occur for inner elements, not for the entire document.

Note that this optimization only applies to certain kinds of scroll events like mousewheel scrolling, not necessarily two-finger touchpad scrolling, clicking-and-dragging the scrollbar, or keyboard-scrolling. So you may need to use a real mouse to reproduce.

To demonstrate, I put together [a little sample application](https://github.com/nolanlawson/react-wheel-jank-demo) based on `create-react-app`. There's a `setInterval()` in there that janks the main thread for 1000 milliseconds every 2000 milliseconds. This is to simulate a very active page with lots of JS.

There are three versions of the app: 1) no `wheel` events, 2) a React `onWheel` event on the inner scrollable div (which adds a global `wheel` event to the document), and 3) a regular DOM `wheel` event on the inner scrollable div. In all cases, the event itself is just `lodash.noop`.

In Firefox and Chrome, there is no difference between (2) and (3). However, in Edge and Safari, React's technique of adding the global `wheel` listener has the unfortunate side-effect of causing the entire page to jank while scrolling,  rather than just when you're scrolling the inner div.

In theory this kind of optimization also applies to `scroll`, `touchstart`, `touchmove`, etc. events, but I only tested `wheel`, since the others have their own performance characteristics and may only apply to touchscreen devices. It's worth investigating, but for this demo I focused on `wheel`.

It's kind of a subtle issue, so I also made a quick video demonstration: https://youtu.be/6Ckepx3wPPE

**Comment by nolanlawson** [comment] 2016-09-01 18:45
Update: added `onTouchStart`/`touchstart` to the demo as well, and confirmed that this causes unnecessary janky touch-scrolling in all mobile browsers (iOS Safari, Android Chrome, Android Firefox, Edge Mobile).

**Comment by gaearon** [comment] 2016-09-01 19:18
We just published [an code dive into React event system](https://www.youtube.com/watch?v=dRo_egw7tBc&feature=youtu.be) (thanks @spicyj and @kentcdodds!)
This would be helpful to anyone who’d like to dig into this.

**Comment by nhunzaker** [comment] 2017-03-26 16:43
Just read [this article](https://blogs.windows.com/msedgedev/2017/03/08/scrolling-on-the-web) and found my way here. I've got some bandwidth now that the [number input issue](https://github.com/facebook/react/pull/7359) is more or less wrapped up. 

Is anyone working on this? Anything I should keep in mind before I get started?

**Comment by nhunzaker** [comment] 2017-03-28 12:05
Working on a fix here:
https://github.com/facebook/react/compare/master...nhunzaker:nh-scroll-fix

This change allows ReactBrowserEventEmitter, which is responsible for attaching event listeners, to make the decision on a case-by-case basis as to what events should be attached to the document vs the element itself.

I still haven't gotten into touch events or serious wheel testing, but I can confirm that it gets rid of the window scroll jank in @nolanlawson [v2 example](https://github.com/nolanlawson/react-wheel-jank-demo)

Time to find a mouse with a wheel!

**Comment by sebmarkbage** [comment] 2017-03-29 23:11
@nhunzaker We should chat about this strategy. There are several considerations here.

1) We want to minimize the amount of work we do during initial render which includes minimizing the checks we do on events. Currently we do way too much work just to figure out that we've already attached an event.

2) We noticed in https://github.com/facebook/react/pull/8117 that moving event listeners locally had many unexpected consequences on other parts of the system so it was harder than it initially seemed. E.g. it can break how the select event plugin works. We need to make sure that all that stuff plays nicely together.

**Comment by nhunzaker** [comment] 2017-03-29 23:31
Absolutely. Is reactiflux, the discord room, best? Really any medium is fine.

Re 1: Are there any known bottlenecks that you could point me to?

Re 2: Totally, and hard to test. It would be good to get some DOM fixtures in place as we uncover issues. That was going to be my next step here.

**Comment by sebmarkbage** [comment] 2017-03-30 00:19
Probably best to start here. I just wanted to highlight those issue so you're aware.

1) ensureListeningTo and [these steps in ReactBrowserEventEmitter](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactBrowserEventEmitter.js#L231-L241) are currently executed for every event listener in the entire page. That's several slowish DOM operations, map lookups, hasOwnProperties and property look ups for every listener before we can show the first screen. In theory, if we attached listeners to every event at the document eagerly, we wouldn't have to do any of that for any event listener.

2) I think wheel specifically is probably pretty safe but I believe at least one platform it might be possible to change the value in a `<select />` with the wheel which might or might not be related.

**Comment by nhunzaker** [comment] 2017-03-31 11:45
@sebmarkbage I recently had a few PRs merged that removing some of the work in BrowserEventEmitter doing support checks we don't need. Next I'm going to see what kind of savings we actually get by just assigning an event listener for every supported event. 

Without changing things too much, I want to figure out what's slow, eliminate that work, then evaluate reworking ReactBrowserEventEmitter with less moving parts (and I better understand what's happening). 

I'm also curious if we can reduce the number of calls to `ensureListeningTo` for special cases in [ReactDomComponent](https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/ReactDOMComponent.js#L136-L147)

Is that a reasonable approach?

**Comment by nolanlawson** [comment] 2017-04-01 15:24
Restricting the set of "prefer local listeners" to `wheel`, `touchstart`, and `touchmove` is probably a good start. All of those events can block scrolling in Edge/Safari/etc. but only if done globally.

FWIW, in case you don't want to go to the trouble of buying a mouse with a wheel, I've found that two-fingered scrolling on a touchpad usually exhibits identical behavior.

**Comment by nhunzaker** [comment] 2017-04-03 11:25
@nolanlawson Thank you for the guidance! I have a mouse with a wheel (thank goodness for conference swag), but I wasn't sure about two-fingered scrolling, that's really good to know.

@sebmarkbage The only hiccup I'm hitting now is that to-string rendering (at least running tests against the feature flag: `useCreateElement: false` throws an error because the node to attach the listener for doesn't exist yet.

`ensureListeningTo`, which runs to make sure a top-level event listener is attached to the document, looks something like this:

```
function ensureListeningTo(inst, registrationName, transaction) {
  if (transaction instanceof ReactServerRenderingTransaction) {
    return;
  }

  listenTo(registrationName, getDocument(inst), getNode(inst));
}
```

The problem is that `getNode(inst)` fails some times when the `useCreateElement` feature flag is set to false. You see this warning:

```
Invariant Violation: React DOM tree root should always have a node reference.
```

**So I had a few questions/ideas:**

1. Is setting `useCreateElement: false` still the best way to test server-side rendering?
2. What about doing enqueuing event listener attachment post mount, like:

```javascript
transaction.getReactMountReady().enqueue(attachListeners, this);
```

If we did this, what do you think about moving all of the local listener logic out of `ReactDOMComponent` and into `ReactBrowserEventEmitter`? For example, this section here:

https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/ReactDOMComponent.js#L254-L310

Then, possibly, we could eliminate the unmount work here:

https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/ReactDOMComponent.js#L1107-L1159

**Comment by sebmarkbage** [comment] 2017-04-03 15:57
`useCreateElement: false` is what happens when you render into a server rendered tree on the client. We're in need of imminently rewriting that whole algorithm and likely need to switch strategies for Fiber anyway.

**Comment by nhunzaker** [comment] 2017-04-04 13:36
I took another pass:
https://github.com/facebook/react/compare/master...nhunzaker:nh-scroll-fix

This diff further moves event listener location handling to BrowserEventEmitter. Here's how it works:

1. `createElement:false` runs a post-mount hook to attach all listeners
2. `_updateDOMProperties` runs `BrowserEventEmitter.listenTo(eventName, document, element)`, more or less like normal.
3. `BrowserEventEmitter.listenTo` is responsible for figuring out if a listener should be attached locally or globally.

No fiber tests fail! But we probably have a few more tests to write.

What _does_ fail is `createElement:false` in the stack renderer: **Because attaching event listeners to invalid nested markup means ReactDOMComponentTree can't find them.**

For example:

```html
<div>
  <tr></tr>
  <tr></tr>
</div>
```

When `ReactDOMComponentTree` goes to precache the nodes, the `<tr>` tags can't be found in the div, they seem to get stripped out. This causes the following validation error:

https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDOMComponentTree.js#L115

```
ReactDOMComponent › nesting validation › warns nicely for table rows
Invariant Violation: Unable to find element with ID 2.
```

So I'm looking for a good check to run to see if the node associated with a ReactDOMComponent instance is actually mountable. This is further complicated by the `<source>` tag inside a `<video>` element. Most of my attempts either fail this test:

https://github.com/facebook/react/blob/master/src/renderers/dom/shared/__tests__/ReactDOMComponent-test.js#L759-L779

Or this family of tests:
https://github.com/facebook/react/blob/master/src/renderers/dom/shared/__tests__/ReactDOMComponent-test.js#L1263-L1277

**Or**

Do we even need to do listener attachment if `createElement` is set to `false`?

**Comment by gaearon** [comment] 2017-04-04 13:43
>Do we even need to do listener attachment if createElement is set to false?

No, `createElement: false` is only used for validating server markup on the client. Its result is thrown away.

**Comment by nhunzaker** [comment] 2017-04-04 13:46
👍 . That solves my problem then

**Comment by nhunzaker** [comment] 2017-04-04 23:56
Okay. [PR soon](https://github.com/facebook/react/compare/master...nhunzaker:nh-scroll-fix?expand=1). here's a test page:
http://nh-react-scroll-fix.surge.sh

Associated code:
https://github.com/nhunzaker/react-wheel-jank-demo

(Thanks @nolanlawson!)

I believe this fixes the issues with wheel, touchstart, and touchmove events. But I need to test touchstart and touchmove on Edge. That's outside of my capabilities. Is this something someone else could take up?

Beyond that, generally, would others be able to help verify?

**Comment by spicyj** [comment] 2017-04-05 00:04
> No, createElement: false is only used for validating server markup on the client. Its result is thrown away.

Wait, I don't think that's true. We use it only when rendering on top of server markup, but when called on the client it does need to attach event handlers! Like Seb said though, server rendering attaching code needs to get rewritten soon for Fiber so we're not sure what will happen.

**Comment by nhunzaker** [comment] 2017-04-05 00:07
@spicyj Well shoot... okay. Any ideas? What is the best way to handle invalidly nested tags that never get created, but React is still tracking?

Would this discussion be better in here? https://github.com/facebook/react/pull/9333 Or do you want me to close that out and keep talking here?

**Comment by spicyj** [comment] 2017-04-05 05:10
Sorry, I haven't been following this whole thread – I just saw the one comment and it seemed wrong. In the div > tr example, why are we doing anything with event listeners? I must be missing something because I would have assumed we skip all the events code for that test.

We do have a public Messenger room at https://m.me/g/Abas8IcWxIvjVxHN which you're welcome to participate in. I'm usually responsive in close to real time and happy to answer questions.

**Comment by nhunzaker** [comment] 2017-04-05 10:56
Perfect, I'll hop in.

**Comment by gaearon** [comment] 2017-04-05 11:43
>We use it only when rendering on top of server markup, but when called on the client it does need to attach event handlers!

Oops, you’re right, thanks for correcting me! Still learning 😄 Sorry @nhunzaker for confusing you.

**Comment by Nandez89** [comment] 2019-03-21 23:08
This might be related to https://github.com/facebook/react/issues/14856 or become more important since that chrome change.

**Comment by gaearon** [comment] 2020-07-24 19:33
This has been implemented and will go out in React 17.

**Closed by gaearon** 2020-07-24 19:33 UTC
Labels: Component: DOM, Resolution: Backlog, Type: Enhancement
