### ISSUE TITLE
TestUtil's onMouseEnter and onMouseLeave do not work

### ISSUE THREAD

**Issue by lkkadiri** [facebook/react#4264] opened 2015-07-01 17:37 UTC
I was trying to use the TestUtils onMouseEnter and onMouseLeave events, like,

```  
it('should trigger mouse events', () => {
        let renderedButton = TestUtils.renderIntoDocument(<someButton/>);
        TestUtils.Simulate.mouseEnter(renderedButton.getDOMNode());
        TestUtils.Simulate.mouseLeave(renderedButton.getDOMNode());
});
```
I had no luck with either of the Simulates' mouse events.
However, i found on stackoverflow a workaround to use this,

     it('should trigger mouse events', () => {
        let renderedButton = TestUtils.renderIntoDocument(<someButton/>);
        TestUtils.SimulateNative.mouseOver(renderedButton.getDOMNode());
        TestUtils.SimulateNative.mouseOut(renderedButton.getDOMNode());
    });

and this works for now and i also haven't noticed an open issue about this, hence opening one here.  Is there already a fix for it or should I keep using this workaround? I just feel iffy about using SimulateNatives events as opposed to Simulate which works for most of the other click events we have in our app.

**Comment by spicyj** [comment] 2015-07-04 17:39
Dupe of #1297. mouseEnter/mouseLeave should work in the 0.14 beta and in 0.14 when it comes out.

**Closed by spicyj** 2015-07-04 17:40 UTC
