### ISSUE TITLE
componentWillMount with .getDOMNode() that isn't in document yet

### ISSUE THREAD

**Issue by Gozala** [facebook/react#2784] opened 2014-12-29 18:21 UTC
Currently there is no hook that would allow us to set attributes on the node before it's injected into a document. Which is unfortunate as there are some attributes in the wild that take effect only before element is injected into a document.

To workaround this I'm forced to replacing react injected nodes with clones on `componentDidMount`
https://github.com/Gozala/firefox.html/blob/react/js/element.js#L57-L61

It would be great if react could expose node that will be inserted during `componentWillMount` or added another hook where node will be provided.

**Comment by jsfb** [comment] 2015-01-03 00:00
Which attributes need to be set before element injection in order to take effect?

Also, is the underlying issue that React doesn't let you set unknown/unrecognized attributes?  If so, perhaps this is a duplicate of https://github.com/facebook/react/issues/2746

**Comment by spicyj** [comment] 2015-02-27 00:36
Closing due to inactivity, but we can discuss more if you still have an issue.

**Closed by spicyj** 2015-02-27 00:36 UTC
