### ISSUE TITLE
Like @hugo , I encountered this when testing [a new Ionic application](https://ionicframework.com/docs/react):

### ISSUE THREAD

**Issue by AlbertGaocong** [facebook/react#19057] opened 2020-06-01 12:24 UTC
When i implementer slidemenu, i also encountered this problem

**Comment by bvaughn** [comment] 2020-06-02 15:29
It doesn't look like this bug report has enough info for one of us to reproduce it (or even understand what's being reported).

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-06-02 15:44
I'm going to close this issue for now because it's not actionable. Provide some more info and we can re-open it! :)

**Closed by bvaughn** 2020-06-02 15:44 UTC
Labels: Resolution: Needs More Information
