### ISSUE TITLE
Development flavor is way bigger than the production one

### ISSUE THREAD

**Issue by ericmorand** [facebook/react#20177] opened 2020-11-06 10:18 UTC
Using latest React release, the development flavor is way bigger than the production one:

* react (cjs): **72KB** vs **6.5KB**
* react-dom (cjs): **895KB** vs **121KB**

It makes bundling the development flavor way slower than bundling the production one, which is the exact opposite of what developer needs: developers need the lowest possible build time when developing, and they don't care if the production build is slower.

Replacing the development flavor with the production one leads to at least twice faster building time when developing the application. With no drawbacks at all since we still have access to the React DevTools.

I think that the production flavor should be the default one declared by package.json and that the development one should be left optional for people that needs the benefits it brings - which at that point are not clear to me.

**Comment by gaearon** [comment] 2020-11-06 13:32
What bundler are you using and what practical speed difference are you seeing?

There are very important differences — the development build includes many warnings that point out critical bugs but wouldn’t be displayed for a production build.

We could certainly do something like strip out the comments but it would impede the rare cases when people want to debug the source code.

**Comment by ericmorand** [comment] 2020-11-06 14:01
Using Browserify, with a very simple React application consisting of a single Button component, bundling takes an average of 2000ms with the development flavor versus an average of 500ms with the production flavor.

Granted, Browserify is not the most powerful bundler available but the difference remains. It makes sense to me: reading and parsing a a 970KB set of source data (react + react-dom development flavor) and writing back into a bundle takes much more resources than doing the same thing from a 130KB one (react + react-dom production falvor).

Fortunately, it is very easy to force a bundler to use the production flavor instead of a development one.

**Comment by bvaughn** [comment] 2020-11-06 19:13
> Replacing the development flavor with the production one leads to at least twice faster building time when developing the application. With no drawbacks at all since we still have access to the React DevTools.

This isn't really correct. The development build is significantly larger in part because it has not been mangled and minified (so it's easier to debug and step through an error stack) but also (and even more importantly) because we have a lot of DEV-only validations and warnings to help identify and fix problems before they make it to production.

**Comment by ericmorand** [comment] 2020-11-06 20:09
It is debatable that providing an easy way to debug react sources is legitimate. But would you want to provide such a thing then a source map would be the way to go. If consumers have to debug the react sources themselves when using the public API then something more profound is flawed and _that_ should be taken care of.

Anyway, I'm not saying that React should not come with a development flavor. I believe that the producion

**Comment by bvaughn** [comment] 2020-11-06 21:11
> and the development one should be triggered with an environment variable set to "DEV" or something.

That's exactly what's already happening :smile: If `NODE_ENV` is anything other than "production" then the development build of React is loaded.

```js
if (process.env.NODE_ENV === 'production') {

// DCE check should happen before ReactDOM bundle executes so that
// DevTools can report bad minification during injection.
checkDCE();
  module.exports = require('./cjs/react-dom.production.min.js');
} else {
  module.exports = require('./cjs/react-dom.development.js');
}
```

**Comment by ericmorand** [comment] 2020-11-06 21:40
No it's not. The development one should be triggered with an environment variable set to "DEV". Not set to _nothing_

**Comment by bvaughn** [comment] 2020-11-06 21:47
That's you're opinion, which is okay, but it's not the ecosystem-wide convention.

**Comment by ericmorand** [comment] 2020-11-06 21:49
I don't get what you mean: what is not the ecosystem-wide convention?

**Comment by ericmorand** [comment] 2020-11-06 21:55
And to clarify my point: finding a bug that forces a developer to debug the React sources themselves is not a common expectation of developers. There is no reason that the default flavor of React assumes that things will go wrong except is the framework itself admits that it's flawed.

On the other hand, having the lowest possible build time is a common expectation of developers.

My point is that the current strategy sacrifices the experience of the developers in exchange for something that they rarely (if ever) need. I believe that the production build should be the default and that developers that want to debug the React sources should explicitly install and use the debug-oriented flavor when needed and only when needed.

**Comment by bvaughn** [comment] 2020-11-06 22:04
> I don't get what you mean: what is not the ecosystem-wide convention?

The convention I was referring to was specifying either "development" or "production" (or in some cases "test") as `NODE_ENV`. I think that convention has been around for 10 years or so, dating back to Express JS. At this point, it's pretty widely used by libraries and build tools.

I don't think it's likely that we're going to change this convention by having a conversation on GitHub :smile:  I'm just trying to share insight into why it is currently the way it is.

> And to clarify my point: finding a bug that forces to debug the React sources is not a common expectation of developers. There is no reason that the default flavor of React assumes that things will go wrong except if the framework itself admits that it's flawed.

I think that focusing on this point is misleading. It's not about debugging React. Although React, like all software, has flaws :smile:

When tracing through a call stack during development debugging, it's always a nicer experience to look at code that's as close to source as possible. Could source maps be used to achieve a similar result? Maybe. FWIW though, I don't think we hear many (any?) complaints about the size of React itself as being the cause of slowness during development builds. React itself is generally *small* compared to the size and amount of application code.

**Comment by bvaughn** [comment] 2020-11-07 16:50
> What bundler are you using and what practical speed difference are you seeing?

I was curious about this too, so I setup a simple test project (single React component) and tested Browserify myself.

![Screen Shot 2020-11-07 at 11 49 28 AM](https://user-images.githubusercontent.com/29597/98446961-5cbb8d80-20ef-11eb-8637-c1169492be49.png)

So for me at least, in the *worst case scenario* (where there's only one component and React is literally the majority of what Browserify is building), the development bundle adds an additional 24% to the build time (but this is only 0.14s). I imagine in a realistic app (where React is by far smaller than the application source code) that this would not even be noticeable.

Makes me wonder about the 2000ms vs 500ms difference mentioned above.

**Comment by ericmorand** [comment] 2020-11-07 20:15
Here are my results using this source file as entry point:

```js
const {Component, createElement} = require('react');
const {render} = require('react-dom');

class App extends Component {
    render() {
        return createElement('div');
    }
}

render(new App(), document.getElementById('app'));
```

* First, by using the default `node_modules/react/index.js` and `node_modules/react-dom/index.js`:

```bash
time npx browserify index.js -t > bundle.js

real    0m3,638s
user    0m4,171s
sys     0m0,489s
```

* Second, by using custom `node_modules/react/index.js` and `node_modules/react-dom/index.js` that only export the production modules:

```js
module.exports = require('./cjs/react.production.min.js');
```

```js
module.exports = require('./cjs/react-dom.production.min.js');
```

```bash
time npx browserify index.js -t > bundle.js

real    0m2,090s
user    0m2,382s
sys     0m0,213s
```

In the first case, both production and development sources are included in the final bundle. In the second case, only the minified production one is included in the bundle.

For exhaustivity sake, here is the result when using custom  `node_modules/react/index.js` and `node_modules/react-dom/index.js` that only export the development modules:

```js
module.exports = require('./cjs/react.development.js');
```

```js
module.exports = require('./cjs/react-dom.development.js');
```

We are back to the same magnitude than with both sources included:

```bash
time npx browserify index.js -t > bundle.js

real    0m3,554s
user    0m4,273s
sys     0m0,337s
```

Which means that most of the time spent at bundling comes from including the development source. It makes sense: it weights around 1MB versus 130KB for the production sources, so the impact of bundling the production sources is negligeable.

**Comment by bvaughn** [comment] 2020-11-07 22:36
> In the first case, both production and development sources are included in the final bundle. In the second case, only the minified production one is included in the bundle.

I'm confused. Why are you including both production and development versions in your bundle?

**Comment by ericmorand** [comment] 2020-11-07 23:30
> I'm confused. Why are you including both production and development versions in your bundle?

I'm not. Not expicitly at least.

The entry points of both react and react-dom _are_ including both versions:

```js
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

At run-time, one or the other will be used depending on the value of NODE_ENV variable - and it will probably won't be set so development flavor will be used. But both are included in the bundle. You have to use bundler plugins that detect dead code paths at bundling-time to get rid of them. Which you didn't do in your example: envify would only replace the environment variable with its value at bundle time, leading to the following code being bundled instead of the original:

```js
'use strict';

if ('development' === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

Which leads to both of the versions being bundled, whatever the value of NODE_ENV.

**Comment by bvaughn** [comment] 2020-11-08 14:30
Gotcha. I misunderstood what you were saying to imply that both bundles were being *used*.

**Comment by bvaughn** [comment] 2020-11-08 14:31
Gotcha. I misunderstood what you were saying to imply that both bundles were being *used*.

Anyway, again: can you share an actual repro that we can run ourselves?

**Comment by ericmorand** [comment] 2020-11-08 15:58
Here it is:

https://github.com/ericmorand/react-20177

**Comment by PupoSDC** [comment] 2020-11-10 13:08
I tried to run the builds from @ericmorand but only the first two scripts work. anyway, here are the results:

```
 ➜ time npx node reference.js
npx node reference.js  0.45s user 0.06s system 128% cpu 0.399 total

 ➜ time npx browserify src/index.js > bundle.js
npx browserify src/index.js > bundle.js  0.89s user 0.08s system 138% cpu 0.704 total
```

there is some added slowliness indeed, but it's a price worth paying for having the react sources to step trough while debugging 👍

**Comment by mvhk** [comment] 2021-01-24 04:27
I think, close this issue, since it has more debate rather than solving problem...

**Comment by gaearon** [comment] 2021-03-24 19:16
DEV build is the default because it contains warnings. People who need it the most (non-experts) are the ones that _wouldn't know_ to enable it if it was opt-in. That's why it's default.

Re: bundling speed, it sounds like we're discussing subsecond differences. Nothing prevents you from using an incremental bundler that should in principle be able to avoid whatever the cost is being spent here going through the ReactDOM file. It is intentionally pre-compiled so that it's a single bundle. You can also configure your Browserify setup to use the production bundle, or to use a UMD bundle that doesn't need to be rebuilt at all during development.

**Closed by gaearon** 2021-03-24 19:16 UTC
Labels: Status: Unconfirmed
