### ISSUE TITLE
Error "Electron failed to install correctly, please delete node_modules/electron and try installing again"

### ISSUE THREAD

**Issue by romaniv1024** [facebook/react#19977] opened 2020-10-07 20:12 UTC
When I try to start program using command
```sudo npx react-devtools```
I get error
```
/usr/local/lib/node_modules/react-devtools/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/react-devtools/node_modules/electron/index.js:14:11)
```
Even I install react-devtools localy by `sudo npm install -g react-devtools` and after start program by `sudo react-devtools`, get the same error. 

Any idea how to fix this?

---
Linux Mint 20 Cinnamon
react-devtools Version 4.8.2

**Comment by eps1lon** [comment] 2020-10-08 06:57
Duplicate of #19976

**Closed by eps1lon** 2020-10-08 06:57 UTC
