### ISSUE TITLE
Error: "Cannot read property 'isCollapsed' of undefined"

### ISSUE THREAD

**Issue by mageshkumar1598** [facebook/react#19410] opened 2020-07-20 05:50 UTC
Describe what you were doing when the bug occurred:
1. I was trying to inspect the state of the particular element. 
2. Scrolled the dev tool page up, then this error occurs.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.2-fed4ae024

Call stack: at Store.getElementAtIndex (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:19359:35)
    at Store.getElementIDAtIndex (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:19376:26)
    at chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:26594:18
    at List.render (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:21229:18)
    at li (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:11802:76)
    at ki (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:11793:10)
    at ck (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:14433:86)
    at bk (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:13779:11)
    at ak (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:13768:5)
    at Sj (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:13750:7)

Component stack: at List (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:20924:30)
    at div
    at AutoSizer (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:2786:5)
    at div
    at div
    at Tree_Tree (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:26368:45)
    at div
    at div
    at InspectedElementContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:26848:23)
    at OwnersListContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:25520:23)
    at SettingsModalContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:26139:23)
    at Components_Components (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:30926:50)
    at ErrorBoundary (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:27172:5)
    at PortaledContent (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:27303:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:30463:23)
    at TreeContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:22538:23)
    at SettingsContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:23040:27)
    at ModalDialogContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:28328:23)
    at DevTools_DevTools (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:33797:21)

**Comment by MaximeMazet** [comment] 2020-07-20 06:04
Hello
You can post your code please ;)

**Comment by bvaughn** [comment] 2020-07-20 12:20
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-07-23 01:48
Going to close this issue because it doesn’t contain any repro info, happy to reopen if there’s more information.

**Closed by bvaughn** 2020-07-23 01:48 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
