### ISSUE TITLE
useEffect, componentWillReceiveProps usage

### ISSUE THREAD

**Issue by ahmetcaglayan** [facebook/react#17571] opened 2019-12-11 06:39 UTC
my script;

When my goal is to change the line,
Clear the selection and update the state lines.
![41617FEA-D822-4C74-B422-A06B10DF20A8](https://user-images.githubusercontent.com/13018803/70597482-888d7500-1bf9-11ea-8860-c4f9396e63e8.jpeg)

Since it enters the console.log (a) at first boot, I need to clear the selection.

**(First Render Console)**
![1645F842-A81A-40B6-AF1F-8FECF9F3C6EE](https://user-images.githubusercontent.com/13018803/70597565-b672b980-1bf9-11ea-8395-64197c21b138.jpeg)

but when I update props.rows,
both lines should be updated, as well as clear the selection.

**(Set Props Render Console)**
![6F215AF6-8E86-4789-B403-8E95FF149D43](https://user-images.githubusercontent.com/13018803/70597621-d73b0f00-1bf9-11ea-9ec7-52384fdd567e.jpeg)

but when I do with callback, the current props.rows are not coming. When the first opening works on.

will not work on first boot. It will only work on line changes. it also needs to arrive up to date line information.

callback does not show the current line information :(

how do i do it like componentWillReceiveProps?

@gaearon 
Why does useEffect work on first boot even though props.rows is connected and props.rows is unchanged? Shouldn't it expect props.rows to change?

**Comment by ahmetcaglayan** [comment] 2019-12-11 06:40
`useEffect(() => {
    console.warn("a", props.rows) // New props
    return (c) => {
      console.warn("b", props.rows) // Old props
      setSelectionState([]);
      setRows(generateRowsId(props.rows));
    };
  }, [props.rows]);`

**Comment by MrIrick** [comment] 2019-12-11 06:47
got the same problem!

i understood why the view update is async, but  why the setXXX also is async

**Comment by MrIrick** [comment] 2019-12-11 06:55
can anyone else can explain it? i just wanna the state can be update in time when i setXXX

**Comment by HowardTangHw** [comment] 2019-12-11 09:16
I think the following documents can help you
[Why am I seeing stale props or state inside my function?
](https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function)

**Comment by ahmetcaglayan** [comment] 2019-12-11 09:45
location has nothing to do with this.
I just want something similar to the componentWillReceiveProps property. As shown here, useEffect works on first boot. I have written a callback to work after the prop is updated. its does not come up to date prop. that is ridiculous.

**Comment by ahmetcaglayan** [comment] 2019-12-11 09:47
Why does useEffect work on first boot even though props.rows is connected and props.rows is unchanged? Shouldn't it expect props.rows to change?

**Comment by MrIrick** [comment] 2019-12-11 12:42
![image](https://user-images.githubusercontent.com/22052869/70621814-64f81800-1c55-11ea-94a3-00b3764838aa.png)

i am writing a common component Select, i think take all data state whthin the comp would be best.
when i  togg the props of options,then to udpate the opt!
but when i get the default value from opt , its still the previous options;
why the state update is async~

do not say i render the view with options directly. that will take some comp state out of the Select.
i dont thinks it's a constructive style.

any opine is appreciate!

**Comment by bvaughn** [comment] 2019-12-22 20:22
This issue does not provide enough context for us to be able to help. Pictures of parts of code are usually not enough for someone to be able to spot a problem. (The problem is often in the code that is *not* pictured, or the way the code fits together.) This is why we usually as for something like a Code Sandbox that reproduces the problem.

Looking at the way you're things like `props.grouping` to `grouping` state and calling `setGrouping` in an effect any time the props change- I think you should probably read this blog post:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

Although that blog post was written for class components, the general patter of syncing state and props can apply to hooks as well- and looks like it would apply here.

If you'd like us to take a closer look at why one of your props isn't updating as expected, please give us some code we can actually see all of (and run). I'm going to close this issue for now though because it's not really actionable.

Good luck!

**Closed by bvaughn** 2019-12-22 20:22 UTC
