### ISSUE TITLE
Click <button type="button"> will submit form

### ISSUE THREAD

**Issue by littlee** [facebook/react#10690] opened 2017-09-13 05:54 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
https://jsfiddle.net/4dLo3nm2/1/
Click "edit" will submit the form

**What is the expected behavior?**
Click "edit" should not submit the form

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Mac OS 10.12.6
Chrome 61.0.3163.79
React 15.6.1 (I tried 15.5.1 also has this issue)

**Comment by suhaotian** [comment] 2017-09-13 06:21
It's browser's feature.. not react's bug..

**Comment by stsiushkevich** [comment] 2017-09-13 08:52
Yes... Need to close this issue

**Comment by littlee** [comment] 2017-09-13 09:52
![image](https://user-images.githubusercontent.com/7534668/30371145-3ec4fb40-983f-11e7-9a00-b299255184bf.png)

Please notice that edit button has type="button" attribute

**Comment by syranide** [comment] 2017-09-13 10:06
That is very weird, the attribute is there and doing the same without React behaves correctly (even setting the type late via attribute/property). I have no idea why this would be happening.

https://jsfiddle.net/k40r1kgL/

**Comment by syranide** [comment] 2017-09-13 10:07
Oh wait I see, the problem is that you are replacing it with a button that does NOT have the type. Essentially, the type is checked after the event is dispatched, not before. So you end up removing the type and thus submitting the form.

**Comment by syranide** [comment] 2017-09-13 10:10
Actually, this is the better way of doing it: https://jsfiddle.net/6k1c74tn/

**Closed** 2017-09-13 12:49 UTC

**Comment by GlynL** [comment] 2019-05-16 00:14
@syranide So the click event is dispatched and this changes the button type attribute. And after this, the form is checking the button type?

**Comment by littlee** [comment] 2019-05-16 11:15
After using react for those years, I thinks add `key` attribute for button could be a way

**Comment by syranide** [comment] 2019-05-17 19:03
@littlee You are entirely correct, `key` is the correct solution here. They are technically two different buttons and they should not "reconcile" to the same instance.
