### ISSUE TITLE
Audio <source> src attribute updates are not recognized

### ISSUE THREAD

**Issue by danbovey** [facebook/react#9447] opened 2017-04-17 19:42 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

Searched other issues but couldn't find anything discussing using `<source>` tags within `<audio>` tags. I think it's more of a browser problem than a React problem as it updates the DOM fine but I thought there should be a discussion on solutions/next steps.

**What is the current behavior?**

Source `src` example: https://jsfiddle.net/danbovey/km5c3zmq/
Audio `src` example: https://jsfiddle.net/danbovey/v40cbwpx/

The browser is not recognising any changes React makes to the `src` prop of `<source>`, if you change the `src` prop directly on the `<audio>` tag the browser re-renders/resets the audio tag as expected.

**What is the expected behavior?**

The source example should match the behaviour of the audio example. Happens in all browsers.

**Comment by aweary** [comment] 2017-04-17 20:40
Thanks for the report @danbovey! This appears to expected behavior. [This example](https://jsfiddle.net/198mcb0z/) shows that setting `src` on a `source` element does not update update it's parent media element. This is consistent in Firefox and Chrome.

We can look into ways around this. For now, you can use a `key` on the `audio` elements to force React to create new DOM elements, which seems to provide the behavior you're looking for https://jsfiddle.net/74oqdtd8/

**Comment by aweary** [comment] 2017-04-21 20:58
Yeah, I'll close this since it's apparently expected and there's an easy workaround.

**Closed by aweary** 2017-04-21 20:58 UTC

**Comment by ShahadatAnik** [comment] 2023-01-21 06:08
The visible problem has been [solved here.](https://stackoverflow.com/a/70336105/19040848) 

I have implemented this solution in [this reactJS app.](https://ilmiyah.netlify.app/Ayah)

> **Do you want to request a _feature_ or report a _bug_?**
> 
> bug
> 
> Searched other issues but couldn't find anything discussing using `<source>` tags within `<audio>` tags. I think it's more of a browser problem than a React problem as it updates the DOM fine but I thought there should be a discussion on solutions/next steps.
> 
> **What is the current behavior?**
> 
> Source `src` example: https://jsfiddle.net/danbovey/km5c3zmq/ Audio `src` example: https://jsfiddle.net/danbovey/v40cbwpx/
> 
> The browser is not recognising any changes React makes to the `src` prop of `<source>`, if you change the `src` prop directly on the `<audio>` tag the browser re-renders/resets the audio tag as expected.
> 
> **What is the expected behavior?**
> 
> The source example should match the behaviour of the audio example. Happens in all browsers.

**Comment by adonaiKasawa** [comment] 2023-01-30 00:38
> Merci pour le rapport@danbovey! Cela semble être le comportement attendu. [Cet exemple](https://jsfiddle.net/198mcb0z/) montre que la configuration `src`d'un `source`élément ne met pas à jour son élément multimédia parent. Ceci est cohérent dans Firefox et Chrome.
> 
> Nous pouvons chercher des moyens de contourner cela. Pour l'instant, vous pouvez utiliser un `key`sur les `audio`éléments pour forcer React à créer de nouveaux éléments DOM, ce qui semble fournir le comportement que vous recherchez https://jsfiddle.net/74oqdtd8/

thank you very much you saved me 👏👏👏
