### ISSUE TITLE
some attributes are only set if SSR is used

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5966] opened 2016-02-02 11:57 UTC
Maybe we don't care, but some attributes are currently only set if SSR is used.

http://jsfiddle.net/8ftyu8eq/

Not sure if it's worse than the old behavior (which was different for initial render as compared to subsequent renders).  But this could be a tricky one for people to debug if they hit it, since it depends on a more subtle difference (SSR vs CSR); I imagine people frequently fail to test their components on SSR, so the difference is more likely to catch them by surprise.

**Comment by zpao** [comment] 2016-02-02 23:31
CSS selectors use the DOM attribute. Now that we aren't generating the markup and inserting, initial values are also set the same way that they were for updates. `value` uses the property, not the attribute. Unless *everything* is set via the attribute (which isn't 100% possible) then we'll need to have some cases that aren't possible to catch. But we could potentially start using attributes for everything that is possible. cc @spicyj

**Comment by spicyj** [comment] 2016-02-02 23:35
For `value`, this is essentially a dupe of #4618.

Gonna call style a wontfix.

**Closed by spicyj** 2016-02-02 23:35 UTC
