### ISSUE TITLE
TestUtils.Simulate.{event}(compositeInstance) should throw early

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#10165] opened 2017-07-12 23:06 UTC
With the help of `node debug` I found this bug:

```
exception in node_modules/react-dom/lib/ReactDOMComponentTree.js:113
TypeError: Cannot read property '__reactInternalInstance$3isc485qtdibe29' of undefined
 111  */
 112 function getClosestInstanceFromNode(node) {
>113   if (node[internalInstanceKey]) {
 114     return node[internalInstanceKey];
 115   }
```

you're not testing against undefined variables here and also before calling that `getClosestInstanceFromNode` function.

Initially reported in https://github.com/facebook/react/issues/10108, trying to find out what's wrong here.

Backtrace is

```
#0 ReactDOMComponentTree.js:113:11
#1 ReactDOMComponentTree.js:147:14
#2 ReactTestUtils.js:336:74
#3 CancelSubmitButtons.es:38:34
#4 queueRunner.js:38:12
#5 promise queueRunner.js:31:21
#6 index.js:42:16
```

Using React + React DOM v15.5.4 both here.

**Comment by aweary** [comment] 2017-07-12 23:15
@binarykitchen as mentioned in https://github.com/facebook/react/issues/10108, this error is usually the result of a swallowed error putting React into a corrupted state. `getClosestInstanceFromNode` shouldn't be called with an undefined node, so what you're seeing is just another side effect of this corrupted state.

If you can provide an example reproducing this error, please do so in the original issue https://github.com/facebook/react/issues/10108

Thanks!

**Comment by gaearon** [comment] 2017-07-12 23:31
I mean, it could technically be some other reason, or even a legitimate bug.
But we can’t tell without a minimal reproducing example.

**Comment by binarykitchen** [comment] 2017-07-12 23:31
Instead of a reproducible example (which is too much work), I debugged deeper.

It is this line which causes the error:

```js
TestUtils.Simulate.click(component.refs.cancel)
```

`component.refs.cancel` is a React component itself, a button instance of react-bootstrap.

So, inside that click function the internal `makeSimulator` function is called which has these code lines:

```js
    if (ReactTestUtils.isDOMComponent(domComponentOrNode)) {
      node = findDOMNode(domComponentOrNode);
    } else if (domComponentOrNode.tagName) {
      node = domComponentOrNode;
    }
```

it turns out that both if conditions aren't met. Hence the node instance remains undefined.

**Comment by gaearon** [comment] 2017-07-12 23:49
What is `domComponentOrNode`? Is it undefined?

In this case, are you sure you weren’t passing `undefined` in the first place? That is, are you sure `component.refs.cancel` exists?

**Comment by gaearon** [comment] 2017-07-12 23:52
Ohhh I think I see what the issue is. I don’t think `Simulate` methods ever supported passing **component instances** to them. They only supported passing DOM nodes. As you can read [in the docs](https://facebook.github.io/react/docs/test-utils.html#simulate):

>Simulate an event dispatch **on a DOM node** with optional `eventData` event data.

It is confusing that we don’t throw early when you pass something else though. We should add an early invariant for that. Thanks for reporting!

**Comment by binarykitchen** [comment] 2017-07-12 23:54
aaaah, right, that's the mistake. can you add such an early invariant check yeah?

**Comment by binarykitchen** [comment] 2017-07-13 00:02
btw `TestUtils.Simulate.click(ReactDOM.findDOMNode(component.refs.cancel))` fixed it ... a but cumbersome

**Comment by abhishekpathak** [comment] 2017-07-13 06:18
@gaearon @binarykitchen I'll take up the issue, if that's ok. I'm a beginner to react and this looks like a great place to dive in.

**Comment by gaearon** [comment] 2017-07-13 08:28
Sure, sounds good!

**Comment by GFSTEAM** [comment] 2017-07-13 11:36
I Think i need indonesian languange.. i'm so confused

**Comment by gaearon** [comment] 2017-08-17 18:24
Fixed by https://github.com/facebook/react/issues/10414.

**Closed by gaearon** 2017-08-17 18:24 UTC
Labels: Difficulty: beginner
