### ISSUE TITLE
[DevTools Error] Cannot remove node "2315" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by AsheshL** [facebook/react#21534] opened 2021-05-19 20:31 UTC
### Website or app

Website

### Repro steps

Not sure

### How often does this bug happen?

Often

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.2-e468072e17

### Error message (automated)

Cannot remove node "2315" because no matching node was found in the Store.

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment] 2021-05-19 21:19
Hi!

I'm sorry you ran into this problem.

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

We may close issues that have no repro.

**Comment by jlaflash95** [comment] 2021-05-19 21:25
I've had this same issue, it happens when the DOM removes previously rendered components that are conditionally rendered using ternary operators and Context API state.

It's not bothersome enough for me to include all the code etc, but it does make it a littler harder to debug since I have to use console.log instead of viewing the current state of a component.

**Comment by bvaughn** [comment] 2021-05-20 02:18
@AsheshL Without a repro, there's nothing I can do with this issue.

Here's an updated build of DevTools though that _might_ fix the problem you're seeing, if you'd like to test it out:
[ReactDevTools.zip](https://github.com/facebook/react/files/6512405/ReactDevTools.zip)

You can follow these steps to install it:
https://user-images.githubusercontent.com/29597/118749019-b6cda600-b82a-11eb-9449-ef56f41eced5.mp4

**Comment by JoelBrenstrum** [comment] 2021-05-21 02:11
@bvaughn That unpacked extension worked for me! Thansk

**Comment by bvaughn** [comment] 2021-05-21 14:19
Thanks!

I'm going to go ahead and close this since we still don't have any repro info. Hopefully the updated extension fixes the problem, but if not- we can re-open the issue later.

**Closed by bvaughn** 2021-05-21 14:19 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed, Type: Bug
