### ISSUE TITLE
Question on reconciliation

### ISSUE THREAD

**Issue by hanalice** [facebook/react#23311] opened 2022-02-16 06:20 UTC
Let's say on first render, first datastore as below:

```json
[
  {id: 1, name: "Duke"},
  {id: 1, name: "Villanova"},
  {id: 1, name: "Neclause"},
  {id: 2, name: "Derk"}, 
  {id: 3, name: "Lily"}
]
```
we render following:
<ul>
  <li key="1">Duke</li>
  <li key="1">Villanova</li>
  <li key="1">Neclause</li>
  <li key="2">Derk</li>
  <li key="3">Lily</li>
</ul>
I changed the datasource to `[{id: 2, name: "Derk second time"}, {id: 3, name: "Lily second time"}]` after a setTimeout, What I expect on next render is:

<ul>
  <li key="2">Derk second time</li>
  <li key="3">Lily second time</li>
</ul>

But it render the following result,  key="1" li remains in the dom tree, which I expect to be eliminated.

<ul>
  <li key="1">Duke</li>
  <li key="1">Villanova</li>
  <li key="2">Derk second time</li>
  <li key="3">Lily second time</li>
</ul>

Hower when I changed the datasource to `[]` after a setTimeout, What I expect on next render is:
<ul>
  <li key="1">Duke</li>
  <li key="1">Villanova</li>
  <li key="2">Derk second time</li>
  <li key="3">Lily second time</li>
</ul>

Out ot my expection, I got following a empty dom tree???
A online demo is accessiable on https://codesandbox.io/s/ji-chu-lie-biao-antd-4-18-7-forked-nm4sly?file=/index.js

Can someone explain the reconciliation for me this case, thanks!

**Comment by Muhiq146** [comment] 2022-02-16 08:17
If You change the datasource to  [ ] than obviously it will display none, not this what you expect 

`Duke
Villanova
Derk second time
Lily second time`

You will get an empty dom tree that's not out of your expectation, it is reality.

**Comment by sammy-SC** [comment] 2022-02-16 14:46
Hey,

I couldn't reproduce the first case you mention: going from five items in the list to two items.  Setting data source to empty array is expected to result in empty DOM tree.

I'm going to close this issue. Feel free to reopen it if you would like a further clarification.

**Closed by sammy-SC** 2022-02-16 14:46 UTC
Labels: Type: Question, Status: Unconfirmed
