### ISSUE TITLE
onChange events can't stopPropagation under IE9&IE10.

### ISSUE THREAD

**Issue by windyGex** [facebook/react#7791] opened 2016-09-22 11:46 UTC
**Do you want to request a _feature_ or report a _bug_?**

_bug_

**What is the current behavior?**

onChange events can't stopPropagation under IE9, IE10. It will throw a error and then trigger change events.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net**

https://jsfiddle.net/69z2wepo/57337/

``` js
var Hello = React.createClass({
  render: function() {
   return <span onChange={this.log}>
                <input onChange={this.stop}/>
                </span>
  },
  log: function(e){
    console.log('change');
  },
  stop: function(e){
    e.stopPropagation();
  }
});

ReactDOM.render(
  <Hello />,
  document.getElementById('container')
);
```

**What is the expected behavior?**

span should not trigger onChange events when type in input under IE9&IE10.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.3.0. IE9&IE10.

**Comment by syranide** [comment] 2016-09-22 11:48
This is fixed in master, not sure if released.

**Comment by syranide** [comment] 2016-09-22 11:49
> span should not trigger onChange events when type in input.

That is not a bug though, that is how the HTML DOM works.

**Closed** 2017-10-04 13:37 UTC
