### ISSUE TITLE
Setting the selection range of a text input only works asynchronously

### ISSUE THREAD

**Issue by jchitel** [facebook/react#6483] opened 2016-04-11 10:45 UTC
Hello,

I'm trying to implement a text field and have fine control over its behavior. The state of a text field includes its value and the selection range, so I pass those in as properties. The selection range isn't exposed as an HTML attribute of a text input, but you can set it using the underlying DOM element object. I can get that value using the "ref" attribute, and set it in `componentDidUpdate()`, like so (note that I'm using [Elemental UI's FormInput component](https://github.com/elementalui/elemental/blob/master/src/components/FormInput.js), which is just a wrapper around a regular input):

```javascript
import React from 'react';
import { FormInput } from 'elemental';

export default class FineControlTextField extends React.Component {
    static propTypes = {
        value: React.PropTypes.string.isRequired,
        onKeyPress: React.PropTypes.func.isRequired,
        selection: React.PropTypes.object.isRequired,
    };

    componentDidUpdate() {
        setTimeout(() => {
            this.input.setSelectionRange(this.props.selection.start, this.props.selection.end);
        }, 0);
    }

    render() {
        const props = {
            type: 'text',
            value: this.props.value,
            onKeyDown: this.props.onKeyPress,
            onKeyPress: (e) => { e.stopPropagation(); e.preventDefault(); },
            onKeyUp: (e) => { e.stopPropagation(); e.preventDefault(); },
            ref: (ref) => this.input = ref && ref.refs.input,
        };

        return (<FormInput {...props} />);
    }
}
```

- I'm using Redux, so all properties you see are coming from the Redux store.
- I don't actually change the selection yet, so the value is always `{ start: 0, end: 0 }`. Thus, I should expect the cursor to sit at the start of the field and not move.
- At the moment, the `onKeyPress` function passed into the component just dispatches a Redux action that adds an 'a' to the end of the text. It also calls `stopPropagation` and `preventDefault` because I thought those might help me, but they didn't.

You'll notice that I had to put the `this.input.setSelectionRange()` in a `setTimeout`. If I don't do this, the call does nothing. However, this isn't a complete solution because the cursor gets moved to the end of the input regardless, so when I press keys, the cursor moves to the end of the input, then my selection gets called and the cursor quickly moves back to the beginning. Since it works asynchronously, I can deduce that React likely sets the selection range itself after `componentDidUpdate()` is called.

Is there any way that I can have more control over this behavior? This isn't a common use case so I can understand that there isn't an exposed API for setting the selection range. But is there some workaround or something I'm not aware of that I need to do to get this to work?

**Comment by jimfb** [comment] 2016-04-15 19:03
I don't think we set selection ever; I think we rely on the synchronous value update to handle cursor position.  To be honest, I'm confused why the `setTimeout` is necessary, I wouldn't have expected that.

cc @spicyj @jquense

**Comment by spicyj** [comment] 2016-04-15 19:07
Yes, I wouldn't expect the setTimeout here to be necessary. Sometimes browsers are finicky with focus and selection though so it may just be due to that.

**Comment by jquense** [comment] 2016-04-15 19:30
my guess would be that `onKeyDown` firing before `onChange` has something to do with it...it looks like you are changing the input value on that event instead of `onChange`?

my quick test works fine with onChange: https://jsfiddle.net/69z2wepo/38922/ but not `onKeyDown`

**Comment by jchitel** [comment] 2016-04-15 19:32
Perhaps that will work for me, but the selection range does get set here:

https://github.com/facebook/react/blob/67f8524e88abbf1ac0fd86d38a0477d11fbc7b3e/src/renderers/dom/client/ReactInputSelection.js#L114

I will try onChange, though, thanks.

**Comment by jimfb** [comment] 2016-04-15 19:52
With @jquense's excellent observation that the `onKey` events fire before `onChange`, I now feel like everything is behaving as expected.  For reference, my fiddle: https://jsfiddle.net/rmsLxtbj/

@jchitel If you can provide a fiddle that demonstrates something you believe is unexpected behavior, let us know and we can re-investigate.

**Comment by jchitel** [comment] 2016-04-16 02:30
Using onChange worked! Thanks!

So for the sake of my understanding, my onKeyDown handler triggered a change of state, which set the selection, but then the onChange event fired and reset the selection? Where can I find more information about event ordering?

**Comment by jimfb** [comment] 2016-04-16 03:47
Event ordering is defined by the browsers, you can probably find some W3C docs on when events are fired.

If I understand correctly, anything that is selected at the time `onChange` fires will get replaced by the character that was typed into the text box.  This seems to be supported by my fiddle, which always replaces the first character (which is selected by the key event).

As far as I can tell, everything is working correctly / as expected, so I'll close this out.  If you run into any issues and things are looking sketchy/wrong, let me know and we can re-examine.

**Closed by jimfb** 2016-04-16 03:47 UTC
Labels: Status: Unconfirmed
