### ISSUE TITLE
useObserver and ESlint conflict

### ISSUE THREAD

**Issue by igorkamyshev** [facebook/react#16594] opened 2019-08-28 08:25 UTC
Hello!

I found **bug** in `eslint-plugin-react-hooks` package.

Now, it throw error (`React Hook "useState" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.`) for the following code:

```js
import { useObserver } from 'mobx-react-lite';

const Component = () =>
  useObserver(() => {
    const [count, setCount] = useState(0);
   
    const increment = useCallbacl(() => setCount(c => c + 1));
   
   return (
     <>
       <p>COUNT {count}</p>
       <button onClick={increment}>INC</button>
     </>
   )
  });
```

I guess, it is not correct, because `useObserver` **can** be used like this.

In normal case, this code don't throw eslint error.

This issue accur on `"eslint-plugin-react-hooks": "1"`.

**Comment by lintuming** [comment] 2019-08-28 08:39
Can this work?
```js
import { useObserver } from 'mobx-react-lite';

const Demo=() => {
    const [count, setCount] = useState(0);
   
    const increment = useCallback(() => setCount(c => c + 1));
   
   return (
     <>
       <p>COUNT {count}</p>
       <button onClick={increment}>INC</button>
     </>
   )
  }
const Component = () =>
  useObserver(()=><Demo/>);

```

**Comment by sukjae** [comment] 2019-08-28 10:02
In my opinion, it doesn't seems like a bug.

I dont know how  `useObserver` from `mobx-react-lite` works, 
but as you can see in [React hooks doc](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) you shouldn't call Hooks inside regular js function.

> Don’t call Hooks inside loops, conditions, or nested functions.

> Don’t call Hooks from regular JavaScript functions. Instead, you can:
> ✅ Call Hooks from React function components.
> ✅ Call Hooks from custom Hooks (we’ll learn about them on the next page).

And from my point of view, hooks was called inside your regular JS function as a callback
```js
// this is just regular JS function 
// and will passed to `useObserver` as a parameter(callback) 
() => {  
    const [count, setCount] = useState(0); 
   
    const increment = useCallbacl(() => setCount(c => c + 1));
   
   return (
     <>
       <p>COUNT {count}</p>
       <button onClick={increment}>INC</button>
     </>
   )
 }
```

In conclusion, even though the code you written works, 
you should avoid the code style you written as `eslint-plugin-react-hooks` suggested.

**Comment by igorkamyshev** [comment] 2019-08-28 18:09
> Can this work?
> 
> ```js
> import { useObserver } from 'mobx-react-lite';
> 
> const Demo=() => {
>     const [count, setCount] = useState(0);
>    
>     const increment = useCallback(() => setCount(c => c + 1));
>    
>    return (
>      <>
>        <p>COUNT {count}</p>
>        <button onClick={increment}>INC</button>
>      </>
>    )
>   }
> const Component = () =>
>   useObserver(()=><Demo/>);
> ```

Yes, it works. Also, it works correctly, if I provide named function to `useObserver`, e.g.

```js
mport { useObserver } from 'mobx-react-lite';

const Component = () =>
  useObserver(function InnerComponent() {
    const [count, setCount] = useState(0);
   
    const increment = useCallbacl(() => setCount(c => c + 1));
   
   return (
     <>
       <p>COUNT {count}</p>
       <button onClick={increment}>INC</button>
     </>
   )
  });
```

**Comment by igorkamyshev** [comment] 2019-08-28 18:10
> In my opinion, it doesn't seems like a bug.
> 
> I dont know how `useObserver` from `mobx-react-lite` works,
> but as you can see in [React hooks doc](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) you shouldn't call Hooks inside regular js function.
> 
> > Don’t call Hooks inside loops, conditions, or nested functions.
> 
> > Don’t call Hooks from regular JavaScript functions. Instead, you can:
> > ✅ Call Hooks from React function components.
> > ✅ Call Hooks from custom Hooks (we’ll learn about them on the next page).
> 
> And from my point of view, hooks was called inside your regular JS function as a callback
> 
> ```js
> // this is just regular JS function 
> // and will passed to `useObserver` as a parameter(callback) 
> () => {  
>     const [count, setCount] = useState(0); 
>    
>     const increment = useCallbacl(() => setCount(c => c + 1));
>    
>    return (
>      <>
>        <p>COUNT {count}</p>
>        <button onClick={increment}>INC</button>
>      </>
>    )
>  }
> ```
> 
> In conclusion, even though the code you written works,
> you should avoid the code style you written as `eslint-plugin-react-hooks` suggested.

I don't thinks so. `useObserver` take the real component (function, yeah) as argument and, I guess, we can use hooks in this **normal** component. Also, If I write down name for this component, plugin stops throwing error.

**Comment by threepointone** [comment] 2019-08-28 18:47
closing this since it seems to be as designed, and the workarounds (hoisting the hook usages, or using a named component) are legit.

**Closed by threepointone** 2019-08-28 18:47 UTC

**Comment by igorkamyshev** [comment] 2019-08-29 05:59
@threepointone nice. But, if it works as designed, it has a wrong design. Because, `useObserver` take the **valid Component** as argument, plugin throws error. But, thanks for response.

**Comment by FredyC** [comment] 2019-08-31 09:36
I agree with @igorkamyshev its sort of false positive since the callback is practically called immediately and such it won't cause any ordering issue. However, I don't see how it could be detected properly in such special case so the mentioned workarounds are a better solution; or ignore eslint on that line.

**Comment by terrysahaidak** [comment] 2019-09-02 10:43
I don't think that just ignoring it is a good solution.

The `useObserver` is [just a function](https://github.com/mobxjs/mobx-react-lite/blob/master/src/useObserver.ts#L16-L64) which doesn't violate rules of using hooks, it event uses hooks under the hood. The `useObserver` is a _HOC_, which accepts a functional component. So all the hooks inside it will be run in a functional component, just like it should be.

So the error `React Hooks must be called in a React function component` isn't correct. And since it really works as it should be, here is another bug – eslint-plugin-react-hooks doesn't recognize that callback as a functional component. The workaround is to use named function instead of arrow one, but this seems like a dirty hack for me :)

**Comment by FredyC** [comment] 2019-09-02 11:06
@terrysahaidak It's not exactly correct that `useObserver` is HOC. For one, the callback passed in is just a function, even though it does return React Element, it's not a fully-fledged component (does not accept props). And what's most important it still runs in the same rendering context as the owning component.

The `useObserver` was always intended more like a low-level api. With new React Devtools it's no longer such a big annoyance to have couple extra HOC in the tree. I would essentially recommend to avoid using `useObserver` as some holy grail that can cover anything. There is no need for it.

Or if you really must, you can rename `useObserver` in your import and make it look like it's not a hook and then ESLint won't complain :)

**Comment by terrysahaidak** [comment] 2019-09-02 11:12
Another workaround is to use of `observer` from the latest `mobx-react`

```jsx
import { observer } from 'mobx-react-lite';

const Component = observer(() => {
    const [count, setCount] = useState(0);
   
    const increment = useCallbacl(() => setCount(c => c + 1));
   
   return (
     <>
       <p>COUNT {count}</p>
       <button onClick={increment}>INC</button>
     </>
   )
  });
```

I didn't get that part about `useObserver` and "low-level api", it's required in order to react to changes in my observables and re-render my components.
It's a replacement of `<Observer>{() => fn()}</Observer>`. I can't just avoid using it, really can't :) 

Is that `<Observer />` I've described above is a HOC?

**Comment by FredyC** [comment] 2019-09-02 11:18
@terrysahaidak You got that quite reversed. The [observer HOC](https://mobx-react.js.org/observer-hoc) and [Observer component](https://mobx-react.js.org/observer-component) are both having `useObserver` inside of them. That hook is what makes the whole thing to tick.



> but using is really annoying, also it doesn't let me run all the `useEffect` and other stuff when I want to.

Why would you need to have useEffect inside the observer? Such effect won't be reactive, check the [actual recipe for that](https://mobx-react.js.org/recipes-effects).

We are way off-topic here. Please, if you have some MobX related questions, ask in `mobx-react` repo.

Toward the topic ... yes, the eslint rule is sort of wrong, but it's not worth it to be changing it for this special use case, especially when there are other ways I just described.

**Comment by terrysahaidak** [comment] 2019-09-02 11:24
thanks @FredyC, but useObserver was introduced by mobx-react-lite to trick the bug when I cannot call hooks inside `observer`'ed components, so you're wrong here, it's not `low-level api`, but rather deprecated/private in `mobx-react@6`.
I currently have a lot of `useObserver` in my app, and the easier way here is to disable that eslint plugin for now but would be cool to have something like "whitelist" option in plugin configuration to trick it here.

**Comment by kpounds81** [comment] 2020-02-12 15:43
`import { useObserver } from 'mobx-react-lite';

const Component = () => {
  const [count, setCount] = useState(0)
 
  const increment = useCallbacl(() => setCount(c => c + 1))
 
 return useObserver(() => (
   <>
     <p>COUNT {count}</p>
     <button onClick={increment}>INC</button>
   </>
 ))
}`

Couldn't you just move the useObserver down to wrap the component being returned? This works in my situations anyway and gives no TS lint errors.

**Comment by kpounds81** [comment] 2020-02-12 15:46
```javascript
const Component = () => {
  const [count, setCount] = useState(0)
 
  const increment = useCallbacl(() => setCount(c => c + 1))
 
 return useObserver(() => (
   <>
     <p>COUNT {count}</p>
     <button onClick={increment}>INC</button>
   </>
 ))
}
```

Couldn't you do something like this where the `useObserver` is moved down to wrap the component being rendered? That seems to work well for me in my use cases to get the linter happy.
