### ISSUE TITLE
Error: "Could not find node with id "1681" in commit tree"

### ISSUE THREAD

**Issue by asmyshlyaev177** [facebook/react#17202] opened 2019-10-28 09:53 UTC
Describe what you were doing when the bug occurred:
1. Was profiling component performance.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.0-a8b8ffb89

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:156567
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:156513)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157036)
    at gl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:314363)
    at fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59263)
    at lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103717)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89467)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89392)
    at pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86341)

Component stack: in gl
    in div
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by threepointone** [comment] 2019-10-29 12:41
Closing as a duplicate of #16506

**Closed** 2019-10-29 16:00 UTC
Labels: Component: Developer Tools, Type: Bug
