### ISSUE TITLE
onAnimationEnd/onTransitionEnd Issues

### ISSUE THREAD

**Issue by geekscorner** [facebook/react#15327] opened 2019-04-04 22:54 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

### onAnimationEnd creates unexpected behavior

In the following example, I am creating a simple notification component from an array. Each element in the array is used to generate a html element with a class that has a css animation on it. The generated div has an "onAnimationEnd" binding which will remove them from the array of notifications. The basic idea is that the notification will fade away (using a CSS animation) and then be removed from the array, or alternatively, I am also allowing the user to manually click on the notification element to remove it.

The interesting bug is as follows. If you add two notifications, the first one will trigger its onAnimationEnd and remove itself. The remaining notification will suddenly jump to the end of its css animation and never trigger its own onAnimationEnd. 

Even more curiously if you add four notifications, exactly two of them will have the above bug, while the other two function properly. In fact exactly half of the added elements will trigger onAnimationEnd properly, while the other half will not.

The onClick functionality to remove the notifications from the array does NOT cause any unexpected behavior, and thus I am forced to conclude that the fault lies with onAnimationEnd, since they both run the exact same function.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codepen.io/msorrentino/pen/xeVrwz

Click the "add notification" button. Then press it again before the first element has faded (7 seconds) . You will notice that the second notification element gets "fast forwarded" to the end of its animation when the first notification is removed by its onAnimationEnd trigger. The second notification will then be stuck there, never triggering its own onAnimationEnd.

**What is the expected behavior?**

onAnimationEnd should trigger for each element in the loop properly.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Current version of 16.8.6 displays this behavior.

**Comment by kunukn** [comment] 2019-04-06 20:14
I believe the issue is because the `key` should be unique
I could not reproduce it when I ensured the `key` is unique.

Could you try this demo and see if the issue is still there?

demo
https://codepen.io/kunukn/pen/51da6d407d00b2818be610c6db2d74c8

**Comment by geekscorner** [comment] 2019-04-08 13:17
@kunukn You are correct. That does seem to be the source of the behavior.  It is strange (to me) that onClick and onAnimationEnd would react so differently in this particular case. OnClick does not have any issue at all with the key yet onAnimationEnd does have an issue (exactly 50% of the time).

**Comment by threepointone** [comment] 2019-04-11 13:27
it's also because you're directly mutating the array, leading the math to be a bit off. 
```jsx
  remove = (notification) => {
    this.setState({notifications: this.state.notifications.filter(x => x !== notification)})
  }
```

that said, this still isn't particularly good code, because it's matching on content (in this case they all have the same one, so it animated right, but this might not be true when you actually use it) Would recommend attaching ids to each notification, and using that as a reference when removing from the array. 

closing this issue.

**Closed by threepointone** 2019-04-11 13:27 UTC
Labels: Type: Question
