### ISSUE TITLE
Bug: React Dev Tools crashes with Hookstate hooks

### ISSUE THREAD

**Issue by Singha360** [facebook/react#20609] opened 2021-01-18 11:05 UTC
React version: 17.0.1
Dev Tools Version: 4.10.1 

## Steps To Reproduce
_Reading this will make this bug report more clearer: https://github.com/avkonst/hookstate/issues/123_

I am using [Hookstate](https://github.com/avkonst/hookstate) to manage the states of my components. Dev Tools shows some errors when using the Hookstate's `useState` hook more than once in a component. I reported this bug to the [Hookstate repo](https://github.com/avkonst/hookstate/issues/123) as I thought it was more appropriate. But the owner told me that this bug wasn't present before and that it only showed up recently so I was redirected to report this bug here. 

Further more, even using it's `useState` hook in combination with React's `useState`, [the error still pops up](https://github.com/avkonst/hookstate/issues/123#issuecomment-761901078).

Hookstate's hook returns a [different data structure](https://github.com/avkonst/hookstate/issues/123#issuecomment-761970835) than React's hook. This causes the React Dev Tools to struggle picking up the states in a component and throws an error.

This bug can be reproduced with this litle example:
```js
import React from "react";
import { useState } from "@hookstate/core";

import { globalState } from "./globalState";

function Counter() {
	const counter = useState(globalState);
	// const test = useState(0); <-- Uncommenting this and it's corresponding h1 causes the error.

	const onClick = () => {
		counter.set((value: number) => (value += 1));
	};

	return (
		<div className="Counter">
			<h1>{counter.value}</h1>
			<button onClick={onClick}>Click to Add</button>
			{/* <h1>{test.value}</h1> */}
		</div>
	);
}

export default Counter;
```

## The current behavior
React Dev Tools isn't able to read every state in a component when using Hookstate's implementation of the `useState` hook. It causes an error and the Dev tools doesn't load: 
![image](https://user-images.githubusercontent.com/35334787/104906147-53ea0200-5951-11eb-83fa-e97de36688cc.png)
![image](https://user-images.githubusercontent.com/35334787/104905381-42ecc100-5950-11eb-8021-88109bb7a841.png)

## The expected behavior
Every state should be displayed and no errors should pop up within the Dev Tools.

**Comment by rickhanlonii** [comment] 2021-01-18 19:57
@Singha360 are you able to reproduce this without Hookstate to rule out Hookstate as the source of the issue?

**Comment by Singha360** [comment] 2021-01-18 20:38
@rickhanlonii Using `React.useState` doesn't cause this issue. I wouldn't have opened an issue for this if it wasn't for the fact that the owner of hookstate mentioned [never having come across this error before](https://github.com/avkonst/hookstate/issues/123#issuecomment-761970835):

> The crash is somewhere within the devtools. And I think it is relatively recent issue as I have not seen it before and I am sure I used more than one state hook in many places.

**Comment by rickhanlonii** [comment] 2021-01-18 22:53
@Singha360 does Hookstate use React Hooks under the hood? If so, this issue should be reproducible with vanilla React. If not, and Hookstate is not using React, then it is not supported by React DevTools.

**Comment by Singha360** [comment] 2021-01-18 23:07
@rickhanlonii it is indeed using React Hooks under the hood.

![image](https://user-images.githubusercontent.com/35334787/104969956-e45b2d80-59b7-11eb-88d3-ff37fcf45568.png)

And I tried reproducing it with React Hooks and no errors popped up.

**Comment by rickhanlonii** [comment] 2021-01-18 23:33
@Singha360 thanks for the info!

I'm going to close this until there's a vanilla React reproduction case since, as you said, this works when using just React hooks.

**Closed by rickhanlonii** 2021-01-18 23:33 UTC
Labels: Status: Unconfirmed

**Comment by avkonst** [comment] 2021-01-19 00:12
@rickhanlonii Author of Hookstate is here. Hookstate uses two React hooks underneath useState and useEffect. There is no other special magic except specially maintained hash map to efficiently identify and notify (via a call to setState coming from React.useState) components affected by state change. This hash map gives React extraordinary performance boost, which you may not be seen before; see this demo of 10000 cells table state re-rending update to 1 cell every single millisecond - https://hookstate.js.org/docs/performance-frequent-updates. 

In relation to the reported bug. I disagree it was closed. And I am reopening it for the following reasons:

1. The bug happens with ONLY vanilla react hooks as Hookstate uses only vanilla react and 2 vanilla react hooks.
2. If you do not like the fact that there is a dependency to Hookstate, then copy index.ts from Hookstate to your project and use this instead of the Hookstate lib, and it will cause the crash in development tools. Would you like me to create such a reproducer repo for you?
3. Also, aren't you concerned that the crash stack trace points to the react dev tools code? I would thought that the code should be robust to the input it receives from various apps.
4. Moreover, the bug is reproducible if you simply add `React.useState(0)` - vanilla react hook - line to the sample React app: https://github.com/avkonst/hookstate/tree/master/docs/demos/todolist
![image](https://user-images.githubusercontent.com/3971413/104972656-3ef79680-5a57-11eb-8f06-7d8783e05914.png)
Otherwise it works fine. Should you be concerned that the addition of `React.useState(0)` is a part of the cause of the bug?

**Comment by avkonst** [comment] 2021-01-19 00:13
It seems like I do not have permissions to reopen it. Could you please reopen it?

**Comment by avkonst** [comment] 2021-01-19 01:52
Concise version of this bug is opened: https://github.com/facebook/react/issues/20613

**Comment by rickhanlonii** [comment] 2021-01-19 01:54
@avkonst thanks for the detailed information, I'll reply on the new issue.
