### ISSUE TITLE
`act` is not really helpful when setting state from promise callback

### ISSUE THREAD

**Issue by faergeek** [facebook/react#14779] opened 2019-02-06 20:06 UTC
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

https://codesandbox.io/s/zn7p0168vp

Wrapping in `act` doesn't help because `setState` is called later, on another tick, so warning is printed in a console.

**What is the expected behavior?**

Some way to test code like this without getting warning in a console about wrapping inside `act`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.0

**Comment by bvaughn** [comment] 2019-02-06 20:45
Looks like a duplicate of #14775 – Let's move the discussion there 😄

**Closed by bvaughn** 2019-02-06 20:45 UTC

**Comment by faergeek** [comment] 2019-02-06 21:12
@bvaughn not sure if it can be counted as a duplicate. Problem with timers can be solved by `jest.useFakeTimers`, but I couldn't find anything similar for promises :-(

**Comment by nbrady-techempower** [comment] 2019-02-07 00:46
@bvaughn I just came to open this same issue that I don't think can be resolved with `jest.useFakeTimers`.

```javascript
  <div>{count}</div>
  <button onClick={async () => await someFuncThatChangesCount() } />
```

How do you test this with `act`?

**Comment by bvaughn** [comment] 2019-02-07 07:31
Agreed in hindsight that `jest.useFakeTimers` isn't a valid solution for async/await. Since we've already go discussions going on both issues though, let's just continue it on that one. Sunil's aware of this and looking into it.
