### ISSUE TITLE
Input tags' values invisible to Sizzle/jQuery since v15

### ISSUE THREAD

**Issue by japgolly** [facebook/react#6478] opened 2016-04-11 08:01 UTC
Prior to v15 an input tag like `<input value="hello" />` would be found by a Sizzle/jQuery query like `':text[value=hello]'`. Since v15 the same query returns 0 results. If I reduce the query to `:text` and check its `.value`, sure enough the output is `"hello"`.

If you're wondering what I'm doing, I use Sizzle both directly in my unit tests to assert React output, and indirectly in a DOM-zipper library also for testing.

**Comment by japgolly** [comment] 2016-04-11 08:02
Also it's strange to me not being a JS wizz but calling `.outerHTML` returns only `<input class="">`.

**Comment by japgolly** [comment] 2016-04-11 08:07
Here is an example that's really quick and easy with Sizzle that is going to be more verbose and a little annoying otherwise:
```js
Sizzle("tr:has(:text[value=blahh]) button:contains('Delete')")
```

**Comment by robertkowalski** [comment] 2016-04-15 15:16
same here

**Comment by jineshshah36** [comment] 2016-04-22 18:02
This is not just when using Sizzle/jQuery I can confirm that the value attribute does not seem to be produced when rendering with react-dom but it does show up when rendering with react-dom/server. This is causing an invalid checksum for me

**Comment by spicyj** [comment] 2016-05-02 17:36
@jimfb Would #6406 fix this?

**Comment by jimfb** [comment] 2016-05-02 17:37
Yes, fairly certain.

**Comment by lud2k** [comment] 2016-05-04 01:23
I have a related issue. jQuery fails to get the value of an input with jsdom because their codes looks for the attribute "value" and it isn't there anymore in React 15.

Issue:
$('input[type=radio]').val() return 'on' in React 15.

jQuery code:
https://github.com/jquery/jquery/blob/master/src/attributes/val.js
return elem.getAttribute( "value" ) === null ? "on" : elem.value;

**Comment by Haotian-InfoTrack** [comment] 2016-06-01 05:04
Same here. I have to add value attribute to the input field after Mount... waiting for #6406 to be released.

**Comment by jimfb** [comment] 2016-06-08 15:18
This should be fixed now that https://github.com/facebook/react/pull/6406 has merged.  Will be released in an upcoming release.

**Closed by jimfb** 2016-06-08 15:18 UTC
Labels: Type: Regression
