### ISSUE TITLE
Components and profiler tabs don't appear

### ISSUE THREAD

**Issue by arch-abs** [facebook/react#19010] opened 2020-05-27 01:18 UTC
Very often the components and profiler tabs don't appear.

**Comment by bvaughn** [comment] 2020-05-27 16:11
Duplicate of #19002

If you have more info on how to reproduce (or even basic info like which browser and OS you're using) please add it to that issue.

**Comment by bvaughn** [comment] 2020-05-27 16:11
@arch-abs By chance, do you have the Relay extension installed?

**Closed by bvaughn** 2020-05-27 16:11 UTC
