### ISSUE TITLE
property 'key' not allowed

### ISSUE THREAD

**Issue by japrescott** [facebook/react#6045] opened 2016-02-16 16:13 UTC
Heads up to anybody going through debugging hell.
If you have your own fancy component (e.g `<AwesomeInput/>`) and you think its smart passing a prop named `key` to your component, so that you can set it as the `react-key` (you know, the one React complains about needing if there are multiple elements on the same level), `this.props.key` will be undefined within your component!

**'key' and 'ref' are reserved words that are not allowed to be passed as props.**

renaming the prop resolves this issue. It is too bad, that React doesn't warn you about that as it does with many other things. Would be great if this would be reflected more prominently in the docs under 'reserved names' or similar.

**Comment by jimfb** [comment] 2016-02-16 16:15
Duplicate of https://github.com/facebook/react/issues/5742

**Closed by jimfb** 2016-02-16 16:15 UTC
