### ISSUE TITLE
SetState fails in callback (via ComponentWillMount), on server only

### ISSUE THREAD

**Issue by darreng** [facebook/react#4873] opened 2015-09-15 01:06 UTC
I need to render React components on the server for SEO. My component fetches data in `ComponentWillMount`, based on the query parameters - but on the server (Node 4.0.0), `SetState` fails in the request's callback. The error can be reproduced with a simpler `setTimeout` too, as in the code example below.

I have found numerous discussion on the web relating to complications between React and server-side rendering. I'm working on two work-around approaches:
- removing all ajax requests from the server, instead rendering the result of the request directly into a global variable embedded in the first-serve HTML
- moving the ajax request prior to initialization of the React components, on the server only (the request would still have to live in `ComponentWillMount` (or `ComponentDidMount`) for the client version.

Please let me know if there is an alternative or recommended approach instead.

n.b. the reason I chose React over say Angular is because of `renderToString` is to ensure search engines can index the page, so this is all a bit of a bother for me right now...

```
var React = require('react');

// Reproduced in React 0.13.3 and 0.14.0-beta1
var ReactDOMServer = require("react-dom/server");

var A = React.createClass({
    componentWillMount: function() {
        var _this = this;
        // for example an ajax call to fetch data based on request parameters:
        setTimeout(function(err, res) {
            // state is set based on results
            _this.setState({ a: 1 });
        }, 100);
    },
    render: function() {
        return React.createElement('div', null);
    }
});


ReactDOMServer.renderToString(React.createElement(A, null));
```

```
$ node index.js 
/app/node_modules/react/lib/getActiveElement.js:25
    return document.body;
           ^

ReferenceError: document is not defined
    at getActiveElement (/app/node_modules/react/lib/getActiveElement.js:25:12)
    at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/app/node_modules/react/lib/ReactInputSelection.js:38:23)
    at ReactReconcileTransaction.Mixin.initializeAll (/app/node_modules/react/lib/Transaction.js:168:75)
    at ReactReconcileTransaction.Mixin.perform (/app/node_modules/react/lib/Transaction.js:135:12)
    at ReactUpdatesFlushTransaction.Mixin.perform (/app/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/app/node_modules/react/lib/ReactUpdates.js:86:38)
    at Object.flushBatchedUpdates (/app/node_modules/react/lib/ReactUpdates.js:147:19)
    at Object.wrapper [as flushBatchedUpdates] (/app/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/app/node_modules/react/lib/Transaction.js:202:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/app/node_modules/react/lib/Transaction.js:149:16)
```

**Comment by jimfb** [comment] 2015-09-18 20:50
I think the official recommendation at this point is to have a top-down data flow, rather than having components manage their own data requests.  That is to say, all the data a component utilizes should be passed down from the parent.

That said, we do acknowledge that sideways data loading is a hammer that we want to provide.  Duplicate of https://github.com/facebook/react/issues/3398 and https://github.com/facebook/react/issues/3858

**Closed by jimfb** 2015-09-18 20:50 UTC

**Comment by gaearon** [comment] 2015-09-18 21:04
Until there is a built-in solution, what you usually want to do is to have a data layer using a library like Alt, Flummox or Redux, and “hydrate” the data *before* rendering React components.

For example, see http://rackt.github.io/redux/docs/recipes/ServerRendering.html

**Comment by darreng** [comment] 2015-09-21 21:49
Ok, thank you for the advice.
