### ISSUE TITLE
Devtools V4 standalone script at localhost:8097 fails to load

### ISSUE THREAD

**Issue by sushruth** [facebook/react#16426] opened 2019-08-16 17:42 UTC
**Do you want to request a *feature* or report a *bug*?**

Reporting a bug

**What is the current behavior?**

The standalone devtools v4 script does not load when we navigate to `http://localhost:8097/`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

1. Run `react-devtools`
2. Navigate to `http://localhost:8097/` in a browser

**What is the expected behavior?**

- Expect the network call to end and a script to show up

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

not applicable

**Comment by bvaughn** [comment] 2019-08-16 17:52
Can't reproduce this. (Works fine for me.)

> **which browser / OS are affected by this issue?**
> not applicable

Seems applicable to me.

Could it be that you've got another extension or process that's blocking the port?

**Comment by bvaughn** [comment] 2019-08-18 03:56
Nevermind. I can repro this when running the package using e.g. `npx react-devtools@next`.

**Comment by bvaughn** [comment] 2019-08-18 04:11
Fixed via https://github.com/bvaughn/react-devtools-experimental/commit/95ca079556b6aa86b15c3ba98e5b9a302e5fb646

Fix will go out with the next point release (probably sometime Monday).

**Comment by bvaughn** [comment] 2019-08-18 16:21
Fix didn't land as part of 4.0.4. Should go out with 4.0.5. Re-opening in the meanwhile to remind myself to test.

**Comment by bvaughn** [comment] 2019-08-19 16:45
Fixed in the latest version, 4.0.5

**Closed by bvaughn** 2019-08-19 16:45 UTC
Labels: Component: Developer Tools, Type: Bug

**Comment by DevStar234** [comment] 2021-10-05 01:11
[asd](url)
