### ISSUE TITLE
Bug: `use-exhaustive-deps` static analysis doesn't work with destructure assignment or safety operator.

### ISSUE THREAD

**Issue by thijsnado** [facebook/react#20280] opened 2020-11-17 15:02 UTC
Using destructuring assignment on objects falsely triggers `use-exhaustive-deps`. For example, I would expect the following not to trigger lint rule:

```javascript
const object = { hello: 'world', foo: 'bar' }

useEffect(() => {
  const { hello } = object
  console.log(hello)
}, [object.hello])
```

The linter insists I pass `object` to the dependency array which is problematic since objects are compared by reference instead of value. I could destructure out of the useEffect block but this can cause naming collisions for bigger components/hooks. I can also assign variables the old fashioned way but that conflicts with our coding style.

The linting rule also has trouble with safety operator:

```javascript
const object = { hello: 'world', foo: 'bar' }

useEffect(() => {
  const hello = object?.hello
  console.log(hello)
}, [object.hello])
```

will cause it to ask for object in the dependency array.

**Comment by michie1** [comment] 2020-11-20 20:18
Duplicate of #17312

**Closed** 2020-11-20 21:23 UTC
Labels: Status: Unconfirmed
