### ISSUE TITLE
Cannot access lower leaves in object loaded with JSON and put in `this.state`

### ISSUE THREAD

**Issue by Mark-L6n** [facebook/react#4352] opened 2015-07-11 16:56 UTC
After loading a JSON object and adding it to `this.state` in the manner shown in the [React Tutorial](https://facebook.github.io/react/docs/tutorial.html), I am not able to access leaves below the first level.  Given this JSON file:
```json
{
	"simple": "A simple key-value",
	"dag1": {"key" : "A key pointing to a key-value" },
	"dag2": { "firstkey": { "secondkey": "A key pointing to a key pointing to a key-value" } }
}
```
the following results:
1. `{this.state.data.simple}`     works: "A simple key-value"
2. `{this.state.data.dag1.key}`    "Uncaught TypeError: Cannot read property 'key' of undefined"
3. `{this.state.data.dag.firstkey.secondkey}`    "Uncaught TypeError: Cannot read property 'firstkey' of undefined"

By putting debug variables in function `loadJSONFromServer`, one can see that that we can reference data fine from the JSON data structure itself, but not through `this.state` after `this.setState` adds it:
```javascript
	this.secondkey = data.dag2.firstkey.secondkey;	// Works here!
	this.setState({data: data});
	this.secondkey2 = this.state.data.dag2.firstkey.secondkey;	// But doesn't work here!
```
Here is the full test file, loading the JSON above in file `test-data.json`.  In the output, 1) and 4) work; 2) and 3) invoke the above error messages; and 5) returns nothing.
```html
<!DOCTYPE html>
<html>
<head>
  <title>Test referencing JSON object in React state</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>
<body>

<h2>JSON Test</h2>
<div id="content"></div>

<script type="text/jsx">

var ContentBox = React.createClass({
  loadJSONFromServer: function() {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      cache: false,
      success: function(data) {
				this.secondkey = data.dag2.firstkey.secondkey;	// Works here!
        this.setState({data: data});
				this.secondkey2 = this.state.data.dag2.firstkey.secondkey;	// But doesn't work here!
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
	getInitialState: function() {
    return {data: ''};
  },
  componentDidMount: function() {
    this.loadJSONFromServer();
  },
  render: function() {
		// var testValue = {this.state.data.junk};
    return (
      <div>
        <h2>Test</h2>
				<p>1. {this.state.data.simple}</p>
				<p>4. {this.secondkey}</p>
				<p>5. {this.secondkey2}</p>
      </div>
    );
  }
});

React.render(
  <ContentBox url="test-data.json" />,
  document.getElementById('content')
);

</script>

</body>
</html>
```

**Comment by andersekdahl** [comment] 2015-07-11 17:08
`this.setState` doesn't update `this.state` immediately. If you need to perform some action once the state has been set, you can pass a callback to `this.setState` as the second argument. `this.state` will be what you expected inside that callback.

**Comment by jimfb** [comment] 2015-07-11 18:50
@andersekdahl is correct, set state is queued.  I'm going to close this out since it's not a bug in React core, and we use github issues to track core bugs.  That said, feel free to continue this discussion if you're still running into an issue with this.

In the future, usage questions like this are better addressed on StackOverflow.

**Closed by jimfb** 2015-07-11 18:50 UTC

**Comment by Mark-L6n** [comment] 2015-07-11 18:54
Thanks for the quick response!
1.  I added a callback as follows:
`        this.setState({data: data}, this.loadJSONCallback);`
which calls:
```javascript
	loadJSONCallback: function() {
		this.secondkey2 = this.state.data.dag2.firstkey.secondkey;	// Still not returned by render()...
		console.log('this.secondkey2 = ' + this.secondkey2);		// ...but shows up in console.log
 	},
```
However, the output of 5) is still blank, although `console.log` shows the assignment.  Perhaps that assignment is still taking place later than `render()`.  Is it just not possible to use something from `this.state` in the return value of `render()`?  Or is there some function I could use in render() to ensure the date was updated?  Perhaps checking a `has-loaded` variable that is updated from within the callback function?

2) I didn't ID this a timing problem, since part of the object worked (`{this.state.data.simple}`) while the rest didn't...strange behavior!

3) A newbie question:  if the JSON is only loaded once, and won't be updated again, would it be better to use a prop instead of state, such as using [setProps](https://facebook.github.io/react/docs/component-api.html#setprops)

4) See I'm cross-posting with @jimfb .  Thanks to you and @andersekdahl for the quick advice!

**Comment by jimfb** [comment] 2015-07-11 23:50
Re 2: When you are reading `{this.state.data.dag.firstkey.secondkey}`, there is no variable on data called `dag`; there is only `dag1` and `dag2`.  I suspect your other errors are similar.

Re 3: setProps is about to be deprecated, do not use it.  Props are usually better than state, but if your component is setting it's own data, it needs to be state.  If the application (or a parent component) is loading the data, it can be a prop, which is usually ideal.

Your `loadJSONCallback` does not appear to be calling setState or otherwise performing a new render, so my first guess is that your issue is you're not rerendering after getting the data.

**Comment by Mark-L6n** [comment] 2015-07-12 00:37
Many thanks again @jimfb!
re 2:  good catch on the typo.  However, fixing it has the same error.  (Also, this is a simplified example I wrote to display the problem I had in another program, in which I tried a huge # of variations trying to figure this out, getting the same error.)  The errors are not due to a typo (in the fixed program below).
A further weirdness, that shows the corrected program working, is that the object works when printing from within `success()` to `console.log`.
```javascript
success: function(data) {
	this.secondkey = data.dag2.firstkey.secondkey;	// Works here!
	this.setState({data: data}, this.loadJSONCallback);
	console.log('this.state.data.dag2.firstkey.secondkey = ' + this.state.data.dag2.firstkey.secondkey );  // Works!
	this.secondkey3 = this.state.data.dag2.firstkey.secondkey;	// Still not returned by render()...
}.bind(this),
```
This would make it look like the data within `render()` is getting set initially, before the JSON is loaded, except for the fact that the 1st leaf prints out OK:  `1. {this.state.data.simple}`

I'm confused about the comment:
> Your `loadJSONCallback` does not appear to be calling `setState`...

...since  `loadJSONCallback` is itself called by `setState`.

Here is the modified complete program (the 1 typo fixed, with a couple of extra debugging lines):
```html
<!DOCTYPE html>
<html>
<head>
  <title>Test referencing JSON object in React state</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>
<body>

<h2>JSON Test</h2>
<div id="content"></div>

<script type="text/jsx">

var ContentBox = React.createClass({
	loadJSONCallback: function() {
		this.secondkey2 = this.state.data.dag2.firstkey.secondkey;	// Still not returned by render()...
		console.log('this.secondkey2 = ' + this.secondkey2);		// ...but shows up in console.log
 	},
  loadJSONFromServer: function() {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      cache: false,
      success: function(data) {
				this.secondkey = data.dag2.firstkey.secondkey;	// Works here!
        this.setState({data: data}, this.loadJSONCallback);
				console.log('this.state.data.dag2.firstkey.secondkey = ' + this.state.data.dag2.firstkey.secondkey );
				this.secondkey3 = this.state.data.dag2.firstkey.secondkey;	// Still not returned by render()...
     }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
	getInitialState: function() {
    return {data: ''};
  },
  componentDidMount: function() {
    this.loadJSONFromServer();
  },
  render: function() {
		// var testValue = {this.state.data.junk};
    return (
      <div>
        <h2>Test</h2>
				<p>1. {this.state.data.simple}</p>
				{/*<p>2. {this.state.data.dag1.key}</p>*/}
				{/*<p>3. {this.state.data.dag2.firstkey.secondkey}</p>*/}
				<p>4. {this.secondkey}</p>
				<p>5. {this.secondkey2}</p>
				<p>6. {this.secondkey3}</p>
      </div>
    );
  }
});

React.render(
  <ContentBox url="test-data.json" />,
  document.getElementById('content')
);

</script>

</body>
</html>
```

**Comment by jimfb** [comment] 2015-07-12 01:18
> I'm confused about the comment:
> > Your loadJSONCallback does not appear to be calling setState...

> ...since loadJSONCallback is itself called by setState.

Yes, that is my point.  setState() has already happened before loadJSONCallback gets called (that's why you're getting the callback).  If you set a local variable after the last call to setState, your component will not re-render because nothing told React that your component's state has changed.  Setting a local variable in the setState callback is a really weird thing to do, not recommended.  If you call setState again from within loadJSONCallback, I think it'll force another re-render and display the data for secondkey2.

Same for for secondkey3, that line occurs after the last call to setState(), so again, it's not going to show up in your render.

**Comment by Mark-L6n** [comment] 2015-07-12 02:50
@jimfb, thanks for bearing with me.  I finally figured out what was going on and will put it in my own words.
The reason the error messages were occurring is because the *1st* time that `render()` is getting called, the JSON object has not loaded yet, so there are not yet keys for `this.state.data.dag1.key` and `this.state.data.dag2.firstkey.secondkey`, and the error messages are produced.  (So the strange thing here is that `this.state.data.simple` did not produce the same error message.)
By adding `<p>7. {this.state.data}</p>` to the return values, I can see that after `render()` was called the final time, all of the data was there.
This is the reason that in the [React tutorial](https://facebook.github.io/react/docs/tutorial.html), there is:
```javascript
getInitialState: function() {
    return {data: ''};
 },
```
Without `this.state.data` being created by `getInitialState()`, the same error would have occurred the 1st time `render()` was called.  If I initialize the data structures, with for example:
```javascript
getInitialState: function() {
   return { data: {
			"simple": "",
			"dag1": {"key" : "" },
			"dag2": { "firstkey": { "secondkey": "" } }
		}
	}
 },
```
Then `render()` does not fail the 1st time, and everything works.
