### ISSUE TITLE
[DevTools Bug] Cannot remove node "20025" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by vivek-nrt** [facebook/react#24949] opened 2022-07-18 06:27 UTC
### Website or app

https://dev.threemad.com

### Repro steps

On inspecting comment modal

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.25.0-336ac8ceb

### Error message (automated)

Cannot remove node "20025" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26725:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24626:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24795:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54959:39)
```

### Error component stack (automated)

```text
comment
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by lunaruan** [comment] 2022-07-25 18:51
Hey! Thanks for reporting! Your link doesn't work for me unfortunately. Could you create a codesandbox repro case so we can take a look? Thanks!

**Comment by sbearben** [comment] 2022-08-05 14:50
Hitting this as well - had ran into this issue after attempting [the fix](https://github.com/facebook/react/issues/24437#issuecomment-1127022094) (updating `react-devtools-core` resolutions) for this similar issue: https://github.com/facebook/react/issues/24437

**Comment by lunaruan** [comment] 2022-08-17 20:18
@sbearben Do you have a repro case for this issue? Unfortunately we're unable to debug the issue without a way to reproduce it.

**Comment by lunaruan** [comment] 2022-09-06 23:03
Closing since there have been no repro cases. Fell free to reopen if you are able to provide one!

**Closed by lunaruan** 2022-09-06 23:03 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools
