### ISSUE TITLE
React Devtools standalone subpanels frozen on version 4.2.1

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [facebook/react#17532] opened 2019-12-05 08:40 UTC
Verified that version 4.2.0 works well, so a recent regression. Haven't tried to create a small example to reproduce, but since it's a recent bugfix version that should be fairly easy to pinpoint.

**Comment by olo2552** [comment] 2019-12-05 09:03
Doesn't work wor me too- I can click on tabs i.e. "Components" & "Profiler", but I cannot click and scroll components tree and star a profiler recording.

**Comment by hristo-kanchev** [comment] 2019-12-09 08:28
Duplicate of #17522

**Comment by hristo-kanchev** [comment] 2019-12-10 07:24
Hey @BartlomiejLewandowski  and @olo2552! What OS are you using by the way?

**Comment by salmankhilji** [comment] 2019-12-10 10:50
Same here.  Using Node 10.17 on Ubuntu 18.04.  Node installed using NVM.

**Comment by bvaughn** [comment] 2019-12-29 21:46
Fixed via PR #17584

**Closed by bvaughn** 2019-12-29 21:46 UTC

**Comment by bvaughn** [comment] 2020-01-03 18:24
FYI this issue should be fixed in v4.4 (released today)
