### ISSUE TITLE
Allow for 'x' prefixed attributes.

### ISSUE THREAD

**Issue by muffinresearch** [facebook/react#4757] opened 2015-09-01 12:37 UTC
Currently custom html attributes that start with 'x-' are not allowed.

Here's a test case: http://jsbin.com/jehefo/edit?html,js,console 

Allowing custom attributes would be helpful as for example things like Firefox OS use `x-inputmode="digit"` to provide a hint that the keyboard should only contain only digits. [1]

[1] http://www.wufoo.com/html5/attributes/23-inputmode.html

**Comment by jimfb** [comment] 2015-09-01 18:20
Duplicate of https://github.com/facebook/react/issues/140

**Closed by jimfb** 2015-09-01 18:20 UTC
