### ISSUE TITLE
Bug: When a cloneElement conditionally switches components, the onTouchMove is invalid

### ISSUE THREAD

**Issue by tgioer** [facebook/react#21949] opened 2021-07-24 06:01 UTC
React version: 17.0.2

```tsx
<div
    ref={rootRef}
    className="rate"
    onTouchMove={onTouchMove}
>
    {
        cloneElement(full ? fullIcon : voidIcon, {
            className: classNames("rate__icon", {
                "rate__icon--full": full,
            }),
        })
    }
</div>
```

Codesandbox：https://codesandbox.io/s/quiet-meadow-rfq1m

## The current behavior

When a cloneElement conditionally switches components, the onTouchMove is invalid

## The expected behavior

When a cloneElement conditionally switches components, the onTouchMove should work

**Comment by eps1lon** [comment] 2021-07-24 08:39
It doesn't look like this bug report has enough info for one of us to reproduce it. 
It's unclear what it means for an event handler to be "invalid" ("the onTouchMove is invalid")

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by eps1lon** [comment] 2021-07-25 04:22
Duplicate of https://github.com/facebook/react/issues/1355

**Closed by eps1lon** 2021-07-25 04:22 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
