### ISSUE TITLE
getDerivedStateFromProps is calling render method even I am returning null

### ISSUE THREAD

**Issue by skirankumar7** [facebook/react#14511] opened 2018-12-31 07:42 UTC
**What is the current behavior?**
Currenty render method is invoking even I am returned null in the getDerivedStateFromProps irrespective of whether props changed or not (just to check the behavior).

Here is CodeSandBox link:

**https://codesandbox.io/s/7wy6xm1z10**

Expected behavior : Not to invoke render method.

**React version: 16.6.3**
```jsx
import React from "react";
class Demo extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hello: "sam" };
  }

  static getDerivedStateFromProps(props, state) {
    console.log("getDerivedStateFromProps ", props, state);
    return null;
  }

  render() {
    console.log("render", this.state);
    return (
      <React.Fragment>
        Hello
        <hr />
        <button
          onClick={() =>
            this.setState(() => {
              return { name: "Kiran" };
            })
          }
        >
          click me
        </button>
      </React.Fragment>
    );
  }
  componentDidMount() {
    this.state = { HEHE: "HEHE" };
    console.log("DidMount");
  }

  getSnapshotBeforeUpdate() {
    console.log("getsnapshotbeforeupdate");
    return 12;
  }
  componentDidUpdate(props, state, snapshot) {
    console.log("DId Update", props, state, snapshot);
  }
  componentWillUnMount() {
    console.log("Will Unmount");
  }
}

export default Demo;
```

**Comment by joelmats** [comment] 2018-12-31 08:36
I think this is a duplicate of https://github.com/facebook/react/issues/14505

**Comment by vtereshyn** [comment] 2019-01-08 18:23
Yes, it is expected `getDerivedStateFromProps` work.

**Closed** 2019-02-08 17:17 UTC
