### ISSUE TITLE
Bug: invokeGuardedCallbackDev called too many times in dev mode

### ISSUE THREAD

**Issue by etomanon** [facebook/react#21033] opened 2021-03-18 21:14 UTC
React version: 17.0.1

## Steps To Reproduce

1. Create table with virtualized rendering 
2. Dev mode: Watch frames per second go to 1 for more than 1438ms in dev mode due to invokeGuardedCallbackDev calls when the scroll triggers rendering of new rows
3. Prod mode: Frames per second go to 7 for 139ms

### Dev mode performance:
![image](https://user-images.githubusercontent.com/17390813/111695753-b701f300-8833-11eb-8f88-d0d07f6ef0f0.png)
![image](https://user-images.githubusercontent.com/17390813/111695833-cc771d00-8833-11eb-8af0-bfa997ed8e81.png)

### Prod mode performance:
![image](https://user-images.githubusercontent.com/17390813/111696511-abfb9280-8834-11eb-91da-d85b78e7f886.png)
![image](https://user-images.githubusercontent.com/17390813/111696964-3e039b00-8835-11eb-8174-0ba95d1eb8ee.png)

Link to code example:

## The current behavior
It seems like the invokeGuardedCallbackDev is called on mount / unmount of every div. 1 row has 40 columns. 1 cell has 2 divs. So after scroll it can render 30 new rows = around 2 400 divs (and remove 2 400 old divs). Is it possible to lower the rate of invokeGuardedCallbackDev calls in dev mode? Linked issue: https://github.com/facebook/react/issues/19950

**Comment by bvaughn** [comment] 2021-03-19 00:56
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-03-19 00:57
To clarify:
> ## Steps To Reproduce
> 1. Create table with virtualized rendering

This isn't a repro. Please attach runnable code. :smile:

**Comment by bvaughn** [comment] 2021-03-22 16:52
Closing for now due to lack of repro information.

**Closed by bvaughn** 2021-03-22 16:52 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
