### ISSUE TITLE
I was getting an issue about React Devtools and i had downloaded that and as per the instructions 

### ISSUE THREAD

**Issue by RajeshDundurthi** [facebook/react#17868] opened 2020-01-19 11:05 UTC
👉 Please follow one of these issue templates:
- https://github.com/facebook/react/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by bvaughn** [comment] 2020-01-19 18:14
Duplicate of #17869

**Closed by bvaughn** 2020-01-19 18:14 UTC
