### ISSUE TITLE
Error: "Commit tree does not contain fiber 3661. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by JoshWhite** [facebook/react#18923] opened 2020-05-14 08:33 UTC
Describe what you were doing when the bug occurred:
1. Using Profiler tab
2. Clicked on a commit
3. It threw this error

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162825)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161772)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:164582)
    at ec (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:339280)
    at ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59620)
    at nl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:69923)
    at Ll (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:110996)
    at qc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102381)
    at Hc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102306)
    at Vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102171)

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by JoshWhite** [comment] 2020-05-14 08:34
If it's relevant, this console error is also present before using the profiler:
```
react-dom.development.js:88 Warning: React instrumentation encountered an error: TypeError: Cannot read property 'memoizedState' of null
```

**Comment by bvaughn** [comment] 2020-05-18 20:51
@JoshWhite Can you reproduce this behavior? If so, would you be willing to try a newer build of DevTools to see if you can still reproduce with it? I've fixed several bugs in the Profiler recently (not yet released).

Here's a build from master:
[ReactDevTools.zip](https://github.com/facebook/react/files/4646618/ReactDevTools.zip)

I'm going to close this issue as a duplicate of #18831 but it would be helpful if you could share more info with me.

**Closed by bvaughn** 2020-05-18 20:51 UTC

**Comment by loia5tqd001** [comment] 2020-07-13 17:16
[Here](https://streamable.com/teb3to) is a video reproducing the problem.

I saw that the action clicking the blue button: "Thêm mới đối tác", which was a *react-router-dom*'s `<Link to="merchant-add" />`, took 1-2 seconds to operate, which was a little bit janky to me. So I decided to use the Profiler to track and see what caused the 1-2s operation. And the video is the result of profiling.

**Comment by bvaughn** [comment] 2020-07-13 17:17
Hi @loia5tqd001 

Please add repro info to the open issue, #18831
