### ISSUE TITLE
Bug: input won't trigger onChange after a chain of setStates

### ISSUE THREAD

**Issue by voliva** [facebook/react#18128] opened 2020-02-25 15:54 UTC
React-dom version: 16.9.0 to 16.12.0 (latest)

This bug was not present in 16.8.6

## Steps To Reproduce

1. Create a controlled input element
2. Add an `onKeyDown` event handler that will change a state.
3. Add a `useEffect` hook that depends on the state from (2.), and changes another state
4. Try to type in something in the input

Link to code example: https://codesandbox.io/s/nostalgic-lake-zzynt

## The current behavior
The input updates with the key the user has pressed

## The expected behavior
The input doesn't update. The handler for `onKeyDown` was called, but the handler for `onChange` wasn't.

**Comment by voliva** [comment] 2020-02-25 16:46
Update: I've bisected this happens after #15650 merged

**Comment by hyonisss** [comment] 2020-03-12 07:22
> React-dom version: 16.9.0 to 16.12.0 (latest)
> 
> This bug was not present in 16.8.6
> 
> ## Steps To Reproduce
> 1. Create a controlled input element
> 2. Add an `onKeyDown` event handler that will change a state.
> 3. Add a `useEffect` hook that depends on the state from (2.), and changes another state
> 4. Try to type in something in the input
> 
> Link to code example: https://codesandbox.io/s/nostalgic-lake-zzynt
> 
> ## The current behavior
> The input updates with the key the user has pressed
> 
> ## The expected behavior
> The input doesn't update. The handler for `onKeyDown` was called, but the handler for `onChange` wasn't.

**Comment by kof** [comment] 2020-04-27 10:36
I did more triaging, this broke in react-dom package in particular.
- Using react@16.13.1  with react-dom@16.9.0-alpha.0 - shows the expected behavior
- Using react@16.13.1 with 16.9.0-rc.0 - shows the broken behavior

**Comment by voliva** [comment] 2020-08-26 12:36
I tried with react@17.0.0-rc.0 (hoping that with the refactored event system it would work) and it seems like it still doesn't work.

**Comment by gaearon** [comment] 2020-08-26 16:08
We haven't touched that part but there are some post-17 changes planned that should simplify this. We'll revisit at that point.

**Comment by gaearon** [comment] 2021-06-23 21:19
This is fixed in 18 alpha.
https://codesandbox.io/s/tender-glade-80ks5?file=/src/App.js

Unfortunately we won't backport the fix to 17 because it was a complex refactor which relies on other things we're putting in 18.

**Closed by gaearon** 2021-06-23 21:19 UTC
Labels: Type: Bug
