### ISSUE TITLE
Should have a queue. This is likely a bug in React. Please file an issue.Bug: 

### ISSUE THREAD

**Issue by aanarkulov** [facebook/react#21849] opened 2021-07-12 11:57 UTC
https://sentry.io/share/issue/9b4a3b588cd34fcea5f2d461516afd2b/

**Comment by bvaughn** [comment] 2021-07-12 13:40
Hi @aanarkulov

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-07-14 22:54
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-07-14 22:54 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
