### ISSUE TITLE
[Bug] Radio button only fires the onChange event one time

### ISSUE THREAD

**Issue by hieudole** [facebook/react#10168] opened 2017-07-13 10:04 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Radio button only fires the onChange event once for each option.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Demo code: https://jsfiddle.net/84v837e9/154/

**What is the expected behavior?**
Radio button should fire the onChange event whenever value is changed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Current latest version (15.6.1)

**Comment by aweary** [comment] 2017-07-14 17:55
Hey @hieudole! I believe this is a duplicate of #9988 (same issue, different context)

This should be resolved in the next 15.6 release thanks to https://github.com/facebook/react/pull/10186

Thanks!

**Closed by aweary** 2017-07-14 17:55 UTC

**Comment by vebjorni** [comment] 2017-08-22 16:38
@aweary Has this been released yet?

**Comment by aweary** [comment] 2017-08-22 16:40
@vebjorni not yet, it should be included in the 15.6.2 release
