### ISSUE TITLE
[DevTools Bug]: "Hook parsing failed" Components tab

### ISSUE THREAD

**Issue by adrian19hub** [facebook/react#24980] opened 2022-07-24 12:53 UTC
### Website or app

https://studio-test-2.netlify.app/

### Repro steps

click "Components" tab
click on component
click "parse hook names"

### How often does this bug happen?

Every time

### DevTools version (automated)

4.25.0

### Error message (automated)

"Hook parsing failed"

**Comment by tamirmatz** [comment] 2022-07-25 06:58
i have the same issue...

**Comment by mondaychen** [comment] 2022-07-25 13:55
Which component? I tried on the input box and it worked for me
<img width="948" alt="image" src="https://user-images.githubusercontent.com/1001890/180794433-3db7019f-043e-43da-83cb-3b1ead195f1c.png">

**Comment by adrian19hub** [comment] 2022-07-26 08:17
> Which component? I tried on the input box and it worked for me <img alt="image" width="948" src="https://user-images.githubusercontent.com/1001890/180794433-3db7019f-043e-43da-83cb-3b1ead195f1c.png">

interesting..
None of them work.

**Comment by mondaychen** [comment] 2022-07-26 18:13
Can you please provide more information, such as name and version of your browser, OS, devtools extension, etc?

**Comment by adrian19hub** [comment] 2022-07-28 14:10
> Can you please provide more information, such as name and version of your browser, OS, etc., as well as devtools extension version and react version?

browser - Chrome 103.0.5060.134
OS - Windows 10 Pro, 21h2 19044.1826
React version - 17.0.2
Devtools version - 4.25.0 (7/13/2022)

Thanks

**Comment by adrian19hub** [comment] 2022-08-07 14:06
anyone? :(

**Comment by mondaychen** [comment] 2022-08-08 17:27
I tried it on Windows 10 and it still worked for me.
Can you try it on a clean profile (without any other extensions)?

**Comment by adrian19hub** [comment] 2022-08-09 08:36
> I tried it on Windows 10 and it still worked for me. Can you try it on a clean profile (without any other extensions)?

Tried, worked one time

**Comment by mondaychen** [comment] 2022-08-09 14:19
If it works for you on a clean profile, you might have some special environmental set-up that breaks the feature. Maybe you can try disable some of your other extensions, or check if you turned on some experimental Chrome feature flags.

**Comment by adrian19hub** [comment] 2022-08-10 07:20
> If it works for you on a clean profile, you might have some special environmental set-up that breaks the feature. Maybe you can try disable some of your other extensions, or check if you turned on some experimental Chrome feature flags.

Unfortunately it worked only one time.

**Comment by mondaychen** [comment] 2022-08-10 16:45
Do you mean it worked for the first time, but stopped working when you move away from the component and try parse again?
Any chance you can provide a video?

**Comment by adrian19hub** [comment] 2022-08-11 14:04
> Do you mean it worked for the first time, but stopped working when you move away from the component and try parse again? Any chance you can provide a video?

If i recall well than yes,
tried to make a video but i couldn't reproduce the issue :/

**Comment by mondaychen** [comment] 2022-08-11 14:46
If it's no longer an issue, can I close this?

**Comment by adrian19hub** [comment] 2022-08-14 07:31
> If it's no longer an issue, can I close this?

It still is :), i couldn't reproduce the solving by using clean profile.

**Comment by lunaruan** [comment] 2022-08-17 20:17
Hey, I am unable to reproduce this issue, and it seems as if @mondaychen was unable to reproduce this issue as well. I'm going to close this for now since we can't do anything about it, but if you are able to create a consistent repro case please feel free to reopen!

**Closed by lunaruan** 2022-08-17 20:17 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools

**Comment by adrian19hub** [comment] 2022-08-28 11:29
> Hey, I am unable to reproduce this issue, and it seems as if @mondaychen was unable to reproduce this issue as well. I'm going to close this for now since we can't do anything about it, but if you are able to create a consistent repro case please feel free to reopen!

Is it possibly related to this popup?
![image](https://user-images.githubusercontent.com/79521379/187071869-87c23bc4-ddf1-43b2-b2a9-1308f5ad421f.png)

**Comment by alexschrod** [comment] 2022-10-29 07:08
I've never gotten this to work either, but I couldn't tell you why. Always the same outcome, on every React project I have, in multiple browsers:
![image](https://user-images.githubusercontent.com/767490/198818837-27511356-40e4-4aca-a780-603fa9229d04.png)

**Comment by back2Lobby** [comment] 2023-08-01 11:48
> I've never gotten this to work either, but I couldn't tell you why. Always the same outcome, on every React project I have, in multiple browsers: ![image](https://user-images.githubusercontent.com/767490/198818837-27511356-40e4-4aca-a780-603fa9229d04.png)

I am facing exactly same issue in my react-ts app on Ubuntu 22. I tried it on different browsers but still same, it doesn't even show any error message except "Hook parsing failed"

**Comment by holaChaitanya** [comment] 2024-01-05 07:57
![image](https://github.com/facebook/react/assets/86062961/6fda7750-04c2-404f-b762-b4a87a85e081)
Tried multiple times, but faced the same issue

**Comment by kevinbarabash** [comment] 2024-03-26 14:30
I'm seeing the same issue.

**Comment by jamesbvaughan** [comment] 2024-03-26 17:56
@kevinbarabash What version of the extension do you have installed? My fix was released in version 5.0.2. If you're on that version or higher, then my fix must not have covered all cases. In that case, can you provide a reproduction?

**Comment by maxbarry** [comment] 2024-04-04 02:32
I've always had this issue on projects that use [Recoil](https://github.com/facebookexperimental/Recoil) for state management.

Not sure if that's supposed to be supported, but here's a minimal repro. Under 5.0.2 I get "Hook parsing failed" and no value for the Recoil data (`Username`), while the `useState` value does display fine.

![image](https://github.com/facebook/react/assets/892447/2506ba00-7505-40bf-a602-79b7bb1898e2)

```javascript
import React, { useState} from 'react'
import ReactDOM from 'react-dom'
import { RecoilRoot, atom, useRecoilValue } from 'recoil'

const RecoilApp = () => (
    <RecoilRoot>
        <App />
    </RecoilRoot>
)

const App = () => {
    const [ count, setCount ] = useState(0)
    const name = useUsername()

    return (
	<RecoilRoot>
            <button onClick={() => setCount(count + 1)}>
		{name} count: {count}
	    </button>
	</RecoilRoot>
    )
}

const username = atom({
    key: 'user',
    default: 'Guest',
})

const useUsername = () => useRecoilValue(username)

ReactDOM.render(
    <React.StrictMode>
	<RecoilApp />
    </React.StrictMode>,
    document.getElementById('root')
)
```

**Comment by carolineartz** [comment] 2025-01-08 17:22
@maxbarry i dunno if you're still on that...but I know that you can `useDebugValue` in a custom hook like your recoil value abstractions...not saying that's great 😆  or doesn't make things much more verbose... but at least its easier to add during dev and applies across all your components that use it...i'm using recoil (unfortunately) and I do this sometimes :/

```ts
const useUsername = () => {
  const username =  useRecoilValue(username)
  useDebugValue(username)
  
  return username
}
```

dev tools => Username: whatever

**Comment by Sbrjt** [comment] 2025-07-06 16:27
Same issue

**Comment by Sbrjt** [comment] 2025-07-06 16:38
https://github.com/facebook/react/issues/25427
