### ISSUE TITLE
Ensures role attribute has an appropriate value for the element (aria-allowed-role - https://dequeuniversity.com/rules/axe/4.7/aria-allowed-role?application=msftAI)

### ISSUE THREAD

**Issue by msftedad** [facebook/react#30010] opened 2024-06-21 08:41 UTC
React version: 16.14.0

## Steps To Reproduce

1. Launch the application using URL: [Bryntum Scheduler - Vertical mode demo (React)](https://www.bryntum.com/products/scheduler/examples/frameworks/react/javascript/vertical/build/).
2. “Vertical mode demo (React)” screen should open.
3. TAB to “Filter Event” button.
4. Run AI4W fast pass and observe the issue.

Link to code example:

## The current behavior
Ensures role attribute has an appropriate value for the element (aria-allowed-role - https://dequeuniversity.com/rules/axe/4.7/aria-allowed-role?application=msftAI)

 

Element path: .b-grid-header-container

Snippet: <header role="row" aria-rowindex="1" class="b-grid-header-container b-show-yscroll-padding" data-owner-cmp="b-scheduler-1" data-max-depth="0">

![224479_AI4W](https://github.com/facebook/react/assets/93735775/68209366-b799-4efd-9f08-0d078a50e6e4)

## The expected behavior
ARIA role row is not allowed for given element

**Comment by eps1lon** [comment] 2024-06-25 11:17
Duplicate of https://github.com/facebook/react/issues/30018

**Closed by eps1lon** 2024-06-25 11:17 UTC
Labels: Status: Unconfirmed
