### ISSUE TITLE
Strict propTypes mode

### ISSUE THREAD

**Issue by idris** [facebook/react#3113] opened 2015-02-10 18:08 UTC
It would be nice to be able to set a flag that will trigger invariant warnings any time a prop is referenced from or passed into a component, but that was not declared in propTypes.

**Comment by irvinebroque** [comment] 2015-02-10 18:13
Invariant is probably too harsh for this, but I'd be all for a console warning.

**Comment by milanlandaverde** [comment] 2015-02-12 04:09
#2060

(I know, cause I just asked for this)

**Comment by idris** [comment] 2015-02-12 04:32
Seems like this is also a dupe of #1587

**Comment by jsfb** [comment] 2015-02-18 22:39
I'm going to close this as a duplicate of https://github.com/facebook/react/issues/1587

TLDR:
> It's a bit tricky because of transferPropsTo (or whatever we do instead) where you might have props that need to be passed on even if you don't consume them.

That said, I think it's a good idea, and would prefer to optimize for the common case where the unrecognized prop is a mistake rather than the less common case where people are transferring props.  Just not as easy as it might seem at first glance.

**Closed** 2015-02-18 22:40 UTC
Labels: Resolution: Duplicate
