### ISSUE TITLE
Components should be able to render arrays of nodes

### ISSUE THREAD

**Issue by kmalakoff** [facebook/react#5050] opened 2015-10-04 17:55 UTC
Over the last two weeks, I have encountered the problem of wanting to return arrays of nodes during Component rendering:

1) building a tree - rendering a flat list with the node and children at the same level
2) building table rows - rendering two table rows for one piece of data

Both cases were hacky to work arounds since the Component held UI state for the node / children or rows. I am finding that components returning a single node is too limiting as it can lead to head scratching workarounds to try to unroll logic.

I've read some of the other issues related to this, but I hope these two concrete cases will help you reconsider loosening the component principles of one component to one DOM node since in reality there are cases when this is not the case.

**Comment by spicyj** [comment] 2015-10-04 19:57
Dupe of #2127.

**Closed by spicyj** 2015-10-04 19:57 UTC
