### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by geetanshum** [facebook/react#20260] opened 2020-11-15 13:41 UTC
var _jsxFileName = "D:\\reacttut\\awesomeapp\\src\\index.js";
  23 | 
  24 | 
> 25 | react_dom__WEBPACK_IMPORTED_MODULE_2___default.a.react( /*#__PURE__*/Object(react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__["jsxDEV"])("h1", {
     |                                                  ^  26 |   children: "hello world"
  27 | }, void 0, false, {
  28 |   fileName: _jsxFileName,

**Comment by bvaughn** [comment] 2020-11-15 14:04
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-11-17 21:29
Going to close this due to lack of repro info.

**Closed by bvaughn** 2020-11-17 21:29 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
