### ISSUE TITLE
Catch errors from render methods

### ISSUE THREAD

**Issue by mjomble** [facebook/react#10215] opened 2017-07-19 02:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

If a component's render method throws an error, it leaves React in an inconsistent state.
Subsequent renders attempt to update the inconsistent component and result in errors like "Cannot read property 'getHostNode' of null".

**Proposed behavior**

React could catch the error from the render method, set an "inconsistent state" flag and re-throw it.
Afterwards, if React is about to update the previously rendered component, but this flag is set, it could discard or unmount the existing component and perform a fresh render, as if the container were empty.

**Which versions of React, and which browser / OS are affected by this issue?**

I've encountered the inconsistent state problems in 15.5 and 15.6

**Comment by MehdiAlouafi** [comment] 2017-07-19 09:17
It will be done in the next major release of react called fiber.

Here is the requested features as an issue on this repo : https://github.com/facebook/react/issues/2461

Good read : 

https://giamir.com/what-is-react-fiber

**Comment by gaearon** [comment] 2017-07-19 09:28
Closing as a duplicate of https://github.com/facebook/react/issues/2461.

**Closed by gaearon** 2017-07-19 09:28 UTC
