### ISSUE TITLE
Mismatch node type when hydrating SVG from SSR

### ISSUE THREAD

**Issue by donysukardi** [facebook/react#11397] opened 2017-10-30 06:22 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Getting the following error while trying to hydrate SSR content.
`Expected server HTML to contain a matching <linearGradient> in <defs>.`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

The following check returns false
https://github.com/facebook/react/blob/177cd8525348c83a89962c426fa482b5c8ca4f39/packages/react-dom/src/client/ReactDOM.js#L453-L462

as `type` is `linearGradient` and `instance.nodeName.toLowerCase()` is `lineargradient`

**What is the expected behavior?**

Node types are compared correctly as SVG uses camelCase for tagName

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16

**Comment by gaearon** [comment] 2017-10-30 15:29
This is a duplicate of https://github.com/facebook/react/issues/10772 and has been fixed on master. Thanks for report!

**Closed by gaearon** 2017-10-30 15:29 UTC

**Comment by gaearon** [comment] 2017-11-03 00:52
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.
