### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by NikkiMather** [facebook/react#22087] opened 2021-08-13 15:50 UTC
First I just want to preface this by stating that I'm unsure if this is a Google Places API issue or a React issue. The issue I'm having is that React renders `autoComplete="ignore"` as `autoComplete="off"` no matter what I do. I have highlighted the code below that triggers this issue with double asterisks.

    useEffect(() => {
        if (!googleApiReady || typeof onPlaceClicked !== "function") {
            return;
        }

        **const placesAutoComplete = new window.google.maps.places.Autocomplete(
            ref.current,
            {  componentRestrictions: { country: "us" } }
        );**

        placesAutoComplete.setFields(["address_components", "formatted_address"]);
        placesAutoComplete.addListener("place_changed", () => {
                const place = placesAutoComplete.getPlace();
                const results = {}
                const map = {
                    street_number: "short_name",
                    route: "long_name",
                    locality: "long_name",
                    administrative_area_level_1: "short_name",
                    country: "long_name",
                    postal_code: "short_name",
                };

                for (const component of place.address_components) {
                    const addressType = component.types[0];
                    if (map[addressType]) {
                        results[addressType] = component[map[addressType]]
                    }
                }

                onPlaceClicked(results)
            }
        );
    }, [googleApiReady])

React version: 17.0.1

## Steps To Reproduce

1. Add `autoComplete="ignore"` to an input and initialize the Google Places API

## The current behavior

React renders `autocomplete="off"` to the page rather than `autocomplete="ignore"`.

## The expected behavior

React renders `autocomplete="off"` to the page.

**Comment by jacty** [comment] 2021-08-15 01:24
sorry, cannot see where you have updated `autocomplete`. Perhaps you need to give more detail plz.

**Comment by bvaughn** [comment] 2021-08-15 21:22
Hi!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by NikkiMather** [comment] 2021-08-16 12:27
Hi,

I am unable to provide an example since i'd have to expose our Google Maps API key(s), however I have replicated the issue in Codesandbox. I have attached a screenshot showing the `autoComplete` on the input set to `test` but rendered as `off`.

**Comment by bvaughn** [comment] 2021-08-16 14:32
Bugs without repros don't get fixed. (Most of the time they don't even get looked into, because of the volume of issues and the limited number of contributors.)

We usually suggest you try to remove as many third party apps as possible when narrowing down the bug (so in this case, maybe removing Google Maps integration entirely). This makes it easier for our team to understand and identify the bug. In many cases, we've found that as someone reduces the repro they uncover the cause of the bug themselves (often times a misunderstanding of how to use a third party API for example).

**Comment by NikkiMather** [comment] 2021-08-16 14:36
Hey Brian,

Removing the Google Maps API code snippet does indeed 'fix' the issue, however I'm unsure if that means that Google Maps API is incorrectly working with React, or React is incorrectly working with the Google Maps API key. I opened a bug report in both React and the Maps API team as I'm unable to figure out essentially who is responsible.

Thanks again.

**Comment by bvaughn** [comment] 2021-08-16 14:39
> I'm unsure if that means that Google Maps API is incorrectly working with React, or React is incorrectly working with the Google Maps API.

Realistically, this is something you'll probably need to figure out as part of reporting the bug. Our team doesn't have the bandwidth to dig into potential bug reports when third party libraries are involved.

I suggest trying to narrow the bug (that only you can reproduce at this moment) down by gradually removing non-essential code.

**Comment by NikkiMather** [comment] 2021-08-16 14:42
Okay got it. I've done exactly that in my Codesandbox. Shall I now share the repo with you? How can I send it to you directly so it's not visible in the Issue (I don't wish to share the API keys publicly).

**Comment by bvaughn** [comment] 2021-08-16 14:45
I'm suggesting you continue to reduce the repro case until the bug no longer occurs. Is that possible without Google Maps API? If not, that suggests the bug might be in the API. If it's possible with "just React" then it's either a React bug or (sometimes) a browser compatibility quirk.

If you'd like to email me (brian david vaughn at gmail) I can take a quick look, but I'm not familiar with Google Maps API and I don't have _much time_ to dig in.

**Comment by bvaughn** [comment] 2021-08-18 14:57
I'm going to close this issue for now. If you are able to reduce it to a repro without the full Google Maps API, please share it with me and I'll re-open and take a look. Thank you for understanding.

**Closed by bvaughn** 2021-08-18 14:57 UTC
Labels: Status: Unconfirmed, Type: Needs Investigation
