### ISSUE TITLE
setState called twice trigger render twice

### ISSUE THREAD

**Issue by colorhook** [facebook/react#5760] opened 2015-12-31 07:07 UTC
use react-0.14.5

in the examples/basic-click-counter/index.html

change the `handleClick` method: 

```
handleClick: function () {
          this.setState({clickCount: this.state.clickCount+1});
          this.setState({clickCount: this.state.clickCount+1});
}
```

and add `componentDidMount` method:

```
componentDidMount: function(){
  setTimeout(function(){
    this.handleClick()
  }.bind(this), 2000)
}
```

If I click  &lt;h2&gt; element, the `setState` invoked twice, and the `render` invoked one time. But If the `setState` invoked in `setTimeout` callback, the `render` invoked multi times.

**Comment by colorhook** [comment] 2015-12-31 07:47
CallLater maybe a solution

```
var callLater = new CallLater();
var expensiveMethod = function() {
}

// expensiveMethod just invoked once.
callLater.call(expensiveMethod);
callLater.call(expensiveMethod);
```

```
var CallLater = function(){

  var inCallLaterPhase;
  var callLaterFlag;
  var ToString = Object.prototype.toString;
  
  var methodMap=(function(){
    var data = [];
    return {
      add: function(f, a, t){
        if(this.getIndex(f) == -1){
          data.push({f:f, a:a, t:t});
        }
      },
      getIndex: function(f){
        for(var i = 0, l = data.length; i < l; i++){
          if(data[i].f == f){
            return i;
          }
        }
        return -1;
      },
      remove: function(f){
        var i = this.getIndex(f);
        if(i >= 0){
          data.splice(i, 1);
        }
      },
      each: function(callback){
        for(var i = 0, l = data.length; i < l; i++){
          callback(data[i].f, data[i].a, data[i].t);
        }
      },
      reset: function(){
        data = [];
      }
    }
  })();

	function executeCallLater(){
		inCallLaterPhase = true;
		methodMap.each(function(f, a, t){
			f.apply(t, a);
		});
		methodMap.reset();
		inCallLaterPhase = false;
		callLaterFlag=false;
	}

  this.call = function(method, args, target) {
    if (inCallLaterPhase || ToString.call(method) !== '[object Function]'){
      return;
    }

    if (args && (ToString.call(args) != '[object Array]')) {
      args = [ args ];
    }

    methodMap.add(method, args, target);

    if (!callLaterFlag) {
      callLaterFlag=true;
      requestAnimationFrame(executeCallLater);
    }
  }
};
```

**Comment by brigand** [comment] 2015-12-31 08:20
Here's a jsbin showing it against master http://jsbin.com/veyedexapi/1/edit?js,console,output

**Comment by jimfb** [comment] 2016-01-12 05:58
I'm pretty sure this is expected behavior, unless I'm missing something.

When an event fires, the event is trapped by React, and React calls the event handler.  Multiple setStates within that cycle are batched together, because React is on the stack and will be able to process all the `setStates()` after the eventHandler has completed.  When a `setState` is invoked as the result of a `setTimeout`, React is not on the stack, and so the batch completes as soon as `setState` finishes (ie. it is effectively executed synchronously).

There are some talks about using `requestanimationframe` (or some similar solution, like `setTimeout`) to perform all operations asynchronously, but that is part of a much wider conversation about a new reconciler.  There is no actionable short-term task in this issue, so I'm going to close it out.

**Closed by jimfb** 2016-01-12 05:58 UTC

**Comment by zpao** [comment] 2016-01-12 06:51
Yes, state updates in event handlers are batched together.

**Comment by AlexGalays** [comment] 2016-01-24 11:18
For info, how high are batched updates of setStates calls from any location (and not just event handlers)  on your priority list?

**Comment by jimfb** [comment] 2016-01-24 17:02
Not high.  There are talks, and it might happen as part of a reconciler rewrite, but nothing is planned in the short term.

**Comment by AlexGalays** [comment] 2016-01-24 17:53
Ok thanks.

**Comment by jackielii** [comment] 2016-02-10 19:44
I too spent a few hours tracking this one down. Tried googling something like `setState didn't re-render` or `two setState only one triggered` but couldn't find anything useful. Maybe some documentation is due?

**Comment by jimfb** [comment] 2016-02-10 19:50
@jackielii It is documented pretty clearly in the big red NOTE box for `setState`: https://facebook.github.io/react/docs/component-api.html#setstate
