### ISSUE TITLE
Missing guard for double-require invariant

### ISSUE THREAD

**Issue by Schoonology** [facebook/react#4343] opened 2015-07-10 21:56 UTC
TL;DR: I propose we create a simple guard around doubly-including React, which can cause issues if different blocks work with different instances of `React`.

I understand this invariant isn't going to matter to everyone, but I've at two points in so many weeks fixed a bug on a co-worker's project because they were accidentally including React twice in the browser: one from a Browserify bundle, and once from a standalone `<script>`.

**Comment by jimfb** [comment] 2015-07-10 22:00
Duplicate of https://github.com/facebook/react/issues/2402

TLDR: It's more complicated than you might think.

**Closed by jimfb** 2015-07-10 22:00 UTC

**Comment by Schoonology** [comment] 2015-07-10 22:05
Thanks. Sorry for the dupe, I _promise_ I searched as much as I could think
of first.
