### ISSUE TITLE
Error boundaries: Recover from errors thrown in `render`

### ISSUE THREAD

**Issue by longlho** [facebook/react#2461] opened 2014-11-04 05:13 UTC
So I'm trying to put some graceful error handling in case 1 of my views crap out:

``` jsx
var MyGoodView = React.createClass({
  render: function () {
    return <p>Cool</p>;
  }
});

var MyBadView = React.createClass({
  render: function () {
    throw new Error('crap');
  }
});

try {
  React.render(<MyBadView/>, document.body);
} catch (e) {
  React.render(<MyGoodView/>, document.body);
}
```

However, `MyGoodView` does not get rendered w/ the following stack trace:

![stack trace](http://f.cl.ly/items/0G3d3s1G452p3g1q0T2j/Screen%20Shot%202014-11-04%20at%2012.11.43%20AM.png)

Seems like error throw React in a bad state where `renderedComponent` is `undefined`, thus cannot be unmounted. How do I handle this scenario?

**Comment by jsfb** [comment] 2015-03-05 10:00
https://github.com/facebook/react/issues/3313 has a really nice unit test that we should probably start using once the error boundaries issue is fixed.

**Comment by pedroteixeira** [comment] 2015-03-16 12:16
:+1:

**Comment by samzscott** [comment] 2015-06-11 15:30
+1

**Comment by moosingin3space** [comment] 2015-06-11 15:31
+1 This makes debugging React apps much more difficult than it has to be!

**Comment by jnak** [comment] 2015-06-11 21:32
+1 It's very scary that one child component error can take an entire component tree down. It would be awesome to put try/catch statements at some key components in that tree.

**Comment by skiano** [comment] 2015-06-22 15:34
I am working on an isomorphic app with many components, and we lean on very messy third-party APIs. So there is a relatively high risk that a developer can write a new component that makes bad assumptions about the data it receives (since we render server side, this destroys the request and the user cannot get any part of the page)

We decided to take an aggressive approach to the problem by wrapping React.createElement in our app and replacing the lifecycle methods with our own error handling. For ES6 we were thinking of doing the same thing by extending the Component class

Even though this leaves the app in an invalid state we thought it was preferable to rendering nothing for the user.

Here is a link to the code I am working on:
https://github.com/skiano/react-safe-render/blob/feature/safe-methods/index.js

Is there some reason why I really should not do this?

**Comment by spicyj** [comment] 2015-06-22 21:39
@skiano If that's working for you, no reason to stop. Our eventual solution should be a little more flexible than this and more efficient but will be similar in spirit.

**Comment by conoremclaughlin** [comment] 2015-07-08 08:23
+1

**Comment by timbur** [comment] 2015-07-22 06:34
Any idea what the time-frame might be for an official solution?  Just curious.  :)  In the mean-time I will probably just monkey-patch everything.

**Comment by mhagmajer** [comment] 2015-09-11 12:09
+1

**Comment by nmartin413** [comment] 2015-10-14 14:08
+1

**Comment by aleclarson** [comment] 2015-10-18 23:04
:+1:

**Comment by gaearon** [comment] 2015-10-19 23:31
@spicyj Should we label this as `big-picture`?

**Comment by spicyj** [comment] 2015-10-19 23:56
I'm willing to but it doesn't require much discussion, it just needs to get done.

**Comment by benmosher** [comment] 2015-10-28 22:18
I'd be glad to help out with this. It's a constant pain point for my team.

**Comment by LeZuse** [comment] 2015-11-22 18:41
Hi, first of all the test case in the first post works only within certain app context. Here's the working test case http://jsfiddle.net/XeeD/pLqphjm4/.

There is an already mounted component, that will throw in `render()` for the **second** render pass which leaves React in an inconsistent state, breaking the code [here]( https://github.com/facebook/react/blob/c5867ea401eee56ed40cdfb121d76c508ebc0826/src/renderers/shared/reconciler/ReactReconciler.js#L72) in `ReactReconciler.unmountComponent`

We thought about a few approaches by catching it [here]( https://github.com/facebook/react/blob/c5867ea401eee56ed40cdfb121d76c508ebc0826/src/renderers/shared/reconciler/ReactCompositeComponent.js#L811) in `ReactCompositeComponentMixin._renderValidatedComponent ` and:
* render an error string instead of the component (might be good for `__DEV__===true`)
* render an empty `<span>` (good for `__DEV__===false`)
* log the thrown error into the console (invariant)

However we are not sure about the correct way how to handle this. Feedback? Working on PR atm.

**Comment by ngasull** [comment] 2015-11-24 23:10
+1, this would be a huge improvement

**Comment by yagudaev** [comment] 2015-12-04 01:17
+1, been thinking about this lately

**Comment by slorber** [comment] 2015-12-11 23:31
very interested by this issue too.

Any idea on how the problem can be solved efficiently?

**Comment by spicyj** [comment] 2015-12-16 22:04
Let's leave this open until the new feature is complete.

**Comment by mhagmajer** [comment] 2015-12-29 15:24
What is the expected behavior here? Are we going to propagate the error to the top-most component?

**Comment by spicyj** [comment] 2015-12-29 17:32
An error bubbles up to the nearest error boundary (that is, a component with `unstable_handleError` defined).

**Comment by natew** [comment] 2015-12-29 19:11
Is there a PR to track for this? Just want to throw in my thanks on this as well, you all are killing it as usual.

**Comment by spicyj** [comment] 2015-12-29 19:24
#5602 has the first code for this which catches errors only on initial render but not at any other time. When we have more I am sure that this issue number will be mentioned in the description so you will see them in the comment history here.

**Comment by cappslock** [comment] 2016-01-16 02:56
+1, just got bit by this :)

**Comment by mik01aj** [comment] 2016-01-27 13:56
Well, there's [`react-transform-catch-errors`](https://github.com/gaearon/react-transform-catch-errors) for those using Babel, but I'd still like to see it fixed directly in React. :+1: from me.

**Comment by joaomilho** [comment] 2016-01-31 17:04
+1

**Comment by DanielSundberg** [comment] 2016-03-14 13:10
My team just ran into this issue and found this thread.

Some comments in here hint that the react team is working on improving this...

Can anyone comment if there's any progress being made or if this perhaps is on the roadmap for 15.0 or a later release?

**Comment by jimfb** [comment] 2016-03-14 18:17
@DanielSundberg Yes, basic/unstable support was added for initial render in v15, and support for updates is being added in a future release.  It will be documented when it becomes stable.

**Comment by vguzev** [comment] 2016-03-16 08:14
For those who need some kind of error handling in React 13/14 here is the workaround.
We created file following component Interceptor.jsx:
`
/**
 * Interceptor function that returns JSX-component in case of error.
 * Usage example:
 * render: interceptor('MyClass.myFunc', function() {
 *   ... Here is some code that potentially can generate Exception
 * }, <b>Hallelujah! Another soul saved!</b>)
 *
 * @param where - Name of the function - will be displayed in console when exception is caught
 * @param renderFunction - Function where exception can be raised.
 * @param component - Optional component which should be displayed in case of error.
 * @returns {Function}
 */
var Interceptor = function (where, renderFunction, component) {
    return function () {
        if (typeof Config != 'undefined' && Config.General && Config.General.stackTraceEnabled) {
            if (console) {
                if (console.debug) {
                    console.debug(where);
                }
                else {
                    console.log(where);
                }
            }
        }
        try {
            return renderFunction.apply(this, arguments);
        }
        catch (e) {
            console.error('Intercepted @ ' + where, e, this);
            if (component != null) {
                return component;
            }
            // Just redefine this logic here to return default custom error-handling component
            Core.Actions.InterfaceActions.crash();
            return null;
        }
    };
};

module.exports = Interceptor;
`

and you can use it like this:
`
render: interceptor('ThisIsMyComponentName.render', function() {
  var a = b.c; // Raising exception...
  return <div>Hello world!</div>
}   
`

**Comment by chandlerprall** [comment] 2016-04-20 00:31
Any plan / possibility the `unstable_handleError` approach could be implemented to work in `ReactDOM.renderToString`? Currently React errors on `var checkpoint = transaction.checkpoint();` in `performInitialMountWithErrorHandling`

**Comment by thom-nic** [comment] 2016-05-07 02:08
Can anyone point to an example of `unstable_handleError` use in v15?  I can't seem to figure out how to make it work :/

**Comment by jimfb** [comment] 2016-05-07 02:43
@thom-nic Officially, v15 does not support error boundaries.  Unofficially, https://github.com/facebook/react/blob/master/src/core/__tests__/ReactErrorBoundaries-test.js

**Comment by thom-nic** [comment] 2016-05-07 02:52
Understood.  Thanks for the example.  Unfortunately I can't seem to get it working.  I have the `unstable_handleError` defined in a root component with a console log statement but I don't see it called.  Strange.

**Comment by Aldredcz** [comment] 2016-06-19 22:00
Just wrote elegant (and global) workaround by monkeypatching `React.createElement`. Check out this gist if you are looking for a solution before this issue makes it to a release: https://gist.github.com/Aldredcz/4d63b0a9049b00f54439f8780be7f0d8

**Comment by Aldredcz** [comment] 2016-06-19 22:01
Just wrote elegant (and global) workaround by monkeypatching `React.createElement`. Check out this gist if you are looking for a solution before this issue makes it to a release: https://gist.github.com/Aldredcz/4d63b0a9049b00f54439f8780be7f0d8

**Comment by wangyangjun** [comment] 2016-08-02 12:49
Hi, @Aldredcz Thanks for your shearing. What is the licence of _monkeypatching_? Could I use it in my project?

**Comment by Aldredcz** [comment] 2016-08-02 13:43
@wangyangjun use it anywhere you wish :)

**Comment by tomchentw** [comment] 2016-10-05 03:09
The updated link to `unstable_handleError ` in v15 is here:
https://github.com/facebook/react/blob/15-stable/src/renderers/shared/stack/reconciler/__tests__/ReactErrorBoundaries-test.js

**Comment by ahmedyahiaalkaff** [comment] 2016-10-13 15:38
Hi, I get the following error when I try to use unstable_handleError:
[Error] TypeError: null is not an object (evaluating 'this._renderedComponent.unmountComponent')
	(anonymous function) (comp.js, line 15788)

**Comment by ivansglazunov** [comment] 2016-11-09 09:00
@Aldredcz It's really great work, thanks!

**Comment by bitmage** [comment] 2017-01-05 03:08
It seems as of React 15.0.2 the default behavior for `performInitialMountWithErrorHandling` is to swallow errors without any output.  This makes debugging incredibly difficult.  I don't know if it still works this way with more recent versions, but I would suggest a default of spitting out a warning at least.  Anything that would tell the developer what just happened.  Thanks!

FYI, as a workaround I implemented this in my top level component:
```js
  unstable_handleError(...args) {
    console.error(...args)
  }
```

Not a terrible inconvenience, but how do you find this issue thread when you don't have an error to go off of?  I had to run chrome with "pause on caught exceptions" to find it.

**Comment by hyperh** [comment] 2017-01-17 19:50
+1

**Comment by spicyj** [comment] 2017-01-17 19:53
@bitmage That's true; if you implement unstable_handleError then React doesn't log anything or rethrow the error; it is up to you to do so. It is like a try/catch. In a future version of React we will log an error regardless though (see #8756 for a preview).

**Comment by slorber** [comment] 2017-01-18 17:28
@spicyj are there cases where the unstable_handleError is not called?

I'm trying to build an HOC like that but the callback does not seem to be ever called:


```


import React from "react";



const RenderFallback = () => (
  <div>error</div>
);

// See https://github.com/facebook/react/issues/2461
export const ErrorBoundaryConstructor = ({
  fallbackComponent: RenderFallback,
  onError = undefined,
} = {}) => (WrappedComponent) => {
  
  return class ErrorBoundary extends React.Component {
    
    constructor(props) {
      super(props);
      this.state = {error: false};
    }
    
    unstable_handleError(e) {
      console.warn("unstable_handleError",e);
      onError && onError(e);
      this.setState({error: true});
    }
    
    render() {
      const Comp = this.state.error ? fallbackComponent : WrappedComponent;
      return <Comp {...this.props}/>;
    }
    
  }
  
};

export const DefaultErrorBoundary = Component => {
  return ErrorBoundaryConstructor()(Component);
};
```

An example of client code:

```javascript
import React from "react";
import Portal from "react-portal";
import classNames from "classnames";
import {DefaultErrorBoundary} from "utils/errorBoundary";

const FullscreenPortal = React.createClass({
  render() {
    return (
      <Portal isOpened={true}
              className={classNames(this.props.className, "fullscreen-portal")}
      >
        {this.props.children}
      </Portal>
    )
  },
});
export default DefaultErrorBoundary(FullscreenPortal);
```

**Comment by spicyj** [comment] 2017-01-18 23:08
Where is your error thrown? I don't see it in your code.

**Comment by slorber** [comment] 2017-01-21 00:36
@spicyj it's in the children of FullscreenPortal 

Just wanted to know if my HOC makes sense for this usecase or if this is an anti-pattern. Because thinking about it, there might be something I've missed in my implementation (like my children not being a composite component but an already rendered element tree)

**Comment by aweary** [comment] 2017-03-24 19:43
>That's all fine and dandy, but I'm really just interested in seeing the error as an initial step. Currently the stack trace doesn't even hint at where the code broke. You just know that "something rendered wrong".

@stevendesu the Fiber implementation provides the component stack for the error ([reference](https://github.com/facebook/react/blob/f606e0e7d37b3dbfdfd880921d5905c119be75bc/src/renderers/shared/fiber/ReactFiberScheduler.js#L1191-L1198))

**Comment by bvaughn** [comment] 2017-03-24 19:52
@stevendesu fiber also gives you this info in a nicely formatted console warning: 
![image](https://cloud.githubusercontent.com/assets/29597/24311238/8d1f5c9a-1090-11e7-9943-b0bb3d73e095.png)

**Comment by stevendesu** [comment] 2017-03-25 17:53
@aweary @bvaughn , any guesses when Fiber will be production-ready? Or is it too uncertain at this point?

**Comment by bvaughn** [comment] 2017-03-25 18:14
Don't know yet 😄 You can follow along with the remaining work on #8854 if you're interested.

Some of the things we're working on now/next include:
* Smaller, more optimized renderer bundles.
* A release of react-native that can use fiber. Getting ready to enter a couple week period of internal testing (at Facebook) for that renderer.
* Server-side rendering. We now have some nice failing unit tests for it thanks to Sasha. (See [isfiberreadyyet.com](http://isfiberreadyyet.com/))
* Some shallow renderer work remains as well that I think Leland and co are working on. (See airbnb/enzyme/pull/742, #8982)

Andrew and I are working toward one last 15.x release (probably next week) that adds a few deprecation notices and such for things that will be going away or changing in 16.

In the meanwhile there's an alpha release available (`16.0.0-alpha.6`) if you'd like to play with the react-dom renderer and fiber.

**Comment by davidfurlong** [comment] 2017-04-13 09:30
Whats the best practice for handling uncaught runtime errors in react lifecycle methods then? 
One uncaught error in production breaks the entire react component tree / serves a blank page. 
There must be a better solution than to add `try/catch` statements everywhere. 

The package https://github.com/gaearon/react-transform-catch-errors seems like a good idea, but its deprecated & recommended not to be used in production. 

Cheers

**Comment by kossnocorp** [comment] 2017-04-13 09:40
@davidfurlong `react-transform-catch-errors` is not only deprecated but also doesn't work with function components. AFAIK there is no better way than monkey-patch `React.createElement`. It may sound scary but it works reliable and doesn't have any overhead.

Check out my library https://github.com/kossnocorp/react-guard. It's used in several production apps for a few months already.

As a nice bonus, it allows to capture the component props & state:

![](http://i.ncrp.co/2x3Q3l0c3P14/Image%202017-04-13%20at%2012.36.54%20PM.public.png)

**Comment by kossnocorp** [comment] 2017-04-13 09:54
Btw, we got a white screen of death in production because of `react-transform-catch-errors`, so I don't even recommend to use it in `development`. It happened because of `react-transform-catch-errors` + `redbox-react` suppressing exceptions in development. So when an exception happened at the initial render but fixed by the following one, we didn't notice that and deployed that to production.

**Comment by davidfurlong** [comment] 2017-04-13 10:04
@kossnocorp Looks awesome and simple! Exactly what I was looking for! Thanks

**Comment by DanielSundberg** [comment] 2017-04-13 10:24
In our project we use the following as a base class for all components, outputs an error box if rendering fails. Ugly but works here:

````js
class BaseComponent extends React.Component {
    constructor(props) {
        super(props);
    }

    _safeRender() {
        throw new Error('_safeRender must be implemented in derived components')
    }

    render() {
        try {
            return this._safeRender();
        } catch (error) {
            log.error(error.stack);

            return (
                <div className="error-message">
                    <p>{error.message}</p>
                    {error.stack}
                </div>
            );
        }
    }
}
````

**Comment by kromit** [comment] 2017-04-13 10:57
Will monkey-patching become impossible with v16 since `React.createElement` is deprecated?

**Comment by joshclowater** [comment] 2017-05-23 18:14
Why the :-1:s for @DanielSundberg? His implementation is the only one I can get to work with component classes.

**Comment by DouglasLivingstone** [comment] 2017-05-24 09:11
I've not voted on it myself, but I wouldn't use it since it changes which method all the derived classes need to override to render, so special-case knowledge about how error handling in the base class works propagates to affect all React components. The current workaround I'm using is to wrap the render method in the base class in the constructor by calling `trapRenderExceptions`, which is very hacky but requires no changes to how the derived classes need to be written, so at least constrains the impact of the hack:

```
function trapRenderExceptions(component) {
    var oldRender = component.render;
    component.render = () => {
        try {
            return oldRender.call(component);
        }
        catch (e) {
            console.error("Serious error: Exception thrown in render. Report as a bug.");
            console.error(e);
            return null;
        }
    };
}
```

Very much looking forward to v16 with proper error boundaries!

**Comment by byronmwong** [comment] 2017-06-12 18:12
We've used the `BatchingStrategy` API as a way to wrap `try/catch`es around React code. It catches errors in `render()`s (initial and updates) and catches errors in your event handlers/callbacks. It doesn't require any monkey-patching and doesn't require you to wrap or modify any of your existing components.

**HOWEVER**, the `BatchingStrategy` API is going to be deprecated, so this strategy won't work with React 16. We've used it successfully in React 0.13 through 15.5, and I think it's a useful solution until error boundaries are ready.

More details here: https://engineering.classdojo.com/blog/2016/12/10/catching-react-errors/

**Comment by gaearon** [comment] 2017-06-26 14:35
Small update on this: latest alphas of React are still not ready for wide use (there's known issues with infinite loops in development), but they implement error boundaries so you can start playing with them (and see if they satisfy your use case).

The recommended way to use them is to create a component like this:

```js
class ErrorBoundary extends React.Component {
  state = { error: null };

  unstable_handleError(error, info) {
    this.setState({ error });
    // Note: you can send error and info to analytics if you want too
  }

  render() {
    if (this.state.error) {
      // You can render anything you want here,
      // but note that if you try to render the original children
      // and they throw again, the error boundary will no longer catch that.
      return <h1>Something went wrong: {this.state.error.toString()}.</h1>;
    }
    return this.props.children;
  }
}
```

Then you can put it anywhere:

```js
<ErrorBoundary>
  <MyApp />
</ErrorBoundary>
```

or to protect specific components:

```js
<Layout
  left={<Sidebar />}
  right={<ErrorBoundary><RouteHandler /></ErrorBoundary>}
/>
```

Note that `ErrorBoundary` acts as a "catch" block. It only "catches" errors in its children, but not in itself. You can nest error boundaries (just like you can nest catch blocks).

The exact API may change in 16.

**Comment by gaearon** [comment] 2017-06-26 14:39
@slorber If error boundaries don't work in latest alpha for some reason please create a complete reproducing example.

**Comment by kossnocorp** [comment] 2017-06-26 15:25
`ErrorBoundary` seems interesting, however, how it would allow rescuing individual components instead of a (sub)tree? In the examples above when a small icon throws an error during render, the whole app/page won't be rendered at all.

I'm imagining something like that:

```js
ReactDOM.safeRender(
  <App />,
  document.getElementById('root'),
  (err, componentInstance) => {
    // If component fails then report the incident and render nothing
    reportError(err, componentInstance)
    return null
  }
)
```

...or at least on a class level, so that we could use inheritance.

```js
class SafeComponent extends Component {
  catchRender (err) {
    reportError(err, this)
    return null
  }
}

class Whatever extends SafeComponent {
  render () {
    throw 'whoops'
    return <div>A small cosmetic detail</div>
  }
}
```

**Comment by gaearon** [comment] 2017-06-26 15:28
There is no support for doing this at individual component level (randomly disappearing individual components isn't a great user experience). You are, however, free to wrap all your components with an error boundary, or to create a base class (although we generally don't recommend that).

**Comment by natew** [comment] 2017-06-26 16:44
One question I have is with hmr, how to reset that error. I guess we'd need
to store the boundaries that saved errors in the react proxy logic. Or
perhaps a way to bubble up when a child has force updated. Anyway just
thinking out loud, excited to give it a try.

**Comment by gaearon** [comment] 2017-06-26 16:49
That warrants a separate discussion (it's not immediately clear to me how hot reloading should work with error handling). We'll might be looking at hot reloading some time this year, and this is a good time to discuss the ideal experience.

**Comment by joshclowater** [comment] 2017-06-27 14:17
I ended up implementing `ErrorBoundary` as a higher order component to wrap my components with.

```javascript
export default function ErrorBoundary(WrappedComponent) {
  class ErrorBoundaryComponent extends React.Component {
    state = { error: null };

    unstable_handleError(error, info) {
      console.error(error, info);
      this.setState({ error });
      // Note: you can send error and info to analytics if you want too
    }

    render() {
      if (this.state.error) {
        return null;
      }
      return <WrappedComponent {...this.props} />;
    }
  };
  return ErrorBoundaryComponent;
}
```

This solution is considerably better than extending a base component because it can wrap functional components

```javascript
function FunctionalComponent(props) {
  ...
}
export default ErrorBoundary(FunctionalComponent);
```

and catch errors that occur in the component's other wrappers, such as a selector in redux's `mapStateToProps`.

```javascript
export default ErrorBoundary(connect(mapStateToProps, mapDispatchToProps)(SomeComponent));
```

**Comment by gaearon** [comment] 2017-06-27 14:49
@joshclowater What is the benefit as opposed to using a regular component?

```js
<ErrorBoundary>
  <Something />
</ErrorBoundary>
```

This gives you more freedom with granularity.

**Comment by joshclowater** [comment] 2017-06-27 15:14
@gaearon Personal preference I guess. I find it slightly cleaner as it abstracts the error handling out of the JSX. If I'm wrapping many components, it could noisy to parse through all of the `<ErrorBoundary>`s. Also, if I know that's how I want the component to handle errors, then I don't have to worry about the parent containers wrapping it with `<ErrorBoundary>...<ErrorBoundary>` and risk missing it somewhere else.

```javascript
<ErrorBoundary>
  <Something />
</ErrorBoundary>
<ErrorBoundary>
  <Something />
</ErrorBoundary>

...

<Something /> // Oops missed that one
```

**Comment by jedwards1211** [comment] 2017-07-07 06:59
Every time I get an error in a `render` method I have to scroll up through dozens of errors from React being in a broken state to find the error from my code that actually blew it up.  That's the biggest difficulty it causes me.

And now that `react-transform-catch-errors` is deprecated but `react-hot-loader` 3 doesn't really do the same thing, I'm not sure how to make my life easiest in this regard.

**Comment by jedwards1211** [comment] 2017-07-07 07:09
Perhaps concern about the try-catch performance penalty will soon be obsolete: https://stackoverflow.com/a/19728876/200224

Not only does one comment mention that V8 will eventually be able to optimize functions containing a try-catch block, that answer explains that most of the performance penalty can be avoided by moving the try-catch into a wrapper function so that the main function which could throw can be optimized.

**Comment by gaearon** [comment] 2017-07-07 10:33
@jedwards1211 

>That's the biggest difficulty it causes me. I sort of wish React would could just stop dead and not even throw any more errors, since it would be easier for me to find the root cause, and it's not really in a viable state anyway.

Yes, and this is exactly what we’re doing in React 16. 😉 

>react-hot-loader v3 doesn't seem to manage to wrap all of my functional stateless components... it would be really helpful if there were a supported way to guarantee a dev tool (i.e. in dev mode if not prod) would show a redbox if any rendering throws an error.

Please read my comment above: https://github.com/facebook/react/issues/2461#issuecomment-311077975. This is pretty much what we’ve added.

**Comment by jedwards1211** [comment] 2017-07-07 14:09
@gaearon oh, I see.  That will be nice, though for

**Comment by jedwards1211** [comment] 2017-07-07 14:25
...nevermind, I thought `react-guard` made it possible to display a redbox in place of the component that failed, but it appears to display the redbox in place of the root component.

**Comment by gaearon** [comment] 2017-07-07 15:12
Error boundaries don't have to be at the root, as I mentioned before. You can put them in a few strategic places (e.g. route handler wrapper, and important components big enough to show a useful box).

I don't think it's a good idea to show them in place of every individual components. Components can be offscreen, or too little to show the box. In fact in DEV I'd probably always want to see a fullscreen error.

We still haven't decided what's the default way to show error boxes in React 16. @bvaughn was prototyping this at some point. We'll get back to it before the release.

**Comment by bvaughn** [comment] 2017-07-08 00:50
👍 I look forward to exploring this a bit more, hopefully soon

**Comment by btnwtn** [comment] 2017-07-17 18:58
Is `unstable_handleError` going to be the official name of the method in React 16?

**Comment by gaearon** [comment] 2017-07-17 19:04
No. We settled on `componentDidCatch`.

**Comment by ivansglazunov** [comment] 2017-07-25 10:11
@gaearon  `componentDidCatch` just for current component or for childs too?

**Comment by gaearon** [comment] 2017-07-25 10:23
It catches for the whole subtree (but not for the component itself).

**Comment by gaearon** [comment] 2017-07-26 22:42
Catching errors in child components is now supported.
You can use the new `componentDidCatch()` hook in [React 16 Beta 1 which you can try now](https://github.com/facebook/react/issues/10294).

You can read more about this feature in our new blog post: [Error Handling in React 16](https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html).

I think we can close this issue. It is likely the feature will evolve over time, and we’d love your feedback, but let’s discuss it in more focused future issues.

**Closed by gaearon** 2017-07-26 22:42 UTC
Labels: big picture
