### ISSUE TITLE
Show property type of value (string,int,etc) on state/props.

### ISSUE THREAD

**Issue by gydotitulaer** [facebook/react#16545] opened 2019-08-22 14:37 UTC
**feature**

**What is the current behavior?**
On the new developer tool you are unable to see what property type the value. You used to be able to see if the value was a string or int because of the quotation marks (for example id: "1" (string) or id: 1 (int)). Both string and int are shown without quotes.

**What is the expected behavior?**
I want to see if the value inside the prop or state is an string or integer by using quotation marks on the value.
`id: "1"`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I'm using version:
4.0.5 (8/19/2019)

Did this work in previous versions of React?
Yes, 3.*

**Comment by bvaughn** [comment] 2019-08-23 03:01
> On the new developer tool you are unable to see what property type the value. ou used to be able to see if the value was a string or int

You still can. Numbers use `<input type="number">` (which shows the up/down stepper). Booleans use `<input type="checkbox">`. Strings use `<input type="text">`.

**Comment by bvaughn** [comment] 2019-08-23 03:03
I do hear you though. This is currently kind of limited in that the type isn't super clear, but worse- you can't _change_ the type if you want to.

The style editor supports different types using JSON.parse. We could probably do the same here.

We actually already have an issue tracking this, so I'm just going to mark this one as a duplicate of #16476. 😄

**Closed by bvaughn** 2019-08-23 03:03 UTC
Labels: Component: Developer Tools, Type: Feature Request

**Comment by gydotitulaer** [comment] 2019-08-23 07:54
> > On the new developer tool you are unable to see what property type the value. ou used to be able to see if the value was a string or int
> 
> You still can. Numbers use `<input type="number">` (which shows the up/down stepper). Booleans use `<input type="checkbox">`. Strings use `<input type="text">`.

Hey bvaughn,

Thanks for your reply, i did meant the data inside a prop or state as you mentioned in your second post.

When I was developing I quickly looked into the editor to check what type of data my number was, so i could set my PropType to number or string. The editor made me think it was a int. But yea thanks again for your reply and i'll keep track of the other issue.
