### ISSUE TITLE
Bug: Property length undefined in Profiler

### ISSUE THREAD

**Issue by itsezc** [facebook/react#20583] opened 2021-01-13 22:36 UTC
React version:  17.0.1

Error happens while trying to use the profiler on my React app on Chrome

## The current behavior
```
Call stack: at getChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19767:32)
at ProfilingCache_ProfilingCache.getFlamegraphChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19992:11)
at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34007:32)
at Hh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:12871:7)
at qi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13521:7)
at nk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16162:86)
at mk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15541:11)
at lk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15533:23)
at dk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15517:5)
at Xj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15129:105)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33986:50)
at div
at div
at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28048:3)
at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35614:50)
at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29061:5)
at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29178:32)
at div
at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32776:3)
at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24164:3)
at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24653:3)
at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29246:3)
at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36049:3)
```

Worked absolutely fine on older versions of the Chrome extension.

**Comment by eps1lon** [comment] 2021-01-14 09:47
Thanks for the report

> Error happens while trying to use the profiler on my React app on Chrome

Could you elaborate a bit more on this point:

1. Does this happen with every app or just your app? If it only happens with your app can you reduce this to a minimal example and share with us?
2. What exact steps in the profiler lead to this error?

**Comment by itsezc** [comment] 2021-01-22 00:09
- This happens on all apps that I open
- It occurs when trying to view the flame graph after a recording

**Comment by eps1lon** [comment] 2021-01-22 08:22
> This happens on all apps that I open

It would help us a lot if you can share one of those apps. As minimal as possible until you can no longer reproduce the error. "all apps that I open" is a bit ambiguous since all the apps you did open might use a specific React API that causes this issue.

**Comment by bvaughn** [comment] 2021-01-22 15:03
Yeah, unfortunately this isn't very actionable for us at the moment. (Profiler works fine for me.) Getting access to one of your apps (or better yet a smaller reduced test case) would be very helpful though!

**Comment by Vrishtrix** [comment] 2021-01-22 18:35
I have the same issue on Opera 63 with the latest React Dev Tools via Chrome extensions on ElementaryOS. Any help?

**Comment by bvaughn** [comment] 2021-04-13 15:45
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-04-13 15:45 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed
