### ISSUE TITLE
Chrome SVG bug

### ISSUE THREAD

**Issue by kulicuu** [facebook/react#4398] opened 2015-07-16 08:17 UTC
##### chromium svg bug report
July 16, 2015  

Also see the same bug registered with Chromium at: [chromium issue 513167](https://code.google.com/p/chromium/issues/detail?id=513167)

###### to run the reduced-test-case:
https://github.com/Terebinth/Vickers/tree/chrome_svg_bug
You don't even need to clone the repo.  From the the /build folder get vickers.html and vickers__packed.js, save them locally to same folder.  Then open the html in Firefox and Chrom(e/ium).

##### please note:
_This bug occurs in Chrome but not in Firefox. The app works **fine** in Firefox._

I'm using Chromium version  43.0.2357.81 , on Ubuntu 14.04 64 bit

##### Description of the app:

The app implements MineSweeper.  There is an 8x8 grid of 64 tiles.

At the beginning of the game all of the tiles will be showing the `water_000` component, which is currently a fuzzy blue ring over lightblue.

You can click the tiles to reveal them. Non-mine tiles will show a number ; mined tiles will show a black mine glyph over a gold/purple gradient disk.

Right clicking a non-revealed tile will flag that tile.  The flag glyph is a fuzzy grey disk over black background.

The game does not end when clicking on and revealing a mine.  This is the programmed behaviour for development purposes.

##### Description of the bug:

**Chrome only**

1. Clicking a mined tile causes all of the tiles other than the revealed mine tile(s) to go completely black.  This is not programmed behaviour.  Feel free to test in Firefox; those tiles should stay as they were.  It's not programmed behaviour that all those tiles go black.

2. Right clicking to flag a tile has a variety of possible unintended effects:
    - If the board is fresh or no mines are revealed, the first click to toggle on the flag will work; the second click to remove the flag will also work; the third click will make every other tile on the board transparent except for a border region. The fourth click will return all the other tiles to their appropriate state (the visual state they would have without the bug) .
    - If the board has had all its tiles blackened by the revealing of a mine(s), then the behaviour of the tiles that are not revealed mines is as in first bullet above; the behaviour of revealed mines is to cycle through various states of visual mutation and decomposition of the SVG glyph. This starts on the third toggling of the flag, where the mine disappears (but not its halo ring), then it reappears on th fourth toggling, then on the fifth toggling it goes through some more subtle mutation, then it cycles through these states on subsequent togglings.

##### Reduced-test-case

I've attempted a reduced-test-case for this bug.  Unfortunately, as the bug involves interaction logic and visual detail, I wasn't able to reduce it all that much.

**Comment by kulicuu** [comment] 2015-07-16 10:13
I suspect I know something of what may be going on.  Just a hunch. 

The app is a composition of SVGs, with a lot of filtering and gradient attributes being computed.  As transitions go on, some of the attribute namespaces may collide and do weird things to the attributes, hence the subtle effects on the mine glyphs when toggling flags.

Also, I've been doing more testing with Firefox today (on master branch development) and found there are some (usually more subtle) issues creeping into things with Firefox also.  

I'll update here as I learn more.

**Comment by kulicuu** [comment] 2015-07-23 08:41
I'm going to list possibly related Chromium bugs here:

https://code.google.com/p/chromium/issues/detail?id=411906

**Comment by spicyj** [comment] 2015-07-23 18:59
This doesn't sound like a React bug to me so I'm going to close this issue. If you do find that it's caused by React, let us know and we'll revisit.

**Closed by spicyj** 2015-07-23 18:59 UTC

**Comment by kulicuu** [comment] 2015-07-24 03:29
Agreed, thanks.
