### ISSUE TITLE
unexpected re-render between different node_env

### ISSUE THREAD

**Issue by CVarisco** [facebook/react#10413] opened 2017-08-08 20:20 UTC
Hi 🙂 

**Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug that gets me crazy!

**What is the current behavior?**
We found a very strange behavior between the development version and the production one.
We don't know why but with the production build when a redirect happens the entire tree under the switch component is re-rendered from scratch.
### NODE_ENV = development
![dev](https://user-images.githubusercontent.com/7335613/29087007-c5ff4b60-7c74-11e7-8585-2bf1b0fdd8e5.gif)

### NODE_ENV = production
![prod](https://user-images.githubusercontent.com/7335613/29087006-c5fd1cbe-7c74-11e7-84fc-f15a7460a8c1.gif)

We noticed that in the production env keys are generated every time the route changes.
I opened an [issue](https://github.com/ReactTraining/react-router/issues/5421) on react-router repos also.
We tried also to don't minify anything and the result it is the same.

Someone knows why this is happening and what may be causing it? 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: 15.5.4
react-router-dom: 4.1.1
OS: MacOS Sierra Version 10.12.4
Browser: Google Chrome Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by gaearon** [comment] 2017-08-09 01:15
Could you please provide a full example?

**Comment by CVarisco** [comment] 2017-08-09 10:05
Hi @gaearon,
Thanks for your support 👍 

I created a repo [here](https://github.com/CVarisco/re-render-bug) with the same structure of our project (I can't pass the entire project).
But I can't reproduce the issue in this project 🙁 . 

Could be something on our project... but what?

We think that could be the `Loader` component that mounting every time when we fetch the user on redirect, but why we don't have the same behavior on dev?

**Comment by aweary** [comment] 2017-09-15 21:31
SInce there's been no update on this, and there's no reproduction that we can investigate, I'm going to close this out. If you can isolate the issue further and provide a clear reproduction that demonstrates an issue with React, I'll be happy to help and re-open!

If you need general help figuring out how to isolate or resolve this issue I suggest checking out the resources listed in [Where to Get Support](https://facebook.github.io/react/community/support.html).

**Closed by aweary** 2017-09-15 21:31 UTC
Labels: Need More Information

**Comment by bhoomipatel6386** [comment] 2018-05-30 20:57
@CVarisco  I have the same problem . Did you figure out what was the problem ?

**Comment by CVarisco** [comment] 2018-05-31 07:58
@bhoomipatel6386 Updating version of React should solve the issue.
If not, probably was related on our env.

Sorry man 🙁
