### ISSUE TITLE
Bug: react-hooks/exhaustive-deps reports a TypeScript type via typeof as a dependency

### ISSUE THREAD

**Issue by RebeccaStevens** [facebook/react#19327] opened 2020-07-12 23:48 UTC
react-hooks/exhaustive-deps reports a missing dependency when a variable is used purely for it's type.

Once the typescript code has been transpiled, that variable will no longer be referenced in that part of the code and thus it's not a dependency.

React version: react@16.13.1
Eslint Plugin version: eslint-plugin-react-hooks@4.0.7

## Steps To Reproduce

1. Have some typed variable declared in the component.
2. Within a hook callback, refer to that variable's type via `typeof x`

Link to code example: https://codesandbox.io/s/late-sun-rpws4?file=/src/App.tsx

## The current behavior

An eslint error such as the following occurs:

`react-hooks/exhaustive-deps - "React Hook useEffect has a missing dependency: ..."`

## The expected behavior

No error should occur.

**Comment by rickhanlonii** [comment] 2020-07-13 02:31
Oh nice find @RebeccaStevens, confirmed. Any interest in working on a PR?

**Comment by rickhanlonii** [comment] 2020-07-13 03:07
Actually this may be a dupe of https://github.com/facebook/react/issues/18828.

And the related PR https://github.com/facebook/react/pull/19316 may fix it already.

**Comment by RebeccaStevens** [comment] 2020-07-13 03:33
Looks, like it is. Sorry for the dupe.

**Comment by rickhanlonii** [comment] 2020-07-13 04:07
No worry! Let's keep this open in case it's slightly different and to make sure we add a test case for this specific example 👍

**Comment by gaearon** [comment] 2020-07-13 17:03
@delca85 fixed this in #19316. If you find other similar issues, please report them too! Thanks.

`eslint-plugin-react-hooks@4.0.8` should have the fix.

**Closed by gaearon** 2020-07-13 17:03 UTC
Labels: Component: ESLint Rules, Component: Hooks, good first issue
