### ISSUE TITLE
Unknown DOM property autocomplete when W3C spec says HTMLInputElement.autocomplete, autofocus

### ISSUE THREAD

**Issue by binki** [facebook/react#10139] opened 2017-07-11 02:53 UTC
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

I get:

> Warning: Unknown DOM property autocomplete. Did you mean autoComplete?

When I use `autoComplete` works fine.

This is misleading because the name of the DOM property is `autocomplete`, not `autoComplete`. React implies that the DOM property is named differently than it really is.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

https://jsfiddle.net/binki/84v837e9/133/

**What is the expected behavior?**

Accepts `autocomplete`, rejects `autoComplete`.

*OR*

The error message should not claim that `autoComplete` is the name of a DOM property because it isn’t. I don’t see any mention of a DOM property called `autoComplete` in the IDL documentation for [`HTMLInputElement`](https://www.w3.org/TR/html5/forms.html#htmlinputelement), but I do see mention of `autocomplete`. It should claim that `autoComplete` is a “React property name mapped onto a differently-named DOM property” or use some other wording (I’m not good at coming up with wordings).

```js
> typeof document.createElement('input').autocomplete
"string"
> typeof document.createElement('input').autoComplete
"undefined"
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react-15.6.1

Same issue exists for at least `HTMLInputElement.autofocus`.

**Comment by gaearon** [comment] 2017-07-11 10:09
Thanks for the report!

React generally uses `camelCase` convention for JSX property names. This is a duplicate of https://github.com/facebook/react/issues/2882.

We might revisit this some time in the future, but this is intentional and not a bug.

**Closed by gaearon** 2017-07-11 10:09 UTC
