### ISSUE TITLE
SVG elements missing

### ISSUE THREAD

**Issue by kulicuu** [facebook/react#6146] opened 2016-02-29 18:45 UTC
I've built and run v15 alpha, and still cannot use SVG elements like `foreignObject` and `filter`.  
The issue closure messages implied that the related tied-in issues were fixed (and they were closed), but these issues are not fixed, just passed over.  Should reopen a general SVG issue ticket to address these.

**Comment by jimfb** [comment] 2016-02-29 18:48
What do you mean by "cannot use"?  Do you get an error message?  Do they get filtered out?  Do they fail in subtle ways?  What specifically is the issue?

It would be helpful if you can provide a minimal testcase (in a jsfiddle, feel free to fork http://jsfiddle.net/9kungxn4/) that describes the expected behavior and demonstrates that the actual behavior differs.

**Comment by kulicuu** [comment] 2016-03-01 13:13
```coffeescript
c = -> console.log.apply console, arguments
{p, div, h1, h2, h3, h4, h5, h6, span, svg, circle, rect, ul, line, li, ol, code, a, input, defs, clipPath, linearGradient, stop, g, path, d, polygon, image, pattern, filter, feBlend, feOffset, polyline, feGaussianBlur, feMergeNode, feMerge, radialGradient, foreignObject, text, ellipse} = React.DOM
c "React", React
c "React.version", React.version
c 'foreignObject', foreignObject
c 'filter', filter
c 'text', text
c 'circle', circle
c 'rect', rect
c 'svg', svg
c 'React.DOM', React.DOM
```

gives:

```
React Object { Children: Object, Component: ReactComponent(), createElement: ReactElementValidator.createElement(), cloneElement: ReactElementValidator.cloneElement(), isValidElement: ReactElement.isValidElement(), PropTypes: Object, createClass: ReactClass.createClass(), createFactory: ReactElementValidator.createFactory(), createMixin: React.createMixin(), DOM: Object, 4 more… } instant_chat.js:332:11
React.version 0.15.0-alpha.1 instant_chat.js:332:11
foreignObject undefined instant_chat.js:332:11
filter undefined instant_chat.js:332:11
React.DOM Object { a: function (), abbr: function (), address: function (), area: function (), article: function (), aside: function (), audio: function (), b: function (), base: function (), bdi: function (), 122 more… }
```

**Comment by jimfb** [comment] 2016-03-02 20:08
Ah, gotcha.  I honestly forgot React.DOM existed and thus had no idea what you were talking about :).

React.DOM are just convenience wrappers around React.createElement for DOM components.  You could always use `React.createElement('filter');` or `React.createElement('foreignObject');`

Browsers are constantly adding new element types, and maintaining a huge whitelist of all of them is out of scope.  Same goes for SVG.  We are looking to move away from maintaining whitelists.  Eventually you will hit an element not on our whitelist and will need to break out and use `createElement` instead.

For this reason, I'm going to close the issue, since we aren't going to track all the separate elements in `React.DOM` individually.  If you want to submit a PR for all the SVG elements, I bet other SVG users would appriciate it.

The file you will want to look at for a PR is [ReactDOMFactories.js](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactDOMFactories.js)

**Closed by jimfb** 2016-03-02 20:08 UTC

**Comment by kulicuu** [comment] 2016-03-03 06:24
Ah awesome thankyou !  I was hoping I was missing something.
