### ISSUE TITLE
Bug: Internal React error: Expected static flag was missing. Please notify the React team.

### ISSUE THREAD

**Issue by Mumujianguang** [facebook/react#25589] opened 2022-10-31 04:37 UTC
After I upgraded the React version of the project from 16.14.0 to 18.2.0, the console reported the following warning after the project started

```
Warning: Internal React error: Expected static flag was missing. Please notify the React team.
```
![image](https://user-images.githubusercontent.com/52249626/198931381-bf4cb492-398d-480a-9d9b-a8576a1aa430.png)

I don't know the specific cause of the bug

**Comment by eps1lon** [comment] 2022-10-31 08:06
Duplicate of https://github.com/facebook/react/issues/24391

**Closed by eps1lon** 2022-10-31 08:06 UTC
