### ISSUE TITLE
React Developer Tools Chrome Extension causes an error.

### ISSUE THREAD

**Issue by brave-merida** [facebook/react#17402] opened 2019-11-19 10:39 UTC
Hi,
I found a bug.

My project is using `Uppy` (https://uppy.io/).
When I use `React Developer Tools` Chrome extension, my app is crashing.
If I disable the extension then my app works without crashing.

![image](https://user-images.githubusercontent.com/30062357/69139166-eba85200-0afa-11ea-805c-ca3cceafda9f.png)
 
![image](https://user-images.githubusercontent.com/30062357/69139406-62dde600-0afb-11ea-9d50-b6bc82426d9d.png)

react: 16.8.6
@uppy: 0.30.4

**Comment by threepointone** [comment] 2019-11-19 14:25
Could you please share a reproducing example with codesandbox or as a git repo? It's hard to tell what's happening without some code. Thanks!

**Comment by bvaughn** [comment] 2019-11-26 19:42
The bottom two error screenshots above don't look like they are DevTools. The call stacks shown in the error messages seem to refer to uppy code.

The top one seems to suggest a legacy React version (v15?) is passing an invalid argument to DevTools. Given that you reference React v16.8 above, I think there's something else running React on your page as the `_topLevelWrapper` codepath is only run for legacy React versions (before v16).

We're going to need to be able to repro this issue, as Sunil mentions.

**Comment by bvaughn** [comment] 2019-12-10 19:01
Closing due to lack of info.

**Closed by bvaughn** 2019-12-10 19:01 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
