### ISSUE TITLE
CSSTransitionGroup transitions don't fire reliably unless `transition` set on -active class

### ISSUE THREAD

**Issue by deadlyicon** [facebook/react#2104] opened 2014-08-28 16:54 UTC
Here is an example of how `<ReactCSSTransitionGroup>` is explained in the README:

http://jsfiddle.net/deadlyicon/kb3gN/4984/

It works. 

Here is that same example except I've added a `componentDidMount` method that focuses a button within the component being transitioned:

http://jsfiddle.net/deadlyicon/kb3gN/4985/

Notice how the `enter` transition fails to animate.

This is possibly a browser bug but I thought I'd let you know anyway. 

It's also worth noting that this bug can be worked around by moving the `transition` out of `.example-enter` and into `.example-enter.example-enter-active` like so:

http://jsfiddle.net/deadlyicon/kb3gN/4986/

Hope this helps improve React :D

**Comment by rmosolgo** [comment] 2015-01-17 00:03
I don't have a ton to add here, but I'll tell my story: 

I added a `CSSTransitionGroup` around a hidden input with `autoFocus=true`. 

At first, I put `transition` on the non-active classes, as I read in the docs:

```sass
.new-pass
  $icon-height: 300px
  height: $icon-height
  overflow-y: hidden

  &.slide-enter
    max-height: 0px
    transition: max-height .3s ease-in-out

    &.slide-enter-active
      max-height: $icon-height

  &.slide-leave
    max-height: $icon-height
    transition: max-height .3s ease-in-out

    &.slide-leave-active
      max-height: 0px
```

But, on a really old iPad, it gave me a weird jump at the end of the `enter` animation. Happily, I could reproduce on the emulator. When you tapped "Add a barcode", it would open, then jump closed, then jump open again.

(There's a hidden, auto-focused input there, too. It's supposed to take input from a barcode scanner.)


![barcodes-animation](https://cloud.githubusercontent.com/assets/2231765/5786348/53a15594-9d98-11e4-9a88-62fed1f095a0.gif)


I found this thread and tried moving the `transition` stuff to the `-active` classes:

```sass
.new-pass
  $icon-height: 300px
  height: $icon-height
  overflow-y: hidden

  &.slide-enter
    max-height: 0px

    &.slide-enter-active
      max-height: $icon-height
      transition: max-height .3s ease-in-out

  &.slide-leave
    max-height: $icon-height

    &.slide-leave-active
      max-height: 0px
      transition: max-height .3s ease-in-out
```


Then everything was  :cake:

**Comment by gilbarbara** [comment] 2015-03-06 14:25
I was having trouble with the `-enter` transition been skipped with "some" components that use componentWillMount and/or componentDidMount.
Moving the transition to the `-enter-active` fixed it, although it seems counter-intuitive to me.
Weird!

**Comment by nmn** [comment] 2015-03-06 16:30
My last problem was probably a special case. I was unable to detect what caused it to happen. In newer versions of React, CSSTransitionGroup breaks very often. TransitionGroup seems to work fine most of the times though.

I get an error with CSSTransitionGroup saying that the callback failed to fire, so there is at least some sort of detection going on. I think the CSSTransitionGroup should rely on a timeout if the callback fails to fire.

**Comment by ffxsam** [comment] 2015-09-13 19:31
>Notice where the transition is - it's on the .enter.active css rule, not on the .enter

Thank you! Moving `transition` to my `.modal-appear-active` class fixed this.

**Comment by malectro** [comment] 2015-10-27 23:20
moving the `transition` rule to `active` didn't fix the focus-on-mount issue for me, but deferring the `focus` call using something like lodash `defer` made the transitions work again.

**Comment by gaearon** [comment] 2016-10-27 13:59
Closing since this is not actionable for us.

**Closed by gaearon** 2016-10-27 13:59 UTC
Labels: Component: Addons / TransitionGroup
