### ISSUE TITLE
Incorrect blame for checksum mismatch due to browsers unescaping HTML

### ISSUE THREAD

**Issue by voideanvalue** [facebook/react#3465] opened 2015-03-20 00:43 UTC
React uses `escapeTextContentForBrowser` to escape `'` to `&#x27;` and `"` to `&quot;` (amongst other things). But browsers seem to unescape back to `'` and `"`, potentially causing incorrect blame in case of checksum mismatches.

Demo: http://jsfiddle.net/voideanvalue/txoe3dpa/
In the console:
```
(client) ">test &amp;&gt;&lt;&quot;&#x27; test te
(server) ">test &amp;&gt;&lt;"' test test</div>
```
Reproducible in latest stable releases of Chrome, Firefox and Safari on OS X.

I'm not sure what would be a good way to fix this. Re-escaping `"` to `&quot;` and `'` to `&#x27;` in `rootMarkup` before comparing calling `firstDifferenceIndex` (https://github.com/facebook/react/blob/a321247ee5c6a51f4cf9feec4c8989a769bcd78a/src/browser/ui/ReactMount.js#L830) would likely escape unrelated characters as well and unescaping both `markup` and `rootMarkup` before comparing would not produce an exact diff (unless we were to keep track of the unescapes performed before comparing and then revert them while producing the diff string, but that sounds like going through more trouble than might be needed).

**Comment by spicyj** [comment] 2015-03-20 00:47
Dupe of #3399.

**Closed by spicyj** 2015-03-20 00:47 UTC
