### ISSUE TITLE
Disabled radio button fires onChange event from double click in Internet Explorer.

### ISSUE THREAD

**Issue by lawrence-yu** [facebook/react#6069] opened 2016-02-19 00:15 UTC
In Internet Explorer, a disabled radio button will fire an onChange event when double clicked.  The checked state does not change, but the onChange event fires nonetheless.

http://jsfiddle.net/abzosdau/4/

**Comment by jimfb** [comment] 2016-02-19 17:33
Duplicate of https://github.com/facebook/react/issues/4457

**Closed by jimfb** 2016-02-19 17:33 UTC
