### ISSUE TITLE
Really strage error when pressing F5

### ISSUE THREAD

**Issue by martijnhiemstra** [facebook/react#9591] opened 2017-05-03 06:29 UTC
I work for a company and we are converting the previous server side website to react with rest services. We have started making components we when we press F5 we get the following error in the console. 

Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().

Also the browser jumps to a completly different url. We use a container with 2 components in it

Any solutions?

**Comment by gaearon** [comment] 2017-05-03 06:48
Please provide a project reproducing the problem.

**Comment by tsriram** [comment] 2017-05-03 06:48
Guess we need more details or probably a jsfiddle with a minimal code required to see the error would help. You may want to use this template - https://jsfiddle.net/84v837e9/

**Comment by martijnhiemstra** [comment] 2017-05-03 07:21
Our website has been designed by different people. I am currently going through the code and I have noticed the different programming styles when I look at the code. 

Right now we have a ComponentA that is defined with a function:

```
export default function ComponentA(props){
  return (
    <ComponentB />
  )
}
```

and ComponentB is defined with extending React.Component

```
class ComponentB extends React.Component {
  render() {
    const {propA} = this.props
    <div>
        <ComponentC />

        <ComponentD />
      </div>
  }
}

```

ComponentC is a function and ComponentD is a class. Is it okay to mix the function and class options or must all component extend React.Component?

**Comment by gaearon** [comment] 2017-05-03 07:25
It's totally fine to use both functions and classes, but this code looks wrong:

```js
class ComponentB extends React.Component {
  render() {
    const {propA} = this.props
    <div>
        <ComponentC />

        <ComponentD />
      </div>
  }
}
```

It’s missing a `return` statement here:

```js
class ComponentB extends React.Component {
  render() {
    const {propA} = this.props
    return ( // <------ don't forget to return!
      <div> 
        <ComponentC />

        <ComponentD />
      </div>
    );
  }
}
```

Does this fix the issue? Regardless, it is strange that you didn’t get a proper error (the one you posted is just a byproduct of an earlier mistake, if my diagnosis is correct).

So I have three questions:

1) Does my fix help?
2) Are you sure you only see one error in console, and not more?
3) If you only see one error, can you check "Pause on Caught Exceptions" in Chrome Sources pane? I think your code might be swallowing the original error (e.g. in a `try` / `catch` block).

<img width="228" alt="screen shot 2017-05-03 at 08 25 15" src="https://cloud.githubusercontent.com/assets/810438/25651279/210c5648-2fda-11e7-8bcd-43f98c770c23.png">

**Comment by domenikasd** [comment] 2017-05-03 07:36
I can explen the language when arrival home I see the message the Greek .thenk you stay withe me k help me please I am afraid.
--
Sent from myMail for Android Τετάρτη, 03 Μαΐου 2017, 10:28π.μ. +03:00 from Dan Abramov  notifications@github.com :

>It's totally fine to use both functions and classes, but this code looks wrong:
>class ComponentB extends React.Component {
  render() {
    const {propA} = this.props
    <div>
        <ComponentC />

        <ComponentD />
      </div>
  }
}
>It’s missing a return statement here:
>class ComponentB extends React.Component {
  render() {
    const {propA} = this.props
    return ( // <------ don't forget to return!
      <div> 
        <ComponentC />

        <ComponentD />
      </div>
    );
  }
}

**Comment by martijnhiemstra** [comment] 2017-05-03 07:51
@gaearon 

I am now using Chrome which apparently has much better logging that firefox. In chrome I see this in the console:

Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().
Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().
    at invariant (http://localhost:4300/myapp/app/index.js:16322:16)
    at Object.onSetChildren (http://localhost:4300/myapp/app/index.js:18947:71)
    at callHook (http://localhost:4300/myapp/app/index.js:23599:9)
    at emitEvent (http://localhost:4300/myapp/app/index.js:23611:8)
    at Object.onSetChildren (http://localhost:4300/myapp/app/index.js:23828:6)
    at ReactDOMComponent.setChildrenForInstrumentation (http://localhost:4300/myapp/app/index.js:29831:39)
    at ReactDOMComponent._updateChildren (http://localhost:4300/myapp/app/index.js:30034:40)
    at ReactDOMComponent.updateChildren (http://localhost:4300/myapp/app/index.js:29973:13)
    at ReactDOMComponent._updateDOMChildren (http://localhost:4300/myapp/app/index.js:27164:13)
    at ReactDOMComponent.updateComponent (http://localhost:4300/myapp/app/index.js:26982:11)

index.js:79111 Uncaught TypeError: Cannot read property 'componentWillEnter' of undefined
    at Constructor.performEnter (http://localhost:4300/myapp/app/index.js:79111:19)
    at Array.forEach (native)
    at Constructor.componentDidUpdate (http://localhost:4300/myapp/app/index.js:79066:18)
    at measureLifeCyclePerf (http://localhost:4300/myapp/app/index.js:30592:13)
    at http://localhost:4300/myapp/app/index.js:31244:12
    at CallbackQueue.notifyAll (http://localhost:4300/myapp/app/index.js:23113:23)
    at ReactReconcileTransaction.close (http://localhost:4300/myapp/app/index.js:33521:27)
    at ReactReconcileTransaction.closeAll (http://localhost:4300/myapp/app/index.js:24291:26)
    at ReactReconcileTransaction.perform (http://localhost:4300/myapp/app/index.js:24238:17)
    at ReactUpdatesFlushTransaction.perform (http://localhost:4300/myapp/app/index.js:24225:21)

index.js:79143 Uncaught (in promise) TypeError: Cannot read property 'componentWillLeave' of undefined
    at Constructor.performLeave (http://localhost:4300/myapp/app/index.js:79143:19)
    at Array.forEach (native)
    at Constructor.componentDidUpdate (http://localhost:4300/myapp/app/index.js:79070:18)
    at measureLifeCyclePerf (http://localhost:4300/myapp/app/index.js:30592:13)
    at http://localhost:4300/myapp/app/index.js:31244:12
    at CallbackQueue.notifyAll (http://localhost:4300/myapp/app/index.js:23113:23)
    at ReactReconcileTransaction.close (http://localhost:4300/myapp/app/index.js:33521:27)
    at ReactReconcileTransaction.closeAll (http://localhost:4300/myapp/app/index.js:24291:26)
    at ReactReconcileTransaction.perform (http://localhost:4300/myapp/app/index.js:24238:17)
    at ReactUpdatesFlushTransaction.perform (http://localhost:4300/myapp/app/index.js:24225:21)

**Comment by martijnhiemstra** [comment] 2017-05-03 08:33
I updated some packages in npm and that made the index.js:79111 Uncaught TypeError: Cannot read property 'componentWillEnter' of undefined go away

The main error occures in 

`var ReactComponentTreeHook = {`

on the line

`!nextChild.isMounted ? process.env.NODE_ENV !== 'production' ? invariant(false, 'Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().') : _prodInvariant('71') : void 0;`

This only happens in non production mode and what I notice is !nextChild.isMounted
Does this imply that is executed because a child component is not mounted? If so how can that happen?

**Comment by gaearon** [comment] 2017-05-03 14:25
I need an example I could run to debug this.

**Comment by aweary** [comment] 2017-09-20 16:03
Since there was no example provided, I'm going to close this out. If anyone can provide an example reproducing this issue with the latest version of React, feel free to ping me and we can investigate.

**Closed by aweary** 2017-09-20 16:03 UTC
Labels: Status: Unconfirmed

**Comment by MehdiAlouafi** [comment] 2017-11-16 16:44
I was having this error because I was missing an import statement and I corrected it by importing the missing component
