### ISSUE TITLE
Bug: Rules of hooks lint rule doesn't catch some uses of custom hooks

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#25728] opened 2022-11-22 12:32 UTC
React version: Latest

## Steps To Reproduce

```js
import * as hooks from "bundle-o-hooks";

function MyComponent({x}) {
    if (x > 1) {
        const something = hooks.useAHook(); // not flagged
     }
}
```

## The current behavior

The current hook-matching rules only counts bare identifiers or member expressions where the target object is in Pascal case

https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L25-L44

## The expected behavior

I'd like the pascal case restriction to be removed, or at least have the docs updated, as neither the existing docs nor the beta docs mention this additional rule for what gets considered a hook by the linter.

**Comment by eps1lon** [comment] 2022-11-24 14:56
Duplicate of https://github.com/facebook/react/issues/25472

**Closed by eps1lon** 2022-11-24 14:56 UTC
Labels: Status: Unconfirmed
