### ISSUE TITLE
setValueForProperty @ DOMPropertyOperations.js:142 throwing untraceable/unpausable error

### ISSUE THREAD

**Issue by tnrich** [facebook/react#9984] opened 2017-06-16 06:21 UTC
Hey there,

I am getting the following error many time over in my console:

```
Error: <path> attribute d: Expected number, "…A 111 111 0 0 1 NaN NaN L NaN Na…".
setValueForProperty @ DOMPropertyOperations.js:142
_updateDOMProperties @ ReactDOMComponent.js:873
mountComponent @ ReactDOMComponent.js:514
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountComponentIntoNode @ ReactMount.js:104
perform @ Transaction.js:140
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:320
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
./demo/src/index.js @ index.js:31
__webpack_require__ @ bootstrap 333c997…:659
fn @ bootstrap 333c997…:83
0 @ demo.js:139816
__webpack_require__ @ bootstrap 333c997…:659
(anonymous) @ bootstrap 333c997…:708
(anonymous) @ bootstrap 333c997…:708
DOMPropertyOperations.js:142 Error: <path> attribute transform: Expected number, "…ate(0,0) rotate(NaN,0,0) "
```

I've tried setting "pause on exceptions to true", but it doesn't seem to pause on the error. The actual error message itself is very unhelpful for debugging what the underlying issue is because I have many places in my component where I am rendering an svg path:
`Error: <path> attribute d: Expected number, "…A 111 111 0 0 1 NaN NaN L NaN Na…".`

Any help tracking down which <path> component is actually causing this error would be greatly appreciated. Thanks!!

**Comment by gaearon** [comment] 2017-06-16 09:44
Can you provide a project reproducing this?

**Comment by tnrich** [comment] 2017-06-16 17:32
Here ya go:
https://github.com/tnrich/wierd-react-error

**Comment by aweary** [comment] 2017-06-16 18:23
The issue is because [you're passing an invalid value to the `d` attribute](https://github.com/tnrich/wierd-react-error/blob/master/src/App.js#L13), specifically the `NaN`. If you remove the `NaN` you'll see the error goes away.

It is confusing why it's not pausing on this exception though, and I [can't reproduce outside of React](https://jsfiddle.net/6vucod3p/) which is strange. I must be missing something 🤔

**Comment by tnrich** [comment] 2017-06-16 18:37
Hey @aweary , yup, the issue in my mind is not that I'm hitting an error - that makes perfect sense if I'm passing NaN as a value to the path's d attribute - but that I'm not able to pause on that exception or get any type of stack trace leading me back to which element is causing the issue.

**Comment by aweary** [comment] 2017-06-19 15:31
@tnrich I'm wondering if this is a browser bug, I'm assuming you're using Chrome? Firefox doesn't seem to throw an error for invalid `d` values.

I discovered that it [throws the error even without JavaScript](https://jsfiddle.net/tmmt4u3o/). This might mean that Chrome is throwing this error in a way that isn't compatible with the provided debugging tools. Even [`window.onerror` isn't invoked](https://jsfiddle.net/0t1hfejo/) for this error.

This might be something that should be brought up the Chrome team instead.

**Comment by gaearon** [comment] 2017-07-11 11:53
I guess this is out of our control so I'm closing. Let me know if I'm mistaken.

**Closed by gaearon** 2017-07-11 11:53 UTC
