### ISSUE TITLE
Bug: Devtools extension not building in windows and ubuntu

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#27194] opened 2023-08-05 08:26 UTC
Devtools extension is not building in ubuntu and windows

Below is the extension build failing in ubuntu even though it says chrome extension has built
![bikid476@BIKISDESKTOP_ ~_react-1_packages_react-devtools-extensions 8_5_2023 1_40_08 PM](https://github.com/facebook/react/assets/72331432/597f6019-895b-4e1c-befa-8b7e6bab3dbe)

Below is the extension failing in windows
![bikid476@BIKISDESKTOP_ ~_react-1_packages_react-devtools-extensions 8_5_2023 1_51_08 PM](https://github.com/facebook/react/assets/72331432/d817153f-cc3a-40d5-9a19-6d015299017a)

It just fails with some artifact error!

@hoxyq 😅 My mac has gone dead and i am looking to tinker with devtools and have some ideas in plan to implement so we can fix this out and hopefully i can continue to work on devtools

**Comment by ketanbaitule** [comment] 2023-08-13 14:06
Pls add "Steps To Reproduce"

**Comment by hoxyq** [comment] 2023-09-21 10:55
Duplicate of https://github.com/facebook/react/issues/27193

**Closed by hoxyq** 2023-09-21 10:55 UTC
Labels: Status: Unconfirmed
