### ISSUE TITLE
Bug: Object(...) is not a function

### ISSUE THREAD

**Issue by hieusmiths** [facebook/react#18967] opened 2020-05-21 02:34 UTC
My React version:

"react": "^16.13.1"

## The current behavior

The first i'am using React with version 16.8.6 and met a bug (Object(...) is not a function)
In this component i'm using React.ContextAPI.

Then i updated React to version 16.13.1 and it not working.

Thank sou much React Team.

**Comment by HiMrHu** [comment] 2020-05-21 03:00
can you provide an example?

**Comment by hieusmiths** [comment] 2020-05-21 03:08
> can you provide an example?

I checked all example with Context API but i can't find any error.
Oh my god, bumm getup and have a bug :(

**Comment by HiMrHu** [comment] 2020-05-21 03:22
> > can you provide an example?
> 
> I checked all example with Context API but i can't find any error.
> Oh my god, bumm getup and have a bug :(

have a good day :)

**Comment by bvaughn** [comment] 2020-05-21 17:42
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-07-30 17:48
Since the issue is not currently actionable, I'm going to close this issue until more information is provided.

**Closed by bvaughn** 2020-07-30 17:48 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
