### ISSUE TITLE
React is slow when unmount 1000 components on page

### ISSUE THREAD

**Issue by dtuyenle** [facebook/react#16990] opened 2019-10-02 21:23 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
When unmount 1000 components. It takes more than 2 seconds to finish.

**What is the expected behavior?**
It should just throw the whole container node that contains these 1000 components without doing any diffing.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16. This is something with the way react-fiber works I think.

**Comment by threepointone** [comment] 2019-10-03 04:34
Please make a reproducing usecase on codesandbox or as a git repo. I’d also love to know more about your actual usecase?

**Comment by dtuyenle** [comment] 2019-10-03 04:46
@threepointone Thanks I will try to do it in a sandbox and have some benchmark but It is pretty straight forward. You just need to create 10000 div initial load then when click on a button, you empty that list. Benchmarking showing react going through 10000 items and unmount them. Currently I need to support SEO so I have to display all of these elements on page when load.

**Comment by lxender** [comment] 2019-10-03 14:10
I created an [example for this issue](https://codesandbox.io/s/busy-sky-4posz). According to the profiler, 1000 items render in less than 100ms. 10K items cannot be measured with the profiler, but it feels very slow.

@dtuyenle You could try to minimize the work on page load by resorting to a virtual list like [react-virtualized](https://github.com/bvaughn/react-virtualized) or taking advantage of React's performance tools like React.memo/useMemo.

**Comment by threepointone** [comment] 2019-10-03 14:57
I don’t understand why SEO would require you to render 10000 components. I’d recommend you profile your app to look for bottlenecks. Maybe every word doesn’t have to be a component. I’m not even sure React is the bottleneck here.

**Comment by dtuyenle** [comment] 2019-10-04 14:21
@lxender  For SEO I have to render them all at once. Putting a spinner does help though. So basically when user filter we show a spinner then when its done we remove the spinner.

**Comment by threepointone** [comment] 2019-10-07 10:50
@lxender can you verify if this behaviour is the same for prod mode? 

I'm going to close this because there's no extra information provided, and it appears you have a workaround. Happy to discuss if there are more details.

**Closed by threepointone** 2019-10-07 10:50 UTC
