### ISSUE TITLE
React Developer Tools chrome extension not detecting react

### ISSUE THREAD

**Issue by arcman7** [facebook/react#21213] opened 2021-04-08 22:37 UTC
Google Chrome
Version 89.0.4389.114 (Official Build) (x86_64)

macOS Big Sure
Version: 11.2.3 (20D91)

I'm developing on localhost. All-access, including file-urls and incognito mode, are allowed. 

Weird thing is the redux tool seems to be working just fine.

EDIT: I just realized that having a particular URL pattern breaks the react detection:
`http://localhost:3000/fakeframe/?link=http://localhost:3000/some/feature-im-working-on`
It's not using an iframe or anything, just a particular URL format used when doing certain things on our app. 

My problem is solved, but I'll leave this open for bug exposure in case anyone else runs into this.

**Comment by bvaughn** [comment] 2021-04-09 03:17
I don't think this issue is that helpful (at least to me as a maintainer) without any repro information.

**Comment by bvaughn** [comment] 2021-04-13 15:44
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-04-13 15:44 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
