### ISSUE TITLE
DOM attribute dateTime isn't lowercased when rendered to string

### ISSUE THREAD

**Issue by larsnystrom** [facebook/react#11492] opened 2017-11-08 20:06 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The DOM property `dateTime` isn't converted to its lowercase attribute counterpart `datetime` for the `<time>` element when the element is rendered with `ReactDOMServer.renderToString()`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

```
const React = require('react');
const ReactDOMServer = require('react-dom/server');

const markup = ReactDOMServer.renderToString(React.createElement('time', {
	dateTime: "2017-11-02T20:49:25+01:00"
}));
console.log(markup);
```

The above will print `<time dateTime="2017-11-02T20:49:25+01:00" data-reactroot=""></time>`.

**What is the expected behavior?**

The above output should be `<time datetime="2017-11-02T20:49:25+01:00" data-reactroot=""></time>`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.0.0
React DOM 16.0.0
Node v6.11.5

**Comment by gaearon** [comment] 2017-11-08 20:46
This is a duplicate of https://github.com/facebook/react/issues/10863.

We’re hesitant about this. **HTML is case-insensitive** so technically our behavior is correct even if a little surprising. There's absolutely nothing wrong with emitting attributes with any casing, even `DaTeTiMe` would be perfectly understood by browsers, and the difference would be completely unobservable for the client-side code.

Though we potentially can “fix” this to be less surprising (https://github.com/facebook/react/pull/11110) we’re not confident it won’t lead to a slight performance regression. So it might not be worth it. We’d need data from people using SSR in production to tell if this would be a problem or not.

**Closed by gaearon** 2017-11-08 20:46 UTC
