### ISSUE TITLE
Bug: Use Typescript error

### ISSUE THREAD

**Issue by dom996byid** [facebook/react#20313] opened 2020-11-22 06:08 UTC
### Errors
**D:\XXXXXX\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:239**
      appTsConfig.compilerOptions[option] = value;

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (D:\Code\react-demo-ts\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (D:\Code\react-demo-ts\node_modules\react-scripts\scripts\start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.

**Comment by kachkaev** [comment] 2020-11-22 10:01
Likely duplicate of https://github.com/facebook/create-react-app/issues/10110

**Closed** 2020-11-22 11:11 UTC
Labels: Status: Unconfirmed
