### ISSUE TITLE
Error: "Cannot read property 'concat' of undefined"

### ISSUE THREAD

**Issue by HarleySG** [facebook/react#19205] opened 2020-06-27 23:29 UTC
Describe what you were doing when the bug occurred:
1. Click on Reload and start profiliing
2. Click on Start profiling
3. Click on Select next commit

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.7.0-23309eb38

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:164715)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:163849)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:166664)
    at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342328)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:62450)
    at tl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:71793)
    at zl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:113765)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104502)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104430)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104298)

Component stack: at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342099)
    at div
    at div
    at div
    at Co (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:263571)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:366677
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:276314)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:278724
    at div
    at div
    at Xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:325177)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:207026)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:216342)
    at Va (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:293773)
    at us (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:371869)

**Comment by ankitgadents** [comment] 2020-06-28 06:08
I am also getting somewhat same error:

```
npm run build

> js@0.1.0 build /Users/agade/anktest/plugins/share-cart/assets/js
> react-scripts build

Creating an optimized production build...
Failed to compile.

Cannot read property 'length' of undefined
CompileError: Begins at CSS selector .wcssc-icons-container


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agade/.npm/_logs/2020-06-28T05_52_02_486Z-debug.log
```

Seems like issue is with the css. If I do not import any of css in my app and run build, then build executes successfully.

**Comment by bvaughn** [comment] 2020-06-28 14:35
@HarleySG This is a duplicate of #18256. Let's move any repro discussion to that issue.

@ankitgadents The error you posted looks like a very different issue. Not something to do with React :)

**Closed by bvaughn** 2020-06-28 14:35 UTC
Labels: Component: Developer Tools
