### ISSUE TITLE
When a module which uses react hooks is dynamically imported into an application the application crashes

### ISSUE THREAD

**Issue by rajithaw** [facebook/react#16664] opened 2019-09-05 07:30 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

My application consists of two parts. The main web application and a module which gets dynamically loaded into the web application.
Both web application and the module uses React 16.9.0.
The module is loaded into the web application using React.lazy() and dynamic import() statement.
When the module is loaded the application crashes with the following message in the console.

![Lazy loading demo](https://user-images.githubusercontent.com/5545438/64320589-39381700-d002-11e9-9026-33da5388496c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

To reproduce the issue, we require an application and 2 modules each having their own build.
Therefore a demo couldn't be created in codesandbox. I've attached a demo which can be used to reproduce the issue.
[lazy-loading.zip](https://github.com/facebook/react/files/3577981/lazy-loading.zip)

1. Download the attached demo app.
2. Navigate to "\app\modules\module1" and "\app\modules\module1" folders and run "npm install" and "npm build" to build the modules.
3. Navigate to "\app" folder and run "npm install" and "npm start" to run the main app.
4. Open the dev tools and Browse to http://localhost:3000.
5. Application will try to load the module which uses react hooks and crashes. The error message in the above screenshot will be displayed in the console.
6. In app.jsx comment the line < LazyModule1 /> and un-comment the line < LazyModule2 />. Now the application will try to load the module which does not use react hooks.
7. The app will now load successfully.

**What is the expected behavior?**

When both the app and the dynamically imported module is using the latest version of react the app should load without crashing.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React - v16.9.0
Browser - Chrome
OS - Windows 10

**Comment by threepointone** [comment] 2019-09-05 08:14
This seems related to https://github.com/facebook/react/issues/13991, you're likely loading multiple versions of React because you're bundling the modules separately, as the error message states. You can see that index.bundle.js, module1.js, and module2.js, all have their React included in their bundles. Closing this issue as a duplicate of https://github.com/facebook/react/issues/13991.

**Closed by threepointone** 2019-09-05 08:14 UTC
