### ISSUE TITLE
Bug: extra render with the same value for useState and onClick only for React-DOM

### ISSUE THREAD

**Issue by trajano** [facebook/react#22940] opened 2021-12-11 15:56 UTC
React version: 16.13.1

## Steps To Reproduce

1. I used the following code in Jest

```ts
  it("should not rerender when setting state to the same value via click", async () => {
    const callback = jest.fn();
    function MyComponent() {
      const [foo, setFoo] = useState("bir");
      callback();
      return (<div data-testid="test" onClick={() => setFoo("bar")}>{foo}</div>);
    }

    const { getByTestId } = render(<MyComponent />)
    const testElement = getByTestId("test");
    expect(testElement.textContent).toEqual("bir");
    expect(callback).toBeCalledTimes(1);

    act(() => { fireEvent.click(testElement); });
    expect(testElement.textContent).toEqual("bar");
    expect(callback).toBeCalledTimes(2);

    act(() => { fireEvent.click(testElement); });
    expect(testElement.textContent).toEqual("bar");
    expect(callback).toBeCalledTimes(2); // gets 3 here

    /*
     assuming we update the last line as follows
     expect(callback).toBeCalledTimes(3); // really should be 2
     act(() => { fireEvent.click(testElement); });
     expect(testElement.textContent).toEqual("bar");
     expect(callback).toBeCalledTimes(3); // does not re-render
    */

  })
```

Link to code example:

- Similar code in [codesandbox](https://codesandbox.io/s/rerender-on-first-two-clicks-700c0?file=/src/App.js)
- Simlar AND working code in [an Expo Snack](https://snack.expo.dev/@trajano/usestate-test)

## The current behavior

On initial render OK
On first click, rerender due to value change OK
On second click, rerender even with the same value NOT OK

## The expected behavior

On initial render OK
On first click, rerender due to value change OK
On second click, no rerender because useState dispatch with the same value

Note this works correctly on React-Native as shown by Expo

**Comment by eclipseeer** [comment] 2022-01-01 21:06
I got the same bug too - React 17.0.2

    const Content = () => {
    const [x, setX] = useState(1);
    const onClick = () => setX(2);
  
    console.log('render component');
    console.log(x);
  
      return (
        <div>
          <button onClick={onClick}>Click</button>
        </div>
     );
    }

After a few clicks result will be the next:

    render component 
    1
    render component
    2
    render component
    2 

What is wrong, because there is should be only 1 rerender, not 2.

Also, something similar is with `useRef` - if you will pass a function call like `useRef(Math.random())` after first rerender it will recall it and the `ref.current` will change.

**Comment by eps1lon** [comment] 2022-01-07 18:47
Duplicate of https://github.com/facebook/react/issues/23055.

See https://github.com/facebook/react/issues/23055#issuecomment-1003712895 for an explainer of why this is happening.

**Closed by eps1lon** 2022-01-07 18:47 UTC
Labels: Status: Unconfirmed

**Comment by trajano** [comment] 2022-01-07 20:45
@eps1lon the comment actually does not say WHY it's happening.

>  React *may still need to render that specific component again*

But does not go to *WHY do you need to render that specific component again*

**Comment by hxse** [comment] 2022-01-08 06:49
At least let us know why this happens. 
This is weird and should be fixed.

**Comment by hxse** [comment] 2022-01-08 11:21
@eclipseeer 
> Also, something similar is with useRef - if you will pass a function call like useRef(Math.random()) after first rerender it will recall it and the ref.current will change.

About useRef(Math.random()) I did not find it changed, what the change you said?
Code: https://codesandbox.io/s/react-usestate-stateless-component-forked-7qxq9?file=/src/index.js

![image](https://user-images.githubusercontent.com/22582226/148642219-8e886616-9aec-4012-b011-daad7a1630a2.png)

**Comment by eclipseeer** [comment] 2022-01-08 20:01
@hxse it happens only if `StrictMode` is enabled
![image](https://user-images.githubusercontent.com/18114189/148658123-4247e73c-0f41-44a4-a1eb-2d489199020d.png)

**Comment by hxse** [comment] 2022-01-11 05:50
@eclipseeer I submit a issues https://github.com/facebook/react/issues/23091
