### ISSUE TITLE
Bug: React Dev Tool extension won't load for a development server

### ISSUE THREAD

**Issue by codinghedgehog-python** [facebook/react#19453] opened 2020-07-25 10:31 UTC
I'm not sure if screenshots are necessary in this case. Please ask if you need them.
React Dev Tool extension won't load up when working locally. It loads up fine when on live server.

browser:  Firefox Dev Edition
OS:  Ubuntu 20.04

## Steps To Reproduce

1. Install latest Firefox Dev Edition
2. Add React Dev Tool extension
3. Run local dev server (on Docker or off)

## The current behavior
Described above

## The expected behavior
The extension loading up no matter if working locally or in production.

**Comment by bvaughn** [comment] 2020-07-27 13:35
Screenshots would not be helpful. A repro case would be needed before anyone could take a look at this issue.

**Comment by bvaughn** [comment] 2020-07-30 17:47
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

Since the issue is not currently actionable, I'm going to close this issue until more information is provided.

**Closed by bvaughn** 2020-07-30 17:47 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
