### ISSUE TITLE
issue with loading react developer tools 

### ISSUE THREAD

**Issue by sudheer-kolli** [facebook/react#22789] opened 2021-11-18 15:46 UTC
failed in loading components and profiler

**Comment by bvaughn** [comment] 2021-11-22 14:45
Sorry, but there isn't enough information for us to help with this issue.

Just in case you weren't aware, React DevTools only show up when you're viewing a website built with React. (For example, you can visit www.reactjs.org to test this.)

You might also want to try restarting your browser.

If these still don't fix the problem, please leave a comment with the following information:
* What operating system (and version) are you using
* What browser (and version) are you using
* Which version of React DevTools have you installed
* What website are you visiting that DevTools doesn't work on (how can we reproduce the problem)
* Are there any errors in your browser console?

Sometimes it is also helpful to share if you have any other extensions installed that might be interfering.

I'm going to close this issue for now since we can't do anything with it, but if you respond with the above information we can take a look.

**Closed by bvaughn** 2021-11-22 14:45 UTC
