### ISSUE TITLE
[DevTools] Components tab goes blank with React 16.8.0

### ISSUE THREAD

**Issue by abelardolg** [facebook/react#20261] opened 2020-11-15 14:52 UTC
React version: 16.8.0

## Steps To Reproduce
Install react 16.8.0

1. Build a hello world with any component
2. Open React Dev Tools.
3. Choose components tab.
4. Nothing will be seen.

Link to code example:

## The current behavior
Tab "Component" is blank

## The expected behavior
Tab "Component" should show React components

FYI: I installed Material UI library.
Chrome: Versión 86.0.4240.183 (Build oficial) (64 bits) Ubuntu 18.04.
Tested today.
Versión
4.10.0 (11/12/2020)
Actualizado
13 de noviembre de 2020

**Comment by brettgoulder** [comment] 2020-11-16 05:02
I am unable to reproduce this bug unfortunately.

<img width="913" alt="Screen Shot 2020-11-15 at 9 02 00 PM" src="https://user-images.githubusercontent.com/22752/99214765-db669980-2785-11eb-8896-64ec634fde0a.png">

**Comment by abelardolg** [comment] 2020-11-16 08:57
Hi @brettgoulder , 

Are you using Google Chrome for Ubuntu with the version I specified? 
Later I will upload a screenshot to document this issue.

Best regards.

**Comment by bvaughn** [comment] 2020-11-16 13:28
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by brettgoulder** [comment] 2020-11-16 16:54
@abelardolg yes, I just checked and I still can't confirm it on 18.04. Here's a screenshot: 

<img width="654" alt="Screen Shot 2020-11-16 at 8 50 36 AM" src="https://user-images.githubusercontent.com/22752/99282749-f28aa300-27e8-11eb-9434-c884d1a23092.png">

Here's the URL for the test app: https://mzfm7.csb.app/    and code: https://codesandbox.io/s/lucid-franklin-mzfm7

**Comment by zachwright** [comment] 2021-02-16 23:23
I'm also experiencing this issue. My app is running on localhost without errors, but the Components tab is blank.

![Screenshot 2021-02-16 171405](https://user-images.githubusercontent.com/28732225/108133866-e4b01c80-707a-11eb-98ea-b78b66ae60e4.png)

Is there a way to view the error logs of the React Dev Tools to see if RDT is failing somehow even if my app isn't complaining?

**Versions**
* Chrome: 88.0.4324.182 (Official Build) (64-bit)
*  React Dev Tools: 4.10.1 (12/4/2020)
*  React Version: 16.8.6

**Comment by hagiosofori** [comment] 2021-03-08 12:29
also been experiencing this issue for a few days now. It's gotten to the point where there's a bug I'm struggling to figure out without the devtools, so I'm resorting to thsi

**Comment by bvaughn** [comment] 2021-03-08 14:52
> Is there a way to view the error logs of the React Dev Tools to see if RDT is failing somehow even if my app isn't complaining?

Yes. Undock DevTools from the main window so that it's a separate window, then pop out a second DevTools for it.

https://user-images.githubusercontent.com/29597/110337494-fa6a8f00-7ff3-11eb-9cad-a468a17f9670.mp4

**Comment by flying-sheep** [comment] 2021-06-23 10:07
I just get `Attempt to postMessage on disconnected port` multiple times per second.

When I try to finds the frame with the extension, I get to `chrome://browser/content/webext-panels.xhtml`. That contains a `<stack id=webext-panels-stack><browser id=webext-panels-browser>...</browser></stack>`.

I can’t find a way to debug the contents of this `<browser/>`, which seems to contain the react devtools.

**Comment by flying-sheep** [comment] 2021-06-23 10:23
Trying to open devtools in the test app results in an error (sometimes, it’s really flaky):

```
InspectedElementContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:31391:43
Suspense
ErrorBoundary_ErrorBoundary@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:30033:5
div
InspectedElementErrorBoundaryWrapper@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:30175:46
NativeStyleContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:32660:38
div
div
OwnersListContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:28267:37
SettingsModalContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:28708:40
Components_Components@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:34512:52
ErrorBoundary_ErrorBoundary@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:30033:5
PortaledContent@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:30146:34
div
div
ProfilerContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:34137:35
TreeContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:24944:31
SettingsContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:25547:35
ModalDialogContextController@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:30233:38
DevTools_DevTools@moz-extension://cda19686-3928-4e8e-8c40-7419ecd1d955/build/main.js:37240:27
```

**Comment by bvaughn** [comment] 2021-06-23 15:32
> Attempt to postMessage on disconnected port

In my experience this generally means that the extension has been invalidated (e.g. b'c it was just updated or something edge casey) and reloading the page will fix the problem.

> When I instead go through `about:debugging` and click `Inspect` next to the extension, I can indeed inspect `panel.html`. There’s no errors, there is just a `width: 0, height: 0` empty div where content should be. I see a warning about some cookie being outdated every second though.

Does this reproduce for you? If so, are you using Chrome Canary or some other pre-stable-release version? I've only seen blank behavior from pre-release Chromes.

**Comment by flying-sheep** [comment] 2021-06-24 19:09
Firefox, and reproducable (Most of the time: Very rarely, the tree view actually shows up)

**Comment by ashmeet-kandhari** [comment] 2021-06-27 00:40
Is this still an issue?
Looks like this was fixed in version: 16.14.0 
Can we confirm, if not would like to take this up

**Comment by flying-sheep** [comment] 2021-06-27 15:39
I have React 16.14.0 and devtools 4.13.5 (0ae5290b5434dd7a14be02a5c3f62bd80ad75d6d)

**Comment by bvaughn** [comment] 2021-06-28 03:41
> Can we confirm, if not would like to take this up

@ashmeet-kandhari Please feel free to take a look! Help would be welcome.

**Comment by ashmeet-kandhari** [comment] 2021-06-29 08:15
Sure 

> > Can we confirm, if not would like to take this up
> 
> @ashmeet-kandhari Please feel free to take a look! Help would be welcome.

Sure @bvaughn, will have a look

**Comment by ashmeet-kandhari** [comment] 2021-06-30 04:45
Earlier I was able to face the same issue.
Unfortunately, when I deleted my node-modules and package-lock.json  and re-installed everything, am not able to reproduce it
Here are my dependencies

` "dependencies": {
    "react": "16.14.0",
    "react-dom": "16.14.0",
    "react-scripts": "^4.0.3"
  },
  "devDependencies": {
    "react-devtools": "^4.13.5"
  }`

**Comment by ashmeet-kandhari** [comment] 2021-06-30 06:15
> Earlier I was able to face the same issue.
> Unfortunately, when I deleted my node-modules and package-lock.json and re-installed everything, am not able to reproduce it
> Here are my dependencies
> 
> ` "dependencies": { "react": "16.14.0", "react-dom": "16.14.0", "react-scripts": "^4.0.3" }, "devDependencies": { "react-devtools": "^4.13.5" }`

I was able to reproduce the issue when I was using react `16.8.0` version after a clean install.
I have narrowed down the issue to a map variable `fiberToIDMap` not getting populated in `react_devtools_backend.js` with react's 16.8.0 version.

Can somebody guide me what triggers the population of that variable?

**Comment by ashmeet-kandhari** [comment] 2021-06-30 13:24
> I have React 16.14.0 and devtools 4.13.5 ([0ae5290](https://github.com/facebook/react/commit/0ae5290b5434dd7a14be02a5c3f62bd80ad75d6d)) and this is an issue.

Hi @flying-sheep , 
Can you do a clean install and confirm if this is still an issue?

**Comment by bvaughn** [comment] 2021-06-30 13:31
@ashmeet-kandhari Are you able to reliably reproduce this? If so, can you share a repro with me (either a GitHub project or a Code Sandbox built with the version of React you're talking about)?

**Comment by ashmeet-kandhari** [comment] 2021-07-01 14:22
@bvaughn 
I was talking about react 16.8.0 where this issue comes up.
Here is the git repo
https://github.com/ashmeet-kandhari/reactjs-helloworld

Just run
* npm install
* npm start
* Open the page along with react devtools plugin where you will see blank
* Click on the Open Element button and hover on the page, you will see the error in console about missing fibreId 

My System Config
**OS:** Windows 10 version 21H1 
**OS Build Version:** 19043.1081
**Browser:** Chrome 91.0.4472.124 (Official Build) (64-bit)

**Comment by bvaughn** [comment] 2021-07-01 14:30
Thanks @ashmeet-kandhari! I can reproduce the blank component tab behavior with the project you sent, but have not had time to dig into _why_ yet.

**Comment by ashmeet-kandhari** [comment] 2021-07-02 13:28
> > Earlier I was able to face the same issue.
> > Unfortunately, when I deleted my node-modules and package-lock.json and re-installed everything, am not able to reproduce it
> > Here are my dependencies
> > ` "dependencies": { "react": "16.14.0", "react-dom": "16.14.0", "react-scripts": "^4.0.3" }, "devDependencies": { "react-devtools": "^4.13.5" }`
> 
> I was able to reproduce the issue when I was using react `16.8.0` version after a clean install.
> I have narrowed down the issue to a map variable `fiberToIDMap` not getting populated in `react_devtools_backend.js` with react's 16.8.0 version.
> 
> Can somebody guide me what triggers the population of that variable?

Hi @bvaughn,

I did dig deep into this and these are some findings I have
* The issue is when using `react v16.8.0` the method `onCommitFiberRoot` of `hooks.js` is not being called
* When I dug deeper, I found that in `react-refresh-runtime.development.js`' -> `hook.inject` (line 451) 
          ` if (typeof injected.scheduleRefresh === 'function' && typeof injected.setRefreshHandler === 'function') {
        // This version supports React Refresh.
        helpersByRendererID.set(id, injected);
      }
     ` 
the if clause fails as `scheduleRefresh ` and `setRefreshHandler`  are not added/present in `react-dom.development.js`

This is the main reason for the field `fiberToIDMap` never gets populated and components don't showup in the dev tool

**Comment by bvaughn** [comment] 2021-07-02 14:50
Oh _right_. It's not that DevTools and React 16.8.0 are incompatible. It's that Fast Refresh was breaking the DevTools hook at one point.

I fixed several DevTools bugs caused by Fast Refresh (#20129 as well as #21523 and #21536) and we made new releases of Fast Refresh. Unfortunately some past releases remain broken. I guess the best path forward here is to just avoid using those releases. (It's probably a good idea to use the latest bugfix release of a given minor anyway, e.g. 16.8.6 rather than 16.8.0)

**Comment by ashmeet-kandhari** [comment] 2021-07-03 09:10
So Maybe this issue can be closed in that case?

**Comment by flying-sheep** [comment] 2021-07-03 10:07
As said, we could both originally reproduce that with react 16.14, not 16.8.

When I purge my npm-shrinkwrap and reinstall everything, the issue is also gone, but the point of that file is to have a reproducible environment, so if the recommendation is to nuke it every time an issue appears, what purpose does it serve?

**Comment by bvaughn** [comment] 2021-07-03 17:02
@ashmeet-kandhari Yes, perhaps it could be closed. If the cause if this a known-to-be-broken version of Fast Refresh (that happens to be version locked with react-dom@16.8.0) then I guess there isn't much value in keeping this issue open.

@flying-sheep I am not convinced you are talking about the same error/issue, based on your messages above.

**Comment by bvaughn** [comment] 2021-07-03 23:31
I'm going to close this as something we won't/can't fix, since the problem is caused by a bad release of Fast Refresh. The solution: upgrade.

**Closed by bvaughn** 2021-07-03 23:31 UTC
Labels: Component: Developer Tools, Type: Bug

**Comment by leocaseiro** [comment] 2021-11-03 05:05
Hi @bvaughn, could you please elaborate on what we need to update to fix this issue?
 Is Fast Refresh a dependency of some library? Which one?

Should we update via npm or something like that?

Thank you!
