### ISSUE TITLE
async value updates on inputs reset cursor position

### ISSUE THREAD

**Issue by jquense** [facebook/react#5386] opened 2015-11-04 12:34 UTC
Hello again.

this strikes me as a bug, it is certainly annoying and difficult to workaround. If you control an input and set the value asynchronously, say with a setTimeout as in the example, the cursor position is reset to the end of the input.

in the below jsFiddle, try typing in the middle of the input text the cursor should reset to the end of the line.

https://jsfiddle.net/69z2wepo/19927/

**Addendum** I see that native inputs exhibit the same behavior is you, say use jquery and setinterval. To me tho that is still not the behavior you'd want, since in a controlled input scenario you know when the value is actually changing.

**Comment by syranide** [comment] 2015-11-04 14:06
This is an unsolvable problem without explicitly setting the selection yourself.

Setting the value asynchronously is practically equivalent to setting it to an arbitrary value. A string has no selection information and there is no generic transformation of the selection that makes sense, so this behavior is unavoidable. Your only option is to manage and set the selection yourself if this is something you want to do.

Also, beware that setting it asynchronously implies that multiple timeouts may be scheduled simultaneously with unintended results.

**Comment by jquense** [comment] 2015-11-04 14:43
In the general case it seems fine by itself, but in the specific, doesn't react just sort of sometimes throw asynchrony at you? setState in the parent may be async, rendering into a new subtree as well...is there something special about those cases that React handles it correctly but not others?

Is the problem too general for ReactDOMInput to handle restoring the selection on flushed value changes (which is how I've handled it in our app)?

**Comment by syranide** [comment] 2015-11-04 15:32
> In the general case it seems fine by itself, but in the specific, doesn't react just sort of sometimes throw asynchrony at you? setState in the parent may be async, rendering into a new subtree as well...is there something special about those cases that React handles it correctly but not others?

Loosely speaking, `setState` is only asynchronous within the current transaction. They're still executed before React surrenders execution back to the DOM, so it still appears synchronous to the input. Again, loosely speaking.

> Is the problem too general for ReactDOMInput to handle restoring the selection on flushed value changes (which is how I've handled it in our app)?

Once React surrenders execution back to the browser it's no longer meaningful for a string to be implicitly associated with a selection I would say. It *could* still be done, but it's really stretching the definition of what is sane and as I mentioned above, it starts becoming really muddled/fragile if multiple events occur simultaneously. So even *if* it would be possible, deferring user input degrades the user experience and opens up a can of worms.

Personally I would argue that even the current way the selection is implicitly tied to the new string is a hack, but it simplifies the vast majority of use-cases so it makes practical sense. I've wanted to write a component that exposes the selection too, but haven't entirely gotten around to it yet.

Makes any more sense?

**Comment by gaearon** [comment] 2017-10-03 22:51
I’ll close this as it works as designed I think.

If you use controlled inputs, you’re expected to update the value synchronously. If you need to, for example, debounce, you can do this *after* updating the value. For example one might maintain two values in the state: one for the input, and one for the “debounced” value.

**Closed by gaearon** 2017-10-03 22:51 UTC
