### ISSUE TITLE
img onLoad does not always fire in react 18

### ISSUE THREAD

**Issue by peternycander** [facebook/react#17306] opened 2019-11-07 19:29 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

`<img onLoad={fn} />` does not always trigger `fn` when rendered using createRoot if it has siblings which are heavy to render (I think?).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/quiet-dawn-t1std
You might have to use the retry button a few times, but hopefully you should be able to see it. Don't disable cache while trying

**What is the expected behavior?**

onLoad always fires if img gets loaded.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

0.0.0-experimental-f6b8d31a7
Reproduced in chrome and firefox windows. Have not tried the codesandbox in mac, but the actual bug in our app occurred there first so I'd be surprised if it is OS specific.

It does not happen with regular "sync" mode.

**Comment by peternycander** [comment] 2020-02-06 17:21
From what I can tell it is still an issue with the latest (241c4467e) experimental, so I don't think it should be closed.

**Comment by gaearon** [comment] 2022-03-30 00:16
I thought https://github.com/facebook/react/pull/23316 would fix this but I think I can still repro.

https://codesandbox.io/s/laughing-chandrasekhar-17l6tk?file=/src/index.js

Maybe @gnoff could have a look.

**Comment by gnoff** [comment] 2022-03-30 07:10
@gaearon I can't seem to repro. what browser are you using? Are you getting the error state on every retry or just in rare cases?

**Comment by gaearon** [comment] 2022-03-30 07:11
Maybe I misunderstood the repro. What is the expected behavior? If it works, can you check whether it was reliably broken with the old version?

**Comment by gaearon** [comment] 2022-03-30 13:49
> showing only a flash of the other text.

Yes, that’s what I saw. Does this mean the flash does not constitute a bug? My brain is bit fried and I’m not sure how to interpret the sandbox.

**Comment by peternycander** [comment] 2022-03-31 06:17
I think it is fixed. The flash is from the 'pending' state. The original issue was that the pending state never disappeared.

**Comment by gaearon** [comment] 2022-03-31 08:51
Ohh ok. So we can close this?

**Comment by peternycander** [comment] 2022-03-31 08:57
> Ohh ok. So we can close this?

I think so, but I'm not an expert

**Closed** 2022-03-31 09:41 UTC
Labels: Type: Needs Investigation, React 18

**Comment by kalnode** [comment] 2025-06-17 19:20
I don't know if it was OP's problem, but this topic always needs a mention that browser-cached images may not always fire `onLoad` because they get instantly displayed (independent of React). There are workarounds.
