### ISSUE TITLE
Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 21"

### ISSUE THREAD

**Issue by mengxuhui** [facebook/react#17444] opened 2019-11-24 15:38 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.0-a8b8ffb89

Call stack: at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150913)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:150791)

Component stack: in dl
    in div
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by bvaughn** [comment] 2019-11-26 19:16
Duplicate of #16412

**Closed by bvaughn** 2019-11-26 19:16 UTC
Labels: Component: Developer Tools, Resolution: Duplicate, Type: Bug
