### ISSUE TITLE
Feature request: get a ref of a in memory dom element before mount.

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/react#12701] opened 2018-04-26 19:08 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

currently, there isn't a great way in react to build UI from components due to needing refs to check the props of a DOM element, you have to wait for the component to mount, and then repaint if you want to make changes to the UI based off the information you've received from the ref.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

you can create DOM nodes in memory before appending them to the DOM, so I'd expect react to create the elements necessary in memory before appending to the mount point of ReactDOM.render

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

No

**Comment by gaearon** [comment] 2018-04-26 19:19
Can you explain more about why doing measurements in `componentDidMount` and calling `setState` there is not sufficient for you?

These updates are processed before React exits the top call stack frame so the browser will only paint the final state even if you do an update there.

**Comment by aweary** [comment] 2018-05-18 05:25
Since there's been no update, I'm going to assume the issue is resolved and close this.

**Closed by aweary** 2018-05-18 05:25 UTC
Labels: Resolution: Needs More Information
