### ISSUE TITLE
Any way to handle setState changes output on SSR?

### ISSUE THREAD

**Issue by fjaguero** [facebook/react#6102] opened 2016-02-23 18:00 UTC
I was wondering how it's the best way to render server-side (without rendering this on the client) AND handle the state changes. What I mean here is how to get the HTML from a server component that has a state changing.

Example:

1. A server gets a requests to generate an HTML
2. The server 'requires' a react component, passing some props
3. The react component renders in the server, but it has to do an Ajax/Socket query to get some info. The event is sent and the response comes later.
4. The react component changes the state, changing the output
5. The HMTL generated is ready and with the latest state changes.

What's happening here is that ReactDOM.renderToStaticMarkup(), as expected, doesn't wait for the component to finish the state changes (in this case, wait for the data and re-render).

How can I achieve this? Doing all the queries first and passing all the data as props? Is this the only way?

Thanks!

**Comment by jimfb** [comment] 2016-02-24 18:05
Duplicate of https://github.com/facebook/react/issues/1739

**Closed by jimfb** 2016-02-24 18:05 UTC
