### ISSUE TITLE
Clarify SSR expectations/contract

### ISSUE THREAD

**Issue by Andarist** [facebook/react#20047] opened 2020-10-17 10:31 UTC
I've been asked about the safety of a certain pattern and I'd like to clarify this with you (the React team). 

In my opinion - the actual SSRed output and the hydrating tree **do not have to match**. This is, of course, a weird space of things and one should understand how things work together to even think about it, but there is no technical aspect forbidding this now. Question is - is it safe to assume that such a "use case" will stay supported in the future. I believe it is because the only thing that is used as an input to the rehydration is the current HTML structure and the React team doesn't intend to ship any extra metadata in the SSRed output about the actual render tree that was used to render it.

This can be a little bit of a vague question - so let's take a look at an example. Emotion does 2 things on the server differently than on the client:
1. it does not use `React.forwardRef` (refs are useless on the server, so we don't see a need to grow the render tree rather significantly by using it)
2. we render `<style>` elements "inline", together with other elements. This is an example SSRed output:
```html
<div id="react-root">
  <style data-emotion-css="bjcoli">
    .css-bjcoli{color:green;}
  </style>
  <div class="css-bjcoli">
    <style data-emotion-css="ihiui2">
      .css-ihiui2{color:hotpink;}
    </style>
    <div class="css-ihiui2">
    </div>
    <div class="css-ihiui2">
    </div>
  </div>
</div>
```

On the client we:
- use `React.forwardRef` as it's important to do so
- we **move** `<style>` elements to the `<head>` **before** rehydration can even be called

This makes the HTML structure **identical** to what React sees during the first render so there is **no SSR mismatch**, even though initially there kinda is one.

We totally understand this is a gray area and trickery - question is: do u plan to make things like this break in the future? I totally would understand the answer being "we can't guarantee that", but at the same time it would be great if it would be accompanied by "probably not, this is _safe_ to do and there are no plans to make this break now"

cc @eps1lon

**Comment by gaearon** [comment] 2020-10-17 10:49
>we move <style> elements to the <head> before rehydration can even be called

I haven't thought deeply about this but I'm not sure this will keep making sense.

There's an age-old problem with React server rendering related to code splitting. You want to render some significant chunk of HTML on the server but you don't want to block *starting* hydration on loading *all* of the JS for the HTML you rendered. Today you don't really have a good solution for that.

Concurrent Mode adds the foundation to solve it. In CM, hydration is progressive — i.e. it doesn't just happen in a large synchronous block when all the HTML has loaded. Instead, the ideal way is to do it as early as possible, *before* you load all the code. In fact you call `render(<App />, { hydrate: true })` at the very beginning, when you have almost no code except some app shell and React. The actual app code is code-split (likely in multiple chunks). React attempts to hydrate as much as it can until it Suspends (waiting for code). But if the parts that Suspend are wrapped in `<Suspense>`, we can hydrate everything outside of them. The app code would already be resilient to `<Suspense>` having a fallback (e.g. it wouldn't assume all refs to be available synchronously).

In other words, in CM we support "dehydrated Suspense boundaries" — HTML *content* from the server stays dehydrated while the associated *code* is still loading. It doesn't get replaced by fallback unless something very unfortunate (like an early top-level Context update, which is discouraged for this reason with SSR) happens during hydration and we have no other choice but to hide server HTML content (think: dark theme toggle switch).

In this world, "moving all styles before hydration" doesn't quite make sense to me because there is no single point "before" hydration. The goal is to get away from it being a synchronous bottleneck happening at the very end, and instead make it a progressive and continuous process that we start as early as possible to become partially responsive while most of the code is still loading. But more HTML content may continue to stream in, which I don't think quite works with what you're suggesting.

**Comment by gaearon** [comment] 2020-10-17 10:53
I'd say that in general, from React's point of view, the output *does* have to match. If it doesn't match, all guarantees are off. However, I agree that the *way* you get this output doesn't 100% have to match (e.g. your forwardRef case seems ok to me since the difference is completely unobservable to the client code).

**Comment by eps1lon** [comment] 2020-10-17 11:14
My main gripe with these CSR-only techniques is that as a library author I have no robust way to detect my component is rendered with client or server-side API. There are popular libraries out there that use the SSR-API in the browser e.g. to make a pre-pass over the tree (`@apollo/client`) so any `typeof window`-type check is insufficient. So I end up with a bunch of issues about noisy warnings that I can't act on. 

> Although for that forwardRef optimization I kind of wish we just got a PR that changes the implementation to do a fast path call-through for it in SSR instead of hacking around it.

Would that be something that we can introduce in v16 or v17 and would it make sense for an outside contributor to work on it? I'd rather solve this reliably within React than working around it imperfectly.

**Comment by gaearon** [comment] 2020-10-17 11:32
>There are popular libraries out there that use the SSR-API in the browser e.g. to make a pre-pass over the tree (@apollo/client) so any typeof window-type check is insufficient

FWIW there are bigger problems with that approach in general and it's very fragile. I know Apollo is doing it but this is not really the supported way to use React since it's essentially trying to reimplement its semantics. So it's in the "if you can keep it working, cool" territory but I assume you're asking about long-term solutions rather than workarounds.

>Would that be something that we can introduce in v16 or v17 and would it make sense for an outside contributor to work on it? I'd rather solve this reliably within React than working around it imperfectly.

Maybe I misunderstand but I thought the point is just a tiny perf optimization? I don't think there would be an actual behavior difference. If it's a perf optimization to avoid pushing the frame, it can probably be done by anyone in `ReactPartialRenderer` source today. I don't fully understand how beneficial this is though tbh. Has someone profiled this?

**Comment by gaearon** [comment] 2020-10-17 11:34
To be clear, if there's a gap in the API that is impossible for you to solve, let's discuss what you need. But let's not focus on the proposed solution ("make it possible to emit mismatching output") and instead focus on the fundamental problem. Let's think about how it's supposed to work with partial hydration and streaming, too. In that world, what does your ideal solution look like?

**Comment by eps1lon** [comment] 2020-10-17 11:47
> I don't fully understand how beneficial this is though tbh. Has someone profiled this?

**Comment by eps1lon** [comment] 2020-10-17 12:01
> Maybe I misunderstand but I thought the point is just a tiny perf optimization? I don't think there would be an actual behavior difference. If it's a perf optimization to avoid pushing the frame, it can probably be done by anyone in ReactPartialRenderer source today. I don't fully understand how beneficial this is though tbh. Has someone profiled this?

I'd hope that there is not difference. If React would implement the call-through `emotion` wouldn't need to do it and Material-UI wouldn't see any warnings because we have a warning-heuristic for components not forwarding their refs.

> FWIW there are bigger problems with that approach in general and it's very fragile. I know Apollo is doing it but this is not really the supported way to use React since it's essentially trying to reimplement its semantics. So it's in the "if you can keep it working, cool" territory but I assume you're asking about long-term solutions rather than workarounds.

It's a "matter-of-fact" issue for us (Material-UI). We tell people the same thing (don't do it) but that's not a battle we can win. The impact for us is that we get issues reported because library authors (that includes us) implement approximations for "we're server rendering so let's skip some stuff" and we can't act on these issues.

We already lost that battle with `useLayoutEffect` on the server and I'd like to avoid the same stalemate with `forwardRef` on the server. Now it seems to me you're open to accept a fast-path solution for `forwardRef` on the server if it actually has a perf impact.

**Comment by gaearon** [comment] 2020-10-17 13:27
I think we might be talking about slightly different things in both cases. I probably misunderstood what you meant.

Re: Apollo, the only thing we don’t recommend and don’t really support is the “manual prepass” where someone writes an approximation of React hoping to match its semantics. I think there was a package that does it, and then it has to update every time React adds a feature. This was not very good. Using the *actual* SSR renderer on the client, generally saying, is fine and supported today. Even though I’d agree using it to warm up fetching is not the intended use case.

As for forwardRef I also don’t quite think I understood you. I didn’t mean forwardRef itself would be pass through. That would be an observable detail which seems risky (because you can inspect the component type). I only meant that, *if* that was a perf problem (which I doubt but that’s how I read your description), we can skip creating an extra internal frame when buffering the output. But this is an implementation detail of the server renderer. Some clarification on what exactly the perf problem is and what evidence exists for it would be very helpful.

**Comment by gaearon** [comment] 2020-10-17 13:29
I wonder if the perf problem is just a guess that deeper tree is bad based on client experimentation. I want to emphasise that server renderer shares no code with the client renderer and they have different performance characteristics. I wouldn’t expect a forwardRef wrapping to have measurable impact but if it does, we can try to optimise it.

**Comment by eps1lon** [comment] 2020-10-17 14:23
To clarify why I'm cc-ed here:

Emotion's factory creates a `React.forwardRef` component on the client but a plain function on the server. Something like

```js
function styled(Component) {
  if (isBrowser) {
    return React.forwardRef((props, ref) => {
       return <Component ref={ref} {...props} />
    })
  }
  return (props) => {
    return <Component {...props} />
  }
}
```

I was told this was for performance reasons. 

Some Material-UI components allow overriding the rendered component but we do expect that these components can hold a ref. We issue a warning if we're sure that these components cannot hold a ref i.e. `typeof Component === "function" && Component.prototype?.isReactComponent === false`:

```jsx
function MaterialUIComponent({ component: Component }) {
  return <Component ref={React.useRef()} />
}
```

The reason we do this is to provide a better error message because the React warning makes it seems like a problem with Material-UI when the issue is with the app author.

If the given `component` is created with emotion then we'll log a warning on the server. 

The issue is that it seems fine for emotion to do it because React itself will not issue a warning if a plain function component is given a ref when server rendering. We could also skip the warning on the server but React has no API to detect the used renderer. We can only approximate it with environment sniffing (which is not accurate due to e.g. apollo).

We're probably just adding the usual `typeof window` check but if there's a real perf gain I rather see React fix it, emotion drop their workaround and we don't have to change any code (sounds great to me :wink:). That way everyone benefits and not just emotion users.

**Comment by gaearon** [comment] 2020-10-17 14:36
> I was told this was for performance reasons.

A benchmark showing the difference would be very useful.

**Comment by gaearon** [comment] 2020-10-17 14:38
> We issue a warning if we're sure that these components cannot hold a ref i.e. typeof Component === "function" && Component.prototype?.isReactComponent === false

I’m confused by this. Doesn’t this prevent people from passing completely valid forwardRef components? It sounds like this limitation would force people to unnecessarily use classes.

**Comment by eps1lon** [comment] 2020-10-17 16:08
> I’m confused by this. Doesn’t this prevent people from passing completely valid forwardRef components? It sounds like this limitation would force people to unnecessarily use classes.

`Component.prototype?.isReactComponent === false` was hand-waving `!isReactClassComponent` which covers more edge cases. We're disallowing certain component types e.g. plain functions instead of allowing certain components. There's no API to check element-types. We only reject plain functions that aren't class components. `forwardRef` does not return a function.

Full code: https://github.com/mui-org/material-ui/blob/b2903d6362e6fd450167f9278ca0b2a666b6de2f/packages/material-ui-utils/src/elementTypeAcceptingRef.ts#L4-L49
Test suite: https://github.com/mui-org/material-ui/blob/d9d60e615470d78a721f5d392a84aaf892637a17/packages/material-ui-utils/src/elementTypeAcceptingRef.test.tsx#L63

**Comment by gaearon** [comment] 2020-10-17 16:26
In this case it seems like we have two libraries trying to do a clever trick (one tries to conditionally apply a wrapper, another one tries to make a better warning than a built-in one) and the combination doesn’t quite work. That, unfortunately, happens with clever tricks.

I think the correct solution to this would be for Emotion to remove the conditional wrapping. The rationale is similar to why we show key warnings even on the server. Even if you start using React in some purely static way (eg static site generator) you shouldn’t run into a ton of warnings when you add client rendering. Therefore, Material should warn if you pass a non-forwarding component even on the server. Therefore, Emotion should not pretend that their component isn’t capable of ref forwarding (because it is). This also avoids the problem that you work around this in Material, but every other similar lib that supports Emotion users has to copy the same trick.

If there’s something slow about forwardRef about on the server, I’d like to see a benchmark. Then I could take a stab at optimising it.

**Comment by eps1lon** [comment] 2020-10-17 16:36
> Therefore, Material should warn if you pass a non-forwarding component even on the server. 

I didn't even know React doesn't warn about it on the server. Your language is a bit weird here. Do you suggest we shouldn't warn about this on the client either? Because not forwarding the ref does cause actual issues on the client. We're only adding this validation if our components actually need the ref. But since we can't know where React is currently rendering we have to rely on clever tricks.

**Comment by gaearon** [comment] 2020-10-17 16:42
>I didn't even know React doesn't warn about it on the server. 

Sorry, I'm not quite following what you mean. But I'm saying that ideally React should have the same warnings on the client and on the server. If some warning is missing in the server renderer, it is not intentional — we should add it. And by the same logic, I don't think a workaround where Material tries to detect if it's "on the server" is the right one. Both because, as I just mentioned, ideally the warnings should be the same between server and client — and because, as you mentioned, the concept of "being on the server" is not entirely clear anyway and there are edge cases with SSR being run on the client.

>Do you suggest we shouldn't warn about this on the client either? Because not forwarding the ref does cause actual issues on the client.

I believe I suggested the opposite. I suggested that you keep your warning as is, but that Emotion removes the "conditional rendering" behavior. I think that would resolve your problem?

>We're only adding this validation if our components actually need the ref. But since we can't know where React is currently rendering we have to rely on clever tricks.

This is a valid point, and I think it's why "warn in Material", while OK today, is not a great long-term approach. In long term, there would be no `forwardRef` at all, `ref` would just be a regular prop. In that world, your detection mechanism won't work anyway.

I think the underlying problem here is that the warning React provides is ambiguous so you're trying to work around it by providing a more specific userland warning. But this doesn't solve the future case where you won't be able to detect it. Which is why in the end we should probably fix this in React somehow. For example, maybe we could have a separate warning about refs not being properly "consumed". I don't know yet if this is possible though as I haven't really thought about this. Maybe that's the feature request here?

**Comment by eps1lon** [comment] 2020-10-17 17:33
> Sorry, I'm not quite following what you mean. But I'm saying that ideally React should have the same warnings on the client and on the server.

I would expect the same which would not be in the interest of emotion because their conditional forwardRef would produce additional warning

> believe I suggested the opposite.

The choice of words ("even on the server") threw me off.

> And by the same logic, I don't think a workaround where Material tries to detect if it's "on the server" is the right one. 

Agreed. Though we have to be practical about warnings that don't produce any problem in current React.  So while not ideal we're definitely adding it for now so that we don't start ignoring warnings.

> while OK today, is not a great long-term approach. In long term, there would be no forwardRef at all, ref would just be a regular prop. In that world, your detection mechanism won't work anyway.

It's definitely not something we intended to keep for long. Mainly as a migration helper for a short period of time. The assumption was that react forwarding refs without `forwardRef` would be released in a major release so we were somewhat save by SemVer + peerDependencies.

> I think the underlying problem here is that the warning React provides is ambiguous so you're trying to work around it by providing a more specific userland warning. [...] Maybe that's the feature request here?

The actual feature request would be that the component stack trace would only list owners and not individual components. It doesn't matter to the user of Material components what the internal component structure looks like. So if we render

```jsx
function Demo() {
  return (
    <Tooltip title="test">
      <Component />
    </Tooltip>
  );
}
```

I'd rather see 

```diff
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

-Check the render method of `ForwardRef(Tooltip)`.
+Check the render method of `Demo`.
    in Component (at Demo.js:17)
-   in ForwardRef(Tooltip) (created by Tooltip
    in Tooltip (at Demo.js:16)
    in Demo (at src/index.js:6)
```

But I think this is only desired for 3rd party libraries.

**Comment by gaearon** [comment] 2022-03-25 23:13
We can probably close this now. The expectation _is_ that the output observed by React is identical. Especially because with streaming, hydration starts _before_ all the chunks have arrived. So there is no "before" at which you can extract everything.

For injecting styles into the stream, there's a writeup at https://github.com/reactwg/react-18/discussions/110.

**Closed by gaearon** 2022-03-25 23:13 UTC
Labels: Type: Discussion
