### ISSUE TITLE
Bug: keydown Event - inconsistent behaviour

### ISSUE THREAD

**Issue by damianOfKyan** [facebook/react#18653] opened 2020-04-17 12:20 UTC
There is inconsistency in Event triggering.
Can be observed by testing in Chrome and Firefox.
In below code example:
In Chrome, On button focus, when "Space" bar keypress, React triggers 1x keydown Event
In Firefox, On button focus, when "Space" bar keypress, React triggers 1x keydown Event and 1x click Event

https://codesandbox.io/s/confident-nobel-9bos1?file=/src/button.js

React version: 16.2.1 (tested)

## The current behavior
Two events fired when keypress, keydown & click

## The expected behavior
One event fired, when keypress, keydown

React should handle this events exactly same.

**Comment by bvaughn** [comment] 2020-04-17 15:52
I think the expected behavior here is wrong. I think two events should fire: "keydown" (on keydown) and "click" (on keyup). This is what Chrome, Firefox, and Safari do by default.

**Comment by bvaughn** [comment] 2020-04-17 15:53
cc @trueadm

**Comment by pswartz66** [comment] 2020-04-17 16:57
Tested on chrome and I don't see any console.log for the keydown event either.

See screenshot:
![image](https://user-images.githubusercontent.com/33533794/79594387-ec91df80-80aa-11ea-80eb-1a802def5122.png)

**Comment by bvaughn** [comment] 2020-04-17 16:59
You have to actually focus the button.

**Comment by eps1lon** [comment] 2020-04-17 17:00
That's the same behavior you observe with native html. It's indeed confusing that preventing the default in keydown prevents the default of the keyup (which is dispatching a click if the key is Space).

To me it looks like firefox is behaving correctly. It shouldn't prevent the click dispatch in keyup if we didn't prevent the default of the keyup event.

**Comment by aweary** [comment] 2020-04-17 17:06
> To me it looks like firefox is behaving correctly. It shouldn't prevent the click dispatch in keyup if we didn't prevent the default of the keyup event.

According to the [UI Events spec](https://www.w3.org/TR/uievents/#event-type-keydown), the `keydown` event should dispatch a `click` event as part of the default action, and `preventDefault` prevents the default action. So I think Chrome is behaving correctly here.

**Comment by bvaughn** [comment] 2020-04-17 17:27
Oh snap, I scanned the Sandbox too quickly and didn't notice the `preventDefault` bit. Agreed!

**Comment by bvaughn** [comment] 2020-04-17 17:29
Given that- and the fact that [Firefox reproduces the same behavior without React involved](https://codesandbox.io/s/broken-bird-f1eob?file=/src/index.js), I think we can close this:

**Comment by aweary** [comment] 2020-04-17 17:31
I think the only open question is whether we should attempt to normalize the `preventDefault` behavior? I'm not sure if there's much we can do if the native `click` event isn't being dispatched but maybe @trueadm has thoughts 🙂

**Comment by rachelnabors** [comment] 2020-07-17 13:09
The problem lies in the inconsistent UI Event spec implementations across browsers. You can [file a bug with Firefox](https://bugzilla.mozilla.org/enter_bug.cgi) and [Chrome](https://bugs.chromium.org/p/chromium/issues/list) to help support web standards adoption. We used to try to normalize inconsistent browser behavior, but over the years it's proven more productive to rely on vendors working together to adhere to standards to the benefit of all libraries and the Web at large :)

**Closed by rachelnabors** 2020-07-17 13:09 UTC
