### ISSUE TITLE
Error: "Commit tree does not contain fiber 97. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by benftwc** [facebook/react#18903] opened 2020-05-13 10:39 UTC
Describe what you were doing when the bug occurred:
1. Open the Profiler after playing a while with some React Application
2. Try to reach some snap with the player
3. This happens

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162825)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161772)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:164582)
    at ec (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:339280)
    at ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59620)
    at nl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:69923)
    at Ll (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:110996)
    at qc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102381)
    at Hc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102306)
    at Vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102171)

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by irohitb** [comment] 2020-05-14 01:04
Possible duplicate of https://github.com/facebook/react/issues/18859

**Comment by benftwc** [comment] 2020-05-15 21:09
Yep, seems duplicate

**Comment by bvaughn** [comment] 2020-05-18 20:49
Going to close this as a duplicate of #18831

**Closed by bvaughn** 2020-05-18 20:49 UTC

**Comment by bvaughn** [comment] 2021-04-28 20:30
@benftwc  This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼
