### ISSUE TITLE
multiple checkbox/toggle affecting state

### ISSUE THREAD

**Issue by tomasinouk** [facebook/react#6466] opened 2016-04-09 08:10 UTC
hi guys, 

I am experiencing _strange_ behaviour, if I have couple of checkboxes. 
It behaves that other checkbox change state of other after selecting. Below is a snippet for the reference.

On other hand, I might overlooked something, but cannot see it :( 
any advise would be great.

 ```javascript

import { default as React, PropTypes } from 'react';
import mui from 'material-ui';

import getMuiTheme from 'material-ui/lib/styles/getMuiTheme';
import Checkbox from 'material-ui/lib/checkbox';

let injectTapEventPlugin = require('react-tap-event-plugin'); 
 
  const styles = {
  block: {
    maxWidth: 150,
  },
  checkbox: {
    marginBottom: 1,
  },
    toggle: {
    marginBottom: 1,
  },
};
  
  class IoTable extends React.Component {
  
  constructor(props) {
    super(props);

    this.state = {
      camera: props.camera,
      wifi: false,
      router: false,
      cameraText: toString(props.camera),
    };
    this.handleChange = this.handleChange.bind(this);
  }

  getChildContext() {
      return {
          muiTheme : getMuiTheme()
      }
  }
  componentWillMount() {
    injectTapEventPlugin();
  }

  handleChange() {
        this.setState(
            {
            camera: !this.refs.cameraInput.state.switched,
            router: !this.refs.routerInput.state.switched,
            // wifi: this.refs.wifiInput.state.switched,
            } 
          );

        var text = String(!this.refs.cameraInput.state.switched);
        this.setState({cameraText: text});

          console.log("refs.camera.switched: " + !this.refs.cameraInput.state.switched);
          console.log('camera: ' + this.state.camera); 
  }

  render() {

    return (
      <div>
      <h2>IO State</h2>
      
      <div>this.state.camera: {this.state.cameraText}</div>
          <div style={styles.block}>
            <Checkbox
            label="Camera" 
            onTouchTap={this.handleChange}
            ref="cameraInput"
            style={styles.toggle}
            defaultToggled={this.props.camera}
            />
          </div>

          <div style={styles.block}>
            <Checkbox
            label="Router"
            onTouchTap={this.handleChange}
            ref="routerInput"
            style={styles.toggle}
            
            />
          </div>
            
    </div>
    );
  }
}
  
  IoTable.PropTypes = {
    camera: PropTypes.bool,
    cameraText: PropTypes.string,
  };

  IoTable.defaultProps = {
    camera: true,
    cameraText: '',
  }

IoTable.childContextTypes = {
   muiTheme: React.PropTypes.object
};

export default IoTable;
```

**Comment by gaearon** [comment] 2016-04-09 12:01
I don’t think this is a bug in React. This code has a fundamental problem: it reads the private `state` of a ref. This should never be the case in React apps. Instead, you should pass the new value to the `onChange` handler. And the child should not be stateful: instead, the state should live in the parent component, and `Checkbox` should merely reflect the props passed to it. This way the data flow is easy to think about because there is just one source of truth, that is, the parent component. 

In React, `setState` is asynchronous. This is why reading `state` right away won’t work. And in any case reading *other* component’s state is always discouraged: it is private by design.

I think you might find this guide helpful: https://facebook.github.io/react/docs/thinking-in-react.html. It explains how state ownership works in React apps. Please don’t skip it because it is absolutely essential, and you’re going to run into more issues if you keep using multiple sources of truth and reach into private component state from other components.

If you refactor the code to use the top-down data flow and the problem persists please let us know and try to provide a fiddle where you can reproduce this. Right now this looks like incorrect usage so I am closing. Cheers!

**Closed by gaearon** 2016-04-09 12:01 UTC

**Comment by tomasinouk** [comment] 2016-04-10 09:26
thanks @gaearon for quick reply, you saved my day with your few pointers.

realising that `setState` is asynchronous and double checking the top-down data flow (I have that, just did not know how to post it) I realised, I am doubling on props passing via `jsx`.

Thank you heaps. 
Yes, no issue with React.

**Comment by gaearon** [comment] 2016-04-10 11:51
Glad it helped!
