### ISSUE TITLE
When I console.log(), the Chrome console gives the log but instead of showing the file and line number 

### ISSUE THREAD

**Issue by mahanthi-arun-kumar** [facebook/react#22270] opened 2021-09-08 13:27 UTC
When I console.log(), the Chrome console gives the log but instead of showing the file and line number it just says react_devtools_backend.js:4049. How do I get the console to show the file and line number when I console.log()?

**Comment by bk973** [comment] 2021-09-08 13:42
Hello @mahanthi-arun-kumar is there some code that you can show???

**Comment by gaearon** [comment] 2021-09-08 13:56
Duplicate of https://github.com/facebook/react/issues/22257.

**Closed by gaearon** 2021-09-08 13:56 UTC

**Comment by gaearon** [comment] 2021-09-09 17:35
Here's a temporary workaround: https://github.com/facebook/react/issues/22257#issuecomment-916174962
