### ISSUE TITLE
Bug: Button onClick event doesn't trigger function (React + Express)

### ISSUE THREAD

**Issue by RFlintstone** [facebook/react#21640] opened 2021-06-07 17:33 UTC
## Dependency versions:

    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0"

## Steps To Reproduce

1. Setup express.js (with router)
2. Setup react as view engine
3. Use `<button onClick={() =&gt; sayHello("Test")} style={{ position: "absolute", top: "40%" }}</button>` and a function called sayHello. 
4. When express is running and the button is clicked the function **wont** execute. 

#### Link to code example:
https://github.com/RFlintstone/express-react-movies/blob/main/views/index.jsx
/
https://github.com/RFlintstone/express-react-movies

If you try it on CodeSandbox it does work:
https://codesandbox.io/s/twilight-water-n07o4?file=/src/App.js

## The current behavior
If the button is clicked the function **wont** be triggered. 

## The expected behavior
If the button is clicked the function **is** triggered

**Comment by christopherrobin** [comment] 2021-06-16 02:46
I am seeing this work as intended using the dependencies you listed. The code snippet used to test is below. This is not an issue with React; however, it could relate to your other dependencies. What does your `package.json` look like?

```
import React from 'react';

const App = () => {
    function sayHello(name) {
        alert(`hello, ${name}`);
    }
    return (
        <button onClick={() => sayHello('Test')}>Test</button>
    );
};

export default App;

```

**Comment by bvaughn** [comment] 2021-06-16 16:40
Going to close this issue for now.

**Closed by bvaughn** 2021-06-16 16:40 UTC
Labels: Status: Unconfirmed
