### ISSUE TITLE
[React 19] Cannot assign to readonly property

### ISSUE THREAD

**Issue by hipstersmoothie** [facebook/react#30172] opened 2024-07-01 16:26 UTC
## Summary

I'm using https://waku.gg to use react components. I was trying to upgrade to the latest 19 rc and I started getting getting this error:

![image](https://github.com/facebook/react/assets/1192452/c8452687-af93-48cf-a549-5cb20d6354ed)

I boiled down the app into just a few file to demonstrate the issue [here](https://github.com/hipstersmoothie/waku-repro/)

The issue is as follow:

```tsx
// Client context Provider
import { StoryContextProvider } from "../../components/Context";
// Server Component
import A11yDecorator from "../../A11yDecorator";
// Client Component
import CenteredDecorator from "../../CenteredDecorator";

export default function Iframe() {
  const page = {};

  return (
    <StoryContextProvider value={{ page }}>
      <CenteredDecorator page={page}>
        <A11yDecorator page={page}>
          foo
        </A11yDecorator>
      </CenteredDecorator>
    </StoryContextProvider>
  );
}
```

Some observations:

- If I switch the order of `A11yDecorator` and `CenteredDecorator`, the app renders
- If I don't use a shared `page` variable and just pass objects to the relevant places, the app renders
- If I spread the `page` and make an new object when passing to the relevant places, the app renders

**Comment by hipstersmoothie** [comment] 2024-07-01 17:16
[I did](https://github.com/dai-shi/waku/issues/766). The example code is pretty light. I could potentially test against next.js too

cc @dai-shi

**Comment by himself65** [comment] 2024-07-01 19:21
I personally don't think this is a react issue. Seems like something happened in parser process

**Comment by dai-shi** [comment] 2024-07-02 09:38
I originally thought it's a Waku's issue. But, as it turns out, it reproduces with changing React beta, without changing Waku.

@hipstersmoothie I would recommend to find which commit in React causes the, and look for the background of the change. My gut feeling is that this change is intentional (for safety or something).

**Comment by eps1lon** [comment] 2024-07-02 11:11
> // Server Component
> import A11yDecorator from "../../A11yDecorator";

This is a client component according to the repro: https://github.com/hipstersmoothie/waku-repro/blob/aec12ed7c9594950987157242f80cec86957a71e/src/A11yDecorator.tsx#L1

**Comment by eps1lon** [comment] 2024-07-02 11:27
I can't repro this in React's test suite (https://github.com/facebook/react/pull/30194) but I can repro it in Next.js (https://github.com/eps1lon/waku-repro-as-nextjs)

**Comment by dai-shi** [comment] 2024-07-02 14:54
So, is it an already fixed bug? I wonder if `-rc.1` will be released.

**Comment by eps1lon** [comment] 2024-07-22 14:38
Fixed in https://github.com/facebook/react/pull/29823.

The current plan is to release `rc.1` after https://github.com/facebook/react/issues/29898 is resolve

**Closed by eps1lon** 2024-07-22 14:38 UTC
Labels: Type: Bug, React 19
