### ISSUE TITLE
Event Handler on React Component not invoked when React Component is rendered inside a Web Component

### ISSUE THREAD

**Issue by nilshartmann** [facebook/react#9242] opened 2017-03-23 12:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A React Component with an Event Handler (for example onClick) is rendered inside a Web Component. When the Component is clicked the Event does not receive the React Component (specified callback is not invoked)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

You can reproduce it with Web Component example contained in the react repository (https://github.com/facebook/react/blob/master/examples/webcomponents/index.html): Replace the 'a' element with a button and add for example an onClick event handler. 

You can find a modified version of the Web Component example (based on the 15.4.2 codebase - https://github.com/facebook/react/blob/v15.4.2/examples/webcomponents/index.html) here:
https://gist.github.com/nilshartmann/3a520920e5fc920bfde49e077ad3beab#file-index-html-L50 

**What is the expected behavior?**
The event handler should be called.

For testing I have modified `getEventTarget.js` to return the target from the `path` property of the `nativeEvent` (instead of the "original" `target` from the `nativeEvent`). With this addition it works - 
the Event Handler is called.

You can find the modified version also in the gist: https://gist.github.com/nilshartmann/3a520920e5fc920bfde49e077ad3beab#file-geteventtarget-js-L6

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.4.x and 16.x
I've tested in Chrome, Firefox and Safari. I don't know if it works in previous versions of React (don't think so)

**Comment by DeanBDean** [comment] 2017-03-23 19:09
@nilshartmann Should path be composedPath() instead?

https://hayato.io/2016/shadowdomv1/#getting-event-path

By the way, this almost entirely solves an issue I was having where events were not being captured by a web component that encapsulated a ReactDOM.

**Comment by mgrdevport** [comment] 2017-04-10 06:02
@DeanBDean You are right. We were using Chrome to investigate the event bubbling issue months ago, which gave us access to the event.path property. We are using the webcomponentsjs polyfill to make the shadow dom available in all browsers. Today the polyfill (shadyDom) provides us the composedPath() function, so we should maybe change it to the following:

```javascript
// If encapsulated in a Web Component use the composed Event path
if(nativeEvent.composedPath && nativeEvent.composedPath()) {
    return nativeEvent.composedPath()[0];
}
```

**Comment by sutkh** [comment] 2017-05-21 18:26
I'm having the same problem, is there a workaround for this currently?

**Comment by gaearon** [comment] 2017-10-04 18:59
We should confirm whether it still happens on master with native web components.
(16.0.0 WC support is borked but I fixed it on master.)

**Comment by larkintuckerllc** [comment] 2017-10-08 19:56
First, I have also observed this first hand with React 16.0.0 (today). Also confirmed that a fellow opened up a related issue and wrote a working temporary fix, https://www.npmjs.com/package/react-shadow-dom-retarget-events .

While I do not see a use case for web components in my React applications, I am considering using React in building more complicated web components to be delivered to other platforms (I am thinking for WordPress bloggers; or similar).

**Comment by rytisbac** [comment] 2017-10-13 06:25
Same problem here... Created component with react and want to include it to other sites - similar as iframe.  The only way it can work is to retarget events. But I think it realy hurts performace

**Comment by robdodson** [comment] 2017-10-17 06:11
Does React use event delegation to listen for clicks on React components? If so I imagine the shadow boundary would get in the way of that... Just want to make sure I understand the problem :)

**Comment by xastor** [comment] 2017-11-22 11:15
The react-shadow-dom-retarget-events module works, but has a few problems of its own.  If I'm correct, it picks on the native events on the shadow dom element, and then directly calls the react component event handlers (onClick, etc.. ) using those native events, instead of synthetic events.  I think that because of this, stopPropagation() does not work.

It would be nice to see the React team pick this issue up and provide a proper fix. Shadow dom is gaining momentum! :-)

**Comment by marionebl** [comment] 2018-02-05 20:06
Is there interest in a fix based on the suggestions by @nilshartmann? I'd be happy to contribute the required changes and new tests if required.

**Comment by opichals** [comment] 2019-05-29 08:25
Tested using the `event.composePath()` in https://github.com/opichals/react/tree/add-event-target-composePath-support

**Comment by renegare** [comment] 2019-09-23 13:23
Not sure if this is still an issue with anyone; I however found the following addition to your react app entry point will work:

```
class CustomElement extends HTMLElement {
  connectedCallback() {
    // setup
    const shadow = this.attachShadow({ mode: "open" });
    const root = document.createElement("div");
    shadow.appendChild(root);

    // Making the shadow appear like document 
    // so react events work as normal
    Object.defineProperty(root, "ownerDocument", { value: shadow });
    shadow.createElement = (...args) => document.createElement(...args);

    ReactDOM.render(<App />, root);
  }
}
customElements.define("custom-element", CustomElement);
// DONT FORGET to add <custom-element></custom-element> to your page
```

The rationale here is:
* react event system does work normally
* shadow dom re-targeting is the issue
* custom re-re-targeting is complex; and does not reliably work with events that do not bubble - example focus and blur
* instead of react binding to document it should bind to the shadow. Because as far as css and js events that is the true document root of a shadow dom
* react binds event listeners to the `ownerDocument` property of the root element it renders into. It expects that to be document.
* `createElement` appears to be the only method missing from the shadow element, which react needs

This works with the create-react-app setup.

Any issues one can foresee taking this approach?

**Comment by renegare** [comment] 2019-09-23 13:25
if my assumptions are correct; this issue is not a problem or an issue on the react side at least.

But what could be cool is for `ReactDOM.render` to have a third `options` arg? which allows you better customize all global props it depends on to function e.g `document`

**Comment by GeorgeTaveras1231** [comment] 2019-09-23 16:57
@renegare Your approach seemed to work for me except that there were a couple of other APIs that react depended on that I needed to add to the shadow root:

- `createElementNS`
- `createTextNode`

**Comment by renegare** [comment] 2019-09-23 17:19
I think this beats maintaining a list of events. Maintain a list of document methods 

... but as you can see be aware this is a hack!

**Comment by patrickpietens** [comment] 2019-10-07 10:45
This is definitely the best solution so far. However, I still can't get `createPortal()` to work.

**Comment by chrisparton1991** [comment] 2019-10-17 10:48
Unfortunately `customElements.define` is `null` inside Chrome extension content scripts (possibly Firefox too, I haven't checked). See https://bugs.chromium.org/p/chromium/issues/detail?id=390807.

I'm trying to convert a Chrome extension to use React. The content script uses a shadow DOM to avoid styling conflicts from the host page.

At the moment it looks like I'll have to remove the shadow DOM and do my best to override any weird styling that I come across.

**Comment by scythargon** [comment] 2019-10-21 15:15
Can't make SyntheticEvent's of `react-bootstrap` package work when it's component is rendered inside shadow DOM...

**Comment by renegare** [comment] 2019-10-21 16:34
> Unfortunately `customElements.define` is `null` inside Chrome extension content scripts (possibly Firefox too, I haven't checked). See https://bugs.chromium.org/p/chromium/issues/detail?id=390807.

yeah sounds like web components are yet to be enabled within the context of an extension. But why do you need it there, out of interest? I believe an extension sandboxed so you can do as you please (kinda) without the need of a custom element.

**Comment by chrisparton1991** [comment] 2019-10-21 22:23
@renegare I'm using a shadow root because I need to inject an overlay onto particular websites, and the parent website styles will often conflict with mine. I've even had one site mutate my DOM to wrap my input fields.

**Comment by JonyE** [comment] 2019-12-17 14:03
@chrisparton1991 u can get window, see here https://gist.github.com/devjin0617/3e8d72d94c1b9e69690717a219644c7a
as about shadow dom: https://www.npmjs.com/package/react-shadow

**Comment by adrian-dobre** [comment] 2020-03-04 15:41
I found one issue with @chrisparton1991 's solution: If you use React Portals the reference to owner document is lost (because it uses document.createElement directly instead of ownerDocument). You could try to avoid Portals usage, unfortunately you could rely on some libs that use Portals (like ant design system - modal). 

However, if the parent container (passed in with getContainer) is created inside the shadowRoot (and it should be, otherwise this is not a problem), relying on the fact that Portal Wrapper does something like _parent.appendChild_ you can rewrite parent.appendChild to also add ownerDocument :)

`
changeOwnerDocumentToShadowRoot(element: HTMLElement, appContainer: ShadowRoot) {
     Object.defineProperty(element, 'ownerDocument', {value: appContainer});
 }

augmentAppendChildWithOwnerDocument(elem: HTMLElement, appContainer: ShadowRoot) {
        const origAppChild = elem.appendChild;
        const propDesc = Object.getOwnPropertyDescriptor(elem, 'appendChild');
        if (!propDesc || propDesc.writable) {
            Object.defineProperty(elem, 'appendChild', {
                value: function (child: HTMLElement) {
                    changeOwnerDocumentToShadowRoot(child, appContainer);
                    origAppChild?.call(elem, child);
                }
            });
        }
    }

augmentCreateElementWithOwnerDocument(appContainer: ShadowRoot, createFnName: keyof Document) {
        const originalCreateFn = document[createFnName] as Function;
        appContainer[createFnName] = (...args) => {
            const element = originalCreateFn.call(document, ...args);
            changeOwnerDocumentToShadowRoot(element, appContainer);
            augmentAppendChildWithOwnerDocument(element, appContainer);
            return element;
        };
    }

changeOwnerDocumentToShadowRoot(appRootNode as HTMLElement, appContainer);
augmentCreateElementWithOwnerDocument(appContainer, 'createElement');
augmentCreateElementWithOwnerDocument(appContainer, 'createElementNS');
augmentCreateElementWithOwnerDocument(appContainer, 'createTextNode');
`
Hopefully this will help somebody having the same problem. Sorry for the somewhat confusing code, I pulled it out from my solution without cleanup

**Comment by nlrowe-pfg** [comment] 2020-03-25 18:33
I switched from react-shadow-dom-retarget-events to renegare fix and all was working well in modern browsers. Unfortunately, this seems to be causing issues with the [webcomponents pollyfill](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs) in at least edge and IE. I believe it is altering `this.ownerDocument` on this [line](https://github.com/webcomponents/polyfills/blob/9f73cf59a68fcbd789426cb476e6c21946796958/packages/shadydom/src/patches/Node.js#L179) and it throws 'SCRIPT65535: Invalid calling object'.

**Comment by nlrowe** [comment] 2020-03-25 18:35
I switched from react-shadow-dom-retarget-events to renegare fix and all was working well in modern browsers. Unfortunately, this seems to be causing issues with the webcomponents pollyfill in at least edge and IE. I believe it is altering this.ownerDocument on this line and it throws 'SCRIPT65535: Invalid calling object'.

**Comment by stevematney** [comment] 2020-04-06 14:43
We've built out a fairly small solution for this problem called [`react-html-element`](https://github.com/WTW-IM/react-html-element). It's extremely early in its development, so it probably doesn't cover every use case, since there are certainly some we don't know about.

We'll be dogfooding this in our internal projects, but would love anybody that wants to try it out to do so! Please log issues if you find them, as we have a vested interest in it being robust and useful!

**Comment by gaearon** [comment] 2020-08-17 14:46
This has been fixed in React 17.

Fiddle with 16: https://codesandbox.io/s/elegant-wilson-jirq9?file=/src/index.js
Fiddle with 17: https://codesandbox.io/s/nifty-benz-rflo0?file=/package.json

**Closed by gaearon** 2020-08-17 14:46 UTC
Labels: Component: DOM, Type: Discussion

**Comment by stevematney** [comment] 2020-08-17 17:30
> This has been fixed in React 17.

@gaearon was #15894 the fix for this?

**Comment by gaearon** [comment] 2020-08-17 17:31
No, it was the changes to event delegation (to attach events at the root).

https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation
https://github.com/facebook/react/pulls?q=is%3Apr+author%3Atrueadm+modern+event+is%3Amerged

**Comment by stevematney** [comment] 2020-08-17 17:35
That looks great! It seems like the perfect fix. Thank you!

**Comment by wugaoliang1116** [comment] 2023-03-06 08:12
升级react 18吧

**Comment by kudorgyozo** [comment] 2023-06-28 17:21
Is this fixed?

**Comment by tozz** [comment] 2023-06-29 10:29
@kudorgyozo If you look five comments up.

> This has been fixed in React 17.
> 
> Fiddle with 16: https://codesandbox.io/s/elegant-wilson-jirq9 Fiddle with 17: https://codesandbox.io/s/nifty-benz-rflo0
> 
> There may still be some corner cases so feel free to file new issues if something doesn't work.
