### ISSUE TITLE
React Dev Tools: Components never shows up anymore

### ISSUE THREAD

**Issue by lilithebowman** [facebook/react#19194] opened 2020-06-25 14:07 UTC
Google Chrome Extension does not work anymore.

Google Chrome is up to date
Version 83.0.4103.116 (Official Build) (64-bit)

Most of the time, the new developer tabs never show up.

If I kill the whole process and re-load it, sometimes it will load, sometimes it doesn't. 

The plugin has access to all data on all sites.

Was this plugin ever updated to use the new plugin format?

Note: I didn't initially realize this is the entire react project and not the dev tools plugin. Not sure why the dev tools plugin page in Chrome sent me here for support.

**Comment by bvaughn** [comment] 2020-06-25 14:25
This is a duplicate of #19002 which is caused by [Chromium bug 1085215](https://bugs.chromium.org/p/chromium/issues/detail?id=1085215).

**Closed by bvaughn** 2020-06-25 14:26 UTC
