### ISSUE TITLE
React DevTools not persisting settings

### ISSUE THREAD

**Issue by brianblakely** [facebook/react#16556] opened 2019-08-23 15:08 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

DevTools extension does not persist state. For example, the “Welcome” dialog displays upon every refresh.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

1. Open React DevTools in a React app.
2. Change DevTools settings.
3. Refresh app in browser. 

**What is the expected behavior?**

Settings should be changed. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This is in a corporate install of Chrome 71. It’s possible that it blocks whichever persistence API React DevTools is using (Chrome DevTools itself persists settings successfully).

**Comment by bvaughn** [comment] 2019-08-23 17:50
Duplicate of #16475, let's roll discussion into that issue.

I think this is because local storage API is not enabled, which (unfortunately) affects extensions too. We can (and probably should) change the Welcome screen to use a different extension API (assuming it doesn't require extra permissions). I don't think we could easily do this for other preferences though, since the extensions storage API is _async_ and that causes a lot of complexity for e.g. component filters.

**Closed by bvaughn** 2019-08-23 17:50 UTC
