### ISSUE TITLE
onPaste event firing on wrong target

### ISSUE THREAD

**Issue by peonmodel** [facebook/react#12031] opened 2018-01-17 03:57 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
pasting this string "12/11/2013" into either of the 2 input fields, one of type date and the other text
```
<input type="text" id="1" onPaste={e => console.log(e.target, e.clipboardData.getData('text'))}/>
<input type="date" id="2" onPaste={e => console.log(e.target, e.clipboardData.getData('text'))}/>
```
result from console:
```
<input type="text" id="1"> "12/11/2013" // when pasting into the date input
<input type="text" id="1"> "12/11/2013"  // when pasting into the text input
```
when pasting into either input, the event.target is the input[type=text]

**What is the expected behavior?**
event target should be input type date when pasting into the date input and likewise for type text
```
<input type="text" id="1"> "12/11/2013"
<input type="date" id="2"> "12/11/2013"
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
"react": "^16.2.0",
"react-dom": "^16.2.0",
```
Chrome: Version 63.0.3239.132 (Official Build) (64-bit)

For Firefox 57.0.1
the paste event does not trigger on the input[type=date] at all

**Comment by vldvel** [comment] 2018-01-17 08:49
It's not a bug. Just try reload page and select input date first and then paste your string - it won't work, cause you can't do that in chrome. But if you choose input type text first and paste it works fine.
So problem here is that you still passing string in type text and not in type date. And get same output each time.

**Comment by gaearon** [comment] 2018-01-28 13:15
Closing per above comment (I haven't checked). If you're sure it's a React bug please prepare *runnable* examples (e.g. fiddles) with and without React that demonstrate this issue is specific to React.

**Closed by gaearon** 2018-01-28 13:15 UTC
