### ISSUE TITLE
Hover bug: If you mouse in and out of element quickly hover appears but then doesn't go away when using onMouseEnter and onMouseLeave

### ISSUE THREAD

**Issue by paulwehner** [facebook/react#3806] opened 2015-05-03 11:20 UTC
Here is a JSFiddle: https://jsfiddle.net/y9swecyu/5/

Video of JSFiddle that shows how when you mouse over quickly, sometimes the onMouseLeave doesn't seem to register: https://vid.me/ZJEO

Finally a StackOverflow: http://stackoverflow.com/questions/29981236/how-do-you-hover-in-reactjs-onmouseleave-not-registered-during-fast-hover-ove

```
var Hover = React.createClass({
    getInitialState: function() {
        return {
            hover: false
        };
    },
    onMouseEnterHandler: function() {
        this.setState({
            hover: true
        });
        console.log('enter');
    },
    onMouseLeaveHandler: function() {
        this.setState({
            hover: false
        });
        console.log('leave');
    },
    render: function() {
        var inner = normal;
        if(this.state.hover) {
            inner = hover;
        }

        return (
            <div style={outer}>
                <div style={inner}
                    onMouseEnter={this.onMouseEnterHandler}
                    onMouseLeave={this.onMouseLeaveHandler} >
                    {this.props.children}
                </div>
            </div>
        );
    }
});

var outer = {
    height: '120px',
    width: '200px',
    margin: '100px',
    backgroundColor: 'green',
    cursor: 'pointer',
    position: 'relative'
}

var normal = {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'red',
    opacity: 0
}

var hover = {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'red',
    opacity: 1
}

React.render(
    <Hover></Hover>,         
    document.getElementById('container')
)
```

**Comment by levibuzolic** [comment] 2015-05-05 23:07
I don't think this is a React bug, as you can encounter this same issue using native JS, jQuery or any other library. I imagine it's a limitation of browser performance.

On my computer I was unable to reproduce the issue with your component, however I think that will be due to a performance difference between my machine and yours.

**Comment by gaearon** [comment] 2017-10-04 11:21
I’ll close this report as it doesn’t specify crucial details like OS, browser, and its version.

I am not able to reproduce it, and for the lack of details, I’m assuming it was a transient browser bug.

**Closed by gaearon** 2017-10-04 11:21 UTC
