### ISSUE TITLE
Bug: setValue hooks not working!

### ISSUE THREAD

**Issue by berkbaski** [facebook/react#21050] opened 2021-03-22 15:26 UTC
Firstly, so easy! I was execute the setMyLocation function with values.
Secondly, i was write a console.log and then value still null.

ABSOLUTELY I didn't understand.

React version: 16.13.1

## Steps To Reproduce

![Screen Shot 2021-03-22 at 18 13 31](https://user-images.githubusercontent.com/25839586/112014654-27fb2080-8b3c-11eb-9ef8-66c2f8b0e89b.png)
![Screen Shot 2021-03-22 at 18 13 18](https://user-images.githubusercontent.com/25839586/112014659-292c4d80-8b3c-11eb-998f-f735b37d5c72.png)

Link to code example: https://gist.github.com/berkbaski/95c935a530876aba9e7573f4ee57652c#file-page-js

## The current behavior
NOT CHANGE STATE VALUE!

## The expected behavior
DIDN'T CHANGE STATE VALUE

**Comment by berkbaski** [comment] 2021-03-22 15:30
it's still not working when given static value.

![Screen Shot 2021-03-22 at 18 29 31](https://user-images.githubusercontent.com/25839586/112015235-afe12a80-8b3c-11eb-9193-a626671294fb.png)
![Screen Shot 2021-03-22 at 18 29 36](https://user-images.githubusercontent.com/25839586/112015231-aeaffd80-8b3c-11eb-888e-ec18044e992b.png)

**Comment by fdaciuk** [comment] 2021-03-22 16:01
@berkbaski put the `console.log` after the hook definition to see the updated value of the state:

```js
const [myLocation, setMyLocation] = useState(null)
console.log(myLocation) // here you'll see the latest value for myLocation ;)
```

**Comment by AmeerAsif777** [comment] 2021-03-22 16:41
@berkbaski hey, everything you are doing to set up the new value to myLocation is correct, but the problem is, beginning when getCurrentLocation is called, it will memoizing all state variable's current value, which is `myLocation = null`. After that, you are set up a new value to myLocation by calling setMylocation, but getCurrentLocation function doesn't know the latest value of myLocation. It knows only cache value of myLocation, which is `null`. That's why when you are consoling inside getCurrentLocation, its throwing null.  If you console outside as @fdaciuk  said, you will get lastest value. Hope you will understand now.

**Comment by bvaughn** [comment] 2021-03-22 16:50
The code you linked to does not follow the [rules of hooks](https://reactjs.org/docs/hooks-rules.html), specifically the effect hook is missing dependencies. The documentation says:
> If you use this optimization, make sure the array includes **all values from the component scope (such as props and state) that change over time and that are used by the effect**.

The way you've written your code:
```js
useEffect(() => {
  getCurrentLocation()
}, [])
```

This tells React only to your effect when the component initially mounts. That means that `getCurrentLocation` will only be called once, with the initial value of `myLocation`.

From your description it sounds like you expect it to be called again whenever `myLocation` changes but that's what how your code was written to do.

It also seems like you're only sharing part of your code with us (e.g. there are no console logs in the Gist you sent). Partial/incomplete examples make it difficult to tell exactly what you're talking about.

**Comment by AmeerAsif777** [comment] 2021-03-22 17:03
@bvaughn Agreed, there is a logic flaw, but  @berkbaski is expecting while consoling `latitude` and `longitude`, some numeric values are showing. Even though he set up these values  (latitude and longitude) to `myLocation`, it's showing `null`. That was his question.

**Comment by bvaughn** [comment] 2021-03-22 17:06
```js
Geolocation.getCurrentPosition(({ coords: { latitude, longitude } }) => {
  console.log("\n\n\n------------START------------\n\n\n");
  setMyLocation({ latitude: 37.33233141, longitude: -122.0312186 });
  console.log("myLocation", myLocation);

  // React will not synchronously update state while this function is still running.
  // All calls to setState (including hooks) are asynchronous.
  // In this case, even if React *was* to synchronously process the update,
  // latitude and longitude are locally defined variables in this method,
  // set a few lines above, and so they would not have been updated.

  console.log("coordinates from getCurrentPosition", { latitude, longitude });
  console.log("\n\n\n------------FINISH------------\n\n\n");
  return Promise.resolve();
});
```

**Comment by AmeerAsif777** [comment] 2021-03-22 17:10
@bvaughn I already commented before, hope that is also correct 
https://github.com/facebook/react/issues/21050#issuecomment-804217322

**Comment by bvaughn** [comment] 2021-03-22 17:13
The comment you linked to above did not explicitly mention that React will not synchronously update component state, which seems to be (I think) the assumption in the code above.

Anyway, this doesn't seem like a React issue so I'm going to close it. Folks can keep the discussion going here though. 😄

**Closed by bvaughn** 2021-03-22 17:13 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed

**Comment by berkbaski** [comment] 2021-03-23 07:30
@bvaughn hey! ty for helps but still i don't understand... okay, i updated the [gist](https://gist.github.com/berkbaski/95c935a530876aba9e7573f4ee57652c#file-page2-js) and my codes. so, i removed from useEffect and i put to top level. but myLocation value still showing null. i think i don't understand. someone would give more detail?
 
Also my personal comment is "strange"... I think i can get real value of variable when just button clicked???

**Comment by AmeerAsif777** [comment] 2021-03-23 07:59
I reckon you are not getting a proper picture of this issue. If so, this is my discord id dirtyAmeer007#3039, or emailId ameer.asif777@gmail.com, you can contact me. I will try to explain it clearly.  @berkbaski

**Comment by berkbaski** [comment] 2021-03-23 08:03
Thanks @AmeerAsif777 but i don't understand what i did wrong. I just want set to value and then next line i want get the value. my request is like this. i don't understand why this is so complex ...

**Comment by AmeerAsif777** [comment] 2021-03-23 08:06
I understood your req and explained here https://github.com/facebook/react/issues/21050#issuecomment-804217322 @berkbaski

**Comment by berkbaski** [comment] 2021-03-23 08:10
Okay, i see @AmeerAsif777 thank you. I want send an email to you :)

**Comment by berkbaski** [comment] 2021-03-24 13:04
I solved this problem. I wrote a override function for setMyLocation. Because different function can get latest values from state. 

````js
import React from 'react'
import RNLocation from 'react-native-location';

const Page = () => {
    const [myLocation, setMyLocation] = React.useState(null)

    const setMyLocationOverriden = (newLatitude, newLongitude) => {
        console.log('myLocation', myLocation)

        const distance = calculateDistance(myLocation?.latitude, myLocation?.longitude, newLatitude, newLongitude)
        if (distance >= 5) {
            setMyLocation({
                latitude: newLatitude,
                longitude: newLongitude
            })
        }
    }

    RNLocation.subscribeToLocationUpdates(
        location => {
            const { latitude, longitude } = location[0];
            setMyLocationOverriden(latitude, longitude)
        }
    )

    const calculateDistance = (lat1, lon1, lat2, lon2) => {
        //there is some calculate operations. i will return false for now.
        return 10
    }

    return <></>
}

export default Page
````

the conversation continued on this [gist](https://gist.github.com/berkbaski/3bfb54a765579ce7a5328b11daa44102)

<hr>

thanks for helps @AmeerAsif777 😄
