### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by xveganxxxedgex** [facebook/react#6740] opened 2016-05-10 17:54 UTC
I'm getting this error in the console when certain components are removed from the DOM. It's calling the method below, which assumes that target is not null and tries to access addEventListener of null object. Should it be checking if (target && target.addEventListener) {...} instead? Are components being removed in an incorrect way that would cause this to happen?
```
/**
 * Upstream version of event listener. Does not take into account specific
 * nature of platform.
 */
var EventListener = {
  /**
   * Listen to DOM events during the bubble phase.
   *
   * @param {DOMEventTarget} target DOM element to register listener on.
   * @param {string} eventType Event type, e.g. 'click' or 'mouseover'.
   * @param {function} callback Callback function.
   * @return {object} Object with a `remove` method.
   */
  listen: function (target, eventType, callback) { // target = null, eventType = "click", callback = emptyFunction()
    if (target.addEventListener) {
      target.addEventListener(eventType, callback, false);
      return {
        remove: function () {
          target.removeEventListener(eventType, callback, false);
        }
      };
    } else if (target.attachEvent) {
      target.attachEvent('on' + eventType, callback);
      return {
        remove: function () {
          target.detachEvent('on' + eventType, callback);
        }
      };
    }
  }
```

**Comment by gaearon** [comment] 2016-05-10 18:21
This is most likely a duplicate of #6538.
It has been fixed in master in #6650 and will be out in the next React release soon.

**Closed by gaearon** 2016-05-10 18:21 UTC
