### ISSUE TITLE
React breaks on empty nesting

### ISSUE THREAD

**Issue by Olierook** [facebook/react#15547] opened 2019-04-30 23:30 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
React breaks

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I wasn't able to create a jsfiddle but this is what's going on:
I am setting up a template for a way I want to build my site, this is (a part of) my structure:

- src
    - components
        - frames
            - `index.js`
        - pages
            - `index.js`
    - `App.js`
    - `index.js`

In `index.js` I import `App.js` and then render it to the DOM

```javascript
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

ReactDOM.render(<App />, document.getElementById("root"));
```

In `App.js` I import my frame

```js
import React from "react";
import Frame from "./components/frames";

const App = () => <Frame />;

export default App;
```

In the index of the frames folder I import a page
```js
import React from "react";
import Page from "../pages";

const Frame = () => <Page />;

export default Frame;
```
in that index I actually do something

```js
import React from "react";

const Page = () => <div>Hello, world</div>;

export default Page;
```

At this point a little cumbersome, but still, pretty straight forward. Whenever I do this, my dev server won't load and will eventually give a 'page not responding' error. When I was messing around with it I got it to work once, but then, when I went back to my actual structure (even more deeply nested, exactly like I do above) it will break again.

**What is the expected behavior?**
React rendering normally

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.6
App with create-react-app on windows 10

**Comment by cryptic22** [comment] 2019-05-01 07:48
> **Do you want to request a _feature_ or report a _bug_?**
> A bug
> 
> **What is the current behavior?**
> React breaks
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
> I wasn't able to create a jsfiddle but this is what's going on:
> I am setting up a template for a way I want to build my site, this is (a part of) my structure:
> 
> * src
>   
>   * components
>     
>     * frames
>       
>       * `index.js`
>     * pages
>       
>       * `index.js`
>   * `App.js`
>   * `index.js`
> 
> In `index.js` I import `App.js` and then render it to the DOM
> 
> ```js
> import React from "react";
> import ReactDOM from "react-dom";
> import App from "./App";
> 
> ReactDOM.render(<App />, document.getElementById("root"));
> ```
> 
> In `App.js` I import my frame
> 
> ```js
> import React from "react";
> import Frame from "./components/frames";
> 
> const App = () => <Frame />;
> 
> export default App;
> ```
> 
> In the index of the frames folder I import a page
> 
> ```js
> import React from "react";
> import Page from "../pages";
> 
> const Frame = () => <Page />;
> 
> export default Frame;
> ```
> 
> in that index I actually do something
> 
> ```js
> import React from "react";
> 
> const Page = () => <div>Hello, world</div>;
> 
> export default Page;
> ```
> 
> At this point a little cumbersome, but still, pretty straight forward. Whenever I do this, my dev server won't load and will eventually give a 'page not responding' error. When I was messing around with it I got it to work once, but then, when I went back to my actual structure (even more deeply nested, exactly like I do above) it will break again.
> 
> **What is the expected behavior?**
> React rendering normally
> 
> **Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
> 
> React 16.8.6
> App with create-react-app on windows 10

I tried to replicate your issue. It is working perfectly fine for me. Here is codesandbox link: https://codesandbox.io/s/xj8921x7vq. Tried to run this if it works for you perfectly.

**Comment by nmain** [comment] 2019-05-01 16:15
Given what you're describing, it's likely that your original code has an inadvertent mutual recursion in it, that's hard to spot because of the layers of nesting and importing.

```
function Foo() { return <Bar /> }
function Bar() { return <Foo /> }
```

As outlined in https://github.com/facebook/react/issues/12525, React currently has no mechanism to warn for this.

**Comment by robbertolierook** [comment] 2019-05-01 16:29
> > **Do you want to request a _feature_ or report a _bug_?**
> > A bug
> > **What is the current behavior?**
> > React breaks
> > **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
> > I wasn't able to create a jsfiddle but this is what's going on:
> > I am setting up a template for a way I want to build my site, this is (a part of) my structure:
> > 
> > * src
> >   
> >   * components
> >     
> >     * frames
> >       
> >       * `index.js`
> >     * pages
> >       
> >       * `index.js`
> >   * `App.js`
> >   * `index.js`
> > 
> > In `index.js` I import `App.js` and then render it to the DOM
> > ```js
> > import React from "react";
> > import ReactDOM from "react-dom";
> > import App from "./App";
> > 
> > ReactDOM.render(<App />, document.getElementById("root"));
> > ```
> > 
> > 
> > In `App.js` I import my frame
> > ```js
> > import React from "react";
> > import Frame from "./components/frames";
> > 
> > const App = () => <Frame />;
> > 
> > export default App;
> > ```
> > 
> > 
> > In the index of the frames folder I import a page
> > ```js
> > import React from "react";
> > import Page from "../pages";
> > 
> > const Frame = () => <Page />;
> > 
> > export default Frame;
> > ```
> > 
> > 
> > in that index I actually do something
> > ```js
> > import React from "react";
> > 
> > const Page = () => <div>Hello, world</div>;
> > 
> > export default Page;
> > ```
> > 
> > 
> > At this point a little cumbersome, but still, pretty straight forward. Whenever I do this, my dev server won't load and will eventually give a 'page not responding' error. When I was messing around with it I got it to work once, but then, when I went back to my actual structure (even more deeply nested, exactly like I do above) it will break again.
> > **What is the expected behavior?**
> > React rendering normally
> > **Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
> > React 16.8.6
> > App with create-react-app on windows 10
> 
> I tried to replicate your issue. It is working perfectly fine for me. Here is codesandbox link: https://codesandbox.io/s/xj8921x7vq. Tried to run this if it works for you perfectly.

That _is_ weird, the sandbox did work on my machine. Thank you for making one! 
After continuing my development, so the components would be more than a single reference to another component, the problem stopped occurring. 

The bug occurred on both Chrome and Firefox, though it might still be a local bug from my machine if you can't replicate it.

**Comment by threepointone** [comment] 2019-05-06 16:04
Can’t make a call here with a reproducible link on codesandbox or the like, but it does look like you’re unblocked, so that’s good. Didn’t seem like a react issue at all iiuc? I’m closing this issue on that basis, but do correct me if I’m wrong.

**Closed by threepointone** 2019-05-06 16:04 UTC
