### ISSUE TITLE
Error: "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by SunnyDark** [facebook/react#18990] opened 2020-05-23 20:14 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.7.0-23309eb38

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:313982
    at Ii (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:314116)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:62450)
    at zl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:112731)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104502)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104430)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104298)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99542)
    at F (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:3011)
    at MessagePort.w.port1.onmessage (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:1767)

Component stack: at Ii (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:313542)
    at div
    at Oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:310221)
    at div
    at Ti (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:307361)
    at Suspense
    at pi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:300435)
    at div
    at div
    at Uo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:272479)
    at Hr (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:250828)
    at Co (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:263571)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:333079
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:276314)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:278724
    at div
    at div
    at Xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:325177)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:207026)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:216342)
    at Va (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:293773)
    at us (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:371869)

**Comment by csulit** [comment] 2020-05-26 02:54
Reproduce?

**Comment by bvaughn** [comment] 2020-05-26 17:54
> Describe what you were doing when the bug occurred

Would be helpful if you could do this.

**Comment by bvaughn** [comment] 2020-07-30 18:05
Since the issue is not currently actionable, I'm going to close this issue until more information is provided.

**Closed by bvaughn** 2020-07-30 18:05 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
