### ISSUE TITLE
Bug: Error should have queue. this is likely a bug in react.

### ISSUE THREAD

**Issue by Annu2013** [facebook/react#21877] opened 2021-07-14 12:21 UTC
![image](https://user-images.githubusercontent.com/40827668/125621023-d8117c6b-47f8-464c-9ae2-184018cd91e3.png)

React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by bvaughn** [comment] 2021-07-14 14:39
Hi!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by uragirii** [comment] 2021-07-15 07:54
This usually happens when the order of hooks in which they are initialised is changed.

**Comment by bvaughn** [comment] 2021-07-19 14:16
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-07-19 14:16 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
