### ISSUE TITLE
Bug: contentEditable attribute does not allow the 'plaintext-only' value

### ISSUE THREAD

**Issue by nathan-osman** [facebook/react#27619] opened 2023-10-29 04:09 UTC
React version: 18.2.0

## Steps To Reproduce

1. Create a React project with TypeScript enabled
1. Create an element with the `contentEditable="plaintext-only"` attribute

Reproducible example:  
https://codesandbox.io/s/cool-voice-w8w7q2

## The current behavior

The TypeScript compiler flags the attribute as an error:

    Type '"plaintext-only"' is not assignable to type 'Booleanish | "inherit"'.ts(2322)

    index.d.ts(1988, 9): The expected type comes from property 'contentEditable' which is declared here on type
      'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'

## The expected behavior

No error is generated. This value is supported for the attribute [on several popular browsers](https://caniuse.com/mdn-html_global_attributes_contenteditable_plaintext-only), including Chrome, Edge, Safari, and Opera.

**Comment by joaquinuriarte** [comment] 2023-10-30 02:16
The file is here: https://github.com/DefinitelyTyped/DefinitelyTyped/edit/master/types/react/index.d.ts.

As of commit [69dbf71], the issue is on line 1955. 

A potential solution could be to change:
"contentEditable?: Booleanish | "inherit" | undefined;" 
for 
"contentEditable?: Booleanish | "inherit" | "plaintext-only" | undefined;"

**Comment by joshuadschoep** [comment] 2023-10-30 15:51
I would be able to take this issue (it will be my first contribution to both React and DefinitelyTyped)

**Comment by eps1lon** [comment] 2023-11-05 09:22
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67250

**Closed by eps1lon** 2023-11-05 09:22 UTC
Labels: Status: Unconfirmed
