### ISSUE TITLE
allow components to render abstract elements(feature request)

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/react#2449] opened 2014-11-02 12:15 UTC
Every component we create we have to return an actiaul element. But in some cases we just don't actually need that. For example, when we attempt to transitions like what Famo.us does, we would calculate every position by hand, and such a wrapper becomes unnesseccery. So how about introducing something like "abstract elements" to do that?

**Comment by spicyj** [comment] 2015-02-27 01:22
Closing this as a dupe of #2127.

**Closed by spicyj** 2015-02-27 01:22 UTC
