### ISSUE TITLE
[16.6.0] Cannot read property replace of null, when trying to remove the string "topsecret-" from fiber.name

### ISSUE THREAD

**Issue by danieldunderfelt** [facebook/react#13997] opened 2018-10-27 09:50 UTC
### Bug report

When using React version 16.6.0, my app suddenly crashed with the error "Cannot read property replace of null". The exception happens when React tries to remove the string "topsecret-" from fiber.name. I tried to revert back to 16.5.2 to confirm the version where it happens, and it does indeed not happen in 16.5.2.

I'm not sure about steps to reproduce it, I've been using React 16.6.0 for a few days in this project without issues until now. Here's a screenshot of the exception and the file it happens in, along with the stack. Seems like a straightforward fix, so I hope a reproduction example isn't needed in this case.

![Screenshot](https://i.imgur.com/W3d7lmM.png)

**Comment by bvaughn** [comment] 2018-10-27 15:08
Looks like a duplicate of facebook/react-devtools/issues/1195

Make sure you're running the latest version of DevTools (3.4.2). You _might_ need to restart your browser for the update to be applied!

**Closed by bvaughn** 2018-10-27 15:08 UTC

**Comment by danieldunderfelt** [comment] 2018-10-27 15:12
Oh okay, thanks!

**Comment by chrisnojima** [comment] 2018-11-15 20:22
(In case anyone is in the same boat I was) I was running into this with the standalone react-devtools with an older version that react-native pulled in. I removed it from my yarn.lock and installed again and got the newer version
