### ISSUE TITLE
onMouseUp not triggered on right click (context menu)

### ISSUE THREAD

**Issue by nkbt** [facebook/react#5531] opened 2015-11-23 03:25 UTC
http://codepen.io/nkbt/pen/PPgvZg?editors=001

Explanation of the codepen:

Click on link, there will be counter increment onMouseDown. Each onMouseDown and onMouseUp event is logged. Try clicking with Right Mouse Button (open context menu for link). onMouseDown is triggered with counter incremented, but onMouseUp is skipped entirely.

![onmouseup-issue](https://cloud.githubusercontent.com/assets/175264/11329265/f71bd2ae-91ed-11e5-8bf0-0f2d1a84730d.gif)

I found this old webkit bug (resolved) if it helps: https://bugs.webkit.org/show_bug.cgi?id=6595

**Comment by camspiers** [comment] 2015-11-23 04:52
This is expected behaviour (as it is how a vanilla DOM version behaves too): http://codepen.io/anon/pen/NGmVer

**Comment by nkbt** [comment] 2015-11-23 05:53
I double-checked, it works fine in Firefox, and not fine in chrome, seems like purely chrome-related issue =(

**Comment by camspiers** [comment] 2015-11-23 19:52
Looks like it behaves that way in Safari too. Maybe see if there is an open issue tracking it.

**Comment by camspiers** [comment] 2015-12-01 21:56
@jimfb @spicyj I think this one can be closed as it isn't a React bug.

**Comment by spicyj** [comment] 2015-12-01 22:01
Thanks.

**Closed by spicyj** 2015-12-01 22:01 UTC

**Comment by jimfb** [comment] 2015-12-01 22:05
For reference: https://code.google.com/p/chromium/issues/detail?id=506801
