### ISSUE TITLE
[DevTools Bug]: Chrome Dev Tools extension shows websites built with other framework as React web sites

### ISSUE THREAD

**Issue by pavankjadda** [facebook/react#23138] opened 2022-01-18 20:59 UTC
### Website or app

https://angular.io/start

### Repro steps

1. Go to https://angular.io/start or https://vuejs.org/
2. Click on React Dev Tools extension
3. You should see message **This page is using the production build of React. ✅**

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment] 2022-01-18 22:56
This is a bug caused by the Redux DevTools extension: [zalmoxisus/redux-devtools-extension#829](https://github.com/zalmoxisus/redux-devtools-extension/issues/829)

Duplicate of #23107, #23124

**Closed by bvaughn** 2022-01-18 22:56 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools
