### ISSUE TITLE
Do HTML components maintain state?

### ISSUE THREAD

**Issue by mrgreen7** [facebook/react#4298] opened 2015-07-06 06:53 UTC
Say you have

    let myComp = React.createClass({
      render: function() 
        return <input type="checkbox"/>
      } 
    });

and myComp is rendered into the DOM. Then the user checks the checkbox. If you call myComp.render() now it seems as if the checkbox is stell checked even though this should re-render the checkbox. Where does this statefullness come from? Does react handle that? Maybe the input element has something like this.state.checked?

I apologize if this is a question covered by the docs  (I suspect because it is somewhat basic) but I could not find information about it.

**Comment by brigand** [comment] 2015-07-06 07:00
Some of your code was swallowed by markdown (use triple backticks around code). 

But take this code for example:

```js
React.render(<input type="checkbox" checked={true} />, el);
```

It'll render a checkbox that's always checked. If you use value or checked react will ensure that stays correct.

By the way, StackOverflow or IRC are better places for questions.

**Comment by jimfb** [comment] 2015-07-06 18:43
Thanks @brigand, great answer!

I'm going to close this issue, since we use Github issues to track bugs in the React core and this is not a bug in the core.  Feel free to continue the discussion on this thread, or as @brigand suggested StackOverflow is a better place for usage questions.

**Closed by jimfb** 2015-07-06 18:43 UTC
