### ISSUE TITLE
Profiler doesn't work 

### ISSUE THREAD

**Issue by Deribolot** [facebook/react#22677] opened 2021-11-02 09:04 UTC
Chrome 95.0.4638.69 React 16.8
It worked in 95.0.4638.54

**Comment by bvaughn** [comment] 2021-11-02 14:29
@Deribolot We need more information than "it doesn't work". What does it do? What are the repro instructions?

**Comment by bvaughn** [comment] 2021-11-03 19:55
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-11-03 19:55 UTC
Labels: Resolution: Needs More Information, Component: Developer Tools
