### ISSUE TITLE
Error: "Could not find node with id "6002" in commit tree"

### ISSUE THREAD

**Issue by Rutulpatel7077** [facebook/react#16457] opened 2019-08-19 17:12 UTC
PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

Simply click on profiler and baam!!

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.3-95ffd3c

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11441
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11387)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11920)
    at _i (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:277079)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)

Component stack: in _i
    in div
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ha
    in le
    in ve
    in ko
    in Ul

**Comment by bvaughn** [comment] 2019-08-19 18:07
Any more detailed repro steps would be appreciated. 

Duplicate of #16446

**Closed by bvaughn** 2019-08-19 18:07 UTC
Labels: Component: Developer Tools, Resolution: Duplicate
