### ISSUE TITLE
Bug: Use component inside itself

### ISSUE THREAD

**Issue by rdwnsjjd** [facebook/react#22802] opened 2021-11-22 07:56 UTC
Hi
when I write this code:
```
export default function Bug(props) {
    return (
        <Bug></Bug>
    )
}
```

it will cause crashes and my browser never responses on the page and the page progress indicator turns forever without any error or something else. and the whole page freezes:

![Screenshot from 2021-11-22 11-21-35](https://user-images.githubusercontent.com/84472404/142823377-37d7d97b-8c41-46d0-b3ab-1ac75c8fb248.png)
![Screenshot from 2021-11-22 11-22-30](https://user-images.githubusercontent.com/84472404/142823368-19339644-2f2f-4781-8eaf-63620004488c.png)

I report it because I know React provides infinite loops, but here it crashes unexpectedly.

**Comment by irinakk** [comment] 2021-11-22 09:40
No, React does not "provides infinite loops". You'll need a base case for the recursion.

**Comment by eps1lon** [comment] 2021-11-22 10:28
> No, React does not "provides infinite loops". You'll need a base case for the recursion.

I think what they meant was that React guards against certain infinite loops e.g. setting state unconditionally during render.

Closing in favor of https://github.com/facebook/react/issues/12525
Duplicate of https://github.com/facebook/react/issues/12525, https://github.com/facebook/react/issues/20629

**Closed by eps1lon** 2021-11-22 10:28 UTC
Labels: Status: Unconfirmed
