### ISSUE TITLE
[DevTools Bug] Cannot add child "11802" to parent "11726" because parent node was not found in the Store.

### ISSUE THREAD

**Issue by mohammad-mustafa-tfs** [facebook/react#21786] opened 2021-07-02 03:02 UTC
### Website or app

https://www.mapac.thermofisher.com

### Repro steps

The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21126:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19286:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19446:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37413:39)

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.5-0ae5290b54

### Error message (automated)

Cannot add child "11802" to parent "11726" because parent node was not found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21126:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19286:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19446:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37413:39)
```

### Error component stack (automated)

```text
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21126:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19286:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19446:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37413:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add child  to parent  because parent node was not found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment] 2021-07-03 23:46
> ### Repro steps
> 
> The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21126:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19286:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19446:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37413:39)

These aren't repro steps 😄  and the website listed (mapac.thermofisher.com) is not accessible to me ("_This site can’t be reached_"). Without a repro, there's nothing I can do to look into this issue. Please share your app/code and steps on how to reproduce the bug you're reporting using your app?

**Comment by bvaughn** [comment] 2021-07-06 17:05
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-07-06 17:05 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed, Type: Bug
