### ISSUE TITLE
TestUtils cannot render stateless function components

### ISSUE THREAD

**Issue by ibrown-gaikai** [facebook/react#5901] opened 2016-01-21 17:49 UTC
I'm using react 14.3, babel 6.0.15 and react test utils addon 0.14.6 . Jasmine 2.3 is my testing framework of choice.

It seems as though any stateless function component cannot be tested by TestUtils.renderIntoComponent or TestUtils.createRenderer().render(). Either returns null when rendering the function component.

Test with any stateless function component and it should yield the same result.

Component:
-----

`import React from 'react';`

`const User = ({name, age}) => (
    return <div>{name}, {age}</div>
);`

`module.exports = User;`

Test:
------
`expect(TestUtils.renderIntoDocument(<User name={"bob"} age={20} />)).toBeTruthy();`

Error:
------
Expected null to be truthy.

**Comment by jimfb** [comment] 2016-01-21 18:56
Duplicate of https://github.com/facebook/react/issues/5455

**Closed by jimfb** 2016-01-21 18:56 UTC

**Comment by antgonzales** [comment] 2017-03-31 21:23
@jimfb I'm not sure this is necessarily a duplicate. This is specific to the TestUtils render, not necessarily refs at the end of that ticket chain you mentioned above. I'm currently having this issue with Phantom + Mocha.

**Comment by thealjey** [comment] 2019-02-19 08:59
@antgonzales did you manage to overcome this problem somehow?

**Comment by antgonzales** [comment] 2019-02-27 22:14
@thealjey I moved over to Jest/JSDOM/Enzyme, I bet this issue isn't a problem in a Jest/JSDOM environment. Happy to give it a test if you're seeing this issue in that environment or a Mocha/JSDOM environment.
