### ISSUE TITLE
setState callbacks not getting executed in expected order

### ISSUE THREAD

**Issue by nihartrivedi810** [facebook/react#12261] opened 2018-02-21 14:47 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v. 15.6.2
Not sure if it worked in previous versions.

**What is the current behavior?**

For the following piece of code, when `componentWillReceiveProps` is called multiple times quickly without executing the callbacks(or completing `setState`), it is expected that the callbacks are executed in the correct order with the corresponding `nextProps` in their scope.

```
componentWillReceiveProps(nextProps) {
    this.setState({someStateValue:  nextProps.someValue}, () => {
         this.doSomethingElse(nextProps);
    })
}
```

But, contrary to the expected behavior, the callback with the later value of `nextProps` is being called first and the one with the older value next, eventually calling the `doSomethingElse` with an older value.

Upon debugging, in the following piece of code from `react-dom.js`

```
enqueueCallback: function (publicInstance, callback, callerName) {
    ReactUpdateQueue.validateCallback(callback, callerName);
    var internalInstance = getInternalInstanceReadyForUpdate(publicInstance);

    // Previously we would throw an error if we didn't have an internal
    // instance. Since we want to make it a no-op instead, we mirror the same
    // behavior we have in other enqueue* methods.
    // We also need to ignore callbacks in componentWillMount. See
    // enqueueUpdates.
    if (!internalInstance) {
      return null;
    }

    if (internalInstance._pendingCallbacks) {
      internalInstance._pendingCallbacks.push(callback);
    } else {
      internalInstance._pendingCallbacks = [callback];
    }
    // TODO: The callback here is ignored when setState is called from
    // componentWillMount. Either fix it or disallow doing so completely in
    // favor of getInitialState. Alternatively, we can disallow
    // componentWillMount during server-side rendering.
    enqueueUpdate(internalInstance);
  },
```
It was found that for the second call to `setState`, `internalInstance._pendingCallbacks` was null even though the callback for the first `setState` was not executed.

**What is the expected behavior?**
Expected that callbacks are registered and executed in order.

Is this a known bug or is there some mistake being made here?

**Comment by aweary** [comment] 2018-02-24 00:07
@nihartrivedi810 can you please provide the details that were in the issue template you deleted? Without information like what version of React you're using, and an example reproducing your problem, it's very difficult to figure out what's happening.

**Comment by nihartrivedi810** [comment] 2018-02-24 09:54
@aweary Updated the details.

**Comment by aweary** [comment] 2018-03-18 22:59
@nihartrivedi810 without an actual reproduction it's going to be difficult for us to help you.

**Comment by aweary** [comment] 2018-03-27 22:59
Since there's been no follow up, and we're enable to reproduce, I'm going to go ahead and close this out.

**Closed by aweary** 2018-03-27 22:59 UTC
Labels: Resolution: Needs More Information
