### ISSUE TITLE
Bug: slow rendering

### ISSUE THREAD

**Issue by WOLFIEEEE** [facebook/react#20947] opened 2021-03-07 04:27 UTC
Trying to update charts in realtime I am having maximum of 200 point per second .I will add a link to code below , for 1 minute the chart is working fine but after that is start lagging the data lag between sensor and react just keep increasing , I check the server code there are no issues with my server code.

React version:17.0.1

## Steps To Reproduce

1. As it contain server code and needs a arduino I don't think you will able to reproduce it.
2. If you have a arduino that given data in serial plot , I will heappy to help you reproduce the issue

##Libraries Used:- 

1. Socekt.io client :- For collecting data from server
2. Recharts:- charts library  

##Link to code:

  Githubgist of Client code:- [client](https://gist.github.com/WOLFIEEEE/b9b424bf619b34d05241e537611f4647)
  Githubgist of server code :- [server](https://gist.github.com/WOLFIEEEE/4ef9d0e3060c19ef0c0dafa806f380b9)

**Comment by bvaughn** [comment] 2021-03-07 16:48
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-03-09 19:56
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-03-09 19:56 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
