### ISSUE TITLE
React Devtools won't connect to Application running on iOS Simulator

### ISSUE THREAD

**Issue by dallasclark** [facebook/react#24089] opened 2022-03-13 23:31 UTC
React Devtools doesn't connect to the instance running in the iOS Simulator.

React DevTools Screenshot

![image](https://user-images.githubusercontent.com/542948/158083928-0be956e7-6357-4308-8990-55cd3d0a8565.png)

iOS Simulator Screenshot

![image](https://user-images.githubusercontent.com/542948/158083953-c61f5079-78a9-4424-bae9-c7dfbd633404.png)

React Native appears to have some interactivity as you can see "DevTools initialized" and the inspector on the iOS Simulator is running in the condensed mode.

OS: macOS Monterey (12.2.1)
Chip: Apple M1 Pro

**Comment by bvaughn** [comment] 2022-03-14 13:35
This looks like a duplicate of #23307. I think what's actually going on here is that the backend and frontend versions mismatch, and DevTools is crashing (in a way that isn't user-visible). Going to close this and roll it into #23307

**Closed by bvaughn** 2022-03-14 13:35 UTC
