### ISSUE TITLE
Context not updated on Component mounted with React.render()

### ISSUE THREAD

**Issue by jquense** [facebook/react#3340] opened 2015-03-07 01:34 UTC
This is tough for me to explain so I created a fiddle to demonstrate it. I have a layer/portal/whatever we are calling this pattern, that renders the children of a component to a new tree off of body via `React.render()`. I would expect context to also be passed, and I've taken special care to make sure the child to be passed to `.render()` is created with the correct owner. It all works fine context is passed, but it is never updated at that point. If I inspect the child element to be passed `._context` is correct but `.context` is never updated on the instance. Not sure if perhaps I just have the wrong expectation here?

Here is an illustration: **(updated with simpler example)**
http://jsfiddle.net/69z2wepo/3772/

**Comment by jsfb** [comment] 2015-03-09 18:39
@jquense looks like a bug.  Your example can be cleaned up a bit (for example, your passing of `children` and `props` to modal is superfluous and makes it more difficult to fully understand what's going on there).

@sebmarkbage The issue is more readily demonstrated using the deprecated `withContext` function.  See my demo: http://jsfiddle.net/Lbdwo477/ (should render "bar" instead of "foo").

@sebmarkbage Under the new parent-based context (to be enabled in 0.14), how do we expect `React.render` to behave?  Should it inherit the current context, or use the context that is effective at that position in the DOM (eg. someone renders into a leaf node of a React component after mounting).

**Comment by jquense** [comment] 2015-03-09 19:05
> Under the new parent-based context (to be enabled in 0.14), how do we expect React.render to behave? Should it inherit the current context, or use the context that is effective at that position in the DOM (eg. someone renders into a leaf node of a React component after mounting).

I am super interested in this as well, in some sense it doesn't make sense to pass a parent context, but It would break this example, unless of course we just manually pass context down

**Comment by jsfb** [comment] 2015-03-09 19:14
Yeah, my intuition is that it should inherit the context from the DOM.  If a user wants to explicitly pass a new context, they should create a wrapper component that provides the context variables (potentially received as props) and pass that wrapper component into `React.render`, thus maintaining the parent-based propagation of variables.

@jquense Owner is not necessarily a subset of Parent.  Parent and Owner can (in theory) be independent, though the owner is **usually** a parent.  We warn in cases where context variables are used and the owner's provided value does not match the parent's provided value.  That should be rare.

**Comment by spicyj** [comment] 2015-03-09 19:50
We do want some way to pass the context down. See "#3210 Nested Render Trees".

**Comment by sebmarkbage** [comment] 2015-03-09 20:27
This was fixed in 0.13. https://github.com/facebook/react/commit/ed7332c74921874cdcb3cce629bb5bd8c95a7968#diff-c818825b9093d7a157d104790f972ff2R304

**Closed by sebmarkbage** 2015-03-09 20:27 UTC
Labels: Type: Bug
