### ISSUE TITLE
`React.createClass` fails when called with a spec created with `Object.create(null)`

### ISSUE THREAD

**Issue by ryankaplan** [facebook/react#6002] opened 2016-02-08 19:08 UTC
Hi React Team!

Right now the following code fails:

```
var spec = Object.create(null);
spec.render = function () {
  return <div />;
};
React.createClass(spec);
```

It fails because the function `mixSpecIntoComponent` called from `React.createClass` references `spec.hasOwnProperty`. But `spec` was created from `Object.create(null)`, so it doesn't have regular prototype methods like `hasOwnProperty`.

Here's a [patch](https://github.com/ryankaplan/react/commit/547af13f1fdc4772f9573e8ec19994691240f8c3) that fixes the issue. Let me know, based on my explanation below, if you agree that this is worth fixing and I can submit a PR.

---

Motivation for fixing this: I'm experimenting with building React bindings for a language called [Skew](http://skew-lang.org/). Skew compiles to Javascript (among other languages) and the map-type in Skew compiles to instances of `Object.create(null)`. That is: the Skew code `var map = { "hi": "there" }` translates roughly to `var map = Object.create(null); map["hi"] = "there";`. This is sensible - there's no need for a map to inherit from `Object.prototype`.

In Skew I'd like to be able to do something like...

```
React.createClass({
    "render": () React.Element => {
        return SkewReact.createElement("div");
    } 
})
```

Where `React.createClass` is the regular `createClass` function defined in the React library. But this fails because it passes a Skew map (which is `Object.create(null)` in Javascript)  to `createClass`. Instead I have to do something like:

```
SkewReact.createClass({
    ...
})
```

Where `SkewReact` will wrap the input into something that inherits `Object` before passing that on to the real `React.createClass`. This works, but means that my API won't mirror that of React directly which means it'll be harder for people to learn.

**Comment by jimfb** [comment] 2016-02-08 21:57
Does skew not support ES6 classes?  ES6 classes exist largely to allow for language interoperability.  Also, `createClass` is mostly legacy anyway.

With regards to the specifics of your patch, it seems fine to me.  Looks like there is virtually zero perf impact (http://jsperf.com/4v5ye45ybe5u6) so I see no reason not to take it.

**Comment by zpao** [comment] 2016-02-08 22:18
@jimfb if you're going to take the patch then let's be super thorough and see if there are other places that we should be supporting prototype-less objects.

**Comment by ryankaplan** [comment] 2016-02-08 22:43
@jimfb Thanks for the fast response! "`createClass` is mostly legacy" - I was unaware of this. I'm going to dig in and find out if I can make things work by similarly extending `React.Component` in Skew. I'll post back here with an update.

@zpao Makes sense to me. If we move ahead, I'll take a stab at looking around where else this would come up.

**Comment by ryankaplan** [comment] 2016-02-10 08:02
@jimfb Here's an update: Skew seems to support ES6 classes, but that doesn't solve my problem for two reasons...

1. Classes aren't first-class objects in Skew. So you can't pass a class to a function like `React.createElement(ClassName, ...)`. I could just keep using `React.createClass`, or there might be a workaround where I can trick the Skew compiler into letting me pass a class around, but the bigger problem is what @zpao anticipated...

2. There are many places that the React API takes an `Object` where I would like it to take a prototype-less map. Some examples...

```
// PROBLEM: spec could be prototype-less
var spec = {

    // PROBLEM: propTypes could be prototype-less
    propTypes: {
        someProp: ...
    },

    getDefaultProps: function () {
        // PROBLEM: The return value here could be prototype-less
        return { defaultProp: 0 };
    }

    someFunction: function () {
        // PROBLEM: The argument to setState could be prototype-less
        this.setState({ someVar: 0 });
    }
};
React.createClass(spec);
```

As it is, a few - but not all - of these use-cases cause an exception when called with `Object.create(null)`. I expect to find more as I play around.

Proposal: I would be happy to find and update all API-reachable calls of `obj.hasOwnProperty(...);` to `Object.prototype.hasOwnProperty(obj, ...);` and write tests to make sure that those specific calls don't regress. But this seems like a sizable piece of work and I wanted to be sure that you're on board before I do it. Please let me know if you're on board :)

A few notes:

- The examples above are all `obj.hasOwnProperty` where `obj` is prototype-less. But we could run into this issue for `obj.keys()` or `obj.values()`, or any other method on `Object`. So I would sweep the codebase for all API-reachable method-calls that might belong on `Object.prototype` instead of an instance. So far it seems that `hasOwnProperty` is the primary offender in the React codebase and others don't account for much.

- Instead of finding all the *API-reachable* uses of `hasOwnProperty`, I could change *every* use in the codebase since I don't see any reasonable case where calling the method on an instance does what you want but calling it on `Object.prototype` doesn't. This may be a simpler approach, and would be easier to maintain with a code-base guideline ("Always use Object.prototype.blahBlahBlah instead of obj.blahBlahBlah') or lint rule. Let me know what you think of this.

**Comment by jimfb** [comment] 2016-02-10 16:15
@ryankaplan Personally, I'm agnostic about the whole change.  If the change is helpful to you/others, and doesn't cause undue code complexity or perf regressions (which it doesn't appear to do), I generally lean in favor of taking it.  However, I'm not the only person on the team.  The value proposition in this case is fairly marginal, so it would be possible for someone to find a reason to block it.  Both your proposals seem fine to me.  My best guess is that we would likely take the change since I don't see a reason to not take it, but I can't make any promises.

**Comment by ryankaplan** [comment] 2016-02-11 04:58
@jimfb Fair enough - thanks for the response. I'll prepare a PR some time over the next few days and let you know when it's ready. We'll see how it goes from there. In the mean time if you think of any reason why it's likely to be blocked, or there are particular people on the team who you think are likely to have issues with it, please let me know.

**Comment by jimfb** [comment] 2016-03-02 20:56
Ping @ryankaplan: did you want to propose a PR, or what's the status on this?

**Comment by ryankaplan** [comment] 2016-03-04 00:08
Hey @jimfb - thanks for the reminder. I still want this fixed but haven't found the time to do it. I'm also a little worried by my approach.

I'd like to change all calls to `object.hasOwnProperty(key)` to `Object.prototype.call(object, key)` - and similarly for other `Object.prototype` methods called on an instance that may not inherit from `Object`.

But it's not much good to make a sweeping change and then for someone else to add a new `object.hasOwnProperty` call a few days later. Does the react codebase have a linter where I could add a rule to warn engineers who use `object.hasOwnProperty` instead of `Object.prototype.hasOwnProperty`?

**Comment by jimfb** [comment] 2016-03-04 00:10
Yes, there is a linter.  You could also add a bunch of unit tests, which has a similar effect :).

**Comment by Mitranim** [comment] 2016-06-02 14:17
FYI the same problem occurs when passing null-derived props to `React.createElement`. Example:

```js
// raises exception by attempting to call `config.hasOwnProperty`
React.createElement('div', Object.create(null))
```

Would really like to have this fixed across the React codebase.

**Comment by jimfb** [comment] 2016-06-08 15:35
I'm going to close this out, since it has been a few months and it doesn't look like this is going to happen at this point.  `createClass` is mostly legacy at this point anyway; the preferred API is to use a stateless function or an ES6 class.

**Closed by jimfb** 2016-06-08 15:35 UTC
