### ISSUE TITLE
ReactDOM.hydrate falsely warns about text content mismatch

### ISSUE THREAD

**Issue by zdila** [facebook/react#11268] opened 2017-10-18 14:29 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

```javascript
function Foo() {
  return 'foo';
}

function Test() {
  return <span><Foo />bar</span>;
}
```

Hydration of `<Test />` to serverside rendered `<Test />` produces following warning:

```
Warning: Text content did not match. Server: "foobar" Client: "foo"
```

**What is the expected behavior?**

No warning.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

* react@16.0.0
* react-dom@16.0.0

**Comment by gaearon** [comment] 2017-10-18 14:44
This was fixed in master. Duplicate of https://github.com/facebook/react/issues/10598.

**Closed by gaearon** 2017-10-18 14:44 UTC

**Comment by gaearon** [comment] 2017-11-03 00:54
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.
