### ISSUE TITLE
Bug: setState behaves sync when inside a promise callback and async when not.

### ISSUE THREAD

**Issue by jasongornall** [facebook/react#20991] opened 2021-03-12 21:31 UTC
```jsx
import ReactDOM from "react-dom";
import React, { useState } from "react";
import "./styles.css";

class Hello extends React.Component {
  constructor() {
    super();
    this.state = { data: [] };
  }

  async fetchJoke() {
    return Promise.resolve({
      id: Math.random(),
      joke: `${Math.random()}`
    });
  }

  // state is sync
  fetchAllJokesSync() {
    this.fetchJoke().then((joke) => {
      let jokes = [];
      console.log("before", this.state.data.length); // 0
      jokes.push(joke);
      console.log("before-2", this.state.data.length); //0
      this.setState({ data: jokes });
      console.log("before-3", this.state.data.length); // 1
      console.log("after", this.state.data.length); // 1
    });
  }
  // state is async
  fetchAllJokesASync() {
    const joke = {
      id: "wakka",
      joke: "wakka"
    };
    let jokes = [];
    console.log("before", this.state.data.length); //0
    jokes.push(joke);
    console.log("before-2", this.state.data.length); // 0
    this.setState({ data: jokes });
    console.log("before-3", this.state.data.length); // 0
    console.log("after", this.state.data.length); // 0
  }

  async componentDidMount() {
    this.fetchAllJokesSync();
    // this.fetchAllJokesASync();
  }

  render() {
    return (
      <div>
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<Hello />, rootElement);


```

React version:
React 16.12.0
React-Dom 16.12.0

## Steps To Reproduce

1. Toggle between 2 functions in componentDidMount and observe changes to state and observe console

Link to code example:
https://codesandbox.io/s/badjokes-forked-3o08z?file=/src/index.js SetState

## The current behavior
setState is sync inside a promise callback

## The expected behavior
setState should always by async inside a promise callback

**Comment by jasongornall** [comment] 2021-03-12 21:45
I recognize https://reactjs.org/docs/react-component.html#setstate This states that it **does not always immediately update the component** but when does it decide to do that and why? I'm worried this can lead to accidental bugs if this is non deterministic. Is there a way to force this to always be async for development purposes so people don't accidentally rely on this being sync?

**Comment by jordyvandomselaar** [comment] 2021-03-12 22:06
Hi,

Are you loading all polyfills: https://create-react-app.dev/docs/supported-browsers-features/?

**Comment by jasongornall** [comment] 2021-03-12 22:08
no but I'm running this on latest chrome.

**Comment by jasongornall** [comment] 2021-03-12 22:13
I found a tweet that suggests the right answer: https://twitter.com/dan_abramov/status/959507572951797761
Is this still the case?

**Comment by jordyvandomselaar** [comment] 2021-03-12 22:17
I'm so sorry, my first reply is on the wrong issue 😅

**Comment by jordyvandomselaar** [comment] 2021-03-12 22:18
I'm not sure if it is still the case to be honest. I've since moved on to hooks which are a lot less weird to me =)

**Comment by jordyvandomselaar** [comment] 2021-03-12 22:20
In any case, I strongly suggest not to depend on it being synchronous. Because `setState()` is more of a request than an order, React decides when it can safely update the state best. This is usually near to instant but could take a little bit longer if React thinks that's a good idea.

**Comment by markerikson** [comment] 2021-03-13 02:03
This is entirely standard and intentional behavior. Currently, React only batches state updates that happen within its own event handlers. Logic in a promise callback is outside that event handler tick and thus outside the batching wrapper, so it's processed synchronously

https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#render-batching-and-timing

You should also probably read Dan's extensive explanation at https://github.com/facebook/react/issues/11527#issuecomment-360199710

Note that in Concurrent Mode, state updates are _always_ batched all the time.

**Comment by eps1lon** [comment] 2021-03-13 08:13
Closing since this is expected behavior. 

https://github.com/facebook/react/issues/20991#issuecomment-797789432 and are great answers https://github.com/facebook/react/issues/20991#issuecomment-797847609.

**Closed by eps1lon** 2021-03-13 08:13 UTC
Labels: Status: Unconfirmed

**Comment by jasongornall** [comment] 2021-03-13 20:43
These explanations are great, and thankyou for the links!! Would it be possible to get this officially documented?

**Comment by markerikson** [comment] 2021-03-13 20:50
FWIW, the React team is currently working on a complete rewrite of the docs:

https://github.com/reactjs/reactjs.org/issues/3308

Not sure what specifically will be in there, but I'm hopeful that some of the behavior like this will be covered.
