### ISSUE TITLE
Safari (macOS) Text fields are unable to receive input

### ISSUE THREAD

**Issue by curxxx** [facebook/react#16836] opened 2019-09-19 19:38 UTC
While teaching myself react I've run into an issue where I am unable to type any text into text inputs but only in macOS Safari (and latest Technology Beta). 
Every other browser I've tried (Firefox Dev, Opera Dev, Chrome) it behaves as expected. 

Hopefully it's not just me doing something wrong (which it probably is) but I figured I'd report it anyway considering it's only affecting a single browser... 

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Safari only (macOS): Text fields are unable to receive input at all. eventHandlers are not even being called.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I've tried to simplify it as much as I can, sorry it's not the most simplest example but here's my CodeSandbox (https://codesandbox.io/s/unfortunate-broken-panda-bd708)

**What is the expected behavior?**
The 2 input fields should be able to receive text.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.9 and 16.8 tested and confirmed to be not working in macOS 10.14.6 (18G95) _Safari Version 12.1.2 (14607.3.9)_ and _Safari Technology Preview Release 92 (Safari 13.1, WebKit 14609.1.4)_

**Comment by bvaughn** [comment] 2019-09-19 20:11
This is because of the `user-select` style in your CSS:
```css
input {
  user-select: none;
  -moz-user-select: none;
  -webkit-user-select: none;
}
```

**Comment by bvaughn** [comment] 2019-09-19 20:14
Closing because this behavior isn't due to React/ReactDOM. (You can reproduce it with just JavaScript+HTML.)

**Closed by bvaughn** 2019-09-19 20:14 UTC
