### ISSUE TITLE
Error: "Could not find node with id "952" in commit tree"

### ISSUE THREAD

**Issue by hardikbeladiya** [facebook/react#17052] opened 2019-10-09 13:10 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.0-a8b8ffb89

Call stack: at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154414)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)
    at e (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:154999)

Component stack: in dl
    in div
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by bvaughn** [comment] 2019-10-09 16:25
Duplicate of #16446 that doesn't add any additional info, so closing.

@hardikbeladiya If you would be willing to provide additional info on how to reproduce this bug, that would be very helpful.

**Closed by bvaughn** 2019-10-09 16:25 UTC
