### ISSUE TITLE
Bug: false warnings for controlled form inputs

### ISSUE THREAD

**Issue by justrealmilk** [facebook/react#20092] opened 2020-10-24 18:49 UTC
There are plenty of issues opened for this but they're from like, 1995 so I thought it was best to not ping a thousand people with a comment.

I've tried a handful of different approaches to this problem, including an uncontrolled approach which results in the same error.

The form itself works fine but the console error grinds my gears.

React version: 17.0.1

## Steps To Reproduce

1. create a form as per example

```js
  const [date, setDate] = useState(d);
  const [time, setTime] = useState(t);

  function handler_onChange(event) {
    if (event.target.type === 'date') {
      setDate(event.target.value)
    } else {
      setTime(event.target.value);
    }
  }

  return (
    <div className='form'>
      <div className='field'>
        <input type='time' value={time} onChange={handler_onChange} />
      </div>
      <div className='field'>
        <input type='date' value={date} onChange={handler_onChange} />
      </div>
    </div>
  );
```

## The current behavior
![image](https://user-images.githubusercontent.com/156681/97091139-74bee780-15ee-11eb-82be-bf84c198acca.png)

## The expected behavior
No warning.

**Comment by gaearon** [comment] 2020-10-24 22:55
Sandbox, please? :-)

**Comment by justrealmilk** [comment] 2020-10-24 23:30
> Sandbox, please? :-)

https://codesandbox.io/s/blissful-ramanujan-qse25?file=/src/App.js

**Comment by gaearon** [comment] 2020-10-24 23:32
How do I trigger the warning?

**Comment by IAmRkrishnaV21** [comment] 2020-10-25 01:23
<img width="274" alt="input-error" src="https://user-images.githubusercontent.com/33129619/97096738-ff770500-1635-11eb-8531-4dea394f9cb8.png">

I am also facing the same issue, in my case my input is of type textbox to enter the date, when I changed it to defaultValue as per the warning then its working but the hardest part is, its difficult to make the textbox field empty when trying to reset as I am assigning to defaultValue instead of value. I have to use input ref to clear the actual value instead of resetting the state value.

**Comment by gaearon** [comment] 2020-10-25 01:42
@RamyaKVelivala without a reproducing example in a sandbox that shows the warning, your comment is unfortunately not helpful. There’s nothing I can do because you have not provided sufficient details (a runnable example).

**Comment by gaearon** [comment] 2020-10-25 01:44
If this thread keeps getting more comments where people don’t supply reproducing cases I will have to close it to reduce confusion. Please make sure that if you comment, you have a sandbox that demonstrates the issue.

**Comment by RamyaKVelivala** [comment] 2020-10-25 02:42
@gaearon Sorry for the inconvenience. This warning is visible with onBlur event and trying to set the value. Below is the codesandbox. I have just re-used above example

https://codesandbox.io/s/hardcore-feather-ef0zp?file=/src/App.js

**Comment by gaearon** [comment] 2020-10-25 02:58
Thank you for the example! The warning seems expected here. You’re right there is a trade off — either your pick controlled inputs and write a bit more code or you pick uncontrolled inputs but then resetting is more annoying.

Can you tell me more about why you want to only update the state on blur and not as you type?

**Comment by RamyaKVelivala** [comment] 2020-10-25 03:15
I am using dayjs in my project to build a date range picker to show calendar year, month and day. User can either select a date from calendar control or type in the textbox field to enter date in any format. The reason for choosing onBlur event is to wait until user types in the entire date so that the entire date/text can be validated by dayjs to show any validation error. Not sure if I can use onChange event to validate as it triggers for every letter that we type in and dayjs throws error for every type in text as the entire date or text could not be validated at once.

**Comment by gaearon** [comment] 2020-10-25 07:28
Could you create a sandbox demonstrating that? I’m not familiar with dayjs and its constraints.

**Comment by ben-m-j-taylor** [comment] 2020-10-25 11:11
With regards to reproducing @justrealmilk's issue, I've tried a number of different combinations of ways to structure functions to manage controlled inputs in this [sandbox](https://codesandbox.io/s/react-issue-20092-repro-b3cno?file=/src/App.js) and unfortunately wasn't able to reproduce it.

However if it can be reproduced by someone else I'd be more than happy to pick it up and raise a PR for the fix @gaearon.

**Comment by bvaughn** [comment] 2020-11-07 14:40
I am going to close this issue since it does not have repro information. We will re-open if updates come in.

**Closed by bvaughn** 2020-11-07 14:40 UTC
Labels: Resolution: Needs More Information
