### ISSUE TITLE
Bug: Devtools shows Anonymous for memoized function components

### ISSUE THREAD

**Issue by jwongnz** [facebook/react#17876] opened 2020-01-21 03:53 UTC
![image](https://user-images.githubusercontent.com/34125384/72774268-0794b500-3c5e-11ea-9840-93620f87dbe5.png)

React version: 16.12.0
React dev tools version: 4.4.0

## Steps To Reproduce

1. create-react-app
2. Render memoized function component 
3. Inspect the component with latest React dev tools chrome extension

## The current behavior
Component's name in devtools is Anonymous, I've seen adding a displayName work in the past but it does not anymore.

## The expected behavior
Name of component in devtools should be the set displayName.

**Comment by alikadir** [comment] 2020-01-21 10:03
I have similar issue,
default exported component shows anonymous in devtool

![Screen Shot 2020-01-21 at 1 01 00 PM](https://user-images.githubusercontent.com/11225437/72795168-3571fd80-3c4e-11ea-8897-7bbd6d5d81d9.png)

**Comment by KevinKelbie** [comment] 2020-01-21 10:58
I think I found a workaround. If you do `SomeComponent.type.displayName = "SomeComponent"` it works. Here is a codesandbox for reference: https://codesandbox.io/s/laughing-rgb-v0puv

**Comment by threepointone** [comment] 2020-01-21 15:01
I would not recommend mutating `type.` A 'proper' fix for this, is to use a named function with `React.memo`, like so - 
```jsx 
const SomeComponent = React.memo(function SomeComponent(){
  // ...
})
```
forking your example - https://codesandbox.io/s/laughing-rgb-v0puv-c0nc5

This could be enforced with an eslint rule (similarly for `forwardRef`, imo)

Closing since this is expected behaviour.

**Closed by threepointone** 2020-01-21 15:01 UTC
Labels: Status: Unconfirmed

**Comment by moonrailgun** [comment] 2020-02-12 09:35
@threepointone 
Hi. I dont think its a good idea.  

We use `displayName` to ensure we can check correct name in production environment. Not a compressed function name if use any js compress tools.

and its also have a problem of typescript is the type defintion look like allow set `displayName`. its return `NamedExoticComponent`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/28ff2e3a70ee7172902b2efb0f0c527e8ada0430/types/react/index.d.ts#L798-L801

Please consider it, Please!

**Comment by iyunusov** [comment] 2020-08-14 15:53
So did anyone fix the issue? I still see all Anonymous components when inspected. :(

**Comment by coding-sue-true** [comment] 2021-04-12 16:07
Do you still see if you do the below?

`
const SomeFunction = () => { return () }
export default SomeFunction
`

**Comment by adenekan41** [comment] 2022-03-08 15:44
Still happening in 2022. and still the same solution

```jsx
/**
 * Set display name for the component so it's easily debuggable.
 * the memo method prevents the FC from being named
 */
SomeComponent.displayName = 'SomeComponent';
```

**Comment by rosskipp** [comment] 2022-03-23 13:22
I had this issue after I changed around my browser list to fix a build issue (using parcel). I was able to find a combination of browsers (actually just `"browserlist": "default"`) the build to work to get the component names back. Might be helpful for people with the issue...
