### ISSUE TITLE
keyMirror should be exposed.

### ISSUE THREAD

**Issue by israelito3000** [facebook/react#5467] opened 2015-11-14 01:48 UTC
keyMirror as other utils could be exposed as React.utils.keyMirror or by the way you want, many people have to include the package separated and this could be optimized.

**Comment by jimfb** [comment] 2015-11-14 02:33
This code is intended to be internal to React, and is not part of our public/supported API.  It is an implementation detail, and we reserve the right to make changes at any time, so it should be considered unstable - thus the reason we don't export it.

Duplicate of https://github.com/facebook/react/issues/1639#issuecomment-140133010

**Closed by jimfb** 2015-11-14 02:33 UTC

**Comment by zpao** [comment] 2015-11-14 03:24
FYI: Key mirror is now shipped in fbjs, which react and other Facebook projects consume. It's available there but there are no top level APIs - only require(fbjs/lib/keyMirror) - in that package and the rest of what Jim said holds.
