### ISSUE TITLE
Error: "Minified React error" in React dev tools when using Components tab

### ISSUE THREAD

**Issue by tchaffee** [facebook/react#16926] opened 2019-09-27 14:29 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
React Dev tools gets this error when I try to look at the Components Tab

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I don't know how to reproduce it. It was working yesterday and not working today.

**What is the expected behavior?**
That the Components tab of the React dev tools doesn't crash.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6.3

Here is what I see. It's not my React app crashing. It's the dev tools.

![Selection_880](https://user-images.githubusercontent.com/148813/65777237-058c7080-e11a-11e9-800a-261e2d3f435d.png)

Copy paste of the errors from the screenshot in case that's helpful:

```
The error was thrown at hi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:61172)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:256084
    at Vo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:256125)
    at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58828)
    at Jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103390)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89163)
    at Ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89088)
    at ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86037)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45275
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:3691)
```
```
The error occurred in Vo
    in div
    in aa
    in div
    in za
    in div
    in si
    in div
    in li
    in Suspense
    in Wa
    in div
    in div
    in Jo
    in Xr
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc
```

**Comment by bvaughn** [comment] 2019-09-27 17:59
Hi @tchaffee. Can you give me some more info about which operating system and browser/version you're using? I'm not able to reproduce this behavior, although clearly some others are (e.g. #16925) I'm just trying to figure out how to narrow down the cause.

**Comment by bvaughn** [comment] 2019-09-27 18:10
@tchaffee If you can reproduce the problem reliably, I wonder if you'd be willing to install a test build of DevTools to see if it fixes the problem. (I could create a build after backing out one or two changes that might be related, to at least help narrow down the cause.)

**Comment by tchaffee** [comment] 2019-09-27 20:14
@bvaughn I can't reproduce it. It went away. Must have been something in my branch that has since changed. It was happening in both Chrome and Chromium.

OS: Ubuntu 18.04.3 LTS. 
Chrome: Version 77.0.3865.90 (Official Build) (64-bit)
Chromium: Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

If I do get it to happen again reliably, I'll freeze the branch and let you know.

**Comment by bvaughn** [comment] 2019-09-27 20:21
Thanks much for the update.
Please do keep me posted.

**Comment by bvaughn** [comment] 2019-09-27 21:07
Looks like fa1a326 was the problematic commit. Not sure why yet though.

**Comment by bvaughn** [comment] 2019-09-27 23:32
Bugfix posted via PR #16934

**Comment by bvaughn** [comment] 2019-09-28 00:09
4.1.2 has just been published to NPM and uploaded to the Chrome+Firefox stores with a fix for this issue. Thank you for the report and I apologize for the inconvenience.

**Closed by bvaughn** 2019-09-28 00:09 UTC
Labels: Component: Developer Tools, Type: Bug
