### ISSUE TITLE
onChange event not fired when with pollfilled IE8

### ISSUE THREAD

**Issue by hh9527** [facebook/react#4637] opened 2015-08-16 04:48 UTC
I used IE8 pollyfill
 from https://github.com/WebReflection/ie8 and onChange event for <input> is broken.

**Comment by sairion** [comment] 2015-08-17 11:27
How is it "broken"? Would you care to elaborate?

**Comment by spicyj** [comment] 2015-08-18 00:40
Dupe of #3131, more or less. I don't know yet whether we want to support this.

**Closed by spicyj** 2015-08-18 00:40 UTC
