### ISSUE TITLE
Error: "Minified React error #301"

### ISSUE THREAD

**Issue by AkitoItashi** [facebook/react#16925] opened 2019-09-27 13:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The Chrome React Developement Tool throws this error:

> The error was thrown at hi (chrome-
> extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:61172)
>     at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:256084
>     at Vo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:256125)
>     at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58828)
>     at Jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103390)
>     at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89163)
>     at Ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89088)
>     at ac (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86037)
>     at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45275
>     at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:3691)

> The error occurred in Vo
>     in div
>     in aa
>     in div
>     in za
>     in div
>     in si
>     in div
>     in li
>     in Suspense
>     in Wa
>     in div
>     in div
>     in Jo
>     in Xr
>     in _o
>     in Unknown
>     in n
>     in Unknown
>     in div
>     in div
>     in zi
>     in Ge
>     in un
>     in ba
>     in Rc

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
When I open the Developement Tool for Chrome i get the error, without doing anythign special sometimes.
After reloading the frame it only says: Unable to find React on the page.
I need to shutdown my whole PC and restart it, then I see the Tool again, till I go onto the next page and it needs to reaload...

**What is the expected behavior?**
No crash.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- Windows 10 Version 1903 (Build 18362.356) 64-bit
- Google Chrome Version 77.0.3865.90 64-bit
- React Developer Tools (Version created from revision a9cd9a765)
It worked very well some days ago, without any errors.

**Comment by AkitoItashi** [comment] 2019-09-27 13:35
Addition:
It seems like it is throwing the error, when i use the select-component-tool to click on an element in the viewport, so that it gets focussed in the React Developer Tool...

**Comment by bvaughn** [comment] 2019-09-27 18:03
@AkitoItashi Is there any particular element this happens for or a particular website? I'm not able to reproduce the problem so far (although I'm not using Windows 10)

**Comment by bvaughn** [comment] 2019-09-27 18:10
@AkitoItashi If you can reproduce the problem reliably, I wonder if you'd be willing to install a test build of DevTools to see if it fixes the problem. (I could create a build after backing out one or two changes that might be related, to at least help narrow down the cause.)

**Comment by bvaughn** [comment] 2019-09-27 21:07
Looks like fa1a326 was the problematic commit. Not sure why yet though.

**Comment by bvaughn** [comment] 2019-09-27 23:32
Bugfix posted via PR #16934

**Comment by bvaughn** [comment] 2019-09-28 00:09
4.1.2 has just been published to NPM and uploaded to the Chrome+Firefox stores with a fix for this issue. Thank you for the report and I apologize for the inconvenience.

**Closed by bvaughn** 2019-09-28 00:09 UTC
Labels: Component: Developer Tools, Type: Bug
