### ISSUE TITLE
Update shouldComponentUpdate docs with advice about closures

### ISSUE THREAD

**Issue by thysultan** [facebook/react#12185] opened 2018-02-08 12:38 UTC
**Do you want to request a *feature* or report a *bug*?**

Possible bug depending on my understanding of the new context feature.

**What is the current behavior?**

The presence of an `<Indirection>` component with `shouldComponentUpdate:false` is blocking updates to context consumers below it after the first click of "Toggle Top Data": [https://codesandbox.io/s/v87rp187r7](https://codesandbox.io/s/v87rp187r7)

**What is the expected behavior?**

For consumers below a shouldComponentUpdate component to continue updating after the first "Toggle Top Data" click.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3.0-alpha.0

**Comment by TrySound** [comment] 2018-02-08 13:21
@thysultan That's the case of `shouldComponentUpdate`. React just don't react on changing props. The case of new context api is not relating to shouldComponentUpdate of component which renders consumer itself like here
```js
class Indirection extends React.Component {
  shouldComponentUpdate() {
    return false;
  }
  render() {
    return (
      <DataConsumer>
        {nestedController => (
           <div>
           </div>
          )}
       </DataConsumer>
    );
  }
}
```

**Comment by TrySound** [comment] 2018-02-08 13:43
@thysultan It's not a bug. Indirection component is not rendered when any prop is changed. Consider `children` as any prop.

**Comment by thysultan** [comment] 2018-02-08 13:53
I'm not sure i understand you, `<Indirection>` is updated when you click "Toggle Top Data" the first time but stops updating on future events. The test details that the new context API should be able to propagate updates through any* number of nested components that could have otherwise prevented the update with `shouldComponentUpdate:false` in the alternate/older context API.

**Comment by bvaughn** [comment] 2018-02-08 23:03
I think the test you linked to specifically confirms that the behavior works correctly. (The `Indirection` component is not rendered again, since it returns false from `shouldComponentUpdate`, but the `Context.Consumer` _is_ rerendered when the `Context.Provider` value changes.)

In this case, your test shows that changes to `topController` don't propagating through the `Indirection` component to the _inner_ consumer, but I think that's expected, because the `Indirection` is _inside of_ the top-level consumer.

**Comment by thysultan** [comment] 2018-02-08 23:14
The behavior works for the first click, but subsequent clicks are not registered(every click should alternate between true and false).

**Comment by bvaughn** [comment] 2018-02-08 23:27
I don't know. This test is hard for me to read. There's several levels of indirection and stuff.

I've tried to simplify it a little (so I can better understand it) here:
https://codesandbox.io/s/7wl94qq5m0

I see the behavior I would expect from this.

**Comment by thysultan** [comment] 2018-02-08 23:45
The expected result based on what i understand from the test specifications would be identical to [https://codesandbox.io/s/321kq30kx1](https://codesandbox.io/s/321kq30kx1).

**Comment by bvaughn** [comment] 2018-02-08 23:53
Please take a look at the CodeSandbox I linked, and let me know what's unexpected.

Your CodeSandbox is a bit odd to me. It has the following structure:
Context.Consumer > Context.Provider > Context.Consumer > Context.Consumer > Context.Provider > Context.Consumer

**Comment by thysultan** [comment] 2018-02-09 00:19
The CodeSandbox you linked to doesn't reveal the same behavior/bug.

Yes there's a lot of `Indirection`, i think that was intentional for that particular example, the original was by @kentcdodds, i added the `Indirection` component to get a better sense of what the context API is spec'd to support.

Does the new Context API have restrictions on the amount of indirection a context update can propagate through?

**Comment by bvaughn** [comment] 2018-02-09 02:12
I'm just not convinced it _is_ a reasonable bug. What does it even mean for a context's `Consumer` to wrap its own `Provider` (as it does in your example)? It looks like a mistake, like you're using the consumer and provider in exactly the opposite way as they're intended. This is why I rewrote in an attempt to simplify.

**Comment by bvaughn** [comment] 2018-02-09 02:13
Can you point me to the example by Kent that you're referring to?

**Comment by bvaughn** [comment] 2018-02-09 02:26
I assume you're referring to [this blog post](https://dev.to/kentcdodds/reacts--new-context-api-dpi)?

It does not demonstrate the odd wrapping/nesting behavior your CodeSandbox does.

I think this is kind of a version of Kent's that shows the indirection you mention (and it also seems to work):

https://codesandbox.io/s/mz5m6zx2zx

**Comment by thysultan** [comment] 2018-02-09 07:03
The CodeSandBox is a fork of Kent's [CodeSandBox](https://twitter.com/kentcdodds/status/961284657353404417) – my fork adds the `<Indirection>` component to the version posted in this issue.

**Comment by bvaughn** [comment] 2018-02-09 15:24
Can you acknowledge [the strange nesting structure](https://github.com/facebook/react/issues/12185#issuecomment-364288859) and explain why it's important? I believe it's the cause of the behavior you're reporting as unexpected, and I don't understand why it's necessary.

For instance, if you remove the double layer of `Context.Consumer` in the middle, the pen behaves like you want it to:
https://codesandbox.io/s/47vq1pzx0

**Comment by jquense** [comment] 2018-02-09 15:37
@bvaughn  a "Consumer wrapping its own Provider" is a pattern I ran into migrating code to the new API, as a way for having components map/alter context as it passes through. It does seem though like the problem is not that but `Consumer` -> `Consumer` or at least that pattern mixed around the nested Providers. Still I can think of cases where that might happen naturally? e.g nested ThemedComponents, each consumer the context?

**Comment by bvaughn** [comment] 2018-02-09 15:49
To be clear, context supports nesting the same provider multiple times, and there are tests for this, so it's okay for a provider to be an ancestor of a consumer. The code snippet provided above just looked a bit unnecessarily/arbitrarily complex and so I was trying to better understand _why_ it had to be that way.

I'm not sure yet what the specific bit that's causing a problem is. Maybe I'll try to pair it down in a unit test this morning.

**Comment by gaearon** [comment] 2018-02-09 15:51
In any case, whether there is a bug in React and whether the code is strange are two different discussions.

**Comment by jquense** [comment] 2018-02-09 15:52
sure, just trying to help out i've also not been able to simply the example effectively :/

**Comment by gaearon** [comment] 2018-02-09 15:58
Yeah, I just mean that

>I'm not sure this level of nesting is indicative of a valid use-case

doesn't mean we shouldn't fix it. 🙂

**Comment by bvaughn** [comment] 2018-02-09 16:03
> In any case, whether there is a bug in React and whether the code is strange are two different discussions.

I didn't mean to imply otherwise, although re-reading the comment you quoted above, I can see where it gave that impression.

**Comment by gaearon** [comment] 2018-02-09 16:04
I thought so, just wanted to make sure the original author also knows this. 🙃

**Comment by bvaughn** [comment] 2018-02-09 16:05
Good call.

I'm going to pick this up now and see if I can catch it in a local test.

**Comment by gaearon** [comment] 2018-02-09 16:09
Here's a reduced case. https://codesandbox.io/s/k967n8x5v

I'm not convinced it's a bug. I think it might be an artifact of reading `topController.data` from a closure (from an old render). Not sure.

**Comment by bvaughn** [comment] 2018-02-09 16:11
Here's a more reduced case: https://codesandbox.io/s/mq29590rjy

If you remove the `Indirection` component (or comment out its sCU method) the "bug" doesn't manifest.

**Comment by gaearon** [comment] 2018-02-09 16:14
Apparently I gave a wrong link :-( I had a smaller example but CodeSandbox didn't save it.

**Comment by bvaughn** [comment] 2018-02-09 16:14
Yeah, adding logging to the click handler shows that's the case: stale data

> sandbox.16fdafda.js:5036 onClickHandler() {
  "topLevel": true
}
08:14:22.920 sandbox.16fdafda.js:5036 onClickHandler() {
  "topLevel": true
}
08:14:23.435 sandbox.16fdafda.js:5036 onClickHandler() {
  "topLevel": true
}
08:14:23.690 sandbox.16fdafda.js:5036 onClickHandler() {
  "topLevel": true
}
08:14:23.864 sandbox.16fdafda.js:5036 onClickHandler() {
  "topLevel": true
}

**Comment by gaearon** [comment] 2018-02-09 16:18
Here's an example with components combined https://codesandbox.io/s/kyrj9jq93

**Comment by bvaughn** [comment] 2018-02-09 16:18
The problem is that the inner `Indirection` prevents the `button` from re-rendering with new data.

**Comment by bvaughn** [comment] 2018-02-09 16:19
The consumer _is_ being re-rendered each time though (as my added logging shows)

**Comment by gaearon** [comment] 2018-02-09 16:20
That makes sense to me (and sounds as expected behavior).

The tree is:

```
- Provider
  - Consumer
    - Indirection that blocks update
      - Component that doesn't re-render but uses values from consumer
```

The fix would be to move indirection above the consumer.

**Comment by bvaughn** [comment] 2018-02-09 16:20
Yup, yup. Agreed.

**Comment by gaearon** [comment] 2018-02-09 16:21
I guess it's worth documenting as a gotcha.

**Comment by gaearon** [comment] 2018-02-09 16:22
The original example still confuses me though. There, Indirection appears to be inside of the consumer..

**Comment by gaearon** [comment] 2018-02-09 16:23
Ahh I get it now. It's inside a *nested consumer*. It's trying to read a value from the *top-level* consumer though.

This is exactly why "toggle nested" keeps working. It only uses context values "below" the indirection.

**Comment by bvaughn** [comment] 2018-02-09 16:23
Yup!

**Comment by gaearon** [comment] 2018-02-09 16:25
This is why I hate render props 😂 

Well, not "hate". But I do find that they present their own pitfalls compared to HOCs, and people too readily ignore them. Anyway, I'm fine with the new context API. Just ranting a bit.

**Comment by bvaughn** [comment] 2018-02-09 16:26
😆 

cc @acdlite too (who is writing the new context API docs)

**Comment by acdlite** [comment] 2018-02-09 18:18
There are a few things going on here. One is that closures are confusing. It's really easy to accidentally depend on values from an outer scope without realizing it. @gaearon is right that render props, because they rely on closures, can exacerbate this confusion.

But in my view the core problem with all these examples with all these examples is that `shouldComponentUpdate` always returns false. The solution is... not to do that :D (So it's worth pointing out that you could have this same bug with an HOC or with a normal component, too.)

By returning return false in from Indirection's `shouldComponentUpdate`, you're signaling to React that the children are the same. So, it never re-renders the children, sp the click event handler never gets updated with the new closure values, so the `topController.data` is stale the next time you click it.

The unit tests for context happen always return false in `shouldComponentUpdate` in a few places, but that's my bad. I should have chosen a more realistic scenario. You should never do that unless the children are completely static.

I believe the actionable items for React here are:

- Add additional documentation for `shouldComponentUpdate` with advice to never treat two closures  or two `children` props as equal unless they are referentially identical, since it's impossible to know what values they close over.
- In the documentation for the new context API, when advertising its ability to bypass `shouldComponentUpdate` bailouts, don't mislead people into thinking that it can reach into JavaScript closures and swap out those values, too 😆

**Comment by thysultan** [comment] 2018-02-09 18:28
From my understanding of the new API this looked like a bug since it manifested the same limitation of the old context API – that is i expected `DataConsumer` to re-render regardless of `shouldComponentUpdate:false`, and in doing so also update the inline `onClick` function.

**Comment by gaearon** [comment] 2018-02-09 18:41
> i expected DataConsumer to re-render regardless of shouldComponentUpdate:false, and in doing so also update the inline onClick function.

`DataConsumer` *did* re-render. There's no reason why it would update the `onClick` function though because `Indirection` says "I never update to new children". 

Maybe a simpler way to explain this is imagine you had code like this:

```js
<Context>
  {value => (
    <Indirection>
      {value}
    </Indirection>
  )}
</Context>
```

I hope you can see that there's no way `value` would update, with either old or new context.

It wouldn't even update if there was no context usage at all:

```js
function MyLabel(props) {
  return (
    <Indirection>
      {props.value}
    </Indirection>
  );
}
```

Does this make more sense now?

New context doesn't force every single component below to update, just in case some of those components happen to pass that context value down and later render it.

New context just fixes an issue where *context consumers* wouldn't get updated. From them and down, everything flow like normal React, subject to normal React rules.

Another way to explain this is that your example would work if you changed `Indirection` to shallowly compare props (e.g. by inheriting from `PureComponent`). Then it would "notice" the `children` element has changed. With old context, `PureComponent` wouldn't work there, but with the new one, it does.

**Comment by acdlite** [comment] 2018-02-09 18:43
@thysultan An easy way to confirm that the consumer re-renders is to put a log statement inside its render prop.

**Comment by thysultan** [comment] 2018-02-09 18:50
>DataConsumer did re-render. There's no reason why it would update the onClick function though because Indirection says "I never update to new children".

I'm assuming that if it re-renders then it also reconciles the difference...

```
<Indirection>
  <DataConsumer>
    {nestedController => (...)}
```

That is to say, it calls the render prop function and reconciles that part of the tree using the new return value.

>I hope you can see that there's no way value would update, with either old or new context.

The `Indirection` is outside of `DataConsumer` so i'm not sure that example would apply in this case.

**Comment by gaearon** [comment] 2018-02-09 19:07
It applies in your case, it's just not very obvious why.

<img width="666" alt="screen shot 2018-02-09 at 7 02 46 pm" src="https://user-images.githubusercontent.com/810438/36044918-090ab492-0dcc-11e8-9535-26495e3c8778.png">

The root of the issue is you're referencing top-level `topController` value from that nested closure at the bottom. But `Indirection` doesn't update its children. The context consumer in it re-rendered, but because `Indirection` refused to update, **the `topControlled` value in the closure is stale**. So it just uses the previous value again.

You'd have the exact same problem if you just closed over some variable at the top of the render method, and then have that "blocking" indirection in the middle. Even if a component deeper than the indirection re-rendered, it would still have the "stale" top-level value from a stale closure.

**Comment by gaearon** [comment] 2018-02-09 19:12
<img width="666" alt="screen shot 2018-02-09 at 7 02 46 pm" src="https://user-images.githubusercontent.com/810438/36045318-38e30204-0dcd-11e8-9878-b70495ace55a.png">

**Comment by thysultan** [comment] 2018-02-09 20:03
Thanks, that makes sense.

**Comment by tkh44** [comment] 2018-02-10 21:27
For anyone that wants to play around with this concept, I made a sandbox that might be useful.

https://codesandbox.io/s/k0lmr9xn57

**Comment by Nirvananirvan** [comment] 2018-02-16 16:06
Lets me

**Comment by gaearon** [comment] 2018-08-09 01:04
Closing since it doesn't seem to come up often.
Also we track docs issues in https://github.com/reactjs/reactjs.org now.

**Closed by gaearon** 2018-08-09 01:04 UTC
