### ISSUE TITLE
DevTools: "Show only components where..." instead of just "Hide components where"

### ISSUE THREAD

**Issue by tanhauhau** [facebook/react#16835] opened 2019-09-19 15:43 UTC
I wonder whether is it in the plan to do the inverse of hiding components that match the filters, which is "show only components where match the filters"?

I am currently doing a negative lookahead regex filter to achieve the behavior: https://twitter.com/lihautan/status/1174239606612647941. 

I am willing to work on it if this is a good feature to have.

**Comment by bvaughn** [comment] 2019-09-19 15:59
No plan to switch the filter UX. Admittedly it's a bit anecdotal, but we think the most common use case is to _hide_ host components (it's even the default). This would be a lot more work to do if we inverted the search.

If you are asking about whether we show _both_ options, I did briefly consider that (even mocked it up at one point) but decided against it for two reasons:
* I think the expected behavior would be a little confusing. What if show and don't-show filters collide? There is precedent in other tools for this that we could follow though, probably.
* I don't think filtering is "core" enough for DevTools to warrant the extra effort/complication to the code. In many cases, and as you mentioned, negative regex filters can be used to approximate this.

**Comment by bvaughn** [comment] 2019-09-19 16:00
I'm on the fence about whether to leave this open or close it. I think I'm going to close it since it was a question asked and answered. If you're passionate about this, PRs are always welcome and we could discuss it more.  I don't think anyone on the team has any plans to build this feature though. 😄

**Closed by bvaughn** 2019-09-19 16:00 UTC
Labels: Component: Developer Tools
