### ISSUE TITLE
useContext(Context.Consumer) doesn't receive updates properly

### ISSUE THREAD

**Issue by nealeu** [facebook/react#14019] opened 2018-10-29 12:07 UTC
I think there's a bug in 16.7.0-alpha.0 unless this is intentional.

**What is the expected behavior?**
I've been using the context API to implement a dynamic loader where a parent component is responsible for triggering and loading some network data, and one or more grand-child components want to consume that data or show "Loading..." while that data is being fetched.

**What is the current behavior?**
When I migrated to useContext() I don't get a re-render, and can't quite see how this is going to come about.  

Can you update examples to show dynamic behaviour, or if not supported to highlight that we will still need to use Context.Consumer for that.

**Comment by nealeu** [comment] 2018-10-29 15:36
It's looking like react-async is a good generalisation of my current approach and also provides a [useful view of how they may go with useAsync building on the Hooks API](https://github.com/ghengeveld/react-async/pull/9/files), but it does look even more complex under the hood and perhaps is an API that itself to be at the core of React so as to have good support and coverage.

**Comment by aweary** [comment] 2018-10-30 02:32
Can you please provide a code sample demonstrating the bug you're reporting? You can use https://codesandbox.io/s/new as a starting point.

**Comment by nealeu** [comment] 2018-11-03 16:52
Sorry folks.  If you read what I wrote, you'll see that I am asking if this is the intended behaviour or not.  For now I'll leave those with employers who are in profit to take the time on this.  I'll just stick with the old ways until things are stable.

**Comment by gaearon** [comment] 2018-11-03 19:18
That’s not intentional based on the description. Unfortunately things can only get more stable if people help us by isolating issues. Appreciate your help reporting this and hope we’ll get more details from somebody else!

**Comment by sophiebits** [comment] 2018-11-05 00:33
@nealeu Here's a demo of useContext triggering a rerender even though an ancestor returned false from shouldComponentUpdate:

https://codesandbox.io/s/zw0qk98k9p

For the purposes of updates, it should work exactly the same way as a context Consumer component does.

I'm going to close this issue since I don't believe there is enough info here for this to be actionable for us right now, but if you end up having time to comment here with a small test case or if someone else runs into the same issue we'll definitely take a look.

**Comment by markerikson** [comment] 2018-11-05 00:57
@nealeu : were you running `useContext(MyContext)`, or `useContext(MyContext.Consumer)` ?  When I tried the latter, I found that my component received an _initial_ value, but did not get re-run when the context updated.  The React team has told me that this is actually a bug, in that passing only the consumer shouldn't work at _all_ - you should be passing the _entire_ context object.

**Comment by sophiebits** [comment] 2018-11-05 00:58
@markerikson whoaaaa

**Comment by sophiebits** [comment] 2018-11-05 01:06
@nealeu Can you confirm if this is what you were doing? I'll mention that you should have seen a warning in your console saying this:

> Warning: Calling useContext(Context.Consumer) is not supported, may cause bugs, and will be removed in a future major release. Did you mean to call useContext(Context) instead?

But maybe we should make this more obvious.

**Comment by Kovensky** [comment] 2018-11-05 08:30
This is not released yet, it could be better to just never add support to it in `useContext` to begin with if detectable.

**Comment by nealeu** [comment] 2018-11-05 10:22
I was using useContext(Context).  

I'm happy for this to be closed given there is a working example (thanks @sofiebits), but will have another look as it should come up during our hackathon this week.

**Comment by tgochenour** [comment] 2018-11-22 20:11
> @sophiebits Here's a demo of useContext triggering a rerender even though an ancestor returns false from shouldComponentUpdate:
> 
> https://codesandbox.io/s/zw0qk98k9p
> 

I have a question regarding useContext() as utilized in this demo.  I've compared my prototype to this demo and I believe the significant difference of the two is that yours is a simple type:
<Context.Provider value={count}>...

whereas mine is a composite type:
  return <DataContext.Provider value={data}>{props.children}</DataContext.Provider>;

Yours is a simple number type whereas mine is a JSON object containing changes made within.  The top level object reference hasn't changed.  Is this the reason why my children who useContext(DataContext) are not getting notified of changes to the document?

I'm looking for best practices here.  I've just started researching MobX as a mechanism for observing object fragments within this object for any changes. This may well solve my problem.  I see they have released an Alpha of MobX for Hooks.  Everything is on the cutting edge.

**Comment by gaearon** [comment] 2018-11-22 20:21
>With mine the top level object reference doesn't change. Is this the reason why my children who useContext(DataContext) are not getting notified of changes to the document?

Yes.

https://reactjs.org/docs/context.html#contextprovider

>Changes are determined by comparing the new and old values using the same algorithm as `Object.is`.

**Comment by tgochenour** [comment] 2018-11-22 20:49
Thank you for a quick response.  I have code written to clone the original document before calling setState() and this made the object reference different so useContext() would properly trigger a complete rendering of the page.  I'm concerned this may be too compute intensive so today I'm researching the right way to do this.

So is best practice for observing changes to fragments of an object is to use MobX observable pattern?  There's nothing I'm missing available within React that handles this case?  I have fields listening at multiple scopes, first for their own individual property changes, then listening for changes to other properties of the same transaction and also listening for global replacement of the entire document.  All the tutorials/examples I've seen handle simple types.  But how does this scale?

**Comment by tgochenour** [comment] 2018-11-23 17:44
I'm cloning the DataContext document and replacing the old one with the new one so that consumers are notified to update.  All of the components that use DataContext will re-render.  Then all of them fire their side-effect to fetch current data from DataContext.  If the current state is different from the one retrieved, then the side-effect triggers another render of that particular component.  This two phase process is what you call lazy-loading and is by design (yes?).  

I'm attempting to write <table> insert/delete row functionality and I find the removal of a table row has got some weird behavior where the state of a component is transferred to the component of the next row.  Everything is async so timing is key.  Perhaps Its the GSX key of each row that's at issue.  

I'm considering if there is a way to add additional layers of contexts (like a TransactionContext around each table row) to break the composite document into logical fragments that consumers can focus on so they won't be asked to re-render so much.  It's just a thought, don't know where it'll go.  What I need is a way to register conditional observers so the consumer can say what its really interested in.  Right now everything is interested in everything else.

I've spent my first day now with MobX tutorials.  MobX wraps accessors in the standard JS Object prototype to implement an observable across all properties/arrays/objects of that object.  Any access to the object then becomes an observer...by magic (so it seems).  All the examples I've seen so far are condensed into one component.  These simple examples hide the complexity I know I will need to spread observers across multiple grandchildren.  I'm sure it can be done, I just haven't seen proof of it yet.

**Comment by gaearon** [comment] 2019-01-18 03:38
We added a warning for this.

**Closed by gaearon** 2019-01-18 03:38 UTC
Labels: Resolution: Needs More Information

**Comment by xskipy** [comment] 2020-07-09 11:49
Little offtopic but google directed me here with my slightly different problem, when my function didn't receive context value properly.
My problem was with using `useCallback()` function and i didn't put the context value into the `inputs` array of the function, so it was returning memoized version with the default context value.)
For future reference of anyone wondering where the problem is.
`const myFunction = useCallback((functionInput) => /*function body*/ ,[inputsArray, contextValue]);`
