### ISSUE TITLE
ReactDOM - Internet Explorer  - ie11 exception thrown and not caught (notFoundError - SCRIPT5022 )

### ISSUE THREAD

**Issue by B-o-l-e** [facebook/react#12988] opened 2018-06-06 22:42 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
For some reason just IE 11 is raising an exception and pointing to this:
```
ReactBatch.prototype._onComplete = function() {
  if (this._didComplete) {
            return;
  }

  this._didComplete = true;
  const callbacks = this._callbacks;
  if (callbacks === null) {
    return;
  }

  // TODO: Error handling.
  for (let i = 0; i < callbacks.length; i++) {
    const callback = callbacks[i];
    callback();
  }
};
```

**What is the expected behavior?**
My guess is that it wouldn't throw an exception if the callback call is handled.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Not sure, started seeing it in the last month and a half or more.

The thing is, the exception just pops up randomly. I can see that it happens on a project a lot lately from the logs. Ill make a fork, this seems very easy to handle, posting for visibility, any insight of what this code actually does and why it would break on ie 11 is welcome.

Thanks

**Comment by aweary** [comment] 2018-06-06 23:53
Thanks for the report @B-o-l-e. We'll need an example reproducing the issue to be of any help here.

**Comment by aweary** [comment] 2018-06-24 01:18
Closing this out since there's been no follow up.

**Closed by aweary** 2018-06-24 01:18 UTC
Labels: Resolution: Needs More Information
