### ISSUE TITLE
[DevTools Bug]: Different results in chrome and firefox

### ISSUE THREAD

**Issue by bhargavmungara** [facebook/react#23155] opened 2022-01-20 18:17 UTC
### Website or app

https://www.youtube.com/, https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox,https://docs.github.com/en

### Repro steps

I was using the YouTube website. I have a habit of checking if the website i have visited was using react or not. As always I checked for YouTube website too. But the react developer tools extension was showing the youtube website is using react. 

Just to make sure it was right I have installed the firefox browser then installed the react developer tools extension and opened the youtube website, But in firefox, the extension was saying the youtube is not using react. 

For confirming with other websites, I have visited mdn and GitHub docs in both chrome and firefox. The chrome react developer tools extension says that the mdn is using react and the firefox react developer tools extension says that the mdn is not using react. For the GitHub docs website, the chrome extension says that the GitHub docs website was using the react whereas the firefox react developer tools extension shows that the Github docs website doesn't use the react. 

I am attaching the screen recording. To differentiate what websites I have visited in chrome and firefox I previously opened the websites in chrome and showed the results, for firefox I have typed the query and showed the results. Can you tell why it was happening like this?

https://user-images.githubusercontent.com/59245935/150397327-1cae5d73-0e63-4a32-b54b-5aa3da522db4.mov

Repro steps
1. Login to the website
2. Scrolling  the website
3. Noticed the bug 

Versions:

Chrome: 97.0.4692.99
Firefox: 96.0.2
React Developer Tools:4.22.0

### How often does this bug happen?

Every time

**Comment by harish-sethuraman** [comment] 2022-01-20 18:30
This issue is not seem to be caused by react dev tools. Possibly a duplicate of https://github.com/facebook/react/issues/23107.

**Comment by bvaughn** [comment] 2022-01-20 20:37
That's right. This was a bug caused by Redux DevTools (https://github.com/reduxjs/redux-devtools/issues/1030) which has since been fixed. Just update (or disable) the Redux DevTools extension to get rid of the bug.

**Closed by bvaughn** 2022-01-20 20:37 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools

**Comment by bhargavmungara** [comment] 2022-01-21 10:33
I uninstalled and installed the Redux DevTools extension. it works normally now. Thanks for the reply
