### ISSUE TITLE
Error: "Commit tree does not contain fiber 13861. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by didulalakshitha** [facebook/react#20288] opened 2020-11-18 08:32 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.0-11a2ae3a0d

Component stack: CommitFlamegraphAutoSizer@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:34133:50
div
div
div
SettingsModalContextController@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:28194:1
Profiler_Profiler@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:35761:50
ErrorBoundary_ErrorBoundary@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:29208:5
PortaledContent@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:29325:27
div
div
ProfilerContextController@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:32922:1
TreeContextController@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:24310:1
SettingsContextController@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:24799:1
ModalDialogContextController@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:29392:1
DevTools_DevTools@moz-extension://6d279fb6-5484-4bfe-af1b-7776429d75f6/build/main.js:36195:1

**Comment by bvaughn** [comment] 2020-11-18 15:29
Please do a quick search for existing bugs before filing a new one. This particular issue has been filed ~30 times :smile:

Closing as a duplicate of #20197

**Closed by bvaughn** 2020-11-18 15:29 UTC
