### ISSUE TITLE
cloneWithProps with function type property, `this` points to window

### ISSUE THREAD

**Issue by jzlxiaohei** [facebook/react#2861] opened 2015-01-15 12:13 UTC
``` js
var React = require('react')
require('react/addons')
function createCircle(x,y,r){
    return (
        <circle r={r} cx={x} cy={y}/>
    )
}

var MyCircle = React.createClass({
    render:function(){
        var circle = createCircle(100,100,10);
        return (
            React.addons.cloneWithProps(circle,{
                onClick :function(){
                    console.log(this);
                }
            })
        )
    }
})

React.render(
    <MyCircle />,
    document.getElementById('svg-test')
)
```

when click the circle , `this` is `window`。

i am not sure whether it is a bug,but it will be nice if `this` refer to `MyCircle` element

**Comment by andreypopp** [comment] 2015-01-15 12:22
This is not a React issue, just bind function to `this` before passing to `cloneWithProps`:
```
onClick: function(){
  console.log(this);
}.bind(this)
```

**Comment by jzlxiaohei** [comment] 2015-01-16 05:25
@andreypopp ok..but what about the code below

```js
// extraProps  from outside
var extraProps={
    onClick :function(){
        console.log(this);
    }
}
var MyCircle = React.createClass({
    render:function(){
        var circle = createCircle(100,100,10);
        return (
             //var returnObj=
             React.addons.cloneWithProps(circle, 
                extraProps //!!!
            )
        )
    }
})  
```
i have to loop the props of `returnObj`, if prop is `function` then `bind(returnObj)`,it works,but uncomfortable

**Comment by HeyImAlex** [comment] 2015-01-27 22:32
This is the intended behavior, but I think maybe I understand why you're having problems.

Try the same thing with something way simpler, no need to even involve cloneWithProps, and [you get the same thing](http://jsfiddle.net/kb3gN/9157/).

If, however, you add an event listener to the actual element, [you see what (I'm thinking) you expect](http://jsfiddle.net/kb3gN/9158/), the targeted element.

So DOM level 2 events will call the listener function with `this` set at the element the listener was added to. But [inline listeners don't do that](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget.addEventListener#The_value_of_this_within_the_handler), and React listeners are... kind of neither but they definitely don't do that either. Whatever function props you pass will need to be bound by you or they'll be called without a `this`.

If you just want the target, take it from the event passed to the handler:

function(e){
    console.log(e.target);
}

**Comment by jsfb** [comment] 2015-01-29 02:58
I'm not entirely sure what your updated question/post is asking, but it doesn't look like a React bug, so I'm going to close it out.  Let me know if you still believe this is a bug and we can reopen.

The bind method is well-documented here:
https://msdn.microsoft.com/en-us/library/ie/ff841995%28v=vs.94%29.aspx

In React 0.4, we introduced a feature called autobinding, which saved some typing:
http://facebook.github.io/react/blog/2013/07/02/react-v0-4-autobind-by-default.html

Turns out, this has been the source of a lot of confusion, so autobinding will not be enabled for React 0.13 using ES6 classes:
http://facebook.github.io/react/blog/#autobinding

**Closed by jsfb** 2015-01-29 02:58 UTC
