### ISSUE TITLE
Hanging process references in 15.3.0 pulling in shim when bundling

### ISSUE THREAD

**Issue by insin** [facebook/react#7447] opened 2016-08-09 01:00 UTC
This occurs a bunch of times in 15.3.0:

``` js
if (typeof process !== 'undefined' && process.env && process.env.NODE_ENV === 'test') {
  // Temporary hack.
  // Inline requires don't work well with Jest:
  // https://github.com/facebook/react/issues/7240
  // Remove the inline requires when we don't need them anymore:
  // https://github.com/facebook/react/pull/7178
  ReactComponentTreeDevtool = require('./ReactComponentTreeDevtool');
}
```

This leaves some `process` references after the usual `process.env.NODE_ENV` replacement is done when creating a production build, resulting in a `process` shim being pulled in and increasing your bundle size unless you manually configure it off (e.g. `node: {process: false}` in Webpack config).

Should this be mentioned in the release notes?

**Comment by zpao** [comment] 2016-08-09 01:14
This was an intentional change but I hadn't thought of that case. cc @gaearon

**Comment by gaearon** [comment] 2016-08-09 09:31
Yeah, this is a temporary build size regression (it doesn't affect our UMD builds but it will affect the ones you bundle yourself). I don't think it's worth mentioning because we intend to fix it with the Rollup PR. Let's keep this issue open though.

**Comment by gaearon** [comment] 2017-10-04 01:12
Fixed in 16.

**Closed by gaearon** 2017-10-04 01:12 UTC
