### ISSUE TITLE
React 15: select with value not working with optgroups

### ISSUE THREAD

**Issue by statianzo** [facebook/react#6552] opened 2016-04-20 17:34 UTC
Since upgrading to React 15.0.1, when rendering `<select>` with optgroups, the value is not set on the DOM correctly. The first option will always get picked.

```js
// Renders with "Yes" selected, I expect "Maybe"
  <select value={3}>
    <optgroup label="One">
    <option value={1}>Yes</option>
    </optgroup>
    <optgroup label="Two">
    <option value={2}>No</option>
    </optgroup>
    <optgroup label="Three">
    <option value={3}>Maybe</option>
    </optgroup>
  </select>
```

## Examples

[React 15.0.1 Fiddle (broken)](http://jsbin.com/madesikinu/3/edit?html,js,output)
[React 0.14.7 Fiddle (works)](http://jsbin.com/zofayocijo/1/edit?html,js,output)
[React 15.0.1 without optgroup Fiddle (works)](http://jsbin.com/madesikinu/5/edit?html,js,output)

## Environment
OS X 10.11.4
Safari Version 9.1 (11601.5.17.1)
Chrome Version 49.0.2623.110 (64-bit)
Firefox 45.0.1

_Edit: I also noticed that the same behavior occurs when using `defaultValue`._

**Comment by mshenfield** [comment] 2016-04-20 20:20
[React 15.0.1 with optgroups except around expected option (works)](http://jsbin.com/nihusi/edit?html,js,output)

**Comment by gaearon** [comment] 2016-04-20 20:29
Hi, thanks for reporting. This is a duplicate of https://github.com/facebook/react/issues/6547 and two other issues linked from there. It is fixed in master but this fix hasn't gotten into a release yet. Let's keep this open so people don't file more issues.

**Comment by statianzo** [comment] 2016-04-20 20:33
Great to hear the fix is coming. Thanks, @gaearon!

**Comment by jimfb** [comment] 2016-04-20 22:55
Fixed in https://github.com/facebook/react/pull/6442

@gaearon We generally close out issues when things have been merged into master.  The reason is that otherwise, it's too hard to tell what is still an active item (needs to be fixed) verses things that are already fixed and remain open only to help people find them.  You could read through all the comments, but that takes time (especially if you're going through a bunch of them) and they are often nuanced with regards to remaining action items.  You don't want to read through an hour of comments, only to discover that the whole thing is fixed and no longer relevant.

**Closed by jimfb** 2016-04-20 22:55 UTC
