### ISSUE TITLE
Bug: I am getting a new error in my existing react application stating "TypeError: init is not a function"

### ISSUE THREAD

**Issue by subbu199410** [facebook/react#20210] opened 2020-11-10 05:55 UTC
react-dom.development.js:17662 Uncaught TypeError: init is not a function
    at mountLazyComponent (react-dom.development.js:17662)
    at beginWork (react-dom.development.js:19055)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at scheduleUpdateOnFiber (react-dom.development.js:21881)
    at updateContainer (react-dom.development.js:25482)
    at react-dom.development.js:26021
    at unbatchedUpdates (react-dom.development.js:22431)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020)
    at Object.render (react-dom.development.js:26103)
    at Module.<anonymous> (index.js:22)
    at Module../src/index.js (index.js:27)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Object.1 (store.js:13)
    at __webpack_require__ (bootstrap:856)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
index.js:1 The above error occurred in one of your React components:

    at Lazy
    at Route (http://localhost:3000/static/js/11.chunk.js:81411:29)
    at Switch (http://localhost:3000/static/js/11.chunk.js:81626:29)
    at Suspense
    at Router (http://localhost:3000/static/js/11.chunk.js:81057:30)
    at BrowserRouter (http://localhost:3000/static/js/11.chunk.js:80758:35)
    at App (http://localhost:3000/static/js/main.chunk.js:60:1)
    at ThemeProvider (http://localhost:3000/static/js/11.chunk.js:2679:24)
    at Provider (http://localhost:3000/static/js/11.chunk.js:78103:20)
    at Router (http://localhost:3000/static/js/11.chunk.js:81057:30)
    at BrowserRouter (http://localhost:3000/static/js/11.chunk.js:80758:35)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
react-dom.development.js:23275 Uncaught TypeError: init is not a function
    at mountLazyComponent (react-dom.development.js:17662)
    at beginWork (react-dom.development.js:19055)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at scheduleUpdateOnFiber (react-dom.development.js:21881)
    at updateContainer (react-dom.development.js:25482)
    at react-dom.development.js:26021
    at unbatchedUpdates (react-dom.development.js:22431)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020)
    at Object.render (react-dom.development.js:26103)
    at Module.<anonymous> (index.js:22)
    at Module../src/index.js (index.js:27)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Object.1 (store.js:13)
    at __webpack_require__ (bootstrap:856)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
localhost/:1 Error while trying to use the following icon from the Manifest: http://localhost:3000/favicon.ico (Resource size is not correct - typo in the Manifest?)
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/injectGlobalHook.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/contentScript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

React version:
react:^16.8.6
react-dom:latest
reatc-router-dom:^5.0.1

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by eps1lon** [comment] 2020-11-10 08:07
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2020-11-11 14:30
I'm going to close this because it doesn't have a repro. If you'll share a repro, I'll reopen it. :)

**Closed by bvaughn** 2020-11-11 14:30 UTC
Labels: Resolution: Needs More Information

**Comment by shmoon2917** [comment] 2022-04-07 09:10
I have same problem. did you find a solution?

**Comment by gaearon** [comment] 2022-04-07 12:47
You likely have code like

```js
const Something = React.lazy(SomethingElse)
```

and `SomethingElse` is not a function. `React.lazy` only accepts functions.

**Comment by caseychoiniere** [comment] 2022-05-04 21:40
Another common cause of this is dependency mismatches between `react` and `react-dom`
