### ISSUE TITLE
input type="number" re-formats already valid numbers

### ISSUE THREAD

**Issue by MMeent** [facebook/react#10022] opened 2017-06-21 22:47 UTC
I'd like to report a bug

**What is the current behavior?**
Using input type="number" will shave off any trailing 0s behind the seperator. 

See e.g. https://jsfiddle.net/84v837e9/107/ -- the state starts as being "3.0000", but the number input only shows "3".

**What is the expected behavior?**

The number input should show "3.0000". Or, at least provide a way to specify that toFixed is used with N numbers behind the seperator.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
^15.5.6, 15.6.x (tested in FF 53)

It goes wrong on these lines: https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js#L192-L200

**Comment by gaearon** [comment] 2017-06-22 01:38
cc @aweary

**Comment by aweary** [comment] 2017-06-22 06:50
This appears to be Firefox specific. Firefox will [truncate number values with trailing zeros](https://jsfiddle.net/ps3s5v56/). It also predates those changes made to the input's value, [here's the same issue in 15.4](https://jsfiddle.net/ox4oaqcm/). I suspect this has been an issue for a long time.

Here's a bug report in Bugzilla for this from 3 years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1003896

I have a feeling this isn't something we can work around, though we can look into it.

**Comment by aweary** [comment] 2017-06-23 18:44
cc @nhunzaker can you think of any viable away around this? I can't think of a way that doesn't involve using text inputs, and that's not a reasonable solution.

It's not a regression or an issue with React itself, so without a viable normalization strategy I think we may have to write this off as a Firefox quirk.

**Comment by nhunzaker** [comment] 2017-06-23 23:39
I don't believe there is anything we can do here. It looks like:

1. Extraneous zeroes are lost in the display value (what the user sees)
2. Extraneous zeroes are correctly reported when you access the value property (so `input.value` reports `"3.0000"` even if it doesn't show it
3. Extraneous precision is lost as soon as the user types. Accessing `input.value` at this point returns a truncated string number (`"3"`)

(tested via https://jsfiddle.net/ps3s5v56/8/)

So I don't think we can do anything about this other than to wait for Firefox to make a change. In the meantime, number inputs are really fussy about formatting. I would recommend using a text input for maximum control over the display value.

Either way, I've sent out a PR with a test to cover that this _would_ work otherwise:
https://github.com/facebook/react/pull/10033

**Comment by aweary** [comment] 2017-07-03 17:29
Closing this now that https://github.com/facebook/react/pull/10033 is merged.

**Closed by aweary** 2017-07-03 17:29 UTC
