### ISSUE TITLE
Error: "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by IDrissAitHafid** [facebook/react#19970] opened 2020-10-06 18:13 UTC
Describe what you were doing when the bug occurred:
I couldn't reproduce it.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.2-fed4ae024

Call stack: at getChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18061:32)
    at ProfilingCache.getFlamegraphChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18301:14)
    at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31722:32)
    at vh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11067:7)
    at fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11733:7)
    at ck (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:14430:86)
    at bk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13779:11)
    at ak (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13768:5)
    at Sj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13750:7)
    at Mj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13351:105)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31701:48)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26139:23)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33363:48)
    at ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27172:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27303:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30463:23)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:22538:23)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:23040:27)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28328:23)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33797:21)

**Comment by bvaughn** [comment] 2020-10-06 18:42
This is also a duplicate (#19547) so I'm closing it. Please check before opening an issue :smile:

Also I think it's highly likely that these (this one, #19964, #19965) are all the same root cause– so let's dig into it first.

**Closed by bvaughn** 2020-10-06 18:42 UTC

**Comment by IDrissAitHafid** [comment] 2020-10-06 18:57
Sorry, I have looked it up, but I didn't find it 😅

Yes, they are all related to unfound tree nodes of a certain id.

**Comment by bvaughn** [comment] 2020-10-07 01:56
The duplicate issues I closed today had search matches with the *exact* title 😅 

But thank you for sharing the repro case on the other issue. I'm pretty busy this week but I'm going to try to find some time to dig in! Maybe we'll fix all three at the same time. That would be nice.

**Comment by IDrissAitHafid** [comment] 2020-10-07 02:57
I have added Uncaught to the beginning of the title on the search bar, that's why it didn't come up 😅.

Anyway, I know how to repro this one (#19633)[https://github.com/facebook/react/issues/19633] on my code, but I couldn't figure out a simpler way to reproduce it. And I have just found by inspecting the profiler itself that all three errors are thrown and some other errors, which I will not open issues for them even if some of them are not open 😄, until I can reproduce it using a code sandbox app, then I will share more details on the specified issue.

Please ping me if you start working on it and I shared nothing.

**Comment by bvaughn** [comment] 2020-10-07 12:31
Ok, thanks!
