### ISSUE TITLE
Bug: React Devtools incorrectly updates the setter function of useState hooks

### ISSUE THREAD

**Issue by crimx** [facebook/react#19114] opened 2020-06-10 19:07 UTC
From the docs:

> React guarantees that setState function identity is stable and won’t change on re-renders. This is why it’s safe to omit from the useEffect or useCallback dependency list.

When React Devtools is opened, new `setState` is created on each rendering, which could lead to inconsistencies.

React version: 16.13.1

## Steps To Reproduce

1. Open the [codesandbox](https://codesandbox.io/s/react-devtools-suspense-bug-hqwuq?file=/src/App.js).
2. Click the "Open in new window" button beside the codesandbox browser url.
3. On the new page which is running the code, open the React Devtools `Component` tab.
4. Click on the `App` Component.
5. Refresh the page and click the button "Component updates xx times".
6. Nothing is updated.
7. Close devtools, refresh, click the button again, update works fine.

```jsx
// This component is created solely for
// pointing out the bug
function App() {
  const updateCountRef = useRef(0)
  updateCountRef.current++

  const [state, setState] = useState('A');

  const cbRef = useRef()
  cbRef.current = () => {
    setState(c => String.fromCharCode(c.charCodeAt(0) + 1))
  }

  const handler = () => cbRef.current()

  return (
    <div className="App">
      <button onClick={handler}>
        Component updates {updateCountRef.current} times
      </button>
      <p>Current state value: {state}</p>
    </div>
  )
}
```

Link to code example:

<https://codesandbox.io/s/react-devtools-suspense-bug-hqwuq?file=/src/App.js>

## The current behavior

- Component does not update when React Devtools is opened.
- New `setState` is created on each rendering.

## The expected behavior

- Component should update on each click.
- There should be only one `setState`.

**Comment by eps1lon** [comment] 2020-08-20 12:59
While I can certainly reproduce your specific issue it is also code that is unsafe in concurrent mode since you're triggering side-effects in render. Once you switch to 

```js
React.useEffect(() => {
  cbRef.current = () => {
    setState((c) => String.fromCharCode(c.charCodeAt(0) + 1));
  };
}, []);
```
devtools is no longer interfering.

Do you have a use case that isn't triggering side-effects during render? Adding the original use case would help the maintainers decide if this is an issue worth working on.

**Comment by crimx** [comment] 2020-08-20 16:28
Hi, can you elaborate on why it is considered side-effect? AFAIK it's just a variable assignment to the ref.

```js
cbRef.current = () => {
  setState(c => String.fromCharCode(c.charCodeAt(0) + 1))
}
```

The original use case is from [`useSubscription`](https://github.com/crimx/observable-hooks/blob/master/packages/observable-hooks/src/internal/use-subscription-internal.ts) in observable-hooks. It has a signature of `useSubscription(stream$, next, error, complete)`, where the `stream$` is an observable, and the rest are observer callback functions.

Under the hood `useSubscription` uses a ref object to keep the latest callbacks so that users don't have to worry about closure staleness and can reference any variable directly in the callbacks like in `useEffect`. This should be safe in concurrent mode but correct me if I am wrong.

In [useObservableSuspense](https://github.com/crimx/observable-hooks/blob/16fc97c1058eefffe6c0f7cd646ce8995e2e8de6/packages/observable-hooks/src/use-observable-suspense.ts), usage like this causes the issue:

```js
const [state, setState] = useState(0)

useSubscription(stream$, value => {
  setState(0)
})
```

Currently I fixed this by keeping the initial `setState`.

```js
const [state, _setState] = useState(0)
const setState = useRef(_setState).current

useSubscription(stream$, value => {
  setState(0)
})
```

**Comment by gaearon** [comment] 2020-08-20 17:05
>AFAIK it's just a variable assignment to the ref.

It's a mutation in render, which makes it impure. That can cause issues if a render doesn't end up getting committed to the screen. (However, in this particular case it doesn't seem like it would matter since you're not using any props/state in the closure.)

**Comment by crimx** [comment] 2020-08-20 17:44
Oh! I see it now. I'll try updating the callbacks after render phase and see if it works. Thanks for the hints.

**Comment by gaearon** [comment] 2020-08-20 17:51
I don't actually understand why the state update is ignored though. I'm confused by this.

**Comment by crimx** [comment] 2020-08-21 05:36
One more question regarding concurrent mode. Is it safe/recommended to use layout effects for this purpose?

```js
useIsomorphicLayoutEffect(() => {
  argsRef.current = args
})
```

Adding this works with React Devtools and passes all my current tests. I am also using the `Scheduler` mock for [testing tearing](https://github.com/crimx/observable-hooks/blob/3933a21f048b164a9bca6b24315d53affaaa7f48/packages/observable-hooks/__tests__/concurrent-mode.spec.tsx#L30-L107). How can I stop a render being committed? So that I can test correctness of the callbacks in ref.

**Comment by crimx** [comment] 2020-08-21 05:57
I mean since the layout effects run synchronously, with the Scheduler mock I am not able to find a way to break the jobs right before them.

**Comment by omarsy** [comment] 2020-09-24 21:06
Can I push a PR?

**Comment by bvaughn** [comment] 2020-10-14 14:24
The only case when mutating a ref during render is safe is [the lazy-initialization case](https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily) shown in the docs.

The "bug" being reported here seems to be caused by an unsafe mutation during render. From what I can tell, there is no other bug here. (Is that right? Am I overlooking something?)

> It's a mutation in render, which makes it impure. That can cause issues if a render doesn't end up getting committed to the screen. (However, in this particular case it doesn't seem like it would matter since you're not using any props/state in the closure.)

Regarding this use case:
```js
cbRef.current = () => {
  setState(c => String.fromCharCode(c.charCodeAt(0) + 1))
}
```

While the above code isn't recommended, I also don't see where it would cause a problem. (Indeed, testing it myself– it doesn't seem to).

> One more question regarding concurrent mode. Is it safe/recommended to use layout effects for this purpose?
>
> useIsomorphicLayoutEffect(() => {
>   argsRef.current = args
> })

You could use an effect or a layout effect. Our [docs example](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state) uses an effect.

I'm going to close this issue because I don't think there's anything wrong here. Please let me know if I've misread or misunderstood something though and I can take another look.

**Closed by bvaughn** 2020-10-14 14:24 UTC
Labels: Component: Reconciler, Type: Bug, Type: Needs Investigation
