### ISSUE TITLE
Bug: React Hooks eslint plugin reports i should add dependencies to useEffect which break my functionality

### ISSUE THREAD

**Issue by Markos-Th09** [facebook/react#23179] opened 2022-01-25 11:56 UTC
React version: 17.0.2(latest)

## Steps To Reproduce

1. Create a new react app (i use typescript but it not required)
2. Create a file with those custom hooks
```ts
import React, { useEffect, useState } from "react"

export const useLocalStorage=<S extends { toString: () => string }>(key: string,initialState?: S | (() => S)):[S, React.Dispatch<React.SetStateAction<S>>] =>{
        const [state, _setState] = useState<S>(initialState as S)

    useEffect(() => {
        const item = localStorage.getItem(key)
        if (item) _setState(typeof state === "string" ? item : JSON.parse(item))
    }, [])

    useEffect(() => {
        localStorage.setItem(key, state.toString())
    },[state])

    const setState:React.Dispatch<React.SetStateAction<S>> = (value) => {
        _setState(value)
    }

    return [state,setState]
}
```

Link to code example: https://codesandbox.io/s/silly-browser-nws03?file=/src/useStorage.ts

## The current behavior
All the useEffects have warnings from eslint-plugin-react-hooks.
On the first useEffect: 
```
React Hook useEffect has missing dependencies: 'key' and 'state'. Either include them or remove the dependency array. You can also do a functional update '_setState(s => ...)' if you only need 'state' in the '_setState' call
```
The desired action is to set the state to the value stored in localStorage (I use useEffect to make it ssr friendly). Also the key is never going to change anyway.

On the second useEffect: 
```
React Hook useEffect has a missing dependency: 'key'. Either include it or remove the dependency array
```
This doesn't break anything but it is unnecessary because the key is just never going to change. 

## The expected behavior
I shouldn't warn for this cases.

**Comment by eps1lon** [comment] 2022-01-25 12:47
> This doesn't break anything but it is unnecessary because the key is just never going to change.

The problem is that a lint rule will never be able to know this. If you know that it doesn't change, then you can safely add it to the dependencies while also ensuring your hook continues to work if it ever changes.

For the first example: It's unclear why you think `state` should not be a dependency. What do you think should happen if `state` does change during the lifetime of the hook?

**Comment by Markos-Th09** [comment] 2022-01-26 07:25
> > This doesn't break anything but it is unnecessary because the key is just never going to change.
> 
> The problem is that a lint rule will never be able to know this. If you know that it doesn't change, then you can safely add it to the dependencies while also ensuring your hook continues to work if it ever changes.
> 
> For the first example: It's unclear why you think `state` should not be a dependency. What do you think should happen if `state` does change during the lifetime of the hook?
> 
> 
> 
> 

When the state changes it the value stored in localStorage should also be updated

**Comment by Markos-Th09** [comment] 2022-01-26 07:26
When the state changes its value in localStorage should also change

**Comment by Markos-Th09** [comment] 2022-01-26 07:31
Because the state is set to the value contained in the localStorage. That should only happen one time.

**Comment by eps1lon** [comment] 2022-04-29 15:10
Closing since this is out of scope for a lint rule. Either disable the rule for a particular effect if you don't want it to re-fire when certain dependencies change, or include it even if you think it'll never change.

**Closed by eps1lon** 2022-04-29 15:10 UTC
Labels: Status: Unconfirmed, Component: ESLint Rules

**Comment by Markos-Th09** [comment] 2022-04-29 17:13
> Disabling the rule is pretty much always the wrong solution. Including the dependencies that "never change" is fine.

I understand that Dan. Although I remember if I added it to one of them it kinda broke

**Comment by ravenkim** [comment] 2024-06-14 00:19
what about make some rule for some words that user add like 
 eslint-disable-missing-dependency: ['state', 'dispatch']

**Comment by ravenkim** [comment] 2024-06-14 00:19
what about make some rule for some words that user add like
eslint-disable-missing-dependency: ['state', 'dispatch']
