### ISSUE TITLE
UNSAFE_componentWillUpdate doesn't triggers in test 

### ISSUE THREAD

**Issue by deepakaggarwal7** [facebook/react#17388] opened 2019-11-17 04:35 UTC
I'm using a Swiper which invokes props.onIndexChange when a swipe takes place or its `ScrollTo(index)` is called. Internally, scrollTo scrolls the ScrollView and updates component's state which further calls `UNSAFE_componentWillUpdate` and inside this` props.onIndexChange` gets called. 

I wrapped this swiper along with a button in a component

```
const SwiperWithButton = props => (
  <View>
     <Swiper ref={c=>{this.swiper=c} onIndexChange={()=>console.log('changed')}>...</Swiper>
     <Button onPress={()=>{this.swiper.scrollTo(2)/>
)
```
When I run this in emulator, everything works. When I hit the button, swiper slides, lifecycle gets called which triggers onIndexChange and I see the log.

I wanted to test this component using renderer. However, when I fire button's press event, `onIndexChange` isn't invoked. Is it because that it is triggered from inside a lifecycle event? Is there still a way to make it work?

**Comment by threepointone** [comment] 2019-11-18 16:00
Please make a minimal reproducing usecase. Since this is a test, I'd recommend sharing it as a git repo.

**Comment by bvaughn** [comment] 2019-11-26 19:46
Closing due to lack of a response. We can re-open later if we get repro steps.

**Closed by bvaughn** 2019-11-26 19:46 UTC
Labels: Resolution: Needs More Information
