### ISSUE TITLE
onChange firing on a td element when there's checkbox element inside it

### ISSUE THREAD

**Issue by m4n3z40** [facebook/react#7157] opened 2016-06-30 19:32 UTC
I don't think this is the expected behavior, so I'll be reporting this as a bug.

I'm creating a data table component for one of my projects, and in this component I decided to implement extensions to the table as different types of columns, but when I was creating a 'CheckableTableColumn' to extend the regular column to support 'toggle' actions (just putting a checkbox inside it) I ran into this strange behavior where when I try to attach a onChange handler to the checkbox from an upper-in-the-tree component, the event was firing twice. 

Looking into it, I found out that the onChange event in the checkbox (that React translates to a onclick event) was bubbling up to the td component that contains the checkbox (which for simplicity was just spreading the passed props to it).

I managed to reproduce this behavior in the following bin: http://jsbin.com/fakasoqino/edit?js,console,output (to reproduce it, just click on one of the checkboxes on in the table)

I do not know why the td element is attaching the onChange handler, but I think it should not do it, should it?

I've had the same problem in the latest stable chrome, firefox and opera. 

The React version that I'm currently using is the latest one (v15.1.0).

Thank you all in advance.

**Comment by karczk** [comment] 2016-07-01 14:05
> I do not know why the td element is attaching the onChange handler, but I think it should not do it, should it?

It should, because you passed onChange to td.

`<TableColumn {...props}>`
This code is equivalent to:

`<TableColumn value={this.props.value} onChange={this.props.onChange} etc >`
onChange is implicitly transferred by spread operator (...), so maybe you didn't notice that. Set attributes explicitly or write sth like that:

```
var { onChange, ...other } = props;
    return (
        <TableColumn {...other}>
```

**Comment by syranide** [comment] 2016-07-01 14:31
`onChange` bubbling is intentional (but IMHO weird). Other than that, @karczk is correct and even more so you should **not** rely on components silently dropping unknown properties, it may change in the future.

**Comment by m4n3z40** [comment] 2016-07-02 12:03
I think I failed at expressing the point of the issue, the code is a little misleading, I agree.

@karczk I did know that, and that IS intentional, because I need ```CheckableTableColumn``` to pass down all props for the regular ```TableColumn``` to know what to render with it. What I think is weird, is a ```TD``` element firing a ```onChange``` event, which is not consistent or intuitive at all, because of the ```TD``` element not being editable, meaning it cannot receive user's input (with the exception of ```onClick``` events). 

@syranide I agree with you, when dealing with 3rd party components we should not rely on that, but when the core lib documentation does not tell you a ```TD``` or a ```DIV``` for that matter, can fire a ```onChange``` after a click has fired by one of it's children then assuming that won't happen is an honest mistake.

In fact, as you will see in the following bin: http://jsbin.com/ralaviwade/edit?js,console,output
The ```onChange``` event will not fire, which I think it's right.
Even when adding an element with a ```onClick``` event handler inside it: http://jsbin.com/riqukanumi/1/edit?js,console,output

I really think this is inconsistent, not desirable behavior and should be flagged as a bug. 
And if that happens, I'll be glad to try to fix that and attach a PR to this issue.

**Comment by m4n3z40** [comment] 2016-07-02 12:21
Simpler reproduction of the issue: http://jsbin.com/sasecojoke/edit?js,console,output

**Comment by syranide** [comment] 2016-07-02 13:02
> I agree with you, when dealing with 3rd party components we should not rely on that

You should never rely on it, React in the future or other frontends may render all properties without a whitelist.

> In fact, as you will see in the following bin: http://jsbin.com/ralaviwade/edit?js,console,output
The onChange event will not fire, which I think it's right.

Of course `onChange` won't fire for a click event.

> Simpler reproduction of the issue: http://jsbin.com/sasecojoke/edit?js,console,output

I personally think it is a bad feature, but some actively rely on it and there are tangential discussions surrounding it. So it's not a bug.

**Comment by m4n3z40** [comment] 2016-07-02 13:25
> You should never rely on it, React may in the future (or other frontends) render all properties without a whitelist. So it's never a good idea to rely on it ignoring unsupported properties.

I understand your point. And it is fairly good one. Will keep that in mind for now on. Thanks!

> Of course onChange won't fire for a click event.

The ```onChange``` in a checkbox element is translated to a ```onClick``` by React, that makes it not so obvious, does it?

> I personally think it is a bad feature, but some actively rely on it and there are tangential discussions surrounding it. So it's not a bug.

Feature? Who relies on a non-editable element firing a ```onChange```, could you please provide use cases for this?

**Comment by syranide** [comment] 2016-07-02 14:07
> The onChange in a checkbox element is translated to a onClick by React, that makes it not so obvious, does it?

Huh, there is no checkbox in that source, it's just a td with "click me".

> Feature? Who relies on a non-editable element firing a onChange, could you please provide use cases for this?

I don't agree with it, but a bunch of people with large number of inputs (building forms) seem to prefer to have one centralized handler for them all and have made themselves heard when various changes have been made that will/have affected them.

Again, personally, I think it's a bad idea for all kinds of reasons, but some people rely on it so it's necessary to have a larger discussion around it and not just outright drop it.

**Comment by m4n3z40** [comment] 2016-07-02 18:33
> Huh, there is no checkbox in that source, it's just a td with "click me".

I think you're missing the point. How this

```js
<td onChange={evt => console.log('Fired from TD')}>
   <span onClick={() => {}}>Click me</span>
</td>
```
behaving differently than this:

```js
<td onChange={evt => console.log('Fired from TD')}>
    <input type="checkbox" onChange={() => {}} />
</td>
```

is consistent? knowing they're are essencially the same code. (Again, knowing how React translate onchange to onclick in checkable elements)

>  don't agree with it, but a bunch of people with large number of inputs (building forms) seem to prefer to have one centralized handler for them all and have made themselves heard when various changes have been made that will/have affected them.

Didn't even know that was possible, but I can see where that can be somewhat useful. And still, this "feature" is not documented anywhere, so I'm assuming this is the same case of the component's ```context``` object in React's older versions. I'm curious to know now how many of these hidden "features" are the in the depths of React.

Thanks for the enlightenment @syranide, That was really helpful.

**Comment by selvagsz** [comment] 2016-07-04 08:13
> What I think is weird, is a TD element firing a onChange event, which is not consistent or intuitive at all, because of the TD element not being editable, meaning it cannot receive user's input (with the exception of onClick events).

@m4n3z40 `onChange` is bubbling up the DOM & it is not triggered by the `td` itself. Input elements triggers both the `click` & `change` events. (http://jsbin.com/tosuro/7/edit?html,js,console,output)

**Closed** 2017-10-02 15:05 UTC
