### ISSUE TITLE
Bug:在联通4g或wifi网络环境下,引用在线cdn报错

### ISSUE THREAD

**Issue by wangjia0525** [facebook/react#22869] opened 2021-12-05 13:24 UTC
<script crossorigin src="https://unpkg.com/react@17.0.2/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js"></script>
引用这两个资源在联通4g或wifi网络环境下,引用react和react-dom报错

<img width="779" alt="023059F6-585C-47D0-A095-072A6829C4C5" src="https://user-images.githubusercontent.com/29113575/144748521-465243b7-4895-48a0-a377-6e055f4c301e.png">

**Comment by wangjia0525** [comment] 2021-12-05 13:27
<img width="779" alt="023059F6-585C-47D0-A095-072A6829C4C5" src="https://user-images.githubusercontent.com/29113575/144748453-2ffc2681-5912-494d-8c37-8472e8d46c8a.png">

**Comment by wangjia0525** [comment] 2021-12-05 13:28
<img width="779" alt="023059F6-585C-47D0-A095-072A6829C4C5" src="https://user-images.githubusercontent.com/29113575/144748532-fefc84f5-c484-406d-a97e-8ba754674caf.png">

**Comment by 1999onL799** [comment] 2021-12-05 15:19
冤有頭債有主，施主，何必呢？

**Comment by lixiaofeng666** [comment] 2021-12-06 02:15
你是来搞笑的吗...

**Comment by bigbigDreamer** [comment] 2021-12-06 11:48
Invalid issue,Can be closed. @bvaughn 
@wangjia0525 @1999onL799 @lixiaofeng666  但行好事，莫问前程。hhh

**Comment by bvaughn** [comment] 2021-12-06 14:36
There isn't enough information on this issue for us to help. Seems like you're reporting that you're unable to load files from unpkg.com, but that's not something we can help with.

**Comment by bvaughn** [comment] 2021-12-07 18:32
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-12-07 18:32 UTC
Labels: Status: Unconfirmed, Resolution: Needs More Information

**Comment by fengsx** [comment] 2022-04-06 06:17
@wangjia0525 大陆可以使用  staticfile.org 或者其他公共 cdn 提供商
