### ISSUE TITLE
after upgarding to 16.8.2 - Getting error TypeError: Cannot set property 'props' of undefined PureComponent node_modules/react/cjs/react.development.js:394

### ISSUE THREAD

**Issue by hardikb08** [facebook/react#14911] opened 2019-02-21 07:45 UTC
Pls find screenshot for more [details](url
<img width="1280" alt="screen shot 2019-02-21 at 12 24 41 pm" src="https://user-images.githubusercontent.com/45588444/53152091-b3f79280-35da-11e9-99dc-658940473d5f.png">
)

Package.json

"@babel/core": "7.1.6",
    "@svgr/webpack": "2.4.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "9.0.0",
    "babel-jest": "23.6.0",
    "babel-loader": "8.0.4",
    "babel-plugin-named-asset-import": "^0.3.1",
    "babel-preset-react-app": "^7.0.1",
    "bfj": "6.1.1",
    "bootstrap-daterangepicker": "^3.0.3",
    "case-sensitive-paths-webpack-plugin": "2.1.2",
    "chalk": "2.4.1",
    "connected-react-router": "^6.3.1",
    "css-loader": "1.0.0",
    "dotenv": "6.0.0",
    "dotenv-expand": "4.2.0",
    "eslint": "^5.14.0",
    "eslint-config-react-app": "^3.0.7",
    "eslint-loader": "2.1.1",
    "eslint-plugin-flowtype": "2.50.1",
    "eslint-plugin-import": "2.14.0",
    "eslint-plugin-jsx-a11y": "6.1.2",
    "eslint-plugin-react": "7.11.1",
    "exceljs": "^1.7.0",
    "file-loader": "2.0.0",
    "file-saver": "^2.0.1",
    "fork-ts-checker-webpack-plugin-alt": "0.4.14",
    "fs-extra": "7.0.0",
    "history": "^4.7.2",
    "html-webpack-plugin": "4.0.0-alpha.2",
    "identity-obj-proxy": "3.0.0",
    "immutable": "^4.0.0-rc.12",
    "jest": "23.6.0",
    "jest-pnp-resolver": "1.0.1",
    "jest-resolve": "23.6.0",
    "jquery": "^3.3.1",
    "jquery-param": "^1.0.1",
    "mini-css-extract-plugin": "0.4.3",
    "moment": "^2.24.0",
    "normalize.css": "^8.0.1",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "pnp-webpack-plugin": "1.1.0",
    "postcss-flexbugs-fixes": "4.1.0",
    "postcss-loader": "3.0.0",
    "postcss-preset-env": "6.3.1",
    "postcss-pxtorem": "^4.0.1",
    "postcss-safe-parser": "4.0.1",
    "prop-types": "^15.7.2",
    "query-string": "^6.2.0",
    "react": "^16.8.2",
    "react-app-polyfill": "^0.2.1",
    "react-bootstrap": "^0.32.4",
    "react-bootstrap-daterangepicker": "^4.1.0",
    "react-dev-utils": "^7.0.3",
    "react-dom": "^16.8.2",
    "react-dropzone": "^8.1.0",
    "react-infinite-scroller": "^1.2.4",
    "react-redux": "^6.0.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-slick": "^0.23.2",
    "react-toastify": "^4.5.2",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.4",
    "redux-define": "^1.1.1",
    "redux-form": "^8.1.0",
    "redux-immutable": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-starter-kit": "^0.3.3",
    "redux-thunk": "^2.3.0",
    "resolve": "1.8.1",
    "sass-loader": "7.1.0",
    "style-loader": "0.23.0",
    "styled-components": "^4.1.3",
    "terser-webpack-plugin": "1.1.0",
    "url-loader": "1.1.1",
    "webpack": "4.19.1",
    "webpack-dev-server": "^3.1.14",
    "webpack-manifest-plugin": "2.0.4",
    "whatwg-fetch": "^3.0.0",
    "workbox-webpack-plugin": "3.6.3",
    "xlsx": "^0.14.1"

**Comment by Finesse** [comment] 2019-02-21 08:13
This is a `react-redux` issue, not a `redux` issue. And `this` is available only in class components, not function components.

**Comment by hardikb08** [comment] 2019-02-21 09:18
understood

**Comment by threepointone** [comment] 2019-02-21 13:09
can't say much without a reproducible demo, please use codesandbox or something similar to share a small version of this failure. at a glance, this looks like an issue with react-redux, but I can't comment more without seeing a working demo. I'd recommend you post this issue at https://github.com/reduxjs/react-redux/issues instead

**Comment by JustJacqui** [comment] 2019-05-12 06:21
I am having the same issue. 

I use c9 and then generate the default react app using 
npx create-react-app nameofapp

My node and npm versions are up-to-date and I change nothing in the code. I just run it from what is generated.

Bad timing as I need this for an assignment and don't know enough to make one from scratch :(

**Comment by NeilHaff** [comment] 2019-08-16 14:13
I put a typo style error in a class based component such as-
class App extends Component () {
instead it should obviously be- 
class App extends Component  {
Which causes this error.

**Comment by threepointone** [comment] 2019-09-04 10:03
I'm going to close this issue, but I'd be happy to reopen if someone can provide a reproducing example on codesandbox, or as a git repo.

**Closed by threepointone** 2019-09-04 10:03 UTC
Labels: Resolution: Needs More Information

**Comment by kt995** [comment] 2020-04-04 01:35
> I put a typo style error in a class based component such as-
> class App extends Component () {
> instead it should obviously be-
> class App extends Component {
> Which causes this error.

@NeilHaff omg you're the best, this is such a dumb error but I couldn't figure it out thank you! :)
