### ISSUE TITLE
MouseEnter event bubbling happens in reverse order?

### ISSUE THREAD

**Issue by vbarbarosh** [facebook/react#5739] opened 2015-12-28 08:52 UTC
I expect **mouseenter** event will bubble from very top element down to very bottom, the same way **onclick** event does. Contrary it is bubbles from very bottom element to the very top element.

In Chrome, FF, IE10, and IE11 native **mouseenter** bubbling works as expected (from top to bottom)... Also **mouseover** bubbles from top to bottom, as expected, either in native or in React.

https://jsfiddle.net/69z2wepo/25483/

**Comment by gaearon** [comment] 2018-01-05 21:21
Tagging as good first issue. I don't know if it's a bug: you'd need to investigate what happens and whether it's still reproducible with React 16.

**Comment by gaearon** [comment] 2018-01-05 21:23
It does seem to still repro in 16: https://jsfiddle.net/bwmreymj/.

So the question is whether it's a bug or not. I don't know :-) If you have questions on this issue please post them here!

**Comment by brandonrninefive** [comment] 2018-01-06 01:44
Hello, I'd love to make this my first contribution! I'll begin looking into this ASAP.

**Comment by gaearon** [comment] 2018-01-06 02:33
Sounds great!

**Comment by brandonrninefive** [comment] 2018-01-11 04:13
After some digging, I believe that I've isolated the issue to the following for loop:

https://github.com/facebook/react/blob/6c1fba539adbc3088c425a4d832bb8c4132e7b31/packages/shared/ReactTreeTraversal.js#L143

Since the loop is from the end of the array to the beginning, it causes the onMouseEnter events to fire in the reverse order than expected. I'm not sure if this was intentional or not. Since this is my first contribution, I'm also not sure if changing this code would have any unintended side effects. If it turns out that this is unintentional, and there wouldn't be any negative side effects, I will gladly submit a PR to fix it!

**Comment by caleblogan** [comment] 2018-01-25 04:55
This seems to be the intended function according to the docs: https://reactjs.org/docs/events.html#mouse-events.

> The onMouseEnter and onMouseLeave events propagate from the element being left to the one being entered instead of ordinary bubbling and do not have a capture phase.

The event bubbles up to closest ancestor (not inclusive) then back down to the the entering node. I don't know enough about the code base to have an opinion on whether it should be changed though.

**Comment by gaearon** [comment] 2018-08-18 01:49
Indeed, the docs indicate it's the expected behavior. I don't know for sure what's the historical context behind this but I guess it was done because it maps more intuitively to how engineers tend to use these events. If you disagree with the rationale please file a new issue with your change proposal — but I'll close this because it doesn't seem to be a bug.

**Closed by gaearon** 2018-08-18 01:49 UTC
Labels: Component: DOM, Difficulty: medium, Type: Bug, good first issue (taken)

**Comment by TotooriaHyperion** [comment] 2019-04-10 08:10
I don't think e3 -> e2 -> e1 is expected.

Because e3 is child of e2 and e2 is child of e1, thus you must enter e1 to enter e2, enter e2 to enter e3.
e1 -> e2 -> e3 should be the expected behavior. Mouseenter and Mouseout event don't bubble, and since browser find the element from the current pointer position, and then process the whole event cycle. So it's clearly that the mouseenter's mechanism is designed to trigger from ancestor to descendent. See the [specs](https://w3c.github.io/uievents/#event-type-mouseenter).

Because e1 has a mouseenter listener, so when pointer enter into e3, e1 should be triggered immediately. Imagine if your e3 is position absolute and be positioned out of e1's space, in this case, mouseenter on e1 should also be triggered.

But mouseover is a normal bubbling event, so the e3's mouseover would bubble to e2 and e1.

So the answer is: mouseenter/mouseout should never bubbles, they just trigger different event in an order that from ancestor to descendent.
