### ISSUE TITLE
DevTools: showing wrong state

### ISSUE THREAD

**Issue by Kogoruhn** [facebook/react#16843] opened 2019-09-20 13:24 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Visual bug: showing wrong state; so user cant use devtools for debugging

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/wizardly-lewin-dlw5k
https://dlw5k.csb.app/

1) Open https://dlw5k.csb.app/
2) Open browser dev tools
3) select "Components", click on "App", expand `selectedPairs` of `State`
4) select 3+ currencies from the list on the page. State is proper for now
5) uncheck any not last box. 
Devtools will remove the last from the list.
Uncheck something once more, and again just last item will disappear.

6) Click on 'bug' icon ("Log this component data to the console") 
Expand data, 'State' is ok. So just a visual bug?

**What is the expected behavior?**

Devtools should update State properly.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React Developer Tools: 4.1.0 (9/19/2019)
Browser: Google Chrome 76.0.3809.132 (64bit)
OS: Windows 7 Professional SP1 64bit

**Comment by roman-tiukh** [comment] 2019-09-20 13:52
+

**Comment by hristo-kanchev** [comment] 2019-09-20 16:39
Found the issue. Currently about to open a PR with thee hotfix. @bvaughn expect something in 10-15 minutes.

**Comment by hristo-kanchev** [comment] 2019-09-21 15:01
I closed the PR that I submitted yesterday. 
Unfortunately it didn't fully fix the issue.

I won't be able to work on this this weekend sadly 😭 

Anyone want to help out?

You can see the comments that @bvaughn made that fully describes the problem we are having.

**Comment by bvaughn** [comment] 2019-09-21 17:32
Good chance I'll look into this myself sometime early next week.

**Comment by EddyHamzich** [comment] 2019-09-23 13:58
I'm also having an issue where I have a button with a onClick state (boolean true/false). Whenever I click it, with the React Dev Tools opened, it does NOT update the state IN DevTools (but it still WORKS inside the web-app) I have to click on a different component (in DevTools) and then back to the component with the state to actually see it update the state (in DevTools)... In previous version of DevTools (the one without the blue theme) it would update immediately...

**Comment by mark-quinn** [comment] 2019-09-23 15:05
^ same as [issue#16840](https://github.com/facebook/react/issues/16840)

**Comment by Kogoruhn** [comment] 2019-09-23 16:00
@EddyHamzich Yep, noticed the same issue today.

**Comment by bvaughn** [comment] 2019-09-23 16:07
Hey everyone :wave: We know about this issue, and we know the cause (see my messages on #16859). Please just give us a bit of time to fix it :smile:

**Comment by EddyHamzich** [comment] 2019-09-23 16:07
@mark-quinn it is not the same issue... The other one is about DevTools being blank... let's not mix two seperate issues...

**Comment by saipopcornapps** [comment] 2019-09-25 06:04
@bvaughn And we also need back the button to toggle the state variable to true/false. Is there a way we can switch back to the older version of react dev tools

**Comment by vicmpen** [comment] 2019-09-25 08:53
FWIW, printing out the state of the component, via the button in the devtools, will spit out the correct state at the time.

**Comment by bvaughn** [comment] 2019-09-25 16:24
@saipopcornapps You can toggle the variables to true/false by typing "true" or "false". The inputs accept any valid JSON values now. This enables the data type to be changed for props that could be of more than one type, or that have `undefined` initial values.

If you really want the old DevTools back, the release blog explains how to install them. This is not something I Would recommend though.
https://reactjs.org/blog/2019/08/15/new-react-devtools.html#how-do-i-get-the-old-version-back

**Comment by bvaughn** [comment] 2019-09-25 17:46
This issue will be fixed in the next release (probably sometime today)

**Closed** 2019-09-25 17:46 UTC
Labels: Component: Developer Tools, Type: Bug

**Comment by bvaughn** [comment] 2019-09-26 17:51
This fix has just been published to NPM and posted to Chrome/Firefox as v4.1.1

**Comment by iraqwarvet31** [comment] 2020-04-29 17:53
> This fix has just been published to NPM and posted to Chrome/Firefox as v4.1.1

Can you please provide the link for the fix? Still experiencing this issue.

**Comment by hasanfd** [comment] 2020-06-09 12:12
This issue is still reproducible with version 4.7.0 on Chrome

**Comment by bvaughn** [comment] 2020-06-10 01:45
File a new issue **with a repro case**.
