### ISSUE TITLE
BUG: JSX allow tag use `class` property

### ISSUE THREAD

**Issue by soulteary** [facebook/react#5964] opened 2016-02-02 10:51 UTC
![image](https://cloud.githubusercontent.com/assets/1500781/12747238/ce6c4762-c9dd-11e5-8820-6e9bb5fcc173.png)

Node ver: 5.0.0

Babel Deps:

-     "babel-cli": "^6.4.0",
-     "babel-core": "^6.3.26",
-     "babel-eslint": "^5.0.0-beta6",
-     "babel-loader": "^6.2.0",
-     "babel-plugin-add-module-exports": "^0.1.2",
-     "babel-polyfill": "^6.3.14",
-     "babel-preset-es2015": "^6.3.13",
-     "babel-preset-react": "^6.3.13",
-     "babel-preset-react-hmre": "^1.0.1",
-     "babel-preset-stage-0": "^6.3.13"

It seems cause by custom html tag.

**Comment by jimfb** [comment] 2016-02-02 10:53
Not a bug, duplicate of https://github.com/facebook/react/issues/4933

**Closed by jimfb** 2016-02-02 10:53 UTC

**Comment by soulteary** [comment] 2016-02-02 10:57
@jimfb thx
