### ISSUE TITLE
onChange doesn't work on IE for type=range

### ISSUE THREAD

**Issue by kud** [facebook/react#3096] opened 2015-02-09 17:32 UTC
I don't know yet if I'm a newbie or it is a bug but `onChange` event on `<input type="range">` doesn't work on IE (even 11).

Here an example of my code:

```javascript
<input onChange={this.changeVolume} onMouseUp={this.changeVolume} ref="volumeSlider"  type="range" min={0} max={1} step={.1} value={this.state.volume} title="Sound" />
```

Yes, I use `onMouseUp` as crap patch.

**Comment by kud** [comment] 2015-02-09 17:34
I've tried with integer instead of float, it did the same. In fact, onChange never fires on IE.

**Comment by petehunt** [comment] 2015-02-09 17:38
Can you confirm that this fiddle is broken? http://jsfiddle.net/sua850oc/

**Comment by lionelB** [comment] 2015-02-09 19:25
Hi,
it's broken on windows 7 for IE 11 (also IE10 using ie devtools)
working on latest FF  and chrome

**Comment by zpao** [comment] 2015-02-09 19:35
@syranide, any interest in taking this on? I think we probably might just need to handle a different event for ranges (like we use clicks for checkboxes)

**Comment by kud** [comment] 2015-02-09 21:55
![test](https://cloud.githubusercontent.com/assets/655838/6116626/a885c2f6-b0ae-11e4-9e05-0b8a034185c0.gif)

Windows 7, Internet Explorer 11

**Comment by kud** [comment] 2015-02-09 21:56
Oh and `onClick` or `onMouseUp` work well. But it's not updated on every step. It's updated at the end of the user's choice.

**Comment by syranide** [comment] 2015-02-09 23:43
@zpao I haven't really done much *actual* event normalization so this feels somewhat alien to me, I believe @spicyj made the amazing `onChange` implementation for `inputs`?

**Comment by spicyj** [comment] 2015-02-11 19:58
@kud Can you try a native `input` event listener?

**Comment by jquense** [comment] 2015-02-11 20:27
I just checked in IE11 and the native change event fires just fine, But the react onChange does not seem too...

input doesn't fire at all

http://jsfiddle.net/sua850oc/7/

**Comment by jquense** [comment] 2015-02-11 20:57
@spicyj It seems that the input event does not fire for range types in IE, which is what react is trying to use, The issue seems to be the this check fails in ie but not chrome/ff. Not sure how ya'll do checks like this, but you could change:
https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/browser/eventPlugins/ChangeEventPlugin.js#L60

it include a `(elem.nodeName === 'INPUT' && elem.type === 'range' && isIE)` sort of check to make sure it uses change event

**Comment by rickbeerendonk** [comment] 2015-02-12 14:32
All browsers behave different and React is not behaving like one of the browsers.

 | IE 11 | Chrome 40 | Firefox 34 | React 12.2 in IE 11 | React 12.2 in Chrome 40 | React 12.2 in Firefox 34
--- | --- | --- | --- | --- | --- | ---
drag | onchange (once per step) | oninput (once per step) | oninput (once per step) | | oninput + onchange (once per step) | oninput + onchange (once per mouse move)
drag end | | onchange | onchange | | | 
key left/right/up/down | onchange | oninput + onchange | oninput | | oninput + onchange | oninput + onchange

CodePen: http://codepen.io/rickbeerendonk/pen/vEdBmm

**Comment by spicyj** [comment] 2015-02-17 19:21
@xymostech Here's the bug I mentioned to you yesterday, if you're interested – it involves working on [ChangeEventPlugin](https://github.com/facebook/react/blob/a8d9bff3ca0e123f0dade1987ad6040e23397989/src/browser/eventPlugins/ChangeEventPlugin.js) so that we can listen to both the input and change events for `range` inputs. The current code structure isn't super amenable to this change, but it should be possible with a little refactoring.

**Comment by spicyj** [comment] 2015-02-26 23:29
(Dupe of #554.)

**Closed by spicyj** 2015-02-26 23:29 UTC
Labels: Component: Events

**Comment by jaygood** [comment] 2016-08-03 20:01
Hey,

Was this supposed to be fixed in #544? I'm using ie 11 with react 15.3 and it looks like the issue still persists. Neither onChange nor onInput are being called at any point in the lifecycle of the drag.

[https://jsfiddle.net/m78g29m5/](url)

**Comment by maxdeviant** [comment] 2017-04-06 14:00
@jaygood I ran into the same issue.

It looks like it will be fixed in React v16 ([source](https://github.com/facebook/react/issues/554#issuecomment-271579096)).

**Comment by saawsan** [comment] 2017-04-21 10:12
Hi, 
I recently came across this issue too. Is there any local patch that could help us while waiting for a public fix (apparently on React v15.5 or v16)?

**Comment by c0debreaker** [comment] 2017-05-29 15:40
Glad I saw this thread. My app is on React 15.5.4. I'm encountering it too on my Windows phone. User-agent is `Mozilla/5.0 (Windows Phone 8.1;ARM;Trident/7.0;Touch;rv:11.0; IEMobile/11.0;NOKIA;Lumia 920) like Gecko`

**Comment by NullVoxPopuli** [comment] 2017-07-11 16:23
https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=8&qpcustomd=1
