### ISSUE TITLE
Binding in react

### ISSUE THREAD

**Issue by sandysaders** [facebook/react#7385] opened 2016-07-31 16:27 UTC
I recently read an [article](https://medium.com/@rjun07a/binding-callbacks-in-react-components-9133c0b396c6#.x2t0839fs) on Medium about binding in react. Basically explaining how you should bind functions inside of the constructor of stateful components to prevent unnecessary rerenders in a component. It shows how using arrow function and `.bind` causes function creation on the spot and makes it seem like new props are being received continuously even when it may not. This is bad and prevents optimizations according to the article. So great I know I should bind in constructor but what about binding methods with parameters not just calling them in stateful and stateless components?

Say theres something like the following:
```js
// Using stateful components
  class Something extends React.Component {
    constructor () {
      super()
      this.doSomething = this.doSomething.bind(this)  
    }
    doSomething (take, take2) {
       return take + take2;
    }

    render () {
      return (
        <div>
          <button onClick={this.doSomething(5, 6)}>clickMe!</button>
        </div>
      );
    }
  }

// Using stateless components
  function Something (props) {

    function doSomething (take, take2) {
       return take + take2;
    }

    return (
      <div>
       <button onClick={doSomething(5, 6)}>clickMe!</button>
      </div>
    );
  }
```

It throws an error because the call evaluates immediately to a number when it should be a function. This makes sense and the only way around this I've been able to go around this is using an arrow function in the `onClick` `() => doSomething(5, 6)` and that will run. But this will cause unnecessary rerenders that the article explained. So how could you do this better and prevent unnecessary rerenders in stateless and stateful components?

**Comment by brigand** [comment] 2016-07-31 18:45
This bug tracker is for issues with react itself. For usage questions, please ask on StackOverflow or IRC.

The only solution that comes to mind is some kind of memoization, but there are a lot of ways to do it with different trade offs.

**Comment by hnordt** [comment] 2016-08-01 15:31
```js
  class Something extends React.Component {
    constructor () {
      super()
      this.doSomething = this.doSomething.bind(this)  
    }
    doSomething (take, take2) {
       return event => {
         event.preventDefault()
         return take + take2
       };
    }

    render () {
      return (
        <div>
          <button onClick={this.doSomething(5, 6)}>clickMe!</button>
        </div>
      );
    }
  }

// Using stateless components
  function Something (props) {

    function doSomething (take, take2) {
       return take + take2;
    }

    return (
      <div>
       <button onClick={doSomething(5, 6)}>clickMe!</button>
      </div>
    );
  }
```

**Comment by Aweary** [comment] 2016-08-01 15:38
Yeah, the issue is that you're invoking your method, not passing it down. You can also pass arguments to `bind` so that when its invoked it will be invoked with those arguments

```js
this.doSomething = this.doSomething.bind(this, 5, 6)
```

If you have access to the arguments for `doSomething` in the initial `props` you can bind it like that in the `constructor` and just do

```js
<button onClick={this.doSomething}>clickMe!</button>
```

> I'm not use if it'll prevent unnecessary rerenders. Can you test and send me feedback?

@hnordt your method won't prevent unnecessary renders because you're still returning a new function very time the component is rendered.

**Comment by milesj** [comment] 2016-08-01 17:20
Or just use arrow functions.

```
<button onClick={() => this.doSomething(5, 6)}>clickMe!</button>
<button onClick={() => doSomething(5, 6)}>clickMe!</button>
```

**Closed** 2016-08-01 17:25 UTC

**Comment by Aweary** [comment] 2016-08-01 17:28
@milesj that would still mean that the `onClick` function is recreated on every `render` call

**Comment by kennetpostigo** [comment] 2016-08-01 17:47
@milesj yea using arrow functions cause it to recreate the onClick on every render call @milesj

**Comment by gaearon** [comment] 2016-08-01 19:40
Re-creating functions in `render()` is not *that* expensive.
Please don’t blindly follow advice you see in articles.
It’s not always applicable, and you should measure and test if it makes a difference.

Using arrows (or even `bind` in `render()`) only prevents `PureRenderMixin`-like optimizations **which aren’t enabled by default anyway.** So if you don’t use `PureRenderMixin`, `PureComponent`, or `shallowCompare` addon in the components below the tree, you don’t gain anything by binding in constructor.

**Comment by gaearon** [comment] 2016-08-01 19:43
If you **really know that binding was expensive in your case after measuring the performance before and after in your app**, but you want to pass some arguments, you can just pass them as props: `doSomething={this.doSomething} x={5} y={6}`, and let the child component do something like `this.props.doSomething(this.props.x, this.props.y)`. The benefits of this are dubious if `x` and `y` change often because if the data changes, shallow comparisons won’t help you anyway. So this is only useful in rare cases when the code is perf critical *and* those arguments are relatively stable (e.g. IDs).

**Comment by sandysaders** [comment] 2016-08-01 20:05
@gaearon I ask not only because I think its a performance hit to my app at all. I ask because if there is a better way or more efficient way of doing things because I am using `PureRenderMixin` I would rather do it the best way now rather than going back later and changing a whole lot of code. It's no pain to me to do this now. I just wasn't sure __how__ to do this without arrow functions or `.bind()` in the article and couldn't find it in the docs and I was curious really in an `onClick` handler as this is where I usually use something like this. 

It's kind of like the issue going around on twitter where you have developers passing all the props using rest. rather than passing down whats needed. Both work just one is preferred so that it is explicit what is needed. I view it like this. I rather do it right the first time around not because the other way is wrong but because I think it might be beneficial in the slightest way.

**Comment by timche** [comment] 2016-08-01 20:08
@gaearon, Why not just use the props directly in the function?

```js
```

**Comment by sandysaders** [comment] 2016-08-01 20:10
@timeche I thought the same. As the child component would need to call the function with the props in a handler as well?

**Comment by timche** [comment] 2016-08-01 20:11
@gaearon Why not use the props directly in the `this.doSomething` function`?

```js
doSomething() {
  return this.props.x + this.props.y
}

render() {
  return (
    <Comp doSomething={this.doSomething} />
  )
}
```

**Comment by gaearon** [comment] 2016-08-01 20:11
@timche I think presumably they would be different for each item in a list (that’s the usual use case) but I’m not sure because the example is too trivial.

**Comment by gaearon** [comment] 2016-08-01 20:14
@sandysaders 

>I ask because if there is a "better" way or more efficient way of doing things because I am using PureRenderMixin I would rather do it the "best" way now rather than going back later and changing a whole lot of code.

I think the "best" way is to write the code as naturally as you can, and *if you have issues*, you can optimize individual components. It won't be changing "a whole lot of code", most likely you'll need to tweak a few components for desired perf. Also in most apps you won't even have those issues to begin with.

The funny thing with perf is there is no hard rule that you could just follow every time. We *don't* recommend making every single component use `PureRenderMixin` or equivalent. We recommend that you write your app normally, and *if* you need to optimize it, then you can use React Perf tools to figure out the best components to optimize, and optimize just them.

**Comment by timche** [comment] 2016-08-01 20:18
@sandysaders 

> It's no pain to me to do this now. I just wasn't sure how to do this without arrow functions or .bind() in the article and couldn't find it in the docs

Take a look [here](https://facebook.github.io/react/docs/reusable-components.html#no-autobinding) ;)

> We recommend that you bind your event handlers in the constructor so they are only bound once for every instance:

**Comment by gaearon** [comment] 2016-08-01 20:20
And no, you can’t do this with stateless functional components.

So if you insist on *never* passing arrows down, you either won’t be able to pass callbacks down from stateless functional components.

**Comment by sandysaders** [comment] 2016-08-01 20:20
@gaearon I totally hear you dude. Really was just curious because I had never thought about it how to "properly" bind functions/methods for handlers before.

@timche nice

**Comment by timche** [comment] 2016-08-01 20:28
@sandysaders Btw, you can also use arrow functions in your classes with [`babel-transform-class-properties`](http://babeljs.io/docs/plugins/transform-class-properties/), so you don't have to bind them anymore.

Example:
```js
doSomething = (x, y) => x + y

render() {
  return <Comp doSomething={this.doSomething} />
}
```

**Comment by cvazac** [comment] 2016-08-02 06:34
We have been using html data attributes when every item of a list needs to know who it is. 
```
render () {
  return (
    <div>
      this.props.items.map((item, index) => {
        return <button data-index={index} onClick={this.onClick} />
      })
    </div>
  )
}
onClick = ({target: {dataset: {index}}}) => {
  alert(this.props.items[index])
}
```

**Comment by gaearon** [comment] 2016-08-02 18:43
Reading from DOM is generally not very great if you already have this data provided by React.

**Comment by cvazac** [comment] 2016-08-02 19:12
yep, i agree. the `dataset` pattern is just a workaround to avoid writing a new component that just `render`s the `button`

**Comment by ErythroME** [comment] 2016-08-03 10:31
[This article](https://daveceddia.com/avoid-bind-when-passing-props/) provided an way to pass arguments without bind. Perhaps it helps.

**Comment by milesj** [comment] 2016-08-03 16:47
@ErythroME I'd take that article with a grain of salt. The only truth is #2, in that `bind()` itself can be really slow depending on the browser and environment. 

Arrow functions are not inefficient -- this is exactly what their use case is for. If anything, it's the transpilation down to regular functions via babel that is the performance loss.

Furthermore, don't use #4 or #6 as they're not finalized specs or they are dead/denied specs.

The best, easiest, and most idiomatic approach in my opinion is #5 (or the 2nd bonus). These should be the standard as it solves most, if not all of use cases.
