### ISSUE TITLE
Error: "Could not find node with id "44300" in commit tree"

### ISSUE THREAD

**Issue by chrisdusyk-iq** [facebook/react#16711] opened 2019-09-09 15:10 UTC
Describe what you were doing when the bug occurred:
1. Reading the flamegraph of my React app
2. Clicked on one of the options in the `Rendered at` list of the graph
  ![image](https://user-images.githubusercontent.com/41026008/64542778-69710580-d2e1-11e9-8846-ab1b810e034c.png)
3. This caused the below error to appear in React DevTools.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.6-a39d9c3

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11442
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11388)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11921)
    at xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:277807)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55891)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62940)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99536)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84256)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81286)

Component stack: in xi
    in div
    in div
    in div
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by threepointone** [comment] 2019-09-09 15:28
Marking this as a duplicate of https://github.com/facebook/react/issues/16446

CCing @bvaughn because this contains a *little* more of information than the marked bug. That said, is there any chance you can share any more information how this happened? If it's a small project, could you share the git repo, or a codesandbox version of your code?

**Closed by threepointone** 2019-09-09 15:28 UTC

**Comment by chrisdusyk-iq** [comment] 2019-09-09 16:08
@threepointone unfortunately I can't really share the project as it's work code. I can confirm that was with React version `16.9.0`. To get there, all I did was click on the `Locations` component in the Flamegraph, and click on the 3rd `Rendered at` option. I can say it's a fairly large component holding a bunch of data returned from the server. I have a task to switch it over to use `react-virtualized` for performance improvements in a couple sprints.

**Comment by threepointone** [comment] 2019-09-09 17:55
Does this error happen reliably for you? Or did you see it just once?

**Comment by chrisdusyk-iq** [comment] 2019-09-09 19:53
> Does this error happen reliably for you? Or did you see it just once?

It doesn't seem to be consistent. I re-created it with a similar profiling session, but I tried clicking the break link a second time after reloading and it worked. However it broke again when I tried a different `Rendered at` time for a different component

**Comment by bvaughn** [comment] 2019-09-10 15:37
I'm sorry to hear this @chrisdusyk-iq chrisdusyk-iq

Any chance one of us could get access to the app (not code, but running app) so we can try to repro?
