### ISSUE TITLE
`onMouseLeave` can be unreliable in Chrome

### ISSUE THREAD

**Issue by petehunt** [facebook/react#4492] opened 2015-07-26 20:23 UTC
See this jsfiddle: https://jsfiddle.net/tvxderw3/

In Chrome, as you quickly move your mouse up and down the list, you'll notice that some get stuck in the hover state. This works fine in Safari, and works in Chrome if you use a stable key between the hover states. I think `mouseout` somehow isn't firing if the underlying DOM node is replaced by a new one in the same tick, but it's odd that this is a Chrome-only bug.

**Comment by spicyj** [comment] 2015-07-26 20:30
Didn't you write React?

**Comment by spicyj** [comment] 2015-07-26 20:31
Best guess: the top-level onMouseOut doesn't fire on the removed node.

**Comment by cody** [comment] 2015-07-26 20:53
@petehunt 
> This works fine in Safari

I see the bug in Safari as well, version 8.0.7. In Firefox it happens too, but not so often.

**Comment by syranide** [comment] 2015-07-27 08:01
FYI this happens without React as well. https://jsfiddle.net/ahf3tay5/

**Comment by spicyj** [comment] 2015-07-29 03:22
Well that's just lovely. Time to file a Chrome bug?

**Comment by syranide** [comment] 2015-07-29 07:00
@spicyj It's in IE too, perhaps this is actually a weird spec thing?

**Comment by pswai** [comment] 2015-10-03 01:42
@syranide I have tried with pure JS and it works fine (tested in Mac Chrome) https://jsfiddle.net/2gmzzzv1/

**Comment by syranide** [comment] 2015-10-03 09:05
@pswai You're testing a different scenario, my fiddle shows that this is not a problem with the React event system, it's a "problem" with browser behavior when the hovered nodes are replaced/removed.

**Comment by pswai** [comment] 2015-10-03 10:58
@syranide Ah you are right. Thanks for pointing that out.

**Comment by pswai** [comment] 2015-10-03 11:32
There seems to be bug reports about this for Chrome

https://code.google.com/p/chromium/issues/detail?id=276329
https://code.google.com/p/chromium/issues/detail?id=515921

**Comment by henlz** [comment] 2017-08-22 21:49
I'm also having troubles with this event, tested on Chrome, Firefox (stable) and Edge. It only worked fine on Firefox nightly.

It fires the onMouseEnter just fine, but it almost never works for the onMouseLeave event. There is no way at all to use this Synthetic Event.

**Comment by gaearon** [comment] 2017-10-03 21:07
@henlz Perhaps it's time to file a new issue with a reproducing example? This one is pretty stale, and it's hard to say if they're even related or not.

**Comment by henlz** [comment] 2017-10-03 21:46
@gaearon You're right. I will create one with all the details and steps to reproduce it for a better discussion.

**Comment by gaearon** [comment] 2017-10-03 23:24
I’ll close this one as it’s unlikely we’ll make meaningful progress on an issue from 2015.

**Closed by gaearon** 2017-10-03 23:24 UTC
Labels: Component: DOM, Type: Bug

**Comment by oyeanuj** [comment] 2018-04-27 04:14
@henlz Is there an issue you created for this somewhere? Just ran into this as well :/

**Comment by WillSquire** [comment] 2018-05-17 10:37
Is there a workaround for this?

**Comment by kevin-king** [comment] 2018-09-07 19:01
Also just ran into this issue. Still investigating workarounds. Anyone find a workaround? Will post back if I find a good way to fix.

**Comment by DamianDobrev** [comment] 2018-10-02 17:15
I managed to "fix" this. I'm doing two things:
1. Added the listener to element which is **not** `display: inline;`, rather block/inline-block.
2. Added `pointer-events: none` to any containers of SVGs inside the element with the listener.

Seems to work fine now, the event is fired properly. I do not know why though.

**Comment by KevinGrant12** [comment] 2019-07-27 19:32
@DamianDobrev Thank you! What an odd problem. I have a button with child SVG's being animated and this was a 4 day headbanger that I finally tracked to here! It was simply a matter of disabling the pointer events on the child svg's.

**Comment by yardenapp** [comment] 2019-12-28 11:56
I fixed this by invalidating the hover state between renders

```
// Inside your component
const divRef = useRef();
const [hovered, setHovered] = useState();
 
if(hovered && divRef.current && divRef.current.matches(':hover') === false)
    setHovered(false);

return (
    <div ref={divRef} onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)}/>
)
```

**Comment by cory-vade** [comment] 2022-09-16 16:09
> 

Does anyone have a better explanation for why this happens?

**Comment by cory-vade** [comment] 2022-09-16 16:09
> I managed to "fix" this. I'm doing two things:
> 
> 1. Added the listener to element which is **not** `display: inline;`, rather block/inline-block.
> 2. Added `pointer-events: none` to any containers of SVGs inside the element with the listener.
> 
> Seems to work fine now, the event is fired properly. I do not know why though.

Does anyone actually understand the root cause of this?

**Comment by AKclown** [comment] 2022-12-19 06:27
> I managed to "fix" this. I'm doing two things:
> 
> 1. Added the listener to element which is **not** `display: inline;`, rather block/inline-block.
> 2. Added `pointer-events: none` to any containers of SVGs inside the element with the listener.
> 
> Seems to work fine now, the event is fired properly. I do not know why though.

Thanks a lot, this is very helpful for me

**Comment by danny-dang** [comment] 2023-09-11 11:07
> I fixed this by invalidating the hover state between renders
> 
> ```
> // Inside your component
> const divRef = useRef();
> const [hovered, setHovered] = useState();
>  
> if(hovered && divRef.current && divRef.current.matches(':hover') === false)
>     setHovered(false);
> 
> return (
>     <div ref={divRef} onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)}/>
> )
> ```

Thank you. This solution works like a champ
