### ISSUE TITLE
[react profiler bug]Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 1"

### ISSUE THREAD

**Issue by Zaynex** [facebook/react#16412] opened 2019-08-16 05:57 UTC
---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.2-2bcc6c6

Call stack: at d (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:5744)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:8526)
    at Ai (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:274200)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)

Component stack: in Ai
    in div
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ua
    in le
    in ve
    in ko
    in Fl

**Comment by bvaughn** [comment] 2019-08-16 15:08
Could you share repro steps for this please?

**Comment by raibima** [comment] 2019-08-18 05:12
Got a similar error. It happens when you **click on one of the components in the flame graph** and **toggle the filter by commit duration**.

If you don't click the component first, the filter works as expected :ok_hand: 

minimal repro: https://codesandbox.io/s/xenodochial-lamarr-q71wt

![repro-2](https://user-images.githubusercontent.com/4465644/63220403-ef9d9e80-c1b0-11e9-9185-b9020316f68a.gif)

**Comment by Zaynex** [comment] 2019-08-18 06:08
> Could you share repro steps for this please?

I'am afraid not. That's my company project and I just start the react project and open react-dev-tools.

How about react team  send  the error stack error to some analyze website  like `sentry` ?
I mean you can get the real code stack (not uglify codebase).

**Comment by gaearon** [comment] 2019-08-18 10:43
@zaynex It’s not the error stack that we’re looking for but the reproduction instructions.

**Comment by bvaughn** [comment] 2019-08-18 14:43
Yup, something as detailed as @raibima's instructions above would be super helpful.

**Comment by bvaughn** [comment] 2019-08-18 15:44
I've fixed the related issue, but I'm not sure how to repro this one yet so it's likely still broken. Still, might be worth checking 4.0.4 (will be uploading shortly) to see if it's fixed for you.

**Comment by Zaynex** [comment] 2019-08-19 01:52
I click the next commit arrow `->`. 

![react-demo](https://user-images.githubusercontent.com/13745971/63234177-bd4e7880-c266-11e9-9bd4-436373f2da2e.gif)

**Comment by bvaughn** [comment] 2019-08-19 02:04
Hm. Seems like something related to your project or setup/environment then. Just profiling and clicking the "->" arrow isn't sufficient to repro the error in my experience.

**Comment by bvaughn** [comment] 2019-09-13 21:54
I finally saw this locally when profiling a react-window prototype.

Profiler data export:
https://gist.github.com/bvaughn/db4465f4be801f492ee672306a382875

It looks like the profiling session has only 33 saved `operations` in the array but it thinks it has 42 commits/snapshots.

**Comment by bvaughn** [comment] 2019-09-16 14:33
I narrowed this down some more over the weekend. (This might not be the _only_ source of the bug, it is the only reliable trigger I am aware of.) Anyway, when the bug manifests it follows this pattern.

First, (due to a bug in local code I was testing), we encounter a duplicate key warning:
![Screen Shot 2019-09-16 at 7 30 04 AM](https://user-images.githubusercontent.com/29597/64966578-e78a5a80-d853-11e9-82dc-96629b606e94.png)

Then on a subsequent update, the backend tells the frontend to re-order children - but one is missing (the first one to use the duplicate key above).
![Screen Shot 2019-09-16 at 7 30 11 AM](https://user-images.githubusercontent.com/29597/64966579-e822f100-d853-11e9-8129-0507715f0c1f.png)

Digging into this a bit more, it looks like React actually doesn't notify DevTools of the that node being removed. (It doesn't call `handleCommitFiberUnmount`.) This seems like a React bug.

**Comment by bvaughn** [comment] 2019-09-16 14:48
Knowing the above, I've been able to trap the bug within a small repro now:
```js
function Foo() {
  return <div />
}

function App() {
  const [state, setState] = React.useState(false);
  const handleClick = () => setState(on => !on);
  return (
    <React.Fragment>
      <button onClick={handleClick}>{state ? 'on' : 'off'}</button>
      <div>
        {state
          ? [<Foo key="b" />, <Foo key="a" />, <Foo key="a" />]
          : [<Foo key="a" />, <Foo key="b" />]
        }
      </div>
    </React.Fragment>
  )
}
```

Clicking the button twice triggers the error. The first click causes the duplicate key warning and the second shows the unmount bug.

**Comment by bvaughn** [comment] 2019-09-17 18:21
I think the bug is here: https://github.com/facebook/react/blob/901139c2910d0dc33f07f85c748c64371f8664f4/packages/react-reconciler/src/ReactChildFiber.js#L872-L873

(and so here as well):
https://github.com/facebook/react/blob/901139c2910d0dc33f07f85c748c64371f8664f4/packages/react-reconciler/src/ReactChildFiber.js#L1061-L1062

Existing children can't be represented by a map when there are duplicate keys, which causes the logic below to skip over one of the duplicates.

**Comment by bvaughn** [comment] 2019-09-17 19:45
After digging into this, I think the case above is not one that we will fix into React, because fixing it would significantly hurt performance for the common case (no duplicate keys, which is technically _not_ supported anyway).

**Comment by bvaughn** [comment] 2019-09-17 19:51
@Zaynex Could you confirm whether you see a duplicate key warning (or any other warnings) in the console around the time when you see the Profiler error?

**Comment by Zaynex** [comment] 2019-09-18 03:08
@bvaughn  I am sure there are no duplicate key warning. But a new warning was found.

```
backend.js:1 Uncaught RangeError: Invalid array length
    at He (backend.js:1)
    at backend.js:1
    at Set.forEach (<anonymous>)
    at Object.flushInitialOperations (backend.js:1)
    at backend.js:9
    at <anonymous>:1:225
    at Array.map (<anonymous>)
    at Object.emit (<anonymous>:1:202)
    at i (backend.js:9)
    at backend.js:9
    at Map.forEach (<anonymous>)
    at y (backend.js:9)
    at e (backend.js:1)
He @ backend.js:1
(anonymous) @ backend.js:1
flushInitialOperations @ backend.js:1
(anonymous) @ backend.js:9
(anonymous) @ VM1079:1
emit @ VM1079:1
i @ backend.js:9
(anonymous) @ backend.js:9
y @ backend.js:9
e @ backend.js:1
postMessage (async)
r @ contentScript.js:1
(anonymous) @ contentScript.js:1
setInterval (async)
108 @ contentScript.js:1
n @ contentScript.js:1
(anonymous) @ contentScript.js:1
(anonymous) @ contentScript.js:1
```
![image](https://user-images.githubusercontent.com/13745971/65104577-88b81300-da04-11e9-8c59-308c32003916.png)

**Comment by bvaughn** [comment] 2020-01-03 21:46
RE [this comment](https://github.com/facebook/react/issues/16412#issuecomment-531403049)

> It looks like [the exported profiling session](https://gist.github.com/bvaughn/db4465f4be801f492ee672306a382875) has only 33 saved mutations in the `operations` array, but it has 42 snapshots in the `commitData` array. Not sure how this happened.

I believe my changes in PR #17771 should fix this mismatch and so, possible, fix the source of this bug. Let's keep an eye out once that fix has been released and see if we can still trigger this bug.

**Closed** 2020-01-05 00:51 UTC
Labels: Component: Developer Tools, Type: Bug
