### ISSUE TITLE
Error: "Commit tree already contains fiber 10819. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by ahsan7786** [facebook/react#18877] opened 2020-05-09 12:57 UTC
Describe what you were doing when the bug occurred:
simple running profiler and popout this error

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162221)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161772)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161696)

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by irohitb** [comment] 2020-05-09 19:17
Looks Similar to this issue: https://github.com/facebook/react/issues/18859

**Comment by bvaughn** [comment] 2020-05-11 23:31
Sorry for the inconvenient!

This looks like a duplicate of #18859 though. If you're able to provide more info on how to repro- that would be great! Otherwise the duplicate issue doesn't add a lot of value, so I'm going to close it.

**Closed by bvaughn** 2020-05-11 23:31 UTC

**Comment by bvaughn** [comment] 2021-04-28 20:30
@ahsan7786  This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼
