### ISSUE TITLE
yarn test failing node v10.15.3 npm 6.9.0

### ISSUE THREAD

**Issue by kambleaa007** [facebook/react#19760] opened 2020-09-03 14:56 UTC
node v10.15.3 
npm 6.9.0

`yarn -v` is `1.15.2`
`OS` is `Windows 10`
`npm view react version` is `16.13.1`
`npm -v` is `6.9.0`
`node -v` is `v10.15.3`

## Steps To Reproduce
I forked reactjs,
i did 
`yarn` --> it worked
`yarn test` --> it fails 

1. yarn test

Link to code example:

## The current behavior
Summary of all failing tests
 FAIL  packages/react-dom/src/__tests__/ReactServerRendering-test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, stat 'D:\Folder1\Git\React-toPR\react\node_modules\pretty-format\node_modules\react-is\index.js'

      at Object.statSync (node_modules/@jest/transform/node_modules/graceful-fs/polyfills.js:308:16)
      at getScriptCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:797:22)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:554:24)
      at Object.<anonymous> (node_modules/pretty-format/build/plugins/ReactElement.js:8:39)
      at Object.<anonymous> (node_modules/pretty-format/build/index.js:19:44)

 FAIL  packages/react-dom/src/__tests__/ReactTestUtils-test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, stat 'D:\Folder1\Git\React-toPR\react\node_modules\pretty-format\node_modules\react-is\index.js'

      at Object.statSync (node_modules/@jest/transform/node_modules/graceful-fs/polyfills.js:308:16)
      at getScriptCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:797:22)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:554:24)
      at Object.<anonymous> (node_modules/pretty-format/build/plugins/ReactElement.js:8:39)
      at Object.<anonymous> (node_modules/pretty-format/build/index.js:19:44)

 FAIL  packages/react-art/src/__tests__/ReactART-test.js
  ● ReactARTComponents › should warn if radius is missing on a Circle component

    Error: Unexpected warning recorded: - Expected
    + Received

      Warning: Failed prop type: The prop `radius` is marked as required in `Circle`, but its value is `undefined`.
    -     in Circle (at **)
    +     in <anonymous> (at **)

      142 |         // We don't throw an Error here though,
      143 |         // Because it might be suppressed by ReactFiberScheduler.
    > 144 |         unexpectedWarnings.push(new Error(errorMessage));
          |                                   ^
      145 |       };
      146 |
      147 |       // TODO Decide whether we need to support nested toWarn* expectations.

      at BufferedConsole.consoleSpy (scripts/jest/matchers/toWarnDev.js:144:35)
      at printWarning (packages/shared/consoleWithStackDev.js:45:30)
      at error (packages/shared/consoleWithStackDev.js:24:5)
      at checkPropTypes (packages/shared/checkPropTypes.js:101:42)
      at validatePropTypes (packages/react/src/ReactElementValidator.js:230:35)
      at Object.createElementWithValidation (packages/react/src/ReactElementValidator.js:481:5)
      at packages/react-art/src/__tests__/ReactART-test.js:426:15
      at Object.matcher (scripts/jest/matchers/toWarnDev.js:156:11)
      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:380:30)
      at Object.throwingMatcher [as toErrorDev] (node_modules/expect/build/index.js:381:15)
      at Object.<anonymous> (packages/react-art/src/__tests__/ReactART-test.js:428:5)
      at Object.<anonymous> (packages/react-art/src/__tests__/ReactART-test.js:428:5)

  ● ReactARTComponents › should warn if width/height is missing on a Rectangle component

    Error: Unexpected warning recorded: - Expected
    + Received

      Array [
        "Warning: Failed prop type: The prop `width` is marked as required in `Rectangle`, but its value is `undefined`.
    -     in Rectangle (at **)",
    -   "Warning: Failed prop type: The prop `height` is marked as required in `Rectangle`, but its value is `undefined`.
    -     in Rectangle (at **)",
    +     in <anonymous> (at **)",
      ]

      142 |         // We don't throw an Error here though,
      143 |         // Because it might be suppressed by ReactFiberScheduler.
    > 144 |         unexpectedWarnings.push(new Error(errorMessage));
          |                                   ^
      145 |       };
      146 |
      147 |       // TODO Decide whether we need to support nested toWarn* expectations.

      at BufferedConsole.consoleSpy (scripts/jest/matchers/toWarnDev.js:144:35)
      at printWarning (packages/shared/consoleWithStackDev.js:45:30)
      at error (packages/shared/consoleWithStackDev.js:24:5)
      at checkPropTypes (packages/shared/checkPropTypes.js:101:42)
      at validatePropTypes (packages/react/src/ReactElementValidator.js:230:35)
      at Object.createElementWithValidation (packages/react/src/ReactElementValidator.js:481:5)
      at packages/react-art/src/__tests__/ReactART-test.js:444:54
      at Object.matcher (scripts/jest/matchers/toWarnDev.js:156:11)
      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:380:30)
      at Object.throwingMatcher [as toErrorDev] (node_modules/expect/build/index.js:381:15)
      at Object.<anonymous> (packages/react-art/src/__tests__/ReactART-test.js:445:5)
      at Object.<anonymous> (packages/react-art/src/__tests__/ReactART-test.js:445:5)

  ● ReactARTComponents › should warn if outerRadius/startAngle/endAngle is missing on a Wedge component

    Error: Unexpected warning recorded: - Expected
    + Received

      Array [
        "Warning: Failed prop type: The prop `outerRadius` is marked as required in `Wedge`, but its value is `undefined`.
    -     in Wedge (at **)",
    -   "Warning: Failed prop type: The prop `startAngle` is marked as required in `Wedge`, but its value is `undefined`.
    -     in Wedge (at **)",
    -   "Warning: Failed prop type: The prop `endAngle` is marked as required in `Wedge`, but its value is `undefined`.
    -     in Wedge (at **)",
    +     in <anonymous> (at **)",
      ]

      142 |         // We don't throw an Error here though,
      143 |         // Because it might be suppressed by ReactFiberScheduler.
    > 144 |         unexpectedWarnings.push(new Error(errorMessage));
          |                                   ^
      145 |       };
      146 |
      147 |       // TODO Decide whether we need to support nested toWarn* expectations.

      at BufferedConsole.consoleSpy (scripts/jest/matchers/toWarnDev.js:144:35)
      at printWarning (packages/shared/consoleWithStackDev.js:45:30)
      at error (packages/shared/consoleWithStackDev.js:24:5)
      at checkPropTypes (packages/shared/checkPropTypes.js:101:42)
      at validatePropTypes (packages/react/src/ReactElementValidator.js:230:35)
      at Object.createElementWithValidation (packages/react/src/ReactElementValidator.js:481:5)
      at packages/react-art/src/__tests__/ReactART-test.js:470:77
      at Object.matcher (scripts/jest/matchers/toWarnDev.js:156:11)
      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:380:30)
      at Object.throwingMatcher [as toErrorDev] (node_modules/expect/build/index.js:381:15)
      at Object.<anonymous> (packages/react-art/src/__tests__/ReactART-test.js:470:202)
      at Object.<anonymous> (packages/react-art/src/__tests__/ReactART-test.js:470:202)

Test Suites: 3 failed, 246 passed, 249 total
Tests:       3 failed, 26 skipped, 5979 passed, 6008 total
Snapshots:   78 passed, 78 total
Time:        298.599s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## The expected behavior
It should pass all tests, as i didnt made any changes
surprisingly, it works for following configuration,
Online working config
[Online working config](https://ba79e71d-bf59-4fce-81a7-b8677c5b23c0.ws-us02.gitpod.io/)

`yarn -v` is `1.22.4`
`npm -v` is `6.14.7`
`node -v` is `v12.18.3`
`npm view react version` is `16.13.1`

**Comment by eps1lon** [comment] 2020-09-04 07:13
The failed ART test suite is handled in #18610. I can't reproduce `ReactServerRendering` and `ReactTestUtils` failing.

What OS are you using and what is the output for `yarn -v` for you?

**Comment by kambleaa007** [comment] 2020-09-04 09:26
`yarn -v` is `1.15.2`

**Comment by eps1lon** [comment] 2020-09-04 12:05
Note that you shouldn't use `npm` to install with this repository. Dependencies are managed with `yarn` which means using `npm` results in undefined behavior.

Closing in favor of #18610 since the other issues are likely related to outdated local installs. For me windows 10 and yarn 1.17 produced the correct `node_modules` layout.

**Closed by eps1lon** 2020-09-04 12:05 UTC
Labels: Status: Unconfirmed
