### ISSUE TITLE
Setting progress element value to 0 is removed from the markup

### ISSUE THREAD

**Issue by ScottDowne** [facebook/react#6704] opened 2016-05-05 02:55 UTC
Seems like `<progress max="5" value="0"/>` isn't working as expected.

Here it is in regular HTML: https://jsfiddle.net/a4zx1oq2/

Expected: rendered an empty progress bar.

In react however, it's rendered as https://jsfiddle.net/6xsnLaey/1/

I noticed however, setting the value to `0` in `componenetDidMount` seems to get around this bug, same with using `-0`

Here it is in react: https://jsfiddle.net/69z2wepo/40939/

**Comment by syranide** [comment] 2016-05-05 08:03
#6119 and the new DOM renderer is the root cause for this (and HTML being quirky as always).

**Comment by ScottDowne** [comment] 2016-05-05 12:33
Now that you mention input, it's doing some weird things with `value="0"` too, but seems to still function fine.

If I set `value="0"` in plain html, and inspect it, it's still there. If I do it in react, the input has the 0 in the input, but inspecting it doesn't show the attribute in the markup. https://jsfiddle.net/5154tdL9/1/

`input` quirk above is probably not a concern, but it might give us room to wiggle on changing things for progress without breaking regular input? I understand the desire to not make a special case for progress.

**Comment by syranide** [comment] 2016-05-05 14:16
@ScottDowne That's "intended" and a behavior exhibited by HTML (try typing in a regular input and inspect). Anyway, this is known issue and it's being indirectly fixed AFAIK, the end result being that value should not be special-cased at all but rather handled differently by `ReactDOMInput` itself and thus this problem goes away.

**Comment by Pomax** [comment] 2016-05-05 15:57
Ran into this as well, hopefully https://github.com/facebook/react/pull/5680 can be rebased and resolved soon (it looks like it's been gathering a bit of dust?)

**Comment by jimfb** [comment] 2016-05-05 16:45
This will be fixed by https://github.com/facebook/react/pull/6406, which has also been gathering a bit of dust.  #6406 was intended to supersede #5680.

**Comment by Pomax** [comment] 2016-05-05 18:12
ah, nice!

**Comment by jimfb** [comment] 2016-06-08 15:24
Fixed in https://github.com/facebook/react/pull/6406

**Closed by jimfb** 2016-06-08 15:24 UTC

**Comment by mrlew** [comment] 2016-06-22 02:04
One possible workaround (for the ones that are still using the unfixed version) is [`passing a two decimal float number`] (http://stackoverflow.com/questions/37956826/react-value-prop-not-reaching-dom-if-set-to-0). So, `value={parseFloat(row.quantity).toFixed(2)}` will transform `0` into `0.00` and it  works.
