### ISSUE TITLE
In NW.js app, the 'file' type <input> onChange event doesn't fire

### ISSUE THREAD

**Issue by zhouce** [facebook/react#7295] opened 2016-07-18 01:48 UTC
I use react in my node webkit application. 
I just update the react and react-dom from 0.14.3 to 15.2.0, I haven't changed my code. But the onChange event not fire now, and there is no error console log.

Any help will be appreciated.

**Comment by stephenkingsley** [comment] 2016-07-18 07:22
@zhouce can I review your code?

**Comment by Coderah** [comment] 2016-08-13 04:26
I actually just hit this issue as well, however i had been at 15.0.1 and it was working fine till I auto upgraded to 15.3.1, downgrading did not fix it. `onChange` breakpoint for the `input` does not hit, however if I set a breakpoint in `ReactEventListener.dispatchEvent` and slowly step through the topChange event it will actually end up reaching the component. This broke our app and I'm struggling to find a fix, any guidance would be immensely helpful.

**Comment by syranide** [comment] 2016-08-13 08:52
@stephenkingsley `file`, not `text`.

**Comment by jochenberger** [comment] 2016-09-23 11:26
I have a similar problem. If I select the same file twice, `onChange` is only called once in Chrome but twice in Firefox. Given that the file's content may have changed, I feel the latter is correct.
Should I resort to using `onInput`?

**Comment by xdroidx** [comment] 2016-10-13 08:40
Same problem with React 15.3.2 and nw.js environment.

**Comment by Keats** [comment] 2016-11-14 02:42
Same here (React 15.3.2), except it worked on Linux but not on Mac (haven't tried Windows).

Code was:
```js
<input onChange={this.uploadFile.bind(this)} type="file" style={{"display": "none"}} ref="file-upload"/>
```
Switching to the following works: 
```js
componentDidMount() {
    this.refs["file-upload"].onchange = this.uploadFile.bind(this);
}
```

**Comment by gaearon** [comment] 2017-10-04 01:06
We’ll need a full example reproducing this to look into it.

**Comment by aweary** [comment] 2018-06-25 18:49
Closing since there was no follow up or reproducing example provided.

**Closed by aweary** 2018-06-25 18:49 UTC
Labels: Component: DOM, Type: Bug
