### ISSUE TITLE
React render script tags

### ISSUE THREAD

**Issue by nguyengiangdev** [facebook/react#3373] opened 2015-03-11 04:35 UTC
I have some prolem when i render script tag.
Example when i click link on page A, i new render page B which i inluce demo.js file. In demo.js i console.log('Hello world'). But when i open google devtools i don't see that. What happen which that erros.

**Comment by jimfb** [comment] 2015-07-21 23:55
Closing this as a duplicate of https://github.com/facebook/react/issues/654

**Closed by jimfb** 2015-07-21 23:55 UTC
