### ISSUE TITLE
Error: "Context menu with id "SelectedElement" already registered."

### ISSUE THREAD

**Issue by MrOrgani** [facebook/react#17785] opened 2020-01-06 09:48 UTC
Describe what you were doing when the bug occurred:
1. Just tryed to use `Components` tab

Edit :  error seems to appear using Firefox, not Chrome

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.4.0-f749045a5

Component stack: in Vo
    in bi
    in div
    in Ai
    in Suspense
    in ei
    in div
    in div
    in la
    in Ur
    in vo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Qi
    in Ve
    in nn
    in Da
    in Yc

**Comment by bvaughn** [comment] 2020-01-06 17:32
I don't think this is sufficient info to reproduce the bug. (The Components tab seems to work fine for me in both Firefox and Chrome.)

Which version of Firefox are you using? How long do you use DevTools before you see this error? Are you doing anything other than literally just opening the Components tab?

**Comment by bvaughn** [comment] 2020-01-11 16:15
Closing for now since I can't reproduce the broken behavior. I'd love to fix this though so if @MrOrgani adds repro steps, I'll re-open!

**Closed by bvaughn** 2020-01-11 16:15 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
