### ISSUE TITLE
JSX render won't allow webkitdirectory and directory to be used

### ISSUE THREAD

**Issue by GaryYufei** [facebook/react#3468] opened 2015-03-20 05:43 UTC
I tried to use webkitdirectory and directory in the input DOM. But I found that it is impossible to add these two label to the input DOM. Anyway to solve this problem?

**Comment by jsfb** [comment] 2015-04-01 22:25
We currently have a whitelist of supported attributes.  We want to remove the whitelist and allow all attributes at some point (https://github.com/facebook/react/issues/140) but it's tricky because some components pass all attributes to their children.

Closing as duplicate of https://github.com/facebook/react/issues/140

**Comment by jsfb** [comment] 2015-04-01 22:26
@GaryYufei Feel free to submit a PR that adds these attributes to the whitelist, I'm sure it would be considered.

**Comment by jsfb** [comment] 2015-04-10 17:18
Fixed by https://github.com/facebook/react/pull/3644.

**Comment by jsfb** [comment] 2015-04-10 17:20
Still need mozdirectory and directory.

**Comment by mikeachen** [comment] 2015-05-09 09:38
https://github.com/facebook/react/pull/3644 was reverted by @zpao. He makes a good point about camelcase.

Where should we continue this discussion? Here?

Currently I'm working around this by manipulating the DOM node directory in componentDidMount.

**Comment by mxstbr** [comment] 2016-02-18 19:02
Any update on this? Taking a cue from #3644, I could submit a PR adding `mozdirectory`, `directory`, `webkitdirectory` and `nwdirectory` if that's still wanted. /cc @zpao

**Comment by zpao** [comment] 2016-02-18 19:11
I think we're pretty unlikely to take it for the next release (very soon) and we'll hopefully get to a point before the next release after that where all attrs will work without the whitelist. So I'm not super inclined to spend any effort here at the moment.

**Comment by mxstbr** [comment] 2016-02-18 19:13
Fair enough, I reckon this can be closed then!

**Comment by VictorBjelkholm** [comment] 2016-08-20 21:02
@zpao any news regarding being able to use mozdirectory and the rest with or without the whitelist?

**Comment by fa7ad** [comment] 2016-09-10 02:47
# BUMP!
Is `nwdirectory` supported on 15.x?

**Comment by sassanh** [comment] 2016-09-10 09:37
Guys it's such a required feature. Is there any workaround for it?

**Comment by gaearon** [comment] 2016-09-10 10:05
We intend to drop the whitelist and pass all attributes through, possibly in React 16.

**Comment by gaearon** [comment] 2016-09-10 10:06
In the meantime you can do this in `componentDidMount` by putting a ref on the node, and calling `setAttribute` yourself.

**Comment by fa7ad** [comment] 2016-09-10 10:09
@gaearon I'm doing that right now, but that's just a dirty hack. Plus, going through the PRs I noticed one that suggests that we might be getting warnings about direct DOM manipulations in the future, so there's that :worried:

**Comment by VictorBjelkholm** [comment] 2016-09-10 10:36
Thanks @gaearon for the update and possible workaround.

**Comment by sassanh** [comment] 2016-09-10 10:48
Yeah I did this:
```
    componentDidMount() {
        this.refs.x.directory = true;
        this.refs.x.webkitdirectory = true;
    }
```
but I just don't like these lines in my code.

**Comment by sassanh** [comment] 2016-09-10 10:50
Though of course we can wait till react 16 is out.

**Comment by sassanh** [comment] 2016-09-10 14:57
Setting the html tag attributes in `componentDidMount` doesn't always work. For example in my case I had something like this:
```
    componentDidMount() {
        this.refs.x.directory = true;
        this.refs.x.webkitdirectory = true;
    }

    render() {
        return this.context.pending
            ? <input ref='x' type='file'/>
            : <div>y</div>;
    }
```
To solve this I had to do this:
```
    componentDidMount() {
        if (this.refs.x) {
            this.refs.x.directory = true;
            this.refs.x.webkitdirectory = true;
        }
    }

    componentDidUpdate() {
        if (this.refs.x) {
            this.refs.x.directory = true;
            this.refs.x.webkitdirectory = true;
        }
    }

    render() {
        return this.context.pending
            ? <input ref='x' type='file'/>
            : <div>y</div>;
    }
```
I guess doing this every time `componentDidUpdate` triggers shouldn't have any overhead. I think browser ignores it if it's already set.

**Comment by fa7ad** [comment] 2016-09-10 15:27
@sassanh isn't string refs deprecated?

I'm doing it like,
```jsx
...
render () {
  return (
    <input ref={i => this._inp = i} type='file' />
  )
}

componentDidMount () {
  this._inp.nwdirectory = true
}
```

as for your conditional you could just define an empty object called `this._inp` in the constructor, so it wouldn't do anything if the ref doesn't exist.

**Comment by Aweary** [comment] 2016-09-10 15:32
@fa7ad string refs are legacy, but not deprecated yet.

> Although string refs are not deprecated, they are considered legacy, and will likely be deprecated at some point in the future. Callback refs are preferred.

[Refs to Components](https://facebook.github.io/react/docs/more-about-refs.html)

**Comment by fa7ad** [comment] 2016-09-10 15:37
@Aweary sorry, missed that. Been a long time since I visited the site. Anyhow, since we know why this is a wontfix, can we close this?

**Comment by sassanh** [comment] 2016-09-10 16:19
@fa7ad actually I like the legacy string refs. They're great for simple use-cases like this and don't force you to define another variable on your class. I'm sure there are use-cases for new function refs but for simple use-cases like this I prefer string refs. I hope it'll never get deprecated.

**Comment by gaearon** [comment] 2016-09-10 16:37
>I'm doing that right now, but that's just a dirty hack. Plus, going through the PRs I noticed one that suggests that we might be getting warnings about direct DOM manipulations in the future, so there's that 😟

I’m not sure what you’re referring to, but touching DOM from lifecycle hooks was (and will be) allowed as long as you’re careful to not mess up the tree controlled by React.

>Setting the html tag attributes in componentDidMount doesn't always work.

Yes, but you can fix this by using callback refs instead and doing the work in the ref callback. 

```js
    _addDirectory(node) {
      if (node) {
        node.directory = true;
        node.webkitdirectory = true;
      }
    }

    render() {
      return this.context.pending
        ? <input ref={node => this._addDirectory(node)} type='file'/>
        : <div>y</div>;
    }
```

**Comment by sassanh** [comment] 2016-09-10 16:45
Yeah, a good use-case for refs. But this is not the same use-case as above, to keep a reference to a dom element simply to do a manipulation on it later I still prefer string refs over storing it on a variable in class - though I hope I don't need to do that at all, maybe when react is version 1 someday we don't feel the need to use it.

**Comment by fa7ad** [comment] 2016-09-10 17:00
@sassanh react is version 15 right now, so... :confused:

**Comment by sassanh** [comment] 2016-09-10 17:14
Oh I thought it's version .15. I searched react in google and went to https://facebook.github.io/react/ to check it out, then went to my `package.json` file and you're right it's version 15. My bad.

**Comment by gaearon** [comment] 2017-09-08 19:46
This will be supported in React 16.

https://facebook.github.io/react/blog/2017/09/08/dom-attributes-in-react-16.html

**Closed by gaearon** 2017-09-08 19:46 UTC
Labels: Component: DOM, Difficulty: beginner

**Comment by toddobryan** [comment] 2018-10-28 19:12
Is it just me, or is this still not supported in React 16? I'm on ^16.4.18 of React and ^16.0.9 of ReactDOM and I'm having exactly the issues described here.

**Comment by bheptinh** [comment] 2018-12-18 19:15
It works for me if I add empty string

```js
<input directory="" webkitdirectory="" type='file' />
```

**Comment by lw-sassy** [comment] 2020-01-11 06:09
> Yeah I did this:
> 
> ```
>     componentDidMount() {
>         this.refs.x.directory = true;
>         this.refs.x.webkitdirectory = true;
>     }
> ```
> 
> but I just don't like these lines in my code.



> Yeah I did this:
> 
> ```
>     componentDidMount() {
>         this.refs.x.directory = true;
>         this.refs.x.webkitdirectory = true;
>     }
> ```
> 
> but I just don't like these lines in my code.

It's Working

**Comment by softmarshmallow** [comment] 2020-10-07 06:07
> It works for me if I add empty string
> 
> ```js
> <input directory="" webkitdirectory="" type="file" />
> ```

this does not seems to be working..

```
Type '{ directory: string; webkitdirectory: string; type: string; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Property 'directory' does not exist on type 'DetailedHTMLProps<InputHTMLAttributes<HTML
```

**Comment by fa7ad** [comment] 2020-10-07 06:33
@softmarshmallow this might have to do with the typescript typings rather than an issue in React itself. Last I checked, the empty string thing works in normal JavaScript just fine.

**Comment by qkreltms** [comment] 2020-10-22 00:38
@softmarshmallow I was able to fix this issue by doing this ```/* @ts-expect-error */```
```
      <input
        type="file"
        id="dcmFolderSelector"
        multiple
        /* @ts-expect-error */
        directory=""
        webkitdirectory=""
        ref={dicomInputRef}
        onChange={onUploadHandler}
      />
```

**Comment by itsarnavsingh** [comment] 2020-12-16 13:51
I am still facing this issue. no error is thrown. It just doesn't work

**Comment by itsarnavsingh** [comment] 2020-12-16 14:29
In my case, it got fixed by removing styled-components

**Comment by manoharlalitech** [comment] 2022-02-07 11:31
```
declare module 'react' {
  interface InputHTMLAttributes<T> extends HTMLAttributes<T> {
    // extends React's HTMLAttributes
    directory?: string;
    webkitdirectory?: string;
  }
}
```

Use above code after your imports , then you can use both **directory** and **webkitdirectory**

**Comment by bsides** [comment] 2022-02-10 16:47
> ```
> declare module 'react' {
>   interface InputHTMLAttributes<T> extends HTMLAttributes<T> {
>     // extends React's HTMLAttributes
>     directory?: string;
>     webkitdirectory?: string;
>   }
> }
> ```
> 
> Use above code after your imports , then you can use both **directory** and **webkitdirectory**. its works in tsx and jsx files.

Nice one, but I believe the type would be `directory?: boolean | undefined` for each of them (webkitdirectory or mozdirectory too)

**Comment by f-o-w-l** [comment] 2022-12-15 07:02
> 

Nope, it doesn't work with React if you use a boolean.  Who knows when they'll be added to the whitelist, or if React is even still using a whitelist.

**Comment by f-o-w-l** [comment] 2022-12-15 07:02
> > ```
> > declare module 'react' {
> >   interface InputHTMLAttributes<T> extends HTMLAttributes<T> {
> >     // extends React's HTMLAttributes
> >     directory?: string;
> >     webkitdirectory?: string;
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Use above code after your imports , then you can use both **directory** and **webkitdirectory**. its works in tsx and jsx files.
> 
> Nice one, but I believe the type would be `directory?: boolean | undefined` for each of them (webkitdirectory or mozdirectory too)

Nope, it doesn't work with React if you use a boolean. Who knows when they'll be added to the whitelist, or if React is even still using a whitelist.

**Comment by hchauvat-owkin** [comment] 2025-03-14 16:19
This doesn't work on React19
