### ISSUE TITLE
State not updating in realtime

### ISSUE THREAD

**Issue by rohan7chaudhary** [facebook/react#16891] opened 2019-09-25 12:32 UTC
I am updating state in setState() and the page is rendered correctly, but "React Developer Tools" is showing previous state.
Objects and Arrays are updating in realtime but not "boolean / string / number values".
But when I close the dev tools window ( not switching tabs ) and reopen it, then only it shows the updated state.
I don't remember if this was the issue from prev version, but please add realtime state update functionality to it.

**Comment by yasuf** [comment] 2019-09-25 18:48
do you have an example of the issue?

**Comment by rohan7chaudhary** [comment] 2019-09-25 19:33
Hi Yasuf, I have made a video of the issue, hope it will help you in understanding the issue better.
https://drive.google.com/file/d/1kMxzZUfuoQZfEgq1JNrK0pg3VJM3NSPb/view

**Comment by dominiceden** [comment] 2019-09-25 20:02
I'm also experiencing this. Chrome Version 77.0.3865.90 (Official Build) (64-bit), Mac OS X 10.14.6 (18G95), React Developer Tools 4.1.0, React version 16.9.0. The state (as seen in the React DevTools) does not update when the DevTools are open, but closing the Chrome Developer Tools and reopening the React DevTools to inspect the state shows that the state has changed.

**Comment by bvaughn** [comment] 2019-09-25 20:42
Duplicate of #16843

Fix will be going out sometime this afternoon, probably. Sorry for the inconvenience.

**Closed by bvaughn** 2019-09-25 20:42 UTC
Labels: Component: Developer Tools, Resolution: Duplicate

**Comment by dominiceden** [comment] 2019-09-26 06:20
Ah thanks @bvaughn, I didn't see that duplicate issue. Thanks for all your great work, DevTools is a lifesaver.

**Comment by mcgee87** [comment] 2019-11-25 07:49
@bvaughn  Did you ever resolve the issue regarding state not reflecting updates with React DevTools ?

**Comment by dominiceden** [comment] 2019-11-29 13:48
Hi @mcgee87 an update should have been released a while ago - if it's still happening to you, have you tried uninstalling DevTools and reinstalling to ensure you pick up the latest version? Chrome's extension updating mechanism isn't that obvious unfortunately - AFAIK it likes to just update silently in the background.

**Comment by Shameel123** [comment] 2022-08-10 18:44
I am facing the same issue right now.

**Comment by Shameel123** [comment] 2022-08-10 18:45
I am unable to edit the state at all.
Has this issue ever been resolved?

**Comment by iAmZubair00** [comment] 2022-12-21 06:37
this issue is still there in latest version of this extension.
