### ISSUE TITLE
Some means of determining component order in hierarchy

### ISSUE THREAD

**Issue by kierenj** [facebook/react#13084] opened 2018-06-21 12:57 UTC
I apologise for raising this issue again, I'm not intending to be annoying or disrespectful by this, but my previous issue #13034 was closed with a suggestion which I believe not does mitigate the feature request.  I'm simply not aware if I should take the hint and go away, if there's a bit of a backlog and I should hang in there, or if it's been missed.  I'm assuming the latter, but beg forgiveness if that is not the case.  Should you want me to go away I will do so :)  Thanks.

I'm trying to build a container component and child component, whereby the children can sit anywhere in the hierarchy beneath the container, but know their relative order/index within that hierarchy.

My use-case is to build a helper wrapper for CSS grids, allowing subcomponents to themselves render a "row" component which knows it must be the next index, and may or may not progress the row counter for the next "row" component found in order.

I've looked into two possible avenues - recursing using React.Children on the component, which stops when it hits a component without props.children (e.g. a redux-connect()-ed one), and passing some means of counting via context, which fails because it seems the render() methods of the child components isn't always called in "DOM order".

More background here - https://stackoverflow.com/questions/50776933/react-get-component-order-within-hierarchy

It would be great to have some feature in React which might allow for this.

@aweary had previously suggested in #13034 that context could do this with nesting, however I'd raised the thought that this would give an indication of recursion depth, not relative position.

**Comment by gaearon** [comment] 2018-08-02 17:11
This sounds a use case for the "call / return" experiment that we had but deleted (we weren't happy with the API or the implementation). I don't really have anything to offer you right now. Currently, you can only know the order at the time of commit (`componentDidMount`) but by then it's too late to render (unless you're willing to always render in two passes which is slow). Let's keep this open.

**Comment by gaearon** [comment] 2018-08-02 17:14
Actually, going to close as a duplicate of https://github.com/facebook/react/issues/13036.

**Closed by gaearon** 2018-08-02 17:14 UTC
Labels: Type: Feature Request
