### ISSUE TITLE
Bug: react-hooks/rules-of-hooks rule is not applied inside of anonymous/arrow functions passed as an argument

### ISSUE THREAD

**Issue by alina-zaieva** [facebook/react#26901] opened 2023-06-05 09:57 UTC
React version: 17, 18

## Steps To Reproduce

Link to code example: <https://codesandbox.io/s/gallant-minsky-6cmgol?file=/src/App.js>

## The current behavior
When hooks are erroneously used in an anonymous or arrow function that is immediately passed as an argument to another function, these usages are not being detected as errors by `react-hooks/rules-of-hooks`.

## The expected behavior
The rule behavior is the same as for ordinary functions and arrow functions assigned to a variable, where an error is shown.

**Comment by alina-zaieva** [comment] 2023-06-05 10:04
Also seem to be intended, based on this test, so would be great if it was possible to configure this 🙂
https://github.com/facebook/react/blob/e6fae308e9300ca545003ac147cc7e4e541f561c/packages/eslint-plugin-react-hooks/__tests__/ESLintRulesOfHooks-test.js#LL294C29-L294C29

**Comment by MeenuyD** [comment] 2023-06-05 17:53
Hello, I think so which code do you provide the addLogging function itself is a regular function and is not considered a component or hook. It takes a function as an argument and returns a new function. In this case, the arrow function ( ) => {...} is passed as an argument to addLogging, and the resulting function is assigned to createBar3.
Although the arrow function itself is not a component or hook, it is executed within the scope of the returned function from addLogging. Inside this returned function, the func argument is executed, which contains the arrow function and uses the useFoo hook. Same for the createBar4.

**Comment by alina-zaieva** [comment] 2023-06-05 21:01
The implementation of `addLogging` has no effect on the rule in this case though, you can replace it with any function and the result would be the same - hook calls are not considered to be hooks by the rule. As mentioned above, this seems to be by design based on the unit tests, but to me this looks too relaxed as it can cause easily avoidable errors in hooks usage.

**Comment by karol-wons-deel** [comment] 2023-11-07 09:19
Hey,

I've noticed a similar issue when using this rule together with `mobx`.

In this case, I'm not getting any error:

```jsx
import { observer } from 'mobx-react';
import { useEffect } from 'react';

export const Foo = observer(() => {
  if (Math.random() < 0.5) {
    useEffect(() => { // no error
      console.log('yolo');
    });
  }

  return null;
});

```
However, without `observer` it works:
```jsx
import { useEffect } from 'react';

export const Foo = () => {
  if (Math.random() < 0.5) {
    useEffect(() => { // React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render.
      console.log('yolo');
    });
  }

  return null;
};
```

**Comment by bradzacher** [comment] 2023-12-12 00:08
As a side note - you can work-around this issue by using a non-anonymous function expression, eg:
```diff
- const Foo = observer(() => {
+ const Foo = observer(function Foo() {
    // ...
  });
```

Though the migration for an existing codebase to apply such a workaround is quite a major effort.

**Comment by rickhanlonii** [comment] 2024-01-29 16:29
Dupe of https://github.com/facebook/react/issues/14404

**Comment by rickhanlonii** [comment] 2024-01-29 16:39
Sorry, no this is different and still broken.

**Comment by rickhanlonii** [comment] 2024-01-29 16:49
Yeah, here's the right dupe: https://github.com/facebook/react/issues/22520

**Closed by rickhanlonii** 2024-01-29 16:49 UTC
Labels: Status: Unconfirmed

**Comment by scamden** [comment] 2024-04-26 17:27
the dupe was closed but this is still definitely an issue: 

for example when using jotai it's really easy for a dev to accidentally think they can use a hook and it's not caught:
```ts
export const atomBiSavedViewExamples = atom(
  async (get) => {
   // no error here..
    const showWatershedSavedViewTemplates = useFeatureFlag(
      'myFlag'
    );
   //...etc
});
```
