### ISSUE TITLE
invalid unitless properties

### ISSUE THREAD

**Issue by Kflash** [facebook/react#6347] opened 2016-03-26 13:05 UTC
I noticed that some of the unitless properties are invalid. E.g. when the 'o' prefix are added to the style name, some of the style names are converted into `OOpacity`, `OOrder`, `OOrphans` and some other weird names.

And some of the prefix are not needed anymore for some of the unitless properties.

**Comment by Aweary** [comment] 2016-03-26 15:51
Can you provide a code sample (like a JSBin) reproducing this?

**Comment by Kflash** [comment] 2016-03-26 16:10
Just use `console.log` on the `isUnitlessNumber` and take a look at the output in the console. All properties are listed there, and if you scroll you will see the properties I mentioned plus some other weird props

**Comment by gaearon** [comment] 2016-03-26 17:34
[`isUnitlessNumber` checks for different browser prefixes](https://github.com/facebook/react/blob/dcd092560da72d6435b4c941ee7bf58b6d648903/src/renderers/dom/shared/CSSProperty.js#L66-L70) but this doesn’t affect the actual used style name. Putting a `console.log()` there and seeing invalid property names is expected and doesn’t mean those invalid property names are actually being used anywhere other than those checks.

I’m closing because this appears to work as designed: we do extra checks just to be careful and to avoid hardcoding every possible prefix permutation. **If you see incorrect behavior for specific properties**, please provide a JSFiddle reproducing it, and we will be happy to reopen and inspect it.

But if you’re just worried that `isUnitlessNumber` performs tests on invalid names—that’s just a tradeoff that lets us avoid keeping a much larger whitelist.

**Closed by gaearon** 2016-03-26 17:34 UTC
