### ISSUE TITLE
Custom Renderer API Support

### ISSUE THREAD

**Issue by iamdustan** [facebook/react#7850] opened 2016-10-03 14:50 UTC
I’m working through upgrading some renderers and documentation to the current master build (installing from http://react.zpao.com/builds/master/latest/).

From following along I knew there were some hard breaking changes I wanted to begin a discussion on what commitments React is willing to make at this time to support this use case.

Rather than trying to figure all of the current APIs needed up front I’d like to begin this by looking at the `Mount* entry point and discuss what APIs could be exposed and which should be covered in other APIs.

## ReactMount

[ReactMount](https://github.com/facebook/react/blob/eaefd9052ae41d3318a2add286828a75da362193/src/renderers/dom/client/ReactMount.js), [ReactNativeMount](https://github.com/facebook/react/blob/1c5a639c37039a9c60752980dfee168129b76b32/src/renderers/native/ReactNativeMount.js), and [ReactTestMount](https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/src/renderers/testing/ReactTestMount.js) are the entry points to three Facebook/React supported renderers. They all live in this codebase and have first class access to a number of internals that external renderers do not currently get.

Specifically, a few modules that each access are:

* [`ReactReconciler`](https://github.com/facebook/react/blob/dd0c65c6aa7c80eeeb0783e29bef89399b5796af/src/renderers/shared/stack/reconciler/ReactReconciler.js)
* [`instantiateReactComponent`](https://github.com/facebook/react/blob/dd0c65c6aa7c80eeeb0783e29bef89399b5796af/src/renderers/shared/stack/reconciler/instantiateReactComponent.js) a helper function to create the correct React Component type (host, composite, text, ...). Also a part of the reconciler
* [`ReactUpdates`](https://github.com/facebook/react/blob/a3e576e1bb80f674fa685966ce415fc65238638c/src/renderers/shared/stack/reconciler/ReactUpdates.js) : my understanding is this is a part of ReactReconciler
* [`ReactInstrumentation`](https://github.com/facebook/react/blob/0d927844fba35df4956e904fdb33e2f7a034eace/src/renderers/shared/ReactInstrumentation.js) bridge between React internals and devtools (not limited to just the [React DevTools](https://github.com/facebook/react-devtools/)

(There are a few other modules that I see used between FB and my own renderers beyond these that may be worth future consideration, though these are what I understand to be the most important to unblock renderer development.)

My understanding is that a renderers `Mount` method is dependent upon the reconciler to bridge the renderer semantics to React core. The reconciler has become effectively private and non-shareable with the recent build changes.

What can be done today to allow renderers to continue existing and experimenting in the 16.x release cycle?

A few initial ideas to get feedback on for possible direction (if any) would be acceptable. With both of these ideas comes developer/console warnings that this is an unsupported and non-guaranteed API that could break at any moment including patch releases:

* Expose minimal Reconciler surface area
* Create a `ReactReconciler` package

**Comment by gaearon** [comment] 2016-10-03 15:02
I think the intention is to move towards Fiber (#6170) which has a completely different API that does not use classes, today’s `ReactReconciler`, and friends. [Fiber reconciler](https://github.com/facebook/react/blob/f6fdfd1bf0d13e51098a6009c2c85687b1245c9b/src/renderers/shared/fiber/ReactFiberReconciler.js) is intentionally written with opaque targets in mind so that it’s decoupled from day one and can be exposed as a package once it’s mature without all the pitfalls we have today caused by shared state between renderers, like #7386.

In the meantime, if you work on a custom renderer, I think you are encouraged to ship a copy of React reconciler. At least this is what React Native will do as far as I know. This means you aren’t affected by breaking changes in React repo master and can update your renderer at any time. It complicates setting up a custom renderer (you’ll need a script to keep your reconciler fork in sync with React repo) so it would be cool if somebody contributed that for RN and then other renderers could use that. It is not meant to be a long-term solution, but neither is our current renderer architecture.

**Comment by iamdustan** [comment] 2016-10-03 15:10
Yeah, I’m looking for something to maintain through the 15.4/16 release cycle primarily knowing that Fiber will change the world. It sound like you’re saying you’d rather see a hack from the community to sync the React Reconciler code *out of* this codebase (something that React Native can avoid by being in this repo) rather than expose something explicitly between the new build format being released and Fiber becoming official and stable?

**Comment by gaearon** [comment] 2016-10-03 15:22
>It sound like you’re saying you’d rather see a hack from the community to sync the React Reconciler code out of this codebase (something that React Native can avoid by being in this repo)

React Native doesn't plan to avoid it. On the opposite, there is an open diff for React Native to ship a copy of the reconciler that will be manually synced just like I described. This lets RN team experiment with changing the renderer code, and sync it at their own pace.

Exposing the renderer as a package has pitfalls, the most significant one being unintentionally shared state between different renderers, like in #7386.

**Comment by iamdustan** [comment] 2016-10-03 15:38
Do you have a link to that open diff by chance? I couldn’t find it in my browsing of https://github.com/facebook/react-native/pulls

**Comment by gaearon** [comment] 2016-10-03 15:40
I don't think it was submitted as a PR, more likely as an internal diff 😞 .
@yungsters Do you have any updates on getting it merged?

**Comment by gaearon** [comment] 2016-10-27 13:03
I'll close as there are no plans to take extra steps to support custom renderers for stack reconciler while we're changing everything in Fiber. Fiber will have a first-class custom renderer support.

**Closed by gaearon** 2016-10-27 13:03 UTC

**Comment by sompylasar** [comment] 2017-01-02 08:55
Linking for future readers just for reference:
* https://twitter.com/dan_abramov/status/801782049963175936
* https://github.com/facebook/react/blob/7d2be2c9a7b4a976e20d2d7c312b43b1bee01a07/src/renderers/dom/fiber/ReactDOMFiber.js#L63-L150

**Comment by leoselig** [comment] 2017-08-23 21:00
@gaearon 
With the first beta releases of Fiber going out I was wondering if the custom renderer is documented somewhere already or if there is any place to track progress of it.

Your [much quoted tweet](https://twitter.com/dan_abramov/status/801782049963175936) gave some great outlook already but it seems somewhat outdated by now and not sufficient to actually start digging into the topic

**Comment by sompylasar** [comment] 2017-08-23 21:11
@leoselig Related: https://github.com/diegomura/react-pdf/blob/46a8b0e04659d52a4d41eaa3187879aff0d4bcf9/packages/react-pdf/src/renderer.js#L3-L123
