### ISSUE TITLE
[DevTools Bug]: not sure if bug or  not:  devtools marks Youtube as built with react.

### ISSUE THREAD

**Issue by bmwasonga** [facebook/react#23124] opened 2022-01-16 14:57 UTC
### Website or app

https://www.youtube.com/

### Repro steps

I was watching a video on youtube when I noticed the new video hover features which were not there on the 15th of January 2022. 
This then led me to the react dev tools which I noticed had turned blue, never had before. wanted to know of this is a bug or not. 
I have restarted my computer and browser severally.

[](url
![tube](https://user-images.githubusercontent.com/65865227/149665223-b3243940-c1b0-418f-bfba-a8ca9eebb885.png)
)

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment] 2022-01-16 17:56
This bug is caused by Redux DevTools: https://github.com/zalmoxisus/redux-devtools-extension/issues/829

Duplicate of #23107

**Closed by bvaughn** 2022-01-16 17:56 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools
