### ISSUE TITLE
Bug: react-test-renderer provides no equivalent to attachTo option of Enzyme, mandatory to snapshot Leaflet and other

### ISSUE THREAD

**Issue by eric-burel** [facebook/react#20590] opened 2021-01-14 15:47 UTC
React version: 16.13.1

## Steps To Reproduce

1. In a project with React, and react-leaflet@2.7.0
2.
```ts
import React from "react";
import Renderer from "react-test-renderer";
import { Map, TileLayer } from "react-leaflet";

let component = Renderer.create(
    <Map>
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
    </Map>
  );
```

Link to code example: https://codesandbox.io/s/react-test-renderer-leaflet-mohzp

## The current behavior

It raise an error `Map container not found.`

## The expected behavior

Enzyme's `attachTo` option allow to mount the comment in a more realistic environment, which fixes this bug. But there is no equivalent feature in `react-test-renderer` as far as I know.

See https://github.com/PaulLeCam/react-leaflet/issues/246 for more info about the Enzyme fix for this issue.

It should render the map as expected.

**Comment by eps1lon** [comment] 2021-01-15 10:35
Duplicate of https://github.com/facebook/react/issues/20589

**Closed by eps1lon** 2021-01-15 10:35 UTC
Labels: Status: Unconfirmed
