### ISSUE TITLE
Cannot read property 'getHostNode' of null

### ISSUE THREAD

**Issue by kevart** [facebook/react#8579] opened 2016-12-15 05:23 UTC
*feature request*

**What is the current behavior?**
_Cannot read property 'getHostNode' of null_

**What is the expected behavior?**
An error message that tells me what is wrong so I know what to fix.

**"react": "15.3.2"**

**Comment by TeanWang** [comment] 2016-12-15 06:18
#Duang

**Comment by gaearon** [comment] 2016-12-15 12:06
Please see https://github.com/facebook/react/issues/8267.
This usually means React is an inconsistent state caused by an *earlier* error in your code.
If you don't see this error it might be because you have a `catch` block silently swallowing it.

Related explanations: https://github.com/facebook/react/issues/7617#issuecomment-247710003, https://github.com/facebook/react/issues/4199#issuecomment-246196341.

If you’re sure this is not the problem please provide a reproducing example.

**Comment by aweary** [comment] 2016-12-20 04:55
Closing as there's been no update and it's likely related to #8267. @kevart if provide a case reproducing the issue we can look into re-opening it if its identified as a different issue.

**Closed by aweary** 2016-12-20 04:55 UTC
Labels: Status: Unconfirmed

**Comment by AjayU** [comment] 2017-05-31 17:03
Getting this error in IE. The build application works fine in mozilla and chrome. Moreover, the standalone express server app runs fine too in IE but the built js file using webpack and babel fails to navigate when used inside of a jsp file

**Comment by bhgames** [comment] 2017-06-06 22:31
Same here @AjayU

**Comment by bhgames** [comment] 2017-06-07 12:29
@AjayU I discovered it was because I was using for(let key of something) { } loops in my code. Apparently this isn't polyfilled properly. Replacing them with .map({})'s worked. Had nothing to do with react-router - it was just that was firing the render call that caused the error to happen.

**Comment by vTrip** [comment] 2017-06-19 07:21
this issue occurs for me specifically when using `setState`

**Comment by gaearon** [comment] 2017-06-19 13:47
Please read this comment https://github.com/facebook/react/issues/8579#issuecomment-267312367.
When you see this issue without a descriptive error before it, your code is swallowing errors.

**Comment by gaearon** [comment] 2017-07-27 10:35
A small update on this. We just released [React 16 beta](https://github.com/facebook/react/issues/10294) which shouldn’t emit cryptic errors like this one. Even if the application code swallows an error, React 16 will still print it to the console. It might be too early for you to try React 16 (since ecosystem is still preparing for it), but this error should never occur in the future after you switch to it.
