### ISSUE TITLE
inline style with decimal numbers

### ISSUE THREAD

**Issue by cvlmtg** [facebook/react#11532] opened 2017-11-12 11:12 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If the style prop is passed a decimal number, react converts the dot in a comma, resulting in an invalid css value. I suspect this might be due to my locale being different from english, but the behavior should be the same irregardless of the user's locale (and the conversion is correct if I use `String(12.34)`)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

https://jsfiddle.net/ab4zx24r/3/

<img width="150" alt="schermata 2017-11-12 alle 12 12 46" src="https://user-images.githubusercontent.com/6401008/32698272-e74979de-c7a2-11e7-8005-0e1b6c695916.png">

**What is the expected behavior?**

decimal numbers should be always converted with a dot

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react version: 16.x.0
os: macos 10.13.1
browsers:
  * chrome 62
  * safari 11.0.1

firefox 58.0 beta 1 is unaffected

**Comment by gaearon** [comment] 2017-11-12 13:59
Nice find. Definitely seems like a bug.

**Comment by gaearon** [comment] 2017-11-12 13:59
Did this work in React 15.x?

**Comment by sjy** [comment] 2017-11-12 14:14
I'd like to make a pr for this bug.

**Comment by cvlmtg** [comment] 2017-11-12 16:52
@gaearon not sure about react 15.x, I should do a test. I found it on an app I've started developing recently, so it used react 16.x from day one.

@sjy 

```
window.navigator.language
"it"
window.navigator.languages
(4) ["it-IT", "it", "en", "en-US"]
```

**Comment by cvlmtg** [comment] 2017-11-12 17:10
@gaearon I've modified my previous fiddle to include react 15.6.x instead of react 16.x

https://jsfiddle.net/ab4zx24r/4/

it seems the bug is still there (plus the deprecation message about passing a value as a string)

**Comment by oxlay** [comment] 2017-11-13 21:47
I tried but could not reproduce this on macOS 10.12.6, with Chrome 62 and Safari 11.0.1, even after changing the locales to those you suggested @cvlmtg. Could this be a High Sierra-related bug?

**Comment by gaearon** [comment] 2017-11-13 21:54
Regardless, worth checking how we serialize string values, and then google if locale can affect those methods. :-)

**Comment by cvlmtg** [comment] 2017-11-14 09:28
@oxlay could it be related to the OS language rather than the browser config? as soon as I have some spare time I'll try to set the browser config to just plain english and see if I still have the same bug.

**Comment by sjy** [comment] 2017-11-14 16:19
I have go through the related code,  [CSSPropertyOperations](https://github.com/facebook/react/blob/HEAD/packages/react-dom/src/shared/CSSPropertyOperations.js), it seems the problem has nothing to do with react-dom or react itself. 
Besides, I found a interesting issue of Electron reporting the similar issue caused by specific version of Chromiums ; [Decimals numbers in styles are formatted incorrectly](https://github.com/electron/electron/issues/8825) .
Some guys have report the issue to Chromiun, [chromium-717216](https://bugs.chromium.org/p/chromium/issues/detail?id=717216) and (623347)[https://bugs.chromium.org/p/chromium/issues/detail?id=623347].
@cvlmtg I did't make to reproduce the issue, please upgrade your Chrome and try to see if the case happens again.

**Comment by oxlay** [comment] 2017-11-14 17:28
I reviewed the relevant code as well and couldn't find any part that may be problematic.

However I finally managed to reproduce the bug by launching Chrome from the CLI (thanks @sjy for the findings, that led me in the right direction). From my tests, it looks like that the bug is not related to the OS language setting but rather to the LANG environment variable :

- When `LANG` is set to `en_US.UTF-8`, the bug does not appear
- When `LANG` is set to `fr_FR.UTF-8`, `it_IT.UTF-8` or `ru_RU.UTF-8` for instance (I didn't try others), the bug appears

I couldn't reproduce it (yet) with Safari.

@cvlmtg are you launching Chrome/Safari from the CLI ? And can you confirm your `LANG` environment variable is `it_IT.UTF-8`?

**Comment by cvlmtg** [comment] 2017-11-14 20:51
@sjy 

my chrome is 62.0.3202.89, so it's already at the latest version

@oxlay

<img width="149" alt="schermata 2017-11-14 alle 21 35 26" src="https://user-images.githubusercontent.com/6401008/32803437-c37689a6-c983-11e7-808f-7a5a3c1a0fd9.png">

yes, LANG is set to 'it_IT', but I do not launch chrome from the cli, I run it from the finder like any other app.

Anyway, just out of curiosity, is the function that turns numbers in "px" values `dangerousStyleValue`? what baffles me is that if I try to turn a number into a string from the console it works... I've added to the fiddle this simple code

```
  const t1 = String(12.34);
  const t2 = 12.34 + 'px';
```

and this is the result

<img width="389" alt="schermata 2017-11-14 alle 21 48 31" src="https://user-images.githubusercontent.com/6401008/32803995-af3723cc-c985-11e7-8320-14b8e575a4e0.png">

**Comment by maxviewup** [comment] 2017-12-11 13:48
same issue here.

**Comment by gaearon** [comment] 2018-01-05 21:09
Closing as a browser issue per the above discussion. If someone finds it related to React please file a new one with two examples (React and non-React ones) so we can see what React is doing wrong.

**Closed by gaearon** 2018-01-05 21:09 UTC
Labels: Component: DOM, Difficulty: beginner, good first issue (taken), Type: Bug

**Comment by maxviewup** [comment] 2018-01-08 10:44
@gaearon maybe this is really an chrome issue, but maybe react is using something that leads to this...

**Comment by gaearon** [comment] 2018-01-08 13:22
We don't keep issues forever open because *maybe* something is wrong :-)

If you want to investigate why this happens, please help. So far people investigated and couldn't find anything in React, but *did* find browser issues. I don't see a reason to keep the issue open unless you see a specific thing we're doing wrong in React (in which case we'd be happy to take a fix).
