### ISSUE TITLE
React 18: It's time learn VUE3.0!

### ISSUE THREAD

**Issue by SaltFish001** [facebook/react#23404] opened 2022-03-03 06:42 UTC

**Comment by devcui** [comment] 2022-03-03 07:03
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/26159886/156513417-46f0c69d-004e-47d9-966d-f585de1b0fa1.png">

I feel bad that React is very political, and the spirit of open source shouldn't be.

**Comment by SaltFish001** [comment] 2022-03-03 07:05
Same on Node.js.

**Comment by cnmade** [comment] 2022-03-03 07:05
and please support new suggest:
https://github.com/facebook/react/issues/23403

**Comment by eps1lon** [comment] 2022-03-03 07:05
Duplicate of https://github.com/facebook/react/issues/23402

**Closed by eps1lon** 2022-03-03 07:05 UTC
Labels: Type: Discussion, React 18

**Comment by SaltFish001** [comment] 2022-03-03 09:48
> ![JPG_20220303_174478](https://user-images.githubusercontent.com/100838287/156539053-0799fde8-7188-44e4-a6df-b7d848787157.jpg)

这是他个人问题, 不用上升到Vue
他自己也回应过
https://github.com/vuejs/vue/pull/12483
