### ISSUE TITLE
Error: "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by sumedh0803** [facebook/react#21407] opened 2021-05-01 23:58 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.13.0-2a7bb41548

Call stack: at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20601:53)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)
    at walkTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20632:30)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35634:34)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29016:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37064:34)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30336:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30416:5)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34462:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25252:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25855:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30558:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37572:3)

**Comment by bvaughn** [comment] 2021-05-02 13:47
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-05-04 13:38
Closing due to lack of repro info.

**Closed by bvaughn** 2021-05-04 13:38 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
