### ISSUE TITLE
 TestUtils.renderIntoDocument difference between 0.12 and 0.13 when render returns null/false

### ISSUE THREAD

**Issue by cesarp** [facebook/react#3453] opened 2015-03-18 20:02 UTC
TestUtils.renderIntoDocument has a different behavior between react 0.12 and 0.13 when your component render method returns false or null. 

```
var myComponent = TestUtils.renderIntoDocument(<MyComponent flag={false}/>);
var noscript = TestUtils.findRenderedDOMComponentWithTag(myComponent, 'noscript');

expect(noscript).toBeTruthy();
```

This fails in react 0.13 (Error: Did not find exactly one match for tag:noscript) but it works in 0.12, am I doing something wrong?

Repo with test case, just switch the version in package.json.
https://github.com/cesarp/react-test-demo

**Comment by aweary** [comment] 2017-09-20 00:25
Hey ,@cesarp, I'm sorry we never responded to your issue. Sadly, issues fall through the cracks sometimes. Since it's been over two years and almost 3 major releases, I'm going to close this out, since a regression between 0.12 and 0.13 is no longer a concern.

If you have an issue with the current behavior of `renderIntoDocument` feel free to open another issue with an updated repro, and I'll be happy to look at it.

Thanks!

**Closed by aweary** 2017-09-20 00:25 UTC
