### ISSUE TITLE
Bug: Unnecessary re-render

### ISSUE THREAD

**Issue by behnammodi** [facebook/react#18719] opened 2020-04-23 17:38 UTC
![y](https://user-images.githubusercontent.com/1549069/80130965-bb377900-85ae-11ea-9ccf-0050af4f5d81.gif)

React version: 16.13.1

## Steps To Reproduce
1- The first render is correct 
2- The second re-render is correct because `X` changes from `1` to `2`
3- The third re-render in the wrong 

Link to code example:
https://codesandbox.io/s/bug-in-render-ldycb

## The current behavior
The third re-render is unnecessary but happen

## The expected behavior
The third re-render should not happen

**Comment by eps1lon** [comment] 2020-04-23 18:15
Does this happen with the production build as well? I'm asking because it doesn't actually commit when transitioning from 2->2.

You can observe this wrapping the (side-effect) in `useEffect`:
```js
React.useEffect(() => {
  console.log("render App", x);
})
```

**Comment by eps1lon** [comment] 2020-04-23 18:19
Also: Probably a duplicate of #14994

**Comment by behnammodi** [comment] 2020-04-23 18:21
@eps1lon Yes It's happen

**Comment by eps1lon** [comment] 2020-04-23 18:28
Fairly certain this is a duplicate of #14994. `Child` won't re-render on the 2->2 transition: https://codesandbox.io/s/bug-in-render-ubppr?file=/src/index.js

**Comment by behnammodi** [comment] 2020-04-23 18:32
@eps1lon Thanks

**Comment by eps1lon** [comment] 2020-04-23 18:38
> @eps1lon Thanks, but every solution is awful.

I can understand why this might be undesired behavior for you. But this won't get solved by keeping duplicate issues open which require maintenance from the core team.

It also helps keeping the discussion focused so that potential workarounds aren't spread over the repository.

**Comment by behnammodi** [comment] 2020-04-23 18:41
@eps1lon All right, I'll close it

**Closed** 2020-04-23 18:43 UTC
Labels: Status: Unconfirmed
