### ISSUE TITLE
warnings use console.error instead of console.warn

### ISSUE THREAD

**Issue by piyushgarg195** [facebook/react#16123] opened 2019-07-12 16:55 UTC
warnings use console.error instead of console.warn

**Comment by threepointone** [comment] 2019-07-12 19:27
Yes, that’s by design. Any specific problem?
We occasionally use console.warn for “low priority” warnings too. 

Closing since this isn’t a bug or feature request.

**Closed by threepointone** 2019-07-12 19:27 UTC
