### ISSUE TITLE
Bug: React hooks are broken when using as submodule with nodemodules installed

### ISSUE THREAD

**Issue by ljmerza** [facebook/react#24662] opened 2022-06-02 17:47 UTC
If using a component that has a hook from a submodule, react thinks the component is being called as a function

```
react.development.js:207 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

React version:
18.1.0

## Steps To Reproduce

- Pull this branch https://github.com/ljmerza/react-error then pull the submodules `git submodule update --init --recursive`. 
- run `npm ci` inside the src/submod folder (the submodule)
- run `npm ci` in the root folder. 
- Run `npm start` and try to go to the home page

if i skip step 2 then it works but if using typescript, the submodule may have typings that the parent repo doesnt have so you need to run `npm ci` inside the submodule in this instance.

Link to code example:
https://github.com/ljmerza/react-error

**Comment by eps1lon** [comment] 2022-07-17 07:46
Your app and component library probably have each a version of React installed. Libraries should declare React in `peerDependencies` and apps should make sure you only have a single version installed (hence the "You might have more than one copy of React in the same app" error).

Duplicate of https://github.com/facebook/react/issues/13991

**Closed by eps1lon** 2022-07-17 07:46 UTC
Labels: Resolution: Duplicate, Status: Unconfirmed
