### ISSUE TITLE
ReactTransisitionGroup doesn't allow the option to append or prepend a child to siblings

### ISSUE THREAD

**Issue by mutley** [facebook/react#6369] opened 2016-03-29 14:54 UTC
The ReactTransistionGroup assumes that children should be prepended to their siblings when inserted into the parent. I think we should add an optional prop that allows configuration to prepend or append children. I have working code I can submit a pull request I just wanted to make sure I wasn't missing something.
```
childrenToRender.push(React.cloneElement(
  this.props.childFactory(child),
  {ref: key, key: key}
));
```
https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js#L215-L218

**Comment by gaearon** [comment] 2016-03-29 14:59
Thank you for reporting! I believe this to be a duplicate of #6142 so I’m closing. Feel free to join the discussion there or in #6149.

**Closed by gaearon** 2016-03-29 14:59 UTC
