### ISSUE TITLE
Is it possible to make React.Component / React.StateComponent

### ISSUE THREAD

**Issue by jEnbuska** [facebook/react#10082] opened 2017-06-30 19:49 UTC
Feature:
I would like to represent the application state and state validation using JSX.
Instead of defining context/redux state using reducers, It would be nice if it was possible to create components that on result data on 'render'. 
'render' is not the most descriptive name because I do not mean to represent UI, but what I'm mostly interested in is using react lifecycle methods and recursive update on setState.

Currently when setState is called to a React.Component the renders are not instant, and this is troublesome for me:

Example case:
```
//this represents application-/context-state
<Obj name='appState>
  <Obj name='cars'>
    <Obj many>
      <Bool name='pending'/>
      ['id','brand', ... ].map(name= > <Str name={name} key={name} />)
   </Obj>
  </Obj>
  ...
</Obj>
```

```
//this represents actions like with react-redux
function addACar(car){
 return function(appState){
   const {cars} = appState;
   const id = createId();
   car.setState({[id]: {...car, id}});
   const newCar = car[id];
   newCar.setState({pending: true});   //!!!newCar is not defined YET
 }
}
```

Is it possible to make Components to render recursively when setState gets called, before the next line of code gets executed to avoid the situation represented above?

_Needing a **document** to 'render' into is a whole other issue, but for now, I will just use span:s with 'display: none' to get around issue with rendering invalid elements into DOM._

**Comment by aweary** [comment] 2017-07-05 22:38
Hey, @jEnbuska! It sounds like you're requesting that React begins rendering synchronously after a `setState` call is made. This would likely introduce performance regressions and doesn't work well with Fiber, which takes the opposite direction by embracing asynchronous, dynamically scheduled render cycles.

With that in mind, I'm going to close this out since this isn't a change that's likely to be made at the moment. You can try to get around this by managing your own queue of updates outside of React's render cycles. 

Hope that helps!

> Needing a document to 'render' into is a whole other issue, but for now, I will just use span:s with 'display: none' to get around issue with rendering invalid elements into DOM.

You can return `null` from components that you don't want rendering to the DOM!

**Closed by aweary** 2017-07-05 22:38 UTC
