### ISSUE TITLE
Bug: Prop with name "is" breaks the className prop on tag

### ISSUE THREAD

**Issue by marceloadsj** [facebook/react#17944] opened 2020-01-31 15:42 UTC
If you add a prop named "is" together with a "className" prop, on a html tag component
(e.g. `<div is="p" className="text-red">`) it "breaks" the markup and render an attribute "classname" instead of "class".

React & React DOM version: 16.12.0

## Steps To Reproduce

1. Write a simple component that render a html tag
2. Add a prop named "is" and a "className"
3. Check the rendered markup

Link to code example: https://codesandbox.io/s/quiet-sun-535rg

Example:
`<div is="p" className="text-red">I'm not red</div>`

## The current behavior
Injecting the props as html attrs.

Markup:
`<div is="p" classname="text-red">I'm not red</div>`

## The expected behavior
Markup:
`<div is="p" class="red">I'm red</div>`

**Comment by michalczaplinski** [comment] 2020-02-02 02:54
If you set an `is` prop on a react component, react treats it as a [Custom Element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements). 

https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/isCustomComponent.js#L12

Because of this, props like `className` or `htmlFor` are not translated to `class` and `for` because you might have an attribute with that same name (like `className` or `htmlFor`) used by your custom element.

The documentation mentions this briefly https://reactjs.org/docs/web-components.html
> One common confusion is that Web Components use “class” instead of “className”.

I can agree that it's def a bit confusing 😅

**Comment by bvaughn** [comment] 2020-02-03 00:37
@michalczaplinski is correct! The `is` attribute is an HTML standard thing:

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/is

> The **is** global attribute allows you to specify that a standard HTML element should behave like a defined custom built-in element (see Using custom elements for more details).

In this case, I think React DOM is behaving reasonably (although I understand why it could be a bit surprising too)

**Comment by bvaughn** [comment] 2020-02-03 00:41
This issue has come up a few times in the past:
* #12810
* #8419
* #7200

Dan's comment seems inline with ours above:
https://github.com/facebook/react/issues/7200#issuecomment-230780250

There's also been some extensive discussion about the `className` property on web components here: #4933

Our web component docs suggest using a `class` attribute in such cases, as confirmed by [this comment](https://github.com/facebook/react/issues/4933#issuecomment-256664482).

I'm going to close this issue since I think it's all been discussed before :smile:

**Closed by bvaughn** 2020-02-03 00:41 UTC
Labels: Status: Unconfirmed

**Comment by marceloadsj** [comment] 2020-02-03 06:18
Maybe would be good to have a section on docs saying about this. What do you think?

It's hard to search because of the word "is", so, if we add a FAQ explaining, it will avoid that kind of issues being opened.

I just opened because I didn't find anything on docs or github issues, searching for keywords like "prop html tag is className attribute".

:)

**Comment by bvaughn** [comment] 2020-02-03 15:46
Sure, if you have ideas for how to improve the docs page send them our way.

This page:
https://reactjs.org/docs/web-components.html

Is here:
https://github.com/reactjs/reactjs.org/blob/master/content/docs/web-components.md

**Comment by shadowboxflynn** [comment] 2025-10-17 15:53
> This issue has come up a few times in the past:
> 
> * ["is" on <button> causes "className" to translate to "classname" not "class" #12810](https://github.com/facebook/react/issues/12810)
> * [className doesn't work with `is` attribute is present #8419](https://github.com/facebook/react/issues/8419)
> * [Weird behaviour when 'is' prop is present #7200](https://github.com/facebook/react/issues/7200)
> 
> Dan's comment seems inline with ours above: [#7200 (comment)](https://github.com/facebook/react/issues/7200#issuecomment-230780250)
> 
> There's also been some extensive discussion about the `className` property on web components here: [#4933](https://github.com/facebook/react/issues/4933)
> 
> Our web component docs suggest using a `class` attribute in such cases, as confirmed by [this comment](https://github.com/facebook/react/issues/4933#issuecomment-256664482).
> 
> I'm going to close this issue since I think it's all been discussed before 😄





https://shrew565.github.io/bYFEzpvCkR/
