### ISSUE TITLE
Event dispatch fails after unmounting

### ISSUE THREAD

**Issue by vsiao** [facebook/react#7733] opened 2016-09-14 21:47 UTC
**What is the current behavior?**
Repro: https://jsfiddle.net/s8fg30fx/
- Click "Click Me!"
- Fails with "React DOM tree root should always have a node reference."

**What is the expected behavior?**
No failure, and event dispatch stops.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.3.1, Chrome 52+ OS X
Not certain if this has worked before.

Maybe related: #7103 and #7661

**Comment by zpao** [comment] 2016-09-14 22:29
cc @spicyj @sebmarkbage

**Comment by sebmarkbage** [comment] 2016-09-14 22:57
If you do this in the DOM you would get both events fired. Similarly if we defer DOM operations to a later schedule, that's also what would happen. I think that's the semantics we would want for this. Not a super high priority to fix this though.

The solution is to call `event.stopPropagation();` in the inner handler.

**Comment by spicyj** [comment] 2016-09-14 23:00
Dupe of #3298 I guess.

**Closed by spicyj** 2016-09-14 23:00 UTC
