### ISSUE TITLE
[DevTools Bug]: Component tree panel becomes unresponsive after clicking on a few components

### ISSUE THREAD

**Issue by Aaron-Ennis** [facebook/react#24626] opened 2022-05-26 22:56 UTC
### Website or app

Multiple; but you can check at https://react-bootstrap.github.io/

### Repro steps

1. Access a website in Chrome that uses React.
2. Open Chrome Developer Tools
3. Open the React Developer Tools Components tab/panel
4. Click on 5 - 10 components in the component tree individually to inspect them

Notes: 

- This started happening on all React-based websites after updating to Chrome Version 102.0.5005.61 on my work MacBook (x86_64) and my personal MacBook (arm64). Reverting back to Chrome 100 seems to help.
- I had a co-worker test as well, with the same result.
- You can still select individual components using the picker, even after the panel locks up.
- The lock-up seems to happen quicker when `Expand component tree by default` is selected in the `Components` tab in the panel settings, but will still lock up if you manually expand enough components.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.24.6 (5/12/2022)

### Error message (automated)

None

### Error call stack (automated)

N/A

### Error component stack (automated)

N/A

### GitHub query string (automated)

N/A

**Comment by gomo-psivarh** [comment] 2022-05-27 02:58
Same problem here.

Chrome version 102.0.5005.62 on Windows 10

**Comment by cham11ng** [comment] 2022-05-27 06:23
Facing the same problem.
(Version 102.0.5005.61 (Official Build) (64-bit).

**Comment by cike8899** [comment] 2022-05-27 13:38
Facing the same problem.
(Version 102.0.5005.61 (Official Build) (64-bit) on Mac.

**Comment by mondaychen** [comment] 2022-05-27 16:14
I can reproduce this issue on Chrome Canary (v104) but not on v101. Not sure what has changed on Chrome since v102.
@bvaughn can you help investigate?

**Comment by bvaughn** [comment] 2022-05-27 16:30
Probably not any time soon. I'm pretty swamped at the moment.

**Comment by jennazee** [comment] 2022-05-27 21:16
I found that the unresponsiveness happens after scrolling, and that inspecting the flamegraph container itself and removing `pointer-events: none` from the `<svg>` makes it responsive again. I don't have the bandwidth to do the fix, but from the source I see in the extension, this might get thrown on the container while scrolling, so something is maybe making it think we're still scrolling? Hopefully someone can take this and run with it!

**Comment by Aaron-Ennis** [comment] 2022-05-27 21:46
@jennazee Good catch re: scrolling. I can click around in the component tree to my heart's content, as long as I don't scroll in the component tree panel.

**Comment by mondaychen** [comment] 2022-05-28 03:18
Thanks @jennazee and @Aaron-Ennis. Yes, I think this is related to scrolling. The component panel uses a `<FixedSizeList>` from [react-window](https://github.com/bvaughn/react-window), which sets `pointerEvents` to `none` when scrolling. 
https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js#L365
My guess is that for some reason the `isScrolling` state is no longer correctly set back to `false`

**Comment by mondaychen** [comment] 2022-05-28 03:29
It's quite strange that when I'm testing the inline version of devtools, this issue does not exist. This might be an extension-only issue.
Before we figure this out and release a fix, if you've already upgraded to Chrome v102 or above, as far as I know it would not be easy to downgrade. You can consider use Firefox for now, or use the [standalone DevTools app](https://github.com/facebook/react/tree/main/packages/react-devtools)

**Comment by lunaruan** [comment] 2022-05-28 21:03
Hey everyone! After some investigation, we discovered that this issue is likely due to `requestAnimationFrame` not getting called in the extension. The reason a lot of you were seeing `pointer-events: none` on components is because the library we use for windowing sets pointer events to none when we scroll. We use `requestAnimationFrame` to determine when scrolling is done. Unfortunately, because `requestAnimationFrame` doesn't call its callback function in extensions for some reason, we never set scrolling to be finished, thus causing this issue.

**This is a Chrome bug**, but because it affects React DevTools, we will put up a temporary while it gets resolved. In the meantime, please either downgrade your Chrome version or use Firefox until this is fixed. Thanks so much for reporting this issue!

**Comment by bvaughn** [comment] 2022-05-28 22:19
Nice find!

 Is this by chance the same bug I reported to them a while ago?
https://bugs.chromium.org/p/chromium/issues/detail?id=1241986#c19

**Comment by mondaychen** [comment] 2022-05-29 00:49
@bvaughn this is new in v102 so more likely a different bug. It's related to `requestAnimationFrame` behaving differently in devtools_page.
I've found a way to create a minimal repro. Will upload in a few hours.

**Comment by mondaychen** [comment] 2022-05-29 01:25
I've created a repro of the Chrome bug https://github.com/mondaychen/devtools-bug-repro
and reported the bug https://bugs.chromium.org/p/chromium/issues/detail?id=1330118

**Comment by mondaychen** [comment] 2022-05-29 20:39
@bvaughn actually -- it might be the same issue. Probably because they have turned on that feature by default since v102?

**Comment by bvaughn** [comment] 2022-05-29 21:16
Yeah. That’s what I was thinking.

**Comment by mondaychen** [comment] 2022-05-30 03:25
A temporary workaround before we land a fix:
1. go to chrome://flags/
2. search for `Throttle non-visible cross-origin iframes`
3. change the flag to disable
4. relaunch Chrome to make the change effective

**Comment by mondaychen** [comment] 2022-06-02 20:02
Version 4.24.7 with the temporary fix is on [Chrome Web Store](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) now. I'm closing this issue.
Also for the record Chrome team has decided to revert that change caused this issue. `requestAnimationFrame` should work again on the stable version of Chrome v104+.

**Closed by mondaychen** 2022-06-02 20:02 UTC
Labels: Type: Bug, Component: Developer Tools

**Comment by paulirish** [comment] 2023-02-04 01:41
HI @mondaychen. I work on the Chrome team and just posted an update to the crbug for this: https://bugs.chromium.org/p/chromium/issues/detail?id=1241986#c31

Can take a look? Let us know if that all sounds good. We'd like to ship the flag that was paused because of this breakage. And based on my conclusion, I think we can go ahead and do that, assuming that the https://github.com/facebook/react/pull/24633 workaround is still in place, and you're happy with that. :)

Cheers

**Comment by mondaychen** [comment] 2023-02-07 20:28
Hi @paulirish. Yes, the workaround is still in place. If you ship the flag, please let me know and I'll update it to be a long term solution.
Also, I'll leave some <del>complaint</del> suggestions in the crbug issue :P

**Comment by wjmaclean** [comment] 2023-02-17 18:53
Hi @mondaychen ... we plan on re-enabling the flag early next week, so if you could do the update you mention in the proceeding post that would be great. Thanks!

**Comment by mondaychen** [comment] 2023-02-17 19:39
@wjmaclean will do. Thanks for letting me know!
