### ISSUE TITLE
[Dev Tools] giving false positive if redux dev tools installed

### ISSUE THREAD

**Issue by raffi23** [facebook/react#23159] opened 2022-01-21 08:19 UTC
React Dev Tool is turning to blue color on websites that are not built with react.

The issue happens when Redux DevTools extension is installed.

[Screenshot](https://we.tl/t-tH1rEHTNoW)

Redux DevTools: [Click Here](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd)

**Comment by eps1lon** [comment] 2022-01-21 08:36
This is a bug caused by the Redux DevTools extension: https://github.com/zalmoxisus/redux-devtools-extension/issues/829

Duplicate of #23107, #23124, #23138

**Closed by eps1lon** 2022-01-21 08:36 UTC
