### ISSUE TITLE
Bug: `cache` API Not Caching Functions with Object Parameter

### ISSUE THREAD

**Issue by OreQr** [facebook/react#31390] opened 2024-10-30 19:33 UTC
When using the `cache` utility to cache function that takes an object as input, the caching doesn't work.

## React version:
All versions that include the cache API.

## Steps To Reproduce

1. Create a function using the `cache` utility, with a destructured parameter object as input:
   ```typescript
   import { cache } from "react";

   interface Props {
     params: Promise<{ query?: string; page?: number }>;
   }

   const getPosts = cache(async ({ query, page }: Props["params"]) => {
     // Function logic
   });
   ```

2. Attempt to call `getPosts` multiple times with the same parameters.

3. Observe that caching does not occur, and the function executes on each call instead of retrieving from cache.

In comparison, if the function is structured to accept individual parameters (as shown below), caching works as expected:

```typescript
import { cache } from "react";

const getPosts = cache(async (query?: string, page?: number) => {
  // Function logic
});
```

## The current behavior

When `getPosts` accepts an object as input, caching does not work, and the function executes anew for each call, even with identical parameters.

## The expected behavior

`cache` should correctly cache function calls, regardless of whether the input is provided as individual parameters or a single object. In this case, `getPosts` should only execute once per unique set of parameters, reusing the cached result for subsequent calls with identical parameters.

**Comment by saul-atomrigs** [comment] 2024-10-31 05:30
I believe the reason for this is:
> If your arguments are not primitives (ex. objects, functions, arrays), ensure you’re passing the same object reference.

(https://react.dev/reference/react/cache#troubleshooting)

Does the following work?:
```ts
import { cache } from "react";

interface Props {
  params: Promise<{ query?: string; page?: number }>;
}

const getPosts = cache(async ({ query, page }: Props["params"]) => {
  // Function logic
});

// Memoize the parameter objects
const memoizedParams = { query: "example", page: 1 };

await getPosts(memoizedParams);  // Call 1
await getPosts(memoizedParams);  // Call 2 - Same reference, should use cache
```

**Comment by eps1lon** [comment] 2024-10-31 13:57
Closing since this expected behavior as explained by [saul-atomrigs](https://github.com/saul-atomrigs).

**Closed by eps1lon** 2024-10-31 13:57 UTC
Labels: Status: Unconfirmed

**Comment by reaktor-frank** [comment] 2025-03-17 16:08
This is not expected behavior. If an argument happens to be an object, they should be compared by the equality of their keys and values (e.g. by running `JSON.stringify`) and not by equality of references.

Our project uses `tRPC` to wrap server functions and provide functionalities such as input validation, authorization, and logging. `tRPC` only allows for single-argument functions by design, so an object must be used if several input values are required.

How am I supposed to maintain equality of references for the same input across all calls to this function spanning multiple different server components? Especially if the user ID per the example below is passed around using props and the input object is constructed ad-hoc when invoking the function? That's a ridiculous design flaw in my opinion. Please either reopen this issue, or address it.

```ts
export const getUser = cache(
    protectedAction
        .input(
            type({
                id: 'string.uuid.v4',
            }),
        )
        .output(
            type({
                id: 'string.uuid.v4',
                name: 'string',
                age: 'number',
            }),
        )
        .query(async ({ input }) => {
            const user = await userServices.getUser(input.id)

            if (!user) {
                throw new TRPCError({ code: 'NOT_FOUND' })
            }

            return user
        }),
)

```
