### ISSUE TITLE
Missing components and profiler in React extension

### ISSUE THREAD

**Issue by Devfront-end** [facebook/react#22247] opened 2021-09-04 19:17 UTC
Hello,

I have trouble installing React extension. Components and profiler are missing.

I've checked everywhere, many times unsuccessfully.

Can anyone help ?

Jules 
![Capture d’écran 2021-09-04 à 21 14 43](https://user-images.githubusercontent.com/84040216/132105600-70f2e91a-4779-4161-b03a-af56bc1a6f5e.png)
![Capture d’écran 2021-09-04 à 21 13 58](https://user-images.githubusercontent.com/84040216/132105603-96c128b1-043f-4aef-abd5-7eee1c22c408.png)

[
![Capture d’écran 2021-09-04 à 20 55 06](https://user-images.githubusercontent.com/84040216/132105545-57aed4a0-e737-40d8-9aee-df0cbd32645b.png)
](url)

**Comment by bvaughn** [comment] 2021-09-06 20:53
You need to visit a website that's running react for the extension to show up. Try [reactjs.org](https://www.reactjs.org).

**Comment by bvaughn** [comment] 2021-09-07 13:38
Generally when this is reported, the cause is that someone is not viewing a website built with React. I'm going to close this issue now with the assumption that the same is true.

If not, please respond with the following information and we can re-open the issue:
* Which browser (and version) are you using?
* Which operating system (and version) are you using?
* Which website(s) are you viewing that you expect DevTools to work for?

**Closed by bvaughn** 2021-09-07 13:38 UTC
Labels: Component: Developer Tools
