### ISSUE TITLE
Keyboard event handlers no longer invoked if document.body get's focus.

### ISSUE THREAD

**Issue by Gozala** [facebook/react#2846] opened 2015-01-12 22:09 UTC
In my example app / root component is rendered into `document.body` it also set's up `onKeyDown` `onKeyUp` to handle application keyboard shortcuts. 

The problem I'm running into is that some user interaction like clicking around page causes `document.body` to obtain focus (to become `document.activeElement`) and in that case `onKeyDown` & `onKeyUp` event handlers are no longer invoked.

I know I could register "keydown", "keyup" event handlers manually once app component is mounted but I would prefer to stay with-in react.

**Comment by syranide** [comment] 2015-01-21 22:44
I'd call this a duplicate of #285, re-open if you disagree.

**Closed by syranide** 2015-01-21 22:44 UTC
