### ISSUE TITLE
Bug: In some cases virtual dom className not generating class 

### ISSUE THREAD

**Issue by nicewaytodoit** [facebook/react#20566] opened 2021-01-09 22:04 UTC
React version:
react-dom@17.0.1

## Steps To Reproduce

Bug described here: https://github.com/gatsbyjs/gatsby/issues/28951

In what circumstances class that is already in virtual DOM element would not reflect on DOM?
Above issue is already described as Gatsby but I am not sure it is issue with React.

Two elements have same className, after hard reload both element in Virtual DOM have same className, but only one element has styled applied, how?!

**Comment by bvaughn** [comment] 2021-01-10 02:29
Can you reproduce this issue with React only (not using Gatsby)? If not, then it's probably a Gatsby bug. Since you've filed it as a Gatsby bug, I suggest closing this issue (unless you're able to reduce the repro to be React only).

**Comment by nicewaytodoit** [comment] 2021-01-10 09:17
Issue with Gatsby and hydration, I will close this.

**Closed** 2021-01-10 09:16 UTC
Labels: Resolution: Needs More Information, Status: Unconfirmed
