### ISSUE TITLE
using context to control user logged in  true or false 

### ISSUE THREAD

**Issue by Patriciadburns1** [facebook/react#13226] opened 2018-07-17 23:20 UTC
**Do you want to request a *feature* or report a *bug*?**
I am using Context to implement a user login/ log out feature and I am getting the following error : 

**What is the current behavior?**
warning.js:33 Warning: A context consumer was rendered with multiple children, or a child that isn't a function. A context consumer expects a single child that is a function. If you did pass a function, make sure there is no trailing or leading whitespace around it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

I want to change my slide out menu to either Log In or Log out then link to another page through the menu. I also tried using a ternary but that did not work either ( in the menu) I get the word to change but not the link 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am using React 16.4/ React Context API 
What I am noticing though is Context is not robust enough to control state / the passing in through the render could be more straightforward ( esp. documentation). 

See code below: 

import React, { Component, Fragment } from 'react';
import './menu.css';
import { Link } from 'react-router-dom';
import SearchData, { SearchDataContext } from '../searchdata';

class Menu extends Component {
    constructor(props){
        super(props);
        this.userAuthentication= this.userAuthentication.bind(this); 
    }

    userAuthentication(context) {
        if (context.userLoggedIn) { 
            return(
                <Fragment>
                    {/* <div className="menuLinkStyle"> Log Out </div> */}
                    <Link to="/UserFavorites"> <div className="menuLinkStyle"> User Profile </div> </Link>
                </Fragment>
            )
                
        }
        else {
            return(
                <Link to="/LogIn"> <div className="menuLinkStyle"> Log In </div> </Link>
            )              
        }
    }

    render() {
        // {context.userLoggedIn ?  <Link to="/LogIn"> <div className="menuLinkStyle"> Log Out </div> 
        // </Link>  : <Link to="/LogIn"> <div className="menuLinkStyle"> Log In </div> </Link> }

        // {context.userLoggedIn? <Link to="/UserFavorites"> Favorites </Link> : <span> </span> }

        return (
            <SearchDataContext.Consumer>{(context) => (
                <div className={this.props.visible ? "invisibleMenuContainer show" : "invisibleMenuContainer hide"} onClick={this.props.handleMenuClick}>
                    <div className={this.props.visible ? "show" : "hide"} id="menuContainer" onClick={this.props.handleMenuClick}>
                        <Link to="/"> <div className="menuLinkStyle">Home</div></Link>
                        {this.userAuthentication(context)}
                        {/* {context.userLoggedIn ? <Link to="/UserFavorites"> <div className="menuLinkStyle"> User Profile </div> </Link> : <Link to="/LogIn"> <div className="menuLinkStyle"> Log In </div> </Link>  } */}
                        <Link to="/MultipleResults"><div className='menuLinkStyle'>Random Snack</div></Link>
                        <Link to="/About"><div className="menuLinkStyle">About</div></Link>
                        <Link to="/Contact"><div className="menuLinkStyle">Contact</div></Link>
                    </div>
                </div>
            )}
            </SearchDataContext.Consumer>
        );
    }
}

export default Menu;

**Comment by aweary** [comment] 2018-07-17 23:30
@Patriciadburns1 did you follow the instructions in the warning?

> Warning: A context consumer was rendered with multiple children, or a child that isn't a function. A context consumer expects a single child that is a function. **If you did pass a function, make sure there is no trailing or leading whitespace around it.**

From the code you posted it looks like you might have some trailing whitespace after the function being passed to `SearchDataContext.Consumer`.

```jsx
      </div>
  </div>
 )}    // <- there's probably whitespace here
</SearchDataContext.Consumer>
```

It's hard to say without a runnable example reproducing your issue. Please follow the instructions in the issue template when opening an issue. You can see the links to the templates you can use in the template.

> Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:

If you believe this warning is occurring when it shouldn't, please use one of those templates to provide a minimal example reproducing the issue. In this case it seems like you're mostly asking a _usage_ question.

In that case, we use this issue tracker for bugs and feature requests. If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.htmls you can use in your post.

**Comment by aweary** [comment] 2018-07-24 02:09
No follow up, I'll assume the above comment fixed your problem and close this.

**Closed by aweary** 2018-07-24 02:09 UTC
Labels: Resolution: Needs More Information
