### ISSUE TITLE
Documentation Translations

### ISSUE THREAD

**Issue by gbezyuk** [facebook/react#8541] opened 2016-12-09 14:28 UTC
Hello there. Are there any plans for including official community-supported translations for React docs? At @translaiton-gang we've just completed Vue.js` docs Russian translation, and we also have some progress with React ones. I believe, at least Japanese and Chinese communities would also like to have their own translations. So, could we integrate it somehow?

UPD: I see some random translation files under `docs/community`. Is it how it's done now? How is the document version to display being detected? I mean, I can't see any header dropdown language choice or something.

**Comment by gaearon** [comment] 2016-12-09 15:22
>UPD: I see some random translation files under docs/community.

These are left overs, never mind them. We recently rewrote docs completely and had to delete old translations to avoid confusion. We planned to integrate some sort of tool so that we can decouple translations from main repo but haven’t decided on anything. I hope @lacker can give us some guidance here.

This is a duplicate of https://github.com/facebook/react/issues/8063 so let's discuss there.

**Closed by gaearon** 2016-12-09 15:22 UTC

**Comment by gaearon** [comment] 2019-01-29 16:50
I sent an email to you folks, hope you receive it!

**Comment by gbezyuk** [comment] 2019-01-30 20:51
@gaearon received and responded.

**Comment by gaearon** [comment] 2019-02-25 17:11
We've launched our first translations, and many need more contributors.

https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html
