### ISSUE TITLE
Problems with click events on IE and Edge

### ISSUE THREAD

**Issue by vasilkrastev90** [facebook/react#8912] opened 2017-02-02 09:38 UTC
I would like to point out a specific behaviour when using React with IE and Edge.

I am building a user-computer chat application where users are presented prompts to navigate them through a user journey. One of the steps is where the user enters a street name/postcode and they are presented a list of addresses to choose from. Therefore I have a step with a text input field which after the user submits disappears for a list of addresses to appear.

I have an example where there are two ways for submitting. One is by clicking on a send button, and the other is by hitting 'Enter' on a keyboard. When the user uses the mouse submission everything is ok on all browsers, however if the user presses the keyboard key then click events do not work as expected on IE and Edge.

My assumption is that the problem comes because the field that has the focus is deleted from the DOM but I can't be sure. To make things stranger I could only reproduce the issue by putting the addresses in the list in two nested div elements with display:flex set in the styles.

Here is a link to a fiddle: https://jsfiddle.net/rcvx5uLt/

Expected: After a value is entered in the input and enter is pressed or send is clicked I would expect the list of addresses provided to be clickable.

Actual:
- When a value is entered end send is clicked with the mouse the events on the list items can be tracked.
- When a value is entered and Enter is pressed the events on the list can't be tracked.

I am using react 15.4.2 with IE 11.713.10586.0 and  Edge 25.10586.672.0/EdgeHTML 13.10586.

**Comment by aweary** [comment] 2017-02-03 00:17
Thanks for the report @vasilkrastev90! I was able to verify the behavior you described in IE11. It's definitely super weird that it only occurs when using `display: flex` 😕  We'll have to look into this more to get a better idea of what's going on, but I'm suspecting it's some kind of bug with IE/Edge since `display: flex` shouldn't affect React at all.

If we could also reproduce it this without React (using `document.createElement` and `appendChild`) that would be really helpful, but may be difficult in this case.

**Comment by vasilkrastev90** [comment] 2017-02-03 17:59
In case people are affected, pro-actively removing focus before the text input unmounts resolves the issue.

**Comment by jddxf** [comment] 2017-02-15 12:52
@aweary Reproduced without React here http://codepen.io/inamessnow/pen/apMyNE.
As @vasilkrastev90 has suggested, removing focus before input is removed solves the problem.

**Comment by jdalton** [comment] 2017-03-30 22:05
This seems to be resolved in Edge 15.

**Comment by aweary** [comment] 2017-03-30 22:08
@jdalton thanks for the update. I think we can close this now since it's unlikely we could (or want to) make any changes to fix this in older Edge versions

**Closed by aweary** 2017-03-30 22:08 UTC
Labels: Type: Bug

**Comment by yael-screenovate** [comment] 2020-09-22 10:20
super weird, i had an <a/> tag with an onClick function that didn't work on edge only. removing display: flex from its div container solved the problem.
