### ISSUE TITLE
What happens if you encounter custom properties that are not supported by react?

### ISSUE THREAD

**Issue by cytGitHub** [facebook/react#9173] opened 2017-03-14 08:17 UTC
I need to use ```x5-video-player-type="h5"```  ```x5-video-player-fullscreen = "true``` these attributes, but react does not support these properties at all . how to do it??

**Comment by FezVrasta** [comment] 2017-03-14 12:22
Dupe of https://github.com/facebook/react/issues/140

**Closed** 2017-03-17 22:26 UTC
