### ISSUE TITLE
Remove usage of PooledClass

### ISSUE THREAD

**Issue by PezCoder** [facebook/react#9325] opened 2017-04-04 02:41 UTC
In [PooledClass.js](https://github.com/facebook/react/blob/master/src/shared/utils/PooledClass.js#L18) we have some static poolers based on the number of arguments & the comment specifies `it's not made dynamic so we don't have to use arguments.`

I have 2 questions with this:
1. What is the issue with using arguments (i noticed we're using it in other place [reference](https://github.com/facebook/react/blob/master/docs/js/react-dom.js#L8444)) if it's going to reduce duplicate code ? 
2. Can't we use the spread syntax for this like this:
```js
function nArgumentPooler(...args) {
    var Klass = this;
    if (Klass.instancePool.length) {
        var instance = Klass.instancePool.pop();
        Klass.call(instance, args);
    	return instance;
    } else {
        return new Klass(args);
    }
}
```

**Comment by gaearon** [comment] 2017-04-04 13:47
The person who wrote this code several years ago was likely worried about JS engine deoptimizations caused by using `arguments`.

To be honest I think the whole `PooledClass` abstraction needs to go. It might not be as necessary anymore with modern browsers. We discussed this before, and I think we haven’t really reached a decision there.

Would you like to send a PR to remove it and rewrite the code that relies on it? We could then experiment with the result and see its effect on performance.

**Comment by aweary** [comment] 2017-04-04 21:34
It's worth noting that while modern browsers may optimize `arguments` access, we support some older browsers, so we would need to profile performance with those as well.

It's not a big deal if there is a small performance regression in a limited number of limited use browsers, but anything more would probably be worth considering more carefully.

**Comment by nhunzaker** [comment] 2017-04-04 21:40
@aweary how would we go about doing that profiling? Is that something we could add to our fixture data? Or should that go somewhere else?

**Comment by aweary** [comment] 2017-04-04 21:46
Maybe, but it would be less clear what was passing and failing behavior. I imagine you'd have to write an app that taxed `PooledClass` (something that allocates a lot of `SyntheticEvent`s maybe) and then just compare performance before and after the changes.

**Comment by gaearon** [comment] 2017-04-04 22:28
`traverseAllChildren` used by `ReactChildren` also uses pooling so maybe that could be used in a benchmark instead.

>It's worth noting that while modern browsers may optimize arguments access, we support some older browsers, so we would need to profile performance with those as well.

The whole issue with `arguments` is moot if we remove `PooledClass` altogether. To be clear, I'm suggesting that, and not changing the pooling code as in the first comment. Also, in general we're okay with slight performance regressions in older browsers if it helps drop bundle size.

**Comment by aweary** [comment] 2017-04-04 22:39
Okay, that works. As far as I know, object pooling is done to limit object allocations when possible. In that case, we should benchmark on low-memory devices to see if removing `PooledClass` negatively affects performance there.

**Comment by gaearon** [comment] 2017-04-04 22:45
I'm not really sure what kind of benchmark could show it. `traverseAllChildren` was used in hot paths in Stack, but Fiber doesn't use it for reconciliation anymore. So we're left with `React.Children` using it (relatively uncommon path), and `SyntheticEvent` (would you really get so many events per second to cause GC trash?) I can imagine this being meaningful on React Native though.

**Comment by gaearon** [comment] 2017-04-04 22:53
My proposal: let's remove pooling from `traverseAllChildren` since it's not a hot path in Fiber. Then let's rewrite the event pooling code by hand specifically for that case (it should be possible to make it shorter I hope). Anyone wants to try?

**Comment by aweary** [comment] 2017-04-04 22:59
I can handle it unless someone else really wants to take it 😃

**Comment by gaearon** [comment] 2017-04-04 23:12
Renamed the issue to be more focused. Thanks @aweary!

**Comment by koba04** [comment] 2017-04-05 05:05
@aweary @gaearon If you consider removing usage of PooledClass from `SyntheticEvent`, I can work on to investigate whether PooledClass is needed for `SyntheticEvent` or not.

I have a work in progress branch for this.

https://github.com/koba04/react/tree/remove-pooling-synthetic-event

A commit is https://github.com/koba04/react/commit/2ef294fe2003d328518e9c8392aadc4aa716011d
(All tests passes)

**Comment by syranide** [comment] 2017-04-05 07:21
Regarding `SyntheticEvents`, I challenged it some time ago and the team was insisting that it was a necessary gain (even considering the API impact), especially as they had witness "GC thrashing" in even modern browsers. (some info; https://github.com/facebook/react/pull/1612) It may have changed since then though.

But like I suggested elsewhere, multiple events of the same type are never really in-flight at the same time, so just keeping a single event should be enough, pooling should not be necessary. https://github.com/facebook/react/pull/1664#issuecomment-48835201

**Comment by gaearon** [comment] 2017-04-05 10:38
The approach I would like to try is to not use pooling for traversal, but to hardcode pooling implementation into the event system with less dynamic indirection. I think it would make sense to start with a single event object per type since each type might have different fields. We can later look if we can reduce it to one object overall.

**Comment by koba04** [comment] 2017-04-05 16:56
I've picked files depending on PooledClass.

The following files are dependencies of Stack reconciler.
So it seems to be able to remove them when Fiber is landed (in v16?)

* [ReactReconcileTransaction](https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/ReactReconcileTransaction.js)
* [ReactServerRenderingTransaction](https://github.com/facebook/react/blob/master/src/renderers/dom/stack/server/ReactServerRenderingTransaction.js)
* [CallbackQueue](https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/CallbackQueue.js)
* [ReactUpdates](https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/ReactUpdates.js)
* [ReactTestReconcileTransaction](https://github.com/facebook/react/blob/master/src/renderers/testing/stack/ReactTestReconcileTransaction.js)

To remove PooledClass, we would need to consider about the following files.

* [FallbackCompositionState](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/eventPlugins/FallbackCompositionState.js)
* [ReactEventListener](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactEventListener.js)
* [ReactNativeReconcileTransaction](https://github.com/facebook/react/blob/master/src/renderers/native/ReactNativeReconcileTransaction.js)
* [SyntheticEvent](https://github.com/facebook/react/blob/master/src/renderers/shared/shared/event/SyntheticEvent.js)
* [ReactChildren](https://github.com/facebook/react/blob/master/src/isomorphic/children/ReactChildren.js) (PR #9339)

**Comment by aweary** [comment] 2017-04-05 18:20
@gaearon how should we handle removing `PooledClass`  with the stack renderer still utilizing it?

**Comment by aweary** [comment] 2017-04-09 19:47
ping @gaearon, hoping you could provide some more guidance on ^

**Comment by gaearon** [comment] 2017-04-09 20:40
I’m mostly interested in looking at removing its occurrences in Fiber. Stack would be deleted soon anyway.

**Comment by aweary** [comment] 2017-04-10 15:51
@gaearon so in that case, it probably doesn't make sense to go through and remove `PooledClass` from stack-specific code paths. I suppose that depends on how many more `15` releases we intend to cut and whether making those changes would be worth the risk.

**Comment by gaearon** [comment] 2017-04-10 18:04
Oh, we definitely don't want to do this in 15.x so you're right.

**Comment by PezCoder** [comment] 2017-08-04 21:57
Looking for a good first bug but I started a beast here. 
This is what happens when you're trying to improve one thing & doubt the existence of the whole thing 😉

**Comment by gaearon** [comment] 2017-08-05 02:50
Haha, sorry! I think we can close this because we removed its usage in the modern part of the codebase, and we’ll delete the legacy one very soon.

**Closed by gaearon** 2017-08-05 02:50 UTC

**Comment by 282159468** [comment] 2020-04-06 14:34
> The person who wrote this code several years ago was likely worried about JS engine deoptimizations caused by using `arguments`.
> 
> To be honest I think the whole `PooledClass` abstraction needs to go. It might not be as necessary anymore with modern browsers. We discussed this before, and I think we haven’t really reached a decision there.
> 
> Would you like to send a PR to remove it and rewrite the code that relies on it? We could then experiment with the result and see its effect on performance.

I am too low in technology and have too many questions, but I want to know why


1. I found that react@16.13.0 deleted the pooledclass.js file, but in the following three files I found a separate implementation similar to pooledclass. What is the reason for this?
![image](https://user-images.githubusercontent.com/28442945/78569204-d89de080-7855-11ea-9b20-6d87eddeeedb.png)
2. why JS engine deoptimizations caused by using `arguments`.
3. why It might not be as necessary anymore with modern browsers
