### ISSUE TITLE
PureRenderMixin does not respect changes in context

### ISSUE THREAD

**Issue by professor** [facebook/react#6571] opened 2016-04-21 20:53 UTC
We accidentally applied PureRenderMixin to a page that that rendered the same result given the same props and state, however, it broke the page since the context changed (for a isUserLoggedIn).

**Comment by jimfb** [comment] 2016-04-21 20:55
Effectively a duplicate of https://github.com/facebook/react/issues/2517

**Closed by jimfb** 2016-04-21 20:55 UTC
