### ISSUE TITLE
Boolean attributes on Web Components

### ISSUE THREAD

**Issue by nickdima** [facebook/react#9230] opened 2017-03-21 15:09 UTC
When setting boolean attributes on Web Components
`<x-search somebool name={this.props.name} />`
they get rendered as attribute/value pairs instead
`<x-search somebool="true" name={this.props.name}>`

This causes problems with some AMP components, for eg. `<amp-iframe />` which has a `resizable` attribute that gets rendered as `resizable="true"`. This results in non valid AMP content and developers crying with blood tears on their keyboards :)
> The attribute 'resizable' in tag 'amp-iframe' is set to the invalid value 'true'. (see https://www.ampproject.org/docs/reference/components/amp-iframe)

Is there any reason for the current behaviour? Will changing this break something else?

**Comment by Krizzu** [comment] 2017-03-22 12:43
Hey @nickdima 

This behavior is described in [Docs (old jsx gotchas) here.](https://facebook.github.io/react/docs/jsx-in-depth.html#props-default-to-true) 

So basically, if You pass a prop without a value, it default to "True"

**Comment by nickdima** [comment] 2017-03-22 14:12
> Digging deeper, this behavior (React Docs also point that) is standard behavior of html5 boolean attributes. Simply put, when you have an input element:
<input type="checkbox" checked />

Well yeah, but React is doing the contrary in this case, id doesn't render `<some-tag somebool />` but `<some-tag somebool="true />`.
I know it works for known tags like `input` for `disabled` and `checked` but it doesn't work for unknown tags and attributes.

**Comment by aweary** [comment] 2017-03-22 14:51
Thanks for the report @nickdima! Current React just [passes attributes through](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/dom/stack/client/ReactDOMComponent.js#L1005-L1012) if the element is a custom element. So if you pass `somebool={true}` the attribute will get set via `setAttribute('somebool', true)` which will set the attribute value to `"true"`. 

You can verify that's exepcted behavior with:

```jsx
var element = document.createElement('some-tag');
element.setAttribute('somebool', true);
// <some-tag somebool="true"></some-tag>
```

According to the [HTML5 spec on boolean attributes](https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html#boolean)

> If the attribute is present, its value must either be the empty string or a value that is a case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

So as a workaround you should be able to do `<some-tag somebool=""></some-tag>`  and it should render as `<some-tag somebool></some-tag>`.

I'm not sure if that will accomplish what you want, as it probably depends on how AMP is reading these attributes. Attributes like `checked` or `disabled` are reflected properties, so `element.setAttribute('checked', '')` sets `element.checked === true` . I'm assuming that Web Components should take care of that for you then?

React can potentially be smarter about this and coerce `true` to `''` to comply with the boolean attribute spec.

**Comment by nickdima** [comment] 2017-03-22 15:04
Thanks @aweary! The workaround `<some-tag somebool=""></some-tag>` seems to do the trick!
Should we document this somewhere?

**Comment by aweary** [comment] 2017-03-22 15:15
@nickdima glad to hear it! I'm not sure yet, it will depend on whether we'll want to just coerce `true` to `''` internally for custom element attributes. cc @spicyj what do you think?

**Comment by spicyj** [comment] 2017-03-22 18:34
I don't remember all the history here, but I think we assume that custom elements are string-typed, not boolean-typed. For all string-typed attributes we just coerce to strings (even for boolean values). So like `<a href={true} />` makes `href="true"`. I'm inclined to say we'll leave this current behavior.

**Comment by aweary** [comment] 2017-03-22 18:36
Is there any reason to assume booleans should be coerced to strings? Are there any cases where `attribute={true}` should be rendered as `attribute="true"` and not `attribute`?

If we leave the current behavior then we should definitely document how to render boolean attributes.

**Comment by aweary** [comment] 2017-04-05 19:00
ping @spicyj, what do you think about ^?

**Comment by robdodson** [comment] 2017-07-27 23:16
I think there may be an issue here because if the boolean is `false`, React will set `<my-element somebool="false">`. Typically that still evaluates to `true`. For instance, `<input type="checkbox" checked="false">` will still produce a checked checkbox. I think removing the boolean attribute is the typical practice.

I guess the distinction to be drawn here is between enumerated attributes (which expect "true"/"false") and boolean attributes. Some examples of enumerated attributes are things like `aria-hidden="true"` and as @syranide pointed out in #9779, `spellcheck="true"`.

Taking a bigger step back, I think switching to [passing properties to custom elements](https://github.com/facebook/react/pull/8755) would be really nice as it sort of sidesteps some of these issues. But it doesn't resolve what to do in the AMP case if AMP requires an attribute instead of a property :\

**Comment by robdodson** [comment] 2017-08-12 21:38
I looked at what Preact does here and I think their solution is pretty decent. If the value is a boolean it will add or remove the attribute. If the value is a string it will set the attribute to the string. Example:

```js
let val;

val = true;
<x-foo bool={val}></x-foo>
// output: <x-foo bool="true"></x-foo>

val = false;
<x-foo bool={val}></x-foo>
// output: <x-foo></x-foo>

val = "true";
<x-foo bool={val}></x-foo>
// output: <x-foo bool="true"></x-foo>

val = "false";
<x-foo bool={val}></x-foo>
// output: <x-foo bool="false"></x-foo>
```

This seems like it would allow you to support boolean attributes (`checked`, `disabled`) and enumerable attributes (`spellcheck`, `aria-hidden`).

**Comment by jessepinho** [comment] 2018-05-10 17:07
For TypeScript users, I noticed that TypeScript complains if I pass an empty string as the value. So I'm getting around that by passing `undefined`:

```TypeScript
    <Helmet>
      <script
        async={undefined}
        custom-element="amp-bodymovin-animation"
        src="https://cdn.ampproject.org/v0/amp-bodymovin-animation-0.1.js"
      />
    </Helmet>
```

This renders as `<script data-react-helmet="true" async custom-element="amp-bodymovin-animation" src="https://cdn.ampproject.org/v0/amp-bodymovin-animation-0.1.js"></script>`. Hope this helps!

**Comment by itsmelion** [comment] 2018-07-04 21:04
I think boolean attributes should be allowed as they were declared.
my css framework detects custom attributes, and having to type `attr=""` instead of `attr` is kinda annoying.

take a look:
```<section row flex align="around center" />```
```<section row="" flex="" align="around center" />```

**Comment by morewry** [comment] 2019-07-09 00:04
So...hold up. You're telling me there's no way to get React to call `.removeAttribute()`?

**Comment by MichaelDimmitt** [comment] 2019-12-07 23:47
Issue is still open +1

**Comment by beqaMeqvabishvili** [comment] 2021-12-17 19:57
hey, so it looks like the fix was merged and removed latter on. the problem is still there. passing `booleanAttr={false}` to a custom components still resolves to component being rendered with `booleanAttr="false"`, which then fails the `Element.hasAttribute("booleanAttr")` test. doing something like `booleanAttr={condition ? true : ""}` is a good workaround, but is not consistent with React's behavior with regular elements and would create confusion with developers who did not write custom component but are using it in react

**Comment by andrewcovenant** [comment] 2022-01-02 17:08
@gaearon Can I work on this as a first contribution?

**Comment by horuskol** [comment] 2022-04-10 00:44
> hey, so it looks like the fix was merged and removed latter on. the problem is still there. passing `booleanAttr={false}` to a custom components still resolves to component being rendered with `booleanAttr="false"`, which then fails the `Element.hasAttribute("booleanAttr")` test. doing something like `booleanAttr={condition ? true : ""}` is a good workaround, but is not consistent with React's behavior with regular elements and would create confusion with developers who did not write custom component but are using it in react

I think you'll find that `booleanAttr={condition ? true : ""}` won't pass - even setting the attribute to an empty string will leave the attribute in the markup.

I found that `booleanAttr={condition ? '' : null}` is the way.

**Comment by gaearon** [comment] 2022-04-10 13:34
Has this been fixed in the `@experimental` releases? Can somebody check please?

**Comment by eps1lon** [comment] 2022-05-10 10:30
> Has this been fixed in the `@experimental` releases? Can somebody check please?

It's still adding attributes with the stringified value: https://codesandbox.io/s/web-components-boolean-props-lgbhp0?file=/src/index.js

**Comment by eps1lon** [comment] 2022-05-11 09:50
Re: https://github.com/facebook/react/issues/9230#issuecomment-322007671


```jsx
val = true;
<x-foo bool={val}></x-foo>
// output: <x-foo bool="true"></x-foo>
```
@robdodson Wouldn't this still be problematic with the initial case of `<amp-iframe resizeable />` where `resizeable` should be `""` not `"true"` like Preact does?

For enumerated attributes like `aria-hidden` you should then render `<custom-element aria-hidden="true" />` instead of `<custom-element aria-hidden />`.

**Closed** 2022-05-20 17:10 UTC
Labels: Component: DOM, Type: Discussion
