### ISSUE TITLE
Warning setState on unmounted component with traceback

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#4526] opened 2015-07-30 21:07 UTC
> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.

It would be great to get a stack trace here so I know what this warning is referring to

**Comment by jimfb** [comment] 2015-07-31 06:21
Duplicate of https://github.com/facebook/react/issues/4216.  Fixed in 0.14.

**Closed by jimfb** 2015-07-31 06:21 UTC

**Comment by ccorcos** [comment] 2015-07-31 07:07
:)
