### ISSUE TITLE
Bug: Warning: React does not recognize the `fetchPriority` prop on a DOM element [React 18.3.1]

### ISSUE THREAD

**Issue by martabitbrain** [facebook/react#28948] opened 2024-04-29 09:28 UTC
React version: 18.3.1

This bug may be related to #28946 .

## Steps To Reproduce

1. Create an image tag with `fetchPriority="high"` attribute (camelCase)
2. Create an image tag with `fetchpriority="high"` attribute (lowercase)

Link to code example: https://codesandbox.io/p/sandbox/quiet-haze-5hkscx 

## The current behavior
**Output**: (fetchpriority attribute looks ok!)
```
<img fetchpriority="high" src="https://dummyimage.com/200x64/b000b0/fff&text=fetchPriority">
<img fetchpriority="high" src="https://dummyimage.com/200x64/00b075/fff&text=fetchpriority">
```
**Warning**: 
```
Warning: React does not recognize the `fetchPriority` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchpriority` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

## The expected behavior
The same output, but no warning.

**Comment by eps1lon** [comment] 2024-04-29 09:52
Duplicate of https://github.com/facebook/react/issues/27233. Fixed in Canary release channel and once React 19 becomes stable.

**Closed by eps1lon** 2024-04-29 09:52 UTC
Labels: Status: Unconfirmed

**Comment by martabitbrain** [comment] 2024-04-29 10:05
Sorry, I didn't notice.

**Comment by MKSisti** [comment] 2024-11-07 11:03
it's Nov now and React 19 is still not stable sadly, can we get the fix rolled for 18.x.x @eps1lon 🙏

**Comment by kallelat** [comment] 2025-01-21 10:56
Hi, it seems fetchPriority is not recognized yet in 19.0.0.
