### ISSUE TITLE
Don't bring politics to React 

### ISSUE THREAD

**Issue by yuu2lee4** [facebook/react#23402] opened 2022-03-03 04:47 UTC
![1646279332634](https://user-images.githubusercontent.com/8046366/156497787-3fae7d87-8ade-41a0-af57-deb86363789f.jpg)

I feel so sad you bring politics to React. In my opinion, Support Ukraine government equal support nazi.

**Comment by wusb** [comment] 2022-03-03 04:57
+1

**Comment by Yumwey** [comment] 2022-03-03 05:14
Shame on react!

**Comment by YoungLightMing** [comment] 2022-03-03 05:34
+1

**Comment by bibi7** [comment] 2022-03-03 05:35
agree

Why a technical framework gets involved in politics? So It is the next step to ban developers from Russia from using React?

**Comment by zhaohuanyuu** [comment] 2022-03-03 05:51
Why not support Iraq, Afghanistan, Syria, etc.?

**Comment by juanfu1997** [comment] 2022-03-03 05:55
support Nazi！？Are you kidding me？

**Comment by awefeng** [comment] 2022-03-03 05:56
the king of this universe is America ? Why a technical framework have this tip ?  Why you are so stupid ?

**Comment by cdll** [comment] 2022-03-03 06:06
Shame on react!

**Comment by cnywt** [comment] 2022-03-03 06:06
Shame !

**Comment by pomelovico** [comment] 2022-03-03 06:06
it's not your business

**Comment by pomelovico** [comment] 2022-03-03 06:07
feel so sad

**Comment by yichen454** [comment] 2022-03-03 06:08
+1

**Comment by xueqingxiao** [comment] 2022-03-03 06:10
if you guys are not going to support Nazi, take a look [this video](https://vimeo.com/202792798).  and remove this highlight from react doc site.

**Comment by liuqh0609** [comment] 2022-03-03 06:11
so sad

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:15
+1

**Comment by liuqh0609** [comment] 2022-03-03 06:17
Goodwill towards react has plummeted

**Comment by init-center** [comment] 2022-03-03 06:18
+1

**Comment by gggso** [comment] 2022-03-03 06:21
+1

**Comment by BuzzWoods** [comment] 2022-03-03 06:25
React bring  Humanitarian Aid to Ukraine,
Wait... 
What? They make a title on a website!  
I thought React Developers had bought tickets to help the Ukrainian people
What a joke! fuck you react

**Comment by RandolphCYG** [comment] 2022-03-03 06:26
爷找到了不写react的理由

**Comment by z-bai** [comment] 2022-03-03 06:26
I don't know anything about politics. But I hope those innocent Ukraine people just like you and me are safe and sound.

**Comment by xueqingxiao** [comment] 2022-03-03 06:29
> I don't know anything about politics. But I hope those innocent Ukraine people just like you and me are safe and sound.

Azov Battalion was killing innocent Ukraine people. where are you?
why are you show too much mercy now?

**Comment by fengtomy** [comment] 2022-03-03 06:34
Put it simply, technology knows no borders
Now I think it's just a joke

**Comment by Mark24Code** [comment] 2022-03-03 06:38
+1

**Comment by watsonhaw5566** [comment] 2022-03-03 06:49
Shame !

**Comment by ShopkeeperEgg** [comment] 2022-03-03 06:50
我卢本伟支持vue

**Comment by ShopkeeperEgg** [comment] 2022-03-03 06:51
My name is Lu Benwei. Let's play on Vue

**Comment by ZoeLeee** [comment] 2022-03-03 06:51
Please keep the code pure

**Comment by ShopkeeperEgg** [comment] 2022-03-03 06:53
https://v3.vuejs.org/

**Comment by cnmade** [comment] 2022-03-03 06:54
I hope you guys support Ukraine, please support our new suggest: 
https://github.com/facebook/react/issues/23403

**Comment by HuXin957** [comment] 2022-03-03 06:57
Shame on react!

**Comment by cnmade** [comment] 2022-03-03 06:57
格局，格局，注意格局。
乌克兰正在饱受战火摧残，于情于理我们都要得到善意的支持，我们不要问React社区为乌克兰做了什么，我们要反思，我们还能为乌克兰做什么。
这就是格局啊，兄弟们。

除了加一个链接，我们还可以做更多。
让我们一起呼吁，ReactJS改名为UkraineNeedHelpJs。

让每一个用此项目的人，发自内心的支持乌克兰。

我们就是黑夜中微弱的光，即使弱小，也要照亮黑暗。

如果你是个善良的人，请支持我们：
https://github.com/facebook/react/issues/23403

**Comment by cnmade** [comment] 2022-03-03 06:59
```js
import * from UkraineNeedHelpJs;
```

每一次扣腚，就是一次支持乌克兰，世界会变得更加美好。

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:59
> 布置，布置，注意布置。 乌克兰正在饱受战事的 打算就是布置啊，兄弟们。
> 
> 除了加一个链接，我们还可以做更多。 让我们一起倡议，ReactJS改UkraineNeedHelpJs。
> 
> 让每一个用这个项目的人，发自内心的支持。
> 
> 我们就是黑夜中微的光，即使是微弱的小，今天也是黑暗。
> 
> 如果你是个善良的人，请支持我们： #23403

Please don't kidnap morally. No support is not good. The United States is not the king of the world. Why is there no support in Afghanistan and Iraq because the war launched by the United States is just?

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:59
Please don't kidnap morally. No support is not good. The United States is not the king of the world. Why is there no support in Afghanistan and Iraq because the war launched by the United States is just?

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:59
Please don't kidnap morally. No support is not good. The United States is not the king of the world. Why is there no support in Afghanistan and Iraq because the war launched by the United States is just?

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:59
Please don't kidnap morally. No support is not good. The United States is not the king of the world. Why is there no support in Afghanistan and Iraq because the war launched by the United States is just?

**Comment by ZhangDengchuan** [comment] 2022-03-03 06:59
Please don't kidnap morally. No support is not good. The United States is not the king of the world. Why is there no support in Afghanistan and Iraq because the war launched by the United States is just?

**Comment by zhangshengran** [comment] 2022-03-03 07:00
to low to low   Im so so  Although I haven't used it yet

**Comment by nqdy666** [comment] 2022-03-03 07:00
+1

**Comment by zhangshengran** [comment] 2022-03-03 07:00
to low to low, Im so sad, Although I haven't used it yet

**Comment by Skyzhanyou** [comment] 2022-03-03 07:01
Russian troops never attacked Ukrainian civilians. In contrast, the Ukrainian army shelled civilians in eastern Ukraine for 8 years, and some of their soldiers held Nazi flags, but the Western world chooses to ignore.
So react, fxxk you!🖕

**Comment by unclepan** [comment] 2022-03-03 07:10
sb

**Comment by 632781460** [comment] 2022-03-03 07:11
react sb

**Comment by iolh** [comment] 2022-03-03 07:12
For shame!

**Comment by SaltFish001** [comment] 2022-03-03 07:14
Same on Node.js
![image](https://user-images.githubusercontent.com/42058801/156515093-c087fcee-1404-4a51-bdcd-c4a72e147035.png)

**Comment by cnmade** [comment] 2022-03-03 07:17
@TingYinHelen 纯净，只有在他们有利的时候，他们才会让你纯净。当他们不想，他们就可以为所欲为。

**Comment by Tomcater** [comment] 2022-03-03 07:18
Поддержка России 🇷🇺

**Comment by Channing-Huang** [comment] 2022-03-03 07:18
+1

**Comment by 0x219** [comment] 2022-03-03 07:24
🇷🇺乌拉

**Comment by cnmade** [comment] 2022-03-03 07:26
这些天西方媒体也好，政治家也好，甚至开源组织也好，一再再的秀下限。你跟他们说和平是人人生而平等。他们说：只有乌克兰才需要和平。

看看今天也门， 也门不需要和平吗？

他们的所谓和平，只有在他们需要和平的时候，他们才会站出来。

只有他们想看见的时候，他们才能看得见。
只有他们想伸张正义的时候，他们才正义。


西方普遍的伪善，伪君子，注定会被历史钉在耻辱柱上。无数冤死在美国，北约炮火下的冤魂，不舍昼夜，悠悠悲鸣，又有谁人听呢？


那些梦想着移民到国外，就可以化身为人的中国人。

你们可以想一下，英国开始没收俄罗斯人的财产了哟。请看看最新的新闻。

你们无处可逃。你们这辈子是中国人，黄皮肤脸孔，你怎么逃。。。

**Comment by Charliecheung2** [comment] 2022-03-03 07:28
> 这些天西方媒体也好，政治家也好，甚至开源组织也好，一再再的秀下限。你跟他们说和平是人人生而平等。他们说：只有乌克兰才需要和平。
> 
> 看看今天也门， 也门不需要和平吗？
> 
> 他们的所谓和平，只有在他们需要和平的时候，他们才会站出来。
> 
> 只有他们想看见的时候，他们才能看得见。 只有他们想伸张正义的时候，他们才正义。
> 
> 西方普遍的伪善，伪君子，注定会被历史钉在耻辱柱上。无数冤死在美国，北约炮火下的冤魂，不舍昼夜，悠悠悲鸣，又有谁人听呢？
> 
> 那些梦想着移民到国外，就可以化身为人的中国人。
> 
> 你们可以想一下，英国开始没收俄罗斯人的财产了哟。请看看最新的新闻。
> 
> 你们无处可逃。你们这辈子是中国人，黄皮肤脸孔，你怎么逃。。。

这里有一位主动放弃绿卡的，让我们起立鼓掌

**Comment by cnmade** [comment] 2022-03-03 07:29
三年来最严重的伤亡 
过去一个月，也门平民伤亡人数达到了“惊人的”创纪录水平。联军对萨达一个拘留设施的空袭造成300多名在押人员死亡或受伤，这是三年来最严重的事件之一。 

格伦德伯格指出，空袭急剧增加，其中包括对萨那和重要港口城市荷台达的居民区和民用基础设施的空袭。他强调，战争也在经济领域进行，因为双方及其盟友在资源、通过红海港口的贸易流动和货币政策方面展开了斗争。 

他表示，所有也门人都受到战争影响。过去一个月，燃料和石油衍生品尤其严重短缺，特别是在安萨尔阿拉控制的地区。

**Comment by Jack-rainbow** [comment] 2022-03-03 07:35
+1

**Comment by Month7** [comment] 2022-03-03 07:36
agree

**Comment by Jack-rainbow** [comment] 2022-03-03 07:36
Azov Battalion was killing innocent Ukraine people. where are you?
why are you show too much mercy now?

**Comment by zhongmeizhi** [comment] 2022-03-03 07:37
> Поддержка России 🇷🇺

<img width="280" alt="image" src="https://user-images.githubusercontent.com/17895124/156518260-d474e8b9-6367-482e-bbbd-4ad56ad9b136.png">


？？？ what fuck ？？？

**Comment by cnmade** [comment] 2022-03-03 07:38
@charliecheung 你的讽刺我收到。我看了你的资料，你不管是不是华人，但是请注意，总有一天，他们善意的铁拳，不排除会打到你身上。我希望你保护好自己。不要被伤害。
希望到时候，有人帮助你，维护你，让你安全。

**Comment by qiansc** [comment] 2022-03-03 07:38
Shame of React~

**Comment by yisar** [comment] 2022-03-03 07:40
react sb！

**Comment by cnmade** [comment] 2022-03-03 07:40
> > Поддержка России 🇷🇺
> 
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/17895124/156518260-d474e8b9-6367-482e-bbbd-4ad56ad9b136.png">
> 
> ？？？ what fuck ？？？Google Translate really works！

很明显，他们都是帝国主义的走狗。。还能有什么其他坏心思呢？本来就不是人，自然干不了人事。

所谓的公正，公平，和平。

他们可以说，你不可以说。

他们可以作恶，你不可以。

**Comment by CreazyJack** [comment] 2022-03-03 07:41
+1

**Comment by zhongmeizhi** [comment] 2022-03-03 07:45
<img width="626" alt="image" src="https://user-images.githubusercontent.com/17895124/156519377-6bcf2326-58ba-49bc-b09e-0efaef4bfe3f.png">

**Comment by kirainmoe** [comment] 2022-03-03 07:45
Open source community should be pure like this: https://github.com/vuejs/vue/pull/12483

**Comment by cnmade** [comment] 2022-03-03 07:45
@zhongmeizhi  I like your  works

**Comment by cnmade** [comment] 2022-03-03 07:47
@kirainmoe 我喜欢尤大的观点，非常公平，公正，正义。
![image](https://user-images.githubusercontent.com/278153/156519782-65d24d3b-a4fd-4b18-8ebc-f731e3f76d6a.png)

**Comment by 0x219** [comment] 2022-03-03 07:47
Sorry, I don't use react anymore, `solidjs` is nice.

**Comment by cnmade** [comment] 2022-03-03 07:48
用照用，骂照骂，互不影响。

**Comment by bibi7** [comment] 2022-03-03 07:51
@cnmade 表达观点是可以的，但是还是要注意这是一个被广泛使用的库的 issue 讨论区，可以合理讨论观点，不是你的吐槽专区。

**Comment by SaltFish001** [comment] 2022-03-03 07:52
> @cnmade 表达观点是可以的，但是还是要注意这是一个被广泛使用的库的 issue 讨论区，可以合理讨论观点，不是你的吐槽专区。

可他们也没有考虑过自己的社会影响力

**Comment by cnmade** [comment] 2022-03-03 07:54
@bibi7 你好，反思怪。

我不反思，我不检讨。你们什么都做不了，还搁这儿反思呢。

**Comment by cnmade** [comment] 2022-03-03 07:55
@SaltFish001 哪有什么社会影响力。

**Comment by CFMJ** [comment] 2022-03-03 07:56
So,Who cares about the Donetsk's people being bombed  by the Ukrainian army? Hummm, FaceBook?

**Comment by cnmade** [comment] 2022-03-03 08:00
@bibi7 你不问他们支持乌克兰合理不合理，你搁这儿反思啥呢？
别人刀都割你头发了，你还搁这儿反思。

反思怪你好。

**Comment by wangxxxb** [comment] 2022-03-03 08:01
Shame on react!

**Comment by yisar** [comment] 2022-03-03 08:03
Shame on react!

**Comment by reactDashabi** [comment] 2022-03-03 08:03
北约挑动乌克兰战争,导致乌克兰人民处于水深火热之中,现在又利用乌克兰人民卖惨,戴上人道主义面具,控制媒体丑化俄罗斯,恶心心.想想乌克兰换成我们国家的新疆西藏,俄罗斯换成我们国家,到时候react又support新疆西藏,手段何其恶心,阴险,挑事的是你,站在道德制高点狂轰滥炸的还是你.真是替乌克兰平民感到难过,也希望我们国家不会被逼上这条路

**Comment by cnmade** [comment] 2022-03-03 08:06
> 北约挑动乌克兰战争,导致乌克兰人民处于水深火热之中,现在又利用乌克兰人民卖惨,戴上人道主义面具,控制媒体丑化俄罗斯,恶心心.想想乌克兰换成我们国家的新疆西藏,俄罗斯换成我们国家,到时候react又support新疆西藏,手段何其恶心,阴险,挑事的是你,站在道德制高点狂轰滥炸的还是你.真是替乌克兰平民感到难过,也希望我们国家不会被逼上这条路

支持你的观点，同时希望 @bibi7 这种反思怪少一点。

没事动不动就反思自己的过错。。你没错他们就不能杀你吗？

**Comment by phasedarray** [comment] 2022-03-03 08:08
> 北约挑动乌克兰战争,导致乌克兰人民处于水深火热之中,现在又利用乌克兰人民卖惨,戴上人道主义面具,控制媒体丑化俄罗斯,恶心心.想想乌克兰换成我们国家的新疆西藏,俄罗斯换成我们国家,到时候react又support新疆西藏,手段何其恶心,阴险,挑事的是你,站在道德制高点狂轰滥炸的还是你.真是替乌克兰平民感到难过,也希望我们国家不会被逼上这条路

确实，这事本来跟中国关系不大，但是全世界可能就我们最能理解毛子处境。

**Comment by Can-Chen** [comment] 2022-03-03 08:11
乌拉🇷🇺

**Comment by yisar** [comment] 2022-03-03 08:11
我本来想中立，但是欧美的行为太恶心了，令人作呕

**Comment by cnmade** [comment] 2022-03-03 08:15
欧美的问题在于选择性站队：只许州官放火不许百姓点灯。

某些事件上视而不见听而不闻。

如果他们能做到真正的公平正义和和平。别说支不支持乌克兰。捐款都可以。


一方面中东也门被虐，一方面，以色列在攻击袭击巴勒斯坦无辜平民。


哪儿哪儿都不太平。怎么偏偏就乌克兰要支持它的和平。

**Comment by lvbaiying** [comment] 2022-03-03 08:17
乌拉🇷🇺

**Comment by willx12123** [comment] 2022-03-03 08:18
So, next step react want to ban developers in Ruassia to use it? Why open source projects are so eager to express their political standpoint?

**Comment by wangxxxb** [comment] 2022-03-03 08:19
> So, next step react want to ban developers in Ruassia to use it? Why open source projects are so eager to express their political standpoint?

因为他们是走狗，给钱就叫的狗

**Comment by qyqcswill** [comment] 2022-03-03 08:21
Shame on react!

**Comment by lazycat92** [comment] 2022-03-03 08:28
> @cnmade 表达观点是可以的，但是还是要注意这是一个被广泛使用的库的 issue 讨论区，可以合理讨论观点，不是你的吐槽专区。

react 都沦为政治工具了，影响更大，不见你说

**Comment by cnmade** [comment] 2022-03-03 08:29
> > @cnmade 表达观点是可以的，但是还是要注意这是一个被广泛使用的库的 issue 讨论区，可以合理讨论观点，不是你的吐槽专区。
> 
> react 都沦为政治工具了，影响更大，不见你说

1. 反思怪 2. 双标狗 3. 走狗
不管它是哪一种，我都不屑尿它

**Comment by cnmade** [comment] 2022-03-03 08:31
> @cnmade 表达观点是可以的，但是还是要注意这是一个被广泛使用的库的 issue 讨论区，可以合理讨论观点，不是你的吐槽专区。

我翻译一下给大家听听：
```
这是一个开源社区哟？我React要恶心大家了，你们准备好了么？ 你们不可以吐槽槽哦，那样你们很没礼貌哦？ 啥？我恶心到大家了？那你不支持乌克兰吗？你良心哪里去了？你不支持和平吗？你是恶魔吗？
```

**Comment by Huxpro** [comment] 2022-03-03 08:38
Duplicate of https://github.com/reactjs/reactjs.org/issues/4398

**Comment by gaearon** [comment] 2022-03-03 16:23
Hi there.

People in Ukraine are in the middle of a severe humanitarian crisis. According to UN, a million of people have become refugees this week. It is widely reported that many people, including kids, are sheltering in basements, traveling in freezing temperatures, and are short on supplies. This is why we would like to encourage everyone using React to help those in need.

It is true that we have not responded to every humanitarian disaster. There is no single objective threshold of scale, and we’ve only started doing these banners recently. However, this is not a zero-sum activity. First, we are only a single project, and there are other projects which may choose different causes (or not support any causes at all). Second, getting the message out about one crisis does not hurt people affected by a different crisis. This is why the “whataboutism” is mostly a distraction, and we will not spend time seriously entertaining it.

The Meta Open Source teams have collectively taken a stance in supporting humanitarian aid to Ukraine. The React team supports this stance. You are free to suggest other causes to support in the future. However, spamming the repo with duplicate issues and comments is disruptive. This violates the GitHub the terms of service, and GitHub will be removing this type of content. There is nothing more we would like to say on this at this point, so we will be locking this issue.

Thank you!

**Closed by gaearon** 2022-03-03 16:23 UTC
Labels: Status: Unconfirmed
