### ISSUE TITLE
TypeScript support for JSX

### ISSUE THREAD

**Issue by thorn0** [facebook/react#759] opened 2013-12-31 10:56 UTC
Would be great if JSX recognized TypeScript constructs.

**Comment by davidreher** [comment] 2015-01-16 15:07
anything new on this issue?

**Comment by pspeter3** [comment] 2015-01-16 16:05
FWIW, it's been fine just using the DOM factory functions in TypeScript

**Comment by RReverser** [comment] 2015-01-16 16:25
@davidreher I believe it's superseded with Flow now which supports TypeScript + JSX + ES6 syntax at once.

**Comment by sebmarkbage** [comment] 2015-01-16 17:57
Unfortunately I think that we need to leave this to the TypeScript team to make the decision if they want to support JSX since they have other syntax that conflicts with JSX.

Using TypeScript without JSX will still be possible but it's expected that it won't work quite as well as Flow. http://flowtype.org/ At least not as quickly. Since Flow is being developed with the intent to support React concepts.

**Comment by basarat** [comment] 2015-01-16 18:09
> since they have other syntax that conflicts with JSX

Which ones specifically (I suppose its just *type casting*)? Doesn't flow intend to have syntax parity with TypeScript? 


Note: TypeScript calls these *type assertions* because casting generally implies runtime safety.

**Comment by brigand** [comment] 2015-01-16 18:13
Basart, no, flow is intended to just work with JS+JSX+optional type
annotations.  The ideal case for flow is where you don't need any type
annotations, and it's just plain JavaScript (possibly with JSX)

TypeScript adds a lot of stuff that isn't in JS.. those things are specific
to TypeScript.

On Fri, Jan 16, 2015 at 11:09 AM, Basarat Ali Syed <notifications@github.com

**Comment by sebmarkbage** [comment] 2015-01-16 19:11
@basarat yea, just _type assertions_ conflicts. Flow doesn't support type assertions since it attempts to be more sound than TypeScript.

@brigand that's not quite correct. Flow works well without type annotations, but it definitely intents to use type annotations too. For three reasons:

- Documentation of intent and as a way to catch mistakes that would pass type inference but isn't intended to work.
- As a way to intentionally limit the API surface area even if it would currently work with a wider set of inputs. I.e. defining a contract.
- As a way to speed up type analysis of large code bases by enabling parallelized analysis.

Flow aims to unify with TypeScript where it makes sense but it doesn't attempt to support all the syntax/concepts and does diverge in some areas.

**Comment by brigand** [comment] 2015-01-16 21:19
Thanks for clarifying.

**Comment by fdecampredon** [comment] 2015-01-17 10:55
I had a TypeScript parser working with typescript and jsx with @CyrusNajmabadi method and it works fine never had time to finish it properly. The idea is pretty simple when we encounter a tag `<something>` we try to parse it as a JSX tag, if we have a parsing error, and we are in an ambiguous case (no attribute) we rewind the parser state and try to parse it as a type assertion.
This is not optimal because it will often report inadequate error, but at least it allows to parse all typescript construct and all JSX ones.

When I'll have time... I'll try to finish it

**Comment by RReverser** [comment] 2015-01-17 11:04
Yeah, I had pretty much the same and here is some brief demo from its early versions: http://www.youtube.com/watch?v=4c2pLtHf7KQ (shows how tags and type asserts are distinguished, completion support etc.) but decided to give up since TypeScript was/is breaking a lot of inner stuff in order to move to 2.0 and implement ES6, and final decision to suspend was caused by release of Flow which superseded all the features of all three worlds (ES6, JSX, TypeScript) and added even more.

**Comment by davidreher** [comment] 2015-01-19 07:09
@RReverser @sebmarkbage thanks for your suggestion. Since we are on a windows platform flow is actually not an option at the moment ... thanks for sharing your suggestions, but i think we need to think of a different solution. Either we will work with jsx for the views and ts for all the rest or don't make use of jsx at all.

**Comment by fdecampredon** [comment] 2015-01-19 08:34
@davidreher Honestly I still think that he good solution would be to create a TS fork with JSX support, my problem is that it will takes time, time that I don't have actually. @RReverser TSX could be a good base

**Comment by jbrantly** [comment] 2015-01-19 14:08
@davidreher In my upcoming talk at React.js Conf I'll be addressing the issue by using my hack described earlier in this issue (basically a JSX -> TS preprocessing step). I've posted an example in gulp, and during the conference I'll show how to do it with webpack. 

A TS fork with JSX support would be ideal, for sure, but creating one is beyond the realm of average coders and thus far nobody has released one, much less a stable production-ready one. Until that happens (and I hope and believe it eventually will), I believe the hack works wonders for the average "just need to get this project done before the deadline" developer.

**Comment by fdecampredon** [comment] 2015-01-19 15:04
@jbrantly  I did not release anything :D sorry to disappoint you ^^

**Comment by jbrantly** [comment] 2015-01-19 15:12
@fdecampredon I meant this: https://github.com/fdecampredon/jsx-typescript
Release may have been too strong a word. I meant "make available publicly".

**Comment by fdecampredon** [comment] 2015-02-05 13:14
I finally decided myself to finish this work : https://github.com/fdecampredon/jsx-typescript/ is an alpha version, it is just *working* and need extra works. it's based on master branch of typescript.
I'll publish it to npm soon but if someone could help me by testing it a bit (especially in visual studio, since I'm on OSX) that would help, thanks!

**Comment by abergs** [comment] 2015-02-05 14:50
@fdecampredon Very cool. I will test it when I have some available time. :+1:

**Comment by tedvanderveen** [comment] 2015-02-05 15:03
Cool!!

**Comment by basarat** [comment] 2015-02-05 21:00
Will definitely take it for a spin ❤️

**Comment by pspeter3** [comment] 2015-02-05 23:05
Congratulations!

**Comment by jbrantly** [comment] 2015-02-09 18:04
@fdecampredon Thanks for your continued contributions in this space! Wish you had released before React.js Conf, definitely would have mentioned it in my talk :(

I just updated [ts-loader](https://github.com/jbrantly/ts-loader) for webpack to support jsx-typescript, so if you're using TypeScript+JSX+webpack you may be interested.

**Comment by fdecampredon** [comment] 2015-02-09 18:11
Thanks @jbrantly unfortunately I had too much work to do before react conf and since my company don't use typescript nor react I can only work on that topic when I have free time.
Thank you for ts-loader! I generally use browserify but I'm thinking about switching to webpack since the workflow with browserify is a bit painful.

**Comment by pspeter3** [comment] 2015-02-09 18:37
I'm using browserify + gulp for incremental TypeScript compilation and can write about that if it would be helpful. Need to check out ts-loader

**Comment by nathggns** [comment] 2015-02-09 19:18
Something to flag up: I've written a proposal for another use of the `<` and `>` characters within the TypeScript language. While it is only used in places where defining generics can already be done, I just want to make sure there are no conflicts.

It's over at https://github.com/Microsoft/TypeScript/issues/1985

**Comment by fdecampredon** [comment] 2015-02-09 19:27
@nathggns I don't think there will be any problem, place where a generic can be defined was really not prone to conflict with JSX, the hardest part was about type assertion, which has been resolved with lookahead and close-tags map like @CyrusNajmabadi described, the only compromise I had to accept is to forbid the usage of the char `}` in jsx text (you have to use entities) to disambiguate cases like: 
```
<foo>{<foo>something}</foo>
```

After they might be still case I have not think about if anyone find one please report an issue.

**Comment by scboffspring** [comment] 2015-03-11 17:13
@pspeter3 have any config to share ?

**Comment by pspeter3** [comment] 2015-03-15 21:26
@scboffspring For gulp and browserify?

**Comment by scboffspring** [comment] 2015-03-16 09:19
@pspeter3 Yes please

**Comment by fdecampredon** [comment] 2015-03-23 14:42
> The discussion so far mostly talks about writing JSX syntax in .ts files so you can get the benefits of TypeScript such as static analysis. This would be nice, but this is not the only way to get the benefits of TypeScript. The other way is to write a translator from .jsx to .ts. (This could be a simple change to the existing .jsx to .js translator.) There should also be syntax extensions to specify the state and props fields and their types in an interface. Once translated to .ts, the TypeScript compiler can then verify the usage of props and state fields.

I have tried this way, but it is a lot more complex than having a fork with jsx support, firstly anyway you will need a parser that understand typescript and jsx anyway, secondly integration of a build step before typescript makes pretty hard to take advantage of the language service, and finally the type-checking for the compiled jsx is not handled pretty well by typescript.
For all this reasons I think [jsx-typescript](https://github.com/fdecampredon/jsx-typescript) is a lot more safer and easy to manage than having a build step jsx -> ts.

**Comment by jbrantly** [comment] 2015-03-23 15:01
@petilon That is exactly what [this](https://github.com/facebook/react/issues/759#issuecomment-40954893) suggests. I demoed this concept [here](https://www.youtube.com/watch?v=9PTa9-PPVAc&t=8m19s) along with showing some simplistic type checking on state and props. If you're using webpack, super easy to integrate it using [ts-jsx-loader](https://github.com/jbrantly/ts-jsx-loader).

All of that said, everything @fdecampredon says is true. I get around the parser understanding both TypeScript and JSX because I just regular expressions instead of a parser which has its own set of problems. I also require explicitly marking the JSX which I can certainly understand many people not being a fan of. My approach definitely lacks any sort of language service integration (intellisense, etc). And lastly, the type-checking for props using `createElement` is definitely **not** very good. I show some of this in my talk, but I only show the parts that work and skip over the parts that don't.

**Comment by 1two** [comment] 2015-03-24 15:05
Just adding a bit of my personal experience to that discussion.
I tried an alternative route which is to separate the JSX templates from the code, using [react-templates](https://github.com/wix/react-templates) and attempted to make it work for typescript. The sad conclusion is that is does not work well for the combination Typescript+IntelliJ/Webstorm (even with the latest 1.4 support). 

Also, because one needs to import another file (the compiled template), this sometimes end up with circular dependencies which are impossible to solve with the rigid 'import at the top' "feature" of Typescript. A typical exemple is a recursive display of a Menu object.

OTHA, inline solutions like ts-jsx-loader in IntelliJ/WS work great when you use backticks (templates strings). Syntax coloring and auto-completion is available for HTML inside the template string.

**Comment by fdecampredon** [comment] 2015-03-25 10:35
@1two the problem is that intellij don't use the LanguageService, which make it very hard to adapt to different ts version.

**Comment by 1two** [comment] 2015-03-25 10:52
@fdecampredon Not sure I follow you; do you mean variables/context discovery (in addition to syntax auto-completion) ?

Using this syntax in  IJ 14.1/WS 10EAP

    render() {
        //language="JSX Harmony"
        return React.jsx( `

        <li>
            <a title={this.props.title}>
                <span>{this.props.title}</span>
            </a>
        </li>

        `)
    }

I get syntax coloring and auto-completion on the JSX but nothing on `this` which is not inferred.
It works for me in nearly all cases but for sure, it will never be as good as direct full support of JSX in both the Typescript compiler and the IJ/WS syntax analyzer.

**Comment by fdecampredon** [comment] 2015-03-25 14:37
No typescript comes with a bundled languageService utilities for editor development. 
Last time I checked intellij did not use it. 
That's why with visual studio/atom-typescript etc you can directly use different typescript fork (like jsx-typescript) out of the box (as long as they respect language service interface), and that's why it does not work with intellij.

**Comment by Ciantic** [comment] 2015-03-30 06:07
Couldn't JSX just simply have escaping possibility:

    var a = 
        <SomeComponent>
        {
            if (someFunc\<generic\>(param)) {
                <NotGeneric>
            }
        }
        </SomeComponent>

Or in case of type-assertions:

    var a = 
        <SomeComponent>
        {
            if ((\<SomeType\> a).test) {
                <NotGeneric>
            }
        }
        </SomeComponent>

Either way, I think JSX transformer should have escaping.

**Comment by Rajeev-K** [comment] 2015-06-03 16:34
Another possibility is to generate TypeScript interfaces from .jsx files. Here's a tool to do this: https://github.com/fuselabs/jsxtyper

**Comment by QuantumInformation** [comment] 2015-06-19 20:08
Do you think there will be a solution that will allow TypeScript to be used with reflux?

**Comment by spicyj** [comment] 2015-06-19 21:22
@QuantumInformation Probably a better question for the reflux folks.

**Comment by spicyj** [comment] 2015-06-19 21:24
TypeScript may start supporting JSX per https://github.com/Microsoft/TypeScript/issues/3203. We don't have plans to develop JSX support separately from that, so I'm going to close out this issue – but feel free to continue discussing here or on https://discuss.reactjs.org/ if helpful.

**Closed by spicyj** 2015-06-19 21:24 UTC
Labels: JSX (React Flavored)

**Comment by spicyj** [comment] 2015-07-10 16:44
See http://www.jbrantly.com/typescript-and-jsx/ for an update from @jbrantly on the current state of affairs.
