### ISSUE TITLE
onChange event for input[type="range"] doesn't fire in IE10 and IE11

### ISSUE THREAD

**Issue by romanmatiasko** [facebook/react#2048] opened 2014-08-15 15:11 UTC
While in other browsers this works as expected, onChange (and also onInput in IE11) event doesn't get triggered in IE.

jsfiddle: http://jsfiddle.net/ekjone1z/

**Comment by spicyj** [comment] 2015-02-26 23:29
(Dupe of #554.)

**Closed by spicyj** 2015-02-26 23:29 UTC
