### ISSUE TITLE
Bug on resolving default props (HTMLAllCollection) + fix

### ISSUE THREAD

**Issue by karczk** [facebook/react#5957] opened 2016-02-01 20:53 UTC
**Introduction**
I found a bug on resolving default props when component props have property with HTMLAllCollection. React ignores value and uses default value (it should take that collection).

isIE9OrLower (look at the end of topic) is simple function to test Internet Explorer in version 9 or lower. Simple use case:
`isIE9OrLower() ? "IE9 or lower" : "modern browser ;)"`

Chrome/Firefox/modern IE (yeah, i know....) returns HTMLAllColection (as document.all), but old IE returns true. HTMLAllCollection is weird collection:

```
document.all // returns DOM collection
typeof document.all // returns "undefined" (!)
document.all === undefined // false (ok)
!document.all // returns true (!)
document.all && false // returns HTMLAllCollection (!)
[] && false // returns false (ok)
```

**Source of bug and fix**

- release: 0.14.7
- file: react.js
- line: 9149
- code (bug): if (typeof props[propName] === 'undefined') {
- code (fix): if (props[propName] === undefined) {

Btw, === undefined is faster than typeof === 'undefined' on Chrome and IE.
http://jsperf.com/type-of-undefined-vs-undefined/78

**Reproduction**
Open in Firefox / Chrome / IE10 or higher.

Fiddle: https://jsfiddle.net/69z2wepo/29719/
Raw:
```
<body>
    <div id="container"></div>

    <script type="text/javascript">
        var Hello = React.createClass({
            getDefaultProps: function() {
                return {
                    isPrehistoricBrowser: true
                };
            },
            render: function() {
                return React.createElement("div", null, "Hello " + (this.props.isPrehistoricBrowser ? "bug" : "World!"));
            }
        });

        ReactDOM.render(
            React.createElement(Hello, { isPrehistoricBrowser: isIE9OrLower() }), 
            document.getElementById('container'));

        function isIE9OrLower() {
            return document.all && !window.atob;
        }
    </script>
</body>
```

**Workaround**
Change
`document.all`
to
`!!document.all`

**Comment by jimfb** [comment] 2016-02-01 22:03
Haha, browsers suck.  Want to submit a PR?

It looks like we do that `typeof` thing unnecessarily in ~10 places in the React codebase.

```
jsproch-mbp:src jsproch$ grep -R " === 'undefined'" .
./addons/link/ReactLink.js:    value: typeof linkType === 'undefined' ?
./isomorphic/classic/class/ReactClass.js:        if (typeof initialState === 'undefined' &&
./isomorphic/classic/element/ReactElement.js:      if (typeof props[propName] === 'undefined') {
./renderers/dom/client/ReactDOMSelection.js:  if (typeof offsets.end === 'undefined') {
./renderers/dom/client/ReactDOMSelection.js:  var end = typeof offsets.end === 'undefined' ?
./renderers/dom/client/ReactInputSelection.js:    if (typeof end === 'undefined') {
./renderers/dom/ReactDOM.js:    if (typeof __REACT_DEVTOOLS_GLOBAL_HOOK__ === 'undefined') {
./renderers/shared/reconciler/ReactCompositeComponent.js:        typeof inst.props === 'undefined' || !propsMutated,
./renderers/shared/reconciler/ReactCompositeComponent.js:      if (typeof renderedComponent === 'undefined' &&
./shared/utils/traverseAllChildren.js:  if (type === 'undefined' || type === 'boolean') {
```

**Comment by karczk** [comment] 2016-02-02 00:15
I went through the react repo configuration (build, tests execution). Fix didn't break anything, but so far I didn't find solution to make good test (phantomjs doesn't have document.all property). document.all (HTMLAllCollection) is probably the only exception to the typeof and document.all is not a html standard.

https://msdn.microsoft.com/pl-pl/library/ms537434%28v=vs.85%29.aspx

> [all is no longer supported. Starting with Internet Explorer 11, use getElementById. For info, see Compatibility changes.]

Any suggestions to the unit test for this fix/improvement?

**Comment by jimfb** [comment] 2016-02-02 00:18
As long as you tested it manually and it worked in IE, I think we can accept this change without a unit test.

**Comment by jimfb** [comment] 2016-02-03 22:39
Fixed in https://github.com/facebook/react/pull/5965

**Closed by jimfb** 2016-02-03 22:39 UTC
Labels: good first bug

**Comment by spicyj** [comment] 2016-02-03 22:54
lol what even

**Comment by spicyj** [comment] 2016-02-03 22:59
I can't reproduce `typeof document.all` being `"undefined"` in IE 8 or IE 9 on Windows 7, either in standards or quirks mode. What am I missing?

**Comment by karczk** [comment] 2016-02-03 23:16
IE < 10 is fine. Problem occurs when using modern browser like Chrome, Firefox or IE >= 10, Edge. They returns `'undefined'`.

1. Set component prop as `document.all` in Chrome.
2. React will compare your prop with default prop (which is `true`). `typeof document.all` on Chrome is `'undefined'` so React treats it as missing value. Default prop (`true`) will be selected.
3. In the end, prop will be always set to `true` on modern browser in this case.

**Comment by spicyj** [comment] 2016-02-03 23:21
Oh! Sorry I totally misread. Yes I can repro this.
