### ISSUE TITLE
Inline setTimeout within the render causes a random number to appear on screen.

### ISSUE THREAD

**Issue by AlastairM-E** [facebook/react#16638] opened 2019-09-02 18:49 UTC
Reporting a bug:

The current behaviour is that setTimeout, inside a render method, is producing a random number, for no explained reason. The number persist after the setTimeout has gone off, and the setTimeout still produces the desired effect, for example, if it was to log something the console, it would still do that.
```jsx
// sample code

(not the original code in which the problem occurred, but I was able to reproduce the problem in codesandbox.io):

** start of code example **
(styles.css = 
    .App {
        font-family: sans-serif;
        text-align: center;
    }
)

import React from "react";
import ReactDOM from "react-dom";

import "./styles.css";

function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      {setTimeout(() => console.log("hello world"), 3000)}
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

/* (output of webpage) */

Hello CodeSandbox
Start editing to see some magic happen!
5

** end of code **

The expected behaviour was that the setTimeout function would produce no trace of any text, whilst still working.

It is present in react version 16.9.0

**Comment by threepointone** [comment] 2019-09-02 19:10
setTimeout returns a number (specifically a time-out id that you can use with clearTimeout) so this is expected behaviour. 

That said, you shouldn’t run code that generates side effects inside render directly; did you mean to call it inside useEffect?

**Comment by giovannibenussi** [comment] 2019-09-02 20:30
I cannot see your code clearly but I got an idea of what are you trying to do.

According to [Mozilla's setTimeout documentation](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout):

> The returned timeoutID is a positive integer value which identifies the timer created by the call to setTimeout(); this value can be passed to clearTimeout() to cancel the timeout.

You are trying to render a number because you have the setTimeout call inside curly braces in the returned value of your component, and it returns a number, so it will be rendered.

You need to add the setTimeout call by using the [`useEffect`](https://reactjs.org/docs/hooks-effect.html) hook:

```
function Counter() {
  useEffect(() => {
    setTimeout(() => console.log("hello world"), 3000)
  });

  return ...;
}
```

If you are not using hooks, you can add the `setTimeout` call inside `componentDidMount`:

```
class App extends React.Component {
  componentDidMount() {
    setTimeout(() => console.log("hello world"), 3000)
  }

  render() {
    return ...;
  }
}
```

**Comment by bvaughn** [comment] 2019-09-02 20:59
As @giovannibenussi mentioned, the `setTimeout` call is a side effect, so it belongs in an effect hook. You can read about them here: https://reactjs.org/docs/hooks-effect.html

For a bit more background info on why side effects are unsafe in render, the `StrictMode` docs page might be somewhat helpful: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

I'm going to close this issue since it's been answered. 😄

**Closed by bvaughn** 2019-09-02 20:59 UTC

**Comment by sahilkalkal** [comment] 2023-05-18 15:51
Just don't use setInterval() and setTimeout() inside render(), declare a function outside render() and use them in that function and then call that function in render(), it will not return id.
Hope it will work for you, it worked for me.
