### ISSUE TITLE
[Possible Improvements] NODE_ENV === 'staging' and warning about minification

### ISSUE THREAD

**Issue by le0pard** [facebook/react#6581] opened 2016-04-22 17:15 UTC
Hello.

We using react for some our projects and found, what on staging servers it start generate warning about "It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster". 

We still need all possible warnings about propTypes or about controlled/uncontrolled components to debug all issues on environment, which as close as possible to production, but still is not production. In this case "staging" environment should be builded with minification to check app before delivering on production. 

Proposal: remove this warning (https://github.com/facebook/react/blob/67f8524e88abbf1ac0fd86d38a0477d11fbc7b3e/src/renderers/dom/ReactDOM.js#L94-L100) for `NODE_ENV === 'staging'` env, if this possible. 

Thanks.

**Comment by jimfb** [comment] 2016-04-22 17:37
In general, if you are minifying your code on staging to simulate a production environment, you should probably be running the production copy of React just in case there are any subtle differences in the code paths (there shouldn't be, if we did everything right, but you never know and it's that type of bug that can really bite you).

Anyway, closing as a duplicate of https://github.com/facebook/react/issues/6479

**Closed by jimfb** 2016-04-22 17:37 UTC

**Comment by gaearon** [comment] 2017-10-04 19:03
Also, as I mention in https://github.com/facebook/react/issues/7512#issuecomment-334137262 regarding `staging` environment:

>React 16 ships with separate entry points for production CommonJS bundles in `react/cjs/react.production.min.js` and `react-dom/cjs/react-dom.production.min.js`. You can alias `react` and `react-dom` to these bundles to force a production environment even if `NODE_ENV` says otherwise.

So there is a workaround.
