### ISSUE TITLE
Warning: Did not expect server HTML to contain a <ul> in <div>

### ISSUE THREAD

**Issue by heathzipongo** [facebook/react#14843] opened 2019-02-14 01:34 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I'm using Server Side rendering with `react-loadable` and my home page see this in the browser.  The warning test to be a bit different on other pages, but still seems to happen generally.  My app is using Grommet in case that matters...

When the page renders I see the following in the console:
```
Warning: Did not expect server HTML to contain a <ul> in <div>.

warningWithoutStack | @ | react-dom.development.js:506
-- | -- | --
  | warnForDeletedHydratableElement | @ | react-dom.development.js:8254
  | didNotHydrateInstance | @ | react-dom.development.js:8960
  | deleteHydratableInstance | @ | react-dom.development.js:13964
  | popHydrationState | @ | react-dom.development.js:14183
  | completeWork | @ | react-dom.development.js:15801
  | completeUnitOfWork | @ | react-dom.development.js:17981
  | performUnitOfWork | @ | react-dom.development.js:18179
  | workLoop | @ | react-dom.development.js:18191
  | renderRoot | @ | react-dom.development.js:18277
  | performWorkOnRoot | @ | react-dom.development.js:19166
  | performWork | @ | react-dom.development.js:19078
  | performSyncWork | @ | react-dom.development.js:19052
  | requestWork | @ | react-dom.development.js:18921
  | scheduleWork | @ | react-dom.development.js:18730
  | scheduleRootUpdate | @ | react-dom.development.js:19398
  | updateContainerAtExpirationTime | @ | react-dom.development.js:19426
  | updateContainer | @ | react-dom.development.js:19483
  | ReactRoot.render | @ | react-dom.development.js:19775
  | (anonymous) | @ | react-dom.development.js:19915
  | unbatchedUpdates | @ | react-dom.development.js:19281
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:19911
  | hydrate | @ | react-dom.development.js:19969
  | (anonymous) | @ | client.js:52
  | Promise.then (async) |   |  
  | renderApp | @ | client.js:51
  | (anonymous) | @ | client.js:60
  | (anonymous) | @ | client.js:90
  | ./src/client.js | @ | main.js:10934
  | __webpack_require__ | @ | main.js:767
  | fn | @ | main.js:130
  | (anonymous) | @ | client.js:4
  | 0 | @ | main.js:11473
  | __webpack_require__ | @ | main.js:767
  | (anonymous) | @ | main.js:902
  | (anonymous) | @ | main.js:905
```
The html captured on the server was as follows:
```
<div lang="en-US" class="grommet grommetux-app grommetux-app--centered"><div class="grommetux-header__container grommetux-header__container--fixed grommetux-header__container--fill"><div class="grommetux-header__mirror"></div><div class="grommetux-header__wrapper grommetux-header__wrapper--small"><div class="grommetux-box grommetux-box--direction-column grommetux-box--responsive grommetux-box--pad-none grommetux-box--flex-off"><header class="grommetux-box grommetux-box--direction-row grommetux-box--align-center grommetux-box--pad-horizontal-none grommetux-box--pad-vertical-none grommetux-box--pad-between-small grommetux-header grommetux-header--small header"><div class="grommetux-box grommetux-box--direction-column grommetux-box--responsive grommetux-box--pad-none grommetux-menu grommetux-menu--column grommetux-menu--small grommetux-menu--controlled grommetux-menu__control"><button type="button" class="grommetux-button grommetux-button--plain" aria-label="Open  Menu"><span class="grommetux-button__icon"><svg version="1.1" viewBox="0 0 24 24" width="24px" height="24px" role="img" class="grommetux-control-icon grommetux-control-icon-menu grommetux-control-icon--responsive" aria-label="menu"><path fill="none" stroke="#000" stroke-width="2" d="M2,19 L22,19 M2,5 L22,5 M2,12 L22,12"></path></svg></span></button></div><div class="grommetux-box grommetux-box--direction-row grommetux-box--justify-start grommetux-box--align-center grommetux-box--flex-grow grommetux-box--pad-none grommetux-box--size-small grommetux-box--size grommetux-title grommetux-title--responsive grommetux-title--truncate"><a href="/" class="grommetux-anchor link link-white">Zipongo Admin Tool</a></div></header></div></div></div><div class="grommetux-box grommetux-box--direction-column grommetux-box--responsive grommetux-box--pad-small"><ul class="home-container small-block-grid-1 medium-block-grid-3 large-block-grid-5 text-center"><li class="home-item-container"><a class="home-item link link-white bold" href="/cafes">Cafe home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/cms">CMS home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/daily-emails">Daily email home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/easy-meals">Easy meals</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/foodscripts/plan">Foodscripts plan</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/household-invites/custom-text">Household custom text</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/mobile-push">Mobile push</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/partner-events">Partner events</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/orderwell-data">Orderwell data</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/tools">Tools home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/user">User home</a></li></ul></div><span style="display:none"></span><div class="grommetux-app__announcer" aria-live="polite"></div></div>
```
 I went in and added some debug logging in `warnForDeletedHydratableElement()` to output the `parentNode` and `child`, as follows:

```
parentNode:
<div class="grommetux-box grommetux-box--direction-column grommetux-box--responsive grommetux-box--pad-small"><ul class="home-container small-block-grid-1 medium-block-grid-3 large-block-grid-5 text-center"><li class="home-item-container"><a class="home-item link link-white bold" href="/cafes">Cafe home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/cms">CMS home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/daily-emails">Daily email home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/easy-meals">Easy meals</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/foodscripts/plan">Foodscripts plan</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/household-invites/custom-text">Household custom text</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/mobile-push">Mobile push</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/partner-events">Partner events</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/orderwell-data">Orderwell data</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/tools">Tools home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/user">User home</a></li></ul></div>
```
```
child:
<ul class="home-container small-block-grid-1 medium-block-grid-3 large-block-grid-5 text-center"><li class="home-item-container"><a class="home-item link link-white bold" href="/cafes">Cafe home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/cms">CMS home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/daily-emails">Daily email home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/easy-meals">Easy meals</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/foodscripts/plan">Foodscripts plan</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/household-invites/custom-text">Household custom text</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/mobile-push">Mobile push</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/partner-events">Partner events</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/orderwell-data">Orderwell data</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/tools">Tools home</a></li><li class="home-item-container"><a class="home-item link link-white bold" href="/user">User home</a></li></ul>
```
It was then I noticed something suspicious... in the browser inspector `parentNode` had a little bit different HTML than the server because the browser added `::before` and `::after` pseudo elements into the DOM of the `ul` as is noticeable in a screenshot I attached below.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I'm not in a place to be able to boil this down to a simple test case at this time, but at least it would be interesting to know if these pseudo elements in the DOM would break the hydration code?

**What is the expected behavior?**
That my hydrate doesn't fail because of these pseudo elements (it thats what it is)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Not sure, but it definitely happened with 16.7.0 and continues with 16.8.1

**Comment by heathzipongo** [comment] 2019-02-14 01:35
Here's the screenshot from the browsers's console... the first one is the `parentNode` the second is the `child`
![screen shot 2019-02-13 at 5 31 50 pm](https://user-images.githubusercontent.com/36862526/52756321-cd368880-2fb5-11e9-9c45-264820407405.png)

**Comment by nhunzaker** [comment] 2019-02-14 05:14
Huh. That's super interesting. I tried to reproduce this with the [DOM Hydration Fixture](https://react-dom-fixtures.surge.sh/hydration?version=16.7.0) using this example, but I wasn't able to find anything:

```javascript
// Add pseudo-selectors before React mounts DOM
var css = 'ul:before { content: "test"; display: block; } ul:after { content: "test"; display: block; }';
var style = document.createElement('style');
style.appendChild(document.createTextNode(css));
document.head.appendChild(style)

class Fixture extends React.Component {
  render() {
    return (
      <div>
        <ul>
          <li>Hello!</li>
          <li>Hello!</li>
          <li>Hello!</li>
          <li>Hello!</li>
          <li>Hello!</li>
        </ul>
      </div>
    )
  }
}
```

Still, it makes sense to me that pseudo selectors could mess things up. Trying to get a solid reproduction needs to the first step. Is that something you could help with?

**Comment by heathzipongo** [comment] 2019-02-22 00:45
I'm pretty busy with work but I've been slowly trying to whittle it down to something I can send you.  Might take a while

**Comment by nhunzaker** [comment] 2019-02-22 01:20
No worries :)

**Comment by heathzipongo** [comment] 2019-02-22 18:46
In the mean time, are there any resources or white papers to help me debug this issue locally on the odd chance there is something my app is doing to cause this?

**Comment by threepointone** [comment] 2019-02-23 12:36
Could you try this in an incognito window with *no* extensions running?

**Comment by heathzipongo** [comment] 2019-02-25 19:10
Same result, except that the stack trace is shorter:

![screen shot 2019-02-25 at 11 09 51 am](https://user-images.githubusercontent.com/36862526/53361997-0217d900-38ee-11e9-8e33-f2a2aaf1d730.png)

**Comment by alpap** [comment] 2019-10-25 16:34
any new on this i have the same problem with the warning <svg> in a <a>

**Comment by reginpv** [comment] 2019-11-03 05:40
Having this issue aswell currently :'(

**Comment by permanar** [comment] 2019-11-07 06:08
Yep, me too. It perfectly running in normal HTML. Then, I tried to convert it into JSX and everything is messed up. I am using Next.js as the SSR with React.

**Comment by threepointone** [comment] 2019-11-07 10:29
Y’all need to share a reproducing example with either codesandbox or as a a for repo if we have to debug this further. Simply complaining that it affects you won’t help if we can’t see some minimal code that reproduces the problem. Thanks!

Fwiw, this is NOT because of pseudo elements, because they’re not a part of the html that’s compared.

**Comment by bvaughn** [comment] 2020-01-16 17:05
I am going to close this issue since it has no repro case, we have been unable to reproduce it using the information reported, and question it raised (about pseudo elements) has been answered.

**Closed by bvaughn** 2020-01-16 17:05 UTC
Labels: Component: DOM, Component: Server Rendering, Type: Needs Investigation
