### ISSUE TITLE
React 16.6.0 performance is worse than 16.5.2

### ISSUE THREAD

**Issue by dragonflypl** [facebook/react#13987] opened 2018-10-26 13:45 UTC
Some time ago I did refactoring of cell renderers components to achieve performance gain (I have a huge table). I did refactoring from functional stateless components to `PureComponent`. E.g.:

    import React from 'react';
    import PropTypes from 'prop-types';
    
    class SomeCell extends React.PureComponent {
      render() {
        const { obj } = this.props;
        return (
          <>
            {obj.name}
            <br />
            {obj.isin}
          </>
        );
      }
    }
    
    SomeCell .propTypes = {
      obj: PropTypes.object,
    };
    
    export default SomeCell ;

Now I saw that `React.memo` was released so I updated to `react@16.6.0` and `react-dom@16.6.0` (from `16.5.2`) and refactored from `PureComponent` to `React.memo` with the expectation that it would be even faster (no lifecycle methods called, function smaller than class in memory etc...):

    import React from 'react';
    import PropTypes from 'prop-types';
    
    const SomeCell = React.memo(function({ obj }) {
      return (
        <>
          {obj.name}
          <br />
          {obj.isin}
        </>
      );
    });
    
    SomeCell .propTypes = {
      obj: PropTypes.object,
    };
    
    export default SomeCell;

And to my surprise, performance went significantly down.

Profile data in prod mode (no addons in chrome) show that there's much more scripting happening than before with `PureComponent` (scripting time for my case went from 0.5s to 3.8sek).

After some investigation, it seems that it is not an issue with `React.memo` but with the new version of React. I've reverted cell renderers to PureComponent and left new react@16.6.0 version and a result (significantly slower performance) is still present.

Do you have any idea what could be the issue with it?

**Comment by TrySound** [comment] 2018-10-26 17:31
@dragonflypl Did you tested in development or production mode?

**Comment by wojtekmaj** [comment] 2018-10-30 10:39
Hmmm, I couldn't reproduce it with a quick JSFiddle. Could you share Chrome Performance data? You can safe profiles by right clicking the list of timeline sessions.

![obraz](https://user-images.githubusercontent.com/5426427/47712605-6ffe0d80-dc38-11e8-89fc-a9055af8108a.png)

**Comment by dragonflypl** [comment] 2018-10-30 11:33
Thanks for help. Here're files:

[profiles.zip](https://github.com/facebook/react/files/2529427/profiles.zip)

It is `react-dom` update that slows things down.

**Comment by sophiebits** [comment] 2018-10-30 21:31
If your code is open source, can you please link it? Assuming it's not…

Can you possibly run a git bisect to help us figure out what React commit changed it? If you have a local clone of the repo, you should be able to run `yarn build` and then you'll have packages you can install in `build/node_modules`. You should be able to go from the tag `v16.5.2` to `v16.6.0` (using PureComponent for all, no need to use `memo`).

Thanks in advance for helping to investigate this. Best guess is something change with batching, but it's hard to tell.

**Comment by dragonflypl** [comment] 2018-10-31 09:56
I'll try. Btw. is there a way to download this repo but without cmd `git clone ... ` (I'm behind proxy that is blocking github cloning)

**Comment by noahbenham** [comment] 2018-10-31 20:53
@dragonflypl Can you try [setting your git config](https://github.com/w3c/epubcheck/issues/771#issuecomment-309230445) to work with the proxy?

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`
or
`git config --global http.proxy http://proxy.server.com:8080`

**Comment by sophiebits** [comment] 2018-11-01 18:44
You should be able to try cloning over either https (in which case you can also use a proxy) or ssh. Not sure if both are blocked. If that doesn't work I would clone from a different network and then copy the whole folder between computers (including the hidden .git directory). In normal cases you could download the tgz from GitHub but since you need the history here that won't work.

**Comment by dragonflypl** [comment] 2018-11-02 09:30
- 16.6.0 8b97a9c36f2ef7d2c570b25e988b8ca832d9b436

- 2 [b753f76a74644dd19e7a29f8aa4e8c759190f9ef] Fix failing async tests in Node 10 - bad
- 4 [95a313ec0b957f71798a69d8e83408f40e76765b] Unfork Lazy Component Branches (#13902) - bad
- 7 [e16cdd5b178a82db09f51349fe6c636a5072516f] Always bail out timed out children even if they receive an update (#13901) - good
- 6 [7268d97d2b2b595db24cb6210e535dd2bd421df2] Centralize props memoization (#13900) - good
- 5 [36db538226c45fc427abe4438851854892ee75c4] Bugfix for #13886 (#13896) - good
- 3 [d9a3cc070c3b554ce6c4b43b917c1ba8951f9b5f] React.lazy constructor must return result of a dynamic import (#13886) - good
- 1 [c9be16f5b6fc85e1458467a0c1e9743b15549424][scheduler] Rename priority levels (#13842) - good

- 16.5.2 bec2ddaf157497ddca85e823e180536d8154a52f

And the output is:

> $ git bisect good
> 95a313ec0b957f71798a69d8e83408f40e76765b is the first bad commit
> commit 95a313ec0b957f71798a69d8e83408f40e76765b
> Author: Sebastian Markbåge <sebastian@calyptus.eu>
> Date:   Fri Oct 19 22:22:45 2018 -0700

**Comment by sophiebits** [comment] 2018-11-02 14:02
@dragonflypl Thank you, this is really helpful.

**Comment by martinsb** [comment] 2018-11-02 16:39
I can also confirm that our app performance has dropped since 95a313e

**Comment by sophiebits** [comment] 2018-11-02 19:18
@sebmarkbage Any idea what could cause a perf regression from your "Unfork Lazy Component Branches" commit?

My instinct was incorrectly calling `resolveDefaultProps` leading to a missed bailout, but I verified in our test suite, only the tests that use `lazy` end up calling `resolveDefaultProps` so it doesn't seem to be that.

**Comment by gaearon** [comment] 2018-11-06 14:57
Hmm no, I'm wrong. `workInProgress.elementType === Component` should protect against this.

**Comment by gaearon** [comment] 2018-11-06 15:17
Gah. You already tried that. 😆

>My instinct was incorrectly calling resolveDefaultProps leading to a missed bailout, but I verified in our test suite, only the tests that use lazy end up calling resolveDefaultProps so it doesn't seem to be that.

**Comment by sompylasar** [comment] 2018-11-07 02:00
This may be minor but is there a reason to have two functions which call one another instead of one with all the code? From a brief review of the commit the inner function doesn't seem to be used anywhere else but I may be missing the bigger picture.
```js
export function createFiberFromElement(
  element: ReactElement,
  mode: TypeOfMode,
  expirationTime: ExpirationTime,
): Fiber {
  const fiber = createFiberFromElementWithoutDebugInfo(
    element,
    mode,
    expirationTime,
  );
  if (__DEV__) {
    fiber._debugSource = element._source;
    fiber._debugOwner = element._owner;
  }
   return fiber;
}
```

**Comment by gaearon** [comment] 2018-11-07 02:03
Google Closure Compiler (which is part of our build step) should inline it.

**Comment by localvoid** [comment] 2018-11-07 04:56
I think that I've noticed the same issue, here is how to reproduce:

1. `git clone https://github.com/localvoid/uibench-react.git`
2. `cd uibench-react`
3. `git checkout react-issue-13987`
4. `yarn`
5. `yarn build`
6. `http-server`
7. Open `http://127.0.0.1:8080/docs/16` url in the browser

![screenshot from 2018-11-07 11-43-42](https://user-images.githubusercontent.com/132045/48111356-bc25ff00-e283-11e8-9ed1-f93700611f4b.png)

[Switching from uglify to terser](https://github.com/localvoid/uibench-react/blob/react-issue-13987/webpack.config.js#L37-L40) fixed the issue:

![screenshot from 2018-11-07 11-46-37](https://user-images.githubusercontent.com/132045/48111395-e7105300-e283-11e8-9006-5a0e2fd4dc27.png)

**Comment by benwiley4000** [comment] 2018-11-07 05:01
"Switching minifiers solves the problem" was not the conclusion I expected to find at the bottom of this thread...

**Comment by sophiebits** [comment] 2018-11-07 05:29
Also – thank you @localvoid.

**Comment by sophiebits** [comment] 2018-11-07 05:42
In particular, piping

```js
(function() {
  function FiberNode(a) {
    this.tag = a;
  }
  function foo(a) {
    return new FiberNode(a);
  }
  global.foo = foo;
})();
```

to `npx uglify-es@3.3.9 -cm` gives

```
!function(){global.foo=function(n){return new function(n){this.tag=n}(n)}}();
```

which is bad news.

**Comment by sophiebits** [comment] 2018-11-07 05:57
@dragonflypl To confirm that what you're seeing is the same issue, can you (a) check that you're using uglify and (b) try checking out the same commit 95a313ec0b957f71798a69d8e83408f40e76765b from your bisect then editing packages/react-reconciler/src/ReactFiber.js to add a "FiberNode.foobar = {};" on line 273 (after the definition of FiberNode) then rebuild and see if it fixes the issue in your app?

**Comment by aweary** [comment] 2018-11-07 05:58
> maybe do something clever so that it doesn't try to inline it in React any more

If you use a function expression it won't inline it

```js
(function() {
  var FiberNode = function FiberNode(a) {
    this.tag = a;
  }
  function foo(a) {
    return new FiberNode(a);
  }
  global.foo = foo;
})();
```

```
!function(){var n=function(n){this.tag=n};global.foo=function(o){return new n(o)}}();
```

**Comment by aweary** [comment] 2018-11-07 06:01
> maybe do something clever so that it doesn't try to inline it in React any more

If you use a function expression it wont inline it

```js
(function() {
  var FiberNode = function FiberNode(a) {
    this.tag = a;
  }
  function foo(a) {
    return new FiberNode(a);
  }
  global.foo = foo;
})();
```

```
!function(){var n=function(n){this.tag=n};global.foo=function(o){return new n(o)}}();
```

**Comment by sebmarkbage** [comment] 2018-11-07 06:03
That's just not semantically equivalent. Seems like a pretty bad bug in `uglify`.

**Comment by sebmarkbage** [comment] 2018-11-07 06:06
`global.foo().constructor === global.foo().constructor`

**Comment by aweary** [comment] 2018-11-07 06:07
a

**Comment by sompylasar** [comment] 2018-11-07 07:15
It looks like something to do with `single_use` of `FiberNode`.

<img width="1372" alt="screen shot 2018-11-06 at 11 03 10 pm" src="https://user-images.githubusercontent.com/498274/48116023-9e23b480-e219-11e8-8d15-334a8b19e84e.png">

<img width="1149" alt="screen shot 2018-11-06 at 11 04 28 pm" src="https://user-images.githubusercontent.com/498274/48116030-a380ff00-e219-11e8-8192-dd23c23b6eff.png">

It does not inline if the constructor function is used more than once:
```js
(function() {
  function FiberNode(fiberNodeArg) {
    this.tag = fiberNodeArg;
  }
  function foo(fooArg) {
    return new FiberNode(fooArg);
  }
  function bar(barArg) {
    return new FiberNode(barArg);
  }
  global.foo = foo;
  global.bar = bar;
})();
```
```js
!function(){function n(n){this.tag=n}global.foo=function(o){return new n(o)},global.bar=function(o){return new n(o)}}();
```

**Comment by sompylasar** [comment] 2018-11-07 07:17
<img width="1147" alt="screen shot 2018-11-06 at 11 08 11 pm" src="https://user-images.githubusercontent.com/498274/48116162-15f1df00-e21a-11e8-8f41-2607317617f3.png">

<img width="1148" alt="screen shot 2018-11-06 at 11 09 57 pm" src="https://user-images.githubusercontent.com/498274/48116174-1db18380-e21a-11e8-9125-8c2b00969831.png">

**Comment by sophiebits** [comment] 2018-11-07 07:29
It’s rarely in a minifier’s best interest to inline variables/etc that are used many times, so that isn’t too surprising on its own. Note that 16.5.2 also calls the constructor only in one place. As @sebmarkbage points out though, it is incorrect to ever inline a function that “new” is applied to (unless it’s provable the instantiation runs at most once).

It seems like uglify-es is known to be buggy and is not maintained. We should probably focus our efforts on shifting people off it.

**Comment by sompylasar** [comment] 2018-11-07 07:40
For reference: https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-421509930 uglify-es is stale

> > so it seems strange to abandon it. Since you haven't deprecated it on NPM, should I assume you're only taking a break from maintaining it?
> 
> `uglify-es` has been forked and the new project is called `terser`. For projects that need ES6 support, use it instead of `uglify-es`, since all new development will be happening over there (and things like webpack are switching over to it shortly too):
> [fabiosantoscode/terser](https://github.com/fabiosantoscode/terser)

**Comment by danburzo** [comment] 2018-11-07 14:15
Thank you for the report and the solution. I hoped transitioning from `uglify-js` to `terser` (via their respective Webpack plugins) would be as simple as switching packages, but unfortunately terser seems to be running out of memory consistently on some of our machines, whereas uglify-js does not... 😕 (this is with either parallel=true or false). We've downgraded back to React 16.5.2 / uglify-js until we figure this out.

**Comment by gaearon** [comment] 2018-11-07 14:34
I guess we can close this then.

**Closed by gaearon** 2018-11-07 14:34 UTC
Labels: Type: Needs Investigation

**Comment by benwiley4000** [comment] 2018-11-07 16:39
Is it really fair to close this? It seems the proposed solution is to transition people from uglify to terser, which is not feasible in the very short term. Additionally as reported above by @danburzo terser has memory issues.

If it would be possible to edit the code (at least temporarily) to avoid the uglify-es bug that would be great.

**Comment by gaearon** [comment] 2018-11-07 16:46
The solution is not to transition from `uglify`, it's **from `uglify-es`**. This is a known buggy package which has already caused a bunch of bugs before. There is nothing we can do to fix this on our side — you are using a broken minifier.

**Comment by benwiley4000** [comment] 2018-11-07 17:41
Ah I see. I wasn't aware of those issues but I guess it's true uglify-es is
less widely used than uglify.

Le mer. 7 nov. 2018 11 h 49, Dan Abramov <notifications@github.com> a
écrit :

**Comment by robpalme** [comment] 2018-11-07 18:42
@danburzo Would you be up for raising an issue on the Terser repo and providing a reproduction case?  From what I can see, you are the first person to hit this issue.

**Comment by danburzo** [comment] 2018-11-07 19:08
> The solution is not to transition from uglify-js, it's to transition from uglify-es

Sorry, I meant `uglify-es`, amended my comment. We were using it via `uglifyjs-webpack-plugin@1.x.x`. Seems like bumping the plugin to `2.xx` is the easiest way to handle this at the moment, as it rolled back to `uglify-js`. (Will try it in the morning). 

In regards to terser, I'll follow up in the repo's issues with anything I can find, as to not derail this thread too much.

**Comment by dragonflypl** [comment] 2018-11-08 12:44
@sophiebits : I confirm that 

- application of the `FiberNode.foobar = {}` fixed performance issue
- currently I am using Webpack4 that under the hood has `"uglifyjs-webpack-plugin": "^1.2.4",` that has `"uglify-es": "^3.3.4",`). Migration to latest `uglifyjs-webpack-plugin` or `terser-webpack-plugin` solved the issue.

Thanks all for support!

**Comment by martinsb** [comment] 2018-11-08 13:49
I can also confirm that switching from Webpack 4's `uglify-webpack-plugin` to `terser-webpack-plugin` fixes the performance problem.
Thank you all!

**Comment by sophiebits** [comment] 2018-11-08 14:59
Thank you for confieming!

**Comment by ryankshaw** [comment] 2018-11-08 18:12
For anyone that needs a quick fix without having to upgrade to webpack 4 ([because the terser-webpack-plugin only works webpack 4+](https://www.npmjs.com/package/terser-webpack-plugin#requirements)) you can just turn off the `reduce_funcs` compression option for uglify-es (https://www.npmjs.com/package/uglify-es#compress-options). To do that in a webpack config it would look something like:
```javascript
    new UglifyJsPlugin({
      uglifyOptions: {
        compress: {
          reduce_funcs: false
        }
      }
    })
```
to verify that it worked I did the following: 
first:
```sh
cat test.js
```
```javascript
(function() {
  function FiberNode(fiberNodeArg) {
    this.tag = fiberNodeArg;
  }
  function foo(fooArg) {
    return new FiberNode(fooArg);
  }
//  function bar(barArg) {
//    return new FiberNode(barArg);
//  }
  global.foo = foo;
//  global.bar = bar;
})();
```

This is how the output looks when using `terser` (which does not have the bug):
```sh
cat test.js | npx terser --compress --mangle
```
```javascript
!function(){function n(n){this.tag=n}global.foo=function(o){return new n(o)}}();
```

this is how the output looks by default with `uglify-es`
```sh
cat test.js | npx uglify-es --compress --mangle
```
```javascript
!function(){global.foo=function(n){return new function(n){this.tag=n}(n)}}();`
``` 
(has the bug)

and finally, this is how the output looks with `uglify-es` and the `reduce_funcs` option set to `false`
```sh
cat test.js | npx uglify-es --compress reduce_funcs=false --mangle
```
```javascript
!function(){function n(n){this.tag=n}global.foo=function(o){return new n(o)}}();
``` 
(doesn't have the bug and is the same as what terser outputs)

**Comment by ryankshaw** [comment] 2018-11-08 18:16
obviously, only do that ^ if you need a quick bug fix that has the least amount of change to your code. the real long-term fix is to get on a newer version of webpack which will use terser.

**Comment by uriklar** [comment] 2018-12-17 11:51
I believe this issue should be made much more visible. I just got bitten by it. Also, because of it's nature, you might see it for the first time when pushing to production.

Maybe it should be added to the docs/release notes?

**Comment by dcworldwide** [comment] 2019-02-20 14:29
@uriklar  Is correct. We found this issue once we pushed to prod. 50k user system. Not a great DX for us.
