### ISSUE TITLE
Bug: Unnecessary `submit` event of form occurs across re-rendering

### ISSUE THREAD

**Issue by yukiyokotani** [facebook/react#25887] opened 2022-12-15 10:06 UTC
When a state update causes the form's submit button to be displayed, the form's submit event fires even though the submit button has not been pressed.

React version: 18.2

## Steps To Reproduce

1. Press the "Change Mode" button on the first linked sample.
2. Checking the console, you can see the `submit` event is fired.

Link to code example:

https://codesandbox.io/embed/friendly-alex-ehlut4?fontsize=14&hidenavigation=1&theme=dark

In the above sample, if the submit button is enclosed in `<div>`, this does not happen. Therefore, this phenomenon seems to be a bug related to React's re-rendering.

https://codesandbox.io/embed/cocky-frost-fwd7vm?fontsize=14&hidenavigation=1&theme=dark

## The current behavior

When the "Change Mode" button is pressed while in mode A, the `changeMode` handler for the `click` event is executed, and after being re-rendered in mode B, the `submit` event fires with the "Submit" button as the submitter.

## The expected behavior

When the Change Mode button is pressed while in mode A, only `changeMode`, the handler of the `click` event, is executed.

**Comment by eps1lon** [comment] 2022-12-23 13:12
Duplicate of https://github.com/facebook/react/issues/25930

**Closed by eps1lon** 2022-12-23 13:12 UTC
Labels: Status: Unconfirmed
