### ISSUE TITLE
Expose minified React with addons that includes TestUtils and Perf

### ISSUE THREAD

**Issue by jacehensley-wf** [facebook/react#7007] opened 2016-06-09 22:31 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**Requested feature:**
I am currently upgrading from React 0.14.7 to 15.1.0 and have noticed that our test suite is running considerably slower. In 0.14.7 it was running in about 4 minutes and with 15 it is running in about 15 minutes.

I created a custom version of react-with-addons.min.js that does not remove `TestUtils` and `Perf` which brought the time down to about 3 minutes.

My request is to expose a react-with-addons file that is minified but also includes `TestUtils` and `Perf`. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.1.0, yes in React 0.14.7 our test suite was not slowed down.

**Comment by gaearon** [comment] 2016-06-10 00:15
I’m a bit confused as to how

>our test suite is running considerably slower. In 0.14.7 it was running in about 4 minutes and with 15 it is running in about 15 minutes.

is related to 

>expose a react-with-addons file that is minified but also includes TestUtils and Perf.

In any case, the perf regression is likely the same as #6983 and will be fixed in the closest release.

**Comment by jacehensley-wf** [comment] 2016-06-10 15:35
I built another custom react-with-addons that did not include `React.addons.Perf`, since I am not using that, and saw the same results that I was seeing before removing `React.addons.Perf`.

That leads me to believe it is something with how `React.addons.TestUtils` runs in dev mode.

**Comment by gaearon** [comment] 2016-06-10 16:07
Can you check if you still have this problem with master?

**Comment by jacehensley-wf** [comment] 2016-06-10 16:42
It is __MUCH__ better but it seems to bog down towards the end of my test suite. 

If I run all tests by the end they are running slower. But if I just run those tests at the end they run just as fast as I would expect.

**Comment by gaearon** [comment] 2016-06-16 18:43
I’ll close because the problem is *mostly* solved in master per your report, and any marginal improvements are better done as PRs. You are welcome to contribute 😉

**Closed by gaearon** 2016-06-16 18:43 UTC

**Comment by jacehensley-wf** [comment] 2016-06-22 22:44
@gaearon Just as a follow up. Is there a roadmap/ETA for React 16?

**Comment by gaearon** [comment] 2016-06-23 00:08
I don’t think there’s anything in particular slated for 16, we’ll release whatever we have in a few months with some breaking changes. You can track the merged [16.0 milestone PRs](https://github.com/facebook/react/pulls?q=is%3Apr+milestone%3A16.0+is%3Aclosed).

**Comment by jacehensley-wf** [comment] 2016-06-23 16:17
Okay, thanks!
