### ISSUE TITLE
dangerouslySetInnerHTML escaping raw SVG on server

### ISSUE THREAD

**Issue by iamdevonbutler** [facebook/react#5232] opened 2015-10-21 14:39 UTC
Hi, I created the following component that accepts a raw svg string and transforms it into a react element. The component works; however, on the server, the SVG is being escaped.

```
import React, {PropTypes, Component} from 'react';

export default class Svg extends Component {

  static propTypes = {
    svg: PropTypes.string.isRequired,
  }

  render() {
    const {...other, svg} = this.props;
    return (
      <span {...other} dangerouslySetInnerHTML={{__html: svg}}></span>
    );
  }

}
```

In the browser console I get this error:

"React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server"

```
(client) .1.0.1"><svg xmlns="http://www.w3.org/20
(server) .1.0.1"><svg xmlns="\&quot;http://www.w3
```

**Comment by chicoxyzzy** [comment] 2015-10-24 19:06
duplicate of #5223

**Closed** 2015-10-24 23:51 UTC
