### ISSUE TITLE
Context does not work with Portals

### ISSUE THREAD

**Issue by d07RiV** [facebook/react#14391] opened 2018-12-04 21:41 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a component is rendered into document root via a Portal, it does not receive context from parent components.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
This is an example using React Bootstrap Overlay, which seems to be using portals (https://github.com/react-bootstrap/react-overlays/blob/master/src/Overlay.js):

https://jsfiddle.net/931bnzp4/2/

React DevTools shows the overlay component in a completely separate subtree, if that means anything. But it definitely calls `createPortal`, confirmed by stepping through overlays source.

**What is the expected behavior?**
Context should be visible inside the overlay component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This worked with previous context implementation, as seen in the fiddle.

**Comment by threepointone** [comment] 2018-12-05 22:30
could you try to reproduce the issue with a regular react portal, without including react-bootstrap?

**Comment by brollins90** [comment] 2018-12-06 02:42
I saw something similar with the react-bootstrap Overlay component.  The fix for me was to reimplement the OverlayTrigger component, which did NOT use the newer apis.

**Comment by jquense** [comment] 2018-12-06 03:00
All the current versions of react bootstrap use the portal apis. I'm gonna close this since it doesn't seem to be a react issue. Happy to reopen with a simplified reproduction tho!

**Closed by jquense** 2018-12-06 03:00 UTC
