### ISSUE TITLE
Datetime field doesn't register changes

### ISSUE THREAD

**Issue by derekdreery** [facebook/react#4733] opened 2015-08-28 12:44 UTC
When using a 'datetime-local' field, setting just the date doesn't register a change of value (so when setting to no value react doesn't know there has been a change).

A fix would be to always set the value of datetime fields even when the virtual dom shows no change - or just to accept it as a limitation.

```jsx
// An example
<input type="datetime-local" value={this.state.date} onChange={(evt) => {
    this.setState({date: evt.target.value})
}} />
```

(Tested on Chrome only (not supported on FF))

**Comment by derekdreery** [comment] 2015-08-28 12:49
This also affects `date` input fields in Chrome

**Comment by spicyj** [comment] 2015-08-28 20:00
Thanks. Dupe of #3659 probably.

**Closed by spicyj** 2015-08-28 20:00 UTC
Labels: Component: Events
