### ISSUE TITLE
In Chrome, synthetic drag and drop events should use DOMStringList for event.dataTransfer.types

### ISSUE THREAD

**Issue by aaronshaf** [facebook/react#3656] opened 2015-04-13 04:46 UTC
`event.dataTransfer.types.contains(...)` is broken in Chrome.

**Comment by syranide** [comment] 2015-04-13 08:09
Drag and drop events are not normalized by React (at the moment).

**Comment by aaronshaf** [comment] 2015-04-13 16:02
React seems to be inconsistently and unintentionally normalizing some dnd events in certain browsers.

**Comment by syranide** [comment] 2015-04-15 07:30
https://github.com/facebook/react/blob/master/src/browser/syntheticEvents/SyntheticDragEvent.js is the entire implementation (extends SyntheticMouseEvent which is normalized though), so `event.dataTransfer` is not currently normalized.

**Comment by gaearon** [comment] 2016-03-27 04:05
I’m closing this as a duplicate of #2676.

**Closed by gaearon** 2016-03-27 04:05 UTC
Labels: Component: Events
