### ISSUE TITLE
Bug: using useState without changing the state generate a useless rerender

### ISSUE THREAD

**Issue by Sharcoux** [facebook/react#18761] opened 2020-04-28 07:05 UTC
When using useState in a component, this component will rerender twice, whereas nor the state nor the props did change.

React version: 16.13.1

## Steps To Reproduce

1. Create a dummy functionnal component
2. Create a state with useState

Link to code example: [codesandbox](https://codesandbox.io/s/unnecessary-rerender-when-using-usestate-q82l5?file=/src/index.js)

```javascript
import React from "react";

let count = 0;

const App = () => {
  const [a] = React.useState("render");
  count++;
  console.log(a, count);
  return <div>{count}</div>;
};

export default App;
```

## The current behavior

Logs are:
render 1
render 2

## The expected behavior
render 1

**Comment by rositskyy** [comment] 2020-04-28 15:45
Same problem. When removing React.StrictMode it solves the problem

**Comment by nyz123** [comment] 2020-04-29 08:18
> Same problem. When removing React.StrictMode it solves the problem

When removing useState and useEffect it solves the problem,too.

**Comment by Sharcoux** [comment] 2020-04-29 09:26
> > Same problem. When removing React.StrictMode it solves the problem
> 
> When removing useState and useEffect it solves the problem,too.

Removing the component solves the problem too xD

**Comment by nyz123** [comment] 2020-04-29 09:36
> > > Same problem. When removing React.StrictMode it solves the problem
> > 
> > 
> > When removing useState and useEffect it solves the problem,too.
> 
> Removing the component solves the problem too xD

haha~,  you make me laugh...

**Comment by rovansteen** [comment] 2020-04-29 09:42
> It's an intentional feature of the StrictMode. This only happens in development, and helps find accidental side effects put into the render phase. We only do this for components with Hooks because those are more likely to accidentally have side effects in the wrong place.

Source: https://github.com/facebook/react/issues/15074#issuecomment-471197572

**Comment by Sharcoux** [comment] 2020-04-29 09:52
Ok, my bad then. I didn't know at all about this feature. Should strict mode log a message in develpment to warn about this or anything? I think it is hard for devs to discover about the source of what they may experience in the current state of things.

**Comment by Eddie-CooRo** [comment] 2020-04-29 16:33
@Sharcoux I think Sebastian already worked on this part: [PR](https://github.com/facebook/react/pull/18547).
But as a general rule, React doesn't promise anything about when and how many times it calls our function. So it might call the render function multiple times even outside of the StrictMode.

**Comment by macmaster** [comment] 2020-05-03 05:08
Cool, thanks for sharing. I learned something new:

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by rachelnabors** [comment] 2020-07-09 12:41
I can confirm this is fixed in https://github.com/facebook/react/pull/18547 and the fix will be included in React 17. To be clear, the component will still run twice, but the `console.log` will be disabled on the second run.

**Closed by rachelnabors** 2020-07-09 12:41 UTC
Labels: Status: Unconfirmed

**Comment by gaearon** [comment] 2022-03-30 18:08
To clarify, there was no bug here, and so nothing was fixed. The behavior is as intended: StrictMode calls your component function twice to help find accidental mutations and side effects.
