### ISSUE TITLE
nextState in shouldComponentUpdate is equal to this.state

### ISSUE THREAD

**Issue by svapreddy** [facebook/react#14873] opened 2019-02-17 04:34 UTC
**Do you want to request a *feature* or report a *bug*?**  
Bug   

**What is the current behavior?**

I am trying to use shouldComponentUpdate hook to avoid child re-render. So I added `shouldComponentUpdate` hook to detect if child re-render is necessary or not.

While doing that, I noticed a behavior where nextState received in shouldComponentUpdate and `this.state` are equal. I am assuming this is not correct behavior considering the goal of `shouldComponentUpdate`.  Please check the example in  [codesandbox.io](https://codesandbox.io/s/3rxlyyv1w6)

**What is the expected behavior?**
Assuming the `nextState` should not be equal to `this.state` when `shouldComponentUpdate` is called. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am not sure about previous versions of React. But the current React version I checked is `16.8.0`

**Comment by marvinhagemeister** [comment] 2019-02-17 09:00
This is the expected behaviour. You're running into this problem because you're mutating the current `state` inside the `setState` callback.

Instead the `setState` return value should be a __new__ `object` containing only the updated properties. 

```js
this.setState({ a: 11 });
```

**Comment by svapreddy** [comment] 2019-02-17 10:42
@marvinhagemeister Thanks for the response. That makes sense as the state passed to the callback is holding reference to this.state object.

Unfortunately `shouldComponentUpdate` does not talk about it as it is mentioned in the `setState` documentation. Any thoughts on passing an extra parameter to the `shouldComponentUpdate` to communicate the nextState is equal to the this.state? Will be useful for developers to skip using nextState in conditionally re-rendering in such cases. This would be really helpful as `shouldComponentUpdate` is given as a tool to increase the React's performance.

**Comment by threepointone** [comment] 2019-02-17 15:22
This would not be a good idea - mutating this/state directly is the source of many bugs, and goes against the way React handles updates and state changes. In your case, doing the comparison would be pretty fast and efficient, so I don't see the need to add a new api. The linked doc has more detail, and links to more resources if you're curious. closing this issue, cheers.

**Closed by threepointone** 2019-02-17 15:22 UTC
