### ISSUE TITLE
Component sometimes fires event handlers twice

### ISSUE THREAD

**Issue by patrick-radulian** [facebook/react#16763] opened 2019-09-12 12:38 UTC
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
Event handlers on elements are fired twice, when hovering from one element onto the next.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/quizzical-mountain-9s48c

**What is the expected behavior?**
Event handlers should only fire once.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.4
ReactDOM 16.8.4
Chrome 76.0.3809.132
Firefox 69.0 (64-Bit)
Edge 44.18362.267.0

**Comment by yuanoook** [comment] 2019-09-21 20:27
After testing it, again and again, I found how to reproduce it:

Step 1, render a new component inside a rendered component;
Step 2, inside the new component, mouse enter a node by mousing out from its sibling.

Current result: onMouseEnter is called more than once.
Demo: https://codesandbox.io/s/hungry-field-kgkli

@bvaughn We may change the issue title because it's not related with `dangerouslySetInnerHTML`.

I've made a test and fixture for this: https://github.com/yuanoook/react/commit/71dcd9ed72e21a2d7f3d9345a3ab8a7dffb23bc3

Hope the information can be helpful. I still have no idea how to fix it.

**If there's no one working on this, I would like to pick this up.**

There's a similar issue https://github.com/facebook/react/issues/10906 
@gaearon Do you have any advice?

**Comment by bvaughn** [comment] 2019-09-23 15:50
> If there's no one working on this, I would like to pick this up.

Go for it, @yuanoook!

**Comment by souravbadami** [comment] 2019-10-24 11:21
Let's close this? I see the fix was merged in #16928.

**Closed** 2019-10-24 18:18 UTC
Labels: Type: Bug, good first issue (taken)
