### ISSUE TITLE
Error: "Cannot read property 'isCollapsed' of undefined"

### ISSUE THREAD

**Issue by mrYbc** [facebook/react#23397] opened 2022-03-02 09:57 UTC
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-5eb066c

Call stack: at store_Store.getElementAtIndex (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:22078:35)
    at store_Store.getElementIDAtIndex (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:22094:26)
    at chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:29537:63
    at List.render (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:23810:18)
    at Ji (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:14036:76)
    at Ii (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:14027:10)
    at vk (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:16776:86)
    at uk (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:16293:11)
    at rk (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:16285:23)
    at kk (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:16269:5)

Component stack: at List (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:23505:30)
    at div
    at AutoSizer (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:3125:5)
    at div
    at div
    at Tree_Tree (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:29298:47)
    at div
    at div
    at OwnersListContextController (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:28447:3)
    at SettingsModalContextController (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:28888:3)
    at Components_Components (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:34765:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:30173:5)
    at PortaledContent (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:30253:5)
    at div
    at div
    at ProfilerContextController (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:34384:3)
    at TreeContextController (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:25298:3)
    at SettingsContextController (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:25912:3)
    at ModalDialogContextController (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:30396:3)
    at DevTools_DevTools (chrome-extension://bkcfmmcegcefjgackpfecdalgkgoalpk/build/main.js:37759:3)

**Comment by bvaughn** [comment] 2022-03-04 20:40
Hi!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2022-03-09 18:30
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2022-03-09 18:30 UTC
Labels: Resolution: Needs More Information, Component: Developer Tools
