### ISSUE TITLE
Bug: setState Executed twice;

### ISSUE THREAD

**Issue by laolaolulu** [facebook/react#24057] opened 2022-03-09 04:51 UTC
```js
import { useState, useEffect } from "react";

export default function App() {
  const [test, setTest] = useState<number>(1);
  const [test1, setTest1] = useState<number>(1);
  useEffect(() => {
    const test = () => {
      console.log("test");
      setTest(() => {
        setTest1(2);
        console.log("edit");
        return 0;
      });
    };

    window.addEventListener("scancode", test);
    setTimeout(() => {
      window.dispatchEvent(new CustomEvent("scancode"));
    }, 1000);
  }, []);

  return (
    <div className="App">
      <h1>test:{test}</h1>
      <h1>test1:{test1}</h1>
    </div>
  );
}
```

### Why output test once and edit twice?

Link to code example:

https://codesandbox.io/s/determined-shape-tkpreq?file=/src/App.tsx

**Comment by vkurchatkin** [comment] 2022-03-09 16:29
You can't perform side effects (such as calling `setTest1`) in the function that is passed to `setTest`. It is supposed pure. Because of this, it might be called more than once, for example in `StrictMode`

```js
setTest(() => {
        setTest1(2); // <--- HERE
        console.log("edit");
        return 0;
      });
```

**Comment by eps1lon** [comment] 2022-03-12 08:40
In addition to the above explainer, you can check https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects which explains this behavior in more detail.

Closing since this is expected behavior.

**Closed by eps1lon** 2022-03-12 08:40 UTC
Labels: Status: Unconfirmed
