### ISSUE TITLE
Cannot Click into Select on any version of IE

### ISSUE THREAD

**Issue by VonKieffer** [facebook/react#6845] opened 2016-05-23 17:34 UTC
Nothing happens when I attempt to click into the date select on IE.  Works on every other browser.

              <Select
                name="exp_month"
                placeholder="Month"
                options={monthsArray()}
                optionValue={(x) => x.padded}
                optionText={(x) => x.name}
                {...exp_month}
                error={null}
              />

export function monthsArray() {
  return [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ].map((monthName, index) => {
    let month    = {};
    month.name   = monthName;
    month.abbr   = month.name.slice(0, 3);
    month.number = index + 1;
    month.padded = (month.number < 10 ? '0' + month.number.toString() : month.number.toString());
    return month
  })
}

**Comment by jimfb** [comment] 2016-05-23 18:00
@VonKieffer Can you provide a jsfiddle that demonstrates the issue?

**Comment by VonKieffer** [comment] 2016-05-23 18:16
I wouldn't even know where to begin, massive code base.  I tried to include what I thought was necessary.

**Comment by jimfb** [comment] 2016-05-23 18:52
@VonKieffer Your example uses a `Select` with a capital `S` and you're setting props which you didn't define in the code above.  The code fragments you posted depend on application logic outside of React, and do not allow us to easily reproduce your issue.  If you can't reproduce the bug in a jsfiddle, it's probably an issue in your application.  Either way, we are going to need a reproducible test case that demonstrates the bug (otherwise this issue is unactionable).

**Comment by gaearon** [comment] 2016-05-23 20:54
@VonKieffer To be completely clear, `Select` is not something React provides. It’s a custom component that you import from somewhere. Have you verified it’s not a bug in that `Select` component?

**Comment by VonKieffer** [comment] 2016-05-23 21:20
My select component :

import React from 'react'
import './Select.css'

export function Select(props) {

  let {
    label,
    name,
    value,
    options,
    onChange,
    onBlur,
    error,
    touched,
    placeholder,
    optionValue,
    optionText,
    style = {
      width: 'auto',
    },
    changed = function() {}
  } = props

  const styles = {
    Select: {
      display: 'inline-block',
      width: style.width,
    },
    wrapper: {
      position: 'relative',
      display: 'inline-block',
      background: value ? '#80b729' : '#FFF',
      color: !value ? '#80b729' : '#FFF',
      width: style.width,
    },
    select: {
      WebkitAppearance: 'none',
      MozAppearance: 'none',
      background: 'none',
      border: '1px solid #80b729',
      borderRadius: '0px',
      padding: '5px 30px 5px 10px',
      position: 'relative',
      fontFamily: "'Open Sans', sans-serif",
      fontWeight: 400,
      fontSize: '19px',
      width: '100%',
    },
    option: {
      background: '#fff !important',
      color: 'black !important'
    },
    arrow: {
      width: '8px',
    	height: '8px',
    	borderLeft: `2px solid ${!value ? '#80b729' : '#FFF'}`,
    	borderBottom: `2px solid ${!value ? '#80b729' : '#FFF'}`,
      transform: 'rotate(-45deg) ',
      WebkitTransform: 'rotate(-45deg) ',
      position: 'absolute',
      top: '0.9em',
      right: '0.9em',
    }
  }

  return (
    <div className="Select fieldset-validate" style={Object.assign(styles.Select, style)}>
      {label ? <p><label className="bebas grey">{label}</label></p> : null}
      <div style={styles.wrapper}>
        <div style={styles.arrow}/>
        <select style={styles.select} className={value ? '-hasValue' : ''} name={name} defaultValue='' value={value} onBlur={onBlur} onChange={(e) => onChange(e, changed(e.target.name, e.target.value))}>
          {placeholder ? <option value='' disabled>{placeholder}</option> : null}
          {options ? options.map((option, index) => {
            return (
              <option key={index} style={styles.option} value={optionValue ? optionValue(option) : option}>{optionText ? optionText(option) : option}</option>
            )
          }) : null}
        </select>
      </div>
      {error ? <div className="Input-error">{error}</div> : null}
    </div>
  )
}

Select.propTypes = {
  label:    React.PropTypes.string,
  name:     React.PropTypes.string.isRequired,
  options:  React.PropTypes.array.isRequired,
  changed:  React.PropTypes.func,
  onChange: React.PropTypes.func,
}

export default Select


And my select.css

select {
  &:-moz-focusring {
    color: transparent;
    text-shadow: 0 0 0 #80b729;
  }
  &.-hasValue:-moz-focusring:not(:active) {
    color: transparent;
    text-shadow: 0 0 0 #fff;
  }
  option:disabled {
    color: gray !important;
    background: #fff !important;
  }
  &::-ms-expand {
    visibility: hidden;
  }
}

**Comment by VonKieffer** [comment] 2016-05-23 21:22
I have quite a few issues throughout the application just with IE, each having to do with my react component rendering

**Comment by jimfb** [comment] 2016-05-23 21:27
@VonKieffer Your code is still setting props that you haven't specified in this issue.  Realistically, there is too much going on here for us to easily see if this is in userland or a React bug.   I think we're going to need simplified examples using jsfiddles.

**Comment by zpao** [comment] 2016-05-23 23:08
FYI: I fixed the formatting in your comment above.

While this is a much smaller example than being deep in your app, as Jim said, the most helpful thing would be a jsfiddle (here's a good one to start from: https://jsfiddle.net/reactjs/69z2wepo/). You can probably use most of the code you have above as is in there and then just make sure it reproduces in IE. It would be even more helpful if you could reduce it further (Eg, if you removed all the styles, does this still happen? or is there some specific style that breaks it?)

**Comment by jimfb** [comment] 2016-06-08 21:23
No fiddle from OP, closing.  We can re-examine if we get a fiddle that demonstrates a React bug.

**Closed by jimfb** 2016-06-08 21:23 UTC
Labels: Status: Unconfirmed
