### ISSUE TITLE
PropTypes metadata

### ISSUE THREAD

**Issue by brigand** [facebook/react#5067] opened 2015-10-07 04:24 UTC
It'd be great if propTypes had a property that gave vision into the expectations. This would allow easily generating documentation without parsing the code, which is easier and allows flexibility like reusing propType shapes, etc. It also helps with test automation / coverage reports.

Also related, a .note method on propTypes would allow better error messages, documentation, and coverage report output, and static analysis error messages e.g. in flow.

```js
class Foo extends React.Component {
  static propTypes = {
    name: PropTypes.string.isRequired
      .note('The user\'s full name'),
    color: PropTypes.oneOf(['red', 'green', 'blue']),
    car: PropTypes.shape({
      model: PropTypes.string.isRequired,
      make: PropTypes.string.isRequired,
    }),
  };
  // ...
};
```

expression | result
---- | ----
`Foo.propTypes.name.meta.type` | `'string'`
`Foo.propTypes.name.meta.note` | `'The user\'s full name'`
`Foo.propTypes.color.meta.type` | `'oneOf'`
`Foo.propTypes.color.meta.variants` | `['red', 'green', 'blue']`
`Foo.propTypes.car.meta.shape.model.meta.type` | `'string'`

Why react core? I started writing a library that does this, but I realized that tools like flow require you to use react's propTypes.  This would be a non-breaking change, and I think it adds a moderate amount of value.

**Comment by keithamus** [comment] 2015-10-07 08:41
I've tried to use PropTypes as a way to generate dynamic forms which allow demoing the element - a React playground, if you will. The use case is similar to the above.

Right now it is possible to introspect *some* information out of the proptypes, but certainly not enough. For instance, I can perform equality checks to see what the types are - it's a little painful, but mostly works:

```js
const mapping = {};
for (const key in component.propTypes) {
  switch (component.propTypes[key]) {
    case React.PropTypes.array:
      mapping[key] = { type: 'array', required: false };
      break;
    case React.PropTypes.array.isRequired:
      mapping[key] = { type: 'array', required: true };
      break;
    case React.PropTypes.bool:
      mapping[key] = { type: 'bool', required: false };
      break;
    case React.PropTypes.bool.isRequired:
      mapping[key] = { type: 'bool', required: true };
      break;
    case React.PropTypes.func:
      mapping[key] = { type: 'func', required: false };
      break;
    case React.PropTypes.func.isRequired:
      mapping[key] = { type: 'func', required: true };
      break;
    case React.PropTypes.number:
      mapping[key] = { type: 'number', required: false };
      break;
    case React.PropTypes.number.isRequired:
      mapping[key] = { type: 'number', required: true };
      break;
    case React.PropTypes.object:
      mapping[key] = { type: 'object', required: false };
      break;
    case React.PropTypes.object.isRequired:
      mapping[key] = { type: 'object', required: true };
      break;
    case React.PropTypes.string:
      mapping[key] = { type: 'string', required: false };
      break;
    case React.PropTypes.string.isRequired:
      mapping[key] = { type: 'string', required: true };
      break;
    case React.PropTypes.element:
      mapping[key] = { type: 'element', required: false };
      break;
    case React.PropTypes.element.isRequired:
      mapping[key] = { type: 'element', required: true };
      break;
    default:
      mapping[key] = 'unknown';
      break;
  }
}
```

The problem is as soon as we get to the function call variants: `instanceOf`, `oneOf`, `oneOfType`, `arrayOf`, `objectOf`, `shape` - or custom validator functions, the entire thing falls apart, as these functions become fully opaque.

I love the idea of having a meta object, `type`, `required` and `variants` would be minimum requirements for me - although I'd additionally love to see a `description`/`notes` too.

**Comment by iamdustan** [comment] 2015-10-07 12:34
These needs are fully met by tools such as https://github.com/reactjs/react-docgen without requiring anything additional to the PropTypes API.

Whilst it does require a bit more tooling, this likely isn’t a barrier for most of us in the React community since we’re already using compilers like babel and build tools like webpack and browserify.

**Comment by iamdustan** [comment] 2015-10-07 12:38
Related convo #3510

**Comment by keithamus** [comment] 2015-10-07 14:14
The downside to react-docgen is that it doesn't provide runtime introspection, and with React PropTypes we're already incredibly close to that. It's a shame that React is very declarative, while offering little in terms of runtime introspection - the two almost go hand in hand.

**Comment by iamdustan** [comment] 2015-10-07 14:20
I understand that. That was my initial thought as well. Turned out I could treat the code as data and annotate it for runtime introspection automatically. I originally wrote https://github.com/Skookum/react-autodoc for that very purpose, but have opted to use and support docgen instead. We’re able to use this to automatically generate an interactive styleguide/documentation site with propType declarations as well—and that’s just one more React component away from having an autogenerated form for different permutations of a component.

**Comment by NameFILIP** [comment] 2016-04-03 19:14
Yes, having a form based on propTypes that allows you to live edit the component would be superuseful. For that it would be cool if we can get a structure of propTypes from a component. As said above, right now it's quite hard, if possible, to get values of `oneOf`, `shape`, etc. propTypes.

**Comment by jimfb** [comment] 2016-04-03 20:55
Proptypes are mostly legacy and in maintenance mode, having been replaced by tools like Flow. My guess is we aren't going to add this, so let's close it out. We can re-open if our thinking on this matter changes substantially.

**Closed by jimfb** 2016-04-03 20:55 UTC
