### ISSUE TITLE
Cannot type Chinese  in `<input />`  under controlled mode + ReactDom 16.8.2

### ISSUE THREAD

**Issue by youluna** [facebook/react#14861] opened 2019-02-15 13:23 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Cannot type Chinese  in `<input />`  under controlled mode when using react-dom 16.8.2 via CND

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/youluna/egz9Lvrp/36/
1. Switch IME(input method editor) into Chinese
2. try type any letters, you can only get English letters but not Chinese characters
![image](https://user-images.githubusercontent.com/10049465/52859396-8be5da80-3167-11e9-96ac-95caa4e7f5a7.png)

**What is the expected behavior?**
Can type Chinese characters
![image](https://user-images.githubusercontent.com/10049465/52859361-740e5680-3167-11e9-8a7c-6e28d7650b4e.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Not worked in react-dom 16.8.2 
But worked well in react-dom 16.8.1 

related https://github.com/alibaba-fusion/next/issues/324

update:
It's wired that use React as a <script> tag from a CDN doesn't work, but as a react package on npm worked well. Both are version 16.8.2
1. CDN: https://jsfiddle.net/youluna/6o3rhg7u/1/
2. npm: https://codesandbox.io/s/xp15m8woww

**Comment by apyrkh** [comment] 2019-02-18 09:48
The problem is not only with Chinese.
When cursor is in the middle of input text  and you're typing the cursor jumps to the end.

Reproduced on 16.8.2. On 16.8.1 works correctly, please check the pen 
https://codepen.io/apyrkh/pen/GzPBpK

**Comment by nhunzaker** [comment] 2019-02-20 00:00
Yikes! This isn't good! 

I can confirm with the [DOM Test Fixtures](http://react-dom-fixtures.surge.sh/) that something changed between React 16.8.1 and 16.8.2 to break text selection.

The module that usually handles this hasn't been updated since November:
https://github.com/facebook/react/commits/master/packages/react-dom/src/client/ReactDOMInput.js

I wonder what else it could be...

**Comment by afc163** [comment] 2019-02-20 03:01
It breaks our `<Input />` in codepen demo too: https://codepen.io/afc163/pen/bzZjLd

ref #14931

**Comment by otakustay** [comment] 2019-02-21 13:59
> I wonder [what else it could be](https://github.com/facebook/react/compare/v16.8.1..v16.8.2)...

One possible cause could be the fiber reconciler to break composition state of input, committing values in a wrong stage

**Comment by dancerphil** [comment] 2019-02-21 14:19
maybe https://github.com/facebook/react/pull/14799 fires more performSyncWork?
I may be wrong.

**Comment by nhunzaker** [comment] 2019-02-21 16:02
@dancerphil I built a version of React that omits this addition and the problem persists, but thanks for taking a look!

**Just to reiterate:** this is only reproducible in the UMD builds of React, at least for the latin character set. 

**This Codesandbox is fine (CommonJS build)**
https://codesandbox.io/s/6wm5wp98yk

**However this JSFiddle is broken (UMD Build)**
https://jsfiddle.net/j2o9g085/2/

Would anyone be willing to verify this for me with composable characters (like Chinese)?

**Comment by nhunzaker** [comment] 2019-02-21 16:10
Ah looks @gaearon is already on top of this:
https://github.com/facebook/react/pull/14914

**Comment by nhunzaker** [comment] 2019-02-21 16:19
I built a version of our DOM fixtures with this change:
https://react-dom-umd-fix.surge.sh/hydration

This is working for me with latin characters. Just for good measure: could someone confirm this with composable characters (like Chinese)?

**Comment by gaearon** [comment] 2019-02-21 16:30
@nhunzaker For the future, please don't hesitate to reach out when you see a critical issue like this. I saw "Chinese" in the title and assumed this is some old IME bug.

**Comment by nhunzaker** [comment] 2019-02-21 16:38
@gaearon Sorry :cry:. Will do.

**Comment by gaearon** [comment] 2019-02-21 16:39
No problem, thanks for jumping on it anyway. :-)

**Comment by nhunzaker** [comment] 2019-02-21 16:53
Confirmed this is a valid fix for composed Japanese too, :+1:

**Comment by gaearon** [comment] 2019-02-21 18:31
Fixed in 16.8.3.

**Closed by gaearon** 2019-02-21 18:31 UTC
Labels: Component: DOM, Type: Bug
