### ISSUE TITLE
Setting select value fails when using optgroup

### ISSUE THREAD

**Issue by tanepiper** [facebook/react#6434] opened 2016-04-07 13:43 UTC
As per this fiddle: http://jsfiddle.net/gqdzgue2/

The output of this in the select field is (edited for brevity)

```
<select>
  <optgroup label="Scotland">
    <option value="Fife" label="Fife">Fife</option>
    <option value="Midlothian" label="Midlothian">Midlothian</option>
  </optgroup>
</select>
```

When passing into the select field the value of "Midlothian" it is still showing "Fife" as the selected value.

However it does seem that it possibly works with defaultValue being passed (http://jsfiddle.net/w12xwd3z/6/) however it does not work with both being passed: http://jsfiddle.net/h34yL9yu/

**Comment by gaearon** [comment] 2016-04-07 14:29
There is a typo in the fiddle. You are passing `selected="Midlothain"` but the value is `Midlothian`.
The fiddle works with the typo fixed: http://jsfiddle.net/j03c41pw/

Please let me know if I missed something! So far this appears to work as intended so closing.

**Closed by gaearon** 2016-04-07 14:29 UTC

**Comment by tanepiper** [comment] 2016-04-08 09:18
@gaearon Looks like #6440 references the same issue.  The JSFiddle *did* work because it's react 0.14 - but can confirm it's not working in 15

**Comment by gaearon** [comment] 2016-04-08 13:30
Let's discuss it there then? 🙂

It's a fun coincidence but I wouldn't say it's the same issue, as here the issue was the typo, and in the other issue, it is a genuine regression caused by a bugfix that was never released in RCs so it couldn't cause any issues before the final 15.
