### ISSUE TITLE
Component constructor called multiple times when using cloneElement

### ISSUE THREAD

**Issue by djs15** [facebook/react#13116] opened 2018-06-27 16:02 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The component constructor is being called multiple times when using React.cloneElement.

https://jsfiddle.net/Luktwrdm/652/

Clicking the button changes which components are rendered. When the WithConstructor element is displayed, it shows how many times the constructor has been called. Clicking the button repeatedly causes the constructor to be called every time that component is displayed.

However, if you change line 33 to be `const isEven = false` and click the button, the component's constructor will only be called once. 

**What is the expected behavior?**
The component constructor should only be called once when the component is created.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is happening in all browsers. React 16.4. Unsure if this worked in previous versions.

**Comment by aweary** [comment] 2018-06-27 18:31
This looks like expected behavior to me. When `isEven` is true you don't render the `WithConstructor` component anymore so it gets unmounted. When `isEven` is false again the `WithConstructor` component gets rendered again so it mounts. The constructor is called when a component mounts, so this behavior is expected.

You can see that [the constructor gets called even without `cloneElement`](https://jsfiddle.net/4jmxta9g/).

Keep in mind that a class component isn't instantiated when you call `React.cloneElement` or `React.createElement`. You can see that [if an element is never rendered, the constructor is never called](https://jsfiddle.net/bs2r8g1y/). That's because `<App />` is just sugar for `React.createElement(App)` which returns a _representation_ of the React component. It hasn't actually called the `App` function/class at all yet.

Once that element actually gets rendered by some other component React will create the class instance and call its lifecycle methods. If it's no longer rendered, that instance will eventually get GC'd. If the element gets rendered again (even if it's the same element!) React will start that whole process again. So that's why the constructor is called every time the `WithConstructor` element (`this._component`) is rendered.

Does that make sense?

I'll close this out since this is expected, but please feel free to ask any clarifying questions

**Closed by aweary** 2018-06-27 18:31 UTC

**Comment by djs15** [comment] 2018-06-27 18:57
@aweary Thanks for your response. That makes sense.

So then if `WithConstructor` has some value in `state` (like in this example https://jsfiddle.net/Luktwrdm/667/), cloneElement won't retain that value because the component is unmounted. 

However if `WithConstructor` is remains mounted (like in this example https://jsfiddle.net/Luktwrdm/668/), cloneElement will retain `state`.

Correct?

**Comment by djs15** [comment] 2018-06-29 19:05
I'm curious - why would that instance get garbage collected if we're keeping a reference to it (via the `this._component` private member)? Is it that the internal representation of the component is garbage collected even though we retain a reference to the outer/public representation?
