### ISSUE TITLE
Error: "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by drager** [facebook/react#22333] opened 2021-09-16 05:45 UTC
Describe what you were doing when the bug occurred:
1. Just trying to profile an React Native app

![Screenshot_2021-09-16_07-44-35](https://user-images.githubusercontent.com/1957563/133556382-73ddabab-f985-4fd2-9d60-1a1438d8bd8b.png)

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-3a8c04e3b2

Call stack: at Jc (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:342921)
    at ii (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:59391)
    at Kl (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:114564)
    at Ns (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101189)
    at Is (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101117)
    at Os (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:100980)
    at gs (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:96690)
    at w (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:1749)
    at MessagePort.A.port1.onmessage (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:2251)

Component stack: at Jc (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:341665)
    at div
    at div
    at fi (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:235808)
    at /nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:347533
    at Hi (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:249715)
    at /nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:251980
    at div
    at div
    at lu (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:305412)
    at En (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:173743)
    at jn (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:184811)
    at Ji (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:253490)
    at Nd (/nix/store/dhc43b6q83i2d842ry36ydnwck64wlyc-react-native-debugger-0.11.7/share/resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:353738)

**Comment by bvaughn** [comment] 2021-09-16 22:55
Hi!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by sowrovsarkar63** [comment] 2021-09-18 01:40
I'm recommending bvaughn  comment

**Comment by bvaughn** [comment] 2021-09-18 14:51
I literally commented above saying that this bug needs more information.

**Comment by bvaughn** [comment] 2021-11-15 15:51
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-11-15 15:51 UTC
Labels: Type: Bug, Resolution: Needs More Information, Component: Developer Tools
