### ISSUE TITLE
Regression: React 16 automatically marks first item of a mutliple select as checked

### ISSUE THREAD

**Issue by megawac** [facebook/react#12200] opened 2018-02-09 19:47 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug - Regression

**What is the current behavior?**

In react 16 when creating a `<select multiple>` the first child `<option>` is automatically getting marked as selected. In React 16 there does not seem to be a way to specify no `<option>` gets selected by default

https://codesandbox.io/s/moxm2on3z9

**What is the expected behavior?**

In React 15 unless you marked an option to be selected `<option selected>` no options were selected by default.

https://codesandbox.io/s/ll11z5wqzl

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Versions effected include `react^16.2`, this worked in `react^0.13` and `react^15`. This bug is reproducible in chrome 64 and Firefox 58.

-------------------------------

The hacky workaround I found to get around the first option getting selected is to inject a `<option style={{display: 'none'}} />` as the first child of the multiselect.

**Comment by gaearon** [comment] 2018-02-09 19:54
cc @aweary

**Comment by jquense** [comment] 2018-02-09 20:24
The change was made specifically for the single select since that's what the specced behavior is supposed to be. It seems like this behavior is only specified when the `size` is 1, which is a confusing complication because one can do `<select multiple size="1">`. The DOM is so fun folks.

ref: https://html.spec.whatwg.org/multipage/form-elements.html#concept-select-size

**Comment by jquense** [comment] 2018-02-09 20:31
jsfiddle showing non-react behavior: https://jsfiddle.net/wvr6f6x3/

- multiple: false -> selects first option
- multiple: false, size: 4 -> doesn't select first option

- multiple: true ->  doesn't select first option
- multiple: true, size: 1 -> doesn't select first option

Same in Chrome, Safari, and FF (random bonus there is like 7 year old bug in webkit where `size` has no affect) 

looks like the logic is, "only select the first option when it's not displayed like a listbox"

**Comment by aweary** [comment] 2018-02-09 21:02
The last time we touched this select logic was in https://github.com/facebook/react/pull/11057, which doesn't actually affect the behavior we're seeing here (`updateOptions` isn't called at all)

The reason we see this regression is because the _order_ of operations between when attributes are set and children are appended has changed. In React 15, attributes were set on an element before the children were appended. This means that the `multiple` was set on `select` before any option elements were appended.

In React 16, children are appended before attributes are set on the parent. So all the `option` elements are appended before `multiple` is set. 

This exposes some nuanced behavior around how option elements work: if you append a child to a `select` element that is not `multiple` it updates `select.selectedIndex` from -1 to 0. It _does not_ do that if you append a child to a multi-select.

So what happens in React 16 is that we append all the options to a select element that it assumes is a single select, and we see the spec defined behavior @jquense mentioned.

[Here's an example reproducing this issue without React](https://jsfiddle.net/dm6vkq9q/). You'll see that if you set `select.multiple` to `true` before appending the options, it works as expected.

**Comment by aweary** [comment] 2018-02-09 21:06
The solution will likely be either:

1) Ensure that attributes are set before children are appended. This would make React 16 consistent with 15. It would potentially resolve any other unknown issues that will arise due to this, but I think it will also require changes to the reconciler which may affect other renderers with different requirements

2) Have a special set of attributes that are set before children are appended

3) Go back after all the attributes and children are set and manually fix this

The first option is probably the best one if it doesn't cause any other problems.

**Comment by GarethSmall** [comment] 2018-02-17 14:52
@aweary Do you mind if I take this on as my first issue?

**Comment by jquense** [comment] 2018-02-17 14:54
@GarethSmall go for it 👍 let us know if you have any questions, it's not the most straightforward are of the code base :P

**Comment by GarethSmall** [comment] 2018-02-17 14:55
@jquense Thank you! I've got many, i'm looking through the tests now. If I have any afterwards, I'll be sure to ask.

**Comment by aweary** [comment] 2018-02-17 19:26
Continuing the discussion from https://github.com/facebook/react/pull/12240

I think it makes the most sense to ensure that _all_ attributes are set before children are appended. I'll try and comb through the spec for more append behavior that forks based on parent attributes, but my gut tells me `multiple` isn't unique. If it _is_ unique, or there are other attributes that depend on children being appended before the attribute is set, then maybe just manually fixing this in `ReactDOMSelectFiberSelect` is the best idea. 

The problem with just re-ordering the reconciler methods is that this might not make sense for other renderers like React Native. Maybe @acdlite or @bvaughn have some insights there?

Maybe we could put the `setInitialDOMProperties` call somewhere else in the lifecycle. I'm not sure.

**Comment by GarethSmall** [comment] 2018-02-17 19:34
From what it looks like we're doing two things in setInitialProperties, we're setting the initial properties and we're "handling" events. Is it fair to say these to processes should be separated?

**Comment by GarethSmall** [comment] 2018-02-17 21:42
Another thing to note is if we set the properties before we append the children we run into other issues. For example: We have a defaultValue property we set properties > append all children our defaultValue won't be set.

**Comment by gaearon** [comment] 2018-08-03 17:10
This was fixed in https://github.com/facebook/react/pull/13270, with an extra regression test in https://github.com/facebook/react/pull/12242.

**Closed by gaearon** 2018-08-03 17:10 UTC
Labels: Component: DOM, Type: Bug, Type: Regression, good first issue (taken)
