### ISSUE TITLE
Error: "Cannot read property 'isCollapsed' of undefined"

### ISSUE THREAD

**Issue by jellydn** [facebook/react#19927] opened 2020-09-30 02:34 UTC
Describe what you were doing when the bug occurred:
1. Open React Devtool
2. Select the Component tab
3. Got below error

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.2-fed4ae024

Call stack: at Store.getElementAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19359:35)
    at Store.getElementIDAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19376:26)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26594:18
    at List.render (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21229:18)
    at li (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11802:76)
    at ki (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11793:10)
    at ck (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:14433:86)
    at bk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13779:11)
    at ak (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13768:5)
    at Sj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13750:7)

Component stack: at List (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20924:30)
    at div
    at AutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:2786:5)
    at div
    at div
    at Tree_Tree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26368:45)
    at div
    at div
    at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26848:23)
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25520:23)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26139:23)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30926:50)
    at ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27172:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27303:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30463:23)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:22538:23)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:23040:27)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28328:23)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33797:21)

**Comment by eps1lon** [comment] 2020-09-30 07:11
Thanks for the report. Could you include the component tree that you were inspecting when the devtools crashed? A [codesandbox](https://react.new) would be perfect.

**Comment by jellydn** [comment] 2020-09-30 07:14
Thanks, I will try to reproduce that issue on my side again.

**Comment by HarshitJoshi9152** [comment] 2021-05-08 18:31
i take it you couldn't reproduce the issue so check this [react codebase](https://github.com/HarshitJoshi9152/showerthoughts)

Steps to reproduce.

1. install dependencies and run the code with `npm run start`
2. go to localhost:3000 and click on any post.
3. hit reload.
4. open dev tools and we have the same error.

**Comment by HarshitJoshi9152** [comment] 2021-05-08 18:33
![isCollapsedBug](https://user-images.githubusercontent.com/37842304/117549783-f1308980-b059-11eb-9d4b-7c72c6418b51.PNG)

**Comment by bvaughn** [comment] 2021-05-25 18:48
Thanks for the repro case, @HarshitJoshi9152 😄 

I just tested this with 4.13 (on NPM and in Chrome/Firefox/Edge) and I can no longer reproduce the bug with your test case, so I'm going to close this issue.

If you still see the issue, please open a new bug (with updated repro steps). Please make sure you're running the latest version of React DevTools before opening this bug. :)

**Closed by bvaughn** 2021-05-25 18:48 UTC
Labels: Component: Developer Tools, Type: Bug, Type: Needs Investigation
