### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by hophacker** [facebook/react#22972] opened 2021-12-15 22:22 UTC
Using `react-dom@^18.0.0-rc.0` inside a nextjs project(`next@12.0.7`), then opening a [antd](https://ant.design/) dropdown, will cause page to be deadly frozen. After downgraded react to `17.0.2`, the issue disappears.

My wild guess: this issue caused by some conflict btw dom manipulation and animation.

I'm happy to show detailed stuff if the React team needs. 

React version:
18.0.0-rc.0

**Comment by bvaughn** [comment] 2021-12-16 03:59
> I'm happy to show detailed stuff if the React team needs.

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by wuifdesign** [comment] 2021-12-16 13:15
i think this just happens because antd still depends on `findDOMNode` for some components.

**Comment by bvaughn** [comment] 2021-12-17 13:50
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-12-17 13:50 UTC
Labels: Type: Bug, Status: Unconfirmed, Resolution: Needs More Information
