### ISSUE TITLE
How to best define a propType for accepting a component as a prop?

### ISSUE THREAD

**Issue by jimbolla** [facebook/react#5143] opened 2015-10-12 16:14 UTC
Given this contrived example, what is the best definition of `componentType`?

    const componentType = PropTypes.oneOfType([
        PropTypes.shape({render: PropTypes.func.isRequired}), // React.createClass / React.Component ...better way to describe?
        PropTypes.func,                                       // Stateless function
        // others?
    ]);

    const Selector = React.createClass({

        propTypes: {
            components: PropTypes.arrayOf(componentType).isRequired,
            index:      PropTypes.number.isRequired,
        },

        render() {
            const Component = this.props.components[this.props.index];
            return (
                <Component />
            );
        }
    });

**Comment by yaycmyk** [comment] 2015-10-12 17:15
@jimbolla `React.PropTypes.node` I believe is the right one, it means anything renderable.

**Comment by jimfb** [comment] 2015-10-12 17:35
@yaycmyk Sounds right to me, thanks for answering!

@jimbolla This is a usage question rather than a bug in the React core.  We use github issues for tracking bugs in the React core.  Usage questions are better answered on StackOverflow.  Since this is not a bug in the React core, I'm going to close this issue.  Feel free to continue the discussion on this thread.

**Closed by jimfb** 2015-10-12 17:35 UTC

**Comment by jimbolla** [comment] 2015-10-12 17:37
@yaycmyk  That's not I'm looking for. `node` usage would look like this:

    <Selector components={[<ThingA  />, <ThingB  />]} />

whereas I want something that would look like:

    <Selector components={[ThingA, ThingB]} />

**Comment by zpao** [comment] 2015-10-12 17:41
`PropTypes.node` isn't correct but there isn't a great type for this as it could be one of a number of things. A simple function (for stateless functional components), a `class` which is also a function (which we're making required to extend React.Component), or a React Class which is also a function. Since *any* function can be passed here, that's the closest type you'll get. Further, since any function can be valid, we can't accurately check what the return value will be. This is where a static type checker will come in handy.

**Comment by jimbolla** [comment] 2015-10-12 17:43
@zpao Thanks. Would you just use `PropTypes.func` and call it a day? Are there any valid values that aren't `func`?

**Comment by zpao** [comment] 2015-10-12 17:46
`PropTypes.oneOfType([React.PropTypes.string, React.PropTypes.func])`

This also captures the native element case (eg `"div"`).

**Comment by jimbolla** [comment] 2015-10-12 17:47
Ok, thank you.

**Comment by vipcxj** [comment] 2018-04-27 10:02
@zpao This is wrong now. The new context api caused object also maybe a react component.

**Comment by nermand** [comment] 2018-06-27 14:35
`PropTypes.element` maybe?

**Comment by kachkaev** [comment] 2018-09-11 14:47
FYI:

```
PropTypes.oneOfType([React.PropTypes.string, React.PropTypes.func])
```

does not support components created with `React.forwardRef` – see https://github.com/facebook/prop-types/issues/200

**Comment by ZackKnopp** [comment] 2019-02-04 20:12
This is how react-router handles it:

```
Route.propTypes = {
    children: PropTypes.oneOfType([PropTypes.func, PropTypes.node]),
    component: (props, propName) => {
      if (props[propName] && !isValidElementType(props[propName])) {
        return new Error(
          `Invalid prop 'component' supplied to 'Route': the prop is not a valid React component`
        );
      }
    },
    exact: PropTypes.bool,
    location: PropTypes.object,
    path: PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.arrayOf(PropTypes.string)
    ]),
    render: PropTypes.func,
    sensitive: PropTypes.bool,
    strict: PropTypes.bool
  };
```

**Comment by Arghyadeb** [comment] 2019-02-05 12:39
@ZackKnopp That's what I also said.
I suggested using Array.some() because it was an array according to his use-case.

**Comment by Dalzhim** [comment] 2019-04-24 21:23
@ZackKnopp : Here's a modified version of the validation function that is more generic and that can be reused everywhere:
```
import React from "react";
import { isValidElementType } from "react-is";

function elementTypePropTypeChecker(props, propName, componentName)
{
  if (props[propName] && !isValidElementType(props[propName])) {
      return new Error(`Invalid prop '${propName}' supplied to '${componentName}': the prop is not a valid React component`);
    }
}

MyComponent.propTypes = {
  myChildProp: elementTypePropTypeChecker,
};
```

**Comment by tiborsaas-tw** [comment] 2019-07-09 13:02
You can now use `PropTypes.elementType` to validate for Component type props:

https://github.com/facebook/prop-types/pull/211

**Comment by AleksandrHovhannisyan** [comment] 2020-05-26 18:09
Could someone clarify how `PropTypes.element` differs from `PropTypes.elementType`?

**Comment by mamadOuologuem** [comment] 2020-07-21 23:05
@AleksandrHovhannisyan 
- `PropTypes.element` is for rendered components (eg. `<MyComponent />`)
- `PropTypes.elementType` is for not rendered component (eg. `MyComponent`)

```
const Component = ({ myButton: MyButton, myRenderedButton }) => {
  return (
    <>
      <MyButton />
      {myRenderedButton}
    </>
  );
};

Component.propTypes = {
  myButton: PropTypes.elementType,
  myRenderedButton: PropTypes.element,
};

============================================================================

const Button = () => {
  return <button>Hello</button>;
};

const App = () => {
  return <Component myButton={Button} myRenderedButton={<Button/>}/>
};
```

**Comment by jdnichollsc** [comment] 2021-03-02 17:00
What types of TypeScript do you use to support both?

**Comment by gondolio** [comment] 2021-05-25 11:18
> @jimbolla `React.PropTypes.node` I believe is the closest one, it means anything renderable.

I think this is incorrect as per the [docs](https://reactjs.org/docs/typechecking-with-proptypes.html) node is something else:
```
  // Anything that can be rendered: numbers, strings, elements or an array
  // (or fragment) containing these types.
  optionalNode: PropTypes.node,
```

It looks like the correct PropType for react components is `PropTypes.element`:
```
  // A React element.
  optionalElement: PropTypes.element,

  // A React element type (ie. MyComponent).
  optionalElementType: PropTypes.elementType,
```
