### ISSUE TITLE
[DevTools Bug]: Long keys overlap

### ISSUE THREAD

**Issue by MinimumViablePerson** [facebook/react#21695] opened 2021-06-16 20:57 UTC
### Website or app

https://05cdc.csb.app/

### Repro steps

![image](https://user-images.githubusercontent.com/16916098/122292219-a540f200-ceed-11eb-8799-211fcd4b7399.png)

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment] 2021-06-16 22:48
This doesn't repro for me:
<img width="298" alt="Screen Shot 2021-06-16 at 3 47 36 PM" src="https://user-images.githubusercontent.com/29597/122304525-5dad6c80-ced3-11eb-8fce-263b9252857b.png">

I think more information is needed. For instance, which operating system (and version) and browser (and version) are you using?

**Comment by bvaughn** [comment] 2021-06-18 17:48
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-06-18 17:48 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed, Type: Bug
