### ISSUE TITLE
License file is not included in the react and react-dom NPM packages

### ISSUE THREAD

**Issue by Pashokus** [facebook/react#5426] opened 2015-11-09 11:29 UTC
Please add these files with full license text to the NPM distribution packages. Unfortunately, from the legal standpoint, simply specifying the name of the license is not enough, because it's unclear where to get the EXACT (legally binding) text of that license. This is a major roadblock on our way to using the module, seriously.

Thanks a lot for the great code, and thanks in advance for fixing this blocker.

**Comment by jimfb** [comment] 2015-11-09 17:12
Duplicate of https://github.com/facebook/react/issues/4517

**Closed by jimfb** 2015-11-09 17:12 UTC
