### ISSUE TITLE
Error: "Cannot read property 'concat' of undefined"

### ISSUE THREAD

**Issue by neolite** [facebook/react#19137] opened 2020-06-15 14:34 UTC
Describe what you were doing when the bug occurred:
By this video link
https://share.getcloudapp.com/xQuDgBXA
---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.7.0-23309eb38

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:164715)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:163849)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:163773)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:166664)
    at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342328)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:62450)
    at tl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:71793)
    at zl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:113765)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104502)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104430)

Component stack: at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342099)
    at div
    at div
    at div
    at Co (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:263571)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:366677
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:276314)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:278724
    at div
    at div
    at Xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:325177)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:207026)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:216342)
    at Va (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:293773)
    at us (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:371869)

**Comment by bvaughn** [comment] 2020-06-16 14:43
Can you share your profiling data?

**Comment by neolite** [comment] 2020-06-16 15:48
Profiler data:
https://drive.google.com/file/d/125l8fvrGVxga9RHbw7mvPKgrZ0ZqtR0j/view?usp=sharing

Page using React-table with Semantic-ui Select and have a ~2000 items in options, when i clicked in select, options was showed after ~5 seconds.
I open React profiler for detect reason for this lag, and when i clicked to large column profiler was crashed.

**Comment by bvaughn** [comment] 2020-06-16 16:40
@neolite Are you able to reproduce the problem by profiling again? If so, can you share access to the site with me?

**Comment by bvaughn** [comment] 2020-06-16 16:47
@neolite To clarify, the profiling data you shared is likely corrupt in some way, but the *interesting* part is figuring out why or how it got corrupted in that way.

This issue is a duplicate of #18256 so I'm going to close it, but more info would be appreciated on how to repro this problem though! If you can share, please do!

**Closed by bvaughn** 2020-06-16 16:47 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
