### ISSUE TITLE
Bug: the <textarea> component's ValidityState.tooShort is incorrect when component is controlled and the value is passed in via the value prop

### ISSUE THREAD

**Issue by matwlev** [facebook/react#27878] opened 2024-01-04 22:30 UTC
React version: 18.2.0

## Steps To Reproduce

1. Create a controlled `<textarea>` component with the value passed to the *value* prop (not as children)
2. Pass a *minLength* prop with a value > 0

Link to code example: https://codesandbox.io/p/sandbox/react-textarea-bug-mjwyw5

## The current behavior
If the `<textarea>` component is part of a form, submission of the form occurs even if the length of the value in the `<textarea>` is less than the value passed in to the *minLength* prop and no invalid event is fired. Checking the `<textarea>` element's ValidityState shows that the element is valid and `ValidityState.tooShort` is `false`.

## The expected behavior
Submission of the form should be prevented and an invalid event should fire. The ValidityState of the element should show `ValidityState.tooShort` as `true`.

**Comment by rickhanlonii** [comment] 2024-01-05 21:38
Dupe of https://github.com/facebook/react/issues/19474

**Closed by rickhanlonii** 2024-01-05 21:38 UTC
Labels: Status: Unconfirmed

**Comment by matwlev** [comment] 2024-01-05 21:44
> Dupe of #19474

That's great! Thank you @rickhanlonii
