### ISSUE TITLE
[Complier bug] TypeError

### ISSUE THREAD

**Issue by mqklin** [facebook/react#31801] opened 2024-12-16 10:33 UTC
React compiler 
https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwFkBPAQU0wAoAlPmAAdNvjiswBMvgC8+KGATchAbnH4lKgMoQAtglwALJnQDm-LdvxCFAPknSIlBADpKEK2XcAjdzhBABp8AHow-AAVTkwEAFEYGBxkfABhMjo6CAIYBDJCfExkuLwmBDB8CBIlOmIScwRC-jyC8wt8AHI4TsEbQU06AF9xcVoGZlYdBH0jU3b+OD9hMQkpOhlnOqZJtkVlBDTWQh2WOg0bJhrF49PWFZttJYuJEeHRunHGM+mj7d37KttHlcLA2ORKCpBkMQEMgA

Compiler eslint was silent

**Comment by mofeiZ** [comment] 2024-12-16 20:39
Thanks for reporting, this looks to be a duplicate of #31551.

We believe that a type system (i.e. typescript / flow) should make this optimization safe for most users, but recognize that even such type checkers have many sources of unsoundness. We're already planning to remove this optimization from the default enabled set (see linked issue for context).

I'm curious -- did you ran into this case when testing the compiler on your own codebase? If so, we'd love to see a minimal repro with your product code logic.

**Closed** 2024-12-16 20:39 UTC
Labels: Status: Unconfirmed

**Comment by mqklin** [comment] 2024-12-17 09:02
Yes, I got it on my production project, so I disabled compiler till this is fixed. 
I've provided you an example, my code looks almost the same. The logic is: if user is logged in, condition is true, and callback is being called. But the bug I caught happened when user was not logged in, so I didn't expect the callback to be called.
