### ISSUE TITLE
Throws warning with key and refs when passing {...props}

### ISSUE THREAD

**Issue by KrisCoulson** [facebook/react#6450] opened 2016-04-08 02:15 UTC
[facebook/react/pull/5744](https://github.com/facebook/react/pull/5744)

It seems with the newest update v15 when passing props into a child component with the spread operator the console throws the warnings associated with this pull request.

seems to only throw issue when the component is not a class but only stateless component hence passing just {...props} and not {...this.props}

![image](https://cloud.githubusercontent.com/assets/6943688/14372403/141329b2-fcf5-11e5-9ef8-7cc2ae19a571.png)

I am not accessing refs or keys in the child component

**Comment by CaptainN** [comment] 2016-04-13 20:04
I have a similar issue when cloning children to add props:

```Javascript
{React.Children.map (props.children, (child) => {
  return React.cloneElement (child, props)
})}

**Comment by jimfb** [comment] 2016-04-15 22:08
This is almost a duplicate of https://github.com/facebook/react/pull/6268, the relevant discussion is there.

**Comment by dlong500** [comment] 2016-05-11 03:38
I'm also running into this when using `cloneElement`.  The code accessing refs and keys is definitely in that function (not in my code).  I've read through #6268 but can't tell if that PR specifically solves this particular issue with `cloneElement`.

**Comment by xile611** [comment] 2016-05-25 07:10
Same problem when using `cloneElement`.

**Comment by gaearon** [comment] 2017-10-03 23:40
I believe this was fixed in https://github.com/facebook/react/pull/6880.

**Closed by gaearon** 2017-10-03 23:40 UTC
Labels: Type: Regression
