### ISSUE TITLE
HTML tags missing content when wrapped with comments v15rc1

### ISSUE THREAD

**Issue by imdpk** [facebook/react#6299] opened 2016-03-19 17:18 UTC
I have notices that since there are no longer spans everything element wrapper by comments content fails to display for IE and Edge.

**Comment by cody** [comment] 2016-03-19 17:24
The Release Candidate 2 is out and your bug is probably already fixed there. Here is the blog post about it: https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html

**Comment by gaearon** [comment] 2016-03-19 23:00
I’m closing as this most likely is a duplicate of #6246 which has been fixed in RC2.
If you still experience the problem in RC2 please let us know and I will reopen.
Thank you for reporting!

**Closed by gaearon** 2016-03-19 23:00 UTC
