### ISSUE TITLE
[FR] Support style as string, set via cssText

### ISSUE THREAD

**Issue by probablyup** [facebook/react#10118] opened 2017-07-07 00:13 UTC
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The style prop must always be an object.

**What is the expected behavior?**
The style prop could optionally accept a CSS string which would be set under the hood via `element.style.cssText = styleStr`

**Comment by Sergeytroinin** [comment] 2017-07-09 21:03
If somebody else is interested in such feature, I could take it.

**Comment by aweary** [comment] 2017-07-10 17:06
This is a duplicate of https://github.com/facebook/react/issues/5397, please provide any input there 😄

**Closed by aweary** 2017-07-10 17:06 UTC

**Comment by Ta4i** [comment] 2017-07-27 12:27
@Sergeytroinin @aweary I duplicate my concerns here (I wrote in #5397 originally).

I need to be able to set inline styles as `cssText`. In my case, I should calculate `linear-gradient` using state like:

```
render() {
  const gradient = `
     background: -moz-linear-gradient(${this.state.gradient});
     background: -webkit-linear-gradient(${this.state.gradient});
     background: linear-gradient(${this.state.gradient});
  `

  return <div style={gradient}></div>
}
```

As you see, the problem is applicable to all vendor-specific values, not just for `linear-gradient`.

At least, are there any workaround you can suggest?
