### ISSUE TITLE
Error: "Cannot read property 'duration' of undefined"

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#18786] opened 2020-04-30 00:58 UTC
Describe what you were doing when the bug occurred:

Profiled the new FB. Scrolled down to tail loads.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-a2fb84beb

Call stack: at chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:345591
    at Array.map (<anonymous>)
    at chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:345397
    at Ai (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32:62580)
    at zl (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32:112694)
    at jc (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32:104789)
    at Oc (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32:104717)
    at Tc (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32:104585)
    at gc (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32:101042)
    at chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32:47376

Component stack: at chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:344679
    at div
    at div
    at n (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:194307)
    at div
    at Cc (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:346311)
    at div
    at n (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:3:8163)
    at div
    at bc
    at div
    at div
    at div
    at Do (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:262081)
    at chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:364048
    at n (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:274563)
    at chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:277138
    at div
    at div
    at ol (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:323458)
    at Ze (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:205764)
    at pn (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:215038)
    at $a (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:292153)
    at ws (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:40:369231)

**Comment by bvaughn** [comment] 2020-05-01 22:09
Possible duplicate of #18798.

**Comment by Amine-H** [comment] 2020-05-03 01:28
I can work on this issue.

**Comment by bvaughn** [comment] 2020-05-19 21:14
Fixed via #18862

**Closed by bvaughn** 2020-05-19 21:14 UTC
Labels: Component: Developer Tools, Type: Bug
