### ISSUE TITLE
Bug: in strict mode, states are rerendered out of order

### ISSUE THREAD

**Issue by aquark** [facebook/react#25023] opened 2022-08-01 13:36 UTC
Using a combination of useRef and useState I am able to create a scenario where a state value is updated, then a subsequent rerender caused by strict mode uses the old value of the state.

React version: 17 and 18

## Steps To Reproduce

Using the following script, click "show", then "hide", then "show" again. The *second* time you click "show", the value `ready` changes from `true` to `false` (expected) and then immediately to `true` again (unexpected).

Code example:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World</title>
    <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>

    <!-- Don't use this in production: -->
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/babel">

const useHasChanged = (state) => {
  const previousStateRef = React.useRef(state);
  if (
    previousStateRef.current.every((value, index) => value === state[index])
  ) {
    return false;
  }
  previousStateRef.current = state;
  return true;
};

const Thing = ({ visible, setVisible }) => {
  const [ready, setReady] = React.useState(false);
  if (useHasChanged([visible]) && visible) {
    console.info("setReady(false)");
    setReady(false);
    setTimeout(() => {
        console.info("setReady(true)");
        setReady(true)
    }, 1000)
  }
  console.info("Thing", { ready, visible });
  return <div>{ visible && (<><p>visible: {`${visible}`}, ready: {`${ready}`}</p><p><a
  onClick={() => {
      console.info("hide");
      setVisible(false)
  }}>hide</a></p></>) }</div>
}

const App = () => {
  const [visible, setVisible] = React.useState(false);
  return <React.StrictMode>
  <div><Thing visible={visible} setVisible={setVisible} /><p><a
  onClick={() => {
  console.info("show");
    setVisible(true)
    }}>show</a></p></div></React.StrictMode>
}

const container = document.getElementById('root')
const root = ReactDOM.createRoot(container);
root.render(<App />)

    </script>
  </body>
</html>
```

## The current behavior

```
Thing {ready: false, visible: false}
Thing {ready: false, visible: false}
show
Thing {ready: false, visible: true}
setReady(false)
Thing {ready: false, visible: true}
Thing {ready: false, visible: true}
setReady(true)
Thing {ready: true, visible: true}
Thing {ready: true, visible: true}
hide
Thing {ready: true, visible: false}
Thing {ready: true, visible: false}
show
Thing {ready: true, visible: true}
setReady(false)
Thing {ready: false, visible: true}
Thing {ready: true, visible: true}     <-- HERE is the stale state being replayed
setReady(true)
Thing {ready: true, visible: true}
Thing {ready: true, visible: true}
```

## The expected behavior

```
Thing {ready: false, visible: false}
Thing {ready: false, visible: false}
show
Thing {ready: false, visible: true}
setReady(false)
Thing {ready: false, visible: true}
Thing {ready: false, visible: true}
setReady(true)
Thing {ready: true, visible: true}
Thing {ready: true, visible: true}
hide
Thing {ready: true, visible: false}
Thing {ready: true, visible: false}
show
Thing {ready: true, visible: true}
setReady(false)
Thing {ready: false, visible: true}
Thing {ready: false, visible: true}
setReady(true)
Thing {ready: true, visible: true}
Thing {ready: true, visible: true}
```

## Notes

Interestingly, if I change the `useHasChanged` implementation to `useState` instead of `useRef`, the problem isn't visible:

```
export const useHasChanged = (state) => {
  const [previousState, setPreviousState] = useState(state);
  if (previousState.every((value, index) => value === state[index])) {
    return false;
  }
  setPreviousState(state);
  return true;
};
```

It looks like the reason is that when the `ready true` state is replayed, the `previousState [false]` state is *also* replayed, causing it to `setReady(false)` a second time, which "corrects" the stale replayed state.

**Comment by r-augustine** [comment] 2022-08-01 15:05
Hey, there may be some issues with your implementation:

1. console.log should not be called directly in the function body, this be inconsistent with the lifecycle of the component and produces out of order logs. Use [React.useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect) to sync console.log with the component lifecycle

`
React.useEffect(() => {
console.info("Thing", {ready, visible});
})
`

2. [useRef](https://reactjs.org/docs/hooks-reference.html#useref) will give you the same ref object on ever render and doesn't notify you when its content changes. Hence the stale state, useState re-renders the component on every state change.

**Comment by eps1lon** [comment] 2022-08-01 15:23
Reading or writing a ref during render is generally discouraged. Writing basically constitutes a side-effect which is not allowed during render.

If you can convert this to a [codesandbox](https://react.new/) I can help you more concretely. But you most likely need to move writing to the ref into a `useEffect`.

**Comment by aquark** [comment] 2022-08-01 16:31
@r-augustine 1) yes, I'm aware that logging should generally be done from an effect, but these log statements are there to show the values *during render* for debugging purposes. 2) yes, I'm aware that `useRef` doesn't trigger a render when it changes. In this case, triggering a render when the state changes would be inefficient because the use case of `useHasChanged` is to detect when *some other* state has changed between renders.

@eps1lon https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes -- useEffect is specifically not recommended for this use case (adjusting state based on other state) due to the fact that it triggers an additional DOM synchronization. Note that this example uses `useState` but that's inefficient because it triggers an unnecessary extra render just to record the previous state.

I'll try and convert to codesandbox. I had expected a standalone HTML file without dependencies on any external service would make it easier to repro and debug.

**Comment by aquark** [comment] 2022-08-01 16:42
Here's a code sandbox which reproduces the issue: https://codesandbox.io/s/divine-water-ksu00r

**Comment by aquark** [comment] 2022-08-01 16:53
I think what's surprising about this example is that the docs seem to say that strict mode's rerendering is the same as unmounting and remounting the component. But I don't believe that unmounting and remounting the component would cause it to render with a stale state; I would expect the second time it renders to use the state set by the first render.

**Comment by eps1lon** [comment] 2022-08-01 17:57
> useEffect is specifically not recommended for this use case (adjusting state based on other state) due to the fact that it triggers an additional DOM synchronization.

I wasn't saying you should use useEffect + another setState. Just that the setting of the ref should be done in an effect i.e. useEffect instead of during render.

Same applies to calling `setTimeout` which is another side-effect and all of these should not be called during render.

This all looks like you should be able to achieve the same behavior with just useEffect or setting state in an event handler. Without knowing the concrete use case the following example does not cause infinite renders: 

```jsx
...
const useHasChanged = (state) => {
  const previousStateRef = useRef(state);
  useEffect(() => {
    previousStateRef.current = state;
  });

  return previousStateRef.current.some(
    (value, index) => value !== state[index]
  );
};

const Thing = ({ visible, setVisible }) => {
  const [ready, setReady] = useState(false);
  const hasChanged = useHasChanged([visible]);
  if (hasChanged && visible && ready) {
    setReady(false);
  }
  useEffect(() => {
    if (hasChanged && visible) {
      const timeoutID = setTimeout(() => {
        console.info("setReady(true)");
        setReady(true);
      }, 1000);

      return () => {
        clearTimeout(timeoutID);
      };
    }
  }, [hasChanged, visible]);
...
```

-- https://codesandbox.io/s/pedantic-tamas-bodbqe

**Comment by GreLI** [comment] 2022-12-15 13:30
Yep, we ran into few issues recently using v. 18.2.0 (and Next.js 12.3.3) when extra re-render appeared with wrong (outdated) state out of nowhere. In reproduces only in development mode, but in production mode everything works as expected.

In the latest issue I've explored, it was just extra render caused by flush something in fibers. The component caused an issue has an updating re-render when props change and an effect (not related directly, but triggered by the state update).

**Comment by Stan-Stani** [comment] 2023-01-22 22:30
I'm also dealing with a similar problem but I'm wondering if the states being rerendered out of order is an intended result of strict mode.

**Comment by catamphetamine** [comment] 2023-03-23 01:38
I've also encountered this bug: when running in "strict" mode in development, the component re-renders with an out-of-place stale state.

Observed:

* The initial state value is "A"
* Functional component render function is run
* `useLayoutEffect()` is called
  * Inside that effect, the state variable is set to "B"
* `useLayoutEffect()` is immediately unmounted (by design of "strict" mode)
* `useLayoutEffect()` is called again
  * Inside that effect, the state variable is set to "C"
* The component re-renders with state value being equal to "B"
* The program crashes because it was expecting "C"

Expected: 

The component should've re-rendered with the latest state value — "C"

Possible hacky workarounds:

* I could modify the state update function to write the latest argument value to a "ref" and then compare it to that "ref" on a subsequent re-render.

```js
// This approach filters out any weird intermediate inconsistent/invalid/stale state values.
// https://github.com/facebook/react/issues/25023
function Component() {
  const latestWrittenState = useRef(initialState)
  const latestValidState = useRef(initialState)
  const [_state, _setState] = useState(initialState)
  
  let state
  if (_state === latestWrittenState.current) {
    state = _state
    latestValidState.current = _state
  } else {
    state = latestValidState.current
  }
  
  const setState = useCallback((newState) => {
    latestWrittenState.current = newState
    _setState(newState)
  }, [])
}
```

**Comment by gaearon** [comment] 2023-03-23 15:36
>Here's a code sandbox which reproduces the issue: https://codesandbox.io/s/divine-water-ksu00r

This sandbox reads and writes refs in render, so I can't reason about its behavior.

**Comment by GreLI** [comment] 2023-03-31 15:07
Seems like changing `useRef` to `useState` with saved prev state really fixes the issue.

E.g. instead of
```jsx
const [state, setState] = useState(deriveFrom(prop));
const prevProp = useRef(prop);
if (prop !== prevProp.current) {
    prevProp.current = prop;
    /* do stuff like setState(deriveFrom(prop)) */
}
```
write
```jsx
const [state, setState] = useState(deriveFrom(prop));
const [prevProp, setPrevProp] = useState(prop);
if (prop !== prevProp) {
    setPrevProp(prop);
    /* do stuff like setState(deriveFrom(prop)) */
}
```
component state starting to render properly.

**Comment by gaearon** [comment] 2023-03-31 15:39
It's hard to say what the original example is trying to do because it uses `setTimeout` during render to later set `ready` to `true`. But `setTimeout` during render is not really supported in that way. So I don't know what the intent of the original code is.

Resetting a state variable after a prop update is generally not recommended because it leads to complicated code and two-pass renders. It's *especially* not recommended to stuff this kind of logic into a reusable Hook like `useHasChanged` because it "hides" the fact that this Hook causes the component to do two-pass rendering. This makes it too easy to create perf problems.

With that caveat, the canonical way to do this is indeed by calling `setState` *during* render as in https://github.com/facebook/react/issues/25023#issuecomment-1492082541. See https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes for details.

I think we can close this, because the only "buggy" sandboxes write and read refs during render — which explicitly is not supported.

**Closed by gaearon** 2023-03-31 15:39 UTC
Labels: Status: Unconfirmed, Resolution: Needs More Information

**Comment by GreLI** [comment] 2023-03-31 15:47
In my case it's an animation hook which depends on prop (basically, user pressed a button) and current state. Show, hide and two transitional states. Similar to useTransition but simple. The states are needed since element must be rendered in every state except one hide state.

**Comment by GreLI** [comment] 2023-03-31 15:49
Still, I'd say, there is a bug with the way how Refs work that breaks its mental modal.

**Comment by aquark** [comment] 2023-04-02 22:24
The original example uses setTimeout to simulate an asynchronous event like the user clicking a button. To be clear, the example is not real application code, it's just a way to reproduce the behavior.

Naturally all the examples use side effects during rendering like setting refs because this is an easy way to "observe" the out of order states. Of course a pure component won't be affected if states are rendered out of order. Nevertheless, in practice people do write impure components and this is a case where the behavior when doing so is counterintuitive.
