### ISSUE TITLE
Error: "Could not find node with id "1145" in commit tree" on React Profiler

### ISSUE THREAD

**Issue by fidellr** [facebook/react#17769] opened 2020-01-03 18:16 UTC
Describe what you were doing when the bug occurred:
1. Open ranked tab
2. Changing "Render at" repeatedly
3. Error appeared

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.3.0-3e0967783

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159833
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159779)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:160302)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:322998)
    at ii (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59363)
    at qi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:67999)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:108660)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99973)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99898)

Component stack: in Sl
    in div
    in div
    in div
    in vo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Qi
    in Ve
    in nn
    in Da
    in Yc

**Comment by bvaughn** [comment] 2020-01-03 21:38
Duplicate of #16446

This was hopefully fixed in v4.4 which was released earlier today but not yet live in the Chrome store. (Pending review at the moment.)

**Closed by bvaughn** 2020-01-03 21:38 UTC
