### ISSUE TITLE
SVG xmlns attribute

### ISSUE THREAD

**Issue by salzhrani** [facebook/react#7176] opened 2016-07-02 22:15 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
The following error is raised
"Warning: Unknown prop `xmlns` on `svg` tag
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
create an a component with and svg tag and set the xmlns attribute
**What is the expected behavior?**
No warning
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.2.0

**Comment by brianreavis** [comment] 2016-07-02 22:22
This is a duplicate of https://github.com/facebook/react/pull/6471

**Comment by salzhrani** [comment] 2016-07-02 22:28
They are symptoms of the same problem ... but #6471 is not about this warning

**Comment by gaearon** [comment] 2016-07-02 23:16
This is not a bug per se. You see the warning because this attribute is currently unsupported.
I think this should be solved by #6532 (seems closer to what @zpao wanted than #6471).

**Comment by salzhrani** [comment] 2016-07-03 14:58
any would do ...

**Comment by zpao** [comment] 2016-07-13 20:29
Merged #6471 so closing this out.

**Closed by zpao** 2016-07-13 20:29 UTC
