### ISSUE TITLE
Click events aren't fired for mobile devices on table rows

### ISSUE THREAD

**Issue by seanadkinson** [facebook/react#2931] opened 2015-01-25 01:58 UTC
Could be missing something here, but if I have a `onClick` handler for a table row, mobile devices won't fire the event unless I add an `onTouchStart` handler, event if it's an empty function.

Fiddle here: http://jsfiddle.net/sadkinson/145k6bqc/4/

If you comment out the `doNothing` function in the fiddle, mobile devices won't actually fire the `onClick` handler when tapping the row.  Tried with Safari/Chrome on IOS 8, iPhone 6.

**Comment by syranide** [comment] 2015-01-25 13:27
#1169 #1418

Just add `cursor: pointer` and iOS will emit click events as expected.

**Comment by brigand** [comment] 2015-01-25 22:45
I wouldn't be opposed to something like [onclick=""](https://github.com/facebook/react/issues/1169#issuecomment-40651887) which has the aditional benefit of letting my style all clickable elements, and making the generated html clearer.  

In angular projects use this css: `[ng-click] { cursor: pointer }`.  Three birds with one stone (unless there are some serious perf problems with adding an empty onclick attribute).

**Comment by syranide** [comment] 2015-01-25 22:46
It's supposed to be fixed by MobileSafariClickEventPlugin, but it broke some time ago and haven't been fixed yet IIRC. `cursor: pointer` is the workaround for now I think.

**Comment by percyhanna** [comment] 2015-02-03 23:49
We recently ran into this problem as well, and found that the `cursor: pointer` workaround worked.

*NB:* The `cursor` must be defined as a non-`:hover` pseudo-class selector. I've personally never cared for defining the `cursor` on `:hover`, but that pattern is likely common enough that it might cause some problems. Since the `cursor` isn't actually set to pointer in the element's *normal* state, then iOS doesn't detect that it's clickable.

**Comment by spicyj** [comment] 2015-02-27 00:05
Dupe of #1169, essentially. Should be fixed in 0.14 by my PR.

**Closed by spicyj** 2015-02-27 00:05 UTC
