### ISSUE TITLE
[BUG] Ref doesn't show up.

### ISSUE THREAD

**Issue by trusktr** [facebook/react#5033] opened 2015-10-01 20:56 UTC
I'm setting a `ref` on an element, but it doesn't show up. This is what I'm doing in a class:

```js
    constructor(props) {
        super(props)

        this.bigGpsButtonElement = class extends Node {
            render() {
                return (
                    <Button _famousParent={this} ref="bigGpsButton"> </Button>
                )
            }
        }
    }

    render() {
        return (
            <Node _famousParent={this}>
                <this.bigGpsButtonElement ref="bigGpsButtonElement" />
            </Node>
        )
    }

    componentDidMount() {
        console.log('ref?', this.refs.bigGpsButtonElement) // Error
    }
```

When the `console.log` statement fires, I get the error

```
Uncaught TypeError: Cannot read property 'refs' of undefined
```

Why is that?

**Comment by jimfb** [comment] 2015-10-01 21:02
I think this is related to https://github.com/facebook/react/issues/5031#issuecomment-144838785

Your owner is the bigGpsButtonElement component, and then you are expecting the ref to appear on that component's parent.  The ref is attached to the owner, as Ben mentioned in the other issue you opened.

Closing out as not a bug in React.  Please ask usage questions like this on StackOverflow.  Github issues are reserved for tracking bugs in the React core.

**Closed by jimfb** 2015-10-01 21:02 UTC

**Comment by trusktr** [comment] 2015-10-01 21:04
Aha! In a class that extends the above class, I'm doing

```js
    render() {
        return (
            <Node _famousParent={this}>
                ...
                {this.bigGpsButtonElement}
                ...
            </Node>
        )
    }
```

In order to fix it, I changed the extending class to also do

```js
    render() {
        return (
            <Node _famousParent={this}>
                ...
                <this.bigGpsButtonElement ref="bigGpsButtonElement" />
                ...
            </Node>
        )
    }
```

**Comment by trusktr** [comment] 2015-10-01 21:05
@jimfb
