### ISSUE TITLE
Strange behavior of conditional rendering when bypassing props in functional component

### ISSUE THREAD

**Issue by ru-web-designer** [facebook/react#12255] opened 2018-02-20 18:15 UTC
This is a bug I've got today. I have a parent component, that includes a nested child component with a prop passed into it. Prop named the same way as a variable, from which I get the value (idk if this is important). Prop is used later to conditional render some JSX block. In the first cycle, component gets this prop in a correct way: null passed and JSX block didn't render. In the next cycle, when prop gets a value insted of null, it also works. But when finally prop got a null agian, like in the beginning, condition doesn't work proper, block still appears.

Code trivia:

```jsx
//doesn't work proper
const Parent = ({someProp}) => {

	//some code here...

	return (
		<Child someProp={someProp}/>
	);
};

const Child = ({someProp}) => (
	{someProp ? (<SomeJsx/>) : (null)}
);

//works great
const Parent = ({someBigProps}) => {
	var someProp = someBigProps.someProp;

	//some code here...

	{someProp ? (<SomeJsx/>) : (null)}
};
```

Real code shots:

![image](https://user-images.githubusercontent.com/3310192/36441246-1a638dd0-1683-11e8-82dc-27a9e1df320a.png)

![image](https://user-images.githubusercontent.com/3310192/36441259-1f0f206a-1683-11e8-9f3c-35ef33e8af74.png)

![image](https://user-images.githubusercontent.com/3310192/36441261-24261af4-1683-11e8-8111-05120e08a6a3.png)

**Comment by mrgurdeep** [comment] 2018-02-21 07:01
Can you try changing your code as below. Can you also try to reproduce the issue is jsfiddle.

Try debugging code it will also help.

```
const Child = ({someProp}) => {
	if (!someProp) { 
		return null;
	} 
	return <SomeJsx/>;
};
```

**Comment by ru-web-designer** [comment] 2018-02-21 10:31
> Try debugging code it will also help.

When I put a breakpoint into a ternary, it's just don't run that code branch at all, when it in child component. Looks like it's don't even touch a lifecycle event.

**Comment by ru-web-designer** [comment] 2018-02-21 10:57
> Can you try changing your code as below.

This actually helps!

Basically, what i've done:

```jsx
//was
const Parent = ({someProp}) => {

	//some code here...

	return (
		<Child someProp={someProp}/>
	);
};

const Child = ({someProp}) => (
     <Fragment>
          {someProp ? (<SomeJsx/>) : (null)}
     </Fragment>
);

//now
const Parent = ({someProp}) => {

	//some code here...

	return (
		<Child someProp={someProp}/>
	);
};

const Child = ({someProp}) => {
     var children = [];
     
     if (someProp) {
          children.push((<SomeJsx/>));
     }
     
     return (
          <Fragment>
               {children}
          </Fragment>
     );
};
```

Initially `Fragment` was  there for contain multiple elements, so i make an array of them for better situation coverage.

But now it's a questuon, why the first one code isn't working and don't even hit a brakepoint inside of child component.

**Comment by ru-web-designer** [comment] 2018-02-21 11:00
Maybe something is wrong in putting ternary condition inside a `Fragment`?

![image](https://user-images.githubusercontent.com/3310192/36476674-99b6340c-170f-11e8-9b2e-51e5f68e8b42.png)

**Comment by gaearon** [comment] 2018-02-21 13:14
Can you please provide a full example we can run to reproduce the problem?

**Comment by aweary** [comment] 2018-03-27 23:00
Since there's been no follow up or reproducible example, I'm going to go ahead and close this out.

**Closed by aweary** 2018-03-27 23:00 UTC
Labels: Resolution: Needs More Information
