### ISSUE TITLE
React renders differently on server and client.

### ISSUE THREAD

**Issue by vlinder** [facebook/react#4616] opened 2015-08-12 14:15 UTC
I have read #3152 and #3879 but this seemed like maybe another but related problem.

When the browser tries to bootstrap React and rerender the page I get this warning.

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. 
This generally means that you are using server rendering and the markup generated on 
the server was not what the client was expecting. React injected new markup to compensate 
which works but you have lost many of the benefits of server rendering. Instead, figure 
out why the markup being generated is different on the client or server:
 (client) e6zyboqo.1.2.1.0.1">&quot;This is a
 (server) e6zyboqo.1.2.1.0.1">"This is a test
```

Apart from the case that it is unnecessary to escape the quote it seems to render differently on the server  and browser. This is just static content so I don't really understand why?

The markup to render the element is like this.

```
<p><strong>Next:</strong>"This is a test"</p>
```

How come it's rendered different?

**Comment by zpao** [comment] 2015-08-12 19:14
This is likely a red herring, the warning here didn't do the best job of detecting differnces like this, but we've improved it on master. Can you try with the latest betas and see if it still repros?

**Comment by zpao** [comment] 2015-08-12 19:15
Or rather, it would still report that something is different, but it should point you at the actual difference and not a random encoded entity (see other discussion in #4608)

**Comment by mridgway** [comment] 2015-08-14 00:40
Posted this in my issue as well:

It turns out that Chrome now has `Object.assign` support and the `object-assign` package will fall back to using the native method. The key ordering is different when using `Object.assign` vs. `object-assign`'s polyfill.

**Comment by spicyj** [comment] 2015-08-14 20:49
That's weird, I would expect both to use the enumeration order.

**Comment by mridgway** [comment] 2015-08-14 21:19
I have traced it down to `React.__spread` when used as `<Foo ...props>` messing with the enumeration order of `props`.

**Comment by spicyj** [comment] 2015-08-14 21:22
Yeah, that should just use this for/in loop: https://github.com/facebook/react/blob/master/src/shared/stubs/Object.assign.js#L37.

**Comment by mridgway** [comment] 2015-08-14 21:23
If I switch out the `<Foo ...props>` with `React.createElement(Foo, props)` or `React.createElement(Foo, objectAssign({}, props))` (from `object-assign` package) it works fine.

**Comment by mridgway** [comment] 2015-08-18 18:16
Appears to be a [bug in v8](https://code.google.com/p/v8/issues/detail?id=3056&can=1&q=getOwnPropertyNames&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Area%20Stars) with `getOwnPropertyNames` which is used by `object-assign`. They have marked the issue as WorkingAsIntended unfortunately. I also created an [issue](https://github.com/sindresorhus/object-assign/issues/22) against `object-assign` since this issue arose when they switched from using `Object.keys` to `Object.getOwnPropertyNames`.

**Comment by spicyj** [comment] 2015-08-18 18:30
Good sleuthing.

**Comment by Spy-Seth** [comment] 2015-11-25 15:10
I'm facing to this issue. Any news on it? 

My server generate: `foo&#x27;bar` and my client `foo'bar`.

**Comment by zpao** [comment] 2015-11-25 18:47
@Spy-Seth your issue is unrelated. Make sure you have charset as utf-8 and if that doesn't resolve it please work it out elsewhere or file an issue if you can pinpoint a bug in React

**Comment by Spy-Seth** [comment] 2015-11-26 08:16
My page is already interpreted in utf8 `<meta charSet="utf-8" />`. And do not really see a difference between this issue and mine.

**Comment by shouze** [comment] 2015-11-27 21:36
@zpao could this be caused on server side by server not having locales generated for `utf-8`, only POSIX ones?

**Comment by zpao** [comment] 2015-11-28 19:25
@Spy-Seth if you read the rest of the issue, I said the entity piece was probably a red herring and then the original reporter never responded. The rest of the discussion is about ordering of attributes (with some other discussion in #4608). If your issue is actually about encoding, then please file a new issue with a complete example to reproduce. It's otherwise impossible to help.

**Comment by zpao** [comment] 2015-11-28 19:27
@spicyj @mridgway what was the outcome here - did we need to make a change to `React.__spread`?

**Comment by mridgway** [comment] 2015-11-28 19:42
Our issue turned out to be an issue with the `object-assign` package switching to using `getOwnPropertyNames` which returns keys in the wrong order when the object's key become too large. See https://code.google.com/p/v8/issues/detail?id=3056. In version 4.x of `object-assign` they moved away from using `getOwnPropertyNames`.

`Object.assign` in Chrome also has the same issue, so if you're using a polyfill on the server and Chrome's native `Object.assign` on the client, then you will hit the checksum issue. Some polyfills are now checking the enumeration order and overriding the native version if it fails. See [object.assign](https://github.com/ljharb/object.assign/blob/master/polyfill.js#L5) and [core-js](https://github.com/zloirock/core-js/blob/v1.2.6/modules/%24.object-assign.js#L6)(used by babel's polyfill).

**Comment by ktslwy** [comment] 2016-01-21 18:21
Is this issue about mismtach caused by character encoding (@vlinder) or attribute ordering changed by object.assign (@mridgway)?

I am seeing a similar issue as @mridgway that in some cases the props key ordering is changed by object.assign and then by using the spread operator to specify them causes the server the client to render the attributes in different order.

Since the spec doesn't specify the ordering the keys in an object, it seems pretty fragile that we take the attribute ordering into account when determining if there is a mismatch. The other way is to have the spread operator returns a consistent ordering, but not sure how you can do that except doing a sort on the keys, which is pretty costly.

**Comment by vlinder** [comment] 2016-01-22 08:14
@ktslwy For me it was always character encoding. As my original message pointed out. Did not have any time to create a minimal test case though. And I haven't been seeing this error in a while. So prabably a newer version has corrected the problem.

**Comment by Download** [comment] 2016-04-18 19:34
@mridgway 
> Our issue turned out to be an issue with the object-assign package switching to using `getOwnPropertyNames` which returns keys in the wrong order when the object's key become too large.

Ah!! That sounds like a really good reason for me seeing this warning:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) ut" id="textfield-" value="" type="text"
>  (server) ut" id="textfield-" type="text" value=""

I have an isomorphic app so I can't see a reason key ordering should be different.... except for what you are saying here. Thanks!

**Comment by eliseumds** [comment] 2016-05-11 15:48
@Download same thing here with React 15.0.2.. This is the diff: https://www.diffchecker.com/zvlfqz5n.

**Comment by spicyj** [comment] 2016-05-11 16:45
Can anyone seeing wrong attribute orders re-install and make sure you have object-assign@4.1.0? That should fix the issue.

**Comment by eliseumds** [comment] 2016-05-11 19:58
@spicyj that works for me. Thanks.

**Comment by Download** [comment] 2016-05-17 09:23
Thanks @spicyj I uninstalled React 15.0.1 and I installed React 15.0.2 and this seems to have fixed it.

**Comment by gaearon** [comment] 2017-10-03 22:10
I'll close since the fix has been out for a while, and we also don't care about the prop order in 16.

**Closed** 2017-10-03 22:09 UTC
