### ISSUE TITLE
Bug: React Devtools not coming up.

### ISSUE THREAD

**Issue by Lazy-poet** [facebook/react#20866] opened 2021-02-23 15:30 UTC
React version:
react: "17.0.1";
react-scripts: "4.0.2"

## Steps To Reproduce

1.
2.

Link to code example:

## The current behavior

I keep getting the response “unable to find react on the page” under the Components tab

## The expected behavior

I should be able to view all my React components as well as the state and props within them

**Comment by bvaughn** [comment] 2021-02-23 15:39
Steps to reproduce are pretty important. Without them there isn't much we can do to help with this issue, as DevTools seems to be working fine for me.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-02-23 15:39
Your browser + OS versions might also be helpful. As well as letting us know whether this happens on _every_ site or just one.

**Comment by Lazy-poet** [comment] 2021-02-23 15:52
I just restarted my browser and it actually works well now. I was scared for a minute

**Comment by bvaughn** [comment] 2021-02-23 16:04
Okay 👍  Good.

Going to close this for now then.

**Closed by bvaughn** 2021-02-23 16:04 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information
