### ISSUE TITLE
Сontext via Provider and static contextType.

### ISSUE THREAD

**Issue by GTOsss** [facebook/react#15220] opened 2019-03-27 01:00 UTC
If for Provider we will pass as value a new object or function, everytime when new props passed to component - render function will be called without shouldComponentUpdate

If use Consumer instead of static contextType - shoudComponentUpdate will works as expected.

Also if we try to use function and object by reference or primitive data type as value for Provider - shoudComponentUpdate will works as expected.
 
shouldComponentUpdate not working: (23 line):
https://codesandbox.io/s/6w6v78j5kn 
 
shouldComponentUpdate working: (23 line):
https://codesandbox.io/s/0zzzkrry0 

souldComponentUpdate working with arrow function like first case but now use Consumer insted static contextType: (23 line and 51-53 lines): 
https://codesandbox.io/s/y012725j9z

It's look like bug.

**Comment by gaearon** [comment] 2019-04-03 15:17
If you use context via `contextType`, and that context changes, the component will re-render regardless of `shouldComponentUpdate`.

When you use `Context.Consumer`, it won't affect the *parent* component, but the section inside the render prop will re-render in a similar way.

I'm not really sure what the issue is. It would help if you supplied concrete "actual behavior", "expected behavior", and "steps to reproduce". Thanks.

**Comment by GTOsss** [comment] 2019-04-03 20:41
I got it, the problem is that the changing context ignores shouldComponentUpdate. But it would be very good if the new context were send to shouldComponentUpdate and it was possible to control the unwanted render via shouldComponentUpdate.

**Comment by threepointone** [comment] 2019-09-04 09:44
Closing since there appears to be clarity here, and it's working as designed.

**Closed by threepointone** 2019-09-04 09:44 UTC
Labels: Resolution: Needs More Information
