### ISSUE TITLE
Bug: App is unresponsive with React 18

### ISSUE THREAD

**Issue by deepakbhattmits** [facebook/react#24239] opened 2022-04-01 03:48 UTC
Before upgrading to react 18 app was working well but after upgrading this is not responding well

React version:18

## Steps To Reproduce

1. Open the application and wait for 2 sec. then see buttons are not clickable
2. After sometime we will see page unresponsive (snapshots [issue1](https://github.com/deepakbhattmits/app-jitera/blob/master/src/issues/Screenshot%20from%202022-04-01%2009-01-01.png), [issue2](https://github.com/deepakbhattmits/app-jitera/blob/master/src/issues/Screenshot%20from%202022-04-01%2009-02-37.png))

Link to code example:

https://github.com/deepakbhattmits/app-jitera

Deployed URL : https://app-jitera.netlify.app/

## The current behavior
 As you can see in the screenshot.

## The expected behavior
It should run without lag.

**Comment by gaearon** [comment] 2022-04-01 04:00
>after sometime we will see page unresponsive (snapshots [issue1](https://github.com/deepakbhattmits/app-jitera/blob/master/src/issues/Screenshot%20from%202022-04-01%2009-01-01.png), [issue2](https://github.com/deepakbhattmits/app-jitera/blob/master/src/issues/Screenshot%20from%202022-04-01%2009-02-37.png))

Is there any particular sequence of steps that I need to follow?

**Comment by deepakbhattmits** [comment] 2022-04-01 04:11
Hi Gaearon,
If you see this url then you got to know what i am trying to say no need to do any extra effort  [click here to see current behaviour ](https://app-jitera.netlify.app/)

**Comment by ShayanAbedi** [comment] 2022-04-01 16:37
Hi @deepakbhattmits, I had a similar issue with my app and after upgrading the `react-redux` to `7.2.8` it got fixed. hopefully works for you too

**Comment by deepakbhattmits** [comment] 2022-04-01 17:02
Hi **[@ShayanAbedi](https://github.com/ShayanAbedi)** ,
I have tried with this too unfotunaltely it is not working for me thankyou for your help

**Comment by gaearon** [comment] 2022-04-01 17:12
I can't reproduce the issue, everything is clickable for me. Please provide more details on how exactly to reproduce and your environment.

https://user-images.githubusercontent.com/810438/161310638-9818b48f-cb85-4152-ac8c-3d26acd32008.mov

**Comment by deepakbhattmits** [comment] 2022-04-01 17:21
Hi Dan,

Please see just now I have created

https://user-images.githubusercontent.com/19524332/161311814-661bb0ec-ad4c-45c2-ad2a-1ddc5113bab8.mov

**Comment by gaearon** [comment] 2022-04-01 17:28
We'd need more details like OS, browser, etc. It's not obvious from your screenshots. Can you reproduce on other OS/browser too.

**Comment by deepakbhattmits** [comment] 2022-04-01 17:29
> I can't reproduce the issue, everything is clickable for me. Please provide more details on how exactly to reproduce and your environment.
> 
>  clickable.mov

Yes I ee button is clickable for you theme button also works wor you while making favourite toast message is displayed to you ? , unfotunately that all is not working for me , it works if i revert to react 17.0.2 both react and react-dom

**Comment by gaearon** [comment] 2022-04-01 17:31
Yeah, theme button also works for me. I suspect this has to do with your browser/OS somehow but would need more details.

**Comment by deepakbhattmits** [comment] 2022-04-01 17:35
> We'd need more details like OS, browser, etc. It's not obvious from your screenshots. Can you reproduce on other OS/browser too.

Okay I have checked with OS : Ubuntu 20.04.4 LTS(64 bit), Windows ,Browsers: Chrome, firefox

**Comment by gaearon** [comment] 2022-04-01 17:44
So this happens consistently in different OS and browsers? Have you checked one device or several? Can you disable all extensions in browsers and try again?

**Comment by deepakbhattmits** [comment] 2022-04-01 17:45
> an you disable all

Okay let me try currently I have ubuntu with me and I am checking in firefox and in chrome  or do I nned to with window OS ?

**Comment by deepakbhattmits** [comment] 2022-04-01 17:51
Hey Gaearon,

I have disabled all extensions from browser but it is not working as expected , in firefox i don't have any extension installed so there I have checked same there also not working.

**Comment by gaearon** [comment] 2022-04-01 20:12
Have you tried another computer?

**Comment by deepakbhattmits** [comment] 2022-04-02 03:26
> Have you tried another computer?
Hi Gaearon,

It's working in windows firefox, but in Mac os with safari chrome and in ubuntu chrome , firefox it is not working as expected.

**Comment by deepakbhattmits** [comment] 2022-04-02 06:01
> Hi @deepakbhattmits, I had a similar issue with my app and after upgrading the `react-redux` to `7.2.8` it got fixed. hopefully works for you too

I appreciate to your answer but this is not helpful for me

**Comment by gaearon** [comment] 2022-04-02 17:32
Unfortunately I can't reproduce this on macOS in Chrome, Firefox, or Safari at all. I don't have an Ubuntu machine so can't check that.

One thing you can try is to open the DevTools, and then, when it freezes, press "pause" in the source tab. Take a screenshot of the call stack and upload it here so we can see where it's in the code.

**Comment by CodeDead** [comment] 2022-04-03 00:14
Fedora 35 user using Brave browser. Can confirm his application immediately becomes unresponsive upon opening the website.

**Comment by gaearon** [comment] 2022-04-03 01:44
Hmm. Any chance you could do this?

> open the DevTools, and then, when it freezes, press "pause" in the Sources tab. Take a screenshot of the call stack and upload it here so we can see what the code is busy doing.

**Comment by deepakbhattmits** [comment] 2022-04-03 03:47
Hi Gaearon,

Please see two attached snapshots 
![Screenshot from 2022-04-03 09-16-08](https://user-images.githubusercontent.com/19524332/161410493-1bd4231d-e549-4429-a347-c02a5064ab79.png)
![Screenshot from 2022-04-03 09-17-00](https://user-images.githubusercontent.com/19524332/161410494-3a806e8f-a790-45db-830b-3f70de5bd1db.png)

**Comment by gaearon** [comment] 2022-04-03 14:39
Can you please go to the *Sources* tab, press the *Pause* button and screenshot the *Call Stack*? Thanks!

**Comment by deepakbhattmits** [comment] 2022-04-03 15:14
Sure Gaearon,

here it is 
![Uploading Screenshot from 2022-04-03 20-43-24.png…]()

**Comment by gaearon** [comment] 2022-04-03 15:22
Yeah, this is good but by itself doesn’t tell us much… can you Resume and Pause several times while it’s frozen and post multiple screenshots? Maybe we can spot some pattern.

**Comment by deepakbhattmits** [comment] 2022-04-03 15:28
I have made one clip to detect hope this works for you .

https://user-images.githubusercontent.com/19524332/161435363-2eb9cd87-10e5-4420-aeba-312cafb67d43.mp4

**Comment by gaearon** [comment] 2022-04-03 15:43
Thanks for recording. This isn’t quite what I need because I think you pressing the button in the left part of the screen (over the app) may cause more events to be emitted. Can you try only using the Pause/Resume button in the right part (DevTools itself)?

**Comment by deepakbhattmits** [comment] 2022-04-03 15:53
sure here it is 

https://user-images.githubusercontent.com/19524332/161436493-80955f87-928e-427e-9722-42f70bb8d606.mp4

**Comment by DuCanhGH** [comment] 2022-04-03 15:56
The app completely froze the tab for me too on Windows 10 20H2 and Firefox 99.0b8 and I just loaded the site without actually clicking anything.
Weird, such thing has never happened to me since I upgraded my app to React 18, maybe recheck your code for something that may have escaped your notice?

**Comment by deepakbhattmits** [comment] 2022-04-03 16:04
> such thing has never happened to me since I upgraded my app to React 18, maybe recheck your

Hi @DuCanhGH Oh you also got this , well @gaearon is looking into that let's see what his outcome

**Comment by DuCanhGH** [comment] 2022-04-03 16:32
@deepakbhattmits just felt like being lazy today so I went to check if there is any new experimental/next build xD I surfed through the sourcemap (since I can't access your repo), and the code looks quite... normal? I'm kinda suspicious of antd though, it was kinda heavy last time I tried it, maybe it caused the trouble?

**Comment by deepakbhattmits** [comment] 2022-04-03 16:35
> ourcemap (since I can't access your repo), an

If you want to see this is the deployed url https://app-jitera.netlify.app/

**Comment by DuCanhGH** [comment] 2022-04-03 16:46
> > ourcemap (since I can't access your repo), an
> 
> If you want to see this is the deployed url https://app-jitera.netlify.app/ please let me know does this works for you ?

@deepakbhattmits Well that's what I've been using to look into your problem all these times, and of course it froze
Really, I suspect the antd components so much

**Comment by gaearon** [comment] 2022-04-03 16:50
I can't reproduce this in production, but if I add a logpoint to this line in development, it prints it in a cycle and the page becomes unresponsive in development.

<img width="759" alt="Screenshot 2022-04-03 at 17 47 50" src="https://user-images.githubusercontent.com/810438/161438751-458c4a96-39ab-4169-aa45-61a97a812328.png">

Specifically, showing the tooltip over a button is what seems to trigger this logic.

I suspect that Ant Design needs to add `flushSync` somewhere to force some DOM update to be synchronous.

**Comment by deepakbhattmits** [comment] 2022-04-03 16:55
> I can't reproduce this in production, but if I add a logpoint to this line in development, it prints it in a cycle and the page becomes unresponsive in development.
> 
> <img alt="Screenshot 2022-04-03 at 17 47 50" width="759" src="https://user-images.githubusercontent.com/810438/161438751-458c4a96-39ab-4169-aa45-61a97a812328.png">
> 
> Specifically, showing the tooltip over a button is what seems to trigger this logic.
> 
> I suspect that Ant Design needs to add `flushSync` somewhere to force some DOM update to be synchronous.

Do I need to do test without ant-d then it should work what you say ?

**Comment by gaearon** [comment] 2022-04-03 16:56
On a second look, the relevant code is from `rc-align` and `rc-trigger`. But they're brought into the app via `antd`, so yes, please try without `antd` and see if that solves it.

**Comment by deepakbhattmits** [comment] 2022-04-03 17:00
> On a second look, the relevant code is from `rc-align` and `rc-trigger`. But they're brought into the app via `antd`, so yes, please try without `antd` and see if that solves it.

Yes you are right it working well as expected I have tested without Tooltip and Button Thankyou so much for your response I appreciate it

**Comment by gaearon** [comment] 2022-04-03 17:01
OK. I think we can close this issue. Please try to create a minimal reproducing report for `antd` and file an issue on their repo. Include a link to https://github.com/react-component/trigger/issues/288 because it might be relevant.

**Comment by deepakbhattmits** [comment] 2022-04-03 17:02
> OK. I think we can close this issue. Please try to create a minimal reproducing report for `antd` and file an issue on their repo. Include a link to [react-component/trigger#288](https://github.com/react-component/trigger/issues/288) because it might be relevant.

sure @gaearon

**Closed by gaearon** 2022-04-03 17:01 UTC
Labels: Status: Unconfirmed

**Comment by manojdhakat** [comment] 2024-01-28 08:59
page Unresponsive
you can wait for it to become responsive  or exit the page

**Comment by pwbriggs** [comment] 2024-01-28 22:22
👋 Hey there @manojdhakat,

If you can create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating the bug you're experiencing, please [open a new issue](https://github.com/facebook/react/issues/new/choose).

Thanks! 😄
