### ISSUE TITLE
IE10 nativeEvent object missing returnValue for input onChange events

### ISSUE THREAD

**Issue by jslatts** [facebook/react#6699] opened 2016-05-04 20:22 UTC
I just ran into this issue while testing the upgrade from 0.14.8 to 15.2 in IE 10. If preventDefault() or stopPropagation() is called inside the handler for an onChange event of an input control, a "Member not found" exception is thrown. Stepping through the code, it appears that the the nativeObject reference is broken. Accessing most of the properties of the MSEventObj will throw the same exception.

I am able to reproduce it with the minimal case below on a clean IE10 Windows7 test VM from Microsoft.

Repro Fiddle: https://jsfiddle.net/h6qfwa51/3/

**Comment by jimfb** [comment] 2016-05-04 23:29
Haven't looked into it, but I'll tentatively tag this as a regression since apparently it worked on 0.14.8.

@jslatts sounds like you've started looking into this already.  Do you want to submit a PR for this?

**Comment by jslatts** [comment] 2016-05-05 16:57
@jimfb I will definitely take a crack at tracking down the issue and will submit a PR if I can figure it out. But this will be my first foray into the React codebase, so anyone who knows what they are doing should feel free to jump in. Also would be nice to have someone else confirm the issue.

**Comment by zpao** [comment] 2016-05-05 23:10
Is this only happening with IE10? Does this only happen when using the development build? My guess is that it's related to the new warnings for synthetic events so that's where I would start investigating: https://github.com/facebook/react/blob/2af4765a2af0d4de81d2f23f702d9d39d8917a0b/src/renderers/dom/client/syntheticEvents/SyntheticEvent.js#L177

**Comment by jslatts** [comment] 2016-05-06 17:09
I'm only set up to test in IE10 at the moment. The issue happens on the 15.0.2 release distributed via FB CDN (which is used in my test case above). 

The good news is that I located the [commit and line of code](https://github.com/facebook/react/blob/b5e7a8447caef042b8c52a064f45b925b4ff613c/src/renderers/dom/client/eventPlugins/ChangeEventPlugin.js#L147) that caused the bug.

It also appears to be [fixed in master](https://github.com/facebook/react/commit/045f1a791c6e17253e9d927ffca70ae5d00b4fe5#diff-d7d43033e0c4300df2b535a9df27b8edR168), so assuming that the commit with the fix lands in a future release, I don't think there is any work to do here.

**Comment by jimfb** [comment] 2016-05-06 17:11
@jslatts Would you mind verifying in http://jsfiddle.net/9kungxn4/ which is a build that contains the commit you mentioned.

**Comment by jslatts** [comment] 2016-05-06 21:15
@jimfb that test works correctly in IE10/Win7 and IE10/Win8 for me.

**Comment by jimfb** [comment] 2016-05-06 23:41
Excellent, I'll close this out!  Thanks @jslatts!

**Closed** 2016-05-06 23:47 UTC
Labels: Type: Regression

**Comment by zpao** [comment] 2016-05-09 20:09
It looks like that change isn't likely to make it into 15 so you may be waiting a while for the fix. If there's something smaller that fixes your issue we might be able to take that.

**Comment by jslatts** [comment] 2016-05-09 21:39
@zpao smaller like just reverting this line of code:

    !('documentMode' in document) || document.documentMode > 11

back to 

    !('documentMode' in document) || document.documentMode > 9

?

**Comment by tjcampbell** [comment] 2016-05-24 13:28
@zpao @jslatts I just stumbled across this. Is there a workaround for the time being? I see the fix is only planned for 16.0. I can confirm simply reverting `document.documentMode > 11` to `document.documentMode > 9` as mentioned by @jslatts fixes the issue.

This must be breaking plenty of sites on IE10.

**Comment by jslatts** [comment] 2016-05-24 16:12
@tjcampbell I reverted back to 0.14.8 as a workaround. I would be happy to submit the PR with the one line change above it @zpao confirms they will accept it. I just don't know enough about the intent behind the change in the first place and possible side effects.

**Comment by tjcampbell** [comment] 2016-05-25 09:55
Might help getting @jquense's opinion on this as he made the change. @zpao can we re-open this? I feel this is urgent enough to warrant a separate fix before #5746 is merged. This issue,  #6614 and #6822 seem to be caused by #4051, making React 15 pretty unusable on IE.
