### ISSUE TITLE
Error: "Commit tree does not contain fiber 9869. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by iktarun** [facebook/react#19359] opened 2020-07-15 05:16 UTC
Describe what you were doing when the bug occurred:
1. I was recording profile and then I was trying to navigate to the other route on my website. Then I have stopped profiler and I have seen this error in the profiler.
2. I am lazy loading the page here.

Here is my react version:
 ```
 "react": "16.8.6",
   "react-dom": "16.8.6",
```

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.1-d4eadea6c

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:167176)
    at T (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:165979)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:168938)
    at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346620)
    at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:60964)
    at Ui (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:70944)
    at Bl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:117704)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103070)
    at Oc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102998)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102861)

Component stack: at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346391)
    at div
    at div
    at div
    at Eo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:266560)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:370969
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:279481)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:282269
    at div
    at div
    at Ji (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:329374)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:209300)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:218616)
    at Wa (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:297360)
    at ps (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:376211)

**Comment by gaearon** [comment] 2020-07-15 13:31
Is there a reproducible version of your page somewhere that we could test it on?

**Comment by bvaughn** [comment] 2020-07-15 14:00
Likely a duplicate of #18831

**Comment by bvaughn** [comment] 2020-07-15 14:10
FYI #19368 will likely fix this.

**Comment by bvaughn** [comment] 2020-07-15 16:26
Should be fixed by #19373 

New release will go out shortly

**Closed by bvaughn** 2020-07-15 16:26 UTC
Labels: Component: Developer Tools, Type: Bug

**Comment by bvaughn** [comment] 2020-07-15 17:10
Version 4.8.2 has just been published to NPM and submitted to Chrome/Edge/Firefox stores with a fix for this issue.

Browsers sometimes take a few hours to approve a new extension version, but once the new version goes live this should be resolved. Sorry for the inconvenience.

**Comment by iktarun** [comment] 2020-07-15 17:15
Thanks @gaearon @bvaughn for the response. I'll wait for these changes to reflect soon. 
One more odd behavior I have noticed related to lazy loading and DevTools will create a new thread for that.

**Comment by iktarun** [comment] 2020-07-15 17:17
@gaearon I can't share the page here.
