### ISSUE TITLE
shared `isTextInputElement.js` has untested behavior

### ISSUE THREAD

**Issue by IanDCarroll** [facebook/react#15954] opened 2019-06-21 18:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the shared folder, there is a function that checks if an HTMLElement is a Text field. It's used for helping with onChange events picked up by the ChangeEventPlugin and the SelectEventPlugin. It was at one point part of the ChangeEvent code before being abstracted out in 2013.

If I comment out all but three type checks in this file, The tests all still pass.

```
const supportedInputTypes: {[key: string]: true | void} = {
  // color: true,
  // date: true,
  // datetime: true,
  // 'datetime-local': true,
  // email: true,
  // month: true,
  number: true,
  // password: true,
  range: true,
  // search: true,
  // tel: true,
  text: true,
  // time: true,
  // url: true,
  week: undefined, // changed from true; same behavior as commenting out the line
};
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

Tests should fail if any of the above branching logic switches from false to true or true to false.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm branching off master at `commit 5368f7316c8ae489c6a271694166158428ee4a5e`
This behavior is code-specific so It should be platform agnostic.

**Comment by IanDCarroll** [comment] 2019-06-21 18:37
As a spike, I wrote a test suite that covers the behavior by testing the `isTextInputElement()` function directly. I could submit that as a PR.

Rather than avoiding testing what could be thought of as an implementation detail and writing tests through the ChangeEventPlugin, I thought it might be best to test this code directly, since it now serves more than that single file. But maybe there's another way of thinking.

I realize this is a code cleanliness issue, and not exactly a bug. I was just thinking it's better to be covered in the event of a bug in the future, the tests here will help narrow down the issue.

**Comment by aweary** [comment] 2019-06-24 23:29
@IanDCarroll feel free to submit a PR with some tests! Keep in mind that we don't really write tests that only test implementation details or internal modules. We've found that it's too fragile and often provides a false sense of coverage. If you can come up with some tests using public APIs only, that'd be great!

Closing this since it's not a bug or feature requests.

**Closed by aweary** 2019-06-24 23:29 UTC
