### ISSUE TITLE
[DevTools Bug] Cannot read property 'isCollapsed' of undefined

### ISSUE THREAD

**Issue by ashiktm** [facebook/react#21545] opened 2021-05-21 08:28 UTC
### Website or app

CHROME

### Repro steps

1. Open React Devtool
2. Select the Component tab
3. Got below error

### How often does this bug happen?

Only once

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.3-d6604ac031

### Error message (automated)

Cannot read property 'isCollapsed' of undefined

### Error call stack (automated)

```text
at store_Store.getElementAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21750:35)
    at store_Store.getElementIDAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21766:26)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29360:63
    at List.render (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:23484:18)
    at Fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13922:76)
    at Ei (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13913:10)
    at sk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16655:86)
    at rk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16172:11)
    at qk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16164:23)
    at hk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16148:5)
```

### Error component stack (automated)

```text
at List (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:23179:30)
    at div
    at AutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:3642:5)
    at div
    at div
    at Tree_Tree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29121:47)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28270:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28711:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34555:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30035:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30136:5)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34181:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24947:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25550:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30277:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37284:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot read property 'isCollapsed' of undefined in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment] 2021-05-21 14:37
Hi @ashiktm 👋🏼 

Sorry to hear that you ran into this bug. Unfortunately it doesn't look like you shared any way for us to reproduce it, so it's not something we can help fix. Please update the issue description with instructions (and either code or an app that we can run) telling us how to reproduce the problem.

We generally recommend providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-05-25 18:49
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-05-25 18:49 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
