### ISSUE TITLE
Break with 15rc1

### ISSUE THREAD

**Issue by technion** [facebook/react#6262] opened 2016-03-14 10:09 UTC
Hi,

I have a fairly trivial application which was running on ReactJS 0.14.x. Since I've moved it to 15rc1, it continues to work perfectly in Chrome. However, in IE11, in appears to render critical parts empty. The relevant piece of code where I'm failing is here:

https://github.com/technion/erlvulnscan/blob/master/frontend/assets/erlvulnscan.jsx#L37

There is no error output on the debug console. The DOM explorer appears to just render it with missing data.

<div class="alert alert-info" role="alert"></div>

You can see the application with the relevant behaviour running live at: https://erlvulnscan.lolware.net. Enter any network (127.0.0.0 will yield the fastest return) to see the issue.

Edit: For non IE users, you can see a SS here: http://imgur.com/i9TciqZ

**Comment by syranide** [comment] 2016-03-14 10:29
I suspect this is what you're seeing: #6246 #6251

**Comment by jimfb** [comment] 2016-03-14 18:11
I agree with @syranide, this looks like a duplicate of the mentioned bugs.  The fix has already been merged into master.  If you experience the bug in RC2 (which will be released soon) or in the future build, ping us to reopen/reinvestigate.

**Closed by jimfb** 2016-03-14 18:11 UTC

**Comment by technion** [comment] 2016-03-15 01:46
Thanks everyone! Looking forward to RC2.
