### ISSUE TITLE
Bug: React.StrictMode render 2

### ISSUE THREAD

**Issue by Mrheqiang** [facebook/react#24746] opened 2022-06-17 02:52 UTC
React version: 18.2

## Steps To Reproduce

1. download npx create-react-app my-app --template redux-typescript
2. npm start

Link to code example:

`function Ddd() {
  return (
    <React.StrictMode>
      <Dd />
    </React.StrictMode>
  );
}`

`function Dd() {
  console.log(12);
  return <div>12</div>;
}`

`root.render(
  <Ddd />
);`

## The current behavior
Dd render 2 times

## The expected behavior
Dd render 1 times

**Comment by F3n67u** [comment] 2022-06-17 07:02
I can reproduce this problem with the following code:

```
$ cat index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <div id="container"></div>
    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
    <script>
      function Dd() {
        console.log(12);
        return React.createElement(
          'div',
          null,
          '12'
        );
      }

      function App() {
        return React.createElement(
          React.StrictMode,
          null,
          React.createElement(Dd, null, null)
        );
      }


      const domContainer = document.querySelector('#container');
      const root = ReactDOM.createRoot(domContainer);
      root.render(React.createElement(App));
    </script>

  </body>
</html>
$ npx http-server
```

Then open the link `http://127.0.0.1:8080`, and you will see 12 is printed twice in the console.

**Comment by eps1lon** [comment] 2022-06-17 07:03
This is expected behavior from having your component in a `StrictMode` tree. You can read more about the behavior of `StrictMode` in https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects.

Note that you can disable console logs for the second render in React Devtools:

> In React 17, React automatically modifies the console methods like console.log() to silence the logs in the second call to lifecycle functions. However, it may cause undesired behavior in certain cases where [a workaround can be used](https://github.com/facebook/react/issues/20090#issuecomment-715927125).
>
>Starting from React 18, React does not suppress any logs. However, if you have React DevTools installed, the logs from the second call will appear slightly dimmed. React DevTools also offers a setting (off by default) to suppress them completely.

Duplicate of https://github.com/facebook/react/issues/24425

**Closed** 2022-06-17 07:05 UTC
Labels: Status: Unconfirmed, Resolution: Expected Behavior
