### ISSUE TITLE
Suspense unmounts children and fallback even they have the same type and key

### ISSUE THREAD

**Issue by otakustay** [facebook/react#15921] opened 2019-06-19 10:01 UTC
**Do you want to request a *feature* or report a *bug*?**

I think it is a bug.

**What is the current behavior?**

When a `Suspense` is given `fallback` and `children` with same type and key, suspense still unmount and remount them when its state changes between pending and resolved.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/sleepy-cannon-47291

**What is the expected behavior?**

In console, it should be only 1 "system suspense mounted" message, suspense should update the `SystemContent` component instead of remount it.

When use error boundary to "simulate" a suspense, we can make sure the `CustomContent` is only mounted once, we'd like the native suspense to behave the same.

As a real world case, we rely on the content component to live across promise's life in order to "keep previous data visible when loading new data", when content is unmounted on pending, it loses a `useRef` stored previous data snapshot.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.6

**Comment by kunukn** [comment] 2019-06-20 21:42
It would speculate that this is a feature request.


From the readme: https://reactjs.org/docs/code-splitting.html#suspense
I read it as two different components. It doesn't indicate that it can be the same component.


Secondly, usage of `Suspense` where a promise is thrown seems creative and doesn't exists in any official React documentation to my knowledge. The documentation uses `lazy` and `Suspense` in combination.

**Comment by threepointone** [comment] 2019-09-06 12:14
This is by design. The fallbacks and content aren't reconciled against each other. If you want this behaviour, I'd think that you *don't* want to suspend rendering really. 

There are different loading patterns we want to support and have been working on, and we'll have more to say about it soon. Closing this issue.

**Closed by threepointone** 2019-09-06 12:14 UTC
