### ISSUE TITLE
JSX -- parentheses around object literal transforms to invalid JS

### ISSUE THREAD

**Issue by benmosher** [facebook/react#2855] opened 2015-01-14 12:26 UTC
The comma and right parenthesis emitted from JSX-transforming a line like that in the title will result in the following:
```jsx
// source JSX
var ExampleCommaIssue = React.createClass({
	render: function () {
	    return <div style={({'margin':'42px'})} className="test" />;
	}
});
 
// transforms to 
... React.createElement("div", {style: ({'margin':'42px'}, )className: "test"}); ...
 
// instead of
... React.createElement("div", {style: ({'margin':'42px'}), className: "test"}); ...
```

Notably, this only seems to be a problem if some attribute follows the one with the paren-hugged object literal. 

Also, I did not test to see if arbitrary values in parentheses also result in this.

**Comment by syranide** [comment] 2015-01-21 22:33
Duplicate of #1673

**Closed by syranide** 2015-01-21 22:33 UTC
Labels: JSX (React Flavored)
