### ISSUE TITLE
RFC: distribute `.flow` files with React

### ISSUE THREAD

**Issue by iamdustan** [facebook/react#9061] opened 2017-02-24 20:03 UTC
This RFC is regarding distributing typedef files with React. While this would be generally useful (and possibly useful to extract the [React.js definitions](https://github.com/facebook/flow/blob/master/lib/react.js) out of flow itself (especially for renderer-implementers), it would be especially nice for renderer implementers.

(I have manually extracted the minimal required for a react renderer in https://github.com/iamdustan/tiny-react-renderer/tree/fiber/src/fiber-types)

Possible solutions:

* ensure `flow gen-flow-files ....` works and generates all of the `*.js.flow` files in packages
* add a custom step to the build tooling to include the public renderer type def for each public package + a minimal typedef for `ReactFiberReconciler.js` in each package that receives that file.

**Comment by aweary** [comment] 2017-02-24 20:06
I believe this is a duplicate of https://github.com/facebook/react/issues/5472

**Comment by iamdustan** [comment] 2017-02-24 20:07
Ah. Thanks, @aweary. I looked for that issue in the flow repo.

I’m updating the description because I hit publish prematurely.

**Closed** 2017-02-24 20:09 UTC
