### ISSUE TITLE
Dynamic import with Hook.

### ISSUE THREAD

**Issue by linkdeseda** [facebook/react#17179] opened 2019-10-24 22:07 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Trying dynamic import with hooks and fail with this error: 

> Should have a queue. This is likely a bug in React. Please file an issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```
   const [PathTest, setPathTest] = useState("");

  import(`Layout/ModalTest`).then(module => setPathTest(module.default))
```

**What is the expected behavior?**

Dynamic import with hooks.  This is a example with class component:

import(`${path}`).then(module => this.setState({ module: module.default }))

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

    "react": "^16.9.0",Debian,Vivaldi.

**Comment by aweary** [comment] 2019-10-25 00:29
Can you please provide a minimal demo of the problem? You can use https://codesandbox.io/s/new to share a hosted example. It's not clear from the two lines of code what you're trying to do and whats breaking.

**Comment by M-Izadmehr** [comment] 2019-10-25 17:47
I created a simple example, but it works as expected:
https://codesandbox.io/s/inspiring-aryabhata-p9n8l

Because at the very end, the dynamic import is a simple function(not function but function like) that returns a promise, and you should be able to use useState when it resolves.

Also, maybe the problem is that you are trying to use the dynamic path like `import(path)`, depending on your module bundler it cannot work.
if you use this syntax ```import(`Layout/${path}`)``` it is ok for webpack because it at least knows, it should create a chunk for the contents of Layout folder

**Comment by threepointone** [comment] 2019-10-29 18:16
Did you mean to use React.lazy? https://reactjs.org/docs/code-splitting.html#reactlazy

Closing, happy to reopen if there’s a reproducing example provided.

**Closed by threepointone** 2019-10-29 18:16 UTC
Labels: Resolution: Needs More Information

**Comment by simpleshadow** [comment] 2020-03-06 00:05
Just encountered this issue as a result of trying to lazy load a hook in a `useEffect` + `useState` callback.

**Comment by DominicTobias** [comment] 2020-12-09 15:26
I have the same issue, I don't think React.lazy is a substitute since it causes a flash of unstyled content (when loading the fallback) even if the route is loaded since it's always async and causes everything to unmount even if it's not necessary.

```ts
const importRegistry = new Map<string, () => JSX.Element>();

const lazyPages = {
  HomePage: () => import('pages/HomePage'),
  SignInPage: () => import('pages/SignInPage'),
  SignUpPage: () => import('pages/SignUpPage'),
  CreateFlowPage: () => import('pages/CreateFlowPage'),
  CasePage: () => import('pages/CasePage'),
  NotFoundPage: () => import('pages/NotFoundPage'),
};

export function preloadRoute(name: keyof typeof lazyPages) {
  if (!importRegistry.get(name)) {
    (lazyPages[name]() as Promise<{
      default: () => JSX.Element;
    }>).then((mod) => {
      importRegistry.set(name, mod.default);
    });
  }
}

interface AsyncPageProps {
  name: keyof typeof lazyPages;
}

function AsyncPage({ name }: AsyncPageProps) {
  const [element, setElement] = useState<JSX.Element | undefined>(importRegistry.get(name));

  useEffect(() => {
    if (!element) {
      (lazyPages[name]() as Promise<{
        default: () => JSX.Element;
      }>).then((mod) => {
        importRegistry.set(name, mod.default);
        setElement(mod.default);
      });
    }
  }, [name, element]);

  return element ? element : <>Loading...</>;
}
```

Using this kind of structure should be better than React.lazy as it won't cause a flash of fallback content if the route has already been loaded but getting the same error as the OP:

```tsx
 <Switch>
          <Route path="/signin">
            <AsyncPage name="SignInPage" />
          </Route>
  </Switch>
```
