### ISSUE TITLE
Issue with dangerouslySetInnerHTML and markup rehydration

### ISSUE THREAD

**Issue by smashercosmo** [facebook/react#11228] opened 2017-10-14 20:17 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to rehydrate markup in IE11 'Argument is not optional' error is thrown. It happens only if component has dangerouslySetInnerHTML prop.

**Example**
https://jsfiddle.net/oy9awLtq/

**What is the expected behavior?**
No error should be thrown

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version: 16
Browser: IE11

**Comment by nhunzaker** [comment] 2017-10-14 20:24
Confirmed. The offending code:

```javascript
var normalizeHTML = function (parent, html) {
  if (!testDocument) {
    testDocument = document.implementation.createHTMLDocument();
  }
  // ...
}
```

This is a duplicate of https://github.com/facebook/react/issues/10865, and was fixed in https://github.com/facebook/react/pull/10921.

In any case, thank you for filing and providing a reproduction case!

**Closed by nhunzaker** 2017-10-14 20:24 UTC

**Comment by smashercosmo** [comment] 2017-10-14 20:27
Awesome. Thx.

**Comment by gaearon** [comment] 2017-11-03 00:51
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.
