### ISSUE TITLE
Error: "Could not find node with id "266" in commit tree"

### ISSUE THREAD

**Issue by ldcc-juj** [facebook/react#16446] opened 2019-08-19 01:27 UTC
PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

I got this error when I click 'Ranked'.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.4-3c6a219

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11441
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11387)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11920)
    at _i (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:277123)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:98280)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363

Component stack: in _i
    in div
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ha
    in le
    in ve
    in ko
    in Ul

**Comment by bvaughn** [comment] 2019-08-19 18:07
More detailed repro steps would be appreciated. What did you do up util you clicked "Ranked"?

**Comment by Apollinaire** [comment] 2019-12-10 14:43
Same here. I got this problem today on this profiling: https://gist.github.com/Apollinaire/effeb23efae1d603e9e0b6a8e39132e5
First time i had the error it said id 273, then I refreshed the page, the profiling was still present so I downloaded it to see if just the profiling reproduces the error. It does, but now it says id 257. 
Reproduction: I just opened the profiler, recorded, fiddled with my app, stopped the record, then looked at the commits. Everything was fine, until I clicked on the Ranked tab. I instantly saw the error message that got me here.
Version: `React Developer Tools
4.2.1 (11/27/2019)
Adds React debugging tools to the Chrome Developer Tools. Created from revision 3816ae7c3 on 11/27/2019.`
Hope that helps

**Comment by bvaughn** [comment] 2019-12-10 15:18
@Apollinaire Thank you for sharing the profile JSON and extra info! 🙇

**Comment by bvaughn** [comment] 2020-01-02 18:05
Digging into the repro this morning.

Looks like the missing Fiber (257) *is* in the data, but according to the `operations` array, it doesn't get added until the second commit. However the profiler data for the commit references it in the first commit. Not accounting for that, there seem to be other Fibers that are also off by one like this.

Looking closer at the `operations` array, I see 5 commits even though there are only 3 `commitData` entries. Two of the operations entries stand out because of their small size:
```js
[ 1, 1, 0 ],
```

I *think* this might be the key to the problem. I *think* these commits are bailouts so the profiler is ignoring them. Except it's also indexing their `operations` arrays - so it's ending up throwing things off. If I manually adjust the profiler data to remove these two no-op entries, the data loads and parses without any errors.

I have a solid lead now on how to dig into this! :smile:

**Comment by bvaughn** [comment] 2020-01-02 18:42
Hm 🤔 The specific bailouts I linked to above were added *after* this issue started happening (#17253) but I think the general idea of what's causing this bug is still correct.

**Comment by bvaughn** [comment] 2020-01-02 21:05
@Apollinaire I don't suppose you are able to repro this broken profile export? If so, is there any chance I could see the code that reproduces it? Might help me to track down exactly why it's happening.

**Comment by bvaughn** [comment] 2020-01-03 18:24
FYI v4.4 (released today) should *greatly improve* this issue, but will not fix it entirely. I'm still working on it.

**Comment by bvaughn** [comment] 2020-01-05 00:51
Hopefully fixed by #17771

**Closed by bvaughn** 2020-01-05 00:51 UTC
Labels: Component: Developer Tools, Type: Bug

**Comment by Apollinaire** [comment] 2020-01-08 17:31
@bvaughn I was able to repro it a couple of times when I submitted my first comment here. I have not tried to do it again since I can see that you have (hopefully) found a solution.
And yes, the original code that was profiled is private.
