### ISSUE TITLE
Bug: Yarn test not working after fresh installation

### ISSUE THREAD

**Issue by JustalK** [facebook/react#21549] opened 2021-05-23 07:34 UTC
Hello,

Following [your documentation](https://reactjs.org/docs/how-to-contribute.html#sending-a-pull-request)

I made a fresh install and the test are failing even before doing any modification to the repository

React version:

The one on master branch
commit: https://github.com/facebook/react/commit/a731a51696239a69a6cd89cdd34f23ce2fc39099
Ubuntu LTS
Node v14.16.1

## Steps To Reproduce

1. git clone https://github.com/facebook/react.git
2. yarn install
3. yarn test

Link to code example:
I did not do anything yet and I received 3 errors :

![Screenshot from 2021-05-22 23-05-59](https://user-images.githubusercontent.com/5208910/119251901-abd49600-bbdb-11eb-98f1-d390db8bbead.png)
![Screenshot from 2021-05-22 23-06-17](https://user-images.githubusercontent.com/5208910/119251902-ad9e5980-bbdb-11eb-98d8-623867eb80bf.png)
![Screenshot from 2021-05-22 23-06-21](https://user-images.githubusercontent.com/5208910/119251903-ae36f000-bbdb-11eb-9b5f-b60453f4530b.png)
![Screenshot from 2021-05-22 23-06-24](https://user-images.githubusercontent.com/5208910/119251904-aecf8680-bbdb-11eb-9918-e848ffe22728.png)

## The current behavior

The tests are failing

## The expected behavior

The tests should pass after a fresh install

**Comment by eps1lon** [comment] 2022-04-29 21:15
Duplicate of https://github.com/facebook/react/issues/18610

**Closed by eps1lon** 2022-04-29 21:15 UTC
Labels: Status: Unconfirmed
