### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by TamaraMalakhova** [facebook/react#23035] opened 2021-12-27 20:33 UTC
### Website or app

It's empty project creating with 'react-native init'

### Repro steps

1. Start rn app in debug mode

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.14.0-d0ec283819

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:140545
    at c.emit (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:89515)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:90986
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:347787
    at Array.forEach (<anonymous>)
    at S.Gc.e.onmessage (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:347771)
    at S.n (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:3009)
    at S.emit (events.js:315:20)
    at e.exports.P (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:9318)
    at e.exports.emit (events.js:315:20)
    at e.exports.dataMessage (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:15409)
    at e.exports.getData (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:14651)
    at e.exports.startLoop (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:12066)
    at e.exports._write (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:11421)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by AirZT11** [comment] 2021-12-28 23:26
I'm also getting this error!

**Comment by TamaraMalakhova** [comment] 2021-12-29 08:18
> I'm also getting this error!

Hope It will be resolved soon. Do you have this problem on Mac with M1?

**Comment by systemidx** [comment] 2021-12-29 15:49
I'm also getting this.

Dev Environment: Windows 11
Target: Android Emulator, Pixel 4, API 30
React Native Debugger - v0.12.1
React Native - v0.66.4

**Comment by sdelrio** [comment] 2021-12-31 12:50
Dev Environment: Linux
$ node --version
v16.9.0

packages.json
    "@mdx-js/react": "^1.6.21",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",

**Comment by mikeogi** [comment] 2022-01-01 21:05
Error went missing after adding to package.json
`"resolutions": {
    "react-devtools-core": "4.11.0"
  },`
but there was message about unsupported devtools backend version. Use [flipper](https://github.com/facebook/flipper). More about the problem [there](https://gist.github.com/bvaughn/4bc90775530873fdf8e7ade4a039e579)

**Comment by boxedition** [comment] 2022-01-05 16:12
Bump.

Win 10 - Target: Android Emulator, Pixel 2, API 30

[Info] 
You are running react-devtools version 4.14.0-d0ec283819
Tryed to do: npm i -g react-devtools@^4.22.0  (Nothing)

node -v 16.13.1
npm -v 8.1.2

Fresh Expo from yesterday and RND 0.12.1

"dependencies": {
    "expo": "^44.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-vector-icons": "^9.0.0",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/expo": "^33.0.1",
    "@types/react": "^17.0.38",
    "@types/react-native": "^0.66.11",
    "@types/react-native-vector-icons": "^6.4.10",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.4"
  },

**Comment by dimovj-dj** [comment] 2022-01-11 10:00
I'm also getting this error! Any progress in fix or some temporary solution?

**Comment by mikeogi** [comment] 2022-01-11 10:03
> I'm also getting this error! Any progress in fix or some temporary solution?

I have a bug missing, after all packages have been updated and changed to flipper devtools

**Comment by paulyiu-gammon** [comment] 2022-01-11 10:25
i am using react-native-debugger 0.12.1 and have some issue, it keep compliant react-devtools-core version;(

i can workaround it by:
- add "resolutions": { "react-devtools-core": "~4.14.0" } to package.json
- remove react-devtools-core in yarn.lock
- yarn install --check-files

**Comment by Slyness98** [comment] 2022-01-11 19:42
I'm also receiving this error, both with this package(@latest, v4.22.1) and in react-native-debugger v0.12.1. Here are my findings after combing through this issue, issue [#21636](https://github.com/facebook/react/issues/21636), and a couple indirectly relevant SO questions: Those of you using NPM and encountering this in RNDebugger seem to be out of luck until another version is released, as it still uses React DevTools v4.14, whose compatibility is out of sync with react-devtools-core. I'll see if I can raise an issue or something in that repo to help get it back on track. NPM hasn't had a equivalent to yarn's "resolutions" which has been noted as a workaround above, but according to the bottom answer of [this](https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions) SO thread, it allegedly arrived as "overrides" in npm v8.3. I haven't upgraded nor tested this, but it may be worth taking a shot and seeing if it works. For those of you wanting to try this route, see the relevant portion of the npm docs [here](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)

I _can_ however get the react-devtools package to work by bumping up my global installation of react-devtools-core to the latest v4.22.1, same as react-devtools. This just leaves us with the Profiler and Components tabs of React devtools, instead of RNDebugger's extra redux devtools and plain devtools integration, which is unfortunate but it's better than nothing.

For those of you like me who are brand new to React Native and these various standalone devtools outside the browser, [have a look at how to customize the port that the react-devtools package listens to](https://github.com/facebook/react/tree/main/packages/react-devtools-core#react-devtools-core-1)  if your project's dev environment doesn't listen to the default port 8097.

**Comment by junkboy0315** [comment] 2022-01-12 05:45
@paulyiu-gammon 's quickfix worked for me! thanks.

Note that `resolutions: "..."` is need to be in the root package.json if the project is monorepo.
Writing in sub package's package.json didn't effect for me.

**Comment by junkboy0315** [comment] 2022-01-12 06:16
I realized that upgrading react-devtools-core >= 4.22.0 breaks react-native-debugger.

[Minimal reproductive sample (zip)](https://github.com/facebook/react/files/7852149/sample.zip)

This sample works fine with debugger at first.
But it will break if you follow the steps below.

- remove `react-devtools-core` in `yarn.lock`.
- run `yarn add react-devtools-core`.    <- v4.22.1 will be installed
- run expo. devtools is broken.

**Comment by bvaughn** [comment] 2022-01-12 13:48
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#21636) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~

**Closed by bvaughn** 2022-01-12 13:48 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools
