### ISSUE TITLE
Bug: React render function works in development but returns null in production

### ISSUE THREAD

**Issue by marquisvictor** [facebook/react#19534] opened 2020-08-05 12:43 UTC
I spent a lot of time figuring out why my code works perfectly well in development, but after building and deploying for production, it returns null. See the error below:

`ni(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

It turned out there was a comment immediately after the render function and due to the code minification in production, all the codes written after the comment weren't recognized. That was the bug. The error log isn't on its own very intuitive. I had to figure it out on my own. What made it worse was that it worked in development. It shouldn't have.

React version: 16.13
Node version: 12.16

The easiest way to show this is with an example:

```js
const logic = () => {
        // whatever logic goes here
        return(
        // this comment won't let this div container render 
        <div>Hello there </div>
    );
}
export default showProfiles;
````

The above code works in development but would fail in production because of the comment right after the return statement in the render function. I feel its not supposed to work in the development in the first place. Since the error log just says null in the render function. nothing specific to where the error is coming from.  

```js
const showProfiles = () => {
         
        // whatever logic goes here

        // this comment if you must can then be placed outside the return function.

        return(
 
        <div>Hello there </div>

    );
}
export default showProfiles;
```

This on the other hand works fine in both development and production.

## Current behavior
Works in development and fails in production

## The expected behavior
Output a specific error in both development and production. So the developer knows there's something wrong with the code before shipping for deployment.

**Comment by gaearon** [comment] 2020-08-05 12:47
What are you using to compile and minify your code? Any specific toolchain?

Minification must never change the meaning of the code. What you're describing sounds like a bug in the transform pipeline. This means it's not a React bug but you should report it to the part responsible for breaking the code. It could be some transform you're using, a minifier, or something else.

**Comment by gaearon** [comment] 2020-08-05 12:48
>The above code works in development but would fail in production because of the comment right after the return statement in the render function. I feel its not supposed to work in the development in the first place. 

It's supposed to work. (Both in development and production.) Something that you run in production is buggy and breaks the code.

**Comment by marquisvictor** [comment] 2020-08-05 12:53
I started the project with --create-react-app, I didn't use any specific minifier, just the `yarn build . `

**Comment by gaearon** [comment] 2020-08-05 12:59
Can you please file it here? This sounds a bug in the minifier it's using.
https://github.com/facebook/create-react-app/issues/new/choose

A minimal reproducing project would *really* help too.

**Comment by marquisvictor** [comment] 2020-08-05 13:00
Great thanks. right away.

**Comment by bvaughn** [comment] 2020-08-05 14:48
I'm going to go ahead and close this issue since the thing being discussed is not really related to React, but rather the compilation chain.

**Closed by bvaughn** 2020-08-05 14:48 UTC
Labels: Status: Unconfirmed
