### ISSUE TITLE
[DevTools Bug]: 'This page is using the react build message' in every site

### ISSUE THREAD

**Issue by Fernando-Espinosa** [facebook/react#23107] opened 2022-01-14 05:36 UTC
### Website or app

youtube.com, github.com, gmail.com, lucidchart.app

### Repro steps

1. Open any web app not made with React (e.g.: youtube.com, amazon.com, github.com, gmail.com, lucidchart.app)
2.  The react icon is ON and the popover message says:
 'This page is using the production build of React. ✅'

### How often does this bug happen?

Every time

**Comment by msx47** [comment] 2022-01-14 11:06
Can confirm this happening on all websites I have opened today. No erros logged from content, popup or background scripts.

**Comment by developer-diganta** [comment] 2022-01-14 12:27
Yes I found this issue too. And the components tab is empty if we inspect it on such sites.

**Comment by msx47** [comment] 2022-01-14 13:46
Doesn't seem to be an issue on firefox. Chrome still has the issue even after removing and re-installing the extension (same results in incognito mode).

Firefox Version: 95.0 64-bit, Ubuntu
Chrome Version: 96.0.4664.110 64-bit, Ubuntu

**Comment by bvaughn** [comment] 2022-01-14 14:46
I can't reproduce this error using the URLs listed above:

<img width="835" alt="Screen Shot 2022-01-14 at 9 36 50 AM" src="https://user-images.githubusercontent.com/29597/149532989-e52237d4-24d8-4eba-a36c-aa2fa02642cf.png">

<img width="839" alt="Screen Shot 2022-01-14 at 9 37 08 AM" src="https://user-images.githubusercontent.com/29597/149532991-7ce4c5ca-15cd-4b0f-839d-884067870fcd.png">

Could it be possible that you have some other extension installed that's doing something unexpected here?

Can you run the following code in your developer console on one of these pages and paste the result here for me?
```js
console.log(
  JSON.stringify(
    Array.from(__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.values()).map(
      (renderer) => ({
        rendererPackageName: renderer.rendererPackageName,
        version: renderer.version,
      })
    )
  )
);
```

**Comment by msx47** [comment] 2022-01-14 17:02
> I can't reproduce this error using the URLs listed above:
> 
> <img alt="Screen Shot 2022-01-14 at 9 36 50 AM" width="835" src="https://user-images.githubusercontent.com/29597/149532989-e52237d4-24d8-4eba-a36c-aa2fa02642cf.png">
> 
> <img alt="Screen Shot 2022-01-14 at 9 37 08 AM" width="839" src="https://user-images.githubusercontent.com/29597/149532991-7ce4c5ca-15cd-4b0f-839d-884067870fcd.png">
> 
> Could it be possible that you have some other extension installed that's doing something unexpected here?
> 
> Can you run the following code in your developer console on one of these pages and paste the result here for me?
> 
> ```js
> console.log(
>   JSON.stringify(
>     Array.from(__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.values()).map(
>       (renderer) => ({
>         rendererPackageName: renderer.rendererPackageName,
>         version: renderer.version,
>       })
>     )
>   )
> );
> ```

Here's the output from running on youtube.com

`[{"rendererPackageName":"react-dom","version":"17.0.2"}]`

same output from running on any other non-react webpage.

for webpages actually using react, the output in twitter.com was

`[{"rendererPackageName":"react-dom","version":"17.0.2"},{"rendererPackageName":"react-dom","version":"16.14.0"}]`

I think this has something to do with the redux devtools extension. When I disable it, I get an empty array on running your snippet and the issue also goes away. Just to be sure I installed redux devtools on Firefox and had the same issue.

This probably is due to some new update on redux devtools because I've always had it alongside react devtools and never had this problem.

**Comment by bvaughn** [comment] 2022-01-14 17:24
> Here's the output from running on youtube.com

Gotcha. Thank you for confirming!

This is what I thought. Something is injecting the React runtime into the page, and it's talking to DevTools and causing a false positive.

> I think this has something to do with the redux devtools extension. When I disable it, I get an empty array on running your snippet and the issue also goes away. Just to be sure I installed redux devtools on Firefox and had the same issue.

Thank you for digging in a little further and narrowing it down! 😁 

Sounds like someone should file an issue with the Redux DevTools then. I'm going to close this issue since React DevTools are kind of doing what they're designed to do.

**Closed by bvaughn** 2022-01-14 17:24 UTC
Labels: Type: Bug, Status: Unconfirmed, Component: Developer Tools

**Comment by Fernando-Espinosa** [comment] 2022-01-15 22:48
I've opened this ticket for the Redux Dev Tools extension: [I've opened this ticket for the Redux Dev Tools extension](https://github.com/zalmoxisus/redux-devtools-extension/issues/829)

**Comment by gaearon** [comment] 2022-01-18 15:38
We're getting a bunch of issues about this. Did anything change on our side or on Redux DevTools side? Redux DevTools seems unmaintained so I don't know why we'd start getting a bunch of issues now.

**Comment by bvaughn** [comment] 2022-01-18 15:41
Are there a bunch? I've seen two GitHub issues recently.

> Redux DevTools seems unmaintained

Maybe you're looking at the wrong repo? Doesn't look very unmaintained to me:
https://github.com/reduxjs/redux-devtools

The extension was [last updated on January 11th](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) which likely correlates with the bug reports.

**Comment by gaearon** [comment] 2022-01-18 19:45
>Maybe you were looking at this one?

Ah yes. That's where https://github.com/zalmoxisus/redux-devtools-extension/issues/829 got filed. Got it.

**Comment by gaearon** [comment] 2022-01-18 19:46
And here's a fix. https://github.com/reduxjs/redux-devtools/pull/1031
