### ISSUE TITLE
Error: "Could not find node with id "16070" in commit tree"

### ISSUE THREAD

**Issue by psamim** [facebook/react#16789] opened 2019-09-16 09:03 UTC
Describe what you were doing when the bug occurred:
1. Opened profiler
2. Recorded
3. Switched to waterfall

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.6-a39d9c3

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11442
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11388)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11921)
    at xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:277807)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55891)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:98281)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84256)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81286)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25364

Component stack: in xi
    in div
    in div
    in div
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by bvaughn** [comment] 2019-09-16 15:47
@psamim Does this repro for you? If so, any chance you could let me look at the code?

I'm going to close this issue because it's a duplicate of #16446 but any extra info you could provide would be helpful!

**Closed** 2019-09-16 15:47 UTC
Labels: Component: Developer Tools, Resolution: Duplicate, Type: Bug
