### ISSUE TITLE
improving doc

### ISSUE THREAD

**Issue by ghost** [facebook/react#9317] opened 2017-04-02 12:54 UTC
Here
https://facebook.github.io/react/docs/react-component.html#constructor
it says

> Beware of this pattern, as it effectively "forks" the props and can lead to bugs.

Nice but it would be **better** if docs explains what bugs it can lead to.

**Comment by gaearon** [comment] 2017-04-02 12:56
Thanks, would be great if somebody could contribute! The problem is that since you set state based on initial props, you won't get any updates to props. So your props and state will be out of sync.

**Comment by giorgim** [comment] 2017-04-02 13:09
@gaearon Yup, nice, I thought so, but since it is docs, just saying "it will lead to bugs", is not enough IMO. PS. Hope someone is working on my previous two issues :)

**Comment by gaearon** [comment] 2017-04-02 13:22
We're [in the middle of a rewrite](https://github.com/facebook/react/issues/7925) right now so the issues are somewhat neglected. We'll get to them once we ship it.

**Comment by orlando-paredes-hamsho** [comment] 2017-04-03 05:15
I'd be very interested in contributing! Anything specific you want in there? Or just mention that props and state will be left out of sync by this behavior?

**Comment by hanumanthan** [comment] 2017-04-11 17:15
@gaearon Made a doc updated for the above mentioned issue in this PR(https://github.com/facebook/react/pull/9404).

This is my first contribution to this repo. So if I have missed anything please let me know(submitted CLA)

**Comment by gaearon** [comment] 2017-04-12 23:57
Thanks, this looks good! Ideally we'd also have something like this in the "Troubleshooting" doc (which I suggested in https://github.com/facebook/react/issues/8060#issuecomment-283512242) but nobody wrote it yet. Maybe you'd be interested to start working on it?

**Comment by hanumanthan** [comment] 2017-04-13 03:41
Yes would like to contribute to it. Will first understand the discussions there and get back to you in case of doubts @gaearon

**Comment by hanumanthan** [comment] 2017-04-14 03:43
@gaearon Can we close this issue?

**Comment by gaearon** [comment] 2017-10-04 19:13
Yes, thanks.

**Closed by gaearon** 2017-10-04 19:13 UTC
Labels: Component: Documentation & Website
