### ISSUE TITLE
TypeError: checker is not a function at validate

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#4173] opened 2015-06-19 01:42 UTC
somehow a weird warning is printed to the console when i have this property

```coffeescript
  propTypes:
    links:       React.PropTypes.oneOfType(
      React.PropTypes.object
      React.PropTypes.arrayOf(React.PropTypes.object)
    )
```

the `checkPropTypes()` produces

```
error = TypeError: checker is not a function at validate
```

at

```js
error = propTypes[propName](props, propName, componentName, location);
```

and this will print this warning in the console

```js
Warning: Failed propType: checker is not a function Check the render method of `xxx`.
```

looks like a bug to me ... using React v0.13.3 here

**Comment by zpao** [comment] 2015-06-19 18:12
Can you paste *exactly* what code you have or make a jsfiddle/jsbin? There are a number of red flags in your code sample (`oneOfType` takes an array, you're missing commas)

**Comment by binarykitchen** [comment] 2015-06-20 01:35
It is valid CoffeeScript syntax

**Comment by samwgoldman** [comment] 2015-06-20 01:42
It's valid coffeescript syntax, but it isn't the correct way to invoke `oneOfType`, as @zpao noted. `oneOfType` takes an array as it's only argument.

```
foo(
  bar
  baz
)
```

desugars to `foo(bar, baz)`, but you want `foo([bar, baz])`, so you need to write something like

```
foo [
  bar
  baz
]
```

instead.

**Comment by binarykitchen** [comment] 2015-06-21 22:28
oh right, my bad ... forgot the array syntax.

hmmm, any chance you could add a type check here and throw an error when `oneOfType` doesn't have an array?

**Comment by rohanBagchi** [comment] 2016-06-21 10:06
I am facing a similar issue. 
```
Component.propTypes = {
    filter: PropTypes.shape({
        options: {
            openings: PropTypes.arrayOf(
                PropTypes.shape({
                    id: PropTypes.number,
                    name: PropTypes.string
                })
            )
        },
        selected: {
            opening_ids: PropTypes.arrayOf(PropTypes.number),
            candidate_added_date_range: PropTypes.string
        }

    }),
    syncOpeningsFilter: PropTypes.func,
    fetchOpeningsFilterOptions: PropTypes.func.isRequired,
    syncCandidateDateRangeFilter: PropTypes.func
};
```

Any clue what I might be missing?

**Comment by gaearon** [comment] 2016-10-27 14:48
Closing as not a common issue, and caused by wrong usage. If it comes up often, feel free to send a PR that adds better warnings.

**Closed by gaearon** 2016-10-27 14:48 UTC

**Comment by aljones15** [comment] 2018-03-30 07:10
just for future refenrce you can also get this error if a PropType is left uncomplete ie.

county: PropTypes

**Comment by alfrejivi** [comment] 2021-02-04 10:03
I had this same issue and is because `Component.propTypes` has the first letter lowercase, it should be `Component.PropTypes`
