### ISSUE TITLE
Error: "can't access property "isCollapsed", child is undefined"

### ISSUE THREAD

**Issue by jasman7799** [facebook/react#20769] opened 2021-02-09 17:20 UTC
Describe what you were doing when the bug occurred:
1. On initializing dev tools for react components

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-f160547f47

Component stack: List@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:22629:30
div
AutoSizer@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:3003:19
div
div
Tree_Tree@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:28429:47
div
div
InspectedElementContextController@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:28920:43
OwnersListContextController@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:27557:37
SettingsModalContextController@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:28205:40
Components_Components@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:33383:52
ErrorBoundary_ErrorBoundary@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:29219:5
PortaledContent@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:29336:27
div
div
ProfilerContextController@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:32933:35
TreeContextController@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:24321:31
SettingsContextController@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:24810:35
ModalDialogContextController@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:29403:38
DevTools_DevTools@moz-extension://6883bcc9-237a-4a4c-aa0b-be251be145ec/build/main.js:36206:27

**Comment by bvaughn** [comment] 2021-02-09 18:03
> 1. On initializing dev tools for react components

@jasman7799 This isn't enough info for one of us to investigate the issue. Can you please provide more context?

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-02-16 18:23
Closing due to lack of info.

**Closed by bvaughn** 2021-02-16 18:23 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Type: Bug
