### ISSUE TITLE
Bug: React instrumentation encountered an error: Error: Could not find ID for Fiber "Portal"

### ISSUE THREAD

**Issue by jackluson** [facebook/react#22741] opened 2021-11-11 08:34 UTC
React version:  17.0.2

## Steps To Reproduce
1. 
> when i execute `Modal.hide()` 

2.
![image](https://user-images.githubusercontent.com/36684351/141264440-be0f55b9-4aa8-4ff4-a9de-1c8c0291f813.png)

Link to code example:
![image](https://user-images.githubusercontent.com/36684351/141264419-bcb20cd5-8f69-44d8-a8b2-2cf5c64882b8.png)

**Comment by bvaughn** [comment] 2021-11-11 20:49
Hi @jackluson,

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment] 2021-11-15 15:51
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-11-15 15:51 UTC
Labels: Type: Bug, Status: Unconfirmed, Resolution: Needs More Information, Component: Developer Tools
