### ISSUE TITLE
Bug: Native multiple only change value on second click on Firefox

### ISSUE THREAD

**Issue by marincenusa** [facebook/react#20810] opened 2021-02-12 11:47 UTC
React version: 17.0.1

## Steps To Reproduce

1. Open codesandbox with Mozilla Firefox
2. Select a user from users list
3. The value is not selected on first time, need to click second time on list to get event.target.value

Link to code example: [https://codesandbox.io/s/stupefied-newton-lz134](https://codesandbox.io/s/stupefied-newton-lz134)

**Comment by eps1lon** [comment] 2021-02-12 12:35
Thanks for the report!

Repro without 3rd party dependencies: https://codesandbox.io/s/lucid-elgamal-4ej2v?file=/src/App.js (source: https://github.com/mui-org/material-ui/issues/24872#issuecomment-778143610)

I was hoping that this was fixed by enabling flushing of discrete events in a microtask. But using a build from https://github.com/facebook/react/pull/20792 still reproduces the issue: https://codesandbox.io/s/heuristic-fermat-r7c0g

I'm closing this as a duplicate of https://github.com/facebook/react/issues/6951. Though this report is still helpful since we gained new information. 

Aside: `<select multiple />` is already problematic since it dispatches `onChange` on `click` not `mousedown`. Maybe this causes this issue.

**Closed by eps1lon** 2021-02-12 12:35 UTC
Labels: Resolution: Duplicate, Status: Unconfirmed
