### ISSUE TITLE
[DevTools Bug] Could not inspect element with id 192

### ISSUE THREAD

**Issue by erwinpra** [facebook/react#21803] opened 2021-07-06 15:56 UTC
### Website or app

website for development

### Repro steps

Uncaught Error: Could not inspect element with id 192

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.5-0ae5290b54

### Error message (automated)

Could not inspect element with id 192

### Error component stack (automated)

```text
at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31392:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30033:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30176:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32661:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28268:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28709:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34512:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30033:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30147:5)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34138:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24945:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25548:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30234:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37241:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not inspect element with id 192 in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment] 2021-07-06 17:04
Hi @erwinpra!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. 


> **Website or app**
> website for development

This isn't a website we can access. Please share either a project (on GitHub) or a publicly accessible URL.

> **Repro steps**
> Uncaught Error: Could not inspect element with id 192

Repro steps should be a list of steps someone (like me) can follow to reproduce the bug. This is the error message, which we also have in the bug summary. Can you please provide repro steps here?

**Comment by alk-mandrianarijaona** [comment] 2021-07-07 15:15
It seems to be a duplicate of https://github.com/facebook/react/issues/21724

**Comment by bvaughn** [comment] 2021-07-07 15:21
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.

**Closed by bvaughn** 2021-07-07 15:21 UTC
Labels: Component: Developer Tools, Resolution: Needs More Information, Status: Unconfirmed, Type: Bug
