### ISSUE TITLE
React Child Component with Array Props Updating Incorrectly

### ISSUE THREAD

**Issue by msgraber** [facebook/react#16964] opened 2019-09-30 17:40 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A child Component with array Props update incorrectly when the array is updated in the parent with setState.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

The child is declared in the parent Component render as follows (Alarms is the child Component, filteredStatus is the array):

<div key={1} className={'1'}>
  <span className='text'><b>{locationName} <i>Status</i></b></span>
  <Alarms filteredStatus={this.state.filteredStatus}/>
</div>
The child displays the array as a table.

public generate = () => {
    return this.props.filteredStatus.map(status =>
    {
      return (
      <TableRow key={status.location}>
        <TableCell align="left">
          {(status.severity === 40) && <ErrorIcon style={{ fill: '#FF3333'}}/>}
          {(status.severity === 30) && <NotificationIcon style={{ fill: 'FFA033'}}/>}
          {(status.severity === 20) && <WarningIcon style={{ fill: 'FFE033'}}/>}
        </TableCell>
        <TableCell align="left">{status.description}</TableCell>
        <TableCell align="left">{status.timestamp}</TableCell>
        <TableCell align="left">{status.location}</TableCell>

        {/* <div className="ListBtn">
          <Tooltip title={"Clear '" + alarm.who + "'"}>
            <Avatar>
              <IconButton aria-label="Delete" onClick={this.openClearAlarmConfirmDialog.bind(this, alarm)} >
                <DeleteIcon />
              </IconButton>
            </Avatar>
          </Tooltip>
        </div> */}
      </TableRow>
      );
    });
  }

  public render() {
    return (
      <div>
        {/* <Paper> */}
          <Table>
            <TableHead>
              <TableCell align="left">Severity</TableCell>
              <TableCell align="left">Description</TableCell>
              <TableCell align="left">Timestamp</TableCell>
              <TableCell align="left">Location</TableCell>
            </TableHead>
            <TableBody>
              {this.generate()}
            </TableBody>
          </Table>
        {/* </Paper> */}
      </div>
    );
  }

filteredStatus is declared in the parent Component state as...

    interface IState {
      dtName: string;
      dtDesc: string;
      dtInfo: IDrivetrainInfo;
      drillDownIndex: number;
      componentName: string;
      navLocations: string[];
      filteredStatus: Status[];
      nullStatus: Status[];
      locationStatus: Status;
    }

Status is a user defined class...

    export class Status {
        public location: string;
        public timestamp: string;
        public severity: number;
        public description: string;
    }
The filteredStatus is updated in the parent from a timer... A new array of Status is created and assigned to the state.filtered status as follows:

this.setState({filteredStatus: this.localStatus});
What happens is that the updated table doesn't correctly show the new array of components. The new array appears to be merged with the old array. I added the size of the array to the child display and at times the size shows 0 while the list shows 15 elements.

I was able to work around this problem by first setting the filteredStatus to a null array, then the new array as follows:

const nullStatus = Array<Status>();
this.setState({filteredStatus: nullStatus});
this.setState({filteredStatus: this.localStatus});
I may be doing something wrong, but this appears to be a problem with the rendering of the array props in the child Component.

**What is the expected behavior?**
The child array should display the elements of the array correctly.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: "^16.8.5",
Chrome browser.

**Comment by Dergash** [comment] 2019-09-30 18:15
Hello @msgraber! Did you use `key` property for a root element of your child component inside your map call?
```jsx
 this.props.filteredStatus.map((status, index) =>
    <TableRow key={index}>
        // content
    </TableRow>
)
```
Should be unique id of your Status elements or index, if you missed it then it definitely could lead to some confusing render behavior with your list elements looked 'merged' between previous and next states.

Also might be the way you recreating this.localStatus, you say it's recreated on every filteredStatus change it should be ok but it is not clear from your code; if keys are alright, please specify how exactly your  this.localStatus is updated from parent timer call to a this.localStatus assignment. Although in that case it should just show previous array items, not merged.

**Comment by msgraber** [comment] 2019-09-30 18:40
The key is set as follows:
      <TableRow key={status.location}>
        <TableCell align="left" style={{maxWidth: 30}}>
          <ErrorIcon style={{ fill: '#FF3333'}}/>
        </TableCell>
        <TableCell align="left" style={{width:550, maxWidth: 550}}>{status.description}</TableCell>
        <TableCell align="left" style={{maxWidth: 100}}>{status.timestamp}</TableCell>
        <TableCell align="left" style={{width: 350, maxWidth: 350}}>{status.location}</TableCell>
      </TableRow>

where status.location is a text string.

I'm recreating localStatus from scratch, starting with ...
    const statusArray = new Array();
then...
    const status: Status = new Status();
    ...
    statusArray.push(status);
    ...
    const filteredStatus = status;
    this.setState({filteredStatus});

**Comment by Dergash** [comment] 2019-09-30 19:07
> The key is set as follows:  

Could you please enclose your code sample inside code markdown? It seems that parts of your code are still missing, because I do not see any key. Try this:

![markdown](https://user-images.githubusercontent.com/13132449/65908178-1a098b00-e3f0-11e9-8b4c-d74e9f04293e.png)

**Comment by msgraber** [comment] 2019-09-30 19:32
I don't know why my code disappeared...

      <TableRow key={status.location}>
        <TableCell align="left" style={{maxWidth: 30}}>
          <ErrorIcon style={{ fill: '#FF3333'}}/>
        </TableCell>
        <TableCell align="left" style={{width:550, maxWidth: 550}}>{status.
description}</TableCell>
        <TableCell align="left" style={{maxWidth: 100}}>{status.timestamp}</
TableCell>
        <TableCell align="left" style={{width: 350, maxWidth: 350}}>{status.
location}</TableCell>
      </TableRow>

**Comment by bvaughn** [comment] 2019-09-30 19:37
This type of report is much easier to look at and help with if a Code Sandbox rero is provided. Any chance you could share one?

**Comment by msgraber** [comment] 2019-09-30 20:18
I reduce the code and include it. There is a dependent API which will not
be present.

**Comment by adibfirman** [comment] 2019-10-01 06:49
Hello @msgraber 
maybe you forgot to wrap your child with One Element use `HTMLElement` or `React.Fragment` cus React can return with just an element, for instance:

```jsx
return (
  <Fragment>
     all these HTML
  </Fragment>
)
```

**Comment by msgraber** [comment] 2019-10-01 12:36
I was able to fix this problem.
The key was changing... It was...
      <TableRow key={status.location}>
Where location was the location of the alarms. This appears to have caused
the problem.
I changed the key to a constant value...
      <TableRow key='alarms'>
And it now works correctly.

Thank you for your help.
Steve

**Comment by carkod** [comment] 2019-10-01 12:52
The problem is that you are replying with email, that's why you lost your code format while replying it. I believe this issue can be closed?

**Comment by msgraber** [comment] 2019-10-01 13:56
Yes, the issue is resolved.

**Comment by bvaughn** [comment] 2019-10-01 15:37
Thanks for the update, @msgraber. Glad you got it sorted.

**Closed by bvaughn** 2019-10-01 15:37 UTC
