### ISSUE TITLE
Error: "Commit tree already contains fiber 1. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by justinbc820** [facebook/react#19274] opened 2020-07-07 18:33 UTC
Describe what you were doing when the bug occurred:
1. Went to the profiler
2. Did reload and record
3. Stopped Recording
4. Went to Flamegraph
5. Started paging through commits.
6. At around the 5th commit, this error was thrown.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.7.0-23309eb38

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:164298)
    at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:163849)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:166664)
    at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342328)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:62450)
    at tl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:71793)
    at zl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:113765)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104502)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104430)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104298)

Component stack: at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342099)
    at div
    at div
    at div
    at Co (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:263571)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:366677
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:276314)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:278724
    at div
    at div
    at Xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:325177)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:207026)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:216342)
    at Va (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:293773)
    at us (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:371869)

**Comment by bvaughn** [comment] 2020-07-07 19:45
Hey @justinbc820. Sorry you saw this error.

It looks like a duplicate of #18859 though so I'm going to close this issue. If you have any additional repro steps that might help us track it down, please add a comment to that issue!

**Closed by bvaughn** 2020-07-07 19:45 UTC

**Comment by bvaughn** [comment] 2021-04-28 20:30
@justinbc820  This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼

**Comment by justinbc820** [comment] 2021-04-29 16:29
@bvaughn, I actually haven't had React DevTools installed for awhile because it kept causing my MacBook Pro fan to spin up like crazy. But, I just reinstalled it and tried to pound on our development site, but was unable to reproduce the bug again. I will keep the DevTools installed for awhile to see if I can get it to happen again.

**Comment by bvaughn** [comment] 2021-04-29 16:54
Thanks!

**Comment by bvaughn** [comment] 2021-04-29 16:55
PS If you could share more info about why it causes your fans to spin that would be something I'd be interested in looking into also
